### ISSUE TITLE
Colorbar with imshow(logNorm) shows unexpected minor ticks

### ISSUE THREAD

**Issue by billtau** [matplotlib/matplotlib#8307] opened 2017-03-16 13:04 UTC
### Bug report

**Bug summary**

When using colorbar with imshow(image, norm=LogNorm()),  the produced colorbar automatically adds minorticks, and cannot be turned off with cbar.ax.minorticks_off().  Also the font of the tick label is not the same as the font set in matplotlibrc. 

**Code for reproduction**

```python
# This is modified from an example in matplotlib gallery.

import matplotlib.pyplot as plt
import numpy as np
from numpy import ma
from matplotlib import colors, ticker, cm
from matplotlib.mlab import bivariate_normal

N = 100
x = np.linspace(-3.0, 3.0, N)
y = np.linspace(-2.0, 2.0, N)

X, Y = np.meshgrid(x, y)

z = (bivariate_normal(X, Y, 0.1, 0.2, 1.0, 1.0)
     + 0.1 * bivariate_normal(X, Y, 1.0, 1.0, 0.0, 0.0))

z = ma.masked_where(z <= 0, z)

fig, ax = plt.subplots()

from matplotlib.colors import LogNorm

cs = ax.imshow(z,norm=LogNorm())

cbar = fig.colorbar(cs)

cbar.ax.minorticks_off()

plt.show()

```

**Actual outcome**

![screen shot 2017-03-16 at 9 02 34 pm](https://cloud.githubusercontent.com/assets/14089622/23997331/e67a8234-0a8b-11e7-94c2-f057a08e8769.png)

**Expected outcome**

I would expect the colorbar to not have minorticks and to use the same font as other tick labels (I set font to be Arial in matplotlibrc). 

**Matplotlib version**

- Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)

2.0.0_1, OSX

- How did you install Matplotlib and Python (pip, anaconda, from source ...)
Macports

**Edit by @afvincent:** removed the unnecessary instructions coming from the _bug report_ template.

**Comment by QuLogic** [comment] 2017-03-17 00:05
It appears you also have some custom rcParam settings; the ticks should not be pointing inward. In any case, I can still reproduce myself.

These minor ticks are not supposed to be shown with so many major decades visible, right @efiring? @NelleV?

The font weirdness is probably #8017.

**Comment by billtau** [comment] 2017-03-17 00:12
Oh, yes, I changed rcParam so that so ticks point inward.  Sorry I didn't mention that. First time to report something here.

**Comment by NelleV** [comment] 2017-03-17 00:41
Indeed, I would not have expected minor ticks to appear.

**Comment by afvincent** [comment] 2017-10-23 23:21
FWIW this issue still present on Matplotlib 2.1.

If that was not obvious, please note that the problem does not come from `ax.minorticks_off` as the subticks are actually *major* ticks in the case of `LogLocator`. I did not find where is located the problem in `LogLocator` for the moment, but in the meantime a possible workaround is:
```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.mlab import bivariate_normal
from matplotlib.ticker import LogLocator
from matplotlib.colors import LogNorm

N = 100
x = np.linspace(-3.0, 3.0, N)
y = np.linspace(-2.0, 2.0, N)
X, Y = np.meshgrid(x, y)

z = (bivariate_normal(X, Y, 0.1, 0.2, 1.0, 1.0)
     + 0.1 * bivariate_normal(X, Y, 1.0, 1.0, 0.0, 0.0))
z = np.ma.masked_where(z <= 0, z)

fig, ax = plt.subplots()
cs = ax.imshow(z, norm=LogNorm())
cbar = fig.colorbar(cs)
cbar.ax.yaxis.set_major_locator(LogLocator())  # <- why is this required to get the next line working?!
cbar.set_ticks(cbar.ax.yaxis.get_major_locator().tick_values(z.min(), z.max()))
fig.show()
```
![workaround_8307](https://user-images.githubusercontent.com/17270724/31917758-1c8c4184-b80e-11e7-94fd-39931b5b7d01.png)

**Comment by afvincent** [comment] 2017-10-24 01:57
Well, the handling of the tick locator seems a bit convoluted with colorbars, at least for my current understanding ^^... Nevertheless, here is a workaround that is  bit simpler than my previous one (it was not obvious to me that one could simply pass a Locator instance to `cbar.set_ticks`...):
```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.mlab import bivariate_normal
from matplotlib.ticker import LogLocator
from matplotlib.colors import LogNorm

N = 100
x = np.linspace(-3.0, 3.0, N)
y = np.linspace(-2.0, 2.0, N)
X, Y = np.meshgrid(x, y)

z = (bivariate_normal(X, Y, 0.1, 0.2, 1.0, 1.0)
     + 0.1 * bivariate_normal(X, Y, 1.0, 1.0, 0.0, 0.0))
z = np.ma.masked_where(z <= 0, z)

fig, ax = plt.subplots()
cs = ax.imshow(z, norm=LogNorm())
cbar = fig.colorbar(cs)
# One-line workaround 
cbar.set_ticks(LogLocator())  # defaults are more or less what one wants (otherwise adapt the parameters)

fig.show()
```

**Comment by afvincent** [comment] 2017-10-24 03:21
Ok, if I understood it correctly, the “culprit” may be the following [line](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colorbar.py#L594) in `colorbar.ColorbarBase._ticker`:
```python
                    locator = ticker.LogLocator(subs='all')
```
that was introduced by 1fe5820.

Pinging @efiring, who is apparently our `LogLocator` & `Colorbar` expert :). TBH I am not sure that there is much that one can do about this “surprising behavior” (i.e. `cbar.ax.minorticks_off` having no effect because `colorbar.ColorbarBase._ticker` is called anyway in `colorbar.ColorbarBase.update_ticks`). Except maybe adding some proper example, something like:
```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import LogLocator
from matplotlib.colors import LogNorm

# Dummy data
N = 101
x = np.linspace(-3.0, 3.0, N)[np.newaxis, :]
y = np.linspace(-1.0, 1.0, N)[:, np.newaxis]
z = (x.max() - np.abs(x))*(y.max() - np.abs(y))**2 + 1e-3

fig, (ax0, ax1) = plt.subplots(ncols=2, figsize=(9.6, 4.8))

for ax, title, ticks in [
        (ax0, "Default colorbar\nwith “minor” log ticks", None),
        (ax1, "Colorbar with\nonly base log ticks", LogLocator())
        ]:
    cs = ax.imshow(z, norm=LogNorm())
    ax.set_title(title)
    cbar = fig.colorbar(cs, ax=ax, ticks=ticks)

fig.show()
``` 
![tentative_example](https://user-images.githubusercontent.com/17270724/31923449-61c55558-b82f-11e7-85b2-b4381f11506d.png)

**Comment by jklymak** [comment] 2017-10-24 05:04
ping @efiring who said he was looking at colorbar ticks...

**Comment by efiring** [comment] 2017-10-24 05:26
Yes.  Short of a major overhaul of the whole tick system, what is needed is to add full support for minor ticks to the colorbar.  In reality this should be needed only for a log scale, but it probably makes more sense to put in all the machinery instead of special-casing log scales.  Then colorbar ticking would be more similar to normal axis ticking.  It will never be identical, though, because a colorbar simply is not a normal Axis in a normal Axes.

**Comment by dstansby** [comment] 2019-05-04 21:12
This is working fine in `3.1`; my guess is it was fixed by recent changes to how colorbar axes are handled.

**Closed by dstansby** 2019-05-04 21:12 UTC
