### ISSUE TITLE
[Bug]: tight layout breaks with toolbar.push_current()

### ISSUE THREAD

**Issue by rowlesmr** [matplotlib/matplotlib#21970] opened 2021-12-16 01:39 UTC
### Bug summary

Updating the plot stack via toolbar.update() and toolbar.push_current() breaks the behaviour of fig.set_tight_layout().
"reset original view" makes the plot expand outside the viewable area.
"reset" from "configure subplots" corrects it, but pressing "home" again re-breaks it.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.use('TKAgg')

x1 = [1, 2, 3, 4, 5, 6]
y1 = [3, 4, 5, 6, 7, 8]

x2 = [2, 3, 4, 5, 6, 7]
y2 = [8, 7, 6, 5, 4, 3]

# do all the plot setup
fig, ax = plt.subplots(1, 1)
toolbar = fig.canvas.manager.toolbar
fig.set_tight_layout(True)
ax.margins(x=0)

# plot data - this really happens by the user choosing a dataset to plot
line, = ax.plot(x1, y1, marker="o", label="data")
ax.set_xlabel("X ordinate")

# zoom in - this really happens by user interaction with the zoom tool
ax.set_xlim(2.5, 5.5)
ax.set_ylim(3, 6)

# save the current zoom for restoring later
old_x_lim = ax.get_xlim()
old_y_lim = ax.get_ylim()

# replace data - this really happens by the user choosing new data to plot
line.set_data(x2, y2)

# let matplotlib calculate the optimal axes settings for the new data
ax.relim()
ax.autoscale()

# restore the zoom so the new data is plotted in the same view as the old
toolbar.update()  # Clear the axes stack
toolbar.push_current()  # save the current status as home
ax.set_xlim(old_x_lim)
ax.set_ylim(old_y_lim)

# show the plot - this really happens by the program calling things
plt.show()

#Now when I click the "home" button, the axes expand to put the axis titles and ticks off-screen, and
# if I keep clicking "home", the move around. Clicking "reset" in the "configure subplots" menu puts everything right.
```

### Actual outcome

After running the above code and pressing the "home" / "Reset original view" button once:

![mpl_bug1](https://user-images.githubusercontent.com/14921460/146290775-5455f832-9f88-437a-ab1f-036e37898f44.png)

Furthermore, if there is an x-axis title, and the home button is clicked multiple times, the plot becomes smaller and smaller in the vertical direction, like:

![mpl_bug2](https://user-images.githubusercontent.com/14921460/146290794-2207e20c-c134-47d3-8dce-5e9944699df2.png)

and eventually I get a UserWarning:

```
C:\Users\_______\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py:814: UserWarning: Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all axes decorations.
  func(*args)
```

and tight_layout is removed. After this, all functionality appears to be normal.

![mpl_bug3](https://user-images.githubusercontent.com/14921460/146290811-7f7d8cb1-1d87-499d-97e3-95e1d826d15e.png)

### Expected outcome

The expected outcome, after pressing the home button, looks like

![mpl_expected1](https://user-images.githubusercontent.com/14921460/146290851-6109cb67-d29e-449b-af8b-234aa70bf680.png)

And continuing to press the home button should not further alter the view.

### Additional information

This only happens when tight layout is set to True.
The vertical shrinking only happens when there is an X axis label.
There is no horizontal shrinking when a y axis label is set.
The same behaviour was observed in 3.4.3
Behaviour persists in TKAgg, QtAgg, Qt5Agg, wxAgg

### Operating system

Windows 10

### Matplotlib Version

3.5.1

### Matplotlib Backend

TKAgg

### Python version

3.9.4

### Installation

pip

**Comment by jklymak** [comment] 2021-12-16 05:54
Yes this is a duplicate of https://github.com/matplotlib/matplotlib/issues/11059. I'll close here to keep the conversation in one spot.  Thanks!

**Closed** 2021-12-16 05:56 UTC
Labels: topic: geometry manager, status: duplicate
