### ISSUE TITLE
Matplotlib animation.Artistanimation from Axes3D is very slow to convert to html5 video

### ISSUE THREAD

**Issue by aluhamaa** [matplotlib/matplotlib#10207] opened 2018-01-09 22:25 UTC
### Bug report

 A simple animation of both 2D and 3D plot works fine, but when I convert to html5 video, the 3D version is very slow even with few images and does not even finish for larger image sizes

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from mpl_toolkits.mplot3d import Axes3D
import time

## Prepare initial data
a = 20
d = 20
tm0 = 10
t_m = tm0 * np.pi/180
def phi(t):
    return np.pi/4 + (6 + 0.1*t) * t
def r(t):
    return d/2 * (1 - phi(t)/phi(t_m))
def Fp(x,y,t):
    return -1/np.sqrt((x + r(t)*np.cos(phi(t)))**2 + (y + r(t)*np.sin(phi(t)))**2)                                                            \
           -1/np.sqrt((x - r(t)*np.cos(phi(t)))**2 + (y - r(t)*np.sin(phi(t)))**2)     
X = np.arange(-1*a, a)
Y = np.arange(-1*a, a)
x,y=np.meshgrid(X,Y)

## generate image data
imageList = []
for t in range(tm0):
    imageList.append(Fp(x,y,t*np.pi/180))

## Create animation and video from 2D images
fig = plt.figure(figsize=(10,10))
ims = []
for i in range(len(imageList)):
    im = plt.pcolormesh(imageList[i], animated = True)
    ims.append([im])
    
ani1 = animation.ArtistAnimation(fig, ims, blit=True, repeat_delay=2000)
plt.colorbar()
t1=time.time()
ani1.to_html5_video()
t2=time.time()
print("2D image to video took: ", t2 - t1)

## Create animation and video from 3D images
t1 = time.time()
fig = plt.figure()
ax = Axes3D(fig)
ims = []
for i in range(len(imageList)):
    im = ax.plot_surface(x,y,imageList[i], antialiased=False, animated=True)
    ims.append([im])
    
ani = animation.ArtistAnimation(fig, ims, blit=True, repeat_delay=2000)
## plt.show()
t2 = time.time()
print("3D animation creation took: ", t2 - t1)
ani.to_html5_video()
t3=time.time()
print("3D animation to video took:", t3 - t2)
```

**Matplotlib version**

  * Operating system: Max OS X vs 10.12.6 
  * Matplotlib version: 2.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): MaxOSX, Agg
  * Python version: Python 3.6.3 :: Anaconda, Inc.
  * Other libraries: ffmpeg  3.4.1

Libraries installed from conda-forge

**Comment by WeatherGod** [comment] 2018-01-10 16:22
ArtistAnimations can be very memory intensive. Could you see if that might
be the issue here? If so, then you probably are going to want to utilize a
FuncAnimation, that can clear the previous surface object and create a new
one on-the-fly, thereby keeping memory usage low and avoiding
swap-thrashing.

**Comment by aluhamaa** [comment] 2018-01-11 08:55
No memory is not an issue, and animation works just fine in interactive mode, it is the conversion to video that is slow. The time to compose does not grow linearly, but more like exponential, i.e. double the frames and it takes 4 times more cpu time to process.

nr_of_frames  time_to_html5_video
10                     15s
20                    60s
30                   140s
40                   264s
I have 16G of ram on MBP and python process takes 1.1% of memory, no significant swapping or other processes like ffmpeg taking memory.

**Comment by WeatherGod** [comment] 2018-01-11 16:49
Ah, so this is strictly an html5 video encoding issue? Does the problem
occur saving to any other video format using the various external encoders?

**Comment by aluhamaa** [comment] 2018-01-12 07:56
Yes, I could have been more explicit that it is the video encoding. 
I tried also ._to_jshtml() in the notebook and it is slightly faster and nice to use when ready, but still too slow for reasonable interactive use. 420s for 80 frames.
Any suggestions what external encoder should I try? Documentation is not very informative and I cannot afford spending too much time on inventing the wheel.

**Comment by WeatherGod** [comment] 2018-01-12 17:20
Chapter 3 of my book "Interactive Applications using Matplotlib" is
probably the only published documentation out there on animations.

**Comment by aluhamaa** [comment] 2018-01-12 17:59
The context why I started to investigate this is that a particular university is considering using Jupyter in teaching Physics (possibly some related fields). Matplotlib plays a quite central part here, including animations. But, to convince some more conservative persons in the feasibility, nice examples are needed. Potentially some audience for the book.

**Comment by ImportanceOfBeingErnest** [comment] 2018-01-16 22:00
To have a better overview and also some actual data to discuss here, I created a test case where I saved the same data as an animation, varying the number of frames of that animation and recording the time it takes for the animation to be saved (or its output being created). The parameters in use here are 2D vs. 3D animation, Arstist- vs FuncAnimation and different output formats.  For each animation a grid of 20x20 pixels is used. The result is shown below. 

There is a summary of the interesting observations below. The main point I guess is that while for a 2D plot, there is no difference between an `ArtistAnimation` and a `FuncAnimation` to be seen, in 3D there is a huge difference. 

![image](https://user-images.githubusercontent.com/23121882/35011972-5b6cfd02-fb08-11e7-9624-c34f1a4ae0f4.png)

1. **Difference between 2D and 3D**. We observe that creating a 3D animation takes in general longer than a 2D animation. I guess this is to be expected, simply because drawing a 2D figure is faster than drawing a 3D figure (no need for the projections to 2D, less complex shapes etc.). 
2. **Nonlinear save time for `ArtistAnimation` in 3D**. If a figure with a 3D plot takes a factor x longer to draw than one in 2D, one could be tempted to assume that creating an animation in 3D takes roughly that factor longer. Since we observe a linear relation between the time and the number of frames, one would expect to see a linear relation in 3D as well, just with a slope of a factor x larger. This seems to be the case for the `FuncAnimation`, but the `ArtistAnimation` shows a strictly nonlinear behaviour between time and frame number. At least it seems that the nonlinear effect only takes effect for much larger frame numbers for the 2D case (see last plot, where a grid of 100x100 pixels is used). 
3. The **`ArtistAnimation` in 3D takes a lot longer than the `FuncAnimation` in 3D**.  This is especially interesting, because there is no such difference between `ArtistAnimation` and `FuncAnimation` in 2D. It is not clear, why one of them should behave drastically different, just because the figure being drawn is a 3D plot.  
4. **The output format is rather irrelevant**. Creating the animation via `html5_video`, `ffmpeg` (mp4) or `jshtml` does not make much of a difference. The difference between any of the other parameters (2D vs 3D and Artist- vs. FuncAnimation) are much larger.




![image](https://user-images.githubusercontent.com/23121882/35011959-4d6bc184-fb08-11e7-9ccb-1ad49106f1b0.png)

![image](https://user-images.githubusercontent.com/23121882/35012752-2a69c91c-fb0b-11e7-9d94-af575fd0cb09.png)

![image](https://user-images.githubusercontent.com/23121882/35014161-ff7c82bc-fb0f-11e7-9f48-b0bf2f7c4394.png)


Complete code for reproduction. Note that I used `blit=False` here, because turning blitting on resulted in strange errors; since blitting should not matter for saving anyways, I did not care about that at this point.

```
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from mpl_toolkits.mplot3d import Axes3D
import time
import pandas as pd


def get_data(N, m):
    l = np.linspace(-3,3,m)
    X,Y = np.meshgrid(l,l)
    F = lambda a: a*np.exp(-X**2-Y**2)
    Z = np.empty((N,m,m))
    A = np.cos(np.linspace(0,2*np.pi,N, endpoint=False))
    for i,a in enumerate(A):
        Z[i,:,:] = F(a)
    return X,Y,Z

def create_Animation(N,m, dim="2D", typ="Artist",figsize=(6,4)):
    X,Y,Z = get_data(N,m)
    vmin, vmax = Z.min(), Z.max()
    
    fig = plt.figure(figsize=figsize)
    if dim == "2D":
        ax = fig.add_subplot(111)
        func = ax.pcolormesh
        kw = dict(vmin=vmin,vmax=vmax,cmap=plt.cm.YlGnBu_r)
    else:
        ax = fig.add_subplot(111,projection="3d")
        ax.set_zlim(-1,1)
        func = ax.plot_surface
        kw = dict(antialiased=False, cmap=plt.cm.YlGnBu_r)
    
    if typ == "Artist":
        ims=[]
        for i in range(len(Z)):
            im = func(X,Y,Z[i,:,:], **kw)
            ims.append([im])
            
        ani = animation.ArtistAnimation(fig, ims, blit=False,repeat=False)
    else:
        ims = [None]
        if dim == "3D" : kw.update(color="w")
        def update(i):
            if ims[0]: ims[0].remove()
            ims[0] = func(X,Y,Z[i,:,:], **kw)
            if dim == "3D":
                ims[0]._facecolors2d=ims[0]._facecolors3d
                ims[0]._edgecolors2d=ims[0]._edgecolors3d
            return ims[0],
        ani = animation.FuncAnimation(fig, update, frames=len(Z), blit=False,repeat=False)    
    return ani

def save_ani_to_js(ani, show=False):
    t1=time.time()
    vid = ani.to_jshtml()
    t2=time.time()
    #print("saving to html5: ", t2 - t1)
    if show: plt.show()
    plt.close("all")
    return t2-t1

def save_ani_to_html5(ani, show=False):
    t1=time.time()
    vid = ani.to_html5_video()
    t2=time.time()
    #print("saving to html5: ", t2 - t1)
    if show: plt.show()
    plt.close("all")
    return t2-t1

def save_ani_to_mp4(ani, show=False):
    t1=time.time()
    Writer = animation.writers['ffmpeg']
    writer = Writer(fps=15, metadata=dict(artist='Me'))
    ani.save("rtest.mp4", writer=writer )
    t2=time.time()
    #print("saving to mp4: ", t2 - t1)
    if show: plt.show()
    plt.close("all")
    return t2-t1


dims=["2D","3D"]
typs = ["Artist", "Func"]
outputs = ["html5", "mp4", "js"] #
    
def run_test(name):
    df = pd.DataFrame(columns=["N", "m", "dim", "typ", "output", "time"])
    
    Ns = range(5,60,5)
    m = 20
    for output in outputs:
        for dim in dims:
            for typ in typs:
                for N in Ns:
                    ani = create_Animation(N,m, dim=dim, typ=typ)
                    if output == "mp4":
                        t = save_ani_to_mp4(ani)
                    elif output =="html5":
                        t = save_ani_to_html5(ani)
                    elif output =="js":
                        t = save_ani_to_js(ani)
                    dic = {"N":N, "m":m, "dim":dim, "typ":typ, "output":output, "time":t}
                    print " ", dic
                    df = df.append(dic, ignore_index=True)
    
    df.to_pickle(name)

def filterdf(ax, df, dim, typ, output, color=None, ls="-"):
    lab = "{}, {}, {}".format(dim,typ,output)
    df[(df["dim"]==dim) & (df["typ"]==typ) & (df["output"]==output)] \
                .plot(x = "N", y="time", color=color, label=lab, ls=ls, ax =ax)

def plot_result(*args):
    df = pd.read_pickle(args[0])
    
    fig, ax = plt.subplots()
    colors = ["C0","C1","C2","C3"]
    lss = ["-","-.",":"]
    for k,output in enumerate(outputs):
        for i,dim in enumerate(dims):
            for j,typ in enumerate(typs):
                print (i*len(typs)+j)%len(colors)
                filterdf(ax,df, dim, typ, output, 
                         color=colors[(i*len(typs)+j)%len(colors)], ls=lss[k])
    ax.set_xlabel("number of animation steps")
    ax.set_ylabel("time to save animation [s]")
    ax.set_title("Time it takes to create an animation")
    plt.show()
    
# Show single animation
#ani = create_Animation(20,20, dim="3D", typ="Func")
#t = save_ani_to_html5(ani, show=True)
    
# run everything
run_test("all2_60_20.pickle")
plot_result("all2_60_20.pickle")
```

**Comment by dopplershift** [comment] 2018-01-17 21:47
Thanks for the detailed detective work. It sounds like we have n^2 behavior somewhere in `ArtistAnimation`, but I have no idea why, and no idea why it wouldn't be a problem on 2D. This might call for some strategically placed `print`s to see what's actually called. (I guess one could also try to use a profiler...)

**Comment by anntzer** [comment] 2018-01-18 02:21
Some quick profiling shows that the issue should be fixed by
```
diff --git a/lib/mpl_toolkits/mplot3d/axes3d.py b/lib/mpl_toolkits/mplot3d/axes3d.py
index 156a55c9f..14dea1582 100644
--- a/lib/mpl_toolkits/mplot3d/axes3d.py
+++ b/lib/mpl_toolkits/mplot3d/axes3d.py
@@ -276,7 +276,7 @@ class Axes3D(Axes):
 
         # Calculate projection of collections and zorder them
         for i, col in enumerate(
-                sorted(self.collections,
+                sorted([col for col in self.collections if col.get_visible()],
                        key=lambda col: col.do_3d_projection(renderer),
                        reverse=True)):
             col.zorder = i
```
(gets rid of the quadratic behavior, although I haven't actually checked that the movies are correct...)

Basically the problem is that ArtistAnimation is I think designed to use different artists on each frame, but right now we're z-sorting *all* artists (even the invisible ones that are only visible on other frames) before  drawing them, and do so on each frame (hence the quadratic behavior).

In fact even the 2D code has the same quadratic behavior here, except that it doesn't do z-sorting: it directly grabs the zorder attribute of the artist, and attribute access is fast enough that you don't notice the time cost.  On the other hand, 3D z-projection is very expensive.

(Note that a proper fix should do this not only for collections, but also for all other relevant artist classes)

**Comment by WeatherGod** [comment] 2018-01-18 02:39
ooooh, good catch! Now, another question is why is this happening only on
encoding? The OP noted that artist animation works fine for showing, right?

**Comment by dopplershift** [comment] 2018-01-18 22:27
@anntzer Which profiler did you use? Just curious how I may make it easier for myself to do some "quick profiling". 😁 

@WeatherGod Maybe it's hidden better by the natural delay between frames? Testing showing only involved a few frames (fewer artists)? I'm completely grasping at straws here.

**Comment by dopplershift** [comment] 2018-01-18 22:28
@anntzer Are you planning on putting in a PR with that fix? Would you prefer someone else?

**Comment by anntzer** [comment] 2018-01-18 22:34
pprofile (with statistical mode, NOT instrumenting mode (which always has terrible overhead)) + kcachegrind for visualization (many python profilers seems to invent their own visualization code which is a bit silly when you have perfectly good profile visualizers already available; pprofile is nice because it can output in a format kcachegrind can understand.

I don't think the fix I wrote is really good because again you don't want to only handle collections but also other artists (in fact, looking at the implementation now, I'm a bit confused why collections and patches are getting zordered separately, and lines appear not be be zordered at all? confused).  Also perhaps it may make more sense for ArtistAnimation to be in charge of manipulating the list of artists seen by the Axes (rather than just setting the visibility flag) so that the problem doesn't even reach there.

**Comment by WeatherGod** [comment] 2018-01-18 22:40
Lines aren't zordered by axes3d because -- compared to surfaces -- you
can't really tell which line is supposed to be above others, so we don't
really bother with zordering beyond the normal zorder values. collections
were the original thing that was zordered in axes3d, and I think we added
support for patches separately(maybe?). It is what it is. mplot3d is not
meant to be a full 3d compositor, so we don't bother with that goal. Just
"good enough".

**Comment by dopplershift** [comment] 2018-01-18 23:22
I don't think we want `ArtistAnimation` to be in the business of manipulating the internals of artists on a figure. IMO, that would leave calling `Artist.remove()` and `ax.add_artist()`; these aren't exactly free, and the latter isn't even guaranteed to be correct.

In fact, now that I think of it, given that we have artists distributed between `collections`, `lines`, `patches`, `texts`, and `artists`...no, I don't want `ArtistAnimation` to manage that. Not. one. bit. 😱 

Honestly, it seems perfectly sensible to just filter on visible when drawing--I see **zero** downside.

**Comment by anntzer** [comment] 2018-01-19 02:55
Well, someone just needs to write that PR :)

**Comment by vlsd** [comment] 2018-07-11 19:52
I've noticed this behavior in 2D animations as well, where the `ArtistAnimation` would run quadratically, and almost identical code written with `FuncAnimation` would run more or less linearly. This supports @anntzer's findings from a few posts ago. Since it seems a proper fix can't happen without serious re-writing of `ArtistAnimation`, maybe a note in the documentation about this behavior would be a good move. It would definitely help steer people who want to make long animation away from `ArtistAnimation` and towards `FuncAnimation`

**Comment by jaraujo98** [comment] 2020-04-20 09:44
Has this issue been solved? I am having a similar problem. The following MWE replicates it

```
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from mpl_toolkits.mplot3d import axes3d, Axes3D

import numpy as np

fig = plt.figure()
ax = Axes3D(fig)
frames = []
for i in range(200):
    bars = np.random.rand(50,6)
    im = ax.bar3d(bars[:,0],bars[:,1],bars[:,2],bars[:,3],bars[:,4],bars[:,5],
                  alpha=0.5,animated=True,color='r')
    frames.append([im])
    
ani = animation.ArtistAnimation(fig, frames, interval=50,
                                blit=True, repeat_delay=1000)
ani.save("test.mp4")
```

Note: The call to np.random is just to simulate the creation of variable `bars`. The code which actually computes it is spread over several files...

Running the program in Spyder, the animation appears almost instantly, and plays without problems. However, saving the animation can take almost 30 minutes, in some cases only to yield a 120kB mp4 video. If I `Ctrl-C`the program while it is saving, I get tracebacks similar to the one below. Clearly, the video is being stored, although in a very slow way (slow when compared to the visualization which appears almost instantly in Spyder).

```
Traceback (most recent call last):
  File "[...]/python3.6/site-packages/matplotlib/animation.py", line 230, in saving
    yield self
  File "[...]/python3.6/site-packages/matplotlib/animation.py", line 1156, in save
    writer.grab_frame(**savefig_kwargs)
  File "[...]/python3.6/site-packages/matplotlib/animation.py", line 384, in grab_frame
    dpi=self.dpi, **savefig_kwargs)
  File "[...]/python3.6/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "[...]/python3.6/site-packages/matplotlib/backend_bases.py", line 2082, in print_figure
    **kwargs)
  File "[...]/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 442, in print_raw
    FigureCanvasAgg.draw(self)
  File "[...]/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "[...]/python3.6/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "[...]/python3.6/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "[...]/python3.6/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "[...]/python3.6/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "[...]/python3.6/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 292, in draw
    reverse=True)):
  File "[...]/python3.6/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 291, in <lambda>
    key=lambda col: col.do_3d_projection(renderer),
  File "[...]/python3.6/site-packages/mpl_toolkits/mplot3d/art3d.py", line 710, in do_3d_projection
    key=lambda x: x[0], reverse=True)
  File "[...]/python3.6/site-packages/mpl_toolkits/mplot3d/art3d.py", line 708, in <genexpr>
    for idx, ((xs, ys, zs), fc, ec)
  File "<__array_function__ internals>", line 6, in column_stack
  File "[...]/python3.6/site-packages/numpy/lib/shape_base.py", line 639, in column_stack
    arr = array(arr, copy=False, subok=True, ndmin=2).T
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_spaql.py", line 216, in <module>
    agent.export_video(name=video_name)
  File "/Users/joaopedroaraujo/Dropbox/IST/5o ano 2o semestre/Dissertacao/SinglePartitionAQL/agents.py", line 279, in export_video
    ani.save(name)
  File "[...]/python3.6/site-packages/matplotlib/animation.py", line 1156, in save
    writer.grab_frame(**savefig_kwargs)
  File "[...]/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "[...]/python3.6/site-packages/matplotlib/animation.py", line 232, in saving
    self.finish()
  File "[...]/python3.6/site-packages/matplotlib/animation.py", line 367, in finish
    self.cleanup()
  File "[...]/python3.6/site-packages/matplotlib/animation.py", line 411, in cleanup
    self._proc.returncode, self._proc.args, out, err)
subprocess.CalledProcessError: Command '['ffmpeg', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '640x480', '-pix_fmt', 'rgba', '-r', '20.0', '-loglevel', 'error', '-i', 'pipe:', '-vcodec', 'h264', '-pix_fmt', 'yuv420p', '-y', 'test.mp4']' returned non-zero exit status 255.
```

**Closed** 2021-11-09 07:42 UTC
Labels: topic: animation, status: has patch
