### ISSUE TITLE
3.4.2: pytest fails

### ISSUE THREAD

**Issue by kloczek** [matplotlib/matplotlib#20312] opened 2021-05-26 18:06 UTC
I'm trying to build rpm package with matplotlib module.
setuptools build and install are ok but pytest is failing for me.
May I ask for poin on what I'm doing wrong?
```console
+ PATH=/home/tkloczko/rpmbuild/BUILDROOT/python-matplotlib-3.4.2-2.fc35.x86_64/usr/bin:/usr/bin:/usr/sbin:/usr/local/sbin
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-matplotlib-3.4.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-matplotlib-3.4.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/python3 -Bm pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.9, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/matplotlib-3.4.2, configfile: pytest.ini, testpaths: lib
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, cov-2.11.1, httpbin-1.0.0, xdist-2.2.1, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, pyfakefs-4.4.0, freezegun-0.4.2, cases-3.4.6, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, asyncio-0.15.1, toolbox-0.5, xprocess-0.17.1, flaky-3.7.0, requests-mock-1.9.2, aiohttp-0.3.0, checkdocs-2.7.0, mock-3.6.1, hypothesis-6.13.5, rerunfailures-9.1.1
collected 0 items / 1 error

================================================================================== ERRORS ==================================================================================
______________________________________________________________________ ERROR collecting test session _______________________________________________________________________
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:783: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
lib/matplotlib/__init__.py:107: in <module>
    from . import _api, cbook, docstring, rcsetup
lib/matplotlib/cbook/__init__.py:31: in <module>
    from matplotlib import _api, _c_internal_utils
E   ImportError: cannot import name '_c_internal_utils' from partially initialized module 'matplotlib' (most likely due to a circular import) (/home/tkloczko/rpmbuild/BUILD/matplotlib-3.4.2/lib/matplotlib/__init__.py)
========================================================================= short test summary info ==========================================================================
ERROR  - ImportError: cannot import name '_c_internal_utils' from partially initialized module 'matplotlib' (most likely due to a circular import) (/home/tkloczko/rpmbui...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.41s =============================================================================
```

**Comment by tacaswell** [comment] 2021-05-26 20:00
It looks like you did not fully build Matplotlib and are missing the .so for `_c_internal_utils`.  Can you import Matplotlib outside of pytest?

Have you looked at https://src.fedoraproject.org/rpms/python-matplotlib//blob/rawhide/f/python-matplotlib.spec which is the basis for the fedora/RHEL rpms?

**Comment by QuLogic** [comment] 2021-05-27 00:08
If you run `pytest` from the source directory, it will attempt to load Matplotlib from there after it's loaded the tests, which will not have any of the stuff you have built. You need to run `pytest` against the installed Matplotlib; see the above spec file. We install all test files, so this is not a problem.

**Comment by kloczek** [comment] 2021-05-27 06:48
> If you run pytest from the source directory

Above output was generated when pytrest started in root of source tree.

> You need to run pytest against the installed Matplotlib

Please leook closer on top of the output where you mey see line:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-matplotlib-3.4.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-matplotlib-3.4.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
```
Which is causeing that pytest is executed exactly against installed resources.

**Comment by tacaswell** [comment] 2021-05-27 18:20
However the traceback you are importing from the local source tree

```
lib/matplotlib/__init__.py:107: in <module>
    from . import _api, cbook, docstring, rcsetup
lib/matplotlib/cbook/__init__.py:31: in <module>
    from matplotlib import _api, _c_internal_utils
```

We add `lib` to pytests test paths here: https://github.com/matplotlib/matplotlib/blob/734479c302c8d194181f36c8d38ee47067cbc112/pytest.ini#L5 which means that pytest is also adding things to the PYTHONPATH that are likely coming before the additions you set via the ENV.  The core of the issue is that if you want pytest to automatically discover the tests, then the source needs to be in the path.  If the source is in the path, then it will also found the main from source, and then you get the problem you are seeing.  If you look at how it is done in the spec linked above, they use the `test.py` file at the top level which does test discovery in a slightly different way that correctly finds the installed tests and library.

I am going to close this as the issue because this is a local installation issue and there is a working spec file for building and testing Matplotlib against system libraries linked above.

**Closed by tacaswell** 2021-05-27 18:20 UTC

**Comment by kloczek** [comment] 2021-05-27 19:17
Issue is that exactly the same method which I'm trying to use is used by Fedora with few hundhreds packages.
matplotlib is one of handfull packages which which seems does not allow use standard.
Other thing is that this is not abut installation but **testing** methodology (when pytest is used).

`testpaths = lib` looks incorrect because that path will never contain DSO modules (all modules are build under `build/`).

**Comment by QuLogic** [comment] 2021-05-27 22:37
This is how `pytest` and Python work; there's nothing wrong with the configuration here. If you want to test the installed version, use `--pyargs`. If you don't, it'll use the source directory, which have no built shared libraries.

**Comment by tacaswell** [comment] 2021-05-27 23:08
If you do an inplace build or editable install the `.so` will be in the tree (which is the mode many of the developers work in day-to-day and how we run tests on CI).

**Comment by kloczek** [comment] 2021-05-28 07:40
> This is how pytest and Python work; there's nothing wrong with the configuration here. If you want to test the installed version, use --pyargs. If you don't, it'll use the source directory, which have no built shared libraries.

If it would be true it would be not possinble to build and test any package from non-root account.
However it is not true and you have thousands packages which are building DSOs and where pytest is used to test just installed in PYTHONPATH paths files.
Issue is that sometning in matplotlib is wrongly implemented that during use ptytest is not possinbel to find necessary resources.
In case of mathplot pytest is not working against installed in paths specified in PYTHONPATH abd is not working against source tree.
Log with testing against PYTHONPATH you have on top.
Here is teh same log agains just source tree:
```console
[tkloczko@barrel matplotlib-3.4.2]$ ls -l build/lib.linux-x86_64-3.8
total 4
drwxr-xr-x 1 tkloczko tkloczko 2370 May 27 20:45 matplotlib
drwxr-xr-x 1 tkloczko tkloczko  104 May 27 20:44 mpl_toolkits
-rw-r--r-- 1 tkloczko tkloczko   90 May  8 04:18 pylab.py
[tkloczko@barrel matplotlib-3.4.2]$ ls -l build/lib.linux-x86_64-3.8/*/*.so
-rwxr-xr-x 1 tkloczko tkloczko   31544 May 27 20:44 build/lib.linux-x86_64-3.8/matplotlib/_c_internal_utils.cpython-38-x86_64-linux-gnu.so
-rwxr-xr-x 1 tkloczko tkloczko  502728 May 27 20:44 build/lib.linux-x86_64-3.8/matplotlib/_contour.cpython-38-x86_64-linux-gnu.so
-rwxr-xr-x 1 tkloczko tkloczko  631168 May 27 20:44 build/lib.linux-x86_64-3.8/matplotlib/ft2font.cpython-38-x86_64-linux-gnu.so
-rwxr-xr-x 1 tkloczko tkloczko 1853904 May 27 20:45 build/lib.linux-x86_64-3.8/matplotlib/_image.cpython-38-x86_64-linux-gnu.so
-rwxr-xr-x 1 tkloczko tkloczko 1427640 May 27 20:45 build/lib.linux-x86_64-3.8/matplotlib/_path.cpython-38-x86_64-linux-gnu.so
-rwxr-xr-x 1 tkloczko tkloczko   67904 May 27 20:45 build/lib.linux-x86_64-3.8/matplotlib/_qhull.cpython-38-x86_64-linux-gnu.so
-rwxr-xr-x 1 tkloczko tkloczko 1167104 May 27 20:45 build/lib.linux-x86_64-3.8/matplotlib/_tri.cpython-38-x86_64-linux-gnu.so
-rwxr-xr-x 1 tkloczko tkloczko  607608 May 27 20:45 build/lib.linux-x86_64-3.8/matplotlib/_ttconv.cpython-38-x86_64-linux-gnu.so
[tkloczko@barrel matplotlib-3.4.2]$ pytest
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.9, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/matplotlib-3.4.2, configfile: pytest.ini
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, cov-2.11.1, httpbin-1.0.0, xdist-2.2.1, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, pyfakefs-4.4.0, freezegun-0.4.2, cases-3.4.6, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, asyncio-0.15.1, toolbox-0.5, xprocess-0.17.1, flaky-3.7.0, aiohttp-0.3.0, checkdocs-2.7.0, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, hypothesis-6.13.7
collected 0 items / 1 error

================================================================================== ERRORS ==================================================================================
______________________________________________________________________ ERROR collecting test session _______________________________________________________________________
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:783: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
lib/matplotlib/__init__.py:107: in <module>
    from . import _api, cbook, docstring, rcsetup
lib/matplotlib/cbook/__init__.py:31: in <module>
    from matplotlib import _api, _c_internal_utils
E   ImportError: cannot import name '_c_internal_utils' from partially initialized module 'matplotlib' (most likely due to a circular import) (/home/tkloczko/rpmbuild/BUILD/matplotlib-3.4.2/lib/matplotlib/__init__.py)
========================================================================= short test summary info ==========================================================================
ERROR  - ImportError: cannot import name '_c_internal_utils' from partially initialized module 'matplotlib' (most likely due to a circular import) (/home/tkloczko/rpmbui...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.66s =============================================================================
```
Please at least rey to reporoduce above.

**Comment by QuLogic** [comment] 2021-05-29 07:02
I don't need to try to reproduce it; I already know it won't work as I've already explained.

>  However it is not true and you have thousands packages which are building DSOs and where pytest is used to test just installed in PYTHONPATH paths files.

Name one with the same layout then.

>  In case of mathplot pytest is not working against installed in paths specified in PYTHONPATH abd is not working against source tree.

Yes, and I've already explained why; if you don't understand, you should read the [Pytest docs on test discovery](https://docs.pytest.org/en/6.2.x/goodpractices.html#conventions-for-python-test-discovery).

**Comment by kloczek** [comment] 2021-05-29 08:16
Just checked in which my python packages are produced DSOs and is used pytest on my sample about ~450 python module packages:
```console
[tkloczko@barrel SPECS]$ grep gcc python-* -l | xargs grep ^%pytest
python-aiohttp.spec:%pytest
python-bcrypt.spec:%pytest
python-cbor2.spec:%pytest
python-cffi.spec:%pytest -k "not test_unpack_args" c/ testing/
python-dulwich.spec:%pytest
python-editdistance.spec:%pytest
python-editdistance-s.spec:%pytest
python-geventhttpclient.spec:%pytest -k "\
python-immutables.spec:%pytest
python-lmdb.spec:%pytest
python-markupsafe.spec:%pytest
python-msgpack.spec:%pytest
python-multidict.spec:%pytest
python-pandas.spec:%pytest --cov=pandas --strict
python-pydantic.spec:%pytest
python-pynacl.spec:%pytest
python-pyrsistent.spec:%pytest
python-pyscard.spec:%pytest
python-scss.spec:%pytest
python-simplejson.spec:%pytest
python-sqlalchemy.spec:%pytest
python-ujson.spec:%pytest
python-websockets.spec:%pytest tests
python-wheel.spec:%pytest
python-yarl.spec:%pytest tests
python-zstd.spec:%pytest
```
However I must admit that it there thousands such packages (+95% python modules are not producing DSOs).
Here is the list of few first (going alphabetically from the bottom of the list) which are using pytest and are producing DSOs:
- websockets
- ujson
- simplejson

For the starter it should enough.
It is not exactly what you've been asking (similar/the same layout) but definitely it is non-empty set of python modules which are producing DSOs and pytest JustWorks™️ (in the way which I'm trying to use pytest with matplotlib) so IMO it would is worth to at least peak.

**Comment by kloczek** [comment] 2021-05-29 08:23
A little shorter above list without those packages which have disables %check (execution of the test suite after %iinstall)
```console
[tkloczko@barrel SPECS]$ grep gcc python-* -l | xargs grep ^%pytest -l |xargs grep -v "%bcond_with.*check" -l
python-aiohttp.spec
python-bcrypt.spec
python-cbor2.spec
python-cffi.spec
python-dulwich.spec
python-editdistance.spec
python-editdistance-s.spec
python-geventhttpclient.spec
python-immutables.spec
python-lmdb.spec
python-markupsafe.spec
python-msgpack.spec
python-multidict.spec
python-pandas.spec
python-pydantic.spec
python-pynacl.spec
python-pyrsistent.spec
python-pyscard.spec
python-scss.spec
python-simplejson.spec
python-sqlalchemy.spec
python-ujson.spec
python-websockets.spec
python-wheel.spec
python-yarl.spec
python-zstd.spec
```

**Comment by QuLogic** [comment] 2021-06-01 05:01
`python-dulwich.spec` commented out `%check`. `python-lmdb.spec` does not even use `pytest`. `python-pandas.spec` doesn't have `%check` (I wonder where that went.) `python-scss.spec` does not have `%check`. `python-wheel.spec` doesn't even have compiled extensions. Everything else you listed but `python-simplejson.spec` ship their tests outside of the package. The only reason why `simplejson` works is because the compiled extensions are speedups that are optional. If you made them required, you would see that it fails to import in the same way.

I've now wasted more than enough time on basically confirming how Python import semantics work, so unless you can come up with some _concrete_ reason why something is wrong, I'm not going to bother any further.

**Comment by kloczek** [comment] 2021-06-01 10:31
I'v been asking to check **sdist** archives.
I've not been listing fedora spoec fiels but mine so really .. you wasted your time.
Please have look on those modules **source code**.

> so unless you can come up with some concrete reason why something is wrong, I'm not going to bother any further

Again: with current state of the matplotlib source tree is not possible to use pytest (reason is still the same).
