### ISSUE TITLE
[Bug]: Title of middle subplot does not auto-wrap like subplots on edge

### ISSUE THREAD

**Issue by bielsnohr** [matplotlib/matplotlib#28922] opened 2024-10-02 16:07 UTC
### Bug summary

When creating a grid of subplots that all share x and y axes, and then the title of each subplot is set with auto-wrapping requested, the title of the plot in the middle does not wrap properly.

### Code for reproduction

```Python
import matplotlib.pyplot as plt

fig, (ax1, ax2, ax3) = plt.subplots(1, 3, sharey=True, sharex=True)
y_lims = (-12, 12)
x_lims = (-5, 12)
ax1.set_ylim(*y_lims)
ax1.set_xlim(*x_lims)
ax1.set_title("A long long long long title that needs to wrap", wrap=True)
ax2.set_title("Another long long long title that will need to wrap", wrap=True)
ax3.set_title("The last long long long title that will need to wrap", wrap=True)
fig.tight_layout()
fig.show()
```

### Actual outcome

![matplotlib_subplot_title_bug](https://github.com/user-attachments/assets/fadcf191-4298-441f-8b34-5a499d4d2c18)

### Expected outcome

The title of the middle subplot should wrap like the subplots to either side of it.

### Operating system

Ubuntu 22.04.5 LTS

### Matplotlib Version

3.9.2

### Matplotlib Backend

qtagg

### Python version

3.10.14

### Installation

pip

**Comment by timhoffm** [comment] 2024-10-02 16:25
Duplicate of #28847. See there for an explanation and a workaround.

**Closed by timhoffm** 2024-10-02 16:25 UTC

**Comment by bielsnohr** [comment] 2024-10-02 17:10
Thanks for pointing me towards a solution. I will note that I agree with the other user raising that issue: the behaviour here is unintuitive and inconsistent. Why should the edge subplots wrap their titles properly while the central ones do not?
