### ISSUE TITLE
Temporary styling ignores color cycle

### ISSUE THREAD

**Issue by rjurga** [matplotlib/matplotlib#11376] opened 2018-06-05 07:57 UTC
### Bug report

**Bug summary**

With temporary styling, using colors with respect to the color cycle, like `'C0'`, is ignored if `plt.show()` is called outside of the `with` block. It only works properly if `plt.show()` is called inside the block.

**Code for reproduction**

This reproduces the bug:
```python
import matplotlib.pyplot as plt

with plt.style.context('seaborn'):
    plt.axhline(0, color='C0')
    plt.axhline(1, color='C1')
    plt.axhline(2, color='C2')
plt.show()
```

This works fine and is the expected behavior:
```python
import matplotlib.pyplot as plt

with plt.style.context('seaborn'):
    plt.axhline(0, color='C0')
    plt.axhline(1, color='C1')
    plt.axhline(2, color='C2')
    plt.show()
```

**Actual outcome**

![does_not_work](https://user-images.githubusercontent.com/11193181/40962539-1654efc0-68a6-11e8-9d24-f3b4a455ccc3.png)

Please note that other elements of the style are working fine, such as the grid.

**Expected outcome**

![works](https://user-images.githubusercontent.com/11193181/40962605-4774e2fe-68a6-11e8-843e-3fb362a50841.png)

**Matplotlib version**

  * Operating system: Solus Linux
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.5

Using matplotlib packaged by the linux distribution.

**Comment by afvincent** [comment] 2018-06-05 23:44
@rjurga Thank you for the report :)!

I can reproduce this on master (with Fedora 28 and Python 3.6 from conda).

**Comment by tacaswell** [comment] 2018-06-06 04:22
It does look like the color is resloved at draw time, however for other things that hit the rcparams we resolve them at call time to exactly avoid issues like this.

We should probably move the resolution of the 'C#' values up sooner (have it be done in `Line2D.set_color`) and document the API change unless we can dig up documentation of why we did it this way.

**Comment by jklymak** [comment] 2018-06-21 16:51
I dunno - I think if you drop out of context, you can/should expect strange things to do with the context to happen.  i.e. in the code above, I'd plt.show or fig.savefig inside the context.  Is this really a bug?

**Comment by WeatherGod** [comment] 2018-06-21 18:15
The more I think about this, the more I am convinced this is not a bug, but
rather a good teaching point. The point of these color aliases is to be a
named reference to values that aren't easily accessible to the user. Within
the context, the color cycle can be known and fetched directly for the
plotting call. But the color-cycle outside of the context is not known, and
these color aliases are really the only way to reference those unknown
colors.

**Comment by jklymak** [comment] 2019-02-09 22:44
I'm closing this as won't fix....

**Closed by jklymak** 2019-02-09 22:44 UTC
Labels: API consistency, won't or can't fix
