### ISSUE TITLE
BUG: ConversionInterface not taken into account for errorbar

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#14554] opened 2019-06-14 17:14 UTC
It looks like ``errorbar`` doesn't take into account the ``ConversionInterface`` - here's an example:

```python
import numpy as np
from astropy import units as u
from matplotlib import pyplot as plt
from matplotlib import units


class TestConverter(units.ConversionInterface):

    def default_units(self, x, axis):
        print("In default_units", x, axis)
        return 'test'

    def convert(self, value, unit, axis):
        print("In convert", value, unit, axis)
        return np.ones(len(value))


x = np.arange(10) * u.m
y = np.arange(10)

units.registry[u.Quantity] = TestConverter()

print("HIST")
plt.hist(x, bins=50)
print("ERRORBAR")
plt.errorbar(x, y, yerr=0.1)

plt.savefig('test.png')
```

The output is:

```
HIST
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
In default_units [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] m XAxis(80.000000,52.800000)
In convert [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] m test XAxis(80.000000,52.800000)
ERRORBAR
In convert [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] m test XAxis(80.000000,52.800000)
In convert [<Quantity 0. m>, <Quantity 1. m>, <Quantity 2. m>, <Quantity 3. m>, <Quantity 4. m>, <Quantity 5. m>, <Quantity 6. m>, <Quantity 7. m>, <Quantity 8. m>, <Quantity 9. m>] test XAxis(80.000000,52.800000)
```

It looks like ``errorbar`` is not using the conversion interface properly as it should not be iterating over the ``Quantity`` object and passing in a list.

**Comment by dstansby** [comment] 2020-06-27 18:03
I'm confused as to what the problem is here? Is it an unexpected crash, or an incorrect plot? If it's the latter, could you post an image of the incorrect plot.

**Comment by jklymak** [comment] 2020-09-07 22:14
I'll close for lack of comment, but feel free to re-open....

**Comment by astrofrog** [comment] 2020-09-07 22:33
@jklymak @dstansby I don't have privileges to re-open this so if someone could that would be great. The main issue here is not incorrectness or crash but rather performance - as mentioned in the main description, when calling the convert method a list of Quantity (a Numpy array subclass) objects is passed instead of a vector Quantity - this indicates that somewhere errorbar is not playing nice with numpy array sub-classes. This can lead to a serious performance hit as instantiating Quantity objects can be quite slow (at least when done 1000 times). This is not a problem for e.g. hist which preserves Quantity as vector objects.

**Comment by jklymak** [comment] 2020-09-07 22:40
I'm not sure anyone needs to make 1000 errorbars, but sure - if error bar is not playing well with units, it should be looked at.

**Comment by QuLogic** [comment] 2020-09-08 21:16
`errorbar` goes out of its way to use lists, supposedly in support of units:
https://github.com/matplotlib/matplotlib/blob/855e3bb474428d2be0b89134d12d0fef5d584eb6/lib/matplotlib/axes/_axes.py#L3457-L3458
but nothing is tested there, so I have no idea what the effect of that really is.

**Comment by ksunden** [comment] 2023-03-23 01:49
Current behavior seems to no longer exhibit the stated problem, the numpy array subclass is retained:

```
HIST
In default_units [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] m XAxis(80.0,52.8)
In convert [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] m test XAxis(80.0,52.8)
ERRORBAR
In default_units [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] m XAxis(80.0,52.8)
In convert [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] m test XAxis(80.0,52.8)
In convert [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] m test XAxis(80.0,52.8)
```

Thus, I'll close this

**Closed by ksunden** 2023-03-23 01:49 UTC
Labels: topic: units and array ducktypes
