### ISSUE TITLE
Legend line colors change depending on position of legend

### ISSUE THREAD

**Issue by jonathanunderwood** [matplotlib/matplotlib#12589] opened 2018-10-22 13:26 UTC
**Bug summary**
Working inside a Jupyter notebook, I am observing that the line colors in a legend depend on whether the legend is positioned inside the plot area, or outside of it. This trivial example shows the problem:

**Code for reproduction**

```python
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
matplotlib.rcParams['figure.figsize'] = [2.0 * 6.0, 2.0 * 4.0]

x=np.arange(10)
y1=np.sin(x)
y2=x
y3=np.cos(x)

plt.plot(x, y1, label='a')
plt.plot(x, y2, label='b')
plt.plot(x, y3, label='c')
plt.legend(bbox_to_anchor=(1.05, 1))
```

![screenshot from 2018-10-22 14-25-52](https://user-images.githubusercontent.com/992114/47294995-740da800-d606-11e8-8de3-126de6196677.png)

**Actual outcome**
The line color for line 'b' changes depending on whether it's inside or outside the main plot area. The other two line colors are not changed. Setting `framealpha=1.0` for the legend fixes the problem. 

**Expected outcome**
Legend line color doesn't depend on legend position.

**Matplotlib version**
  * Operating system:
Fedora 28

  * Matplotlib version: 
matplotlib==3.0.0

  * Matplotlib backend (`print(matplotlib.get_backend())`):
module://ipykernel.pylab.backend_inline

  * Python version:
Python 3.6.6

  * Jupyter version (if applicable):
jupyter-client==5.2.3
jupyter-console==6.0.0
jupyter-core==4.4.0

  * Other libraries: 
$ pip freeze
backcall==0.1.0
bleach==3.0.2
cycler==0.10.0
dataclasses==0.6
decorator==4.3.0
defusedxml==0.5.0
entrypoints==0.2.3
ipykernel==5.1.0
ipython==7.0.1
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.13.1
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==6.0.0
jupyter-core==4.4.0
kiwisolver==1.0.1
MarkupSafe==1.0
matplotlib==3.0.0
mistune==0.8.4
nbconvert==5.4.0
nbformat==4.4.0
notebook==5.7.0
numpy==1.15.2
pandas==0.23.4
pandocfilters==1.4.2
parso==0.3.1
pexpect==4.6.0
pickleshare==0.7.5
prometheus-client==0.4.2
prompt-toolkit==2.0.6
ptyprocess==0.6.0
Pygments==2.2.0
pyparsing==2.2.2
python-dateutil==2.7.3
pytz==2018.5
pyzmq==17.1.2
qtconsole==4.4.2
scipy==1.1.0
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.11.0
terminado==0.8.1
testpath==0.4.2
tornado==5.1.1
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2

This was all running inside a virtual env with packages installed via pip.

**Comment by ImportanceOfBeingErnest** [comment] 2018-10-24 02:51
This is a really special issue, which is hard to reproduce. First, restart the kernel, open a new notebook and run this in the first cell of it (I never trust any bug reports that show a problem in cell 101).
If the problem persists, create a new environment with only the necessary packages (here numpy, matplotlib and jupyter (and their dependencies)), see if this reproduces the issue and then install further packages one by one. 
Also to make sure it's not some rendering problem, try in a different browser, and possibly report the contents of `%config InlineBackend.print_figure_kwargs`.

**Comment by jonathanunderwood** [comment] 2018-10-24 08:15
I have done exactly that:

```
$ python3 -m venv venv2
$ source venv2/bin/activate
(venv2) $ pip3 install matplotlib jupyter
...
$ jupyter notebook
```

```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
matplotlib.rcParams['figure.figsize'] = [2.0 * 6.0, 2.0 * 4.0]

x=np.arange(10)
y1=np.sin(x)
y2=x
y3=np.cos(x)

plt.plot(x, y1, label='a')
plt.plot(x, y2, label='b')
plt.plot(x, y3, label='c')
plt.legend(bbox_to_anchor=(1.05, 1))
```

![screenshot from 2018-10-24 09-07-02](https://user-images.githubusercontent.com/992114/47415906-6f630400-d76c-11e8-9c28-80d299150547.png)

Very easy to reproduce.

```
%config InlineBackend.print_figure_kwargs
```
produces:
```
{'bbox_inches': 'tight'}
```

![screenshot from 2018-10-24 09-11-21](https://user-images.githubusercontent.com/992114/47416083-d1bc0480-d76c-11e8-8fee-698c2c89000b.png)

This is with the Chrome browser, Version 70.0.3538.67 (Official Build) (64-bit) on Fedora.

**However** I tried exactly the same thing under Firefox 62.0.3 (64 bit) and I don't see the problem! So the problem manifests in Chrome, but not Firefox.

**Comment by cash** [comment] 2018-11-17 20:52
I am able to reproduce this problem. Chrome Version 70.0.3538.102 (Official Build) (64-bit) on Ubuntu 16.04

matplotlib 3.0.1
jupyter 4.4.0

![image](https://user-images.githubusercontent.com/199558/48665650-6ff76d80-ea80-11e8-80f6-065a9393faca.png)

Also works fine with Firefox

**Comment by ImportanceOfBeingErnest** [comment] 2018-11-17 21:32
The way to report bugs in chrome seems to be [this one](https://support.google.com/chrome/answer/95315?co=GENIE.Platform%3DDesktop&hl=en).

**Comment by jonathanunderwood** [comment] 2018-11-17 21:48
Are we certain this is a chrome bug?

**Comment by jklymak** [comment] 2018-11-17 21:54
My guess, w/o looking into it, is that the facecolor of the figure needs to be set to white to work on both browsers.  But there is no alpha in your line, so its kinda hard to see how this is Matplotlib's fault.  Did the behaviour change recently, or has this always been a problem?

**Comment by jonathanunderwood** [comment] 2018-11-17 21:57
I only recently started needing to use Chrome, so I am not sure when it first started, i am afraid.

**Comment by jklymak** [comment] 2018-11-17 22:06
Unhelpfully, I cannot reproduce on my mac Chrome:

<img width="598" alt="screen shot 2018-11-17 at 2 04 42 pm" src="https://user-images.githubusercontent.com/1562854/48666192-d45f0080-ea71-11e8-978b-44241520c66b.png">

**Comment by cash** [comment] 2018-11-18 00:00
It is an issue with PNG transparency in the legend. Turning off hardware acceleration in Chrome fixed the issue for me.

**Comment by anntzer** [comment] 2019-06-07 15:01
From the discussion here and a bit of googling, it looks this this is an upstream bug in chrome; see also
https://askubuntu.com/questions/1061294/google-chrome-green-outline-around-red-images-in-white-background
https://bugs.chromium.org/p/chromium/issues/detail?id=867813&q=hardware-acceleration%20green&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
https://support.google.com/chrome/forum/AAAAP1KN0B0exyLAt0wjwU/?hl=en&gpf=%23!topic%2Fchrome%2FexyLAt0wjwU%3Bcontext-place%3Dtopicsearchin%2Fchrome%2Fcategory%243ABeta%257Csort%3Arelevance%257Cspell%3Afalse

This should also be fixed in chrome>=70, so I'm going to close this.  Feel free to request a reopen if this can be reproed with a newer chrome *and* turning off hardware acceleration (per https://github.com/matplotlib/matplotlib/issues/12589#issuecomment-439656645, also mentioned in the links) doesn't suffice.

**Closed by anntzer** 2019-06-07 15:01 UTC
