### ISSUE TITLE
Importing matplotlib.animation prevents python script from executing in the background

### ISSUE THREAD

**Issue by helloworld922** [matplotlib/matplotlib#13619] opened 2019-03-07 21:49 UTC
### Bug report

**Bug summary**

Trying to import matplotlib.animation in a Python script prevents it from executing in the background.
I couldn't get the script to run past just the import, but it would also be nice if I could use the animation module to just generate movie file outputs in the background.

**Code for reproduction**

Python code:
```python
# my_script.py
import matplotlib.animation
```

Bash command:
```shell
python3 my_script.py &
jobs
```

**Actual outcome**

```
[1]+  Stopped                 python3 input.py
```

**Expected outcome**

There should be no extra console output from the jobs command since all jobs should have terminated.

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 2.1.1
  * Matplotlib backend: Qt4Agg
  * Python version: 2.7.15rc1 and 3.6.7
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

matplotlib was installed using apt-get:

```
sudo apt install python-matplotlib python3-matplotlib
```

**Comment by tacaswell** [comment] 2019-03-08 01:36
I can reproduce this (on both master and 2.2.4)

The problem seems to be an interaction between backgrounding the process the subprocess calls we make as part of sorting out if ffmpeg is available.

Looks like https://stackoverflow.com/questions/21141352/python-subprocess-calling-a-script-which-runs-a-background-process-hanging and 
https://bugs.python.org/issue13422 are relevant here.

**Comment by tacaswell** [comment] 2019-10-22 19:39
This is working on master and we think think this was fixed by https://github.com/matplotlib/matplotlib/pull/13567.  Close as fixed and not backporting as this is too big of a patch to backport.

**Closed by tacaswell** 2019-10-22 19:39 UTC
Labels: Animation
