### ISSUE TITLE
[Bug]: Python 3.11

### ISSUE THREAD

**Issue by machinelearning7** [matplotlib/matplotlib#22527] opened 2022-02-22 08:17 UTC
### Bug summary

matplotlib doesn't seem to be compatible with Python 3.11, get an error when downloading. Please address the issue or let me know if I need to downgrade to python 3.10. 

### Code for reproduction

```python
BUILDING MATPLOTLIB
            python: yes [3.11.0a5 (v3.11.0a5:c4e4b91557, Feb  3 2022, 14:54:01) [Clang
                        13.0.0 (clang-1300.0.29.30)]]
          platform: yes [darwin]
             tests: no  [skipping due to configuration]
            macosx: yes [installing]
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

### Actual outcome

. BUILDING MATPLOTLIB
            python: yes [3.11.0a5 (v3.11.0a5:c4e4b91557, Feb  3 2022, 14:54:01) [Clang
                        13.0.0 (clang-1300.0.29.30)]]
          platform: yes [darwin]
             tests: no  [skipping due to configuration]
            macosx: yes [installing]
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

### Expected outcome

. BUILDING MATPLOTLIB
            python: yes [3.11.0a5 (v3.11.0a5:c4e4b91557, Feb  3 2022, 14:54:01) [Clang
                        13.0.0 (clang-1300.0.29.30)]]
          platform: yes [darwin]
             tests: no  [skipping due to configuration]
            macosx: yes [installing]
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

### Additional information

see above

### Operating system

os/x

### Matplotlib Version

pip instal matplotlib

### Python version

3.11

### Installation

pip

**Comment by jklymak** [comment] 2022-02-22 09:03
3.11 is not released yet, so if you need to use it you are kind of on your own to compile.

**Comment by oscargus** [comment] 2022-02-22 17:16
Hard to say anything from the sparse log, but may be worth adding 3.11 here: https://github.com/matplotlib/matplotlib/blob/main/setup.py#L288

I doubt that it will help, but the only part of in setup that has anything to do with it. (I would expect NumPy to be a bigger issue, that is what I had problems with trying to get CI running for 3.11.)

**Comment by tacaswell** [comment] 2022-02-22 20:11
My default development environment is the cpython main branch ( https://github.com/tacaswell/build_the_world if you want to participate in this activity ;) ).  Matplotlib compiles and passes tests locally for me and I do not recall any particular fixes that Matplotlib needed to move to py311.  

There is not enough information here to be sure what is going wrong, but I suspect that this a local-build issue.  There tends to be a lot of conflict between CPython and cython (because cython reaches in and touches deep CPython internals and CPython is on a multi-year mission to streamline their internals to enable some go-fast work).  My guess would be that the OP has not previously installed numpy, which in turn requires cython, the 0.29.x cython on pypi does not always work with the development branch of CPython (because the cython developers quite reasonably do not want to wast time chasing a moving target).  Thus, I would bet a cup of coffee that the the problem is in fact with the cythonization / compliation of numpy and not with us.

@machinelearning7 I appreciate you trying out pre-releases (this is something I wish more people did for more projects and is why I do it), but we need more information (e.g. the actual compiler errors).  It may be also worth explicitly installing all of the dependencies "by hand" first to help pin down which project is giving the difficulty.

**Comment by greglucas** [comment] 2022-02-22 22:06
@tacaswell, do you know how long it takes to build the MPL-specific dependencies on 3.11? We could add something like this to the "nightly wheels" scheduled test to run once a week. It looks like the Python 3.11 pre-releases are available on GitHub Actions.

**Comment by QuLogic** [comment] 2022-02-23 07:20
Python 3.11 alphas do not have a stable ABI, so we (and probably most of our dependencies) won't have wheels available. I'm going to close this as unsupported.

**Closed by QuLogic** 2022-02-23 07:20 UTC
Labels: status: needs clarification

**Comment by stonebig** [comment] 2022-08-11 18:29
Python-3.11 as entered "Release Candidates" stage. May we have a "pre" wheels  ? (windows 64 bit if you do only one)
