### ISSUE TITLE
ColorbarBase() is dpi dependent 

### ISSUE THREAD

**Issue by IvanAvdeevGth** [matplotlib/matplotlib#8378] opened 2017-03-25 22:27 UTC
Hi everyone,

I find it out that there is a strange issue with matplotlib.colorbar.ColorbarBase(): when i save a figure with a colorbar in a vector format (such as pdf or eps) the colorbar is kinda jumps out its bounding axes object. First of all i tried to look at colorbar.solid objects, which seems to me as the main colour plot, but all the coordinates of this object was just fine. 

To solve the problem of 'jumped out' colorbars i noticed that it depends on the dpi parameter in the figure.savefig() method. Anyway it is curious for me that dpi is actually a very important parameter for vector pictures (ofc if you use colorbars in such plots).

Examples of different plots are here in included files
[cbar_dpi2.pdf](https://github.com/matplotlib/matplotlib/files/870417/cbar_dpi2.pdf)
[cbar_dpi5.pdf](https://github.com/matplotlib/matplotlib/files/870418/cbar_dpi5.pdf)
[cbar_dpi10.pdf](https://github.com/matplotlib/matplotlib/files/870415/cbar_dpi10.pdf)
[cbar_dpi20.pdf](https://github.com/matplotlib/matplotlib/files/870419/cbar_dpi20.pdf)
[cbar_dpi30.pdf](https://github.com/matplotlib/matplotlib/files/870416/cbar_dpi30.pdf)
[cbar_dpi50.pdf](https://github.com/matplotlib/matplotlib/files/870414/cbar_dpi50.pdf)
[cbar_dpi100.pdf](https://github.com/matplotlib/matplotlib/files/870420/cbar_dpi100.pdf)
[cbar_dpi200.pdf](https://github.com/matplotlib/matplotlib/files/870421/cbar_dpi200.pdf)

**Comment by QuLogic** [comment] 2017-03-25 23:50
Dupe of #6827.

**Closed by QuLogic** 2017-03-25 23:50 UTC
