### ISSUE TITLE
[Bug]: Matplotlib crashes using Figure Options gui with QT5Agg backend on Windows 10 running Spyder

### ISSUE THREAD

**Issue by Jesperten** [matplotlib/matplotlib#22543] opened 2022-02-23 10:21 UTC
### Bug summary

Using the QT5Agg backend with the 3.5.1 version of Matplotlib crashes after pressing 'ok' in the Figure Options GUI. This happens regardless of doing any changes to the plot or not.
The only way to bring Matplotlib back to life, is to restart the python kernel.

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.plot([1,2],[1,2])

# Then open Figure Options, and press 'ok'
```

### Actual outcome

Plot window becomes inactive, and does not response to any input.

### Expected outcome

No changes to the plot window whatsoever. The window should continue being responsive.

### Additional information

I am running my scripts in Spyder, which is where I am experiencing this bug.

### Operating system

Windows 10

### Matplotlib Version

3.5.1

### Matplotlib Backend

Qt5Agg

### Python version

3.9.10

### Installation

conda

**Comment by oscargus** [comment] 2022-02-23 11:06
Can you try running the scripts from a terminal? I experience similar problems and it seems to work better from a terminal. Still a problem of course, but would be interesting to narrow it down. It may still be a Matplotlib issue, but also a Spyder/spyder-kernel/IPython/ipykernel problem...

**Comment by Jesperten** [comment] 2022-02-23 11:11
Hi. thanks for responding so fast.
It works well from a terminal running in the same conda-environment as I use from Spyder.
So it might be related to Spyder/iPython kernel issue...

**Comment by oscargus** [comment] 2022-02-23 11:34
Here are some related issues:
https://github.com/ipython/ipykernel/issues/775
https://github.com/spyder-ide/spyder/issues/17172

Not explicitly like this, but at least indicating that there are some problems with the related code and that it is not really clear who should change what... But for sure worthwhile digging into!

**Comment by oscargus** [comment] 2022-02-23 12:58
It may be that this is fixed by https://github.com/matplotlib/matplotlib/pull/22202

**Comment by QuLogic** [comment] 2022-04-08 22:57
Is there some kind of backtrace, or does it simply die?

**Comment by Jesperten** [comment] 2022-04-08 23:26
It simply just dies, when I try to open the menu.

**Comment by raphaelquast** [comment] 2022-05-18 10:18
hey, I thought I'll add my problem here since it seems to be quite related...  (and I'm using matplotlib v3.5.2)
On my side, the Qt5Agg gui becomes irresponsive if I click on the button to adjust the axis limits while there is more than 1 axes in the plot...  (`plt.subplots(2)` or `ax.twinx()` show the same behaviour)

... and it also simply dies (I can't even close or resize the gui any more)

![mpl_issue](https://user-images.githubusercontent.com/22773387/169013673-bd6ea7c5-cb69-4d30-bf9a-cf09f27bd7d4.gif)

**Comment by Jesperten** [comment] 2022-05-18 13:06
I experience the exact same thing.
The funny thing is that if you manage to hit ok in the pop-up window, before it crashes, it actually stays functional.
So it might be related to the initial window, where you can select which plot you want to configure.

**Comment by raphaelquast** [comment] 2022-05-20 08:34
hey, thanks for the response!

I checked and using `plt.show(block=True)` or a plain `plt.show()` does not help.
... also I get the very same behavior in a basic python console... so spyder does not seem to have anything to do with it.

However, I noticed that this is only an issue if interactive mode is on (e.g. `plt.ion()` is called). 
In non-interactive mode, all works as expected.

<details>
<summary>(click) for a gif showing the behavior directly from a python-console</summary>

![mpl_issue](https://user-images.githubusercontent.com/22773387/169487758-360e1c2b-6d8a-4a8c-a14b-586426a05cf7.gif)

</details>

**Comment by tacaswell** [comment] 2022-05-20 17:40
The behavior of `plt.show()` depends on the value of `plt.isinteractive()` (which is stored in an rcparam).  For debugging please explicitly set `block` to True or False just to be sure we are decoupling from any underlying global state. 

Can you also test in an IPython shell (as oppossed to plain python) and make sure you are using prompttoolkit (rather then readline) for the prompt?

This is starting to get into the realm of https://matplotlib.org/stable/users/explain/interactive_guide.html and how the event loop is (or is not) managed.

**Comment by raphaelquast** [comment] 2022-05-21 14:45
Hey, I can confirm that if I directly use an `IPython 7.31.1` shell all works as expected !
(from what I read, prompttoolkit is used from v5.0 on)
The strange thing is that Spyder is using the same ipyhton version but here the error is happening just as with the plain python shell.

**Comment by tacaswell** [comment] 2022-05-22 19:58
> Hey, I can confirm that if I directly use an IPython 7.31.1 shell all works as expected !

I think this show that this is fundamentally an issue with spyder, readline, pyqt/pyside and the interaction with the event loop.  It is possible that there is something we could do differently on the Matplotlib side to work around this, but I think we would need guidance from down-stream about what those changes will be.

I would point to https://github.com/spyder-ide/spyder/issues/4367 which re-points the problem to the IPython Qt console.  I strongly suspect that this is another version of this. 

I'm going to close this issue here as

1. the issue seems isolated to usage only with in the qt ipython console
2. the integration of the event loop that hosts the Matplotlib figures (any toolkit and and downstream use) is the primary responsibility of down stream tools.  That said we will definitely take any patches that make that integration work better, but failure to work with a given integration is not a bug.

Sorry to play hot-potato 😞 .

---

attn @cordoba12

**Comment by raphaelquast** [comment] 2022-05-22 21:16
hey, ok sounds reasonable...

just as a final comment... 
i think there might be 2 different things in question here
1. the fact that spyders ipython console has the issue but a "plain ipython console" does not
2. the fact that the same error occurs in a plain python console 

While the first one is certainly on spyder (or somewhere further down the road), the second part remains puzzling ...
(e.g. the issue is not isolated to a qt ipython console)

**Comment by tacaswell** [comment] 2022-05-23 01:29
> the fact that the same error occurs in a plain python console

fair, re-opening.

**Comment by jklymak** [comment] 2022-05-23 05:04
I'll re-close since the original issue was Spyder only. @raphaelquast can you open a _new_ reproducible issue with the problem that you can reproduce without Spyder?  Thanks for your understanding.

**Closed by jklymak** 2022-05-23 05:04 UTC
Labels: OS/Microsoft, GUI/Qt

**Comment by raphaelquast** [comment] 2022-05-23 07:05
@jklymak @tacaswell moved to new issue #23103
