### ISSUE TITLE
3.4.x Removes 'drawstyle' property from errorbar (worked latest in 3.3.4)

### ISSUE THREAD

**Issue by CaptnMorgn** [matplotlib/matplotlib#20050] opened 2021-04-23 11:14 UTC
### Bug report

**Bug summary**

Despite the documentation for versions 3.4.x, errobar no longer has the `drawstyle` property/kwarg. It last worked in 3.3.4. Please see note at the bottom of the report too.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.array([0, 1, 3])
y = np.array([5, 6, 9])
u = np.array([1, 2, 4])
plt.errorbar(x, y, yerr=u, ds='steps-mid')
plt.show()
```

**Actual outcome**

```
Traceback (most recent call last):
  File ".\dummy.py", line 7, in <module>
    plt.errorbar(x, y, yerr=u, ds='steps-mid')
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\pyplot.py", line 2741, in errorbar
    return gca().errorbar(
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\__init__.py", line 1352, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\axes\_axes.py", line 3498, in errorbar
    barcols.append(self.vlines(
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\__init__.py", line 1352, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\axes\_axes.py", line 1120, in vlines
    lines.update(kwargs)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\artist.py", line 1062, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'LineCollection' object has no property 'drawstyle'
```
This output was generated using version 3.4.1 of matplotlib.

**Expected outcome**

![image](https://user-images.githubusercontent.com/19305606/115862096-4d0fd700-a3f9-11eb-8fa8-7c477aaf4701.png)
This output was generated using version 3.3.4 of matplotlib.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.1 (bugged) vs 3.3.4 (working)
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg (both bugged and working)
  * Python version: 3.8.1
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

To install 3.4.1 I used: `python -m pip install --upgrade matplotlib`
To install 3.3.4 I used: `python -m pip install matplotlib==3.3.4`

**Note**
I believe having `drawstyle` as a `kwarg` is an intended feature, but got forgotten/bugged in the 3.4.x versions. I also believe it should be a part of it as it helps make beautiful plots. E.g. histograms that have uncertainties. Please make the `kwarg` come back! Here's an example of a plot I made using the feature (via version 3.3.4):
![image](https://user-images.githubusercontent.com/19305606/115863463-15a22a00-a3fb-11eb-95db-d81194229e23.png)

**Comment by anntzer** [comment] 2021-04-23 11:31
looks like a dupe of https://github.com/matplotlib/matplotlib/issues/19879?  feel free to ping for reopen if not.

**Closed by anntzer** 2021-04-23 11:31 UTC

**Comment by CaptnMorgn** [comment] 2021-04-23 12:07
@anntzer 
> looks like a dupe of #19879? feel free to ping for reopen if not.

Ah, you're right. Didn't see that when searching prior to my posting. I'm having a hard time interpreting it's conclusion. Are `drawstyle`s coming back?

**Comment by anntzer** [comment] 2021-04-23 14:02
yes, it's coming back.

**Comment by CaptnMorgn** [comment] 2021-04-23 15:54
Sweet!
