### ISSUE TITLE
ticklabel font changes when using logscale

### ISSUE THREAD

**Issue by khx0** [matplotlib/matplotlib#8198] opened 2017-03-05 16:31 UTC
**Bug summary**

- When switching the axes scaling to 'log' the ticklabel font changes to a different font.

**Code for reproduction**
```python
logscale = True 
    
# create test data
nPoints = 200
xValues = np.logspace(-14, -4, nPoints)
yValues = [x / (1.0e-9 + x) for x in xValues]

# set up figure
f, ax1 = plt.subplots(1)

# plot data       
ax1.plot(xValues, yValues)

# set range and scale
ax1.set_xlim(1.0e-14, 1.0e-4)
if (logscale):
    ax1.set_xscale('log')
ax1.set_ylim(-0.03, 1.03)

# save to file using pdf backend
f.savefig('minimal.pdf')
```

**Actual outcome**

[minimal.pdf](https://github.com/matplotlib/matplotlib/files/819448/minimal.pdf)

**Matplotlib version**
 
This used to work for me in matplotlib version 1.5.1
I am currently using mpl version 2.0.0 on OSX 10.11.6.
My python version is 2.7.13
I am using homebrew provided python and installed matplotlib with pip.

**Comment by anntzer** [comment] 2017-03-05 19:15
Duplicate of #8017, for which a fix is coming.

**Closed by anntzer** 2017-03-05 19:15 UTC
