### ISSUE TITLE
Loglog plots with shared axes sometimes show incorrect labels

### ISSUE THREAD

**Issue by mikerenfro** [matplotlib/matplotlib#8995] opened 2017-08-05 23:01 UTC
### Bug report

**Bug summary**

Given clean loglog data, loglog subplots with shared axes work correctly. Given arbitrary loglog data, axis labels are removed incompletely.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

x_pass = np.logspace(1, 2, 3)
y1_pass = x_pass
y2_pass = 10*x_pass

x_fail = np.array([56., 140., 420.])
y1_fail = x_fail
y2_fail = 10*x_fail

f, ax = plt.subplots(2, sharex=True)
ax[0].loglog(x_pass, y1_pass, 'o')
ax[1].loglog(x_pass, y2_pass, 'o')

f, ax = plt.subplots(2, sharex=True)
ax[0].loglog(x_fail, y1_fail, 'o')
ax[1].loglog(x_fail, y2_fail, 'o')
```

**Actual outcome**

![correct](https://user-images.githubusercontent.com/1451881/28999306-2ee9096a-7a07-11e7-9810-34351941f4c3.png)

![incorrect](https://user-images.githubusercontent.com/1451881/28999305-29581068-7a07-11e7-886f-0fe51700eb0b.png)

**Expected outcome**

The upper subplot in the second figure should hide all its x axis labels, similar to the upper subplot in the first figure.

**Matplotlib version**

  * Operating System: MacOS 10.12.6
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.1 (Python 5.3.0)
  * Other Libraries: numpy 1.12.1

Installed from Anaconda3-4.4.0-MacOSX-x86_64.pkg

**Comment by QuLogic** [comment] 2017-08-06 01:01
This is a duplicate of #8903.

**Closed by QuLogic** 2017-08-06 01:01 UTC
