### ISSUE TITLE
pip install matplotlib broken due to kiwisolver update

### ISSUE THREAD

**Issue by sampathweb** [matplotlib/matplotlib#14045] opened 2019-04-26 00:52 UTC
### Bug report

`pip install matplotlib` fails today on `kiwisolver` error on Mac.  Something broke on `kiwisolver` update that was pushed recently (https://pypi.org/project/kiwisolver/#history).  Related issue - https://github.com/nucleic/kiwi/issues/66

**Code for reproduction**

```bash
conda create -n kiwi-bug python-3.6
conda activate kiwi-bug . # or source activate kiwi-bug
pip install matplotlib
```

**Actual outcome**

<img width="1395" alt="Screen Shot 2019-04-25 at 5 52 14 PM" src="https://user-images.githubusercontent.com/1437573/56776770-e52f4300-6782-11e9-8671-8f5cb7d4b41b.png">

**Comment by tacaswell** [comment] 2019-04-26 01:50
Closing as this looks like there was a missing wheel (as they said over on nucleic/kiwi#66).

@sampathweb can you confirm that this is working now?

**Comment by ksunden** [comment] 2019-04-26 01:50
Duplicate of #14031 
Should have been fixed by the wheels being pushed up to PyPI

**Closed by tacaswell** 2019-04-26 01:50 UTC

**Comment by sampathweb** [comment] 2019-04-26 14:27
Yes..Thanks for your quick response.  It's all resolved now.

**Comment by starseedme** [comment] 2020-10-17 10:01
Even if you get the latest wheen in pypi, the install would still hault at kiwisolver. I have been working on this for more than a day, and my angel coached me :)

> What we did, install kiwisolver 1st, then install matplotlib ---and voila! Installed smoothly!

 

Thanks to the unseen angel coaches!

**Comment by jakubedzior** [comment] 2020-10-19 10:29
pip install wheel
pip install kiwisolver
pip install matplotlip

**Comment by BeckIUT** [comment] 2020-10-23 05:57
it worked thanks 👍

**Comment by swight-prc** [comment] 2020-10-30 16:33
Did not work for me. Seems to want me to have some Microsoft C++ build tools.
