### ISSUE TITLE
inset_axes should have some sort of `set_position`

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#20236] opened 2021-05-15 17:42 UTC
`ax.inset_axes` does not allow `set_position` or `set_transform` if the user wants to change the position of an inset axes.  This s probably easy to add, but I think means that `inset_axes` would need to have a new axes subclass that overloads those methods.

**Comment by jklymak** [comment] 2021-05-15 17:43
x-ref: https://stackoverflow.com/questions/67542636/how-to-update-positions-of-inset-axes-in-matplotlib

**Comment by jeffreypaul15** [comment] 2021-05-16 17:11
@jklymak Could I give this a go?

**Comment by jklymak** [comment] 2021-05-16 17:16
I think so.  Right now `inset_axes` is just a normal `Axes`.  It would be an API change to hoist it to a new subclass (`InsetAxes`?).  But then `bounds` could be modified via `set_position`, and `transform` via `set_transform`.  I think its pretty straightforward. 

However, as you've seen, API decisions can be a bit involved, so just be prepared for some back and forth.

**Comment by QuLogic** [comment] 2023-01-10 10:04
This seems to be a duplicate of #12985?

**Comment by QuLogic** [comment] 2023-01-26 08:30
Going to close as a duplicate of #12985.

**Closed by QuLogic** 2023-01-26 08:30 UTC
Labels: New feature, topic: axes
