### ISSUE TITLE
Plotting three points using scatter results in wrong color - 1.4.3

### ISSUE THREAD

**Issue by liujimj** [matplotlib/matplotlib#5377] opened 2015-11-02 06:31 UTC
I'm running this on Windows 10 / Anaconda Python 3.4.3 / jupyter iPython 4

Here's some repro code:

```python
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure(1)
ax = plt.axes([0., 0., 1., 1.])

points = np.random.rand(2,2) # plot 2 points, totally fine
ax.scatter(points[0], points[1], c=[1, 0, 0],  s=200)
points = np.random.rand(2,3) # plot 3 points, hopelessly broken
ax.scatter(points[0], points[1], c=[0, 1, 0], s=200)
points = np.random.rand(2,3) # plot 3 points with string color, totally ok
ax.scatter(points[0], points[1], c='g', s=200)
points = np.random.rand(2,4) # plot 4 points, totally fine
ax.scatter(points[0], points[1], c=[0, 0, 1], s=200)
plt.show()
```

Here's what I get:

![download 1](https://cloud.githubusercontent.com/assets/704823/10875507/0e2d8a62-80e8-11e5-9a6a-63bd7c144650.png)

As you can see, plotting 2, 4, or any other number of points using `ax.scatter` is fine, but graphing 3 points while using RGB color array results in two points as black, and one point as white, instead of using the specified color.

Here's an example on a real dataset. As you can see, it also messes with the legend color. It's hard to diagnose the issue because it's completely non-obvious that the number of points plotted is what triggers the bug.
![download 2](https://cloud.githubusercontent.com/assets/704823/10875511/17ee50cc-80e8-11e5-81da-d02cf80d489c.png)

I was pulling my hair out for awhile until I realized that the problem only manifested itself on series that had 3 members.

**Comment by efiring** [comment] 2015-11-02 06:53
Confirmed on master.
As a workaround, if you use `c=[[0, 1, 0]]` it will work.
Without the workaround, I get 2 black and 1 magenta rather than white; but in any case it is a bug.

**Comment by liujimj** [comment] 2015-11-02 07:08
Thanks for taking a look.

I tried the workaround but I don't see any change. With nested color arrays:

![download 3](https://cloud.githubusercontent.com/assets/704823/10875998/66ba8ff4-80ed-11e5-9982-187701991023.png)

Here's my attempt:
```
import matplotlib.pyplot as plt

fig = plt.figure(1)
ax = plt.axes([0., 0., 1., 1.])

points = np.random.rand(2,2) # plot 2 points, OK
ax.scatter(points[0], points[1], c=[[1, 0, 0]],  s=200)
points = np.random.rand(2,3) # plot 3 points, broken
ax.scatter(points[0], points[1], c=[[0, 1, 0]], s=200)
points = np.random.rand(2,3) # plot 3 points with string color, OK
ax.scatter(points[0], points[1], c='g', s=200)
points = np.random.rand(2,4) # plot 4 points, OK
ax.scatter(points[0], points[1], c=[[0, 0, 1]], s=200)
plt.show()
```

**Comment by u55** [comment] 2015-11-02 08:34
You have it backwards.  In your examples, the scatter plots with three points are correct, the other plots are wrong.  The documentation for `scatter` says:

c can be a single color format string, or a sequence of color specifications of length N, or a sequence of N numbers to be mapped to colors using the cmap and norm specified via kwargs (see below). **Note that c should not be a single numeric RGB or RGBA sequence because that is indistinguishable from an array of values to be colormapped.** c can be a 2-D array in which the rows are RGB or RGBA, however.

(emphasis mine)

The problem, in my opinion, is that `scatter` should raise a ValueError if `c` is a sequence and does not equal the number of points, instead of trying to interpret sequences of length=3 as RGB values, and sequences of length=4 as RGBA values, as it currently does.

Note that the results depend on the current default colormap, as expected:
```python
import matplotlib.pyplot as plt
import numpy as np

fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2,2)

plt.rcParams['image.cmap'] = 'jet'
points = np.random.rand(2,3)
ax1.scatter(points[0], points[1], c=[0, 1, 0.3], s=200)

plt.rcParams['image.cmap'] = 'gray'
points = np.random.rand(2,3)
ax2.scatter(points[0], points[1], c=[0, 1, 0.3], s=200)

plt.rcParams['image.cmap'] = 'cool'
points = np.random.rand(2,3)
ax3.scatter(points[0], points[1], c=[0, 1, 0.3], s=200)

plt.rcParams['image.cmap'] = 'BrBG'
points = np.random.rand(2,3)
ax4.scatter(points[0], points[1], c=[0, 1, 0.3], s=200)

plt.show()
```
![scatter_bug](https://cloud.githubusercontent.com/assets/8595627/10877202/354a7b32-8101-11e5-97e0-90721e107c30.png)

**Comment by liujimj** [comment] 2015-11-03 18:27
TIL that the c argument expects a vector of colors.

Shouldn't this work though?
`ax.scatter(points[0], points[1], c=[[0, 1, 0]], s=200)`

From the docs: "c can be a 2-D array in which the rows are RGB or RGBA, however, including the case of a single row to specify the same color for all points."

**Comment by u55** [comment] 2015-11-04 04:22
I agree that `c=[[0, 1, 0]]` should work as a single RGB color, but matplotlib 1.5.0 incorrectly treats it the same as `c=[0, 1, 0]`.  This is definitely a bug.

Another possible workaround is to use `matplotlib.colors.rgb2hex`.  Example usage:
```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import rgb2hex
plt.rcParams['image.cmap'] = 'gray'

fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2,2)
points = np.random.rand(2,3)

ax1.scatter(points[0], points[1], s=200, c=[[0, 1, 0]]) # Wrong!
ax2.scatter(points[0], points[1], s=200, c=(points.shape[1]*[[0, 1, 0]])) # Works Correctly
ax3.scatter(points[0], points[1], s=200, c=np.repeat([[0, 1, 0]], points.shape[1], axis=0)) # Works Correctly
ax4.scatter(points[0], points[1], s=200, c=rgb2hex([0, 1, 0])) # Works Correctly

plt.show()
```

**Comment by liujimj** [comment] 2015-11-07 18:03
I confirm that both workarounds get the intended results. Thank you both for your help.

**Comment by has2k1** [comment] 2015-11-14 06:01
Same issue with RGBA tuple. This time the bug shows up when plotting 4 points

```python
import matplotlib.pyplot as plt

x = [[1],
     [2, 2],
     [3, 3, 3],
     [4, 4, 4, 4],
     [5, 5, 5, 5, 5],
     [6, 6, 6, 6],
     [7, 7, 7],
     [8, 8],
     [9]]
y = [list(range(len(_x))) for _x in x]
facecolor = (1.0, 1.0, 1.0, .5)

fig, ax = plt.subplots(1)
for i in range(len(x)):
    ax.scatter(x=x[i],
               y=y[i],
               facecolor=facecolor,
               s=15**2)

plt.show()
```

![scatter-colortup-glitch](https://cloud.githubusercontent.com/assets/780341/11162323/90637c2a-8a62-11e5-8968-734e3039d270.png)

**Comment by wavexx** [comment] 2016-05-16 20:34
I got bitten by this behavior several times now. Seeing #6087 being closed woke me up.
Can't we restrict color specs to be always tuples and remove the ambiguity?

I understand that underneath we convert to ndarray, but the public interface seems pretty unambiguous to me.

**Comment by tacaswell** [comment] 2016-05-16 23:20
The last example now works correctly on 2.x (more-or-less, the default edge width and color changed to 0 and 'face')

```python
import matplotlib.pyplot as plt

x = [[1],
     [2, 2],
     [3, 3, 3],
     [4, 4, 4, 4],
     [5, 5, 5, 5, 5],
     [6, 6, 6, 6],
     [7, 7, 7],
     [8, 8],
     [9]]
y = [list(range(len(_x))) for _x in x]
facecolor = (1, 1, 1, .5)

fig, ax = plt.subplots(1)
for i in range(len(x)):
    ax.scatter(x=x[i],
               y=y[i],
               facecolor=facecolor,
               s=15**2,
               linewidths=1,
               edgecolors='k')

plt.show()
```
![so](https://cloud.githubusercontent.com/assets/199813/15306672/bcc2bece-1b9a-11e6-8443-7a1e147c3793.png)


The fundemental problem here is that sometimes `c` is meant as a 'color spec', that is an RGB on RGBA tuple, or a string (either a color name or a float string which maps to shades of gray) *OR* an array of the same size of x and y which should be color mapped.   In the case of length 3 and 4 there is no way to break user intention so we go with color mapping.  In the case of the kwarg `color` it is always a color.

**Comment by efiring** [comment] 2016-05-17 00:08
On 2016/05/16 10:34 AM, wavexx wrote:
> Can't we restrict color specs to be always tuples and remove the ambiguity?

No, because that would eliminate the use of a 2-D ndarray, (n,3) or 
(n,4), for a sequence of colorspecs.  Or a row indexed from such an array.

With the most recent change, if you want a single color for everything, 
use the "color" kwarg.

The design error here, from early days (and probably from copying 
Matlab), is trying to use a single kwarg for too many different things.

**Comment by wavexx** [comment] 2016-05-24 21:13
The answer from @efiring settles my confusion about allowed types. I didn't realize 2d ndarrays were allowed as well.

My only fear is the subtle difference in c/color semantics used in existing functions (where c/color are aliases).

**Comment by tacaswell** [comment] 2017-10-21 18:04
Closing as given the extra degrees of freedom in `c` we are breaking the ambiguity in a reasonable way and if the user wants to set the (rather than go through the color mapping framework via 'c')  they can use `color` or `facecolor`/`edgecolor`.

**Comment by anntzer** [comment] 2017-10-21 18:29
I think the subtle difference between `c` and `color` could at least be better documented (e.g. in the docstring entry for `c`?).  Feel free to reclose if you disagree.

**Comment by tacaswell** [comment] 2017-10-21 18:54
Fair enough.

Re-milestoned for 2.2, I am trying to use the 2.1.1 milestone to manage the 2.1.1 release!

**Comment by anntzer** [comment] 2017-10-21 19:08
that is totally fine with me :-)

**Comment by QuLogic** [comment] 2020-07-21 04:58
I think this is sufficiently documented now, from e.g., #17499.

**Closed by QuLogic** 2020-07-21 04:58 UTC
Labels: Documentation
