### ISSUE TITLE
Last legend text as path outline with usetex

### ISSUE THREAD

**Issue by rdgeorge** [matplotlib/matplotlib#4558] opened 2015-06-26 11:49 UTC
Apologies if this is a known issue.
When using an external TeX engine, text in the last legend is (I assume) drawn as paths rather than specified as text, which is visible as darker, rougher characters in PDF viewers.

![legends](https://cloud.githubusercontent.com/assets/2445016/8376570/8dbe8a26-1c00-11e5-8ade-38bb9357855f.png)

This occurs when using at least both the standard LaTeX engine and LuaLaTeX (uncomment lines below), and saving as a PDF, EPS or PNG.
It also occurs with just a single legend added via `figure.legend` or similar.

```python
import matplotlib
#matplotlib.use('pgf')
matplotlib.rcParams.update({
    'font.family': 'serif', 'text.usetex': True,
    'text.latex.preamble': [r'\usepackage{mathptmx}',],
    #'pgf.texsystem': 'lualatex',
    #'pgf.rcfonts': False,
    #'pgf.preamble': [
    #        r'\usepackage{mathtools}',
    #        r'\usepackage{lualatex-math}',
    #        r'\usepackage[noendash]{mathastext}',
    #        r'\usepackage{unicode-math}',  # unicode math setup
    #        r'\setmathfont{XITS Math}',
    #        r'\setmainfont{TeX Gyre Termes}',
    #        ]
    })
import matplotlib.pyplot as plt
import numpy as np


fig = plt.figure()
ax = fig.add_subplot(111)

x = np.arange(10)
line0 = ax.plot(x, np.sin(x))
line1 = ax.plot(x, np.cos(x))
line2 = ax.plot(x, np.tan(x))

legend0 = ax.legend((line0[0],), ('line 0',), bbox_to_anchor=(0.3, 0.2), frameon=False)
ax.add_artist(legend0)
legend1 = ax.legend((line1[0],), ('line 1',), bbox_to_anchor=(0.3, 0.15), frameon=False)
ax.add_artist(legend1)
legend2 = ax.legend((line2[0],), ('line 2',), bbox_to_anchor=(0.3, 0.1), frameon=False)
ax.add_artist(legend2)

fig.savefig('figure.pdf')
```

**Comment by tacaswell** [comment] 2015-06-26 17:44
attn @jkseppan

**Comment by jkseppan** [comment] 2015-06-28 06:05
Cannot reproduce. What versions of matplotlib and TeX? Could you attach the resulting pdf file?

**Comment by rdgeorge** [comment] 2015-06-28 07:40
I am using matplotlib 1.4.3 and I also built from master a couple of days ago with the same result.
TeX from TeXlive 2015 (reports itself as 3.14159265)

This is a pdf, but I had to give it a png extension to upload, so you'll need to change it back
![pdf-named-as-png](https://cloud.githubusercontent.com/assets/2445016/8395555/9ab14b6e-1d6e-11e5-9228-642f1a798dd8.png)

Does matplotlib internally use ghostscript/poppler or similar to create a png file? If not then maybe the fact this also happens in png images suggests a different reason - perhaps two copies overlaid on each other?

**Comment by tacaswell** [comment] 2015-07-02 17:39
As a side note legend is handled in a special way, axes have a named `_legend` attribute for the legend artist and each call to `ax.legend` replaces this artist.

You can pass lists of both handles + labels to `ax.legend` or have it search for artists in the figure which have a non-default `label (ex `ax.plot(..., label='show up in the legend')`) and it will auto-build the legend on `ax.legend()`.  See http://matplotlib.org/users/legend_guide.html for examples.

Closing as there is no bug in mpl (just a clever work around to a too-clever-so-it-is-surprising API).

**Closed by tacaswell** 2015-07-02 17:39 UTC
