### ISSUE TITLE
[Bug]: Matplotlib fig.savefig() stalls when I add a singular patch, no matter the size

### ISSUE THREAD

**Issue by evrose54** [matplotlib/matplotlib#27336] opened 2023-11-16 18:59 UTC
### Bug summary

When attempting to save a figure with matplotlib, using fig.savefig(), this function stalls if I have a singular patch, no matter the size of it. I'm not sure what's going on, as it worked yesterday fairly quickly with multiple Circle patches. However, now, even if I add one patch, the savefig call just stalls, and I'm unable to produce an image.

### Code for reproduction

```python
LOG.info(f"{shape_type} Matplotlib Patches being applied.")

    patch = getattr(matplotlib.patches, shape_type)
    crs = ccrs.CRS(mapobj)
    norm = matplotlib.colors.Normalize(vmin=0, vmax=25)
    for idx in range(10):
        lat = data_dict["latitude"][idx]
        lon = data_dict["longitude"][idx]
        radius = data_dict["product"][idx]
        shape = patch(
            crs.transform_point(lon, lat, mapobj.source_crs),
            radius * 8000,
            transform=mapobj,
            color=cmap(norm(radius)),
            alpha=0.5,
        )
        main_ax.add_patch(shape)
        break

.... later in the code

        fig.savefig(
            out_fname,
            dpi=rc_params["figure.dpi"],
            pad_inches=0.1,
            bbox_inches="tight",
            transparent=False,
        )
```

### Actual outcome

No output. Code just hangs one I call fig.savefig. Here is the size of the figure:

```
In [1]: fig
Out[1]: <Figure size 2580.65x2597.4 with 1 Axes>
```

### Expected outcome

For the figure to save with the associated `out_fname`.

### Additional information

This has previously worked, but has since stopped. Here is the version of matplotlib I am using:

```
matplotlib                    3.7.2
matplotlib-inline             0.1.6
```

### Operating system

  `Operating System: CentOS Linux 7 (Core)`

### Matplotlib Version

`matplotlib 3.7.2`

### Matplotlib Backend

agg

### Python version

`Python 3.10.12`

### Installation

pip

**Comment by rcomer** [comment] 2023-11-16 19:11
Thanks for the report @evrose54.  Could you provide a self-contained code example that we can run to reproduce the problem?

**Comment by evrose54** [comment] 2023-11-16 19:38
Sure, I'll start working on that now. Be back soon. Thanks for your quick response!

**Comment by jklymak** [comment] 2023-11-16 19:50
Preferably without cartopy as well if possible.  Otherwise might be better to report there.

**Comment by rcomer** [comment] 2024-03-31 14:14
I'm going to close this one for lack of a reproducing example.  It can always be re-opened if you can provide such an example @evrose54.  Or as @jklymak said, if you can't reproduce the example without Cartopy, feel free to open a new issue over there.

**Closed** 2024-03-31 14:15 UTC
Labels: status: needs clarification
