### ISSUE TITLE
for examples, please provide method of showing source code in browser

### ISSUE THREAD

**Issue by jason-sachs** [matplotlib/matplotlib#4378] opened 2015-04-24 16:31 UTC
The [examples](http://matplotlib.org/1.4.3/examples/index.html) and [gallery](http://matplotlib.org/1.4.3/gallery.html) are awesome, but the source code links have a mime-type of `application/octet-stream`, which prompts browsers to save them as an external file rather than trying to display them. If I just want a quick look at the python code for a particular demo, I have to go through the trouble of finding where I saved it and opening it up in an editor.

Is it possible to do one or more of the following?
- use a mime-type that browsers recognize so they can display directly
- add a "(view as text)" link to view in browser
- have a collapsible source code `<div>` that defaults to hidden, so the source code can be displayed right in the browser next to the sample image

I like the last one of these, but any of them would save me time and allow me to more quickly see how a particular example was achieved.

**Comment by jenshnielsen** [comment] 2015-04-24 16:53
I don't really understand what you are missing. Individual examples such as http://matplotlib.org/1.4.3/examples/animation/animate_decay.html and gallery pages such as http://matplotlib.org/1.4.3/examples/lines_bars_and_markers/barh_demo.html already show the source code in a syntax highlighted text box along with the link to the source code file. 

Can you elaborate on what the issue is?

**Comment by jason-sachs** [comment] 2015-04-24 16:54
OOPS -- my bad; I was looking at http://matplotlib.org/1.4.3/examples/pylab_examples/contour_demo.html and didn't scroll down enough.

**Comment by WeatherGod** [comment] 2015-04-24 17:02
Actually, there is a similar issue. When reading the API documentation, any
links to source code examples there makes it cause a download rather than a
view like it does in the gallery.

**Comment by anntzer** [comment] 2016-01-15 08:00
Kindly requesting that this issue be reopened, for the reason @WeatherGod gave.
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Configuring_server_MIME_types may be related to the problem (other websites which provide links to python sources often set the mimetype properly to application/x-python, so that firefox/chromium offer the "open with ..." option rather than just "download").

**Comment by QuLogic** [comment] 2017-05-05 06:31
This is served by GitHub; I don't think there is anything we can do about the MIME type.

**Comment by dstansby** [comment] 2017-07-10 10:01
I think that this isn't a problem now that sphinx-gallery shows the source code on the page with the example? (eg. http://matplotlib.org/devdocs/gallery/widgets/textbox.html#sphx-glr-gallery-widgets-textbox-py)

**Comment by choldgraf** [comment] 2017-07-15 17:50
All the gallery / tutorial pages will have their source code shown (at least what isn't rendered by the rST). So I think we should close this unless I'm missing something...

**Comment by WeatherGod** [comment] 2017-07-15 19:03
Agreed, closing.

**Closed by WeatherGod** 2017-07-15 19:03 UTC
Labels: Documentation
