### ISSUE TITLE
Interactive mode frozen on python 3.6.2 (Windows 7)

### ISSUE THREAD

**Issue by yhlam** [matplotlib/matplotlib#9206] opened 2017-09-20 08:22 UTC
### Bug report

**Bug summary**

Interactive mode in frozen in python 3.6.2 in Windows 7. I tried matplotlib 1.5.3, 2.0.2 and 2.1.0rc1. All of them have the same issue. Both the anaconda build and official build of python 3.6.2 have the issue. But python 3.5.1 works fine.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

plt.ion()
plt.plot([0, 1], [0, 1])
input('Press enter to exit')
```

**Actual outcome**

The matplotlib GUI screen shown up is frozen. Below is a screenhoot running with python 3.6.2 and matplotlib 2.0.2:

![mpl](https://user-images.githubusercontent.com/1593312/30631371-940e7914-9e16-11e7-8627-78dd6d7a8ffe.png)

**Expected outcome**

The same code works fine on python 3.5.1. Below is a screenshoot running with python 3.5.1 and matplotlib 2.0.2:

![mpl35](https://user-images.githubusercontent.com/1593312/30631533-1dc8770e-9e17-11e7-8292-cd62309caaa5.png)

**Matplotlib version**

  * Operating System: Windows 7 (64 bit)
  * Matplotlib Version: 1.5.3, 2.0.2, 2.1.0rc1
  * Python Version: 3.6.2 (64 bit)
  * Jupyter Version (if applicable):
  * Other Libraries:

**Comment by yhlam** [comment] 2017-09-20 09:41
The issue seems to be independent of backend. Both TkAgg and Qt5Agg have the problem.

Please let me know if more information is need from me. I am not sure how to debug this issue.

**Comment by tacaswell** [comment] 2017-09-20 15:35
Are you doing this in IPython or plain python?  If so are those versions different between py3.5 and py3.6?

**Comment by yhlam** [comment] 2017-09-21 02:03
I am using plain python. I save the code snippet above into test.py and run `python test.py`.

**Comment by tacaswell** [comment] 2017-09-21 02:41
This looks like an issue with the input hook (see https://github.com/matplotlib/matplotlib/pull/4779 for details, but basically the GUI needs to be allowed to spin it's event loop while waiting for the human to type for the figure to be responsive).  Not sure why the python version matter though...

**Comment by jenshnielsen** [comment] 2017-09-21 08:01
I can reproduce the issue with anaconda python 3.6 on windows as well as the MacOSX backend on OSX using Anaconda. But not with any other python installation or backend on OSX

**Comment by yhlam** [comment] 2017-09-21 15:26
@tacaswell, you are right, this seems to be related to `PyOS_InputHook`.

To debug the issue, I run the same script in python 3.5 and 3.6, here are the call stacks:

Python 3.5:
![py35_call_stack](https://user-images.githubusercontent.com/1593312/30702750-5bfd0daa-9f20-11e7-9a71-cbee8ce88197.png)

Python 3.6:
![py36_call_stack](https://user-images.githubusercontent.com/1593312/30702772-6d4390c0-9f20-11e7-841d-2c5afb153402.png)

Both of them are running [`PyOS_StdioReadline`](https://github.com/python/cpython/blob/2ebc5ce42a8a9e047e790aefbf9a94811569b2b6/Parser/myreadline.c#L186). In the python 3.5 call stack, the interpreter calls the tk event loop correctly. But python 3.6 is blocked by the Windows system call.

The issue is caused by [this change](https://github.com/python/cpython/commit/3929499914d47365ae744df312e16da8955c90ac), which attempt to fix Windows Unicode issue. It implemented new readline function for Windows [`_PyOS_WindowsConsoleReadline`](https://github.com/python/cpython/blob/2ebc5ce42a8a9e047e790aefbf9a94811569b2b6/Parser/myreadline.c#L102). The original implementation [calls](https://github.com/python/cpython/blob/2ebc5ce42a8a9e047e790aefbf9a94811569b2b6/Parser/myreadline.c#L268) [`my_fgets`](https://github.com/python/cpython/blob/2ebc5ce42a8a9e047e790aefbf9a94811569b2b6/Parser/myreadline.c#L31) to read input. [`my_fgets`](https://github.com/python/cpython/blob/2ebc5ce42a8a9e047e790aefbf9a94811569b2b6/Parser/myreadline.c#L31) would call `PyOS_InputHook` before the calling the real `fgets`. However, the new implementation [`_PyOS_WindowsConsoleReadline`](https://github.com/python/cpython/blob/2ebc5ce42a8a9e047e790aefbf9a94811569b2b6/Parser/myreadline.c#L102) calls `ReadConsoleW` instead of [`my_fgets`](https://github.com/python/cpython/blob/2ebc5ce42a8a9e047e790aefbf9a94811569b2b6/Parser/myreadline.c#L31), so the tk event loop is never run. 

I will file a bug report to cpython.


@jenshnielsen, I don't have a Mac machine to test. It looks like the MacOSX backend [uses](https://github.com/matplotlib/matplotlib/blob/eea8e4f6c3a97e3492ece2d2520d31f3b971580f/src/_macosx.m#L3172) `PyOS_InputHook` as well. But from what I found above, the issue seems to be affecting Windows only. I am not sure what causing the same/similar problem in OSX. It could be another bug.

**Comment by yhlam** [comment] 2017-09-21 16:18
Filed [Issue 31546](https://bugs.python.org/issue31546) in python bug tracker

**Comment by tacaswell** [comment] 2017-09-22 03:37
Closing here as cpython has decided that this is their bug.

@yhlam Thanks for reporting this and tracking it down!

**Closed by tacaswell** 2017-09-22 03:37 UTC

**Comment by Sandy4321** [comment] 2018-06-27 16:41
is bug fixed?
if not when?
it is an important bug, since everyone creates pictures??

**Comment by tacaswell** [comment] 2018-06-27 21:08
Opened a PR with the changes suggested at bpo https://github.com/python/cpython/pull/7978
