### ISSUE TITLE
Unexpected plot behavior when running stock code for confusion matrix

### ISSUE THREAD

**Issue by vkng12** [matplotlib/matplotlib#15368] opened 2019-10-03 14:20 UTC
### Bug report

**Bug summary**

I'm fairly new to matplotlib and I was trying to create a confusion matrix following the tutorial here: https://scikit-learn.org/stable/auto_examples/model_selection/plot_confusion_matrix.html. I downloaded the example code and when I ran it, the plots looked slightly cropped on the top and bottom edges.

**Code for reproduction**

```python
print(__doc__)

import numpy as np
import matplotlib.pyplot as plt

from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels

# import some data to play with
iris = datasets.load_iris()
X = iris.data
y = iris.target
class_names = iris.target_names

# Split the data into a training set and a test set
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# Run classifier, using a model that is too regularized (C too low) to see
# the impact on the results
classifier = svm.SVC(kernel='linear', C=0.01)
y_pred = classifier.fit(X_train, y_train).predict(X_test)


def plot_confusion_matrix(y_true, y_pred, classes,
                          normalize=False,
                          title=None,
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if not title:
        if normalize:
            title = 'Normalized confusion matrix'
        else:
            title = 'Confusion matrix, without normalization'

    # Compute confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    # Only use the labels that appear in the data
    classes = classes[unique_labels(y_true, y_pred)]
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    fig, ax = plt.subplots()
    im = ax.imshow(cm, interpolation='nearest', cmap=cmap)
    ax.figure.colorbar(im, ax=ax)
    # We want to show all ticks...
    ax.set(xticks=np.arange(cm.shape[1]),
           yticks=np.arange(cm.shape[0]),
           # ... and label them with the respective list entries
           xticklabels=classes, yticklabels=classes,
           title=title,
           ylabel='True label',
           xlabel='Predicted label')

    # Rotate the tick labels and set their alignment.
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
             rotation_mode="anchor")

    # Loop over data dimensions and create text annotations.
    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(j, i, format(cm[i, j], fmt),
                    ha="center", va="center",
                    color="white" if cm[i, j] > thresh else "black")
    fig.tight_layout()
    return ax


np.set_printoptions(precision=2)

# Plot non-normalized confusion matrix
plot_confusion_matrix(y_test, y_pred, classes=class_names,
                      title='Confusion matrix, without normalization')

# Plot normalized confusion matrix
plot_confusion_matrix(y_test, y_pred, classes=class_names, normalize=True,
                      title='Normalized confusion matrix')

plt.show()
```

**Actual outcome**

![Screenshot from 2019-10-03 10-12-56](https://user-images.githubusercontent.com/56123251/66134690-b2f1ff00-e5c6-11e9-9c34-f96644eaf220.png)

**Expected outcome**

The plots were expected to not look cropped.

**Matplotlib version**

  * Operating system: Ubunto 18.04
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.7
  * Jupyter version (if applicable):
  * Other libraries: 

matplotlib installed via pip.

**Comment by ImportanceOfBeingErnest** [comment] 2019-10-03 14:25
Thanks for the report.
Unfortunately, this is due to a bug (#14675) in version 3.1.1 of matplotlib . It will be fixed (#14677) in 3.1.2, which will be released very soon. So appart from the above you can also revert to matplotlib 3.1.0 for now, or use the development version.

Closing as duplicate of #14675

**Closed by ImportanceOfBeingErnest** 2019-10-03 14:25 UTC
