### ISSUE TITLE
Plotting with marker style ',' (pixel marker) shows nothing

### ISSUE THREAD

**Issue by dryo** [matplotlib/matplotlib#4095] opened 2015-02-12 16:47 UTC
* windows 7 x64
* python 3.4.2
* matplotlib 1.4.2

When doing the following, you get a nice plot:

    import matplotlib.pyplot as plt
    plt.plot([0,1,2,3,4], '.')
    plt.show()

When doing the following, the plot window opens and has same axes etc. but you can't see any points:

    import matplotlib.pyplot as plt
    plt.plot([0,1,2,3,4], ',')
    plt.show()

This worked at least with the same setup and matplotlib 1.4.0rc2

Can anyone confirm?

**Comment by mdboom** [comment] 2015-02-12 17:00
I think this is a dupe of #3990, #3711, and possibly others (this is a FRB).  Should be fixed by #3699 and #3687, which will make it into the next point release.

**Closed by mdboom** 2015-02-12 17:00 UTC
