### ISSUE TITLE
weighted_wiggle stackplot fails when all lines are zero at same x

### ISSUE THREAD

**Issue by egpbos** [matplotlib/matplotlib#6313] opened 2016-04-18 11:32 UTC
When using `stackplot(..., baseline='weighted_wiggle')` if all `y` arrays contain zero at some (interval of) `x` the plot stops rendering after that zero point.

``` python
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(10)
y = np.random.random(10)
y2 = np.random.random(10)
y3 = np.random.random(10)

y[5] = 0
y3[5] = 0

fig, ax = plt.subplots(3,2, figsize=(12,8))

ax[0,0].stackplot(x, y, baseline='sym')
ax[0,1].stackplot(x, y, baseline='weighted_wiggle')
ax[1,0].stackplot(x, y, y2, baseline='sym')
ax[1,1].stackplot(x, y, y2, baseline='weighted_wiggle')
ax[2,0].stackplot(x, y, y3, baseline='sym')
ax[2,1].stackplot(x, y, y3, baseline='weighted_wiggle')

ax[0,0].set_title('sym: no problem')
ax[0,1].set_title('failed: stops after zero `y` (x>4)')
ax[1,1].set_title('success: non-zero `y2` saves the day')
ax[2,1].set_title('failed: stops after zero `y` and `y3` (x>4)')

plt.tight_layout()
plt.show()
```

I have this issue with Matplotlib 1.5.1, installed via pip, with Python 2.7.10 on Ubuntu Linux 15.10.

**Comment by tacaswell** [comment] 2016-04-28 17:59
The problem is that there is the weighting which divides by the total weight to sort out how much to move the base line up or down.  This results in a `np.inf` being throw in which (correctly) does not plot.

@egpbos Do you understand the underlying algorithm well enough to sort out what to do in this case?

reference from source http://leebyron.com/streamgraph/

**Comment by tacaswell** [comment] 2016-04-28 17:59
attn @leebyron

**Comment by egpbos** [comment] 2018-07-10 09:32
On the left the old result, on the right the result with matplotlib 2.2.2.
<img width="1131" alt="schermafbeelding 2018-07-10 om 11 29 32" src="https://user-images.githubusercontent.com/6146598/42501709-9a95aa1e-8434-11e8-8ca0-25a7cab2a3f6.png">

I'm not sure whether this is completely expected behavior, especially the right-hand part which seems too high. But I would say the zero-issue is at least solved :)

**Comment by dstansby** [comment] 2019-07-21 15:42
Going to close this as fixed, feel free to comment or re-open if I've missed something.

**Closed by dstansby** 2019-07-21 15:42 UTC
Labels: Confirmed bug
