### ISSUE TITLE
Importing matplotlib.pyplot with Conda Python 2.7.11

### ISSUE THREAD

**Issue by rayosborn** [matplotlib/matplotlib#7708] opened 2016-12-30 15:33 UTC
Matplotlib 2.0.0rc2+2843.g22708ef
Python 2.7.11 (Conda installation on Mac OS X 10.11.6)
freetype 2.7 (conda-forge build)
libpng 1.6.26 (conda-forge build)

Importing matplotlib.pyplot fails because the version of ft2font.so is too low. I experienced a similar problem before, which required manually updating libpng, so I updated freetype and libpng, but it hasn't fixed it. 

Here's the traceback:

    Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58) 
    [GCC 4.2.1 (Apple Inc. build 5577)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    Anaconda is brought to you by Continuum Analytics.
    Please check out: http://continuum.io/thanks and https://anaconda.org
    >>> import matplotlib.pyplot as plt
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
        import matplotlib.colorbar
      File "/Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/colorbar.py", line 36, in <module>
        import matplotlib.contour as contour
      File "/Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/contour.py", line 22, in <module>
        import matplotlib.font_manager as font_manager
      File "/Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/font_manager.py", line 58, in <module>
        from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
    ImportError: dlopen(/Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/ft2font.so, 2): Library not loaded: @rpath/libfreetype.6.dylib
      Referenced from: /Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/ft2font.so
      Reason: Incompatible library version: ft2font.so requires version 19.0.0 or later, but libfreetype.6.dylib provides version 18.0.0

**Comment by rayosborn** [comment] 2016-12-30 15:43
I should add that this is not a problem when downgrading to Matplotlib v1.5.3. If I then do an upgrade to v2.0.0rc2, I get a completely different error about the macosx backend not working because Python is not installed as a framework - but that will have to be another issue if this one is fixed.

**Comment by jenshnielsen** [comment] 2016-12-30 15:57
I don't know about the conda issue but the issue with framework builds is documented here http://matplotlib.org/devdocs/faq/osx_framework.html#osxframework-faq

**Comment by rayosborn** [comment] 2016-12-30 16:56
Thanks. I did come across this page, and did `conda install python.app` as a result, but that didn't seem to change the error, which is also not an issue with Matplotlib 1.5.3. I haven't checked this in enough detail to create an issue yet.

**Comment by jenshnielsen** [comment] 2016-12-30 17:07
You need to run the commands with pythonw after installing python.app. The default python executable is not a framework build and by apples design it cannot interact with Native OSX GUI windows correctly

**Comment by rayosborn** [comment] 2016-12-30 18:56
That's helpful. Thanks. There seem to be a number of errors concealed by other errors. Using `pythonw` does allow the macosx backend to work, so that issue is apparently solved. However, if I use `jupyter qtconsole` with matplotlib v2.0.0rc2, it tries to import from `matplotlib.backends._macosx` which triggers the framework error. I can get around it by adding mpl.use('Qt4Agg') to my jupyter startup file, but that wasn't necessary with older versions of matplotlib. 

This is getting off the topic of the original issue. I'm happy to post another issue on the backend topic. Now, back to using 2.0.0rc2+2843.g22708ef with `jupyter qtconsole`, I get a similar but subtly different error:

    >>> import matplotlib as mpl
    >>> mpl.use('Qt4Agg')
    >>> import matplotlib.pyplot as plt
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-eff513f636fd> in <module>()
    ----> 1 import matplotlib.pyplot as plt
    
    /Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/pyplot.py in <module>()
         27 from cycler import cycler
         28 import matplotlib
    ---> 29 import matplotlib.colorbar
         30 from matplotlib import style
         31 from matplotlib import _pylab_helpers, interactive
    
    /Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/colorbar.py in <module>()
         34 import matplotlib.collections as collections
         35 import matplotlib.colors as colors
    ---> 36 import matplotlib.contour as contour
         37 import matplotlib.cm as cm
         38 import matplotlib.gridspec as gridspec
    
    /Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/contour.py in <module>()
         21 import matplotlib.collections as mcoll
         22 import matplotlib.font_manager as font_manager
    ---> 23 import matplotlib.text as text
         24 import matplotlib.cbook as cbook
         25 import matplotlib.mlab as mlab
    
    /Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/text.py in <module>()
         31 from matplotlib.artist import allow_rasterization
         32 
    ---> 33 from matplotlib.backend_bases import RendererBase
         34 from matplotlib.textpath import TextPath
         35 
    
    /Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/backend_bases.py in <module>()
         62 
         63 import matplotlib.tight_bbox as tight_bbox
    ---> 64 import matplotlib.textpath as textpath
         65 from matplotlib.path import Path
         66 from matplotlib.cbook import mplDeprecation, warn_deprecated
    
    /Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/textpath.py in <module>()
         18 from matplotlib.ft2font import KERNING_DEFAULT, LOAD_NO_HINTING
         19 from matplotlib.ft2font import LOAD_TARGET_LIGHT
    ---> 20 from matplotlib.mathtext import MathTextParser
         21 import matplotlib.dviread as dviread
         22 from matplotlib.font_manager import FontProperties, get_font
    
    /Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/mathtext.py in <module>()
         56 
         57 import matplotlib.colors as mcolors
    ---> 58 import matplotlib._png as _png
         59 
         60 ####################
    
    ImportError: dlopen(/Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/_png.so, 2): Library not loaded: @rpath/libpng16.16.dylib
      Referenced from: /Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/_png.so
      Reason: Incompatible library version: _png.so requires version 43.0.0 or later, but libpng16.16.dylib provides version 30.0.0

I don't get this error with matplotlib 2.0.0rc2, so it's only in the latest development version.

**Comment by naoyak** [comment] 2017-01-19 06:35
@rayosborn if you're still experiencing this - have you tried `conda upgrade libpng`?

**Comment by rayosborn** [comment] 2017-01-19 15:42
That allowed me to update to libpng: 1.6.27-0, but I'm afraid that I still get the error:

    /Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/mathtext.py in <module>()
         56 
         57 import matplotlib.colors as mcolors
    ---> 58 import matplotlib._png as _png
         59 
         60 ####################
    
    ImportError: dlopen(/Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/_png.so, 2): Library not loaded: @rpath/libpng16.16.dylib
      Referenced from: /Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/_png.so
      Reason: Incompatible library version: _png.so requires version 44.0.0 or later, but libpng16.16.dylib provides version 30.0.0

In the comments to #7722, @tacaswell suggested that I should just create a new conda environment to run the development version. That did work.

**Comment by naoyak** [comment] 2017-01-19 17:24
@rayosborn oh right, I just remembered that you have to switch to the `conda-forge` channel to get the latest libpng=1.6.28 when installing mpl 2.0.0 final from conda. The main conda channel only seems to host up to 1.6.27.

**Comment by anntzer** [comment] 2019-10-18 10:24
The issue is quite old and matplotlib master does not depend on libpng anymore, so I'll close this, but feel free to ping for reopen with a recent-ish repro.

**Closed by anntzer** 2019-10-18 10:24 UTC
