### ISSUE TITLE
figsize() includes undocumented 0.3" buffer around plot area

### ISSUE THREAD

**Issue by geofurb** [matplotlib/matplotlib#20368] opened 2021-06-04 21:17 UTC
### Problem

When executing a command sequence such as  
```
width = 600
height = 600
dpi = 96
buffer = 0.3
f, ax = plt.subplots(1, figsize=(width/dpi+buffer,height/dpi+buffer), dpi=dpi, frameon=False, tight_layout=True)
# Code here to do your plotting
plt.savefig(fout, format='png', bbox_inches='tight', transparent="True", pad_inches=0)
```
to save the plot area of a matplotlib plot with the specified resolution (width x height), there is some undocumented behavior:
* The `buffer` added to the figure dimensions is necessary because the figsize argument for the subplot includes an undocumented 0.3" buffer between figures.
* The figsize() argument specifies the _maximal_ width and height, but if the plot `extent` or `xlim` and `ylim` does not use the entire space provided, the subfigure's size will be scaled down to fit the plot area instead of stretching the plot area to fit the subfigure. (This is a good behavior, but it is undocumented.)

This was tested for `3.4.2`, but it is not documented in either `3.4.2` or the `stable` version documentation.

Documentation for the version tested:
https://matplotlib.org/3.4.2/api/_as_gen/matplotlib.pyplot.subplots.html#matplotlib.pyplot.subplots
https://matplotlib.org/3.4.2/api/_as_gen/matplotlib.pyplot.figure.html#matplotlib.pyplot.figure

Current (stable) version documentation:
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplots.html#matplotlib.pyplot.subplots
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.figure.html#matplotlib.pyplot.figure

### Suggested Improvement

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 3.4.2
  * Matplotlib documentation version (is listed under the logo):

**Comment by tacaswell** [comment] 2021-06-04 22:05
This is the expected behavior, because you are passing `bbox_inches=tight` to `savefig` the figure size is effectively ignored when saving.  From https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html

> Bounding box in inches: only the given portion of the figure is saved. If 'tight', try to figure out the tight bbox of the figure.

The figure size only appears to be an upper bound because you are also using `tight_layout=True` which is trying to adjust everything to fit in the figure size before you save.  Without that (or constrained layout) `bbox_inches='tight'` can also increase the size of the figure.

I am not clear what you mean by the "buffer", The "Figure" in the whole space available (see https://matplotlib.org/stable/tutorials/introductory/usage.html#parts-of-a-figure).  

I think what you are referring to is the padding between the region that tight_layout fits the contents into and the Figure.  That can be controlled by passing a dict to `tight_layout` (see https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.figure.html#matplotlib-pyplot-figure) , following the link to https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.tight_layout.html#matplotlib.pyplot.tight_layout we see `pad` is the key we want to set.

I think the code you want is:

```python
import matplotlib.pyplot as plt
from io import BytesIO
import PIL

width = 600
height = 700
dpi = 96
f, ax = plt.subplots(
    1,
    figsize=(width / dpi , height / dpi ),
    dpi=dpi,
    frameon=False,
    tight_layout={"pad": 0},
)

fout = BytesIO()
plt.savefig(fout, format="png", transparent="True", pad_inches=0)
fout.seek(0)
im = PIL.Image.open(fout)
print(f'{im.width=}, {im.height=}')
```

@geofurb Can you please open a PR adjusting this documentation to have been clearer to you or can we close this issue?

**Comment by jklymak** [comment] 2021-06-04 22:40
The savefig method also has pad_inches, which defaults to 0.1.

**Comment by geofurb** [comment] 2021-06-05 16:04
The issue isn't that `bbox_inches=tight` takes off 0.3" from the figure's height and width, it's that there's no mention in `figsize()` that it will include a 0.3" buffer.

**Comment by jklymak** [comment] 2021-06-05 16:20
That's because the padding comes from tight_layout not savefig.   I don't think there are many situations where you need to call both tight_layout _and_ bbox_inches=tight.

**Closed** 2021-06-05 16:26 UTC
Labels: Documentation
