### ISSUE TITLE
Arrow in polar plot broken

### ISSUE THREAD

**Issue by michaelaye** [matplotlib/matplotlib#5344] opened 2015-10-29 01:05 UTC
It works fine only at angle 0, otherwise the arrow head is corrupted.
Using this code:

``` python
fig = plt.figure()
ax = fig.add_subplot(111, polar=True)
ax.arrow(0, 0, 3.14/2, 0.8, linewidth=3, width=0.005 )
ax.yaxis.set_ticklabels([])
ax.tick_params(axis='both', which='major', labelsize=20)
```

Here's how it looks:
![unknown](https://cloud.githubusercontent.com/assets/69774/10807562/ac2e4a70-7da6-11e5-949e-62f4d8f0c710.png)

At zero for 3rd parameter of above arrow call, it looks okay, but **only** there:
![unknown-1](https://cloud.githubusercontent.com/assets/69774/10807564/b1134c2a-7da6-11e5-81da-6af19a477e8b.png)

Version: master on OSX, in the notebook, seen both with `inline` and `nbagg` backend.

**Comment by mdboom** [comment] 2015-10-29 01:18
Good catch, and indeed a problem.  The fix may be tricky, however...

**Comment by QuLogic** [comment] 2015-10-29 07:36
I concur; `FancyArrow` essentially does "nudge a bit left/right" in data space to produce the arrow head. Unfortunately, on a polar plot, "a bit left/right" means a rotation. This is somewhat noted in the docstring with a possible workaround:

>The resulting arrow is affected by the axes aspect ratio and limits.
>This may produce an arrow whose head is not square with its stem. To
>create an arrow whose head is square with its stem, use
>:meth:`annotate` for example::
>```
>            ax.annotate("", xy=(0.5, 0.5), xytext=(0, 0),
>                arrowprops=dict(arrowstyle="->"))
>```

I can confirm that the `ax.annotate` method does work on polar plots, though I'm not sure whether it provides exactly the same styling options as `ax.arrow` would.

**Comment by QuLogic** [comment] 2015-10-29 07:44
Another workaround is to create the arrow at 0-angle, since you've found that it works, then provide a transform to the location you want:
```python
fig = plt.figure()
ax = fig.add_subplot(111, polar=True)
ax.arrow(0, 0, 0, 0.8, linewidth=3, width=0.005,
         # Remember that you're working in (theta,r) space before the data transform.
         transform=mtransforms.Affine2D().translate(np.pi/2, 0) + ax.transData)
ax.yaxis.set_ticklabels([])
ax.tick_params(axis='both', which='major', labelsize=20)
```
but this becomes a bit troublesome if you want to place it in an arbitrary location.

**Comment by michaelaye** [comment] 2015-10-29 13:04
Nice work-arounds, thanks! For me though, a new requirement propped up, in having to draw the arrow inside an ellipse instead of a circle, so I guess I will have to go to free-drawing both elements, and then I might as well do it in a normal plot and switch the axes off.

**Comment by pizzathief** [comment] 2015-10-31 04:22
If you replace the code in patches.py
```
                elif shape == 'full':
                    # The half-arrows contain the midpoint of the stem,
                    # which we can omit from the full arrow. Including it
                    # twice caused a problem with xpdf.
                    coords = np.concatenate([left_half_arrow[:-1], 
                                             right_half_arrow[-2::-1]])
                else:
                    raise ValueError("Got unknown shape: %s" % shape)
```

with 
```
                    coords = np.concatenate([left_half_arrow[:-2],
                                             right_half_arrow[-2::-1]])
```

Then the arrows have both left and right parts drawn fully, they're just pointing in the same wrong directions
![foo](https://cloud.githubusercontent.com/assets/2662541/10861826/24f39382-7fe3-11e5-9c7b-0cc4a29efbe9.png)

**Comment by michaelaye** [comment] 2015-10-31 06:05
The `wrongness` of the arrow heads are not the same for the different angles. It looks like the error on its directions is 45 degrees at 45 and ending up at 90 degrees after going a full turn of 360 degrees around the circle. How fascinating. There seems to be some kind of function on the problem. ;)

**Comment by pizzathief** [comment] 2015-11-01 00:09
Its not the list of points generated by ax.arrow() thats the root of the problem, I've tried a few of the lines, they seem to generate passable arrows (when I stick them in gnuplot and see what happens).  Must be just the polar plot itself thats rotating points too much.

**Comment by pizzathief** [comment] 2015-11-01 00:48
polartransform.transform_non_affine() is converting this:

![xy](https://cloud.githubusercontent.com/assets/2662541/10866669/7145d046-808e-11e5-8bb2-7c5af5312162.png)

into this:

![xy2](https://cloud.githubusercontent.com/assets/2662541/10866671/76612350-808e-11e5-9d82-a56714783476.png)

**Comment by QuLogic** [comment] 2015-11-01 02:03
Yes, that's expected. You are essentially plotting data-space and axes-space (modulo the affine part of the transform) as Cartesian, but they aren't really the same coordinate system. For a polar plot, the data space is (theta,r), so the first plot really shouldn't look anything like the "correct" arrow you see. An addition to the theta component (or "x" in the first plot) results in greater rotation of the arrow head, which is clearly evident in the second plot.

The problem with `arrow` is that it calculates the sides and tip of the arrow as offsets in data-space assuming it is Cartesian. That produces issues not only in polar plots, but probably any other non-standard projection, like anything from Cartopy or Basemap.

**Comment by mdboom** [comment] 2015-11-02 13:05
@QuLogic: I agree.  I think we need a new version of arrow that calculates the tip entirely in Cartesian regardless of the underlying projection (though it probably needs to get its orientation from the underlying projection).

**Comment by pizzathief** [comment] 2015-11-04 10:20
well, here's the patch to fix the arrowhead, if you want it. CR #5392

**Comment by afvincent** [comment] 2017-03-08 14:36
Just a status update.

Linux, Python 2.7, on master (`matplotlib.__version__` is "2.0.0.post3567+g1d45c08").

```python
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure(figsize=(6.4, 6.4))

for sub, lw, w in [(221, 3, 0.005), (222, 1, 0.005),
                   (223, 3, 0.05), (224, 1, 0.05)]:
    ax = fig.add_subplot(sub, polar=True)
    ax.set_yticklabels([])
    ax.set_title("linewidth={lw}, width={w}".format(lw=lw, w=w))

    for rad in np.pi*np.arange(0.0, 2.0, 0.25):
        ax.arrow(0, 0, rad, 0.8, linewidth=lw,  width=w)

plt.tight_layout()
```
produces
[current_state_on_master.pdf](https://github.com/matplotlib/matplotlib/files/827889/current_state_on_master.pdf):

* the directions of the arrow heads are still wrong, except for a null angle;
* the origins of the arrows are not exactly (0, 0). It is especially noticeable in the case of a small line width (see for example with linewidth=1 in the picture above).

**Comment by anntzer** [comment] 2021-06-29 08:39
I'm going to close this as "it's basically behaving as expected (for an arrow drawn fully in data space); you should anyways use Axes.annotate" (and see the arrow_guide.py example as well).
We could consider deprecating Axes.arrow, but that's tracked by https://github.com/matplotlib/matplotlib/issues/20387.

**Closed by anntzer** 2021-06-29 08:39 UTC
Labels: status: confirmed bug, topic: arrow, topic: polar
