### ISSUE TITLE
errorbar is too slow

### ISSUE THREAD

**Issue by ellot** [matplotlib/matplotlib#4373] opened 2015-04-23 07:53 UTC
I found when the data size is large, errorbar will take a very long time. 
I have tested by using the following script. Please save it as test.py and run 'kernprof -l -v test.py' in the terminal. 
With my Macbook, test1 costs 0.243914 seconds and test2 costs 40.8887 seconds. 
I am using use osx 10.10 and matplotlib 1.4.3. I have tried in Ferdora, which gives similar results.
Is there any way to speed up errorbar ?

```
from matplotlib import pyplot as plt
import time
import line_profiler
import numpy as np
@profile
def test1():
    x = np.arange(0,2*np.pi,0.0001)
    y = np.sin(x)
    fig = plt.figure(figsize=(12, 4))
    ax = fig.add_subplot(1, 1,  1)
    ax.plot(x,y)
    plt.savefig('test1.pdf')
    plt.close(fig)
@profile
def test2():
    x = np.arange(0,2*np.pi,0.0001)
    y = np.sin(x)
    fig = plt.figure(figsize=(12, 4))
    ax = fig.add_subplot(1, 1,  1)
    ax.errorbar(x,y,yerr=y)
    plt.savefig('test2.pdf')
    plt.close(fig)

test1()
test2() 
```

**Comment by jenshnielsen** [comment] 2015-04-23 08:35
The issue is that errorbar needs to draw a different marker for every single datapoint where plot can reuse the same marker. I don't think there is any easy fix for this. In general I don't see the use case for that many errorbars in one figure. 

For me your figure looks like this. No single errorbar can be separated from the rest. 

![download 1](https://cloud.githubusercontent.com/assets/548266/7293315/c09f1ad8-e99b-11e4-8978-700092f0e4ae.png)

You can use the errorevery kw argument to subsample the number of errorbars 

In this example i have used errorevery=2000 which gives useful errorbars and a performance on par with plot

![download](https://cloud.githubusercontent.com/assets/548266/7293298/962f24dc-e99b-11e4-9408-d7ccd241821d.png)

**Comment by ellot** [comment] 2015-04-23 08:54
Thank you for your replying. 
The script I posted is an example. In practice, I need to plot hundreds of figures, each of them includes thousands of data points with errorbars. 
So the only way is to reduce the number of errorbars, is that right ?

**Comment by jenshnielsen** [comment] 2015-04-23 09:03
Yes AFAIK thats the best solution. It is possible that something can be done to speedup the drawing of errorbars but I think it will always be slower than regular plot (and be more expensive to store in vector backends pdf etc. ) that is a result of the marker being different for every point.

**Comment by efiring** [comment] 2015-04-23 22:36
@ellot If you don't need fancy errorbar features, but you just want to display a range relative to a line, then using something like `ax.fill_between(x, y-y_err, y+y_err, color='b', alpha=0.2)` might be a good solution.  It's fast and can look very nice.

**Comment by efiring** [comment] 2015-04-23 22:50
I suspect errorbar actually could be sped up with a major re-write, but it would be quite a big job.  It is doing everything via the high-level `plot` method.  For a start, it could use a LineCollection for its lines. I don't know whether that would help with the pdf backend.

**Comment by tacaswell** [comment] 2020-08-11 21:07
I'm going to close this because the the underlying issue here is that the OP is trying to draw more errorbars than there are pixels in the rendered image.  While we could through a bunch of effort at speeding up that draw process, either reducing the number of error bars (via `markevery`) or switch to `fill_between` (or both) is a better path forward.

**Closed by tacaswell** 2020-08-11 21:07 UTC
Labels: Performance
