### ISSUE TITLE
Please clarify matplotlib-version in documentation and sample code!

### ISSUE THREAD

**Issue by michagrandel** [matplotlib/matplotlib#10854] opened 2018-03-21 11:50 UTC
### Bug report

There is no version information on the documentation pages.

### Details

If you google code samples of matplotlib, you will get links to different versions of the matplotlib documentation. On these documentation pages, there is no hint, *which version* of matplotlib you are looking at. Even the URL of the documentation doesn't give a clue! If you try some code (*official samples* from the *official documentation*!), you may wonder why it is not working in your installation of matplotlib. 

### Why this matters

Especially for beginners, this is very frustrating! You may try to figure out whats wrong for hours and post questions on stackoverlow, just to find out, that the matplotlib documentation doesn't care to show a clue which version you are looking at (as happened to me [examples/showcase/xkcd.py](https://matplotlib.org/examples/showcase/xkcd.html))!

**Comment by ImportanceOfBeingErnest** [comment] 2018-03-21 12:37
(User's [initial problem](https://stackoverflow.com/questions/49404704/matplotlibs-xkcd-not-working). Comment on [relevant last PR](https://github.com/matplotlib/matplotlib/pull/9603#issuecomment-374913081) on that topic. )

To collect some more examples of outdated pages: 
* Legend guide:
    * https://matplotlib.org/users/legend_guide.html  (outdated)
    * https://matplotlib.org/tutorials/intermediate/legend_guide.html (current version)

* Customizing:
    * https://matplotlib.org/users/customizing.html (outdated)
    * https://matplotlib.org/tutorials/introductory/customizing.html  (current version)

* The gallery:
    * https://matplotlib.org/gallery.html  (outdated)
    * https://matplotlib.org/gallery/index.html (current version)

**Comment by jklymak** [comment] 2018-03-21 13:37
I agree that the old pages should be removed or redirected somehow.   My understanding is that the issue with just erasing them is that old links die.  But I'm not sure thats worse than having obsolete pages lying around.  

FWIW, #10065 added the version to the header since 2.1.1.  If you don't see that version in the header, then you have an old version of the docs.  

ping @tacaswell who worked on this and sets the doc policy.

**Comment by tacaswell** [comment] 2018-03-21 14:46
Right, we do not want to just nuke them so they are replaced by 404 pages.  There is a 'cleanout.py' script in the docs repo that will replace orphaned pages with a re-direct to the main page, but that also in not great (https://github.com/matplotlib/matplotlib.github.com/blob/master/cleanout.py) 

I sunk some time into trying to automatically do the mapping that @ImportanceOfBeingErnest listed for a few cases above (see details below for code) but got stuck when the brute-force matching approach was going to take days.  You can also try approaching this by asking git what files have been moved (https://github.com/matplotlib/matplotlib/issues/8688 ) and then using that to sort out what the re-directs should be.  I suspect that the final answer is going to be to match up these two sources of data and to add as part of the deploy process running a cleanup script.

<details>

Sorry for the slightly odd extra comments and  indentation and the terrible function/variable names, this is just a brain-dump from my personal notes.

```python
# ** gather file meta-data
#+BEGIN_SRC python
  from pathlib import Path
  import hashlib
  import bs4
  from bs4 import BeautifulSoup
  import bs4.element
  import re
  # from dask.distributed import Client
  # client = Client()

  tld = Path('~/source/p/matplotlib.github.com').expanduser()



  def compute_file_data(fname, base,
                        title_re=re.compile('plotlib \([0-9.]+\) doc', re.IGNORECASE),
                        date_re=re.compile('last updated on ([A-Z]+ [0-9]+, [0-9]{4})', re.IGNORECASE),
                        path_ver_re=re.compile('^([12]\.[0-5]\.[0-3])')):
      hash_md5 = hashlib.md5()

      with open(fname, "rb") as f:
          for chunk in iter(lambda: f.read(4096), b""):
              hash_md5.update(chunk)
      html_date = html_ver = None

      path = fname.relative_to(base)
      path_ver_match = path_ver_re.search(str(path))
      if path_ver_match:
          path_ver = path_ver_match[1]
      else:
          path_ver = None

      if fname.suffix == '.html':
          with open(fname, "rb") as f:
              page = BeautifulSoup(f.read(), 'html.parser')
              title = page.head.title if page.head else None
              if title:
                  title_match = title_re.search(title.text)
                  if title_match:
                      html_ver = title_match[1]
              if page.body:
                  for f in page.body.find_all('div', {'class': 'footer'}):
                      date_match = date_re.search(f.text)
                      if date_match:
                          html_date = date_match[1]
                          break


      return {'fname': fname,
              'path': path,
              'rpath': path.relative_to(path_ver) if path_ver else path,
              'suffix': path.suffix,
              'md5': hash_md5.hexdigest(),
              'html_ver': html_ver,
              'html_date': html_date,
              'path_ver': path_ver,}


  def dask_walk_tree(tlp, client, base=None,
                     exclude_dirs=('xkcd',                                  # other versions of docs
                                   'cmocean', 'mpl-probscale', 'sampledoc'  # other projects docs we host
                                   ),
                     exclude_files=('CNAME', '.nojekyll',               # critical files for website to work
                                    'versions.html', 'downloads.html',  # static HTML
                                    'win32_static.tar.gz',              # legacy binary
                                    'win32_static_vs.tar.gz',           # legacy binary
                                    'cleanout.py',                      # helper script
                                    '.gitignore',                       # git stuff
                     )
                     ):
      ret = []
      if base is None:
          base = tlp
      excluded_files = set(exclude_files)
      for i in tlp.iterdir():
          if i.is_dir():
              if i.name.startswith(('.', ) + exclude_dirs):
                  continue
              ret.extend(dask_walk_tree(i, client, base=base))
          elif i.is_file():
              if i.name in exclude_files:
                  print(f'skpping {i}')
                  continue
              ret.append(client.submit(compute_file_data, i, base))
          else:
              print(f'should never be here, but here we are {i}')
      return ret

  files = client.gather(dask_walk_tree(tld, client))
  grouped_files = toolz.groupby('rpath', files)
  in_versions = {k: {_['path_ver'] for _ in v} for k, v in grouped_files.items()}
  # plt.hist([len(v) for v in in_versions.values()], bins=range(17))
  just_one_version = toolz.valfilter(lambda x: len(x) == 1, in_versions)

#+END_SRC

#+BEGIN_SRC python
  import cytoolz as toolz
  out_of_date = toolz.valfilter(lambda x: None in x and '2.1.1' not in x, in_versions)
  # keyed on type, values are list of (file, version_set) tuples
  ood_grouped_by_type = toolz.groupby(lambda x: x[0].suffix, out_of_date.items())
  ood_by_type = {k: dict(v) for k, v in ood_grouped_by_type.items()}
#+END_SRC

#+BEGIN_SRC python
  from difflib import SequenceMatcher
  import heapq

  def find_matches(tld, target_dir, source):
      with open(tld / source, 'r') as fin:
          a = fin.read()

      seq = SequenceMatcher(None, a, '')
      heap = [(-1, None)] * 5
      for target in tqdm.tqdm(list(target_dir.glob(f'**/*{source.suffix}'))):
          with open(target, 'r') as fin:
              b = fin.read()
          seq.set_seq2(b)
          # get a quick upper bound on match, if less than the smallest,
          # bail
          if seq.real_quick_ratio() < heap[0][0]:
              continue
          if seq.quick_ratio() < heap[0][0]:
              continue
          heapq.heappushpop(heap, (seq.ratio(), target))

      return (source, heap)



  def cleanup(futs):
      out = []
      for f in futs:
          if f.status == 'finished':
              out.append(f.result())
          else:
              f.cancel()
      return out
#+END_SRC

# *** helper to remove junk files

# only show up in top level and not white-listed

#+BEGIN_SRC python
  import subprocess

  for k in (k for k, v in just_one_version.items() if v[0] is None):
      if k.suffix == '.html':
          continue
      ret = input(f"remove file {k} ? ")
      if ret == 'y':
          subprocess.run(['git', 'rm', str(k)],
                         cwd=tld)
      elif ret == 'q':
          break
#+END_SRC

```
</details>

**Comment by ImportanceOfBeingErnest** [comment] 2018-03-21 14:52
My personal opinion:
1. The old pages should stay. 
2. They should tell search engines not to index them any more. 
3. And they should get a huge red warning banner with the link to the current version. 

Why?
1. If you delete them, 
    1. a massive amount of links all over the internet suddenly get broken. 
    2. Information is lost, old issues become isolated and non-reproducible. 

    If you directly redirect to the current version, you prevent i. from happening, but not ii.

2. If google still directs people to the old pages they become annoyed; any search should be directed to the current version.

3. This is to prevent users falling into traps as has happened in this case.

**Comment by tacaswell** [comment] 2018-03-21 15:02
There is still a copy of the old version under `matplotlib.org/X.X.X/FOO.html`.

When we update the docs the old versions of pages that we still make _do_ get forcibly updated so we have a lot of 1.ii no matter what.  This has always been the case, it is just particularly bad right now because the move to using sphinx gallery changed the URL of many of the pages.

**Comment by QuLogic** [comment] 2018-03-22 00:45
Closing as duplicate of #9556. We have too many of this same issue coming up...

**Closed by QuLogic** 2018-03-22 00:45 UTC
Labels: Documentation
