### ISSUE TITLE
Patch 3.1.1 broke imshow() heatmaps: Tiles cut off on y-axis

### ISSUE THREAD

**Issue by svdHero** [matplotlib/matplotlib#15179] opened 2019-09-04 06:06 UTC
### Bug report

**Bug summary**

Matplotlib patch 3.1.1 broke imshow() heatmaps. While with version 3.1.0 the heatmap was plotted correctly, in 3.1.1 the bottom most and the top most heatmap tiles are cut off.
This can even be seen in the Matplotlib online documentation itself, see links below.

**Code for reproduction**

Taken straight from the Matplotlib online documentation:
```python
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# sphinx_gallery_thumbnail_number = 2

vegetables = ["cucumber", "tomato", "lettuce", "asparagus",
              "potato", "wheat", "barley"]
farmers = ["Farmer Joe", "Upland Bros.", "Smith Gardening",
           "Agrifun", "Organiculture", "BioGoods Ltd.", "Cornylee Corp."]

harvest = np.array([[0.8, 2.4, 2.5, 3.9, 0.0, 4.0, 0.0],
                    [2.4, 0.0, 4.0, 1.0, 2.7, 0.0, 0.0],
                    [1.1, 2.4, 0.8, 4.3, 1.9, 4.4, 0.0],
                    [0.6, 0.0, 0.3, 0.0, 3.1, 0.0, 0.0],
                    [0.7, 1.7, 0.6, 2.6, 2.2, 6.2, 0.0],
                    [1.3, 1.2, 0.0, 0.0, 0.0, 3.2, 5.1],
                    [0.1, 2.0, 0.0, 1.4, 0.0, 1.9, 6.3]])


fig, ax = plt.subplots()
im = ax.imshow(harvest)

# We want to show all ticks...
ax.set_xticks(np.arange(len(farmers)))
ax.set_yticks(np.arange(len(vegetables)))
# ... and label them with the respective list entries
ax.set_xticklabels(farmers)
ax.set_yticklabels(vegetables)

# Rotate the tick labels and set their alignment.
plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
         rotation_mode="anchor")

# Loop over data dimensions and create text annotations.
for i in range(len(vegetables)):
    for j in range(len(farmers)):
        text = ax.text(j, i, harvest[i, j],
                       ha="center", va="center", color="w")

ax.set_title("Harvest of local farmers (in tons/year)")
fig.tight_layout()
plt.show()
```

**Actual outcome**

![heatmap_3-1-1](https://user-images.githubusercontent.com/24250824/64229597-84f79d00-ceea-11e9-99f1-0c14b4ec3603.png)
Copied from:
https://matplotlib.org/3.1.1/gallery/images_contours_and_fields/image_annotated_heatmap.html#sphx-glr-gallery-images-contours-and-fields-image-annotated-heatmap-py

**Expected outcome**

![heatmap_3-1-0](https://user-images.githubusercontent.com/24250824/64229624-917bf580-ceea-11e9-9810-c2b46bd27ad7.png)
Copied from:
https://matplotlib.org/3.1.0/gallery/images_contours_and_fields/image_annotated_heatmap.html#sphx-glr-gallery-images-contours-and-fields-image-annotated-heatmap-py

**Matplotlib version**

  * Operating system: Windows 8.1 and Ubuntu 18.04
  * Matplotlib version: 3.1.1
  * Matplotlib backend: Qt5Agg
  * Python version: 3.7.4 on Windows and 3.6.8 on Ubuntu

I am using conda on Windows and pip on Ubuntu.

**Comment by ImportanceOfBeingErnest** [comment] 2019-09-04 10:20
Thanks for the report. You can add

    ax.set_ylim(harvest.shape[0]-0.5, -0.5)

Unfortunately, this is necessary due to a bug (https://github.com/matplotlib/matplotlib/issues/14675) in version 3.1.1 of matplotlib . It will be fixed (https://github.com/matplotlib/matplotlib/pull/14677) in 3.1.2, which will be released very soon. So appart from the above you can also revert to matplotlib 3.1.0 for now, or use the development version.

Closing as duplicate of https://github.com/matplotlib/matplotlib/issues/14675

**Closed by ImportanceOfBeingErnest** 2019-09-04 10:20 UTC
