### ISSUE TITLE
imshow with pgf backend does not render transparency

### ISSUE THREAD

**Issue by owlas** [matplotlib/matplotlib#6278] opened 2016-04-07 10:00 UTC
Using python 3.5.1, matplotlib 1.5.1, OpenSuse 13.2

I am getting odd behaviour using imshow alpha with the pgf backend. The following code produces an image and a colorbar, the alpha matches with the agg backend.

```python
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
fg, ax = plt.subplots()
cb = ax.imshow([[0, 1], [0.5, 0.5]], alpha=0.5)
fg.colorbar(cb)
plt.savefig('pic.png')
```

![agg](https://cloud.githubusercontent.com/assets/11660098/14347579/bdef800c-fcaf-11e5-8c1d-fecf4061f0a9.png)

Using the `pgf` backend, I lose the alpha on the image but not the colorbar.

![pgf](https://cloud.githubusercontent.com/assets/11660098/14347598/dad2954c-fcaf-11e5-96c5-086d5a9afee6.png)

I want to write my plot as a `.pgf` file but that requires pngs for the colour bar and the image, so I lose alpha for my nice latex pgf files.

Has anybody else had this problem?

**Comment by mdboom** [comment] 2016-04-07 18:10
Cc: @pwuertz

**Comment by pwuertz** [comment] 2016-04-08 09:13
I can't reproduce this on my system. When I save a figure like the one produced from the example code above the PGF backend writes out two png-images for to the pgf code. Both of them with alpha transparency as expected. Also the compiled PDF and converted PNG from the pgf backend are looking good.

When saving pgf code, are the "pic-imgX.png" files ok on your system?

**Comment by pwuertz** [comment] 2016-04-26 15:35
Closing issue (not reproducible, no further information). Please reopen if there is anything new.

**Closed by pwuertz** 2016-04-26 15:35 UTC
Labels: backend/pgf
