### ISSUE TITLE
[Bug]: change marker color in legend for scatter plot

### ISSUE THREAD

**Issue by roberthilleck** [matplotlib/matplotlib#24437] opened 2022-11-12 14:26 UTC
### Bug summary

Creating a scatter plot with a legend and setting the color of the legend markers only changes the edgecolor of the markers.

### Code for reproduction

```python
markers = ["+", "s", "o", "*"]

fig, ax = plt.subplots(figsize=figsize)

for i, marker in enumerate(markers):
    data = np.random.randn(10, 3)
    x, y, z = np.split(data, 3, axis=1)
    ax.scatter(x, y, c=z, marker=marker, label=f"scatter {i}")

leg = ax.legend(loc="best")
for leg_handle in leg.legendHandles:
    leg_handle.set_color("k")
    # leg_handle.set_facecolor("k")
    # leg_handle.set_edgecolor("k")
```

### Actual outcome

set_color only changes the edgecolor of the marker instead of changing all colors.
set_facecolor has no effect.
set_edgecolor works as expected.

### Expected outcome

set_color should change all colors of the marker.
set_facecolor should change the face color of the marker.

### Operating system

Windows

### Matplotlib Version

3.5.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.10.4

### Jupyter version

6.4.12

### Installation

conda

**Comment by ksunden** [comment] 2022-11-12 22:06
Comes down to these lines:

https://github.com/matplotlib/matplotlib/blob/dc0328fb9c1c8817b07a5121a106a06be3571433/lib/matplotlib/collections.py#L850-L857

Essentially, because a color map is used, that is taking precedence at draw time.
It, in fact, _does_ set the color, and if you query it before it draws it will tell you it is black, but upon drawing this logic is run with `_original_facecolor="k"`

Which is to say, it is not equal to `"none"`, and thus the flag is set to use the cmap to set the facecolor.

Unfortunately this is not super trivial to fix without impacting desired behavior.

This is actually a duplicate of #13131 (that issue just strips out the details of it being a legend, which is not actually necessary to reproduce the error, though this case may indicate a situation where an explicit call to `changed` is not done by the user), so I'm going to close this to collapse the discussion to one place.

**Closed by ksunden** 2022-11-12 22:06 UTC
