### ISSUE TITLE
[Bug]: Configure subplots dialog freezes for TkAgg with toolmanager

### ISSUE THREAD

**Issue by StefRe** [matplotlib/matplotlib#22092] opened 2022-01-03 12:15 UTC
### Bug summary

When using the `toolmanager` toolbar with the Tk backend the "Configure subplots" dialog works at first but then freezes.

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.rcParams['toolbar'] = 'toolmanager'
plt.matplotlib.use('tkagg')

plt.plot((1,2))
plt.show()
```

### Actual outcome

Open the dialog and move some sliders - after a short while the dialog freezes.

### Expected outcome

Dialog should not freeze.

### Additional information

It works fine without the toolmanager.

### Operating system

Windows

### Matplotlib Version

3.5.1

### Matplotlib Backend

TkAgg

### Python version

3.8.2

### Jupyter version

-

### Installation

pip

**Comment by richardsheridan** [comment] 2022-01-11 17:02
I can confirm this bug and also it seems have been introduced between 3.3.4 and 3.4.0rc1.

**Comment by gtoombs-microsaas** [comment] 2022-02-16 01:15
Similar situation, different pathway: if you copy the [slider example](https://matplotlib.org/stable/gallery/widgets/slider_demo.html) but let both of the sliders go out of scope, the sliders will stop working.

If *either of the sliders* is kept in scope, both sliders will continue to function.

**Comment by QuLogic** [comment] 2022-02-16 04:07
That's unrelated; all widgets must be kept in scope to remain functional. It says so on every widget.

**Comment by QuLogic** [comment] 2022-05-05 08:15
It seems to be working for me; maybe fixed by one of your recent PRs, @richardsheridan? Or perhaps it is Windows only?

**Comment by richardsheridan** [comment] 2022-05-05 14:40
Looks like it was fixed by @anntzer in b896076 as part of #21992.  I don't think it's totally obvious why it was fixed, which presumably also makes the fix hard to backport to 3.5.x...  I recommend closing this issue unless someone has a solid plan to backport a patch.

**Comment by richardsheridan** [comment] 2022-05-05 15:54
For good measure I also bisected the bug introduction back to b9d9049 in #18226. Also not very helpful in proposing a backportable patch!

**Comment by QuLogic** [comment] 2022-05-05 20:26
Hmm, okay then, I think we can close this.

**Closed by QuLogic** 2022-05-05 20:26 UTC
Labels: status: confirmed bug, GUI/tk
