### ISSUE TITLE
Text bug

### ISSUE THREAD

**Issue by skostrichegg** [matplotlib/matplotlib#9182] opened 2017-09-13 02:01 UTC
### Bug report

**Bug summary**

When I run savefig() with some 3D collections and texts, some parts of texts are rarely rendered wrong position.
For example,
 - expected: ABC
 - actually rendered: AC         B

Have there been reported the same as above issue?

**Code for reproduction**

Unfortunately, I can't post my codes because of some reason.
But I can tell that there are about 5 plot_trisurf, 100 plot_surface, 40 texts.
And the font 'STIXGeneral' is used.
And I'm drawing with 2 processes.

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating System: CentOS
  * Matplotlib Version: 1.5.3 (installed by using pip)
  * Python Version: 3.5.2
  * Jupyter Version (if applicable):
  * Other Libraries:

**Comment by jklymak** [comment] 2017-09-13 02:18
Can you reproduce with something smaller?  Can you post a screenshot?

**Comment by skostrichegg** [comment] 2017-09-13 04:40
@jklymak  I can't post a screenshot or codes, I'm sorry for asking a question with lack of data..
But like I said, only texts have wrong position.

I'll try to reproduce with something smaller, but I think it's hard because this issue happens very rarely.
That's the reason why I asked there've been any similar issues(whether get solved or not) before.

Thanks,

**Comment by WeatherGod** [comment] 2017-09-13 18:27
When you say that the expected text is "ABC", you mean that that is a
single text object, or three separate text objects?

I haven't heard of anything this bad that would change the order of
characters. The occasional oddity with kerning or snapping, but nothing
this severe. I do notice that you said that you are generating plots with
two processes, and that this is a rare failure. That smells to me like a
race condition of some sort. We do have some font caches... perhaps there
is some sort of issue there? Could you describe your software design a
little bit more?

**Comment by skostrichegg** [comment] 2017-09-14 05:47
@WeatherGod  Thanks for response.
"ABC" I mentioned is a single text object.

Bellows are some information about my codes.
 - First of all, I generate a figure by matplotlib.figure.Figure()
 - And putting that figure in matplotlib.backends.backend_agg.FigureCanvasAgg
 - Using 'Cairo' backend.
 - Generating five plot_trisurf(), and each of them has about 10000 points
 - Generating 100 plot_surface()
 - Generating 40 text()
 - Saving PNG file by using savefig()
 - Reopening PNG file and saving it as JPEG (PIL.Image.open().save(..., 'JPEG')
 - Clearing figure by using clf(), and drawing again on this figure with same way.
   (The reason why I reuse a figure is that if I generate a new figure, although old one is closed, used memory isn't deallocated.)


I hope these'll help to you..

Thanks,

**Comment by tacaswell** [comment] 2017-09-16 17:41
Can you provide any code?  Your 2nd and 3rd points are, as I understand them, are contradictory.

Are you using latex or the internal mathtex renderer?

Why don't you save directly to jpeg?

**Comment by skostrichegg** [comment] 2017-09-18 10:26
@tacaswell  Sorry for late response.
Like you said, some mistakes in my codes.
I just changed my codes to use FigureCanvasCairo instead of FigureCanvasAgg and save to JPEG directly, not using PIL package.

Thanks for advice, but as I said, this issue has occurred so rarely.
So I'll be testing and monitoring the results consistently, after applying above modification.

Thanks!

**Comment by skostrichegg** [comment] 2017-09-18 11:07
@tacaswell  I missed something for you.
Although I save JPEG directly by using savefig('~.jpg'), its output is not 'JPEG', it is still 'PNG'.

import matplotlib
matplotlib.use('Cairo')

or using " from matplotlib.backends.backend_cairo import FigureCanvasCairo ".

And I installed cairocffi, Pillow.



This is the reason why I use re-open and save JPEG with PIL.
After that, the output file's format is 'JPEG'.

**Comment by skostrichegg** [comment] 2017-09-18 12:01
@tacaswell  I just check if I put the option "format='JPEG'" in savefig(), 'JPEG' image is generated successfully...

I'm sorry to confuse.

Like I said, I'll be monitoring this issue occur again.

**Comment by tacaswell** [comment] 2017-09-18 20:08
That it does not do the right with with jpg as the extension is worrying, however I can not reproduce this with (a few commits past) 2.1rc1.

**Comment by skostrichegg** [comment] 2017-09-20 08:47
@tacaswell  I just check that this issue is occurred again in spite of above modification.
Can multiprocessing for rendering be the reason for this issue?..
Belows are the part of my codes.
===============================================

from matplotlib import figure
from matplotlib import rc
from matplotlib.backends.backend_cairo import FigureCanvasCairo as FigureCanvas
from multiprocessing import Process

def renderer():
     h = figure.Figure()
     canvas = FigureCanvas(h)
     rc('font', family='STIXGeneral')

     for i in range(N):

          ... (generating something like text, 3d surface, etc...)

          h.savefig(~)
          h.clf()

def A():
     proc_a = Process(target=renderer)
     proc_a.daemon = True
     proc_a.start()
     
     renderer()

**Comment by tacaswell** [comment] 2017-09-22 03:37
Can you try with a newer version of mpl (at least 2.0 )?

**Comment by anntzer** [comment] 2017-10-16 07:40
Closing due to lack of reproducibility information.  Feel free to request a reopen if you can provide a minimal example that reproduces the issue.

**Closed by anntzer** 2017-10-16 07:40 UTC
Labels: needs clarification
