### ISSUE TITLE
No version when building from github archive

### ISSUE THREAD

**Issue by callegar** [matplotlib/matplotlib#8443] opened 2017-04-07 13:01 UTC
Hi, I do not know if this is addressable from matplot lib or is due to limitations in github, however, when building from the git head of the project it is impossible to get the matplotlib version, unless you clone the whole matplotlib history.

Sample case:

Assume that someone encounters a bug in the current matplotlib release and knows that the bug is fixed in the master development branch. The obvious thing for him/her is to go to github and get a zipfile of the master branch tip. However, if you build from there the matplotlib version gets set to 0+unknown+something, which is not helpful at all. In fact, if you use pip after that, pip will happily overwrite your home built matplotlib with the current release.

The issue is that the matplotlib sources do not seem to have any _version.py file with $Revision$ markers that the archive functionality of github can rewrite with a tag name (provided that github relies on the git archive functionality to make zip files). Hence, the Versioneer that is now used in matplotlib is unhappy.

I suggest the following:

1) If github does rewrite markers as git archive when creating zip files, assure that a _version.py file with the marker exists in the matplotlib sources. According to the versioneer documentation, this should be the case; Otherwise

2) Update the readme.md with instructions for building from a github downloaded zip snapshot, including a notice that the directory must be renamed to something containing a sensible version number so that the versioneer can get it from there.

**Comment by tacaswell** [comment] 2017-04-07 19:26
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/_version.py#L23 is where the formatting should be taking place, and it seems to work with the tarballs it creates off of tags.

This does get filled in as

```python
def get_keywords():
    # these strings will be replaced by git during git-archive.
    # setup.py/versioneer.py will grep for the variable names, so they must
    # each be defined on a line of their own. _version.py will just call
    # get_keywords().
    git_refnames = " (HEAD -> master)"
    git_full = "a95a2789ef64cd4b2535dff54a5c2452029f974c"
    keywords = {"refnames": git_refnames, "full": git_full}
    return keywords
```

The problem is that you only get local information so you can not tell how far past which tag you are so versioneer likely just throws up it's hands and gives you 'unknown' and 'HEAD' does not match our tag pattern.

Where do we point people towards download the zip?  If anything we should just tell people not to do it.

**Comment by callegar** [comment] 2017-04-07 23:03
Sorry for having got this wrong. I understand that, given the sole commit Id, it is impossible for versioneer to get a proper release version. Yet, I thought that the git archive was able to do some marker substitution in the spirit of `git describe` to provide some more complete info which evidently is not the case.

For what concerns your last question, this is basically where the matplotlib website says "if you [...] need the latest bugfixed version, grab the latest git version". Asking github for a zip file seems the most obvious thing to do since cloning the whole repo is above 400 MB.  On a slow ADSL or on 3G this takes ages and may drain the monthly data transfer allowance. Getting the zip seems to be fine as long as you provide instructions to manually provide a sensible version name before building.

**Comment by anntzer** [comment] 2017-04-07 23:46
Sadly, github does not use git-archive (https://github.com/isaacs/github/issues/554 or just google for it).

**Comment by anntzer** [comment] 2017-04-08 21:21
Closing as it is an upstream issue of either github or possibly versioneer (https://github.com/warner/python-versioneer/issues/140#issuecomment-292746426), but feel free to continue the discussion.

**Closed by anntzer** 2017-04-08 21:21 UTC

**Comment by tacaswell** [comment] 2017-04-09 00:46
Hmm, I had not realized how big our back-history of test images have gotten...

The tarball from releases are definitly from `git archive` (see http://matplotlib.org/devel/release_guide.html#id3 the SHAs match)  and it looks like that is what the zip files are.

`git clone https://github.com/matptlotlib/matplotlib --depth=1` will get you just the most recent commit, but still not enough to get tags.  You can use `git fetch --depth N` to progressively pull more and more commits until you get a tag.
