### ISSUE TITLE
Missing scale 

### ISSUE THREAD

**Issue by Volker-Weissmann** [matplotlib/matplotlib#12873] opened 2018-11-24 00:41 UTC
### Bug report

**Bug summary**

The scale on the y-axis is missing in some logarithmic plots.

**Code for reproduction**:

```python
import matplotlib.pyplot as plt

x = [1, 2]
y = [3.7, 3.8]

plt.plot(x,y)
plt.yscale("log")
plt.show()
```

**Actual outcome**

![abc](https://user-images.githubusercontent.com/39418860/48962990-92f6b580-ef89-11e8-8bd0-31d2314855c5.png)

**Expected outcome**

There should be a scale on the y-axis. Without the scale, you can't tell what the value of y is.

**Matplotlib version**

  * Operating system: Linux
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.5.2
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment] 2018-11-24 05:41
Thanks for reporting this - I think its a duplicate of #8768, and is being handled by #12865, so it should be fixed soon.  In the meantime, you can change the locator to `AutoLocator` for such a small dynamic range: https://matplotlib.org/examples/ticks_and_spines/tick-locators.html

**Comment by jklymak** [comment] 2018-11-24 05:41
I'm going to close, but feel free to comment at #12865 if you think your issue is different.

**Closed by jklymak** 2018-11-24 05:41 UTC
