### ISSUE TITLE
matplotlib window transparent to whatever is behind it

### ISSUE THREAD

**Issue by pavelkomarov** [matplotlib/matplotlib#13769] opened 2019-03-26 18:25 UTC
### Bug report

**Bug summary**

I'm on CentOS 7 running python 3.6.6, matplotlib version 3.0.3 installed via pip. In order to run matplotlib I had to `yum install python36-tkinter` (after updating the #! comments at the top of the yum scripts to make them still use python 2.7 and some further head scratching because this tkinter is for 3.6.6, but I was at the time running 3.6.4). I can now plot things, but my plots are a little transparent.

![image](https://user-images.githubusercontent.com/5639551/55022955-1ffe5980-4fd2-11e9-9a7d-65e769f0fce6.png)

If I drag the window over my terminal it looks even worse!

![image](https://user-images.githubusercontent.com/5639551/55023021-44f2cc80-4fd2-11e9-841e-215260c28ff7.png)

But I noticed dragging the window around, the degree of this effect changes, so I hypothesized it has to do with whatever is behind the window. Here it is against an orange background:

![image](https://user-images.githubusercontent.com/5639551/55023130-87b4a480-4fd2-11e9-8982-cb1f61e7b19c.png)

And finally, against black it looks right!

![image](https://user-images.githubusercontent.com/5639551/55023209-a9ae2700-4fd2-11e9-97ee-e5290e9111a3.png)

What could be going on here? Can I change my matplotlib settings to kill this transparency? Is matplotlib not using tkinter properly here? Or is this a tkinter bug?

**Comment by timhoffm** [comment] 2020-07-16 20:14
@pavelkomarov Is this still an issue?

**Comment by pavelkomarov** [comment] 2020-07-16 22:26
Oh, I don't know. I'm off that operating system not even at that company anymore.

**Comment by flabowski** [comment] 2020-09-28 08:12
I have exactly the same issue on red hat, Python 3.6, matplotlib 3.3.2
any suggestions @timhoffm ?

**Comment by jklymak** [comment] 2020-09-28 12:53
What is your backend and operating system?

**Comment by flabowski** [comment] 2020-09-29 08:40
My backend is also Tkinter and OS is Red Hat Enterprise Linux Server 7.8

**Comment by jklymak** [comment] 2020-10-02 14:42
@flabowski I'll re-open, but can't personally help you.  I somewhat suspect a tkinter  bug because its hard to see how this comes from matplotlib, but maybe someone else can reproduce.

**Comment by tacaswell** [comment] 2020-10-02 15:09
@flabowski what desktop manager are you using and do you have any transparency settings turned on?

Does this happen with any other tk applications (like gitk (which is my second favorite GUI application, but that is a side point) or IDLE)?

That the buttons are also showing the transparent effects makes me think that this is something at the window / toolkit / desktop level not at the Matplotlib level.

**Comment by flabowski** [comment] 2020-10-05 10:47
I am using windows' remote desktop connection and i don't have any transparent settings turned on. Only matplotlib windows seem to be affected, everything else seems to be fine. I didn't find anything like that but this post, therefore i added a comment..
![image](https://user-images.githubusercontent.com/18266347/95070368-4b561e80-0708-11eb-8c28-9d882705105f.png)
gitk seems to be just fine too.
![image](https://user-images.githubusercontent.com/18266347/95070734-d6cfaf80-0708-11eb-896f-9dd2aa08aa41.png)

**Comment by flabowski** [comment] 2020-10-19 08:53
Is anyone able to reproduce this? Is there anything else i can give you?

**Comment by jklymak** [comment] 2020-10-19 14:00
I don't have a comparable setup.  Have you tried using a different backend, like Qt?

**Comment by jklymak** [comment] 2021-04-15 16:39
I think 8.6 had known issues that were fixed upstream.  Closing here.

**Closed by jklymak** 2021-04-15 16:39 UTC
Labels: GUI/tk, status: needs clarification
