### ISSUE TITLE
Unable to draw lines except markers in real-time 

### ISSUE THREAD

**Issue by AbhayKoushik** [matplotlib/matplotlib#14436] opened 2019-06-03 23:48 UTC
### Bug report

**Bug summary**
While plotting real-time generated data using matplotlib, only markers get plotted and not lines.

**Code for reproduction**

```python
import random
import numpy as np
import time
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import matplotlib.dates as mdates

numbers=[]
numbersx=[]

myFmt = mdates.DateFormatter('%H:%M:%S')
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)

myFmt = mdates.DateFormatter('%H:%M:%S')

ax.xaxis.set_major_formatter(myFmt)

# Add labels
plt.title('Numbers Over Time')
plt.xlabel('Time - HH:MM:SS')
plt.ylabel('Numbers')

while True:
    numbers.extend([np.random.random()])
    
    for dates in range(len(numbers)):
        numbersx.extend([datetime.now()])
    ax.set_xlim([datetime.now()-timedelta(seconds=30), datetime.now()])
    plt.plot(numbersx[-1],numbers[-1],'r-')
    plt.pause(0.001)

```

**Actual outcome**

```
plt.plot() plots  
- empty running graph with 'r-'
- the scattered markers correctly with 'r.'   
- only markers and not lines with linestyle ='-' and markers ='.' 

```

**Expected outcome**
Real-time solid line connecting the marker points is expected to be plotted as the graph gets updated. i.e, plt.plot() should work neatly with 'r-'

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version:  3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.6
  
 pip install matplotlib

**Comment by WeatherGod** [comment] 2019-06-04 00:16
You are plotting one value at a time, so matplotlib doesn't know to connect
them. See this example on how to update a plot with more data:
https://matplotlib.org/gallery/animation/simple_anim.html#sphx-glr-gallery-animation-simple-anim-py

**Comment by tacaswell** [comment] 2019-06-04 03:27
I am going to close this because you are seeing expected behavior (multiple calls to `plt.plot()` produce independent lines).  In addition to `set_ydata` there is also a symmetric  `set_xdata` that you will need to use.

If you have more questions I suggest following up on the mailing list (https://mail.python.org/mailman/listinfo/matplotlib-users ) or gitter (https://gitter.im/matplotlib/matplotlib ).

Best of luck @AbhayKoushik !

**Closed by tacaswell** 2019-06-04 03:27 UTC
Labels: Community support

**Comment by AbhayKoushik** [comment] 2019-06-06 01:06
Yup, thanks for letting me know the internal dynamics @WeatherGod and @tacaswell. I found out a nice workaround without the need for animation feature.
