### ISSUE TITLE
matplotlib shows blank figures in jupyter when input() statement is following

### ISSUE THREAD

**Issue by AlexVaith** [matplotlib/matplotlib#18138] opened 2020-07-31 14:58 UTC
### Bug report

**Bug summary**
matplotlib shows blank figures in jupyter with %matplotlib notebook when an the python 'input()' function is following in the same cell. 

**Code for reproduction**

```python
THIS HAS TO RUN IN A CELL in a jupyter notebook

%matplotlib notebook
from matplotlib import pyplot as plt 
import numpy as np

plt.figure()
plt.plot(np.arange(0, 5, 0.1))
plt.show()

input('does this plot look alright')
```

**Actual outcome**
![image](https://user-images.githubusercontent.com/57894920/89047386-9fcacf80-d34e-11ea-91e9-2f6cc91da439.png)

**Expected outcome**
![image](https://user-images.githubusercontent.com/57894920/89047327-8de92c80-d34e-11ea-840a-b8be945a244d.png)

**Matplotlib version**

  * Operating system: mac OS Catalina
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.7
  * Jupyter version (if applicable): 7.1.6 (IPython)
  * Other libraries:

**Comment by tacaswell** [comment] 2020-07-31 15:24
This is unfortunately expected behavior.  In very short, in order for the plot to update the kernel needs to be idle to service requests from the front end to re-render the plot, but when you call `input` you are blocking the kernel so the draw requests never get serviced.  The reason this may work at the command line is that the `input` function can be integrated with the "input hook" (which is the code than is run while the computer waits for the slow humans to provide input) that runs the GUI event loop to process your input.

See https://matplotlib.org/users/interactive.html / https://matplotlib.org/users/interactive_guide.html for more details.

To understand if we can fix this we need to:

 - understand the event loop in the IPython kernel to understand where the requests are getting stalled
 - sort out if it is possible integrate our (custom) comms with `input` and the ipykernel loop

It may be worth trying ipympl (https://github.com/matplotlib/ipympl) which uses the ipywidget framework to do the communication and _may_ already be integrated.

The simplest work around may be to put the `input()` call in the next cell or to add `plt.gcf().canvas.draw()` above the `input` call.  This will still result in "dead" figures (which may not have caught up to the hi-dpi settings of your browser), but they will at least show.  If you pan / zoom on the frozen figure and then put something in the input you will see all of the backed up mouse events get processed which I think confirms the description of what is going wrong above.

**Comment by ianhi** [comment] 2020-10-12 03:13
> It may be worth trying ipympl (https://github.com/matplotlib/ipympl) which uses the ipywidget framework to do the communication and may already be integrated.

Sadly the same issue happens with ipympl
![delayed](https://user-images.githubusercontent.com/10111092/95701327-48cb5b80-0c17-11eb-90e0-24f8c71facc0.gif)

Also discussed a bit there https://github.com/matplotlib/ipympl/issues/258

**Comment by tacaswell** [comment] 2020-10-16 23:28
The fix to this has to be on the jupyter side.  I am going to close this as "can't fix" because there is nothing we can do on our side (the input box is blocking Python so we can not do any work to update the figure!).

**Closed by tacaswell** 2020-10-16 23:28 UTC

**Comment by guyben13** [comment] 2023-12-02 11:40
This is still an issue...

I understand there's nothing you can do to fix `input`, but what about creating a matplotlib function that does the input and also keeps the figures updated until the user finishes inputting?

Something like `comment = plt.input('looks good?')`

Is that something that might be possible?
