### ISSUE TITLE
plt.ion() call before plt.figure() call fails after a Windows 10 update.

### ISSUE THREAD

**Issue by stevievb** [matplotlib/matplotlib#11276] opened 2018-05-19 20:33 UTC
### Bug report

**Bug summary**

This was working until recently. Started failing all of the sudden after a Windows 10 update.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

plt.ion()
fig = plt.figure('test')
```

**Actual outcome**

```
Traceback (most recent call last):
  File "C:/###/Code/####/_test_matplitlib_bug.py", line 4, in <module>
    fig = plt.figure('test')
  File "C:\Anaconda3\envs\py27_sp\lib\site-packages\matplotlib\pyplot.py", line 557, in figure
    draw_if_interactive()
  File "C:\Users\#####\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\1##\helpers\pycharm_matplotlib_backend\backend_interagg.py", line 39, in draw_if_interactive
    figManager.canvas.show()
  File "C:\Users\#####\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\1##\helpers\pycharm_matplotlib_backend\backend_interagg.py", line 62, in show
    self.figure.tight_layout()
  File "C:\Anaconda3\envs\py27_sp\lib\site-packages\matplotlib\figure.py", line 1753, in tight_layout
    rect=rect)
  File "C:\Anaconda3\envs\py27_sp\lib\site-packages\matplotlib\tight_layout.py", line 326, in get_tight_layout_figure
    max_nrows = max(nrows_list)
ValueError: max() arg is an empty sequence
```

**Expected outcome**

It was working before a Windows 10 update. 

**Matplotlib version**

  * Operating system: Windows 10 Home (10.0.17134) Build 171 34
  * Matplotlib version: 2.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://backend_interagg
  * Python version: Python 2.7.13 :: Continuum Analytics, Inc.
  * Jupyter version (if applicable):
  * Other libraries: 

Installed with conda. Default channels.

**Comment by tacaswell** [comment] 2018-05-19 20:38
This is a duplicate of https://github.com/matplotlib/matplotlib/issues/8578 which was fixed in https://github.com/matplotlib/matplotlib/pull/8891 and released in mpl 2.1.

**Closed by tacaswell** 2018-05-19 20:38 UTC
