### ISSUE TITLE
inconsistent outputs for pdf and png using AnchoredText

### ISSUE THREAD

**Issue by jiadong93** [matplotlib/matplotlib#19676] opened 2021-03-10 07:04 UTC
### Bug report

**Bug summary**

Using savefig to pdf and png, outputs are different.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.offsetbox import AnchoredText

fig, ax = plt.subplots(1, 1, figsize=(3.2, 3.2))

ax.imshow(np.random.rand(100 ,100), cmap='Blues', vmin=-0.1, vmax=0.8)
at = AnchoredText("texts",
                  prop=dict(size=12), frameon=True,
                  loc='upper left',borderpad=0.05,
                  )
#at.patch.set_boxstyle("round, pad=0.,rounding_size=0.2")
at.patch.set_alpha(0.5)
at.patch.set_edgecolor([1, 1, 1, 0.5])
at.patch.set_linewidth(1)
ax.add_artist(at)

fig.savefig('test.pdf', dpi=300)
fig.savefig('test.png', dpi=300, transparent=False) 
```

**Actual outcome**

pdf:

![image](https://user-images.githubusercontent.com/15790176/110589554-8e358a00-81b1-11eb-9f02-8b78ead25127.png)

png:

![image](https://user-images.githubusercontent.com/15790176/110589579-9a214c00-81b1-11eb-9b43-cc2c73959740.png)

PNG output has extra lines around the text, which is undesired.

**Expected outcome**

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version:  3.7
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by timhoffm** [comment] 2021-03-10 21:18
I cannot reproduce this. The line is present in both cases, as one would expect because you set `at.patch.set_linewidth(1)`.

PDF / png
![grafik](https://user-images.githubusercontent.com/2836374/110698769-5d277a80-81ee-11eb-8b23-ea569cfa1adc.png)

**Comment by jklymak** [comment] 2021-03-10 22:41
I get the layering of the frame in png, and PDF when viewed in Preview on a Mac.  

Adobe Acrobat, however, does not composite the frame and its interior. This is easier to see if you use a wider frame and different color:

### Adobe:
<img width="448" alt="Adobe" src="https://user-images.githubusercontent.com/1562854/110707552-5416b900-81ae-11eb-8a2f-07910dd83b7f.png">

### Preview PDF:

<img width="448" alt="Preview" src="https://user-images.githubusercontent.com/1562854/110707624-698be300-81ae-11eb-8b9b-7f17aa6f4b80.png">

### PNG

<img width="708" alt="PNG" src="https://user-images.githubusercontent.com/1562854/110707692-832d2a80-81ae-11eb-8dac-5fb57229a02b.png">


I don't know that we can do anything here.  Either argument can be claimed "correct" - we choose one thing in Agg, Preview and Okular the same thing, Adobe chooses something different.

**Comment by QuLogic** [comment] 2021-03-11 01:14
That is likely #10035.

**Comment by timhoffm** [comment] 2021-03-13 23:12
I agree. I'm closing this as duplicate.

**Closed** 2021-03-13 23:13 UTC
Labels: status: duplicate
