### ISSUE TITLE
Missing facecolor2d attribute 

### ISSUE THREAD

**Issue by sarostru** [matplotlib/matplotlib#7495] opened 2016-11-21 17:43 UTC
I encountered a missing attribute bug while using matplotlib 1.5.3 on linux.  New to the community so apologies if this isn't the right way to raise the issue, I did read the [coding guidelines] (http://matplotlib.org/devel/coding_guide.html) but it was still unclear for small bugfixes what the procedure is.

I found I was getting a missing `_facecolor2d` attribute error in the Patch3D class in mplot3d/art3d.py.  It seems like the attribute just wasn't being set so I added it (diff below) and it resolved the problem.

There is a FIXME comment related to facecolor2d just below this point in the code, so someone may have had another fix in mind.

```patch
diff --git a/lib/mpl_toolkits/mplot3d/art3d.py b/lib/mpl_toolkits/mplot3d/art3d.py
index 4ecfb32..73daa6e 100644
--- a/lib/mpl_toolkits/mplot3d/art3d.py
+++ b/lib/mpl_toolkits/mplot3d/art3d.py
@@ -266,6 +266,7 @@ class Patch3D(Patch):
         self._segment3d = [juggle_axes(x, y, z, zdir) \
                 for ((x, y), z) in zip(verts, zs)]
         self._facecolor3d = Patch.get_facecolor(self)
+        self._facecolor2d = self._facecolor3d
 
     def get_path(self):
         return self._path2d
```

**Comment by dopplershift** [comment] 2016-11-21 18:49
Can you post a complete, minimal example that reproduces the problem?

**Comment by sarostru** [comment] 2016-11-21 19:12
Good call, so it was coming out of a mistake where a 3D figure got reused for a 2D plot and then we try to plot a legend.

I'm fine to close this without fixing, but if someone else has a legitimate use case for mixing 3D and 2D you could consider fixing this.

```
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(111, projection='3d')
ax.plot([0, 0, 0], [1, 2, 3], [3, 2, 1], zdir='z', label="some plot")
plt.bar(left=[1, 2, 3, 4], height=[5, 5, 1, 2], label="other thing")
plt.legend(loc="upper left")
plt.show()
```

**Comment by petehuang** [comment] 2017-01-03 14:24
Recommend closing - if someone does have that use case then we can obviously dig this back up

**Comment by WeatherGod** [comment] 2017-01-03 19:11
In a sense, this is a duplicate of #4067 (same error, but for a Poly3DCollection). There are some complications, and the given solution isn't exactly ideal because the value there isn't technically right. See the notes in that issue for more information.

**Closed by WeatherGod** 2017-01-03 19:11 UTC
Labels: mplot3d
