### ISSUE TITLE
[Bug]: _mathtext.py does not support new lines or amsmath matrix

### ISSUE THREAD

**Issue by testor2897** [matplotlib/matplotlib#27014] opened 2023-10-06 09:11 UTC
### Bug summary

The text:
title = r"$\left[\begin{matrix}a\\\\b\end{matrix}\right]$"
is not processed correctly by _mathtext.py

The error is shown below.

The same problem occurs trying to use "\\\\" within \left and \right

The code shows the direct try (matplotlib only) and an indirect try incl. Sympy. (commented lines)

I have found no way to make brackets for multiline texts or matrixes for matplotlib texts or titles.

There is no latex installed on the system.

### Code for reproduction

```python
#from sympy.printing import latex #sympy version
import matplotlib.pyplot as plt
#import sympy as sp #sympy version

fig, ax = plt.subplots(subplot_kw={'projection': '3d'})
ax = plt.gca()
ax.cla()
#a,b = sp.symbols('a, b') #sympy version
#f = sp.Matrix([a, b]) #sympy version
#title = f'${latex(f)}$' #sympy version
title = r"$\left[\begin{matrix}a\\b\end{matrix}\right]$"
##title = r"$\left[a\\b\right]$" # shortened version with newline only
plt.title(title)
plt.show()
```

### Actual outcome

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Python37\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\temp\venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 252, in idle_draw
    self.draw()
  File "C:\temp\venv\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 9, in draw
    super().draw()
  File "C:\temp\venv\lib\site-packages\matplotlib\backends\backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "C:\temp\venv\lib\site-packages\matplotlib\artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "C:\temp\venv\lib\site-packages\matplotlib\artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "C:\temp\venv\lib\site-packages\matplotlib\figure.py", line 2846, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\temp\venv\lib\site-packages\matplotlib\image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\temp\venv\lib\site-packages\matplotlib\artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "C:\temp\venv\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 473, in draw
    super().draw(renderer)
  File "C:\temp\venv\lib\site-packages\matplotlib\artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "C:\temp\venv\lib\site-packages\matplotlib\axes\_base.py", line 3055, in draw
    self._update_title_position(renderer)
  File "C:\temp\venv\lib\site-packages\matplotlib\axes\_base.py", line 3005, in _update_title_position
    if title.get_window_extent(renderer).ymin < top:
  File "C:\temp\venv\lib\site-packages\matplotlib\text.py", line 910, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "C:\temp\venv\lib\site-packages\matplotlib\text.py", line 318, in _get_layout
    clean_line, self._fontproperties, ismath=ismath)
  File "C:\temp\venv\lib\site-packages\matplotlib\backends\backend_agg.py", line 265, in get_text_width_height_descent
    self.mathtext_parser.parse(s, self.dpi, prop)
  File "C:\temp\venv\lib\site-packages\matplotlib\mathtext.py", line 435, in parse
    return self._parse_cached(s, dpi, prop, _force_standard_ps_fonts)
  File "C:\temp\venv\lib\site-packages\matplotlib\mathtext.py", line 456, in _parse_cached
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File "C:\temp\venv\lib\site-packages\matplotlib\_mathtext.py", line 2242, in parse
    str(err)])) from err
ValueError:
\left[\begin{matrix}a\\\\b\end{matrix}\right]
      ^
Expected main, found '\'  (at char 6), (line:1, col:7)

Error with shortened version of text,:
ValueError:
\left[a\\\\b\right]
       ^
Expected main, found '\'  (at char 7), (line:1, col:8)

### Expected outcome

The title shows a matrix [a b] or multiline text between brackets (shortened example).

### Additional information

Is there any kind of workaround (without latex)?

### Operating system

Windows 10

### Matplotlib Version

3.5.3

### Matplotlib Backend

TkAgg

### Python version

3.7.9

### Jupyter version

-

### Installation

pip

**Comment by oscargus** [comment] 2023-10-06 09:23
The problem is that math text does not support matrix nor `\\`.

**Comment by oscargus** [comment] 2023-10-06 14:35
SymPy relies on `amsmath` for its LaTeX rendering (`matrix' is an `amsmath`-environment). Checking the SymPy documentation it is not clear at all that it is automatically loaded, rather it says that one may have to load it manually. I am quite sure that `matrix` was one of the major reasons to automatically load it (and therefore require that it is installed).

[This](https://matplotlib.org/devdocs/users/explain/text/mathtext.html) is probably the most complete guide to what is supported in mathtext. So if it is in there, it should work with mathtext (without LaTeX). If it doesn't work it is a bug, if it is not in there, it is most likely not implemented.

**Comment by testor2897** [comment] 2023-10-10 11:28
Is it possible to use nested \genfrac constructs similar to
https://latex.org/forum/viewtopic.php?t=25155    ?

It looks like:
r'$A=\genfrac{}{}{0}{0}{\mathtt{\genfrac{}{}{0}{0}{\mathtt{\,3.3\;2.5}}{\mathtt{\,4\;3}}}}{\mathtt{\,4\;3}}$'

but equally sized (I don't now how to)?

**Comment by tacaswell** [comment] 2023-10-10 13:17
I am going to close this as "won't fix".  

Our internal mathtext support is intentionally limited (as supporting all of LaTeX would require re-implementing LaTeX and well out of scope) and we have the "use real LaTeX" as the escape hatch to handle cases where you need to do something that our simple parser does not support (or you want to match the fonts in your figures to your text exactly). 

-----

I changed the bug title to better reflect the reported problem.

-----

If you are willing to use conda, conda-forge has mktex built: https://anaconda.org/conda-forge/miktex

**Closed by tacaswell** 2023-10-10 13:17 UTC
Labels: topic: text/mathtext
