### ISSUE TITLE
support PySide6 & PyQt6

### ISSUE THREAD

**Issue by milos-korenciak** [matplotlib/matplotlib#19254] opened 2021-01-07 15:32 UTC
Please, add backends based on [PySide6](https://pypi.org/project/PySide6/) (successor of PySide2) and [PyQt6](https://pypi.org/project/PyQt6/) as the new Qt6 engine lives now.
Many thanks ;-).

**Comment by jklymak** [comment] 2021-01-07 15:39
This is a duplicate of #19226.  Thanks!

**Closed by jklymak** 2021-01-07 15:39 UTC
Labels: New feature
