### ISSUE TITLE
infinite range for hist(histtype="step")

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5221] opened 2015-10-11 03:07 UTC
```python
In [1]: plt.hist(np.arange(10), range=(0, np.inf))
# empty plot
Out[1]: 
(array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]),
 array([ nan,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf]),
 <a list of 10 Patch objects>)

In [2]: plt.hist(np.arange(10), range=(0, np.inf), histtype="step")
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-2-1921805d8f19> in <module>()
----> 1 plt.hist(np.arange(10), range=(0, np.inf), histtype="step")

/usr/lib/python3.5/site-packages/matplotlib/pyplot.py in hist(x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, hold, **kwargs)
   2894                       histtype=histtype, align=align, orientation=orientation,
   2895                       rwidth=rwidth, log=log, color=color, label=label,
-> 2896                       stacked=stacked, **kwargs)
   2897         draw_if_interactive()
   2898     finally:

/usr/lib/python3.5/site-packages/matplotlib/axes/_axes.py in hist(self, x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, **kwargs)
   5872                         ymin = np.amin(m[m != 0])
   5873                         # filter out the 0 height bins
-> 5874                 ymin = max(ymin*0.9, minimum)
   5875                 ymin = min(ymin0, ymin)
   5876                 self.dataLim.intervaly = (ymin, ymax)

UnboundLocalError: local variable 'ymin' referenced before assignment
```
Obviously there's isn't much to do here other than improving the error reporting in the second case.

**Comment by lzkelley** [comment] 2015-11-02 18:20
Should the first case raise an error as-well?  i.e. perhaps `hist` should assert that the range is finite.

**Comment by anntzer** [comment] 2015-11-02 20:57
I think it should.

**Comment by tacaswell** [comment] 2015-11-02 22:28
This should go as a bug against numpy.  We delegate all of the histogram computation to them, we should not maintain significant validation on top of that.

**Comment by anntzer** [comment] 2015-11-02 23:28
Actually this behavior has changed recently, probably with numpy 1.10 & matplotlib 1.5: now neither command raises an error, and both give an empty plot.

**Comment by lzkelley** [comment] 2015-11-03 14:41
I've brought this up in the numpy-discussion mailing list.  Should we close this issue and punt it to them?

**Comment by tacaswell** [comment] 2015-11-04 01:46
Yes, closing this here.  Please ping to have re-opened if discussions with numpy go very badly.  If you end up creating an issue/PR over at numpy can you please also link to this issue?

**Closed** 2015-11-04 01:46 UTC
Labels: Difficulty: Easy, low hanging fruit

**Comment by heroxbd** [comment] 2016-04-15 01:47
@lzkelley Could you please provide a reference to the topic at numpy-discussion mailing list?

**Comment by lzkelley** [comment] 2016-04-15 01:53
Sure, the [this is the topic which I opened (no replies).](https://mail.scipy.org/pipermail/numpy-discussion/2015-November/074161.html)  And [this is the PR I put in to numpy (which was merged)](https://github.com/numpy/numpy/pull/6690).

**Comment by heroxbd** [comment] 2016-04-15 01:53
I do think it is a bug of matplotlib.
My system is with python-2.7.10, numpy-1.10.4 and matplotlib-1.5.1.

`from matplotlib import pylab as plt`
`plt.hist([1,3], range(1,2)) # success`
`plt.hist([1,3], range(1,3), histtype="step") # success`
`plt.hist([1,3], range(1,2), histtype="step") # exception`

> UnboundLocalError                         Traceback (most recent call last)
> <ipython-input-6-73c33d0106be> in <module>()
> ----> 1 plt.hist([1,3], range(1,2), histtype="step")
> 
> /disk/usr100/gentoo/usr/lib64/python2.7/site-packages/matplotlib/pyplot.pyc in hist(x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, hold, data, **kwargs)
>    2956                       histtype=histtype, align=align, orientation=orientation,
>    2957                       rwidth=rwidth, log=log, color=color, label=label,
> -> 2958                       stacked=stacked, data=data, **kwargs)
>    2959     finally:
>    2960         ax.hold(washold)
> 
> /disk/usr100/gentoo/usr/lib64/python2.7/site-packages/matplotlib/__init__.pyc in inner(ax, *args, **kwargs)
>    1810                     warnings.warn(msg % (label_namer, func.__name__),
>    1811                                   RuntimeWarning, stacklevel=2)
> -> 1812             return func(ax, *args, **kwargs)
>    1813         pre_doc = inner.__doc__
>    1814         if pre_doc is None:
> 
> /disk/usr100/gentoo/usr/lib64/python2.7/site-packages/matplotlib/axes/_axes.pyc in hist(self, x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, **kwargs)
>    6207                         ymin = np.amin(m[m != 0])
>    6208                         # filter out the 0 height bins
> -> 6209                 ymin = max(ymin*0.9, minimum) if not input_empty else minimum
>    6210                 ymin = min(ymin0, ymin)
>    6211                 self.dataLim.intervaly = (ymin, ymax)
> 
> UnboundLocalError: local variable 'ymin' referenced before assignment
>

**Comment by heroxbd** [comment] 2016-04-15 01:55
Thanks @lzkelley. This bug is not caused by infinite numbers, but histogram input failing outside of the specified range.

**Comment by lzkelley** [comment] 2016-04-15 01:57
@heroxbd I see - yeah, this looks like a slightly different issue - but hopefully a similar fix.  That is really strange: I see that `plt.hist([1,3], 1, histtype="step")` works fine....
