### ISSUE TITLE
When I run a file that uses matplolib animation, I keep getting this error. Using OS X, Python 2.7, installed Python from python.org then used homebrew. Matplotlib install from pip. 

### ISSUE THREAD

**Issue by TariniHardikar** [matplotlib/matplotlib#6348] opened 2016-04-29 07:02 UTC
To help us understand and resolve your issue please check that you have provided
the information below.

- [ ] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
- [ ] How did you install Matplotlib and Python (pip, anaconda, from source ...)
- [ ] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
      that demonstrates the issue i.e a small piece of code which reproduces the issue
      and can be run with out any other (or as few as possible) external dependencies.
- [ ] If this is an image generation bug attach a screenshot demonstrating the issue.
- [ ] If this is a regression (Used to work in an earlier version of Matplotlib), please 
      note where it used to work.

```pytb
Error:
Traceback (most recent call last):
  File "HOstates.py", line 20, in <module>
    import matplotlib.animation as animation
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/animation.py", line 365, in <module>
    class FFMpegWriter(MovieWriter, FFMpegBase):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/animation.py", line 49, in wrapper
    if writerClass.isAvailable():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/animation.py", line 239, in isAvailable
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 972, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```

**Comment by tacaswell** [comment] 2016-04-29 12:28
Also see

https://github.com/matplotlib/matplotlib/issues/5386
https://github.com/matplotlib/matplotlib/issues/5314

Can you please provide a minimal example which causes thes error?

**Comment by tacaswell** [comment] 2016-04-29 12:30
It also looks like this is a python2 only bug, if you can switch to python3

**Comment by TariniHardikar** [comment] 2016-04-29 17:41
import numpy as np
import matplotlib        ##To get blit working
matplotlib.use('TkAgg')  ##
from matplotlib import pyplot as pl
from matplotlib import animation

I'm not sure why, but there is some error with matplotlib animation. Everything else works fine. Is it a version issue?

**Comment by QuLogic** [comment] 2016-10-22 07:49
This is a dupe of the two bugs @tacaswell noted above.

2.0 will require `subprocess32` to work around this bug (see #6576.)

**Closed by QuLogic** 2016-10-22 07:49 UTC
Labels: OS/Apple
