### ISSUE TITLE
Crazy random colors when saving an image

### ISSUE THREAD

**Issue by Tylersuard** [matplotlib/matplotlib#20371] opened 2021-06-05 18:45 UTC
### Bug report

**Bug summary**

When I create a matplotlib plot, it looks fine when I display it as inline in my notebook.  However, when I save the figure, I get crazy random colors, instead of just the one color that I want.

**Code for reproduction**

plot_save_string = str('/home/ubuntu/400/results/'+ str(item)+ ".png")
print(plot_save_string)
plt.savefig(plot_save_string,bbox_inches='tight',pad_inches = 0)
g = sns.lineplot(x="Datetime", y="Amount", data=shabizzo)

**Actual outcome**
![crazy graph](https://user-images.githubusercontent.com/41713505/120902138-8f7d2400-c5f3-11eb-84a6-8f5eec662de3.png)

**Expected outcome**

![normal graph](https://user-images.githubusercontent.com/41713505/120902121-6f4d6500-c5f3-11eb-8730-3fb822df07a7.png)

**Matplotlib version**

  * Operating system: Linux

**Comment by jklymak** [comment] 2021-06-05 18:47
We don't supply sns.linepkot.  Also this is not reproducible so it's very hard to tell what the issue may be.

**Comment by anntzer** [comment] 2021-07-04 13:08
Closing due to lack of reproducible example.  Feel free to ping for reopen with more info.

**Closed by anntzer** 2021-07-04 13:08 UTC
Labels: status: needs clarification
