### ISSUE TITLE
Wicks are drawn above the candlestick body and they should only be visible outside the body.

### ISSUE THREAD

**Issue by gonzsanc** [matplotlib/matplotlib#13809] opened 2019-03-30 19:46 UTC
The 2D lines of each japanese candlestick of the candlestick_ohlc are drawn upon the box.

This means, if a user wants to use a different color for the line, then the line is drawn on the box while it should be below.

For instance, if I get my lines in the ls variable:
ls, rs = candlestick_ohlc(ax1, ohlc_data, width = 0.4/len(ohlc_data), colorup = 'green', colordown = 'red', alpha = 1)

and foreach l in ls I change the color of the l, I would not only see the wicks of the candle but also a line along the midel of all the candle body, while I should only see the body without the line in the middle and then the wicks.

The attached image shows how a candlestick with a black wick should look like. If you try to do it with the chandlestick_ohlc function, it won't work.
  
![image](https://user-images.githubusercontent.com/11660576/55280933-c5942e80-532c-11e9-9c35-679689f0babf.png)

**Comment by dstansby** [comment] 2019-03-30 20:48
Could you post some simple, self-contnaied example code? That way it will be much easier to see what the problem is.

**Comment by ImportanceOfBeingErnest** [comment] 2019-03-31 02:28
The [`mpl_finance` module](https://github.com/matplotlib/mpl_finance) is no longer part of matplotlib itself and currently not actively maintained. You find the source code in the link and you are free to edit it to your desire. 

If you want to have the lines behind the boxes you can either move the boxes to the front or the lines to the back. The latter could look like

    plt.setp(ls, color="blue", zorder=0)

**Comment by gonzsanc** [comment] 2019-03-31 11:23
Thank you!!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ImportanceOfBeingErnest** [comment] 2019-03-31 11:44
You're welcome. I'm closing this, since there isn't really anything to be done here. 

Note that if you feel strongly about this being a bug and have some evidence from literature that those lines need to be behind the boxes, you can open an issue at the https://github.com/matplotlib/mpl_finance issue tracker, such that if and when someone decides to continue maintainance of that repository, they have something to work on.

**Closed by ImportanceOfBeingErnest** 2019-03-31 11:44 UTC
