### ISSUE TITLE
dynamic ticking (#5588) should avoid (if possible) single ticks

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5784] opened 2016-01-02 08:50 UTC
There's only one xtick left in `statistics/violinplot_demo.py` after #5588 got merged:
![violinplot](https://cloud.githubusercontent.com/assets/1322974/12073888/4eed85de-b0ea-11e5-9b9c-44b8ac686574.png)
Compare with before the patch:
![violinplot_old](https://cloud.githubusercontent.com/assets/1322974/12073891/878eab66-b0ea-11e5-84b1-b4dcc4956f63.png)
The old xticks were perhaps a bit cramped but there's clearly room for, say, two more xticks in the new output.
(On the other hand, this helped me catch a bug in offset text calculation logic when there's a single tick, so it's not all that bad...)

**Comment by tacaswell** [comment] 2016-01-02 19:16
This also starts to touch on the need for categorical axis support.

**Comment by tacaswell** [comment] 2016-01-03 21:46
I think this is also partially addressed by #5772

**Comment by tacaswell** [comment] 2016-05-23 19:42
This is still a problem 

http://matplotlib.org/devdocs/examples/statistics/violinplot_demo.html

![image](https://cloud.githubusercontent.com/assets/199813/15482329/ff700404-20fc-11e6-99d2-c0eb8dbe0b85.png)

**Comment by efiring** [comment] 2016-05-28 18:16
I think that improving this without practically defeating the 'auto' functionality requires a combination of setting a lower bound for the upper bound value, as in #6470, combined with letting the Locator switch to a larger set of "nice" intervals from which to choose.  The larger the set of intervals, the easier it is to fit in a target number of ticks.  The problem is that unless this larger set is exposed as yet another kwarg and rcParam, it will lead to surprises--the Locator will do something other than what the user thought she told it to do, with no way to override that behavior.  In other words, it adds another layer of complexity.

**Comment by efiring** [comment] 2016-06-15 00:56
With #6584: 
![violinplot_demo](https://cloud.githubusercontent.com/assets/85125/16064801/0261ec5a-3240-11e6-97b4-df5dfafd5e6b.png)

**Closed** 2016-06-15 21:01 UTC
Labels: default changes
