### ISSUE TITLE
[Bug]: Annotation position is not update correctly

### ISSUE THREAD

**Issue by Davide-sd** [matplotlib/matplotlib#26178] opened 2023-06-23 21:03 UTC
### Bug summary

I'm trying to create annotations which will eventually get their position updated.

However, I'm not sure if I'm doing it wrong or if there is some bug, because when I update the position of the annotation, it doesn't respect the original intent.

### Code for reproduction

```python
%matplotlib widget
import ipywidgets as ipy
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
img = 0.75 * np.ones((50, 50))
ax.imshow(img, extent=(-2, 2, -2, 2), cmap="gray", vmin=0, vmax=1)
point, = ax.plot([0], [0], linestyle="none", marker="o")
text = ax.annotate(
    text="A", xy=(0, 0),
    xytext=(15, 0),
    textcoords="offset pixels"
)
ax.set_xlim(-3, 3)
ax.set_ylim(-3, 3)

sx = ipy.FloatSlider(0, min=-2, max=2)
sy = ipy.FloatSlider(0, min=-2, max=2)

@ipy.interact(x=sx, y=sy)
def update(x, y):
    point.set_data([x], [y])
    text.set_position((x, y))
```

### Actual outcome

The above code block has been executed on a Jupyter Notebook.

Let's comment the code about ipywidgets and the update function. The resulting plot is:

![image](https://github.com/matplotlib/matplotlib/assets/9921777/1ecd251f-f954-4d58-bdb6-81259bbcb28a)

Note that there is an offset between the annotation point and the annotation text.

Now, let' use ipywidgets and the update function:

![image](https://github.com/matplotlib/matplotlib/assets/9921777/168a2e63-439e-4332-874c-e74141174d6d)

All of a sudden, the offset is gone. Morover, by moving the slider we can see the blue dot get the correct position, whereas the annotation does not.

![image](https://github.com/matplotlib/matplotlib/assets/9921777/47a54548-e06f-4814-bf3a-3d6b893a2f65)

### Expected outcome

I would expect the annotation to correctly update its position.

### Additional information

ipywidgets version: 8.0.4

### Operating system

Ubuntu 22.04

### Matplotlib Version

3.7.1

### Python version

3.10.6

### Jupyter version

6.5.2

### Installation

pip

**Comment by rcomer** [comment] 2023-06-24 12:30
We can reproduce this in a script without the interactive stuff by

```python
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
img = 0.75 * np.ones((50, 50))
ax.imshow(img, extent=(-2, 2, -2, 2), cmap="gray", vmin=0, vmax=1)
point, = ax.plot([0], [0], linestyle="none", marker="o")
text = ax.annotate(
    text="A", xy=(0, 0),
    xytext=(15, 0),
    textcoords="offset pixels"
)
ax.set_xlim(-3, 3)
ax.set_ylim(-3, 3)

point.set_data([1], [1])
text.set_position((1, 1))

plt.show()
```
![image](https://github.com/matplotlib/matplotlib/assets/10599679/192a57b4-890e-47aa-ae6c-7640996659ec)

The `Annotation` object returned by `annotate` inherits from the `Text` object, and that is where the `set_position` method comes from.  I think when you call `set_position` you are updating what you originally set as `xytext`.  `Annotation` does have `xy` as a public attribute though so if we replace the `set_position` line with simply
```python
text.xy = (1, 1)
```
we get
![image](https://github.com/matplotlib/matplotlib/assets/10599679/c2466942-a475-4da7-9490-2d0dcd5ec29e)

**Comment by rcomer** [comment] 2023-06-24 12:41
I do not think it’s a bug in Matplotlib.   Since the attribute is described at https://matplotlib.org/stable/api/text_api.html#matplotlib.text.Annotation, I do not think this is a documentation issue either.  So I'm going to close this, but please do comment if you think there is more we should have done here.  You are also welcome to open a question over at https://discourse.matplotlib.org/ (which is more for usage questions) if you need more help.

**Closed by rcomer** 2023-06-24 12:41 UTC
