### ISSUE TITLE
[Bug]: Animation changing the azimuth only of scatter plot requires mouse click to draw

### ISSUE THREAD

**Issue by dani0805** [matplotlib/matplotlib#22598] opened 2022-03-04 07:44 UTC
### Bug summary

When animating a scatter changing only the azimuth the plot will not be updated unless the mouse is clicked on the plot. 
Might be platform specific on a apple silicon version 3.5.1

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

data = [np.random.random_sample((300, 3)) for _ in range(10)]
x, y, z = data[0][:, 0], data[0][:, 1], data[0][:, 2]


def update_pov(num):
    ax.view_init(elev=10., azim=num % 360)
    
    return graph,


fig = plt.figure(figsize=(5, 5))
ax = fig.add_subplot(111, projection="3d")
graph = ax.scatter(x, y, z, color='orange')

ax.set_xlim3d(0, 1)
ax.set_ylim3d(0, 1)
ax.set_zlim3d(0, 1)

ani = animation.FuncAnimation(fig, update_pov, frames=200, interval=50, blit=False)
plt.show()
```

### Actual outcome

https://youtu.be/3l7gMHrwkqQ
in the video it is only animating when I click on the mousepad

### Expected outcome

animations should flow independently of mouse clicks

### Operating system

MacOS on Apple silicon

### Matplotlib Version

3.5.1

### Matplotlib Backend

MacOSX

### Python version

Python 3.9.2

### Installation

pip

**Comment by greglucas** [comment] 2022-03-04 14:39
I'm going to close this as a duplicate of #10980, as it is demonstrating the same issue of not updating automatically.

#21790 fixes both of these issues for macosx, although I'm not able to test on Apple Silicon.

**Closed by greglucas** 2022-03-04 14:39 UTC
Labels: topic: animation, topic: pyplot API
