### ISSUE TITLE
[Bug]: The behaviour of Figure.colorbar has changed between versions 3.4.2 and 3.5.0.

### ISSUE THREAD

**Issue by sachabaclet** [matplotlib/matplotlib#26471] opened 2023-08-08 13:34 UTC
### Bug summary

Using the exact same code, the behaviour of fig.colorbar has changed unexpectedly between versions 3.4.2 and 3.5.0 of matplotlib when using two-sloped norms:
- in version 3.4.2, the colorbar uses evenly-spaced ticks,
- in version 3.5.0, the middle of the colorbar is the value set as vcenter in matplotlib.colors.TwoSlopeNorm, and the ticks are not evenly spaced anymore. This behaviour remains the same in later versions (tested with 3.7.2).

### Code for reproduction

```python
import matplotlib.pyplot as plt
import matplotlib.colors as clrs
from matplotlib import cm
import numpy as np

def plot_matrix(data, norm, cmap="magma"):
	fig, ax = plt.subplots(1, 1)
	plt.imshow(data, norm=norm, cmap=cmap)
	c = fig.colorbar(cm.ScalarMappable(norm=norm, cmap=cmap), ax=ax)
	plt.axis('off')
	plt.title("title")
	plt.show()

data = np.random.randint(low=-5, high=15+1, size=(10,10))
norm = clrs.TwoSlopeNorm(vmin=-5, vmax=15, vcenter=0)

plot_matrix(
	data=data,
	norm=norm,
	cmap="coolwarm")
```

### Actual outcome

![3 4 2](https://github.com/matplotlib/matplotlib/assets/22750207/9068152f-041d-43f5-a147-983589d6c7a3)
![3 5 0](https://github.com/matplotlib/matplotlib/assets/22750207/ea59e4c5-878f-416e-be7e-5f047d36d2cd)

### Expected outcome

The expected output is the figure obtained using matplotlib version 3.4.2.

### Operating system

Windows 10

### Matplotlib Version

3.4.2/3.5.0

### Matplotlib Backend

TkAgg

### Python version

3.8.10

### Installation

pip

**Comment by jklymak** [comment] 2023-08-08 14:27
This is a duplicate of #23040 and was a purposeful change.

**Closed** 2023-08-08 14:28 UTC
Labels: status: duplicate, topic: color/colorbar

**Comment by sachabaclet** [comment] 2023-08-08 20:55
Hi! Sorry for the duplicate, thank you for your answer.

Is there any way of obtaining the pre-3.5.0 behaviour (as seen on the images) using a newer version of matplotlib?

**Comment by ksunden** [comment] 2023-08-08 21:13
Adding `c.ax.set_yscale("linear")` should do it

**Comment by sachabaclet** [comment] 2023-08-09 12:09
Thank you @ksunden, it works perfectly!

**Comment by tacaswell** [comment] 2023-08-09 13:09
Did we document this change?
