### ISSUE TITLE
Number of ticks for dates still gives overlapping labels

### ISSUE THREAD

**Issue by jorisvandenbossche** [matplotlib/matplotlib#7712] opened 2016-12-31 11:23 UTC
Matplotlib 2.0 introduced better default tick locators to have a better (often less) number of ticks (http://matplotlib.org/devdocs/users/dflt_style_changes.html#number-of-ticks) that prevents overlap of ticklabels. Which is a really nice enhancement, only it seems that this enhancement is not working for datetime tick labels:

```
>>> import matplotlib
>>> import matplotlib.pyplot as plt
>>> matplotlib.__version__
'2.0.0rc2'
>>> import datetime
>>> dates = [datetime.datetime(2016,1,i) for i in range(1,30)]
>>> values = list(range(1,30))
>>> plt.plot(dates, values)
[<matplotlib.lines.Line2D object at 0x7f41327d2e80>]
>>> plt.show()
```

![figure_1-2](https://cloud.githubusercontent.com/assets/1020496/21577206/3aab28a0-cf53-11e6-99b3-53d4301b328a.png)

This still gives the 'too much' tick labels like before (actually, the same plot but with integer x values gives fewer ticks).

Is there a technical reason for this? (the `DateLocator` using another mechanism to determine the number of ticks as the default `AutoLocator`)

Matplotlib 2.0.0rc2 (installed from conda-forge)

**Comment by efiring** [comment] 2016-12-31 16:48
The AutoDateLocator uses a completely different mechanism to set the default max number of ticks.  It has an internal table of max numbers depending on the unit of time it is working with, and there is no consideration of the physical size of the axis or of the font size.  You can supply a max that overrides the default.  You can also slant the tick labels as in http://matplotlib.org/devdocs/examples/api/date_demo.html.

I think that there is considerable room for improvement in the way we handle datetime ticking and labeling, but it needs to be left as a project for after the v2.0 release.

**Comment by patniharshit** [comment] 2017-03-01 06:48
I would like to work on the issue. Where should I start with this?

**Comment by ParagBh** [comment] 2017-03-05 18:18
I am getting some very strange behaviour when I try to trace the program in pycharm.

Here's the code I am using to reproduce the bug:
```

import numpy as np
import matplotlib.pyplot as plt
import datetime

dates = [datetime.datetime(2017,1,i) for i in range(1,30)]
values = list(range(1,30))


fig, ax = plt.subplots()
plt.plot(dates, values)

#fig.autofmt_xdate()
plt.show()
```

When I run this program in debug mode it keeps crashing in dates.py in the following line (in the function _from_ordinalf(x, tz=None)

```
print("value of x", x) #code I added
ix = int(x)
dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC) #keeps crashing here
```

Here's the corresponding stack trace

```
/Users/Username/Library/Python/2.7/lib/python/site-packages/subprocess32-3.2.7-py2.7-macosx-10.12-intel.egg/subprocess32.py:472: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
Backend MacOSX is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
value of x 0.0
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/backends/backend_macosx.py", line 142, in _draw
    self.figure.draw(renderer)
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/artist.py", line 68, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/figure.py", line 1242, in draw
    renderer, self, artists, self.suppressComposite)
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/artist.py", line 68, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/axes/_base.py", line 2383, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/artist.py", line 68, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/axis.py", line 1113, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/axis.py", line 954, in _update_ticks
    tick_tups = list(self.iter_ticks())
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/axis.py", line 897, in iter_ticks
    majorLocs = self.major.locator()
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/dates.py", line 981, in __call__
    self.refresh()
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/dates.py", line 1001, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/dates.py", line 759, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/dates.py", line 401, in num2date
    return _from_ordinalf(x, tz)
  File "/Users/Username/Library/Python/2.7/lib/python/site-packages/matplotlib-2.0.0_3321.geeb5a76-py2.7-macosx-10.12-intel.egg/matplotlib/dates.py", line 254, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC) #keeps crashing here
ValueError: ordinal must be >= 1
```
For some reason, the value of x is 0 even though it shouldn't be 0.

However, when I run the program normally (not in debug mode), the program runs should fine and the values of x it outputs is as follows:

```
value of x 736328.6
value of x 736359.4
value of x 736328.6
value of x 736359.4
value of x 736330.0
value of x 736333.0
value of x 736336.0
value of x 736339.0
value of x 736342.0
value of x 736345.0
value of x 736348.0
value of x 736351.0
value of x 736354.0
value of x 736357.0
```

Anyone have any ideas why it's crashing in debug mode?

**Comment by Shang-Jia** [comment] 2017-03-06 04:04
Modified the AutoDateLocator to use the largest possible tickable size rather than the smallest. Should I submit a pull request? And what testcases/if any should be written for this?
<img width="491" alt="capture" src="https://cloud.githubusercontent.com/assets/17349388/23596313/4dffeaf4-01f7-11e7-9bc7-b30513903b26.PNG">

**Comment by ParagBh** [comment] 2017-03-06 06:29
@Shang-Jia 

How did you get the daily interval to be every 6 days? If you look at the value of DAILY inside the self.intervald dictionary, the intervals can within a month can only be every 1, 2, 3, 7, 14, or 12 days because DAILY: [1,2,3,7,14,21]. So shouldn't the interval be either 1, 2, 3, 7, 14, and 21 and not 6? Please, correct me if I'm wrong.

**Comment by ParagBh** [comment] 2017-03-06 08:56
I think I may have a solution for this one but not sure if it's right. How exactly do I write testcases for this?

![figure_1](https://cloud.githubusercontent.com/assets/8824194/23602915/c3b022cc-0220-11e7-89ca-9f450a5ee388.png)

**Comment by Shang-Jia** [comment] 2017-03-06 16:18
Yeah, I was playing around with differing minticks and intervals as well

**Comment by jklymak** [comment] 2019-01-28 17:57
I'm going to close this as partially obviated by #10841.  That new formatter is not the default, but does give the user a way to have more compact date labels.  

In general, its going to be hard to make tick locating depend on tick formatting.

**Closed by jklymak** 2019-01-28 17:57 UTC
Labels: Difficulty: Medium, Wishlist, date handling
