### ISSUE TITLE
Repeated warning about fc-list

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#5836] opened 2016-01-12 10:18 UTC
Since Matplotlib 1.5.1, I see a warning (twice) each time I instantiate a `FontManager()`:

``` python
In [2]: from matplotlib.font_manager import FontManager

In [3]: FontManager()
/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Out[3]: <matplotlib.font_manager.FontManager at 0x1057b6630>

In [4]: FontManager()
/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Out[4]: <matplotlib.font_manager.FontManager at 0x1064d4ba8>
```

This did not happen with 1.5.0. There's two issues here - the warning is repeated twice at each call, which indicates that the command is being run twice (inefficient), and the warning is being shown at all - why does `fc-list` need to be run every time `FontManager` is run? Even if there is a good reason for it to run, I'm not sure if a warning is necessary?

**Comment by jenshnielsen** [comment] 2016-01-12 10:41
The only change in 1.5.1 is the addition of the warning in #5640 so there should be no performance difference. It's called twice to find both `ttf` and `afm` fonts. Not sure there is a good way to do that with just one call. 

Internally matplotlib pickles the fontmanager and only ever runs this code if there is no font cache installed so this should not be seen on other than the first import of pyplot. The warning was added because that call may be really slow on a system with many fonts installed see #5640 

In the long term there are plans to significantly rewrite the font handling see notes in #5414

**Comment by larrybradley** [comment] 2016-01-12 19:59
This warning is triggering `travis-ci` failures for Sphinx builds for packages that use `matplotlib` in documentation (e.g. https://travis-ci.org/astropy/photutils/jobs/101686421#L521).

**Comment by mdboom** [comment] 2016-01-12 20:13
> This warning is triggering travis-ci failures for Sphinx builds for packages that use matplotlib in documentation (e.g. https://travis-ci.org/astropy/photutils/jobs/101686421#L521).

Hmmm...  That's an interesting outcome of all this.  We could suppress the warning if `sphinx` is in `sys.modules`.  (Yuck).  I am starting to wonder if this warning was worth the trouble.  I'd love to get #5414 finished at some point and address this once and for all (by eliminating matplotlib's own font cache altogether).

**Comment by tacaswell** [comment] 2016-01-12 22:34
I was always ambivalent to it and would be fine with removing it again.  The strongest argument in favor of it is users having short attention spans which I do not really find persuasive.  

`warnings.warn` seems like the wrong mechanism for providing user feed back here, there is nothing that can be done about this and there is no change to the user code that can suppress this warning.  We probably should be using logging of some sort (but adding std logging is a _huge_ task which is even more thankless than most).

**Comment by jenshnielsen** [comment] 2016-01-13 09:44
What about just changing it to a print? The main point is to provide interactive feedback to users when importing pyplot that would be lost if we used logging.

**Comment by fmaussion** [comment] 2016-01-15 11:00
On our travis tests we get the message at each build. On which kind of architecture will the cache take so long that it requires a message?

**Comment by WeatherGod** [comment] 2016-01-25 17:47
The problem with "print" is that that can't be filtered at all. A warning
can at least be filtered if an application developer wants it to be
filtered.

As for what kinds of systems this can take so long, basically any system
with Adobe Illustrator installed. It can take several minutes to create the
initial cache.

**Comment by astrofrog** [comment] 2016-01-25 23:57
A somewhat crazy idea, but  what about emitting the warning only if the process takes more than a certain time? For example:

```python
import time
import warnings
import subprocess
import multiprocessing as mp

def delayed_warning():
    time.sleep(5)
    warnings.warn('Matplotlib is building the font cache using fc-list. '
                  'This may take a moment.')

proc = mp.Process(target=delayed_warning)
proc.start()
subprocess.call('fc-list')
proc.terminate()
```

**Comment by mdboom** [comment] 2016-01-26 20:49
Not a crazy idea, if it's robust enough.

Note that all of this will be wasted effort following #5414, where we just call the font-config API directly and don't have to copy all of its contents into our own cache.

**Comment by derekneil** [comment] 2016-02-04 03:07
not the prettiest work around, but i silenced the warnings for the time being (although the small startup delay is still present) with the following code, maybe a better filter could be used to allow other warnings
```
import warnings;
with warnings.catch_warnings():
    warnings.simplefilter("ignore"); 
    import matplotlib.pyplot as plt
```

**Comment by tacaswell** [comment] 2016-02-04 03:10
@derekneil try removing everything the mpl cache, you should only have seen this once on the first import....

**Comment by derekneil** [comment] 2016-02-08 12:48
@tacaswell i did try removing everything in the cache, but it happens every time on my system for some reason

**Comment by catubc** [comment] 2016-02-14 22:48
I ran the python code w. sudo and it cured it...my guess was that there wasn't permission to write that table... good luck!

**Comment by tacaswell** [comment] 2016-02-15 14:37
@catubc You should sort out what file you do not have permission to write as a user and fix the permissions on that file.  Running python with `sudo` is almost always a bad idea.

**Comment by fmder** [comment] 2016-02-23 18:06
I got this issue after upgrading matplotlib and clearing the cache solved my issue!

**Comment by mpenkov** [comment] 2016-02-24 12:09
@derekneil @fmder +1 "rm -rf ~/.matplotlib" solved the problem for me too

**Comment by sebhahn** [comment] 2016-02-25 09:19
For me it was `rm -rf ~/.cache/matplotlib`

**Comment by eakbas** [comment] 2016-03-09 09:44
`rm -rf ~/.cache/matplotlib`  solved the problem for me.

**Comment by matthewhoffman** [comment] 2016-03-16 20:54
`rm -rf ~/.matplotlib/fontList.cache` worked for me.

**Comment by grantjenks** [comment] 2016-03-23 22:38
`rm -rf ~/.matplotlib` worked for me.

**Comment by RichardoC** [comment] 2016-04-12 15:35
I'm glad this warning is here as it means I know to wait for it to run. @grantjenks I also  found that if I deleted everything in ~/.matplotlib (I'm on OSX) it generated once and I've not had the message since.

**Comment by astrofrog** [comment] 2016-04-17 22:17
Removing ``.matplotlib`` does **not** work for me:

```shell
mac-robitaille2:~ tom$ rm -r .matplotlib
mac-robitaille2:~ tom$ ipython
^[[APython 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:24:55) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from matplotlib.font_manager import FontManager
/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
```

**Comment by mdboom** [comment] 2016-04-18 13:48
Does the warning still appear on subsequent runs, though?  It should appear when importing matplotlib for the first time after deleting the directory.

**Comment by astrofrog** [comment] 2016-04-18 14:07
@mdboom - yes, and interestingly the warnings still appear multiple times every time I instantiate FontManager, as originally reported in this issue:

```shell
In [1]: from matplotlib.font_manager import FontManager
/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

In [2]: FontManager()
/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Out[2]: <matplotlib.font_manager.FontManager at 0x1020dd128>
```

**Comment by astrofrog** [comment] 2016-04-18 14:08
And on subsequent runs it doesn't warn for the import but still does for the ``FontManager()`` instantiation

```shell
In [1]: from matplotlib.font_manager import FontManager

In [2]: FontManager()
/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Out[2]: <matplotlib.font_manager.FontManager at 0x103fb5b70>
```

**Comment by mdboom** [comment] 2016-04-18 14:15
`FontManager` is really meant to be a singleton.  I'm not at all surprised that reinstantiating it causes the cache to be rebuilt.  I think it's always done this, it's just the warning that is new.  We should probably rewrite it as such -- but in the meantime, you should probably use the singleton instance in `fontManager` if you need to access this class directly.  But it seems like a pretty niche use case to want to access the class directly and not just through `findfont`.

As to why the warning appears twice -- the call is made once for `ttf` files and once for `afm` files.  That's just the nature of `fc-list` that we can't do both in one pass.  It's not a sign of doing anything less efficiently than we could (though it would be nice to squash the double warning if we can).

**Comment by mdboom** [comment] 2016-04-18 14:18
In summary, I think (other than the warning appearing twice) this is all behaving optimally and correctly.

**Comment by astrofrog** [comment] 2016-04-19 17:20
Ok, thanks for clarifying! Feel free to close this now :)

**Comment by astrofrog** [comment] 2016-04-19 17:21
Ok, thanks for clarifying! I do still believe that this should probably not be a warning but probably should be more at the ``logging.INFO`` level (since it's not something actionable on the part of the user)

**Comment by bsipocz** [comment] 2016-04-19 17:37
Before closing the issue, I'm still concerned that this warning triggers sphinx build failures on travis.
 
What is the suggestion for downstream CI?

**Comment by larrybradley** [comment] 2016-04-19 17:47
To followup @bsipocz, because of the triggered sphinx build failures, `astropy` (and affiliated packages) are currently stuck using `matplotlib 1.5.0` on travis.  Can the warning be downgraded to `logging.INFO` as suggested by @astrofrog?

**Comment by bsipocz** [comment] 2016-04-19 17:52
(and stacking with the version number also means that we can't go with the conda shipped package any more if also want the latest numpy, https://github.com/OpenAstronomy/conda-channel/issues/9)

**Comment by WeatherGod** [comment] 2016-04-19 18:18
We don't use the logging module, so we can't downgrade like that.

One trick for travis-ci is to do a "python -c 'import matplotlib.pyplot'"
call first prior to running the tests. The cache will be generated and
emits its warnings, but then the tests won't run into any issues. Another
trick is to add:

cache:
  directories:
    - $HOME/.cache/matplotlib

to your .travis.yml file, so the font cache will persist. This will also
give you faster test runs, too.

**Comment by efiring** [comment] 2016-05-11 21:54
My strong impression is that we are not going to make any changes in v1.5.x related to this, so I am closing it.  If someone disagrees, and especially if that person has a suitable PR to offer, please reopen.

**Comment by sami10007** [comment] 2016-05-28 17:39
I am getting a similar warning `Matplotlib is building the font cache using fc-list.` in OS X here http://apple.stackexchange.com/q/239910/15504 Is it related?

**Comment by ipostuma** [comment] 2016-06-06 15:37
`rm -rf ~/.cache/fontconfig/` worked for me !

**Comment by nuest** [comment] 2016-06-17 13:59
I'm getting this error when running a Python script in a Docker container. Since the container is "clean" every time it is started, I cannot delete the cache and there are also no "subsequent" runs.

Any ideas what to do to suppress this error? I do not think @derekneil 's solution will work, because I am not importing matplotlib myself, but a third party script which I run does.

Thanks for any ideas! This really messes up my log file ;-)

**Comment by jenshnielsen** [comment] 2016-06-17 14:14
First this is not an error but a warning and it's a warning that the import will be slow because it's recreating the cache so yes if you delete your cache or start from a fresh you will see it every time. 

You can always filter warnings in python using standard warning filters see https://docs.python.org/2/library/warnings.html#the-warnings-filter either import matplotlib.pyplot before you import from the third party script with the warnings filter around that import. Or just add the warnings filter around the import of the third party script which should do the same. 

You can also perhaps store the cache somewhere outside your container and copy it as part of your docker file startup to avoid recreating the cache every time.

**Comment by leycec** [comment] 2016-07-02 05:40
I second [nuest](https://github.com/nuest)'s Docker-specific complaint. Unfortunately, the obvious solution of persisting the Matplotlib cache (e.g., `$HOME/.cache/matplotlib`) only applies to Docker pipelines supporting caching outside of the current pipeline.

Travis, of course, does. [GitLab-CI](https://about.gitlab.com/gitlab-ci/), however, does _not_ – thanks to an [outstanding issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/4431). Under GitLab-CI, persisting the Matplotlib cache between continuous integration runs requires (in the `.gitlab-ci.yml` file of the applicable repository):

* Exporting the `MPLCONFIGDIR` environment variable to a build-relative path _before_ running tests.
* Adding that path to the `cache / paths` list.

For example:

```
cache:
    paths:
        - mpl-cache

before_script:
    - export MPLCONFIGDIR="mpl-cache"
```

This is GitLab-CI's fault. Nonetheless, thanks to `MPLCONFIGDIR`, this isn't _nearly_ as painful as it might otherwise be. **Yay.**

**Comment by selvamvinod** [comment] 2016-07-09 12:44
I import matplotlib in a wsgi script hosted with mod_wsgi on apache. Everytime, a call to this script is made I get a warning that `warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')`

It just blocks the script execution. Any suggestion to remove this cache building/or complete it fast is much appreciated? In my case it is not at all completing.

**Comment by tacaswell** [comment] 2016-07-09 14:48
@selvamvinod Please make a new issue for this and include

 - what version you have installed
 - how you installed it
 - a minimal example that reproduces the problem

We really do want to make sure your code runs, but you need to provide us enough information to do so.

**Comment by selvamvinod** [comment] 2016-07-10 20:26
Thanks tacaswell.

Platform details:
CentOS Linux release 7.2.1511 (Core) 
Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.0.7 mod_wsgi/4.5.3 Python/3.5.2

The below script blocks with the matplotlib version I got from https://github.com/matplotlib/matplotlib
by a git clone on 9th Jul 2016.(Or may be 10th Jul?....Date same as my previous comment date)

WSGI Script
------------------
#!/usr/bin/env pythonlatest
# -*- coding: utf-8 -*-
import imp
import codecs
import os, sys,imp
import cgi

import ephem
import io
import MySQLdb as mdb
import sys
sys.path.append('/mypython/wsgi')

from pyipinfodb import pyipinfodb
from datetime import datetime
from collections import OrderedDict

import sys
import unicodedata



#import matplotlib
import numpy as np
from mpl_toolkits.basemap import Basemap
#import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt

import io


def application(environ, start_response):
	map = Basemap(width=10,
				  height=20,
				  resolution='c',
				  projection='gall',
				  lon_0=0)

	map.drawcoastlines()
        ...
        ...
        ...
       img_io = io.BytesIO()
       return img_io

**Comment by tacaswell** [comment] 2016-07-18 04:33
Anyone who has this problem can you please tell us:

 - what the last version of matplotlib you upgraded from
 - what version you upgraded to
 - how you installed both
 - the contents of `~/.cache/matplotlib (to the degree your are comfortable sharing).

We are having issues debugging this because we can not reproduce it.

**Comment by datakid** [comment] 2016-07-19 05:33
Had this problem on 1.5.1, new installation inside a py2.7 virtualenv ("pip install matplotlib") on Centos 7.2. 

Note that we are using it with environment modules, so the venv is in /binaries/optitype and once that's in place, people need to "module load optitype" to use. 

contents of ~/.cache/matplotlib:
-rw-rw-r--  1 root root 24018 Jul 19 14:00 fontList.cache
drwxrwxr-x  2 root root     6 Jul 19 14:00 tex.cache

tex.cache is empty

**Comment by QuLogic** [comment] 2016-07-19 08:04
Are you actually running as root? If you're running as a regular user (which you should be), then it's not really a bug; matplotlib may just be unable to modify the files since they aren't owned by the user.

**Comment by datakid** [comment] 2016-07-19 08:59
I was running it from root in that example, but I also ran it as a non su user with the same result and contents of .cache

**Comment by WeatherGod** [comment] 2016-07-19 14:36
I think the point is that since it ran once as root, running it again as a
normal user would result in a false failure in the codebase. One thing that
happens in the process of checking the cache is that it tries to see if it
can write to the target directory. If it fails that, then it warns about it
and then it builds a cache in /tmp instead. The directory and files are now
owned by root, so a regular user can't write to those directories at all,
so it will keep falling back to the /tmp cache. Fix *all* of the
permissions. Don't run as root again.

**Comment by datakid** [comment] 2016-07-19 23:52
Ok...sorry, I'm new here and don't understand the context. 

Permissions on which files explicitly, and what *should* those permissions be?

**Comment by WeatherGod** [comment] 2016-07-20 14:02
The files and folders you mentioned up above should not be owned by root.
It should be owned by the user (and should be a part of whatever group that
user belongs to). Just have root nuke them and where-ever matplotlibrc is
(most likely also owned by root), and reload matplotlib as a normal user.

**Comment by SoonSYJ** [comment] 2016-08-24 02:16
I have updated my matplotlib recently. When trying
` from matplotlib.font_manager import FontManager`
`FontManager()`
I got a UnicodeDecodeError like this "UnicodeDecodeError: 'ascii' codec can't decode byte 0xa1 in position 0: ordinal not in range(128)"

Can anyone give me some advice. Thank you

**Comment by jenshnielsen** [comment] 2016-08-24 07:02
@SoonSYJ It sound like you have a different issue. Can you try removing your font cache as above. If that doesn't solve the issue can you open a new bug so this is not lost. In the new bug please provide platform, matplotlib version, full traceback etc.

**Comment by jzf2101** [comment] 2016-08-29 19:57
I just switched my anaconda to python3 and am now seeing this bug as well

**Comment by tacaswell** [comment] 2016-08-29 20:01
@jzf2101 Can you do `ls -la ~/.cache/matplotlib` ?

**Comment by astrofrog** [comment] 2016-08-29 21:30
By the way, I keep running into this, and I think what's happening is that as a developer, I keep switching between conda environments with different Matplotlib versions, so that somehow messes up the cache (I don't see the warning if I remove all the cache and then stick to using 2.x).

**Comment by tacaswell** [comment] 2016-08-29 23:58
@astrofrog You should only see it once per version switch, does in become persistent after some cycle of versions?

**Comment by anntzer** [comment] 2016-08-30 21:01
I think @astrofrog is seeing https://github.com/matplotlib/matplotlib/issues/4993#issuecomment-224517607, which is a somewhat different issue.

**Comment by rmjarvis** [comment] 2016-11-28 06:19
> I do still believe that this should probably not be a warning but probably should be more at the logging.INFO level (since it's not something actionable on the part of the user). But if there's otherwise agreement this should be a warning, feel free to close this!

I strongly agree with @astrofrog about this.  This is broken behavior, as far as I'm concerned.  Warnings should be reserved for things that are either likely to be user error or where the code's behavior is probably not what the user is expecting.  And in the latter case, there should be an easy way to suppress the warning if it really is what the user meant.

e.g. The warning emitted by `matplotlib.use('Agg')` is a good exemplar.  It warns if the `use` statement happens too late to be effective, tells you how to make it effective, and also gives an option (`warn=False`) to suppress the warning.

The warning about fc-list, OTOH, is not actionable.  And in many cases (e.g. imports by dependencies) it is not suppressible.  And with the rising popularity of Travis CI (and others), we get a clean system each time, so people are seeing it a lot.  It adds quite a lot of noise to our test output, especially with the warning being emitted multiple times, not just once as it should.

For my case, none of the above suggestions for Travis have worked.  My solution has been to use `matplotlib==1.5.0`, which I now consider the latest working version of matplotlib.  Please reopen this issue and fix this bug. 

FWIW, I thought the [suggestion](https://github.com/matplotlib/matplotlib/issues/5836#issuecomment-174735702) by @astrofrog to only emit the warning if building the cache takes more than 5 seconds or so was a good one.  This would solve most of the cases where this behavior is seen as a bug and preserve the cases where people find it useful.  And figuring out why it is emitting the warning multiple times and fixing that would be nice as well.

**Comment by efiring** [comment] 2016-11-28 06:53
I agree; we need to figure out a better way to handle this.

Also, as @astrofrog noted originally, the warning is emitted *twice*, which in itself indicates there is a real bug in the code.

**Comment by efiring** [comment] 2016-11-28 07:38
Not a bug, but an inefficiency:

- The warning is in `get_fontconfig_fonts()`, right before it runs `fc-list`.  
- `get_fontconfig_fonts()` is called once by `getSystemFonts()`.
- But `getSystemFonts()` is called twice by `FontManager.__init__()`, first looking for ttf, then for afm.

**Comment by tacaswell** [comment] 2016-11-29 14:53
Being emitted twice is correct behavior as we are looking for two types of fonts, maybe that should be included in the warning.

> For my case, none of the above suggestions for Travis have worked. My solution has been to use matplotlib==1.5.0, which I now consider the latest working version of matplotlib. Please reopen this issue and fix this bug.

@rmjarvis I find it difficult to take this sort of over-the-top rhetoric seriously.

Almost all of the CI services let you keep a persistent cache between runs, push `~/.matplotlib` in that cache and you will only see the warning occasionally.  Failing that, run a step in your CI that just imports matplotlib with the warning suppressed before you run your main tests.

mpl sits at a weird edge between a library and a user interface.  Providing _some_ sort of feedback to users who hit surprisingly long import times (my understanding is that if you have all the adobe fonts installed this can take minutes) is important.  

The problem with moving to a `logging` based solution is that it brings with it a tremendous amount of overhead (which mpl is currently using none of) and if it is not very noisy by default it will miss the target audience for this warning.

If there is a non-thread based way to get a 5s delay I am :+1: on that, but bringing threads in this seems like complexity overkill.

I think this should be closed again.

**Comment by efiring** [comment] 2016-11-29 16:19
On 2016/11/29 4:53 AM, Thomas A Caswell wrote:
> Being emitted twice is correct behavior as we are looking for two types
> of fonts, maybe that should be included in the warning.

I don't agree.  First, even though we are looking for two types of 
fonts, this does not require running fc-list twice, because as far as I 
can see the calls are identical, returning the same list. Second, 
because this is a very unusual warning in that it is just telling the 
user to be patient.  There is no benefit at all in sending that message 
twice.

**Comment by astrofrog** [comment] 2016-11-29 20:36
@tacaswell @efiring - see https://github.com/matplotlib/matplotlib/pull/7532

**Comment by NelleV** [comment] 2016-12-01 04:38
This is annoying, but not release critical. Bumping this to 2.0.1, as we almost have a patch ready for that one (so it'll probably go in for 2.0).

**Comment by anntzer** [comment] 2016-12-12 00:55
Closed by #7596.

**Closed by anntzer** 2016-12-12 00:55 UTC

**Comment by adaifotis** [comment] 2017-01-19 21:21
For those arriving after experiencing this problem with docker specifically, I added the below to my Dockerfile:

`RUN python -c "import matplotlib.pyplot"`

That way it will create the cache when you first build the image, but then should not warn anymore on subsequent runs.

**Comment by empty16** [comment] 2017-11-06 00:55
Remove the cache works for me, too. Thanks, you guys.

**Comment by jklymak** [comment] 2017-11-06 03:12
It also seems this could be moved from `warnings.warn` to `logging.info` when #9313 gets merged...
