### ISSUE TITLE
IndexError when using ax.fill_between function

### ISSUE THREAD

**Issue by maddyhowell** [matplotlib/matplotlib#25009] opened 2023-01-16 23:09 UTC
I have been using the fill_between function before and recently I have started receiving an `IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed` . I also tried some examples using the fill_between function in your documentation (https://matplotlib.org/stable/gallery/lines_bars_and_markers/fill_between_alpha.html#sphx-glr-gallery-lines-bars-and-markers-fill-between-alpha-py) and was receiving the same error each time. I am currently using matplotlib version 3.5.1 and python version 3.10.6

**Comment by jklymak** [comment] 2023-01-16 23:36
This looks to be a duplicate of https://github.com/matplotlib/matplotlib/issues/24106 - what version of Numpy are you using?  Consider downgrading numpy or upgrading Matplotlib.

**Closed** 2023-02-09 19:58 UTC
Labels: status: needs clarification, status: duplicate
