### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by yanghaoyu97** [matplotlib/matplotlib#22632] opened 2022-03-10 01:46 UTC
### Bug summary

This possible bug seems to be related to some incompatibility between the “extend” argument in “plt.figure.colorbar” and “.ax.invert_yaxis()” functions. More specifically, if I just extend the max of colorbar (second figure) or just invert the y-axis of the colorbar, everything work fine. However, if I do this two at the same time, the colorbar would be inverted while the extended arrow is not(figure one). 

### Code for reproduction

```python
# Generate X/Y point mesh grid
x = np.linspace(-4.5, 1.5, 400)  
y = np.linspace(-8, -2, 400)
X, Y = np.meshgrid(x, y)
potential, rate_determining_step = calculate_limiting_potential_from_linear_relations(X, Y, free_energy_dict)[0], calculate_limiting_potential_from_linear_relations(X, Y, free_energy_dict)[1]   # calculate limiting potential for each point on the mesh grid
 
# Create backup ground volcano plot
fig = plt.figure(figsize=[8, 6])
background = fig.add_subplot(111)  # add sub plot
 
# Add contour plot
contour = background.contourf(X, Y, potential, levels=512, cmap="rainbow")  # create filled contour (reverse rainbow)
 
# Create colorbar
cbar = fig.colorbar(contour, shrink=0.95, aspect=15, ticks=[1, 2, 3, 4])  # create colorbar (shrink/aspect for the size of the bar)
cbar.set_label("Limiting Potential (eV)", fontsize=16)  # add label to the colorbar
cbar.ax.tick_params(labelsize=12)  # set tick label size
cbar.ax.invert_yaxis()  # put the colorbar upside down
```

### Actual outcome

![figure3](https://user-images.githubusercontent.com/80093591/157570730-408cf9a3-3be1-4596-8a99-68f314124ccd.png)
![figure1](https://user-images.githubusercontent.com/80093591/157570816-8e9715c8-ac97-48d1-834f-8727d59a640f.png)

### Expected outcome

The arrow should inverse with the colorbar itself.

### Operating system

Windows11

### Matplotlib Version

Matplotlib 3.5.1

### Python version

Python 3.10

### Installation

pip

**Comment by yanghaoyu97** [comment] 2022-03-10 01:55
Sorry I forgot to mention this: I tried to use python3.6+ matplotlib 3.3.4 with exactly the same code and data. The results look just fine. So I assume this should be related to the 3.5.1 version of matplotlib. Also, apologise for not including the datasheet which contains sensitive data.

**Comment by jklymak** [comment] 2022-03-10 01:58
Please make a self-contained minimal example.  I'm relatively certain this bug has been addressed, but cannot check without an example.

**Comment by jklymak** [comment] 2022-03-10 04:37
This is a duplicate of #22052, though that has not been solved yet.

**Closed by jklymak** 2022-03-10 04:37 UTC
