### ISSUE TITLE
[ENH]: More accurate type stub for `plt.subplots` like VSCode did before.

### ISSUE THREAD

**Issue by cesaryuan** [matplotlib/matplotlib#28226] opened 2024-05-15 03:28 UTC
### Problem

Before matplotlib 3.8, VSCode embedded its type stubs for matplotlib. At that time, the typehint of `plt.subplots` is better than the typehint provided by matplotlib itself. You can see the differences below:

Let's see the embedded typehint for plt.subplots. I made it available by changing the Matplotlib version to 3.7. It can identify the `ax` type correctly.

However, after upgrading to matplotlib 3.8. [The VSCode use the type stub provided by matplotlib instead of the one embedded by itself](https://github.com/microsoft/pylance-release/issues/4351#issuecomment-1737986648). And it cannot get the corrent type for `ax`.

![image](https://github.com/matplotlib/matplotlib/assets/35998162/00d40d1a-49b5-469e-9065-9bce16bfd4b6)
![image](https://github.com/matplotlib/matplotlib/assets/35998162/23bf42f0-260f-406a-8fd4-3f3a42ad3430)

### Proposed solution

Adapt the type stub provided by VSCode. You can see them in https://github.com/microsoft/python-type-stubs/blob/102c1448f7504d6450a221ae9c29a260fa741a30/matplotlib/pyplot.pyi#L200C1-L209C30.

I tried just putting the `pyplot.pyi` file in the `pyplot.py` folder. It works. So maybe we can do it in repo.

**Comment by ksunden** [comment] 2024-05-15 04:43
The short version is "its complicated" and, while we _can_ do _better_ the perfect behavior is not super possible, since this method returns different types based on the value of parameters. Any is a shortcut for "at least it won't yell at users here".

Closing as a duplicate of #28210 and #27025

See also #27001, which is a PR to improve this type hint, and includes a discussion of why the VSCode version is actually incorrect.

**Closed by ksunden** 2024-05-15 04:43 UTC
Labels: New feature
