### ISSUE TITLE
[Bug]: WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

### ISSUE THREAD

**Issue by SercanBayram** [matplotlib/matplotlib#27532] opened 2023-12-16 18:02 UTC
### Bug summary

I am coding with Python on Mac Pro m3 - Sonoma 14.2 operating system. When I print a plot with the Matplotlib library, I get a warning like the following:

> 2023-12-16 20:12:28.405 Python[1286:56828] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

How to solve this Warning...

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

tetha = np.arange(180)
signal = np.sin(tetha*180/2)

plt.plot(tetha, signal)
plt.show()
```

### Actual outcome

2023-12-16 20:12:28.405 Python[1286:56828] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

### Expected outcome

How to solve this Warning...

### Operating system

macOS - Sonoma 14.2

### Matplotlib Version

3.8.2

### Matplotlib Backend

MacOSX

### Python version

3.11.7

### Installation

pip

**Comment by ksunden** [comment] 2023-12-16 23:40
I will close this as a duplicate of #27389.

When that was reported I was unable to reproduce this on my Mac, so if you have any ideas on how to ensure that the problem shows up, please comment over there.

**Closed** 2023-12-16 23:41 UTC
Labels: OS: Apple, GUI: MacOSX

**Comment by SercanBayram** [comment] 2023-12-17 16:13
I get the same warning message regarding this issue when I use the drawing function.

```
import numpy as np
import matplotlib.pyplot as plt

tetha = np.arange(180)
signal = np.sin(tetha*180/2)

plt.plot(tetha, signal)
plt.show()
```
Warning Alert:

> 2023-12-17 18:57:45.598 Python[939:19218] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

I couldn't find anything on how to resolve this warning message.

Operating system: macOS - Sonoma 14.2
Matplotlib Version: 3.8.2
Python version: 3.11.7
Development environment: VS Code

<img width="1020" alt="Ekran Resmi 2023-12-17 18 59 29" src="https://github.com/matplotlib/matplotlib/assets/16906406/cefccf5a-8931-46cc-b19a-33bf07bd4432">

Thanks you from now for your help.
