### ISSUE TITLE
2.0.0b4, debian unstable: lots of ImageComparisonFailure

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#7134] opened 2016-09-18 20:59 UTC
Hello,
while testing 2.0.0b4 on debian unstable, there are a lot of ImageComparisonFailure. it seems that the same test is executed twice, and the first execution always fails, for example:

```
matplotlib.tests.test_axes.test_canonical.test ... FAIL
matplotlib.tests.test_axes.test_canonical.test ... ok
matplotlib.tests.test_axes.test_canonical.test ... ok
... ... ...
FAIL: matplotlib.tests.test_axes.test_canonical.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/matplotlib-2.0.0~beta4/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 58, in failer
    result = f(*args, **kwargs)
  File "/build/matplotlib-2.0.0~beta4/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 261, in do_test
    '(RMS %(rms).3f)'%err)
ImageComparisonFailure: images not close: /build/matplotlib-2.0.0~beta4/result_images/test_axes/canonical.png vs. /build/matplotlib-2.0.0~beta4/result_images/test_axes/canonical-expected.png (RMS 0.003)
```

(that is the 2.7 failure, but it happens also on 3.5 and on their debug flavor interpreters).

the grand total of the testsuite is `FAILED (KNOWNFAIL=69, SKIP=14, failures=887)`

please let me know how i can help you debug this

**Comment by matthew-brett** [comment] 2016-09-18 21:04
On Sun, Sep 18, 2016 at 1:59 PM, Sandro Tosi <notifications@github.com>
wrote:

> Hello,
> while testing 2.0.0b4 on debian unstable, there are a lot of
> ImageComparisonFailure. it seems that the same test is executed twice, and
> the first execution always fails, for example:
>
> matplotlib.tests.test_axes.test_canonical.test ... FAIL
> matplotlib.tests.test_axes.test_canonical.test ... ok
> matplotlib.tests.test_axes.test_canonical.test ... ok
> ... ... ...
> FAIL: matplotlib.tests.test_axes.test_canonical.test
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
>     self.test(*self.arg)
>   File "/build/matplotlib-2.0.0~beta4/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 58, in failer
>     result = f(*args, **kwargs)
>   File "/build/matplotlib-2.0.0~beta4/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 261, in do_test
>     '(RMS %(rms).3f)'%err)
> ImageComparisonFailure: images not close: /build/matplotlib-2.0.0~beta4/result_images/test_axes/canonical.png vs. /build/matplotlib-2.0.0~beta4/result_images/test_axes/canonical-expected.png (RMS 0.003)
>
> (that is the 2.7 failure, but it happens also on 3.5 and on their debug
> flavor interpreters).
>
> the grand total of the testsuite is FAILED (KNOWNFAIL=69, SKIP=14,
> failures=887)
>
> please let me know how i can help you debug this
>

Is it possible you are building against the system freetype, and not the
matplotlib version?

I think the test tolerances depend on a specified freetype version that you
get with

export MPLLOCALFREETYPE=1

**Comment by sandrotosi** [comment] 2016-09-18 21:35
yes i'm using the system package for freetype (at version 2.6.3): in debian we try hard not to use internal versions of libraries we have available in the distro, and i would like to keep doing this with matplotlib as well. Is there a way to adjust the tests sensibility with a different version of freetype?

**Comment by matthew-brett** [comment] 2016-09-18 21:46
I know you try hard not to use internal versions :).

Maybe it would need an addition to the ``image_comparison`` decorator that would allow different tolerances for different freetype versions.

**Comment by tacaswell** [comment] 2016-09-18 22:34
We previously had a default non-zero tolerance on the image comparisons, to account for freetype changing under us.  However, this resulted in a couple of cases where we were rendering _very_ wrong glyphs, but the tests still passed due to the tolerance.  We still have a handful of tests that need a tolerance (particularly on windows iirc), but overall we should not go back to having non-zero tolerances as a standard practice.

The tests running multiple times is probably the png / svg / pdf tests running in sequence (only the png test uses our bindings to freetype, the others work by converting a vector graphic we have checked into the source against the output by rasterizing both with inkscape/ghostscript respectively).

Probably the best solution is to make the image comparison smart enough to skip the png tests if the freetype version is wrong.

attn @Kojoley 

One thing that @astrofrog has with pytest-mpl is to source the baseline images from a URL which will enable use to keep versions of the pngs for multiple versions of freetype, but that would also be a fair amount of work to keep up.

**Comment by sandrotosi** [comment] 2016-09-18 22:53
thanks for looking into this! just a small note about the baseline retrieval via URLs: in debian we dont allow network access during build, so we would need some other solution to keep those images available during build

**Comment by rathann** [comment] 2016-09-19 13:43
Same here on Fedora. We're using freetype-2.6.5 and freetype-2.7, depending on the branch.

**Comment by Kojoley** [comment] 2016-09-19 16:10
> it seems that the same test is executed twice, and the first execution always fails

It is definitely png/svg/pdf tests (prior to 903d11899b677749fc7e8346efdcaa1ad5662c42 commit multiple baselines/extensions per test was looking as the same test run multiple times in the log)

> only the png test uses our bindings to freetype, the others work by converting a vector graphic we have checked into the source against the output by rasterizing both with inkscape/ghostscript respectively

But freetype is still used for text bbox calculations (actually this is the cause of #6899).

> Probably the best solution is to make the image comparison smart enough to skip the png tests if the freetype version is wrong.

This can be done and we already have `freetype_version` on `image_comparison` decorator for this, but I think it is better to tag baselines with freetype version rather than tag tests code.

> which will enable use to keep versions of the pngs for multiple versions of freetype, but that would also be a fair amount of work to keep up

This will take really huge amount of handwork if we are going to create and support separate baselines for several freetype versions and I think we do not have enough resources for this in the current state. It can be less painful if we could reduce the number of the tests that requires text rendering (most of these tests are mathtext tests).

Alternative solution is to test text rendering without font anti-aliasing/hinting (recent freetype changes are mostly related to hinting).

**Comment by rathann** [comment] 2016-09-21 20:36
FWIW, relaxing the default tolerance to 0.306 makes all tests pass on x86_64/rawhide (F26) (except test_pngsuite and streamplot_colormap which override tolerance setting). Most differences are under 0.1. I'm considering carring a patch doing that in Fedora for now as it's too much effort to adjust tolerance for each individual failing test (there are ~900).

**Comment by matthew-brett** [comment] 2016-09-21 20:39
I feel your pain, but I guess it's possible that some of these tests are showing important differences.

**Comment by QuLogic** [comment] 2016-09-21 21:44
@rathann Are you building from [this copr](https://copr.fedorainfracloud.org/coprs/rathann/matplotlib2/) or some other srpm?

**Comment by sandrotosi** [comment] 2016-09-21 21:50
@matthew-brett well yeah the fact the tests doesnt pass means there is a substantial difference, but do we have any way to assess what that is? i mean something better than: look at the 2 images and spot the differences?

**Comment by tacaswell** [comment] 2016-09-21 22:39
@sandrotosi The default tolerance is 0 meaning we get identical RGBA arrays out.  

We spent a while thinking about a better way to evaluate images being 'close but not wrong', but could not come up with anything better.  The problem seems to boil down to how to tell a character shifted by a pixel or two from a different character being there.

**Comment by rathann** [comment] 2016-09-22 08:20
@QuLogic I've been doing local mock builds for the last couple of days, but I've just uploaded my latest SRPM there.

**Comment by QuLogic** [comment] 2016-10-09 09:32
I tried this out on a 32-bit mock for rawhide. Indeed, most of the failures are fairly minor text changes. Strangely, more tests fail on 64-bit, but I've not investigated it.

There are some things that might be just a loss of precision somewhere, e.g., in `test_colorbar/cbar_locationing`, the second blue is expected to be `#0081ff`, but is `#0080ff`.

**Comment by matthew-brett** [comment] 2017-01-23 19:51
@sandrotosi - did you find a solution for these?   We have the same situation over at the 32-bit wheel builds, noted at #6604, as well as intermittent segfaults noted at #6620.   At some point we've got to decide whether to drop the 32-bit builds.

**Comment by sandrotosi** [comment] 2017-01-24 03:39
@matthew-brett i followed the example of Fedora and increase the tolerance to 0.306 and almost all the comparison warning went away. it is suboptimal i know, but different distros have different libraries so a slightly discrepancy is somewhat expected.

as for the 32-bit random failures, oh my i never noticed as we ignore failues for tests (as there are some other issue we still havent resolved, see #5807 for an example) but indeed they are there: https://buildd.debian.org/status/fetch.php?pkg=matplotlib&arch=i386&ver=2.0.0-3&stamp=1485066067&raw=0 shows a

```
matplotlib.tests.test_mathtext.test_mathtext_cm_47.test(1, u'/«PKGBUILDDIR»/result_images/test_mathtext/mathtext_cm_47.png', u'/«PKGBUILDDIR»/result_images/test_mathtext/mathtext_cm_47-expected.png') ... Segmentation fault


matplotlib.tests.test_agg.test_marker_with_nan ... Segmentation fault


matplotlib.tests.test_mathtext.test_mathtext_cm_47.test(1, '/«PKGBUILDDIR»/result_images/test_mathtext/mathtext_cm_47.png', '/«PKGBUILDDIR»/result_images/test_mathtext/mathtext_cm_47-expected.png') ... Fatal Python error: Segmentation fault

Current thread 0xf6fe1140 (most recent call first):
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 2773 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1383 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1383 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3511 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3511 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3829 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3900 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3376 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3511 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3964 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3359 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3511 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3511 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3511 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3829 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3376 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3376 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3511 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3367 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3511 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3698 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3964 in parseImpl
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1379 in _parseNoCache
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1514 in _parseCache
  ...
Segmentation fault
```

i feel so stupid i never noticed them :(

**Comment by matthew-brett** [comment] 2017-01-24 18:55
Over at https://github.com/matplotlib/matplotlib/pull/7757#issuecomment-272720359 @dopplershift suggested making the result images into a package.  I wonder whether we could use that mechanism to provide a different set of test images for the different architectures, via wheels?

**Comment by astrofrog** [comment] 2017-01-26 13:06
> One thing that @astrofrog has with pytest-mpl is to source the baseline images from a URL which will enable use to keep versions of the pngs for multiple versions of freetype, but that would also be a fair amount of work to keep up.

> Over at #7757 (comment) @dopplershift suggested making the result images into a package. I wonder whether we could use that mechanism to provide a different set of test images for the different architectures, via wheels?

@tacaswell @matthew-brett to some extent, your two suggestions require the same amount of work. I think it makes more sense to do the first (remote images) because you need to be able to keep reference images for all versions around, so a package might start to become quite large whereas with remote reference images, you just download what you need. I'm not convinced maintaining this would be a huge amount of work, since I think a lot of it could be automated?

**Comment by sandrotosi** [comment] 2017-01-26 15:00
fetching remote files during build is unacceptable for debian, so we would not be able to use this solution.

i think the main problem is: how can you define if an image is good for a given distribution. in the case of debian, we develop in an ever-changing distribution (unstable) which evolves over a period of time of ~2 years - would generating a snapshot a day work? what about reproducibility? we take snapshots of the upstream projects (that would include also the pngs-for-debian) and release that, it means at a later time if you try to rebuild the same packages that has no diffs in the past, you might get new ones as some other libraries have change in the meantime.

(this might sound stupid, but it might give more ideas) if the main culprit is freetype (so i guess texts) should we try to have images-without-text with a lower tolerance thresholds and images-with-text with a higher threshold? or even "cutting" the image to grab the border (usually with text, like titles, ticks labels, etc) and compare it with a higher threshold that the central part of the image (usually graphs)?

**Comment by tacaswell** [comment] 2017-10-23 00:37
We do already remove text from many images (that is the default behavior of the image comparison tests!)

We used to just use a threshold by default, but we were outputting mathtext images with the wrong symbols that were still passing the tests.

@sandrotosi I suspect it would end up looking like a bunch of (versioned) tarballs of `test_images-MPLVER-FTVER.tar.gz` so I _think_ debian would just have a 'mpl-test-data' package that just is those images put into the correct place in the file system that is a build-time dependency of Matplotlib.

Punting to 2.2 as we are not going to do anything this drastic in a micro release.

**Comment by sandrotosi** [comment] 2018-05-18 00:39
JFYI i decided in debian to not make tests fail if the images are not close: this way we can catch actual failures that would otherwise pass un-noticed in the storm of ImageComparisonFailure failures

**Comment by QuLogic** [comment] 2020-09-24 08:10
I'm going to close this as 2.0.0 is unsupported, and you have #11324 about more recent versions.

**Closed by QuLogic** 2020-09-24 08:10 UTC
Labels: Testing
