### ISSUE TITLE
when import matplotlib, create trackback: no suitable image found

### ISSUE THREAD

**Issue by pxrgod** [matplotlib/matplotlib#20223] opened 2021-05-14 02:49 UTC
### Bug report
I install matplotlib in mac os with version Big Sur 11.3.1 successfully, when i import matplotlib, I find traceback as followings:
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 31, in <module>
    from matplotlib import _api, _c_internal_utils
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/matplotlib/_c_internal_utils.cpython-39-darwin.so, 2): no suitable image found.  Did find:
  /opt/homebrew/lib/python3.9/site-packages/matplotlib/_c_internal_utils.cpython-39-darwin.so: mach-o, but wrong architecture
  /opt/homebrew/lib/python3.9/site-packages/matplotlib/_c_internal_utils.cpython-39-darwin.so: mach-o, but wrong architecture

notes:
I use pip3 install -U matplotlib

**Matplotlib version**
  * Operating system: MacOs Big Sur 11.3.1
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: 3.9
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by QuLogic** [comment] 2021-05-14 03:44
Duplicate of #20224.

**Closed by QuLogic** 2021-05-14 03:44 UTC
