### ISSUE TITLE
[Bug]: Possible issue with Matplotlib 3.9.1 wheel on Windows only

### ISSUE THREAD

**Issue by ianthomas23** [matplotlib/matplotlib#28551] opened 2024-07-12 13:19 UTC
### Bug summary

Since the release of Matplotlib 3.9.1 I have been experiencing CI failures on ContourPy on Windows only that did not occur with Matplotlib 3.9.0. There is some info in my PR contourpy/contourpy#406 that works around it by pinning `matplotlib<3.9.1` on Windows. I am not really sure what the problem is, but I now have a simple reproducer.

### Code for reproduction

```Python
from contourpy import contour_generator
import matplotlib.pyplot as plt

print("START")
cont_gen = contour_generator(z=[[0, 1], [2, 3]])
try:
    cont_gen.filled(2.0, 1.0)
except Exception as e:
    print("EXCEPTION HANDLER", e)
print("END")
```

### Actual outcome

If you run the above code with matplotlib 3.9.1 and contourpy 1.2.1 (the latest releases) it works OK with correct output of
```
START
EXCEPTION HANDLER upper_level must be larger than lower_level
END
```
Note the code imports some of matplotlib but does not use it, and the contourpy code here does not use it either.

If you use matplotlib 3.9.1 or nightly wheel and contourpy nightly wheel then it silently crashes for me with just
```
START
```
But if you comment out the `import matplotlib...` line it works OK again. Use of matplotlib 3.9.0 and any contourpy (1.2.1 or nightly wheel) is always OK.

For my installations here I am `pip install`ing into python-only `conda` environments, i.e.
```bash
conda create -n temp python=3.12
conda activate temp
pip install matplotlib contourpy
```

### Expected outcome

See above.

### Additional information

There is a relevant post by @BertJorissen on the [pybind11 gitter](https://matrix.to/#/#pybind_Lobby:gitter.im) which has some in-depth analysis and leads me to believe that this is not just a ContourPy problem.

### Operating system

Windows only

### Matplotlib Version

`>= 3.9.1`

### Python version

I see same results for python 3.8 to 3.12.

### Installation

pip

**Comment by BertJorissen** [comment] 2024-07-14 11:30
Hi Ian
my problem originated from using inheritance on an Pybind11-class, which has a function that throws some error.
I see that your function above calls `SerialContourGenerator`, which is a child class from the Pybind11-`ContourGenerator`, which will throw a `std::invalid_argument`-exception. It thus seems to be the same issue indeed.
The error comes from matplotlib, as both my test program and contourpy work happily next to each other, but they crash when matplotlib has been loaded (but not necessarily used).
From comparing the releases 3.9.0 and 3.9.1, there does not seem to be any problem that I can point out immediately.
I see however that the wheels are also repaired on windows. I'm not sure if this is necessary. When I turned this repairing on before, my package seemed to behave weirdly.
Best
Bert

**Comment by ianthomas23** [comment] 2024-07-15 08:21
@story645 I use something like this:
```bash
python -m pip install "matplotlib==3.9.1"
python -m pip install --only-binary=:all: --pre --upgrade --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple contourpy
```
to give matplotlib 3.9.1, numpy 2.0.0 and contourpy 1.3.0.dev1

**Comment by ianthomas23** [comment] 2024-07-24 15:49
I've created a repo to demonstrate this at https://github.com/ianthomas23/mpl-test. If you look at the github action run https://github.com/ianthomas23/mpl-test/actions/runs/10079751371 you'll see that it uses the reproducer code from above both with and without the matplotlib import for various combinations of mpl and contourpy versions. The interesting addition is a run that builds mpl 3.9.1 from source using MSVC and this passes the tests, compared to the official wheel (built using the `cibuildwheel` machinery in the mpl repo) which fails the tests.

**Comment by nquetschlich** [comment] 2024-07-24 21:41
I am very happy that I stumbled over this issue because since two weeks, also the CI pipeline for one of our open-source projects failed only on windows without any (useful) error message (see, e.g., https://github.com/cda-tum/mqt-predictor/actions/runs/9824223458/job/27126370262). 
Unfortunately I do not have the time to create a minimal working example, downgrading Matplotlib to <v3.9.1 solved the issue (see https://github.com/cda-tum/mqt-predictor/pull/258).

I just wanted to mention it, seems like we ran into the same issue as you did.

**Comment by ianthomas23** [comment] 2024-08-01 11:54
I have labelled this "release critical" as there is evidence of 3 downstream libraries suffering crashes on Windows using Matplotlib 3.9.1, so it is not specific to ContourPy. I need help with this.

**Comment by tacaswell** [comment] 2024-08-01 15:23
So to summerize:

 - 3.9.0 wheels work
 - 3.9.1 + nightly wheels do not work
 - locally built wheels work

Given that locally built wheels work I suspect that this is not a problem in Matplotlib source, but is something is the build process.  My two suspicions are:

 - a delvewheel bug
 - a pybind11 bug

It looks like delvewheel had releases on April 17 (1.6.0), Jun 20 (1.7.0) and July 3 (1.7.1).  We did 3.9.1 on July 4 and 3.9.0 on May 15 so that means we likely got delvewheel 1.6.0 for mpl3.9.0 and 1.7.1 for mpl3.9.1.

It looks like pybinb11 had release on Mar 27 (2.12.0), Jun 25 (2.13.0) and Jun 26 (2.13.1) which means we likely got 2.12.0 for mpl3.9.0 and 2.13.1 for mpl3.9.1.  However, given that locally built wheels work (and CI has kept working), I am a bit skeptical that it is pybind11 alone.  However, I do have some concern that there could be some interaction between c-extensions using pybind11 with different versions of pybind11 conflicting with each other.  I have never seen any discussion of this being a concern and I trust the pybind11 devs that if this _were_ a known issue they would make it well known, but I do not actually understand how pybind11 works well enough to to explain why it is not a possible problem so would like my assumption checked.


Open technical question:
 - do we see this problem with 3.9.1 from conda-forge?
 - if a working locally built wheel is run through `delvewheel` does it then break? If so, can you try multiple versions to see if that affects it.
 - does changing the version of pybind11 used locally have any affect?
 - if we put the minimal example in our test suite, do our windows builds start failing?  I suspect not, but we should check (I'll do that right after I post this comment)

Open policy question:

 - should we remove the windows 3.9.1 wheels from pypi?

I'm going to put this on our meeting agenda for the call today.

**Comment by ianthomas23** [comment] 2024-08-01 16:52
Some other thoughts:

- version of MSVC probably changed between builds of 3.9.0 and 3.9.1
- Matplotlib is unusual in having some extensions that use pybind11 and some that don't.

**Comment by ksunden** [comment] 2024-08-01 17:58
The dll that is added by delvewheel is identical between mpl 3.9.0 and mpl 3.9.1, which makes it hard to point to that as the problem source... As is the patch inserted in `__init__.py` (aside from the function naming, which references the delvewheel version, which were indeed different (1.7.1 on mpl 3.9.1, 1.6.0 on 3.9.0))

Looking at the commits to delvewheel between the two versions indicates the addition/renaming of two cli args, which we do not use and are not turned on by default, testing/doc changes, and support for 3.13 (which is just adding the build tags to a list of available tags). None of these seem likely to me to cause differences in behavior that would be more subtle than are ruled out by checking the dll hashes.

Therefore I am reasonably convinced delvewheel is not the culprit, at least not on its own/the build chain change that _directly_ caused the problem.

However, that is the biggest difference between the wheels as uploaded to pypi and the wheel that you build by default, so I mean that leaves some room for pybind11 (/mixing pybind11 and non-pybind11) but not a _whole_ lot of room.

**Comment by QuLogic** [comment] 2024-08-01 20:15
On a completely fresh Windows 10 VM with only Python 3.12 installed, trying to import `contourpy` gives me `ImportError: DLL load failed while importing _contourpy: The specified module could not be found.` This is likely to be the MSVC runtime; perhaps `contourpy` should run delvewheel as well so it has its own copy that won't cause these weird conflicts?

**Comment by QuLogic** [comment] 2024-08-01 20:35
Looking at the file in Dependency Walker, it appears that the `_contourpy` extension is missing `msvcp140.dll`, so I installed the latest VC redistributable (14.40.33810.0), but then I could not reproduce the problem. Perhaps it has to do with having an older version of the redistributable already installed on your system? Or maybe it's only to do with conda's Python? I will try the latter next.

**Comment by HDembinski** [comment] 2024-08-01 22:40
I guess there is not much too add by saying this, but iminuit is also affected, which in turn is used by many other libraries https://github.com/scikit-hep/iminuit/pull/1018

**Comment by tacaswell** [comment] 2024-08-02 02:16
Can someone test the wheels generated by Chttps://github.com/matplotlib/matplotlib/actions/runs/10204731582?pr=28635 and https://github.com/matplotlib/matplotlib/actions/runs/10204565050?pr=28637 ?

We earlier confirmed that pinning delvewheel back does not fix the problem.

**Comment by ianthomas23** [comment] 2024-08-02 09:32
> On a completely fresh Windows 10 VM with only Python 3.12 installed, trying to import `contourpy` gives me `ImportError: DLL load failed while importing _contourpy: The specified module could not be found.` This is likely to be the MSVC runtime; perhaps `contourpy` should run delvewheel as well so it has its own copy that won't cause these weird conflicts?

This is worth investigating, but it is a distraction from the actual problem:

1. The problem is in Matplotlib not ContourPy, so no change to ContourPy can fix this.
2. Changes to wheel building of any downstream packages cannot fix the problem either, they need to be able to install from source (so never going near delvewheel) in the presence of the faulty Matplotlib install.

**Comment by ianthomas23** [comment] 2024-08-02 09:32
> Can someone test the wheels generated by https://github.com/matplotlib/matplotlib/actions/runs/10204731582?pr=28635 and https://github.com/matplotlib/matplotlib/actions/runs/10204565050?pr=28637 ?
> 
> We earlier confirmed that pinning delvewheel back does not fix the problem.

It didn't fix the problem.

**Comment by ianthomas23** [comment] 2024-08-02 09:59
There is progress to report here, but accidental. Reproducers that failed for me 15 hours ago are now passing. If you look at the last 2 GHA runs of my `mpl-test` repo (~15 hours ago https://github.com/ianthomas23/mpl-test/actions/runs/10195870963/job/28205423852 and ~1 hour ago https://github.com/ianthomas23/mpl-test/actions/runs/10212785471/job/28256840836) both fail when using Matplotlib 3.9.1 and ContourPy nightly wheel, but the run using both Matplotlib and ContourPy nightly wheels failed 15 hours ago and passed 1 hour ago. There is no change to the ContourPy nightly wheel in that time, but there is a new Matplotlib nightly wheel. They use different `windows-2022` runners: `20240721.1.0` and `20240729.2.0`. It would be good to confirm the runner version that the new Matplotlib nightly wheel was created on.

So as of now I can use the Matplotlib nightly wheel without problems on Windows, but not 3.9.1. I've run the full ContourPy test suite on this (contourpy/contourpy#413) to confirm this. If I was to exclude use of Matplotlib 3.9.1 on Windows all CI runs would pass.

What is the difference between the 3.9.1 and nightly wheels? The `msvcp140.dll` added by `delvewheel` have changed, it has gone from 621960 bytes to 618728, so it is definitely a different file.

I don't know the cause of the problem, but I suspect it relates to a problem that consumed lots of developer time a couple of months ago when the Windows github runner shipped MSVC runtimes that weren't fully back/forward compatible. There are many issues about this e.g. runner-images#10055. I suspect that Matplotlib 3.9.1 was shipped after being built on one of these less-than-ideal images. The problem was supposed to be fixed but given the amount of ongoing chat about this I suspect it wasn't. Perhaps we were just unlucky in timing then, and are now lucky that the runner images have been updated.

I propose the following plan:

1. Yank the 3.9.1 Windows wheels from PyPI to minimise the damage and loss of goodwill in downstream projects.
2. Confirm that the new nightly wheels do work for other downstream projects.
3. Release 3.9.2.

For item 2 for downstream projects (possibly @BertJorissen, @nquetschlich and @HDembinski) you can try out the nightly wheels instead of Matplotlib 3.9.1 by using the following in your CI runs between your build and test stages:
```bash
python -m pip install --only-binary=:all: --upgrade --pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple matplotlib
```

**Comment by BertJorissen** [comment] 2024-08-02 10:47
The nightly build seems to work with my minimal example and the tests within the package https://github.com/BertJorissen/mplpb11/actions/runs/10214271146/job/28261320706 .

**Comment by tacaswell** [comment] 2024-08-02 13:58
I don't think we can yank individual wheels, only the whole release.  Yanking the whole release seems overkill, but we can delete the individual wheels.

Agree on doing a 3.9.2 ASAP.

**Comment by tacaswell** [comment] 2024-08-02 14:05
> It didn't fix the problem.

That is in some sense good news because one of them was 3.9.0 rebuilt with the newer versions of cibuildwheel so it eliminates that and supports the "its the runners" theory.

**Comment by QuLogic** [comment] 2024-08-03 06:40
Note that nightly wheels come from the `main` branch; releases will come from the `v3.9.x` branch. [This is the latest build](https://github.com/matplotlib/matplotlib/actions/runs/10218295005) on that branch. It was built after the nightly that worked, so if it's a CI runner issue, it _should_ also work, but best to confirm.

**Comment by jackjansen** [comment] 2024-08-03 12:37
I'm so happy I found this issue! Same problem for me: something completely different was failing in the GitHub runners, but only in Python test programs, and only in some very few Python test programs.

For whoever gets here in the future: this is my analysis of what is happening:

If and only if Matplotlib is loaded into your running program before something else, that will cause a "faulty" version of `msvcp140.dll` to be loaded into your process, and that will subsequently cause a segmentation violation somewhere completely different, when you try to load a DLL that has been built against a newer version of the MSVC runtime.

"faulty" requires a bit of explanation: `msvcp140.dll` versions are backward compatible but not forward compatible. And last May Microsoft has made an incompatible change to the VC++ runtime. That causes any program or DLL that is built against the newest VC++ runtime to crash with a null pointer reference if at runtime it is given an mvscp140 that is too old.

**Comment by tacaswell** [comment] 2024-08-04 00:55
I have deleted the windows wheels (I removed the pypy one as well given @jackjansen 's analysis I assume it will be as broken as the CPython ones).

**Comment by tacaswell** [comment] 2024-08-04 01:05
```
matplotlib-3.9.1-cp310-cp310-win_amd64.whl@sha256:421851f4f57350bcf0811edd754a708d2275533e84f52f6760b740766c6747a7
matplotlib-3.9.1-cp311-cp311-win_amd64.whl@sha256:a0c977c5c382f6696caf0bd277ef4f936da7e2aa202ff66cad5f0ac1428ee15b
matplotlib-3.9.1-cp312-cp312-win_amd64.whl@sha256:44a21d922f78ce40435cb35b43dd7d573cf2a30138d5c4b709d19f00e3907fd7
matplotlib-3.9.1-cp39-cp39-win_amd64.whl@sha256:dc23f48ab630474264276be156d0d7710ac6c5a09648ccdf49fef9200d8cbe80
matplotlib-3.9.1-pp39-pypy39_pp73-win_amd64.whl@sha256:f1f2e5d29e9435c97ad4c36fb6668e89aee13d48c75893e25cef064675038ac9

```

is what I deleted and I just downloaded a copy from GHA of the zip that was built if anyone really wants those files again.

**Comment by bwoodsend** [comment] 2024-08-04 14:27
Deleting the wheels without also deleting the sdist or yanking the whole version has made the situation worse. Now matplotlib silently builds from source which results in more confusing issues. Just
```yaml
      - uses: actions/setup-python@v3
      - run: pip install matplotlib
      - run: python -c "import matplotlib"
```
causes:
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\hostedtoolcache\windows\Python\3.12.4\x64\Lib\site-packages\matplotlib\__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\hostedtoolcache\windows\Python\3.12.4\x64\Lib\site-packages\matplotlib\cbook.py", line 32, in <module>
    from matplotlib import _api, _c_internal_utils
ImportError: DLL load failed while importing _c_internal_utils: The specified module could not be found.
```

**Comment by joshuacwnewton** [comment] 2024-08-04 15:31
> Deleting the wheels without also deleting the sdist or yanking the whole version has made the situation worse. Now matplotlib silently builds from source which results in more confusing issues. 

+1. We received a different error when trying to build from source on our Windows runners, though:

```
Collecting matplotlib (from -r requirements.txt (line 11))
  Downloading matplotlib-3.9.1.tar.gz (36.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [11 lines of output]
  + meson setup C:\Users\runneradmin\AppData\Local\Temp\pip-install-f9q65a7v\matplotlib_7323a6cc9d9440d5845338664df0016b C:\Users\runneradmin\AppData\Local\Temp\pip-install-f9q65a7v\matplotlib_7323a6cc9d9440d5845338664df0016b\.mesonpy-zrshzjfo -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\runneradmin\AppData\Local\Temp\pip-install-f9q65a7v\matplotlib_7323a6cc9d9440d5845338664df0016b\.mesonpy-zrshzjfo\meson-python-native-file.ini
  The Meson build system
  Version: 1.5.1
  Source dir: C:\Users\runneradmin\AppData\Local\Temp\pip-install-f9q65a7v\matplotlib_7323a6cc9d9440d5845338664df0016b
  Build dir: C:\Users\runneradmin\AppData\Local\Temp\pip-install-f9q65a7v\matplotlib_7323a6cc9d9440d5845338664df0016b\.mesonpy-zrshzjfo
  Build type: native build
  Program python3 found: YES (C:\hostedtoolcache\windows\Python\3.7.9\x64\python3.EXE)
  
  ..\meson.build:4:11: ERROR: Command `C:\hostedtoolcache\windows\Python\3.7.9\x64\python3.EXE -m setuptools_scm` failed with status 1.
  
  A full log can be found at C:\Users\runneradmin\AppData\Local\Temp\pip-install-f9q65a7v\matplotlib_7323a6cc9d9440d5845338664df0016b\.mesonpy-zrshzjfo\meson-logs\meson-log.txt
  [end of output]
```

(CI run producing this error: https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/10235678007/job/28319913582#step:3:169)

**Comment by SoftologyPro** [comment] 2024-08-04 17:51
This also causes all gradio pip installs to fail on Windows.
I have a lot of Python environments that use gradio that now fail to install because gradio specifies an inexact version of matplotlib which triggers this build issue.
So hopefully a new 3.9.2 will fix this.  It trickles down and kills a lot of other systems/code/etc.

**Comment by tacaswell** [comment] 2024-08-04 19:40
Sigh of the options:

 - re-upload the wheel-that-cause-segfaults (with a new name) - no, we should not publish wheels that can cause sugfaults
 - re-run the GHA that generates the wheels for 3.9.1 and 🤞🏻 that it will run on the new image that fixed it self and upload them with a new name - maybe, I'll go push the button to start that, but I will need someone with a windows machine to verify it is working
 - yank the whole release - easy, but seems completely backwards to yank the release for everyone due to a binary artifact issue on one platform


-----

In the short term, if people want to fix this on their side while we sort out what to do you can:

 - explicitly skip 3.9.1 via `matplotlib!=3.9.1` (I suspect there is also a way to make the platform dependent, but I don't know how off the top of my head)
 - add `--only-binary matplotlib` to the dependencies (this is probably a good idea for all packages with extensions that you are not prepared to build from source)

**Comment by tacaswell** [comment] 2024-08-04 19:45
ok, I can not figure out how to re-run the job :( 

https://github.com/matplotlib/matplotlib/actions/runs/9789558015 in the original run.

**Comment by giswqs** [comment] 2024-08-04 23:41
I just ran into the same issue with CI failures on Windows. 

> ImportError: DLL load failed while importing _c_internal_utils: The specified module could not be found.

**Comment by tacaswell** [comment] 2024-08-05 01:00
A secondary question is why is the failure mode failure on import and not a build failure.

**Comment by tacaswell** [comment] 2024-08-05 01:07
Incase it get lost 

```
Current runner version: '2.317.0'
Operating System
Runner Image
  Image: windows-2022
  Version: 20240630.1.0
  Included Software: https://github.com/actions/runner-images/blob/win22/20240630.1/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240630.1
Runner Image Provisioner
  2.0.370.1
```

Is the runner image version for the build that produced the broken wheels.

**Comment by tacaswell** [comment] 2024-08-05 01:43
It looks like we can not re-run it:

```
@ gh run rerun 9789558015
run 9789558015 cannot be rerun; its workflow file may be broken
```

```
@ gh run rerun -j 27029515400
job 27029515400 cannot be rerun
```

so that looks like it takes option 2 off the table which leaves the worst option of "yanking" as a the only solution I think we can get done before open-of-business Monday for most of the world (well, we are already past that in AU and CN) so I am going to make the executive decision to yank 3.9.1 and try to get 3.9.2 out ASAP.

**Comment by tacaswell** [comment] 2024-08-05 02:43
Follow on tasks:

 1. get 3.9.2 tagged and out
 2. verify that https://github.com/matplotlib/matplotlib/issues/28551#issuecomment-2266699619 is indeed the correct explanation of the segfaults and verify that both cibuildwheel and delvewheel are in fact blameless here.
 3. update our documentation to indicated that Matplotlib is put in a requirements file for CI it should include `--prefer-binary` or `--only-binary "matplotlib"` to harden CI against a missing wheel (I think this is good advise for any dependency with an extension that you are not prepared to build from source)
 4. start a conversation with PyPA (not sure exactly which project and/or in https://discuss.python.org yet) about:
    1. What can be done to prevent us from ending up in the condition again?  We got bitten by this, but I do not think there is anything specific to Matplotlib about the underlying issue (assume the answer to 2 is "yes").
    2. When something like this happens again (wheels for a sub-set of the platforms have fatal issues, but everything else is fine), what is the correct short-term corrective action?  It is pretty clear that "delete the bad wheels" is experimentally not the correct solution, but "yank the whole release" also seems like it has an order of magnitude too big of an impact and can not be the preferred solution.
 5. sort out why the failure users are reporting is `importing _c_internal_utils: The specified module could not be found` as a) building failing on CI should have failed a lot earlier b) we should not be installing a partially built version of Matplotlib.  I would believe that the issue is in our config, menson/meson-python, or pip 
 6. Can we adjust the cibuildwheel job for tags to have a button of "re-run, but as postN"?  I guess worst-case scenario we have an orphan branch (or another repo) that only has a GHA workflow on it that pulls the sdist from pypi, run each of the cibuildwheel workers, is configured in source with `N`, and has the keys to auto-upload to pypi.
 7. If we can sort out a way to get post1 wheels built for windows upload them and unyank 3.9.1


------

I also think that this whole episode highlights a number of the meta topics and key issues identified in https://pypackaging-native.github.io .  I know there was some discussion of PSF moderating the PyPA discussions to make progress, hopefully one positive outcome of this issue will be to provide non-hypothetical of things that can go wrong.

**Comment by tacaswell** [comment] 2024-08-05 02:56
https://github.com/shap/shap/pull/3776#issuecomment-2267538091 may be of interest to point 5 above.

**Comment by joshuacwnewton** [comment] 2024-08-05 03:07
_(As a side note: Thank you for taking time out of your weekend to handle this issue. I know open source maintenance can be a thankless, stressful job, especially given the exposure to unsolicited downstream feedback. I hope that this has not been too stressful for you. I appreciate all the work you have done in helping to maintain `matplotlib` for this community. :hearts:)_

**Comment by bwoodsend** [comment] 2024-08-05 08:04
> but "yank the whole release" also seems like it has an order of magnitude too big of an impact and can not be the preferred solution.

I imagine that there are a lot more Windows users running `pip install matplotlib` than there are people who specifically need 3.9.1.

Although perhaps deleting the sdist too would have been a workable middle ground.

**Comment by cocktailpeanut** [comment] 2024-08-05 12:57
hi, is there an ETA for the resolution of this issue?

**Comment by tacaswell** [comment] 2024-08-05 13:10
@cocktailpeanut With 3.9.1 yanked unless you are pinning `==3.9.1` and unable to build from source on windows you should not see this.

**Comment by cocktailpeanut** [comment] 2024-08-05 16:36
@tacaswell thank you! checked them all and confirmed everything is back to normal!

**Comment by SoftologyPro** [comment] 2024-08-06 04:15
Thank you for the rapid fix.  I can confirm it fixes my issues too.  Saves me editing loads of scripts and environments to fix it.

**Comment by tacaswell** [comment] 2024-08-06 14:09
To expidite getting 3.9.2 out today can someone please confirm that the wheels linked in https://github.com/matplotlib/matplotlib/issues/28551#issuecomment-2266526260 (a build from the 3.9.x branch that is built with the updated runner image) works?  It would be less than ideal to do the release and then have to do this whole thing again.

**Comment by ianthomas23** [comment] 2024-08-06 15:15
I've tested all the Windows wheels from https://github.com/matplotlib/matplotlib/issues/28551#issuecomment-2266526260, including the PyPy ones, against both the latest ContourPy nightly wheels and a local build, and they are all working correctly.

**Comment by QuLogic** [comment] 2024-08-06 19:54
> Can we adjust the cibuildwheel job for tags to have a button of "re-run, but as postN"? I guess worst-case scenario we have an orphan branch (or another repo) that only has a GHA workflow on it that pulls the sdist from pypi, run each of the cibuildwheel workers, is configured in source with `N`, and has the keys to auto-upload to pypi.

Since we've determined that there are no changes needed to how we build things, nor to `cibuildwheel`, yes! But we don't need to change the job, just tag a `postN` tag on the same commit as `v3.9.1`. I've done that now, and in a few hours once it's built, there should be working 3.9.1.post0 wheels available. Since I've enabled environment confirmations, we can confirm again once those are built before uploading to PyPI.

In the meantime, I'll work on getting 3.9.2 finished.

**Comment by QuLogic** [comment] 2024-08-06 20:00
@ianthomas23 do you think we should be defining `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` as well (as you did in https://github.com/contourpy/contourpy/pull/414)?

**Comment by QuLogic** [comment] 2024-08-06 20:09
> I've done that now, and in a few hours once it's built, there should be working 3.9.1.post0 wheels available. Since I've enabled environment confirmations, we can confirm again once those are built before uploading to PyPI.

The Windows wheels for `v3.9.1.post0` are [already built here](https://github.com/matplotlib/matplotlib/actions/runs/10272980428) if anyone wants to double check.

**Comment by tacaswell** [comment] 2024-08-06 20:18
> just tag a postN tag on the same commit as v3.9.1.

That is delightfully simple but did not occur to me!

**Comment by QuLogic** [comment] 2024-08-06 21:07
> > just tag a postN tag on the same commit as v3.9.1.
> 
> That is delightfully simple but did not occur to me!

Alas, perhaps a bit too simple, as something (probably `setuptools-scm`) only saw the first tag, and gave the sdist/wheels the wrong version. I will try one more time against the Zenodo commit, but if not, 3.9.2 will work.

**Comment by ianthomas23** [comment] 2024-08-06 21:11
> @ianthomas23 do you think we should be defining `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` as well (as you did in [contourpy/contourpy#414](https://github.com/contourpy/contourpy/pull/414))?

No, I don't think we should. It only has an effect if using a C++ `std::mutex` and there is no use of this directly in Matplotlib. There is one in pybind11 but not in a codepath that we use. So there is no logical reason to do so. I confess that I am not 100% confident of this given the DLL swapping/sharing that we've experienced over the last couple of weeks, but I cannot bring myself to suggest that we should define it just in case without a concrete reason to do so. I will be watching this closely though.

**Comment by QuLogic** [comment] 2024-08-06 22:01
The 3.9.1.post1 wheels are [now available on PyPI](https://pypi.org/project/matplotlib/3.9.1.post1/).

**Comment by ianthomas23** [comment] 2024-08-07 10:27
This hasn't fully fixed the problem, we now have some strange interaction with delvewheel, or maybe we always did. Using the released 3.9.1.post1 wheels or the latest nightly wheels with contourpy nightly wheels in the manual tests that myself and @story645 tried does work. But using either mpl 3.9.1.post1 or nightly wheels and compiling contourpy from source gives segmentation faults still. I've added an extra test to my simple reproducer repository https://github.com/ianthomas23/mpl-test/actions/runs/10282014029 to show this.

So the good news is that end users probably aren't affected here if they install wheels, it is only compiling other libraries from source that is a problem. It would be good to confirm this, perhaps @BertJorissen could check using the 3.9.1.post1 wheels?

There was one mpl nightly wheel for which everything worked for me which was [3.10.0.dev513+g109ab93ba2](https://github.com/matplotlib/matplotlib/actions/runs/10227059586/job/28298087600). The latest one [3.10.0.dev524+ga00a714bd0](https://github.com/matplotlib/matplotlib/actions/runs/10272282149/job/28424163560) fails as does 3.9.1.post1 built around the same time. What is the difference? Both nightly builds used runner version `2.317.0`, image `windows-2022` version `20240729.2.0`. The good one used delvewheel `1.7.2` and the bad one `1.7.3`. The MSVC DLLs that delvewheel added to them have identical size and hash, but in the good wheel it is called `msvcp140.dll` and in the bad wheel `msvcp140-cb1364a8f14ec1d3687d6faef0fd327e.dll`. There has been quite some action on DLL name mangling in `delvewheel` recently with 1.7.2 released on 1 August (allowing all my tests to pass) and 1.7.2 on 6 August (when they started failing again). Unfortunately the [delvewheel repo](https://github.com/adang1345/delvewheel) has a policy of pushing directly to `master` branch rather than using PRs so the changes don't have much attached explanation.

Incidentally @tacaswell's task 5 above about `importing _c_internal_utils: The specified module could not be found` is related, this is the problem that delvewheel 1.7.3 was released to solve. 

I am going to submit a draft PR to try building Matplotlib wheels with `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` set, just in case. I will also open an issue on delvewheel about this.

**Comment by BertJorissen** [comment] 2024-08-07 11:54
The `3.9.1.post1` and the nightly build (with the installation with pip as given before) [both fail](https://github.com/BertJorissen/mplpb11/actions/runs/10283679041/job/28458044794).
The nightly build [was working before](https://github.com/BertJorissen/mplpb11/actions/runs/10214271146/job/28261320942).
I used both a pre-compiled version of my program and a test program that is compiled within the action, both failed.

**Comment by tacaswell** [comment] 2024-08-07 16:50
@BertJorissen If you are building a wheel, can you also run delvewheel?

**Comment by ksunden** [comment] 2024-08-07 18:38
See here for a rundown of the extremely unfortunate timing of some changes in delvewheel:

https://github.com/adang1345/delvewheel/issues/52#issuecomment-2274093747

Literally, immediately after we reasoned that delvewheel was not the direct cause, they released a version which changed behavior to at least hide the problems (not sure if we would expect _other_ problems or not). And after we tested `.post0` but before cutting `.post1`, they released a reversion of that change.

**Comment by igurin-invn** [comment] 2024-08-07 23:14
Thank you for fixing this so quickly! I did have `matplotlib>=3.9.1` because of a bug in 3.9.0.

**Comment by QuLogic** [comment] 2024-08-08 09:39
> sort out why the failure users are reporting is `importing _c_internal_utils: The specified module could not be found` as a) building failing on CI should have failed a lot earlier b) we should not be installing a partially built version of Matplotlib. I would believe that the issue is in our config, menson/meson-python, or pip

This is a combination of the GitHub runner environment, and security changes in Python. On the runners, the mingw compilers are available on the `PATH`, and so Meson defaults to using them. They link dynamically to their standard C and C++ libraries, which are in the same directory. However, as of [Python 3.8](https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew), `PATH` is disabled for DLL searching, and so their libraries are not found. You could work around this (if building from source) [by adding the mingw directory to the DLL search path](https://github.com/QuLogic/mplpb11/actions/runs/10295536408/job/28495358980#step:8:2). Alternatively, you could [pass `--vsenv` to have Meson prefer MSVC](https://github.com/QuLogic/mplpb11/actions/runs/10295748733/job/28495946375#step:4:4). However, since installing from source is not how we expect users to install Matplotlib, this is not likely something to recommend in general.

I did manage to find and fix a few warnings while debugging this, which are in #28682.

I also [prepared a job with extra debugging](https://github.com/QuLogic/mplpb11/actions/runs/10299493111/job/28506878410); from there I see we load:
- `C:\hostedtoolcache\windows\Python\3.12.4\x64\VCRUNTIME140.dll`
- `C:\hostedtoolcache\windows\Python\3.12.4\x64\Lib\site-packages\_pyerror.cp312-win_amd64.pyd`
- `C:\hostedtoolcache\windows\Python\3.12.4\x64\VCRUNTIME140_1.dll`
- `C:\Windows\SYSTEM32\MSVCP140.dll`
- `C:\hostedtoolcache\windows\Python\3.12.4\x64\Lib\site-packages\matplotlib\_c_internal_utils.cp312-win_amd64.pyd`
- `C:\hostedtoolcache\windows\Python\3.12.4\x64\Lib\site-packages\matplotlib.libs\msvcp140-cb1364a8f14ec1d3687d6faef0fd327e.dll`
- `C:\hostedtoolcache\windows\Python\3.12.4\x64\Lib\site-packages\matplotlib\_path.cp312-win_amd64.pyd`
- `C:\hostedtoolcache\windows\Python\3.12.4\x64\Lib\site-packages\matplotlib\ft2font.cp312-win_amd64.pyd`
- `C:\hostedtoolcache\windows\Python\3.12.4\x64\Lib\site-packages\kiwisolver\_cext.cp312-win_amd64.pyd`

And surprisingly, this is where we crash, sometime after locating `PyInit__cext` from kiwisolver. Unfortunately, the debugger does not stop properly and I couldn't find how to easily print a traceback automatically.

**Comment by Sedeniono** [comment] 2024-08-08 14:46
In case it helps, I originally debugged the crashes on the GitHub runners due to the Microsoft STL update by creating crash dumps via procmon and uploading them as artifacts. See [here](https://gist.github.com/Sedeniono/e6d6504e3bf0645937852ee5681ef9ee) for an example. The crash dumps can be opened in Visual Studio or WinDbg.

**Comment by QuLogic** [comment] 2024-08-13 01:48
3.9.2 is tagged now, and I confirmed that [the wheels worked on Windows again](https://github.com/QuLogic/mplpb11/actions/runs/10361620251) via @BertJorissen's workflow, so pushed them to PyPI. As #28687 was also confirmed to work by @ianthomas23, I'm to close this issue, hopefully for good this time.

**Closed by QuLogic** 2024-08-13 01:48 UTC
Labels: status: confirmed bug, Release critical, third-party integration: contourpy

**Comment by jfuruness** [comment] 2024-09-12 07:41
On github actions, on windows, using pypy3 and matplotlib 3.9.2,  I get what seems to be the same error. Oddly though, I only get the error on certain repos of mine that use matplotlib, and not others:

```
  .tox\pypy3\lib\site-packages\matplotlib\__init__.py:159: in <module>
      from . import _api, _version, cbook, _docstring, rcsetup
  .tox\pypy3\lib\site-packages\matplotlib\cbook.py:32: in <module>
      from matplotlib import _api, _c_internal_utils
  E   ImportError: The specified module could not be found
  ```

**Comment by tacaswell** [comment] 2024-09-12 13:04
@jfuruness I suspect your issues is that you are using pypy310 which we do not provide wheels for (yet) and something is going wrong with your local build.  Please see the install docs on building from source on windows.

**Comment by jfuruness** [comment] 2024-09-13 06:56
@tacaswell Ah I didn't realize, thank you for the explanation. Looking at a few of the past prior releases I don't see wheels for pypy310, is there a plan to add these in the future (and perhaps a gh issue I could follow)?

**Comment by QuLogic** [comment] 2024-09-13 07:00
We are waiting for NumPy wheels https://github.com/numpy/numpy/issues/24728

**Comment by jfuruness** [comment] 2024-09-13 07:05
@QuLogic Ah makes sense, sounds good! Thank you both for you support of matplotlib!
