### ISSUE TITLE
nbagg (%matplotlib notebook) renderer doesn't set .mpl-canvas height and width properly in style-attribute

### ISSUE THREAD

**Issue by prinsherbert** [matplotlib/matplotlib#18218] opened 2020-08-11 11:42 UTC
**Note:** I've solved this with a monkey-patch, but wanted to share anyway.

matplotlib 3.3.0, python 3.7.8 and jupyter 1.0.0

Plots wouldn't render properly as the HTML-canvas .mpl-canvas would have "undefinedpx" height and width. The culpitt is in the two lines I'll mention soon.

```python
%matplotlib notebook

from matplotlib import pyplot

pyplot.figure(figsize=(4, 4))
pyplot.plot([1, 2, 3, 2])
```

I've used console.log(...) to debug and noticed `entry.contentBoxSize` in the code below would be a list of one item, instead that idem directly. Hence I monkey-patched a `[0]` in two lines in `.virtualenvs/my-environment/lib/python3.7/site-packages/matplotlib/backends/web_backend/js/mpl.js` as a fix.

```javascript
                width = entry.contentBoxSize[0].inlineSize;
                height = entry.contentBoxSize[0].blockSize;
```

I'm clueless what exactly I've done and whether it makes sense, but it solved the problem. 

I've also noticed that there's nothing similar to the code mentioned in the current [head of github](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/web_backend/js/mpl.js), so probably this will resolve itself within the next update.

I just wanted to share, in case some else runs into this issue or future-me.

This is the relevant code-snippet of `matplotlib/backends/web_backend/js/mpl.js` that I needed to change.

```javascript
    var resizeObserver = new ResizeObserver(function (entries) {
        var nentries = entries.length;
        for (var i = 0; i < nentries; i++) {
            var entry = entries[i];
            var width, height;
            if (entry.contentBoxSize) {
                width = entry.contentBoxSize.inlineSize;
                height = entry.contentBoxSize.blockSize;
            } else {
                width = entry.contentRect.width;
                height = entry.contentRect.height;
            }

            // Keep the size of the canvas and rubber band canvas in sync with
            // the canvas container.
            canvas.setAttribute('width', width * mpl.ratio);
            canvas.setAttribute('height', height * mpl.ratio);
            canvas.setAttribute(
                'style',
                'width: ' + width + 'px; height: ' + height + 'px;'
            );

            rubberband_canvas.setAttribute('width', width);
            rubberband_canvas.setAttribute('height', height);

            // And update the size in Python. We ignore the initial 0/0 size
            // that occurs as the element is placed into the DOM, which should
            // otherwise not happen due to the minimum size styling.
            if (width != 0 && height != 0) {
                fig.request_resize(width, height);
            }
        }
    });
```

**Comment by QuLogic** [comment] 2020-08-11 19:48
This is a duplicate of #18132, and will be fixed in 3.3.1.

**Closed by QuLogic** 2020-08-11 19:48 UTC
