### ISSUE TITLE
[Bug]: hatch inconsistency between PDF and png

### ISSUE THREAD

**Issue by caizixian** [matplotlib/matplotlib#22862] opened 2022-04-19 07:09 UTC
### Bug summary

When drawing with hatches, dots show up in PDF as circles but they render fine as PNGs.

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(6, 3))
ax.bar([1], height=4, hatch=".")
plt.savefig("demo.pdf")

fig, ax = plt.subplots(figsize=(6, 3))
ax.bar([1], height=4, hatch=".")
plt.savefig("demo.png", dpi=300)
```

### Actual outcome

**PDF**
[demo.pdf](https://github.com/matplotlib/matplotlib/files/8510681/demo.pdf)
PDF converted as png
![demo](https://user-images.githubusercontent.com/2891235/163945882-3d67e72c-b27b-42e1-b4f9-991da8dcacaf.png)

**PNG**
![demo](https://user-images.githubusercontent.com/2891235/163945922-f9407bd2-ebd6-4693-af55-ebbeeede0f87.png)

### Expected outcome

The PNG and the PDF should look the same.

### Operating system

macOS 12.3.1

### Matplotlib Version

3.4.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline (inside jupyter notebook), PDF backend when generating PDF

### Python version

Python 3.8.9

### Jupyter version

6.4.0

### Installation

pip

**Comment by oscargus** [comment] 2022-04-19 08:03
This seems to be a problem for filled hatches. Same with '*'.

**Comment by banarni** [comment] 2022-07-04 07:40
Just an additional observation for the backend-experts: A custom patch without facecolor is rendered correctly. Additionally, an edgecolor is only necessary for png export, not for pdf.

## Code
```python
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

fig, ax = plt.subplots(figsize=(6, 3))
bar = ax.bar([1], height=4, hatch=".", label="auto")
patch_custom_1 = Patch(label="custom - with fc", hatch=".", edgecolor="k")
patch_custom_2 = Patch(label="custom - without fc", hatch=".", edgecolor="k", facecolor="None")
patch_custom_3 = Patch(label="custom - without fc and ec", hatch=".", edgecolor="None", facecolor="None")

leg = plt.legend(handles=[bar, patch_custom_1, patch_custom_2, patch_custom_3], labelspacing=2, borderpad=1)
for patch in leg.get_patches():
    patch.set_height(20)
    patch.set_y(-7)

plt.xlim([0, 5])
plt.savefig("demo.pdf")

fig, ax = plt.subplots(figsize=(6, 3))
bar = ax.bar([1], height=4, hatch=".", label="auto")
patch_custom_1 = Patch(label="custom - with fc", hatch=".", edgecolor="k")
patch_custom_2 = Patch(label="custom - without fc", hatch=".", edgecolor="k", facecolor="None")
patch_custom_3 = Patch(label="custom - without fc and ec", hatch=".", edgecolor="None", facecolor="None")

leg = plt.legend(handles=[bar, patch_custom_1, patch_custom_2, patch_custom_3], labelspacing=2, borderpad=1)
for patch in leg.get_patches():
    patch.set_height(20)
    patch.set_y(-7)

plt.xlim([0, 5])
plt.savefig("demo.png", dpi=300)
```
## Output

**PDF** ([demo.pdf](https://github.com/matplotlib/matplotlib/files/9037158/demo.pdf))
<img width="796" alt="demo_pdf" src="https://user-images.githubusercontent.com/81868387/177105478-3e0b897a-8c41-4bcb-ae80-eb8ab35c8f8f.png">


**PNG**
![demo](https://user-images.githubusercontent.com/81868387/177105568-494261ae-fff1-492e-a1a5-cabdbe7d1c71.png)

**Comment by QuLogic** [comment] 2022-07-04 23:24
This is a duplicate of #10034.

**Closed by QuLogic** 2022-07-04 23:24 UTC
Labels: status: confirmed bug, backend/pdf, topic: hatch
