### ISSUE TITLE
calling plt.hist() with np.nan value raises confusing error massage

### ISSUE THREAD

**Issue by mordoron** [matplotlib/matplotlib#8105] opened 2017-02-20 05:03 UTC
### Bug report

**Bug summary**

When calling plt.hist(a), with a containing a np.nan value, the error raised is:
"max must be larger than min in range parameter."
 This is confusing especially for novice users unfamiliar with the fact that np.nan>x is True for any number x. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
plt.hist([1,2,3,np.nan])

```
**Actual outcome**
C:\Continuum\Anaconda2\lib\site-packages\numpy\lib\function_base.pyc in histogram(a, bins, range, normed, weights, density)
    664     if mn > mx:
    665         raise ValueError(
--> 666             'max must be larger than min in range parameter.')
    667     if not np.all(np.isfinite([mn, mx])):
    668         raise ValueError(

ValueError: max must be larger than min in range parameter.```

**Expected outcome**

ValueError: values in histogram contains nan```

**Matplotlib version**
 matplotlib version 1.5.3
python version python 2.7 - 1.12.0 for windows 64 bit
- How did you install Matplotlib and Python (pip, anaconda, from source ...)
Anaconda installation

**Comment by anntzer** [comment] 2017-02-20 06:30
Duplicate of https://github.com/matplotlib/matplotlib/issues/6483.

**Closed by anntzer** 2017-02-20 06:30 UTC
