### ISSUE TITLE
'ctrl-w' keybinding in wx causes segfault

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#5354] opened 2015-10-29 17:53 UTC
Closing a wxagg figure window with 'ctrl-w' results in a segfault.  Closing the window via pyplot (`plt.close('all')`) works correctly as does closing the window directly via the OS window manager.

I suspect that somehow we are trying to clean up some c++ objects twice.

**Comment by jenshnielsen** [comment] 2015-10-29 19:49
I think this issue is related to #3316

**Comment by jenshnielsen** [comment] 2015-12-09 14:39
Unfortunatly this still happens

**Comment by story645** [comment] 2016-06-01 08:03
is this a dupe of #3690?

**Comment by jenshnielsen** [comment] 2016-06-01 08:32
Yes probably

**Comment by story645** [comment] 2016-06-01 19:16
So can we close one? (or at the least label 'em dupes?)

**Comment by efiring** [comment] 2016-06-01 19:26
It's possible that both this one and #3690 have been fixed by #5639.  @story645, are you able to reproduce the failures?  And if so, can you test with v2.x to see whether the problem has indeed been fixed?

**Comment by QuLogic** [comment] 2017-05-28 03:35
This looks like a dupe to me.

**Closed by QuLogic** 2017-05-28 03:35 UTC
Labels: GUI/wx
