### ISSUE TITLE
import matplotlib.pyplot as plt, ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by PerfectWzp** [matplotlib/matplotlib#9954] opened 2017-12-08 07:50 UTC
`import matplotlib.pyplot as plt` is erroring with python2.7, anaconda3
The error is `ImportError: libGL.so.1: cannot open shared object file: No such file or directory`

### Error report
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/serving/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/serving/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/serving/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "/serving/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 26, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/serving/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/serving/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/serving/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 128, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

### conda list is
$conda list
cairo                     1.14.8                        0    defaults
certifi                   2016.2.28                py27_0    defaults
cycler                    0.10.0                   py27_0    defaults
dbus                      1.10.20                       0    defaults
expat                     2.1.0                         0    defaults
fontconfig                2.12.1                        3    defaults
freetype                  2.5.5                         2    defaults
functools32               3.2.3.2                  py27_0    defaults
glib                      2.50.2                        1    defaults
gst-plugins-base          1.8.0                         0    defaults
gstreamer                 1.8.0                         0    defaults
harfbuzz                  0.9.39                        2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
icu                       54.1                          0    defaults
jpeg                      9b                            0    defaults
libffi                    3.2.1                         1    defaults
libgcc                    5.2.0                         0    defaults
libgfortran               3.0.0                         1    defaults
libiconv                  1.14                          0    defaults
libpng                    1.6.30                        1    defaults
libxcb                    1.12                          1    defaults
libxml2                   2.9.4                         0    defaults
matplotlib                2.0.2               np113py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mkl                       2017.0.3                      0    defaults
numpy                     1.13.1                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
openssl                   1.0.2l                        0    defaults
pandas                    0.20.3                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pango                     1.40.3                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
patsy                     0.4.1                    py27_0    defaults
pcre                      8.39                          1    defaults
pip                       9.0.1                    py27_1    defaults
pixman                    0.34.0                        0    defaults
pycairo                   1.10.0                   py27_0    defaults
pyparsing                 2.2.0                    py27_0    defaults
pyqt                      5.6.0                    py27_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python                    2.7.13                        0    defaults
python-dateutil           2.6.1                    py27_0    defaults
pytz                      2017.2                   py27_0    defaults
qt                        5.6.2                         5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
qt5                       5.3.1                         1    dsdale24
readline                  6.2                           2    defaults
scikit-learn              0.19.0              np113py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
scipy                     0.19.1              np113py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
setuptools                36.4.0                   py27_1    defaults
sip                       4.18                     py27_0    defaults
six                       1.10.0                   py27_0    defaults
sqlite                    3.13.0                        0    defaults
statsmodels               0.8.0               np113py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
subprocess32              3.2.7                    py27_0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py27_0    defaults
zlib                      1.2.11                        0    defaults
(python27)

**Comment by lkjell** [comment] 2017-12-08 08:33
Have you tried another backend? PyQt5 does not officially support python 2.7.

**Comment by lkjell** [comment] 2017-12-08 08:37
Try for example 

```
import matplotlib
matplotlib.use("tkagg")
import matplotlib.pyplot as plt

print(matplotlib.get_backend())

plt.plot(range(10))

plt.show()
```

**Comment by jenshnielsen** [comment] 2017-12-08 08:41
@lkjell  Are you sure about that According to this http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html it supports 2.6 and up. I think the issue is that @PerfectWzp has at least 2 different versions of qt5 installed. one from  dsdale24 and the regular conda one. I would suggest creating a new clean conda environment or even reinstalling anaconda from scratch.

**Comment by lkjell** [comment] 2017-12-08 08:48
@jenshnielsen I must be reading from the wrong page then.

http://pyqt.sourceforge.net/Docs/PyQt5/installation.html

**Comment by jenshnielsen** [comment] 2017-12-08 09:09
@lkjell As I read it that page is about wheel based installation only. On pypi there are indeed only python 3.5 and up wheels

**Comment by PerfectWzp** [comment] 2017-12-08 09:59
I have tried PyQt4 and PyQt5, both 4 and 5 have this error!
I install PyQt4 and PyQt5 in my anaconda3 environment.

```
>>> import matplotlib
>>> matplotlib.use("tkagg")
>>> import matplotlib.pyplot as plt
>>> 
>>> print(matplotlib.get_backend())
TkAgg
>>> plt.plot(range(10))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/serving/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/pyplot.py", line 3306, in plot
    ax = gca()
  File "/serving/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/pyplot.py", line 950, in gca
    return gcf().gca(**kwargs)
  File "/serving/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/serving/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/serving/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/serving/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/serving/anaconda3/envs/python27/lib/python2.7/lib-tk/Tkinter.py", line 1820, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
>>> 
```

how can I solve the error "ImportError: libGL.so.1: cannot open shared object file: No such file or directory" ? thanks

**Comment by jenshnielsen** [comment] 2017-12-08 12:55
Did you create a new environment and start from scratch? Installing more versions on top of each other is not likely to solve anything

The last issue comes from the TKAgg backend and says that it cant find a display. Are you on a server without a display? In that case its better to use a non gui backend.

```
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

print(matplotlib.get_backend())

plt.plot(range(10))

plt.savefig('test.png')
```

**Comment by PerfectWzp** [comment] 2017-12-12 07:28
Yes, I create a new environment and start from scratch, install pyqt5 .
I use a server without a display.
I use your code and it runs successfully
`matplotlib.use("Agg")`

Thankyou very much !!!
@jenshnielsen :+1:

**Comment by jenshnielsen** [comment] 2017-12-12 08:14
Great, I will close this then

**Closed by jenshnielsen** 2017-12-12 08:14 UTC
