### ISSUE TITLE
Annotation text bbox calculated incorrectly in matplotlib>=1.4.3?

### ISSUE THREAD

**Issue by joferkington** [matplotlib/matplotlib#4139] opened 2015-02-21 16:56 UTC
Prior to matplotlib 1.4.3, text bounding boxes created with `annotate` did not include the connection arrow.  Starting with 1.4.3 and continuing up to the current HEAD, the bbox includes the connection arrow.  

As an example:

```
import matplotlib.pyplot as plt
import matplotlib

fig, ax = plt.subplots()

ax.annotate('Matplotlib {}'.format(matplotlib.__version__),
            xy=(0.1, 0.1), xytext=(50, 50), size=20,
            xycoords='data', textcoords='offset points',
            bbox=dict(alpha=0.5, fc='yellow'),
            arrowprops=dict(arrowstyle='->'))

plt.show()
```

![mpl1 4 2](https://cloud.githubusercontent.com/assets/906803/6314963/e80f9c8c-b9b7-11e4-81a0-583a64784df7.png)

![mpl1 4 3](https://cloud.githubusercontent.com/assets/906803/6314965/ef713d00-b9b7-11e4-9668-64397e8f2914.png)

![mpl_github](https://cloud.githubusercontent.com/assets/906803/6314968/f731695c-b9b7-11e4-962f-ae4337f495ad.png)

This may be related to https://github.com/matplotlib/matplotlib/issues/4012?

**Comment by jenshnielsen** [comment] 2015-02-21 17:04
I think this is likely due to #4023 which was merged as 26c7d656de106534b1871433c965dac9789ef264

**Comment by tacaswell** [comment] 2015-02-21 19:30
I agree with @jenshnielsen's diagnosis.  Someplace a call to `self.`get_window_extent()` needs to be changed to `Text.get_window_extent(self)`.

**Comment by cimarronm** [comment] 2015-02-22 19:25
It is related to #4023. The issue is that the `Annotation` draw method calls the `Text` draw method to draw the text box portion. Inside that, it calls `bbox_artist` from the patches modules which then calls `get_window_extent` of the instance.

**Comment by efiring** [comment] 2015-03-01 01:01
There's even more: if `boxstyle='square'` is added to the `bbox` dictionary kwarg in the example, so that a FancyBboxPatch is drawn, then the filled region is correct, but the arrow is not clipped correctly.

**Comment by tacaswell** [comment] 2015-03-01 01:26
The clipping is related to #4012 I think.

**Closed** 2015-07-22 03:50 UTC
