### ISSUE TITLE
Next to my previous post (was [#18166])

### ISSUE THREAD

**Issue by Mike-HubGit** [matplotlib/matplotlib#18170] opened 2020-08-04 20:28 UTC
I sent a post [#18166] in which I mentionned a possible bug in Matplotlib when getting informations about the plot size in pixels. It only showed the erroneous behaviour of ipympl mode of Matplotlib on a regular/official example in Matplotlib.

This post was closed, arguing the erroneous behaviour is "normal" whereas unexpected. I wanted to mention :
- if some API should not be used they should be mentionned to be or to become deprecated somewhere
- If some API should not be used it would be nice to update the examples, or to ask the community to do it.

Simply saying "How you work around this is up to you" assumes my knowledge of Matplotlib is at the best level, which is not the case at all : I am an early beginner with python (6 month), coming from C/C++/Matlab.

I'd like you to tell to me where I could work to obtain changes in the documentation of Matplotlib and in the examples, to avoid unexpected results for other users.

### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by tacaswell** [comment] 2020-08-04 21:08
I agree with @jklymak that this is an example of Matplotlib working correctly and doing exactly what you told it to, even if it is not what you wanted.  

As noted in that tutorial we have a 6 stacked / nested coordinate systems in Matplotlib.  When you do `xdisplay, ydisplay = ax.transData.transform_point((xdata, ydata))` you are saying 'right now, given the current figure size, dpi, axes location, data limits, axes scale, what is the pixel location in "display space" of this position in "data space"?'  When you do 

```
disp = ax.annotate('display = (%.1f, %.1f)' % (xdisplay, ydisplay),
                   (xdisplay, ydisplay), xytext=(0.5*offset, -offset),
                   xycoords='figure pixels',
                   textcoords='offset points',
                   bbox=bbox, arrowprops=arrowprops)
```

you are saying "please put the point at exactly this pixel in the final render, full stop".  Once we get here, we have no way of knowing that the float object you passed in (which is just a plain Python float) was meant to track something about the data space (the ability to make sure that things "stay right" is the reason the transform system exists). 

Hopefully that clarifies what is happening.  In https://matplotlib.org/tutorials/advanced/transforms_tutorial.html we say at the top

> Note that specifying objects in display coordinates will change their location if the dpi of the figure changes.

and there is a "Note" box directly below the example you are working with that addresses this point.  

I think what Jody meant by "How you work around this is up to you" is that depending on why you are using location in "display space" you will need different work around.  I (and I suspect Jody) read #18166 as using an example from our documentation to be illustrative of the actually issue you are having in your work.

If the purpose is just learning, then the work around is "learn to not just display-space positions", if you need to point an arrow at a specific place in the data / axes / figure coordinates, use the transfrom, and if you really need to know the screen space location of a point for some other purpose use the `on_draw` event to be notified when a draw happens and update your cache.

I am going to open a docs PR making a bigger about about not caching, but going to close this issue now and suggest further discussion about how / why transforms work be moved to https://discourse.matplotlib.org/

**Closed by tacaswell** 2020-08-04 21:08 UTC

**Comment by jklymak** [comment] 2020-08-04 21:17
... and right under the example it also says, explicitly:

```
Note

If you run the source code in the example above in a GUI backend, you may also find that the two arrows for the data and display annotations do not point to exactly the same point. This is because the display point was computed before the figure was displayed, and the GUI backend may slightly resize the figure when it is created. The effect is more pronounced if you resize the figure yourself. This is one good reason why you rarely want to work in display space, but you can connect to the 'on_draw' Event to update figure coordinates on figure draws; see Event handling and picking.
```

I don't think there is any feasible way we could have documented this better.

**Comment by Mike-HubGit** [comment] 2020-08-04 21:31
A suggestion : 
If you consider working with "display" coordinates is not the good way to work, do not show as primary example an example that relies on "display" coordinates ... 
I did this that way after reading again the documentation. But a more straightforward, context independant example would have been welcomed and, in my mind, more "pythonic" ...

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
x = np.arange(0, 10, 0.005)
y = np.exp(-x/2.) * np.sin(2*np.pi*x)

fig, ax = plt.subplots()
ax.plot(x, y)
ax.set_xlim(0, 10)
ax.set_ylim(-1, 1)

xdata, ydata = 5, 0
xaxes, yaxes = ax.transAxes.inverted().transform(ax.transData.transform((xdata, ydata)))

bbox = dict(boxstyle="round", fc="0.8")
arrowprops = dict(
    arrowstyle="->",
    connectionstyle="angle,angleA=0,angleB=90,rad=10")

offset = 72
ax.annotate('data = (%.1f, %.1f)' % (xdata, ydata),
            (xdata, ydata), xytext=(-2*offset, offset), textcoords='offset points',
            bbox=bbox, arrowprops=arrowprops)

disp = ax.annotate('axes = (%.1f, %.1f)' % (xaxes, yaxes),
                   (xaxes, yaxes), xytext=(0.5*offset, -offset),
                   xycoords='axes fraction',
                   textcoords='offset points',
                   bbox=bbox, arrowprops=arrowprops)


plt.show()
```

**Comment by jklymak** [comment] 2020-08-04 21:49
> If you consider working with "display" coordinates is not the good way to work, do not show as primary example an example that relies on "display" coordinates ...

Sure, but display co-ordinates, for better or worse, are a fundamental concept to Matplotlib: all the transforms transform to pixel co-ordinates and all the internal logic is in display space.   Your suggested change, while more impervious to dpi changing in the GUI, is not illustrating the point of the tutorial which is to explain the difference between the pixel space and data space.  

https://matplotlib.org/tutorials/text/annotations.html is probably a more appropriate place to learn how to use annotations.

**Comment by tacaswell** [comment] 2020-08-05 01:27
Please see #18178 for changes I hope will make this clearer.  

I agree with @jklymak  again, the point of this tutorial is to explain how the transforms work and by design they go to display-space.
