### ISSUE TITLE
Matplotlib.get_backend()/matplotlib.use() cause NSException with Anaconda

### ISSUE THREAD

**Issue by moonshoes87** [matplotlib/matplotlib#13096] opened 2019-01-03 22:26 UTC
### Bug report

**Bug summary**

The fix for #12362 appears to cause an NSException in matplotlib 3.0.2 with Anaconda Python.

**Code for reproduction**

```python
import matplotlib
if matplotlib.get_backend() != "TKAgg":
    matplotlib.use("TKAgg")
from matplotlib import pyplot as plt
plt.figure(num=1, figsize=(5, 5))
```

**Actual outcome**

```
2019-01-03 14:09:18.001 python[99909:9620635] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fdeb78338c0
2019-01-03 14:09:18.006 python[99909:9620635] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fdeb78338c0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2d52523b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff547a4c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2d5bdd94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff2d49b700 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff2d49b0c8 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x00000001243e131d TkpInit + 413
	6   libtk8.6.dylib                      0x000000012433917e Initialize + 2622
	7   _tkinter.cpython-36m-darwin.so      0x000000011a1f3a16 _tkinter_create + 1174
	8   python                              0x000000010e947088 _PyCFunction_FastCallDict + 200
	9   python                              0x000000010ea1df4f call_function + 143
	10  python                              0x000000010ea1babf _PyEval_EvalFrameDefault + 46847
	11  python                              0x000000010ea0f209 _PyEval_EvalCodeWithName + 425
	12  python                              0x000000010ea1eb1c _PyFunction_FastCallDict + 364
	13  python                              0x000000010e8c58b0 _PyObject_FastCallDict + 320
	14  python                              0x000000010e8ecfe8 method_call + 136
	15  python                              0x000000010e8ccefe PyObject_Call + 62
	16  python                              0x000000010e96e385 slot_tp_init + 117
	17  python                              0x000000010e9728c1 type_call + 241
	18  python                              0x000000010e8c5821 _PyObject_FastCallDict + 177
	19  python                              0x000000010e8cda67 _PyObject_FastCallKeywords + 327
	20  python                              0x000000010ea1e048 call_function + 392
	21  python                              0x000000010ea1bb6f _PyEval_EvalFrameDefault + 47023
	22  python                              0x000000010ea1e30c fast_function + 188
	23  python                              0x000000010ea1dfac call_function + 236
	24  python                              0x000000010ea1babf _PyEval_EvalFrameDefault + 46847
	25  python                              0x000000010ea0f209 _PyEval_EvalCodeWithName + 425
	26  python                              0x000000010ea1eb1c _PyFunction_FastCallDict + 364
	27  python                              0x000000010e8c58b0 _PyObject_FastCallDict + 320
	28  python                              0x000000010e8ecfe8 method_call + 136
	29  python                              0x000000010e8ccefe PyObject_Call + 62
	30  python                              0x000000010ea1bcc0 _PyEval_EvalFrameDefault + 47360
	31  python                              0x000000010ea0f209 _PyEval_EvalCodeWithName + 425
	32  python                              0x000000010ea1e3ba fast_function + 362
	33  python                              0x000000010ea1dfac call_function + 236
	34  python                              0x000000010ea1bb6f _PyEval_EvalFrameDefault + 47023
	35  python                              0x000000010ea0f209 _PyEval_EvalCodeWithName + 425
	36  python                              0x000000010ea67d4c PyRun_FileExFlags + 252
	37  python                              0x000000010ea67224 PyRun_SimpleFileExFlags + 372
	38  python                              0x000000010ea8dd66 Py_Main + 3734
	39  python                              0x000000010e8bd929 main + 313
	40  libdyld.dylib                       0x00007fff553be015 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

```

**Expected outcome**

I expected a figure to be created without crashing.  This worked in matplotlib 2.2.3.

**Matplotlib version**

  * Operating system:  OSX 10.13.6
  * Matplotlib version:  3.0.2            py36h54f8f79_0 
  * Matplotlib backend (`print(matplotlib.get_backend())`):  TKAgg
  * Python version:  Python 3.6.7 :: Anaconda custom (64-bit)
  * Jupyter version (if applicable):
  * Other libraries: 

Matplotlib was installed via conda using the default channel.

**Comment by jklymak** [comment] 2019-01-03 23:46
I've never had TkAgg work on my MacOSX machine either (though maybe it worked in 2.2.3 - I've not tried recently).

**Comment by moonshoes87** [comment] 2019-01-04 02:21
Actually, the TKAgg backend does work both in 2.* and 3.0.2.  I.e., this code is fine:

```
import matplotlib                                                                     
matplotlib.use("TKAgg")
from matplotlib import pyplot as plt
plt.figure(num=1, figsize=(5, 5))
plt.draw()
plt.show()
```

It appears to be just the call to `matplotlib.get_backend()` that causes problems (in 3.0.2).

**Comment by anntzer** [comment] 2019-01-04 08:01
Run with `python -Xfaulthandler test.py`?

**Comment by moonshoes87** [comment] 2019-01-04 21:46
@jklymak, TKAgg is selected before the script crashes.   

@anntzer, output when run with -Xfaulthandler:

```
TkAgg
2019-01-04 13:45:42.035 python[6502:9959316] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7f95b01a9420
2019-01-04 13:45:42.037 python[6502:9959316] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7f95b01a9420'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2d52523b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff547a4c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2d5bdd94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff2d49b700 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff2d49b0c8 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x000000012470631d TkpInit + 413
	6   libtk8.6.dylib                      0x000000012465e17e Initialize + 2622
	7   _tkinter.cpython-36m-darwin.so      0x0000000124486a16 _tkinter_create + 1174
	8   python                              0x000000010ec98088 _PyCFunction_FastCallDict + 200
	9   python                              0x000000010ed6ef4f call_function + 143
	10  python                              0x000000010ed6cabf _PyEval_EvalFrameDefault + 46847
	11  python                              0x000000010ed60209 _PyEval_EvalCodeWithName + 425
	12  python                              0x000000010ed6fb1c _PyFunction_FastCallDict + 364
	13  python                              0x000000010ec168b0 _PyObject_FastCallDict + 320
	14  python                              0x000000010ec3dfe8 method_call + 136
	15  python                              0x000000010ec1defe PyObject_Call + 62
	16  python                              0x000000010ecbf385 slot_tp_init + 117
	17  python                              0x000000010ecc38c1 type_call + 241
	18  python                              0x000000010ec16821 _PyObject_FastCallDict + 177
	19  python                              0x000000010ec1ea67 _PyObject_FastCallKeywords + 327
	20  python                              0x000000010ed6f048 call_function + 392
	21  python                              0x000000010ed6cb6f _PyEval_EvalFrameDefault + 47023
	22  python                              0x000000010ed6f30c fast_function + 188
	23  python                              0x000000010ed6efac call_function + 236
	24  python                              0x000000010ed6cabf _PyEval_EvalFrameDefault + 46847
	25  python                              0x000000010ed60209 _PyEval_EvalCodeWithName + 425
	26  python                              0x000000010ed6fb1c _PyFunction_FastCallDict + 364
	27  python                              0x000000010ec168b0 _PyObject_FastCallDict + 320
	28  python                              0x000000010ec3dfe8 method_call + 136
	29  python                              0x000000010ec1defe PyObject_Call + 62
	30  python                              0x000000010ed6ccc0 _PyEval_EvalFrameDefault + 47360
	31  python                              0x000000010ed60209 _PyEval_EvalCodeWithName + 425
	32  python                              0x000000010ed6f3ba fast_function + 362
	33  python                              0x000000010ed6efac call_function + 236
	34  python                              0x000000010ed6cb6f _PyEval_EvalFrameDefault + 47023
	35  python                              0x000000010ed60209 _PyEval_EvalCodeWithName + 425
	36  python                              0x000000010edb8d4c PyRun_FileExFlags + 252
	37  python                              0x000000010edb8224 PyRun_SimpleFileExFlags + 372
	38  python                              0x000000010edded66 Py_Main + 3734
	39  python                              0x000000010ec0e929 main + 313
	40  libdyld.dylib                       0x00007fff553be015 start + 1
	41  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Fatal Python error: Aborted

Current thread 0x00007fff8de14380 (most recent call first):
  File "/Users/nebula/anaconda3/lib/python3.6/tkinter/__init__.py", line 2023 in __init__
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 1008 in new_figure_manager_given_figure
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 3218 in new_figure_manager
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 525 in figure
  File "simplest.py", line 6 in <module>
Abort trap: 6
```

**Comment by anntzer** [comment] 2019-01-04 21:50
If you print the result of `matplotlib.backends._get_running_interactive_framework()` between each line, what do you get?

**Comment by tacaswell** [comment] 2019-01-05 04:40
Does the following diff

```diff
modified   lib/matplotlib/__init__.py
@@ -1376,10 +1376,13 @@ def get_backend():
 
     See Also
     --------
     matplotlib.use
     """
+    val = dict.__getitem__(rcParams, 'backend')
+    if val is rcsetup._auto_backend_sentinel:
+        return 'unselected'
     return rcParams['backend']
 
 
 def interactive(b):
     """

```

solve the problem?

**Comment by moonshoes87** [comment] 2019-01-06 00:36
@anntzer, `matplotlib.backends._get_running_interactive_framework()` returns `None` at each line of my script.  Only the call to `matplotlib.get_backend()` returns `TKAgg`.


```
None
None
None
TkAgg
None
None
2019-01-05 16:30:48.673 python[9117:10203624] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7f929ec9f4c0
2019-01-05 16:30:48.681 python[9117:10203624] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7f929ec9f4c0'
*** First throw call stack:
```

**Comment by moonshoes87** [comment] 2019-01-06 00:48
@tacaswell, that diff fixes it!

**Comment by anntzer** [comment] 2019-01-06 12:48
Not to be a royal pain, but the proposed patch won't fix the issue if someone does `if rcParams["backend"] == "TkAgg"` (which triggers backend resolution) instead of `if get_backend() == "TkAgg"` (as in the original report), and backend selection does need to occur at *some* point.
IOW I think this is papering over a more serious issue (i.e. why does `_get_running_interactive_framework()` return None instead of detecting that the OSX event loop has apparently already started).

**Comment by tacaswell** [comment] 2019-01-06 20:34
Sorry, I should have provided more context with that diff, I just wanted to see if avoiding touching the OSX backend at all would avoid the problem, not as a fix to the problem.

@moonshoes87 The fastest fix is to remove the conditional (as re-setting the backend to `'TkAgg'` is not harmful) in your code while we figure this out...

**Comment by asmeurer** [comment] 2019-01-28 18:52
I am getting what I believe is the same error. @anntzer's description of the issue sounds apt, since I am using some eventloop code similar to IPython's.

**Comment by asmeurer** [comment] 2019-01-28 19:03
I guess in some sense my code is bugged. I should be using `pythonw`. There the default backend is MacOSX. With regular `python` the default backend is tk (except in Python 3.5 for some reason, it's still MacOSX). But I don't know how well the IPython eventloop code should work outside of a Framework build.

**Comment by jjhelmus** [comment] 2019-01-29 20:49
I ran into this issue debugging some issue Anaconda users reported. I can provide some examples which replicate the problem using a conda provided Python as well as Python from Python.org.

The root cause seems to be that if `matplotlib.backends._macosx` is imported then attempts to use the TkAgg backend will raise an NSException .  This is true even if the import of `macosx` fails when a [non-framework Python is detected](https://github.com/matplotlib/matplotlib/blob/v3.0.2/src/_macosx.m#L2578-L2608).  

The following script will terminate with an uncaught NSException using Python 3.7.2 from Python.org after pip installing matplotlib 3.0.2:

``` Python
import matplotlib
from matplotlib.backends import _macosx
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
fig = plt.figure()
```

**Comment by jklymak** [comment] 2019-01-29 20:58
I think master now works with the non framework build on macosx.  I’ve never had Tkagg work though others report it working. 

Does tkagg really work if macosx is not imported?

**Comment by jjhelmus** [comment] 2019-01-29 21:03
> Does tkagg really work if macosx is not imported?

The following works on my machine using a conda provided Python as well as Python.org Python:
``` Python
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
fig = plt.figure()
plt.plot([1,2,3])
plt.show()
```

**Comment by jjhelmus** [comment] 2019-01-29 21:13
One final example example, the following will terminal with an uncaught exception on a non framework Python provided by conda despite the `_macosx` module failing to import:

``` Python

**Comment by jklymak** [comment] 2019-01-29 21:22
I can confirm that error w/ 3.0.2.

On master it runs fine, so I think (?) we've fixed this.  Are you able to test the development version?  Otherwise, it'll be available w/ 3.1

**Closed as completed** 2019-01-30 07:28 UTC
Labels: OS: Apple, GUI: MacOSX

**Comment by egpbos** [comment] 2019-02-27 08:29
@jjhelmus how did you confirm that the issues were fixed in master? Did you build the Conda recipe with master? Because the new Conda matplotlib 3.0.3 package still has the issue.

I searched the master branch commits for something like the patch @tacaswell mentioned, but couldn't find it there. Are we sure this has been fixed for the Conda + macOS case that this issue was about? Or is the issue in the Conda package somehow?

**Comment by tacaswell** [comment] 2019-02-27 12:35
3.0.3 was tagged off of the 3.0.x branch, not master.

We got our book-keeping crossed on this, re-milestoning to where it is actually fixed.

We should consider doing a 3.0.4 that fixes this issue + the pytest3.8 backports?

**Comment by egpbos** [comment] 2019-02-27 13:27
Ah, I see, thanks for the clarification. Seeing as 3.1.0 is expected soon, I would be fine with skipping 3.0.4, just my 2ct.

**Comment by Samaritan1011001** [comment] 2019-11-26 06:17
I could not solve this issue. 
I used : 
```
import matplotlib 
if matplotlib.get_backend() != "TKAgg":
    matplotlib.use("TKAgg")
from matplotlib import pyplot as plt
```

Tried it with "macOSX"

It just doesn't work. My flask webapp crashes the moment it runs `plt.show()`

pip installed matplotlib version: `3.2.0rc1` 
MacOS: `Catalina 10.15.1`

**Comment by jklymak** [comment] 2019-11-26 06:21
Can you open a new issue with your exact error message?  tk has serious issues on MacOS.  Have you tried Qt?

**Comment by Samaritan1011001** [comment] 2019-11-26 06:25
Sure. Will create it soon. I tried `Qt5Agg` but it says `ImportError: Failed to import any qt binding`

**Comment by jklymak** [comment] 2019-11-26 06:27
Install Qt?

**Comment by Samaritan1011001** [comment] 2019-11-26 06:41
A bit new to this. Yeah, installed it and it still crashes. 

Here is the complete error message:

```
2019-11-26 00:39:49.183 python[34833:361239] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff34b9cf53 __exceptionPreprocess + 250
        1   libobjc.A.dylib                     0x00007fff6aac9835 objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff34bb752c -[NSException raise] + 9
        3   AppKit                              0x00007fff31d6b6b2 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
        4   AppKit                              0x00007fff31d68bc1 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
        5   AppKit                              0x00007fff31d68633 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
        6   AppKit                              0x00007fff31ffb0d8 -[NSWindow initWithContentRect:styleMask:backing:defer:screen:] + 52
        7   libqcocoa.dylib                     0x00000001290ec195 qt_plugin_instance + 161509
        8   libqcocoa.dylib                     0x00000001290d9aac qt_plugin_instance + 86012
        9   libqcocoa.dylib                     0x00000001290d3722 qt_plugin_instance + 60530
        10  libqcocoa.dylib                     0x00000001290d31ab qt_plugin_instance + 59131
        11  QtGui                               0x0000000127e2322c _ZN14QWindowPrivate6createEby + 140
        12  QtWidgets                           0x00000001289536d1 _ZN14QWidgetPrivate6createEv + 1201
        13  QtWidgets                           0x00000001289523c2 _ZN7QWidget6createEybb + 322
        14  QtWidgets                           0x0000000128965a7d _ZN14QWidgetPrivate10setVisibleEb + 189
        15  QtWidgets.so                        0x000000012844e23e _ZN14sipQMainWindow10setVisibleEb + 110
        16  QtWidgets.so                        0x000000012860675b _ZL17meth_QWidget_showP7_objectS0_ + 75
        17  Python                              0x000000010696334b _PyMethodDef_RawFastCallKeywords + 235
        18  Python                              0x00000001069629d4 _PyCFunction_FastCallKeywords + 41
        19  Python                              0x00000001069f7384 call_function + 628
        20  Python                              0x00000001069f035f _PyEval_EvalFrameDefault + 6767
        21  Python                              0x0000000106962da8 function_code_fastcall + 106
        22  Python                              0x00000001069f73f1 call_function + 737
        23  Python                              0x00000001069f0346 _PyEval_EvalFrameDefault + 6742
        24  Python                              0x00000001069f7be5 _PyEval_EvalCodeWithName + 1698
        25  Python                              0x000000010696299c _PyFunction_FastCallKeywords + 212
        26  Python                              0x00000001069f73f1 call_function + 737
        27  Python                              0x00000001069f0346 _PyEval_EvalFrameDefault + 6742
        28  Python                              0x00000001069f7be5 _PyEval_EvalCodeWithName + 1698
        29  Python                              0x0000000106962614 _PyFunction_FastCallDict + 444
        30  Python                              0x00000001069f0643 _PyEval_EvalFrameDefault + 7507
        31  Python                              0x00000001069f7be5 _PyEval_EvalCodeWithName + 1698
        32  Python                              0x0000000106962614 _PyFunction_FastCallDict + 444
        33  Python                              0x000000010696371b _PyObject_Call_Prepend + 131
        34  Python                              0x0000000106962ae1 PyObject_Call + 136
        35  Python                              0x00000001069f0643 _PyEval_EvalFrameDefault + 7507
        36  Python                              0x00000001069f7be5 _PyEval_EvalCodeWithName + 1698
        37  Python                              0x000000010696299c _PyFunction_FastCallKeywords + 212
        38  Python                              0x00000001069f73f1 call_function + 737
        39  Python                              0x00000001069f035f _PyEval_EvalFrameDefault + 6767
        40  Python                              0x00000001069f7be5 _PyEval_EvalCodeWithName + 1698
        41  Python                              0x000000010696299c _PyFunction_FastCallKeywords + 212
        42  Python                              0x00000001069f73f1 call_function + 737
        43  Python                              0x00000001069f04a2 _PyEval_EvalFrameDefault + 7090
        44  Python                              0x0000000106962da8 function_code_fastcall + 106
        45  Python                              0x00000001069f0643 _PyEval_EvalFrameDefault + 7507
        46  Python                              0x0000000106962da8 function_code_fastcall + 106
        47  Python                              0x00000001069f73f1 call_function + 737
        48  Python                              0x00000001069f0346 _PyEval_EvalFrameDefault + 6742
        49  Python                              0x0000000106962da8 function_code_fastcall + 106
        50  Python                              0x00000001069f73f1 call_function + 737
        51  Python                              0x00000001069f0346 _PyEval_EvalFrameDefault + 6742
        52  Python                              0x0000000106962da8 function_code_fastcall + 106
        53  Python                              0x00000001069f73f1 call_function + 737
        54  Python                              0x00000001069f0346 _PyEval_EvalFrameDefault + 6742
        55  Python                              0x0000000106962da8 function_code_fastcall + 106
        56  Python                              0x000000010696371b _PyObject_Call_Prepend + 131
        57  Python                              0x00000001069a00ea slot_tp_call + 71
        58  Python                              0x000000010696284a _PyObject_FastCallKeywords + 358
        59  Python                              0x00000001069f73ea call_function + 730
        60  Python                              0x00000001069f035f _PyEval_EvalFrameDefault + 6767
        61  Python                              0x000000010696e3fb gen_send_ex + 244
        62  Python                              0x00000001069efb60 _PyEval_EvalFrameDefault + 4720
        63  Python                              0x00000001069f7be5 _PyEval_EvalCodeWithName + 1698
        64  Python                              0x000000010696299c _PyFunction_FastCallKeywords + 212
        65  Python                              0x00000001069f73f1 call_function + 737
        66  Python                              0x00000001069f03fa _PyEval_EvalFrameDefault + 6922
        67  Python                              0x00000001069f7be5 _PyEval_EvalCodeWithName + 1698
        68  Python                              0x000000010696299c _PyFunction_FastCallKeywords + 212
        69  Python                              0x00000001069f73f1 call_function + 737
        70  Python                              0x00000001069f0346 _PyEval_EvalFrameDefault + 6742
        71  Python                              0x0000000106962da8 function_code_fastcall + 106
        72  Python                              0x00000001069f73f1 call_function + 737
        73  Python                              0x00000001069f0346 _PyEval_EvalFrameDefault + 6742
        74  Python                              0x0000000106962da8 function_code_fastcall + 106
        75  Python                              0x00000001069f73f1 call_function + 737
        76  Python                              0x00000001069f035f _PyEval_EvalFrameDefault + 6767
        77  Python                              0x0000000106962da8 function_code_fastcall + 106
        78  Python                              0x00000001069f73f1 call_function + 737
        79  Python                              0x00000001069f0346 _PyEval_EvalFrameDefault + 6742
        80  Python                              0x0000000106962da8 function_code_fastcall + 106
        81  Python                              0x000000010696371b _PyObject_Call_Prepend + 131
        82  Python                              0x00000001069a0ade slot_tp_init + 80
        83  Python                              0x000000010699d80a type_call + 172
        84  Python                              0x000000010696284a _PyObject_FastCallKeywords + 358
        85  Python                              0x00000001069f73ea call_function + 730
        86  Python                              0x00000001069f035f _PyEval_EvalFrameDefault + 6767
        87  Python                              0x0000000106962da8 function_code_fastcall + 106
        88  Python                              0x00000001069f73f1 call_function + 737
        89  Python                              0x00000001069f0346 _PyEval_EvalFrameDefault + 6742
        90  Python                              0x0000000106962da8 function_code_fastcall + 106
        91  Python                              0x000000010696371b _PyObject_Call_Prepend + 131
        92  Python                              0x0000000106962ae1 PyObject_Call + 136
        93  Python                              0x00000001069f0643 _PyEval_EvalFrameDefault + 7507
        94  Python                              0x0000000106962da8 function_code_fastcall + 106
        95  Python                              0x00000001069f73f1 call_function + 737
        96  Python                              0x00000001069f0346 _PyEval_EvalFrameDefault + 6742
        97  Python                              0x0000000106962da8 function_code_fastcall + 106
        98  Python                              0x00000001069f73f1 call_function + 737
        99  Python                              0x00000001069f0346 _PyEval_EvalFrameDefault + 6742
        100 Python                              0x0000000106962da8 function_code_fastcall + 106
        101 Python                              0x000000010696371b _PyObject_Call_Prepend + 131
        102 Python                              0x0000000106962ae1 PyObject_Call + 136
        103 Python                              0x0000000106a5ddbf t_bootstrap + 71
        104 Python                              0x0000000106a2515e pythread_wrapper + 25
        105 libsystem_pthread.dylib             0x00007fff6c038d36 _pthread_start + 125
        106 libsystem_pthread.dylib             0x00007fff6c03558f thread_start + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
