### ISSUE TITLE
Dotted grid lines in v2.0.0b1

### ISSUE THREAD

**Issue by rayosborn** [matplotlib/matplotlib#6515] opened 2016-05-31 19:16 UTC
After installing v2.0.0b1 into my conda installation (Mac OS X 10.11.5, Python 2.7.11, Anaconda 2.3.0), I noticed a subtle problem with dotted lines in grids. I used the following code to generate the two attached images in v1.5.1 and v2.0.0b1, respectively:

    import numpy as np
    import matplotlib.pyplot as plt
    
    x = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3])
    y = np.array([1, 2, 3, 1, 2, 3, 1, 2, 3])
    a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
    grid = a.reshape(3, 3)
    
    plt.imshow(grid, extent=(x.min(), x.max(), y.min(), y.max()),interpolation='bicubic')
    plt.grid(linestyle='dotted')
    plt.show()

If you blow up the new image, alternate dots are linked by a faint gray line, whereas the old dots are clearly separated. Overlaid on some plots, this can make the gridlines look more like dashed lines. 
![old-matplotlib-grid](https://cloud.githubusercontent.com/assets/1193959/15687413/25542ad6-273a-11e6-8ecf-a626293eec2b.png)
![new-matplotlib-grid](https://cloud.githubusercontent.com/assets/1193959/15687415/27e68e74-273a-11e6-982e-78b4bd13810b.png)

**Comment by jenshnielsen** [comment] 2016-06-01 17:12
This is caused by the changes in #5926 where we now changed the default pattern and made them scale with line-width. When the dash/dotted pattern is to small the anti aliasing causes the dots to overlap.

I still think that scaling with line width is a good idea but perhaps we should make the minimum patterns somewhat larger.

**Comment by tacaswell** [comment] 2016-06-06 19:53
The solution is to change the default dot spacing to `[1.1, 1.1]`, PR (plus justification plots) coming.

**Comment by efiring** [comment] 2016-06-06 20:09
And change the min value to 2.

**Comment by tacaswell** [comment] 2016-06-19 21:07
Under #6547 this code gives

![figure_1](https://cloud.githubusercontent.com/assets/199813/16179846/39d48784-3640-11e6-87f3-5e78e7ac4084.png)

**Comment by afvincent** [comment] 2016-06-19 22:23
@tacaswell : isn't the patterns a bit flat compared to the aspect ratio of the dotted line style in the picture that you just posted on #6547? If I paste the orange dotted line with lw=1.555… from your example in #6547 over the example showing the new grid lines, here is what I get:
![comparison_dotted_vs_dotted_grid](https://cloud.githubusercontent.com/assets/17270724/16180085/9249460e-367a-11e6-856b-dcb15bd04c7d.png)
The orange dots (with ~ default lw) look much more like dots to me than the thiner black ones. I guess this is the result of combining a very thin linewidth value for the grid lines and the new scale floor of lw=2. The black ones may be a bit surprising when one asked for a *dotted* grid. 

But anyway, AFAIK the new grid style is better than before.

(NB: comparison picture done with Gimp, zoom is 400% and no interpolation was used.)

**Comment by tacaswell** [comment] 2016-07-16 21:33
Closing as resolved

@rayosborn Can you check the 2.0.0b2 to verify that it actually fixes this for you?

**Closed by tacaswell** 2016-07-16 21:33 UTC
Labels: default changes

**Comment by rayosborn** [comment] 2016-07-18 21:19
It looks more consistent, and is certainly distinct from dashed. I'm not sure it really looks dotted to me - more like short-dashed. I think to look truly dotted, you probably have to have larger gaps between each dash, but I guess that is a matter of taste. I can live with this.

**Comment by fkbreitl** [comment] 2017-01-30 10:41
After testing mpl2.0.0-rc2 I realize the same problem of dotted grid lines not looking dotted as in earlier versions, but dashed.
Could you please realize a dotted appearance of grid lines and reopen this ticket.
The current style is not satisfying and a step back.
