### ISSUE TITLE
Hexbin if singular and mincnt used

### ISSUE THREAD

**Issue by gunthergl** [matplotlib/matplotlib#16461] opened 2020-02-10 14:26 UTC
### Bug report

**Bug summary**

Related to #3038, #2863 and [this stackoverflow bug](https://stackoverflow.com/questions/14780362/is-it-possible-to-plot-a-list-of-identical-points-on-a-matplotlib-hexbin-plot): if only identical (or one single) points are given, 

This seems to *still* be a bug when using `mincnt > 0`

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

mytens = [np.array([[-1, 1], [1, 1]]),
          np.array([[-1, 1], [-1, -1], [-1, -1]]),
          np.array([[-1, 1]])]
fig, axs = plt.subplots(nrows=2, ncols=2, sharex="all", sharey="all", squeeze=False)
axs[0, 0].hexbin(
    x=mytens[0][:, 0],
    y=mytens[0][:, 1],
    mincnt=1,
    gridsize=4
)
axs[0, 0].set_title("correct point 1")
axs[0, 1].hexbin(
    x=mytens[1][:, 0],
    y=mytens[1][:, 1],
    mincnt=1,
    gridsize=4
)
axs[0, 1].set_title("correct point 2")
axs[1, 0].hexbin(
    x=mytens[2][:, 0],
    y=mytens[2][:, 1],
    mincnt=1,
    gridsize=4
)
axs[1, 0].set_title("actual point not plotted, instead at 0,0!")
axs[1, 1].hexbin(
    x=mytens[2][:, 0],
    y=mytens[2][:, 1],
    # mincnt=0,  # if not given, 0 is assigned internally
    gridsize=4
)
axs[1, 1].set_title("actual point plotted, expected behaviour")
plt.show()



```

**Actual outcome**

![removeme](https://user-images.githubusercontent.com/14908309/74157497-a9357380-4c18-11ea-9df6-657a9003a29b.png)

**Expected outcome**

Point on the bottom left should be on the left top. The plotted point (0,0) does not even exist in the given data.

**Matplotlib version**

  * Operating system: Win 10
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version:  3.7.6 
  * Jupyter version (if applicable): - 
  * Other libraries: 
    - numpy 1.18.1  
    - (But same problem with torch)

**Comment by dstansby** [comment] 2020-02-13 11:27
Thanks for the report; here's a smaller example

```python
import matplotlib.pyplot as plt

x = [-1]
y = [1]
fig, axs = plt.subplots(ncols=2)
for ax, gridsize in zip(axs, [4, 100]):
    ax.hexbin(x=x, y=y, gridsize=gridsize, mincnt=1)
    ax.set_xlim(-1, 1)
    ax.set_ylim(-1, 1)
    ax.set_title(f'gridsize={gridsize}')
plt.show()
```

The problem is not that the point doesn't appear, as `mincnt=1` means only bins with counts > 1 appear. However, the bin at (0, 0) shouldn't be appearing! As shown above, this seems to depend on the value of `gridsize`.

**Comment by dstansby** [comment] 2020-02-13 12:23
This is a wild bug that led me down a rabbit hole! The issue turns out to be under this if statement: https://github.com/matplotlib/matplotlib/blob/acc7ecbfbe5c6e944a45fa08cc39142098149893/lib/matplotlib/collections.py#L354 - something is going wrong when doing a single path optimisation drawing that means the offsets aren't being taken into account.

**Comment by anntzer** [comment] 2020-02-14 09:45
FWIW this is fixed by https://github.com/matplotlib/matplotlib/pull/13696 -- basically, `offset_position="data"` is *only* there for hexbin() (so IOW hexbin has its "own" codepath in each backend...) even though this is actually not necessary; using just normal, more tested codepaths avoids the issue.

**Comment by QuLogic** [comment] 2020-03-14 01:18
To cross-reference with #16496, this bug occurs at least as far back as 1.5.3. It may have always existed...

**Closed** 2020-04-27 22:03 UTC
Labels: Confirmed bug
