### ISSUE TITLE
2.1 figure.legend broken

### ISSUE THREAD

**Issue by 2sn** [matplotlib/matplotlib#9320] opened 2017-10-08 14:52 UTC
### Bug report

**figure.legend no longer accepts "handles" and and "labels" as keywords**

**Code for reproduction**

```python
# Paste your code here
#
#
fig.legend(
    handles = patches,
     labels = labels,
    ...)

**Actual outcome**

<!--The output produced by the above code, which may be a screenshot, console output, etc.-->

```
# If applicable, paste the console output here
#
#
~/Python/lib/python3.6/site-packages/matplotlib/figure.py in legend(self, *args, **kwargs)
   1523                             '(artist handles, figure labels, legend location)')
   1524 
-> 1525         l = Legend(self, handles, labels, **kwargs)
   1526         self.legends.append(l)
   1527         l._remove_method = lambda h: self.legends.remove(h)
TypeError: __init__() got multiple values for argument 'handles'
```

**Expected outcome**

<!--A description of the expected outcome from the code snippet-->
<!--If this used to work in an earlier version of Matplotlib, please note the version it used to work on-->

**Matplotlib version**
<!--Please specify your platform and versions of the relevant libraries you are using:-->
  * Operating system: Fedora 26
  * Matplotlib version: 2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.3
  * Jupyter version (if applicable):
  * Other libraries: 

<!--Please tell us how you installed matplotlib and python e.g., from source, pip, conda-->
<!--If you installed from conda, please specify which channel you used if not the default-->

**Fix**

if handles and labels are provided as kwargs, use these and pop from kwargs.

**Comment by 2sn** [comment] 2017-10-08 14:55
There is many more issues.  mpl 2.1.0 is *not* a production version.

**Comment by tacaswell** [comment] 2017-10-08 16:32
Can you please provide a runnable example?

**Comment by jklymak** [comment] 2017-10-08 16:40
```python

import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 2)
hs = []
for axx in ax:
    h = axx.plot(np.arange(10))
    hs += [h]
fig.legend(handles=hs, labels=['Boo', 'Hoo'])
plt.show()
```

Doesn't make a legend and returns:

```
/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/matplotlib/figure.py:1505: UserWarning: No labeled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labeled objects found. "
```

This is using master.

**Comment by jklymak** [comment] 2017-10-08 16:51
@dstansby It looks like you maybe made this change?  Are we dropping support for `handles` and `labels` keywords?  

Interestingly, using positional arguments doesn't work either:

```python
import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 2)
hs = []
lab = ['Boo', 'Hoo']
for nn, axx in enumerate(ax):
    h = axx.plot(np.arange(10))
    hs += [h]
fig.legend(hs, lab)
plt.show()
```

returns
```
/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/matplotlib/legend.py:623: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x10da40080>] instances.
A proxy artist may be used instead.
See: http://matplotlib.org/users/legend_guide.html#using-proxy-artist
  "#using-proxy-artist".format(orig_handle)
```

OTOH, 

```
fig, ax = plt.subplots(1, 2)
hs = []
lab = ['Boo', 'Hoo']
for nn, axx in enumerate(ax):
    h = axx.plot(np.arange(10), label=lab[nn])
    hs += [h]
fig.legend()
plt.show()
```

works just fine.

**Comment by dstansby** [comment] 2017-10-08 16:54
Do you have a PR/commit reference for where I made the change? Can't remember anything like this off the top of my head.

**Comment by jklymak** [comment] 2017-10-08 17:00
@dstansby  #7811,  I think.    However, I have no idea if `handles=` and `labels=` were ever supported.  Also please note I edited the comment above as I'd done something silly ;-)

**Comment by dstansby** [comment] 2017-10-08 17:10
According to the `2.0` docstring, `legend()` never accepted handles and labels as kwargs, but instead as normal arguments. If it worked before I guess it was a co-incidence. The `2.1` docstring also doesn't mention them as kwargs, so I don't think anything is technically wrong, but it seems sensible to support them as kwargs so will leave this open.

In the mean time, just dropping `handles=` and `labels=` should fix the problem.

**Comment by tacaswell** [comment] 2017-10-08 17:47
Because they were named args before, the expectation is that they will work as kwargs as well.  This is a regression that should be fixed (and it is a easy fix, just check if they are in kwargs before falling back to searching).

**Comment by jklymak** [comment] 2017-10-08 17:52
`axes.legend` allows them to be kwargs as well.  `axes.legend` also allows just passing one argument, a list of the labels.  I'm not sure if we want to do that...

I'd fix this, but I don't understand why `handles`, `labels`, and `loc` aren't still named positional args that default to `None`.  Do we not like positional arguments?

**Comment by jnothman** [comment] 2017-10-09 23:44
Also makes scikit-learn doc builds fail at https://github.com/scikit-learn/scikit-learn/blob/master/examples/neural_networks/plot_mlp_training_curves.py#L88

**Comment by jklymak** [comment] 2017-10-10 01:50
See or #9324 for possible fix.  However I wouldn’t expect every invocation combination to be respected.

**Comment by 2sn** [comment] 2017-10-11 04:31
Yes, I had looked at the source file rather than the doc and used the names positional arguments from there.  I think it is better being able to give them as named arguments that can be passed as keywords so you don't have to remember the order.  Explicit is better.  Thanks for fixing!

**Comment by 2sn** [comment] 2017-10-11 06:06
PS - I have edited my code to now use positional arguments, but the old behaviour was nicer.

**Closed** 2017-10-31 17:46 UTC
Labels: Release critical
