### ISSUE TITLE
Persian language words not show in word clouds with matplotlib

### ISSUE THREAD

**Issue by majidebraa** [matplotlib/matplotlib#23086] opened 2022-05-21 05:20 UTC
when using matplotlib to show  word clouds with a dataset in the Persian language get this picture from the matplotlib :

![myplot](https://user-images.githubusercontent.com/82038698/169636747-4ad37c4a-0f5d-45d5-9a7b-021bccd0445b.png)

**Comment by jklymak** [comment] 2022-05-21 05:52
We don't supply a word loud function so you will have tot ale this up elsewhere or isolate the Matplotlib bug.

**Comment by majidebraa** [comment] 2022-05-21 11:49
the problem, not word cloud. basically, the problem whit showing Persian or Arabic language on the axises and in plot

**Comment by timhoffm** [comment] 2022-05-21 12:22
This looks like the used font does not provide persian characters. Have you set a knot working font?

**Comment by jklymak** [comment] 2022-05-21 13:33
@majidebraa We can't help you if we know nothing about what you did or how.  I'm going to close this, and encourage you to either edit this issue with all the information we asked for in the issue template, or open a new issue with that information.   Of note, we need to know your system, python versions, matplotlib version, backend etc.  We also need a self-contained reproducible example that we can run, preferably confined to loading matplotlib and numpy.  Thanks for your understanding.

**Closed by jklymak** 2022-05-21 13:33 UTC
Labels: status: needs clarification

**Comment by majidebraa** [comment] 2022-05-21 13:41
> This looks like the used font does not provide Persian characters. Have you set a knot working font?

@timhoffm I set Persian font but just matplotlib set it for title
![plot_2](https://user-images.githubusercontent.com/82038698/169654202-85821b75-b826-4ff1-87a8-ee4cc8be7c8f.png)
 my code for set font:
```
font_path = 'iransans/iran_sans_normal.ttf'
font_manager.fontManager.addfont(font_path)
prop = font_manager.FontProperties(fname=font_path)
matplotlib.rcParams['font.family'] = prop.get_name()
```

**Comment by majidebraa** [comment] 2022-05-21 13:44
> @majidebraa We can't help you if we know nothing about what you did or how. I'm going to close this, and encourage you to either edit this issue with all the information we asked for in the issue template, or open a new issue with that information. Of note, we need to know your system, python versions, matplotlib version, backend etc. We also need a self-contained reproducible example that we can run, preferably confined to loading matplotlib and numpy. Thanks for your understanding.

@jklymak 

python == 3.8
os == windows
ide == pycharm community edition
matplotlib==3.5.2
