### ISSUE TITLE
[Bug]: matplotlib figures inhibit `input` longer than 100 chars in IPython

### ISSUE THREAD

**Issue by jdtsmith** [matplotlib/matplotlib#25756] opened 2023-04-23 16:54 UTC
### Bug summary

After matplotlib activates a plot in IPython, `input` behavior is changed.  In particular, input longer than 100 characters is no longer directly accepted.  Since IPython uses `input` in its REPL loop when `--simple-prompt` is set, this defeats various modes (such as Emacs) which use this.

### Code for reproduction

```python
% python3 -m IPython --simple-prompt
Python 3.11.3 (main, Apr  7 2023, 19:29:16) [Clang 14.0.0 (clang-1400.0.29.202)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: input('Test1: '); print("success!")
Test1: avaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravar=3
success!

In [2]: import matplotlib.pyplot as plt; plt.plot([1])
Installed osx event loop hook.
Out[2]: [<matplotlib.lines.Line2D at 0x10a704a10>]

In [3]: input('Test2: '); print("success!")
Test2: avaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravar=3
# Return does not send the input
```

### Actual outcome

To send the input, an additional newline is required, which is then interpreted as an additional (blank) command.  Commands shorter than 100 characters are still directly accepted.

### Expected outcome

Python's native `input` should work the same in IPython before and after activating a matplotlib figure, for arbitrary command lengths (up to the terminals line length limit). 

### Additional information

Issue posted with IPython as well: ipython/ipython#14030. I have tested disabling `enable_gui`, but this is not the culprit.  To see the bug, you must actually create a figure (but do not need to show it).  This does not occur in regular `python` sessions, only IPython (and possibly only on MacOS?).

### Operating system

MacOS 12.6

### Matplotlib Version

3.7.1 (same behavior on various versions back to 3.4)

### Matplotlib Backend

MacOSX (though same behavior with other backends, e.g. qt6)

### Python version

3.11.3 (same behavior back to 3.9)

### Jupyter version

n/a

### Installation

pip

**Comment by tacaswell** [comment] 2023-04-24 13:23
> I have tested disabling enable_gui, but this is not the culprit. 

What exactly does this mean?  In pyplot we will detect if IPython is imported, and if so run IPython specific code https://github.com/matplotlib/matplotlib/blob/d77801ea94b06b990fc2b535a42522b45143e630/lib/matplotlib/pyplot.py#L173-L207 which is called at tho bottom of `plt.switch_backend`.

If you set the backend to Agg (or any of the non-interactive backends) does the problem go away?  My _guess_ is that something about the way the GUI eventloop integrates....

iirc IPython patches `input`.

**Comment by tacaswell** [comment] 2023-04-24 14:51
I can reproduce this on linux with qt6.

**Comment by jdtsmith** [comment] 2023-04-24 15:44
>> I have tested disabling enable_gui, but this is not the culprit.

> What exactly does this mean? 

I mean I considered that the installation of the interactive event loop by IPython was responsible.  So I altered `TerminalInteractiveShell::enable_gui` to return immediately, without any change in behavior (other than inhibiting the "Installed osx event loop hook." message).   

I've also tried:

- auditing input: no audit events arrive after the first `Return` on >100 char input. 
- tracing all line by line events: no trace events of any kind arrive after the first `Return` on >100 char input.

So it seems some quite primitive change in `input` data handling gets activated somehow by matplotlib.

**Comment by tacaswell** [comment] 2023-04-24 16:56
ok, good news and bad news: It is indeed the inputhook (good news, we know where the problem is), but it is at the level of the GUI toolkits interacting with `PyOSInputHook` and readline (bad news, it involves `fgets` and upstream).


-------

First test is to use PyQt6 which install an inputhook on import but also provides a method to remove / restore it:


```
✔ 12:13:28 $ python3 -m IPython --simple-prompt
Python 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import PyQt6

In [2]: import PyQt6.QtCore

In [3]: PyQt6.QtCore.pyqtRemoveInputHook
Out[3]: <function PyQt6.QtCore.pyqtRemoveInputHook>

In [4]: input('Test2: '); print("succes")
Test2: avaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravarava
succes

In [5]: import matplotlib.pyplot as plt; plt.plot(range(5))
Installed qt6 event loop hook.
Out[5]: [<matplotlib.lines.Line2D at 0x7f2951060670>]

In [6]: input('Test2: '); print("succes")
Test2: avaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravar=3

succes

In [7]:
In [7]: PyQt6.QtCore.pyqtRemoveInputHook()

In [8]: input('Test2: '); print("succes")
Test2: avaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravar=3
succes

In [9]: PyQt6.QtCore.pyqtRestoreInputHook()

In [10]: input('Test2: '); print("succes")
Test2: avaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravar=3

succes

In [11]:
In [11]:
```


To confirm, if we force to use PySide6 (which does not even ship with a readline associated inputhook)

```
✔ 12:21:02 $ python3 -m IPython --simple-prompt
Python 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import PySide6.QtCore

In [2]: import matplotlib.pyplot as plt; plt.plot(range(5))
Installed qt6 event loop hook.
Out[2]: [<matplotlib.lines.Line2D at 0x7fdf460f19c0>]

In [3]: type(fig.canvas).mro()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 type(fig.canvas).mro()

NameError: name 'fig' is not defined

In [4]: fig = plt.gcf()

In [5]: type(fig.canvas).mro()
Out[5]:
[matplotlib.backends.backend_qtagg.FigureCanvasQTAgg,
 matplotlib.backends.backend_agg.FigureCanvasAgg,
 matplotlib.backends.backend_qt.FigureCanvasQT,
 matplotlib.backend_bases.FigureCanvasBase,
 PySide6.QtWidgets.QWidget,
 PySide6.QtCore.QObject,
 PySide6.QtGui.QPaintDevice,
 Shiboken.Object,
 object]

In [6]: input('Test2: '); print("succes")
Test2: avaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravar=3
succes

In [7]:
```

we do not have the problem.

I also tested with `tk` (assuming that if the buggy bit was the input hook the tk one would have a better chance of being right).


-----


I have a theory:

Start from https://github.com/python/cpython/blob/385d8d2b6438c7825006df6106dab41a95332a6a/Parser/myreadline.c#L47-L58

```c
    while (1) {
        if (PyOS_InputHook != NULL) {
            (void)(PyOS_InputHook)();
        }


        errno = 0;
        clearerr(fp);
        char *p = fgets(buf, len, fp);
        if (p != NULL) {
            return 0; /* No error */
        }
        int err = errno;
```
 
so while waiting for the human run the input hook, the input hooks are expected to exit when they detect a keystroke (or just run for a very short time).  If you then look at https://github.com/python/cpython/blob/385d8d2b6438c7825006df6106dab41a95332a6a/Parser/myreadline.c#L304-L322

```c
    do {
        size_t incr = (n > 0) ? n + 2 : 100;
        if (incr > INT_MAX) {
            PyMem_RawFree(p);
            PyEval_RestoreThread(tstate);
            PyErr_SetString(PyExc_OverflowError, "input line too long");
            PyEval_SaveThread();
            return NULL;
        }
        pr = (char *)PyMem_RawRealloc(p, n + incr);
        if (pr == NULL) {
            PyMem_RawFree(p);
            PyEval_RestoreThread(tstate);
            PyErr_NoMemory();
            PyEval_SaveThread();
            return NULL;
        }
        p = pr;
        int err = my_fgets(tstate, p + n, (int)incr, sys_stdin);
```

that is where the 100 comes from.

My guess as that the story is something like:

1. you paste in / type a long line
2. you hit enter, the inputhook exits and python reads the first 100 characters
3. the inputhook restarts, and just runs
4. you hit enter again, it sees the new line(s) at the end and returns


Problems with my theory:

 - I thought inputhooks exited on every keystroke, but apparently only on return (?!)


I suspect the right fix is for in `my_fgets` for upstream to keep trying to drain the buffer before starting the input hook.

**Comment by jdtsmith** [comment] 2023-04-24 19:57
Wow, good sleuthing.  And here I was ripgrepping for `100` all around the IPython and matplotlib codebases.  Who is installing the input hook?  Is there an opportunity to debug on that side?

BTW, I tried installing PySide6, but it did not fix things:

```python
% python3 -m IPython --simple-prompt 
Python 3.11.3 (main, Apr  7 2023, 19:29:16) [Clang 14.0.0 (clang-1400.0.29.202)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import PySide6.QtCore

In [2]: import matplotlib.pyplot as plt; plt.plot(range(5))
Installed osx event loop hook.
Out[2]: [<matplotlib.lines.Line2D at 0x11cb7f790>]

In [3]: input('Test2: '); print("success")
Test2: avaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravar=12345
# double Ret needed
success

In [4]: 
In [4]: 
```

**Comment by tacaswell** [comment] 2023-04-24 21:09
`type(fig.canvas).mro()` is the most reliable way to say which backend you are using, you can also start with the `MPLBACKEND=qtagg' env set.  If you do not set the backend we guess and on mac we try OSX first.

I think this is the input hook for the OSX backend: https://github.com/matplotlib/matplotlib/blob/52a2a7ca6a52bd4a1544d391e75534a7c610a91f/src/_macosx.m#L89-L179

and where it is installed: https://github.com/matplotlib/matplotlib/blob/52a2a7ca6a52bd4a1544d391e75534a7c610a91f/src/_macosx.m#L288

(but I confess I do not understand _how_ that line installs it) so we are doing that.  

It looks like tk does it when you create the tk application (https://github.com/python/cpython/blob/518050ced18422fd00fadc1a81b0d942b98e2e5b/Modules/_tkinter.c#L689)

For Qt, it does it after some sort of initialization, but I do not understand enough of the sip build chain to understand:

```
%PostInitialisationCode
// Process events from the input hook.
PyOS_InputHook = qtcore_input_hook;
%End

```

but given that the function requires using the QApplication (which must be a process singleton) I suspect it is connected just after the application is created.

I do not know off the top of my head what gtk and wx do.

**Comment by jdtsmith** [comment] 2023-04-24 21:50
Right you are (below).  PySide doesn't seem to process interactive events for me, so I guess it functions like Agg (no input hook?).  That seems to indicate that _all_ input hooks are showing this problem (though did you say wx didn't?  I can't test that one).  Maybe a better argument for an upstream fix?

```python
% MPLBACKEND=qtagg python3 -m IPython --simple-prompt
Python 3.11.3 (main, Apr  7 2023, 19:29:16) [Clang 14.0.0 (clang-1400.0.29.202)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import PySide6.QtCore

In [2]: import matplotlib.pyplot as plt; plt.plot(range(5))
Installed qt6 event loop hook.
Out[2]: [<matplotlib.lines.Line2D at 0x120381f10>]

In [3]: type(plt.gcf().canvas).mro()
Out[3]: 
[matplotlib.backends.backend_qtagg.FigureCanvasQTAgg,
 matplotlib.backends.backend_agg.FigureCanvasAgg,
 matplotlib.backends.backend_qt.FigureCanvasQT,
 matplotlib.backend_bases.FigureCanvasBase,
 PySide6.QtWidgets.QWidget,
 PySide6.QtCore.QObject,
 PySide6.QtGui.QPaintDevice,
 Shiboken.Object,
 object]

In [4]: input('Test2: '); print("success!")
Test2: avaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravar=3
success!

In [5]: 
```

**Comment by jdtsmith** [comment] 2023-04-24 21:56
I'm also confused as to why this works without issue:

```python
% python3
Python 3.11.3 (main, Apr  7 2023, 19:29:16) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
>>> plt.ion()
<contextlib.ExitStack object at 0x101ff8050>
>>> plt.plot(range(5))
[<matplotlib.lines.Line2D object at 0x105082710>]
>>> input('Test2: '); print("success!")
Test2: avaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravar=3
'avaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravaravar=3'
success!
>>> 
```

Where is the figure event loop running if not via an input hook?

**Comment by tacaswell** [comment] 2023-04-24 21:57
> Wow, good sleuthing.

I wish I could say this was my first round of debugging this sort of issue 🤣 .


Sorry, I meant to say "I do not know what gtk and wx do about `PyOS_InputHook`".


----

> Maybe a better argument for an upstream fix?

Yes, I am convinced that this is an upstream CPython bug and should be fixed there.


---

> PySide doesn't seem to process interactive events for me, so I guess it functions like Agg (no input hook?).

It does not process events while waiting for the human, if you do `plt.show()` it will run the event loop in a blocking way and be live (but it will block your prompt for any other work).  See https://matplotlib.org/stable/users/explain/interactive_guide.html#eventloop-integration-mechanism for more details.

**Comment by tacaswell** [comment] 2023-04-24 22:43
> I'm also confused as to why this works without issue:

For me with PyQt6 I also see the 100 character limit issue unless I do `PyQt6.QtCore.pyqtRemoveInputHook()` (and if I do so the figure is not interactive whille `input` is blocking the prompt) in prompt toolkit IPython.  So, I am also confused why it works!

**Comment by jdtsmith** [comment] 2023-04-25 16:27
If `fgets` blocks waiting for `\n` or `len` chars, doesn't that mean the input hook runs only _once_ (per increment), then fgets waits for (up to) 100 characters to arrive?  That doesn't seem consistent with figure event behavior during command creation.  For example the x,y readout on plots certainly works in the midst of typing a long command.  I.e., I'd expect the while(1) loop to be spinning fast.  Maybe it relies on `fgets` returning an _error_ over an over, until data are actually present on stdin?

**Comment by tacaswell** [comment] 2023-04-25 17:28
> doesn't that mean the input hook runs only once (per increment), then fgets waits for (up to) 100 characters to arrive?

Yes, but the order is:

 - PyOS_InputHook runs (forever) which spins the UI event loop
 - stdin declares itself ready to read and via the UI event loop stops the UI event loop
 - fgets reads (up to) 100 characters (or `n+2` in subsequent calls)

I think it most operations that `while(1)` loop only actually runs once and returns very early.


hiting `ctrl-D` is what sends EOF, if there is nothing there `fgets` just waits.

Digging into this a bit more, it seems to be the case that when starting Python with a prompt the stdin is line buffered so things only show up as readable in new-line terimnated chunks.  I think this means my proposed fix will behave very badly if you turn that off.

xref https://discuss.python.org/t/unbuffered-stdin-bug-in-docs-or-implementation/20361/24

Also https://www.gnu.org/software/libc/manual/html_node/I_002fO-on-Streams.html for understading what the c code is doing with the stream.

**Comment by jdtsmith** [comment] 2023-04-25 20:02
Oh I think I see.  So the input hook is responsible for using `select` or similar on stdin, and during its event loop it only returns when there is something for fgets to read, which will either include a newline or "enough" characters as requested.  If there are more than enough character data, the input hook is called _again_, but this time it doesn't break until yet more data are available (like a return key).

Most terminals are line-buffered, but you could try `!stty raw` to see how bad it goes.  I've occasionally used a pipe instead of TTY to communicate with iPython; the gui event loop certainly won't run in that case (though I wish it would; it's _much_ faster than TTY's on MacOS).

**Comment by tacaswell** [comment] 2023-04-25 21:42
My brain is apparently sufficiently warped by Python I did not grok that was a global 🤦🏻 .

**Comment by tacaswell** [comment] 2023-04-27 04:05
I'm trying to get a minimal reproduction example before going upstream with this bug + patch.  The following is about as minimal of a Tk app as I think is rich enough to show everything working

```python
from tkinter import *
from tkinter import ttk


def run():
    root = Tk()
    frm = ttk.Frame(root, padding=10)
    frm.grid()
    lbl = ttk.Label(frm, text="Hello World!")
    lbl.grid(column=0, row=0)

    j = 0

    def set_label():
        nonlocal j
        j += 1
        lbl["text"] = f"push count = {j}"

    ttk.Button(frm, text="Push Me!", command=set_label).grid(column=1, row=0)

    return root, frm


```

however if you just fire up the plain Python prompt it will use the readline version of the terminal + input which does not have the bug.  Still working on how to reproduce without using IPython....

**Comment by jdtsmith** [comment] 2023-04-27 12:21
Hmm.  What happens if you unload the readline module and use input?

**Comment by tacaswell** [comment] 2023-04-27 14:51
once you can type Python at the interactive Python shell it is too late (the readline modules registers itself as the provider of interactive stdin functions on module import and you can only do that registration via the c-api).  I did not track through where Python tries to import readline on startup if it detects it is in interactive mode at a tty, but I suspect it is "early".

-----

I got a minimal reproducer working (ok, not strictly minimal but it is self-describing):

```python
import string
import sys
from tkinter import Tk
from tkinter import ttk


def run():
    """
    This sets up a minimal tk application that has enough functionality
    to verify it is "live" and the inputhook is running while waiting for
    user input.
    """
    root = Tk()
    frm = ttk.Frame(root, padding=10)
    frm.grid()
    lbl = ttk.Label(frm, text="push count = 0")
    lbl.grid(column=0, row=0)

    j = 0

    def set_label():
        nonlocal j
        j += 1
        lbl["text"] = f"push count = {j}"

    ttk.Button(frm, text="Push me!", command=set_label).grid(column=1, row=0)

    return root, frm


run()

print("This is a demo of a bug in the non-readline based stdio code\n\n")
print(f"The readline module is not loaded {'readline' in sys.modules}")

test_string = (string.ascii_lowercase + string.ascii_uppercase) * 2

print(
    f"""
We are using the test string :

\t{test_string}

as it is easy to eyeball the length (it is 104 characters long in 26
character blocks).

You should see a tk window with a button that says "Push me!" and a counter.
Pushing the button should increment the counter.

Follow the instructions to demonstrate the bug.


"""
)

print(
    f"""
To see a case where it works paste

{test_string[:10]}

into the prompt below.  Before hitting return, try pushing
the button on the UI to verify that the inputhook is running.
"""
)

a = input("paste here >> ")
print(f"You pasted {a}")


print(
    f"""
To see it fail past the full string

{test_string}

into the prompt below (you will have to hit enter twice)
"""
)

a = input("paste here >> ")
print(f"You pasted {a}")

print("There is still a newline in the buffer, this input will be 'skipped'\n")
a = input("you can not input here >> ")
print(f"we got an empty string!: {a=!r} (also note no new line in stdout)")


print(
    f"""

you can now play with it or ctrl-d to exit.

The longest string that works is:

{test_string[:98]}

"""
)

while True:
    print("\n")
    a = input("test input >> ")
    print(f"what you entered: {a=}")


```


I'm going to go ahead and open a bug (and PR) upstream with this.

**Comment by tacaswell** [comment] 2023-04-27 15:43
https://github.com/matplotlib/matplotlib/issues/25756 is the upstream PR.

**Comment by tacaswell** [comment] 2023-04-27 15:44
I am going to close this as it requires and upstream fix and I do not think there is anything else we can do at the Matplotlib (or IPython) level to address this.

**Closed by tacaswell** 2023-04-27 15:44 UTC

**Comment by jdtsmith** [comment] 2023-05-07 16:49
I am discouraged by finding [15 year old](https://bugs.python.org/issue23237) PyOS_InputHook bugs that never got traction.  In the meantime, can you think of any practical work-arounds, aside from unsetting/resetting the input hook around long commands?
