### ISSUE TITLE
Incorrect coordinates from onselect callback function with RectangleSelector

### ISSUE THREAD

**Issue by rowlesmr** [matplotlib/matplotlib#20592] opened 2021-07-07 09:50 UTC
### Bug report
 
The coordinates reported for `eclick` and `erelease` from the `onselect` callback function don't match what was actually clicked on when drawing a rectangle with `RectangleSelector`

**Code for reproduction**

```python
from matplotlib.backend_bases import MouseButton, MouseEvent
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.widgets import RectangleSelector


xdata = np.linspace(0,9*np.pi, num=301)
ydata = np.sin(xdata)

def rect_coords_from_clicks(eclick, erelease):
    x1, y1 = eclick.xdata, eclick.ydata
    x2, y2 = erelease.xdata, erelease.ydata
    print(f"You pressed at {(x1,y1)}, and released at {(x2,y2)}.")

def on_press(event):
    print(f"You pressed {str(event.button)} at {(event.xdata, event.ydata)}.")

def on_release(event):
    print(f"You released {str(event.button)} at {(event.xdata, event.ydata)}.")

fig, ax = plt.subplots()
line, = ax.plot(xdata, ydata)

rs = RectangleSelector(ax, rect_coords_from_clicks, button=[MouseButton.LEFT])

plt.connect('button_press_event', on_press)
plt.connect('button_release_event', on_release)

plt.show()
```

**Actual outcome**

clicking the left mousebutton at ~(0,0), dragging the rectangle to ~(25,-1) and then releasing results in the following
```
You pressed MouseButton.LEFT at (0.028502352703939415, -0.009523809523809268).
You pressed at (0.028502352703938527, -0.9976190476190476), and released at (24.922457204324836, -0.009523809523809268).
You released MouseButton.LEFT at (24.922457204324836, -0.9976190476190476).
```

clicking the left mousebutton at ~(25,1), dragging the rectangle to ~(0,0) and then releasing results in the following
```
You pressed MouseButton.LEFT at (25.04786755622217, -0.9797619047619047).
You pressed at (0.028502352703938527, -0.9797619047619047), and released at (25.04786755622217, 0.0023809523809525945).
You released MouseButton.LEFT at (0.028502352703939415, 0.0023809523809525945).
```

The coordinates of click and release aren't respected by the onselect function of RectangleSelector: the "click" coordinate is always the bottom left corner of the rectangle and the "release" coordinate is always the top right corner.

The coordinates given by the `on_press` and `on_release` functions are always correct.

**Expected outcome**

clicking the left mousebutton at ~(0,0), dragging the rectangle to ~(25,-1) and then releasing results in the following
```
You pressed MouseButton.LEFT at (0.028502352703939415, -0.009523809523809268).
You pressed at (0.028502352703939415, -0.009523809523809268), and released at (24.922457204324836, -0.9976190476190476).
You released MouseButton.LEFT at (24.922457204324836, -0.9976190476190476).
```

clicking the left mousebutton at ~(25,1), dragging the rectangle to ~(0,0) and then releasing results in the following
```
You pressed MouseButton.LEFT at (25.04786755622217, -0.9797619047619047).
You pressed at (25.04786755622217, -0.9797619047619047), and released at (0.028502352703939415, 0.0023809523809525945).
You released MouseButton.LEFT at (0.028502352703939415, 0.0023809523809525945).
```

The coordinates reported by `eclick` and `erelease` should match the actual click and release coordinate.

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 3.4.2
  * Matplotlib backend: Qt5Agg
  * Python version: 3.9.4

**Comment by rowlesmr** [comment] 2021-07-07 13:18
On further investigation, the issue comes from `RectangleSelector`. On button-press,  `_press` takes the `event.xdata` and `event.ydata` and puts it into `extents`. On button-release, `_release` takes the ordinates given by `extents`. `extents` is not designed to keep the coordinates of button press/release, it is designed to keep the coordinates of a rectangle:

``` python
    @property
    def extents(self):
        """Return (xmin, xmax, ymin, ymax)."""
        x0, y0, width, height = self._rect_bbox
        xmin, xmax = sorted([x0, x0 + width])
        ymin, ymax = sorted([y0, y0 + height])
        return xmin, xmax, ymin, ymax
```

We would need to introduce (something like) a new function to specifically keep button press/release ordinates

``` python
    @property
    def press_release(self):
        """Return (xpress, xrelease, ypress, yrelease)."""
        # code goes here
        return xpress, xrelease, ypress, yrelease
```

**Comment by QuLogic** [comment] 2021-07-08 06:14
Duplicate of #9608.

**Closed by QuLogic** 2021-07-08 06:14 UTC
Labels: topic: widgets/UI
