### ISSUE TITLE
Axes3d does not correctly set the log z scale

### ISSUE THREAD

**Issue by samcunliffe** [matplotlib/matplotlib#15248] opened 2019-09-11 14:13 UTC
### Bug report

**Bug summary**

Bar chart with Axes3d does not correctly set the log z scale. There is a note in the doc: [here](https://matplotlib.org/mpl_toolkits/mplot3d/api.html#mpl_toolkits.mplot3d.axes3d.Axes3D.set_zscale) saying this was added in 1.1.0. (And also asks to report bugs :-) )

**Code for reproduction**

```python
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 unused import
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# dumb dump of data
dx, dy = 0.5, 0.5
xpos = [0.25, 0.25, 0.25, 0.25, 
        1.25, 1.25, 1.25, 1.25, 
        2.25, 2.25, 2.25, 2.25]
ypos = [0.25, 1.25, 2.25, 3.25, 
        0.25, 1.25, 2.25, 3.25,
        0.25, 1.25, 2.25, 3.25]
dz = [1.,  0.517e6,  4.7e6,  2.2e6,  
      1.,  105e6,  96e6,  1.28e9, 
      1.,   1.776e9 ,  4.18e9 ,173.1e9]

ax.set_zlabel("mass [eV]")
ax.set_ylabel("type")
ax.set_xlabel("generation")
ax.set_xticklabels(["", "1", "", "2", "", "3"])
ax.set_yticklabels(["", r"$\nu$", "", r"$\ell$", "", "d", "", "u"])
ax.set_zscale('log')
ax.bar3d(xpos, ypos, 0, dx, dy, dz)

plt.tight_layout()
plt.savefig('Desktop/brokenlog.png')
plt.show()


```

**Actual outcome**
![brokenlog](https://user-images.githubusercontent.com/1836192/64704733-0b921880-d4af-11e9-9321-279cd99bc96a.png)

**Expected outcome**

Log scale on z axis w/ ticks at orders of magnitude.

**Matplotlib version**

  * Operating system: ubuntu 18.04 LTS
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline

  * Python version: 3.6.8
  * Jupyter version (if applicable): 4.4.0

matplotlib installed/updated via `pip3`.

**Comment by harshanavkis** [comment] 2019-09-12 04:55
Is anybody working on this? Is a fix needed? Where do I start?

**Comment by tacaswell** [comment] 2020-06-26 23:09
Duplicate of #209 ?

**Comment by anntzer** [comment] 2021-05-10 14:10
Closing as dupe of #209 (also the docstring has been updated to indicate that only "linear" is supported).

**Closed by anntzer** 2021-05-10 14:10 UTC
Labels: topic: mplot3d
