### ISSUE TITLE
Arrow annotations behave differently between 1.3.1 and 1.4.2

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#4012] opened 2015-01-19 10:13 UTC
~~Sorry, here's another one without a simplified test case. I will try and get to that tomorrow. For this, you will need matplotlib 1.4.2 and the development version of [ObsPy](https://github.com/obspy/obspy). Then run `obspy3-runtests -d obspy.station.tests.test_station.StationTest.test_response_plot`.~~ Test case is below.

With mpl 1.3.1, the plot is as so:
![station_response](https://cloud.githubusercontent.com/assets/302469/5798822/65e23d88-9f99-11e4-9a24-874f3eee5285.png)

With mpl 1.4.2 (and master), the plot is as so:
![station_response](https://cloud.githubusercontent.com/assets/302469/5798827/77bac822-9f99-11e4-9848-b359a5693c6e.png)

![station_response-failed-diff](https://cloud.githubusercontent.com/assets/302469/5798832/7feab8fe-9f99-11e4-9aa1-8b5a01ee8727.png)

You can see that the arrows are thinner and shifted a bit.

I believe the relevant bit of code is the following, but I will try to simplify it later:
```
            trans_above = blended_transform_factory(ax1.transData,
                                                    ax1.transAxes)
            trans_right = blended_transform_factory(ax1.transAxes,
                                                    ax1.transData)
            arrowprops = dict(
                arrowstyle="wedge,tail_width=1.4,shrink_factor=0.8", fc=color)
            bbox = dict(boxstyle="round", fc="w")
            ax1.annotate("%.1g" % self.instrument_sensitivity.frequency,
                         (self.instrument_sensitivity.frequency, 1.0),
                         xytext=(self.instrument_sensitivity.frequency, 1.1),
                         xycoords=trans_above, textcoords=trans_above,
                         ha="center", va="bottom",
                         arrowprops=arrowprops, bbox=bbox)
            ax1.annotate("%.1e" % self.instrument_sensitivity.value,
                         (1.0, self.instrument_sensitivity.value),
                         xytext=(1.05, self.instrument_sensitivity.value),
                         xycoords=trans_right, textcoords=trans_right,
                         ha="left", va="center",
                         arrowprops=arrowprops, bbox=bbox)
```

I did a bisect and the bad commit was:
```
3363b125715724ad89d4b33cbddb23e31e7277d5 is the first bad commit
commit 3363b125715724ad89d4b33cbddb23e31e7277d5
Author: Thomas A Caswell <tcaswell@gmail.com>
Date:   Tue Aug 27 17:07:58 2013 -0500

    re factored `_AnnoationBase` to push keeping track of there the
    secondary object is to the sub-classes.
    
    Added properties to maintain back-compatibility
    
    added properties to replace xytext and textcoords (xyann, anncoords)
    
    properly deprecated `textcoord` and `xytext` in favor of `anncoords`
    and `xyann`.

:040000 040000 f17d8e1a70232471435f96b1faa8550bc697ec32 567d4a0a86bb3d1fb7ec55dc0fa98e86c1dec71a M	doc
:040000 040000 34339e9d0d9f49477908fc3c3227b1b7b55735b4 4dc225e1358d422aa86f9361672c36e127955bee M	lib
```

**Comment by tacaswell** [comment] 2015-01-19 15:18
man, that commit message is embarrassing ...

**Comment by tacaswell** [comment] 2015-01-19 16:49
I suspect something subtle got broken when annotations changed from a 'has-a' to 'is-a'  `Text` object.

My guess is that something changed about where the base of the arrow is calculated and poor interaction with the `FancyArrowPatch` object that gets created.

I am some what more distressed by the extra blue lines around the vertical blue dashed lines.

**Comment by tacaswell** [comment] 2015-01-19 16:57
in `_update_positoin_xytext` there are a bunch of calls to `get_window_extent` which is where I suspect the issue is (as the reported extent of the annotation object may have changed.

(mostly notes to my self)

**Comment by WeatherGod** [comment] 2015-01-19 18:13
"something changed about where the base of the arrow is calculated"

This sounds familiar. I think we fixed a real bug wrt how the arrow was
positioned awhile back.

On Mon, Jan 19, 2015 at 11:49 AM, Thomas A Caswell <notifications@github.com

**Comment by tacaswell** [comment] 2015-01-19 19:57
@WeatherGod How recently?

**Comment by WeatherGod** [comment] 2015-01-19 21:04
Perhaps this (or one of the ones referenced in it)?
https://github.com/matplotlib/matplotlib/pull/566
But, for some reason, I am thinking of something more recently (like, a bug
fixed for 1.3.x)

**Comment by QuLogic** [comment] 2015-01-20 00:34
For a simpler example, I took the `annotation_demo.py` example and changed the `arrowprops` to match the one in ObsPy.

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse


fig = plt.figure()
ax = fig.add_subplot(111, autoscale_on=False, xlim=(-1,5), ylim=(-3,5))

t = np.arange(0.0, 5.0, 0.01)
s = np.cos(2 * np.pi * t)
ax.plot(t, s, lw=3, color='purple')

arrowprops = dict(arrowstyle="wedge,tail_width=1.4,shrink_factor=0.8")

ax.annotate('axes center', xy=(.5, .5),  xycoords='axes fraction',
            horizontalalignment='center', verticalalignment='center',
            arrowprops=arrowprops)

ax.annotate('pixels', xy=(20, 20),  xycoords='figure pixels',
            arrowprops=arrowprops)

ax.annotate('points', xy=(100, 300),  xycoords='figure points',
            arrowprops=arrowprops)

ax.annotate('offset', xy=(1, 1),  xycoords='data',
            xytext=(-15, 10), textcoords='offset points',
            horizontalalignment='right', verticalalignment='bottom',
            arrowprops=arrowprops)

ax.annotate('local max', xy=(3, 1),  xycoords='data',
            xytext=(0.8, 0.95), textcoords='axes fraction',
            horizontalalignment='right', verticalalignment='top',
            arrowprops=arrowprops)

ax.annotate('a fractional title', xy=(.025, .975),
            xycoords='figure fraction',
            horizontalalignment='left', verticalalignment='top',
            fontsize=20,
            arrowprops=arrowprops)

ax.annotate('bottom right (points)', xy=(-10, 10),
            xycoords='axes points',
            horizontalalignment='right', verticalalignment='bottom',
            fontsize=20,
            arrowprops=arrowprops)

plt.show()
```

Here is 1.3.1:
![mpl131](https://cloud.githubusercontent.com/assets/302469/5810285/ca94a464-a011-11e4-9744-724b94cb54ea.png)

Here is 1.4.2:
![mpl142](https://cloud.githubusercontent.com/assets/302469/5810291/cfcf70a8-a011-11e4-9b5a-8edc3e480fba.png)

And the diff:
![diff](https://cloud.githubusercontent.com/assets/302469/5810293/d3ceff8e-a011-11e4-9db6-5083cdfa977a.png)

Hopefully that's a lot easier to test.

**Comment by QuLogic** [comment] 2015-01-20 00:54
> I am some what more distressed by the extra blue lines around the vertical blue dashed lines.

Yea, that's odd too. I will try to see where those lines originate.

**Comment by QuLogic** [comment] 2015-01-21 01:49
> > I am some what more distressed by the extra blue lines around the vertical blue dashed lines.
> 
> Yea, that's odd too. I will try to see where those lines originate.

I honestly don't know where these are from, and they stopped showing up, so I wouldn't worry about them.

**Comment by tacaswell** [comment] 2015-01-21 02:20
this seems to be fixed by #4019

**Comment by QuLogic** [comment] 2015-01-21 02:47
I'm sorry, it seems that simple example exposes a different bug. Here is a test case that should _only_ trigger the bug in the first plot:

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.transforms import blended_transform_factory

fig = plt.figure()
ax = fig.add_subplot(111, autoscale_on=False, xlim=(-1,5), ylim=(-3,5))

t = np.arange(0.0, 5.0, 0.01)
s = np.cos(2 * np.pi * t)
ax.plot(t, s, lw=3, color='purple')

trans_above = blended_transform_factory(ax.transData,
                                        ax.transAxes)
trans_right = blended_transform_factory(ax.transAxes,
                                        ax.transData)

bbox = dict(boxstyle="round", fc="w")

arrowprops = dict(arrowstyle="wedge,tail_width=1.4,shrink_factor=0.8")

ax.annotate("0.1",
            (3, 1.0),
            xytext=(3, 1.1),
            xycoords=trans_above, textcoords=trans_above,
            ha="center", va="bottom",
            arrowprops=arrowprops, bbox=bbox)

ax.annotate("0.2",
            (1.0, 0.75),
            xytext=(1.05, 0.75),
            xycoords=trans_right, textcoords=trans_right,
            ha="left", va="center",
            arrowprops=arrowprops, bbox=bbox)

plt.show()
```

With 1.3.1:
![mpl131](https://cloud.githubusercontent.com/assets/302469/5830385/90b0d3e4-a0ed-11e4-9e68-23424c7e27aa.png)
and with 1.4.2:
![mpl142](https://cloud.githubusercontent.com/assets/302469/5830389/961ca222-a0ed-11e4-9f83-1e8b192cd5ee.png)
Diff:
![diff](https://cloud.githubusercontent.com/assets/302469/5830391/99a6d99e-a0ed-11e4-9372-2805ddf311fa.png)

If you remove the `bbox`, they work the same.

**Comment by tacaswell** [comment] 2015-01-31 22:44
Digging into this I still have no idea what the problem is.  My suspicion is that something I changed had a crucial side effect...

**Comment by tacaswell** [comment] 2015-02-01 05:23
I am going to take one more pass at this tomorrow, if I can't figure it out I am going to boot this to 1.4.x as this seems to be only an issue when using both the `FancyArrowPatch` and `FancyBoundingBox` at the same time.

**Comment by tacaswell** [comment] 2015-02-07 21:34
attn @leejjoon Can you point me in the right direction on this?  I think something in getting out of sync in updating where the center of the text is with the bounding box.

**Comment by tacaswell** [comment] 2015-07-22 04:25
@QuLogic Can you check your examples with current master, I think #4178 fixes part of the issues.

![so](https://cloud.githubusercontent.com/assets/199813/8817921/0fab849c-3008-11e5-888d-ae82a8560888.png)

**Comment by QuLogic** [comment] 2015-07-22 19:29
It's pretty close now. There's a slight difference in the box, but that may be due to font changes (the tick labels have also shifted a little)?

![mpl-master-diff](https://cloud.githubusercontent.com/assets/302469/8835077/4e84ff76-3086-11e5-8fb1-6c5e4c08e86e.png)

**Comment by tacaswell** [comment] 2015-07-22 20:47
I am more concerned about the shift in the plotted line. Did you make the diff from my png, or from running it on your system?

**Comment by QuLogic** [comment] 2015-07-22 20:57
From running it on my system, using the original `mpl131.png` I generated a while back for reference.

**Comment by efiring** [comment] 2015-07-22 21:40
On 2015/07/22 10:47 AM, Thomas A Caswell wrote:
> I am more concerned about the shift in the plotted line.

That looks to me like a difference in rendered width, not in position.

**Comment by QuLogic** [comment] 2015-07-22 21:52
If you're really interested in the shift, the bisect was inconclusive:
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
4a56cdadeb874fd959263fdb7af474c2416457f4
cfbf8d5225ac696cb2c3a8ae096911470074a5f8
339537d58374e8c2f7dd62299a9869d819956937
8dae8186c82f7243b819162d6eb1a64c1afeb379
6e19dac792a42e6cc0f68f2066248a35657673ff
a22596839a7eb31d9700822f2ae09f43c2b765ce
697b3ef37c044787b01344ca166a24d4da58345b
c5ab7474a02f16e75e1bbabcb7af5f7d72f6f847
5204635911f911a48c03ca3cf2f1f70341d396cf
af578f5f35b2d7fef36a35a50d156c027472a816
0624664f857f35583301f55553d28e00a4013770
6d0717930000cafeeecabed900ac1b286a4176da
ba4016014cb4fb4927e36ce8ea429fed47dcb787
d862c4740984433545461ded596d421f48f6b6a7
d8c1d0d5e494465cbc27a639d5337240d84997fe
We cannot bisect more!
bisect run cannot continue any more
```

**Comment by tacaswell** [comment] 2015-07-31 22:14
@QuLogic That is inside of the massive re-work of how we expose Agg up to python.

We have also done some changes to how white space around fonts is handled.

@mdboom I am inclined to call this good enough?

**Comment by tacaswell** [comment] 2015-08-06 20:15
Closing this as 'good enough'. 

@QuLogic Please ping to have this re-opened if you disagree.

**Closed by tacaswell** 2015-08-06 20:15 UTC
Labels: Difficulty: Medium, In Progress, mpl_toolkit
