### ISSUE TITLE
[Bug]: FontManager doesn't get pinging.ttc 

### ISSUE THREAD

**Issue by Artoria2e5** [matplotlib/matplotlib#27705] opened 2024-01-26 11:26 UTC
### Bug summary

`/System/Library/Fonts/PingFang.ttc` is the macOS default Chinese font. The file is a collection of three family names representing three regional glyph variants, PingFang SC, PingFang HK, and PingFang TC. FontManager doesn't seem to be able to find the SC family inside; I haven't tried the others yet.

(Manually constructing a fontProperties works, as demonstrated in https://github.com/matplotlib/matplotlib/issues/20251#issuecomment-843943883. However, it's not a solution for well-encapsulated code from other people.)

### Code for reproduction

```python
import matplotlib
import matplotlib.pyplot as plt
matplotlib.rcParams['font.family'] = ['Ubuntu', 'PingFang SC', 'sans-serif']
plt.title('你好世界world')
plt.savefig("test.png")
```

### Actual outcome

```
indfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
/private/tmp/1.py:5: UserWarning: Glyph 20320 (\N{CJK UNIFIED IDEOGRAPH-4F60}) missing from current font.
  plt.savefig("test.png")
/private/tmp/1.py:5: UserWarning: Glyph 22909 (\N{CJK UNIFIED IDEOGRAPH-597D}) missing from current font.
  plt.savefig("test.png")
/private/tmp/1.py:5: UserWarning: Glyph 19990 (\N{CJK UNIFIED IDEOGRAPH-4E16}) missing from current font.
  plt.savefig("test.png")
/private/tmp/1.py:5: UserWarning: Glyph 30028 (\N{CJK UNIFIED IDEOGRAPH-754C}) missing from current font.
  plt.savefig("test.png")
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
findfont: Font family 'PingFang SC' not found.
```
![test](https://github.com/matplotlib/matplotlib/assets/6459309/8af70e6d-c54b-487a-a482-2eab9d84c5f5)

### Expected outcome

The text should not be thin rectangles.

### Operating system

macOS

### Matplotlib Version

3.8.2

### Matplotlib Backend

MacOSX

### Python version

Python 3.11.6

### Installation

pip

**Comment by Artoria2e5** [comment] 2024-01-26 11:36
Got the debug trace here:
[out.txt](https://github.com/matplotlib/matplotlib/files/14064421/out.txt)

PingFang is only resolved to HK
```
DEBUG:matplotlib.font_manager:findfont: score(FontEntry(fname='/System/Library/Fonts/PingFang.ttc', name='PingFang HK', style='normal', variant='normal', weight=400, stretch='normal', size='scalable')) = 10.05
```

So the issue is probably this: `ttfFontProperty` only returns one property for a whole ttc. It should at least return one *per unique family name*.

**Comment by ksunden** [comment] 2024-01-26 15:00
Yes, currently we have only limited ttc support that only resolves the first font in a ttc.

See #23293 #3135

**Comment by QuLogic** [comment] 2024-01-30 00:14
I'll close as a duplicate of #3135.

**Closed by QuLogic** 2024-01-30 00:14 UTC

**Comment by Artoria2e5** [comment] 2024-01-31 13:29
Fair enough!
