### ISSUE TITLE
`ax.xaxes.axis_date()` fails with `tz` `TypeError` error when units are not recognized/not correctly parsed

### ISSUE THREAD

**Issue by valeriupredoi** [matplotlib/matplotlib#25419] opened 2023-03-09 14:41 UTC
Hello guys, here is a minimal test case you can run see the behaviour: this is for Matplotlib=3.7.1, previous Matplotlbs <3.6 worked fine wrt this:

```python
import matplotlib.pyplot as plt


def test_axes_goes():
    ax = plt.gca()
    ax.xaxis.set_units(None)
    ax.xaxis.axis_date(tz='UTC')


def test_axes_fails():
    ax = plt.gca()
    ax.xaxis.set_units(('proleptic_gregorian', 'days since 2000-01-01'))
    ax.xaxis.axis_date(tz='UTC')


if __name__ == '__main__':
    test_axes_goes()
    test_axes_fails()
```

this fails with:

```
Traceback (most recent call last):
  File "/home/b/b382109/test_matplotlib.py", line 18, in <module>
    test_axes_fails()
  File "/home/b/b382109/test_matplotlib.py", line 12, in test_axes_fails
    ax.xaxis.set_units(('proleptic_gregorian', 'days since 2000-01-01'))
  File "/home/b/b382109/miniconda3/envs/release280rc1/lib/python3.10/site-packages/matplotlib/axis.py", line 1763, in set_units
    axis._update_axisinfo()
  File "/home/b/b382109/miniconda3/envs/release280rc1/lib/python3.10/site-packages/matplotlib/axis.py", line 1692, in _update_axisinfo
    info = self.converter.axisinfo(self.units, self)
  File "/home/b/b382109/miniconda3/envs/release280rc1/lib/python3.10/site-packages/matplotlib/dates.py", line 1933, in axisinfo
    return self._get_converter().axisinfo(*args, **kwargs)
  File "/home/b/b382109/miniconda3/envs/release280rc1/lib/python3.10/site-packages/matplotlib/dates.py", line 1850, in axisinfo
    majloc = AutoDateLocator(tz=tz,
  File "/home/b/b382109/miniconda3/envs/release280rc1/lib/python3.10/site-packages/matplotlib/dates.py", line 1339, in __init__
    super().__init__(tz=tz)
  File "/home/b/b382109/miniconda3/envs/release280rc1/lib/python3.10/site-packages/matplotlib/dates.py", line 1136, in __init__
    tzx = _get_tzinfo(tz)
  File "/home/b/b382109/miniconda3/envs/release280rc1/lib/python3.10/site-packages/matplotlib/dates.py", line 234, in _get_tzinfo
    raise TypeError("tz must be string or tzinfo subclass.")
TypeError: tz must be string or tzinfo subclass.
```

There are two things two unpack here:

- the code should probably not fail with a TimeZone-related error, least a `TypeError` since I am clearly defining my `tz` arg
- if the units are not recognized by Matplotlib, as this is the case, since those are cf_units from an iris cube, there should be a warning or raiser at `ax.xaxis.set_units()` step

Cheers muchly for all your good work! :beer:

**Comment by oscargus** [comment] 2023-03-09 15:17
The error happens in the `set_units`-call, although it relates to `tz` being set incorrectly.

What happens is that `('proleptic_gregorian', 'days since 2000-01-01')` is passed as `tz`. 

Earlier, what was passed as `tz` was just set as the `tz` attribute in `DateLocator` and then you code updated with the correct timezone attribute before it was used. Now, it errors when trying to decode the tuple as a timezone. I am quite sure that it is the wanted behavior, to not be able to arbitrarily set the timezone to whatever, which means that maybe the unit handling should be updated to not go down the date path by default? Is this some way to get it printing as "units"? As I do not think that `('proleptic_gregorian', 'days since 2000-01-01')` is a valid unit specification.

I think that this change has led to that it is no longer possible to pass a string (or a tuple) as units. Not sure if/how that used to work earlier though.

**Comment by valeriupredoi** [comment] 2023-03-09 15:45
cheers muchly @oscargus - let me downgrade to an older Matplotlib, and I'll point you exactly to how that was handled for us. BTW that unit is not the one I have in my actual code in our package, that's almost as the one we have, though, since it's a `cf_units.Unit` object. But let me see if I can dig out the old behaviour, that used to work fine with exactly the same data :+1:

**Comment by valeriupredoi** [comment] 2023-03-09 16:30
Hi @oscargus - I just checked with Matplotlib=3.5.3, and the test script above runs fine, even if that unit is a bit wonky (our real case situation actually has a similar unit `('proleptic_gregorian', 'days since 2000-01-01', <class 'cftime._cftime.datetime'>)`), in both cases above the `tz` is correctly built from a string passed to `axis_date()` and it is `tz = tzfile('/usr/share/zoneinfo/UTC')` - we'd be happy if such a behaviour would be preserved, or, if now Matplotlib really needs correct Matplotlib-readable/recognizable units, then a units-related error should pop up. But it'd be nice if units wouldn't be enforced, since in this case, one can plot one's crazy axes with crazy units without getting an error, just with, say, a warning that the units are not recognized hence the dates displayed may be weird :grin:

**Comment by jklymak** [comment] 2023-03-09 16:35
As @oscargus notes, for datetime units are not really date units, but rather we use timezones as a unit-type. You may have entered your tuple before, but it didn't do anything, now we error that it's not usable as a timezone as passed to tzinfo. 

Looking at the dates.py, I'd argue this is all pretty poorly explained....

Certainly we don't decode cftimes, so specifying a unit like "seconds since 1970-01-01" will not work at all.  Allowing your old units to pass was a bug, and could have lead to very obscure behaviour, whereas now you are getting an error, which I'd strongly argue is correct.

**Comment by oscargus** [comment] 2023-03-09 16:53
The problem is, sort of, that checking if the unit is valid is not done until one actually tries to convert the data or, as in this case, when `update_units` is called. The error message is indeed confusing as it has nothing with the `tz` argument passed in, but the existing `units` being passed. 

It would be (slightly) easier to realize if the incorrect `tz` argument was printed, so I'll add that if nothing else...

**Comment by valeriupredoi** [comment] 2023-03-09 17:02
very cool, cheers muchly, gents! It is now clear to me what's the hap and we've fixed our end of the code too, so please do close this when you think it's time to close (after #25420 gets merged I reckon) :+1:

**Comment by dstansby** [comment] 2024-01-14 19:00
Closing as per the above comment

**Closed by dstansby** 2024-01-14 19:00 UTC
Labels: topic: date handling, topic: units and array ducktypes
