### ISSUE TITLE
[Bug]: Mouse Scroll Event is not caputred if ALT key is pressed

### ISSUE THREAD

**Issue by ramsluk** [matplotlib/matplotlib#25671] opened 2023-04-12 09:46 UTC
### Bug summary

I want to use the scroll event in my plot and define different behavior if a certain modifier key is pressed. I used the standard example and found out no scroll event is triggered when pressing the ALT key. Is there a specific reason for this behavior or is it an actual bug?

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt


class IndexTracker:
    def __init__(self, ax, X):
        self.index = 0
        self.X = X
        self.ax = ax
        self.im = ax.imshow(self.X[:, :, self.index])
        self.update()

    def on_scroll(self, event):
        print(event.button, event.step)
        increment = 1 if event.button == 'up' else -1
        max_index = self.X.shape[-1] - 1
        self.index = np.clip(self.index + increment, 0, max_index)
        self.update()

    def update(self):
        self.im.set_data(self.X[:, :, self.index])
        self.ax.set_title(
            f'Use scroll wheel to navigate\nindex {self.index}')
        self.im.axes.figure.canvas.draw()


x, y, z = np.ogrid[-10:10:100j, -10:10:100j, 1:10:20j]
X = np.sin(x * y * z) / (x * y * z)

fig, ax = plt.subplots()
# create an IndexTracker and make sure it lives during the whole
# lifetime of the figure by assigning it to a variable
tracker = IndexTracker(ax, X)

fig.canvas.mpl_connect('scroll_event', tracker.on_scroll)
plt.show()
```

### Actual outcome

No scroll event at all is captured.

### Expected outcome

Scroll event should be captured.

### Additional information

PyQt recognizes scroll events when pressing ALT

### Operating system

Windows

### Matplotlib Version

3.6.2

### Matplotlib Backend

QtAgg

### Python version

3.9.13

### Installation

pip

**Comment by tacaswell** [comment] 2023-04-12 15:10
> PyQt recognizes scroll events when pressing ALT

How did you test this?

**Comment by tacaswell** [comment] 2023-04-12 15:15
alt + scroll works with tkagg, does not work with qtagg for me (on linux) so the bug is likely someplace in the event handling chain specific to Qt.

I am labeling this as a good first issue as there should be no API design choices and the expected behavior is quite clear, but medium difficulty as it will require understanding both our mpl event handling chain and enough about Qt to sort out what is going wrong.

There are 4 Qt bindings (pyqt and pyside for Qt5 and QT6), I think the first debugging step is to verify this behavior is consistent across all 4 and to get an example Qt program that shows the ALT + scroll being delivered to the Python side of a Qt application.

**Comment by GerardDorado** [comment] 2023-05-12 11:26
Hi! I'm trying to tackle this issue, but I don't have experience with QT. So, I'll share what I've found here in case someone more experienced wants to solve it more quickly.

I believe the issue is that when we press the ALT key, the focus shifts to the menu bar, even though it's not currently displayed in the application. You can try this by pressing ALT, followed by the 'down arrow' key:

![image](https://github.com/matplotlib/matplotlib/assets/39635414/8c74b4c5-b767-428e-884f-e80efb9cad59)

I'm not sure if matplotlib utilizes the menu bar, so I don't know if this behavior is expected or not. If it's not expected, I could attempt to disable the focus change when the ALT key is pressed or find a way to remove the menu bar altogether.

**Comment by tacaswell** [comment] 2023-05-12 14:03
That is not a menu bar we put in, that a menu that comes from the widow manager.

We (Matplotlib) are at the end of a long chain of software from the user pressing a physical key and any of those layers can decide to not forward a key to us (e.g. on my system `win-leftkey` changes my virtual desktop and no application will ever see that set of keys because the desktop manager ate them).  If the problem is the desktop/window manager / UI framework using `alt` to change focus, that is something we (at the Matplotlib level) should accept and leave it to the users to change their environment to _not_ eat those keys of they want to get them into applications.

**Comment by GerardDorado** [comment] 2023-05-16 13:39
Sorry, I was using TkAgg the first time I tried it, so the change of focus was not related to QT (I can create an Issue about that if you want).

I also leave a PR with what I think is the correct solution.

**Comment by tacaswell** [comment] 2023-05-26 15:04
See https://github.com/matplotlib/matplotlib/pull/25895#issuecomment-1559246876

We have decided that this is a feature of Qt (independent if every one agrees it is a good feature) and we should not try to second-guess the behavior.


I'm going to close this with no action, but thank you for the report @ramsluk .

**Closed** 2023-05-26 15:04 UTC
Labels: status: won't or can't fix, GUI: Qt
