### ISSUE TITLE
prop_cycle breaks keyword aliases

### ISSUE THREAD

**Issue by lkluft** [matplotlib/matplotlib#6343] opened 2016-04-28 07:36 UTC
Debian GNU/Linux 6.0.10 (squeeze) and OSX 10.11.4, Python 3.5.1, matplotlib 1.5.1 (anaconda 4.0.5)

Setting the prop_cycle for an axis breaks the usage of keyword aliases in the plot function. In the following snippets the keyword `lw=0.1` is ignored, but `linewidth=0.1` produces the wanted result.

Maybe it is worth mentioning that `color` is still accessible via its alias `c` after setting a prop_cycle.

If it seems weird to set the prop_cycle to just ignore it: I stumbled across this problem while playing around with stylesheets to set a default cycle through different linestyles. But sometimes you want to explicitly change this behaviour.

```python
fig, ax = plt.subplots()
ax.set_prop_cycle('linewidth', [2, 3, 4])
for c in range(5):
    ax.plot(np.arange(10), c * np.arange(10), lw=0.1)
```

![broken](https://cloud.githubusercontent.com/assets/9482218/14878368/67b54a4e-0d23-11e6-8c1e-5e5f2d777a0b.png)

```python
fig, ax = plt.subplots()
ax.set_prop_cycle('linewidth', [2, 3, 4])
for c in range(5):
    ax.plot(np.arange(10), c * np.arange(10), linewidth=0.1)
```

![working](https://cloud.githubusercontent.com/assets/9482218/14878374/6bc90d00-0d23-11e6-8f82-5e939869f28a.png)

**Comment by WeatherGod** [comment] 2016-04-28 13:58
At first, I was thinking this was a duplicate of #5875 (which is fixed in master), but I see that this is different. The problem here is that ax.plot() probably isn't properly normalizing all of the various keyword arguments, and as such doesn't detect that the cycler and the keyword property are colliding.

The `plot()` function explicitly normalizes the 'c' keyword into 'color', but it doesn't do it for any other properties. I think I can put together a patch for this utilizing the same normalization tool that the cycler goes through. @tacaswell, wasn't there another normalization mechanism that was added recently?

**Comment by tacaswell** [comment] 2016-04-28 14:06
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cbook.py#L2449 but we need to _use it_ places now.

**Comment by WeatherGod** [comment] 2016-04-28 14:11
> but we need to use it places now

Sorry... my parser couldn't grok that sentence.

**Comment by tacaswell** [comment] 2016-04-28 14:58
I mean we have the function available to use, but we need to actually use it in `plot`, etc

**Comment by WeatherGod** [comment] 2016-04-28 15:03
Ah. Yeah, I started looking into that, and I am not entirely sure it is ready for prime-time. At least, we don't really have the supporting data for it. One of the big problems I see is that it requires me to know what other keyword arguments will be allowed that don't go through the aliasing mechanism.

Perhaps it makes sense to break this function out into three levels. The first level simply does normalization (like I do in the validation step of prop_cycle), and the second level does precedence handling (conflict resolution), and the third level does the "required"/"allowed" handling?

**Comment by tacaswell** [comment] 2016-04-28 15:29
the `allowed` parameter only does something if it is not `None`, otherwise it lets things pass through.

**Comment by WeatherGod** [comment] 2016-04-28 17:00
I created #6345 that should address this problem. Note that v1.5.x will still have a problem if your manually created property cycle uses aliased property names, but that is fixed in 2.x as I noted earlier.

**Closed** 2016-04-30 07:12 UTC
Labels: needs_review

**Comment by lkluft** [comment] 2016-04-30 07:14
This seems to solve the problem properly so I closed the issue.

Thanks for the quick response!
