### ISSUE TITLE
Segfault when figures are deleted in random order

### ISSUE THREAD

**Issue by olcc** [matplotlib/matplotlib#6231] opened 2016-03-27 17:35 UTC
Hello, please consider the following code...
```
import matplotlib.pyplot as pyplot
fig1 = pyplot.figure()
fig2 = pyplot.figure()
pyplot.show()
```
If I delete Figure 2, then Figure 1, the program finishes correctly.
If I delete Figure 1, then Figure 2, the program finishes with a segmentation error.
I believe that the program should not segfault in the second case.

Olivier
-- Matplotlib 1.5.1, Python 3.5.1, Debian Linux

**Comment by tacaswell** [comment] 2016-03-27 17:42
What backend are you using?

**Comment by olcc** [comment] 2016-03-27 17:46
Using matplotlib backend: TkAgg

**Comment by tacaswell** [comment] 2016-03-27 20:24
I can not reproduce this with 1.5.1 / 3.5.1 from anaconda on arch.

**Comment by cgohlke** [comment] 2016-04-02 04:57
This is a known issue on Python 3.4 for Windows, which ships with an outdated version of tcl86. Maybe that's the case here too? See https://github.com/ipython/ipython/issues/8921 and http://stackoverflow.com/questions/30729180

**Comment by olcc** [comment] 2016-04-02 12:49
Yes, it's the same behavior, but on Linux. I have these packages :
* tcl     8.6.0+9
* tk      8.6.0+9

**Comment by cgohlke** [comment] 2016-04-02 15:59
On Windows tcl/tk 8.6.1 (included with Python 3.4) crashes while tcl/tk 8.6.4 (included with Python 3.5) does not crash.

**Comment by tacaswell** [comment] 2016-04-02 16:38
I was testing with tcl/tk 8.5.0 (what anaconda ships) or 8.6.4 (what arch packages).

@sandrotosi This is something that may need to be addressed in the debian packaging?

**Comment by tacaswell** [comment] 2016-04-02 17:28
Possibly relevant bug report

 - https://bugs.python.org/issue24858 (possibly other packaging issues with debian)

**Comment by tacaswell** [comment] 2016-04-02 17:33
loosely related (tk segfaults due to bad linking) https://github.com/matplotlib/matplotlib/issues/3821

**Comment by tacaswell** [comment] 2016-04-08 05:27
Can someone here who can reproduce this test #6277 ?

**Comment by sandrotosi** [comment] 2016-04-15 21:11
@tacaswell sorry for getting back so late; I just tested on debian with tcl/tk (with TKAgg backend) and I cant reproduce this issue

**Comment by tacaswell** [comment] 2016-04-15 23:19
What is the exact tk/tcl version you used?

**Comment by sandrotosi** [comment] 2016-04-16 00:06
gaah sorry i thought i wrote that: 8.6.5 for tcl and tk

**Comment by tacaswell** [comment] 2016-04-17 05:28
what debian channel are those versions available in?

**Comment by sandrotosi** [comment] 2016-04-17 08:16
debian unstable (but the same version is available also in testing; stable has 8.6.2)

**Comment by mdboom** [comment] 2016-05-16 19:42
Closing as fixed upstream.  We've documented the problematic versions, and I'm not sure if there's much we can do as a workaround.

**Closed** 2016-05-16 19:46 UTC
Labels: needs_review, upstream fix required
