### ISSUE TITLE
[Bug]: MatplotlibDeprecationWarning

### ISSUE THREAD

**Issue by eminphi** [matplotlib/matplotlib#23962] opened 2022-09-20 04:29 UTC
### Bug summary

The line `fig, ax = plt.subplots(nrows=1, ncols=2, figsize=[12,6])` results in the following warning message:

`MatplotlibDeprecationWarning: The resize_event function was deprecated in Matplotlib 3.6 and will be removed two minor releases later. Use callbacks.process('resize_event', ResizeEvent(...)) instead.`

### Code for reproduction

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots(nrows=1, ncols=2, figsize=[12,6])
```

### Actual outcome

`MatplotlibDeprecationWarning: The resize_event function was deprecated in Matplotlib 3.6 and will be removed two minor releases later. Use callbacks.process('resize_event', ResizeEvent(...)) instead.`
`fig, ax = plt.subplots(nrows=1, ncols=2, figsize=[12,6])`

### Expected outcome

No warning message.

### Operating system

macOS

### Matplotlib Version

3.6.0

### Matplotlib Backend

MacOSX

### Python version

3.10.6

### Jupyter version

6.4.12

### Installation

pip

**Comment by QuLogic** [comment] 2022-09-20 04:33
Duplicate of #23921

**Closed by QuLogic** 2022-09-20 04:33 UTC
