### ISSUE TITLE
[Bug] 3.5.1: hidden install time `matplotlib` module dependencies

### ISSUE THREAD

**Issue by kloczek** [matplotlib/matplotlib#22880] opened 2022-04-23 12:41 UTC
### Bug summary

I'm tryng to build `matplotlib` documetation as man page (and fix that process because it doesn't work now). Working on that I found some dependencies which ar enot listed as install time dependencies.

Few fragments from `sphinx-build` command output with som call traces

```console
[tkloczko@devel-g2v matplotlib-3.5.1]$ /usr/bin/sphinx-build -n -T -b man doc build/sphinx/man

[..]

from ipykernel or jupyter_client instead.
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 0 added, 16 changed, 0 removed
reading sources... [100%] users/prev_whats_new/whats_new_3.5.0
/home/tkloczko/rpmbuild/BUILD/matplotlib-3.5.1/doc/api/animation_api.rst:146: WARNING: toctree contains reference to nonexisting document 'gallery/animation/animate_decay'
/home/tkloczko/rpmbuild/BUILD/matplotlib-3.5.1/doc/api/animation_api.rst:146: WARNING: toctree contains reference to nonexisting document 'gallery/animation/bayes_update'
/home/tkloczko/rpmbuild/BUILD/matplotlib-3.5.1/doc/api/animation_api.rst:146: WARNING: toctree contains reference to nonexisting document 'gallery/animation/double_pendulum'
/home/tkloczko/rpmbuild/BUILD/matplotlib-3.5.1/doc/api/animation_api.rst:146: WARNING: toctree contains reference to nonexisting document 'gallery/animation/animated_histogram'
/home/tkloczko/rpmbuild/BUILD/matplotlib-3.5.1/doc/api/animation_api.rst:146: WARNING: toctree contains reference to nonexisting document 'gallery/animation/rain'
/home/tkloczko/rpmbuild/BUILD/matplotlib-3.5.1/doc/api/animation_api.rst:146: WARNING: toctree contains reference to nonexisting document 'gallery/animation/random_walk'
/home/tkloczko/rpmbuild/BUILD/matplotlib-3.5.1/doc/api/animation_api.rst:146: WARNING: toctree contains reference to nonexisting document 'gallery/animation/simple_anim'
/home/tkloczko/rpmbuild/BUILD/matplotlib-3.5.1/doc/api/animation_api.rst:146: WARNING: toctree contains reference to nonexisting document 'gallery/animation/strip_chart'
/home/tkloczko/rpmbuild/BUILD/matplotlib-3.5.1/doc/api/animation_api.rst:146: WARNING: toctree contains reference to nonexisting document 'gallery/animation/unchained'
/home/tkloczko/rpmbuild/BUILD/matplotlib-3.5.1/doc/api/animation_api.rst:165: WARNING: toctree contains reference to nonexisting document 'gallery/animation/dynamic_image'
/home/tkloczko/rpmbuild/BUILD/matplotlib-3.5.1/doc/api/animation_api.rst:245: WARNING: toctree contains reference to nonexisting document 'gallery/animation/frame_grabbing_sgskip'
WARNING: autodoc: failed to import module 'backend_nbagg' from module 'matplotlib.backends'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_nbagg.py", line 15, in <module>
    from ipykernel.comm import Comm
ModuleNotFoundError: No module named 'ipykernel'

[..]

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 62, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_nbagg.py", line 18, in <module>
    from IPython.kernel.comm import Comm
  File "/usr/lib/python3.8/site-packages/IPython/kernel/__init__.py", line 12, in <module>
    warn("The `IPython.kernel` package has been deprecated since IPython 4.0."
IPython.utils.shimmodule.ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.

WARNING: autodoc: failed to import module 'backend_tkagg' from module 'matplotlib.backends'; the following exception was raised:
cannot import name 'ImageTk' from 'PIL' (/usr/lib64/python3.8/site-packages/PIL/__init__.py)
WARNING: autodoc: failed to import module 'backend_tkcairo' from module 'matplotlib.backends'; the following exception was raised:
cannot import name 'ImageTk' from 'PIL' (/usr/lib64/python3.8/site-packages/PIL/__init__.py)
WARNING: autodoc: failed to import module 'backend_webagg' from module 'matplotlib.backends'; the following exception was raised:
Traceback (most recent call last):/
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_webagg.py", line 27, in <module>
    import tornado
ModuleNotFoundError: No module named 'tornado'
```
And indeed /usr/lib64/python3.8/site-packages/matplotlib/backends/backend_nbagg.py uses `ipykernel` and  /usr/lib64/python3.8/site-packages/matplotlib/backends/backend_webagg.py needs `tornado`.
I know that those dependencies are listed in requirements/doc/doc-requirements.txt however those are dependencies for building documentation.

Issue is that those files are part of the installed code and I've checked autogenerated  by rpm install-time dependencies as:
```console
python3.8dist(cycler) >= 0.10
python3.8dist(fonttools) >= 4.22
python3.8dist(kiwisolver) >= 1.0.1
python3.8dist(numpy) >= 1.17
python3.8dist(packaging) >= 20
python3.8dist(pillow) >= 6.2
python3.8dist(pyparsing) >= 2.2.1
python3.8dist(python-dateutil) >= 2.7
```
I have no full knowledge about what is the role of those files so without that kind of knoiwledge it is possible to say that there are two sulution:
- add those two modules to install-time dependencies (ands check maybe there are more such bits)
- remove those files from install list as part of the code which should be used only on `matplotlib` build-time.

### Code for reproduction

```python
N/A
```

### Actual outcome

N/A

### Expected outcome

All modles whci are actuallu used by installed code should be listed in install time dependencies.

### Additional information

N/A

### Operating system

Linux/x86_64

### Matplotlib Version

3.5.1

### Matplotlib Backend

N/A

### Python version

3.8.13

### Jupyter version

N/A

### Installation

git checkout

**Comment by tacaswell** [comment] 2022-04-23 20:16
We do not consider the documentation build dependencies to be install time dependencies.  I understand that you @kloczek want to build the documentation as part of installing the Matplotlib, however we make a distinction between building/installing the library and the documentation. 

The documentation requirements are documented at https://matplotlib.org/stable/devel/dependencies.html#additional-dependencies-for-building-documentation and is available in a machine-readable form at https://github.com/matplotlib/matplotlib/blob/main/requirements/doc/doc-requirements.txt (which we use on our CI to verify the docs build cleanly https://github.com/matplotlib/matplotlib/blob/e0773948af38c8c5123fda0d90cf40140d8b020c/.circleci/config.yml#L90-L101).

Getting the man-page version of the docs to build is not something that to my knowledge has ever worked and we do not consider it a bug that it does not build.  That said, I think we would be happy to review and merge a PR with an enhancement to the documentation build process to also cleanly build the man-pages version.

I am going to close this because the documentation requirements are clearly documented.

**Closed by tacaswell** 2022-04-23 20:16 UTC

**Comment by kloczek** [comment] 2022-04-24 04:04
> I understand that you @kloczek want to build the documentation as part of installing the Matplotlib, however we make a distinction between building/installing the library and the documentation.

No. no .. I'm only pointing on fact that dome files **installed** are using modules which are not listed in `matplotlib` install-time dependencies.
Fact that I found that on building documetation is only coincidence and has nothing to do with those dependencies.

**Comment by oscargus** [comment] 2022-04-24 13:26
The thing is that those dependencies are like the QT backend requiring QT-libraries. We do not require all dependencies for all backends to be installed, only the ones you will use.

Nbagg is the backend for Jupyter (which is based on IPython). Webagg is the browser-based backend and tornado is the webserver used.

**Comment by kloczek** [comment] 2022-04-24 14:03
> The thing is that those dependencies are like the QT backend requiring QT-libraries. We do not require all dependencies for all backends to be installed, only the ones you will use.

Issue is that QT it is not python module. Please .. I'm taking about pure python code dependencies, and dependencies between pythom modules only.
Issue is that in case of using those .py files which have undeclared in python module dependencies list whoever will be tying to use that code will be surprised that module have no of those modules dependencies.
I've not been looking on the actual code, and I'm just forming humble question: it is intentional or maybe it is sometbing which could be fixed by rewrite that code and drop those dependencies because (I don't kniw) maybe someone just by mistake lost from radar what those files are doing. 🤔 

Just please asses that situation and please make some decision ..

I'm only pointing on those not listed explicit dependencies, and I'm not trying to suggest any solution because I have no enough knowledge what is implemented in twse files. Only this and nothing more.
I can understand that this issue maybe is not urgent however if it is still something which can be done just please keep opened that ticket to not loose that from ToDo list 😄

**Comment by anntzer** [comment] 2022-04-24 14:38
The fact that ipython/ipykernel are not dependencies is **intentional** and not a bug: it is absolutely intended that matplotlib can be installed without also installing ipython/ipykernel; this will not change.  It is also intended that in that case (of an install without ipython/ipykernel), importing backend_nbagg will result in a ModuleNotFoundError.  Therefore there is no todo here.

As a general point, _please_ understand that the packaging-related choices of Matplotlib have been well thought-out over many years and by many contributors, and that even though bugs are always possible, _usually_ there's a reason for why things are the way they are.

**Comment by tacaswell** [comment] 2022-04-25 01:25
> Issue is that QT it is not python module. Please .. I'm taking about pure python code dependencies, and dependencies between pythom modules only.

we access Qt via PyQt and making a distinction between "pure" Python and Python + extensions is not a sustainable path.

> Issue is that in case of using those .py files which have undeclared in python module dependencies list 

This is the reason that debian (and conda) actually produce multiple packages from the Matplotilb source.  If you want to pull library apart and package sub-sections so you can never install with a missing dependency that is a down-stream packaging choice.

We have the optional dependencies documented at https://matplotlib.org/stable/devel/dependencies.html#optional-dependencies and we are indeed missing ipykernel for nbagg, I'll open a PR to fix this.
