### ISSUE TITLE
Pillow 7.0.0 Support

### ISSUE THREAD

**Issue by marty-sullivan** [matplotlib/matplotlib#16083] opened 2020-01-03 16:51 UTC
### Bug report

Pillow 7.0.0 is unsupported by pyplot.savefig when saving as jpeg.

**Code for reproduction**

With Pillow 7.0.0 installed:

```python
import matplotlib.pyplot as plt

plt.plot(range(10))
plt.savefig('testplot.jpg')
```
The outcome is an exception is thrown, as follows:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2021, in print_figure
    canvas = self._get_output_canvas(format)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1961, in _get_output_canvas
    raise ValueError(
ValueError: Format 'jpg' is not supported (supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz)
```

The expected outcome is that savefig saves a jpeg image without an exception. This works fine with Pillow 6.2.2 and lower.

**Matplotlib version**

  * Operating system: Linux
  * Matplotlib version: 3.1.2
  * Python version: 3.8.1

**Comment by WeatherGod** [comment] 2020-01-03 16:59
Can you try saving a jpeg with your installation of pillow? I suspect that
the new release of Pillow that came out yesterday might not be packaged
with the jpeg support, and matplotlib is properly detecting the lack of
that support.

**Comment by marty-sullivan** [comment] 2020-01-03 17:06
I ran a quick test, it seems like pillow 7.0.0 is reading/writing jpeg images fine.

```
Python 3.8.1 (default, Dec 28 2019, 05:40:54) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> im = Image.open('test.jpg')
>>> im
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=10848x9298 at 0x7F5B59177100>
>>> im.save('test-save.jpg')
>>> 
```

**Comment by timhoffm** [comment] 2020-01-03 21:10
This is also failing the CI on 3.2.x (see e.g. https://github.com/matplotlib/matplotlib/pull/16084/checks?check_run_id=372887957).

**Comment by tacaswell** [comment] 2020-01-04 01:18
The issue is that 

```
from PIL import PILLOW_VERSION
```

fails with pillow 7, the change is documented here: https://pillow.readthedocs.io/en/stable/releasenotes/7.0.0.html#pillow-version-constant .  It was originally done in pillow 5.2 (https://pillow.readthedocs.io/en/stable/releasenotes/5.2.0.html#deprecations) but we apparently missed the memo :/

If that import fails, we conclude that pillow is not installed and don't put the jpeg generating methods on the Agg canvas class.

**Comment by tacaswell** [comment] 2020-01-04 01:23
This won't be a problem on the mastre branch as we now have a hard dependancy on pillow, but will be a problem on 3.2.x, 3.1.x, and 2.2.x

**Comment by anntzer** [comment] 2020-01-04 09:54
Closed by #16086.

**Closed by anntzer** 2020-01-04 09:54 UTC

**Comment by hugovk** [comment] 2020-01-04 09:59
Are backports to v3.1.x and v2.2.x needed?

**Comment by timhoffm** [comment] 2020-01-04 15:07
Backport to v3.1.x is running (#16091). v2.2.x does not have this version check and thus does not need the backport.
