### ISSUE TITLE
move vertices in widgets.PolygonSelector doesn't work as intended

### ISSUE THREAD

**Issue by 5cout** [matplotlib/matplotlib#18359] opened 2020-08-26 14:56 UTC
### Bug report

**Bug summary**

The Demo for the PolygonSelector tool suggests, that one can move single vertices by holding crtl and dragging a vertex around. However this doesn't work for me.

**Long Description**
When running [this Demo](https://matplotlib.org/3.3.1/gallery/widgets/polygon_selector_demo.html), some lines at the end suggest how interacting with the verices should work.

```python
print("Select points in the figure by enclosing them within a polygon.")
print("Press the 'esc' key to start a new polygon.")
print("Try holding the 'shift' key to move all of the vertices.")
print("Try holding the 'ctrl' key to move a single vertex.")
```
The shift command works just fine. Also, if I close the polygon and do a normal left click on one of the lines, I create another vertex (I suppose this is how it is intended to work).
However, clicking a second time on any line will do nothing. Instead, clicking on an existing vertex and dragging it will move the vertex. At the same time, pressing crtl will deny any interaction with the polygon. I assume this is a bug in the polygon selector tool.

**Side Note regarding the demo**

I had to remove 
```python
selector.disconnect()
```
to get the demo running. I also assume this is a mistake, as I can't see the reason why the tool should be disconnected before it gets to interact.
Edit: made the text more readable.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.3.1 - via conda
  * Matplotlib backend: Qt5 (spyder)
  * Python version: 3.8
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by QuLogic** [comment] 2020-08-27 04:14
All of these work for me; some words appear to be missing from your description which makes it a bit confusing.

> The Demo for the PolygonSelector tool suggests, that one can single vertices by holding and dragging a vertex around. However this doesn't work for me.

One can do what to single vertices?

> Also, if I close the polygon and do a normal left click on one of the lines, I create another vertex (I suppose this is how it is intended to work).

This does not happen for me.



> Instead, clicking on an existing vertex and dragging it will move the vertex.

I can confirm this.

> At the same time, pressing will deny any interaction with the polygon.

Pressing what?



> I had to remove
> 
> ```python
> selector.disconnect()
> ```

This occurs after `plt.show`, which means the figure would be closed already.



>     * Matplotlib backend: Qt5 (spyder)

Are you sure you are using Qt5, or are you using Spyder's backend? What does `matplotlib.get_backend()` actually return?

**Comment by 5cout** [comment] 2020-08-27 07:16
I do appologize, as this is my first issue report. I tried to indicate keyboard presses as `<ctrl>` and didn't realise that would make it disappear.
As for your questions: `matplotlib.get_backend()` returns Qt5Agg. At the same time, 
I couldn't recreate the creation of new vertices by normal clicking. Instead normal clicking or pressing crtl will both move single vertices around when clicking on them. I am not sure whether this is the intended way it is supposed to work (imo adding vertices when the polygon is closed already is a nice thing), but for now it seems like we are getting the same result.

> 
This occurs after plt.show, which means the figure would be closed already.
> 
I would also assume that this should not be a problem, but inserting 
```python
selector.disconnect()
```
will close stop the selectortool before I can use it. This might be because I'm using IPython (?)

**Comment by 5cout** [comment] 2020-08-27 07:43
The LassoSelector [demo](https://matplotlib.org/3.1.0/gallery/widgets/lasso_selector_demo_sgskip.html) does things a bit differently:
```Python
    def accept(event):
        if event.key == "enter":
            print("Selected points:")
            print(selector.xys[selector.ind])
            selector.disconnect()
            ax.set_title("")
            fig.canvas.draw()

    fig.canvas.mpl_connect("key_press_event", accept)
```

**Comment by QuLogic** [comment] 2020-08-27 21:28
> I do appologize, as this is my first issue report. I tried to indicate keyboard presses as `<ctrl>` and didn't realise that would make it disappear.

Sorry, I should have recognized that.

> This might be because I'm using IPython (?)

Ah, this could be the case. Are you using `%run`? The example is meant to be run standalone, which is why the `disconnect` happens after `show`. In IPython, the figure runs in the background and the `show` returns immediately.

**Comment by QuLogic** [comment] 2020-08-27 21:31
No, actually, I can't reproduce using `%run`. Are copying and pasting into IPython? Please read about [interactive mode](https://matplotlib.org/users/interactive.html).

**Comment by 5cout** [comment] 2020-08-28 10:57
No, I run the code from the .py file in Python. Its just that the console is IPython

**Comment by 5cout** [comment] 2020-09-01 12:57
As the lasso selector works seemingly as intended, should I convert this issue to a feature request requesting what I have mentioned before?
> (imo adding vertices when the polygon is closed already is a nice thing),

**Comment by timhoffm** [comment] 2020-09-07 21:03
I'm closing this ticket because the selector works as expected. You are welcome to open a feature request for additional functionality, but it's better to write that up cleanly in a new ticket.

Note however that widgets are currently not a high priority in the project and I doubt core devs will pick the topic up unless somebody comes up with a pull request.

**Closed by timhoffm** 2020-09-07 21:03 UTC
Labels: widgets/UI
