### ISSUE TITLE
Include tests.py in archive of release

### ISSUE THREAD

**Issue by FRidh** [matplotlib/matplotlib#6017] opened 2016-02-17 19:47 UTC
It seems matplotlib tests need to be run with `python tests.py`. Unfortunately, `tests.py` is not included in releases. Please add this file, since it makes it easier for maintainers to check whether their package works. Thanks!

**Comment by tacaswell** [comment] 2016-02-18 03:48
Duplicate of https://github.com/matplotlib/matplotlib/issues/5831 which was closed in https://github.com/matplotlib/matplotlib/pull/5840 which was against 1.5.x so the next release off any branch will include this.

What are you packaging mpl for (given that you have hit both here an cycler in the last few days)?

**Closed by tacaswell** 2016-02-18 03:48 UTC

**Comment by FRidh** [comment] 2016-02-18 07:04
Oops, I should remember to search in the closed issues as well :-)

I'm packaging a bunch of (Python) packages for Nix/NixOS. We basically have a function to a build a Python package, and by default tests are also automatically run with `python setup.py test`. In case the tests need to be called in a different way we override the default call.

That reminds me. I just accidentally happened to notice that tests had to be run like this. Nowadays, with the newer versions of `setuptools`, we basically always get an error when tests are not found, thereby halting the build. This is great for us, since that way we can be almost entirely sure that all packages are actually being tested in the correct way.

With matplotlib `python setup.py test` shows the message that tests have to be run as `python tests.py` and then exits gracefully. I think it would be better to raise an exception, just as if `python setup.py test` was not implemented, but then of course with this added message.

**Comment by QuLogic** [comment] 2016-02-18 07:21
At the very least, it should probably exit with a non-zero exit code.

**Comment by jenshnielsen** [comment] 2016-02-18 08:52
We did have support for `python setup.py test` but in the end it resulted in a series of new issues so we removed it again. I would be strongly against waisting any more time on that but making it raise an error seems like a good idea.

**Comment by tacaswell** [comment] 2016-02-18 15:15
:+1: to dying less cleanly and :+1: to not spending any more time getting `python setup.py test` to run now.

We might want to re-evaluate the second part if/when the move to `py.test` from nose gets merged.

**Comment by FRidh** [comment] 2017-01-30 17:13
Am I correct that from 2.0 the sdist won't include the tests?

**Comment by tacaswell** [comment] 2017-01-30 17:31
the source dist should include all of the tests and baseline images.

**Comment by FRidh** [comment] 2017-01-30 17:51
Indeed, they are included, though not installed, which is fine. I was just checking how to run the tests now since we get `ImportError: matplotlib test data is not installed`. Can we run the tests with an installed copy, without installing the tests, by referring to the matplotlib source?

**Comment by tacaswell** [comment] 2017-01-30 19:55
Yes, that should be possible.  See http://matplotlib.org/api/api_changes.html#default-install-no-longer-includes-test-images

**Comment by kapsh** [comment] 2018-12-02 09:49
If somebody wants to read last link, it is https://matplotlib.org/2.1.0/api/api_changes.html#default-install-no-longer-includes-test-images to be precise.

**Comment by tacaswell** [comment] 2018-12-02 23:08
Thanks @kapsh !  I should have used the stable link initially.

**Comment by sameer-dubal** [comment] 2019-02-13 12:39
Hi   , I have installed matplotlib 2.2.3, and i have enabled the flag " local_freetype=True"  in setup.cfg.template . But still i am getting the error . Please check below for the error. 

=====

Python 3.7.1 (default, Feb  6 2019, 03:49:16)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib as mat
>>> mat.test("full")
/usr/local/lib/python3.7/site-packages/matplotlib/__init__.py:1472: UserWarning: Matplotlib is not built with the correct FreeType version to run tests.  Set local_freetype=True in setup.cfg and rebuild. Expect many image comparison failures below. Expected freetype version 2.6.1. Found freetype version 2.6.1. Freetype build type is not local
  "" if ft2font.__freetype_build_type__ == 'local' else "not "
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/matplotlib/__init__.py", line 1488, in test
    raise ImportError("Matplotlib test data is not installed")
ImportError: Matplotlib test data is not installed
>>>
root@fcdd10:/home/sameer#

======
I will really appreciate if someone can provide help to resolve the above issue. 

Thanks,
Sameer

**Comment by tacaswell** [comment] 2019-02-13 15:13
@sameer-dubal can you please move this discussion to the user mailing list?
