### ISSUE TITLE
Warnings from test_contour.test_corner_mask

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5363] opened 2015-10-30 17:51 UTC
```
matplotlib.tests.test_contour.test_corner_mask.test ... ok
/matplotlib/colorbar.py:539: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 4
  colors = np.asarray(colors)[igood]
/matplotlib/colorbar.py:539: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3
  colors = np.asarray(colors)[igood]
```

Cc: @efiring: Any thoughts as a colorbar expert?  I think the warning is due to a recent tightening in Numpy, but I'm not sure how to fix it.

**Comment by tacaswell** [comment] 2015-10-30 20:51
Those may be coming out of the contouring code and I thought that @ianthomas23 fixed that.

Bit worried we may have had a bad bug-fix branch merge at somepoint that blew that away.

**Comment by WeatherGod** [comment] 2015-10-30 21:04
This has not been fixed. The problem that was fixed was the one in the
triangulation code. I *think* this is duplication or related to #4998

**Comment by ianthomas23** [comment] 2015-10-30 21:17
I confirm that I fixed a different, but similar, problem related to numpy
tightening in the TriAnalyzer code, issue #4999, PRs #5065 and #5070.  The
fix was simple, just increase the size of the boolean array to match that
of the array it is indexing.

**Comment by QuLogic** [comment] 2016-12-22 22:37
I think this is a duplicate of #7334, and although this one is older, that one has the new name of the test and it's got some comments from @pelson who wrote the tests originally, so I'm going to close this one.

**Closed by QuLogic** 2016-12-22 22:37 UTC
