### ISSUE TITLE
[Bug]: Can not close figure when using multiple figures on MacOS X

### ISSUE THREAD

**Issue by FengChendian** [matplotlib/matplotlib#28387] opened 2024-06-13 04:18 UTC
### Bug summary

I can not close figure when use multiple figures. 

I use
- macOS 14.5 (23F79).
- Apple M1 Pro

 

### Code for reproduction

```Python
import matplotlib.pyplot as plt

import numpy as np

a = np.arange(10)
y = np.sin(a)

plt.figure()
plt.plot(a, y)
plt.figure()
plt.plot(a, y)
plt.show()
```

### Actual outcome

https://github.com/matplotlib/matplotlib/assets/37545115/86c03ed7-ed48-4af1-b918-ba132edb4c3b

### Expected outcome

I should close these figures immediately.

### Operating system

OS/X

### Matplotlib Version

3.8.4

### Matplotlib Backend

MacOSX

### Python version

3.12.3

### Installation

conda

**Comment by greglucas** [comment] 2024-06-13 13:11
I can reproduce this, but only when using tabbed window mode: `plt.rcParams["macosx.window_mode"] = "tab"`.

It looks like it was introduced by https://github.com/matplotlib/matplotlib/pull/27290 and reverting that commit does fix this issue on main for me. v3.8.1 works as expected, v3.8.2 is where this issue started to occur.
cc @ksunden

**Comment by tacaswell** [comment] 2024-06-13 13:22
Does reverting #27290 also bring back the segfault on py312?

My guess is that we have generated some sort of deadlock on the GIL and probably need to change some of our logic on close on macOS to be "please exit when you can" from "please exit now, I'all wait"

**Comment by greglucas** [comment] 2024-06-13 13:42
> Does reverting https://github.com/matplotlib/matplotlib/pull/27290 also bring back the segfault on py312?

Yes, it sure does, sorry I shouldn't have implied we _should_ revert it, just that reverting does get us the old desired behavior with tabs.

> My guess is that we have generated some sort of deadlock on the GIL and probably need to change some of our logic on close on macOS to be "please exit when you can" from "please exit now, I'all wait"

I agree with this assumption of needing to update our logic.

**Comment by ksunden** [comment] 2024-06-14 18:01
Hmmm... interestingly, you can actually pull the tabs apart into separate windows, and then they close perfectly fine... 

I wonder if the deadlock is caused by dispatching the close signal to two tabs at once...

I will note that it also freezes on hitting an individual tab close button, not just the red window close button.

A few quick print debugging steps do in fact confirm that we are hanging at `PyGILState_Ensure` in `_buffer_release`. Though wonder if tracing back farther will be productive.

Further, during normal separated window closing, `_buffer_release` is _not_ called at all, so not sure why it is called when tabbed, perhaps it is closing one, triggering a draw on the other, even if they are closing?

**Closed** 2024-06-26 19:24 UTC
Labels: GUI: MacOSX
