### ISSUE TITLE
OS X libpng incompatability 

### ISSUE THREAD

**Issue by ChristopherShort** [matplotlib/matplotlib#7579] opened 2016-12-07 02:26 UTC
matplotlib v2.0.0rc1, Python 3.5,   OSX

upgraded via conda over standard anaconda installation

`%matplotlib notebook`

fails with an error message:

`Incompatible library version: _png.cpython-35m-darwin.so requires version 43.0.0 or later, but libpng16.16.dylib provides version 39.0.0`

Resolved via: `conda upgrade libpng`  

Stackoverflow suggests its an occasional issue - the last answer [here](http://stackoverflow.com/questions/28124359/error-with-homebrew-opencv-libpng) links it to anaconda 

May or may not be a matplotlib installer concern

**Comment by QuLogic** [comment] 2016-12-07 03:06
I'm guessing this is more of a `conda`/`conda-forge` issue in that Matplotlib doesn't really require a specific version of libpng, but it just happens to be built with a newer version and conda's package format doesn't really record/utilize that information. I don't know if we can even force it to build against an older version, but that's something to ask on https://github.com/conda-forge/matplotlib-feedstock or the main conda-forge page.

I'm going to close this because I don't think it's strictly a Matplotlib problem, but feel free to re-open if you feel otherwise.

**Closed by QuLogic** 2016-12-07 03:06 UTC

**Comment by tacaswell** [comment] 2016-12-07 16:38
Duplicate of #7576

**Comment by ChristopherShort** [comment] 2016-12-08 00:59
Perhaps add a note to the  [OS X/Anaconda install instructions](http://matplotlib.org/users/installing.html) that it may require libpng upgrade via `conda upgrade libpng`.

This issue stumped me several times this year when wanting to test the beta versions and I wasn't able to figure out/find a solution.  I got lucky yesterday on that.

The advice of [#7576](https://github.com/matplotlib/matplotlib/issues/7576) to `conda update --all` isn't optimal as the user may end up with dependency conflicts across various libraries.

I'm happy to have a go at that at that small amendment - though it will have to wait a few days.

**Comment by tacaswell** [comment] 2016-12-08 02:48
@ChristopherShort Please do!
