### ISSUE TITLE
AttributeError: module 'matplotlib.cbook' has no attribute '_classproperty' 

### ISSUE THREAD

**Issue by MarvelGuo** [matplotlib/matplotlib#17128] opened 2020-04-14 00:29 UTC
Yesterday I upgraded matplotlib to 3.2.1. Today when I tried to import matplotlib.pyplot, I just get this error and failed to import. Is this something wrong due to the upgrade?

```python
# AttributeError: module 'matplotlib.cbook' has no attribute '_classproperty'
```

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.7
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by QuLogic** [comment] 2020-04-14 00:38
Maybe you have an old `cbook.py` lying around, but this is definitely caused by some crossed installation.

**Comment by MarvelGuo** [comment] 2020-04-14 00:40
What do you mean by crossed installation?

**Comment by QuLogic** [comment] 2020-04-14 00:50
You still have files from the old version somewhere.

**Comment by MarvelGuo** [comment] 2020-04-14 01:52
So is there any potential solution to this? There is hardly anything I could do for my work with matplotlib not working.

**Comment by QuLogic** [comment] 2020-04-14 23:48
Yes, you need to delete the old files. I cannot say much more than that as there are no details here.

Since this is not a bug, I'm going to close this report. If you are still having issues with your installation, please continue on our discourse at https://discourse.matplotlib.org

**Closed by QuLogic** 2020-04-14 23:48 UTC
Labels: Community support

**Comment by kernelizd** [comment] 2020-06-15 02:35
@QuLogic  was correct. I went to `C:\user\AppData\Roaming\Python\Python37\site-packages`

and deleted matplotlib and it worked!
