### ISSUE TITLE
PS export issue with custom font

### ISSUE THREAD

**Issue by klonuo** [matplotlib/matplotlib#6525] opened 2016-06-01 19:36 UTC
Hi,

in my matplotlibrc I've set `font.sans-serif: Calibri`.

When I export figure to PS/EPS I cant open the file. Problem seems to be in `%%Copyright` comment in exported file, which is split on two lines.:

```postscript
...
%!PS-Adobe-3.0 Resource-Font
%%Title: Calibri
%%Copyright: © 2016 Microsoft Corporation. All Rights Reserved.
Hebrew OpenType Layout logic copyright © 2003 & 2007, Ralph Hancock & John Hudson. This layout logic for Biblical Hebrew is open source software under the MIT License; see embedded license description for details.
%%Creator: Converted from TrueType to type 3 by PPR
...
```

So if I join the lines to:

```postscript
...
%!PS-Adobe-3.0 Resource-Font
%%Title: Calibri
%%Copyright: © 2016 Microsoft Corporation. All Rights Reserved. Hebrew OpenType Layout logic copyright © 2003 & 2007, Ralph Hancock & John Hudson. This layout logic for Biblical Hebrew is open source software under the MIT License; see embedded license description for details.
%%Creator: Converted from TrueType to type 3 by PPR
...
```

file is properly decoded.

_matplotlib-2.0.0b1 on 64-bit Python 3.5.1 on Windows 10_

**Comment by QuLogic** [comment] 2016-06-01 20:44
This is a dupe of #5862, but with a different font.

**Closed by QuLogic** 2016-06-01 20:44 UTC
