### ISSUE TITLE
Easy fix for clipping misrendering of matplotlib's SVG in other viewers

### ISSUE THREAD

**Issue by marklundeberg** [matplotlib/matplotlib#2277] opened 2013-08-04 06:56 UTC
I've been noticing lately that matplotlib's SVG output appears with incorrect clipping in a lot of SVG viewers (rsvg-view, Ristretto, gpicview), even though it does appear correctly in good SVG viewers like inkscape, firefox, chrome. The data curves peek outside of the axes. Luckily there is an fix in matplotlib that should be easy enough to implement:

Currently, the SVG structure looks more or less like this, with the clipPath defined at the end:
```xml
<svg ..>
 <g id="figure_1">
  <g id="axes_1">
  .... curves drawn in here, referencing clip-path p7ff5b81e1d
  </g>
 </g>
 <defs>
  <clipPath id="p7ff5b81e1d">
   <rect height="345.6" width="446.4" x="72.0" y="43.2"/>
  </clipPath>
 </defs>
</svg>
```

I found that if I simply moved the <defs> section containing that clipPath earlier in the file, then the SVG views just fine in any viewer that I can find. I guess that these basic SVG viewers don't like forward references.

For examples, this works:
```xml
<svg ..>
 <g id="figure_1">
 <defs>
  <clipPath id="p7ff5b81e1d">
   <rect height="345.6" width="446.4" x="72.0" y="43.2"/>
  </clipPath>
 </defs>
  <g id="axes_1">
  .... curves drawn in here, referencing clip-path p7ff5b81e1d
  </g>
 </g>
</svg>
```

I would attach an example SVG but github doesn't seem to support that...

**Comment by tacaswell** [comment] 2015-04-28 03:25
Duplicate of https://github.com/matplotlib/matplotlib/issues/4341, closing in favor of that one.

**Closed by tacaswell** 2015-04-28 03:25 UTC
Labels: backend/svg, Duplicate, upstream fix required
