### ISSUE TITLE
[Bug]: Pyparsing warnings emitted in mathtext

### ISSUE THREAD

**Issue by jmd-dk** [matplotlib/matplotlib#25204] opened 2023-02-12 16:19 UTC
### Bug summary

When plotting anything with at least one logarithmic axes (`plt.semilogx()`, `plt.semilogy()`, `plt.loglog()`) I get two warnings emitted due to code in `_mathtext.py`. These warnings are not emitted by default, but appears when running Python with e.g. [`-Wdefault`](https://docs.python.org/3/using/cmdline.html#cmdoption-W).

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.semilogx([1, 2], [3, 4])
plt.savefig('plot.png')
```

### Actual outcome

```
/path/to/python/lib/python3.9/site-packages/matplotlib/_mathtext.py:1871: UserWarning: warn_name_set_on_empty_Forward: setting results name 'sym' on Forward expression that has no contained expression
  - p.placeable("sym"))
/path/to/python/lib/python3.9/site-packages/matplotlib/_mathtext.py:1876: UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'name' on ZeroOrMore expression collides with 'name' on contained expression
  "{" + ZeroOrMore(p.simple | p.unknown_symbol)("name") + "}")
```

### Expected outcome

No warnings/text should be printed.

### Additional information

To see the warnings from the above code, save it to e.g. `test.py` and run it as either
```bash
python -Wdefault test.py
```
or
```
PYTHONWARNINGS=default python test.py
```

The two warnings are triggered by the following lines within `matplotlib/_mathtext.py`:
```python3
        p.accent <<= (
            csnames("accent", [*self._accent_map, *self._wide_accents])
            - p.placeable("sym")
```

```python3
        p.operatorname <<= cmd(
            r"\operatorname",
            "{" + ZeroOrMore(p.simple | p.unknown_symbol)("name") + "}")
```
where the various attributes on `p` are instances of `pyparsing.Forward`.

The warnings appear with Pyparsing versions 3.0.0–3.0.9 but not prior to 3.0.0 (e.g. 2.4.7). Also, the warnings only appear for Matplotlib versions 3.6.0–3.6.3, not e.g. 3.5.3

### Operating system

Linux Mint 20

### Matplotlib Version

3.6.3

### Matplotlib Backend

QtAgg

### Python version

3.8.5

### Installation

pip

**Comment by rcomer** [comment] 2023-02-12 17:18
Thanks for the report @jmd-dk.  It looks like the second warning at least was addressed for v3.7 by #24989.  But actually I didn't reproduce those warnings on my machine (Ubuntu 22.04) with matplotlib v3.6.3, pyparsing 3.0.9 and python 3.8.16.  I install with Conda rather than pip.

Are you able to test with the v3.7 release candidate?  If not, v3.7 itself should be out very soon.

**Comment by rcomer** [comment] 2023-02-12 17:22
Thanks for the clear report @jmd-dk.  After a couple of false starts (!) I have reproduced this with `main`:

```
/home/ruth/git_stuff/matplotlib/lib/matplotlib/_mathtext.py:1880: UserWarning: warn_name_set_on_empty_Forward: setting results name 'sym' on Forward expression that has no contained expression
  - p.placeable("sym"))
/home/ruth/git_stuff/matplotlib/lib/matplotlib/_mathtext.py:1885: UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'name' on ZeroOrMore expression collides with 'name' on contained expression
  "{" + ZeroOrMore(p.simple | p.unknown_symbol)("name") + "}")

```

**Comment by anntzer** [comment] 2023-02-12 19:41
The second warning is fixed by #25200.

**Comment by anntzer** [comment] 2023-02-12 20:33
The other warning can be suppressed with
```patch
diff --git i/lib/matplotlib/_mathtext.py w/lib/matplotlib/_mathtext.py
index b41dca9d69..71af0dfdea 100644
--- i/lib/matplotlib/_mathtext.py
+++ w/lib/matplotlib/_mathtext.py
@@ -13,6 +13,7 @@ import types
 import unicodedata

 import numpy as np
+import pyparsing
 from pyparsing import (
     Empty, Forward, Literal, NotAny, oneOf, OneOrMore, Optional,
     ParseBaseException, ParseException, ParseExpression, ParseFatalException,
@@ -1875,9 +1876,11 @@ class Parser:

         p.customspace <<= cmd(r"\hspace", "{" + p.float_literal("space") + "}")

-        p.accent <<= (
-            csnames("accent", [*self._accent_map, *self._wide_accents])
-            - p.placeable("sym"))
+        with cbook._setattr_cm(
+                pyparsing.__diag__, warn_name_set_on_empty_Forward=False):
+            p.accent <<= (
+                csnames("accent", [*self._accent_map, *self._wide_accents])
+                - p.placeable("sym"))

         p.function <<= csnames("name", self._function_names)
         p.operatorname <<= cmd(
```
but it's not really clear to me whether it's actually warning about a problematic practice or not (one could move the definition of placeable above the one of accent to suppress the warning, but that actually changes the parsing behavior.

**Comment by slayoo** [comment] 2024-01-22 14:12
just came across the very same problem which made our CI pipeline "red" (as run with `python -We`) after a matplotlib update - would be great address this issue!
Thanks

**Closed** 2024-03-13 21:02 UTC
Labels: status: confirmed bug, topic: text/mathtext
