### ISSUE TITLE
pdf-backend for savefig produces unusual grouping within pdf element

### ISSUE THREAD

**Issue by normanius** [matplotlib/matplotlib#15051] opened 2019-08-13 15:11 UTC
### Bug report

**Bug summary**

When saving the figure as a PDF, the items are grouped unusually, which leads to unexpected results when shown in a viewer that supports [knockout effects](https://www.makeuseof.com/tag/create-knockout-effect-photoshop-illustrator/). 
While this is not problematic most of the time, the issue causes troubles if the PDF created by matplotlib is edited within Illustrator (possibly other PDF editors as well).

**Code for reproduction**

```python
import matplotlib.pyplot as plt
x = [42,43,44]
y=[42,43,44]
plt.scatter(x,y,alpha=0.7,sizes=[500], linewidths=[5])
plt.savefig('sample.pdf')
```

**Actual outcome**
Because I initially thought this is an Illustrator related problem, I posted a [(very detailed) description in one of the Adobe Forums](https://forums.adobe.com/thread/2644593). 

In (MacOS) Preview.app
![image](https://user-images.githubusercontent.com/11406002/62951802-e85e4580-bdea-11e9-8cce-333205149cd6.png)

In Adobe Illustrator:
![image](https://user-images.githubusercontent.com/11406002/62951867-062baa80-bdeb-11e9-987b-bf1853329bcb.png)

In the Adobe Illustrator forum I got the feedback that the grouping of the items is unusual and causes the confusion. Indeed, [ungrouping the elements](https://forums.adobe.com/message/11206013#11206013) resolved all of my problems.

**Expected outcome**
Same as in default preview app.

**Matplotlib version**
  * MacOS 10.14.5
  * Matplotlib v3.1.1
  * Matplotlib backend: MacOSX
  * Python 3.6.7

**Comment by anntzer** [comment] 2019-08-13 16:29
I can repro this issue with mupdf/ghostscript, but not with poppler (okular).  Not sure whether it's the readers not following the spec, or not.
fwiw https://github.com/matplotlib/mplcairo generates pdfs without this issue.

**Comment by jkseppan** [comment] 2020-07-28 08:12
Since ungrouping in Adobe Illustrator solves the problem, could you share 

(1) a small problematic file from matplotlib;
(2) the same file after ungrouping in Illustrator and saving as PDF?

**Comment by normanius** [comment] 2020-07-28 12:39
Here you are. Since Illustrator supports different [versions of PDF](https://en.wikipedia.org/wiki/PDF), I've picked the newest and oldest available version (1.3 and 1.7).

I used the above sample code to create the PDF (sample-original.pdf). The only action performed in Illustrator was to ungroup the items (Cmd+Shift+G), followed by "Save as".

[sample-original.pdf](https://github.com/matplotlib/matplotlib/files/4988263/sample-original.pdf)
[sample-ungrouped-pdf1.3.pdf](https://github.com/matplotlib/matplotlib/files/4988264/sample-ungrouped-pdf1.3.pdf)
[sample-ungrouped-pdf1.7.pdf](https://github.com/matplotlib/matplotlib/files/4988265/sample-ungrouped-pdf1.7.pdf)

**Comment by QuLogic** [comment] 2020-07-28 22:51
I don't think we set knockout groups; I think this is an implicit behaviour in PDF:
![Screenshot from 2020-07-28 18-50-59](https://user-images.githubusercontent.com/302469/88730097-520e5700-d103-11ea-9db5-485bffd5fe73.png)
![Screenshot from 2020-07-28 18-51-25](https://user-images.githubusercontent.com/302469/88730119-5dfa1900-d103-11ea-9368-308895c4b609.png)

**Comment by QuLogic** [comment] 2020-07-28 23:38
So I think that makes this a duplicate of #10035.

**Closed by QuLogic** 2020-07-28 23:38 UTC
Labels: backend/pdf
