### ISSUE TITLE
plt.plot does not plot anything with named arguments

### ISSUE THREAD

**Issue by taxus13** [matplotlib/matplotlib#12106] opened 2018-09-13 06:57 UTC
### Bug report

**Bug summary**

When using named arguments for x and y, the plots created with plt.plot respectively ax.plot are keeping empty. plt.errorbar (or ax.errorbar) are producing the desired output (see code below).
The [documentation](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.plot.html#matplotlib.axes.Axes.plot) shows that x and y are valid named arguments. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(0, 12, .5)
y = np.random.rand(*x.shape)
plt.plot(x, y) #  works as expected
plt.plot(x=x, y=y) # shows empty plot
plt.errorbar(x=x, y=y) # works as expected
```

**Actual outcome**
![empty-diagram](https://user-images.githubusercontent.com/6933947/45471598-ddf68000-b731-11e8-92ed-b9d7591dd194.PNG)

**Expected outcome**
![desired-diagram](https://user-images.githubusercontent.com/6933947/45471603-e18a0700-b731-11e8-9855-8e5ebb56b925.PNG)
or
![desired-diagram2](https://user-images.githubusercontent.com/6933947/45471642-041c2000-b732-11e8-8649-79b8c8c54482.PNG)

**Matplotlib version**

  * Operating system: Windows 10x64
  * Matplotlib version: 2.2.3 (had the same issue with 2.2.2)
  * Matplotlib backend (`print(matplotlib.get_backend())`): 'module://ipykernel.pylab.backend_inline'
  * Python version: 3.6.2
  * Jupyter version (if applicable): 1.0.0  (Jupyter notebook 5.1.0rrc1)
  * Other libraries: numpy 1.14.5+mkl

Python was installed using WinPython, packages installed with pip.

**Comment by anntzer** [comment] 2018-09-13 15:01
I am not particularly sure that we want to support passing x and y as kwargs, see recent discussion on a similar topic at https://github.com/matplotlib/matplotlib/issues/11526.
(But if we decide we indeed don't, then we should make the documentation clear and error out when they *are* passed in as kwargs.)

**Comment by anntzer** [comment] 2018-09-13 19:17
fwiw I'm also against fully kw-only mode (also as discussed in the linked thread).

**Comment by jklymak** [comment] 2018-09-13 19:44
I think that `plt.errorbar(x=x, y=y)` works is more accidental than anything.

**Comment by anntzer** [comment] 2018-09-13 19:45
Well, errorbar doesn't have a completely ~stupid~ weird signature...

**Comment by jklymak** [comment] 2018-09-13 19:54
I guess it is a bit weird that this just doesn't plot anything, rather than give some sort of error.

**Comment by anntzer** [comment] 2018-09-13 20:54
I agree it should error out.

**Comment by rudrathegreat** [comment] 2018-11-08 09:16
If you are using a subplots, then you might want to consider the following - 

```Python

''' The Figure in this case is 'fig' and
inside 'fig' is the subplot 'ax'. '''

fig, ax = plt.subplots(figsize=(12, 6))

# Plot the data

ax.plot([1, 2, 3], [1, 2, 3])
plt.show()

```

I hope that helped!

**Comment by anntzer** [comment] 2019-01-03 17:37
Actually a duplicate of https://github.com/matplotlib/matplotlib/issues/4059.

**Closed by anntzer** 2019-01-03 17:37 UTC
Labels: Argument Checking
