### ISSUE TITLE
axes3D.zaxis.set_major_formatter(mpl.dates.DateFormatter("%Y/%m")) couldn't show datetime axis correctly.

### ISSUE THREAD

**Issue by xiangwangdr** [matplotlib/matplotlib#8762] opened 2017-06-14 12:42 UTC
### Bug report

**Bug summary**

axes3D.zaxis.set_major_formatter(mpl.dates.DateFormatter("%Y/%m")) couldn't show datetime axis correctly. It report ValueError: year is out of range.

**Code for reproduction**

```python
import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime
import time

mpl.rcParams['legend.fontsize'] = 10

fig = plt.figure()
ax = fig.gca(projection='3d')

SJ = pd.to_datetime(['2017/1/1 0:03:36','2017/1/1 0:33:36','2017/1/1 1:03:36'])

for i in np.arange(0, 3, 1):
  x=[ii for ii in np.arange(0,20,1)]
  y=[np.sin(ii) for ii in np.arange(0,20,1)]
  z= SJ[i].timestamp()
  print(str(z)+':'+str(datetime.fromtimestamp(z)))
  # print(datetime.fromordinal(int(z/60/24)))
  ax.plot(x, y, z)

ax.zaxis.set_major_formatter(mpl.dates.DateFormatter("%Y/%m/%d/%H"))
plt.show()
```

**Actual outcome**

```
1483200216.0:2017-01-01 00:03:36
1483202016.0:2017-01-01 00:33:36
1483203816.0:2017-01-01 01:03:36
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\tkinter\__init__.py", line 1550, in __call__
    return self.func(*args)
  File "C:\Program Files\Anaconda3\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 280, in resize
    self.show()
  File "C:\Program Files\Anaconda3\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 351, in draw
    FigureCanvasAgg.draw(self)
  File "C:\Program Files\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)
  File "C:\Program Files\Anaconda3\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1144, in draw
    renderer, self, dsu, self.suppressComposite)
  File "C:\Program Files\Anaconda3\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Program Files\Anaconda3\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 290, in draw
    ax.draw(renderer)
  File "C:\Program Files\Anaconda3\lib\site-packages\mpl_toolkits\mplot3d\axis3d.py", line 258, in draw
    for i, val in enumerate(majorLocs)]
  File "C:\Program Files\Anaconda3\lib\site-packages\mpl_toolkits\mplot3d\axis3d.py", line 258, in <listcomp>
    for i, val in enumerate(majorLocs)]
  File "C:\Program Files\Anaconda3\lib\site-packages\matplotlib\dates.py", line 466, in __call__
    dt = num2date(x, self.tz)
  File "C:\Program Files\Anaconda3\lib\site-packages\matplotlib\dates.py", line 401, in num2date
    return _from_ordinalf(x, tz)
  File "C:\Program Files\Anaconda3\lib\site-packages\matplotlib\dates.py", line 254, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
ValueError: year is out of range
[Finished in 4.8s]
```

**Expected outcome**

**Matplotlib version**

  * Operating System: windows 7 x64
  * Matplotlib Version: 2.02
  * Python Version:python 3.5.2 |Anaconda 4.2.0 （64bit）| [MCS v.1900 64 bit <AMD64>] on win32
  * Jupyter Version (if applicable):
  * Other Libraries:

**Comment by WeatherGod** [comment] 2017-06-14 14:28
I tried running this as-is, but I got an error at the "z= SJ[i].timestamp()"
line, saying that the Timestamp object does not have a method called
"timestamp()". I am not familiar enough with pandas to know what it is
supposed to be. Can you make an example without pandas?

**Comment by xiangwangdr** [comment] 2017-06-15 00:43
Kindly please try the new version without pandas.

``` Python
import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import time

mpl.rcParams['legend.fontsize'] = 10

fig = plt.figure()
ax = fig.gca(projection='3d')

SJ = ['2017/1/1 0:03:36','2017/1/1 0:33:36','2017/1/1 1:03:36']

for i in np.arange(0, 3, 1):
  x=[ii for ii in np.arange(0,20,1)]
  y=[np.sin(ii) for ii in np.arange(0,20,1)]
  z= time.mktime(time.strptime(SJ[i], '%Y/%m/%d %H:%M:%S')) # SJ[i].timestamp()
  print(str(z)+':'+str(datetime.fromtimestamp(z)))
  ax.plot(x, y, z)

ax.zaxis.set_major_formatter(mpl.dates.DateFormatter("%Y/%m/%d/%H"))
plt.show() 
```

@WeatherGod

**Comment by TD22057** [comment] 2022-11-03 00:40
FYI - the example in bug #22207 still fails with the same error as was reported there using the latest MPL (3.6.1).

```
import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d
import matplotlib.testing.jpl_units as units
units.register()

x = [i * units.km for i in range(10)]
y = [2 * i * units.km for i in range(10)]
z = [3 * i * units.km for i in range(10)]

fig = plt.figure()
ax = fig.add_subplot(projection="3d")
ax.plot(x, y, z)
plt.show()
```

IMO the code that @xiangwangdr is showing is not using units correctly.  time.mktime() returns a float but supporting units is about supporting datetime (and any other unitized type) on the axes itself.  It requires that the 3d plot code run the unit->numpy conversion methods that the 2d plot functions already call.

ps: I'm posting this here because bug #22207 was marked as a duplicate of this bug even though IMO they're a different report and I don't want the problem reported in #22207 to be lost.

**Comment by jklymak** [comment] 2022-11-03 01:32
Closing in favour of #22207, because unit conversion is the fundamental problem here so that report is more actionable.

**Closed by jklymak** 2022-11-03 01:32 UTC
Labels: topic: mplot3d, topic: date handling, topic: units and array ducktypes
