### ISSUE TITLE
ax.bar doesn't work correctly when width is a timedelta64 object

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#11290] opened 2018-05-22 21:18 UTC
The following example

```python
In [1]: x = np.array(range(100), dtype='M8[D]')

In [2]: ax = plt.subplot(1,1,1)

In [3]: y = np.random.random(100)

In [4]: ax.bar(x, y)
Out[4]: <BarContainer object of 100 artists>
```

works fine, but if I set width to be the diff of the ``datetime64`` array, which gives a ``timedelta64`` array, things break:

```python
In [7]: ax.bar(x[:-1], y[:-1], width=np.diff(x))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-f05692d600cb> in <module>()
----> 1 ax.bar(x[:-1], y[:-1], width=np.diff(x))

~/miniconda3/envs/dev/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1853                         "the Matplotlib list!)" % (label_namer, func.__name__),
   1854                         RuntimeWarning, stacklevel=2)
-> 1855             return func(ax, *args, **kwargs)
   1856 
   1857         inner.__doc__ = _add_data_doc(inner.__doc__,

~/miniconda3/envs/dev/lib/python3.6/site-packages/matplotlib/axes/_axes.py in bar(self, *args, **kwargs)
   2257         if align == 'center':
   2258             if orientation == 'vertical':
-> 2259                 left = x - width / 2
   2260                 bottom = y
   2261             elif orientation == 'horizontal':

TypeError: ufunc subtract cannot use operands with types dtype('float64') and dtype('<m8[D]')
```

This should however be unambiguous, so it would be nice if it worked.

**Comment by dstansby** [comment] 2018-05-25 21:34
Can you provide the full example with the `timedelta64` array that produces that error? I've encountered similar looking problems before, that depend on when we do our unit conversions, and this might actually be fixed in the master branch.

**Comment by astrofrog** [comment] 2018-05-25 21:49
@dstansby - the full example is:

```python
import numpy as np
import matplotlib.pyplot as plt
x = np.array(range(100), dtype='M8[D]')
ax = plt.subplot(1,1,1)
y = np.random.random(100)
ax.bar(x[:-1], y[:-1], width=np.diff(x))
```

**Comment by timhoffm** [comment] 2018-05-26 06:14
The problem is our unit conversion. We do
~~~
x = self.convert_xunits(x)
width = self.convert_xunits(width)
~~~

However, we don't have a conversion implemented for `timedelta64`. A result, `x` is our internal float-based date format while `width` is still a `timedelta64`, which cannot be subtracted from each other.

The solution would be to implement a converter for `timedelta64`.

**Comment by dstansby** [comment] 2018-05-26 10:00
Ah, so this would be fixed by something like https://github.com/matplotlib/matplotlib/pull/9120 I think.

**Comment by timhoffm** [comment] 2018-05-26 13:39
Sort of. It needs a bit more infrastructure:

- implement a converter analogously to `DateConverter`
- add it to `matplotlib.units.registry`

**Comment by dstansby** [comment] 2018-09-18 17:40
I'm having a look at this now, but having trouble with your example @astrofrog ; when I do
```python
import numpy as np
x = np.array(range(100), dtype='M8[D]')
print((x[:-1] + np.diff(x) / 2.0) - x[:-1])
```
I just get a bunch of zeros; dividing `np.diff(x)` by a number seems to just zero it out. Do you know of a way to fix this? Internally `Matplotlib` has to divide the width by 2, which is why I can't get your example working.

**Comment by QuLogic** [comment] 2018-09-18 20:48
`'M8[D]'` has a single day resolution, and your array goes up by one, so dividing by two rounds down to 0. You'd need to at least change it to hourly resolution.

**Comment by jklymak** [comment] 2018-09-18 21:31
@dstansby, not sure of the approach you are taking here, but I think as @timhoffm says, we should add timedelta64 to dates.py, and register it.  Then all the math can be done in floating point numbers...

**Comment by dstansby** [comment] 2018-09-18 22:00
Trying to take that approach, but running into the problem that `np.timedelta64` is a subclass of `numbers.Number`, so the conversion interface assumes it doesn't need converting:

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.units as munits
x = np.array(range(100), dtype='M8[D]')
xdiff = np.diff(x)
print(xdiff.dtype)
print(munits.ConversionInterface.is_numlike(xdiff))
```
prints
```python
timedelta64[D]
True
```

**Closed** 2019-01-13 11:08 UTC
Labels: units
