### ISSUE TITLE
Importing pyplot with Qt5Agg creates QApplication instance

### ISSUE THREAD

**Issue by laurenmarietta** [matplotlib/matplotlib#10813] opened 2018-03-16 14:02 UTC
### Bug report

**Bug summary**

Importing pyplot while using the matplotlib Qt5Agg backend in IPython creates an unwanted QApplication instance. This not only opens an invisible python window that makes the terminal window no longer the active window, it has interfered with my PyQt5 GUIs by resulting in conflicting QApplication instances.

**Code for reproduction**

```python
In [1]: from PyQt5 import QtCore

In [2]: QtCore.QCoreApplication.instance()

In [3]: import matplotlib

In [4]: matplotlib.use('Qt5Agg')

In [5]: import matplotlib.pyplot as plt

In [6]: QtCore.QCoreApplication.instance()
Out [6]: PyQt5.QtWidgets.QApplication at 0x1152d8948>
```

**Actual outcome**

Simply importing pyplot creates a QApplication instance, and opens a python session that takes focus and appears in the dock:
<img width="74" alt="screen shot 2018-03-16 at 9 51 30 am" src="https://user-images.githubusercontent.com/12650803/37524244-a58fb6e8-28ff-11e8-8b60-d3d2b75d5848.png">
Additionally, when running a simple GUI script, attempting to close the GUI with `app.quit()` results in the following errors:
```
QEventLoop: Cannot be used without QApplication
QSocketNotifier: Can only be used with threads started with QThread
```
which, as far as I can tell, seem to be a result of conflicting QApplication instances.

**Expected outcome**

I wouldn't expect simply importing pyplot to create a QApplication instance when using Qt5Agg? Or, if this is expected behavior, it should be documented somewhere.

**Matplotlib version**

  * Operating system: macOS 10.12.6
  * Matplotlib version: 2.2.0
  * Matplotlib backend: Qt5Agg
  * Python version: 3.5.4
  * PyQt5 version: 5.9.2

Matplotlib and python were both installed with conda using the AstroConda channel at http://ssb.stsci.edu/astroconda.

**Comment by anntzer** [comment] 2018-03-16 14:39
QApplication doesn't exist in QtCore, but in QtWidgets.  And I can't reproduce the issue...

```
In [1]: import PyQt5.QtCore

In [2]: PyQt5.QtCore.QApplication.instance()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-7624cbb313c1> in <module>()
----> 1 PyQt5.QtCore.QApplication.instance()

AttributeError: module 'PyQt5.QtCore' has no attribute 'QApplication'

In [3]: import PyQt5.QtWidgets

In [4]: PyQt5.QtWidgets.QApplication.instance()

In [5]: import matplotlib; matplotlib.use("qt5agg")

In [6]: PyQt5.QtWidgets.QApplication.instance()
```

The QApplication is created at https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_qt5.py#L104 (at some point we do need to create one, someone needs to manage the windows after all), please add e.g. `import traceback; traceback.print_stack()` in that function to see what's the call stack when the function is called.

**Comment by tacaswell** [comment] 2018-03-16 16:32
The application gets created when you import pyplot by IPython at https://github.com/ipython/ipython/blob/e6aa711b6a842ede3ec7ce46f17f1c548c3eab9f/IPython/terminal/pt_inputhooks/qt.py#L9-L14 which is installed as the input hook via https://github.com/matplotlib/matplotlib/blob/bb337ad315aa5b19f6c7fe71e02b38191dc041c1/lib/matplotlib/pyplot.py#L161-L163 which gets run when pyplot is imported and the IPython code runs as soon as the prompt returns which is when the QApp is actually created.  (As a side effect, our QtApp creation code never runs when using IPython, but that is a different matter).

There can not be more than one QApp in a process (the errors you are getting are the best case!  It can also segfault) I suggest doing the "does a QApp exist? if so use it! if not create it" dance where ever you create a QApplication in your code.

The integration with GUI frameworks is a bit delicate, we _try_ to make it 'just work' for the simple cases but that leads to a step learning curve when you want to go a bit beyond that as you run into a wall of 'helpful' features.

**Comment by anntzer** [comment] 2018-05-19 08:57
Closing as can't fix/not a bug/issue with IPython... but open to a doc PR.

**Closed by anntzer** 2018-05-19 08:57 UTC
Labels: GUI/Qt, needs clarification
