### ISSUE TITLE
Bars are not visible in bar plot when log scale is enabled

### ISSUE THREAD

**Issue by laborleben** [matplotlib/matplotlib#9701] opened 2017-11-06 16:39 UTC
When enabling log scale for the bar plot, the bars are not plotted properly and the plot is empty.

See also this bug report https://github.com/matplotlib/matplotlib/issues/163 and the corresponding fix https://github.com/matplotlib/matplotlib/pull/2147.

Commit https://github.com/matplotlib/matplotlib/commit/dda42abd96332578d6764c8f00ae6f520f0691bd changed the default value of `nonpos` parameter from `clip` to `mask` which introduced the issue. I cannot tell whether `clip` should be default behavior or `mask` doesn't work as intended.

```python
import matplotlib.pyplot as plt
plt.bar(x=[1,2,3], height=[1000,2,3])
plt.yscale("log")
plt.show()
```
Result is an empty plot. Saving to an image file or PDF doesn't make a change.

Adding
```python
plt.yscale("log", nonposy="clip")
```
fixes that issue.

Additional info:
Latest Miniconda
Various platforms (Ubuntu 16.04, Windows 10, macOS)
Matplotlib 2.1.0, Qt5Agg (from Anaconda)

**Comment by afvincent** [comment] 2017-11-06 16:58
Thank you for the nice report.

If I am correct this is a duplicate of #9288 and #9628, and the issue was fixed by #9477. Your MWE is working fine with Matplotlib from the current master branch and will be OK with Matplotlib 2.1.1, which should be shipped in aa very near future :).

Closing, but feel free to reopen if you think I was mistaken.

**Closed by afvincent** 2017-11-06 16:58 UTC
Labels: Duplicate
