### ISSUE TITLE
Plot window crashes when the 'Edit axes' button is pressed'

### ISSUE THREAD

**Issue by Kishore96in** [matplotlib/matplotlib#9466] opened 2017-10-18 01:32 UTC
### Bug report

**Bug summary**

**Code for reproduction**
```
import matplotlib.pyplot as plt
a = [[1,2],[3,4]]
plt.imshow(a)
plt.show()
```
Try to click on the 'edit axis, curve, and image parameters' button (the one with the wavy line with an arrow at the end) in the plot window.

**Actual outcome**

When I click the 'edit axis, curve, and image parameters' button in the plot window, the window crashes with the following output:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 681, in edit_parameters
    figureoptions.figure_edit(axes, self)
  File "/usr/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 168, in figure_edit
    + [(name, name) for name in sorted(image.iterpnames)])]
TypeError: 'method' object is not iterable
fish: “python matplotlibbug.py” terminated by signal SIGABRT (Abort)
````

**Expected outcome**

Expected outcome is to open the window which allows to edit the axis and curve parameters. This works on matplotlib version 2.0.2

**Matplotlib version**
  * Operating system: Arch Linux
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.2
  * Jupyter version (if applicable):
  * Other libraries: 

I installed matplotlib from the packages in the Arch repos [https://www.archlinux.org/packages/community/x86_64/python-matplotlib/](https://www.archlinux.org/packages/community/x86_64/python-matplotlib/)

**Comment by anntzer** [comment] 2017-10-18 01:40
duplicate of https://github.com/matplotlib/matplotlib/issues/9332, a PR to fix the issue has already been opened.

**Closed by anntzer** 2017-10-18 01:40 UTC
