### ISSUE TITLE
ImportError: cannot import name 'rcParams'

### ISSUE THREAD

**Issue by santhoshav15** [matplotlib/matplotlib#12983] opened 2018-12-13 11:06 UTC
OS: Ubuntu 16.04
Python Version: 3.5.2
Matplotlib Version: 3.0.2

When i try to `from matplotlib import pyplot as plt`

>     Traceback (most recent call last):
>     File "try.py", line 2, in
>     from matplotlib import pyplot as plt
>     File "/home/artivatic/.virtualenvs/test/lib/python3.5/site-packages/matplotlib/init.py", line 124, in
>     import inspect
>     File "/usr/lib/python3.5/inspect.py", line 35, in
>     import dis
>     File "/home/artivatic/Documents/Santhosh/data/ori_data/dis.py", line 1, in
>     from matplotlib import pyplot as plt
>     File "/home/artivatic/.virtualenvs/test/lib/python3.5/site-packages/matplotlib/pyplot.py", line 32, in
>     import matplotlib.colorbar
>     File "/home/artivatic/.virtualenvs/test/lib/python3.5/site-packages/matplotlib/colorbar.py", line 28, in
>     import matplotlib.artist as martist
>     File "/home/artivatic/.virtualenvs/test/lib/python3.5/site-packages/matplotlib/artist.py", line 10, in
>     from . import cbook, docstring, rcParams
>     ImportError: cannot import name 'rcParams'

Any solution?

**Comment by tacaswell** [comment] 2018-12-13 21:47
The issue is that you have a `dis.py` in your current directory (`File "/home/artivatic/Documents/Santhosh/data/ori_data/dis.py", line 1, in`) that is shadowing the built in `dis` module.  We import `dis` (via `inspect`) in `matplotlib/__init__.py`, your `dis` then import `matplotlib.pyplot` which tries to get things out of the `matplotlib` module before it has finished setting it's self up.

The solution is to run python from a path that does not have files that shadow the standard library.

I am going to close this because there is nothing we can do at the Matplotlib level to avoid this problem.

**Closed by tacaswell** 2018-12-13 21:47 UTC

**Comment by FerCris** [comment] 2019-05-09 20:34
i have the same problem, uninstall matplotlib and then install again.
