### ISSUE TITLE
Saving plot as PNG file prunes tick labels 

### ISSUE THREAD

**Issue by JackCaster** [matplotlib/matplotlib#12564] opened 2018-10-19 10:27 UTC
### Bug report

**Bug summary**
When I export a plot to PNG, some tick labels are pruned. This does not happen if I use another format, such as PDF or SVG.
**Code for reproduction**
I failed to recreate the problem with a dummy dataset. It seems that the problem is very much an edge case probably. This is what I see on my Jupyter notebook:
![image](https://user-images.githubusercontent.com/18400141/47212510-b29e2b00-d398-11e8-948b-e135d4006c44.png)

The plot is exported nicely in PDF: [test.pdf](https://github.com/matplotlib/matplotlib/files/2495405/test.pdf)

But, if I use PNG, the bottom and upper y-tick labels are pruned:
![test](https://user-images.githubusercontent.com/18400141/47212545-cf3a6300-d398-11e8-8839-b053e2f24335.png)

I tried to play around with the padding in `plt.tight_layout()` and the options in `plt.savefig()` without success.

**Matplotlib version**

  * Operating system: Windows 10 Pro N
  * Matplotlib version: 3.0.0 (from Conda)
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.6.6 (from Conda)
  * Jupyter version (if applicable): 1.0.0

**Comment by ImportanceOfBeingErnest** [comment] 2018-10-19 12:28
Feel free to provide a minimal verifiable example, which allows to reproduce the probem. Else, I see little chance to help here.

**Comment by jklymak** [comment] 2018-10-19 14:34
Try increasing your dpi on the png.  

There is some weird dpi-dependent code for adding or dropping ticks.  One of my prs fixes it though I’m not sure if it’s been merged yet.

**Comment by JackCaster** [comment] 2018-10-19 17:31
> Try increasing your dpi on the png.
> 
> There is some weird dpi-dependent code for adding or dropping ticks. One of my prs fixes it though I’m not sure if it’s been merged yet. EDIT: Not merged: #12158

It is indeed related to the DPI I set. But it is the other way around you suggested. Up to 80 DPI everything is fine. Above that, the tick labels are pruned. Weird. I would try to come up with a reproducible example.

**Comment by jklymak** [comment] 2018-10-19 17:39
You probably don't need to - its a known issue...  From my testing, I think its an issue of your upper ylimit limit being close, but less than, 1.25.  When you decrese the dpi, your upper limit becomes within 1/2 a pixel of 1.25 and includes the 1.25; when you increase the dpi your upper limit is no longer within 1/2 a pixel, and it gets trimmed.

#12158 will *always* trim that tick because your upper y-limit < 1.25.  Of course, if you manually specify set_ylim([0, 1.25]) it will *not* be trimmed.   I think that is the correct and consistent behaviour.

**Comment by jklymak** [comment] 2018-10-19 18:12
A minimal example is:

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.set_ylim(0, 1.199)

fig.savefig('boo100.png', dpi=100)
fig.savefig('boo200.png', dpi=200)
```

![boo100](https://user-images.githubusercontent.com/1562854/47236066-d8730200-d38f-11e8-8691-47671a9081f6.png)

![boo200](https://user-images.githubusercontent.com/1562854/47236080-e45ec400-d38f-11e8-8d81-3a05e0242c5f.png)

**Closed** 2018-10-21 11:48 UTC

**Comment by JackCaster** [comment] 2018-10-21 11:49
> You probably don't need to - its a known issue... From my testing, I think its an issue of your upper ylimit limit being close, but less than, 1.25. When you decrese the dpi, your upper limit becomes within 1/2 a pixel of 1.25 and includes the 1.25; when you increase the dpi your upper limit is no longer within 1/2 a pixel, and it gets trimmed.
> 
> #12158 will _always_ trim that tick because your upper y-limit < 1.25. Of course, if you manually specify set_ylim([0, 1.25]) it will _not_ be trimmed. I think that is the correct and consistent behaviour.


Thank you. That worked.
