### ISSUE TITLE
Pyplot.savefig is very slow with some combinations of data/ylim scales

### ISSUE THREAD

**Issue by soupault** [matplotlib/matplotlib#5918] opened 2016-01-26 08:46 UTC
Hi!

I've found this quite strange behaviour where `savefig` hangs:

    import numpy as np
	import pandas as pd
	import matplotlib.pyplot as plt

	df_data = pd.DataFrame(np.random.rand(20, 1), columns=['a'])

	fig, axes = plt.subplots()

	axes.errorbar(
	    df_data.index,
	    df_data['a'],
	    color='CadetBlue', marker='d')

	# Hangs
	# axes.vlines(8.5, 0, 1e6, colors='Silver', linestyles='dashed')
	# axes.set_ylim((0, 1))

	# Works
	# axes.vlines(8.5, 0, 1e3, colors='Silver', linestyles='dashed')
	# axes.set_ylim((0, 1))

	# Works
	# axes.vlines(8.5, 0, 1e6, colors='Silver', linestyles='dashed')
	# axes.set_ylim((0, 1e1))

	print('check A')
	plt.savefig('test_image')
	print('check B')
	plt.close()

Software versions:
Windows 7 x64 (will test on Linux later);
Python 3.4.4 (conda);
matplotlib 1.5.1 (from C.Gohlke website).

**Comment by jenshnielsen** [comment] 2016-01-26 11:32
I cannot reproduce on OSX but the first example is significantly slower than the other ones.

```bash
✔ /tmp time python test.py
check A
check B

real	0m4.510s
user	0m4.337s
sys	0m0.137s
✔ /tmp time python test.py
check A
check B

real	0m0.596s
user	0m0.428s
sys	0m0.137s
✔ /tmp time python test.py
check A
check B

real	0m0.989s
user	0m0.820s
sys	0m0.139s
```

**Comment by soupault** [comment] 2016-01-26 14:45
**Archlinux x86 (VirtualBox, host OS - Windows 7) + Python 3.5**:

    real	0m30.383s
    user	0m23.423s
    sys	0m0.430s

    real	0m1.398s
    user	0m1.137s
    sys	0m0.130s

    real	0m3.780s
    user	0m3.280s
    sys	0m0.187s

**Windows 7 x64 + Python 3.4/3.5**:
    
    Time in function:  1.6603806768324172
    Time in function:  0.1836972611066508
    Time in function:  1.5265597221127234

**Windows 7 x64 + Python 3.4 + PyCharm 5.0.3**:

    Time in function:  15.115553113146417
    Time in function:  0.18948891189273387
    Time in function:  1.6320876580224977

Same as the last one, but with 2 similar subplots (data deepcopied):

    Time in function:  10.064142940647127
    Time in function:  0.2876432809620065
    Time in function:  1.284863381885545

---
Performance on Windows is measured with:

    import time
    t_ = time.clock()
    # ... code ...
    time.clock() - t_

**Comment by jenshnielsen** [comment] 2016-01-26 15:00
It is certainly slower than it should be. If your aim is to create a line which goes from top to bottom you might be better off with axvspan see http://matplotlib.org/api/axes_api.html#matplotlib.axes.Axes.axvspan

**Comment by soupault** [comment] 2016-01-26 18:31
@jenshnielsen thanks for the hint!
Still, I find this issue important because it may point at some archcitectural flaws.

**Comment by mdboom** [comment] 2016-01-26 20:57
Running this in the profiler, it seems that this is due to plotting a very long dashed line.  Dashing lines is quite slow, and due to the way Agg renders things, rather memory intensive.  Clipping would help here, but we don't currently clip path collections (since doing so would be harder to do the "stamping" optimizations when the same shape at the same size is used multiple times).

As @jenshnielsen suggested, if you just want to make sure the vertical line goes all the way across the axes, you can use `axvspan`.

I'm going to close this as "wontfix", but feel free to reopen if `axvspan` does not turn out to be a reasonable solution for your use case.

**Closed by mdboom** 2016-01-26 20:57 UTC
