### ISSUE TITLE
imshow doesn't properly display some images

### ISSUE THREAD

**Issue by jbhopkins** [matplotlib/matplotlib#10072] opened 2017-12-21 16:59 UTC
### Bug report

**Bug summary**
When using imshow with larger images, you lose pixel resolution for low intensity pixels with lots of nearby zeros (not sure if the intensity or nearby zeros are relevant, or just relative isolation of the pixel). It's like they're being interpolated away, even if interpolation is set to nearest. This is new behavior in version 2.1.

**Code for reproduction**
Use the attached npy file, which is an image referenced in this test script.
```python
import matplotlib.pyplot as plt
import numpy as np

img = np.load('test_image.npy')

#Display full image
plt.imshow(img, interpolation = 'nearest')
plt.clim(0, 5)
plt.show()

#Display part of image
plt.imshow(img[200:400,500:700], interpolation = 'nearest')
plt.clim(0, 5)
plt.show()
```

**Actual outcome**
Using matplotlib 2.1.1:
Screenshot from the display of full image (first plot in code above):
![full_plot_2p1](https://user-images.githubusercontent.com/23534688/34265221-4dc67306-e643-11e7-80ee-ab4886a03f65.png)

Using the  zoom tool to zoom in on a region when the full image is plotted:
![zoom_full_plot_2p1](https://user-images.githubusercontent.com/23534688/34265229-53ac1550-e643-11e7-81d3-6519f2975046.png)

Plotting roughly the same zoom region initially (second plot in code above):
![partial_plot_2p1](https://user-images.githubusercontent.com/23534688/34265239-5c248a3c-e643-11e7-893f-a2cd6445a34b.png)

**Expected outcome**
It should all look like the third image. Here's the output when the same code is run in version 2.0.2
Screenshot from the display of full image (first plot in code above):
![full_plot_2p0](https://user-images.githubusercontent.com/23534688/34265349-9a67f072-e643-11e7-80a7-ed77c4f9d5cf.png)

Using the  zoom tool to zoom in on a region when the full image is plotted:
![zoom_full_plot_2p0](https://user-images.githubusercontent.com/23534688/34265367-a3143028-e643-11e7-82b9-da96e16c6284.png)

Plotting roughly the same zoom region initially (second plot in code above):
![partial_plot_2p0](https://user-images.githubusercontent.com/23534688/34265376-a9e27dec-e643-11e7-9bf2-c1e36fe90a9d.png)

**Matplotlib version**
  * Operating system: macOS 10.12.6
  * Matplotlib version: 2.1.1 (broken) and 2.0.2 (working)
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 2.7.12
  * Other libraries: numpy version 1.13.3

All libraries are installed through conda, using the standard channel. This includes both versions of matplotlib (2.1.1 and 2.0.2).

Numpy file with image data:
[test_image.zip](https://github.com/matplotlib/matplotlib/files/1579886/test_image.zip)

**Comment by jbhopkins** [comment] 2017-12-21 17:02
One additional note. This doesn't seem to be backend dependent. I first noticed the bug on the wxagg backend. Here's some code for reproducing it there if you want:

```python
import matplotlib
import numpy as np
import wx
from matplotlib.backends.backend_wxagg import NavigationToolbar2WxAgg
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg

class ImagePanel(wx.Panel):

    def __init__(self, parent, panel_id, name, *args, **kwargs):

        wx.Panel.__init__(self, parent, panel_id, *args, name = name, **kwargs)

        self.fig = matplotlib.figure.Figure((5,4), 75)
        self.canvas = FigureCanvasWxAgg(self, -1, self.fig)

        self.draw_cid = self.canvas.mpl_connect('draw_event', self.safe_draw)

        self.toolbar = NavigationToolbar2WxAgg(self.canvas)
        self.toolbar.Realize()

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.canvas, 1, wx.LEFT|wx.TOP|wx.GROW)
        sizer.Add(self.toolbar, 0, wx.GROW)

        self.SetSizer(sizer)

    def safe_draw(self, event = None):
        '''should allow drawing when the panel resizes'''
        self.canvas.mpl_disconnect(self.draw_cid)
        self.canvas.draw()
        self.draw_cid = self.canvas.mpl_connect('draw_event', self.safe_draw)

    def showNewImage(self, img):
        '''Plots a new image'''
        self.img = img
        self.fig.clear()

        a = self.fig.gca()

        self.imgobj = a.imshow(self.img, interpolation = 'nearest')

        a.set_title('My Image Title')
        a.set_xlabel('x (pixels)')
        a.set_ylabel('y (pixels)')
        a.axis('image')

        self.imgobj.set_clim(0, 5)

        self.canvas.draw()

class ImageFrame(wx.Frame):
    ''' A Frame for testing the image panel '''

    def __init__(self, title, frame_id):
        wx.Frame.__init__(self, None, frame_id, title, name = 'MainFrame')

        self.SetSize((750,750))

        self.background_panel = wx.Panel(self, -1)
        self.image_panel = ImagePanel(self.background_panel, -1, 'ImagePlotPanel')

        sizer = wx.BoxSizer()
        sizer.Add(self.image_panel, 1, wx.GROW)

        self.background_panel.SetSizer(sizer)

        self.loadTestImage()

    def loadTestImage(self):
        img = np.load('test_image.npy')
        self.image_panel.showNewImage(img)


class ImageTestApp(wx.App):
    ''' A test app '''

    def OnInit(self):

        frame = ImageFrame('My Image', -1)
        self.SetTopWindow(frame)
        frame.CenterOnScreen()
        frame.Show(True)
        return True

if __name__ == "__main__":
    app = ImageTestApp(0)
    app.MainLoop()
```

**Comment by tacaswell** [comment] 2017-12-21 17:24
What is the datatype of your input data?

Can you reproduce this with synthetic data?

**Comment by jbhopkins** [comment] 2017-12-21 17:29
The datatype is a numpy array saved as a .npy file. It's attached in a .zip file at the very end of the initial post. It started life as an image from an x-ray detector (hdf5 file), but the converted and attached version shows the same bug.

I haven't tried with synthetic data. If I have a chance, I'll try to generate a dataset and test, but I can't promise I'll have time to do that.

**Comment by tacaswell** [comment] 2017-12-21 17:55
Does it work if you cast to floats first?  My knee-jerk guess is that we have gotten too-careful with preserving input types.

**Comment by jbhopkins** [comment] 2017-12-21 18:00
If I cast it as a float it works fine, good guess!

I don't understand enough about the inner workings of matplotlib to know why that changed things. Is this something you'll fix going forward, or should I just default to casting to float?

**Comment by tacaswell** [comment] 2017-12-21 18:10
Definitely something that should be fixed (hopefully soon!), but as a work around _now_ casting to float will work.

The root of the issues is we removed a couple of cast-to-float calls (both to save memory and to avoid down-casting float128 values) but apparently now let uint though un cast which means in the normalization step they all end up being 0 or 1 (as it looks like your minimum is 0 and all of the other values are strictly less that the maximum value except the maximum so integer division does it's thing).

**Comment by jbhopkins** [comment] 2017-12-21 18:23
Great, thanks! I will look for it in the next release (hopefully). I appreciate the fast response, and all of your hard work, along with the rest of the community.

**Comment by jklymak** [comment] 2017-12-30 00:14
Pretty sure it was https://github.com/matplotlib/matplotlib/pull/8966  around line 382 of `image.py`

**Comment by xanfus** [comment] 2018-03-02 15:33
Setting interpolation to "none" leads to image being displayed with white blank area.
![for github](https://user-images.githubusercontent.com/5682375/36906778-e25aa9a6-1e47-11e8-90cd-732093c87c21.png)
```
plt.imshow(nx_19R_24R[1],aspect="auto",interpolation="none")
plt.gca()[:invert_yaxis]()
plt.colorbar()
plt.show()
```

**Comment by jklymak** [comment] 2018-03-02 15:42
Impossible to replicate.  If you make a random matrix the same size as your input what happens?   Do you need the other stuff to trigger the error?

**Comment by xanfus** [comment] 2018-03-02 16:19
Calls for gca and colorbar aren't required to replicate issue at my side. Random noise of same size is depicted being cut in same way.
x is iterated from 10000 to 80000
```
plt.imshow(rand(100,x),aspect="auto",interpolation="none")
    plt.show()
```
![figure_11](https://user-images.githubusercontent.com/5682375/36909208-796bf862-1e4e-11e8-9b53-127478a45a97.png)
![figure_1-3](https://user-images.githubusercontent.com/5682375/36909242-86fcfd0a-1e4e-11e8-96d0-f223e93b9d94.png)
![figure_1-4](https://user-images.githubusercontent.com/5682375/36909241-86deb7e6-1e4e-11e8-8a6f-8e0978fd6c6f.png)
![figure_1-5](https://user-images.githubusercontent.com/5682375/36909240-86c05738-1e4e-11e8-830d-57dfbf8a7afa.png)
![figure_1-6](https://user-images.githubusercontent.com/5682375/36909239-869ce082-1e4e-11e8-889f-63bb4d9e71e7.png)
![figure_1-7](https://user-images.githubusercontent.com/5682375/36909238-867cd440-1e4e-11e8-8797-9c0c4d939caa.png)
![figure_1-8](https://user-images.githubusercontent.com/5682375/36909236-865cafa8-1e4e-11e8-8b04-73355d81b573.png)

**Comment by jklymak** [comment] 2018-03-02 17:09
@xanfus This is a separate issue.  Can you open a new issue?  Thanks!

**Comment by jklymak** [comment] 2018-03-02 18:08
Also, cannot replicate on master with qt5Agg, so this is either fixed, or backend dependent.

**Comment by xanfus** [comment] 2018-03-04 11:56
I have to supply issue with full toolchain and matplotlib version. I've postponed the task.

**Comment by mmf1982** [comment] 2018-04-13 13:10
The sort of problem can be reproduced with: 
``
x=np.random.random([3,3])
x[1,1]=1.e88
plt.imshow(x,vmax=2)
plt.show()
``
In matplotlib v.2.0.2 this was still ok, v.2.1 and 2.2 fail here. I think this is the issue we see in the original post.
The problem is in image.py, _ImageBase, _make_image, in the section of "if not unsampled", section "A.dim ==2": To produce  A_resampled, A is  first scaled into the range .1 --.9. If the original values have too large a spread, you loose resolution in color space and the values passed to the Normalize object from colors.py already lost the "details" (i.e. in the example above, all the values around 1.e88 are the same). A quick fix is to use A instead of A_scaled when creating the A_resampled and then not to un-do the rescaling in the A_resampled. (i.e. comment out lines 397 -- 402 and 421 -- 424). There is a note in the comment to that part of the code that mentions possible problems: 

> This may introduce numeric instabilities in very broadly scaled data

**Comment by tacaswell** [comment] 2018-04-13 13:40
@mmf1982 If you do not scale then you run into clipping issues as the underyling re-sampling code will clip to [0, 1].

Which version of 2.2 are you testing with?

**Comment by mmf1982** [comment] 2018-04-13 13:50
Hi Thomas,

Thanks for your email.

 

Why do you need the scaling at that point at all?

After creating the resampled A, the scaling is reversed again.... so I think it is not needed at that point (?)

I do not think that there are issues if you skip the scaling in that part of the image code (it is like if you were using pcolor instead of image before sending the data to Normalize)

 

I used version 2.2.2 and version 2.1.2. Both have the same problem. In version 2.0.2, this is not the case.

 

Ciao,

Martina.

 


 

__________________________________________________________
The advertisement below this line was added by GMX __________________________________________________________

 
 

Gesendet: Freitag, 13. April 2018 um 15:41 Uhr
Von: "Thomas A Caswell" <notifications@github.com>
An: matplotlib/matplotlib <matplotlib@noreply.github.com>
Cc: mmf1982 <5464@gmx.net>, Mention <mention@noreply.github.com>
Betreff: Re: [matplotlib/matplotlib] imshow doesn't properly display some images (#10072)


@mmf1982 If you do not scale then you run into clipping issues as the underyling re-sampling code will clip to [0, 1].

Which version of 2.2 are you testing with?

**Comment by jklymak** [comment] 2018-04-13 14:00
The scaling is there to make sure out-of-range interpolation works properly.  

We need to do math on your data to plot it.  If you supply values that cause floating point roundoff you will get floating point roundoff and your data will lose resolution.

**Comment by mmf1982** [comment] 2018-04-13 14:34
Why would you need this scaling- and un-scaling for image but not for pcolor? Consider:
``x=np.array([[1.,2.],[0.1,1e18]]); plt.subplot(121); plt.imshow(x,vmax=4);plt.subplot(122,aspect="equal").invert_yaxis(); plt.pcolormesh(x,vmax=4)
``
pcolor works just fine. I have not encountered problems skipping this scaling-and un-scaling in image. In scientific datasets, large number are often used as invalid data identifier. I used to use image for quickly checking data. However, this new "feature" make imshow pretty useless for this.

**Comment by jklymak** [comment] 2018-04-13 16:32
First, I think its pretty straightforward to do `x = np.ma.masked_greater(x, 1e10)` or whatever is adequate to catch your bad flag.  

But, I agree that if you specify `vmax` in `imshow` that it should do a better job of the scaling.  

@tacaswell the interpolation happens at draw time.  Should we not use `vmin` and `vmax` to do the scaling if they are set?

**Comment by jklymak** [comment] 2018-04-13 16:40
Oh, hold it, we kind of do, but only if you set both `vmin` and `vmax`.  The bug here is that `vmin=None` and then our attempt to make things right fails.

**Comment by tacaswell** [comment] 2018-04-13 16:45
For pcolor we are rendering individual rectangle patches w for here as for image we resample the image and then pass that to the renderer.  In general `imshow` will be much faster for large arrays.

You can not use `vmin` and `vmax` for the rescaling limits because you will not get the interpolation correct as you will be clipping any large values to just above / below the limits.

**Comment by tacaswell** [comment] 2018-04-13 16:46
ah, that means we just need to make sure the norm has auto-scaled.

**Comment by mmf1982** [comment] 2018-04-13 16:56
jklymak, sure I can mask the bad flag, but it's one more step to do and not at all handy if you do not know beforehand what was actually used and you just want to get an impression of the data. 
I realized that, if I do the plotting and then re-size the plotting window, using version 2.2.2, it sets back to ok scaling. The same is not true for 2.1.2.

**Comment by jklymak** [comment] 2018-04-13 16:56
See #11047 for the same fix as before, but this time handling if the norms are `None`.

@tacaswell, I just used the data min and max rather than relying on a norm autoscaling.

**Comment by jklymak** [comment] 2018-04-13 16:57
@mmf1982 OK, thats probably because the autoscaling for the norm gets applied at the first draw, so the second raw has the correct info.

**Comment by mmf1982** [comment] 2018-04-13 18:26
There are still problems if the initial dtype is not float64 and the outlier is negative, consider:
``x=np.array([[0.1,0.2],[-1.e18,0.3]]).astype("float32");plt.imshow(x,vmin=0,vmax=0.5)``
I set both vmin and vmax, but still the result does not look as wanted. In fact, this is even more akward,0.1, 0.2 and -1e18 are coloured as min and 0.3 as maximum. 
I still do not see why you "need to do the scaling and unscaling" to the data. If you do not do it, the internal resampling is fine. (?)

**Comment by tacaswell** [comment] 2018-04-13 19:39
@mmf1982 See discussions at https://github.com/matplotlib/matplotlib/issues/8631 https://github.com/matplotlib/matplotlib/pull/8966, https://github.com/matplotlib/matplotlib/pull/5718 and https://matplotlib.org/users/dflt_style_changes.html#colormapping-pipeline for more details.

**Comment by jklymak** [comment] 2018-04-13 20:04
The `dv  * 1e7` was too big for `float32`.  Changed to `dv * 1e4` seems OK, but that value was just empricallly decided.  See change to #11047

**Comment by mmf1982** [comment] 2018-04-16 12:08
Thanks @tacaswell for the references and thanks @jklymak for the fix.

**Closed** 2018-05-14 19:30 UTC
