### ISSUE TITLE
Markers have compression artifacts

### ISSUE THREAD

**Issue by fkbreitl** [matplotlib/matplotlib#8284] opened 2017-03-13 18:52 UTC
### Bug report

**Markers appear smeared and not clear**

- When I plot markers with pyplot they show compression artifacts even when I save them as PNG.

**Code for reproduction**

```python
#!/usr/bin/env python                                                          

import numpy as np
import matplotlib.pyplot as plt

x = [1, 2, 3]

plt.errorbar(x, x, xerr=.05, yerr=.02, fmt='+')

plt.savefig('test.png')
```

**Actual outcome**

See image attached. 

**Expected outcome**

I want markers without smearing or interpolation as clear as the resolution permits.

**Matplotlib version**

- Matplotlib version 2.0.0, Python 2.7.13 and Debian 9.
- Matplotlib installed with `pip`

![test](https://cloud.githubusercontent.com/assets/1030293/23870396/909af9d2-0826-11e7-92e9-3c583b1d692d.gif)

**Comment by tacaswell** [comment] 2017-03-13 18:55
Why do you think these are compression artifacts?

**Comment by fkbreitl** [comment] 2017-03-13 18:56
What else?

**Comment by fkbreitl** [comment] 2017-03-13 19:23
I just realize now, that the asymmetry of the marker is caused by the fmt='+'. If I replace this by `linestyle=''`, then the smearing becomes symmetric. I think this is then displayed correctly and this is not a bug.

**Comment by QuLogic** [comment] 2017-03-13 23:54
`fmt='+'` means each value gets a plus marker, then the errorbars are drawn on top. If you want no markers, then use `fmt='none'`, but there's currently a bug there... #8163

**Comment by tacaswell** [comment] 2017-03-14 18:25
This is a duplicate of https://github.com/matplotlib/matplotlib/issues/3400 due to fractional pixel offests between the lines used for the error bars and the marker.

**Closed by tacaswell** 2017-03-14 18:25 UTC
