### ISSUE TITLE
Subscripts not displayed correctly for high dpi

### ISSUE THREAD

**Issue by swish42** [matplotlib/matplotlib#18899] opened 2020-11-05 15:31 UTC
Some subscripts seem to be incorrectly displayed in figures with high pixel density. For example, subscript + is shown correctly even for dpi=600, while subscript - or * are not shown correctly and the previous letter is cut off. This is similar to #4428, so apparently the issue has not been resolved.
Example:
```
import matplotlib.pyplot as plt
fig1 = plt.figure()
ax1 = fig1.add_subplot(111)
ax1.axis([0, 5, 0, 5])
ax1.text(2,4, '$X_-$', fontsize=25)
ax1.text(4,4, '$X_+$', fontsize=25)
ax1.text(2,2, '$X_*$', fontsize=25)

fig2 = plt.figure(dpi=600)
ax2 = fig2.add_subplot(111)
ax2.axis([0, 5, 0, 5])
ax2.text(2,4, '$X_-$', fontsize=25)
ax2.text(4,4, '$X_+$', fontsize=25)
ax2.text(2,2, '$X_*$', fontsize=25)
```
produces
![correct](https://user-images.githubusercontent.com/62450716/98260326-7d66d480-1f83-11eb-991b-cec0de871ea3.png)
![error](https://user-images.githubusercontent.com/62450716/98260342-80fa5b80-1f83-11eb-9aa8-8fd7a0aa7802.png)

I am using matplotlib 3.3.2 with Python 3.7.8.

**Comment by anntzer** [comment] 2020-11-05 17:52
I think this is a duplicate of https://github.com/matplotlib/matplotlib/issues/15313?

**Closed by anntzer** 2020-11-05 17:52 UTC
Labels: status: duplicate, text/mathtext
