### ISSUE TITLE
[Bug]: new constrained_layout causes axes to go invisible(?)

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#22264] opened 2022-01-19 10:27 UTC
### Bug summary

Since #20426, `plt.figure(constrained_layout=True).subplots(3)` (or `layout="constrained"`) shows no axes whatsoever.
attn @jklymak, I guess :)

### Code for reproduction

See above.

### Actual outcome

Blank figure.

### Expected outcome

Not blank figure.

### Operating system

fedora

### Matplotlib Version

HEAD, bisects to #20426.

### Matplotlib Backend

mplcairo

### Python version

310

### Installation

git checkout

**Comment by jklymak** [comment] 2022-01-19 10:34
I can't reproduce.  And obviously we test CL pretty heavily, so all our tests would fail if that didn't work at all.  So you must have something else in your setup causing the problem.

**Comment by jklymak** [comment] 2022-01-19 10:34
(Well, OK, I didn't try and reproduce with mplcairo)...

**Comment by anntzer** [comment] 2022-01-19 10:40
Oh, that's interesting... this only occurs with mplcairo, even though I would have thought this touched something completely orthogonal to the actual renderer (this is why I didn't think about checking that part).  I'll investigate, sorry for the noise.

**Comment by jklymak** [comment] 2022-01-19 10:43
Well, it is weird that it doesn't work w/ mplcairo.  If there is something we need to fix, we should try before release...

**Comment by anntzer** [comment] 2022-01-19 10:46
Do you know if the sequence of draws changed with #20426?

**Comment by jklymak** [comment] 2022-01-19 11:48
Not on purpose.  However I think things changed so that the layout parameters were not hard coded when the gridspecs are created.  Ie the width ratios etc are done at drawtime.  That allows you to change the gridspec width ratios and have it take effect.  However I think this went in before.

**Comment by anntzer** [comment] 2022-01-20 00:30
OK, I figured out that this occured because I was doing some weird dance to try to reuse renderer instances in order to not invalidate the text layout cache (now see #22271, which doesn't immediately address the text cache but is preliminary work in that direction), but #20426 changed something and I ended up drawing to a draw-disabled renderer.  I just stripped out most of the caching for now.
Perhaps still worth figuring out exactly what changed, but I guess I can just milestone this as 3.6 for myself and have a look when I can, with less urgency.

**Comment by jklymak** [comment] 2022-01-20 08:19
I'm going to close this since it is working as expected for unpatched Matplotlib.  If when adding your "weird" renderer dance you come up with a flaw in how constrained_layout is implemented, feel free to re-raise the issue, but there is nothing actionable for the rest of us (yet).

**Closed by jklymak** 2022-01-20 08:19 UTC
Labels: status: needs clarification, topic: geometry manager
