### ISSUE TITLE
Import Error from Matplotlib v. 2.2.2 under Anaconda 5.1 Mac OS X Sierra

### ISSUE THREAD

**Issue by OrbitalMechanic** [matplotlib/matplotlib#11049] opened 2018-04-14 01:40 UTC
I installed an application PyKep installed under the Anaconda distribution version 5.1 and in running a simple command,

import pykep as pk

posted on https://esa.github.io/pykep/examples/ex1.html. The response I get is contained the attached file to this note.

I'm running this on a Mac Pro under Mac OS X Ver. 10.12.6 Sierra, under Python 3.6.5. I'm running Matplotlib ver. 2.2.2.

It appears that I may have some misconfiguration with respect to Matplotlib with it invoking libz in /usr/lib as opposed to using the one under /Users/user/anaconda3/lib.

Any suggestions?

Sam Dupree
P.S. - I'm still learning Python, so when it comes to solutions please keep it straightforwardly simple (my version of K.I.S.S.)

[Output_Test_for_PyKep.txt](https://github.com/matplotlib/matplotlib/files/1909910/Output_Test_for_PyKep.txt)

**Comment by efiring** [comment] 2018-04-14 19:58
Sam, this is a conda packaging problem, not a matplotlib problem, so the appropriate venue is the `Anaconda - Public <anaconda@continuum.io>` mailing list.

Conda is great but not perfect, and it is not uncommon to run into conflicts.  Usually they are easily resolved with some combination of uninstalling and reinstalling components, sometimes from a different channel--but it can take some exploration to find the right sequence of package operations to clear up a problem.  Often the problem is not in the main package--like matplotlib--but in packages in its chain of dependencies.  This is exactly your case--your libpng and your libz versions are incompatible.

**Closed by efiring** 2018-04-14 19:58 UTC

**Comment by OrbitalMechanic** [comment] 2018-04-15 03:14
Thank you for responding to my post. I'll follow this up on Anaconda.
Sam Dupree.
