### ISSUE TITLE
[Bug]: DeprecatoinWarning 3D surface

### ISSUE THREAD

**Issue by jgrou** [matplotlib/matplotlib#27616] opened 2024-01-09 13:06 UTC
### Bug summary

Using [the example](https://matplotlib.org/stable/gallery/mplot3d/surface3d.html#sphx-glr-gallery-mplot3d-surface3d-py) from the matplotlib website for making a 3D surface colormap plot gives a deprecation warning.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

from matplotlib import cm
from matplotlib.ticker import LinearLocator

fig, ax = plt.subplots(subplot_kw={"projection": "3d"})

# Make data.
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)

# Plot the surface.
surf = ax.plot_surface(X, Y, Z, cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)

# Customize the z axis.
ax.set_zlim(-1.01, 1.01)
ax.zaxis.set_major_locator(LinearLocator(10))
# A StrMethodFormatter is used automatically
ax.zaxis.set_major_formatter('{x:.02f}')

# Add a color bar which maps values to colors.
fig.colorbar(surf, shrink=0.5, aspect=5)

plt.show()
```

### Actual outcome

MatplotlibDeprecationWarning: The clean function was deprecated in Matplotlib 3.8 and will be removed two minor releases later. Use none, you no longer need to clean a Grouper instead.
  surf = ax.plot_surface(X, Y, Z, cmap=cm.coolwarm,

### Expected outcome

The expected plot is there, I but would not expect any warning.

### Operating system

Windows

### Matplotlib Version

3.8.0

### Python version

3.11.4

### Installation

None

**Comment by oscargus** [comment] 2024-01-09 13:18
Considering that there are no warnings printed in the rendered example, this may be a case of a recent issue where mpl_toolkits get loaded from a different Matplotlib version. Can you please include the complete message?

**Comment by jgrou** [comment] 2024-01-09 14:47
This is basically the complete message:
`runfile('C:/Users/jgrou/untitled2.py', wdir='C:/Users/jgrou')
c:\users\jgrou\untitled2.py:17: MatplotlibDeprecationWarning: The clean function was deprecated in Matplotlib 3.8 and will be removed two minor releases later. Use none, you no longer need to clean a Grouper instead.
  surf = ax.plot_surface(X, Y, Z, cmap=cm.coolwarm,`

**Comment by oscargus** [comment] 2024-01-09 15:37
Thanks! Unfortunately there is no path in there as I hoped for...

Checking one of the other reports, can you first do:
```
import warnings

warnings.filterwarnings("error")

import matplotlib.pyplot as plt
```

What is especially interesting is if there are different paths to matplotlib and mpl_toolkits (which hopefully both show up in the complete trace-back).

Related are (probably) #26827 and #27342 although this is a different thing happening. It could still be the same reason though, although we do not really know how to avoid it (python picks up another version of mpl_toolkits, which here seems to call a deprecated method, although the 3.8-version of mpl_toolkits doesn't). One can try uninstalling matplotlib and reinstalling again, which sometimes works.

**Comment by jgrou** [comment] 2024-01-10 08:22
Thanks. With import warnings, the error message is

`Traceback (most recent call last):

  File ~\AppData\Local\anaconda3\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\jgrou\untitled2.py:21
    surf = ax.plot_surface(X, Y, Z, cmap=cm.coolwarm,

  File ~\AppData\Local\anaconda3\Lib\site-packages\mpl_toolkits\mplot3d\axes3d.py:1688 in plot_surface
    self.auto_scale_xyz(X, Y, Z, had_data)

  File ~\AppData\Local\anaconda3\Lib\site-packages\mpl_toolkits\mplot3d\axes3d.py:617 in auto_scale_xyz
    self.autoscale_view()

  File ~\AppData\Local\anaconda3\Lib\site-packages\mpl_toolkits\mplot3d\axes3d.py:643 in autoscale_view
    self._shared_axes["x"].clean()

  File ~\AppData\Roaming\Python\Python311\site-packages\matplotlib\_api\deprecation.py:199 in wrapper
    emit_warning()

  File ~\AppData\Roaming\Python\Python311\site-packages\matplotlib\_api\deprecation.py:193 in emit_warning
    warn_deprecated(

  File ~\AppData\Roaming\Python\Python311\site-packages\matplotlib\_api\deprecation.py:96 in warn_deprecated
    warn_external(warning, category=MatplotlibDeprecationWarning)

  File ~\AppData\Roaming\Python\Python311\site-packages\matplotlib\_api\__init__.py:381 in warn_external
    warnings.warn(message, category, stacklevel)

MatplotlibDeprecationWarning: The clean function was deprecated in Matplotlib 3.8 and will be removed two minor releases later. Use none, you no longer need to clean a Grouper instead.`

So it does indeed seem there are different paths to matplotlib (Roaming\Python\Python311\site-packages) and mpl_tootkits (Local\anaconda3\Lib\site-packages)

**Comment by scottshambaugh** [comment] 2024-01-11 18:00
I cannot reproduce on v3.8.2 and this does look like a mismatched environment, so going to close this issue as a manifestation of https://github.com/matplotlib/matplotlib/issues/26827.

**Closed by scottshambaugh** 2024-01-11 18:00 UTC
Labels: topic: mplot3d
