### ISSUE TITLE
[Bug]: Some styles trigger pcolormesh grid deprecation

### ISSUE THREAD

**Issue by prisae** [matplotlib/matplotlib#21723] opened 2021-11-23 06:00 UTC
### Bug summary

Calling `plot_surface` followed by `fig.colorbar` results in the following deprecation warning:
```
Auto-removal of grids by pcolor() and pcolormesh() is deprecated since 3.5
and will be removed two minor releases later; please call grid(False) first.
```
However, setting `ax.grid(False)` first does not help, the Warning is still shown.

### Code for reproduction

Edit: As noted further down in the discussion: The warning does not appear for the default style. But if you load, e.g., `plt.style.use('bmh')`, you will see the warning.

```python
# https://matplotlib.org/stable/gallery/mplot3d/surface3d.html

import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator
import numpy as np

plt.style.use('bmh')  # Edit: One of the styles with which you will see the warning

fig, ax = plt.subplots(subplot_kw={"projection": "3d"})

# Make data.
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)

# Plot the surface.
surf = ax.plot_surface(X, Y, Z, cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)

# Customize the z axis.
ax.set_zlim(-1.01, 1.01)
ax.zaxis.set_major_locator(LinearLocator(10))
# A StrMethodFormatter is used automatically
ax.zaxis.set_major_formatter('{x:.02f}')

# Add a color bar which maps values to colors.
fig.colorbar(surf, shrink=0.5, aspect=5)

plt.show()
```

### Actual outcome
```
 MatplotlibDeprecationWarning: Auto-removal of grids by pcolor() and pcolormesh() is deprecated
 since 3.5 and will be removed two minor releases later; please call grid(False) first.
 fig.colorbar(surf, shrink=0.5, aspect=5)
```

### Expected outcome

No Warning or a warning with a fix that works.

### Additional information

Works fine for `matplotlib<3.5`.

### Operating system

Linux

### Matplotlib Version

3.5.0

### Matplotlib Backend

module://ipykernel.pylab.backend_inline

### Python version

3.88

### Jupyter version

6.4.0

### Installation

conda

**Comment by QuLogic** [comment] 2021-11-23 07:57
I cannot reproduce this in a script or in Jupyter Notebook. Maybe you have a custom `matplotlibrc` or style setting?

**Comment by prisae** [comment] 2021-11-23 07:59
Good point, and I tried. By default it indeed does not happen. However, it happens if you use, e.g., `plt.style.use('bmh')` or `plt.style.use('ggplot')`.

**Comment by jklymak** [comment] 2021-11-23 08:28
OK, so this has nothing to do with colorbar explicitly, and the same warning pops up for `pcolromesh` by itself:

```python
import matplotlib.pyplot as plt
import numpy as np
plt.style.use('ggplot')

fig, ax = plt.subplots()
# Make data.
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)

surf = ax.pcolormesh(X, Y, Z)
plt.show()
```

```
MatplotlibDeprecationWarning: Auto-removal of grids by pcolor() and pcolormesh() is deprecated since 3.5 and will be removed two minor releases later; please call grid(False) first.
  surf = ax.pcolormesh(X, Y, Z)
```

This came in in #15604 (@anntzer) In that PR we _stopped_ pcolormesh from removing the grid lines automatically, which was the old behaviour.  

OTOH, I guess I am not clear why we are deprecating this, or if it is even possible to do so cleanly.  Its impossible for pcolormesh to know if the user expects the grids to stay or go.

**Comment by timhoffm** [comment] 2021-11-23 23:45
I'll try to summarize the situation.

### History
Basic conflict:
- depending on style we may or may not have grids on; plus maybe explicitly set by the user.
- pcolormesh with a grid on top is not wanted most of the time.

Before #15604 the canonical resolution is that the mesh trumps the grid and pcolormesh deactivates the grid.
This is what you want in many cases, but not always, e.g. The mesh doesn't fill the whole Axes (#15600 which brought up the topic) or a user could have explicitly activated a grid.

Conceptually, auto-remove-grid through a plotting function is questionable. That's beyond their responsibility.

So #15604 deprecated the behavior.

We can get away with this because it doesn't change appearance for most standard cases:
- All shipped styles with grid use `axes.axisbelow: True` and thus the grid vanishes behind the mesh
- The default style has `axes.axisbelow: line` but no grid

### Problem here
The problem is that these cases still see the (irrelevant) deprecation message.

### Solution
I think we can remove most of the deprecation annoyance by not warning in case of `axes.axisbelow: True`.

**Comment by phollox-arch** [comment] 2021-11-24 09:57
Hello,
I'm not sure if I'm adding to this discussion, but I'm seeing the same warning. I'm importing `seaborn` and calling `sns.set()` and `sns.set_palette('bright')`

**Comment by jklymak** [comment] 2021-11-24 10:02
- I feel it was a misfeature that we ever removed the grid in the first place just for this artists type.
- I don't see a way to sensibly deprecate this since it is not something the user is actively doing.  So we can 
   1. stop the behaviour without deprecation, or
   2. live with it.  

I personally prefer 1 as I consider this a bug, but can understand why some would think this was a feature and would prefer 2.

**Comment by jklymak** [comment] 2021-11-24 10:44
... added to the weekly dev call to discuss, unless we can come to consensus here.

**Comment by prisae** [comment] 2022-01-04 15:03
Was there anything decided in this regard? I see the same problem appearing in `v3.5.1` as well.

**Comment by jklymak** [comment] 2022-01-04 15:14
@prisae No I don't think there was a discussion.  I'll re-add to this weeks call.  Thanks for the ping...

**Comment by pharshalp** [comment] 2022-01-12 17:06
I have tried to address this issue in a PR (faced this issue in my code --> created a PR to fix it --> and then realized that this had been reported here earlier).

**Comment by tacaswell** [comment] 2022-01-12 20:41
I think in the case of _just_ colorbare @pharshalp 's PR is reasonable (if we take the position that colorbars were not meant to have grids under the meaning of the rcParam). 

I agree with @timhoffm and @jklymak that moving to a state where plotting does not mess with the visibility of the grid is the right thing to do, however we left no way for a user who wants to keep the grid to avoid the warning.

I think @timhoffm 's suggestion of not warning when the grid would be fully hidden by the mask is reasonable, but has some edges that are not great (meshes with low alpha values and if the user zooms out to bigger than the mesh).

Another alternative is to add some state (either another rcParam on a module attribute) to suppress this warning, default it to False, and have the warning specify to set it.  This is obviously not great as it adds (yet) more state.

**Comment by jklymak** [comment] 2022-01-12 21:48
My position is still that we should just stop removing the grid, and have an API note that says we have changed this and if you dont' want a grid  to go ahead and toggle the grid.  I'm going to guess that most folks who want a grid, also wanted it when there was a pcolormesh, and toggled it on again when we arbitrarily removed it.

**Comment by tacaswell** [comment] 2022-01-13 21:00
The consensus on the call is to go with option 3 (leave the warning, but only when the grid is above the colormesh).

**Comment by jklymak** [comment] 2022-01-14 06:16
re-open because the above is still not implemented to my knowledge.

**Comment by AzharUddinSheikh** [comment] 2022-01-19 13:22
plt.rcParams['axes.grid'] = False
this stop the warning

**Comment by pllim** [comment] 2022-01-20 03:44
Hello. I think this might be affecting `astropy` too. Please see astropy/astropy#12753 . Thanks!

**Closed** 2022-01-25 07:53 UTC
Labels: API: changes
