### ISSUE TITLE
[Bug]: `matplotlib.axis.get_minorticklocs()` does unnecessary computation with `NullLocator` set for axis

### ISSUE THREAD

**Issue by kwankyu** [matplotlib/matplotlib#24557] opened 2022-11-28 02:24 UTC
### Bug summary

SageMath project uses matplotlib for graphics. We are recently upgrading matplotlib to version 3.6. In this effort, we encountered a failure in this command:
```python
plot(2*x+1,(x,0,5), ticks=[[0,1,e,pi,sqrt(20)],2], tick_formatter="latex")
```
Here we use symbolic constants e, pi, sqrt(20) as major x-axis tick values. This worked very well up to now. But matplotlib version 3.6 fails this. I investigated the ultimate source of this failure. 

We set the major tick locator as `FixedLocator` with the above symbolic values, and the minor tick locator to `NullLocator`. When matplotlib renders the plot, it tries to update minor tick values and calls `matplotlib.axis.get_minorticklocs()`, which is
```python
    def get_minorticklocs(self):
        """Return this Axis' minor tick locations in data coordinates."""
        # Remove minor ticks duplicating major ticks.
        minor_locs = np.asarray(self.minor.locator())
        if self.remove_overlapping_locs:
            major_locs = self.major.locator()
            transform = self._scale.get_transform()
            tr_minor_locs = transform.transform(minor_locs)
            tr_major_locs = transform.transform(major_locs)
            lo, hi = sorted(transform.transform(self.get_view_interval()))
            # Use the transformed view limits as scale.  1e-5 is the default
            # rtol for np.isclose.
            tol = (hi - lo) * 1e-5
            mask = np.isclose(tr_minor_locs[:, None], tr_major_locs[None, :],
                              atol=tol, rtol=0).any(axis=1)
            minor_locs = minor_locs[~mask]
        return minor_locs  
```
Note that `tr_minor_locs` is an empty numpy array and `tr_major_locs` contains our symbolic values. The line `mask = np.isclose(...)` raises an exception because it does not understand the symbolic values. This behavior is new due to code changes in `get_minorticklocs()` in matplotlib 3.6. 

Note that as the minor tick locator is `NullLocator`, that is, empty. `get_minorticklocs()` has nothing to do here. So by this change
```diff
---    if self.remove_overlapping_locs:
+++    if len(minor_locs) and and self.remove_overlapping_locs:
```
matplotlib can save unnecessary computation, and our problem in SageMath will be solved. So please consider this.

### Code for reproduction

```python
Explained in Bug summary
```

### Actual outcome

Explained in Bug summary

### Expected outcome

Explained in Bug summary

### Matplotlib Version

3.6

**Comment by rcomer** [comment] 2022-11-28 09:14
Thanks for this report @kwankyu, and for your effort in diagnosing the problem.  Could you provide a complete minimal code example that reproduces the error but works with the previous matplotlib version?

**Comment by kwankyu** [comment] 2022-11-28 13:02
That is tricky since we need symbolic values like those in SageMath. Anyway I could come up with the following
```python
class Symbolic(object):
    def __init__(self, a, b):
        self.num = a
        self.den = b
        
    def __str__(self):
        return '{}/{}'.format(self.num, self.den)
        
    def __float__(self):
        return self.num / self.den
    
    def __le__(self, other):
        return float(self) <= other
    
    def __ge__(self, other):
        return float(self) >= other   
    
    def __abs__(self):
        return abs(float(self))
    
    def __add__(self, other):
        return float(self) + other   
    
    def __neg__(self):
        return -float(self)
    
    def __sub__(self, other):
        return float(self) - other
    
    def __round__(self):
        return int(float(self))     

    
import matplotlib.pyplot as plt
import numpy as np
import sympy as sym
from matplotlib.ticker import FixedLocator, NullLocator, FuncFormatter

# make data
x = np.linspace(0, 3, 100)
y = 2 * x + 1

# plot
fig, ax = plt.subplots()

ax.plot(x, y, linewidth=2.0)

a = Symbolic(1,2)

ax.xaxis.set_major_locator(FixedLocator([1, a, 2, 3]))
ax.xaxis.set_minor_locator(NullLocator())
ax.xaxis.set_major_formatter(FuncFormatter(lambda x, pos: str(x)))

plt.show()
```
which shows with matplotlib 3.5.3
![Figure](https://user-images.githubusercontent.com/1456101/204283430-27f8c0f0-13d0-425b-be08-e2bc0addd70a.png)
but fails with mathplotlib 3.6.2
{{{
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 1193, in _on_timer
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/backends/backend_macosx.py", line 68, in callback_func
    callback()
  File "/usr/local/lib/python3.10/site-packages/matplotlib/backends/backend_macosx.py", line 88, in _draw_idle
    self.draw()
  File "/usr/local/lib/python3.10/site-packages/matplotlib/backends/backend_macosx.py", line 50, in draw
    super().draw()
  File "/usr/local/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 405, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/figure.py", line 3071, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.10/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3107, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.10/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axis.py", line 1304, in draw
    ticks_to_draw = self._update_ticks()
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axis.py", line 1198, in _update_ticks
    minor_locs = self.get_minorticklocs()
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axis.py", line 1431, in get_minorticklocs
    mask = np.isclose(tr_minor_locs[:, None], tr_major_locs[None, :],
  File "<__array_function__ internals>", line 180, in isclose
  File "/usr/local/lib/python3.10/site-packages/numpy/core/numeric.py", line 2373, in isclose
    yfin = isfinite(y)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
}}}

**Comment by tacaswell** [comment] 2022-11-28 15:03
Putting in the check that the length is zero just patches over this the issue and kicks he can down the road to someone who wants to use minor ticks with the symbolic values.

At the risk of playing hot-potatoe, why isn't


```python
import numpy as np

class Symbolic(object):
    def __init__(self, a, b):
        self.num = a
        self.den = b
        
    def __str__(self):
        return '{}/{}'.format(self.num, self.den)
        
    def __float__(self):
        return self.num / self.den
    
    def __le__(self, other):
        return float(self) <= other
    
    def __ge__(self, other):
        return float(self) >= other   
    
    def __abs__(self):
        return abs(float(self))
    
    def __add__(self, other):
        return float(self) + other   
    
    def __neg__(self):
        return -float(self)
    
    def __sub__(self, other):
        return float(self) - other
    
    def __round__(self):
        return int(float(self))     

np.isclose([1, Symbolic(1, 2), 5], [1, 0.5, 5])    
```

failing with

```
TypeError                                 Traceback (most recent call last)
Cell In [48], line 1
----> 1 np.isclose([1, Symbolic(1, 2), 5], [1, 0.5, 5])    

File <__array_function__ internals>:200, in isclose(*args, **kwargs)

File ~/.virtualenvs/bleeding/lib/python3.12/site-packages/numpy/core/numeric.py:2377, in isclose(a, b, rtol, atol, equal_nan)
   2374     dt = multiarray.result_type(y, 1.)
   2375     y = asanyarray(y, dtype=dt)
-> 2377 xfin = isfinite(x)
   2378 yfin = isfinite(y)
   2379 if all(xfin) and all(yfin):

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

a bug in SageMath / numpy? 

```
In [49]: np.isclose(np.array([1, Symbolic(1, 2), 5], dtype=float), [1, 0.5, 5])    
Out[49]: array([ True,  True,  True])

```

works, so there is just something wrong with the case where numpy uses an object dtype.


As a general rule, we try to avoid explicit casts numpy + float, but this may be one of the cases where that makes sense.

attn @ksunden for another case that touches on units / non-standard input types.

------

I think:
 1. the proposed fix may be a minor performance improvement that we might want to do anyway, but is not a fix for this bug
 2. we should explicitly past to float before calling isclose if this can not be fixed upstream

**Comment by kwankyu** [comment] 2022-11-28 22:45
> I think:
> 
> 1. the proposed fix may be a minor performance improvement that we might want to do anyway, but is not a fix for this bug
> 2. we should explicitly past to float before calling isclose if this can not be fixed upstream

On SageMath side, 
```python
sage: sqrt(2)
sqrt(2)
sage: np.isfinite(sqrt(2))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [12], line 1
----> 1 np.isfinite(sqrt(Integer(2)))

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
sage: type(sqrt(2))
<class 'sage.symbolic.expression.Expression'>
sage: np.can_cast(type(sqrt(2)), float, 'safe')
False
sage: float(sqrt(2))
1.4142135623730951
```
SageMath's `Expression` class implements symbolic values that represents float or complex values. Therefore it seems reasonable that numpy gives `False` for the possibility of safely casting `Expression` to `float ` type. 

So it seems we cannot solve the problem on SageMath side. Please consider implementing the proposed fix 1 or 2.

**Comment by jklymak** [comment] 2022-11-28 23:44
That this used to work seems fortuitous to me, rather than by design.  Is I possible for sagemath to provide a `.__array__` method to convert to numpy arrays?  Are there other instances where we allow object arrays for tick locations?  It seems hard for us to have arbitrary information in a tick location array rather than being allowed to assume it is made up of floats.

Sagemath could also add a unit conversion interface, and then they can assign their own tickers and formatters to their own objects.

**Comment by tacaswell** [comment] 2022-11-28 23:44
Can you add `isfinite` support to `Expression` (or a `ConstExpression` which may or may not already exist)? It seems to me that being able to ask if an expression is finite is something you should be able to ask.

In this case you want to pass `Expression` objects mixed in with `float` objects.  Previously we only touched a sub-set of the "float-like" API and now we are touching a bigger part of that API.  However, I still think that this is a bug in SageMath (that these objects are not enough number-like) not a regression in Matplotlib.

**Comment by kwankyu** [comment] 2022-11-29 00:47
Okay.  I will report your opinions to SageMath and we will think about a way to make `Expression` (or a subset of which) behave more `float`-like.  Thanks for the discussion!

**Comment by kwankyu** [comment] 2022-11-29 20:19
I managed to make `Symbolic` more float-like palatable to numpy:
```python
class Symbolic(object):
    __array_interface__ = {'typestr': 'f'} 
    
    def __init__(self, a, b):
        self.num = a
        self.den = b
        
    def __str__(self):
        return '{}/{}'.format(self.num, self.den)
        
    def __float__(self):
        return float(self.num / self.den)
    
import matplotlib.pyplot as plt
import numpy as np
import sympy as sym
from matplotlib.ticker import FixedLocator, NullLocator, FuncFormatter

# make data
x = np.linspace(0, 3, 100)
y = 2 * x + 1

# plot
fig, ax = plt.subplots()

ax.plot(x, y, linewidth=2.0)

a = Symbolic(1,2)

ax.xaxis.set_major_locator(FixedLocator([a, 1, 2, 3]))
ax.xaxis.set_minor_locator(NullLocator())
ax.xaxis.set_major_format ter(FuncFormatter(lambda x, pos: str(x)))

plt.show()
```
But the plot shows `0.5` instead of `1/2`. So it seems the symbolic value is simply converted to a float and matplotlib renders the float value. Would it be possible for the formatter to be fed the original symbolic value instead of the converted float value?

**Comment by jklymak** [comment] 2022-11-29 20:50
You could use a FixedFormatter?  Our tick locations are floats in the axes' data co-ordinate system.

**Comment by kwankyu** [comment] 2022-11-29 21:29
Yes! it seem we could reimplement tick formatter to cope with symbolic values using `FixedFormatter`. Thanks!

**Comment by jklymak** [comment] 2023-03-25 15:26
I think this was closed downstream?

**Closed by jklymak** 2023-03-25 15:26 UTC
Labels: status: upstream fix required, status: needs clarification

**Comment by kwankyu** [comment] 2023-03-26 02:36
Yes.
