### ISSUE TITLE
matplotlib.pyplot.imshow does not work as expected

### ISSUE THREAD

**Issue by Kulbear** [matplotlib/matplotlib#11319] opened 2018-05-27 04:42 UTC
### Bug report

**Bug summary**

matplotlib.pyplot.imshow does not work as expected.

**Actual outcome**

You can see I actually add 4 times mean (which is 24 for this image), and there is nothing changed.

![image](https://user-images.githubusercontent.com/14886380/40582479-4aac01aa-6135-11e8-85cc-82d28f56bdff.png)

**Expected outcome**

After uncommenting the line I assigned one pixel to value 0. It changed to:

![image](https://user-images.githubusercontent.com/14886380/40582498-a76a8056-6135-11e8-9c0f-0d4aae8494c4.png)

**Matplotlib version**

  * Operating system: Window 10
  * Matplotlib version: 2.2.2
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.6.5
  * Jupyter version (if applicable): jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.32.1
jupyterlab-launcher==0.10.5

pip

**Comment by QuLogic** [comment] 2018-05-27 06:31
You are passing a 2D array (MxN), which gets colour mapped. The default normalization for the mapping is the data limits, so if you add a constant to all elements, the result will not change. If you want the change to be visible, then you should specify some limits for the normalization with `vmin` and/or `vmax`.

Closing as this is not a bug.

**Closed by QuLogic** 2018-05-27 06:31 UTC

**Comment by tacaswell** [comment] 2018-05-27 15:41
@Kulbear  is https://matplotlib.org/tutorials/colors/colormapnorms.html useful for understanding the behavior?

**Comment by Kulbear** [comment] 2018-05-28 06:44
@tacaswell @QuLogic Thanks the documentation is helpful.
