### ISSUE TITLE
plt.plot(...) makes python repl in cmd slow

### ISSUE THREAD

**Issue by jankatins** [matplotlib/matplotlib#5159] opened 2015-09-30 14:00 UTC
When producing a small plot in the console, the console becomes very sluggish afterwards:

```
λ python
Python 2.7.10 |Continuum Analytics, Inc.| (default, Sep 15 2015, 14:26:14) [MSC v.1500 64 bit (AMD64)] on win32

Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import matplotlib.pyplot as plt
>>> plt.plot([1,2,3], marker="o")
[<matplotlib.lines.Line2D object at 0x0000000008DB60B8>]

# from here on it's sluggish until I exit -> typing shows the next character
# with a noteable delay and c&p is kind of "typing" the text instead of 
# almost instantly there

>>> plt.show()
```

This a clean new conda env py2.7 (`conda create -n mew_test python matplotlib seaborn ipython`) on windows7, 64bit. I also have cmder installed, but it also happens in the default cmd console

**Comment by WeatherGod** [comment] 2015-09-30 14:26
Which version of matplotlib and which backend (I don't know what the
defaults are for Windows from anaconda).

**Comment by JanSchulz** [comment] 2015-09-30 17:25
```
>>> matplotlib.__version__
'1.4.3'
>>> matplotlib.get_backend()
u'Qt4Agg'
```

**Comment by JanSchulz** [comment] 2015-09-30 17:32
Using `Agg` as a backend does not have this problem (no sluggish typing after `plt.plot()`), but on the other hand I also do not get a plot shown after `plt.show()` . Not sure how to get a plot window with that backend?

```
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt 
plt.plot([1,2,3])
#not sluggish afterwards :-)
plt.show() # does not bring up the plotting window :-(
```

(It seems that I never really learned how to use matplotlib in another environement than the ipython notebook...)

**Comment by tacaswell** [comment] 2015-09-30 21:06
Do you have the same issue from just importing pyqt?  iirc, there are some issues with the os inputhook + windows. 

Do you have the same issue if you use ipython and do a

```
%matplotlib qt
```
?

**Comment by JanSchulz** [comment] 2015-10-01 10:08
I've run `from PyQt4 import QtGui` and didn't notice a slowdown afterwards. Running `%matplotlib qt` in an `ipython` console (not qt, not notebook!) also didn't change anything.

**Comment by WeatherGod** [comment] 2015-10-01 13:22
when you say "also didn't change anything", do you mean that it is slow
just like at the repl, or that it is normal speed, just like using Qt4
normally?

**Comment by JanSchulz** [comment] 2015-10-01 13:43
It's normal, e.g. typing is shown instantly and c&p as well.

**Comment by tacaswell** [comment] 2015-10-01 16:44
I would just use the IPython shell then :wink:.  It takes care of many of the annoying details about setting up interactive mode and managing the gui event loop.

I can't reproduce this on a linux box.

**Comment by JanSchulz** [comment] 2015-10-01 21:14
It happens in both `python` and `ipython`. Unfortunately I currently don't have access to a different windows box, to test if it's specific to my box or to windows. :-(

**Comment by efiring** [comment] 2015-10-01 22:03
Is the tkagg backend available? E.g. in ipython, `%matplotlib tk`. 
I suspect your problem with qt involves a library conflict with something else installed on your machine.  If it were a universal problem with Anaconda python 2.7 on Windows, I think Continuum would have been deluged with complaints by now, and I don't think I have seen this one on the anaconda mailing list.

**Comment by Tillsten** [comment] 2015-10-02 14:02
Can confirm the behavior with qt, but i think this a really old bug, which never got fixed. Something with way readline is used.

**Comment by Tillsten** [comment] 2015-10-02 14:05
I also remember that using ipython would we the fix, but this is not the case. Note that figure doesent have to be show, the slowdown happens after calling  `plot`.

**Comment by tacaswell** [comment] 2015-10-02 20:10
Is this an old mpl bug or an old pyqt bug?

Does this happen on master branch/with the rc (which has a windows conda
build on the conda-forge channel).

**Comment by Tillsten** [comment] 2015-10-02 20:48
The mpl policies was always that if you want have interactive plots in the repl working without any haggle one has to use ipython. This is still true, as long either %gui or %matplotlib is called. As long all the input-hook experience is in the ipython team it is properly the best way, even if having the code directly in mpl would be also nice.

**Comment by JanSchulz** [comment] 2015-10-04 12:20
Ok, I tested it with `%matplotlib tk` and it doesn't become sluggish. I will create a new test env for the newer matplotlib version and then see what happens there...

**Comment by JanSchulz** [comment] 2015-10-04 12:23
BTW: there seems to be no win-64bit matplotlib on conda-forge: https://conda.binstar.org/conda-forge/win-64

**Comment by JanSchulz** [comment] 2015-10-04 12:42
Ok, it's still sluggish on latest matplotlib from git:

```
>>> import matplotlib
>>> matplotlib.__version__
'1.5.0rc2.post7+gdcc3a42'
>>> import matplotlib.pyplot as plt
>>> plt.plot([1,2,3,4])
[<matplotlib.lines.Line2D object at 0x0000000009106B70>]
```

```
λ conda env export                                        
name: dev_27                                              
dependencies:                                             
- certifi=14.05.14=py27_0                                 
- decorator=4.0.2=py27_0                                  
- freetype=2.4.10=0                                       
- funcsigs=0.4=py27_0                                     
- ipykernel=4.0.3=py27_0                                  
- ipython=4.0.0=py27_0                                    
- ipython_genutils=0.1.0=py27_0                           
- ipywidgets=4.0.2=py27_0                                 
- jinja2=2.8=py27_0                                       
- jsonschema=2.4.0=py27_0                                 
- jupyter=1.0.0=py27_0                                    
- jupyter_client=4.0.0=py27_0                             
- jupyter_console=4.0.1=py27_0                            
- jupyter_core=4.0.4=py27_0                               
- libpng=1.6.17=0                                         
- markupsafe=0.23=py27_0                                  
- mistune=0.7.1=py27_0                                    
- mock=1.3.0=py27_0                                       
- nbconvert=4.0.0=py27_0                                  
- nbformat=4.0.0=py27_0                                   
- nose=1.3.7=py27_0                                       
- notebook=4.0.4=py27_0                                   
- numpy=1.9.2=py27_0                                      
- pandas=0.16.2=np19py27_0                                
- path.py=7.6=py27_0                                      
- pbr=1.3.0=py27_0                                        
- pickleshare=0.5=py27_0                                  
- pillow=2.9.0=py27_0                                     
- pip=7.1.2=py27_0                                        
- pygments=2.0.2=py27_0                                   
- pyparsing=2.0.3=py27_0                                  
- pyqt=4.10.4=py27_1                                      
- pyreadline=2.1=py27_0                                   
- python=2.7.10=1                                         
- python-dateutil=2.4.2=py27_0                            
- pytz=2015.4=py27_0                                      
- pyzmq=14.7.0=py27_0                                     
- qtconsole=4.0.1=py27_0                                  
- requests=2.4.0=py27_0                                   
- setuptools=18.3.2=py27_0                                
- simplegeneric=0.8.1=py27_0                              
- six=1.9.0=py27_0                                        
- ssl_match_hostname=3.4.0.2=py27_0                       
- tornado=4.2.1=py27_0                                    
- traitlets=4.0.0=py27_0                                  
- wheel=0.26.0=py27_1                                     
- zlib=1.2.8=0                                            
- pip:                                                    
  - backports.ssl-match-hostname==3.4.0.2                 
  - cycler==0.9.0                                         
  - dnslib==0.9.3                                         
  - ipython-genutils==0.1.0                               
  - jupyter-client==4.0.0                                 
  - jupyter-console==4.0.1                                
  - jupyter-core==4.0.4                                   
  - leapcast (c:\data\external\leapcast)==2.0.0           
  - matplotlib==1.5.0rc2+7.gdcc3a42                       
```

I also tried with a new

**Comment by JanSchulz** [comment] 2015-10-04 12:59
Another observation: 
* before `plt.plot()`, I can paste long lines (2k words of lorem ipsum), but the python interpreter goes to 100% CPU (on one core) and it takes a while to paste the complete line (but not as slow as with plot)... 
* after `plt.plot()`, I can't paste long lines anymore: the interpreter has no CPU, but only 4 chars are shown (=hang?). I have to kill the interpreter (via proc explorer) to get the rest of the chars displayed (in cmd!). Shorter texts can be pasted (I tried with 230 chars), it's much slower as without the plot call but the interpreter (and cmd/...) does not use much CPU (~1% of one core).

**Comment by Tillsten** [comment] 2015-10-04 13:22
You need to use Ipython and call `%matplotlib your_backend` to get non sluggish behaviour. Else the eventloop and pythons inputhook won't play nice with each other.

**Comment by JanSchulz** [comment] 2015-10-04 13:36
Using `%gui qt` in ipython before the `plt.plot()` prevents the sluggishness (=c&p is fast afterwards). Even calling this after `plt.plot()` (and observing sluggish behaviour) is restoring the the c&p behaviour.

So what this means is that using matplotlib in interactive mode on windows will result in sluggish behaviour unless setting the backend to something else than qt4 or using ipython and `%gui qt`?

**Comment by Tillsten** [comment] 2015-10-04 13:48
Yeah, but please note that it is not maplotlibs fault, try:

    from PyQt4 import QtGui
    app = QtGui.QApplication([])

and you will see the same behaviour. IPython jumps through some hoops to circumvent that. Note that `QtCore.pyqtRemoveInputHook()` fixes the sluggishness, but i don't know the downsides of it.

**Comment by JanSchulz** [comment] 2015-10-04 14:21
With your code snippets I found https://github.com/ipython/ipython/issues/481 and https://github.com/ipython/ipython/pull/815 which seem to implement the workarounds which make this work...

Not sure if there is any actionable item here, if matplotlib doesn't want to implement the same workaround as IPython. I think the only thing which makes sense is a warning ala "Use ipython and `%gui qt`" on import if  `_interactive and _onwindows and backend=="QT4Agg" and ("ipython inputhook not present" or "not in ipython")`...

**Comment by Tillsten** [comment] 2015-10-04 15:40
I personally would be fine with calling `QtCore.pyqtRemoveInputHook()` and emitting a warning that the inputhook has been removed. Of course only under windows if the problem is only there.

**Comment by tacaswell** [comment] 2015-10-04 16:48
The downside of removing the inputhook is that figures will no longer be 'live' unless you explicitly start the event loop (ex via `plt.pause()`).

**Comment by jorisvandenbossche** [comment] 2015-10-05 08:18
FWIW, I also experienced this behaviour for some time on Windows with IPython (also using conda). Normally I use `%matplotlib` to enable interactivity, but when I forget to type that and already do a plot, the terminal indeed becomes unusable slow

**Comment by tomderuijter** [comment] 2015-11-17 15:56
I can also confirm this issue. Using Anaconda 2.3.0 with matplotlib 1.4.3 and Python 3.4.3.

**Comment by nplanel** [comment] 2016-08-18 10:43
same issue on a fresh Ubuntu 14.04 LTS uptodate and in an virtualenv (may not related)
Installed via pip

To reproduce it :
```
sudo apt-get update
sudo apt-get install python-pip python-dev python-virtualenv
virtualenv --system-site-packages ~/myenv
pip install matplotlib
python
import numpy             as np
import matplotlib.pyplot as plt
... the REPL is very slow now
```

**Comment by efiring** [comment] 2019-05-23 02:57
Closing, but if the problem is still occurring please reopen.

**Closed by efiring** 2019-05-23 02:57 UTC
Labels: GUI/Qt, OS/Microsoft
