### ISSUE TITLE
Incorrect heatmap display

### ISSUE THREAD

**Issue by aldenleung** [matplotlib/matplotlib#14731] opened 2019-07-09 23:07 UTC
### Bug report

**Bug summary**

The heatmap is now clipped improperly using imshow. The code works properly in 3.1.0 but not in 3.1.1. The bug could be easily reproduced using the categorical heatmap example on:
https://matplotlib.org/gallery/images_contours_and_fields/image_annotated_heatmap.html
Note that the image of the example on the website is also clipped. 

See the same page in 3.1.0 as a comparison.
https://matplotlib.org/3.1.0/gallery/images_contours_and_fields/image_annotated_heatmap.html

**Code for reproduction**

```python
# Paste your code here
#
#
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# sphinx_gallery_thumbnail_number = 2

vegetables = ["cucumber", "tomato", "lettuce", "asparagus",
              "potato", "wheat", "barley"]
farmers = ["Farmer Joe", "Upland Bros.", "Smith Gardening",
           "Agrifun", "Organiculture", "BioGoods Ltd.", "Cornylee Corp."]

harvest = np.array([[0.8, 2.4, 2.5, 3.9, 0.0, 4.0, 0.0],
                    [2.4, 0.0, 4.0, 1.0, 2.7, 0.0, 0.0],
                    [1.1, 2.4, 0.8, 4.3, 1.9, 4.4, 0.0],
                    [0.6, 0.0, 0.3, 0.0, 3.1, 0.0, 0.0],
                    [0.7, 1.7, 0.6, 2.6, 2.2, 6.2, 0.0],
                    [1.3, 1.2, 0.0, 0.0, 0.0, 3.2, 5.1],
                    [0.1, 2.0, 0.0, 1.4, 0.0, 1.9, 6.3]])


fig, ax = plt.subplots()
im = ax.imshow(harvest)

# We want to show all ticks...
ax.set_xticks(np.arange(len(farmers)))
ax.set_yticks(np.arange(len(vegetables)))
# ... and label them with the respective list entries
ax.set_xticklabels(farmers)
ax.set_yticklabels(vegetables)

# Rotate the tick labels and set their alignment.
plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
         rotation_mode="anchor")

# Loop over data dimensions and create text annotations.
for i in range(len(vegetables)):
    for j in range(len(farmers)):
        text = ax.text(j, i, harvest[i, j],
                       ha="center", va="center", color="w")

ax.set_title("Harvest of local farmers (in tons/year)")
fig.tight_layout()
plt.show()

```

**Actual outcome**
![image](https://user-images.githubusercontent.com/16772289/60928646-32985800-a27c-11e9-93f2-b3941e9bc992.png)

**Matplotlib version**

  * Matplotlib version:  3.1.1
  * Python version: 3.6.8

**Comment by ImportanceOfBeingErnest** [comment] 2019-07-10 00:04
Indeed, that is a very unfortunate bug that got into 3.1.1. Thanks for the notification. 

This has also been tracked in https://github.com/matplotlib/matplotlib/issues/14675 and fixed in https://github.com/matplotlib/matplotlib/pull/14677, which means it will be part of the next bugfix release 3.1.2. 

I'm going to close this as being a duplicate of #14675. 

For now, as a workaround you can probably set the limits of the axes manually. In the case of the example it would be

    ax.set_ylim(len(harvest)-0.5, -0.5)

**Closed by ImportanceOfBeingErnest** 2019-07-10 00:04 UTC
