### ISSUE TITLE
colorbar _ticker +_locate bug

### ISSUE THREAD

**Issue by DeadParrot** [matplotlib/matplotlib#6109] opened 2016-03-05 04:33 UTC
The addition of this code block to `ColorbarBase._ticker` in matplotlib 1.5.x:
```python
        if isinstance(locator, ticker.LogLocator):
            eps = 1e-10
            b = b[(b <= intv[1] * (1 + eps)) & (b >= intv[0] * (1 - eps))]
        else:
            eps = (intv[1] - intv[0]) * 1e-10
            b = b[(b <= intv[1] + eps) & (b >= intv[0] - eps)]
```
can cause a numpy array scalar to be passed to `ColorbarBase._locate` but when that happens the `np.searchsorted` call in `_locate` returns an `numpy.int64` scalar, which causes the indexing operations:
```python
        i0[itop] -= 1
        ii[itop] -= 1
        i0[ibot] += 1
        ii[ibot] += 1
```
to generate the exception: 'numpy.int64' object does not support item assignment.

My quick and dirty patch for this was to add this line before the `np.searchsorted` call in `_locate`:
```python
        if np.ndim(xn) == 0: xn = np.array([xn[()]])
```
I don't propose this as a formal patch since it may not be the most efficient fix and this issue may be broader than what I am seeing.

Specs:
* Windows 10 64-bit
* Python 2.7.11 64-bit (python.org installer)
* matplotlib 1.5.1 (pip install)
* Regression: OK in 1.4.3

**Comment by tacaswell** [comment] 2016-03-05 16:24
I do not understand how that code generates a scalar, what version of numpy are you using?

```python
In [79]: tt = np.arange(5)

In [80]: tt[(tt <= 2.5) & (tt >= 3.5)]
Out[80]: array([], dtype=int64)

In [81]: tt[(tt <= 3.5) & (tt >= 2.5)]
Out[81]: array([3])

In [82]: tt[(tt <= 3.5) & (tt >= 2.5)].shape
Out[82]: (1,)
```

In anycase, the fix should go right after that block in `_ticker` to ensure that `b` is always an array.

**Comment by DeadParrot** [comment] 2016-03-05 18:12
Well, it looks like due to a probable bug in the code I'm working on the `ticks` are passed in as an array of strings. This can lead to a scalar:
```python
>>> b = np.array(['5.55E+02', '7.57E+02', '9.59E+02', '1.16E+03', '1.36E+03'])
>>> b[(b<=1566) & (b>=554)]
'5.55E+02'
```
I leave it to you whether the ColorbarBase code should detect/protect against such mis-usage.

**Comment by tacaswell** [comment] 2016-03-05 19:53
On python3 this results in an exception:

```pytb
In [84]: b = np.array(['5.55E+02', '7.57E+02', '9.59E+02', '1.16E+03', '1.36E+03'])

In [85]: b[(b<=1566) & (b>=554)]

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-85-634bf1e29748> in <module>()
----> 1 b[(b<=1566) & (b>=554)]

TypeError: unorderable types: numpy.ndarray() <= int()

```

**Comment by tacaswell** [comment] 2016-03-05 19:54
What version of numpy are you using?

**Comment by DeadParrot** [comment] 2016-03-05 20:16
NumPy 1.10.4 (latest) from http://www.lfd.uci.edu/~gohlke/pythonlibs/ (built with MKL)

**Comment by tacaswell** [comment] 2016-03-05 21:07
Ah, ok, I can reproduce this now with py2.7.11 + np1.10.4

```python
In [6]: b = np.array(['5.55E+02', '7.57E+02', '9.59E+02', '1.16E+03', '1.36E+03'])

In [7]: b[(b<=1566) & (b>=554)]
/tmp/np_test/bin/ipython:1: DeprecationWarning: unorderable dtypes; returning scalar but in the future this will be an error
  #!/tmp/np_test/bin/python
/tmp/np_test/bin/ipython:1: DeprecationWarning: using a boolean instead of an integer will result in an error in the future
  #!/tmp/np_test/bin/python
Out[7]: '5.55E+02'

In [8]: tt[True]
/tmp/np_test/bin/ipython:1: DeprecationWarning: using a boolean instead of an integer will result in an error in the future
  #!/tmp/np_test/bin/python
Out[8]: 1
```

What locator are you using?  It looks like internally `b = np.array(self.locator())` and calling a `Locator` instance should return an array (or at least a list) of numbers.  That is probably where the bug should be fixed.

**Comment by DeadParrot** [comment] 2016-03-05 21:34
The locator was holding an array of strings because the call to `canvas.figure.colorbar` from our application code was passing an array of strings to the `ticks` argument. I doubt that is a legal API use it just happened to not cause a visible problem with matplotlib 1.4.3 and earlier. I'm not sure how the matplotlib code should deal with this but it would be nice if it at least detected the bogus `ticks` argument.

**Comment by tacaswell** [comment] 2016-05-16 20:08
Closing this with no action because in python3 this will raise an exception due to unordarable types. 

In python2 this is operating on memory id comparison so I am not sure how this was working at all.

**Closed by tacaswell** 2016-05-16 20:08 UTC
