### ISSUE TITLE
Misplaced shadows when using FilteredArtistList

### ISSUE THREAD

**Issue by shendric** [matplotlib/matplotlib#5960] opened 2016-02-02 16:20 UTC
Hi, 

I use the Gaussian Filter example from the [demo_agg_filter.py ](http://matplotlib.org/1.5.1/examples/pylab_examples/demo_agg_filter.html) to place a gaussian drop shadow under continents using basemap. Since I switched to matplotlib 1.5, the shadows are misplaced.

The same effect can be seen on the example that is currently online, therefore I do not present my code here. 

![demo_agg_filter](https://cloud.githubusercontent.com/assets/10025761/12755658/a353b14e-c9d0-11e5-9fec-397437f46fcd.png)

Any suggestions on a quick & dirty solution would be very welcome. 
Thank you

**Comment by jenshnielsen** [comment] 2016-02-02 18:28
It looks like there are several issues seperate issues here. The first broken commit which only relates to the changes in the color of the pie chart was 0db6341ca220878f925df8b0fe230f81954766e9 according to my bisect which I'm not absolutely sure why is.

**Comment by mdboom** [comment] 2016-02-02 18:41
This looks like an image y-flipping problem to me.

This doesn't help the 1.5.x branch, but for information #5718 fixes this issue and incorporates some of `demo_agg_filter.py` as a test.

**Comment by jenshnielsen** [comment] 2016-02-02 21:16
On #5718 it looks like this:
![demoaggfilter](https://cloud.githubusercontent.com/assets/548266/12764502/1263d840-c9f2-11e5-92bf-62e4b005f17d.png)

so that seems to fix every thing but the pie chart issue in introduced in 0db6341

**Comment by jenshnielsen** [comment] 2016-02-02 22:22
The change in 0db6341 is caused by fraction now being passed on from `shade_rgb` to `hillshading` previously it was ignored. Setting it to `1` which is the default value in `hillshading` restores the original behaviour together with #5718

**Comment by tacaswell** [comment] 2016-02-05 21:36
Interestingly, the example is broken in _different ways_ between 1.5.0 and 1.5.1.

1.5.0:

![image](https://cloud.githubusercontent.com/assets/199813/12859796/996ba544-cc26-11e5-84b8-8c082c9526e4.png)

**Comment by efiring** [comment] 2016-05-11 22:11
It is still broken in 1.5.x (not surprisingly) so we need to reach a decision soon: sink time into fixing it, or declare it as "won't fix".

**Comment by tacaswell** [comment] 2016-05-11 22:14
If this works on master i am in favor of won't fix.  I assume this is just
a flipped buffer some place so quick if we can find it.

**Comment by tacaswell** [comment] 2016-05-12 00:07
Just to confirm: http://matplotlib.org/devdocs/examples/pylab_examples/demo_agg_filter.html this works on master/v2.x

**Comment by tacaswell** [comment] 2016-05-28 02:21
Closing as 'wont fix' because this will be fixed in the 2.x release and there will be now further 1.5.x.  Sorry for the trouble :disappointed:

**Closed by tacaswell** 2016-05-28 02:21 UTC
Labels: not a blocker
