### ISSUE TITLE
imshow with interpolation='none': PDF contains two pixmaps

### ISSUE THREAD

**Issue by grothesque** [matplotlib/matplotlib#10925] opened 2018-03-30 21:35 UTC
### Bug report

**Bug summary**

The function `matplotlib.pyplot.imshow`, when used with `interpolation='none'`, leads to a PDF file that shows a pixmap that corresponds exactly (pixel-by-pixel) to the array that was plotted.  The PDF file also contains a second (unused it seems) pixmap that corresponds to what would have been created by `interpolation='nearest'`.

**Code for reproduction**

```python
import numpy as np
from matplotlib import pyplot

s = np.linspace(0, 1, 3).reshape((-1, 1))
a = s**2 + s.T**2

pyplot.imshow(a)
pyplot.savefig('default.pdf')

pyplot.imshow(a, interpolation='none')
pyplot.savefig('none.pdf')
```

**Actual outcome**

This creates two files, where `none.pdf` is notably somewhat larger than `default.pdf`:

```
$ ls -l *.pdf
-rw-rw-r-- 1 cwg cwg   6628 Mar 30 23:20  default.pdf
-rw-rw-r-- 1 cwg cwg   6982 Mar 30 23:20  none.pdf
```

The reason is that `none.pdf` (in contrast to `default.pdf`) contains *two* embedded pixmaps:

```
$ pdfimages none.pdf none
$ file *.ppm
none-000.ppm: Netpbm image data, size = 370 x 370, rawbits, pixmap
none-001.ppm: Netpbm image data, size = 3 x 3, rawbits, pixmap
```

It is the small pixmap that is visible when viewing the PDF file.  I verified this by editing the raw PDF file and displaying it.  The large pixmap does not seem to have any use.

**Expected outcome**

I remember that several years ago, equivalent code would produce a smaller PDF file without the large, apparently unused, pixmap.  It seems to me that this behavior should be restored.  Or am I overseeing anything here?

**Matplotlib version**

  * Operating system: Debian GNU/Linux "testing"
  * Matplotlib version: 2.1.1
  * Python version: 3.6

Python and Matplotlib have been installed from official Debian packages.

**Comment by QuLogic** [comment] 2018-03-30 22:08
You are using the stateful interface, i.e., `pyplot.imshow` plots to the current figure. Saving the figure does not close it, so the second call puts the image on top of the old one. If you want a new figure for the second image, you can use `pyplot.figure`; if you want to close the first figure, you can use `pyplot.close`.

This is not a bug.

**Closed by QuLogic** 2018-03-30 22:08 UTC

**Comment by grothesque** [comment] 2018-03-31 07:58
Thanks!
