### ISSUE TITLE
NameError: name 'reduce' is not defined

### ISSUE THREAD

**Issue by BlakeTrebelhorn** [matplotlib/matplotlib#8786] opened 2017-06-21 15:27 UTC
### Bug report

**Bug summary**
I'm trying to plot some SQL data in Jupyter Notebook. I'm using [ipython-sql](https://github.com/catherinedevlin/ipython-sql). Plotting a bar or pie chart works fine, but I get an error when trying to do a regular plot. I've tried importing reduce from functools as well as six, as I'm aware reduce has been moved out of Python natively, but it still doesn't work. I've tried searching on Google as well as the Issues for this error, but nothing's come up so far. If it helps, here's what the data looks like from my SQL query: 

Month | GB Over (divided by 10)
------------ | -------------
October | 0 
November | 2261993 
December | 0 
January | 5813711 
February | 5269143 
March | 11951158 
April | 11961163 
May | 10005480 

**Code for reproduction**

```python
result = %sql select Month, KB_Over as "GB Over (divided by 10)..."
%matplotlib inline
from functools import reduce
result.plot()
```

**Actual outcome**

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-14-083688faac41> in <module>()
      1 from functools import reduce
----> 2 result.plot()

C:\Users\{me}\AppData\Local\Continuum\Anaconda3\lib\site-packages\sql\run.py in plot(self, title, **kwargs)
    197         self.guess_plot_columns()
    198         self.x = self.x or range(len(self.ys[0]))
--> 199         coords = reduce(operator.add, [(self.x, y) for y in self.ys])
    200         plot = plt.plot(*coords, **kwargs)
    201         if hasattr(self.x, 'name'):

NameError: name 'reduce' is not defined
```

**Expected outcome**
Here's the bar chart that I get (there are axes and titles, but GH blacked out around the image for some reason):

![image](https://user-images.githubusercontent.com/18293448/27392160-7ea92de6-566b-11e7-9c92-5a53bc7b841b.png)

**Matplotlib version**

  * Operating System: Windows 7
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.1
  * Jupyter Version (if applicable): 1.0.0
  * Other Libraries: ipython-sql v0.3.8

Installed from Anaconda version 4.4.0

(Also props for this bug report template. Very nice!)

**Comment by jenshnielsen** [comment] 2017-06-21 15:49
This is an issue in ipython-sql, Looking at your traceback you can see that the issue is coming from sql/run.py which is a file within ipython-sql here https://github.com/catherinedevlin/ipython-sql/blob/master/src/sql/run.py#L206

The import of reduce is missing from run.py, you cannot work around that by importing it somewhere else. 

I can see that you have a bug report there too.https://github.com/catherinedevlin/ipython-sql/issues/89 i suggest closing this one

**Closed** 2017-06-21 16:03 UTC
