### ISSUE TITLE
FileNotFoundError followed by AttributeError

### ISSUE THREAD

**Issue by cynliu98** [matplotlib/matplotlib#9036] opened 2017-08-15 01:37 UTC
The error occurs when I import matplotlib.pyplot as plt. The error is:

```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/font_manager.py", line 1429, in <module>
    fontManager = pickle_load(_fmcache)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/font_manager.py", line 965, in pickle_load
    with open(filename, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ctl1/.matplotlib/fontList.py3k.cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ctl1/Pixel_Array_Python/WJ.py", line 12, in <module>
    import matplotlib.pyplot as plt
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/contour.py", line 22, in <module>
    import matplotlib.font_manager as font_manager
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/font_manager.py", line 1439, in <module>
    _rebuild()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/font_manager.py", line 1418, in _rebuild
    fontManager = FontManager()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/font_manager.py", line 1053, in __init__
    self.ttffiles = findSystemFonts(paths) + findSystemFonts()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/font_manager.py", line 336, in findSystemFonts
    for f in get_fontconfig_fonts(fontext):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/font_manager.py", line 303, in get_fontconfig_fonts
    return [fname for fname in _call_fc_list()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/font_manager.py", line 284, in _call_fc_list
    out = subprocess.check_output([str('fc-list'), '--format=%{file}\\n'])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/run/__init__.py", line 145, in __new__
    process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/run/__init__.py", line 121, in create_process
    shlex.split(command),
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shlex.py", line 273, in split
    return list(lex)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shlex.py", line 263, in __next__
    token = self.get_token()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shlex.py", line 90, in get_token
    raw = self.read_token()
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shlex.py", line 118, in 
read_token
     nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'
```

  * Operating System: Mac OS X El Capitan 10.11.6
  * Matplotlib Version: 2.0.2
  * Python Version: 3.5.3
  * Other Libraries: numpy

Installed matplotlib and Python via terminal with pip and pip3

I did some debugging on my own and traced the second error (attribute error) to line 284 of font_manager.py:

` out = subprocess.check_output([str('fc-list'), '--format=%{file}\\n'])`

It appears that the parameter, which is a list, is the parameter that becomes self.instream.

**Comment by tacaswell** [comment] 2017-08-15 21:55
I wonder if this is a mac specific bug

```python
17:25 $ python3.5
Python 3.5.3 (default, Mar 18 2017, 11:42:58) 
[GCC 6.3.1 20170306] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> out = subprocess.check_output([str('fc-list'), '--format=%{file}\\n'])
>>> len(out)
154395
>>> type(out)
<class 'bytes'>
>>> len(out.decode('utf-8').split())
2464
>>> 

```

Works as for me with 3.5 from the Arch linux binaries.

Calling it with a list as the first arguement shows up in the docstring

> 

> Help on function check_output in module subprocess:
> 
> check_output(*popenargs, timeout=None, **kwargs)
>     Run command with arguments and return its output.
>     
>     If the exit code was non-zero it raises a CalledProcessError.  The
>     CalledProcessError object will have the return code in the returncode
>     attribute and output in the output attribute.
>     
>     The arguments are the same as for the Popen constructor.  Example:
>     
>     >>> check_output(["ls", "-l", "/dev/null"])
>     b'crw-rw-rw- 1 root root 1, 3 Oct 18  2007 /dev/null\n'
>     
>     The stdout argument is not allowed as it is used internally.
>     To capture standard error in the result, use stderr=STDOUT.
>     
>     >>> check_output(["/bin/sh", "-c",
>     ...               "ls -l non_existent_file ; exit 0"],
>     ...              stderr=STDOUT)
>     b'ls: non_existent_file: No such file or directory\n'
>     
>     There is an additional optional argument, "input", allowing you to
>     pass a string to the subprocess's stdin.  If you use this argument
>     you may not also use the Popen constructor's "stdin" argument, as
>     it too will be used internally.  Example:
>     
>     >>> check_output(["sed", "-e", "s/foo/bar/"],
>     ...              input=b"when in the course of fooman events\n")
>     b'when in the course of barman events\n'
>     
>     If universal_newlines=True is passed, the "input" argument must be a
>     string and the return value will be a string rather than bytes.
> 

but not in the online docs https://docs.python.org/3.7/library/subprocess.html#subprocess.check_output but https://docs.python.org/3.7/library/subprocess.html#frequently-used-arguments details the expected input.

does that line work as expected by it's self for you?

**Comment by cynliu98** [comment] 2017-08-16 02:33
I think it is (a mac specific bug). When I ran identical code to yours in terminal, I got the same attribute error.

**Comment by dopplershift** [comment] 2017-08-16 16:53
On macOS Sierra 10.12.6

Python 3.6
```python
Python 3.6.2 | packaged by conda-forge | (default, Jul 23 2017, 23:01:38) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> out = subprocess.check_output([str('fc-list'), '--format=%{file}\\n'])
>>> len(out)
24785
>>> type(out)
<class 'bytes'>
>>> len(out.decode('utf-8').split())
975
```

Python 3.5
```python
Python 3.5.4 | packaged by conda-forge | (default, Aug 10 2017, 01:41:15) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> out = subprocess.check_output([str('fc-list'), '--format=%{file}\\n'])
>>> len(out)
24785
>>> type(out)
<class 'bytes'>
>>> len(out.decode('utf-8').split())
975
```

At this point, if it's not a bad install, it's specific to either a framework install of Python or El Cap.

**Comment by cynliu98** [comment] 2017-08-16 22:23
Ok, thanks!

Should I just try reinstalling it?

**Comment by tacaswell** [comment] 2017-08-16 23:00
@cynliu98 Yes, that is probably the best course of action.  If that also does not work I suggest one of the pre-build scientific distributions (continuum's anaconda or enthought's canopy) which give you a user-space install.

I am going to close this as it is not a bug in Matplotlib that we can do anything about.

Best of luck and when you sort it out please let us know!

**Closed by tacaswell** 2017-08-16 23:00 UTC
Labels: GUI/osx
