### ISSUE TITLE
[Bug]: plt.plot() with None spacers, alpha < 1 behavior buggy

### ISSUE THREAD

**Issue by gjkoplik** [matplotlib/matplotlib#23714] opened 2022-08-23 05:36 UTC
### Bug summary

`plt.plot()` with `None` / `np.nan` row spacers doesn't allow for alpha-d lines to weigh on top of each other; instead, the collective lines all display with the same `alpha` value everywhere, regardless of overlap.

(I can of course fall back to the `LineCollection` to regain single line + `alpha` capabilities, but it would be nice if that weren't necessary.) 

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

dat = np.arange(10).reshape(-1, 2)

fig, axes = plt.subplots(2, 2, figsize=(8, 8))


axes.flatten()[0].plot(dat[:, 0], dat[:, 1], alpha=1.0, c="blue")
axes.flatten()[0].set_title("Full Alpha")

axes.flatten()[1].plot(dat[:, 0], dat[:, 1], alpha=1/10, c="blue")
axes.flatten()[1].set_title("1/10 Alpha")

for i in range(10):
    axes.flatten()[2].plot(dat[:, 0], dat[:, 1], alpha=1/10, c="blue")
axes.flatten()[2].set_title("10 Lines of 1/10 Alpha")

temp = np.r_[dat, [[None, None]]]
temp_to_plot = np.row_stack([temp for _ in range(10)])
axes.flatten()[3].plot(temp_to_plot[:, 0], temp_to_plot[:, 1], alpha=1/10, c="blue")
axes.flatten()[3].set_title("Supposed to be\n"
                            "10 Lines of 1/10 Alpha = Full Alpha")
fig.subplots_adjust(hspace=0.5, wspace=0.5)
fig.set_facecolor("white")
plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/25061512/186076873-ad07ef4f-38cb-4293-8933-c1fb533e953e.png)

### Expected outcome

The hope was the bottom right line would be full alpha, due to it being 10 identical lines at 1/10 alpha on top of each other, but instead it comes out as 1/10 alpha.

### Additional information

The key conditions for replicating here are having multiple lines separated in a single `(n, 2)` array by a `[None, None]` / `[np.nan, np.nan]` row, and choosing to plot with  `alpha` < 1.0.

### Operating system

Ubuntu

### Matplotlib Version

3.5.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.8.13

### Jupyter version

6.4.12

### Installation

conda

**Comment by tacaswell** [comment] 2022-08-23 15:08
If you add `marker='o'` those do get overlapped as expected.

My first guess was that this was due to path simplification, however setting `mpl.rcParams['path.simplify'] = False` did not help.

**Comment by gjkoplik** [comment] 2022-08-23 15:42
I suppose I'm trying to understand the motivation for that behavior. I only have 2 frequent use cases that come up for plotting lines with NaN values.

1. I'm plotting multiple lines.
1. I'm plotting lines with missing data.

In both those cases, were the lines to cross over themselves, I would still want alpha overlap to be a thing (otherwise I would just set `alpha=1`).

I guess there would be a case of multiple *sets* of overlapping lines that you may only want to alpha-contrast against *each other* not themselves, but that seems like a more niche use case. (There are of course many use cases I'm not familiar with, so I might be missing glaringly important circumstances for others.) 

In the least, if the behavior is maintained (I have pivoted to `LineCollection` for now, so it's not like my use cases lack support), I think the [handout tips for multiline plotting](https://matplotlib.org/cheatsheets/_images/handout-tips.png) might deserve some qualification that this is in a sense a "constrained" means of multiline plotting for some use cases.

**Comment by anntzer** [comment] 2022-08-23 16:19
This is indeed intended behavior, mimicking e.g. the svg spec (https://stackoverflow.com/a/34493165 first paragraph, also I think this is basically what the following states: https://www.w3.org/TR/SVG2/painting.html#StrokeProperties "When stroking is performed using a complex paint server, such as a gradient or a pattern, the stroke operation must be identical to the result that would have occurred if the geometric shape defined by the geometry of the current graphics element and its associated stroking properties were converted to an equivalent ‘[path](https://www.w3.org/TR/SVG2/paths.html#PathElement)’ element and then filled using the given paint server." although it is admittedly not super explicit).

**Comment by gjkoplik** [comment] 2022-08-23 16:33
Fair enough. I figured there was probably some motivation I was missing.

I would strongly recommend revising the [handout](https://matplotlib.org/cheatsheets/_images/handout-tips.png) then, as the act of plotting multiple lines almost always implies standard compositional `alpha` capabilities. I don't know if it's elsewhere in the documentation, but I would consider this means of multi-line plotting an anti-pattern that should be actively discouraged in favor of `LineCollection`.

**Comment by tacaswell** [comment] 2022-08-23 16:36
From Matplotlib's point of view there is only option 2 (a line with missing data) and viewing that as 1 is a choice of interpretation.  I need to think about the wording a bit, but I will probably put in a PR to the hand-out to tweak the wording to something like "draw a line a disconnected segments".

I can see that this is the fastest way to get many identically styled segments (doing the 2D array broadcasting makes N lines and advances the style cycle for each), however this is not a structuring scheme I would suggest to keep your data in otherwise.  `LineCollection` is a much better tool for doing what you want here.

[had more but @anntzer said it better]

**Comment by gjkoplik** [comment] 2022-08-23 17:36
My recommendation would be phrasing along the lines of "disconnected *and non-overlapping* segments" with a pointer to `LineCollection` as an alternative that's still better than `for` loop plotting for overlapping segments.

Then again, I suppose this is also a fundamental misunderstanding on my part of how line plotting works in `matplotlib`, since I didn't appreciate that even overlapping *individual* lines, with or without NaN values, come out in uniform alpha to match svg spec. I suppose I might want a qualifier as early in the process as the `plt.plot()` docstring. (Maybe these sorts of viz problems should just be solved elsewhere in things like [datashader](https://datashader.org/user_guide/Trajectories.html) with the `ds.count()` aggregator instead.)

Anyway, before I go down too many other rabbit holes, @tacaswell and @anntzer  I appreciate the prompt and detailed explanation. I'm good with closing this issue now. If I can be of any help in a future PR to review any tweaks in wording, feel free to tag me into things.

**Comment by tacaswell** [comment] 2022-08-25 23:45
I'm going to close this here and open an issue on the reference sheet repo.

**Closed by tacaswell** 2022-08-25 23:45 UTC
