### ISSUE TITLE
[Bug]: Changing the color of points in a 3-dimensional graph when changing the viewing angle

### ISSUE THREAD

**Issue by IvanovAnton4682671** [matplotlib/matplotlib#28958] opened 2024-10-09 17:50 UTC
### Bug summary

I am creating a 3-dimensional dot graph with 3 variables, and I set the color of the dots using a colormap.
When you create the graph points, they have the same color, and when you rotate them, their color changes.

### Code for reproduction

```Python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

def calculate_g_t(t: float, t_stop: int) -> int:
    """
    Функция, которая вычисляет целевое состояние среды в зависимости от времени

    Args:
        t (float): Текущее время
        t_stop (int): Лимит симуляции

    Returns:
        result (int): Текущее целевое состояние среды
    """
    mid = t_stop / 2
    return 0 if 0 <= t <= mid else 1

def calculate_u_t(k: float, g_t: int, x_t_tau: float) -> float:
    """
    Функция, которая вычисляет воздействие агента на среду

    Args:
        k (float): Коэффициент агента
        g_t (int): Целевое состояние среды
        x_t_tau (float): Предыдущее состояние среды

    Returns:
        result (float): Воздействие агента на среду
    """
    return k * (g_t - x_t_tau)

def calculate_interpolated_x_i(all_time: list, all_x_i: list, t_minus_tau: float) -> float:
    """
    Функция, которая реализует линейную интерполяцию для вычисления значения x(t-tau) вместо подбора ближайшего значения

    Args:
        all_time (list): Список всех моментов времени симуляции
        all_x_i (list): Список всех значений функции x(t)
        t_minus_tau (float): Текущее значение t-tau, для которого ищем значение функции

    Returns:
        result (float): Значение функции x(t) для заданного t-tau
    """
    if t_minus_tau <= all_time[0]:
        return all_x_i[0]
    return np.interp(t_minus_tau, all_time, all_x_i)

def calculate_x_i(big_T_1: float, big_T_2: float, big_D: float, x_i_prev: float, x_i_prev_2: float, delta_t: float, u_i: float) -> float:
    """
    Функция, которая рассчитывает новое состояние среды

    Args:
        big_T_1 (float): Коэффициент среды
        big_T_2 (float): Коэффициент среды
        big_D (float): Коэффициент воздействия
        x_i_prev (float): Предыдущее состояние среды
        x_i_prev_2 (float): Предыдущее перед предыдущим состояние среды
        delta_t (float): Временной шаг
        u_i (float): Воздействие агента на среду

    Returns:
        result (float): Новое состояние среды
    """
    return ((2 * big_T_2 * x_i_prev) - (big_T_2 * x_i_prev_2) + (big_T_1 * delta_t * x_i_prev) + (big_D * (delta_t**2) * u_i) + (delta_t**2)) / (big_T_2 + (big_T_1 * delta_t) + delta_t**2)

def check_stability(g_t: int, x_t: float) -> float:
    """
    Функция, вычисляющая разность между целевым и текущим состоянием среды

    Args:
        g_t (int): Целевое состояние
        x_t (float): Текущее состояние

    Returns:
        result (float): Разность целевого и текущего состояния
    """
    return abs(g_t - x_t)

def simulation(t: float, delta_t: float, t_stop: int, tau: float, k: float, big_T_1: float, big_T_2: float, big_D: float, max_error_threshold: float) -> float:
    """
    Функция, которая проводит симуляцию системы до времени t_stop

    Args:
        t (float): Начальный момент времени
        delta_t (float): Временной шаг
        t_stop (int): Конец симуляции
        tau (float): Величина tau
        k (float): Параметр агента
        big_T_1 (float): Параметр среды
        big_T_2 (float): Параметр среды
        big_D (float): Параметр воздействия
        max_error_threshold (float): Порог ошибки устойчивости системы

    Returns:
        result (float): Максимальная ошибка системы
    """
    #заполняем массивы начальными данными для того, чтобы они все были одной длины
    all_time = [0]
    all_g_t = [0]
    all_x_i = [0, 0]
    all_stability = [0]

    while t < t_stop:
        all_time.append(t)

        cur_g_t = calculate_g_t(t, t_stop)
        all_g_t.append(cur_g_t)

        t_minus_tau = t - tau
        cur_x_t_minus_tau = calculate_interpolated_x_i(all_time, all_x_i, t_minus_tau)
        cur_u_t = calculate_u_t(k, cur_g_t, cur_x_t_minus_tau)
        cur_x_i = calculate_x_i(big_T_1, big_T_2, big_D, all_x_i[-1], all_x_i[-2], delta_t, cur_u_t)
        all_x_i.append(cur_x_i)

        cur_stability = check_stability(cur_g_t, cur_x_i)
        all_stability.append(cur_stability)

        if cur_stability > max_error_threshold:
            return -1

        t += delta_t
    return max(all_stability)

def refine_simulate(t: float, delta_t: float, t_stop: int, prev_tau_list: list, prev_k_list: list, prev_big_T_1_list: list, prev_big_T_2_list: list, prev_big_D_list: list, max_error_threshold: float, step: float) -> list:
    """
    Функция, реализующая сужение диапазона значений tau, k, big_T_1, big_T_2, big_D для поиска оптимальных значений для устойчивости системы

    Args:
        t (float): Начальный момент времени
        delta_t (float): Временной шаг
        t_stop (int): Конец симуляции
        prev_tau_list (list): Список предыдущих значений tau
        prev_k_list (list): Список предыдущих значений k
        prev_big_T_list (list): Список предыдущих значений big_T
        max_error_threshold (float): Порог ошибки устойчивости системы
        step (float): Шаг уменьшения пределов параметров

    Returns:
        list, list, list, list, list, list (list): 6 списков, описывающие 5 параметров (tau, k, big_T_1, big_T_2, big_D) и максимальные ошибки для каждой комбинации параметров
    """
    tau_list = prev_tau_list
    k_list = prev_k_list
    big_T_1_list = prev_big_T_1_list
    big_T_2_list = prev_big_T_2_list
    big_D_list = prev_big_D_list

    for i in range(1):
        print(f"{i + 1} попытка сужения диапазонов значений")

        tau_critical = []
        tau_stable = []
        x1, x2, y1, y2, z, colors = [], [], [], [], [], []
        error_occurred = False

        print("Начало симуляции:")
        for tau in tau_list:
            for k in k_list:
                for big_T_1 in big_T_1_list:
                    for big_T_2 in big_T_2_list:
                        for big_D in big_D_list:
                            max_stability = simulation(t, delta_t, t_stop, tau, k, big_T_1, big_T_2, big_D, max_error_threshold)
                            if max_stability == -1:
                                tau_critical.append((tau, k, big_T_1, big_T_2, big_D))
                                error_occurred = True
                            else:
                                tau_stable.append((tau, k, big_T_1, big_T_2, big_D))
                            x1.append(tau)
                            x2.append(k)
                            y1.append(big_T_1)
                            y2.append(big_T_2)
                            z.append(big_D)
                            colors.append(max_stability)
            print(f"Симуляция для tau = {tau} закончена")

        if error_occurred and tau_stable:
            tau_min = min([t[0] for t in tau_stable])
            tau_max = max([t[0] for t in tau_stable]) - step
            k_min = min([t[1] for t in tau_stable])
            k_max = max([t[1] for t in tau_stable]) - step
            big_T_1_min = min([t[2] for t in tau_stable])
            big_T_1_max = max([t[2] for t in tau_stable]) - step
            big_T_2_min = min([t[3] for t in tau_stable])
            big_T_2_max = max([t[3] for t in tau_stable]) - step
            big_D_min = min([t[4] for t in tau_stable])
            big_D_max = max([t[4] for t in tau_stable]) - step

            tau_list = np.linspace(tau_min, tau_max, 4)
            k_list = np.linspace(k_min, k_max, 4)
            big_T_1_list = np.linspace(big_T_1_min, big_T_1_max, 4)
            big_T_2_list = np.linspace(big_T_2_min, big_T_2_max, 4)
            big_D_list = np.linspace(big_D_min, big_D_max, 4)
            print(f"Новые диапазоны: tau [{tau_min}, {tau_max}], k [{k_min}, {k_max}], T_1 [{big_T_1_min}, {big_T_1_max}], T_2 [{big_T_2_min}, {big_T_2_max}], D [{big_D_min}, {big_D_max}]")
        elif not tau_stable:
            print("Все комбинации параметров приводят к ошибке")
            break
        else:
            print("Система устойчива при данных параметрах")
            break
    return x1, x2, y1, y2, z, colors

t = 0.00
delta_t = 0.01
t_stop = 10.00
tau_list = np.linspace(0.00, 2.0, 4)
k_list = np.linspace(0.00, 2.0, 4)
big_T_1_list = np.linspace(0.00, 2.0, 4)
big_T_2_list = np.linspace(0.00, 2.0, 4)
big_D_list = np.linspace(0.00, 2.0, 4)
max_error_threshold = 1
step = 1

x1, x2, y1, y2, z, colors = refine_simulate(t, delta_t, t_stop, tau_list, k_list, big_T_1_list, big_T_2_list, big_D_list, max_error_threshold, step)

x1 = np.array(x1)
x2 = np.array(x2)
y1 = np.array(y1)
y2 = np.array(y2)
z = np.array(z)
colors = np.array(colors)

fig = plt.figure(figsize=(10, 7))
ax = fig.add_subplot(111, projection="3d")
img = ax.scatter(x1, x2, y1, c=colors, cmap=cm.viridis)
ax.set_xlabel("tau (коэффициент)")
ax.set_ylabel("k (коэффициент агента)")
ax.set_zlabel("T_1 (коэффициент системы)")
plt.title("График с цветовой кодировкой максимальной ошибки системы")
fig.colorbar(img, ax=ax, label="Ошибка системы")
plt.show()
```

### Actual outcome

![photo_1](https://github.com/user-attachments/assets/3545dfa0-6a39-458b-8d20-2298cc2346c9)
![photo_2](https://github.com/user-attachments/assets/cb9fc1af-a684-4db7-8d3e-fe83d1899611)
The photo shows one graph with a slight change in the viewing angle (it can be seen that some points have changed color).

### Expected outcome

It is expected that the points whose color is set by the color map will not change color when the viewing angle changes.

### Additional information

This bug has already been found in version 1.1.* matplotlib, and even on stackoverflow (https://stackoverflow.com/questions/8971309/matplotlib-3d-scatter-color-lost-after-redraw ) there is a description of the solution, but it did not help me

### Operating system

Windows 11 Version 23H2

### Matplotlib Version

3.8.4

### Matplotlib Backend

TkAgg

### Python version

3.12.2

### Jupyter version

-

### Installation

pip

**Comment by QuLogic** [comment] 2024-10-10 03:16
This example is long and takes a while to run; please simplify to just the plotting-relevant portion. I'm sure it can be reproduced with just 3 or 4 fixed points.

**Comment by jklymak** [comment] 2024-10-10 14:38
Sorry you are having difficulties, but this won't get much attention unless you minimize. Ot would be a great help if you find the values of the arrays (rather than asking us to run a simulation) and then find the smallest subset of those values that trigger the bug.

**Comment by IvanovAnton4682671** [comment] 2024-10-10 21:10
> Sorry you are having difficulties, but this won't get much attention unless you minimize. Ot would be a great help if you find the values of the arrays (rather than asking us to run a simulation) and then find the smallest subset of those values that trigger the bug.

I'm sorry that I added too much code to the report data, it really wasn't correct in terms of saving man-hours.

> So I can reproduce on dev: watch for the dot in the lower back left corner (near 0,0,0) with the red edge:
> 
>  Screen.Recording.2024-10-10.154945.-.Trim.mp4 
> What I'm wondering though is if it's an overplotting issue: basically multiple dots at the same position with different colors. Like this dataset has both of these, which map to the purple and yellow in the video at the position with the red edge:
> 
> x1	x2	y1	color
> 0	0	0	-1
> 0	0	0	1
> is this reproducible if you don't have overplotting?
> 
> Dunno if this will be helpful, but this visualization is trying to show how you've got multiple colors assigned for most of your unique x/y/z positions: ![Untitled-1](https://private-user-images.githubusercontent.com/1300499/375536971-503674c8-485c-45ec-8a49-94929b7b3582.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1OTM4OTAsIm5iZiI6MTcyODU5MzU5MCwicGF0aCI6Ii8xMzAwNDk5LzM3NTUzNjk3MS01MDM2NzRjOC00ODVjLTQ1ZWMtOGE0OS05NDkyOWI3YjM1ODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTBUMjA1MzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWI2OWNlOTM2M2FhOTI3NWUxMjA5N2VhNTE0NGE3MmUyODBjNDVhNWIyODlkNWYwOGQ5MzFjNDJmZThlODBmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._2SbLIv1RmE1JawSkXnVzd_Ftg3QUu58OGjna9SbeVg)

This is a really interesting point. I checked and realized that I was indeed plotting incorrectly relative to my lists.

So, what was the problem.
1. I performed a complete search of combinations of parameters, which is why all the lists became 1024 elements long;
2. When plotting directly from these lists, a cube of the form was obtained 4*4*4 because each of these lists consisted, in fact, of 4 unique values and their repetitions (this would allow for unique combinations, for example, one index for all lists, but this was not used);
3. Because of such data on the graph, most likely, the points simply overlapped with each other (and shimmered with colors, because each point was a combination of 5 parameters, which caused it to have a different error value, and because of this, when the graph was rotated, the points overlapped each other);
4. To solve this problem, I have translated one-dimensional lists into 5-dimensional variations in the number of unique values (4*4*4*4*4), after that, I took unnecessary measurements, and then transferred these lists to one-dimensional ones directly in the graph rendering method (code below):

`x1 = np.array(x1)
x2 = np.array(x2)
y1 = np.array(y1)
y2 = np.array(y2)
z = np.array(z)
colors = np.array(colors)

n = len(tau_list)

new_x1 = x1.reshape(n, n, n, n, n)
new_x2 = x2.reshape(n, n, n, n, n)
new_y1 = y1.reshape(n, n, n, n, n)
new_colors = colors.reshape(n, n, n, n, n)

#фиксируем ненужные измерения данных ввиду невозможности отображения всех разом
slice_index_1 = 0
slice_index_2 = 0

flat_x1 = new_x1[:, :, :, slice_index_1, slice_index_2]
flat_x2 = new_x2[:, :, :, slice_index_1, slice_index_2]
flat_y1 = new_y1[:, :, :, slice_index_1, slice_index_2]
flat_colors = new_colors[:, :, :, slice_index_1, slice_index_2]

fig = plt.figure(figsize=(10, 7))
ax = fig.add_subplot(111, projection="3d")
img = ax.scatter(flat_x1.flatten(), flat_x2.flatten(), flat_y1.flatten(), c=flat_colors.flatten(), cmap=cm.viridis)
ax.set_xlabel("tau (коэффициент)")
ax.set_ylabel("k (коэффициент агента)")
ax.set_zlabel("T_1 (коэффициент системы)")
plt.title("График с цветовой кодировкой максимальной ошибки системы")
fig.colorbar(img, ax=ax, label="Ошибка системы")
plt.show()`

Thank you very much to everyone who took part in solving this problem! I admit that I just didn't understand the topic well and blamed the library developers.
P.S. I didn't expect people to help solve the problem so quickly)

![frame_1](https://github.com/user-attachments/assets/0df4f667-2c87-4e2b-a829-66a2e1069a14)
![frame_2](https://github.com/user-attachments/assets/caff0266-6906-46ce-a4a0-8bfe466e88a8)

**Comment by jklymak** [comment] 2024-10-10 21:46
We typically ask for a self-contained minimal example (http://www.sscce.org) because it narrows down the issue, often before it is reported.  I'll close this.

**Closed by jklymak** 2024-10-10 21:46 UTC
Labels: status: needs clarification
