### ISSUE TITLE
The link to the John Hunter Memorial fund is a 404

### ISSUE THREAD

**Issue by bennoleslie** [matplotlib/matplotlib#5558] opened 2015-11-24 23:17 UTC
This link is not available: http://www.numfocus.org/johnhunter/

**Comment by WeatherGod** [comment] 2015-11-30 16:11
Confirmed. And I can't seem to find the page at all on the site. I'll raise
a question about this on their mailing list.

**Comment by tacaswell** [comment] 2015-11-30 16:36
Sorry, already reached out to numfocus and never reported back.  They are sorting some things out internally and took the page down to make sure they do not say anything false.

**Comment by tacaswell** [comment] 2016-01-01 22:23
Closing this as it is no longer a 404.  #5781 tweaks the wording to be more representative of what is on the other side of the link now.

**Closed by tacaswell** 2016-01-01 22:23 UTC
Labels: Documentation

**Comment by charles-cai** [comment] 2024-03-29 14:01
is this one? https://scopatz.github.io/numfocus.org/johnhunter.html

**Comment by rcomer** [comment] 2024-03-29 14:56
Hi @charles-cai it looks like that page is generated from an old fork of the Numfocus pages.  So it would be unlikely to have up-to-date information.  From the history here, it looks like the repurposing of the Numfocus page was deliberate.
