### ISSUE TITLE
Confusing docstring in matplotlib.pyplot.bar() in version 2.0.0

### ISSUE THREAD

**Issue by atsteich** [matplotlib/matplotlib#8527] opened 2017-04-23 10:10 UTC
### Bug report

doctrsing of matplotlib.pyplot.bar() :
def bar(left, height, width=0.8, bottom=None, hold=None, data=None, **kwargs) Inferred type: (left: Any, height: Any, width: float, bottom: Any, hold: Any, data: Any, kwargs: dict) -> Any

The co called "left" parameter specifies (according to the docstring) the left edge of the bars. In reality, plotted bars will be centered around the given values to "left". Since this is in most cases more convenient, i suggest only to correct the docstring!!

**Comment by QuLogic** [comment] 2017-04-23 18:49
Dupe of #7954.

**Closed by QuLogic** 2017-04-23 18:49 UTC
