### ISSUE TITLE
Load_converter: TypeError: strptime() argument 0 must be str, not <class 'bytes'>

### ISSUE THREAD

**Issue by keigolee514** [matplotlib/matplotlib#4126] opened 2015-02-18 20:49 UTC
```python
from __future__ import print_function
from matplotlib.dates import strpdate2num
#from matplotlib.mlab import load
import numpy as np
from pylab import figure, show
import matplotlib.cbook as cbook

datafile = cbook.get_sample_data('msft.csv', asfileobj=False)
print('loading', datafile)

dates, closes = np.loadtxt(
    datafile, delimiter=',',
    converters={0:strpdate2num('%d-%b-%y')},
    skiprows=1, usecols=(0,2), unpack=True)

fig = figure()
ax = fig.add_subplot(111)
ax.plot_date(dates, closes, '-')
fig.autofmt_xdate()
show()
```

**Comment by WeatherGod** [comment] 2015-02-18 21:04
Which version of matplotlib are you using? Which version of python are you
using? On what OS?

**Comment by keigolee514** [comment] 2015-02-18 21:05
Matplotlib: 1.8.2
Python: 3.4
OS: Windows 8 64-bit

Thank you!

**Comment by WeatherGod** [comment] 2015-02-18 21:08
1.8.2?  Are you a time traveler?

**Comment by keigolee514** [comment] 2015-02-18 21:18
sorry, 1.4.2...

**Comment by cimarronm** [comment] 2015-02-25 00:27
The problem is that numpy passes a byte string to the converter instead of a string. In python 2, since `bytes` and `str` are equivalent it does not matter. For python 3, however, this results in an error as strpdate2num passes it to the standard library's `strptime` which only expects a string.

We could add another converter for byte input to the `dates` module. Not sure if it really would get enough use to make sense in adding, however.

@keigolee514, you could use the following to get it working for you:

```python
from __future__ import print_function
from matplotlib.dates import strpdate2num
#from matplotlib.mlab import load
import numpy as np
from pylab import figure, show
import matplotlib.cbook as cbook

def bytespdate2num(fmt, encoding='utf-8'):
    strconverter = strpdate2num(fmt)
    def bytesconverter(b):
        s = b.decode(encoding)
        return strconverter(s)
    return bytesconverter


datafile = cbook.get_sample_data('msft.csv', asfileobj=False)
print('loading', datafile)

dates, closes = np.loadtxt(
    datafile, delimiter=',',
    converters={0:bytespdate2num('%d-%b-%y')},
    skiprows=1, usecols=(0,2), unpack=True)

fig = figure()
ax = fig.add_subplot(111)
ax.plot_date(dates, closes, '-')
fig.autofmt_xdate()
show()
```

**Comment by tacaswell** [comment] 2015-06-18 04:07
Closed by #4153

**Closed by tacaswell** 2015-06-18 04:07 UTC

**Comment by haunledeshuchang** [comment] 2017-12-31 12:16
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

date,open,close=np.loadtxt('000001.csv',delimiter=',',converters={0:mdates.strpdate2num('%m/%d/%Y')},skiprows=1,usecols=(0,1,4),unpack=True)

plt,plot(date,open)

for the same problem.  
 strptime() argument 0 must be str, not <class 'bytes'>

ask for help

**Comment by tacaswell** [comment] 2018-01-01 00:35
@haunledeshuchang This sort of question is best handled on the mailing list (matplotlib-users@python.org you will need to [join the list](https://mail.python.org/mailman/listinfo/matplotlib-users) to post un-moderated.  We try to keep the issues for bug reports or feature requests.

**Comment by kiddick** [comment] 2018-02-22 15:11
seems I have same issue as @haunledeshuchang 
Python 3.6.4
matplotlib==2.1.2

**Comment by pks9862728888** [comment] 2018-10-09 18:48
Bdw How does the function bytesconverter(b): gets called in,

def bytespdate2num(fmt, encoding='utf-8'):
    strconverter = strpdate2num(fmt)
    def bytesconverter(b):
        s = b.decode(encoding)
        return strconverter(s)
    return bytesconverter
