### ISSUE TITLE
[ENH]: Event to notify non-motion after a specific amount of time

### ISSUE THREAD

**Issue by albavilanova** [matplotlib/matplotlib#29162] opened 2024-11-20 11:54 UTC
### Problem

Hi all,

I hope you are doing well.

I've been reading the [documentation page on event handling](https://matplotlib.org/stable/users/explain/figure/event_handling.html) and haven't found an event to detect if the mouse is not moving for some time (1 second or something configurable). 

We would like to have this feature to be able to get annotations on hover on our plot only when the user stops moving the mouse, instead of when the user moves the mouse with 'motion_notify_event' as we are doing it now, which we think makes our application run more slowly.

If you have any question let me know.

Thanks,

Albs

**Comment by tacaswell** [comment] 2024-11-20 17:46
The general approach I think you would have to take is have a callback on `motion_notify` that starts a timer (and cancels a maybe running time) and then subscribe the actual callback to that timer.

I suggest starting with https://matplotlib.org/stable/api/backend_bases_api.html#matplotlib.backend_bases.FigureCanvasBase.new_timer to get timers integrated with the GUI toolkit and to make sure that the callbacks run on the main thread (threading.Timer will likely run into some "fun" thread related issues).  

I don't see any technical reason why this can not be implemented outside of the core library, but I also suspect it will be subtle enough that it would be worth pulling it into core once it is working. 

Is there prior art of APIs for hover that should be used as inspiration?

**Comment by timhoffm** [comment] 2024-11-20 18:14
Going through matplotlib’s event mechanism feels relatively heavy. The underlying GUI frameworks should have appropriate events that we could subscribe to (e.g. QEvent::Tooltip for Qt). I’d expect that to be more efficient than restarting a timer the through a Python function on every motion event.

**Comment by albavilanova** [comment] 2024-11-21 13:14
It is simple text, generated using [annotate](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.annotate.html), but the text isn't static as it is computed on-the-fly. We have given it a go with Tooltip from Qt and it seems to work much faster keeping motion_notify_event. Feel free to close the issue, thank you!

**Comment by tacaswell** [comment] 2024-11-21 15:18
On reflection I agree with @timhoffm .

**Comment by tacaswell** [comment] 2024-11-21 15:20
I'm going to close this as a duplicate of #23378.

**Closed by tacaswell** 2024-11-21 15:20 UTC
Labels: New feature, status: duplicate

**Comment by ericpre** [comment] 2024-11-25 07:53
Would it worth considering such an event ("non-motion" event) for widgets or selectors? This would a significant improvement for situation where the callback connected to the selectors are too slow to be live: for example instead of connecting the callback on `motion_notify_event`, it could be connect to this `non-motion_notify_event`.
