### ISSUE TITLE
[Bug]: mplstyle figure.dpi is ignored in first plot

### ISSUE THREAD

**Issue by grinsted** [matplotlib/matplotlib#24361] opened 2022-11-04 09:29 UTC
### Bug summary

When you load a stylesheet with a figure.dpi setting, then the dpi setting is not honored in the first figure. (It is honored in subsequent figures).

### Code for reproduction

```python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from pathlib import Path
cfgdir = mpl.get_configdir()

# --- First create a custom style file with just a dpi setting ---
p = Path(cfgdir)
stylelib = (p / 'stylelib')
stylelib.mkdir(exist_ok=True)
path = stylelib / 'mplbug.mplstyle'
path.write_text("figure.dpi: 200")

plt.style.reload_library()

x = np.cos(np.linspace(0,4*np.pi,200))
plt.style.use('mplbug')
plt.plot(x)
```

### Actual outcome

when i run this exact code two times in a row in a jupyter notebook, then the figure size is not the same the two times.  It is wrong in the first figure.

### Expected outcome

I expect the figure to be big the first time and all subsequent times. 

### Operating system

Windows

### Matplotlib Version

3.5.2

### Matplotlib Backend

module://ipykernel.pylab.backend_inline

### Python version

3.8.5

### Jupyter version

6.1.4

### Installation

conda

**Comment by QuLogic** [comment] 2022-11-05 07:16
This is a duplicate of #23007, and I believe you would need to update `matplotlib-inline` to fix it.

**Closed by QuLogic** 2022-11-05 07:16 UTC
Labels: third-party integration: jupyter, topic: styles
