### ISSUE TITLE
PDF backend on OS X 10.8 creates PDFs that are viewable in Adobe Reader, but not in Preview or QuickLook

### ISSUE THREAD

**Issue by tcwalther** [matplotlib/matplotlib#2422] opened 2013-09-13 22:00 UTC
When writing figures to disk using

```
plt.safefig('plot.pdf')
```

the resulting PDF files cannot be opened in Preview or be previewed in OS X' QuickLook (more precisely: they take about half an hour [sic!] to open). Adobe Reader does open them instantly without problems, though.

I tried setting the backend to `PDF` manually as suggested elsewhere, but that didn't change anything. It might also be worth noting that writing PDF files takes a lot longer than PNG files. Maybe that is normal, but if not, it might be another symptom that something is wrong.

Using Python 2.7.5 (distribution from www.python.org) and matplotlib 1.3.0 on OS X 10.8.4.

Edit: for a pdf and python script to reproduce the issue, please see comment below.

**Comment by dstansby** [comment] 2017-11-01 17:07
This looks like a very old bug! Could someone try to reproduce it with Matplotlib 2.1?

**Comment by dstansby** [comment] 2017-11-11 10:52
I'm going to close this since it's very old - feel free to re-open if it's still a problem in the latest version of Matplotlib!

**Closed by dstansby** 2017-11-11 10:52 UTC
Labels: backend/pdf, OS/Apple
