### ISSUE TITLE
Text wrapping doesn't seem to work in jupyter notebook

### ISSUE THREAD

**Issue by ivirshup** [matplotlib/matplotlib#10869] opened 2018-03-23 05:01 UTC
### Bug report

In a jupyter notebook text wrapping doesn't seem to work.

**Code for reproduction**

I've just used [an example from the documentation](https://matplotlib.org/examples/text_labels_and_annotations/autowrap_demo.html). I've attached the notebook in a compressed archive (`mpl_textwrap.tar.gz`) and a rendered copy (`matplotlib_notebook_textwrap.pdf`) here:

[matplotlib_notebook_textwrap.pdf](https://github.com/matplotlib/matplotlib/files/1840207/matplotlib_notebook_textwrap.pdf)

[mpl_textwrap.tar.gz](https://github.com/matplotlib/matplotlib/files/1840214/mpl_textwrap.tar.gz)

**Actual outcome**

Image in notebook looks like:

![nb_image](https://user-images.githubusercontent.com/8238804/37812215-e9e91c90-2eb2-11e8-82b6-404d82f8814e.png)

**Expected outcome**

Should look like:

![test](https://user-images.githubusercontent.com/8238804/37812224-fd0e5ccc-2eb2-11e8-9319-8ba66c3da295.png)

**Matplotlib version**

  * Operating system: macOS 10.13.3
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): `module://ipykernel.pylab.backend_inline`
  * Python version: Python 3.6.4
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: IPython

Everything here installed with `pip`

**Comment by jklymak** [comment] 2018-03-23 16:38
It works in `nbagg` so this is just an inline backend problem.

**Comment by jklymak** [comment] 2018-03-27 05:02
I'm not sure this is going to get fixed any time soon - the inline backend handles its extents a bit differently and I'm not sure it gets active support anymore.

**Comment by tacaswell** [comment] 2018-03-27 05:09
I bet this is the `bbox_inches='tight'` that inline uses that resizes the bounding box to the text rather than the text to the bounding box.

**Comment by jklymak** [comment] 2018-03-27 05:15
Confirmed.  If you do `savefig('test.png', bbox_inches='tight')` you get the same inability to wrap.  

Since I doubt inline is going to change from using bbox_inches='tight', I think this is a "won't fix".... 

Thanks for the bug report @ivirshup , but I don't think there is much we can do about this.  The jupyter backend is kind of special...

**Closed by jklymak** 2018-03-27 05:15 UTC
Labels: won't fix

**Comment by tacaswell** [comment] 2020-04-23 23:51
Per https://stackoverflow.com/a/37879281/380231

```
%matplotlib inline
%config InlineBackend.print_figure_kwargs = {'bbox_inches':None}
```

tells the inline backend to not try to shrink wrap the figures which should fix the wrapped text.
