### ISSUE TITLE
Matplotlib Build & Install on s390x throws KeyError for 'version'

### ISSUE THREAD

**Issue by claudefalbriard** [matplotlib/matplotlib#8413] opened 2017-03-31 17:33 UTC
Bug report: Matplotlib Installation from Source Fails with a message:  KeyError: 'version'  
Bug summary: The install stops at the "python setup.py build" step. 

In order to build Matplotlib from source I used the "python setup.py build" and "python setup.py install"
sequence from the latest 2.0.0 source. The build command throws an Key error on version. The versioneer.py module and displays the following message: 

KeyError: 'version'

Likely, there is a missing environment variable or path setting, required to find the  _version.py file. Could you give some guidance how to ignore, or fix this error in order to build and install matplotlib package? Python 2.7.13 was also compiled from source in order to get the header files. Even when not able to read previous version recordings (for ex. "0+unknown"), why  does it break the install procedure?

**Comment by phobson** [comment] 2017-03-31 18:14
@claudefalbriard , just spit-balling here: what happens if you use `pip install .` instead of `python setup.py ...`?

**Comment by tacaswell** [comment] 2017-03-31 18:19
Can you please provide the full traceback?

**Comment by claudefalbriard** [comment] 2017-03-31 19:00
Below an install attempt from source using the command: pip install . and console log: 

```
tar -zxvf matplotlib-2.0.0.tar.gz
ilab70:/data/downloads/matplotlib2 # cd matplotlib-2.0.0

ilab70:/data/downloads/matplotlib2/matplotlib-2.0.0 # pip install .
Processing /data/downloads/matplotlib2/matplotlib-2.0.0
Requirement already satisfied: numpy>=1.7.1 in /usr/lib64/python2.7/site-packages (from matplotlib==2.0.0)
Requirement already satisfied: six>=1.10 in /usr/lib/python2.7/site-packages (from matplotlib==2.0.0)
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/site-packages (from matplotlib==2.0.0)
Requirement already satisfied: functools32 in /usr/lib/python2.7/site-packages (from matplotlib==2.0.0)
Requirement already satisfied: subprocess32 in /usr/lib64/python2.7/site-packages (from matplotlib==2.0.0)
Requirement already satisfied: pytz in /usr/lib/python2.7/site-packages (from matplotlib==2.0.0)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python2.7/site-packages (from matplotlib==2.0.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /usr/lib/python2.7/site-packages (from matplotlib==2.0.0)
Installing collected packages: matplotlib
  Found existing installation: matplotlib 0+unknown
    Uninstalling matplotlib-0+unknown:
      Successfully uninstalled matplotlib-0+unknown
  Running setup.py install for matplotlib ... done
Successfully installed matplotlib-2.0.0

ilab70:/data/downloads/matplotlib2/matplotlib-2.0.0 # python 
Python 2.7.13 (default, Mar 29 2017, 10:42:47) 
[GCC 4.8.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 135, in <module>
    __version__ = str(get_versions()['version'])
KeyError: u'version'
>>> 
```

**Comment by tacaswell** [comment] 2017-03-31 19:05
change out out of the source directory.  I think you are hitting the local files instead of the files you just installed.

**Comment by claudefalbriard** [comment] 2017-03-31 19:11
thanks for the hint, after changing out of the install directory, still getting the error:  

```
cd /data
ilab70:/data # pwd
/data
ilab70:/data # python
Python 2.7.13 (default, Mar 29 2017, 10:42:47) 
[GCC 4.8.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 135, in <module>
    __version__ = str(get_versions()['version'])
KeyError: u'version'
```

**Comment by tacaswell** [comment] 2017-03-31 19:13
Where did you get that tarball from?

**Comment by claudefalbriard** [comment] 2017-03-31 19:17
from the site:  https://pypi.python.org/pypi/matplotlib - the source version at: [ here ](https://pypi.python.org/packages/79/a9/db688816150a6ef91fd9ce284c828467f7271c7dd5982753a73a8e1aaafa/matplotlib-2.0.0.tar.gz#md5=7aa54b06327f0e1c4f3877fc2f7d6b17l)

**Comment by claudefalbriard** [comment] 2017-03-31 20:29
The file used for version control is present: 
at  `/usr/lib64/python2.7/site-packages/matplotlib/_version.py`
and it is located in the same directory as the calling routine:
at  `/usr/lib64/python2.7/site-packages/matplotlib/__init__.py`
 
The folder structure looks OK, so another guess here: 
. A character encoding error at file read level (its not a x86 platform) as the routine searches for a JSON argument named 'version'.

**Comment by tacaswell** [comment] 2017-03-31 21:28
Can you get into a debugger and look at what `get_version` returns?  

```python
17:21 $ python2
Python 2.7.13 (default, Dec 21 2016, 07:16:46) 
[GCC 6.2.1 20160830] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> {'version': 'foo'}[u'version']
'foo'
>>> 

```

I don't think this is a unicode vs bytes (str) issue.

**Comment by claudefalbriard** [comment] 2017-03-31 21:53
on our s390x system I get the same output: 
```
ilab70:/data # python2
Python 2.7.13 (default, Mar 29 2017, 10:42:47) 
[GCC 4.8.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> {'version': 'foo'}[u'version']
'foo'
>>> 
```

**Comment by claudefalbriard** [comment] 2017-03-31 22:39
Found the following instruction at the begin of the file:  setup.cfg.template. The file setup.cfg is referenced at many sections of the failing versioneer.py code mainly in the cfg class, which reads the JSON. It might change the default load directory configuration. Here the two lines: 
```
# Rename this file to setup.cfg to modify Matplotlib's
# build options.
```

**Comment by claudefalbriard** [comment] 2017-03-31 23:30
Manually executing the _version.py module under python2. Is this format the right one?  

```
import _version
>>> print _version.get_versions()
{u'\x00e\x00r\x00': None, u'\x00v\x00e\x00r\x00': u'\x002\x00.\x00', u'\x00d\x00i\x00': False, u'\x00f\x00u\x00l\x00l\x00-\x00r\x00e\x00': u'\x001\x00b\x00f\x00c\x007\x005\x005\x001\x00f\x003\x002\x00f\x007\x00b\x004\x002\x00b\x00a\x005\x000'}
```

**Comment by claudefalbriard** [comment] 2017-03-31 23:44
also the contents from the source of _version.py: 
```
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1bfc7551f32f7b42ba50620a837f03e51d5b7c77",
 "version": "2.0.0"
}
```

**Comment by QuLogic** [comment] 2017-04-01 04:38
This looks like Python 2's poor bytes/unicode mixing to me:
* `'\x00e\x00r\x00'` is the first `len('error')` elements of `'error'.encode('UTF16-BE')`
* `'\x00v\x00e\x00r\x00'` is the first 7 elements of 'version'
* `'\x00d\x00i\x00'` is the first 5 element of 'dirty'
* `'\x00f\x00u\x00l\x00l\x00-\x00r\x00e\x00'` is the first 15 elements of 'full-revisionid'

Do you have an odd `LANG` or `LC_*` environment variables? Did you compile Python with some specific encoding options (not sure what they are, but I remember some kind of wide character settings)? Have you tried Python 3 (which would crash at the real problem instead of mixing stuff up, unless it's already fixed)?

**Comment by claudefalbriard** [comment] 2017-04-03 11:33
Here a description of the pending issues with versioneer and matplotlib packages: 

**Installation with Python 2.7.13**
. Whatever package install that integrate versioneer is causing the KeyError: 'version', like install of matplotlib version 1.5 and 2.0.0 
. When overwriting the return field with a hardcoded u'2.0.0' variable I get a "core dump" error at the "import matplotlib" command, either for version 1.5 or 2.0.0. 
. Going back to the stable matplotlib 1.3 which does not use the versioneer package, the installation and runtime works OK.  
. Pandas and Quandl packages also rely on successful installation of matplolib and versioneer.  
The matplotlib 1.3 installation is a temporary bypass solution until a fix for the reported issue is available. A Python 2.7 installation from source is welcome, as matplotlib is a requisite for many useful packages. 

**Installation with Python 3.4**
. Zypper installation of python3-devel was OK
. Install of matplotlib version 2.0.0 with "python3 setup.py build" throws an error "No such file or directory  #include "numpy/npy_common.h"
. Install of python3-numpy-devel throws a dependency error with the missing gcc-fortran package. This package is not available from the offical SUSE SLES repository.  
. By ignoring the dependency with zypper install option 2, the installation throws an error:  
  /usr/lib64/gcc/s390x-suse-linux/4.8/../../../../s390x-suse-linux/bin/ld: cannot find -lpython3.4m
  collect2: error: ld returned 1 exit status
  error: command 'g++' failed with exit status 1

The module python2.4m is available at the following system locations: 
find / -name python3.4m
/usr/include/python3.4m
/usr/bin/python3.4m

Support is welcome.

**Comment by tacaswell** [comment] 2017-04-03 13:52
For reference, this is the contents of `_version.py` in the dist tarball is

```python

# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1d5aeae08d2986766c9ffd954d03b92146d96953",
 "version": "2.0.0+3767.g1d5aeae08"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)

```

and for reference one from pandas is


```python

# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from warnings import catch_warnings
with catch_warnings(record=True):
    import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4cb730e95353f414bb47f571a69781746bd3e84b",
 "version": "0.19.0+721.g4cb730e95"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)

```

which is odd that they are slightly different, but I do not see why one would work but the other not.

Only think I can think of is that the one of the imports in `matplotlib/__init__.py` is messing with your default encoding.

Can you correctly import mpl's `_version.py` as a stand-alone package?

Try adding a `from __future__ import unicode_literals` to `_version.py`.

I am pretty sure that this is something local to your system (the locale settings, exactly how python was complied, ...) that we do not have access to to reproduce the issue.  That the keys are coming out encoded as 'UTF16-BE' is very suggestive of this.

**Comment by claudefalbriard** [comment] 2017-04-05 21:44
I've executed the following command to find what is the supported UTF version, its the default setting: ucs2
```
>>> import sys 
>>> print sys.maxunicode 
65535
>>> 
```
The language setting is: en_US.UTF-8

Remains some doubt if a complete recompile of Python 2.7.13 with ./configure --enable-unicode=ucs4 , could solve this error and help us to support the latest Matplotlib 2.0.0 release?

**Comment by claudefalbriard** [comment] 2017-04-08 17:59
I've experimentally recompiled the Python 2.7.13 from source having "ucs4" support enabled. This finished successfully and the sys.maxunicode now displays the value of 1114111. First I built the Numpy package again, which is a prerequisite,  and next I also tried to build Matplotlib Version 2.0.0.  
 
```
./configure --enable-unicode=ucs4
make 
make install  
make test 
```

```
python
>>> import sys
>>> print sys.maxunicode
1114111
```

The recompile from source did not fix the root error, so I decided to return back to the default "ucs2" setting, which is default for 2.7 release and c packages.

Error at Versioneer.py: :   
    __version__ = str(get_versions()['version'])
KeyError: u'version'

Likely its machine portability issue between versioneer.py module and s390x architecture.

**Comment by tacaswell** [comment] 2017-04-08 20:05
I do not know if anyone else has access to that architecture.

Can you install from a git checkout?

Did you try adding from `__future__ import unicode_literals` to _version.py.

Try adding an explicit encoding sting to the top of `_version.py`

Try changing the call to to `get_versions()[str('versions')]`

The underlying problem is that for what ever reason, your system is not interpreting the strings in that file correctly. Once you sort how to fix it, we can fix it upstream so future versions just work!

**Comment by tacaswell** [comment] 2017-05-22 12:54
@claudefalbriard Any updates on this?

**Comment by claudefalbriard** [comment] 2017-05-23 11:33
Dear @tacaswell . Thanks for checking this and your request. Indeed I did not pursue this task to build Matplotlib Rel 2 from source, architecture s390x under the SuSE SLES 12 platform. By use of  Docker containers, I got the chance to build a data science oriented stack under Ubuntu 16, which delivers a pre-packaged version of Matplotlib 1.5.1 using the standard apt-get and automate the package install with a dockerfile, also integrating pandas and other tools. Even like that, I see a need to upgrade to the latest Matplotlib 2.0 versions as a demand for addressing new functions will arise. Will plan to build it in a separate virtual space. Case there is any enhancements available to fix the version function under SuSE, please let me know.

**Comment by tacaswell** [comment] 2017-07-30 02:35
Closing as the OP has solved the problem in a different way and we do not otherwise have access to the problematic hardware to reproduce.

**Closed by tacaswell** 2017-07-30 02:35 UTC
Labels: build
