### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by AmJaz** [matplotlib/matplotlib#13284] opened 2019-01-25 04:39 UTC
I want to plot this simple code:

```python
import numpy as np
import matplotlib.pyplot as plt

# Example data
t = np.arange(0.0, 1.0 + 0.01, 0.01)
s = np.cos(4 * np.pi * t) + 2

plt.rc('text', usetex=True)
plt.rc('font', family='serif')
plt.plot(t, s)

plt.xlabel(r'\textbf{time} (s)')
plt.ylabel(r'\textit{voltage} (mV)',fontsize=16)
plt.title(r"\TeX\ is Number "
          r"$\displaystyle\sum_{n=1}^\infty\frac{-e^{i\pi}}{2^n}$!",
          fontsize=16, color='gray')
# Make room for the ridiculously large title.
plt.subplots_adjust(top=0.8)

plt.savefig('tex_demo')
plt.show()

```

the face the following error:

```
runfile('C:/Workspace/jaza0001/untitled0.py', wdir='C:/Workspace/jaza0001')
Traceback (most recent call last):

  File "<ipython-input-13-2954d5a98220>", line 1, in <module>
    runfile('C:/Workspace/jaza0001/untitled0.py', wdir='C:/Workspace/jaza0001')

  File "C:\Temp\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "C:\Temp\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Workspace/jaza0001/untitled0.py", line 20, in <module>
    plt.savefig('tex_demo')

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\pyplot.py", line 689, in savefig
    res = fig.savefig(*args, **kwargs)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\figure.py", line 2094, in savefig
    self.canvas.print_figure(fname, **kwargs)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\backend_bases.py", line 2075, in print_figure
    **kwargs)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\backends\backend_agg.py", line 510, in print_png
    FigureCanvasAgg.draw(self)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\backends\backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\axes\_base.py", line 2628, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\axis.py", line 1187, in draw
    renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\axis.py", line 1125, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\text.py", line 930, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\text.py", line 313, in _get_layout
    ismath=ismath)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\backends\backend_agg.py", line 209, in get_text_width_height_descent
    s, fontsize, renderer=self)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\texmanager.py", line 464, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\texmanager.py", line 328, in make_dvi
    texfile], tex)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\texmanager.py", line 298, in _run_checked_subprocess
    stderr=subprocess.STDOUT)

  File "C:\Temp\Anaconda\lib\subprocess.py", line 389, in check_output
    **kwargs).stdout

  File "C:\Temp\Anaconda\lib\subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:

  File "C:\Temp\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 171, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Temp\Anaconda\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)

  File "C:\Temp\Anaconda\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified

Error in callback <function install_repl_displayhook.<locals>.post_execute at 0x000001C8A5C1E6A8> (for post_execute):
Traceback (most recent call last):

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\pyplot.py", line 109, in post_execute
    draw_all()

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\_pylab_helpers.py", line 132, in draw_all
    f_mgr.canvas.draw_idle()

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\backend_bases.py", line 1899, in draw_idle
    self.draw(*args, **kwargs)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\backends\backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\axes\_base.py", line 2628, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\axis.py", line 1187, in draw
    renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\axis.py", line 1125, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\text.py", line 930, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\text.py", line 313, in _get_layout
    ismath=ismath)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\backends\backend_agg.py", line 209, in get_text_width_height_descent
    s, fontsize, renderer=self)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\texmanager.py", line 464, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\texmanager.py", line 328, in make_dvi
    texfile], tex)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\texmanager.py", line 298, in _run_checked_subprocess
    stderr=subprocess.STDOUT)

  File "C:\Temp\Anaconda\lib\subprocess.py", line 389, in check_output
    **kwargs).stdout

  File "C:\Temp\Anaconda\lib\subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:

  File "C:\Temp\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 171, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Temp\Anaconda\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)

  File "C:\Temp\Anaconda\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified

Traceback (most recent call last):

  File "C:\Temp\Anaconda\lib\site-packages\IPython\core\formatters.py", line 341, in __call__
    return printer(obj)

  File "C:\Temp\Anaconda\lib\site-packages\IPython\core\pylabtools.py", line 244, in <lambda>
    png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))

  File "C:\Temp\Anaconda\lib\site-packages\IPython\core\pylabtools.py", line 128, in print_figure
    fig.canvas.print_figure(bytes_io, **kw)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\backend_bases.py", line 2049, in print_figure
    **kwargs)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\backends\backend_agg.py", line 510, in print_png
    FigureCanvasAgg.draw(self)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\backends\backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\axes\_base.py", line 2628, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\axis.py", line 1187, in draw
    renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\axis.py", line 1125, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\text.py", line 930, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\text.py", line 313, in _get_layout
    ismath=ismath)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\backends\backend_agg.py", line 209, in get_text_width_height_descent
    s, fontsize, renderer=self)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\texmanager.py", line 464, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\texmanager.py", line 328, in make_dvi
    texfile], tex)

  File "C:\Temp\Anaconda\lib\site-packages\matplotlib\texmanager.py", line 298, in _run_checked_subprocess
    stderr=subprocess.STDOUT)

  File "C:\Temp\Anaconda\lib\subprocess.py", line 389, in check_output
    **kwargs).stdout

  File "C:\Temp\Anaconda\lib\subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:

  File "C:\Temp\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 171, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Temp\Anaconda\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)

  File "C:\Temp\Anaconda\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified

<Figure size 432x288 with 1 Axes>

```

**Comment by jklymak** [comment] 2019-01-25 04:46
What version of Matplotlib?   Something like this was recently fixed so please try 3.0.2.

**Comment by jklymak** [comment] 2019-01-25 04:49
I'm going to close as a duplicate of #12173, but please ping again if a more recent matplotlib *doesn't* fix this problem and we can re-open.

(also in the future, you can use three back ticks to delineate code:  "```" )

**Closed by jklymak** 2019-01-25 04:49 UTC

**Comment by AmJaz** [comment] 2019-01-25 05:08
I use the latest version of matplotlib (3.0.2) but I still have this problem

**Comment by AmJaz** [comment] 2019-01-25 05:18
I use the latest version of matplotlib but I still have this problem

    On Friday, January 25, 2019, 3:19:25 PM GMT+10:30, Jody Klymak <notifications@github.com> wrote:  
 
 
I'm going to close as a duplicate of #12173, but please ping again if a more recent matplotlib doesn't fix this problem and we can re-open.

(also in the future, you can use three back ticks to delineate code: "```" )

**Comment by jklymak** [comment] 2019-01-25 05:54
You hav set `usetex=True`  Do you have a working latex system on your computer?

**Comment by yzhang-gh** [comment] 2019-02-04 17:11
The same issue here. It used to work well but had this issue after I updated it to the latest version.

The minimal reproducing example

```python
import matplotlib.pyplot as plt

plt.rc("text", usetex=True)

plt.plot(range(10))
plt.title("\\textbf{bold}")
plt.show()
```

<details>
<summary>Error traceback</summary>

```
Traceback (most recent call last):
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5.py", line 519, in _draw_idle
    self.draw()
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 2628, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\axis.py", line 1190, in draw
    tick.draw(renderer)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\axis.py", line 304, in draw
    self.label1.draw(renderer)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\text.py", line 754, in draw
    mtext=mtext)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 233, in draw_tex
    Z = texmanager.get_grey(s, size, self.dpi)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\texmanager.py", line 420, in get_grey
    pngfile = self.make_png(tex, fontsize, dpi)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\texmanager.py", line 385, in make_png
    "-T", "tight", "-o", pngfile, dvifile], tex)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\texmanager.py", line 298, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "C:\Users\Yu\Anaconda3\lib\subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "C:\Users\Yu\Anaconda3\lib\subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Yu\Anaconda3\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Yu\Anaconda3\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5.py", line 519, in _draw_idle
    self.draw()
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 2628, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\axis.py", line 1190, in draw
    tick.draw(renderer)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\axis.py", line 304, in draw
    self.label1.draw(renderer)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\text.py", line 754, in draw
    mtext=mtext)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 233, in draw_tex
    Z = texmanager.get_grey(s, size, self.dpi)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\texmanager.py", line 420, in get_grey
    pngfile = self.make_png(tex, fontsize, dpi)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\texmanager.py", line 385, in make_png
    "-T", "tight", "-o", pngfile, dvifile], tex)
  File "C:\Users\Yu\Anaconda3\lib\site-packages\matplotlib\texmanager.py", line 298, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "C:\Users\Yu\Anaconda3\lib\subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "C:\Users\Yu\Anaconda3\lib\subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Yu\Anaconda3\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Yu\Anaconda3\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

</details>

Matplotlib version: 3.0.2

I can confirm the LaTeX works well using the same shell

```
>>> latex --version
pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2018/W32TeX)
...
>>> xelatex --version
XeTeX 3.14159265-2.6-0.99999 (TeX Live 2018/W32TeX)
...
```

**Comment by jklymak** [comment] 2019-02-04 17:59
Can you try 
```python
import subprocess
subprocess.check_output(['latex', '--version'])
```

Otherwise, maybe the cache needs to be cleared?  I think its in `~/.matplotlibrc/tex.cache`.  Its safe to delete that directory.  Maybe move away `~/.matplotlibrc/texsupport.db` as well?

**Comment by yzhang-gh** [comment] 2019-02-04 21:18
Thanks for the quick response.

Tried and seemed no problem as well (no `CalledProcessError`)

![image](https://user-images.githubusercontent.com/7588612/52237585-d9d62500-28c1-11e9-8cbd-35a753d62604.png)

Also tried removing `tex.cache` (no `texsupport.db` there), no luck :(

**Comment by yzhang-gh** [comment] 2019-02-05 13:49
I know the reason now. We also need `dvipng` besides LaTeX

> Matplotlib’s LaTeX support requires a working LaTeX installation, [dvipng](http://www.nongnu.org/dvipng/) (which may be included with your LaTeX installation) ...
>
> - <https://matplotlib.org/users/usetex.html>

Installing `dvipng` resolved my issue.

**Comment by Gokul656** [comment] 2019-07-21 11:14
Use Shell=True, It's working for me.
