### ISSUE TITLE
Missing __init__.py file in mpl_toolkits

### ISSUE THREAD

**Issue by frenzymadness** [matplotlib/matplotlib#9823] opened 2017-11-21 10:52 UTC
### Bug report

**Bug summary**

I am building python-matplotlib RPM for Fedora and I've found out that I cannot execute tests because the file `mpl_toolkits/__init__.py` is missing.

**Code for reproduction**

```
MATPLOTLIBDATA=$PWD/lib/matplotlib/mpl-data/ PYTHONPATH=/builddir/build/BUILDROOT/python-matplotlib-2.1.0-1.fc28.2.x86_64/usr/lib64/python2.7/site-packages/ python tests.py 
```

**Actual outcome**

```
('Python byte-compilation optimization level:', 0)
========================================== test session starts ==========================================
platform linux2 -- Python 2.7.14, pytest-3.2.3, py-1.5.2, pluggy-0.4.0
rootdir: /builddir/build/BUILD/matplotlib-2.1.0, inifile: pytest.ini

===================================== no tests ran in 0.00 seconds ======================================
ERROR: file or package not found: mpl_toolkits.tests (missing __init__.py?)
```

```
$ cat setup.cfg
[packages]
tests = True
toolkits_tests = True

[rc_options]
backend = TkAgg
$ cd /builddir/build/BUILDROOT/python-matplotlib-2.1.0-1.fc28.2.x86_64/usr/lib64/python2.7/site-packages/mpl_toolkits/
$ ll
total 92
drwxr-xr-x. 2 mockbuild mock  4096 Nov 21 11:44 axes_grid
drwxr-xr-x. 2 mockbuild mock  4096 Nov 21 11:44 axes_grid1
drwxr-xr-x. 2 mockbuild mock  4096 Nov 21 11:44 axisartist
-rw-r--r--. 1 mockbuild mock  3966 Oct  3 08:50 exceltools.py
-rw-r--r--. 2 mockbuild mock  3966 Nov 21 11:44 exceltools.pyc
-rw-r--r--. 2 mockbuild mock  3966 Nov 21 11:44 exceltools.pyo
-rw-r--r--. 1 mockbuild mock 19211 Oct  3 08:50 gtktools.py
-rw-r--r--. 1 mockbuild mock 19805 Nov 21 11:44 gtktools.pyc
-rw-r--r--. 1 mockbuild mock 19766 Nov 21 11:44 gtktools.pyo
drwxr-xr-x. 2 mockbuild mock  4096 Nov 21 11:44 mplot3d
drwxr-xr-x. 3 mockbuild mock  4096 Nov 21 11:44 tests
```

**Expected outcome**

Existing `__init__.py` file in `/usr/lib64/python2.7/site-packages/mpl_toolkits/` and running tests.

**Matplotlib version**

  * Operating system: Fedora 28 (rawhide)
  * Matplotlib version: 2.1.0 built from source
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 2.7.14 from distribution package

**Comment by jklymak** [comment] 2017-11-21 15:53
Its in master, so there is something wrong w/ your install.  Closing, but feel free to reopen if you think this is a Matplotlib problem.

**Comment by jklymak** [comment] 2018-03-26 18:52
Maybe the toolkits aren't being installed by default in the pip build?  Re-opening to attract attention from someone who knows more about the builds and pip....

**Comment by anntzer** [comment] 2018-03-27 04:57
If we keep the mpl_toolkits namespace around (really not clear it's worth it, but heh), we should probably just make it an implicit namespace package (per https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages) in 3.0.

**Comment by QuLogic** [comment] 2023-03-17 08:39
Closing as duplicate of #25244, as that's where discussion is happening.

**Closed by QuLogic** 2023-03-17 08:39 UTC
Labels: Build
