### ISSUE TITLE
 from mpl 3.2.2 to 3.3.0 enormous increase in creation time

### ISSUE THREAD

**Issue by edge-python** [matplotlib/matplotlib#18743] opened 2020-10-15 18:05 UTC
Hello

I'm not a professional, but I'm not a beginner either
I have been working with matplotlib since 2013 (see for example issue # 1957)

**my system:** 

Win10(64), IDE PyCharm, python 3.8.2 (64), numpy 1.19.2, matplotlib 3.2.2 and 3.3.0

**I mainly use:** 

```
matplotlib.pyplot as plt
fig, ax=plt.subplot(...)
ax.plot(...)
ax.fill_between(...)
plt.show()
```

**my plot data:**

4 rows each 525600 points (365day * 24hour * 60 min)

**the problem:**

with mpl 3.2.2 the creation of the plot example 1 takes 4 seconds
but
with mpl 3.3.0 the creation of the plot example 1 takes 31 seconds

and

with mpl 3.2.2 the creation of the plot example 2 takes 13 seconds
but
with mpl 3.3.0 the creation of the plot example 2 takes 82 seconds

**example 1**
![example 1](https://user-images.githubusercontent.com/4279914/96168387-f2b12d80-0f20-11eb-951a-152178dc1d9c.png)

**example 2**
![example 2](https://user-images.githubusercontent.com/4279914/96168403-f8a70e80-0f20-11eb-8f48-317f8138e18a.png)

**the question:**

Why is this enormous extension of the creation time?
What has changed from mpl 3.2.2 to 3.3.0?

Thank you

**Comment by jklymak** [comment] 2020-10-15 19:12
Can you recreate the problem with synthetic data?  Hard to tell otherwise...

**Comment by edge-python** [comment] 2020-10-15 19:27
Thanks for the comment

The fact is:
I haven't changed anything in my code,
the change is in mpl 3.3.0 (from 3.2.2 to 3.3.0)

synthetic data? maybe sin cos etc.? I would have to think about that first

**Comment by jklymak** [comment] 2020-10-15 19:35
Sure not claiming it is your code, but we can't investigate where the slow down is without something we can run.  np.random.rand is also useful tool

**Comment by tacaswell** [comment] 2020-10-15 20:59
@edge-python As Jody says if we are going to debug this, knowing exactly what you are doing and synthetic data that can reproduce the slow down will greatly help us to do the work required to track this down (I could imagine it would be easy to write code that "looks like" your example but does not trigger what ever the slow path is).  A snippet of code that we can copy-paste-see-the slow-down would be ideal :)

Can you also try with 3.3.3?  I think we merged a couple of things that fixed performance regressions.

**Comment by edge-python** [comment] 2020-10-15 22:09
also thanks for the comment

with mpl **3.3.2** the creation of the plot example 2 also takes ~ 83 seconds

**synthetic data:**
I started with a simple code
I couldn't reproduce the problem with it
I will probably need some time
in the original code I also use matplotlib.ticker and other things
let's see what's up ...
it will not be easy

**Comment by jklymak** [comment] 2020-10-15 22:53
The other approach is comment out goodies from the other code until you find the bottle neck

**Comment by tacaswell** [comment] 2020-10-16 21:37
@edge-python In the future please paste the code directly into the issues (it is much easier to deal with for us!)

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""plot_cut_syntheticV2_github.py"""
import numpy
import datetime
import matplotlib.ticker
import matplotlib.pyplot as plt
import time

# ____TEST____ time.process_time
steps = {}
step_time = time.process_time()
steps['step_A'] = ['total', '', step_time, None]
steps['step_AA'] = ['    before first for', '', step_time, None]

# synthetic
anzahl_reihen = 2
files = ['16_2020_0000000_aaa.csv', '22_2020_0000001_bbb.csv']

zeit_dat = [[] for j in range(0, anzahl_reihen)]
nhn_dat = [[] for j in range(0, anzahl_reihen)]

# ____TEST____ time.process_time
step_time = time.process_time()
steps['step_AA'][3] = step_time
steps['step_AB'] = ['    first for total', '', step_time, None]

for reihe in range(0, anzahl_reihen):

    # ____TEST____ time.process_time
    step_time = time.process_time()
    steps['step_AB'+str(reihe)] = ['        first for run: ', reihe, step_time, None]

    name_file = files[reihe]
    name_file = name_file.split(".", 1)[0]
    name_file = name_file.split("_", -1)
    pegel_nr = name_file[2]

    if pegel_nr == '0000000':
        pegel_bbm1 = [True, reihe]
    elif pegel_nr == '0000001':
        pegel_bb = [True, reihe]

    # region # synthetic ...
    def datetime_range(startDate, endDate, deltaDate):
        current = startDate
        while current < endDate:
            yield current
            current += deltaDate
        return


    def datetime_to_str(date_time):
        d = str(date_time)
        return d[8:10]+'.'+d[5:7]+'.'+d[0:4]+d[10:16]


    listOfDates = [datetime_to_str(einzelDate) for einzelDate in
                   datetime_range(datetime.datetime(2020, 1, 1, 0, 1),
                                  datetime.datetime(2020, 12, 31, 23, 59),
                                  datetime.timedelta(minutes=1))]

    t = numpy.arange(0, 527041, 1)

    if reihe == 0:
        s = 0.8 * numpy.sin(1/360 * numpy.pi * t)
    elif reihe == 1:
        s = 0.15 * numpy.cos(1/360 * numpy.pi * (t+360)) - 0.10

    synthetic_file = []
    i = 0
    for einzelDate in listOfDates:
        synthetic_file.append(einzelDate+';'+str(s[i]))
        i += 1
    # endregion # synthetic ...

    pegel_plot_daten = \
        [[datetime.datetime(int(feld[0][6:10]),
                            int(feld[0][3:5]), int(feld[0][0:2]),
                            int(feld[0][11:13]), int(feld[0][14:16])),
          float((feld[1].replace(",", ".")) if feld[1] != "" else numpy.nan)]
         for feld in ((line.rstrip('\n')).split(";", 1)
                      for line in synthetic_file)]

    for row in pegel_plot_daten:
        zeit_dat[reihe].append(row[0])
        nhn_dat[reihe].append(row[1])

    # ____TEST____ time.process_time
    step_time = time.process_time()
    steps['step_AB'+str(reihe)][3] = step_time

# ____TEST____ time.process_time
step_time = time.process_time()
steps['step_AB'][3] = step_time
steps['step_AC'] = ['    behind first for - before second for', '', step_time, None]

fig, ax = plt.subplots(figsize=(42.0/2.54, 29.7/2.54))
plt.subplots_adjust(left=0.06, bottom=None, right=0.96, top=0.90, wspace=None, hspace=None)


def move_figure(f, x, y):
    backend = matplotlib.get_backend()
    if backend == 'TkAgg':
        f.canvas.manager.window.wm_geometry("+%d+%d" % (x, y))
    elif backend == 'WXAgg':
        f.canvas.manager.window.SetPosition((x, y))
    else:
        f.canvas.manager.window.move(x, y)
    return


move_figure(fig, 125, 1)

# ____TEST____ time.process_time
step_time = time.process_time()
steps['step_AC'][3] = step_time
steps['step_AD'] = ['    second for total', '', step_time, None]

for reihe in range(0, anzahl_reihen):

    # ____TEST____ time.process_time
    step_time = time.process_time()
    steps['step_AD'+str(reihe)] = ['        ax.plot: ', reihe, step_time, None]

    ax.plot(zeit_dat[reihe], nhn_dat[reihe])

    # ____TEST____ time.process_time
    step_time = time.process_time()
    steps['step_AD'+str(reihe)][3] = step_time

# ____TEST____ time.process_time
step_time = time.process_time()
steps['step_AD'][3] = step_time
steps['step_AE'] = ['    mask and fill_between', '', step_time, None]

# region # mask and fill_between ...
zeit_fill = zeit_dat[0]
nhn_el = nhn_dat[pegel_bbm1[1]]
nhn_nk = nhn_dat[pegel_bb[1]]
mask_entw_fenster_yes = []
mask_entw_fenster_no = []

for i in range(len(zeit_fill)):
    mask_entw_fenster_yes.append(float(nhn_el[i]) < float(nhn_nk[i]))
    mask_entw_fenster_no.append(float(nhn_el[i]) > float(nhn_nk[i]))

ax.fill_between(zeit_fill, nhn_el, nhn_nk, where=mask_entw_fenster_yes, color='b',
                alpha=0.2, interpolate=True)
ax.fill_between(zeit_fill, nhn_el, nhn_nk, where=mask_entw_fenster_no, color='r',
                alpha=0.2, interpolate=True)
# endregion # mask and fill_between

# ____TEST____ time.process_time
step_time = time.process_time()
steps['step_AE'][3] = step_time
steps['step_AF'] = ['    behind mask and fill_between', '', step_time, None]

# region # format ax ...
plt.axis([zeit_dat[0][0], zeit_dat[anzahl_reihen-1][-1], -0.89, 0.89])
ax.set_yticks(numpy.linspace(-1.80, 4.80, num=67))

for tick in ax.get_xticklabels():
    tick.set_rotation(45)

my_base_date = datetime.datetime(1, 1, 1, 0, 0, 0)
my_base_date_follow_day = datetime.datetime(1, 1, 2, 0, 0, 0)
one_day = my_base_date_follow_day - my_base_date


def my_format_tick_labels(x_zeit, pos=None):
    x_zeit_convert = my_base_date + datetime.timedelta(x_zeit) - one_day
    zoom = ax.get_xlim()[1] - ax.get_xlim()[0]
    if zoom < 5:
        zeit_format = '%d.%m.%Y %H:%M'
    elif zoom < 152:
        zeit_format = '%d.%m.%Y'
    else:
        zeit_format = '%m.%Y'
    return x_zeit_convert.strftime(zeit_format)


ax.xaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(my_format_tick_labels))
ax.yaxis.set_major_formatter(matplotlib.ticker.FormatStrFormatter('%.2f'))
ax.xaxis.grid(alpha=0.7, linewidth=0.6)
ax.yaxis.grid(alpha=0.7, linewidth=0.5)
ax.set(ylabel='[m] NHN', title='Titel'+'\n')
ax.set_ylim(-0.89, 0.89)
ax.set_xlim([datetime.datetime(2020, 10, 1, 0, 0), datetime.datetime(2020, 10, 4, 23, 59)])
# endregion # format ax

# ____TEST____ time.process_time
step_time = time.process_time()
steps['step_AF'][3] = step_time
steps['step_A'][3] = step_time
for key, row in steps.items():
    print(key+': '+row[0]+str(row[1])+':  {0:.4f} sec'.format(row[3]-row[2]))

plt.show()

```

**Comment by jklymak** [comment] 2020-10-16 21:40
Also, as far as I can tell the data is not in the zip?  

This is really non-trivial code, and you are doing interesting things like moving the figure around etc, and a bunch of formatting etc.    Is it really all necessary to recreate the problem?

**Comment by tacaswell** [comment] 2020-10-16 22:32
It is something is the datetime handling:

```
In [46]: %prun plt.plot(np.asarray(zeit_dat[0]), np.asarray(nhn_dat[0]))
         5311416 function calls (5310845 primitive calls) in 10.378 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   527041    4.390    0.000    8.058    0.000 dates.py:307(_dt64_to_ordinalf)
  3162246    3.607    0.000    3.607    0.000 {method 'astype' of 'numpy.generic' objects}
   527041    1.407    0.000    9.536    0.000 dates.py:288(_to_ordinalf)
      320    0.658    0.002    0.658    0.002 {built-in method numpy.array}
        1    0.148    0.148    9.686    9.686 function_base.py:2184(_vectorize_call)
   527933    0.072    0.000    0.072    0.000 {built-in method builtins.getattr}
```

if we convert to an array of datetime64 it gets faster.  @edge-python What is the version of numpy in the two cases?

**Comment by edge-python** [comment] 2020-10-16 22:55
as written in the opening post: 

**numpy 1.19.2**

**Comment by edge-python** [comment] 2020-10-16 23:04
@jklymak   the synthetic data is in the short 199 lines of code

**Comment by jklymak** [comment] 2020-10-16 23:05
OK, so why the file names etc? Sorry I just saw that and the zip file and assumed the csv files were needed.

**Comment by jklymak** [comment] 2020-10-16 23:27
Seems to bisect to the epoch change: a3fbc492dfb3f45

Not at all sure why this would be a problem though...

**Comment by tacaswell** [comment] 2020-10-16 23:46
It looks like if we get an iterable of non-datetime64 we go through a numpy-vectorized version of `_to_ordinalf`.  I suspect that the change from the special case in that function to calling `_dt64_to_ordinalf` made it much more expensive.  

```diff
diff --git a/lib/matplotlib/dates.py b/lib/matplotlib/dates.py
index 3b7af0d5d8..90aca57a6b 100644
--- a/lib/matplotlib/dates.py
+++ b/lib/matplotlib/dates.py
@@ -441,7 +441,7 @@ def date2num(d):
             return _dt64_to_ordinalf(d)
         if not d.size:
             return d
-        return _to_ordinalf_np_vectorized(d)
+        return _dt64_to_ordinalf(d.astype('datetime64[s]'))
 
 
 def julian2num(j):

```

fixes the speed regression:


```
step_A: total:  13.2401 sec
step_AA:     before first for:  0.0000 sec
step_AB:     first for total:  6.3157 sec
step_AB0:         first for run: 0:  3.1192 sec
step_AB1:         first for run: 1:  3.1964 sec
step_AC:     behind first for - before second for:  0.1162 sec
step_AD:     second for total:  3.1578 sec
step_AD0:         ax.plot: 0:  1.5838 sec
step_AD1:         ax.plot: 1:  1.5740 sec
step_AE:     mask and fill_between:  3.5688 sec
step_AF:     behind mask and fill_between:  0.0816 sec

```

vs

```
step_A: total:  41.8153 sec
step_AA:     before first for:  0.0000 sec
step_AB:     first for total:  6.5672 sec
step_AB0:         first for run: 0:  3.3592 sec
step_AB1:         first for run: 1:  3.2080 sec
step_AC:     behind first for - before second for:  0.0161 sec
step_AD:     second for total:  17.3695 sec
step_AD0:         ax.plot: 0:  8.5941 sec
step_AD1:         ax.plot: 1:  8.7754 sec
step_AE:     mask and fill_between:  17.7842 sec
step_AF:     behind mask and fill_between:  0.0783 sec

```

**Comment by jklymak** [comment] 2020-10-16 23:52
A simple test is:

```python
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.units
import numpy as np
import datetime
import time

# region # synthetic ...
def datetime_range(startDate, endDate, deltaDate):
    current = startDate
    while current < endDate:
        yield current
        current += deltaDate
    return

listOfDates = [date for date in datetime_range(datetime.datetime(2020, 1, 1, 0, 1),
                              datetime.datetime(2020, 12, 31, 23, 59),
                              datetime.timedelta(minutes=1))]

print('Bad')
start = time.perf_counter()
print(mdates.date2num(np.array(listOfDates)))
stop = time.perf_counter()
print(stop-start)

print('Better')
start = time.perf_counter()
print(mdates.date2num(np.array(listOfDates).astype('datetime64')))
stop = time.perf_counter()
print(stop-start)
```
Bad
13.846317258000001
Better
1.8920521109999981
```

For 3.2.2:

```
Bad
1.8535084829999997
Better
2.080723823
```

So, it seems that letting numpy doing the conversion to dt64 and then doing the rest of the math in dt64 would be a way forward.

**Comment by jklymak** [comment] 2020-10-20 15:40
This will close automatically when #18756 is merged....

**Closed** 2020-10-29 21:28 UTC
Labels: Date handling, Performance
