### ISSUE TITLE
imshow issues

### ISSUE THREAD

**Issue by abcam** [matplotlib/matplotlib#17732] opened 2020-06-23 12:51 UTC
### Bug report

**Bug summary**

imshow is not displaying data accurately. Non existent values displayed in images, white spots as shown below. This issue was also occurring in 3.2.1.

**Code for reproduction**

```python
import numpy as np 
import matplotlib.pyplot as plt
from matplotlib.colors import from_levels_and_colors

rnd = np.random.default_rng(32)
data = rnd.choice((0, 1), (200, 200), p=(.25, .75))

cmap, norm = from_levels_and_colors([0, .5, 1], ['red', 'blue'])
plt.imshow(data, cmap = cmap)
plt.colorbar()
plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/64583949/85404321-b2373980-b556-11ea-83ff-07af69ff04a9.png)

**Expected outcome**

![test1](https://user-images.githubusercontent.com/64583949/85404727-4c977d00-b557-11ea-9483-46cc2c4716a9.png)

As displayed with matplotlib 3.1.3.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.2.1 and 3.2.2
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.7.7 (default, Apr 15 2020, 05:09:04) [MSC v.1916 64 bit (AMD64)]
  * Jupyter version (if applicable):  jupyter core: 4.6.3, jupyter-notebook: 6.0.3, jupyter client: 6.1.3, jupyter lab: 2.1.1
  * Other libraries: numpy 1.18.1

Pip install 3.2.1 and 3.2.2.

**Comment by jklymak** [comment] 2020-06-23 15:22
This is a duplicate of #17722 

We changed to add anti-aliasing to images in 3.2.  If you are getting those speckles you do not have enough resolution for your image.  Either increase your dpi or your figure size.  If you'd like to have the old aliased behaviour you can use `plt.imshow(data, cmap=cmap, interpolation='none')`

**Closed** 2020-06-23 15:22 UTC
Labels: Duplicate, Images
