### ISSUE TITLE
Horizontal alignment of `suptitle` is backwards

### ISSUE THREAD

**Issue by anders-dc** [matplotlib/matplotlib#15779] opened 2019-11-27 10:30 UTC
### Bug report

**Bug summary**

The `horizontalalignment` keyword in [suptitle()](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.suptitle.html) produces title alignment which is opposite to what I expect from it. Setting `horizontalalignment='left'` puts the alignment right, and vice versa.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

for direction in ['left', 'center', 'right']:
    fig = plt.figure()
    fig.suptitle('This is a test title', horizontalalignment=direction)
    plt.subplot(1,1,1)
    plt.plot(range(5),range(5))
    plt.savefig('halign-' + direction + '.png')
```

**Actual outcome**

`horizontalalignment='left'`:
![](https://adamsgaard.dk/files_nonpub/halign-left.png)

`horizontalalignment='center'`:
![](https://adamsgaard.dk/files_nonpub/halign-center.png)

`horizontalalignment='right'`:
![](https://adamsgaard.dk/files_nonpub/halign-right.png)

**Expected outcome**

`horizontalalignment='left'`:
![](https://adamsgaard.dk/files_nonpub/halign-right.png)

`horizontalalignment='center'`:
![](https://adamsgaard.dk/files_nonpub/halign-center.png)

`horizontalalignment='right'`:
![](https://adamsgaard.dk/files_nonpub/halign-left.png)

**Matplotlib version**
  * Operating system: Tested on OpenBSD (6.6) and Void Linux (x86_64, glibc)
  * Matplotlib version: Tested on 2.2.4, 3.1.0, 3.1.1, 3.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): GTK3Agg and agg
  * Python version: Tested on 3.7.4 and 3.6.9
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

Matplotlib and Python are installed through the Void linux and OpenBSD distribution packages.

**Comment by anntzer** [comment] 2019-11-27 12:48
This is essentially a duplicate of https://github.com/matplotlib/matplotlib/issues/12197 AFAICT, see discussion there.

**Closed by anntzer** 2019-11-27 12:48 UTC
