### ISSUE TITLE
[Bug]: x spacing of bars seems off

### ISSUE THREAD

**Issue by haferburg** [matplotlib/matplotlib#24154] opened 2022-10-13 13:58 UTC
### Bug summary

In a plot with only two bars, the spacing of the bars is strange. It seems like the layout is done as if there were three bars, but the bar in the middle is missing.

For n bars I would expect the space to be divided into n sections of equal size, one for each bar, and the bars to be centered in their section.

I think this has something to do with the `width` parameter. It works as expected if width is 1, but the spacing becomes stranger and stranger the smaller the width.

width = 1
![image](https://user-images.githubusercontent.com/4941909/195618362-223cfab3-a79d-4970-8a15-1aaa85f0fa2a.png)

width = 0.1
![image](https://user-images.githubusercontent.com/4941909/195625689-acd860ac-fab2-4b7f-8670-736a0a8b2c02.png)

### Code for reproduction

```python
import matplotlib.pyplot as plt


labels = ['G1', 'G2']
men_means = [20, 35]
women_means = [25, 32]
men_std = [2, 3]
women_std = [3, 5]
width = 0.35       # the width of the bars: can also be len(x) sequence

fig, ax = plt.subplots()

ax.bar(labels, men_means, width, yerr=men_std, label='Men')
ax.bar(labels, women_means, width, yerr=women_std, bottom=men_means,
       label='Women')

ax.set_ylabel('Scores')
ax.set_title('Scores by group and gender')
ax.legend()

plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/4941909/195579505-d7eb2cc9-57ec-433b-b135-bb3eef6f0d2b.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/4941909/195616425-4dd4fe82-2ea5-44d9-92ba-4162f0d6dd50.png)

### Matplotlib Version

3.6.0

**Comment by jklymak** [comment] 2022-10-13 14:57
The spacing is just adding a "margin" to the edge of the first and last bar.  This behaviour is the same as our other plot types. I doubt we will add different margin behaviour just for bars, indeed I'm not sure there is a mechanism for doing so.  Currently users can fix this manually if they don't like the automatic settings.  As you note, bars have a lot of adjustable parameters that make automatically spacing extremely difficult in all situations.

**Comment by timhoffm** [comment] 2022-10-15 19:32
I agree that margins do not look so nice in the 2-bar case. However, this is quite a complicated aesthetics thing: I think the whitespace in the center is the visual issue. This would already be different if there was something in between, e.g.
![image](https://user-images.githubusercontent.com/2836374/196004443-e7d13748-151b-4205-a017-5af17eb47249.png)

So the problem is quite subtle and our layout mechanism will not be able to detect and handle such special cases. I therefore close this as "can't fix".

@haferburg Sorry that we don't have a better solution. I recommend to set the xlims manual for this case:
```
ax.set_xlim(0 - 2*width, len(labels) -1 +2*width)
```
seems a good choice.

**Closed by timhoffm** 2022-10-15 19:32 UTC
