### ISSUE TITLE
[Bug]: Improper edges of half-filled triangular markers

### ISSUE THREAD

**Issue by ktgeier** [matplotlib/matplotlib#28547] opened 2024-07-12 09:28 UTC
### Bug summary

Half-filled triangular markers with edges have strange crown-like features at the top.

### Code for reproduction

```Python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

ax.plot(
    0.5,
    0.5,
    linestyle="none",
    marker="^",
    markersize=50,
    markerfacecolor="tab:red",
    markerfacecoloralt="tab:blue",
    markeredgecolor="black",
    markeredgewidth=5,
    fillstyle="left",
)

plt.show()
```

### Actual outcome

![Figure_1](https://github.com/user-attachments/assets/99a5b42b-2adc-435a-afc0-e87cc4ac1b8f)

### Expected outcome

There should be no little "crown" at the top.

### Operating system

Manjaro

### Matplotlib Version

3.8.4

### Matplotlib Backend

QtAgg

### Python version

Python 3.12.4

### Jupyter version

4.0.11

### Installation

conda

**Comment by timhoffm** [comment] 2024-07-12 12:08
Thanks for the report. This is a duplicate of #14357.

**Closed by timhoffm** 2024-07-12 12:08 UTC
Labels: status: duplicate
