### ISSUE TITLE
Matplotlib scientific axis notation (exponential) fails to reappear

### ISSUE THREAD

**Issue by WhatWheatleySaid** [matplotlib/matplotlib#13638] opened 2019-03-09 00:23 UTC
### Bug report

Not sure if its the TK backend or matplotlib, but I couldn't reproduce this without TK. When you set the visibillity of the ticklabels to False and then to True again and exponential shift is active, the exponent ( in this case 1e9) disappears for the corresponding axis but does not reappear with visibile=True

when you try to draw what the example shows without TK embedding and just set visible= False and True again, the ticklabels actually disappear too

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import tkinter
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
class app:
    def __init__(self,master):
        self.master = master
        self.fig = plt.figure()
        self.canvas = FigureCanvasTkAgg(self.fig, master=self.master)
        self.ax = self.fig.gca(projection = '3d',proj_type = 'ortho')
        self.canvas.get_tk_widget().pack()
        self.master.protocol("WM_DELETE_WINDOW", self.on_closing)
        self.ax.plot([-1e9,1e9],[-1e9,1e9],[-1e9,1e9])
        tkinter.Button(master=self.master,text='TOP', command=self.change_view).pack()
        self.view_cid = None

    def change_view(self):
        self.ax.view_init(90,-90)
        self.axis_visibility(event = None,visible=False)
        self.view_cid = self.fig.canvas.mpl_connect('draw_event',lambda event: self.axis_visibility(event,visible=True))
        self.canvas.draw()

    def axis_visibility(self,event,visible):
        self.ax.set_zticklabels(self.ax.get_zticklabels(),visible=visible)
        if self.view_cid != None:
            self.fig.canvas.mpl_disconnect(self.view_cid)

    def on_closing(self):
        self.master.quit()

if __name__ == '__main__':
    root = tkinter.Tk()
    gui = app(root)
    root.mainloop()
```

**Actual outcome**

[https://imgur.com/VnyOBaj](https://imgur.com/VnyOBaj)

**Expected outcome**
[https://imgur.com/3UB1rIk](https://imgur.com/3UB1rIk)

  * Operating system: Ubuntu 18.04 LTS
  * Matplotlib version: 3.0.3
  * Matplotlib backend: TkAgg
  * Python version: 3.6.7
  * Other libraries: -

i used pip3 to install matplotlib

**Comment by ImportanceOfBeingErnest** [comment] 2019-03-11 15:25
I'm a bit confused. Does this depend on the use of tk for embedding, or does it not? I think it would help seeing the pure matplotlib code that does (or does not?) work as expected.

**Comment by koba1312** [comment] 2019-03-11 19:45
like i wrote, without the embedding something different (but also unexpected) seems to happen:
```python
import matplotlib.pyplot as plt
import matplotlib
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.gca(projection = '3d',proj_type = 'ortho')
ax.plot([-1e9,1e9],[-1e9,1e9],[-1e9,1e9])
ax.view_init(90,-90)

ax.set_zticklabels(ax.get_zticklabels(),visible=False)
fig.canvas.draw()
ax.set_zticklabels(ax.get_zticklabels(),visible=True)
fig.canvas.draw()
plt.show()

```

this should produce the same, but when executed, the tick labels are completly gone and not only the scientific exponent

**Comment by anntzer** [comment] 2020-01-02 23:23
FWIW I cannot repro with tkagg and either 3.0.3 or master.

**Comment by QuLogic** [comment] 2020-03-09 07:15
I'm not sure why you can't reproduce.

On `master` and 3.2.0, the problem is that once you have set the labels to be invisible, then `ax.get_zticklabels` returns nothing, so you aren't really toggling anything back on. A better approach would be to use `ax.zaxis.set_tick_params(label1On=False/True)`, but unfortunately that does not affect the offset. To modify the offset, you can use `ax.zaxis.offsetText.set_visible(True/False)`.

**Comment by QuLogic** [comment] 2020-09-01 21:10
With #16896, `Axis.set_tick_params(label1On=False/True)` now affects the offset text, so I'm going to close this, as that is the best way to affect tick visibility.

**Closed by QuLogic** 2020-09-01 21:10 UTC
Labels: GUI/tk, Needs confirmation, mplot3d
