### ISSUE TITLE
Matplotlib backend does not detect pygtk

### ISSUE THREAD

**Issue by homocomputeris** [matplotlib/matplotlib#11747] opened 2018-07-23 10:07 UTC
### Bug report
I use PyCharm. For some reasons, it fails to show plots with the default Qt5Agg backend. I tried to use GTK,  but it fails even in IPython 6.4 (without PyCharm), although I have PyGTK.

**Code for reproduction**

```python
import matplotlib
matplotlib.use('GTK')
import matplotlib.pyplot as plt

```

**Actual outcome**

```python
import matplotlib.pyplot as plt
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/usr/lib/python3.6/site-packages/matplotlib/backends/backend_gtk.py in <module>()
     16 try:
---> 17     import gobject
     18     import gtk; gdk = gtk.gdk

ModuleNotFoundError: No module named 'gobject'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-3-a0d2faabd9e9> in <module>()
----> 1 import matplotlib.pyplot as plt

/usr/lib/python3.6/site-packages/matplotlib/pyplot.py in <module>()
    113 ## Global ##
    114 
--> 115 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    116 
    117 _IP_REGISTERED = None

/usr/lib/python3.6/site-packages/matplotlib/backends/__init__.py in pylab_setup(name)
     60     # imports. 0 means only perform absolute imports.
     61     backend_mod = __import__(backend_name, globals(), locals(),
---> 62                              [backend_name], 0)
     63 
     64     # Things we pull in from all backends

/usr/lib/python3.6/site-packages/matplotlib/backends/backend_gtk.py in <module>()
     19     import pango
     20 except ImportError:
---> 21     raise ImportError("Gtk* backend requires pygtk to be installed.")
     22 
     23 pygtk_version_required = (2,4,0)

ImportError: Gtk* backend requires pygtk to be installed.

```

**Expected outcome**

Plot window

**Matplotlib version**

  * Operating system: Linux box 4.17.8-1-ARCH
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): GTK
  * Python version: 3.6.6
  * Jupyter version (if applicable):
  * Other libraries: 
local/gobject-introspection-runtime 1.56.1-1
local/gtk2 2.24.32-1
local/gtk3 3.22.30-1
local/pygobject-devel 3.28.3-1
local/pygobject2-devel 2.28.7-1
local/python-gobject 3.28.3-1
local/python2-gobject2 2.28.7-1
PyGTK 2.24.0:
```
pygtk /usr/
pygtk /usr/bin/
pygtk /usr/bin/pygtk-codegen-2.0
pygtk /usr/bin/pygtk-demo
pygtk /usr/include/
pygtk /usr/include/pygtk-2.0/
pygtk /usr/include/pygtk-2.0/pygtk/
pygtk /usr/include/pygtk-2.0/pygtk/pygtk.h
pygtk /usr/lib/
pygtk /usr/lib/pkgconfig/
pygtk /usr/lib/pkgconfig/pygtk-2.0.pc
pygtk /usr/lib/pygtk/
pygtk /usr/lib/pygtk/2.0/
pygtk /usr/lib/pygtk/2.0/demos/
pygtk /usr/lib/pygtk/2.0/demos/__init__.py
pygtk /usr/lib/pygtk/2.0/demos/__init__.pyc
pygtk /usr/lib/pygtk/2.0/demos/__init__.pyo
pygtk /usr/lib/pygtk/2.0/demos/appwindow.py
pygtk /usr/lib/pygtk/2.0/demos/appwindow.pyc
pygtk /usr/lib/pygtk/2.0/demos/appwindow.pyo
pygtk /usr/lib/pygtk/2.0/demos/buttonbox.py
pygtk /usr/lib/pygtk/2.0/demos/buttonbox.pyc
pygtk /usr/lib/pygtk/2.0/demos/buttonbox.pyo
pygtk /usr/lib/pygtk/2.0/demos/changedisplay.py
pygtk /usr/lib/pygtk/2.0/demos/changedisplay.pyc
pygtk /usr/lib/pygtk/2.0/demos/changedisplay.pyo
pygtk /usr/lib/pygtk/2.0/demos/colorsel.py
pygtk /usr/lib/pygtk/2.0/demos/colorsel.pyc
pygtk /usr/lib/pygtk/2.0/demos/colorsel.pyo
pygtk /usr/lib/pygtk/2.0/demos/dialogs.py
pygtk /usr/lib/pygtk/2.0/demos/dialogs.pyc
pygtk /usr/lib/pygtk/2.0/demos/dialogs.pyo
pygtk /usr/lib/pygtk/2.0/demos/dnd.py
pygtk /usr/lib/pygtk/2.0/demos/dnd.pyc
pygtk /usr/lib/pygtk/2.0/demos/dnd.pyo
pygtk /usr/lib/pygtk/2.0/demos/dndpixmap.py
pygtk /usr/lib/pygtk/2.0/demos/dndpixmap.pyc
pygtk /usr/lib/pygtk/2.0/demos/dndpixmap.pyo
pygtk /usr/lib/pygtk/2.0/demos/editable_cells.py
pygtk /usr/lib/pygtk/2.0/demos/editable_cells.pyc
pygtk /usr/lib/pygtk/2.0/demos/editable_cells.pyo
pygtk /usr/lib/pygtk/2.0/demos/entry_completion.py
pygtk /usr/lib/pygtk/2.0/demos/entry_completion.pyc
pygtk /usr/lib/pygtk/2.0/demos/entry_completion.pyo
pygtk /usr/lib/pygtk/2.0/demos/expander.py
pygtk /usr/lib/pygtk/2.0/demos/expander.pyc
pygtk /usr/lib/pygtk/2.0/demos/expander.pyo
pygtk /usr/lib/pygtk/2.0/demos/hypertext.py
pygtk /usr/lib/pygtk/2.0/demos/hypertext.pyc
pygtk /usr/lib/pygtk/2.0/demos/hypertext.pyo
pygtk /usr/lib/pygtk/2.0/demos/images.py
pygtk /usr/lib/pygtk/2.0/demos/images.pyc
pygtk /usr/lib/pygtk/2.0/demos/images.pyo
pygtk /usr/lib/pygtk/2.0/demos/images/
pygtk /usr/lib/pygtk/2.0/demos/images/alphatest.png
pygtk /usr/lib/pygtk/2.0/demos/images/apple-red.png
pygtk /usr/lib/pygtk/2.0/demos/images/background.jpg
pygtk /usr/lib/pygtk/2.0/demos/images/floppybuddy.gif
pygtk /usr/lib/pygtk/2.0/demos/images/gnome-applets.png
pygtk /usr/lib/pygtk/2.0/demos/images/gnome-calendar.png
pygtk /usr/lib/pygtk/2.0/demos/images/gnome-foot.png
pygtk /usr/lib/pygtk/2.0/demos/images/gnome-gimp.png
pygtk /usr/lib/pygtk/2.0/demos/images/gnome-gmush.png
pygtk /usr/lib/pygtk/2.0/demos/images/gnome-gsame.png
pygtk /usr/lib/pygtk/2.0/demos/images/gnu-keys.png
pygtk /usr/lib/pygtk/2.0/demos/images/gtk-logo-rgb.gif
pygtk /usr/lib/pygtk/2.0/demos/infobar.py
pygtk /usr/lib/pygtk/2.0/demos/infobar.pyc
pygtk /usr/lib/pygtk/2.0/demos/infobar.pyo
pygtk /usr/lib/pygtk/2.0/demos/list_store.py
pygtk /usr/lib/pygtk/2.0/demos/list_store.pyc
pygtk /usr/lib/pygtk/2.0/demos/list_store.pyo
pygtk /usr/lib/pygtk/2.0/demos/menu.py
pygtk /usr/lib/pygtk/2.0/demos/menu.pyc
pygtk /usr/lib/pygtk/2.0/demos/menu.pyo
pygtk /usr/lib/pygtk/2.0/demos/panes.py
pygtk /usr/lib/pygtk/2.0/demos/panes.pyc
pygtk /usr/lib/pygtk/2.0/demos/panes.pyo
pygtk /usr/lib/pygtk/2.0/demos/pixbufs.py
pygtk /usr/lib/pygtk/2.0/demos/pixbufs.pyc
pygtk /usr/lib/pygtk/2.0/demos/pixbufs.pyo
pygtk /usr/lib/pygtk/2.0/demos/print_editor.py
pygtk /usr/lib/pygtk/2.0/demos/print_editor.pyc
pygtk /usr/lib/pygtk/2.0/demos/print_editor.pyo
pygtk /usr/lib/pygtk/2.0/demos/sizegroup.py
pygtk /usr/lib/pygtk/2.0/demos/sizegroup.pyc
pygtk /usr/lib/pygtk/2.0/demos/sizegroup.pyo
pygtk /usr/lib/pygtk/2.0/demos/statusicon.py
pygtk /usr/lib/pygtk/2.0/demos/statusicon.pyc
pygtk /usr/lib/pygtk/2.0/demos/statusicon.pyo
pygtk /usr/lib/pygtk/2.0/demos/stock_browser.py
pygtk /usr/lib/pygtk/2.0/demos/stock_browser.pyc
pygtk /usr/lib/pygtk/2.0/demos/stock_browser.pyo
pygtk /usr/lib/pygtk/2.0/demos/textscroll.py
pygtk /usr/lib/pygtk/2.0/demos/textscroll.pyc
pygtk /usr/lib/pygtk/2.0/demos/textscroll.pyo
pygtk /usr/lib/pygtk/2.0/demos/textview.py
pygtk /usr/lib/pygtk/2.0/demos/textview.pyc
pygtk /usr/lib/pygtk/2.0/demos/textview.pyo
pygtk /usr/lib/pygtk/2.0/demos/tooltip.py
pygtk /usr/lib/pygtk/2.0/demos/tooltip.pyc
pygtk /usr/lib/pygtk/2.0/demos/tooltip.pyo
pygtk /usr/lib/pygtk/2.0/demos/tree_store.py
pygtk /usr/lib/pygtk/2.0/demos/tree_store.pyc
pygtk /usr/lib/pygtk/2.0/demos/tree_store.pyo
pygtk /usr/lib/pygtk/2.0/demos/treemodel.py
pygtk /usr/lib/pygtk/2.0/demos/treemodel.pyc
pygtk /usr/lib/pygtk/2.0/demos/treemodel.pyo
pygtk /usr/lib/pygtk/2.0/demos/ui_manager.py
pygtk /usr/lib/pygtk/2.0/demos/ui_manager.pyc
pygtk /usr/lib/pygtk/2.0/demos/ui_manager.pyo
pygtk /usr/lib/pygtk/2.0/pygtk-demo.py
pygtk /usr/lib/pygtk/2.0/pygtk-demo.pyc
pygtk /usr/lib/pygtk/2.0/pygtk-demo.pyo
pygtk /usr/lib/python2.7/
pygtk /usr/lib/python2.7/site-packages/
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/atk.so
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.pyc
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.pyo
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/_gtk.so
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/_lazyutils.py
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/_lazyutils.pyc
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/_lazyutils.pyo
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/compat.py
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/compat.pyc
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/compat.pyo
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/deprecation.py
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/deprecation.pyc
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/deprecation.pyo
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/glade.so
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/keysyms.py
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/keysyms.pyc
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtk/keysyms.pyo
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/gtkunixprint.so
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/pango.so
pygtk /usr/lib/python2.7/site-packages/gtk-2.0/pangocairo.so
pygtk /usr/share/
pygtk /usr/share/pygtk/
pygtk /usr/share/pygtk/2.0/
pygtk /usr/share/pygtk/2.0/defs/
pygtk /usr/share/pygtk/2.0/defs/atk-types.defs
pygtk /usr/share/pygtk/2.0/defs/atk.defs
pygtk /usr/share/pygtk/2.0/defs/gdk-2.10.defs
pygtk /usr/share/pygtk/2.0/defs/gdk-2.12.defs
pygtk /usr/share/pygtk/2.0/defs/gdk-2.14.defs
pygtk /usr/share/pygtk/2.0/defs/gdk-2.16.defs
pygtk /usr/share/pygtk/2.0/defs/gdk-2.18.defs
pygtk /usr/share/pygtk/2.0/defs/gdk-2.20.defs
pygtk /usr/share/pygtk/2.0/defs/gdk-2.22.defs
pygtk /usr/share/pygtk/2.0/defs/gdk-2.24.defs
pygtk /usr/share/pygtk/2.0/defs/gdk-base-types.defs
pygtk /usr/share/pygtk/2.0/defs/gdk-base.defs
pygtk /usr/share/pygtk/2.0/defs/gdk-types.defs
pygtk /usr/share/pygtk/2.0/defs/gdk.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.10-types.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.10.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.12-types.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.12.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.14-types.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.14.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.16-types.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.16.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.18-types.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.18.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.20-types.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.20.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.22-types.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.22.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.24-types.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-2.24.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-base-types.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-base.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-extrafuncs.defs
pygtk /usr/share/pygtk/2.0/defs/gtk-types.defs
pygtk /usr/share/pygtk/2.0/defs/gtk.defs
pygtk /usr/share/pygtk/2.0/defs/gtkunixprint-2.12.defs
pygtk /usr/share/pygtk/2.0/defs/gtkunixprint-2.14.defs
pygtk /usr/share/pygtk/2.0/defs/gtkunixprint-base-types.defs
pygtk /usr/share/pygtk/2.0/defs/gtkunixprint-base.defs
pygtk /usr/share/pygtk/2.0/defs/libglade.defs
pygtk /usr/share/pygtk/2.0/defs/pango-types.defs
pygtk /usr/share/pygtk/2.0/defs/pango.defs
pygtk /usr/share/pygtk/2.0/defs/pangocairo.defs
pygtk /usr/share/pygtk/2.0/defs/pangocairo.override
```

**Comment by homocomputeris** [comment] 2018-07-23 22:54
As issue has been labeled 'Py2-only': shouldn't GTK backends work in Python 3 for at least GTK3? It seems there are some fallback problem, `because matplotlib.use('GTK3Agg')` works.

**Comment by anntzer** [comment] 2018-07-24 07:59
There has never been a fallback, the gtk(agg) and gtk3(agg) backends are conceptually completely independent from one another, and gtk(agg) will not be supported on Py3.

Actually I see from your traceback that you were trying to use this on Py3 so this was indeed never going to work.  Closing as "not a bug", but feel free to ask if you have more questions.

**Closed by anntzer** 2018-07-24 07:59 UTC

**Comment by homocomputeris** [comment] 2018-07-29 12:51
Thanks.
How do I know which are compatible with Python3?

**Comment by anntzer** [comment] 2018-07-29 19:37
See https://matplotlib.org/tutorials/introductory/usage.html#what-is-a-backend: everything works with Py3, except gtkagg/gtkcairo which are clearly marked py2-only.
