### ISSUE TITLE
Column direction breaks label mode L for AxesGrid.

### ISSUE THREAD

**Issue by svaberg** [matplotlib/matplotlib#20640] opened 2021-07-13 04:23 UTC
### Bug report

The `direction="column"` setting appears to break the `label_mode="L"` option for `AxesGrid`.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import mpl_toolkits

fig = plt.figure()
grid = mpl_toolkits.axes_grid1.AxesGrid(fig, 111, nrows_ncols=(2,3), 
   axes_pad=.3, direction="column", label_mode="L")
plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/3267619/125389727-053f9100-e3e5-11eb-865f-dd7140093dcc.png)

**Expected outcome**
![image](https://user-images.githubusercontent.com/3267619/125389873-3cae3d80-e3e5-11eb-9af4-6522189ed7db.png)

**Matplotlib version**

  * Operating system: MacOS 10.15.7
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.8.6
  * Jupyter version (if applicable):  6.1.5
  * Other libraries: 

Installed with conda

**Comment by svaberg** [comment] 2021-07-13 04:24
The title was supposed to be 'Column direction breaks label mode L for AxesGrid'.

**Comment by QuLogic** [comment] 2021-07-13 06:14
Duplicate of #20372.

**Closed by QuLogic** 2021-07-13 06:14 UTC
