### ISSUE TITLE
How to speed up Display in Python using FIgureCanvasTKAgg()

### ISSUE THREAD

**Issue by Aishwarya1708** [matplotlib/matplotlib#11371] opened 2018-06-04 13:37 UTC
### Bug report

**Bug summary**
I have 2 files created, one a .pyx file with a class named AndorCamersSDK which has a function named LiveAcquisition(). The second file, a .py file with a Class AndorCameraGUI which makes use of Tkinter to create a GUI. This class has function LivePlot(), and RepeatPlot().Inside LiveAcquisition() I am acquiring N number of frames and after acquiring each frame I need to display it using  LivePlot() and RepeatPlot(). Without the display, just acquiring and storing for 300 frames takes 6.2 for execution, which is fine by me. But When I start displaying even for 100 frames it takes 54sec. I need to acquire and display within 6 sec for 300 frames. How do I solve this?

**Code for reproduction**

```python
# File 1: .pyx code ; Present inside class AndorCameraSDK
          def  LiveAcquisition(self):
                        for i in range(no_of_frames): 
			           data[i,:,:] = PyArray_NewFromDescr(<PyTypeObject *> np.ndarray, np.dtype('<H'), 2,dims, strides,pBuf, np.NPY_C_CONTIGUOUS, None)
			           if (i==0):
				               self.master.LivePlot(data[i,:,:])
			           elif (i==2) or (i==15) or (i ==65) or (i ==96):
				               self.master.RepeatPlot(data[i,:,:])
			           else:
				               pass


# File 2 : .py code; Below functions are present inside a class named AndorCameraGUI
          def LivePlot(self,image):
		        self.count = 0
		        self.fig = Figure(figsize = (4, 5))
		        self.fig.patch.set_facecolor('xkcd:light grey') # When this is removed a white color is seen in the background of the figure
		        self.a = self.fig.add_subplot(111)
		        self.a.set_xlim([0, self.image_width/int(self.HBin)])
		        self.a.set_ylim([0, self.image_height/int(self.VBin)])
		        image = image.transpose()
		        self.a.imshow(image,'gray')
		        self.canvas = FigureCanvasTkAgg(self.fig,self.master)
		        self.canvas.draw()
		        self.canvas.get_tk_widget().pack(side =LEFT)
		        self.toolbar = NavigationToolbar2TkAgg(self.canvas,self.master)
		        self.toolbar.update()
		        self.canvas._tkcanvas.pack(side = LEFT)# change this to TOP so thee the navigation toolbar on the left down

	 def RepeatPlot(self,image):
		        image = image.transpose()
		        self.a.imshow(image,'gray')
		        self.canvas.draw()






```

**Matplotlib version**

  * Operating system: Linux 16.04
  * Matplotlib version:  2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):Qt5Agg
  * Python version: 2.7
  * Jupyter version (if applicable):
  * Other libraries: Cython

**Comment by ImportanceOfBeingErnest** [comment] 2018-06-04 13:50
You may use blitting to update the image. If you need help with that it may be a good idea to ask a specific question on the mailing list or stackoverflow. (But make sure to have looked at some available resources first.)  
This is the Issue tracker where issues with and improvements of the library itself are discussed.

**Comment by tacaswell** [comment] 2018-06-05 00:58
You should be setting the data on the `AxesImage` instance returned by `imshow` via `im.set_data`.  As implemented, this is going to get slower over time as the previous N-1 images are rendered and then covered before your final image is displayed.

If that is still not fast enough, then blitting is the next tool to pull out.

**Comment by tacaswell** [comment] 2018-06-05 00:59
Closing as this is not a bug in matplotlib.  If you need further help, I suggest sending the question to the mailing list (https://mail.python.org/mailman/listinfo/matplotlib-users you will have to register to post un-moderated).

**Closed by tacaswell** 2018-06-05 00:59 UTC
