### ISSUE TITLE
xkcd plots rendered as regular plots on Mac OS X

### ISSUE THREAD

**Issue by mario-grgic** [matplotlib/matplotlib#5442] opened 2015-11-08 21:11 UTC
This is with Python 2.7.10 and matplotlib 1.5.0 on Mac OS X 10.11.1. All xkcd plots render as regular plots.

**Comment by DanHickstein** [comment] 2015-11-10 16:25
Does switching backends help? 
https://github.com/matplotlib/matplotlib/issues/2269/

**Comment by mario-grgic** [comment] 2015-11-10 23:38
Yes, if I save the plot as pdf or use CocoaAgg backend, it looks right. It looks like the default MacOSX backend has a problem.

**Comment by tacaswell** [comment] 2015-11-11 04:32
@mario-grgic Is regression from 1.4.3?

attn @mdehoon

**Comment by jenshnielsen** [comment] 2015-11-11 09:24
It's not a regression. It doesn't work with the OSX backend in 1.4.3 either.

**Comment by mario-grgic** [comment] 2015-11-11 13:40
In 1.4.3 xkcd plots failed with error described in Issue #5049.

**Comment by mdehoon** [comment] 2015-11-12 05:41
With matplotlib 1.5.0 using the gtkcairo backend, the xkcd plots also render as regular plots. @mario-grgic  can you identify exactly where in the xkcd code the difference between agg/pdf and macosx/gtkcairo occurs?

**Comment by mdboom** [comment] 2015-11-12 13:10
The "sketched line" functionality happens in the path iterator code (`src/path_converters.h`).  The macosx backend interacts with that code through a C wrapper around the C++ (`src/path_cleanup.cpp`) that hasn't been updated to expose the sketch functionality.  We'd need to both update that wrapper and then update the macosx backend to pass along the sketch parameters from the gc to that.  I can probably hack that together when I have time.

The Cairo backend is different -- since it's currently 100% Python (outside of the third-party Cairo wrapper), it doesn't use the path iterator code.  Doing so would require a lot more overhead, but it's doable, and we do actually already expose the path iterators to Python through `_path.cleanup_path`.

**Comment by mdehoon** [comment] 2015-11-13 01:47
@mdboom  OK, when you're done, I can have have a look at the macosx backend side of things.

**Comment by mdboom** [comment] 2016-03-21 18:36
Fixed by #6178.

**Closed** 2016-03-28 19:16 UTC
Labels: GUI/osx, needs_review
