### ISSUE TITLE
mathtext.py bra-ket notation axes

### ISSUE THREAD

**Issue by pederico** [matplotlib/matplotlib#3374] opened 2014-08-17 15:17 UTC
When using qutip, which has mathtext.py in the backend, after setting on an axis the label '$\left|-\right>$' the text is not shown

For the label '$\left|\minus\right>$' only a minus sign is shown. It could be that the \left \right symbols are too small to be seen.

The label '$\left|+\right>$' is shown without any problem, and any other symbol instead of -, also.

**Comment by jfeist** [comment] 2015-02-25 09:01
After #4147 was fixed, I checked if this one is also fixed, and it seems it is not. On current master, the following example produces a png, pdf and svg where the `\left|` and `\right\rangle` characters are missing around the minus signs. Furthermore, I realized that the problem is the same in the interactive backends (at least MacOSX and Qt4Agg, which are the ones I have available here).
For the plus sign, it works like expected. This is on current master.

```python
import matplotlib
matplotlib.use('MacOSX')
import matplotlib.pyplot as plt
plt.text(0.4,0.6,r'$\left|-\right\rangle$')
plt.text(0.4,0.4,r'$\left|\minus\right\rangle$')

plt.text(0.6,0.6,r'$\left|+\right\rangle$')
plt.text(0.6,0.4,r'$\left|\plus\right\rangle$')

plt.savefig('tmp.png')
plt.savefig('tmp.pdf')
plt.savefig('tmp.svg')
plt.show()
```

**Comment by jfeist** [comment] 2015-03-03 13:14
just pinging @mdboom, @tacaswell because I'm not sure this was seen.

**Comment by tacaswell** [comment] 2015-03-03 13:22
I assume that is a similar problem with the height of the | and > being scaled to almost zero.

**Comment by mdboom** [comment] 2015-03-03 15:03
This is a tricky one.  At the end of the day, I think the metrics on the minus sign are just wrong (it defines a character with negative height).  I guess the best we can do is special case it, but that's icky...  Oh well, I think I can have a fix ready shortly.

**Comment by anntzer** [comment] 2018-01-05 11:00
May be worth checking whether another version of computer modern (http://www.ams.org/publications/type1-fonts, http://cm-unicode.sourceforge.net/) has better metrics.

**Comment by anntzer** [comment] 2020-02-09 15:44
This was actually fixed by https://github.com/matplotlib/matplotlib/pull/5871.

**Closed by anntzer** 2020-02-09 15:44 UTC
Labels: text/mathtext
