### ISSUE TITLE
Incorrect plotting for versions > 1.3.1 and GTK.

### ISSUE THREAD

**Issue by migvel** [matplotlib/matplotlib#6856] opened 2016-07-29 12:13 UTC
Hello, 

I'm having an issue plotting a set of points  represented by solid lines, the first point and the last one are always joined(incorrectly) by a solid line.

- This problem happens with the Matplotlib versions above 1.3.1.
- Using GTK as the backend.
- Python 2.7.11
- Both in Linux and windows.

Thanks.
Miguel.

**Comment by afvincent** [comment] 2016-07-29 12:28
@migvel Thank you for reporting the issue. Could you provide a minimal working example please? Furthermore, did you test with other backends than GTK?

**Comment by jenshnielsen** [comment] 2016-07-29 12:40
The GTK backend will be deprecated in Matplotlib 2.0 and has been not recommended to use for a long time. Unless you have some specific dependencies I strongly suggest using GTKAgg or GTKCairo as alternatives. See http://matplotlib.org/faq/usage_faq.html#what-is-a-backend

**Comment by tacaswell** [comment] 2016-07-29 13:39
This maybe fixed in very new version, I have a vauge memory of seeing this before, but I can not find the issue.

The problem is that some backends can not handle paths with commands on the points so we provide a way to simplify them and at some point that the paths were always getting closed.

Closing this issue as "won't fix" due to the backend being deprecated on all active branches.

@migvel We would merge a patch to fix this.

**Closed by tacaswell** 2016-07-29 13:39 UTC
Labels: GUI/gtk, won't fix

**Comment by migvel** [comment] 2016-07-29 13:54
OK, thanks.
