### ISSUE TITLE
Animations in Tkinter window advance non-uniformly

### ISSUE THREAD

**Issue by tj-murphy** [matplotlib/matplotlib#19473] opened 2021-02-07 18:38 UTC
### Bug report

**Bug summary**
When a Tkinter window is created, and multiple Matplotlib animated graphs are inserted into this window, the first animation placed in the window gets updated (gets its animate(i) function) called twice as often as all the others.

**Code for reproduction**

```
import tkinter as tk
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
import matplotlib.animation as animation
import numpy as np

class Graph:
    def __init__(self,tk_root,pos_list):
        self.fig = plt.figure(linewidth=2,edgecolor='black')
        self.ax=self.fig.add_subplot(111)
        canvas = FigureCanvasTkAgg(self.fig, master=tk_root)
        plot_widget = canvas.get_tk_widget()
        x,y,w,h = pos_list
        plot_widget.place(x=x,y=y,w=w,h=h)

        self.line, = self.ax.plot([], [])
        self.xvals = []
        self.yvals = []
        plt.xlim(-10,0.2)
        plt.ylim(-1.1,1.1)
    def animate(self,i):
        print(i)
        self.xvals.append(i/10)
        self.yvals.append(np.sin(i/10))
        self.xvals = self.xvals[-101:]
        self.yvals = self.yvals[-101:]
        self.line.set_data([i-self.xvals[-1] for i in self.xvals],self.yvals)
        return self.line,
root = tk.Tk()
matplotlib.use('TkAgg')

graphs_to_draw = 8
for i in range(graphs_to_draw):
    new_graph = Graph(root,[150*i % 600,i*150//600 * 125,150,100])
    new_anim = animation.FuncAnimation(new_graph.fig,new_graph.animate,interval=1,blit=True)
root.mainloop()
```
**Actual outcome**

8 graphs are produced, as requested. However, it is evident that the first runs twice as fast as all others. Furthermore, in the console output (printed on the first line of the animate function), it is clear that the function is being called twice on that entry for every one time the other entries get called. A sample of console output looks like:

```
97
97
97
97
97
97
97
195
196
98
98
98
98
98
98
98
197
198
99
99
99
99
99
99
99
199
200
```
So it is clear that we get `98` printed 7 times (once for all the normal-functioning graphs), and then we get 197 followed by 198. The frame counter is incrementing twice, and is also at a value that has now reached twice the value of all the others. Every frame is happening twice, but only on the first plot. Note that this is also whichever plot is introduced to the tkinter window first - placement seems to make no difference.
**Expected outcome**
All graphs should perform the same. They're just generated in a for loop and there's no reason one should run so much faster than all the others. Ideally, they would all run at the fast speed, but at the very least the speed should be uniform.

**Matplotlib version**

  * Operating system: `Ubuntu 20.04.2`
  * Matplotlib version: `3.2.1`
  * Matplotlib backend: get_backend() says Qt5Agg, but at the top of my example script I say matplotlib.use('TkAgg'). 
  * Python version: 3.8.4
  * Jupyter version (if applicable): Nope 
  * Other libraries: Only tkinter (built into python). I also import numpy here, but that doesn't seem relevant since I'm just getting a sine.

I think Python comes with Ubuntu. Matplotlib was installed through pip.

**Comment by tj-murphy** [comment] 2021-02-07 18:40
It's very possible this issue is more tkinter's fault, but as that library is built into python, it doesn't seem to have a github issues page for me to report this. Happy to take this to other channels if somewhere else is more appropriate but I'm not sure where that would be.

**Comment by anntzer** [comment] 2021-02-12 13:22
Can you please try with more recent releases?  I tried with master and could not reproduce the issue; there has been some movement both in animations and in tk since 3.2.1.

**Comment by tj-murphy** [comment] 2021-02-12 21:27
I did `pip3 install --upgrade matplotlib` which took me up to 3.3.4.

Now when I run my test script as pasted above, only the last plot actually draws, and the terminal output just counts up by 1 constantly (no repeated numbers at all). The first 7 instantiated animations just give blank white plots with axes.

**Comment by tj-murphy** [comment] 2021-02-13 02:52
Okay, I've gone through all the releases between those two. Any 3.2.X gives the original behavior I described where the first plot goes twice as fast as all the others. Any 3.3.X gives the same as 3.3.4 where only the last one does anything at all. Would it be worth testing older versions?

**Comment by tj-murphy** [comment] 2021-02-13 06:21
Continuing to provide debugging data - I've managed to make a version of my test script which works with PyQt5 (as opposed to Tkinter). That script runs under Matplotlib 3.2.1 smoothly - no issue of the doubled-speed first graph (though all of the graphs run slowly). But when I update to 3.3.4, I get totally empty plots.

To be clear here, my ultimate goal is that I want to be able to plot readings from a few sensors connected over a serial port (well, USB, but you get the idea) and graph them all simultaneously in separate graphs. So I want to tile these matplotlib plots into a window so I can view them all in a GUI at once. Is there a better way to achieve what I want, at a high update rate?

Here's the PyQt5 version of my test script:

`from matplotlib import animation
import matplotlib.pyplot as plt
import numpy as np
import sys, matplotlib
from PyQt5 import QtWidgets, QtCore
from matplotlib.backends.backend_qt5agg import (FigureCanvas, NavigationToolbar2QT as NavigationToolbar)

class Graph(FigureCanvas):
    def __init__(self,parent=None):
        self.fig = plt.figure(linewidth=2,edgecolor='black')
        self.ax=self.fig.add_subplot(111)
        FigureCanvas.__init__(self, self.fig)
        self.setParent(parent)
        self.line, = self.ax.plot([], [])
        self.xvals = []
        self.yvals = []
        plt.xlim(-10,0.2)
        plt.ylim(-1.1,1.1)
        
    def animate(self,i):
        print(i)
        self.xvals.append(i/10)
        self.yvals.append(np.sin(i/10))
        self.xvals = self.xvals[-101:]
        self.yvals = self.yvals[-101:]
        self.line.set_data([i-self.xvals[-1] for i in self.xvals],self.yvals)
        return self.line,
    
class ApplicationWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self._main = QtWidgets.QWidget()
        self.setCentralWidget(self._main)
        self.setFixedSize(750,750)
        self.make_graphs(8)
        
    def make_graphs(self,graph_count):
        anims = []
        for i in range(graph_count):
            new_graph = Graph(self)
            new_graph.setGeometry(150*i % 600,i*150//600 * 125,150,100)
            new_anim = animation.FuncAnimation(new_graph.fig,new_graph.animate,interval=1,blit=True)
            anims += [new_anim]

if __name__ == "__main__":
    qapp = QtWidgets.QApplication(sys.argv)
    app = ApplicationWindow()
    app.show()
    qapp.exec_()
`

**Comment by anntzer** [comment] 2021-02-13 11:19
On master you get
> UserWarning: Animation was deleted without rendering anything. This is most likely unintended. To prevent deletion, assign the Animation to a variable that exists for as long as you need the Animation.

and indeed appending the animations to a global list (`anims.append(new_anim)`) to prevent them from being deleted fixes the problem.

(Actually you also need to increase the interval a bit, looks like 1ms is too fast for the tk event loop.)

**Comment by tj-murphy** [comment] 2021-02-13 17:10
Using my original tkinter script, changing the interval to 20 ms, and adding each animation to a list of animations, I can now run my script under 3.3.4 and see all 8 plots.

However, now even in 3.3.4 I'm getting the first-one-runs-double-fast behavior.

**Comment by anntzer** [comment] 2021-02-13 18:07
I tried with 3.3.4.  I can indeed repro the bug there, but it has apparently been fixed in master as it's not present there anymore.
3.4 should be released in the coming weeks so I'll close this on the assumption that the bug has indeed been fixed, but feel free to ping to reopen if this is still present after you get to try the release.

**Closed by anntzer** 2021-02-13 18:07 UTC
Labels: GUI/tk, status: needs confirmation, topic: animation
