### ISSUE TITLE
PatchCollection with one patch disappears when zooming in too much

### ISSUE THREAD

**Issue by allthedata** [matplotlib/matplotlib#4033] opened 2015-01-23 23:44 UTC
It seems that a `PatchCollection` with only one patch disappears when using the toolbar at the top of a matplotlib window to zoom in a moderate amount. One workaround is to add an invisible second patch with zero size. I'm running the example in IPython with the PyQt backend in Windows.

Also, not sure if this is intended but when a patch with a transform applied is added directly with `add_patch`, the transformation to data coordinates is not automatically applied. When a `PatchColllection` is added with `add_collection` or a patch without a transform is added with `add_patch`, the transformation is applied.

``` python
%gui qt
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from matplotlib.transforms import Affine2D
from matplotlib.collections import PatchCollection

fig1 = plt.figure()
ax1 = fig1.add_subplot(111)
ax1.set_xlim(0, 5)
ax1.set_ylim(0, 5)
ax1.set_title('rect disappears on zoom')
fig2 = plt.figure()
ax2 = fig2.add_subplot(111)
ax2.set_xlim(0, 5)
ax2.set_ylim(0, 5)
ax2.set_title('rect does not disappear on zoom')
fig3 = plt.figure()
ax3 = fig3.add_subplot(111)
ax3.set_xlim(0, 5)
ax3.set_ylim(0, 5)
ax3.set_title('add_patch requires adding transData to transform')

rect1 = Rectangle((1, 1), 1, 1)
rect2 = Rectangle((0, 0), 0, 0)
rect3 = Rectangle((1, 1), 1, 1)
transform1 = Affine2D().translate(-1,-1).skew_deg(20, 0).translate(1,1)
rect1.set_transform(transform1)
transform3 = Affine2D().translate(-1,-1).skew_deg(20, 0).translate(1,1) + ax3.transData
rect3.set_transform(transform3)

ax1.add_collection(PatchCollection([rect1,]))
fig1.show()
ax2.add_collection(PatchCollection([rect1, rect2]))
fig2.show()
ax3.add_patch(rect3)
fig3.show()
```

**Comment by tacaswell** [comment] 2015-01-25 22:54
I can't reproduce the disappearance on zoom of the rectangle using 1.4.2, what version are you using?

I suspect that `add_patch` not changing the assigned transform of the input patch is a feature not a bug, as is the use of the patch-level form as being on top of the default `PatchCollection` transform.

**Comment by tacaswell** [comment] 2015-01-25 22:54
attn @md

**Comment by allthedata** [comment] 2015-01-26 03:17
I'm using 1.4.2. Strangely, the problem on one computer has gone away after restarting, but is still present on another computer. I'm using the Anaconda distribution on both systems, and all the packages are up to date (python 2.7.8, ipython 2.3.1, numpy 1.9.1, matplotlib 1.4.2, pyqt 4.10.4). The only big difference is that the system with the problem is running Windows 8.1 versus Windows 7 on the other one. Actually it's worse than just the rectangle disappearing, the process hangs and sometimes eats all available memory. This happens whether or not there is a transform applied, what matters is that there is only one item in the `PatchCollection`. Zooming in is also not necessary, running this code below with small limits immediately eats all my memory. There's no exception or anything, but if there's a way for me to give you more information let me know. I tried `pdb` but I wasn't sure what to look for.

````python
%gui qt
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from matplotlib.collections import PatchCollection

fig1 = plt.figure()
ax1 = fig1.add_subplot(111)
ax1.set_xlim(1.9994, 2.0006)
ax1.set_ylim(1.9994, 2.0006)
ax1.set_title('hangs')

rect1 = Rectangle((1, 1), 1, 1)
ax1.add_collection(PatchCollection([rect1]))
fig1.show()
````

**Comment by tacaswell** [comment] 2015-01-26 03:29
attn @jbmohler This is apparently a windows issue, can you take a look.

I wonder if this is related to the `draw` vs `draw_idle` issue from a while ago?

**Comment by tacaswell** [comment] 2015-01-26 03:34
does the windows equivalent of `ctrl-c` work and what function is it in when it dies?

I am personally remarkable useless with regard to windows (have not use it for anything but video games in >10 years...).

This example works fine for me on a linux box (hence why I think this is a windows-specific problem).

**Comment by tacaswell** [comment] 2015-01-26 03:46
@cgohlke Have you come across anything like this/any pointers?

**Comment by Tillsten** [comment] 2015-01-26 03:48
The last example crashes my Win8 machine.

**Comment by tacaswell** [comment] 2015-01-26 04:20
Can someone throw a print statement in to the draw method of `PatchCollection`  and see if it spams you?  I have this worry that there is a draw-related infinite loop going on where something in the draw triggers a re-draw...

**Comment by efiring** [comment] 2015-01-26 06:41
It might not be entirely a Windows problem.  With Anaconda on a Mac, it is taking 3 seconds for the show() to bring up the window.  When I leave out the add_collection() call, and use a simple plot() call instead, it is practically instantaneous.  I've tried this several times and it is quite consistent; I have never gotten a complete hang, just that 3 seconds during which the power consumption as viewed on a Kill-A-Watt indicates heavy use.

The behavior can also be seen by using `%matplotlib qt`, pasting in everything above the `show`, and instead executing `plt.draw()`.  It will take 2-3 seconds to return.

On Linux, the strange thing is that a blue square is displayed in this case even without any `plt.draw()`.  
The square goes from the lower-left corner to the middle of the Axes.  But it's fast, as is the subsequent `draw`, which makes no change to the figure.

Since there is odd behavior--but different behavior on all three platforms--I am taking off the MS label.

**Comment by allthedata** [comment] 2015-01-26 15:09
Ctrl-C also works in Windows IPython. But it's unresponsive with these examples, I have to kill the process with task manager. Also, for the computer that I said didn't have the problem anymore, it is now back. I added a print statement to `mpl.collections.Collections.draw()`, it's not printing more than you would expect (unless it hangs, and then it doesn't print anything).

**Comment by tacaswell** [comment] 2015-07-22 03:48
I can not reproduce any of this on master + python3 + linux.

punting as we still don't know what is wrong and I do not want to block 1.5 on this issue.

**Comment by oscargus** [comment] 2022-06-03 19:49
I tried this now on my Win 10 machine with current `main` and I cannot reproduce any of the errors, so I will close this.

If the problem still appears on some platform, feel free to reopen.

**Closed by oscargus** 2022-06-03 19:49 UTC
Labels: status: confirmed bug, GUI/Qt, topic: path handling
