### ISSUE TITLE
Make documentation builds (more) reproducible

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#10702] opened 2018-03-07 00:39 UTC
We have the ability to pass metadata into pngs (to set the creation time), we should sort make the pngs generated as part of building the documentation use this option (presumably by hacking the `.. plot` directive?).

We should leave the build date in the footer.

**Comment by anntzer** [comment] 2018-03-07 00:54
or just make it respect SOURCE_DATE_EPOCH like pdf and ps do?

**Comment by anntzer** [comment] 2018-03-07 09:15
Hum.  Looks like we can write to the tEXt chunk (e.g. a "Creation Time: ..." entry, but we have no API to write to the tIME chunk, which is actually what we want to do here for determinism...  (https://en.wikipedia.org/wiki/Portable_Network_Graphics#Ancillary_chunks).  If that's indeed the case then the issue becomes much more complex.

**Comment by anntzer** [comment] 2019-09-10 09:14
Actually the pngs generated by matplotlib's png writer (or by pillow, in fact) appear to not set either a Creation Time tEXt chunk or a tIME chunk, so the pngs are  actually reproducible as is (which can be checked by verifying that two pngs with the same content created at different times have the same hash).

Hence I think this can be closed?

**Comment by anntzer** [comment] 2019-09-26 22:21
Closing for lack of further activity.

**Closed by anntzer** 2019-09-26 22:21 UTC
Labels: Difficulty: Medium, Documentation, Good first issue
