### ISSUE TITLE
[Bug]: Blank output EPS file when using latex and figure.autolayout = True

### ISSUE THREAD

**Issue by robintimmis** [matplotlib/matplotlib#22840] opened 2022-04-13 10:15 UTC
### Bug summary

When figure.autolayout is set to True the output in the EPS file becomes blank. The file is produced and no errors are mentioned.

### Code for reproduction

```python
import matplotlib.pyplot as plt

plt.rc('text', usetex=True)
plt.rcParams["figure.figsize"] = [3.4, 2.47]
plt.rcParams['figure.autolayout'] = True

[Ignoring creation of data for plots]

plt.plot(t,d,label='electron bunch energy density')
plt.savefig('test.eps')
```

### Actual outcome

EPS file converted to PDF

[test.pdf](https://github.com/matplotlib/matplotlib/files/8480431/test.pdf)

### Expected outcome

EPS file converted to PDF with `plt.rcParams['figure.autolayout'] = False` and all else the same

[test_false.pdf](https://github.com/matplotlib/matplotlib/files/8480446/test_false.pdf)

### Additional information

The bug appears when I change to autolayout = True. I noticed there was an earlier bug fix for a very similar scenario (https://github.com/matplotlib/matplotlib/issues/16898/) which seems to fix for the case where figure.autolayout = False.

### Operating system

HPE Cray Linux Environment

### Matplotlib Version

3.5.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.8.5

### Jupyter version

3.2.9

### Installation

pip

**Comment by jklymak** [comment] 2022-04-13 10:54
Not sure what is going on. But you can manually set tight_layout or constrained_layout

**Comment by robintimmis** [comment] 2022-04-13 11:15
That does appear to work, you are right, thankyou. But I need to set it in the rc params since I am using another program to plot other graphs in matplotlib and cannot access these figures to manually change this.

**Comment by tacaswell** [comment] 2022-04-13 12:46
I think this is a duplicate of https://github.com/matplotlib/matplotlib/issues/21930 which was fixed by https://github.com/matplotlib/matplotlib/pull/22732

@robintimmis If you are able to install from source, checking if this works for you on either main or v3.5.x would be very helpful!

**Comment by tacaswell** [comment] 2022-04-13 12:48
I'm going to close this as a duplicate, please ping to have re-open if this is in fact not fixed on the development versions.

**Closed by tacaswell** 2022-04-13 12:48 UTC
Labels: status: duplicate
