### ISSUE TITLE
Feature Request: Specify fallback math font.

### ISSUE THREAD

**Issue by andrzejnovak** [matplotlib/matplotlib#16492] opened 2020-02-13 10:09 UTC
mpl has a `fallback_to_cm` option, but this is not great when using primarily fonts that don't look much like CM. Specifying a different math font as a fallback option would fix this.

**Comment by anntzer** [comment] 2020-02-13 11:15
I think this is a dupe of #8619, and basically implemented in https://github.com/matplotlib/matplotlib/pull/11644 (which needs rebase/review)?

**Closed** 2020-02-13 11:18 UTC
Labels: Duplicate, New feature, text/mathtext
