### ISSUE TITLE
imshow draws half of the first and last lines

### ISSUE THREAD

**Issue by anki-code** [matplotlib/matplotlib#15154] opened 2019-08-29 12:37 UTC
Hello! I've updated `matplotlib` to the latest version (3.1.1) and got an issue: imshow draws half of the first and last lines when I use `set_yticks`.

Example:
```
import numpy as np
from matplotlib import pyplot as plt

oneDim = np.array([0.5,1,2.5,3.7])
twoDim = np.random.rand(8,4)

plt.figure(figsize=(twoDim.shape[1]/2,twoDim.shape[0]/2))
ax = plt.gca()

ax.imshow(twoDim, cmap='Purples', interpolation='nearest', aspect='auto')
ax.set_xticks(np.arange(0,twoDim.shape[1],1))
ax.set_yticks(np.arange(0,twoDim.shape[0],1))
ax.set_yticklabels(np.arange(0,twoDim.shape[0],1))
ax.grid()
```
Result:
![image](https://user-images.githubusercontent.com/1708680/63940647-9b2cd580-ca72-11e9-9377-4939e14c93c0.png)

How I can back to full square in line instead of the half?

**Comment by ImportanceOfBeingErnest** [comment] 2019-08-29 12:52
You can add

ax.set_ylim(twoDim.shape[0]-0.5, -0.5)

Unfortunately, this is necessary due to a bug (https://github.com/matplotlib/matplotlib/issues/14675) in version 3.1.1 of matplotlib . It will be fixed (https://github.com/matplotlib/matplotlib/pull/14677) in 3.1.2, which will be released very soon. So appart from the above you can also revert to matplotlib 3.1.0 for now, or use the development version.

Closing as duplicate of https://github.com/matplotlib/matplotlib/issues/14675

**Closed by ImportanceOfBeingErnest** 2019-08-29 12:52 UTC
