### ISSUE TITLE
constrained_layout always needs two tries with cartopy axes

### ISSUE THREAD

**Issue by dcherian** [matplotlib/matplotlib#13430] opened 2019-02-13 22:10 UTC
### Bug report

**Bug summary**

`constrained_layout` requires two tries to properly layout a cartopy axes.

**Code for reproduction**

```python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

f, ax1 = plt.subplots(1, 1, constrained_layout=True, 
                      subplot_kw=dict(projection=ccrs.PlateCarree()))

f.savefig('images/temp/mpl-1.png')
f.savefig('images/temp/mpl-2.png')
```

**Actual outcome**

first image:
![mpl-1](https://user-images.githubusercontent.com/2448579/52747444-a453ca80-2f98-11e9-91bb-1750d11c8ff2.png)

second image:
![mpl-2](https://user-images.githubusercontent.com/2448579/52747436-9f8f1680-2f98-11e9-9e58-ea09fe142a19.png)

The interactive window does not change at all but the savefig output does.

**Expected outcome**

should get the second image with the first call to `savefig`.

This is a really simple version. I'm having trouble with overlapping axes labels and titles that get solved by calling `savefig` twice.

**Matplotlib version**

  * Operating system: ubuntu 16.04
  * Matplotlib version: 3.0.2 (conda-forge)
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt
  * Python version: 3.6
  * Jupyter version (if applicable): 6.5
  * Other libraries: cartopy 0.17.0

**Comment by jklymak** [comment] 2019-02-13 22:23
Pretty sure cl already is called twice so this is odd.  Anyhow you should be able to f.canvas.draw to trigger the layout without having to save twice.

**Comment by dcherian** [comment] 2019-02-13 22:27
Yeah that works. I get warnings about axes collapsing to zero...

**Comment by jklymak** [comment] 2019-02-13 22:35
Ok there are issues with some artists being misreported. Maybe minimize the more complicated example.

**Comment by QuLogic** [comment] 2019-02-14 01:53
Probably related to https://github.com/SciTools/cartopy/issues/1207

**Comment by jklymak** [comment] 2019-02-14 02:32
Good memory!  I thought I'd seen this before.

**Comment by QuLogic** [comment] 2020-05-21 02:21
Downstream bug is fixed, and now I don't see any warnings about zero-size axes. The result is better, though not exactly the same, as the first result is a little too big:
![mpl-1](https://user-images.githubusercontent.com/302469/82516238-3e81b700-9ae8-11ea-9dfb-ca25796535e7.png)
vs.
![mpl-2](https://user-images.githubusercontent.com/302469/82516246-43466b00-9ae8-11ea-8c91-77aeb9995d4a.png)

**Comment by jklymak** [comment] 2020-05-21 16:12
Sorry, what's the test for this.  The OP doesn't fit...

**Comment by QuLogic** [comment] 2020-05-21 19:44
Replace `import cartopy` with `import cartopy.crs as ccrs` in the original post.

**Comment by jklymak** [comment] 2020-05-21 21:21
Hmm I can’t build cartopy so kind of hard to test this.

**Comment by jklymak** [comment] 2020-05-22 00:11
OK, got it to work.  

So this default axes is wider than tall, but when `ax.get_tightbbox` is called the first time, it doesn't register as wider than tall.  Somehow the axes aspect is not properly set yet despite `apply_aspect` having been called by `get_tightbbox`.  My guess is that Cartopy has to define its own `get_tightbbox` or `get_window_extent`  and call whatever actually sets the aspect ratio of the axes, but a quick look didn't help.  

You can see what is going on by doing:

```python 
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

for size in [(6,4), (4, 6)]:
    f, ax1 = plt.subplots(1, 1, figsize=size, constrained_layout=True,
                          subplot_kw=dict(projection=ccrs.PlateCarree()))
    f.savefig(f'Cartopy{size[0]}{size[1]}.png', dpi=75)
```
![Cartopy64](https://user-images.githubusercontent.com/1562854/82617798-0761e300-9b86-11ea-99bd-365a9d2e5ae1.png)
![Cartopy46](https://user-images.githubusercontent.com/1562854/82617808-0b8e0080-9b86-11ea-8141-0ff0c5380e4f.png)

**Comment by greglucas** [comment] 2022-12-01 03:39
There has been more work done again now on the downstream Cartopy side and I'm not able to reproduce any of the examples above, so I'm going to close this as fixed. (Tested with Matplotlib 3.6 and Cartopy 0.21)

**Closed by greglucas** 2022-12-01 03:39 UTC
Labels: status: downstream fix required

**Comment by dcherian** [comment] 2022-12-01 05:15
Thank you!
