### ISSUE TITLE
[Bug]: Displaying a graph in PySide6 with snake_case enabled results in a black canvas

### ISSUE THREAD

**Issue by Remco646** [matplotlib/matplotlib#27524] opened 2023-12-15 23:25 UTC
### Bug summary

Displaying a graph in PySide6 with snake_case enabled results in a black canvas. However, if snake_case is disabled, everything works normally.

### Code for reproduction

```python
from PySide6.QtWidgets import QMainWindow, QApplication
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from __feature__ import snake_case


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        figure = Figure()
        ax = figure.add_subplot(111)
        ax.plot([1, 2, 3], [2, 3, 1])
        canvas = FigureCanvasQTAgg(figure)
        self.set_central_widget(canvas)
        self.show()


app = QApplication()
w = MainWindow()
app.exec()
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/53235190/0b8570f5-663f-4f9c-9e91-0e1f5013c937)

### Expected outcome

![image](https://github.com/matplotlib/matplotlib/assets/53235190/0564b069-ebdc-4b25-b203-ca3347a733a5)

### Matplotlib Version

3.8.2

### Matplotlib Backend

QtAgg

### Python version

3.12.0

### Installation

pip

**Comment by QuLogic** [comment] 2023-12-15 23:32
This is a duplicate of #23816.

**Closed by QuLogic** 2023-12-15 23:32 UTC
