### ISSUE TITLE
after updating to python 6 from python 5 stopped to work plt.show(block = False)

### ISSUE THREAD

**Issue by Sandy4321** [matplotlib/matplotlib#11516] opened 2018-06-26 19:50 UTC
May help to create and show figures without blocking calculations 
previously it worked by using 
plt.show(block = False)

but after updating to python 6 it does not work any more

```
import matplotlib.pyplot as plt
fig = plt.figure(figsize=(13, 5))
plt.ion()
x = [1, 2, 3, 4]
y = [1, 4, 9, 6]
labels = ['Frogs', 'Hogs', 'Bogs', 'Slogs']

plt.plot(x, y, 'ro')
# You can specify a rotation for the tick labels in degrees or with keywords.
plt.xticks(x, labels, rotation='vertical')
# Pad margins so that markers don't get clipped by the axes
plt.margins(0.2)
# Tweak spacing to prevent clipping of tick-labels
plt.subplots_adjust(bottom=0.15)
plt.show(block = False)
q=1
fig = plt.figure(figsize=(13, 5))
x = [1, 2, 3, 4]
y = [7, 1, 2, 16]
labels = ['Frogs', 'Hogs', 'Bogs', 'Slogs']

plt.plot(x, y, 'ro')
# You can specify a rotation for the tick labels in degrees or with keywords.
plt.xticks(x, labels, rotation='vertical')
# Pad margins so that markers don't get clipped by the axes
plt.margins(0.2)
# Tweak spacing to prevent clipping of tick-labels
plt.subplots_adjust(bottom=0.15)
plt.show(block = False)
q=1


```

**Comment by Sandy4321** [comment] 2018-06-26 19:53
![image](https://user-images.githubusercontent.com/11426119/41935811-078e187c-7959-11e8-9103-0c5e34fbcea2.png)

**Comment by Sandy4321** [comment] 2018-06-26 19:53
figure are shown as blank empty

**Comment by WeatherGod** [comment] 2018-06-26 20:00
Uhmmm... are you from the future? Python 5? Python 6?

**Comment by tacaswell** [comment] 2018-06-27 00:11
I suspect you mean 'ipython5' -> 'ipython6'?

This looks like the GUI event loop integration is not working correctly.  If you do `plt.show(block=True)` does it work?

I suspect the issue is that when IPython moved from using readline to prompttoolkit the event loop integrations that the GUI libraries set up on import with python no longer work.  

If so setting `plt.ion()` may fix it (in mpl 1.5+ that will, if you are in IPyhon) take care of asking it to install the event loop integrations.

With all versions of Matplotlib and IPython (that you can easily get your hands on) doing `%matplotlib` at the prompt should also fix this problem.

**Comment by Sandy4321** [comment] 2018-06-27 14:52
friends
Uhmmm... are you from the future? Python 5? Python 6?
 I am talking about plain Python
3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
Python Type "help", "copyright", "credits" or "license" for more information.


not ipython
I am running the code above from python, I do use wings Wing IDE 6.0
there is a possibility to run python line by line not only from ipython but using other IDEs
https://wiki.python.org/moin/IntegratedDevelopmentEnvironments
so the question:  this line
plt.show(block = False)
worked for Python 5 
but now does not work for python 6 
and plt.ion(), is not working either
 

how to run   Python , that figure creation will not block calculations. but the figure will be created without a blank image in figure???

**Comment by fredrik-1** [comment] 2018-06-27 15:57
Do you use windows? If you do, look at my post above.

**Comment by Sandy4321** [comment] 2018-06-27 16:39
yes I do use windows, 
, look at my post above.
where is link pls?
if this link
https://github.com/matplotlib/matplotlib/issues/9206
there is no answer
so it is not fixed bug?

**Comment by fredrik-1** [comment] 2018-06-27 16:51
I believe that it is a python bug that the python core team could fix but haven't done yet. 

The solutions are to either use python 3.5, IPython or change operating system.

**Comment by tacaswell** [comment] 2018-06-27 21:09
See https://github.com/python/cpython/pull/7978 for PR into cpython to apply the suggested change.

Closing this as there is nothing more Matplotlib can do.

**Closed by tacaswell** 2018-06-27 21:09 UTC
