### ISSUE TITLE
combination of scipy.signal.savgol_filter and matplotlib plot with dashed or dotted line crashes on lstsq

### ISSUE THREAD

**Issue by jackyOO7** [matplotlib/matplotlib#18157] opened 2020-08-03 08:06 UTC
### Bug report

**Bug summary**

savgol_filter crashes with an error in the lstsq algorithm if executed after a plot with dashed/dotted/dashdotted line style.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from scipy.signal import savgol_filter

ls='--'
# ls=''
y = range(100)
plt.plot(y,ls)
try:
  y_filt=savgol_filter(y,11,2)
except Exception as e:
  print(e)
```

**Actual outcome**

```
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
SVD did not converge in Linear Least Squares
```

**Expected outcome**

It worked until recently without a change in any of the python libraries. I had it running in a fixed environment and it stopped working probably after a windows update. Now I can't get it to work on any PC with any python version.

**Matplotlib version**

  * Operating system: Windows 10.0.19041
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.4
  * Jupyter version (if applicable): NA
  * Other libraries: scipy v1.5.2

installed python from the installer and the libraries with pip

**Comment by dopplershift** [comment] 2020-08-03 09:01
Works for me with matplotlib 3.3 on macOS 10.15 with Python 3.8 and scipy 1.5.2 (all conda-forge).

**Comment by timhoffm** [comment] 2020-08-03 10:01
@jackyOO7 please test with matplotlib 3.3.

**Comment by jackyOO7** [comment] 2020-08-03 10:31
I think it's a problem of the windows build 19041:

Version	10.0.19041 Build 19041
python: 3.6.8 matplotlib: 3.1.1 scipy: 1.3.1 not working
python: 3.7.5 matplotlib: 3.1.1 scipy: 1.4.1 not working
python: 3.7.4 matplotlib: 3.1.1 scipy: 1.5.2 not working
python: 3.7.4 matplotlib: 3.3.0 scipy: 1.5.2 not working
python: 3.5.3 matplotlib: 3.0.3 scipy: 1.4.1 not working
python: 3.8.5 matplotlib: 3.3.0 scipy: 1.5.2 not working

Version	10.0.18362 Build 18362
python: 3.7.4 matplotlib: 3.2.0 scipy: 1.4.1 working
python: 3.5.3 matplotlib: 3.0.3 scipy: 1.4.1 working
python: 3.4.4 matplotlib: 2.2.3 scipy: 1.2.3 working

**Comment by tacaswell** [comment] 2020-08-03 17:41
Where did you get your packages from?

**Comment by jklymak** [comment] 2020-08-03 18:05
Sounds related to https://github.com/matplotlib/matplotlib/issues/17980 ?

**Comment by jackyOO7** [comment] 2020-08-04 04:37
Thank you for your replies!
@tacaswell 
In most distributions where I tested, I installed directly via pip. In some I used the precompiled wheels from @cgohlke 
@jklymak 
That is a good find. Exactly the same error behaviour only this time with numpy. I can confirm the same happens with numpy as well on the build 19041.
The error messages happen on access to the Intel MKL (Math Kernel Library) gelsd functions, which are used for least square optimization of both numpy and scipy. 

The following code shows the error on my system with both libraries:
```python
import matplotlib.pyplot as plt
import scipy.linalg
import sys
import matplotlib
import numpy as np

print('python:',sys.version.split(' ')[0],'matplotlib:',matplotlib.__version__,'scipy:',scipy.__version__,'numpy:',np.__version__)

print(scipy.linalg.lstsq(np.ones((3, 3)), np.arange(3)))
print(np.linalg.lstsq(np.ones((3,3)),np.arange(3),None))
ls='--'
# ls=''
plt.grid(ls=ls)
try:
  y_filt=scipy.linalg.lstsq(np.ones((10,5)),np.arange(10))
except Exception as e:
  print('scipy:',e)
  pass
plt.grid(ls=ls)
try:
  np.linalg.lstsq(np.ones((10,5)),np.arange(10),None)
except Exception as e:
  print('numpy',e)
  pass
```
Result:
```
python: 3.8.5 matplotlib: 3.3.0 scipy: 1.5.2 numpy: 1.19.1
(array([0.33333333, 0.33333333, 0.33333333]), array([], dtype=float64), 1, array([3., 0., 0.]))
(array([0.33333333, 0.33333333, 0.33333333]), array([], dtype=float64), 1, array([3., 0., 0.]))
scipy: SVD did not converge in Linear Least Squares
numpy SVD did not converge in Linear Least Squares
```
It doesn't matter whether you take plt.grid or plt.plot to set the linestyle.

**Comment by cgohlke** [comment] 2020-08-04 06:16
I can't reproduce this issue on Windows 10.0.19041.423. Tried many Python installations including python 3.8.5, matplotlib 3.3.0, scipy 1.5.2, numpy 1.19.1. I could reproduce #17980.

**Comment by jackyOO7** [comment] 2020-08-04 07:06
Thank you for checking!

Did you try the first code snippet from above? In my case either both commands (np.polyfit and scipy.signal.savgol_filter) fail or both work. It is important that you plot something with lines _every_ time before you call the failing routine.
```python
import matplotlib.pyplot as plt
from scipy.signal import savgol_filter
import numpy as np

y = range(100)
plt.plot(y,':')
try:
  savgol_filter(y,11,2)
except Exception as e:
  print('scipy:',e)
plt.plot(y, ':') # if this is not called, the second part will work
try:
  np.polyfit(y, y, 1)
except Exception as e:
  print('numpy:', e)
```

Does it still work for you with the scipy but not the numpy command from #17980?

**Comment by cgohlke** [comment] 2020-08-04 07:23
> Did you try the first code snippet from above? 

You are right. I only tried the longer script with all Python installations. In fact the first, shorter script does fail with official numpy and scipy, but not with the MKL builds.

**Comment by jackyOO7** [comment] 2020-08-04 07:46
For some reason calling the problematic lstsq functions directly does not fail very reliably. I had it failing on my PC when I posted the comment above. But right now, both calls to lstsq work for me as well. 
So I think the calls to scipy.signal.savgol_filter or numpy.polyfit are needed. Probably there are more functions that use lstsq internally and should fail. I'll try the mkl builds. Is it sufficient to install numpy+MKL or do I need a specific scipy build as well?

**Comment by jackyOO7** [comment] 2020-08-04 08:05
I downloaded numpy+MKL and scipy from @cgohlke's repository. And the problem is fixed. Thank you Christoph for your work compiling and sharing all those packages. I can't count the times where they helped me getting things done.
```
python: 3.8.5 matplotlib: 3.3.0 scipy: 1.5.2 numpy: 1.19.1
savgol_filter: works
scipy.linalg.lstsq: works
numpy.polyfit: works
numpy.linalg.lstsq: works
```
I think it is some problem of the intel MKL that is distributed with the latest windows update. By using numpy with integrated MKL we can mitigate the problem. Still the question remains: why does matplotlib linestyle have any effect on this? I suspect some variable name collision, but I am not nearly deep enough involved to know for sure.

**Comment by cgohlke** [comment] 2020-08-04 15:13
> I think it is some problem of the intel MKL that is distributed with the latest windows update.

Intel MKL is not distributed with Windows. The numpy and scipy distributions on PyPI use and include OpenBLAS instead of MKL.

**Comment by ndeadly** [comment] 2020-08-10 18:36
I've been experiencing the same issue since a Windows update. I also noticed that running the code that raises the exception a second time succeeds.

I've worked around it for now by monkey patching the lstsq function

```
from scipy.linalg import lstsq

def _lstsq(*args, **kwargs):
    try:
        return lstsq(*args, **kwargs)
    except:
        return lstsq(*args, **kwargs)

scipy.linalg.lstsq = _lstsq
```

**Comment by StephenRoille** [comment] 2020-09-30 17:39
I want to highlight the fact that the `numpy` team officially acknowledged an issue on **Windows 10 build 2004** when using the **OpenBLAS** linear algebra kernel. See this [comment](https://github.com/matplotlib/matplotlib/issues/17980#issuecomment-701519028) for details.

While you seem to be using a different Windows 10 build, I assume the developers do not test `numpy` on all Windows builds.
The error you faced is probably similar and may not have been highlighted for that particular version of Windows.

Thanks to @cgohlke for its excellent work providing alternative libraries unavailable via PyPI.
Your contribution is extremely valuable 👍😁.

**Comment by dopplershift** [comment] 2020-09-30 20:22
Closing this because I'm pretty sure there's nothing for matplotlib to do here.

**Closed by dopplershift** 2020-09-30 20:22 UTC
Labels: Needs confirmation
