### ISSUE TITLE
plot_date() ignores timezone in matplotlib version 2.0.0

### ISSUE THREAD

**Issue by robinloxley1** [matplotlib/matplotlib#8072] opened 2017-02-14 03:32 UTC
### Bug report

**Bug summary**

- It is a reopen bug report, same to #5575. The bug still exists for version 2.0.0.

copy paste the code from #5575 

```python
import pytz
import matplotlib.pyplot as plt
from datetime import datetime
time_index = [pytz.timezone('Europe/Berlin').localize(datetime(year=2015, month=11, day=27, hour=x)) for x in range(4)]
plt.plot_date(time_index, [4]*4, tz='Europe/Berlin')
plt.plot_date(time_index, [3]*4, tz='UTC')
```

**Actual outcome**

- The output gives no difference in xaxis, implying tz is not working.

**Comment by dstansby** [comment] 2017-02-14 12:14
For reference, this works fine if the two plots are on different axes, which is all #6091 tests for. The problem happens if two plots with different timezones are done on the same axis.

**Comment by tacaswell** [comment] 2017-02-14 16:31
What timezone would you expect the axes to be in if you pass in data with different timezones (which may be considered 'different units')?

**Comment by anntzer** [comment] 2017-04-15 06:02
It seems natural enough to convert everything to the axis' tz?

**Comment by samarthwhistle** [comment] 2018-07-23 22:54
Is there any confirmation on whether this is going to be fixed in v3.0?

**Comment by jklymak** [comment] 2018-07-24 00:18
I don't think there is a fix for this right now.  OTOH, I suspect its not too hard to do.  PR would be welcome...

**Comment by jklymak** [comment] 2018-07-24 13:51
Actually, I take that back.  The problem is that `axis.update_units` only checks that the converter is appropriate for the data, not the actual units of the data. So the fix is to fix the units machinery, but thats under review.

**Comment by samarthwhistle** [comment] 2018-07-24 17:47
Thanks for providing this information. Looking forward to the fix!

**Comment by jklymak** [comment] 2018-07-24 17:57
I agree that the documentation shouldn't claim that this works.  Not sure how we indicate that a kwarg actually has no effect, but that we'd like it to someday...

I wouldn't expect this in the forseable future, as it gets at the root of our units handling, which is currently not set up to change units on the fly.

**Comment by dstansby** [comment] 2024-01-31 09:02
Still seems to be an issue on current main, so I'll keep this open.

**Comment by timhoffm** [comment] 2024-01-31 13:59
Since plot_date is discouraged anyway, it’s unlikely that we’ll change behavior.

I suggest we close this by better documenting, that tz is only used for  [axis_date](https://matplotlib.org/stable/api/_as_gen/matplotlib.axis.Axis.axis_date.html#matplotlib.axis.Axis.axis_date), so affects the axis labeling, but does not directly imply the timezone of the data.

**Comment by dstansby** [comment] 2024-01-31 14:01
I'm guessing this is still and issue with plain `plot()` though, and I don't see why taking the timezone into account when doing the unit conversion isn't a valid feature request (or even a bug fix)?

**Comment by timhoffm** [comment] 2024-01-31 14:11
Ok, but then let’s rephrase this into a new issue using `plot` only.

**Comment by timhoffm** [comment] 2024-01-31 15:14
> it seems we plot in whichever timezone came first.

Which is reasonable. So, if I understand correctly, we don’t have an issue with pure `plot()`.

**Comment by dstansby** [comment] 2024-01-31 16:28
Ah fair enough, sorry for not checking... if we're not fixing anything on `plot_date()` now happy for this to be closed as wont fix 👍

**Comment by jklymak** [comment] 2024-01-31 16:50
I'm confused - are we saying `plot_date` is broken, but `plot` works?  I wasn't aware `plot_date` did anything different that `plot`.

**Comment by dstansby** [comment] 2024-01-31 17:05
Yet again, my bad for not actually checking... `plot_date` does now seem to be working fine.

(as an aside, in the above plot https://github.com/matplotlib/matplotlib/issues/8072#issuecomment-1919262892 I'm a bit confused, isn't Berlin one hour ahead of UTC, which means the lines are the wrong way round (Berlin should be one hour to the right of UTC instead of one hour to the left)??)

**Comment by rcomer** [comment] 2024-01-31 17:21
Confirmed, `plot` errors if you pass the _tz_ parameter.

Yes, Berlin is an hour ahead of UTC (in winter).  So when it's midnight in Berlin, it's only 11pm UTC.  So I think the plot is correct.

**Comment by ksunden** [comment] 2024-01-31 17:52
https://github.com/matplotlib/matplotlib/blob/41d4149f84b40d3a90a70f81b940985b8485f04a/lib/matplotlib/axes/_axes.py#L1820-L1824

This is the implementation of `plot_date` as it stands.

The consequences of this implementation are as follows:

- Only the last `tz` passed is used and is used to interpret _all_ floating point inputs (regardless of what `tz` was passed with a particular floating point input)
   - we do not add the tz to the source data, just set it as the active interpretation of floats
- If no `tz` is provided, it will use the :rc:`timezone` (defaults to UTC)
- `datetime` objects will still translate to the timezone as they hold their timezone info themselves
- `datetime64` does _not_ store timezone info (though will parse it)... there is some handling of `datetime64` in `date2num`/`num2date` that looks like there either _was_ once some tz info or _is_ on some sub dtypes we support (pandas?, not sure, but `astimezone` is not a numpy thing)
   - As such, I believe they are always interpreted as UTC, but might be :rc:`timezone`, didn't spend the time to differentiate that.
- `float` inputs _will_ change (since changing the tz changes what the floating point number isformatted as/translates to as a date, and the tz is not attached to it.

The equivalent to passing the `tz` argument is to call `ax.xaxis_date(tz)` (or y axis, but by default x is the only one set).

So, in the example, both plots are using `datetime` objects which _are_ carrying timezone information as the `x` values... I do _not_ think we should be applying a new timezone to them in `plot_date` when they are given as timezoned values. I could see _an_ argument for attaching the tz to float inputs (e.g. by instead of doing `self.plot(x, y, **kwargs)` doing `self.plot(num2date(x, tz=tz), y, **kwargs)` (modulo x and y bool flag handling...) but even that I would think would only apply to _float_ inputs, not `datetime` inputs as is here... and even then am not sure it's actually expected behavior)

Given the admonition that very explicitly states "Do not use this for `datetime` inputs, use `plot` instead" (in current mpl, such text was not present when this issue was opened in fairness), my opinion is that this should be closed as "expected behavior". The admonition (which was added in #18346) also does give information about calling `axis_Date (though does reach in to the `axis` instead of using the `axes` method which exists... but just is a wrapper so doesn't really change anything)

**Comment by jklymak** [comment] 2024-01-31 20:05
I do wonder if we should go a step further and hard deprecate this method.  Datetime with timezones are confusing enough without slightly different semantics.

**Comment by rcomer** [comment] 2024-01-31 20:29
From the discussion at #18346, it seems the intention at the time had been to pre-deprecate `plot_date` but the `PendingDeprecationWarning` was causing an issue with Sphinx :eyes:

**Comment by timhoffm** [comment] 2024-01-31 22:20
I'm fine with deprecating now. We've even already announced that we we will do this in the admonition at https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.plot_date.html#matplotlib.axes.Axes.plot_date

**Closed** 2024-03-04 19:48 UTC
Labels: topic: date handling, topic: units and array ducktypes, keep
