### ISSUE TITLE
[Feature Request] Support different markers in same `scatter` plot

### ISSUE THREAD

**Issue by jolespin** [matplotlib/matplotlib#18040] opened 2020-07-23 19:23 UTC
### Bug report

**Bug summary**

Please allow support for multiple markers in the same scatter plot

**Code for reproduction**

https://stackoverflow.com/questions/43528300/python-matplotlib-scatter-different-markers-in-one-scatter

```python
# Wrapper around scikit-learn PCA
pca_degs = sy.ordination.PrincipalComponentAnalysis(df_clr.loc[:,idx_deg])
# Array of markers
markers = df_meta["temperature"].map(lambda x: {"26C":"o", "30C":"^"}[x])[pca_degs.data.index]
# Wrapper around matplotlib `scatter`
pca_degs.plot(marker=markers.tolist())

```

**Actual outcome**

```
ValueError: Unrecognized marker style ['^', '^', 'o', '^', '^', 'o', '^', '^', 'o', 'o', 'o', 'o', 'o', 'o', 'o', nan, 'o', 'o', '^', '^', 'o']

```

**Expected outcome**

Plot multiple markers instead of running a for-loop and creating one per marker style

**Matplotlib version**

  * Operating system: OSX
  * Matplotlib version: 3.2.1

  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline

  * Python version: 3.8.2 
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by timhoffm** [comment] 2020-07-23 20:36
The usecase is a bit unusual, but it doesn't look completely off.

From a practical point of view, there are some things to consider:

- Since the marker defines the path in the returned PathCollection, it's a bit different from other properties, in particular one cannot use it as the discriminating property forhttps://matplotlib.org/api/collections_api.html#matplotlib.collections.PathCollection.legend_elements. In particular, you won't be able to make these types of legends for markers https://matplotlib.org/gallery/lines_bars_and_markers/scatter_with_legend.html. (And I don't think there's a resonable way of making that happen.

- The edgecolors handling depends on the marker:
  > For non-filled markers, edgecolors is ignored. Instead, the color is determined like with 'face', i.e. from c, colors, or facecolors.

  If we allow for multiple markers, I don't see a reasonable strategy how to combine them with edgecolors.

Overall, I'm -0.5 on adding this feature because the integration will have rough edge cases.

**Comment by jklymak** [comment] 2020-07-23 20:48
I believe this is a duplicate of #11155, so perhaps transpose the discussion there?  I'll close this one, but feel free to reopen if I've misunderstood...

**Closed by jklymak** 2020-07-23 20:48 UTC
Labels: Needs comment/discussion, New feature
