### ISSUE TITLE
[Bug]: savefig in a thread pool when another thread pool is working is more slower than matplotlib3.2.0

### ISSUE THREAD

**Issue by wqh17101** [matplotlib/matplotlib#21816] opened 2021-11-30 07:47 UTC
### Bug summary

there are two thread pools working together.
`savefig` is in the one of them.
With matplotlib 3.2.0 it costs 1s.
With matplotlib 3.4.3 it costs 30s.

### Code for reproduction

```python
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

import matplotlib
from matplotlib.figure import Figure

matplotlib.use('agg')
import matplotlib.pyplot as plt
import matplotlib.patches as patches

POOL_1 = ThreadPoolExecutor(3)
POOL_2 = ThreadPoolExecutor(3)


def _pull_stream():
    while True:
        a = [100]
        if a[0] < 200:
            continue


def generate_empty():
    fig = Figure(figsize=(9.6, 12.8))
    fig.savefig("./test.jpg")
    fig.clear()


def draw_process():
    start_time = time.time()
    img = plt.imread("./test.jpg")
    fig = plt.figure(figsize=(9.6, 12.8))
    ax_var = plt.Axes(fig, [0., 0., 1., 1.])
    ax_var.set_axis_off()
    ax_var.imshow(img, aspect="equal")
    fig.add_axes(ax_var)
    for i in range(3):
        for j in range(10):
            ax_var.add_patch(patches.Rectangle((1, 1), 2, 3))
            ax_var.text(4, 0, 'Here you are', family='fantasy', fontsize=12, style='italic', color='mediumvioletred')
    plt.axis('off')
    plt.savefig("./test_res.jpg")
    plt.close('all')
    return "cost {}s".format(time.time() - start_time)


def run():
    POOL_1.submit(_pull_stream)
    all_task = [POOL_2.submit(draw_process) for i in range(10)]
    for future in as_completed(all_task):
        data = future.result()
        print("in main: get page {}s success".format(data))


if __name__ == '__main__':
    generate_empty()
    run()

```

### Actual outcome

i just write a simple draw process, for my real process i use add_patch(Rectangle) and text to add some elements for my pic.

matplotlib 3.2.0 
![image](https://user-images.githubusercontent.com/26429138/144004547-7e84cf00-ca99-4e4e-8bb1-ef77db4e4205.png)
matplotlib3.4.3
![image](https://user-images.githubusercontent.com/26429138/144004593-c3d8038a-2cca-4315-b32e-81969f227fc5.png)

### Expected outcome

get the same speed as 3.2.0

### Matplotlib Version

3.4.3

### Matplotlib Backend

agg

### Python version

3.8.8

### Installation

pip

**Comment by jklymak** [comment] 2021-11-30 08:06
Please include all your imports to make this self-contained.

**Comment by wqh17101** [comment] 2021-11-30 11:27
```
import os
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

import cv2
import matplotlib.pyplot as plt
width,height=9.6,12.8
plt.rcParams['figure.figsize'] = width, height

DETECT_STREAM_THREAD = ThreadPoolExecutor(3)
PULL_STREAM_THREAD = ThreadPoolExecutor(3)


def draw_b_box(bbox, image_path, marked_image_path):
    img = cv2.imread(image_path)[:, :, (2, 1, 0)]
    height, width = img.shape[0:2]
    fig = plt.figure()
    fig.set_size_inches(width / 100.0, height / 100.0)
    axis = plt.Axes(fig, [0., 0., 1., 1.])
    axis.set_axis_off()
    fig.add_axes(axis)
    axis.imshow(img, aspect='equal')

    for obj, box in bbox.items():
        for k_var, v_var in box.items():
            draw_box(axis, k_var, v_var, obj)
    plt.axis('off')
    plt.savefig(marked_image_path)
    plt.close('all')
    if os.path.isfile(marked_image_path):
        return marked_image_path
    return ''


def draw_box(ax_var, k_var, v_var, obj):
    """

    :param ax_var:
    :param k_var:
    :param v_var:
    :param obj:
    :return:
    """
    for box in v_var:
        if box:
            border_color = '#01DF3A'
            box_color = 'blue'
            ax_var.add_patch(
                plt.Rectangle((box[0], box[1]),
                              box[2] - box[0],
                              box[3] - box[1], fill=False,
                              edgecolor=border_color, linewidth=3.5)
            )
            ax_var.text(box[0], box[1] - 2,
                        '{:s} {:.3f}'.format(k_var, box[-1]),
                        bbox=dict(facecolor=box_color, alpha=0.5),
                        fontsize=14, color='white')


detect_res = {'10022': {'aaa': [
    [402.397216796875, 303.6626892089844, 429.1062927246094, 343.32269287109375,
     0.5475523471832275],
    [449.9952087402344, 303.76458740234375, 467.965087890625, 342.43792724609375,
     0.5410181283950806],
    [363.09039306640625, 303.4768981933594, 395.4483337402344, 341.50714111328125,
     0.5213803052902222],
    [429.456298828125, 303.8983459472656, 448.97357177734375, 343.036865234375,
     0.5157099366188049],
    [468.06207275390625, 303.6632995605469, 485.36944580078125, 342.32220458984375,
     0.5105130076408386],
    [485.90716552734375, 304.0113830566406, 503.641357421875, 342.2887268066406,
     0.4979272484779358],
    [503.93719482421875, 304.06732177734375, 521.5438232421875, 342.93109130859375,
     0.4940594732761383],
    [521.56640625, 303.9978942871094, 539.7139892578125, 342.65679931640625,
     0.4903692901134491],
    [540.9378662109375, 304.5950927734375, 559.2433471679688, 343.3692321777344,
     0.48610904812812805],
    [597.1905517578125, 305.84197998046875, 614.417724609375, 343.1590576171875,
     0.48125728964805603],
    [559.9869384765625, 304.29156494140625, 578.4329833984375, 343.0211486816406,
     0.46419182419776917],
    [579.3382568359375, 305.90826416015625, 596.2889404296875, 343.60626220703125,
     0.4636862874031067],
    [670.1096801757812, 305.5733947753906, 687.4866943359375, 344.55621337890625,
     0.4249202013015747],
    [632.8704833984375, 305.5631103515625, 649.9483642578125, 343.36077880859375,
     0.4213314354419708],
    [652.4852294921875, 304.95013427734375, 669.3626708984375, 344.2486572265625,
     0.4193057715892792],
    [615.3643798828125, 305.662353515625, 632.5997314453125, 343.4087219238281,
     0.4172344505786896]], 'bbbb': [[330.6, 298.9, 719.4, 348.1, 0.88]]}, '10005': {
    'cccc': [
        [402.397216796875, 303.6626892089844, 429.1062927246094, 343.32269287109375,
         0.5475523471832275],
        [449.9952087402344, 303.76458740234375, 467.965087890625, 342.43792724609375,
         0.5410181283950806],
        [363.09039306640625, 303.4768981933594, 395.4483337402344, 341.50714111328125,
         0.5213803052902222],
        [429.456298828125, 303.8983459472656, 448.97357177734375, 343.036865234375,
         0.5157099366188049],
        [468.06207275390625, 303.6632995605469, 485.36944580078125, 342.32220458984375,
         0.5105130076408386],
        [485.90716552734375, 304.0113830566406, 503.641357421875, 342.2887268066406,
         0.4979272484779358],
        [503.93719482421875, 304.06732177734375, 521.5438232421875, 342.93109130859375,
         0.4940594732761383],
        [521.56640625, 303.9978942871094, 539.7139892578125, 342.65679931640625,
         0.4903692901134491],
        [540.9378662109375, 304.5950927734375, 559.2433471679688, 343.3692321777344,
         0.48610904812812805],
        [597.1905517578125, 305.84197998046875, 614.417724609375, 343.1590576171875,
         0.48125728964805603],
        [559.9869384765625, 304.29156494140625, 578.4329833984375, 343.0211486816406,
         0.46419182419776917],
        [579.3382568359375, 305.90826416015625, 596.2889404296875, 343.60626220703125,
         0.4636862874031067],
        [670.1096801757812, 305.5733947753906, 687.4866943359375, 344.55621337890625,
         0.4249202013015747],
        [632.8704833984375, 305.5631103515625, 649.9483642578125, 343.36077880859375,
         0.4213314354419708],
        [652.4852294921875, 304.95013427734375, 669.3626708984375, 344.2486572265625,
         0.4193057715892792],
        [615.3643798828125, 305.662353515625, 632.5997314453125, 343.4087219238281,
         0.4172344505786896]]}}


def test():
    PULL_STREAM_THREAD.submit(_pull_stream)
    all_task = [DETECT_STREAM_THREAD.submit(_detect_stream) for i in range(10)]
    for future in as_completed(all_task):
        data = future.result()
        print("in main: get page {}s success".format(data))


def _pull_stream():
    while True:
        a = [100]
        if a[0] < 200:
            continue


def _detect_stream():
    start_time = time.time()
    draw_b_box(detect_res, "./empty.jpg", "./empty_res.jpg")
    print("cost {}s".format(time.time() - start_time))
    return "cost {}s".format(time.time() - start_time)


if __name__ == '__main__':
    fig=plt.figure()
    fig.savefig("./test.jpg")
    test()
```


matpoltlib 3.2.0
![image](https://user-images.githubusercontent.com/26429138/144039303-774edcd9-e3e8-44f9-bff1-d0de45c278aa.png)


matplotlib 3.4.3
![image](https://user-images.githubusercontent.com/26429138/144039208-a6ecf967-9f91-4446-890d-44d554d71f74.png)

**Comment by jklymak** [comment] 2021-11-30 14:24
Sorry, I guess I should have _also_ asked you to minimize as much as you can, and preferably drop libraries like `cv2`.  Maybe someone here can help you, but I'm not personally installing cv2 just to see if I can replicate this.

**Comment by wqh17101** [comment] 2021-11-30 15:45
matplotlib 3.2.0
```
in main: get page cost 5.981691837310791ss success
in main: get page cost 9.590320110321045ss success
in main: get page cost 12.328491926193237ss success
in main: get page cost 14.871341228485107ss success
in main: get page cost 14.912289142608643ss success
in main: get page cost 14.833057403564453ss success
in main: get page cost 13.454867839813232ss success
in main: get page cost 12.420564413070679ss success
in main: get page cost 11.194593667984009ss success
```

matplotlib 3.4.3
```
in main: get page cost 5.981691837310791ss success
in main: get page cost 9.590320110321045ss success
in main: get page cost 12.328491926193237ss success
in main: get page cost 14.871341228485107ss success
in main: get page cost 14.912289142608643ss success
in main: get page cost 14.833057403564453ss success
in main: get page cost 13.454867839813232ss success
in main: get page cost 12.420564413070679ss success
in main: get page cost 11.194593667984009ss success
```

**Comment by jklymak** [comment] 2021-11-30 16:12
Thanks - I get similar numbers to yours on master for your 3.4.3 case.  It looks like you have a cut-and-paste error above for the 3.2.0 case?  


### 3.2.0
```
in main: get page cost 1.3607308864593506ss success
in main: get page cost 1.738670825958252ss success
in main: get page cost 2.2226626873016357ss success
in main: get page cost 3.0559439659118652ss success
in main: get page cost 3.329900026321411ss success
in main: get page cost 3.4792609214782715ss success
in main: get page cost 3.3612148761749268ss success
in main: get page cost 3.3297128677368164ss success
in main: get page cost 3.31333327293396ss success
in main: get page cost 2.5424599647521973ss success
```

### main:

```
in main: get page cost 4.868897199630737ss success
in main: get page cost 7.047243118286133ss success
in main: get page cost 8.557204961776733ss success
in main: get page cost 10.899760246276855ss success
in main: get page cost 10.851372003555298ss success
in main: get page cost 11.028491020202637ss success
in main: get page cost 10.900846004486084ss success
in main: get page cost 10.722455739974976ss success
in main: get page cost 11.087290048599243ss success
in main: get page cost 7.743549108505249ss success
```

**Comment by jklymak** [comment] 2021-11-30 16:17
In my quick tests, it is the ax_var.text() call that is causing a big slow down.  It would be interesting to bisect this to see when it got so slow.  @wqh17101 did you try any other versions of Matplotlib to help narrow the search down?

**Comment by jklymak** [comment] 2021-11-30 16:28
Maybe ef58a59331d58a85db https://github.com/matplotlib/matplotlib/pull/15686

**Comment by wqh17101** [comment] 2021-12-01 01:11
@jklymak I just tested 3.2.0 3.4.3 and 3.5.0(which has the same performance as 3.4.3).
In my test,i found that savefig func cost more time , maybe you can move the `start_time = time.time()` before savefig and have a test.



> In my quick tests, it is the ax_var.text() call that is causing a big slow down. It would be interesting to bisect this to see when it got so slow. @wqh17101 did you try any other versions of Matplotlib to help narrow the search down?
I don`t really know the implementation of `ax_var.text()` , maybe it is a lazy func , which will run when `savefig` triggered?

**Comment by jklymak** [comment] 2021-12-01 07:53
I don't think there will be much cost in creating the objects, its all going to be in the draw step...

Matplotlib is not guaranteed to be thread safe - is it possible the font caching etc are trying to open the same files and getting hung up somehow?    I really dont' notice a difference if we remove the text calls.

**Comment by tacaswell** [comment] 2022-01-17 19:10
I think @anntzer 's suggestion that this is something with the scheduler is correct (as the busy/pull thread is hogging all of the cycles) 

Changing the loop in @anntzer 's example to

```python

def infinite_loop():
    while True:
        time.sleep(0)  # this effectively flashes the GIL which gives the other threads a chance to run!
        continue

```

Further supporting this if you add

```python
import sys
sys.setswitchinterval(sys.getswitchinterval() / 10_000)
```

at the top the performance gets a bit better (but still not as good as the `time.sleep(0)` case).

I suspect that we got rid of a `stat` call which (I am speculating) make use of Signals which is one of the things that forces a running thread to release the GIL and let other threads have a chance to run.  I think that without that, mpl makes a lot of calls that go down to the c level and release the GIL (so we let the fast loop get the GIL often) and then have to wait the full time-slice to get it back (because the busy thread never releases it on its own).   With the `time.sleep(0)` the busy loop is releaseing the GIL often so the threads do a better job sharing (and hence you see the faster walltime on the Matplotlib figures).

-----

I'm going to close this as I do not think there is anything we can do on the Matplotlib side (the problem is the other threads being too greedy and doing anything with Sginals to game the scheduler is rude). 

----

For reference, the gil acquisition timeout logic is at : https://github.com/python/cpython/blob/322f962f3ee31d0dbde99e36379de8488ccc6804/Python/ceval_gil.h#L250-L271 and the interpreter main loop is in https://github.com/python/cpython/blob/322f962f3ee31d0dbde99e36379de8488ccc6804/Python/ceval.c (which is a lot more complicated than the last time I look at it).  I could have sworn that there was a "time or number of byte codes processed " logic, but I can not find it....

**Closed by tacaswell** 2022-01-17 19:10 UTC
Labels: topic: text, Performance
