### ISSUE TITLE
imshow rendering changed from 1.3.0 to 1.3.1

### ISSUE THREAD

**Issue by TwsThomas** [matplotlib/matplotlib#15608] opened 2019-11-06 12:14 UTC
**Bug summary**

imshow rendering changed from 1.3.0 to 1.3.1 when `yticks` ar set.
Square matrix display is no longer square.
Note that setting `xticks` do not affect the display.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.imshow([[1,2],[3,4]])
ax.set(yticks=[0,1])  # change the display in 1.3.1
```

outcome in 1.3.**1**
![image](https://user-images.githubusercontent.com/9698757/68293586-8a11cd80-008e-11ea-96c6-57651bf452f4.png)

Previous outcome in 1.3.**0**
![image](https://user-images.githubusercontent.com/9698757/68297201-a154b900-0096-11ea-8eac-4aa3bed7a94a.png)

**Matplotlib version**
  * Operating system: Linux
  * Matplotlib version:  1.3.0 / 1.3.1
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.7.3

**Comment by tacaswell** [comment] 2019-11-06 13:08
This will be fixed in 1.3.2 (hopefully released in the next few days), the issue is picking the limits of the y-axis incorrectly, if you do `set_ylim(-.5, 1.5)` you should get back the 1.3.0 results.

Duplicate of https://github.com/matplotlib/matplotlib/issues/14675

Fixed it #14677.

**Closed by tacaswell** 2019-11-06 13:08 UTC
