### ISSUE TITLE
Pyplot gallery section is mostly OO examples

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#15922] opened 2019-12-12 21:28 UTC
Somewhere between all the convert things to OO and restructure gallery PRs, the [pyplot](
https://matplotlib.org/devdocs/gallery/index.html#pyplot) section of the gallery now has very little pyplot content:

### PyPlot
- [ ] [plot() format string](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_formatstr.html#sphx-glr-gallery-pyplots-pyplot-formatstr-py)
- [ ] [Pyplot mathtext](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_mathtext.html#sphx-glr-gallery-pyplots-pyplot-mathtext-py)
- [ ] [Pyplot simple](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_simple.html#sphx-glr-gallery-pyplots-pyplot-simple-py)
- [ ] [Pyplot text](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_text.html#sphx-glr-gallery-pyplots-pyplot-text-py)
- [ ] [Pyplot three](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_three.html#sphx-glr-gallery-pyplots-pyplot-three-py)
- [ ] [Pyplot two subplots](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_two_subplots.html#sphx-glr-gallery-pyplots-pyplot-two-subplots-py)
### OO
- [ ] [Align y-labels](https://matplotlib.org/devdocs/gallery/pyplots/align_ylabels.html#sphx-glr-gallery-pyplots-align-ylabels-py)
- [ ] [Annotate Transform](https://matplotlib.org/devdocs/gallery/pyplots/annotate_transform.html#sphx-glr-gallery-pyplots-annotate-transform-py)
- [ ] [Annotate a plot](https://matplotlib.org/devdocs/gallery/pyplots/annotation_basic.html#sphx-glr-gallery-pyplots-annotation-basic-py)
- [ ] [Annotate Polar](https://matplotlib.org/devdocs/gallery/pyplots/annotation_polar.html#sphx-glr-gallery-pyplots-annotation-polar-py)
- [ ] [Auto Subplots Adjust](https://matplotlib.org/devdocs/gallery/pyplots/auto_subplots_adjust.html#sphx-glr-gallery-pyplots-auto-subplots-adjust-py)
- [ ] [Boxplot Demo](https://matplotlib.org/devdocs/gallery/pyplots/boxplot_demo_pyplot.html#sphx-glr-gallery-pyplots-boxplot-demo-pyplot-py)
- [ ] [Dollar Ticks](https://matplotlib.org/devdocs/gallery/pyplots/dollar_ticks.html#sphx-glr-gallery-pyplots-dollar-ticks-py)
- [ ] [Fig Axes Customize Simple](https://matplotlib.org/devdocs/gallery/pyplots/fig_axes_customize_simple.html#sphx-glr-gallery-pyplots-fig-axes-customize-simple-py)
- [ ] [Simple Axes labels](https://matplotlib.org/devdocs/gallery/pyplots/fig_axes_labels_simple.html#sphx-glr-gallery-pyplots-fig-axes-labels-simple-py)
- [ ] [Adding lines to figures](https://matplotlib.org/devdocs/gallery/pyplots/fig_x.html#sphx-glr-gallery-pyplots-fig-x-py)
- [ ] [Text Commands](https://matplotlib.org/devdocs/gallery/pyplots/text_commands.html#sphx-glr-gallery-pyplots-text-commands-py)
- [ ] [Text Layout](https://matplotlib.org/devdocs/gallery/pyplots/text_layout.html#sphx-glr-gallery-pyplots-text-layout-py)
- [ ] what's new examples in #15920 

I think there should be a standalone pyplot only gallery page, but think for this PR a potential resolution would be to sort the OO examples into the correct sections (possibly combining them with existing content) or altogether remove them if they're not adding any information. 

xref: #15355 because I think this contributes to some of the confusion discussed there.

**Comment by kolibril13** [comment] 2020-01-01 22:33
From https://github.com/matplotlib/matplotlib/issues/15938 timhoffm wrote:
> What we can do right now
In the short term, it would really help to better document the similarities and differences between pyplot and OO style. The current docs are not quite instructive on that; and no matter what we could add immediately what we plan to do in the long term, these are public APIs and will therefore be around for a long time.

>Additional thoughts
It may even be a good idea to have a complete separation on the API level, in the sense that there should be non-pyplot helper functions for figure/subplot creation (It might be that we still use the same figure management under the hood). That way, one can have two completely separate APIs. Emphasizing this may help to reduce confusion.


My thought to this:
Is it possible to have the whole API default to the pyplot style, but  every example has a button that switches the code example from pyplot to OO?
So that people can choose which code they want to see.

**Comment by timhoffm** [comment] 2020-01-02 00:44
Thanks for the idea! Unfortunately, switching examples between pyplot and OO is not possible.

- The examples are created from pure python files using sphinx-gallery. The switching mechanism would have to be integrated into that framework.
- We‘d need two versions of each example. IMHO auto-conversion is not feasible due to the hidden state in pyplot. Creating such a tool would either fail in more complicated cases or be extremely complicated to write. Given the large amount of examples, manually creating and maintaining multiple versions is also not an option.

**Comment by jklymak** [comment] 2022-09-28 02:42
There is some arguing about what should stay or go, but actually fixing this is pretty easy, so marking good first issue

**Comment by StefRe** [comment] 2022-09-28 07:33
As I'm the culprit of bringing up this topic again in #24023, here's my proposal:

Example | Decision
---|---
[Align y-labels ](https://matplotlib.org/devdocs/gallery/pyplots/align_ylabels.html)|move to Text, labels and annotations 
[Annotate Transform ](https://matplotlib.org/devdocs/gallery/pyplots/annotate_transform.html)|move to Text, labels and annotations 
[Annotating a plot ](https://matplotlib.org/devdocs/gallery/pyplots/annotation_basic.html)|move to Text, labels and annotations 
[Annotation Polar ](https://matplotlib.org/devdocs/gallery/pyplots/annotation_polar.html)|move to Text, labels and annotations 
[Programmatically controlling subplot adjustment ](https://matplotlib.org/devdocs/gallery/pyplots/auto_subplots_adjust.html)|move to Subplots, axes and figures 
[Infinite lines ](https://matplotlib.org/devdocs/gallery/pyplots/axline.html)|keep
[Boxplot Demo ](https://matplotlib.org/devdocs/gallery/pyplots/boxplot_demo_pyplot.html)|move to Statistics
[Dollar Ticks ](https://matplotlib.org/devdocs/gallery/pyplots/dollar_ticks.html)|remove (already covered by Tick formatters in Ticks section in more detail)
[Fig Axes Customize Simple ](https://matplotlib.org/devdocs/gallery/pyplots/fig_axes_customize_simple.html)|move to Ticks
[Simple axes labels ](https://matplotlib.org/devdocs/gallery/pyplots/fig_axes_labels_simple.html)|move to Text, labels and annotations (or remove it and add a regular y-label in the Using accented text in Matplotlib example)
[Adding lines to figures ](https://matplotlib.org/devdocs/gallery/pyplots/fig_x.html)|move to Miscellaneous
[plot() format string ](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_formatstr.html)|remove and merge into "Pyplot Simple"
[Pyplot Mathtext ](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_mathtext.html)|keep
[Pyplot Simple ](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_simple.html)|keep and combine with "plot() format string"
[Pyplot Text ](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_text.html)|keep
[Pyplot Three ](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_three.html)|keep
[Pyplot Two Subplots ](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_two_subplots.html)|keep
[Text Commands ](https://matplotlib.org/devdocs/gallery/pyplots/text_commands.html)|move to Text, labels and annotations (although there already lots of similar examples there)
[Text Layout ](https://matplotlib.org/devdocs/gallery/pyplots/text_layout.html)|remove (duplicate of Text alignment in Text, labels and annotations)

**Closed** 2022-10-02 16:37 UTC
Labels: Documentation, Good first issue
