### ISSUE TITLE
Matplotlib fails installation using pip on Python 3.9 on macOS

### ISSUE THREAD

**Issue by orome** [matplotlib/matplotlib#18881] opened 2020-11-03 17:15 UTC
### Bug report

**Bug summary**

Matplotlib errors on installation on Python 3.9 on macOS Catalina.

**Code for reproduction**

In a fresh directory, with an empty pip cache (`~/Library/Caches/pip` )
```bash
mkvirtualenv --python=`which python3` testmpl
pip install matplotlib
```

**Actual outcome**

Installation fails with
```
  ERROR: Command errored out with exit status 1:
   command: /Users/Orome/Documents/Projects/Coding/Python/venvs/testmpl/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b6/3rk65h797p7407x7d36sqn9c0000gn/T/pip-install-4lxqi3sx/matplotlib/setup.py'"'"'; __file__='"'"'/private/var/folders/b6/3rk65h797p7407x7d36sqn9c0000gn/T/pip-install-4lxqi3sx/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/b6/3rk65h797p7407x7d36sqn9c0000gn/T/pip-wheel-r8ksc5eb
       cwd: /private/var/folders/b6/3rk65h797p7407x7d36sqn9c0000gn/T/pip-install-4lxqi3sx/matplotlib/
  Complete output (17183 lines):
 ...
ERROR: Command errored out with exit status 1: /Users/Orome/Documents/Projects/Coding/Python/venvs/testmpl/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b6/3rk65h797p7407x7d36sqn9c0000gn/T/pip-install-4lxqi3sx/matplotlib/setup.py'"'"'; __file__='"'"'/private/var/folders/b6/3rk65h797p7407x7d36sqn9c0000gn/T/pip-install-4lxqi3sx/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/b6/3rk65h797p7407x7d36sqn9c0000gn/T/pip-record-_pg93m6w/install-record.txt --single-version-externally-managed --compile --install-headers /Users/Orome/Documents/Projects/Coding/Python/venvs/testmpl/include/site/python3.9/matplotlib Check the logs for full command output.
```
Complete output [here](https://gist.github.com/orome/eec2446aeb5e8fc5cc3ab283c7cc03ef).

**Expected outcome**

Expected same behavior as with Python 3.8, which results in a successful installation.

**Matplotlib version**

Matplotlib: 3.3.2
Python: 3.9.0 (Homebrew in ~/Users/Roy/Documents/Projects/Coding/Python/venvs/testmpl/bin/)
Clang: 12.0 build 1200
macOS: 10.15.7-x86_64
CLT: 12.1.0.0.1.1602137645
Xcode: 12.1

**Comment by neeraj162** [comment] 2020-11-04 08:07
hi i am new to open source contribution and i wanted to learn , i wanted to fix this one , could you please guide me through it  and explain me how to fix it and what all i require to fix

**Comment by jarrodmillman** [comment] 2020-11-05 17:14
See #18842.

**Comment by orome** [comment] 2020-11-05 20:40
@jacobherrington [Any estimate on or plans for when this will be fixed?](https://github.com/matplotlib/matplotlib/pull/18842#issuecomment-722480869)

**Comment by tacaswell** [comment] 2020-11-05 21:03
It is difficult to debug this on the provided information, but I suspect that you are missing one of the required system packages, see https://matplotlib.org/users/installing.html#installing-from-source .

Closing this as it is not a bug and are planning to publish 3.9 wheels with the next patch release.

**Closed by tacaswell** 2020-11-05 21:03 UTC

**Comment by orome** [comment] 2020-11-05 21:08
> ... planning to publish 3.9 wheels with the next patch release.

Excellent!
