### ISSUE TITLE
[Bug]: DLL load failed while importing _imaging

### ISSUE THREAD

**Issue by rootsmusic** [matplotlib/matplotlib#27549] opened 2023-12-20 19:02 UTC
### Bug summary

[Pillow >= 2.1.0](https://pillow.readthedocs.io/en/stable/installation.html#warnings) no longer supports `import _imaging`.

### Code for reproduction

```python
import matplotlib as mpl
```

### Actual outcome

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\anaconda3\envs\pandas\lib\site-packages\matplotlib\__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\ProgramData\anaconda3\envs\pandas\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\ProgramData\anaconda3\envs\pandas\lib\site-packages\matplotlib\colors.py", line 52, in <module>
    from PIL import Image
  File "C:\ProgramData\anaconda3\envs\pandas\lib\site-packages\PIL\Image.py", line 82, in <module>
    **from . import _imaging as core**
ImportError: DLL load failed while importing _imaging: The specified module could not be found.

### Expected outcome

no error

### Operating system

Windows 11

### Matplotlib Version

3.8.2

### Python version

3.9.18

### Jupyter version

7.0.6

### Installation

conda

**Comment by tacaswell** [comment] 2023-12-20 19:07
The issue is that your installation of one of our dependencies (pillow) is broken

```
...
File "C:\ProgramData\anaconda3\envs\pandas\lib\site-packages\PIL\Image.py", line 82, in
from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.
```

This is the extension module from PIL.   I suggest re-installing pillow via conda (mixing the use of pip and conda "works" until it does not and causes obscure import errors like this one) or re-creating the environment (when environments get broken it is frequently fastest to re-create them from scratch than try to sort out why they are broken and fix them).


I am going to close this because there is nothing we can do in Matplotlib to prevent this.

**Comment by tacaswell** [comment] 2023-12-20 19:08
If you have more questions, they are better directed to https://discourse.matplotlib.org/c/community/install/13

**Closed by tacaswell** 2023-12-20 19:07 UTC
Labels: Community support

**Comment by rootsmusic** [comment] 2023-12-20 19:12
> If you have more questions, they are better directed to https://discourse.matplotlib.org/c/community/install/13

Ok @tacaswell.  According to Pillow though, "Pillow >= 2.1.0 no longer supports `import _imaging`."

**Comment by tacaswell** [comment] 2023-12-20 19:18
The line in Matplotlib is https://github.com/matplotlib/matplotlib/blob/e5562bb7453c50321070784372cefa75339992e7/lib/matplotlib/colors.py#L52-L53 the call to `_imaging` is internal to pillow.  This suggests you have a "chimera" installation with files from a mix of pillow versions.
