### ISSUE TITLE
[Bug]: inset_locator is broken when used with subfigures

### ISSUE THREAD

**Issue by amcpherson** [matplotlib/matplotlib#24589] opened 2022-12-02 23:49 UTC
### Bug summary

When using inset_locator functions in subfigures, the plots are not placed correctly.  Adapting this demo
https://matplotlib.org/stable/gallery/axes_grid1/demo_colorbar_of_inset_axes.html
to use subfigures shows incorrect plots.

### Code for reproduction

```python
from matplotlib import cbook
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1.inset_locator import inset_axes, zoomed_inset_axes


fig = plt.figure()
fig1, fig2 = fig.subfigures(nrows=2, ncols=1, height_ratios=[1, 1], squeeze=True)

ax = fig1.subplots()
ax.set(aspect=1, xlim=(-15, 15), ylim=(-20, 5))

Z = cbook.get_sample_data("axes_grid/bivariate_normal.npy", np_load=True)
extent = (-3, 4, -4, 3)

axins = zoomed_inset_axes(ax, zoom=2, loc='upper left')
axins.set(xticks=[], yticks=[])
im = axins.imshow(Z, extent=extent, origin="lower")

# colorbar
cax = inset_axes(axins,
                 width="5%",  # width = 10% of parent_bbox width
                 height="100%",  # height : 50%
                 loc='lower left',
                 bbox_to_anchor=(1.05, 0., 1, 1),
                 bbox_transform=axins.transAxes,
                 borderpad=0,
                 )
fig.colorbar(im, cax=cax)

plt.show()
```

### Actual outcome

<img width="414" alt="image" src="https://user-images.githubusercontent.com/1170234/205410117-9ed9619c-2368-42a8-bfbc-8909cfb9eba1.png">

### Expected outcome

Something more similar to https://matplotlib.org/stable/gallery/axes_grid1/demo_colorbar_of_inset_axes.html

### Operating system

OS/X

### Matplotlib Version

3.6.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Installation

pip

**Comment by jklymak** [comment] 2022-12-03 01:09
That seems likely as `axes_grid1` is not very subfigure-aware.  Did you try with `ax.inset_axes` instead?

**Comment by anntzer** [comment] 2022-12-03 20:51
From a quick try, the fix seems to be simply
```patch
diff --git i/lib/mpl_toolkits/axes_grid1/inset_locator.py w/lib/mpl_toolkits/axes_grid1/inset_locator.py
index bb90f8273c..0771efd71f 100644
--- i/lib/mpl_toolkits/axes_grid1/inset_locator.py
+++ w/lib/mpl_toolkits/axes_grid1/inset_locator.py
@@ -73,7 +73,7 @@ class AnchoredLocatorBase(AnchoredOffsetbox):
         bbox = self.get_window_extent(renderer)
         px, py = self.get_offset(bbox.width, bbox.height, 0, 0, renderer)
         bbox_canvas = Bbox.from_bounds(px, py, bbox.width, bbox.height)
-        tr = ax.figure.transFigure.inverted()
+        tr = ax.figure.transSubfigure.inverted()
         return TransformedBbox(bbox_canvas, tr)
```

**Comment by tacaswell** [comment] 2022-12-05 02:22
Labeling this as easy and good first issue because there is a proposed patch and a clear reproduction case.

The tasks here:
 - verify the proposed patch fixes the issue and commit it
 - write a test (based on the bug report)  This may be a bit tricky to do without adding an image test and I suspect be a vast majority of the work on this issue

**Comment by matt256** [comment] 2022-12-08 04:53
mind if I grab this one? Long time user. Would love to be a first time contributor

**Comment by amcpherson** [comment] 2022-12-08 13:01
ax.inset_axes works great btw

**Comment by oscargus** [comment] 2022-12-08 13:09
Please go ahead @matt256 ! We do not assign issues though.

**Comment by matt256** [comment] 2022-12-09 14:18
Understood. Thank you and will do. Fix confirmed. Working on the test

**Comment by matt256** [comment] 2022-12-10 14:58
PR submitted, but i had some issues with the styling of the test image through the decorator not being classic so i just made the comparison image in the classic style. Naturally i figured out i had to change it to mpl20 as soon as I submitted the PR. I assume i can push another commit to a PR?

**Comment by melissawm** [comment] 2022-12-11 19:52
Sure @matt256, you can update your PR as needed. If you need help feel free to ping 😄

**Comment by Gairick52** [comment] 2023-01-10 13:37
@amcpherson  Hello sir,i want to work on this issue,please assign this to me

**Closed** 2023-01-10 15:23 UTC
Labels: topic: mpl_toolkit, Difficulty: Easy, Good first issue, status: has patch
