### ISSUE TITLE
[Bug]: imshow three channel image with pixelwise alpha parameter does not work

### ISSUE THREAD

**Issue by Daraan** [matplotlib/matplotlib#24333] opened 2022-11-01 12:41 UTC
### Bug summary

Using `plt.imshow(B, alpha=alphas)` where B has dimensions NxMx3 and alphas NxM ignores the the alpha parameter is silently ignored and B displayed as is.

### Code for reproduction

```python
import matplotlib as m
import matplotlib.pyplot as plt
import numpy as np

A=np.arange(5*5*3).reshape((5,5,3)) / (5*5*3)

plt.imshow(A)
plt.title("A")
plt.show()

B = np.zeros(5*5*3).reshape((5,3,5))
B[2:4, 2:4] = 1
B.shape = (5,5,3) # do some shifting so its not grayscale
plt.imshow(B)
plt.title("B")
plt.show()

alphas = np.zeros(5*5).reshape((5,5))
alphas[B[:,:,1] > 0] = 0.66
plt.imshow(alphas)
plt.title("Alpha mask")
plt.show()

plt.imshow(A)
plt.imshow(B, alpha=alphas) # gives wrong result
plt.title("wrong result")
plt.show()
```

### Actual outcome

![https://i.stack.imgur.com/6mHzi.png](https://i.stack.imgur.com/6mHzi.png)

### Expected outcome

![grafik](https://user-images.githubusercontent.com/27899926/199234396-d22d1863-93b5-4846-83d3-eb3edbb7ecba.png)

### Additional information

Providing just a single alpha value or the alpha instead as alpha channel in B NxMx4 works.  
But there is no warning to apply this fix or automatically merge it to apply the alpha channel as expected.

### Operating system

linux and windows

### Matplotlib Version

3.5.2 and 3.6.0

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

'3.9.7' and 3.10.6 

### Jupyter version

3.4.4

### Installation

conda

**Comment by tacaswell** [comment] 2022-11-01 16:31
I think the fix is either to enrich the RGB to be RGBA in this case _or_ to raise an exception if both `alphas` is set for non falescolor data.  I can see arguments for both, but this is the worst of all options.

**Comment by QuLogic** [comment] 2024-01-04 09:02
This is a duplicate of #26092, which while newer, does seem to have a bit more discussion.

**Closed by QuLogic** 2024-01-04 09:02 UTC
Labels: topic: color/alpha, topic: images
