### ISSUE TITLE
The documentation on "how to write documentation" need to be updated

### ISSUE THREAD

**Issue by NelleV** [matplotlib/matplotlib#7217] opened 2016-10-04 17:28 UTC
The documentation on how to write documentation is out of date:

http://matplotlib.org/devdocs/devel/documenting_mpl.html#documenting-matplotlib

Specifically, it should refer to our [MEP10](http://matplotlib.org/devdocs/devel/MEP/MEP10.html)

**Comment by NelleV** [comment] 2016-11-10 22:43
Bumping this to 2.1

**Comment by timhoffm** [comment] 2017-12-09 21:31
This is on it's way. The issue is basically duplicate with #9876. Maybe one should mere/collect the stuff in one issue.

Related pull requests:
#9884
#9875 
#9872
#9805
#9786
#9513

**Comment by dstansby** [comment] 2018-02-13 12:40
All those PRs are closed, and we've had a big overhaul of the dev documentation, so shall we close this?

**Comment by remram44** [comment] 2019-12-04 18:54
#9876 was closed but not this

**Comment by NelleV** [comment] 2019-12-04 21:17
Thanks @remram44

**Closed** 2019-12-04 21:17 UTC
Labels: Difficulty: Easy, Documentation
