### ISSUE TITLE
scatterplot axis autoscale fails for small data values

### ISSUE THREAD

**Issue by ariekahn** [matplotlib/matplotlib#6015] opened 2016-02-17 15:56 UTC
I'm finding that the scatterplot autoscaling fails when plotting small values, e.g. <0.001.

The autoscale axis range will never go below -0.008 to 0.008 for me, regardless of how small the range of the data being plotted.

```
plt.figure()
x = np.array([0,1,2,3])
x = np.array([2,4,5,9])
plt.scatter(x,y)
```

Data in a normal range produces
![properly_scaled](https://cloud.githubusercontent.com/assets/54182/13114875/6df15a58-d563-11e5-9655-3276b3b07196.png)

```
plt.figure()
x = np.array([0,1,2,3])
x = np.array([2,4,5,9])
plt.scatter(x/10000,y/10000)
```

While scaling it down produces
![badly_scaled](https://cloud.githubusercontent.com/assets/54182/13114872/6a557f82-d563-11e5-9ef1-93bd4f8bd4b3.png)

**Comment by tacaswell** [comment] 2016-02-18 03:52
On 2.x it seems to go to pm 0.002.

I assume this is due to the non-singular expanding logic?

**Comment by dstansby** [comment] 2017-01-29 19:51
ping @mdboom, I may be wrong, but the referenced commit above doesn't relate to this bug?

**Comment by ImportanceOfBeingErnest** [comment] 2018-07-12 10:14
This problem is still present in current master.

**Comment by FraserParlane** [comment] 2019-01-05 00:51
Apart from manually scaling, is there a workaround for this issue?

**Comment by LindyBalboa** [comment] 2019-01-05 05:17
You can use .plot() instead and use linestyle='none' and define markers.
Obviously this doesn't have the same features as scatter but for basic
functionality it works.

Am Sa., 5. Jan. 2019, 01:52 hat Fraser Parlane <notifications@github.com>
geschrieben:

**Comment by trbedwards** [comment] 2019-01-11 09:13
If you still want the scatter functionality and have autoscale working, there's a good workaround I found  on [stackoverflow](https://stackoverflow.com/questions/45757260/matplotlibs-autoscale-doesnt-seem-to-work-on-y-axis-for-small-values) where you create an invisible `plot` after `scatter`:

```
import matplotlib.pyplot as plt

y=  [1.09E-05,  1.63E-05,   2.45E-05,   3.59E-05,   5.09E-05,   6.93E-05,   9.07E-05]
x=  [0, 10, 20, 30, 40, 50, 60]

fig3, ax3 = plt.subplots()
ax3.scatter(x, y, color='k', marker = "o")
ax3.plot(x, y, color='none')
ax3.relim()
ax3.autoscale_view()
plt.show()
```

**Comment by ImportanceOfBeingErnest** [comment] 2019-12-17 03:02
Closing as fixed by https://github.com/matplotlib/matplotlib/pull/13642

**Closed by ImportanceOfBeingErnest** 2019-12-17 03:02 UTC

**Comment by episodeyang** [comment] 2020-01-19 20:39
Still has this problem.

**Comment by jklymak** [comment] 2020-01-19 20:42
#13642 will be in 3.2

**Comment by moloney** [comment] 2020-02-14 21:56
I installed the 3.2.0rc3 package, and I can confirm that this fixes almost all the issues with autoscaling and `scatter`.  However, if you have points with 0 for the y-axis and enable log scaling there is still an issue with the scatter plot auto scaling (that doesn't show up with the standard `plot` function).

```python
import itertools

import numpy as np
from matplotlib import pyplot as plt


x_vals = [4.38462e-06,
          5.54929e-06,
          7.02332e-06,
          8.88889e-06,
          1.125e-05,
          1.42383e-05,
          1.80203e-05,
          2.2807e-05,
          2.88651e-05,
          3.65324e-05,
          4.62363e-05,
          5.85178e-05,
          7.40616e-05,
          9.37342e-05,
          0.000118632,
          ]

y_vals = [0.0,
          0.10000000000000002,
          0.182,
          0.332,
          0.604,
          1.1,
          2.0,
          3.64,
          6.64,
          12.100000000000001,
          22.0,
          39.60000000000001,
          71.3,
          ]

pts = np.array(list(itertools.product(x_vals, y_vals)))

fig = plt.figure("Scatter plot")
ax = fig.gca()
ax.set_xscale('log')
ax.set_yscale('log')
ax.scatter(pts[:,0], pts[:,1]) # This only shows four rows of points

fig = plt.figure("Regular plot")
ax = fig.gca()
ax.set_xscale('log')
ax.set_yscale('log')
ax.plot(pts[:,0], pts[:,1], marker="o", ls="") # This works

plt.show()
```

**Comment by jklymak** [comment] 2020-02-15 15:23
Can you open this as a new issue?
