### ISSUE TITLE
https://matplotlib.org/users/beginner.html is outdated

### ISSUE THREAD

**Issue by marcelm** [matplotlib/matplotlib#12162] opened 2018-09-19 07:59 UTC
There seems to be an outdated tutorial page online at https://matplotlib.org/users/beginner.html . It has the old “Matplotlib 2.0.0rc2 is available – Install the release candidate now!“ banner.

I guess it’s not reachable from the main page, but it comes up in Google results.

**Comment by QuLogic** [comment] 2018-09-19 08:37
Duplicate of #9556 (and others.)

**Closed by QuLogic** 2018-09-19 08:37 UTC
