### ISSUE TITLE
Incorrect tick labels on colorbar

### ISSUE THREAD

**Issue by natechols** [matplotlib/matplotlib#15756] opened 2019-11-22 19:50 UTC
### Bug report

**Bug summary**

After porting all of our remaining Python 2 code to 3.7.3, and updating matplotlib from 2.2.4 to 3.1.2, I can no longer get the desired colorbar behavior.  Hopefully the images below explain the problem sufficiently.  I've tried many different variations of the code below and most of them lead to the colorbar being full-length but with the tick labels invisible.

**Code for reproduction**
```python
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.cm
import matplotlib.colors
from matplotlib import ticker
import numpy as np

import random

def hexbin_plot(x, y, png_file_name):
    def _get_ticks(vmin, vmax):
        vmin, vmax = 10**vmin, 10**vmax
        ticks = []
        for n in [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]:
            if vmin <= n <= vmax:
                ticks.append(n)
        return ticks
    CMAP = "rainbow"
    assert len(x) == len(y)
    x = np.log10(x)
    y = np.log10(y)
    bins = "log"  # this is the colormap scaling, not the x/y
    fig = plt.figure(figsize=(9,12))
    axes = fig.add_subplot(111)
    cmap = matplotlib.cm.get_cmap(CMAP, 16)
    cmap.set_under(color=(1.0, 1.0, 1.0, 0.0))  # pylint: disable=no-member
    min_xy = min(x.min(), y.min()) * 0.95
    max_xy = max(x.max(), y.max()) * 1.02
    hb = axes.hexbin(x, y,
                     gridsize=(80, 80),
                     mincnt=1,
                     cmap=cmap,
                     bins=bins,
                     extent=(min_xy, max_xy, min_xy, max_xy))
    axes.set_xlabel("Metric 1", fontsize=20)
    axes.set_ylabel("Metric 2", fontsize=20)
    # integer axis labels
    xmin, xmax = axes.get_xlim()
    ymin, ymay = axes.get_ylim()
    xticks = _get_ticks(xmin, xmax)
    yticks = _get_ticks(ymin, ymay)
    axes.set_xticks(np.log10(xticks))
    axes.set_yticks(np.log10(yticks))
    axes.set_xticklabels(["{:,}".format(n) for n in xticks])
    axes.set_yticklabels(["{:,}".format(n) for n in yticks])
    for tick in axes.get_xticklabels():
        tick.set_rotation(45)
    # colorbar
    if matplotlib.__version__ == "3.1.2":
        cmax = np.log10(hb.norm.vmax)
    else:
        cmax = hb.norm.vmax
    cb = fig.colorbar(hb,
                      ax=axes,
    )#                  ticks=cb_ticks)
    #cmin, cmax = cb.get_clim()
    cb.set_label("Counts", fontsize=20)
    cb_ticks = [(-0.0625 + (0.125 * i)) for i in range(1, 9)]
    cb.ax.get_yaxis().set_ticks(cb_ticks)
    cb_tick_labels = [str(int(np.round(10**(t * cmax)))) for t in cb_ticks]
    cb.ax.get_yaxis().set_ticklabels(cb_tick_labels)
    print(list(cb.ax.get_yticklabels()))
    plt.tight_layout()
    plt.savefig(png_file_name)

m1 = np.array([int(random.gauss(50000, 10000)) for n in range(10000)])
m2 = np.array([int(random.gauss(20000, 5000)) for n in range(10000)])
sel = (m2 <= m1) & (m2 > 10)
m1 = m1[sel]
m2 = m2[sel]
hexbin_plot(m1, m2, "hexbin.png")
```

**Actual outcome**

matplotlib 2.2.4:
![hexbin_2 2 4](https://user-images.githubusercontent.com/4529952/69455650-b62f7e80-0d1d-11ea-9c19-74488516d872.png)

matplotlib 3.1.2:
![hexbin_3 1 2](https://user-images.githubusercontent.com/4529952/69455779-f7c02980-0d1d-11ea-95a8-4f1d1e938207.png)

**Expected outcome**

The 2.2.4 version of the plot is correct.  Labels should be rendered correctly, as simple integers (not scientific notation), aligned with the colorbar.

**Matplotlib version**
  * Operating system: Linux
  * Matplotlib version: 3.1.2, installed via pip
  * Matplotlib backend (`print(matplotlib.get_backend())`): Agg
  * Python version: 3.7.3

**Comment by natechols** [comment] 2019-11-22 19:52
PS. A side note: `hb.norm.vmax` is different as well, hence the version-specific `if` statement.  I was using `cb.get_clim()` before, which worked fine in 2.2.4, but that is now deprecated so I'd like to avoid it.

**Comment by dstansby** [comment] 2019-11-27 16:59
Thanks for posting a reproducible example with a bit of code! It's quite a long bit of code though, so would it be possible to go through and remove all the lines that are non-essential to reproduce the bug?

**Comment by jklymak** [comment] 2019-11-28 15:07
The problem is that previous to 3.1 colorbars were made with a fake axes that ran between zero and one.  Now it behaves like a normal axes and runs between `cmin` and `cmax`.  If you just do the default you get:

![cbar](https://user-images.githubusercontent.com/1562854/69815996-5f59f700-11ac-11ea-9c0a-2b59478cf3f6.png)

If you really don't want a logarithmic looking axes:

```python
     cb = fig.colorbar(hb,
                      ax=axes,)
    cb.set_label("Counts", fontsize=20)
    yax = cb.ax.get_yaxis()

    yax.set_ticks([1, 2, 4, 6, 11, 19, 32, 54])
    yax.set_major_formatter(matplotlib.ticker.ScalarFormatter())
    cb.ax.minorticks_off()
```

![Figure_1](https://user-images.githubusercontent.com/1562854/69816591-8d8c0680-11ad-11ea-96fd-2da52cabe082.png)

**Comment by jklymak** [comment] 2019-11-28 15:09
I'm going to close this because this was an already announced API change, and I think things are working as expected, though I appreciate the change from the previous work around was confusing.

**Closed by jklymak** 2019-11-28 15:09 UTC
Labels: colorbar
