### ISSUE TITLE
Antialiasing with colorbars?

### ISSUE THREAD

**Issue by karlwx** [matplotlib/matplotlib#17746] opened 2020-06-24 16:20 UTC
### Problem
When using contourf with alpha < 1, these ugly lines appear at the color boundaries. This is evident both in the contoured data as well as on the colorbar. 
![new_look_0](https://user-images.githubusercontent.com/45180714/85592661-5c28cb80-b614-11ea-98b5-bdd1df31abf4.png)

I can set antialiased=True in contourf to fix the problem with the data, but the lines on the colorbar remain. 
![new_look](https://user-images.githubusercontent.com/45180714/85592658-5c28cb80-b614-11ea-9079-a608503ae940.png)

As far as I can tell from the documentation, there doesn't seem to be a way to set antialiasing for the colorbar. Is there any way to get rid of these lines?

**Comment by jklymak** [comment] 2020-06-24 16:30
You can get the quadmesh object from the colorbar as `cb.solids`, and then do `cb.solids.set_antialiased(True)`

Interestingly, the `ColorbarBase` class doesn't document the solids as an attribute, despite the fact that it documents `lines` etc.  So I think this qualifies as a documentation bug.

**Comment by karlwx** [comment] 2020-06-24 18:36
Unfortunately, trying `cb.solids.set_antialiased(True)` does not change anything for me. 
A workaround is `cb.solids.set_alpha(1)` - this gets rid of the lines, but now the colorbar colors don't quite match the contours (obviously). 

Here's what I'm trying:
```
cb = plt.colorbar(plot, cax=ax2, ticks=cmap.cbar_labels, orientation='vertical', extendfrac=0,
                          boundaries=cmap.color_levels, spacing='uniform', format=ticker.FuncFormatter(fmt))
cb.solids.set_antialiased(True)
cb.ax.tick_params(size=0)
```

**Comment by jklymak** [comment] 2020-06-24 18:37
Try rasterizing the solids?  We could help you more if you provided stripped down code.

**Comment by karlwx** [comment] 2020-06-24 18:47
Here's a simple example:

```
import matplotlib.pyplot as plt
import numpy as np

testdata = np.random.rand(10,10)
plt.figure(figsize=(10,10))
plt.contourf(testdata, cmap='Blues', alpha=0.5, antialiased=True)
cb = plt.colorbar()
cb.solids.set_antialiased(True)
cb.solids.set_rasterized(True)
```

**Comment by jklymak** [comment] 2020-06-24 19:58
@efiring do you know what is going on here?

**Comment by QuLogic** [comment] 2020-06-24 21:47
This is a duplicate of #1188.

**Closed by QuLogic** 2020-06-24 21:47 UTC
Labels: Documentation
