### ISSUE TITLE
Matplotlib installation fails if ``freetype-config --ftversion`` returns unexpected output

### ISSUE THREAD

**Issue by jbzdak** [matplotlib/matplotlib#4741] opened 2015-07-18 14:09 UTC
When I tried to install matplotlib I got following error (I used newest version in pip):

```
   Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-imsaf6c5/matplotlib/setup.py", line 155, in <module>
        result = package.check()
      File "/tmp/pip-build-imsaf6c5/matplotlib/setupext.py", line 961, in check
        min_version='2.3', version=version)
      File "/tmp/pip-build-imsaf6c5/matplotlib/setupext.py", line 445, in _check_for_pkg_config
        if (not is_min_version(version, min_version)):
      File "/tmp/pip-build-imsaf6c5/matplotlib/setupext.py", line 173, in is_min_version
        return found_version >= expected_version
      File "/home/jb/.pythonz/pythons/CPython-3.4.3/lib/python3.4/distutils/version.py", line 76, in __ge__
        c = self._cmp(other)
      File "/home/jb/.pythonz/pythons/CPython-3.4.3/lib/python3.4/distutils/version.py", line 343, in _cmp
        if self.version < other.version:
    TypeError: unorderable types: str() < int()
```

Problem was caused by `freetype-config --ftversion` command returning unexpected output, that is: 

```
freetype-config --ftversion
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
(...)
warning: GREP_OPTIONS is deprecated; please use an alias or script
2.5.2
```

Warnings were coming from grep that was whining about `GREP_OPTIONS` set in my enviorment. When I unexported this variable installation procedeed without error.

**Comment by tacaswell** [comment] 2015-07-20 19:21
I think this is a duplicate of https://github.com/matplotlib/matplotlib/issues/3889

**Comment by DSLituiev** [comment] 2015-07-20 20:56
I experiecned the same problem under Anaconda Python3.4. Tried to install both directly `python3 setup.py install` from the repository `.zip` and with `pip`. Freetype is insalled with `brew`

                        * The following required packages can not be built:
                        * freetype
brew:
    $ brew list
    freetype	libpng

**Comment by tacaswell** [comment] 2015-07-20 20:57
Do you have pkg-config installed?

**Comment by DSLituiev** [comment] 2015-07-20 21:00
No. Now I installed it and it works. Thank you!
Probably a good idea is to check for it during installation.

**Comment by efiring** [comment] 2019-05-23 01:43
This doesn't look like a current problem.  Closing.

**Closed by efiring** 2019-05-23 01:43 UTC
