### ISSUE TITLE
data-sensitive bug found.

### ISSUE THREAD

**Issue by cjliux** [matplotlib/matplotlib#8642] opened 2017-05-19 09:10 UTC
Only an empty canvas can be seen when I call `plt.bar([0, 18000, 36000], [1, 200, 2])`

**Comment by tacaswell** [comment] 2017-05-19 14:25
The problem is that the widths of the rectangles defaults to 0.8 (see http://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.bar.html?highlight=bar#matplotlib-axes-axes-bar ).  At that xrange the bars are _much_ narrower than a single pixel and the anti-aliasing is making them invisible.

```
 plt.bar([0, 18000, 36000], [1, 200, 2], width=1000)
```

Works as expected.

Closing as not a bug.

**Closed by tacaswell** 2017-05-19 14:25 UTC
