### ISSUE TITLE
[Bug]: incorrect display of 3d barchart

### ISSUE THREAD

**Issue by 51moon** [matplotlib/matplotlib#25333] opened 2023-02-26 13:13 UTC
### Bug summary

There are several rendering errors when creating a `bar3d` chart:
- for some bars the side walls are missing, e.g. at (1,0), (3,0) or (7,0).
- the edge to the x-axis of the top of bar (0,1) is partially visible, although it should be completely covered by bar (0,0).
- the label of the y-axis is shifted to the left, the 0 is not at the level of the 0-coordinate.

The list of errors is not complete, I think everyone can recognize the errors when looking closely.

### Code for reproduction

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm

# generate data
x = np.array(10*list(range(10)))
y = np.array([])
for i in x[0:10]:
    y = np.append(y,np.ones(10)*i)
rng = np.random.default_rng(4)
z = rng.random(len(x))+0.5

# plot
fig = plt.figure()
ax = fig.add_subplot(1,1,1, projection='3d')
ax.set_xlabel('x')
ax.set_ylabel('y')
x_pos = x-1/2
y_pos = y-1/2
z_pos = [0]*len(z)
x_size = np.ones(len(z))
y_size = np.ones(len(z))
z_size = z
colormap = cm.ScalarMappable()
color = colormap.to_rgba(z)
ax.bar3d(x_pos, y_pos, z_pos, x_size, y_size, z_size, color=color, shade=True)
plt.savefig('plt.png', dpi=300)
```

### Actual outcome

![plt](https://user-images.githubusercontent.com/81165783/221412290-1787d46c-ca96-4f93-a65c-c7d34b1fc2d0.png)

### Expected outcome

I expect a correct 3D rendering

### Additional information

There is a similar bug [reported here](https://github.com/matplotlib/matplotlib/issues/13728).

### Operating system

Linux Mint

### Matplotlib Version

3.7.0

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.10.6

### Installation

pip

**Comment by jklymak** [comment] 2023-02-26 15:52
This is basically expected.  Matplotlib doesn't have a full 3D rendering pipeline so individual artists are drawn one at a time with no knowledge of the other artists.  When you have many of them together like this, their zorders overlap and things don't look right. 

It would be great if Matplotlib had a proper 3D engine but that is unlikely to happen any time soon, and previous attempts have simply been spun out to other projects.

**Comment by 51moon** [comment] 2023-02-26 16:26
Ok, that's a pity, but good to know. So I will look around for an alternative. Can you name some of these spin-off projects?

**Comment by jklymak** [comment] 2023-02-26 16:31
mayavi is the one that comes to my mind, but there are others.

**Comment by jklymak** [comment] 2023-02-26 16:33
You may also want to check out the experimental: https://github.com/rougier/matplotlib-3d

**Comment by anntzer** [comment] 2023-03-01 16:45
Closing as essentially duplicate of #13728.

**Closed by anntzer** 2023-03-01 16:45 UTC
