### ISSUE TITLE
Rasterizing patch in legend changes position - PDF backend

### ISSUE THREAD

**Issue by claria** [matplotlib/matplotlib#6227] opened 2016-03-26 12:37 UTC
Hi,

i plot a rasterized patch and also want the patch in the legend to be rasterized.
It works fine in the agg backend, but fails in the PDF backend:

mpl version: 1.5.1, python 3.5.1, arch linux

Code to reproduce the issue:

```
import matplotlib
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)


patch1 = matplotlib.patches.Rectangle((0.5, 0.5), 1., 1., color='red', label='patch1')
patch2 = matplotlib.patches.Rectangle((2.0, 0.5), 1., 1., color='blue', label='patch2')

ax.add_patch(patch1)
ax.add_patch(patch2)

ax.set_xlim(0., 3.5)
ax.set_ylim(0., 3)

legend = ax.legend()
# rasterize first  patch in legend
legend.get_patches()[0].set_rasterized(True)

fig.savefig('asdf.png')
fig.savefig('asdf.pdf')
```

PNG output:
![asdf](https://cloud.githubusercontent.com/assets/1030408/14060062/68410060-f357-11e5-8f47-0bac65b8b7d3.png)

PDF output:
![asdf pdf](https://cloud.githubusercontent.com/assets/1030408/14060063/6bf183ec-f357-11e5-85e6-64760f9bd341.png)

**Comment by QuLogic** [comment] 2016-03-26 21:33
Confirmed not working on 1.5.x, 2.x, or master.

**Comment by claria** [comment] 2016-03-27 19:26
There must be some hardcoded dependency on the dpi=72 in the raster backend. If i set
`
matplotlib.rcParams['savefig.dpi'] = 72
`
before plotting (it was 150 before), the legend patch is placed in the correct position.

**Comment by tacaswell** [comment] 2016-03-27 20:31
I think it is more that the pdf backend has a fixed dpi of 72 and the image dpi is getting used for the transform instead of 72.

**Comment by tacaswell** [comment] 2016-03-27 21:51
And this is not a regression for 1.4.3 _or_ fixed by the recent image overhaul

**Comment by tacaswell** [comment] 2016-03-28 00:49
I spent a while chasing down this rabbit hole, and the problem here is that the pdf backend uses a mixed renderer (vector and raster) and they have different DPI.  The legend is implemented as a (deeply) nested `OffsetBox` which provides a 'local' rendering area via many stacked translations _in screen space_.   If some of the artists in the nested offset boxes are rasterized the offsets get crossed.  I _think_ what is happening is that the artists have (eventually) an offset specified in screen space so the rasterizer draws in in the wrong place on the temporary raster buffer and then that wrongly drawn image is correctly transferred to the pdf.

One possible work around is to rasterize the _whole_ legend which will draw it in the correct place (but now your text is no longer a vector) or to, as you discovered, use a dpi of 72 for your rasterization (which means your rasterized images are super low DPI).

Re-tagged this as 2.1 because the fix for this is probably in refactoring the code in `offsetbox.py` which has not been meaningfully touched sense 2008-2010 and would probably be coupled with adding a proper layout manager to the code and ensuring that the transforms that rely on dpi are re-computed when ever the mixed-mode renderer changes renders.

**Comment by claria** [comment] 2016-03-28 06:44
I tested your suspicion that rasterization the whole legend woud work and indeed it avoids the problem.

**Comment by stilley2** [comment] 2017-08-06 13:32
As another potential workaround, using the pgf backend works

e.g.:
```python
from matplotlib.backends.backend_pgf import FigureCanvasPgf
...
canvas = FigureCanvasPgf(fig)
canvas.print_figure('out.pdf')
```

**Comment by jklymak** [comment] 2017-09-21 19:03
Hmmm, see discussion: https://github.com/matplotlib/matplotlib/issues/9203 where the same rasterization issue in the pdf backend came up.

**Comment by oscargus** [comment] 2022-06-03 20:16
This seems to be fixed in the current master:

![image](https://user-images.githubusercontent.com/8114497/171945372-1568b78a-ac44-4072-a150-bcf1eb30581b.png)

**Closed by oscargus** 2022-06-03 20:16 UTC
Labels: status: confirmed bug, topic: geometry manager, backend/pdf, Difficulty: Hard
