### ISSUE TITLE
Arcs with large radii in small 

### ISSUE THREAD

**Issue by LanceJenkinZA** [matplotlib/matplotlib#17547] opened 2020-06-01 04:09 UTC
### Bug report

**Bug summary**

No `matplotlib.patches.Arc` is being rendering when trying to add a small segment of a circle with a large radius.

If I increase the x and y limits to include a larger section of the arc then it is rendered.

**Code for reproduction**

```python
import matplotlib.pylab as pl
from matplotlib import patches

fig = pl.figure()
ax = pl.gca()
x = 212.02529006006412
y = -2115.252900600641
diameter = 4261.655587271447
a = patches.Arc((x, y), diameter, diameter, fill=False)

ax.add_patch(a)
pl.xlim(0, 20)
pl.ylim(0, 20)
fig.show()
```

**Actual outcome**

An empty figure:

![image](https://user-images.githubusercontent.com/6415805/83375015-d9479300-a410-11ea-91dc-cfbc96bb32d0.png)

**Expected outcome**

A figure with a small section of an arc starting a $(0, 5)$ and ending at $(7.98894818241678, 10.0)$
![image](https://user-images.githubusercontent.com/6415805/83375513-6dfec080-a412-11ea-825f-fde02686dd93.png)

**Matplotlib version**

  * Operating system: Windows 10 Pro
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: Python 3.7.5
  * Jupyter version (if applicable): Version 0.35.6
  * Other libraries:

**Comment by LanceJenkinZA** [comment] 2020-06-01 04:16
The issue is with the comparison on [Line L1669 of patches.py](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/patches.py#L1669):

```
        # Get width and height in pixels
        width, height = self.get_transform().transform((width, height))
        inv_error = (1.0 / 1.89818e-6) * 0.5
        if width < inv_error and height < inv_error:
            self._path = Path.arc(theta1, theta2)
            return Patch.draw(self, renderer)
```

For this case I'm getting:
```
inv_error = 263410.21399445785
width = 21326216.85880001
height = 89320455.38223404
```

I've disabled the check and it does render correctly:

![image](https://user-images.githubusercontent.com/6415805/83375488-56273c80-a412-11ea-832a-ec7b9d6ca883.png)

**Comment by anntzer** [comment] 2020-06-02 14:33
This bisects to https://github.com/matplotlib/matplotlib/pull/8047 (2.1).  So it should be fixed but I'm not sure it's release critical.

**Comment by tacaswell** [comment] 2020-06-02 14:42
The `Arc` artists is designed to either draw the full circle and let it get clipped or to render the arc using a more accurate (and expensive) method.  

I also just got to this bisecting to a 2.1 change so it is not a recent regression, but it should still be fixed ASAP as this is a rather terrible bug.

**Comment by tacaswell** [comment] 2020-06-02 15:23
The fix seems to be pretty simple, we need to _not_ do the stretching when going through the accurate path.

**Closed** 2020-06-17 02:57 UTC
Labels: Release critical
