### ISSUE TITLE
File save dialog output goes to python terminal on OS X

### ISSUE THREAD

**Issue by amadio** [matplotlib/matplotlib#3476] opened 2014-09-05 16:53 UTC
I install matplotlib on OS X using a Gentoo prefix install. Everything seems to work ok. The only problem I've encountered so far is that when I try to save something to a file, I can't change the filename on the dialog box, because the keyboard strokes go to the terminal where I am running python. I don't know if this is a matplotlib issue or a issue in tkinter from Python, but matplotlib is the only place where I have this problem.

**Comment by tacaswell** [comment] 2015-02-07 22:25
@amadio ping

**Comment by amadio** [comment] 2015-02-08 16:06
Hi @tacaswell  I'm sorry, completely forgot about this issue. I don't have access to a Mac right now, and won't have for the next three months, so I can't check what backend I was using. Feel free to close this issue, I can open another when I get back home and can test this again.

**Comment by mdboom** [comment] 2015-10-09 11:33
I can reproduce this on a Mac with the macosx backend, Anaconda Python and current master of matplotlib.

**Comment by mdboom** [comment] 2015-10-09 11:35
Scratch that: If started with `pythonw` on Anaconda python, things work correctly.  Using `pythonw` as a workaround seems reasonable.

**Comment by movelikeriver** [comment] 2016-01-20 16:15
same issue here:
I got the lib from scikit: http://scikit-learn.org/stable/install.html
```
conda install scikit-learn
```

```
$ python
Python 2.7.11 |Anaconda 2.4.1 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import sys
>>> sys.executable
'//anaconda/bin/python'
```

`pythonw` is working.

**Comment by dstansby** [comment] 2017-11-01 17:09
I'm going to close this, since importing Matplotlib without using `pythonw` now errors. Feel free to re-open if this is still an issue in Maptlotlib 2.1 whilst running `pythonw`!

**Closed by dstansby** 2017-11-01 17:09 UTC
Labels: needs clarification, needs confirmation, OS/Apple
