### ISSUE TITLE
Regression in test_remove_shared_axes

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5810] opened 2016-01-07 18:57 UTC
See #5809.

**Comment by tacaswell** [comment] 2016-01-08 02:26
The issue is that the final line is `assert assert_arrays_equal(a, b)` which when the np test passes, returns `None` which fails the `assert`.  The underlying code work correctly.

**Comment by tacaswell** [comment] 2016-01-25 21:09
closed by #5809

**Closed by tacaswell** 2016-01-25 21:09 UTC
