### ISSUE TITLE
[ENH]: Be able to findfont by name

### ISSUE THREAD

**Issue by JeremieBergeron** [matplotlib/matplotlib#22798] opened 2022-04-07 15:45 UTC
### Problem

I'm always frustrated when I want to find the font "Arial Black", because the family name of this font is "Arial".
I would like it if we could search a font by it's name.

Here is an example how I search the font "Arial Black":
```
import matplotlib.font_manager as fm
print(fm.findfont("Arial Black"))
```

Here is the output:
```
C:\Users\jerem\Desktop>py font.py
findfont: Font family ['Arial Black'] not found. Falling back to DejaVu Sans.
C:\Users\jerem\AppData\Local\Programs\Python\Python310\Lib\site-packages\matplotlib\mpl-data\fonts\ttf\DejaVuSans.ttf
```

When I say name of the font, I am talking about this name in yellow:
![image](https://user-images.githubusercontent.com/34408507/162241258-8efe6bae-bd13-40f2-9673-a2ff36bba9d7.png)

### Proposed solution

I proposed to add a field "name" to matplotlib.font_manager.FontProperties class: https://github.com/matplotlib/matplotlib/blob/v3.5.1/lib/matplotlib/font_manager.py#L596-L947

**Comment by thedevhaider** [comment] 2022-04-07 18:19
@JeremieBergeron As per the doc. You can provide the weight against the font to set properties such as 'regular', 'medium', 'black' etc. 
https://github.com/matplotlib/matplotlib/blob/v3.5.1/lib/matplotlib/font_manager.py#L620

Is this matches your use case? 

PS: Just started open-source for public repos 😃

**Comment by JeremieBergeron** [comment] 2022-04-07 18:30
No, it does not.

The problem is that I have only these 3 informations:
1. Font name (not font family !)
2. IsBold
3. IsItalic

Here is an example of what I can get:
1. "Arial Black"
2. False
3. False

Because of that, I can't set the properties like you said. I would need to trim the font name or something like that and I think that's a very bad idea.

PS: If you are wondering from what I get these information, I get them from an .ass file (that's not a joke. It is a subtitle format).

**Comment by anntzer** [comment] 2022-04-07 18:53
I think this is basically a duplicate of #4822 (https://github.com/matplotlib/matplotlib/issues/4822#issuecomment-858386487)?

**Comment by JeremieBergeron** [comment] 2022-04-07 19:19
Yes, you're right. I did not see it.

I ask you a question in the issues you mentionned

**Closed** 2022-04-07 20:02 UTC
Labels: New feature, status: duplicate, topic: text/fonts
