### ISSUE TITLE
[Bug]: cannot save figure with PGF backend as of Python 3.12

### ISSUE THREAD

**Issue by carlos-souto** [matplotlib/matplotlib#27693] opened 2024-01-24 11:36 UTC
### Bug summary

Trying to use `plt.savefig` with `mpl.use('pgf')` results in an exception as of Python 3.12.
This is not a problem with the TeX installation, as the code below works on Python 3.11 without problems.

### Code for reproduction

```python
import matplotlib as mpl
import matplotlib.pyplot as plt

# setup
mpl.use('pgf')
mpl.rcParams.update({
    # PGF
    'text.usetex': True,
    'pgf.texsystem': 'lualatex',
    'pgf.rcfonts': False,
    'pgf.preamble': r'''
        \usepackage{fontspec,unicode-math}
        \setmainfont{Cambria}
        \setmathfont{Cambria Math}
    ''',
    # font setup
    'font.family': 'serif',
    'axes.labelsize': 10,
    'legend.fontsize': 9,
    'xtick.labelsize': 8,
    'ytick.labelsize': 8,
})

# plot
plt.figure()
plt.xlabel("The $x$-axis")
plt.ylabel("The $y$-axis")
plt.title("The Title")
plt.plot([0.0, 1.0], [0.0, 1.0], "-k")
plt.savefig("test.pdf")
```

### Actual outcome

Traceback (most recent call last):
  File "C:\Users\Souto\AppData\Local\Programs\Python\Lib\weakref.py", line 666, in _exitfunc
    f()
  File "C:\Users\Souto\AppData\Local\Programs\Python\Lib\weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Souto\AppData\Local\Programs\Python\Lib\site-packages\matplotlib\backends\backend_pgf.py", line 277, in finalize_latex
    latex.communicate()
  File "C:\Users\Souto\AppData\Local\Programs\Python\Lib\subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Souto\AppData\Local\Programs\Python\Lib\subprocess.py", line 1610, in _communicate
    self.stdout_thread.start()
  File "C:\Users\Souto\AppData\Local\Programs\Python\Lib\threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown

### Expected outcome

A pdf image file, without raising an exception.

### Operating system

Windows 11

### Matplotlib Version

3.8.2

### Matplotlib Backend

pgf

### Python version

3.12.1

### Installation

pip

**Comment by anntzer** [comment] 2024-01-25 10:10
Looks like a duplicate of https://github.com/matplotlib/matplotlib/issues/27437, which has a suggested patch.  Can you check whether it works for you (and continue the discussion over there)?

**Closed by anntzer** 2024-01-25 10:10 UTC
