### ISSUE TITLE
Discrepancy between svg and png plots

### ISSUE THREAD

**Issue by danpf** [matplotlib/matplotlib#9276] opened 2017-10-03 19:19 UTC
### Bug report

**Bug summary**

In this example, plots are very different depending if they are saved as png or svg.  I'm not even sure if this is a problem with matplotlib, but none of the viewers I choose are close to what I would expect given  the png.  Is there anything I can do to make my svg as expected, or is this just a limitation of the svg format?

**Code for reproduction**

```python
#!/usr/bin/env python3.6

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

#### free input parameters ####
figheight = 4 # inch
subplotpars = dict(left=0.1, right=0.9)
fontsize = 16
fontname = 'Courier new' # need to choose a monospace font here

myseq = "AAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWAERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLWERGERGEREKLKLKLLLKKLWEWRKLEWRLWKERLKKLYKLTELWLKLRWELKHLW"
scorelist = [np.random.randint(0,5) for x in myseq ]

#### automatic plotting ####
fig = plt.figure(figsize=(6,figheight)) # at this point only height will matter
fig.subplots_adjust(**subplotpars)
ax = plt.subplot()
scorearray = np.array([scorelist,scorelist])

# Plotting the colorbar
cmap = plt.cm.rainbow
im = ax.imshow(scorearray, extent=[-0.5, len(scorelist)-0.5, 0, 5], cmap=cmap)
divider = make_axes_locatable(ax)
cax = divider.append_axes("top", size="5%", pad=0.04)
cbar = plt.colorbar(im, cax=cax, orientation='horizontal')
cbar.ax.xaxis.set_ticks_position('top')
ax.yaxis.set_visible(False)

# position text centered at middle of axes
text = ax.text(0.5,-0.08, myseq, size=fontsize, name=fontname, 
               transform=ax.transAxes, va="top", ha="center")
# draw canvas to fix positions of elements
fig.canvas.draw()
bbox = text.get_window_extent()
# calculate figure width according to width of text
figwidth=bbox.width/float(fig.dpi)/(subplotpars["right"]-subplotpars["left"])
fig.set_size_inches((figwidth, fig.get_size_inches()[1]))

ax.set_xticks([0] + list(np.arange(9, len(myseq), 10)));
ax.set_xticklabels(['1'] + [str(i) for i in range(10, len(myseq), 10)]);
ax.set_xticks(np.arange(-0.5, len(myseq), 1), minor=True);
ax.xaxis.set_tick_params(pad=10)

ax.grid(which='minor', color='w', linestyle='-', linewidth=2)
plt.rcParams['svg.fonttype'] = 'none'
fig.savefig('test.png')
fig.savefig('test.svg',format='svg')
# plt.show()

```

**Actual outcome**

result from viewing svg
chrome:
https://imgur.com/a/SCWwH
gimp:
https://imgur.com/a/3vCTr

**Expected outcome**

https://imgur.com/a/vUWKV

**Matplotlib version**

  * Operating system: linux mint 18.1
  * Matplotlib version: 2.02
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6
  * Jupyter version (if applicable):
  * Other libraries: 

installed with conda , from conda-forge

**Comment by anntzer** [comment] 2017-10-03 20:08
I am almost certain that the difference comes from the font renderer.  Basically, matplotlib asks freetype (the only font rendering library it supports), "what's the size of the following piece of text when using that font", freetype gives some number, and you use it to scale the bars accordingly.  But chromium or inkscape (the two viewers I have tried) use a different font rendering library, which uses a different kerning (spacing between the letters).  In fact if you look carefully at the rendered SVGs you will notice that the letters don't align perfectly with the bars; the difference is small but with such a long string, the deltas accumulate.

I am tempted to close this as essentially an unfixable issue due to the fact that SVG (reasonably) doesn't impose a font rendering library -- the workaround would be to use individual text objects instead.

**Comment by tacaswell** [comment] 2017-10-03 20:59
I suspect that this is related to the dpi when you computed the offsets, try setting the figure dpi to 72 before drawing.

I suspect the easy way to do this is to use the a formatter on the minor ticks (but keep the logic to resize the figure based on how many ticks you have)

**Comment by ImportanceOfBeingErnest** [comment] 2017-10-03 21:21
A short note: This originally as been brought up in [this stackoverflow post](https://stackoverflow.com/questions/46534416/aligning-matplotlib-annotation-to-colorbar) and the code shown here is the not-so-well-working answer I gave. The issue is that using individual letters as ticklabels is not an option for the OP, because he wants to be able to select the text as a whole; hence my attempt to scale the figure according to the text. 

Using a dpi of 72 does not change anything. Why would it? I agree with @anntzer that this is probably not really related to matplotlib and can probably be closed here. However if someone has a good idea on a solution to the original problem, feel free to answer on Stackoverflow.

**Comment by danpf** [comment] 2017-10-03 21:41
@anntzer Okay, that's kind of what I figured. I will have to rethink of how to do this then, as svg html doesn't appear to have a justify to width option.  Thank you for your answer!

On a similar note, I also see missalignment when I save as pdf, is there a way to embed the matplotlib font into the pdf? as a workaround I could just use that until I conjure up some html/css to fix this.

**Comment by ImportanceOfBeingErnest** [comment] 2017-10-03 21:51
@danpf This has little to do with the font itself, but with how the font is being rendered. Even if you embed the font into the pdf you would have the same issue that the renderer places the letters at slightly different positions.

**Comment by anntzer** [comment] 2017-10-03 21:52
You may be able to edit (/ scriptfully transform) the generated SVG to enclose the all individual texts elements into a SVG group, which may or may not be enough for what you want to do.
I think matplotlib's pdf does have its own font subsetting code (although Courier may be specifically excluded (or not) because it's one of the 14 PDF core fonts) (sorry, not super familiar with that part of the codebase...); but that's not going to fix the problem: ultimately, precise positioning of the glyphs is done by the renderer's font renderer library (typically freetype on Linux, but freetype doesn't even keep its output the same from one version to another).

EDIT: @ImportanceOfBeingErnest just beat me :)

**Comment by jklymak** [comment] 2017-10-03 21:56
I think you could get the `tightbbox` for the text object and change the position of the axis to match at draw time?  This would require messing around internally somewhere  so you get the svg canvas to work with; I'd suggest finding where `tight_layout()` is called in `figure.draw()` and put a `my_layout()` function next to it.  You may also be able to do it by specifying the `svg` or `pdf` backends at the start, but then you'd lose the proper formatting for `png`.

**Comment by danpf** [comment] 2017-10-03 22:03
@anntzer @ImportanceOfBeingErnest I see... I feel I understand fonts less and less each day :D 

Yea I think I will have to figure out a way to manipulate the svg file...
I will have to look into that @jklymak sounds like it will take me a bit haha

**Comment by ImportanceOfBeingErnest** [comment] 2017-10-03 22:16
@jklymak As I see it there is no evidence whatsoever that different backends would return a different bbox for the same text. Hence I don't think the proposal of looking into the draw methods will result in anything useful. Again, as I see it there is nothing wrong from the matplotlib side of things.

**Comment by anntzer** [comment] 2017-10-04 01:38
(feel free to continue the discussion, or even reopen the issue if it turns out this can be fixed on mpl's side, but I doubt it...)

**Closed** 2017-10-04 01:38 UTC
Labels: backend/svg, won't fix

**Comment by Mister-Blue-Sky** [comment] 2025-02-17 11:55
Hey! If anyone is stuck, here is an easy solution. Convert your svg file into a png file.

I use this package:  
`pip install cairosvg`

```
  // Your code
  fig.savefig("image.svg")
  cairosvg.svg2png(url="image.svg", write_to="image.png")


```
