### ISSUE TITLE
PolarAxesSubplot.get_yticklabels()

### ISSUE THREAD

**Issue by yangziy** [matplotlib/matplotlib#17904] opened 2020-07-13 01:16 UTC
### Bug report

**Bug summary**

PolarAxesSubplot.get_yticklabels() yield unexpected output.

**Code for reproduction**

The example code below is grabbed from [polar demo](https://matplotlib.org/3.1.1/gallery/pie_and_polar_charts/polar_demo.html) with minor modification.

```python
import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r

ax = plt.subplot(111, projection='polar')
ax.plot(theta, r)
plt.savefig('incorrect_polar.png')
print([text._text for text in ax.get_yticklabels()])
```

**Actual outcome**

Console Output:
```
['0.25', '0.50', '0.75', '1.00', '1.25', '1.50', '1.75', '2.00', '2.25']
```
Image Output:

![incorrect_polar](https://user-images.githubusercontent.com/13228324/87261434-d0b89280-c47b-11ea-8e82-1d77b54403b8.png)

**Expected outcome**

```
['0.25', '0.50', '0.75', '1.00', '1.25', '1.50', '1.75', '2.00']
```

**Matplotlib version**

  * Operating system: macOS 10.15.5
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.6.10
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by timhoffm** [comment] 2020-07-14 08:48
This is not polar-related. The same happens for standard axes.

![grafik](https://user-images.githubusercontent.com/2836374/87405308-8dffd300-c5bf-11ea-9278-20f0f840210c.png)

**Comment by dstansby** [comment] 2024-01-06 10:18
Since we generally return tick labels that are outside the bounds of an axis, I'm going to close this as expected behaviour.

**Closed by dstansby** 2024-01-06 10:18 UTC
Labels: topic: polar, topic: ticks axis labels
