### ISSUE TITLE
[Bug]: plt.savefig incorrectly discarded z-axis label when saving Line3D/Bar3D/Surf3D images using bbox_inches='tight'

### ISSUE THREAD

**Issue by NJU-ZAD** [matplotlib/matplotlib#28931] opened 2024-10-03 11:05 UTC
### Bug summary

I drew a 3D bar graph in python3 using ax.bar3d and then saved the image to pdf under bbox_inches='tight' using plt.savefig, but the Z-axis label was missing in the pdf. Note that everything worked fine after switching matplotlib to version 3.5.0 without changing my python3 code.

### Code for reproduction

```Python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.ticker import MultipleLocator


def plot_3D_bar(x_data, data, save_path, x_label, y_label, z_label,
                var_orient='horizon'):
    if var_orient != 'vertical' and var_orient != 'horizon':
        print('plot_figure var_orient error!')
        exit(1)
    if var_orient == 'vertical':
        data = list(map(list, zip(*data)))
    x_number = len(data[0])
    y_number = len(data)
    if len(x_data) != x_number:
        exit(1)
    x_data_label = ['A', 'B', 'C', 'D', 'E', 'F', 'G']
    if len(x_data_label) % x_number != 0:
        exit(1)
    if y_number == 1:
        label = ['label1']
    elif y_number == 2:
        label = ['label1', 'label2']
    elif y_number == 3:
        label = ['l1', 'l2', 'l3']
    else:
        label = []
    if y_number == 1:
        color = ['green']
    elif y_number == 2:
        color = ['green', 'red']
    elif y_number == 3:
        color = ['green', 'red', 'blue']
    else:
        color = []
    if y_number == 1:
        hatch = ['x']
    elif y_number == 2:
        hatch = ['x', '.']
    elif y_number == 3:
        hatch = ['x', '.', '|']
    else:
        hatch = []
    if y_number != len(label) or y_number != len(color) or \
            y_number != len(hatch):
        exit(1)
    # plt.title('title')
    plt.rc('text', usetex=False)
    plt.rc('font', family='Times New Roman', size=15)
    font1 = {'family': 'Times New Roman', 'weight': 'normal', 'size': 15}
    bar_width_x = 0.5
    dx = [bar_width_x for _ in range(x_number)]
    bar_width_y = 0.2
    dy = [bar_width_y for _ in range(x_number)]
    ax = plt.subplot(projection='3d')
    ax.xaxis.set_major_locator(MultipleLocator(1))
    ax.yaxis.set_major_locator(MultipleLocator(1))
    ax.yaxis.set_minor_locator(MultipleLocator(0.5))
    ax.zaxis.set_major_locator(MultipleLocator(5))
    ax.tick_params(labelrotation=0)
    ax.set_xticks(x_data)
    ax.set_xticklabels(x_data_label, rotation=0)
    ax.set_yticks(np.arange(y_number)+1)
    ax.set_yticklabels(label, rotation=0)
    ax.set_xlabel(x_label, fontweight='bold', size=15)
    # ax.set_xlim([0, 8])
    ax.set_ylabel(y_label, fontweight='bold', size=15)
    # ax.set_ylim([0, 4])
    ax.set_zlabel(z_label, fontweight='bold', size=15)
    ax.set_zlim([0, 25])
    min_x = [0 for _ in range(y_number)]
    min_z = [0 for _ in range(y_number)]
    for _ in range(y_number):
        min_z[_] = np.min(data[_])
        for __ in range(x_number):
            if data[_][__] == min_z[_]:
                min_x[_] = x_data[__]
        min_z[_] = round(min_z[_], 2)
        y_list = [_+1-1/2*bar_width_y for __ in range(x_number)]
        z_list = [0 for __ in range(x_number)]
        ax.bar3d(x_data, y_list, z_list,
                 dx=dx, dy=dy, dz=data[_], label=label[_],
                 color=color[_], edgecolor='k', hatch=hatch[_])
        ax.text(x=min_x[_], y=_+1, z=min_z[_]+3, s='%.2f' % min_z[_],
                horizontalalignment='center', verticalalignment='top',
                backgroundcolor='white', zorder=5,
                fontsize=10, color='k', fontweight='bold')
    plt.grid(axis='both', color='gray', linestyle='-')
    fig = plt.gcf()
    fig.set_size_inches(4, 4)
    if save_path is not None:
        plt.savefig(save_path, bbox_inches='tight')
    plt.show()


x_data = [1, 2, 3, 4, 5, 6, 7]
y_data = [[3, 13, 1, 7, 9, 10, 2],
          [6, 3, 9, 4, 9, 20, 9],
          [7, 9, 5, 8, 5, 3, 9]]
plot_3D_bar(x_data, y_data, 'figure.pdf', '\nxlabel',
            '\nylabel', '\nzlabel', 'horizon')
```

### Actual outcome

There is no Z-axis label in the saved figure.pdf
[figure.pdf](https://github.com/user-attachments/files/17243046/figure.pdf)

### Expected outcome

Saved figure.pdf should contain the z-axis label
[figure.pdf](https://github.com/user-attachments/files/17243055/figure.pdf)

### Operating system

Ubuntu 20.04

### Matplotlib Version

3.9.2

### Installation

pip

**Comment by jklymak** [comment] 2024-10-03 12:44
This is a very long piece of code for what seems like a basic problem. Can you minimize to reproduce?

**Comment by rcomer** [comment] 2024-10-03 13:12
Duplicate of #28117?

**Comment by NJU-ZAD** [comment] 2024-10-03 13:30
> This is a very long piece of code for what seems like a basic problem. Can you minimize to reproduce?

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5, 6, 7]
data = [6, 3, 9, 4, 9, 20, 9]
save_path = "figure.pdf"

ax = plt.subplot(projection='3d')
ax.set_xlabel('xlabel', fontweight='bold', size=15)
ax.set_ylabel('ylabel', fontweight='bold', size=15)
ax.set_zlabel('zlabel', fontweight='bold', size=15)

y_list = [2.5] * len(x)
ax.bar3d(x, y_list, [0] * len(x), dx=[0.5] * len(x),
         dy=[0.2] * len(x), dz=data, color='red', edgecolor='k')

fig = plt.gcf()
fig.set_size_inches(4, 4)
plt.savefig(save_path, bbox_inches='tight')
plt.show()

**Comment by NJU-ZAD** [comment] 2024-10-03 13:37
> Duplicate of #28117?

Yes, the Z-axis label is cut, I encountered this problem when saving the image to pdf

**Comment by rcomer** [comment] 2024-10-03 14:17
OK, I will close this then since the problem is tracked by the other issue.

**Closed by rcomer** 2024-10-03 14:17 UTC
