### ISSUE TITLE
"ValueError: ordinal must be >= 1" when plotting after axhline

### ISSUE THREAD

**Issue by dadkins** [matplotlib/matplotlib#7405] opened 2016-11-04 18:25 UTC
I have reduced the error to the following code snippet which I run in a Jupyter notebook. Swapping the last two lines avoids the bug.

```python
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import sys

print sys.version
print 'pandas', pd.__version__
print 'matplotlib', matplotlib.__version__
df = pd.DataFrame(index = pd.DatetimeIndex(['2016-10-14', '2016-10-21', '2016-10-28'], name='Date'),
                  data = [-1000, -3000, 4500],
                  columns = ['Amount'])
print df

plt.figure(figsize=(12,3))
plt.axhline(y=0, color='r')
df['Amount'].plot(style='o')
```

```
2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
pandas 0.19.0
matplotlib 1.5.3
            Amount
Date              
2016-10-14   -1000
2016-10-21   -3000
2016-10-28    4500

ValueError                                Traceback (most recent call last)
<ipython-input-4-f00cd5582c0e> in <module>()
     15 plt.figure(figsize=(12,3))
     16 plt.axhline(y=0, color='r')
---> 17 df['Amount'].plot(style='o')
...
.../lib/python2.7/site-packages/matplotlib/dates.pyc in _from_ordinalf(x, tz)
    269 
    270     ix = int(x)
--> 271     dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
    272 
    273     remainder = float(x) - ix

ValueError: ordinal must be >= 1
```

- [ ] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
1.5.3, python 2.7.12, Linux
- [ ] How did you install Matplotlib and Python (pip, anaconda, from source ...)
conda

**Comment by tacaswell** [comment] 2016-11-04 19:19
Can you please include the full traceback?

**Comment by dadkins** [comment] 2016-11-04 19:33
---------------------------------------------------------------------------ValueError
                               Traceback (most recent call
last)<ipython-input-4-f00cd5582c0e> in <module>()     15
plt.figure(figsize=(12,3))     16 plt.axhline(y=0, color='r')---> 17
df['Amount'].plot(style='o')
/home/dadkins/conda/envs/jupyter/lib/python2.7/site-packages/pandas/tools/plotting.pyc
in __call__(self, kind, ax, figsize, use_index, title, grid, legend,
style, logx, logy, loglog, xticks, yticks, xlim, ylim, rot, fontsize,
colormap, table, yerr, xerr, label, secondary_y, **kwds)   3597
                    colormap=colormap, table=table, yerr=yerr,   3598
                          xerr=xerr, label=label,
secondary_y=secondary_y,-> 3599                            **kwds)
3600     __call__.__doc__ = plot_series.__doc__   3601
/home/dadkins/conda/envs/jupyter/lib/python2.7/site-packages/pandas/tools/plotting.pyc
in plot_series(data, kind, ax, figsize, use_index, title, grid,
legend, style, logx, logy, loglog, xticks, yticks, xlim, ylim, rot,
fontsize, colormap, table, yerr, xerr, label, secondary_y, **kwds)
2671                  yerr=yerr, xerr=xerr,   2672
label=label, secondary_y=secondary_y,-> 2673                  **kwds)
 2674    2675
/home/dadkins/conda/envs/jupyter/lib/python2.7/site-packages/pandas/tools/plotting.pyc
in _plot(data, x, y, subplots, ax, kind, **kwds)   2467
plot_obj = klass(data, subplots=subplots, ax=ax, kind=kind, **kwds)
2468 -> 2469     plot_obj.generate()   2470     plot_obj.draw()   2471
    return plot_obj.result
/home/dadkins/teza-conda/envs/jupyter/lib/python2.7/site-packages/pandas/tools/plotting.pyc
in generate(self)   1047    1048         for ax in self.axes:-> 1049
          self._post_plot_logic_common(ax, self.data)   1050
  self._post_plot_logic(ax, self.data)   1051
/home/dadkins/conda/envs/jupyter/lib/python2.7/site-packages/pandas/tools/plotting.pyc
in _post_plot_logic_common(self, ax, data)   1175
ax.set_xticklabels(xticklabels)   1176
self._apply_axis_properties(ax.xaxis, rot=self.rot,-> 1177
                            fontsize=self.fontsize)   1178
self._apply_axis_properties(ax.yaxis, fontsize=self.fontsize)   1179
      elif self.orientation == 'horizontal':
/home/dadkins/conda/envs/jupyter/lib/python2.7/site-packages/pandas/tools/plotting.pyc
in _apply_axis_properties(self, axis, rot, fontsize)   1223    1224
 def _apply_axis_properties(self, axis, rot=None, fontsize=None):->
1225         labels = axis.get_majorticklabels() +
axis.get_minorticklabels()   1226         for label in labels:   1227
           if rot is not None:
/home/dadkins/conda/envs/jupyter/lib/python2.7/site-packages/matplotlib/axis.pyc
in get_majorticklabels(self)   1161     def get_majorticklabels(self):
  1162         'Return a list of Text instances for the major
ticklabels'-> 1163         ticks = self.get_major_ticks()   1164
  labels1 = [tick.label1 for tick in ticks if tick.label1On]   1165
     labels2 = [tick.label2 for tick in ticks if tick.label2On]
/home/dadkins/conda/envs/jupyter/lib/python2.7/site-packages/matplotlib/axis.pyc
in get_major_ticks(self, numticks)   1290         'get the tick
instances; grow as necessary'   1291         if numticks is None:->
1292             numticks = len(self.get_major_locator()())   1293
    if len(self.majorTicks) < numticks:   1294             # update
the new tick label properties from the old
/home/dadkins/conda/envs/jupyter/lib/python2.7/site-packages/matplotlib/dates.pyc
in __call__(self)   1005     def __call__(self):   1006
'Return the locations of the ticks'-> 1007         self.refresh()
1008         return self._locator()   1009
/home/dadkins/conda/envs/jupyter/lib/python2.7/site-packages/matplotlib/dates.pyc
in refresh(self)   1025     def refresh(self):   1026         'Refresh
internal information based on current limits.'-> 1027         dmin,
dmax = self.viewlim_to_dt()   1028         self._locator =
self.get_locator(dmin, dmax)   1029
/home/dadkins/conda/envs/jupyter/lib/python2.7/site-packages/matplotlib/dates.pyc
in viewlim_to_dt(self)    769             vmin, vmax = vmax, vmin
770 --> 771         return num2date(vmin, self.tz), num2date(vmax,
self.tz)    772     773     def _get_unit(self):
/home/dadkins/conda/envs/jupyter/lib/python2.7/site-packages/matplotlib/dates.pyc
in num2date(x, tz)    417         tz = _get_rc_timezone()    418
if not cbook.iterable(x):--> 419         return _from_ordinalf(x, tz)
  420     else:    421         x = np.asarray(x)
/home/dadkins/conda/envs/jupyter/lib/python2.7/site-packages/matplotlib/dates.pyc
in _from_ordinalf(x, tz)    269     270     ix = int(x)--> 271     dt
= datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)    272     273
    remainder = float(x) - ix
ValueError: ordinal must be >= 1

**Comment by QuLogic** [comment] 2016-11-04 19:55
Dupe of (or at least related to) #6023?

**Comment by jklymak** [comment] 2018-07-15 15:52
Closing as this works fine on master...

**Closed by jklymak** 2018-07-15 15:52 UTC
