### ISSUE TITLE
[Bug]: "Mouse move and click events" example no more working in jupyter (notebook or lab)

### ISSUE THREAD

**Issue by karlacio** [matplotlib/matplotlib#28044] opened 2024-04-08 08:31 UTC
### Bug summary

The example [Mouse move and click events](https://matplotlib.org/stable/gallery/event_handling/coords_demo.html) is not more working using jupyter. Running in command line is ok.

### Code for reproduction

```Python
Download example https://matplotlib.org/stable/_downloads/1bd44229487dba5976942a2732f0b8b9/coords_demo.ipynb and run in jupyter notebook or lab.

The plot will be shown but no data from mouse movements.
```

### Actual outcome

Just the plot.

### Expected outcome

The plot and mouse coordinate info coming from the on_move(event) calls.

### Additional information

I tried to run the code both in notebook and in lab.

I tried to add (one at once)
`%matplotlib ipympl

%matplotlib widget`

and all the combination of them but the result is the same: plot show but no mouse movement print.

### Operating system

MacOS 13.6

### Matplotlib Version

3.8.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline, module://ipympl.backend_nbagg

### Python version

3.12.2

### Jupyter version

notebook:7.1.2 lab:4.1.5

### Installation

pip

**Comment by timhoffm** [comment] 2024-04-08 09:00
Has this ever been working? If so with which versions?

**Comment by timhoffm** [comment] 2024-04-08 09:02
Duplicate of ##27837.

**Closed** 2024-04-08 09:02 UTC
