### ISSUE TITLE
[Bug]: test_image_comparison_expect_rms nondeterministic failure

### ISSUE THREAD

**Issue by Apteryks** [matplotlib/matplotlib#22992] opened 2022-05-06 13:30 UTC
### Bug summary

This seems a rather rare occurrence, but I've gotten the test to fail like this, on a x86_64 processor:
```
    def test_image_comparison_expect_rms(im1, im2, tol, expect_rms):
        """
        Compare two images, expecting a particular RMS error.
    
        im1 and im2 are filenames relative to the baseline_dir directory.
    
        tol is the tolerance to pass to compare_images.
    
        expect_rms is the expected RMS value, or None. If None, the test will
        succeed if compare_images succeeds. Otherwise, the test will succeed if
        compare_images fails and returns an RMS error almost equal to this value.
        """
        baseline_dir, result_dir = map(Path, _image_directories(lambda: "dummy"))
        # Copy both "baseline" and "test" image to result_dir, so that 1)
        # compare_images writes the diff to result_dir, rather than to the source
        # tree and 2) the baseline image doesn't appear missing to triage_tests.py.
        result_im1 = make_test_filename(result_dir / im1, "expected")
        shutil.copyfile(baseline_dir / im1, result_im1)
        result_im2 = result_dir / im1
        shutil.copyfile(baseline_dir / im2, result_im2)
        results = compare_images(
            result_im1, result_im2, tol=tol, in_decorator=True)
    
        if expect_rms is None:
            assert results is None
        else:
            assert results is not None
>           assert results['rms'] == approx(expect_rms, abs=1e-4)
E           assert 90.15611460128481 == 6.50646 ± 1.0e-04
E            +  where 6.50646 ± 1.0e-04 = approx(6.50646, abs=0.0001)
```

### Code for reproduction

```python
Run the test suite via pytest. In my case, the test suite is run in parallel with xdist, in case this matters. As stated, this is nondeterministic, so it may be difficult to reproduce.
```

### Actual outcome

All tests should pass.

### Expected outcome

The `test_image_comparison_expect_rms` fails  as shown in the bug summary.

### Additional information

Attached complete build log: 
[ffvkxha5p34br976578fm3vz8hppis-python-matplotlib-3.5.1.drv.txt](https://github.com/matplotlib/matplotlib/files/8640333/ffvkxha5p34br976578fm3vz8hppis-python-matplotlib-3.5.1.drv.txt)

### Operating system

GNU Guix

### Matplotlib Version

3.5.1 (the test is unchanged in 3.5.2)

### Python version

3.9.9

### Installation

from source (.tar.gz)

**Comment by Apteryks** [comment] 2022-05-06 13:44
I suspect this failure may be caused by running the tests in parallel.  The parameterized tests juggles with same-named files in what seems to be the same directory, so when run in parallel races are bound to happen.

**Comment by jklymak** [comment] 2022-05-06 14:48
I'm not sure there is anything we can do about this.  If you run parallel tests, it's up to you to make sure the files are not overwriting each other. Regardless without a self contained example test we can't see what the issue is.  I'll close this but few free to request a reopen with more details about what you think we can do.

**Comment by tacaswell** [comment] 2022-05-06 15:06
> If you run parallel tests, it's up to you to make sure the files are not overwriting each other.

I think this is on use to make sure that parameterized tests do not use the same file so if they get distributed to different processes via xdist they can not clobber each other.

I also seem some weird failures when running the tests in parallel (they tend to be "this is not a png" type errors) but have not tracked those down enough to make a bug report (have not even done the simple thing of tracking down if it is always the same test cases or not).

**Comment by jklymak** [comment] 2022-05-06 16:15
Well maybe I just don't understand the bug report, but I don;'t see that we are defining the image names?

**Comment by tacaswell** [comment] 2022-05-06 19:56
https://github.com/matplotlib/matplotlib/blob/7bb3ff5f2f783520473f0a8df84af0aee74b2f3f/lib/matplotlib/tests/test_compare_images.py#L11-L72 is the full context of the text.  Looking at line63 we are indeed copying the output side test images to the same location for testing.

I think the fix here is pretty easy, we need some way to make sure that we inject something into L61 that ensures that the filenames are always unique (either use `tempdir` for the directory or stick a uuid onto `im1`.

**Comment by tacaswell** [comment] 2022-05-06 19:57
upside: this one is easy to fix 🎉 
downside: the issues I see are very likely different :(

**Comment by tacaswell** [comment] 2022-05-10 14:59
@AnnaMastori not on my knowledge.  If there is not a PR it is fair game to work on!

**Comment by AnnaMastori** [comment] 2022-05-17 21:43
Are we looking for something like this ?
https://github.com/NickolasGiannatos/matplotlib/blob/f3edc8771b7c292c5539e0e6444746b6ccefec04/lib/matplotlib/tests/test_compare_images.py#L58-L68

**Comment by tacaswell** [comment] 2022-05-17 21:48
@AnnaMastori Yes, that looks right to me!

**Comment by AnnaMastori** [comment] 2022-05-17 21:49
Great, Should I open a PR ?

**Comment by tacaswell** [comment] 2022-05-17 21:54
Yes please!

**Closed** 2022-06-19 23:19 UTC
Labels: topic: testing, Difficulty: Easy, Good first issue
