### ISSUE TITLE
Marker edges are not painted nicely along the edge of the marker but are scaled towards the interior

### ISSUE THREAD

**Issue by normanius** [matplotlib/matplotlib#15052] opened 2019-08-13 15:25 UTC
### Bug report

**Bug summary**
The marker edges are not painted nicely on the edge of the marker.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
x = [42,43,44]
y=[42,43,44]
plt.scatter(x,y,alpha=0.7,sizes=[500], linewidths=[15], marker='s')
plt.savefig('sample.pdf')
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/11406002/62953572-0f6a4680-bdee-11e9-98db-6098d1eacc13.png)
![image](https://user-images.githubusercontent.com/11406002/62953605-21e48000-bdee-11e9-8548-c935e27564be.png)

**Expected outcome**
The edges should go cleanly around the marker boundary.

![image](https://user-images.githubusercontent.com/11406002/62954167-3117fd80-bdef-11e9-8f1f-7180094fd4ff.png)

**Matplotlib version**
  * MacOS 10.14.5
  * Matplotlib v3.1.1
  * Matplotlib backend: MacOSX
  * Python 3.6.7

**Comment by anntzer** [comment] 2019-08-13 18:45
Unless I am mistaken (in which case please request a reopen) this is a duplicate of https://github.com/matplotlib/matplotlib/issues/13360.

**Closed by anntzer** 2019-08-13 18:45 UTC

**Comment by normanius** [comment] 2019-08-13 19:35
> It's common practice in vector graphics that half of the line width is to either side of the drawing path

Just out of curiosity: why should it be good that the edge overlaps the marker filling by half? An edge is an edge, and the current behavior is counter intuitive, especially if the edge color is the same as fill color.

By the way, setting an edge color mitigates the problem visually. 

```python
plt.scatter(x,y,alpha=0.7,sizes=[5000], linewidths=[15], edgecolors="g")
```

![image](https://user-images.githubusercontent.com/11406002/62970549-0db17a80-be10-11e9-985b-08972a43ffe7.png)

Adding a bit of control could not harm, though. How about a parameter `markeredgeoffset` with `None` or `'None'` giving the current behavior, `aligned` giving my behavior (independent of marker size), and scalar values allowing to adjust the effect?

**Comment by anntzer** [comment] 2019-08-13 19:49
Please move the discussion to #13360, where you're much more likely to get the attention of other devs :)
