### ISSUE TITLE
3d quiver arrow head and tail showing different colours.

### ISSUE THREAD

**Issue by AnirbanChakraborty06** [matplotlib/matplotlib#20240] opened 2021-05-16 07:52 UTC
### Issue summary
When multiple 3d quiver arrows are plotted, using different colours, the arrow heads and tails have different colours. The two ticks of the arrow heads also differ in colour.

### Sample code
```
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook

# Three unit vectors
x = [1,0,0]
y = [0,1,0]
z = [0,0,1]

ax = plt.figure().add_subplot(projection='3d')

# The documentation of quiver says that additional kwargs are delegated to LineCollection
# colors parameter of LineCollection, as per documentation, takes a sequence of RGBA tuples.
ax.quiver(0,0,0,x,y,z,colors=[(1,0,0,1),(0,1,0,1),(0,0,1,1)]) # red, green and blue, with alpha=1.0
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
ax.set_xlim(-2,2)
ax.set_ylim(-2,2)
ax.set_zlim(-2,2)

# ax.quiver(0,0,0,x,y,z,colors=['r','g','b']) shows similar results
```

### Original output
![Question12RGBColours](https://user-images.githubusercontent.com/79497264/118389478-c93bba00-b647-11eb-9d76-b4914712bf51.png)

### Expected output
Each arrow, head to tail, should be of a single colour.

### Versions
Matplotlib: 3.4.1
Python: 3.8.5
Platform: Jupyter Notebook version 6.1.4

**Comment by QuLogic** [comment] 2021-05-17 23:22
Duplicate of #11759.

**Closed by QuLogic** 2021-05-17 23:22 UTC
