### ISSUE TITLE
Wrongly raised AttributeError: draw_artist can only be used after an initial draw which caches the render

### ISSUE THREAD

**Issue by danjjl** [matplotlib/matplotlib#7459] opened 2016-11-14 10:43 UTC
`draw_artist()` raises an `AttributeError` error complaining a `draw()` call was not previously performed even though a `draw()` call was already done.

This happens using the `GTK3Agg` backend.

A minimum (not working) code example _(inspired by [scipy-cookbook](http://scipy-cookbook.readthedocs.io/items/Matplotlib_Animations.html))_

```python
#!/usr/bin/python3
import matplotlib
matplotlib.use('GTK3Agg')
import pylab as p
import numpy as np

ax = p.subplot(111)
canvas = ax.figure.canvas
x = np.linspace(0, 2*np.pi, 500)
line, = p.plot(x, np.sin(x), animated=True)
canvas.draw()
background = canvas.copy_from_bbox(ax.bbox)

# Update
canvas.restore_region(background)
line.set_ydata(np.sin(x+1))
ax.draw_artist(line)
canvas.blit(ax.bbox)

p.show()  
```

_(Tested on python 3.5.2 - matplotlib 1.5.3 installed through pip on Ubuntu 16.04)_

**Comment by tacaswell** [comment] 2016-11-14 22:29
attn @fariza 

I am not sure this is fixable, it looks like the `draw` method in `FigureCanvasGTK3` only triggers a rerender if the figure is visible.  

If you are going to be doing blitting you should hook into the `draw_event` callback to capture your backgrounds and mark you updating artist animated via `set_animated` (which excludes it from the normal draw list) to make sure you deal with resizes properly.  Take a look at how this works in the animation module.

**Comment by fariza** [comment] 2016-11-16 03:11
A quick hack /fix for this specific problem is to add a `FigureCanvasAgg.draw(self)` in `FigureCanvasGTK3.draw` but I don't think this is the right way to do it.


There is definitely something fishy in the handling of the draw in GTK3. 
The problem is more profound than just a missing call

-----------------------------------
The following is myself brainstorming about this problem:

Take the following example to look at the sequence of calls of the different draw methods (backend, agg, axes)
```
import matplotlib
matplotlib.use('Gtk3Agg')
# matplotlib.use('tkagg')
import matplotlib.pyplot as plt

ax = plt.subplot(111)
plt.plot([1, 2, 3])
plt.show()
```

In Gtk3Agg we have the following calls to `draw` methods
`FigureCanvasGTK3.draw`
`FigureCanvasAgg.draw`
`Axes._base.draw`
`FigureCanvasGTK3.draw`
`FigureCanvasAgg.draw`
`Axes._base.draw`
`FigureCanvasAgg.draw`
`Axes._base.draw`

But running with `TKAgg` we have
`FigureCanvasTkAgg.draw`
`FigureCanvasAgg.draw`
`Axes._base.draw`

As we can see, with gtk3 there are duplicate calls that I suspect are there because of bad handling of the events.

If in the example we replace `plt.show()` for `ax.figure.canvas.draw()`
The calls in GTK3Agg is
`FigureCanvasGTK3.draw`

and in TKAgg 
`FigureCanvasTkAgg.draw`
`FigureCanvasAgg.draw`
`Axes._base.draw`

So the calls are not completed in GTK3...

**Comment by danjjl** [comment] 2016-11-16 08:41
Probably related to this issue: if I get an animation working, resizing a window breaks the animation (previous frames not erased). The animation also breaks if the window is brought to the background and then back to the foreground.

![screencast_16-11-16_09_30_02](https://cloud.githubusercontent.com/assets/747240/20340142/70745a06-abe0-11e6-8182-1976345cc42a.gif)

Code to reproduce example:
```python
#!/usr/bin/python3
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GLib
from matplotlib.figure import Figure
from matplotlib.backends.backend_gtk3agg import FigureCanvasGTK3Agg as FigureCanvas
import numpy as np

# Update plot
def plot_update(ax, background, canvas, fig, line):
    global t

    t += 0.1
    x = np.linspace(t, 2*np.pi+t, 500)
    y = np.sin(x)

    try:
        canvas.restore_region(background)
        line.set_ydata(y)
        ax.draw_artist(line)
        canvas.blit(ax.bbox)
    # TODO quick fix while canvas.draw() not called correctly
    except AttributeError:
         ax.cla()
         line, = ax.plot(y, animated=True)
         canvas.draw()
         background = canvas.copy_from_bbox(ax.bbox)
    return True

main_window = Gtk.Window()
main_window.connect("delete-event", Gtk.main_quit)

# Initial data
t = 0
x = np.linspace(0, 2*np.pi, 500)
y = np.sin(x)

# Add figure to
fig = Figure(figsize=(5,5), dpi=96)
canvas = FigureCanvas(fig)
main_window.add(canvas)

main_window.show_all()

ax = fig.add_subplot(111)
line, = ax.plot(y, animated=True)
canvas.draw() # TODO not called correctly
background = canvas.copy_from_bbox(ax.bbox)

GLib.timeout_add(100, plot_update, ax, background, canvas, fig, line)

Gtk.main()
```

**Comment by tacaswell** [comment] 2016-11-16 13:45
The issue with some regions not getting cleared is what I was talking about above.  When there is a resize event you must get a new background.  Look at how the animation module does this for details, but the you need to:

 - mark all of your 'animated' artist as animated via `art.set_animated(True)`
 - on every re-draw (hook into `draw_event` via `canvas.mpl_connect`) manually re-draw your animated artists
 - on every resize capture a new background (via `resize_event` via `canvas.mpl_connect`)
 - on data update, restore the background, update your artists, and then manually re-draw them

Is there a reason you can not just use the `animation` module which takes care of most of these details for you?

**Comment by danjjl** [comment] 2016-11-17 10:49
***(comment not directly related to this issue)***

@tacaswell I might understand the `animation` module wrong but I had the impression it was not suited for my application:

- I have a Gtk application with an embedded matplotlib figure (using `FigureCanvasGTK3Agg`)
- An independent thread receives data from the outside world (UART connection)
- I need a function to periodically update the matplotlib figure with the data from the outside world

*(Can I use the `animation` module with `FigureCanvasGTK3Agg`? While the animation is running will my UI be frozen? Can I run an animation for an undetermined number of frames?)*

**Comment by tacaswell** [comment] 2016-11-17 13:18
The animation module uses a timer lifted from your GUI toolkit.  I see no obvious reason you could not use `FuncAnimation` with a function that polls some shared buffer with the communicating thread.

Even if it does not directly work, starting from the code and deleting what you do not need is probably a good path.

**Comment by dopplershift** [comment] 2016-11-17 16:52
My thinking behind many of the design choices in the `animation` module was to enable exactly the kind of use case you describe. Whether or not it works in practice for you is something I'd be interested to learn.

This [example](http://matplotlib.org/examples/animation/random_data.html), while very simple, shows the concept of using the `animation` module to make a never-ending animation.

**Comment by kawing-chiu** [comment] 2016-12-23 02:59
Is there a way that we can test for whether the initial draw is finished? If yes, then some defensive code can be added before doing any blit update.

**Comment by WeatherGod** [comment] 2016-12-24 16:43
Hmmm, no, I don't think there is a clean way of determining that. The
closest I can think of is finding out if the artist tree's stale parameter
is False everywhere?

**Comment by tacaswell** [comment] 2016-12-25 23:02
There is an event you can subscribe to `'draw_event'` (http://matplotlib.org/users/event_handling.html#event-connections) which fires after a draw is completed.  Tying starting your blit logic to that might work?

```python
state = dict{'draw' : False}
def sentinel(event):
   state['draw'] = True

fig.canvas.mpl_subscribe('draw_event', sentinel)

```

**Comment by QuLogic** [comment] 2021-06-03 07:32
The originally reported bug does not appear to exist any more.

**Closed by QuLogic** 2021-06-03 07:32 UTC
Labels: GUI/gtk, topic: animation
