### ISSUE TITLE
[Bug]: modifer keys not correctly handeled with tk on windows

### ISSUE THREAD

**Issue by alan-isaac** [matplotlib/matplotlib#28643] opened 2024-08-01 23:12 UTC
### Bug summary

When a plot window is showing, switching away from it (Alt-Tab) produces an error message:

`AttributeError: '_tkinter.Tcl_Obj' object has no attribute 'isprintable'`

### Code for reproduction

```Python
from matplotlib import pyplot as plt
fig, ax = plt.subplots(1,1)
ax.plot([0,1])
plt.show()
#now without closing the plot window, press the Alt key
```

### Actual outcome

`AttributeError: '_tkinter.Tcl_Obj' object has no attribute 'isprintable'`

### Expected outcome

Now error message should be produced.

### Additional information

Windows 11, Python 3.13 beta, matplotlib 3.9.1.
Run script (above) from Windows Powershell with pylauncher.

### Operating system

Windows 11

### Matplotlib Version

3.9.1

### Matplotlib Backend

Tkinter

### Python version

3.13

### Installation

pip

**Comment by jklymak** [comment] 2024-08-02 00:19
Does this also happen for a tk hello-world example?   If so, then it is a tk bug.

**Comment by tacaswell** [comment] 2024-08-02 02:09
Can you get any more of the traceback?

`isprintable` is a string method which we do use in handling events coming from the UI, but it would be very helpful to know where is the code base this is trying to be called.  My guess is that some how alt-tab is generating an event that we expect to have a key attached to it and instead we are getting some sort of place holder.

**Comment by alan-isaac** [comment] 2024-08-02 12:28
> Does this also happen for a tk hello-world example? If so, then it is a tk bug.

No, it does not.

**Comment by alan-isaac** [comment] 2024-08-02 12:34
> Can you get any more of the traceback?


`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python313\Lib\tkinter\__init__.py", line 2065, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:\Program Files\Python313\Lib\site-packages\matplotlib\backends\_backend_tk.py", line 397, in key_press
    self._get_key(event), *self._event_mpl_coords(event),
    ~~~~~~~~~~~~~^^^^^^^
  File "C:\Program Files\Python313\Lib\site-packages\matplotlib\backends\_backend_tk.py", line 387, in _get_key
    key = cbook._unikey_or_keysym_to_mplkey(unikey, event.keysym)
  File "C:\Program Files\Python313\Lib\site-packages\matplotlib\cbook.py", line 2278, in _unikey_or_keysym_to_mplkey
    if unikey and unikey.isprintable():
                  ^^^^^^^^^^^^^^^^^^
AttributeError: '_tkinter.Tcl_Obj' object has no attribute 'isprintable'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python313\Lib\tkinter\__init__.py", line 2065, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:\Program Files\Python313\Lib\site-packages\matplotlib\backends\_backend_tk.py", line 402, in key_release
    self._get_key(event), *self._event_mpl_coords(event),
    ~~~~~~~~~~~~~^^^^^^^
  File "C:\Program Files\Python313\Lib\site-packages\matplotlib\backends\_backend_tk.py", line 387, in _get_key
    key = cbook._unikey_or_keysym_to_mplkey(unikey, event.keysym)
  File "C:\Program Files\Python313\Lib\site-packages\matplotlib\cbook.py", line 2278, in _unikey_or_keysym_to_mplkey
    if unikey and unikey.isprintable():
                  ^^^^^^^^^^^^^^^^^^
AttributeError: '_tkinter.Tcl_Obj' object has no attribute 'isprintable'`

**Comment by alan-isaac** [comment] 2024-08-02 12:36
> My guess is that some how alt-tab is generating an event that we expect to have a key attached to it and instead we are getting some sort of place holder.

It happens as soon as I press the `Alt` key.

**Comment by tacaswell** [comment] 2024-08-02 13:37
It looks like https://github.com/matplotlib/matplotlib/blob/adb97e848ca88f0b9abc5b1c5085f548847e3f8f/lib/matplotlib/backends/_backend_tk.py#L386-L387

is sometimes not giving us back a string from `event.char` which is that failing in `cbook._unikey_or_keysym_to_mplkey`.

@alan-isaac what locale and keyboard layout are you using?

> It happens as soon as I press the Alt key.

That is good news as this is only a bug in the key handling system not some extra events from the window becoming inactive/active as part of the window focus switching work of alt tab.  Does it happen with any of the other modifier keys or only alt?

I suspect the fix is to add some validation around L386. 

Exact steps:

 - have a system that this reproduces on (I can not reproduce this with py313 + mpl main on linux)
 - understand what is actually being returned by `event.char` in the case of hitting a modifier without an associated letter key.  This is something that should work and the `event.key` in a callback subscribed to our `'key_press_event'` should be the string 'alt' if only the alt key is pressed.
 - sort out how to convert what ever object tk is giving us into something we can handle

Bonus points if we can sort out why this changed (my guess is the version of tk bundled with Python).


Labeling this a "good first issue" because it is extremely localized, should not require understanding any other parts of Matplotlib to fix, and there are no API choices to be made.  Labeling it as "medium" because you will have to at least partially understand the GUI event system -> mpl event system bridge and some details about tk.


-----


attn @richardsheridan

**Comment by alan-isaac** [comment] 2024-08-02 14:26
> what locale and keyboard layout are you using?

English (United States);  US QWERTY

**Comment by anijjar** [comment] 2024-09-03 22:04
Hi. I am running Python 3.13.0rc1 on Windows 11 with Matplotlib 3.9.1. I also set my Keyboard to English (United States). I was not sure how to run the traceback, but I modified _backend_tk.py to print the event attribute on L395 (def key_press).
### **Test Code**
from matplotlib import pyplot as plt
fig, ax = plt.subplots(1,1)
ax.plot([0,1])
plt.show()
#now without closing the plot window, press the Alt key

### **Investigating L395  (def key_press)**
```
    def key_press(self, event):
        # print(vars(event))
        print(event)
        print("Key pressed: " + str(event.char))
        print("Key type: " + str(type(event.char)))
        KeyEvent("key_press_event", self,
                 self._get_key(event), *self._event_mpl_coords(event),
                 guiEvent=event)._process()

    def key_release(self, event):
        print("Key released: " + str(event.char))
        KeyEvent("key_release_event", self,
                 self._get_key(event), *self._event_mpl_coords(event),
                 guiEvent=event)._process()
```
None of the keys gave an issue besides ALT_L, ALT_R, and TAB. This is the console output for each:

- ALT_L/ALT_R

```
(venv3.13.0rc1) C:\Users\amann\Documents\open source\sandbox>py app.py
<KeyPress event send_event=True state=Mod1|0x40000 keysym=Alt_R keycode=18 x=477 y=188>
Key pressed:
Key type: <class 'str'>
Key released: 
Key released: 
<KeyPress event send_event=True state=Mod1|0x40000 keysym=Alt_R keycode=18 x=477 y=188>
Key pressed:
Key type: <class 'str'>
Key released: 
Key released: 
...
```

- TAB (I need to press TAB 5 ties for the key to be released)
```
(venv3.13.0rc1) C:\Users\amann\Documents\open source\sandbox>py app.py
<KeyPress event send_event=True state=Mod1 keysym=Tab keycode=9 char='\t' x=574 y=448>
Key pressed:
Key type: <class 'str'>
Key released: 
<KeyPress event send_event=True state=Mod1 keysym=Tab keycode=9 char='\t' x=574 y=448>
Key pressed:
Key type: <class 'str'>
Key released: 
```
Here is more data on the ALT Keypress event. 
```
{'serial': 346, 'num': '??', 'height': '??', 'keycode': 18, 'state': 8, 'time': 82966265, 'width': '??', 'x': 1299, 'y': 762, 'char': '', 'send_event': True, 'keysym': 'Alt_L', 'keysym_num': 65513, 'type': <EventType.KeyPress: '2'>, 'widget': <tkinter.Canvas object .!canvas>, 'x_root': 1340, 'y_root': 832, 'delta': 0}
```

### **Results**

- The char attribute is empty from the ALT key event, but the system recognizes this as a string object so I dont think this was the issue. 

- When I press either ALT key, the key_press() method doesn't consistently trigger, but the key_release() method always works as expected. When I press the TAB key, both the key_press() and key_release() methods work correctly at first. However, after the initial use, I have to press the TAB key five times before the key_release() method is triggered again and resets properly. But this may be another issue.

### **Investigating L387 (cbook._unikey_or_keysym_to_mplkey(*))**
Next, I investigated L387 (cbook._unikey_or_keysym_to_mplkey(*)) to see if the TAB and ALT keys were able to be successfully processed. 
```

def _unikey_or_keysym_to_mplkey(unikey, keysym):
    """
    Convert a Unicode key or X keysym to a Matplotlib key name.

    The Unicode key is checked first; this avoids having to list most printable
    keysyms such as ``EuroSign``.
    """
    # For non-printable characters, gtk3 passes "\0" whereas tk passes an "".
    print("unikey: " + str(unikey) + ' | ' + "keysym: " + str(keysym))
    print(dir(unikey))
    if unikey and unikey.isprintable(): # Only letters
        return unikey
    key = keysym.lower()
    print("key:" + str(key))
    if key.startswith("kp_"):  # keypad_x (including kp_enter).
        key = key[3:]
    if key.startswith("page_"):  # page_{up,down}
        key = key.replace("page_", "page")
    if key.endswith(("_l", "_r")):  # alt_l, ctrl_l, shift_l.
        key = key[:-2]
    if sys.platform == "darwin" and key == "meta":
        # meta should be reported as command on mac
        key = "cmd"
    key = {
        "return": "enter",
        "prior": "pageup",  # Used by tk.
        "next": "pagedown",  # Used by tk.
    }.get(key, key)
    print("key end:" + str(key))
    return key
```
These were the results
```
unikey:  | keysym: Alt_R
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
key:alt_r
key end:alt

unikey:          | keysym: Tab
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
key:tab
key end:tab
```
**Results**
As you can see, 'isprintable' is one of the methods available to the unikey object. The attribute error may have existed in an earlier beta version of 13.3, getting fixed by the first candidate release version. Let me know how I can continue 😊

**Comment by tacaswell** [comment] 2024-09-13 02:32
Thank you for the debugging effort on this @anijjar !

**Comment by anijjar** [comment] 2024-10-03 04:46
Since there was no response by alan, should this issue be closed?

**Comment by timhoffm** [comment] 2024-10-03 05:54
I'm closing as this may be fixed upstream and there's no feedback. Please report back if the issue continues to exist.

**Closed** 2024-10-03 05:54 UTC
Labels: Difficulty: Medium, Good first issue
