### ISSUE TITLE
Issue with downloading stinkbug for "Image Tutorial"

### ISSUE THREAD

**Issue by gateslm** [matplotlib/matplotlib#18699] opened 2020-10-09 17:26 UTC
### Problem

When going through the "Image tutorial" on Firefox or Edge, when you try downloading the image of the stinkbug, it will only download as a `webp` file and there is no option to download as `png`. That is even clicking the "View Image" and trying to save it.  Below is trying to save the image in Firefox. 

![image](https://user-images.githubusercontent.com/12010588/95612982-393eed80-0a32-11eb-8e68-3a3ceb85f0ae.png)

This is a problem for introductory students, trying to use this tutorial and learning how to read tutorials. They believe they are doing something wrong and wouldn't be sure how to convert it. As a more advanced user, I still could not find out how to make it a `png` through the tutorial page. 

- Tutorial Link: https://matplotlib.org/tutorials/introductory/images.html 
- Image Link: https://matplotlib.org/_images/stinkbug.png (may say `png` but downloading it is as `webg`)

Operating System: Windows 10 Pro

### Suggested Improvement
The image needs to be updated to a `png` and maybe a direct link to download the image (the latter is not as important). 

If there is a way to do that with a module, that might be cool to include, but just an idea. I can provide more information if necessary.

**Comment by gateslm** [comment] 2020-10-09 17:35
After digging through the [file ](https://github.com/matplotlib/matplotlib/blob/master/tutorials/introductory/images.py), I was able to find the png version. 

I found this [link ](https://raw.githubusercontent.com/matplotlib/matplotlib/master/doc/_static/stinkbug.png) that works (but not available on the tutorial page).

Though the current documentation page (10-9-20) is different that the tutorial in the repository.

**Comment by jklymak** [comment] 2020-10-09 17:52
Well, that is something special firefox is doing and not us.  The stinkbug is a png from other browsers.  Readmore here: https://support.mozilla.org/en-US/questions/1249717
I don't think there is an action item for us, but maybe there is someway we can tell Firefox not to do this...

**Comment by gateslm** [comment] 2020-10-09 18:24
I just tested this in Chrome and it produced the exact same behavior.

**Comment by tacaswell** [comment] 2020-10-09 18:40
I thought we had fixed this before in https://github.com/matplotlib/matplotlib/pull/14896.  I'm working on sorting out where those changes went...

The source of the issue is that we are using cloudflare to proxy / cache our docs and it does some on-the-fly compression / format changes (because our docs are super image heavy I think it is worth keeping these to keep them accessible to people on slow or metered connections).

**Comment by tacaswell** [comment] 2020-10-09 18:42
Ah, the answer is super simple, they are on master and were not backported. See https://matplotlib.org/devdocs/tutorials/introductory/images.html which has a direct-download link.

xref #11296

**Comment by gateslm** [comment] 2020-10-09 18:45
So when it is released, it will be fixed? Because the top of the screen has the following in that link:

![image](https://user-images.githubusercontent.com/12010588/95620407-216d6680-0a3e-11eb-8aeb-4c1832084522.png)

**Comment by tacaswell** [comment] 2020-10-09 19:34
Correct, the docs at https://matplotlib.org/devdocs are built from the current tip of the master branch.  When we do 3.4 and update the default docs the fix will be published to the main doc pages as well.

**Comment by QuLogic** [comment] 2021-02-03 01:43
Duplicate of #11296.

**Closed by QuLogic** 2021-02-03 01:43 UTC
Labels: Documentation
