### ISSUE TITLE
[Bug]: `dpi` setting makes `ax.annotate` arrows disappear with `pgf`

### ISSUE THREAD

**Issue by JulianGoeltz** [matplotlib/matplotlib#27136] opened 2023-10-18 09:33 UTC
### Bug summary

When using `pgf` backend, `ax.annotate` will not be rendered if the dpi is too high, depending on `xycoords` setting.
MWE with GitHub Actions at https://github.com/JulianGoeltz/MWE_mpl_20231018 (build result here: https://github.com/JulianGoeltz/MWE_mpl_20231018/actions/runs/6558671223)

### Code for reproduction

```python
#!/usr/bin/env python3
# encoding: utf-8
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--backend")
parser.add_argument("--dpi", type=int)
args = parser.parse_args()

import matplotlib as mpl
mpl.use(args.backend)
import numpy as np
import matplotlib.pyplot as plt


if __name__ == '__main__':
    fig, (_, ax) = plt.subplots(1, 2, figsize=(1.6, 1.0))

    scale = 0.8
    offset_x, offset_y, offset_1Mx, offset_1My = list(
        np.array([3, 2, 1, 0]) * scale
    )

    arrowprops = {}
    shift = 0.045

    ax_limLX, ax_limHX = -0.03, 1.2
    ax_limLY, ax_limHY = -0.5, 3.0
    ax.set_xlim(ax_limLX, ax_limHX)
    ax.set_ylim(ax_limLY, ax_limHY)
   
    def calc(x, y):
        return ((x - ax_limLX) / (ax_limHX - ax_limLX), (y - ax_limLY) / (ax_limHY - ax_limLY))

    ax.annotate('', xy=calc(0 - shift, offset_x), xycoords='axes fraction',
                xytext=calc(1 + shift, offset_x),
                arrowprops=arrowprops,
                )
    ax.annotate('', xy=(0 - shift, offset_y), xycoords='data',
                xytext=(2 + shift, offset_y),
                arrowprops=arrowprops,
                )

    fn = f'test_{args.backend}_{args.dpi}.pdf'

    print(f"used backend {mpl.get_backend()} and dpi {args.dpi}, saving as {fn}")

    fig.savefig(fn, dpi=args.dpi)
```

### Actual outcome

When using `agg` as backend, both arrows are displayed:
[test_Agg_50.pdf](https://github.com/matplotlib/matplotlib/files/12999897/test_Agg_50.pdf)
[test_Agg_100.pdf](https://github.com/matplotlib/matplotlib/files/12999898/test_Agg_100.pdf)
When using `pgf`, only in the lower `dpi=50` case both are displayed:
[test_pgf_50.pdf](https://github.com/matplotlib/matplotlib/files/12999899/test_pgf_50.pdf)
while in the higher `dpi=100` case, the one with `xycoords='data'` disappears (the one with `xycoords='axes fraction'` is still visible)
[test_pgf_100.pdf](https://github.com/matplotlib/matplotlib/files/12999900/test_pgf_100.pdf)

### Expected outcome

The arrows themselves should not be affected by rasterisation, so they should be displayed irrespective of `dpi` settings, as is the case with the `agg` backend.

### Additional information

I tried to create a suitable MWE, but the bug is very weird to pin down (sorry for the weird numbers, but I couldn't recreate it otherwise)

### Operating system

Ubuntu

### Matplotlib Version

3.8.0

### Matplotlib Backend

pgf

### Python version

3.11

### Installation

pip

**Comment by ksunden** [comment] 2023-10-18 17:19
The thing that is happening here is that when `xycoords = "data"`, the arrow is only shown when the data point in question is in the axes (when it is in `axes fraction`, it is shown regardless)

Please take note of the `annotation_clip` parameter of `annotate`.

There are a couple things that could be relevant here:

- Agg, when saving to PDF, actually offloads to the `pdf` backend, so I think you should get the same results as agg for `pdf` (I appear to, there _can_ be some differences based on things that are computed at call time vs things computed at draw time)

- pgf and pdf are vector backends, so I'm a little surprised this is dpi dependent still, though what is happening is that the point in question is _right_ on the line of the x-axis limits.

The only values that actually matter here are the lower x limit and the x coordinate of the `data` arrow, which are

| transform     | x-axis limit  | Data coord | Notes
| ------------- | ------------- | ---------- | ------
| Data coords   | -0.03         | -0.0122    | Data coord is inside the axes, and thus should be included
| screen@100dpi | 87.6          | 88.4       | If rounded, both round to 88, if truncated, data coord 1 pixel inside, difference is 0.8 pixels
| screen@50dpi  | 43.8          | 44.2       | Actually the same, just at 44, differences is <0.5 pix though
| _get_position_xy@100 pgf | -   | 86.95  | This is the internal method actually used, it is less than the screen coordinate number for some reason.
| _get_position_xy@50 pgf | -   | 43.47  | This is the internal method actually used, it is less than the screen coordinate number for some reason, though both would truncate to the same value, which could explain the behavior
| _get_position_xy pdf | - | 62.6 | This is always in points (72 dpi), regardless of the figure's set dpi, which differs from pgf behavior.

In all, this is edge case behavior within 1 pixel of the cutoff for being out of bounds, which is expected behavior, though yes, ideally I think anything that is in data coords inside of `ax.get_[xy]lim()` _should_ be drawn, the floating point math and rounding that is done makes it hard to ensure that. This _is_ renderer dependent, and so the backend dependence makes some sense.

Though I am a bit surprised, because the check for `Axes.contains_point` (which is ultimately used to decide whether to draw the arrow or not) [includes a radius of 1](https://github.com/matplotlib/matplotlib/blob/39582424f8ce5e042e4e39eeac94893f222c9f8b/lib/matplotlib/axes/_base.py#L4304) which I would have thought would help here. Playing with that number (which I don't think is a good actual fix) shows that upping it to ~1.4 makes it draw the arrow. (Though even the number reported by `_get_position_xy` is within 1 of what the axis limits should be... though actually I think `radius` is a misnomer here and it is actually a diameter, because the 100dpi is the only one to be greater than 0.5 pixels away, which matches the [Path.contains_point](https://matplotlib.org/stable/api/path_api.html#matplotlib.path.Path.contains_point) documented behavior)

If you can deal with the `annotation_clip=False` (which gets odd if the `xy` point is further out from the axes limits) then that may be a solution for you.

**Comment by JulianGoeltz** [comment] 2023-10-20 10:40
Thanks for the quick and thorough response! I think I understand what happens now, at least significantly more so :)

> The thing that is happening here is that when xycoords = "data", the arrow is only shown when the data point in question is in the axes (when it is in axes fraction, it is shown regardless)
> Please take note of the annotation_clip parameter of annotate.

I didn't know about this option, thanks. I wanted to say that the combination of defaults for `xycoord` and `annotation_clip` is surprising, because I guess annotations are usually created and placed intentionally, but with data points well outside the plotting area it does create weird plots.

For me, the main unclarity remaining is why the limits round differently than the data coordinates and why are there no values for the 'x-axis limit' in your table.

Personally, I solved it with the switch from `xycoords='data'` to `xycoords='axes fraction'`, but the `annotation_clip=False` is easier and works equally well.


If you consider the behaviour fully understood and not a bug, feel free to close, and thanks again for the detailed answer.

**Comment by ksunden** [comment] 2023-10-20 17:33
The rounding/dpi dependence I do understand, it has to do with the tolerances being specified in pixels, and thus the smaller the pixels (higher dpi), the lower margin around the plot (which is only half a pixel, to be clear).

Ah... I had missed that the `calc` call was only on the first call to `annotate` (the one in axes fraction)... which explains it. (which gave the -0.0122 number in the table)

Indeed -0.045 (the x value of the annotation in _data_ space) _is_ outside of the axes (-0.03), and _should_ be excluded by the default parameters. (But it is close enough to be within 0.5 px and thus included at some DPIs)

Thus I will indeed close this as expected behavior (with a parameter controlling it as an easy workaround)

**Closed by ksunden** 2023-10-20 17:33 UTC
Labels: backend: pgf
