### ISSUE TITLE
python  complain about "This application failed to start because it could not find or load the Qt platform plugin  'xcb' "  after an update of matplotlib

### ISSUE THREAD

**Issue by csucat** [matplotlib/matplotlib#7597] opened 2016-12-09 02:04 UTC
I am using CentOS 7 and Anaconda 2. Recently, I updated the matplotlib package using `conda`,  if I type 
`import matplotlib.pyplot as plt`, the python interpreter will complain about
> This application failed to start because it could not find or load the Qt platform plugin "xcb".
>Reinstalling the application may fix this problem

I tried to remove `pyqt` and then reinstall the package, but that does not help. Finally I have to remove the 
entire Anaconda install and reinstall Anaconda.

Is there a better way to solve this problem?

**Comment by tacaswell** [comment] 2016-12-09 02:43
try removing and reinstalling qt as well?

What channels did you install from and what is currently in your enviroment?

This probably should be reported against continuum rather than against mpl.

**Comment by csucat** [comment] 2016-12-09 05:36
@tacaswell ,yes, I have tried to remove qt and reinstall it. No effect. 
Now I use the matplotlib (version number 1.5.1) bundled with Anaconda, everything is fine. 
I think the problem is due to the update of matplotlib.

**Comment by dopplershift** [comment] 2016-12-09 17:12
What version of matplotlib was causing the problem?

**Comment by csucat** [comment] 2016-12-10 14:47
@dopplershift, currently I am using matplotlib 1.5.1, the newest version available for Anaconda is 1.5.3. So I think it is matplotlib 1.5.3 which is causing the problem.

**Comment by tacaswell** [comment] 2016-12-10 17:51
Closing this as this is not an issue with mpl, but an issue with the packaging by Continuum (which we have no control over).  

This is probably a duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/1182 .  If not, please raise a new issue on https://github.com/ContinuumIO/anaconda-issues/issues

**Closed by tacaswell** 2016-12-10 17:51 UTC

**Comment by jdhao** [comment] 2017-02-10 06:16
For anyone who have met the same problem. In my system, the problem is that matplotlib is using the qt dynamic library provided by the system, as indicated by https://github.com/ContinuumIO/anaconda-issues/issues/1249. The solution is to remove the `/usr/lib64` (on CentOS system) from the `LD_LIBRARY_PATH `. Then you should be able to `import matplotlib.pyplot as plt` without the above error message.

**Comment by mimoralea** [comment] 2017-07-24 02:21
@jdhao thanks for following up. A quick `unset LD_LIBRARY_PATH` shows that the issue is exactly that. Thank you.

**Comment by motikadosh** [comment] 2017-09-06 07:31
Solved by installing matplotlib from pip instead of conda (In my case both had matplotlib version 2.0.2)

**Comment by unicoe** [comment] 2018-03-12 02:47
@motikadosh Thank you! your method help me~

**Comment by mimoralea** [comment] 2018-06-02 21:46
```bash
pip uninstall matplotlib
pip install matplotlib
```
