### ISSUE TITLE
legend marker update bug

### ISSUE THREAD

**Issue by gregorio-bastardo** [matplotlib/matplotlib#2035] opened 2013-05-21 08:44 UTC
When a line object is added to the legend _without marker_, the update works fine both on data and legend line, but _with marker_ it does not refresh the legend line's marker:

<pre><code class="python">
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)
line, = ax.plot(range(10), range(10))

# uncomment next line to reproduce bug
# line.set_marker('d')

legend = ax.legend([line], ['foo'])
legend_line, = legend.get_lines()
fig.show()
raw_input('press enter to clear marker')
line.set_marker('')
legend_line.set_marker('')
fig.canvas.draw()
raw_input('press enter to set marker')
line.set_marker('d')
legend_line.set_marker('d')
fig.canvas.draw()
raw_input('press enter to exit')
 
</code></pre>

I understand that lines and markers are drawn separately to support special legend patterns, but this is somehow not the case when line is originally added to the legend _without marker_. Please align legend line and marker property updates.

python 2.7.4 win32
matplotlib 1.2.1

originally reported on mpl-users:
http://matplotlib.1069221.n5.nabble.com/legend-marker-update-problem-tc41070.html

**Comment by petehuang** [comment] 2016-12-28 23:12
Reproduced on python 2.7.12, matplotlib 1.5.3

Thanks for the excellent code to repro

**Comment by eltrompetero** [comment] 2018-11-06 21:33
Is this still a bug? I'm using v3.0.1 with Python 3.6.6 and I'm finding that the marker color doesn't update.

```
import matplotlib.pyplot as plt
fig,ax=plt.subplots()

ax.plot([0,1],[0,1],'o-' )
leg=ax.legend((1,))
leg.legendHandles[0].set_color('k')
leg.legendHandles[0].set_mfc('k')
```

**Comment by ImportanceOfBeingErnest** [comment] 2018-11-06 22:16
I suppose this would be fixed by https://github.com/matplotlib/matplotlib/pull/11358, which is still work in progress. 

If you are really in desperate need to do the manipulation without going through the legend creation (again), you may crawl your way through the packers and set the colors of the artists directly.

```
import matplotlib.pyplot as plt
fig,ax=plt.subplots()

ax.plot([0,1],[0,1],'o-' )
leg=ax.legend((1,))

c = leg.get_children()[0].get_children()[1].get_children()[0].get_children()[0].get_children()[0]
for a in c.get_children():
    a.set_color('k')
plt.show()
```

**Comment by eltrompetero** [comment] 2018-11-07 06:31
Yes, I have a simpler workaround by just plotting the marker styles I want some where far away on the graph and fixing the axis limits. But I probably spent more time figuring out that this was a bug and not me being confused than hacking it....haha...

**Comment by ImportanceOfBeingErnest** [comment] 2018-11-07 10:44
@eltrompetero Sorry, I should have been clearer in my last comment. The workaround is meant for cases where you want to manipulate the legend *after* it being created. This might be useful in cases as the original issue, or when you have complex functions you don't want to change for the purpose, or when working with downstream libraries which hide the legend creation from you like seaborn, pandas etc.

If, however, you have full control over the legend generation, you would just create the legend with the handle you want to show. This is (hopefully) described in [the legend guide](https://matplotlib.org/tutorials/intermediate/legend_guide.html). So in your case from above, you would create the legend with a black line from the start:

```
import matplotlib.pyplot as plt
fig,ax=plt.subplots()

ax.plot([0,1],[0,1],'o-' )
ax.legend(handles=[plt.Line2D([],[], marker="o", color="k")], labels=(1,))
```

That being said, if you have a suggestion on how to improve the [legend guide](https://matplotlib.org/tutorials/intermediate/legend_guide.html) or other documentation, which would have prevented you from spending too much time on this, we're all ears.

**Comment by eltrompetero** [comment] 2018-11-07 14:44
Okay. Thanks! Didn't read your comment carefully enough.

**Comment by teto** [comment] 2019-07-17 02:36
Any patch available ? My program relies on pandas/matplotlib and the legend is systematically wrong because of this.

**Closed** 2021-08-14 22:47 UTC
Labels: status: confirmed bug
