### ISSUE TITLE
margins does not handle bézier curves

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7184] opened 2016-09-26 20:56 UTC
2.0b4, example modified from http://matplotlib.org/users/path_tutorial.html#bezier-example

```
import matplotlib.pyplot as plt
from matplotlib.path import Path
import matplotlib.patches as patches

verts = [
    (0., 0.),  # P0
    (0.2, 1.), # P1
    (1., 0.8), # P2
    (0.8, 0.), # P3
    ]

codes = [Path.MOVETO,
         Path.CURVE4,
         Path.CURVE4,
         Path.CURVE4,
         ]

path = Path(verts, codes)

fig, axs = plt.subplots(2)

patch = patches.PathPatch(path, facecolor='none', lw=2)
axs[0].add_patch(patch)
xs, ys = zip(*verts)
axs[0].plot(xs, ys, 'x--', lw=2, color='black', ms=10)

patch = patches.PathPatch(path, facecolor='none', lw=2)
axs[1].add_patch(patch)

plt.show()
```

![figure_1](https://cloud.githubusercontent.com/assets/1322974/18851432/c9de4e8e-83f0-11e6-9e61-2d72101b0f81.png)

Note how the bottom axes have their limits set as if using the positions of the bézier control points (on the unit square), with no margins.

**Comment by WeatherGod** [comment] 2016-09-26 21:26
This is similar to my comments back during the SciPy conference about how
hit-testing is done on the original list of coordinates rather than on the
output list. Other operations like this is also done on the original data
rather than the generated coordinates.

This is a bit trickier, though because the margins are supposed to be about
the datapoints, not the lines. Usually, they are one and the same, but that
is not the case for bezier curves.

**Comment by efiring** [comment] 2016-11-14 06:59
I would classify this as "won't fix".  Autoscaling is already enough of a mess without trying to take Bezier curves into  account.  It's not supposed to be perfect, and able to handle every possible situation; it is supposed to provide a decent first-try plot most of the time.

**Comment by anntzer** [comment] 2016-11-14 07:07
I certainly don't mind milestoning this as 3.0 (as in "far, far future") but I'm don't think the problem is unresolvable.

**Comment by efiring** [comment] 2016-11-14 08:06
It's not a question of whether it can be solved, but of whether it is worth the effort and the added complexity.  We need to set priorities.

**Comment by dopplershift** [comment] 2020-04-21 05:08
Fixed by #16832.

**Comment by dstansby** [comment] 2021-01-02 10:48
I'm not sure why this was closed; on the current master branch I can reproduce the test case in the original issue, so I don't think this has been fixed yet.

**Comment by dstansby** [comment] 2021-01-02 10:51
Also worth noting that one needs to manually autoscale the `Axes` after adding a patch to see the autoscale behaviour, which isn't currently present in the example at the top. Adding `axs[1].autoscale()` just before `plt.show()` works, and shows that the control points are still included in the auto scaling.

**Comment by tacaswell** [comment] 2023-02-09 22:16
> Adding axs[1].autoscale() just before plt.show() works, and shows that the control points are still included in the auto scaling.

I think this means it is fixed as adding the auto scaling line gives:

![so](https://user-images.githubusercontent.com/199813/217951673-746636b6-68a9-4935-9b9b-127a1691545b.png)

which is scaling to the curve and not to the control points.  If `add_patch` should autoscale automatically is a different question!

**Closed by tacaswell** 2023-02-09 22:16 UTC
Labels: topic: path handling

**Comment by dstansby** [comment] 2023-02-09 22:20
I suspect (but haven't checked) that https://github.com/matplotlib/matplotlib/pull/19216 fixed this
