### ISSUE TITLE
[Bug]: dotted line with "lw=0" breaks Adobe Acrobat Reader

### ISSUE THREAD

**Issue by ultimatile** [matplotlib/matplotlib#24371] opened 2022-11-04 22:26 UTC
### Bug summary

When a figure that uses `ls=":"` and `lw=0` is saved as a pdf, it does not render correctly only in Adobe Acrobat Reader.

### Code for reproduction

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots() 
ax.plot([0], [0], ":", lw=0)
plt.savefig("test.pdf")
```

### Actual outcome

# Adobe Acrobat Reader
![スクリーンショット 2022-11-05 6 38 08](https://user-images.githubusercontent.com/18307308/200078837-b367037a-5bde-448f-b2d3-3390dfadc40d.png)

### Expected outcome

# other pdf viewers
I tried Skim, Chrome, and Safari.
![スクリーンショット 2022-11-05 7 05 21](https://user-images.githubusercontent.com/18307308/200081827-75823332-29f3-4616-b720-87bc46dc9cda.png)

### Additional information

Other line style keys, "-", "--" and "-." work fine.

It may be a related discussion.
https://github.com/matplotlib/matplotlib/issues/1188#issuecomment-123589303

### Operating system

macOS 10.15.7

### Matplotlib Version

3.1.0

### Matplotlib Backend

module://ipykernel.pylab.backend_inline, MacOSX

### Python version

3.7.4

### Jupyter version

6.0.1

### Installation

conda

**Comment by tacaswell** [comment] 2022-11-06 03:33
@ultimatile Does this reproduce with a newer version of Matplotlib?  3.1.0 is pretty old now and we have made a number of changes to the pdf backend.

This does remind me of some performance issues we had with the dash pattern scaling with very thin lines because there ended up being _way_ too many segments, however the failure mode of taking out the other lines is very odd.

**Comment by tacaswell** [comment] 2022-11-06 04:52
In 3.6.2 this now raises

```python
File /usr/lib/python3.10/site-packages/matplotlib/backend_bases.py:926, in GraphicsContextBase.set_dashes(self, dash_offset, dash_list)
    923         raise ValueError(
    924             "All values in the dash list must be non-negative")
    925     if dl.size and not np.any(dl > 0.0):
--> 926         raise ValueError(
    927             'At least one value in the dash list must be positive')
    928 self._dashes = dash_offset, dash_list

ValueError: At least one value in the dash list must be positive
```

I think at some point we "fixed" this by making it impossible to generate broken pdfs.  @ultimatile are you OK if we close this?

**Comment by tacaswell** [comment] 2022-11-08 03:06
I'm going to go ahead a close this as it is no longer reproducible.

@ultimatile If you can reproduce this with a newer version of Matplotlib please ping to have the re-opened or open a new issue!

**Closed by tacaswell** 2022-11-08 03:06 UTC
Labels: backend: pdf

**Comment by ultimatile** [comment] 2022-11-08 06:23
Thank you for your replies, and sorry for my late response.
I tried to update the version of matplotlib, but I am having some trouble, and have still been with version 3.5.3.
Therefore, I have not confirmed the issue with version 3.6.2.
I have no objection to closing it since the problem should have been "solved."
As you suggested, I will address the issue if it arises again in the latest version.
