### ISSUE TITLE
Please provide universal2 wheels for macOS

### ISSUE THREAD

**Issue by ronaldoussoren** [matplotlib/matplotlib#19267] opened 2021-01-09 12:36 UTC
Python 3.9.1 introduced an "universal2" installer variant with native support for x86_64 and arm64 on macOS (10.9 or later for x86_64, 11.0 or later for arm64).

It would be nice to have binary wheels for this installer next to the current x86_64 wheels for macOS.

**Comment by QuLogic** [comment] 2021-01-12 10:50
This would require support in cibuildwheel: https://github.com/joerick/cibuildwheel/issues/473

**Comment by QuLogic** [comment] 2021-05-14 23:46
We will need NumPy wheels too, I think: https://github.com/numpy/numpy/issues/18143

**Comment by QuLogic** [comment] 2021-05-20 00:52
Pillow has arm64 wheel, thought not universal2. We will also need kiwisolver wheels: MacPython/kiwisolver-wheels#13

**Comment by QuLogic** [comment] 2021-10-05 05:07
These have been built for 3.5.0rc1. Can someone check whether the arm64 and universal2 wheels work on Apple Silicon? And that the universal2 wheel works on x86_64 as well?

**Comment by greglucas** [comment] 2021-11-23 02:59
The 3.5 release contains the universal2 wheels now. I can confirm that installing the universal2 on x86_64 works for me locally. I can't test on Apple Silicon, but I think we can close this for now and if people have issues we can reopen.

**Closed by greglucas** 2021-11-23 02:59 UTC
Labels: New feature, OS/Apple

**Comment by sIm0ny** [comment] 2024-08-02 20:44
Why are Universal2 wheels no longer available after version 9.0.1? I need a Universal2 wheel for my application to support a universal binary. Can you provide guidance or alternatives?

**Comment by QuLogic** [comment] 2024-08-02 20:51
See https://github.com/matplotlib/matplotlib/pull/26125 and https://github.com/numpy/numpy/pull/20787#issuecomment-1319153645

**Comment by sIm0ny** [comment] 2024-08-02 21:04
Do you know a work arround to still build an universal application?

**Comment by tacaswell** [comment] 2024-08-06 20:15
See instructions in https://github.com/numpy/numpy/pull/20787#issuecomment-1319153645 for how to generate the fused wheels if you need them.
