### ISSUE TITLE
Crashes on Mac

### ISSUE THREAD

**Issue by zhouhao27** [matplotlib/matplotlib#13615] opened 2019-03-07 05:45 UTC
### Bug report

**Bug summary**

It crashes on Mac Osx.

**Code for reproduction**

```python
from matplotlib import pyplot as plt
plt.figure()
```

**Actual outcome**

```
2019-03-07 11:14:39.220 python[13951:2853154] -[QNSApplication _setup:]: unrecognized selector sent to instance 0x7fc9418afd10
2019-03-07 11:14:39.222 python[13951:2853154] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[QNSApplication _setup:]: unrecognized selector sent to instance 0x7fc9418afd10'
*** First throw call stack:
```

**Expected outcome**

**Matplotlib version**

  * Operating system: OSX 10.13.6
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`TkAgg`):
  * Python version: 3.6.5
  * Jupyter version (if applicable):
  * Other libraries: 

```
I installed Matplotlib by pip
```

**Comment by jklymak** [comment] 2019-03-07 06:34
This is a duplicate of #13414, I think.  I'll close here, but feel free to continue discussion there.

**Closed by jklymak** 2019-03-07 06:34 UTC
