### ISSUE TITLE
[ENH]: More control of "axis planes" on 3D axes

### ISSUE THREAD

**Issue by tdelcourt** [matplotlib/matplotlib#23216] opened 2022-06-07 12:51 UTC
### Problem

Duplicate from [stackoverflow 72375427](https://stackoverflow.com/questions/72375427/matplotlib-plot-2d-data-in-3d-plot-as-a-projection-on-faces-without-the-2d-dots) .

When plotting 2D scatter data on a 3D scatter plot (eg as in the [example code from matplotlib website](https://matplotlib.org/stable/gallery/mplot3d/2dcollections3d.html), which incidentally shows the problematic behaviour as the sin curve is obviously off by a bit), the 2D data floats "on top" or "alongside" of the 2D face it is supposed to be placed upon and therefore gives the impression to be wrongly plotted. For example, using this to show the projection of dots from the 3D space to 2D planes (3 plot faces) gives the impression that the dots are not at the correct position, because of the parallax (see plot linked below).

[3D plot with 2D plots on sides, as produced by above code](https://i.stack.imgur.com/yOkNr.png)
[3D plot with 2D plots on sides, as expected](https://i.stack.imgur.com/qDabq.png)

I cannot get the planes to exactly be positioned at a specified coordinate. Setting the x_lim, y_lim and z_lim parameters only slightly improves this, but there is still a slight, seemingly random, margin added beyond the axes limits (contrary to what happens in 2D plots).

### Proposed solution

I may have missed the option to do this. But it would be nice to have the possibility to overrule the automatic setting of the position of the edge planes so that setting the x_lim, y_lim and z_lim parameters fixes the planes to those specified values (for instance, or another extra parameter). 

Another solution based on generating the 2D graphs as images and adding them to the 3D plot could potentially work, but probably is a messy hack more than a solution.

**Comment by tacaswell** [comment] 2022-06-08 22:39
@tdelcourt Is that title an accurate summary of your request?

**Comment by scottshambaugh** [comment] 2022-08-03 16:14
I believe this is a duplicate of https://github.com/matplotlib/matplotlib/issues/18052 ?

**Comment by scottshambaugh** [comment] 2022-08-24 13:46
Duplicate of https://github.com/matplotlib/matplotlib/issues/18052

@tdelcourt thank you for the report, and please let me know if that other issue does not cover the scope of what you're asking for!

**Comment by scottshambaugh** [comment] 2022-08-24 13:48
Closing as a duplicate of https://github.com/matplotlib/matplotlib/issues/18052

@tdelcourt thank you for the report and please let me know if that other issue does not capture the scope of what you're asking for!

**Closed by scottshambaugh** 2022-08-24 13:48 UTC
Labels: New feature, topic: mplot3d, status: duplicate
