### ISSUE TITLE
Plotting masked array lose data points

### ISSUE THREAD

**Issue by montes00** [matplotlib/matplotlib#7542] opened 2016-12-01 09:03 UTC
To help us understand and resolve your issue please check that you have provided
the information below.

- [x] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
osx, linux. Matloplib version 1.5.3. Python version 3.5.2
- [x] How did you install Matplotlib and Python (pip, anaconda, from source ...)
anaconda (osx/linux), macports (osx)
- [x] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
      that demonstrates the issue i.e a small piece of code which reproduces the issue
      and can be run with out any other (or as few as possible) external dependencies.
Enclosed
- [x] If this is an image generation bug attach a screenshot demonstrating the issue.
Attached
- [x] If this is a regression (Used to work in an earlier version of Matplotlib), please 
      note where it used to work.
N/A

==
When plotting numpy's maskedarray with plot(), I could not see some data points.
A simple code follows.  If I savefig() to png file, it works. If I savefig() to pdf (or eps) file, it does not.

```
import matplotlib.pyplot as plt
import numpy as np
arr = np.array([1, 5, -3, -3, 5, -3, -3, 2, -3, -3, 7, -3, -3, 2])
arrm = np.ma.masked_less(arr, 0)
plt.figure()
plt.plot(arrm, 'o')
plt.savefig('a.png')
plt.savefig('a.pdf')
```

![a](https://cloud.githubusercontent.com/assets/6485215/20787595/ff72490c-b7ac-11e6-8f05-0965d0591648.png)
[a.pdf](https://github.com/matplotlib/matplotlib/files/624078/a.pdf)

**Comment by QuLogic** [comment] 2016-12-01 09:14
Note, the problem's with the PDF that's not shown by GitHub, not the PNG.

**Comment by montes00** [comment] 2016-12-01 09:50
The png works fine; we see 6 points, which is for reference.
a.pdf (not previewed in GitHub but the link is in the end) has a problem, which only has 3 points.

**Comment by anntzer** [comment] 2016-12-01 18:15
Pretty sure this is a duplicate of #7293 which has better figures so I'll just close this.

**Closed by anntzer** 2016-12-01 18:15 UTC
Labels: backend/pdf
