### ISSUE TITLE
Unable to install matplotlib on MacOS with Python 3.9

### ISSUE THREAD

**Issue by fablau** [matplotlib/matplotlib#18810] opened 2020-10-26 00:31 UTC
Hello.

I am trying to install matplotlib on MacOS Catalina (version 10.15.6) and Python 3.9 with this command:

`pip3 install matplotlib`

But I get this long error:

`pip3 install matplotlib
Collecting matplotlib
  Using cached matplotlib-3.3.2.tar.gz (37.9 MB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-install-e4h4p2_1/matplotlib/setup.py'"'"'; __file__='"'"'/private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-install-e4h4p2_1/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-pip-egg-info-tan2fixa
         cwd: /private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-install-e4h4p2_1/matplotlib/
    Complete output (62 lines):
    
    Edit setup.cfg to change the build options; suppress output with --quiet.
    
    BUILDING MATPLOTLIB
      matplotlib: yes [3.3.2]
          python: yes [3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23)  [Clang 6.0
                      (clang-600.0.57)]]
        platform: yes [darwin]
     sample_data: yes [installing]
           tests: no  [skipping due to configuration]
          macosx: yes [installing]
    
    running egg_info
    creating /private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-pip-egg-info-tan2fixa/matplotlib.egg-info
    writing /private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-pip-egg-info-tan2fixa/matplotlib.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-pip-egg-info-tan2fixa/matplotlib.egg-info/dependency_links.txt
    writing namespace_packages to /private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-pip-egg-info-tan2fixa/matplotlib.egg-info/namespace_packages.txt
    writing requirements to /private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-pip-egg-info-tan2fixa/matplotlib.egg-info/requires.txt
    writing top-level names to /private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-pip-egg-info-tan2fixa/matplotlib.egg-info/top_level.txt
    writing manifest file '/private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-pip-egg-info-tan2fixa/matplotlib.egg-info/SOURCES.txt'
    init_dgelsd failed init
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-install-e4h4p2_1/matplotlib/setup.py", line 242, in <module>
        setup(  # Finally, pass this all along to distutils to do the heavy lifting.
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 298, in run
        self.find_sources()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 305, in find_sources
        mm.run()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 536, in run
        self.add_defaults()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 572, in add_defaults
        sdist.add_defaults(self)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-install-e4h4p2_1/matplotlib/setup.py", line 88, in finalize_options
        self.distribution.ext_modules[:] = [
      File "/private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-install-e4h4p2_1/matplotlib/setup.py", line 91, in <listcomp>
        for ext in package.get_extensions()
      File "/private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-install-e4h4p2_1/matplotlib/setupext.py", line 345, in get_extensions
        add_numpy_flags(ext)
      File "/private/var/folders/20/l7ql06pw8xjf_x0059b44jsh0000gq/T/pip-install-e4h4p2_1/matplotlib/setupext.py", line 469, in add_numpy_flags
        import numpy as np
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
        raise RuntimeError(msg)
    RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
    RankWarning: Polyfit may be poorly conditioned
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

Any ideas?

Thanks to anyone in advance.

All the best,
Fab.

**Comment by DARK-art108** [comment] 2020-10-26 05:32
I have gone through your error and the error is that the pip is not able to build the egg or wheel so that why it is throwing the error. Try with the below commands to install matplotlib in your machine.

`pip3 install pipwin`
`pipwin install matplotlib`

I hope this will work smoothly, if giving any error drop the msg again I will look into it.

All the Best 
Ritesh

**Comment by jklymak** [comment] 2020-10-26 14:46
This is a duplicate of #18711  Thanks!

**Closed by jklymak** 2020-10-26 14:46 UTC

**Comment by fablau** [comment] 2020-10-26 16:04
Thank you Ritesh, tried your solution but didn't work, got a bunch of errors. It looks like I just need to wait for the NumPy wheels to be available.

Thanks again.

**Comment by orome** [comment] 2020-10-30 15:52
>  It looks like I just need to wait for the NumPy wheels to be available.

Even with NumPy wheels (1.19.3) Matplotlib installation fails on 3.9 (macOS)

**Comment by jklymak** [comment] 2020-10-30 15:54
I was able to install with `conda`.  Maybe open a new issue with exactly what your install steps were and how it fails.

**Comment by orome** [comment] 2020-10-30 16:00
> I was able to install with `conda`. Maybe open a new issue with exactly what your install steps were and how it fails.

I didn't know this was an issue about `conda` . 

I was just using the steps in the OP. Clean 3.9 virtual environment, and then `pip install matplotlib`.

**Comment by jklymak** [comment] 2020-10-30 16:04
... and it fails with the same error?

**Comment by orome** [comment] 2020-10-30 16:43
> ... and it fails with the same error?

Until yesterday, yes. Now I get
```
[... pages and pages ...]
ERROR: Failed building wheel for matplotlib
```
NumPy (as of yesterday) and SimPy now work with 3.9, but Matplotlib (3.3.2) does not.

**Comment by venneladondapati** [comment] 2020-11-02 14:45
> I have gone through your error and the error is that the pip is not able to build the egg or wheel so that why it is throwing the error. Try with the below commands to install matplotlib in your machine.
> 
> `pip3 install pipwin`
> `pipwin install matplotlib`
> 
> I hope this will work smoothly, if giving any error drop the msg again I will look into it.
> 
> All the Best
> Ritesh

I

**Comment by venneladondapati** [comment] 2020-11-02 14:46
> I have gone through your error and the error is that the pip is not able to build the egg or wheel so that why it is throwing the error. Try with the below commands to install matplotlib in your machine.
> 
> `pip3 install pipwin`
> `pipwin install matplotlib`
> 
> I hope this will work smoothly, if giving any error drop the msg again I will look into it.
> 
> All the Best
> Ritesh

I am facing the same issue in mac. Can you please help me with that?

**Comment by orome** [comment] 2020-11-03 17:17
> Again, please open a new issue. It may be helpful to know what those "pages and pages" say...

Posted as #18881 linking to [a gist containing full output](18881).
