### ISSUE TITLE
Cairo backend flips image

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#10821] opened 2018-03-17 22:35 UTC
### Bug report

**Bug summary**

The new Cairo backend flips the `imshow` image compared to the Agg.

**Code**

```
import matplotlib
matplotlib.use("TkCairo") # or matplotlib.use("TkAgg")
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(4,2.5))

im = plt.imread("house.png")
ax.imshow(im, origin="upper")

fig.suptitle(matplotlib.get_backend())
fig.savefig(matplotlib.get_backend()+".png")
plt.show()

```

**Actual outcome: TkAgg (similar with Qt4Agg)**

![tkagg](https://user-images.githubusercontent.com/23121882/37560576-6d5930b4-2a3b-11e8-884d-0d59f78d997b.png)

**Actual outcome: TkCairo (similar with Qt4Cairo)**

![tkcairo](https://user-images.githubusercontent.com/23121882/37560579-71fa8cd0-2a3b-11e8-8472-1b52d6c11a49.png)

**Expected outcome**

I would guess the Agg behaviour is the intended one.

**Matplotlib version**

  * Operating system: Windows 8.1
  * Matplotlib version: 2.2
  * Matplotlib backend:  TkCairo, Qt4Cairo (flipped image); TkAgg, Qt4Agg (upright image)
  * Python version: 2.7.10

**Comment by anntzer** [comment] 2018-03-18 03:07
Duplicate of #8798.

**Closed by anntzer** 2018-03-18 03:07 UTC
