### ISSUE TITLE
Yticks on loglog plots - Duplicates when using ylim()

### ISSUE THREAD

**Issue by JacobEFO** [matplotlib/matplotlib#13305] opened 2019-01-28 07:18 UTC
### Bug report

**Bug summary**
When using loglog plot for plotting gain/phase vs. frequency and setting yticks and labels, the ylim([min max]) writes as powers, whereas I try to set the end-points in whole numbers.

```python
import numpy as np
import matplotlib.pyplot as plt

freq = np.linspace(20, 20e3, 1000) # Frequency vector

# Generate gain vector
gain = []
for frequency in freq:
    gain.append(27.4)
gain = np.array(gain)

fig = plt.figure(dpi=300)
plt.yscale('log')
plt.xticks([20, 100, 1000, 10000, 20000], ['20', '100', '1k', '10k', '20k'])

plt.loglog(freq, gain, color='red', lw=1.3)


ytickval = []
yticknotate = []
for i in range(20, 31):
    ytickval.append(i)
    yticknotate.append(str(i))

plt.yticks(ytickval, yticknotate)
plt.xlim(20, 75000)
plt.ylim(20,30)
plt.show()
```

**Actual outcome**
![error](https://user-images.githubusercontent.com/22648097/51820000-afd69e80-22d4-11e9-818c-fd5a786ac10c.png)
```

**Expected outcome**
The expected outcome is end-points (20dB and 30dB) written as 20 and 30 respectively, instead of 2*10^1 and 3*10^1

**Matplotlib version**
<!--Please specify your platform and versions of the relevant libraries you are using:-->
  * Operating system: Windows 10 Education
  * Matplotlib version:  3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.8 (anaconda)
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: Numpy

<!--Please tell us how you installed matplotlib and python e.g., from source, pip, conda-->
<!--If you installed from conda, please specify which channel you used if not the default-->
Used the default conda channel.

**Comment by timhoffm** [comment] 2019-01-28 23:12
The effect of the duplicated labels comes from the fact that `plt.yticks()` sets the major tick labels. However the minor labels 2x10^1 and 3x10^1 are still there.

One option is to deactivate the minor labels:

~~~
plt.tick_params('y', which='minor', labelleft=False)
~~~
Note also, that can use a formatter instead of hard-coding the strings for the tick labels:
~~~
from matplotlib.ticker import LogFormatter
ytickval = np.arange(20, 31)
plt.yticks(ytickval)
plt.gca().yaxis.set_major_formatter(LogFormatter(minor_thresholds=(1, 10)))
~~~

**Comment by jklymak** [comment] 2019-01-28 23:32
This is really a bug, though.  Minor locators should not be returning ticks where there are major ticks.  A solution has been discussed but not implemented yet.

**Comment by JacobEFO** [comment] 2019-01-29 06:35
Ah, thank you for suggesting this. It does work, nonetheless unfortunate if I end up in the situation where I actually need the minor ticks one day :)

Feel free to consider this issue resolved, unless you wish to keep it open as a "Bug report".

**Comment by anntzer** [comment] 2019-01-29 10:18
I am going to close this as duplicate of #11575 (I think?  feel free to mention anything I missed).

**Closed by anntzer** 2019-01-29 10:18 UTC
Labels: Community support
