### ISSUE TITLE
[Doc]: Link API docs of pyplot wrappers to the corresponding Axes methods

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#23795] opened 2022-09-01 10:10 UTC
### Problem

The API docs for the pyplot plotting functions are not connected to the corresponding Axes methods.  This means that, for example, there is no easy way to reach the fill_between examples at https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.fill_between.html (which may be e.g. where google sends you to), whereas they are present at https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.fill_between.html.

### Suggested improvement

The easiest short-term solution may be to manually fix all backlink entries in examples to include both the Axes method and the pyplot wrapper, regardless of which one is actually showcased in the example.
OTOH it may be better to just merge the two API pages so e.g. Axes.fill_between and pyplot.fill_between are documented *on the same page* (as the contents are actually entirely identical) with both function names in the header (the function signature in bold).  However this may require more fiddling with sphinx.

**Comment by tacaswell** [comment] 2022-09-01 19:00
I am in favor of linking, but against putting them on the same page.  I would like the link to be in a sentance that reads something like "This pyplot function is a sate-full convenience wrapper about <link to Axes method>" 😈 .

**Comment by timhoffm** [comment] 2022-10-15 22:05
Where would we want such a sentence?

- [ ] At the top of the docs (personally :-1:)
- [ ] Before the Parameters section (i.e. at the end of the description block)
- [ ] In a Notes section
- [ ] As a see-also entry

**Comment by timhoffm** [comment] 2024-04-04 23:34
Duplicate of #17786 and partially fixed by #27909 (for the auto-generated methods).

**Closed by timhoffm** 2024-04-04 23:34 UTC
Labels: Documentation, topic: pyplot API
