### ISSUE TITLE
Colorbar becomes 0 to 1 after colorbar ax.yaxis.set_major_formatter

### ISSUE THREAD

**Issue by BowenFu** [matplotlib/matplotlib#7558] opened 2016-12-03 11:53 UTC
matplotlib 1.5.3
pip
python 3.4
Ubuntu 14.04

    NO_POWER_FORM = matplotlib.ticker.ScalarFormatter(useMathText=False, useOffset=False)
    NO_POWER_FORM.set_scientific(False)

    colorbar_ax=matplotlib.pyplot.colorbar(ticks=contour_range).ax
    colorbar_ax.set_title(colorbar_zlabel)
    colorbar_ax.yaxis.set_major_formatter(style.NO_POWER_FORM)

**Comment by tacaswell** [comment] 2016-12-03 16:00
attn @efiring

**Comment by efiring** [comment] 2016-12-03 17:39
@bowenfu, you have not provided a self-contained example so I can't run your code, but I think the problem is that colorbar is not a normal Axes; it is a rather odd special-purpose beast in many ways.  It does not use the Axes locators at all, and it uses the x or y Axes formatter only for the offset string. The API for manipulating the tick label format is via the `format` kwarg in its initializer.

**Comment by BowenFu** [comment] 2016-12-06 06:13
@efiring, yes, matplotlib.pyplot.colorbar(format=NO_POWER_FORM) works well.

**Comment by efiring** [comment] 2016-12-06 06:46
I'm going to close this, as it is not a bug.

**Closed by efiring** 2016-12-06 06:46 UTC

**Comment by BowenFu** [comment] 2016-12-06 06:53
@efiring, maybe  warnings should be given when colorbar_ax.yaxis.set_major_formatter is  called.

**Comment by efiring** [comment] 2016-12-06 07:23
I don't see any reasonably simple way to do this.
