### ISSUE TITLE
Baseline alignment of xtick labels when using usetex=True

### ISSUE THREAD

**Issue by xnx** [matplotlib/matplotlib#4040] opened 2015-01-26 01:35 UTC
The following code produces a mis-aligned 'Q' on the x-axis on my system (Mac OS X Yosemite, Python 2.7.9 and 3.3.5, Matplotlib 1.3.1):

    import numpy as np
    import matplotlib as mpl
    import matplotlib.pyplot as plt

    mpl.rcdefaults()
    mpl.rc('text', usetex=True)

    letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    x = range(26)
    v = np.random.random(26)

    fig = plt.figure()
    ax = fig.add_subplot(111)

    ax.bar(x, v, width=0.8, align='center')

    ax.set_xticks(x)
    ax.set_xticklabels(letters)
    plt.savefig('so.eps')

Apparently only when saving as eps, and only with usetex=True.

![screen shot 2015-01-25 at 20 32 59](https://cloud.githubusercontent.com/assets/371774/5894330/a1dde868-a4d1-11e4-98f1-8f5ab83b4536.png)

**Comment by tacaswell** [comment] 2015-01-26 02:30
I can't reproduce this, but my font looks different:

![so2](https://cloud.githubusercontent.com/assets/199813/5894469/cc606094-a4d5-11e4-97f2-1a33cb0094e1.png)

**Comment by xnx** [comment] 2015-01-26 02:58
The alignment is correct on my set-up if I explicitly set

    mpl.rc('font',**{'family':'serif',})

so I'm beginning to suspect this is something very platform-specific, possibly related to the font Preview is choosing for itself on my Mac?

**Comment by tacaswell** [comment] 2015-01-26 05:16
This would not be the first time that we have discovered deficiencies in third-party readers (I think we have/had issues with preview before with either eps or pdf and had some issues with SVG readers recently as well).

If mpl is generating invalid/ambiguous eps files that is something we can fix, if it is preview behaving badly with fonts, there is not a whole lot we can do.

**Comment by tacaswell** [comment] 2015-02-07 21:32
I am going to close this because it seems to another reader related problem, not an issue with the eps files mpl is generating.

Preview has been known to have issues in the past.

Please re-open this if I am mistaken.

**Closed by tacaswell** 2015-02-07 21:32 UTC
Labels: backend/ps, OS/Apple, text
