### ISSUE TITLE
Segfault when using matplotlib in combination with multiprocessing / concurrent.Futures.ProcessPoolExecutor for python<3.7

### ISSUE THREAD

**Issue by normanius** [matplotlib/matplotlib#12756] opened 2018-11-06 02:25 UTC
### Bug report

**Bug summary**

The following code crashes with a SIGSEGV. It uses `ProcessPoolExecutor` to create subprocesses for solving a least square problem. The crash can be avoided, if matplotlib is not imported. 

**Code for reproduction**

```
import numpy as np
import multiprocessing as mp
from numpy.linalg import lstsq
from concurrent.futures import ProcessPoolExecutor

##################################################
# Two possibilities to avoid the crash
avoid_crash1 = False # Do not import matplotlib
avoid_crash2 = False # Reduce the dataset size
##################################################

if not avoid_crash1:
    import matplotlib.pyplot as plt
size = 128 if avoid_crash2 else 129

#import faulthandler
#faulthandler.enable()

def run(seed):
    try:
        X = np.random.randn(size,176)
        y = np.random.randn(size)
        print("Crash?")
        lstsq(X, y, rcond=None)
        print("No!")
    except Exception as e:
        print("Error!", e)
        raise
    return None

if __name__ == '__main__':
    with ProcessPoolExecutor(max_workers=8) as executor:
        results = executor.map(run, list(range(2)),)

```

**Actual outcome**

A SIGSEGV is caused when entering `np.linalg.lstsq`. 

```
# Crashdump:

Fatal Python error: Segmentation fault

Current thread 0x00007fff77d02000 (most recent call first):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 2041 in lstsq
  File "test.py", line 32 in run
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/Fatal Python error: prSegmentation faulto

ceCurrent thread 0xs00007fff77d02000 (most recent call first):
  File "s/.LpiybFatal Python error: rSegmentation fault"a

ry/Current thread 0xF, line r00007fff77d02000a153 (most recent call first):
m in   File e"w</oLrlikisb/rsPayrtyt/chForona.mmferwpaomr>ew
o  File rk"//VkeLrsis/biPorynastr/h3yo./n6F/.rlfiarbma/empweyowtrohkrosk/nP/3yt.Vh6o/ns.ieftrresa-impoeanwcsok/rak3g/.eV6se//lrnisuibmo/pnpysy//tl3hi.on6na/3ll.gi6/b//lspiiynttaehl-ognp.3ap.cy6/cko"n, line ac2041gu in ersl/sntusmqp
y  File /"rlteinentsa/tfl.ugtp/uylr"ie, line ns32a/ in lpgr.opcryeu"sn, line s
2041.  File  in plys""t, line /s153Lq in i
_b  File pr"arroyc/eFrstasem_escwtho.rupknysk"/
P, line   File y32"t in /hrLouinnb.
rf  File ararmy"e/w/FoLrriakbm/rVeaewrroysr/ikFosrn/asPm/yeFatal Python error: 3tw.hoSegmentation fault6ro

/knls.if/Current thread 0xbrPa/00007fff77d02000mp (most recent call first):
ey  File wto"rh/koL/nVy3ei.rbts6rih/aoocrnno.synf/cFruarrma/erm3weeo.nw6rto/k/l/rfikVubset//urrPpseyyistto/hhnpoosrnn/o.33cf.er6sasm/.elwpioyb."r/6kp/, line yc153to in hn/<oclVnuie3rsrr.tse6icn/ootcnm/opsfn>/uc
3tu  File .ru"6rr//eeLlsnii/tbpb//rrfpouayctreutysrh/esoF.snpr/3yap".mr, line 6eo175w/ in cos_erispsr.opckteses/-sPpy_ya"tcwhkooa, line rng153k.e in efs<rr/l
ani  File mus"em/twpLcoyiorbmk/rp/a>Vr
ey  File r/"sFi/lrLiainmbaelrwgo/oalnrirskny/s/a3F/l.rPg6ay/.mtlpehiyob"n/, line .p2041wfyor in talrmhkseotss/nqP3y
.t  File 6h"/otcne.osfwnrtoac.mruprkeyrw/"eoV, line ren32rkt in s//rVifueounrnt
ssu  File i/ro3en.ss6"////l3pL.irib6ob//clrpieabysrt/syhp.oy/pntFyh3r".oa, line n6m153/3 in .me_u6wpl/orctroiokcnpserc/sousPcr_yerctsehhsnuotin/nnkfg.
/uf  File ptrru"a/mLeoircwbeeorssa/srrp.kyrp//yoVF"cer, line eras93sms in ie.rowpunoynsr"
/k, line   File 3s153".// in 6PL_/yipltbrihroboac/nrep.syyfs/r_Ftacrhmhaoemunwne3ok.w
6ro/  File rc"ko/nsLc/iuPbryrrktae/hnrVtoye/n/rf.Fsufritraouamnrmeseew/swo3/orp.kr6so//crlePkiys/btsV/he.porpnsyyi."tfohrn, line asom153/en in 3w3<.o.6rl6/il/sictbo/kcpny/otcVmhuepornr>r3se
in.  File ot6n"/s//m/Lu3il.bt6ri/aprlfryuotcuerses/iisbFn//rgpp/yarptmorhecoowecnoserss3ks..s.p6/p/yPcyyo"tn, line ch258u in ro_rne".n, line ft175r in /ba_fopmuroetotwucsroeterssrksa//_ppw
or  File rokecreV"se
/sr  File L.s"ipi/boyLr"nia, line sbr/175ry3 in a./_r6Fpy/rr/loaFicmrbeea/swmpseo_ywwtoohrrokkns3e/.rr6Pk/
ys  File ct/"oP/hynLtcoihunbro.rrnfe.rnfartma/ameferwwuyootr/rkuFk/rr/VeaVesmer/repwssoriiroookcnnssess///sP33.y..pt66yh//"llo, line iibn153/b. in /pfpy_rypatrmhoeotcwnhoe3ors.nks63_//.cVm6heu/ulrmnsutkli
ti  File ip"pr/rLooiccboreeansrssys/iFsnir/gna3/gmp.er6wo/o/lrpciokebpsse//nsp_P.yfypottryhhko".on, line pn393y. in ."fr6, line r/u73an in mm
_e  File lw"aou/rnLckihu/bl
Vrt  File ae"riryp/srLii/ooFcbrernsaassmr/e3w.iyo6nr//kgFsl//ripPabrym/otepchwyeootsnrhs.kofsnr/3aP.m.ype6tyw/h"oco, line ornk93n/.c in Vfruerrruarsmeinno
tn  File /s"fe/u/w3Ltoiu.rbrrekas/r/6Vyp/e/rlFroirscbaie/mospensywst.o/ph3r.yo6k"n/s, line 3/l175P.i in 6yb_/t/pmhpruoyolntct.heiofspnrsra3_om.wc6eoew/rsomkrusekl/tiriVn
epg  File rr/"osp/cirLooincbsere/sa3srs..ys6p/i/yFnl"rgi, line /ba258/p in mpo_eypbwtehoonor_nkf3so/.Pr6ykt/.hmopuotyls"ttr, line ia19ppn in r
_o  File .c_fierns"ai/mtsLe_iiwno_grb/
krp/arrVoycee/rsFssr.  File ipaomen"ws/o/yrL3"ki., line bs6r258/a/ in Prl_yyitb/bhoF/oortnpas.mtferrwaaopmr
key  File wthoorn"k3s/.//6VL/Pemiyrbutrslahirtooinynp.srfo/rc3ea.s/s6Fmi/rnelagwim/obeprw/rkoorc/kesVps/eyPsrty.stphihyooo"nnn, line 3s.93.f/ in 6r3r/aummnue
lw  File to."ir6/p/kLrl/ioiVbcbere/rsapssryiiyton/hngoFs/rn/p3a3o.m.pe66we//nomlr_ikfubsol//rtPpiypytrtkhoho.cnope.nsyf3"s.ri, line 6a73n/ in gmm/_ecounltlaetuxintpcwr.hoo
pc  File rey"ks"//sV, line Liein277rbg in rs/airpo_oynPps/eo/Fnpr3e_a.nmf6
oe/  File rwl"okir/.bkLps/iy/pbP"yry, line ta73thrh in ooy_nn/l3.Fa.fru6rna/acmmmheue
wlwo  File tori"krp/skr/L/oiPVcyeetrshssibiornnaogsrn/y/.p/3frF.rora6acm/meelesiwwsobor/r.kpk/ysVt/ehProysntp3ihy.oo"n6, line ./258fm in rnu_aslbm/toe3iow.po6rtr/oklc/eiVsbes/ripssnytigtor/nhapsp/oo3
np.  File 3e6./n"l_6i/f/Lbom/irubkrl.atpriyyp"p/y, line rFt19orh in cao_me_ensiw3snoi.ir6tn/_gmk_us
l/  File Pt/yitcphorno."fo/rnLatimebcexrewtaso.rrspykiy//n"FgVr, line e/arp223mso in eipw_oeoPnrnosk_p/fes3on/.rPk
6.  File y/p"ltyi/hb"Lo/, line in19pb. in yrf_tar_hriaonymni/e3tFw_.or_6ra
/km  File m/euVwle"rt/siLopiirrbkoornscas/er/Psyy3st/.ihFn6ro/anlg.im/fbepr/woaomrpekewspon/ry_Ptkfyh/ootVrnhek3ro..nsp6.iyof/"nrm, line sau73/ml in 3et_.wil6op/arrlukoni/cbcVeh/esp
ryss  File tii"hno/ogLnn/3sc./o63ni/.tm6ebu/xrlltati.ribpyp/y/rp"Foy, line trc277hae in osmnes3.6/wim_onPurgok/pspe/rnl
oP  File tcy"iet/psLhsrio.obnpcry.eas"fs, line ri105yn/ in rFsgrat/amamecerwowotor
nrk  File t/kVsee/xrPtys.tipohyno"ns, line ./277f3 in .r6a/_lmPiebow/"pp/oyLreiktbn/hr
oVan  File r3"y.//6L/Feirrmbsaurimlaoterniyswp//orr3Fok.cr6se//slPsiyibtn/hgpo/anypm.teofhwprooearnnm3k_e.sf6w/o/Porymrktku.h/lpotVynie".rp, line fs19ri in aomn_res_owi/coner3is.kts6/_iV/_nel
gir  File /bsc/ioponyn"tst//heL3oxi.t6.b/prlynai"3b, line r.223/y in 6p/_/yPFctorohapnomecenuw3rn.ro
6er  File /nk"mts/u//LlfitPbiuyrpttaruhroroyn/ecF.serf/arspamsreiwonocgre/mkcsseso/w.nPoptyryetk"xh/toV.enp, line .ry446fs" in ri, line _ao223mn in aes_w/o3Pr.k6//Vlediobrj/spuipesoytntn_h
pso  File rn/"3o3/c.Le6si/s.lb6irb/_/amcproyuutlnytt/i
Fp  File hrr"ooac/nemL3seis.wi6bnor/gram/kursc/yloP/ntFytirepaxrmtoe.cwpeoysrt"shk, line iso277n/n in Pg.y/ftpr_hraPoomoncepe.wefsnosr
ra.  File mpke"/w/VLoeiryrbs"kri, line /ao105Vrn in eyssr//st3F.airr6ota/n
lms  File ieb//3wp"yo/trLhik.bosr6n/a/3rPly.y/i6tb/hFm/orupnly.attfmhirepoawrnomore3kcsw.e/o6srP/skycit/onhVngc/eouprnrs.rrifeoorncatems/esfw.nopusryt/k"u/3r, line .Ve1056es in /rs/lstpiiraboor/nctps
y/e  File t3h.o6n/"3l/.iL6b//spmsyu.ipltytb"hirpo, line an427rr in o3y_c./se6Fts/rascariomtnnec_wuqourrerukees_m/gaP/nncyattog/hnefotmuneet.xunfttrr_ea.smp/typh"rr, line oe223c in ae_dsPes
ow.  File pop"ery/nk"L
/i  File Vb"er, line /ra446sL in riiy_oba/nrdFajsruras/ytm/3eF.wr6oar/mlkeisw_bo//pPrrpykytoshtc/ohenoPsn.ysf3t_.rhc6aomne.ofw/uronacrtmko
e/n  File wVco"eur/rrLkri/sebVnretar/rsfyiu/oitnFousrrne/ass3/m./pe6r3wo./oc6lr/ikelbsis//bsp/P.pyyytpthtyh"onho3on..n, line 63f446/.r in c6_o/anmdcujluutrsiratepm_nrepowtro/rofckceu/steVusseingr/seps_r/croposcruieooncnsetss
/s  File 3.".p/ysL6".i/, line pbly466ri in "ab, line r/105y in p/ssyFuttrbaahmromitent
3w  File
.o  File r6"k//csLo/inP"bcy/rutLrhaiorbnyr./aFfrrrayammree/wweFoonrrarktkms//e/VfPweuyrotstrhukrosen/si.P/fopyrnrtasohm/co3eenw.s.o6frs/kr./lapiVmybee"r/w, line osp427ri in kyo_/nVsestr/as3ri.t6ot_nhsoq/nu3/3e..l66ui//ecblo_/inmpbca/yunptarhygroteehnmno3ten./n3f6tu./t_6cut/rohcenroscen/uapcrdrur
ore  File crn"eets/n/sLtfi./ubpfrtyuu"atrue, line rrs427ye// in sp_F/rsr_tabaoarcstee_s.qmspue.yewp"uoy, line er"575_k in ms<a/, line lnP446iaygs in tethmcoeonmtp_>_
a  File tdh"r/jnLeu.ifbsrrtaaam_redpwy
or/r  File oF"kcr//eLaVsimsebe_rwrsoacirrokyns/s/F/P3ry.otau6hnm/toel
nwi  File .ob"fr//krLpsaiy/mbtPerhwyaotornhry3ko//n.FV.6ref/arrcmasomienwocournkrsse/r/3weo.nPr6ty/k/tlf/hiVouenr.tsfuirbora/nempssey//3wtp.ohr6or/okln/c3ei.Vsb6es/r/.pcpsoyiny"oct, line nhuso466r/n in 33r..e66ns//tlc/iofbnu/ucbptumyuritrrthee
osn  File n/t3_/b.f6a"u/s/ctLouirbnercsau/rryrpeer.noptcy//"efF, line surt575sau.mrpeyew in s"om/r, line apkp466rs
 in o/cPseyust  File bshm".io/tpnL
yi  File ."bf, line rr427a"am in /er_Lsibtrawyaro/rtrFy_rk/q/FaurVmeaeeumrweeso_wirmookarnsnks/as/Pg/y3e.tPmyh6t/ohlnoen.in.fbtfr/r_apatmyhmerteewhwaooodrnr
k3k  File .//"V6V/e/eLrcrissoibioroannrssy//3/.nF63rc/.aulmr6eir/bwel/noitprb/yk/ftsuh/toPuyrtephsyo/nt_n3hb..aofs6ner/.3apc.myoe6"nw/, line cc575ou in orr<nkrlc/eiuVnsrettrr/ecsfnoiutmot/pnu>fsr
u/et  File 3u"s.r//6eLp/sirlb/oi_rcbbae/arspyssy/e.tF.prhpayoym"ne, line 3w496.o in 6r"m/kac, line spo575/
n in P  File c<y"ulttrhierossetnntc.t.of/mrfpaumt>peuyw
r"o  File , line r"41k/ in /LeViesbr</rsmpaiorrdooyucn/lesFes/rs3>..
p6a/yme"w, line o466rl in kisb//sPpuyybttmhhioonnt.3f.ram
ew  File o6r/kc/"oV/nLeicbrusriroennrst//3f.ua6tr/uylr/ieFsb/r/_abpmaysetewh.ooprnyk3"s., line 6/575/P in cymotanhcpuo
rnr.efntr  File /af"mu/teLuwirobersrk/a_/brVaysee/r.Fpsryi"ao, line mn575e in smw/ao3pr
.k6s//  File lP"i/ybLt/ihpborynat.rhfyo/rnFar3am.mee6ww/oorcrkoksn//cPVyuterhrrosnei.noftrn/asmfe/uw3otr.uk6/r/eVlsie/rbs/_ipobnyast/s3he.o6.n/pl3iy.b"6/, line /pcy575ot in nhco<unl3ri.r6s/etcnocntoc/ufmrurpte>un
rte  File /s"f//puLtriuobrceresas/rspy.r/poFyrc"eas, line ms496.e in pwmyoa"r, line pk496
s in   File /maP"pyt
t  File eh"sotten.s.tpf.yrp"ya, line "m41, line e41 in  in wor<km</omdVoueldreus>l
ieo>n
s/3.6/lib/python3.6/concurrent/futures/_base.py", line 575 in map
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/process.py", line 496 in map
  File "test.py", line 41 in <module>
```

**Expected outcome**

No crash.

**Matplotlib version**
  * Operating system: MacOS 10.11.6 (15G20015)
  * Matplotlib version: Matplotlib v2.2.2 and v3.0.1 (via pip)
  * Matplotlib backend: MacOSX
  * Python version: Python 3.6.5
  * Other libraries: numpy v1.14.2

**Comment by WeatherGod** [comment] 2018-11-06 02:30
I would be curious if this happens with any other default backend like AGG
or Qt5Agg. I don't think the macosx backend has ever been tried for
multiprocessing.

**Comment by WeatherGod** [comment] 2018-11-06 03:30
the `plt.switch_backend()` really isn't as reliable as one would like. It is good for switching between non-interactive backends and is very limited for interactive backends. I suggest changing the backend entry in the matplotlibrc file and seeing if that makes a difference.

Note, I don't think this would be a final solution, just seeing if the problem is limited to just macosx backend or not.

**Comment by normanius** [comment] 2018-11-06 03:32
Meanwhile, I got a step further:

Upgrading to python3.7 and creating a separate [multiprocessing context](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor) fixes the problem for me:

    ctx = None
    if sys.platform == "darwin" and sys.version_info > (3,7):
        ctx = mp.get_context("forkserver") # Works for MacOS and python3.7
        return ProcessPoolExecutor(max_workers=n_processes, mp_context=ctx)
    else:
        return ProcessPoolExecutor(max_workers=n_processes)

Downside: I had to upgrade python. Upside: I had to upgrade python :)

**Comment by normanius** [comment] 2018-11-06 03:49
Not entirely sure, but the problem might be related to the topic discussed under [this link](https://github.com/numpy/numpy/issues/5752#issuecomment-90752612). [Here another link](https://bugs.python.org/issue8713) to a related bugreport: from python3.4 onwards, multiprocessing introduced the support for "forkservers", which offered a workaround for several numpy related issues.

Not entirely clear how this could be linked to matplotlib, though. Is it maybe that every child-process tries to load a separate matplotlib backend, which compete for some resources?

**Comment by timhoffm** [comment] 2020-07-16 19:56
Closing as Matplotlib 3.3.0 now requires at least Python 3.7.

**Closed by timhoffm** 2020-07-16 19:56 UTC

**Comment by QuLogic** [comment] 2020-07-16 20:26
Correction: 3.4 will require Python 3.7 in the future; 3.3 still supports Python 3.6.
