### ISSUE TITLE
fill_between interpolation & nan issue

### ISSUE THREAD

**Issue by Phlya** [matplotlib/matplotlib#11781] opened 2018-07-27 10:58 UTC
The issue was discovered here
https://github.com/deeptools/pyGenomeTracks/pull/37

Basically, when fill_between encounters a NaN in the y values, when interpolate=True it produces a strange output.

This is without interpolation:
```python
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(107).astype(float)
y = np.append(np.zeros((100))+0.01, [0.5, 0.75, 1, np.nan, 1, 0.75, 0.5])

plt.figure(figsize=(20, 5))
plt.fill_between(x, y, interpolate=False)
```

![image](https://user-images.githubusercontent.com/2895034/43317242-079e7dfe-9194-11e8-93db-546bbcd8aea6.png)

If I turn interpolation on (which I wouldn't expect to do anything in this case, since there are not zero crossings), this is what I get:

```python
plt.figure(figsize=(20, 5))
plt.fill_between(x, y, interpolate=True)
```
![image](https://user-images.githubusercontent.com/2895034/43317297-346859f4-9194-11e8-9fb5-0978cf04a9c1.png)

Even if I am misunderstanding something about how interpolation is supposed to work, clearly this is not what it should do...

mpl 2.1.2, python 3.5.2

**Comment by Phlya** [comment] 2018-07-27 13:05
Another example to clarify what's going on
```python
x = np.arange(107).astype(float)
y = np.append(np.zeros((100))+0.01, [2, 0.75, 1, np.nan, 1, 0.75, 0.5])

plt.figure(figsize=(20, 5))
plt.fill_between(x, y, interpolate=True)

```
![image](https://user-images.githubusercontent.com/2895034/43322340-16740940-91a6-11e8-9fb6-0d91553395c0.png)

**Comment by Phlya** [comment] 2018-07-27 15:16
Also possible to make an example where this fails when there actually are negative values and a `where=y>0` condition:
```python
x = np.arange(108).astype(float)
y = np.append(np.zeros((100))+np.random.random(100)-0.05,
              [0.25, 0.5, 0.75, np.nan, 1, 0.75, 0.5, -0.5])

plt.figure(figsize=(20, 5))
plt.fill_between(x, y, interpolate=True, where=y>0)
```

![image](https://user-images.githubusercontent.com/2895034/43329446-49dc73fa-91b8-11e8-8d7b-6b12d1bb5b3a.png)

**Comment by jklymak** [comment] 2018-07-27 15:25
While you are testing, have you tried masking instead of passing NaN?

**Comment by timhoffm** [comment] 2018-07-27 19:42
Part of the problem is that

_axes.py l.5039:
~~~
x, y1, y2 = np.broadcast_arrays(np.atleast_1d(x), y1, y2)
~~~
casts the masked arrays back to regular arrays.

_axes.py l.5063ff:
~~~
                    if len(diff_values) == 2:
                        if np.ma.is_masked(diff_values[1]):
                            return x[im1], y1[im1]
                        elif np.ma.is_masked(diff_values[0]):
                            return x[ind], y1[ind]
~~~
does not have an effect anymore (the invalid values are not masked anymore). It works if you replace `np.ma.is_masked()`by `~np.isfinite()`. No sure if this is the right way to go, though.

**Comment by jklymak** [comment] 2018-07-27 19:51
Good find; seems like thats definitely the issue.  

Marking as "units", because how we normalize arrays after they come to us is tied up in the units discussion.  It'd be nice if every x/y data array input to `axes` methods got the same consistent conversion, and that would certainly include how to handle NaN versus masked....

**Comment by Phlya** [comment] 2018-07-28 11:59
Just in case, masking the NaN value doesn't help.

**Comment by jklymak** [comment] 2019-03-03 05:08
This looks to have been introduced in #7562...  ping @anntzer.

**Comment by anntzer** [comment] 2019-03-03 11:13
I can't repro the issue, neither with mpl2.1.2 (original report) or master...

**Comment by jklymak** [comment] 2019-03-04 18:07
You can't reproduce with `interpolate=True`?

**Comment by anntzer** [comment] 2019-03-04 18:15
This is what I get when running the example copy-pasted from https://github.com/matplotlib/matplotlib/issues/11781#issuecomment-408449975 with master:
![test](https://user-images.githubusercontent.com/1322974/53753565-d9757d80-3eb1-11e9-9e9a-ac3c452aec8e.png)

**Comment by jklymak** [comment] 2019-03-04 18:29
https://github.com/matplotlib/matplotlib/issues/11781#issuecomment-408412648 ?

**Comment by anntzer** [comment] 2019-03-04 18:31
![test](https://user-images.githubusercontent.com/1322974/53754375-16db0a80-3eb4-11e9-81fa-70fdc18ac1df.png)

**Comment by jklymak** [comment] 2019-03-04 18:41
```
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(107).astype(float)
y = np.append(np.zeros((100))+0.01, [0.5, 0.75, 1, np.nan, 1, 0.75, 0.5])

plt.figure()
plt.fill_between(x, y, interpolate=True)
plt.show()
```

![figure_1](https://user-images.githubusercontent.com/1562854/53754859-0140f300-3e6a-11e9-95e7-2c730baad1ef.png)

**Comment by anntzer** [comment] 2019-03-04 18:46
What version of numpy?  I'm on 1.16.2.
I can't think of anything else...

**Comment by jklymak** [comment] 2019-03-04 18:51
1.14.6...  Upgrading to 1.16 fixes.   So, I guess we can close this....

**Closed by jklymak** 2019-03-04 18:51 UTC
Labels: units
