### ISSUE TITLE
Improperly spaced time axis

### ISSUE THREAD

**Issue by jbwhit** [matplotlib/matplotlib#6437] opened 2016-05-17 04:00 UTC
I've put a short reproducible example in this gist: https://gist.github.com/jbwhit/467e154cef029f8098d560924f14612c

The problem can be seen in this screenshot

<img width="917" alt="screenshot 2016-05-16 20 44 57" src="https://cloud.githubusercontent.com/assets/105829/15310858/067f8eda-1ba9-11e6-9b89-38f36e4aaab1.png">

Notice how, for example, November is wider than December (so it isn't merely the number of days in each month). My conda installed setup's details: 

```
Software	Version
Python	2.7.11 64bit [GCC 4.2.1 (Apple Inc. build 5577)]
IPython	4.2.0
OS	Darwin 14.5.0 x86_64 i386 64bit
numpy	1.11.0
matplotlib	1.5.1
pandas	0.17.1
Mon May 16 20:54:59 2016 PDT
```

The code in the gist is as follows: 

```
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
ids = [1,2,3,4]
dates = pd.date_range('20150704', '20160331')
vals = np.random.randn(len(ids)*len(dates))
allids = np.array([np.repeat(i, len(dates)) for i in ids]).ravel()
alldates = np.tile(dates, len(ids))

df = (pd.DataFrame(np.vstack((allids, vals)).T, index=alldates)
    .reset_index().rename(columns={'index':'datetime',0:'unique_id',1:'height'}))

time_group = '1w'
threshold = 0.50

fig, axes = plt.subplots(nrows=4, ncols=1, figsize=(12, 16), sharex=True)

for (i, temp), ax in zip(df.groupby('unique_id'), axes.ravel()):
    (temp.set_index('datetime').height
         .groupby(pd.TimeGrouper(time_group))
         .mean()
         .plot(ax=ax))
```

**Comment by tacaswell** [comment] 2016-05-17 13:05
Can you please move the code directly into this issue and can you reproduce this without using pandas plotting methods?

cc @TomAugspurger 
cc @sinhrks

**Comment by jorisvandenbossche** [comment] 2016-05-17 13:18
More easy to reproduce example:

```
s = pd.Series(np.random.randn(40), index=pd.date_range("2015-07-04", periods=40, freq='1w'))
s.plot()
```

But I suppose this is an issue with the pandas specific formatter (although I don't know how it is with latest matplotlib, tested with 1.5.0), because of using equally spaced sub-ticks

**Comment by TomAugspurger** [comment] 2016-05-17 13:20
Definitely not a matplotlib issue. It's coming down to November having 5 weeks at that frequency

```python
In [34]: s.index.month
Out[34]:
array([ 7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9, 10, 10, 10, 10,
       11, 11, 11, 11, 11, 12, 12, 12, 12,  1,  1,  1,  1,  1,  2,  2,  2,
        2,  3,  3,  3,  3,  4], dtype=int32)
```

**Comment by jorisvandenbossche** [comment] 2016-05-17 13:26
Indeed. The difference is that matplotlib is using ticks with irregular locations (so showing the actual beginning of a month), while pandas is doing something more 'fancy' using the actual weeks as ticks (so regularly spaced), but the ticklabels do not really show that

**Comment by tacaswell** [comment] 2016-05-17 15:04
Closing this on the mpl side.  Please ping me if this should be re-opened.

Could this be related to https://github.com/pydata/pandas/issues/7612 ? If this is going through that code path it could result in ticks getting labeled incorrectly.

**Closed by tacaswell** 2016-05-17 15:04 UTC
