### ISSUE TITLE
Numpy version >= 1.10 dependency issue. 

### ISSUE THREAD

**Issue by Erotemic** [matplotlib/matplotlib#4691] opened 2015-07-14 14:25 UTC
I'm working with a development version of numpy version 1.10.0.dev0-30d755d. 

When trying to install matplotlib I get an error saying 
error: numpy 1.10.0.dev0-30d755d is installed but numpy>=1.6 is required by set(['matplotlib'])

This is because 1.10 is registering as less than 1.6. 

I'm not sure if this is fixed in the head repository, but this causes an issue when using current release on pip. Should be an easy fix. I just wanted to ensure people were aware of it.

**Comment by tacaswell** [comment] 2015-07-14 15:54
I feel this should be a bug against setuptools or pip?

**Comment by WeatherGod** [comment] 2015-07-14 15:56
It might be that your setuptools install needs to be updated to properly
handle the new version numbering system.

On Tue, Jul 14, 2015 at 11:54 AM, Thomas A Caswell <notifications@github.com

**Comment by jenshnielsen** [comment] 2015-07-15 02:51
Normally this kind of thing happens when one uses string comparison to compare versions. However we are using LooseVersion in setupext.py which should work correctly.

**Comment by jenshnielsen** [comment] 2015-07-15 03:21
I cannot reproduce this with numpy 1.10.0.dev0+49617ac and matplotlib master 
Python 3.4.3 setuptools 18.0.1 pip 7.1.0 

looseVersion is from distutils so it should be independent of setuptools/pip version unless setuptools does something funny

**Comment by mdboom** [comment] 2015-07-15 15:06
And additionally, I don't think this error message even comes from matplotlib -- it's coming from pip.

**Comment by tacaswell** [comment] 2015-07-17 02:13
I am now getting this too, but I think I have 1.9.2 installed via conda.

Because I am feeling cranky, I assume this is fallout from merging https://github.com/matplotlib/matplotlib/pull/4668

**Comment by tacaswell** [comment] 2015-07-17 02:15
although, but `python setup.py develop` and `python setup.py install` work for me, `python setup.py test` does not

**Comment by tacaswell** [comment] 2015-07-17 02:46
I had a rouge install of numpy which 'pip remove numpy` fixed.

**Comment by tacaswell** [comment] 2015-08-30 22:56
Closing as it is either a) a local configuration issue or b) bug in upstream tooling.

**Closed by tacaswell** 2015-08-30 22:56 UTC
Labels: needs confirmation
