### ISSUE TITLE
[Bug]: TkAgg matplotlib on PyCharm does not show empty plot

### ISSUE THREAD

**Issue by Jonerbay** [matplotlib/matplotlib#22848] opened 2022-04-14 16:34 UTC
### Bug summary

Plot is not shown. Also, process finishes with exit code -805306369 (0xCFFFFFFF).

### Code for reproduction

```python
import matplotlib.pyplot as plt
import matplotlib

matplotlib.use('tkagg')

fig, ax = plt.subplots(1, 1)
plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/62060069/163433223-919886ea-7fd9-40a9-bddd-3cce0c60e041.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/62060069/163433551-c7cf4656-a2f6-49e4-8312-9cbeb63b4204.png)

### Additional information

none

### Operating system

Windows

### Matplotlib Version

3.5.1

### Matplotlib Backend

TkAgg

### Python version

3.9.7

### Installation

pip

**Comment by timhoffm** [comment] 2022-04-15 10:46
I cannot reproduce this here. Does this work if you run it from the command line / in a script? If so, it's either related to the Python environment you are using within PyCharm, or it's related to PyCharm's plot backend.

**Comment by tacaswell** [comment] 2022-04-15 16:29
> ... exit code -805306369 (0xCFFFFFFF).

Can you post the full trace back.  This looks to me like something is going very wrong with your installation.

It may also be worth fully re-installing your environment.

**Comment by jklymak** [comment] 2022-05-16 12:52
I'll close as presumably fixed by a re-install

**Closed by jklymak** 2022-05-16 12:52 UTC
Labels: status: needs clarification
