### ISSUE TITLE
EPS issues with rc parameters used in seaborn library on Win 8.1

### ISSUE THREAD

**Issue by MMCMA** [matplotlib/matplotlib#6160] opened 2016-03-15 14:13 UTC
- matplotlib 1.5.1, python 3.4.4, win8.1, seaborn 0.7.0
- anaconda installation
- EPS produced while using the `seaborn` package are empty in my win 8.1 environment. I went through `seaborn`'s rcmod.py and figured that setting `"font.sans-serif": ["Arial", "Liberation Sans", "Bitstream Vera Sans", "sans-serif"]` causes the problem, which itself calls `matplotlib.rcParams.update()`. PNG, JPG etc. work without problem. It also runs without problems on my UX system.
- Cannot say it has worked before, as I only recently started to use seaborn

**Comment by mdboom** [comment] 2016-03-15 14:27
Does regular .ps, not .eps work?

**Comment by MMCMA** [comment] 2016-03-15 14:34
No, .ps does not work as well.

**Comment by mdboom** [comment] 2016-03-15 14:38
When you say the file is empty, do you mean it has 0 size, or there is contents but nothing visible.  If the latter, could you post the resulting .ps file?

**Comment by MMCMA** [comment] 2016-03-15 14:42
There is content. Here is the file (could not upload .ps, how zipping is fine)
[figure_1_fail.zip](https://github.com/matplotlib/matplotlib/files/174111/figure_1_fail.zip)

**Comment by jenshnielsen** [comment] 2016-03-15 16:31
I think this is a duplicate of #5862 

Trying to open the file I am seeing:
```
ps2pdf failed:

Error: /undefined in Hebrew
...
```

**Comment by tacaswell** [comment] 2016-03-16 16:35
Closing as a duplicate.

**Closed by tacaswell** 2016-03-16 16:35 UTC
Labels: Duplicate
