### ISSUE TITLE
[Bug]: Minus sign subscript in legend disappears in math mode for font sizes larger than 25 + part of legend symbol does not show for large fonts

### ISSUE THREAD

**Issue by gullbrekken** [matplotlib/matplotlib#21693] opened 2021-11-20 15:08 UTC
### Bug summary

There are two problems here. They might be related so I put them both in the bug report.

1: I want to write $\sigma_{-}^{asdf}$ with asdf as superscript and - as subscript in the legend. When I use font size larger than 25, i.e. from 26 and upwards, the - sign disappears.

2: Also, when I write $\sigma_{-}$ the lowest part of the \sigma symbol does not show in the legend for font sizes larger than 23, i.e. from 24 and upwards.

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.rc('font', size=26) # set font size in plots

fig, ax = plt.subplots(figsize=(12, 12))

x = [1,2,3,4]
y = [1,2,3,4]

ax.plot(x, y, label=r'$\sigma^{asdf}$')
ax.plot(x, y, label=r'$\sigma_{-}$')
ax.plot(x, y, label=r'$\sigma_{-}^{asdf}$')
ax.plot(x, y, label=r'$\sigma_{+}^{asdf}$')
ax.legend()
plt.show()
```

### Actual outcome

![fig](https://user-images.githubusercontent.com/65549701/142730918-6ab0b6e4-3584-4813-85ef-1297741cd579.png)

### Expected outcome

1. Both superscript and - subscript shows for larger font sizes (up to a sensible value).
2. Entire math symbol shows for larger font sizes (up to a sensible value).

### Operating system

Windows 10

### Matplotlib Version

3.4.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.8.12

### Jupyter version

6.4.6

### Installation

conda

**Comment by anntzer** [comment] 2021-11-20 16:12
Thanks for the report.  I think this is a duplicate of #15313 and #17944?

**Closed by anntzer** 2021-11-20 16:12 UTC
