### ISSUE TITLE
Cannot pickle a plot result if use tight_layout method (plot with datetime objects)

### ISSUE THREAD

**Issue by bondarevts** [matplotlib/matplotlib#8273] opened 2017-03-12 02:25 UTC
### Bug report

**Bug summary**

Cannot pickle a plot result if use `tight_layout` method on the plot with datetime objects.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import pickle
from datetime import datetime

plot = plt.plot([datetime(1900, 1, 1), datetime(1900, 1, 2)], [1, 2])
plt.gcf().tight_layout()

dump = pickle.dumps(plot)
pickle.loads(dump)
```

**Actual outcome**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/miniconda3/lib/python3.5/site-packages/matplotlib/dates.py", line 719, in __getattr__
    return getattr(self._rrule, name)

 ...

  File "/Users/user/miniconda3/lib/python3.5/site-packages/matplotlib/dates.py", line 719, in __getattr__
    return getattr(self._rrule, name)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Expected outcome**

I expect to have a copy of the `plot` object.

**Matplotlib version**

matplotlib v.2.0.0 with Python 3.5.2 installed with conda on linux.
```
>>> import sys; print(sys.version)
3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]
```

**Comment by anntzer** [comment] 2017-03-12 03:32
Looks like a duplicate of https://github.com/matplotlib/matplotlib/issues/7852 which is fixed by https://github.com/matplotlib/matplotlib/pull/7854.
ping @tacaswell whether to backport to 2.0.1 or not.

**Comment by dstansby** [comment] 2019-05-04 21:15
Seems to be working fine now.

**Closed by dstansby** 2019-05-04 21:15 UTC
