### ISSUE TITLE
Jupyter magic command  %matplotlib notebook  fails with matplotlib2

### ISSUE THREAD

**Issue by fedhere** [matplotlib/matplotlib#7695] opened 2016-12-28 00:08 UTC
The magic command 
%matplotlib notebook 
fails to create an interactive matplotlib window within the notebook with matplotlib2 beta (matplotlib-2.0.0b4+2344.g7b27a1b) and matplotlib2 rc (2.0.0rc2+2827.gab98852)

Here is an example 
https://github.com/fedhere/notebookTests/blob/master/mplnotebook_test.ipynb
The first cell does not show a plot inline nor it generates a popup window.

Tested on python 2.7.12 and python 3.5.2, ipython  5.1.0, jupyter 4.2.1, Chrome 55, macosx-10.6

Switching back to matplotlib1.5 everything works fine (tested on pyton3.5.2)

**Comment by tacaswell** [comment] 2016-12-28 00:17
I can not reproduce this 😞

**Comment by fedhere** [comment] 2016-12-28 09:52
let me know if I can give more info on my system to help reproduce

**Comment by stonebig** [comment] 2016-12-28 17:34
You may provide the result of "!pip list", so we see the version of jupyter-notebook.

Also your jupyter-core-4.0.6 is from september 2015, you may try to upgrade.

**Comment by efiring** [comment] 2017-01-15 03:15
I'm running into this now, but only in master.  I don't know for sure when it started--maybe today, when I upgraded from Mavericks to Sierra, but it could have been earlier.  I haven't been using  `%matplotlib notebook` for a few weeks until today.  With identical environments it *works* with the Anaconda mpl 1.5.3 package *and* with v2.x, but it *fails* with master.  The Line2D object is printed, but no plot appears.

With v2.x I am at 2.0.0rc2.post76+gbe4b2130c.
Master is 2.0.0rc2.post3008+g9edcb03ee.

```
(test) efiring@manini2:~/work$ conda list ipython
# packages in environment at /Users/efiring/anaconda/envs/test:
#
Using Anaconda Cloud api site https://api.anaconda.org
ipython                   5.1.0                    py35_1
ipython-notebook          4.0.4                    py35_0
ipython-qtconsole         4.0.1                    py35_0
ipython_genutils          0.1.0                    py35_0
(test) efiring@manini2:~/work$ conda list jupyter
# packages in environment at /Users/efiring/anaconda/envs/test:
#
Using Anaconda Cloud api site https://api.anaconda.org
jupyter                   1.0.0                    py35_3
jupyter_client            4.4.0                    py35_0
jupyter_console           5.0.0                    py35_0
jupyter_core              4.2.1                    py35_0
(test) efiring@manini2:~/work$
```

**Comment by tacaswell** [comment] 2017-01-15 03:21
I think one of the solutions here is to get 2.0 out so https://pypi.python.org/pypi/ipympl can fully release and we can start to push people to that instead of `%matplotlib notebook`.  A big advantage of `ipympl` is that it is integrated with the jupyter widgets (rather than our injected js).

**Comment by efiring** [comment] 2017-01-15 03:34
If I am correct that v2.x does not have the problem, then by all means, this should not block 2.0.

**Comment by tacaswell** [comment] 2017-01-15 03:47
oh, the OP is against master!  

Neither ab98852fa3b760e87208de53d058f82c3bf934bc nor  7b27a1b is included in 2.0

**Comment by NelleV** [comment] 2017-01-15 04:05
I removed the release critical tag, but it is probably be release critical for 2.1…

**Comment by yoavram** [comment] 2017-03-27 15:07
I do have this problem on OSX with miniconda: python 3.6.0, numpy 1.12.0, mpl 2.0.0, python 5.2.2, ipykernel 4.5.2, notebook 4.4.1. 
Using `%matplotlib notebook` and then creating plots doesn't work - figures just don't appear, but theres a big white spaces where they should appear. No errors in the notebook; jupyter server console shows a bunch of messages like:
```
[IPKernelApp] WARNING | No such comm: b19dec1f04e67164bf57db3a207b607e
```
`%matplotlib inline` works fine; downgrading to mpl 1.5 fixes the problem.

**Comment by jni** [comment] 2017-05-02 10:46
`%matplotlib notebook` used to work for me but current conda (defaults) version doesn't.

macOS 10.12.4, Chrome 58.0.3029.81, Jupyter 4.3.0, matplotlib 2.0.0

**Comment by tacaswell** [comment] 2017-05-02 12:44
attn @Carreau are there any changes to the coms we need to know about?

**Comment by jni** [comment] 2017-05-02 14:10
Incidentally this very well could be a notebook issue, because plotly offline is also not working for me...

**Comment by jenshnielsen** [comment] 2017-05-02 14:29
For what it's worth the notebook backend works for me with all the latest versions of notebook and related jupyter packages (For matplotlib 2.0, master branch is a completely different case which is what this bug was originally about) 

Could this be related to browser plugings, no script of some such thing?

**Comment by Carreau** [comment] 2017-05-03 04:32
> attn @Carreau are there any changes to the coms we need to know about?

Not that I know of, but I haven't touched comms in a long time. @SylvainCorlay ?

It might be a notebook thing (we had other JS issues, like impossibility to type `]` on french keyboard), but so far we've lacked the intersection of time/reproductible/core-dev sweet spot to narrow that down.

**Comment by SylvainCorlay** [comment] 2017-05-03 04:37
I am not aware of any change wrt comms lately. ipympl and the notebook backend are functional with notebook 5 and matplotlib 2.

**Comment by dac09** [comment] 2017-07-21 02:09
I've just started playing around with jupyter and matplotlib, noticed the same bug with the official jupyter-datascience docker container on a python 3 notebook. The docker image might be helpful in reproducing.

On the bright side:
`docker exec -ti {containerId} pip3 install --upgrade ipython pandas`
Upgrading ipython and pandas inside the container seems to have fixed the issue for me. HTH!

**Comment by tacaswell** [comment] 2017-07-21 10:39
The issue here on master is the nbagg is written against ipywidgets 4 (v7 is on the way!).

**Comment by yoavram** [comment] 2017-07-24 09:16
@tacaswell so when nbagg is updated for ipywidgets v7 this issue will be closed? Is there a PR for that? Or are we waiting for ipympl?

**Comment by SylvainCorlay** [comment] 2017-07-24 09:17
The goal of ipympl was to have a faster release cycle than matplotlib to follow that of Jupyter and Jupyter interactive widgets.

The current ipympl is functional with ipywidgets 6.0

**Comment by yoavram** [comment] 2017-07-24 11:04
OK, sounds great, but I'm still not what that means for the current issue..?

**Comment by tacaswell** [comment] 2017-07-24 13:34
@yoavram Yes, this will be fixed when it is updated to a current version of ipywidegts, no there is not a PR for that yet.

I think the plan should be to get `nbagg` up to v6 or v7 of ipywidegts and then mark it as deprecated to point people at ipympl.

**Comment by yoavram** [comment] 2017-07-24 16:46
Oh so ipympl will replace nbagg?
Thanks

**Comment by tacaswell** [comment] 2017-07-25 21:26
@yoavram Yes.  The widgets eco system is spinning way faster than Matplotlib's release cycle can keep up with.  It is better for that to release on it's own cycle.

**Comment by efiring** [comment] 2017-07-27 01:50
I think this might be the single most release-critical thing for 2.1.  There are plenty of notebooks floating around that start with
```python
%matplotlib notebook
```
Breaking all of them with a new mpl release is not acceptable.  I have no idea what would need to be done to prevent, that, though.

**Comment by efiring** [comment] 2017-07-27 02:32
See also https://github.com/ipython/ipython/issues/10717.
Summary:
- `%matplotlib notebook` yields no plot
- `import ipympl` works, but requires `show()` or `ion()`
- Freezing a plot so that it can be saved or included in an export to html, for example, requires clicking the right-most widget icon, after which one will want to click the x to the left of the title bar.  If you click the x first, the plot goes away completely.  If you click the export icon twice, you get two renderings.
- And then there is the validation bug that I report in the ipython issue.

**Closed** 2017-08-14 19:44 UTC
Labels: confirmed bug, Release critical, third-party integration
