### ISSUE TITLE
Unexpected change in behavior in plt.subplot

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#19432] opened 2021-02-02 13:06 UTC
### Bug report

**Bug summary**

#19153 introduced some changes that had (I think) unintended consequences when passing custom kwargs to projections

**Code for reproduction**

Prior to #19153, the following code returned ``False``, that is, two different axes were created:

```python
from astropy.wcs import WCS
import matplotlib.pyplot as plt

wcs1 = WCS(naxis=3)
wcs1.wcs.ctype = ['x', 'y', 'z']

ax1 = plt.subplot(1, 1, 1, projection=wcs1, slices=('x', 'y', 1))

wcs2 = WCS(naxis=3)
wcs2.wcs.ctype = ['a', 'b', 'c']

ax2 = plt.subplot(1, 1, 1, projection=wcs2, slices=('x', 2, 'y'))

print(ax1 is ax2)
```

No deprecation warning or future warning was raised in this case.

Following #19153, this silently ignores the projection and slices in the second call and the print statement returns ``True``.

I don't think #19153 was intended to start making ``plt.subplot`` return the same axes in some cases, rather I thought the goal of that PR was to remove re-use of axes in certain circumstances, so I think this is a regression/bug

**Actual outcome**

``ax1`` and ``ax2`` are the same

**Expected outcome**

``ax1`` and ``ax2`` should be different

**Comment by lpsinger** [comment] 2021-02-02 13:42
This is the expected behavior. From https://matplotlib.org/devdocs/users/next_whats_new/axes_kwargs_collision.html:

> The behavior of the functions to create new axes (pyplot.axes, pyplot.subplot, figure.Figure.add_axes, figure.Figure.add_subplot) has changed. In the past, these functions would detect if you were attempting to create Axes with the same keyword arguments as already-existing axes in the current figure, and if so, they would return the existing Axes. Now, these functions will always create new Axes. A special exception is pyplot.subplot, which will reuse any existing subplot with a matching subplot spec. However, if there is a subplot with a matching subplot spec, then that subplot will be returned, even if the keyword arguments with which it was created differ.

**Comment by dstansby** [comment] 2021-02-02 13:47
It seems like even if this is new expected behaviour, we shouldn't be making behaviour changes without a suitable deprecation period, and it sounds like there wasn't any deprecation for the example above.

So, for 3.4 I think we should
- Re-instate the previous behaviour for the case above (same subplot spec, different projections)
- Add a deprecation warning saying that the behaviour will change in the future

**Comment by astrofrog** [comment] 2021-02-02 13:47
@lpsinger that is a pretty radical change that might break things for a lot of astropy users, and I don't think something like this can be done without a deprecation warning of some kind (the example I showed above did not show any deprecation warning). This seems like a step backwards - what is the motivation for breaking this behavior? I'm completely on board with no longer automatically returning the same axes in many cases but why change things for the example above from not returning the same to returning the same?

**Comment by astrofrog** [comment] 2021-02-02 13:48
Just out of curiosity, what is the motivation for breaking cases like the example I showed?

**Comment by lpsinger** [comment] 2021-02-02 13:51
> Just out of curiosity, what is the motivation for breaking cases like the example I showed? Why would a user ever want the same axes object if the projection is different?

For the motivation, see #18832.

**Comment by dstansby** [comment] 2021-02-02 13:52
Indeed, our docs even said that if you had unique args and kwargs you would get a new subplot, so this is definitely a bug that needs fixing before 3.4 is released:
```
If the figure already has a subplot with key (*args*,
*kwargs*) then it will simply make that subplot current and
return it.  This behavior is deprecated. Meanwhile, if you do
not want this behavior (i.e., you want to force the creation of a
new subplot), you must use a unique set of args and kwargs.
```

**Comment by astrofrog** [comment] 2021-02-02 13:56
@lpsinger - but this just refers to the case where kwargs are the same:

*In Matplotlib 2.1, the behavior of reusing existing axes when created with the same arguments was deprecated (see #9037). The request is to finally remove this behavior.*

I don't see any good reason why in my example above ``ax1`` and ``ax2`` should be the same since the kwargs are clearly different?

Again, this is a major change that is going to affect a lot of users - think about users who loop over files and in the loop call ``plt.subplot`` with different projections each time - now they will silently get the same axes over and over with the projection from the first file.

**Comment by lpsinger** [comment] 2021-02-02 14:00
> Indeed, our docs even said that if you had unique args and kwargs you would get a new subplot, so this is definitely a bug that needs fixing before 3.4 is released:
> 
> ```
> If the figure already has a subplot with key (*args*,
> *kwargs*) then it will simply make that subplot current and
> return it.  This behavior is deprecated. Meanwhile, if you do
> not want this behavior (i.e., you want to force the creation of a
> new subplot), you must use a unique set of args and kwargs.
> ```

It was an oversight that this paragraph should have been removed in #19153. See #19433.

**Comment by astrofrog** [comment] 2021-02-02 14:05
@lpsinger - could you clarify though, why would a user ever want the same axes if the projection and kwargs are different?

**Comment by lpsinger** [comment] 2021-02-02 14:14
> @lpsinger - could you clarify though, why would a user ever want the same axes if the projection and kwargs are different?

As I wrote in #18832:

> My immediate motivation is that I have a [collection of projection classes](https://git.ligo.org/lscsoft/ligo.skymap/-/blob/master/ligo/skymap/plot/allsky.py) that take as a keyword argument an instance of [astropy.coordinates.SkyCoord](https://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord), which [as of Astropy 4.1 are no longer hashable](https://docs.astropy.org/en/stable/whatsnew/4.1.html#whatsnew-4-1-inplace-skycoord) (see also astropy/astropy#9857). This unexpectedly broke my code because I had not realized that projection keyword arguments had to be hashable.

While researching why Matplotlib required projection keyword arguments to be hashable, I discovered that it was in order to support axes reuse. That was _my_ rationale for removing axes reuse, except (as was suggested by @tacaswell in https://github.com/matplotlib/matplotlib/pull/18978#issuecomment-733239090) the one special case of `plt.subplot` when reusing existing subplots with the same subplot spec.

**Comment by astrofrog** [comment] 2021-02-02 14:16
@lpsinger - I can see why removing axes reuse makes sense, but I don't see the motivation for *introducing* new axes reuse behavior where it did not previously exist?

**Comment by astrofrog** [comment] 2021-02-02 14:21
My reading of #18978 was that @tacaswell did not want to break certain behaviors (e.g. calling ``plt.subplot(222)`` twice should return the same object) but I don't think it was his intent to mean that examples such as the one here should now be changed to return the same axes? (@tacaswell can you comment on this?)

**Comment by astrofrog** [comment] 2021-02-02 14:46
To be clear, if people want to keep this new behavior, I think that:

* It should be subject to a deprecation phase
* After the deprecation phase a warning should always be emitted when the second axes is created (as suggested by @jklymak in https://github.com/matplotlib/matplotlib/pull/18978#issuecomment-733240967)

**Comment by jklymak** [comment] 2021-02-02 15:37
@astrofrog, thanks a lot for pre-testing our release!  This would have been a lot more painful after 3.4 went out....

Just to recap:
1. we wanted to get rid of the hash table because its a huge PITA and fragile
2. we need to preserve:
```python
ax0 = plt.subplot(2, 1, 1)
plt.subplot(2, 1, 2)
ax1 = subplot(2, 1, 1)
assert ax0 == ax1
```
because there is no pyplot way to get the axes back if you lost track of it (i.e. if you didn't call `ax0 = ...`)

3. we thought the use case in the OP would be pretty rare, or in pure matplotlib:

```python
ax0 = plt.subplot(2, 1, 1, polar=True)
plt.subplot(2, 1, 2)
ax1 = subplot(2, 1, 1, polar=False)   #  Warns about ignored kwargs
assert ax0 == ax1    # pass
ax2 = subplot(2, 1, 1, polar=True)   #  Warns about ignored kwargs
assert ax0 == ax2    # pass
```
Who slathers axes on top of each other using pure pyplot?  

However, if this truly breaks astropy we probably need to reconsider its rarity.  I'm not at all clear how we can fix this and still move ahead with removing the hash table.  I still think there is some validity to the argument that users should not be using pure pyplot in instances like this, but if it is a common pattern we need to work out a deprecation....

**Comment by lpsinger** [comment] 2021-02-02 16:19
@astrofrog, I think that this old behavior is only used in the astropy _test suite_ and it should be fairly simple to update it.

As for introducing a deprecation step, then I would need to also write a patch to make the axes reuse work with unhashable kwargs, which would also be a pain.

**Comment by dstansby** [comment] 2021-02-02 16:28
I've opened https://github.com/matplotlib/matplotlib/pull/19436 so at least there's a warning when kwargs are ignored (which I think was missed in the original PR?)

I had a quick look at introducing a deprecation step, and it seemed like a deep rabbit hole. But then again as it stands, we would be making a behaviour change to `plt.subplot` that was users were never warned about, and in fact since 2.1 we have had a deprecation warning saying that we were going to do the opposite (always creating a new `Axes` instead of returning an existing one), which I think makes having a deprecation period for the new desired behaviour (not creating a new `Axes` when the subplotspec is the same) even more compelling.

**Comment by jklymak** [comment] 2021-02-02 16:35
As we discussed on the call, we thought it would be rare enough that users would be meaning to put two axes on top of each other using pyplot that it was OK to break.  it was hard to come up with a situation where that would be a useful thing to do.  So... it *would* be nice to know if astropy actually wants its users to do this, or if it was just a testing convenience.  What was the plot above meant to show?

**Comment by tacaswell** [comment] 2021-02-02 17:00
Can we hold onto the kwargs and check for equality?  That seems like a lower bar to ask things to pass.  The behavior could then be:

 - if no axes found from args -> create new axes with args and kwargs
 - if axes found from args:
    - if kwargs match saved kwargs do nothing and return
    - if kwargs do not match saved kwargs .....

Where the .. could be :
  1. warn, return the first axes it founds that matches the args
  2. warn, create a new axes with args + kwargs
  3. create the new axes and return

I think I see a path to implementing this without too much trouble (and just one new private attribute).

**Comment by jklymak** [comment] 2021-02-02 17:06
> Can we hold onto the kwargs and check for equality? 

I was thinking about the same potential solution; I'm sure its doable.  Holding onto kwargs is in general a useful thing to do anyway.  I've started to do that for colorbar.  So I'd be :+1: on doing this if its not super complicated.  

I think it is reasonable to make different kwargs always return a new axes.  The only reason the original change didn't do this was because we didn't want to keep track of the hash anymore.  

However, this would still undo a lot of the simplification.

**Comment by astrofrog** [comment] 2021-02-02 17:37
I don't think I really expect users to deliberately plot multiple axes on top of each other, but the old Matplotlib behavior in a case like this:

```python
from astropy.wcs import WCS
import matplotlib.pyplot as plt

wcs1 = WCS(naxis=3)
wcs1.wcs.ctype = ['x', 'y', 'z']

ax1 = plt.subplot(1, 1, 1, projection=wcs1, slices=('x', 'y', 1))
ax1.plot([0.2, 0.3], [0.2, 0.3])

wcs2 = WCS(naxis=3)
wcs2.wcs.ctype = ['a', 'b', 'c']

ax2 = plt.subplot(1, 1, 1, projection=wcs2, slices=('x', 2, 'y'))
ax2.plot([0.5, 0.6], [0.5, 0.6])

plt.savefig('result.png')
```

was to show the last one rather than the two superimposed:

![result](https://user-images.githubusercontent.com/314716/106639242-ae53a700-657c-11eb-924e-53a823159f0e.png)

(this is with 3.2.2). So user code relying on this might not be as rare as you think. With Matplotlib dev the result is:

![test](https://user-images.githubusercontent.com/314716/106639233-aac02000-657c-11eb-8b36-7c7ac5295217.png)

Given the old behavior, one can easily envisage a user doing something like:

```
for filename in filenames:
    # open some files and extract some projection information as wcs
    ax = plt.subplot(1, 1, 1, projection=wcs) 
```

and this will now use the same axes for all items in the loop silently giving a very different result. Of course users should close the figure at the end of the loop but we all know that doesn't always happen.

One can get back the old behavior by calling ``plt.close`` before the second ``plt.subplot`` call.

To be clear, at the end of the day I don't mind if you choose to keep the new behavior, but it's crucial that in the second subplot call a warning is raised saying that it will essentially have no effect and that if they want it to have an effect they need to close the previous figure or something similar.

**Comment by tacaswell** [comment] 2021-02-02 18:07
A detail that I missed in the original discussion is that there is code at the bottom of `plt.subplot` that detects any fully overlapping axes, so doing

```
ax1 = plt.subplot(1, 1, 1, polar=False)
ax2 = plt.subplot(1, 1, 1, polar=True)
```

would not result in over-lapping Axes, but remove ax1 from the Figure.  This makes a minimal fix for this much simpler (as we will not have multiple axes added via `plt.subplot` at the same gridspec survive.

**Comment by lpsinger** [comment] 2021-02-02 18:09
> A detail that I missed in the original discussion is that there is code at the bottom of `plt.subplot` that detects any fully overlapping axes, so doing
> 
> ```
> ax1 = plt.subplot(1, 1, 1, polar=False)
> ax2 = plt.subplot(1, 1, 1, polar=True)
> ```
> 
> would not result in over-lapping Axes, but remove ax1 from the Figure. This makes a minimal fix for this much simpler (as we will not have multiple axes added via `plt.subplot` at the same gridspec survive.

That's right, that behavior is (supposed to be) preserved. Is it?

**Comment by jklymak** [comment] 2021-02-02 18:12
On master

```python
import matplotlib.pyplot as plt

ax1 = plt.subplot(1, 1, 1)
ax2 = plt.subplot(1, 1, 1, projection='polar')

print(ax1 == ax2)
plt.show()
```

returns True and doesn't add a polar axes.

**Comment by tacaswell** [comment] 2021-02-02 18:16
> That's right, that behavior is (supposed to be) preserved. Is it?

It is, but I was going down the path of sorting out how to resolve "we have N axes at this location, we need to see if _any_ of them match .." so the diff is even smaller than I anticipated.

**Comment by tacaswell** [comment] 2021-02-02 18:22
See https://github.com/matplotlib/matplotlib/pull/19438 which I think gets everything we want:

 - no hashing of kwargs
 - multiple calls with matching (and no) kwargs return the same Axes object
 - multiple call with different kwargs create new axes (and continue to implicitly delete fully over-lapped axes)

at the cost of carry around one more dictionary as private state on the Axes.

**Comment by lpsinger** [comment] 2021-02-02 18:26
> See #19438 which I think gets everything we want:
> 
> * no hashing of kwargs
> * multiple calls with matching (and no) kwargs return the same Axes object
> * multiple call with different kwargs create new axes (and continue to implicitly delete fully over-lapped axes)
> 
> at the cost of carry around one more dictionary as private state on the Axes.

Nice! That patch is delightfully simple.

**Comment by astrofrog** [comment] 2021-02-02 18:27
Thanks everyone for converging on a solution and @tacaswell for the PR! :)

**Closed** 2021-02-19 00:59 UTC
Labels: Release critical
