### ISSUE TITLE
Calling close() on a figure doesn't seem to close it

### ISSUE THREAD

**Issue by mdklatt** [matplotlib/matplotlib#8560] opened 2017-05-02 23:08 UTC
### Bug report

**Bug summary**

Calling `pyplot.close()` on a figure created with `pyplot.subplots()` doesn't seem to actually close the figure. After being closed the figure can still be saved (and is not blank), and this seems to cause a memory leak in long-running processes.

**Code for reproduction**

```python
from resource import getrusage
from resource import RUSAGE_SELF

from matplotlib import use as use_backend
use_backend("Agg")
from matplotlib import pyplot
from numpy.random import randn


def plot():
    """ A simple histogram plot.
    
    """
    fig, axes = pyplot.subplots(1, 1)
    axes.hist(randn(10000))
    pyplot.close(fig)  # should free all resources, doesn't?
    fig.savefig("hist.png")  # should be blank, isn't
    return


if __name__ == "__main__":
    print("before: {:d} kB".format(getrusage(RUSAGE_SELF).ru_maxrss))
    plot()
    print("after: {:d} kB".format(getrusage(RUSAGE_SELF).ru_maxrss))

```

**Actual outcome**

![image](https://cloud.githubusercontent.com/assets/2087508/25642690/114ac984-2f61-11e7-8679-6e1061b51dd2.png)

```
before: 40920 kB
after: 45632 kB
```

**Expected outcome**

The image should be blank because it was saved after the figure was supposedly closed. Ending memory usage should be the same as beginning memory usage because all resources should have been released upon exit from the `plot()` function.

**Matplotlib version**

  * Operating System:
Linux-3.10.0-514.el7.x86_64-x86_64-with-centos-7.3.1611-Core (running as a VirtualBox VM on OS X)
  * Matplotlib Version: 
2.0.0

  * Python Version:
Python 2.7.5

`matplotlib` was Installed via `pip` running in a `virtualenv` environment.

**Comment by tacaswell** [comment] 2017-05-03 03:11
This is the expected behavior.  `plt.close` removes the figure from it's internal state and (if there is a gui) closes the window.  However it does not clear the figure and if you are still holding a reference to the `Figure` object (and it holds references to all of it's children) so it is not garbage collected. 

If you want to clear a figure use `fig.gcf()` if you want to completely get rid of a figure, drop all references to it (as with any other python object) and gc will (eventually) take care of it.  There are a lot of circular references so they may be 'stickier' than they should be.  To hurry it up try adding

```python
import gc
gc.collect(2)
```

Closing as not a bug.  If you think this _is_ a bug, please ping to have this re-opened.  The mailing list (matplotlib-users@python.org) is a better venue for further discussion about this.

**Closed by tacaswell** 2017-05-03 03:11 UTC

**Comment by yanpanlau** [comment] 2018-05-12 08:42
Yes I suffer the same problem where the fig.gcf() does not exist and it keep memory leak inside a for loop.

**Comment by Akshaypatil15** [comment] 2018-06-14 10:53
Solution Found!!!
Late post, but maybe helpful for someone.
Basically, matplotlib BLOCK session until we close the figure. To avoid that we need to change by default block value,
   `plt.show(block=False)
    time.sleep(5)
    plt.close('all')`

**Comment by Akshaypatil15** [comment] 2018-06-14 10:55
Solution Found!!!
Late post, but maybe helpful for someone.
Basically, matplotlib BLOCK session until we close the figure. To avoid that we need to change by default block value,

`plt.show(block=False)`
`time.sleep(5)`
`plt.close('all')`

**Comment by hsuhonghai** [comment] 2018-06-16 09:19
Good  solution! 
better way
