### ISSUE TITLE
Spurious artefact on prime meridian when pcolormesh plots irregular gridded polar data in mpl 3.3.0

### ISSUE THREAD

**Issue by robbiemallett** [matplotlib/matplotlib#18489] opened 2020-09-15 10:09 UTC
Matplotlib pcolormesh introduces spurious features along the prime meridian when deployed with a PolarStereo projection.

**Code for reproduction**

```python
from netCDF4 import Dataset
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

# Double check the versions

import cartopy
import matplotlib
print(matplotlib.__version__)
print(cartopy.__version__)

# Import the data

dat = Dataset('my_data.nc')
# my_data.nc is an ice motion vector file available (after logging in) here: https://nsidc.org/data/nsidc-0116
# The particular file I've used is icemotion_daily_nh_25km_20140101_20141231_v4.1.nc
# I've attached a stripped-down version to this report as a zip file, just unzip and name it my_data.nc
# It's a netcdf with an irregular grid (EASE equal area) with 2d arrays of lons, lats and data vals.

lons = dat['longitude']
lats = dat['latitude']
data = dat['u']

# Make the plot

fig = plt.figure(figsize=(6,6))    
ax = plt.axes(projection=ccrs.NorthPolarStereo())
ax.pcolormesh(lons, lats, data ,transform=ccrs.PlateCarree())
ax.set_extent([-180, 180, 90, 65], ccrs.PlateCarree())
ax.coastlines()
plt.show()
```

**Actual outcome**

This is the output with mpl 3.3.0 and cartopy 0.18

![image](https://user-images.githubusercontent.com/47150532/93194522-175a8f80-f740-11ea-942c-53545a824014.png)

**Expected outcome**

This is the expected output, generated with mpl 3.2.2 and cartopy 0.18

![image](https://user-images.githubusercontent.com/47150532/93194845-71f3eb80-f740-11ea-8501-e68097c5ba88.png)

Installed with conda. To generate the correct plot, I had a downgrade my matplotlib version. To do this I did conda remove matplotlib, and then conda install -c conda-forge matplotlib=3.1.3, and then conda install cartopy=0.18

One notable feature of this bug is that it is not visible when the bounding latitude is at or below 55 degrees. Here are two plots I've made (where the plotted data is just the latitude coord with bounding lats of 55 and 56 degrees.

![image](https://user-images.githubusercontent.com/47150532/93195093-bd0dfe80-f740-11ea-905d-e97eaa3b09cd.png)

I'm aware that this problem is common when deploying pcolormesh with a regular grid, where each of the rows of the 2d data can be characterised by a single lat, and each col by a single lon (i.e. data points are regularly spaced in lon/lat space, this is also known as raster data). The solution to this is to insert a cyclic point at the meridian, in cartopy this is achieved with cartopy.util.add_cyclic_point. This solution is characterised [here](https://stackoverflow.com/questions/56348136/white-line-in-contour-plot-in-cartopy-on-center-longitude). This cannot be done in for an irregular grid, such as the [EASE grid](https://nsidc.org/data/ease), but this didn't cause a problem until mpl 3.3.0. This is not a corner case however, as irregular grids are the norm for polar research (for reasons involving the infinitessimal area of regular lon/lat grid cells near the pole). 

Data file for reproduction:
[my_data.zip](https://github.com/matplotlib/matplotlib/files/5224106/my_data.zip)

**Comment by jklymak** [comment] 2020-09-15 14:04
This is a duplicate of https://github.com/SciTools/cartopy/issues/1638 https://github.com/matplotlib/matplotlib/issues/18317

The get the old behaviour please do `ax.pcolormesh(lons, lats, data[:-1, :-1], transform=ccrs.PlateCarree())` which is exactly what the old default did.

**Closed by jklymak** 2020-09-15 14:04 UTC
