### ISSUE TITLE
Annotation bbox clipping incorrect for `boxstyle='round'` Matplotlib >= 1.4.0

### ISSUE THREAD

**Issue by joferkington** [matplotlib/matplotlib#4140] opened 2015-02-21 17:20 UTC
Annotations using a bbox boxstyle of "round" have different (incorrect?) clipping behavior compared to a square boxstyle.

As an example, note that with matplotlib 1.4.0, the connector arrow extends inside the round box, while it is clipped for the square boxstyle.  With earlier versions, both have the same clipping behavior.

```
import matplotlib.pyplot as plt
import matplotlib

def main():
    fig, ax = plt.subplots()
    ax.set(title='Matplotlib {}'.format(matplotlib.__version__))
    annotate(ax, 'Round')
    annotate(ax, 'Square')
    plt.show()

def annotate(ax, text):
    bbox = dict(fc='none')
    x, y = 0.1, 0.1

    if text == 'Round':
        bbox['boxstyle'] = 'round'
        y = 0.5

    ax.annotate(text, xy=(x, y), xytext=(50, 50), size=20,
                xycoords='data', textcoords='offset points',
                bbox=bbox,  arrowprops=dict(arrowstyle='->'))

main()
```

![clip_mpl1 3](https://cloud.githubusercontent.com/assets/906803/6315056/18b7660a-b9bb-11e4-9f99-3736628f8f02.png)

![clip_mpl1 4 0](https://cloud.githubusercontent.com/assets/906803/6315057/211d3d06-b9bb-11e4-9265-fd14e15f11e9.png)

The problem persists up to and including the current HEAD, but newer versions also have the issue described in https://github.com/matplotlib/matplotlib/issues/4139  The two issues don't appear to be directly related.

**Comment by tacaswell** [comment] 2015-02-21 19:26
This is related to/duplicate of #4012.  There is some subtle 'race' conditions with the fancy bounding boxes + fancy arrows.  The root cause of this is the re-factoring of annotation for 1.4 (which I did).

I sunk a day into this leading up to 1.4.3 and did not make much headway.

**Closed** 2015-07-22 03:50 UTC
