### ISSUE TITLE
Figure rotation using Axes.text () with eps backend

### ISSUE THREAD

**Issue by mauriceleutenegger** [matplotlib/matplotlib#10290] opened 2018-01-22 19:53 UTC
### Bug report

**Bug summary**

When I use the Axes.text () method with rotation='vertical', and call it a sufficient number of times (greater than 7 times in the example below), the resulting figure is rotated by 90 degrees if saved to an eps file. The plot is normal (unrotated) if any of the following are satisfied: Axes.text() is called less than 7 times; or the plot is saved directly to a png file; or the calls to Axes.text() do not specify rotation='vertical'.

**Code for reproduction**

```python

import matplotlib.pyplot as pl

f = pl.figure (figsize=(7,5))
ax = f.add_axes ([0.15,0.15,0.8,0.8])
ax.set_ylim (0., 1.)
ax.set_xlim (0., 1.)

ntext = 8 # this is the minimum number of calls to get rotation
ytext = 0.5
for i in range (ntext) :
    xtext = (xmax / ntext) * i
    n = 'test{}'.format (i)
    ax.text (xtext, ytext, n, rotation='vertical')

f.savefig ('test.eps')
```

**Actual outcome**

The gzipped eps file is attached, as is a png created from the eps using ImageMagick convert. 
[test.eps.gz](https://github.com/matplotlib/matplotlib/files/1653335/test.eps.gz)
![test](https://user-images.githubusercontent.com/8868808/35240729-66d78346-ff82-11e7-97bb-cac1fe81ec48.png)

**Expected outcome**

An unrotated plot, regardless of the number of times Axes.text() is called.

**Matplotlib version**

  * Operating system: OS X 10.13.2
  * Matplotlib version:  anaconda                2.1.1            py27hb768455_0
  * Matplotlib backend : Qt5Agg
  * Python version: Python 2.7.14 |Anaconda custom (64-bit)| (default, Dec  7 2017, 11:07:58)

**Comment by jklymak** [comment] 2018-01-22 20:00
I can't reproduce on master or 2.1.1.  Do you have something funky in your rcparams?

**Comment by mauriceleutenegger** [comment] 2018-01-22 20:10
In my matplotlibrc, I have
ps.usedistiller    : xpdf
ps.distiller.res  : 6000      # dpi

I found that by commenting out usedistiller, I can obtain the expected behavior.

**Comment by jklymak** [comment] 2018-01-22 20:35
OK, I'll close, as I don't think this is an MPL issue.  Feel free to re-open if you think we are doing something incorrect on our end.

**Comment by mauriceleutenegger** [comment] 2018-01-22 21:23
Well, the behavior is still unexpected when the ps distiller is xpdf. Should I file the bug report with xpdf?

**Comment by jklymak** [comment] 2018-01-22 22:49
Well, its `ps2pdf` that seems to have the bug.  If I save the ps file and run it through ps2pdf then it comes out rotated by 90 degrees.  

We can keep this open, but kind of hard to see that its our fault directly...

[boo.ps.zip](https://github.com/matplotlib/matplotlib/files/1653849/boo.ps.zip)

[boo.pdf](https://github.com/matplotlib/matplotlib/files/1653848/boo.pdf)

**Comment by jklymak** [comment] 2018-01-22 22:53
ps2pdf has `"-dAutoRotatePages=false",` option.  I guess it looks at your postscript file, decides enough characters are rotated, and rotates it for you.  

Not sure if this is a "won't fix" or if we just put the fix in to turn off autorotate...

**Comment by mauriceleutenegger** [comment] 2018-01-22 23:06
I agree, this is really an edge case. I don't have any objection to making this one a "won't fix".

**Comment by jklymak** [comment] 2018-01-22 23:08
I’d fix, but just not sure if someone is depending on this auto rotation.   Is it new in GS?

**Comment by mauriceleutenegger** [comment] 2018-01-22 23:11
The top google hit for "ghostscript autorotatepages" is an anti-autorotate rant from 2009. Not new, and we're not the first victims.

**Comment by anntzer** [comment] 2018-01-22 23:39
I think we should pass the option.

**Comment by jklymak** [comment] 2018-01-22 23:51
I think so as well...

**Closed** 2018-01-24 17:35 UTC
