### ISSUE TITLE
WebAgg Backend Canvas is Not an Image

### ISSUE THREAD

**Issue by blink1073** [matplotlib/matplotlib#3972] opened 2015-01-06 19:41 UTC
If you have this canvas in Firefox:

![screenshot from 2015-01-06 13 38 42](https://cloud.githubusercontent.com/assets/2096628/5634884/747de67a-95a9-11e4-8426-783e16aac8f1.png)

And then right click and select "View Image", you get:

![screenshot from 2015-01-06 13 38 59](https://cloud.githubusercontent.com/assets/2096628/5634893/8bfb2600-95a9-11e4-827c-9a293dcba789.png)

The URL is:  data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAoAAAAHgCAYAAAA10dzkAAAEvklEQVR4nO3BAQ0AAADCoPdPbQ43oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4Mwu4AAehrHaUAAAAASUVORK5CYII=

You also get a blank image when selecting "Save Image As...".

Any ideas on why the image "isn't there"?

**Comment by mdboom** [comment] 2015-01-06 19:43
It's an HTML canvas on to which difference images are composited.  I don't think browsers generally have a way to save/view that as an image.  Note in the toolbar, however, that you can choose an image format and press the "save" button to get an image.  I'm going to close this as "not a bug", but please let us know if the existing save functionality isn't sufficient for your use case.

**Comment by tacaswell** [comment] 2015-01-06 19:43
I wonder if this is related to having two layers of canvas objects ('canvas' and 'rubberband').

**Comment by blink1073** [comment] 2015-01-06 19:44
There is no toolbar entry for "Save" in the webagg backend, and the "S" shortcut key is not implemented either.

**Closed by mdboom** 2015-01-06 19:43 UTC

**Comment by blink1073** [comment] 2015-01-06 19:45
Whoops, the toolbar entry is there.

**Comment by blink1073** [comment] 2015-01-06 19:45
Looks like I need to connect the "S" key to the toolbar implementation...

**Comment by blink1073** [comment] 2015-01-06 19:46
Ah, there is no save button in the NbAgg backend, that's what I was thinking of.

**Comment by pelson** [comment] 2015-01-06 20:18
Incidentally, in the nbagg backend, it is possible to right click and save (at least, I remember trying to make it possible). I think I do that by sneakily capturing the right mouse click and pushing the lower image into the upper, or something.

**Comment by blink1073** [comment] 2015-01-07 04:13
Context menus are disabledin nbagg and right clicks have no effect.

**Comment by pelson** [comment] 2015-01-07 08:51
> Context menus are disabled in nbagg and right clicks have no effect. 

Wow, it is amazing how well I compartmentalize things and then move on! I completely forgot I did that.

> Can you remind me of the reasoning for not having a save button in NbAgg?

The webagg backend has a saved image endpoint (URL) which, when you click save, directs to you that URL. With IPython, we have no such endpoint. It might be possible to navigate to a data URL though.
