### ISSUE TITLE
Why not get the same clear image on a high-resolution screen?

### ISSUE THREAD

**Issue by reaCodes** [matplotlib/matplotlib#10235] opened 2018-01-12 09:33 UTC
My screen resolution is 2k, dpi zoom 200%

For example:

This is the picture displayed after running
![image](https://user-images.githubusercontent.com/13817254/34868256-1503d3f6-f7be-11e7-8a36-fb02a26f6b65.png)

And this is an image saved with dpi = 300
![image](https://user-images.githubusercontent.com/13817254/34868338-62a03b7c-f7be-11e7-9419-6d13a2578a3a.png)

My point is that gui applications are not ideal for displaying on high-resolution screens.

**Comment by tacaswell** [comment] 2018-01-12 14:29
what version of Matplotlib, what backend, and what OS?

**Comment by reaCodes** [comment] 2018-01-12 14:55
@tacaswell Matplotlib: 2.1.1, Python: 3.6.4, OS: Windows 10 16299

![image](https://user-images.githubusercontent.com/13817254/34880106-5882cca0-f7ea-11e7-86da-d22e841729d0.png)

Not only pictures, but also the toolbar is not clear.

![image](https://user-images.githubusercontent.com/13817254/34880392-3c1f448e-f7eb-11e7-88de-26e9771df2ae.png)

Can you tell the difference? The second picture is much cleaner, with dpi = 300

**Comment by anntzer** [comment] 2018-01-12 19:18
Can you try with qt5agg instead of tkagg?  (add `import matplotlib; matplotlib.use("qt5agg")` at the very top of your script; you may need to install pyqt5 from conda or pypi.)

**Comment by dstansby** [comment] 2019-04-21 10:38
@reaCodes is this still an issue? Did you get a chance to try out @anntzer's suggestion?

**Comment by timhoffm** [comment] 2019-11-05 23:36
On master: tkagg is blurry. qt5agg is sharp (150%, 200% tested). Holds for icons and plot itself.

**Comment by anntzer** [comment] 2019-11-06 18:03
I think this is essentially a duplicate of #10388.  Even though this issue was opened first I'll close it as there is more discussion on the other.

**Comment by anntzer** [comment] 2019-11-06 18:13
@timhoffm (or anyone else, for that matter) If you have a high-dpi screen available to testing on Windows, can you try calling one of https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiaware https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiawarenesscontext in tkagg.cpp?  (e.g. at the top of PyInit__tkagg)

**Comment by timhoffm** [comment] 2019-11-06 22:13
@anntzer will do some time later this week.

**Comment by QuLogic** [comment] 2021-07-08 20:47
Support for HiDPI in TkAgg on Windows was added in #19167.

**Closed by QuLogic** 2021-07-08 20:47 UTC
Labels: GUI/tk, OS/Microsoft
