### ISSUE TITLE
3D set_aspect(aspect='equal') works

### ISSUE THREAD

**Issue by vondreele** [matplotlib/matplotlib#16089] opened 2020-01-04 12:57 UTC
### Bug report

**Bug summary**

The matplotlib set_aspect(aspect='equal') command for 3D plots works perfectly well after the lines 1279:1282 in …\site_packages\matplotlib\axes\_base.py (matplotlib 3.1.1) are commented out. With it, the plot maintains the 3D aspect ratio despite window resizing. This is the desired behavior for 3D plots where the axes aspect is important and was the behavior in matplotlib 3.0.3.  NB: set_aspect does not establish the axes ratios; that must be done via calls to set_xlim3d(), set_ylim3d(), and set_zlim3d(). Perhaps the documentation for set_aspect should be modified to reflect its usage.

**Comment by tacaswell** [comment] 2020-04-22 02:58
Closing as a duplicate of #17172

**Closed by tacaswell** 2020-04-22 02:58 UTC
Labels: mplot3d
