### ISSUE TITLE
Matplotlib SVG file colours not rendering as expected 

### ISSUE THREAD

**Issue by abcam** [matplotlib/matplotlib#17465] opened 2020-05-20 14:49 UTC
### Bug report

**Bug summary**

Colours in saved matplotlib svg files not the same as displayed originally.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

cdict0 = {'red':   ((0.0, 1.0, 1.0),
                    (0.015, 1.0, 1.0),
                    (1.0, 1.0, 0.0)),

         'green':  ((0.0, 0.0, 1.0),
                    (0.015, 1.0, 1.0),
                    (1.0, 0.0, 0.0)),

         'blue':   ((0.0, 0.0, 1.0),
                    (0.015, 1.0, 1.0),
                    (1.0, 0.0, 0.0))
                   
         }


cdict1 = {'red':   ((0.0, 1.0, 1.0),
                   (1.0, 0.0, 0.0)),

         'green': ((0.0, 1.0, 1.0),
                   (1.0, 1.0, 0.0)),

         'blue':  ((0.0, 1.0, 1.0),
                   (1.0, 1.0, 0.0))
                   
         }

red = mpl.colors.LinearSegmentedColormap('Red Map', cdict0, N = 1000000)

cyan = mpl.colors.LinearSegmentedColormap('Cyan Map', cdict1, N = 1000000)

rng = np.random.default_rng(42)
data = rng.random((256, 256))
data_1 = rng.random((256, 256))
plt.imshow(data, alpha = 1, cmap = red)
plt.imshow(data_1, alpha = .5, cmap = cyan)
plt.axis('off')
plt.savefig('fig.svg')
plt.show()
```

**Actual outcome**

An SVG file containing: 

![image](https://user-images.githubusercontent.com/64583949/82458993-4e30d980-9aaf-11ea-8d4f-8fa83ace29b9.png)

**Expected outcome**
An SVG file containing:
![download](https://user-images.githubusercontent.com/64583949/82458856-1e81d180-9aaf-11ea-894d-d6e324525407.png)

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.2.1
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.7.7
  * Jupyter version (if applicable): jupyter core: 4.6.3, jupyter-notebook: 6.0.3, jupyter client: 6.1.3, jupyter lab: 2.1.1
  * Other libraries: 
 installed matplotlib with anaconda then pip to mpl 3.2.1

**Comment by tacaswell** [comment] 2020-05-20 16:22
I suspect that this is related to the images getting color mapped and then composited before being put in the SVG.

Using

```python
data = np.zeros((15, 15))
data += np.arange(15).reshape(-1, 1)
data_1 = np.zeros((15, 15))
data_1 += np.arange(15).reshape(1, -1)
```

As the sample data you get (saving directly to png)

![fig](https://user-images.githubusercontent.com/199813/82471066-313add00-9a94-11ea-80cf-06f1b7e75b03.png)


vs (saving to svg and then inkscape -> png)

![fig svg](https://user-images.githubusercontent.com/199813/82471132-4a438e00-9a94-11ea-96ca-2f069bf4a62b.png)

so clearly something is going differently with the compositing and alpha blending but I am not sure off the top of my head which is correct or why they are different.

**Comment by anntzer** [comment] 2020-05-22 13:00
possibly related to https://github.com/matplotlib/matplotlib/issues/8847?

**Comment by tacaswell** [comment] 2020-05-23 20:12
I suspect so, I'm in favor of closing this issue and re-milestoning  #8847 for 3.4?

**Comment by QuLogic** [comment] 2021-07-08 21:06
Closing as a duplicate of #8847.

**Closed by QuLogic** 2021-07-08 21:06 UTC
Labels: backend/svg
