### ISSUE TITLE
Log scale scatter limits incorrect if zero value present in data

### ISSUE THREAD

**Issue by svaberg** [matplotlib/matplotlib#18630] opened 2020-10-02 02:51 UTC
### Bug report

When using log scale with a scatter plot the axes are not set correctly if there is a zero value in the data. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt

x=[1e4, 1e5, 1e6, 0]
y=[1, 1, 1, 1]

fig, ax = plt.subplots()

ax.scatter(x, y, marker='o')
ax.set_xscale('log')
plt.show()
```

**Actual outcome**

The first point does not appear in the plot:

![image](https://user-images.githubusercontent.com/3267619/94882671-f28a4a00-04ab-11eb-99ff-83fc5c2f3a1d.png)

**Expected outcome**

Expected all the points to be inside the axis limits as it appears when using `plot` instead of `scatter`:

![image](https://user-images.githubusercontent.com/3267619/94882748-25ccd900-04ac-11eb-8b4a-cf8e14b8f575.png)

**Matplotlib version**

  * Operating system: MacOS
  * Matplotlib version: 3.3.2
  * Matplotlib backend: Both MacOS and Jupyter `module://ipykernel.pylab.backend_inline`
  * Python version: 3.8.5
  * Jupyter version (if applicable): 6.1.4
  * Other libraries: N/A

Python and matplotlib installed with conda in a fresh environment
`conda create --name matplotlib-log-scatter-bug matplotlib jupyter`

**Comment by QuLogic** [comment] 2020-10-02 06:51
Thanks for the report. This is a duplicate of #16552.

**Closed by QuLogic** 2020-10-02 06:51 UTC
