### ISSUE TITLE
Setting ticks on imshow wrongly resizes axis if origin='upper'

### ISSUE THREAD

**Issue by fmaussion** [matplotlib/matplotlib#14955] opened 2019-08-01 15:34 UTC
### Bug report

**Bug summary**

See example code and image.

**Code for reproduction**

```python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import sys

print(sys.version)
print(mpl.__version__)

a = np.arange(4*5).reshape((4, 5))

fig, (ax1, ax2) = plt.subplots(1, 2)

ax1.imshow(a, interpolation='none', origin='lower')
ax1.yaxis.set_ticks([1, 2])

ax2.imshow(a, interpolation='none', origin='upper')
ax2.yaxis.set_ticks([1, 2])

plt.show()
```

**Actual outcome**

![mpl_bug](https://user-images.githubusercontent.com/10050469/62306501-e9ea4e00-b479-11e9-949f-c5c650f0dc71.png)

**Expected outcome**

A similar plot in both cases

**Matplotlib version**

  * Operating system: Linux 
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://backend_interagg
  * Python version: 3.6.7 | packaged by conda-forge

**Comment by fmaussion** [comment] 2019-08-01 15:36
cc @TimoRoth , since this has broken our tests in https://github.com/OGGM/oggm and https://github.com/fmaussion/salem quite badly

**Comment by fmaussion** [comment] 2019-08-01 15:42
Note to the MPL devs: I'm not 100% sure if it's related to conda or to mpl. We've been seeing this on all our conda-forge installs since at least 4 weeks though.

**Comment by jklymak** [comment] 2019-08-01 16:21
Ping @anntzer.  I think this is maybe the same image indexing you fixed a couple weeks ago?

**Comment by ImportanceOfBeingErnest** [comment] 2019-08-01 16:26
Yep, duplicate of https://github.com/matplotlib/matplotlib/issues/14675. This is fixed in the current development version, but not yet released.

**Closed by ImportanceOfBeingErnest** 2019-08-01 16:26 UTC
