### ISSUE TITLE
imshow fails to render row with interpolation='none'

### ISSUE THREAD

**Issue by OverLordGoldDragon** [matplotlib/matplotlib#19662] opened 2021-03-07 17:32 UTC
Unsure if intentional; also for `'nearest'`. Goal is to display data as-is, with minimal "imputing".

```python
import numpy as np
import matplotlib.pyplot as plt

g = np.zeros((392, 240))
g[337, :50] = 1
g[338, 50:200] = 1
g[339, 200:] = 1

plt.imshow(g, interpolation='none', aspect='auto')
plt.show()
```

<img src="https://user-images.githubusercontent.com/16495490/110248797-4bdf3380-7f8c-11eb-8c91-a9ea1cd9a57e.png" width="500">

**Comment by jklymak** [comment] 2021-03-07 17:46
Use more pixels.  Also strongly suggest you reconsider not using `interpolation='none'`.  https://matplotlib.org/stable/gallery/images_contours_and_fields/image_antialiasing.html
I'm closing as this is not a bug, but feel free to continue discussion at https://discourse.matplotlib.org

**Closed by jklymak** 2021-03-07 17:46 UTC
