### ISSUE TITLE
Command prompt starts rapidly loading with usetex=True

### ISSUE THREAD

**Issue by necarion** [matplotlib/matplotlib#8487] opened 2017-04-15 01:54 UTC
When Pyplot rcparams are set s.t. usetex=True, the ipython console begins rapidly opening and closing new command windows (for about a minute) until the console crashes. The windows can be stopped by aborting and restarting the console.  I have TeX Live installed on my machine.

What steps will reproduce the problem?

import matplotlib.pyplot as plt, import numpy as np
plt.rc('text',usetex=True) (or some other method to set usetex=True)
fig = plt.figure(), axis = fig.add_subplot, axis.anything
This has happened on three separate computers running different versions of windows 10

What is the expected output? What do you see instead?

Please provide any additional information below

Versions and main components

Spyder Version: 3.1.1, 3.1.2
Python Version: 2.7.13
Operating system: Windows 10
Dependencies

jedi >=0.8.1 : 0.9.0 (OK)
matplotlib >=1.0 : 2.0.0 (OK)
nbconvert >=4.0 : 4.2.0 (OK)
numpy >=1.7 : 1.11.3 (OK)
pandas >=0.13.1 : 0.19.2 (OK)
pep8 >=0.6 : 1.7.0 (OK)
pyflakes >=0.5.0 : 1.5.0 (OK)
pygments >=2.0 : 2.1.3 (OK)
pylint >=0.25 : 1.6.4 (OK)
qtconsole >=4.2.0: 4.2.1 (OK)
rope >=0.9.4 : 0.9.4 (OK)
sphinx >=0.6.6 : 1.5.1 (OK)
sympy >=0.7.3 : 1.0 (OK)

**Comment by tacaswell** [comment] 2017-04-17 13:09
Do the windows have any text in them?  My _guess_ is that we are calling out to tex wrong, it is failing, and everytime the figure tries to re-draw it's self another window is opened.

Does

```python
import matplotlib.pyplot as plt
plt.ioff()
plt.rc('text',usetex=True)
fig, ax = plt.subplots()
ax.plot(range(5))
fig.savefig('test.png')
```

give you a traceback?

attn @Kojoley

**Comment by phobson** [comment] 2017-04-20 04:44
I haven't used tex in a while, but I remember this happening. I always assumed it was compiling little images for each text block in a figure in separate processes.

**Comment by tacaswell** [comment] 2017-04-20 14:01
That is how it works, but it should not spin forever and we cache pretty aggressively.

**Comment by ImportanceOfBeingErnest** [comment] 2017-08-09 12:47
Someone just reported about the same behaviour on Stackoverflow: [This is the post](https://stackoverflow.com/questions/45588846/using-tex-in-matplotlib-with-spyder-opens-multiple-cmd-windows-on-windows-10).

I just want to add that using python 2.7, matplotlib 2.0.2, on windows 8.1 with MikTeX, I do not ever observe command line windows popping up. So it could be due to Windows 10, or the latex installation in use.

**Comment by imthedevil** [comment] 2017-10-13 08:44
The same thing happened to me also as soon as I updated to Spyder 3 and this has not been fixed. There are no popups when downgrading to Spyder 2 or running any other IDE so it is not a matplotlib issue.

**Comment by tacaswell** [comment] 2017-10-13 23:06
@imthedevil have you reported this to the spyder devs?

Also, your user name makes it difficult to take you seriously.

**Comment by giuliofoletto** [comment] 2017-11-09 15:41
Same problem here, spyder or qtconsole simply crash after loading multiple cmd windows when using `usetex=True`. I tried with Windows 10 64 bit version 10.0.16299.19, MiKTeX 2.9.6350 64-bit (with dvipng), ghostscript 9.22 64 bit, python 3.6, spyder 3.2.4, matplotlib 2.0.2, qtconsole 4.3.1

**Comment by anntzer** [comment] 2019-03-22 09:19
I'm going to close this as the reports are pretty old, the OP did not reply to requests for details, the issue is not reproduced by @ImportanceOfBeingErnest, the issue is supposedly fixed by mpl2.1, and the problem may be on Spyder's side.  Feel free to ping for a reopen if this can be repro'd with the latest matplotlib and outside of spyder.

**Closed by anntzer** 2019-03-22 09:19 UTC
Labels: OS/Microsoft, text/usetex
