### ISSUE TITLE
backend default when no X server present

### ISSUE THREAD

**Issue by ordirules** [matplotlib/matplotlib#9140] opened 2017-08-31 17:58 UTC
### Bug report

**Bug summary**
`matplotlib.pyplot` isn't friendly to remotely run commands with no X server:
```python
In [1]: import matplotlib.pyplot

In [2]: QXcbConnection: Could not connect to display 
Aborted
```

However, selecting the backend before hand fixes the problem:
```python
In [1]: import matplotlib

In [2]: matplotlib.use("Agg")

In [3]: import matplotlib.pyplot
```

I am not very familiar, but could there be some check of the display module before importing? My problem is I obtain this error when running on a remote server with no X11 forwarding and importing a library that by default imports `maplotlib.pyplot`. (The library is [`pims`](http://www.github.com/soft-matter/pims) )

**Matplotlib version**
  * Operating System: Linux (Debian)
  * Matplotlib Version: 1.5.3
  * Python Version: 3.5.3
  * IPython Version :  5.1.0

I installed matplotlib via pip.

**Comment by anntzer** [comment] 2017-08-31 18:20
This is a duplicate of https://github.com/matplotlib/matplotlib/issues/6739.  Please continue the discussion there, thanks!

**Closed by anntzer** 2017-08-31 18:20 UTC

**Comment by ordirules** [comment] 2017-08-31 19:23
thank you!
