### ISSUE TITLE
label keyword is not interpreted proporly in errorbar() for pandas.DataFrame-like objects

### ISSUE THREAD

**Issue by monodera** [matplotlib/matplotlib#5565] opened 2015-11-25 18:10 UTC
I encountered an issue of the legend in matplotlib.pyplot.errorbar when I plot a pandas' DataFrame object.  A minimum example based on the release note of v1.5 is the following.

```python
import pandas
import numpy as np
import matplotlib.pyplot as plt

df = pandas.DataFrame({"var1":[1,2,3,4,5,6], "var2":[1,2,3,4,5,6]})
```

Here is the same as one in the release note, but with a legend.

```python
plt.plot(df["var1"], df["var2"], label='test')
plt.legend()
```

The output is the following.

![test_pandas_plot](https://cloud.githubusercontent.com/assets/90394/11405337/5a201cc4-93a7-11e5-92ea-d747f4e37074.png)

The following code makes the issue.

```python
plt.errorbar(df["var1"], df["var2"], label='test')
plt.legend()
```

![test_pandas_err](https://cloud.githubusercontent.com/assets/90394/11405364/843b58de-93a7-11e5-926f-59b52cddbbbb.png)

As you can see, the 'var2' key is not overridden by the `label='test'` and there are two lines instead of one in the legend. 

A quick workaround is to convert the y values to numpy array with `np.array(df["var2"])` when plotting.

I'm using Python 2.7.8 installed via homebrew on OS X 10.10.5, matplotlib 1.5.0, and pandas 0.17.0.

**Comment by tacaswell** [comment] 2015-11-25 18:21
I think this is a duplicate of https://github.com/matplotlib/matplotlib/issues/5393

**Closed by tacaswell** 2015-11-25 18:21 UTC
