### ISSUE TITLE
%matplotlib notebook offsetting sns.palplot

### ISSUE THREAD

**Issue by jolespin** [matplotlib/matplotlib#7431] opened 2016-11-08 20:07 UTC
When I use `%matplotlib notebook` it creates bigger plots like https://github.com/matplotlib/matplotlib/issues/4853 but also offsets the entire image. 

```
%matplotlib inline
sns.palplot(sns.color_palette("cubehelix", n_colors=50))

%matplotlib notebook
sns.palplot(sns.color_palette("cubehelix", n_colors=50))

```
![screen shot 2016-11-08 at 12 05 32 pm](https://cloud.githubusercontent.com/assets/9061708/20115084/cc8bfb0e-a5ab-11e6-8ca9-b20e66237f48.png)

**Comment by efiring** [comment] 2016-11-08 23:25
Yes, that's because inline is using`tight_layout` to eliminate space around the Axes object, and the notebook backend is not doing this.  The use of tight_layout is a default configuration in ipython, not matplotlib, so it is not under our control.  I suspect you can use it with Seaborn to eliminate the extra space with the notebook backend.  Try using
```python
from matplotlib import rcParams
rcParams['figure.autolayout'] = True
```
before your palplot call.
(This actually is a duplicate of #4853.)

**Closed by efiring** 2016-11-08 23:25 UTC

**Comment by jolespin** [comment] 2016-11-09 01:39
Sorry about the duplicate.  Thanks for the help!
