### ISSUE TITLE
Creating figure resets locale

### ISSUE THREAD

**Issue by skjaeve** [matplotlib/matplotlib#6706] opened 2016-07-08 13:33 UTC
I have an issue where I set the locale of the python script with locale.setlocale(). When I then create a figure, the locale is reset to the default.

I have trouble pinning it down exactly. On my computer (OpenSuse Tumbleweed) it happens with Matplotlib from Git, but not with system-supplied matplotlib. On a CentOS 6 running Miniconda python, it happens with Matplotlib 1.5.1 supplied with Miniconda.

MWE:

``` python
from __future__ import print_function
import locale
import sys
print ('Python version:', sys.__version__)
print ("Initial locale:", locale.getlocale())
print ('Changing locale to en_US')
locale.setlocale(locale.LC_ALL, 'en_US.utf8')
print ("New locale:", locale.getlocale())
import matplotlib
print ("Matplotlib version:", matplotlib.__version__)
print ("Locale after importing matplotlib:", locale.getlocale())
import matplotlib.pyplot as pyplot
print ("Locale after importing pyplot:", locale.getlocale())
pyplot.figure()
print ("Locale after creating figure:", locale.getlocale())

```

Running the MWE on my computer:

```

§~/src> python3 mwe.py
Python version: 3.5.1 (default, Dec 09 2015, 07:29:36) [GCC]
Initial locale: ('nn_NO', 'UTF-8')
Changing locale to en_US
New locale: ('en_US', 'UTF-8')
Matplotlib version: 2.0.0b1+1771.g5dfe000
Locale after importing matplotlib: ('en_US', 'UTF-8')
Locale after importing pyplot: ('en_US', 'UTF-8')
Locale after creating figure: ('nn_NO', 'UTF-8')

§~/src> mv ~/.local/lib/python3.5/  ~/.local/lib/xpython3.5/ # Revert to system-supplied matplotlib
§~/src> python3 mwe.py
Python version: 3.5.1 (default, Dec 09 2015, 07:29:36) [GCC]
Initial locale: ('nn_NO', 'UTF-8')
Changing locale to en_US
New locale: ('en_US', 'UTF-8')
Matplotlib version: 1.5.1
Locale after importing matplotlib: ('en_US', 'UTF-8')
Locale after importing pyplot: ('en_US', 'UTF-8')
Locale after creating figure: ('en_US', 'UTF-8')
```

To help us understand and resolve your issue please check that you have provided
the information below.
- [x] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
- [x] How did you install Matplotlib and Python (pip, anaconda, from source ...)
- [x] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
    that demonstrates the issue i.e a small piece of code which reproduces the issue
    and can be run with out any other (or as few as possible) external dependencies.
- [ ] If this is an image generation bug attach a screenshot demonstrating the issue.
- [ ] If this is a regression (Used to work in an earlier version of Matplotlib), please 
    note where it used to work.

**Comment by anntzer** [comment] 2016-07-09 19:11
A quick look indicates that the behavior is backend dependent.  Non-interactive backends do not reset the locale.  Qt5Agg resets it after importing `figure`; TkAgg resets it after importing `pyplot`.

**Comment by tacaswell** [comment] 2016-07-10 01:26
If it is backend dependent that I suspect it is the default locale handling in the GUI frameworks.

**Comment by anntzer** [comment] 2016-12-02 09:14
I can confirm that this is due to locale handling by the GUI framework.  `tkinter` appears to reset the locale when imported for the first time:
```
$ python -c 'import locale; locale.setlocale(locale.LC_ALL, "fr_FR.utf8"); print(locale.getlocale()); import tkinter as tk; print(locale.getlocale())'
('fr_FR', 'UTF-8')
('en_US', 'UTF-8')
```

Likewise Qt5 resets the locale when the QApplication is created.

Thus the best thing that can be done is probably to add a note in the docs to that effect.

**Comment by anntzer** [comment] 2018-12-29 12:17
I'm going to close this as far too specific to be worth an entry in the docs IMO.
Still, thanks for the report.

**Closed by anntzer** 2018-12-29 12:17 UTC
Labels: Documentation, can't fix
