### ISSUE TITLE
Cannot use Qt4Agg backend in mpl 3.2.1

### ISSUE THREAD

**Issue by alexsong19** [matplotlib/matplotlib#17594] opened 2020-06-09 02:08 UTC
### Bug report

**Bug summary**
Can't use qt4agg, error reported below.

Downgrade to matplotlib 3.1.3 solves the problem.

**Code for reproduction**

```python
import matplotlib as mpl
mpl.use('qt4agg')
```
Or, set it to Qt4Agg in `matplotlibrc` file.

**Actual outcome**

```
ImportError: cannot import name '_isdeleted' 
Failed to enable GUI event loop integration for 'qt5'
```

**Matplotlib version**

  * Operating system: win 10 LTSC 2019
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): can only use TkAgg
  * Python version: 3.6

**Comment by tacaswell** [comment] 2020-06-09 03:27
I think this is a duplicate of https://github.com/matplotlib/matplotlib/issues/16834 which was fixed by https://github.com/matplotlib/matplotlib/pull/16835 and will be included in 3.2.2 which should be tagged this week.

Thank you for reporting this and sorry it has taken us a while to get a release with the fix out.

**Closed by tacaswell** 2020-06-09 03:27 UTC
