### ISSUE TITLE
[Bug]: polar plotting does not handle negative values correctly

### ISSUE THREAD

**Issue by petermao** [matplotlib/matplotlib#27002] opened 2023-10-05 17:13 UTC
### Bug summary

Polar plotting does not handle negative values correctly.  For example, a polar plot of `cos(theta)` should yield a circle to passing through the origin and `(theta = 0, r = 1)`.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

theta = 2 * np.pi * np.arange(0, 1, 0.005)
r = cos(theta)

fig, ax = plt.subplots(subplot_kw={'projection': 'polar'})
ax.plot(theta, r)
ax.grid(True)

ax.set_title("cos$\\theta$??", va='bottom')
show()
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/1535322/d5186116-d3a5-4b17-944c-1dfdd1397875)

### Expected outcome

from Matlab:
![image](https://github.com/matplotlib/matplotlib/assets/1535322/1338bd79-e303-48f5-a6e7-df26ff019216)

### Operating system

OS/X

### Matplotlib Version

3.6.3

### Matplotlib Backend

MacOSX

### Python version

3.9.17

### Jupyter version

N/A

### Installation

pip

**Comment by jklymak** [comment] 2023-10-05 17:21
This is basically a duplicate of https://github.com/matplotlib/matplotlib/issues/25090. Matplotlib allows r<0 in polar axes, and in that co-ordinate system you don't get a circle.

**Comment by petermao** [comment] 2023-10-05 17:23
OK, this is a documentation issue then.  Polar plots with the origin not `r=0` are **very** unusual.

**Comment by tacaswell** [comment] 2023-10-05 17:54
I believe the historical reason we support this is to plot radial distributions in decibels which are often negative.   When plotting there is always a transformation from your data to pixel space in the output.  Matplotlib's choice here is to _not_ pin the transfrom in polar coordinates to always have a minimum of 0.  Matplotlib's choice here is the more general one.  If you want the reflection behavior it is a small bit of pre-processing on your input to get vs in the reflection case it would be much harder (saying "impossible" is a bit strong) to get the "radial is just a scale" behavior.

Please remember that Matplotlib is used by a very wide span of domains.  It is not uncommon for some behavior to be the "obvious right thing" in one domain while simultaneously being "obviously the wrong thing" in another.

The tick labels are a bit too tightly packed by default, but they are labeled with negative values.

If you set `ax.set_rlim(rmin=0)` you get 
![so](https://github.com/matplotlib/matplotlib/assets/199813/c7b94671-0bd9-4c0f-b56b-93f030628d0e)

However, this is effectively not showing half of your data.

**Closed** 2023-10-06 04:11 UTC
Labels: status: duplicate, topic: polar, Community support

**Comment by Aminkuhbor** [comment] 2024-03-11 06:29
what is the solution for the : r= 1+2cos(theta)?!!
