### ISSUE TITLE
[Bug]: colorbar interacts poorly with TwoSlopeNorm when one slope is infinite

### ISSUE THREAD

**Issue by bjodah** [matplotlib/matplotlib#24283] opened 2022-10-27 11:51 UTC
### Bug summary

The range of colors shown in the colorbar is incorrect when a `TwoSlopeNorm` is used over data which is biased to either side of the center of the Norm.

Here's the code for reproduction:

https://gist.github.com/bjodah/76d2f42684141f01ec350ad6d1edcd41

### Code for reproduction

```python
# see above link, or here's the pasted code from above notebook:
import matplotlib.pyplot as plt
import matplotlib.colors as mc
import numpy as np
def imshow_with_colorbar(M, cmap, norm=None):
    fig, ax = plt.subplots(1, 1)
    mappable = ax.imshow(M, cmap=cmap, norm=norm or mc.TwoSlopeNorm(0))
    fig.colorbar(mappable)



A = np.arange(-3., 3.).reshape((2, 3))
B = np.arange(0.0, 6.).reshape((2, 3))

# This looks reasonable:
imshow_with_colorbar(A, plt.cm.coolwarm)

# when the range starts at zero, note how the color for zero (grey) is not represented in the colorbar:
imshow_with_colorbar(B, plt.cm.coolwarm)

# the bug is more apparent using another colormap (hsv):
imshow_with_colorbar(B, plt.cm.hsv)

# below is not a bug per se, just a possible area of improvement: the colorbar get no tick printed on negative side when magnitudes differ, so there is no way to estimate the magnitude by only looking at the plot:
B2 = B - 1e-10
imshow_with_colorbar(B2, plt.cm.coolwarm)

# one possible remedy is to manually set the lower bound to a value of simliar magnitude
m = np.max(np.abs(2))
imshow_with_colorbar(B2, plt.cm.coolwarm, norm=mc.TwoSlopeNorm(vmin=-m, vcenter=0, vmax=m))

# but then we cannot tell if we are in the negative or not by simply looking at the color
```

### Actual outcome

![bild](https://user-images.githubusercontent.com/485936/198277875-ec22b48c-877a-449e-8fbb-89fe528315e6.png)
(see above link for more context)

### Expected outcome

the colorbar should include all colors shown in the axes.

### Matplotlib Version

3.6.1
### Python version
3.10

**Comment by jklymak** [comment] 2022-10-27 15:54
_Most_ of this report is a duplicate of https://github.com/matplotlib/matplotlib/issues/23040

**Comment by tacaswell** [comment] 2022-10-27 16:43
Ah, great.  That does indeed fix the last case, but there is still something wrong when half of the range is degenerate:

```python

# see above link, or here's the pasted code from above notebook:
import matplotlib.pyplot as plt
import matplotlib.colors as mc
import numpy as np
def imshow_with_colorbar(M, cmap, norm=None):
    fig, (ax1, ax2) = plt.subplots(2, 1, layout='constrained')
    
    def inner(ax, scale):
        mappable = ax.imshow(M, cmap=cmap, norm=norm or mc.TwoSlopeNorm(0))
        cbar = fig.colorbar(mappable, ax=mappable.axes)
        if scale is not None:
            cbar.ax.set_yscale(scale)
        ax.set_title(f'{scale=}')

    inner(ax1, None)
    inner(ax2, 'linear')

A = np.arange(-3., 3.).reshape((2, 3))
B = np.arange(0.0, 6.).reshape((2, 3))

# This looks reasonable:
imshow_with_colorbar(A, plt.cm.coolwarm)

# when the range starts at zero, note how the color for zero (grey) is not represented in the colorbar:
imshow_with_colorbar(B, plt.cm.coolwarm)

# the bug is more apparent using another colormap (hsv):
imshow_with_colorbar(B, plt.cm.hsv)

# below is not a bug per se, just a possible area of improvement: the colorbar get no tick printed on negative side when magnitudes differ, so there is no way to estimate the magnitude by only looking at the plot:
B2 = B - 1e-10
imshow_with_colorbar(B2, plt.cm.coolwarm)

# one possible remedy is to manually set the lower bound to a value of simliar magnitude
m = np.max(np.abs(2))
imshow_with_colorbar(B2, plt.cm.coolwarm, norm=mc.TwoSlopeNorm(vmin=-m, vcenter=0, vmax=m))

# but then we cannot tell if we are in the negative or not by simply looking at the color

```

![so](https://user-images.githubusercontent.com/199813/198349601-0d8373ad-1b78-4f16-b377-f69974ce896e.png)

**Comment by jklymak** [comment] 2022-10-28 00:43
> there is still something wrong when half of the range is degenerate:

I mean if vmin>=center, its pretty hard to expect anything sensible.  I guess we could warn at the Norm level.

**Comment by tacaswell** [comment] 2022-10-28 01:22
The interpolation in the inverse is sensible.   Shouldn't we be able to show the top (or bottom) half of the colorbar?

**Comment by jklymak** [comment] 2022-10-28 02:44
The way the colorbar works is it makes an evenly spaced grid 256 elements long between 0 and 1, and then maps those to values using the inverse of the norm.   If all the values from 0 to 0.5 get mapped to "center", then I think you get what is shown here.   We could mess around with the logic to make the degenerate values map to "vmin" probably, but that sounds like a bunch of ugly special casing, for little practical end-user benefit.

**Comment by tacaswell** [comment] 2022-10-28 03:15
That make sense, but I do not understand why that makes the color at `2` wrong (it should be blue like the top-right not magenta like the bottom left).

**Comment by jklymak** [comment] 2022-10-28 03:24
Oh, thats weird.  Sorry I missed that.   I'm not sure what is happening there!

**Comment by bjodah** [comment] 2022-10-28 07:46
Great, I was worried I had misunderstood something, but now I think we are all on the same page. :-)
And thank you for taking a look at this.

**Comment by dstansby** [comment] 2023-01-22 21:44
A minimal example here is:
```python
import matplotlib.pyplot as plt
import matplotlib.colors as mc
import numpy as np

B = np.arange(0.0, 6.).reshape((2, 3))

fig, ax = plt.subplots()
mappable = ax.imshow(B, cmap=plt.cm.hsv, norm=mc.TwoSlopeNorm(0))
cbar = fig.colorbar(mappable, ax=mappable.axes)

plt.show()
```
The value of the lower left square is 3, but the color of it doesn't match 3 on the colorbar:
![twoslope](https://user-images.githubusercontent.com/6197628/213941984-19f5fe86-55a4-49a7-b4ed-ade864b6e798.png)

**Closed** 2023-01-24 20:40 UTC
Labels: status: confirmed bug, topic: color/colorbar, topic: transforms and scales
