### ISSUE TITLE
[Bug]: Resizing does not work in WebAgg backend in Safari

### ISSUE THREAD

**Issue by zhizheng1** [matplotlib/matplotlib#24089] opened 2022-10-04 03:28 UTC
### Bug summary

Resizing by dragging the bottom right corner works fine in Chrome but doesn't work in Safari.

### Code for reproduction

```python
plot anything
```

### Actual outcome

https://user-images.githubusercontent.com/114848324/193728089-ad8c5866-295b-48e8-b3b6-bc8058462c2b.mov

https://user-images.githubusercontent.com/114848324/193728101-e490dba8-d427-47cf-8fcf-c65ccf12eeee.mov

### Expected outcome

Resizing should work in Safari too.

### Matplotlib Version

3.6.0

### Matplotlib Backend

webagg

**Comment by QuLogic** [comment] 2022-10-04 08:28
I can only check Firefox and Chrome right now, and not macOS. If Safari is WebKit-based, perhaps I can find an alternate browser that uses it to test.

I've also rebased #23540 and explicitly requested it test all browsers which should hopefully check this as well.

**Comment by QuLogic** [comment] 2022-10-04 08:34
OK, I can confirm in Midori, which is WebKit-based.

**Comment by zhizheng1** [comment] 2022-10-04 13:21
@QuLogic Thanks for following up the issue; would be really helpful if it can be resolved for WebKit-based browsers. For now I'm applying my patch each time MPL is updated, however would be great if there's a uniform solution for all browsers..

**Comment by QuLogic** [comment] 2022-10-27 06:09
So there are apparently two very old bugs about this in WebKit, https://bugs.webkit.org/show_bug.cgi?id=144526 and https://bugs.webkit.org/show_bug.cgi?id=181818. But since it's been fixed in Blink, it'd be nice if they could cross-port that fix (though I have no idea how easy that is.)

This does make it a bit difficult to fix though, since Chrome seems to report as WebKit still. Maybe keying off Safari in `userAgent` might work.

**Closed** 2022-10-31 23:39 UTC

**Comment by zhizheng1** [comment] 2022-11-04 09:04
Thank you, confirmed working in the latest MPL.
