### ISSUE TITLE
Latex text, problem with decimals

### ISSUE THREAD

**Issue by latkins** [matplotlib/matplotlib#7301] opened 2016-10-18 10:48 UTC
Using matplotlib 1.5.1 on python 3.5, installed via anaconda on debian stretch, I am having trouble with latex for writing text, set by:

```
mpl.rcParams.update({
    "text.latex.unicode": True,
    "font.family": "serif",
    "font.serif": [],
    "font.sans-serif": [],
    "font.monospace": [],
    "axes.labelsize": 10,
    "font.size": 12,
    "legend.fontsize": 10, 
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "figure.figsize": figsize(0.9), 
    "pgf.texsystem": "pdflatex",   
    "pgf.preamble": [
        r"\usepackage[utf8x]{inputenc}",    
        r"\usepackage[T1]{fontenc}",        
        ]
    })
```

I am doing this in a jupyter notebook. This generally works fine, but when I need decimals to be printed (e.g. for x/y ticks, or manually via labels) it fails. Some examples:

```
plt.plot([1,2], [2,3])
plt.show()
```

Results in:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/IPython/core/formatters.py in __call__(self, obj)
    337                 pass
    338             else:
--> 339                 return printer(obj)
    340             # Finally look for special method names
    341             method = _safe_get_formatter_method(obj, self.print_method)

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/IPython/core/pylabtools.py in <lambda>(fig)
    224 
    225     if 'png' in formats:
--> 226         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    227     if 'retina' in formats or 'png2x' in formats:
    228         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    115 
    116     bytes_io = BytesIO()
--> 117     fig.canvas.print_figure(bytes_io, **kw)
    118     data = bytes_io.getvalue()
    119     if fmt == 'svg':

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2178                     orientation=orientation,
   2179                     dryrun=True,
-> 2180                     **kwargs)
   2181                 renderer = self.figure._cachedRenderer
   2182                 bbox_inches = self.figure.get_tightbbox(renderer)

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py in print_png(self, filename_or_obj, *args, **kwargs)
    525 
    526     def print_png(self, filename_or_obj, *args, **kwargs):
--> 527         FigureCanvasAgg.draw(self)
    528         renderer = self.get_renderer()
    529         original_dpi = renderer.dpi

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    472 
    473         try:
--> 474             self.figure.draw(self.renderer)
    475         finally:
    476             RendererAgg.lock.release()

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     59     def draw_wrapper(artist, renderer, *args, **kwargs):
     60         before(artist, renderer)
---> 61         draw(artist, renderer, *args, **kwargs)
     62         after(artist, renderer)
     63 

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/figure.py in draw(self, renderer)
   1157         dsu.sort(key=itemgetter(0))
   1158         for zorder, a, func, args in dsu:
-> 1159             func(*args)
   1160 
   1161         renderer.close_group('figure')

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     59     def draw_wrapper(artist, renderer, *args, **kwargs):
     60         before(artist, renderer)
---> 61         draw(artist, renderer, *args, **kwargs)
     62         after(artist, renderer)
     63 

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2322 
   2323         for zorder, a in dsu:
-> 2324             a.draw(renderer)
   2325 
   2326         renderer.close_group('axes')

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     59     def draw_wrapper(artist, renderer, *args, **kwargs):
     60         before(artist, renderer)
---> 61         draw(artist, renderer, *args, **kwargs)
     62         after(artist, renderer)
     63 

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/axis.py in draw(self, renderer, *args, **kwargs)
   1106         ticks_to_draw = self._update_ticks(renderer)
   1107         ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
-> 1108                                                                 renderer)
   1109 
   1110         for tick in ticks_to_draw:

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/axis.py in _get_tick_bboxes(self, ticks, renderer)
   1056         for tick in ticks:
   1057             if tick.label1On and tick.label1.get_visible():
-> 1058                 extent = tick.label1.get_window_extent(renderer)
   1059                 ticklabelBoxes.append(extent)
   1060             if tick.label2On and tick.label2.get_visible():

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/text.py in get_window_extent(self, renderer, dpi)
    959             raise RuntimeError('Cannot get window extent w/o renderer')
    960 
--> 961         bbox, info, descent = self._get_layout(self._renderer)
    962         x, y = self.get_unitless_position()
    963         x, y = self.get_transform().transform_point((x, y))

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/text.py in _get_layout(self, renderer)
    359                 w, h, d = renderer.get_text_width_height_descent(clean_line,
    360                                                         self._fontproperties,
--> 361                                                         ismath=ismath)
    362             else:
    363                 w, h, d = 0, 0, 0

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py in get_text_width_height_descent(self, s, prop, ismath)
    227             fontsize = prop.get_size_in_points()
    228             w, h, d = texmanager.get_text_width_height_descent(s, fontsize,
--> 229                                                                renderer=self)
    230             return w, h, d
    231 

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/texmanager.py in get_text_width_height_descent(self, tex, fontsize, renderer)
    673         else:
    674             # use dviread. It sometimes returns a wrong descent.
--> 675             dvifile = self.make_dvi(tex, fontsize)
    676             dvi = dviread.Dvi(dvifile, 72 * dpi_fraction)
    677             try:

/home/lpa24/anaconda/envs/struct_gpu/lib/python3.5/site-packages/matplotlib/texmanager.py in make_dvi(self, tex, fontsize)
    420                      'string:\n%s\nHere is the full report generated by '
    421                      'LaTeX: \n\n' % repr(tex.encode('unicode_escape')) +
--> 422                      report))
    423             else:
    424                 mpl.verbose.report(report, 'debug')

RuntimeError: LaTeX was not able to process the following string:
b'$2.2$'
Here is the full report generated by LaTeX: 

No latex error report available.

```

The following works:

```
plt.plot([1,2], [2,3])
plt.xticks([])
plt.yticks([])
plt.show()
```

Manually setting a label to "$0.2$" works, but "0.2" or "$0.02$" fail with the same error. I expect this is something to do with my latex install, but I'm not really sure what.

**Comment by tacaswell** [comment] 2016-10-19 16:03
It looks like byte strings are making it down to you latex.

Can you try with 1.5.3 (available from conda, conda-forge has a version that will not bump your qt version).  I can not reproduce this with 1.5.3.

```
 ipython                                                                                                                                                                                                                                                                                                                                                                                                                         
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06)                                                                                                                                                                                                                                                                                                                                                               
Type "copyright", "credits" or "license" for more information.                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                        
IPython 5.1.0 -- An enhanced Interactive Python.                                                                                                                                                                                                                                                                                                                                                                                        
?         -> Introduction and overview of IPython's features.                                                                                                                                                                                                                                                                                                                                                                           
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib as mpl

In [2]: import matplotlib.pyplot as plt
/tmp/mpl153/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/tmp/mpl153/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

In [3]: xkbcommon: ERROR: failed to add default include path /home/ray/mc-x64-2.7/conda-bld/qt_1475858339722/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
In [3]: 

In [3]: mpl.rcParams.update({
   ...:     "text.latex.unicode": True,
   ...:     "font.family": "serif",
   ...:     "font.serif": [],
   ...:     "font.sans-serif": [],
   ...:     "font.monospace": [],
   ...:     "axes.labelsize": 10,
   ...:     "font.size": 12,
   ...:     "legend.fontsize": 10, 
   ...:     "xtick.labelsize": 10,
   ...:     "ytick.labelsize": 10,
   ...: 
   ...:     "pgf.texsystem": "pdflatex",   
   ...:     "pgf.preamble": [
   ...:         r"\usepackage[utf8x]{inputenc}",    
   ...:         r"\usepackage[T1]{fontenc}",        
   ...:         ]
   ...:     })

In [4]: 

In [4]: plt.ion()

In [5]: plt.plot([1,2], [2,3])
   ...: plt.show()
   ...: 

In [6]: /tmp/mpl153/lib/python3.5/site-packages/matplotlib/font_manager.py:1288: UserWarning: findfont: Font family ['serif'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))

```

**Comment by anntzer** [comment] 2017-09-11 08:01
Closing as the issue could not be reproduced (and I could not reproduce it either).  If the issue is still present for you, feel free to request the issue be reopened, of course.

**Closed by anntzer** 2017-09-11 08:01 UTC
Labels: needs confirmation
