### ISSUE TITLE
MEP for a matplotlib geometry manager

### ISSUE THREAD

**Issue by pelson** [matplotlib/matplotlib#1109] opened 2012-08-19 18:32 UTC
Write a MEP for a matplotlib figure geometry manager.

There is a **lot** of experience in the matplotlib community with requirements & ideas. This would be a good place to collate _before_ a MEP gets written.

**Comment by Tillsten** [comment] 2015-04-21 13:20
@sccolbert Playing around with kiwi again, the follwing questions pop up:

*  Is there a difference between using `s.addConstraint(x == 5)` and s.suggestValue(x, 5)`
*  Can i specify the strength of an constraint?

**Comment by sccolbert** [comment] 2015-04-21 14:54
@Tillsten The combination of `addEditVariable` + `suggestValue` is used when you want to resolve the same problem with slightly varying inputs. As a simple example, consider the layout of widgets in a panel. The input to the system is the `width` and `height` of the panel, and the output is the new geometry of the child widgets. In this type of problem, the `width` and `height` variables for the panel are added as edit variables in the solver instead of as constraint expressions. When the size of the panel changes, the new values for `width` and `height` will be provided to the solver via `suggestValue` and the system will be resolved. The solver is optimized for this use cas: set up a system, then resolve it several times with slightly varying inputs.

If your particular problem doesn't have this type of setup, that's okay. There are lots of problems which don't really have "inputs" of which to speak, and the system is just solved once in its entirety. In that case, you can just ignore edit variables and `suggestValue`. Indeed, you can solve the problem example above without using `suggestValues` by adding and removing hard constraints for the panel `width` and `height` as needed, it just wont be as fast since the solver will not take the optimized path.

You can change the strength of a constraint expression using the `|` operator and ORing the constraint with a symbolic strength, or a number. The valid symolic strengths are `'required'`, `'strong'`, `'medium'`, and `'weak'`. The default strength is 'required'. The mapping from symbolic strength to numeric strength can be found here:
https://github.com/nucleic/kiwi/blob/master/kiwi/strength.h

User code will typically always use a symbolic strength:
`(x == 5) | 'weak'`

**Comment by Tillsten** [comment] 2015-04-22 15:04
Thanks a lot! I even tried ORing, but i forgot the braces around the constraint.

There is now a atleast somewhat working very basic prototype at https://github.com/Tillsten/MplLayouter. At the moment it uses its own methods for adding labels and titles, any intregation would requiere to subclass Axes and overwrite the corresponding methods. As most here will understand, i don't want to touch Axes at the moment.  

Still a open issuse is the handling of ticklabels: right now u reuse the approach of tight_layout, that means drawing the axes checking and adjust the size afterwards. But this makes the handling of axes alignment more difficult than necessery. I hope that i can still work around it or maybe distangle the ticklabels from the rest.

Also while it is possible to get the text extent, i still don't know how to get the text baseline. Any help or comments are welcome.

**Comment by Tillsten** [comment] 2015-04-22 15:13
To see the (boring) example, just run the python file. Needs kiwisolver (avaible via conda). The only nice thing which can be seen is that the top labels are automatically aligned with resepect to each other, regardless of titles of the size of the ticklabels.

**Comment by tacaswell** [comment] 2015-04-22 15:29
@Tillsten :+1: Awesome thanks for working on this.

When you say 'disentangle the ticktlabels' do you mean pulling apart the `Tick` objects (that draw the tick label, the tick mark, and the grid line)?

attn @mdboom re the internals of text objects.

**Comment by pwuertz** [comment] 2015-04-22 15:36
Concerning text baseline, see my earlier comment (hint to `Renderer.get_text_width_height_descent()`).

**Comment by Tillsten** [comment] 2015-04-22 15:39
@tacaswell The problem is that size and position of the ticklabels is only know after drawing. For layout proposes it would be easier to place them directly using the constraints system. For that one needs to have a least an estimate of their size.

It should be doable even in current form by using the bbox from get_tightlayout() and recalculating the layout, but i still have to implement this corretcly. A

**Comment by jklymak** [comment] 2017-08-01 04:45
OK, I was thinking about taking a stab at this based on some prodding from @tacaswell. Thanks to @Tillsten excellent prototype, I think it should be doable.

*However*, I'm not clear on the exact plan here.  Would this be something called *after* an initial render like `tight_layout()` is called now?  Or would it attempt to do this at draw time like @Tillsten 's example?  

As noted above, the latter is harder because we don't know the size of the ticklabel elements before they are rendered; we don't even know how many tick labels there are!  (I admit to being a little befuddled - if we change the size of the yaxis then the number of y-ticks could change, so we are stuck in a bit of a confusing loop of hoping the yticklabels don't get wider or more narrow.)

It seems to me that the easiest way for this to all work would be as a static "clean-up" like `tight_layout` is already.  Another advantage to this approach is that we may not need to actually re-implement any of the artists - all the calculations could be done virtually, and then the results used to adjust the already existing artists.

**Comment by njsmith** [comment] 2017-08-01 06:31
I don't see how running it after the initial render makes a difference, conceptually. If changing the layout can change the size of elements and invalidate the layout, then that's something that needs to be dealt with whenever the layout is applied. It seems like you either need to find some way to avoid this happening (can you get a decent upper bound on the label size? can you bound the circumstances in which layout affects axis limits?), or else use some kind of render/layout/render/layout/... iterate-until-you-find-a-fixpoint algorithm, and if you're doing that then having 1 render done ahead of time doesn't make much difference.

-----

BTW, I thought this thread on the beeware-developers list was interesting, about why they switched their "Toga" gui library from using Cassowary to using a CSS-flexbox-style layout model:
https://groups.google.com/forum/#!msg/beeware-developers/4rmWFePjmmI/udPsqKHuB7QJ

The problem of laying out a GUI so that it automatically looks good on arbitrary devices is very different from the problem of laying out a complex figure so that it looks good at a specific size, so I don't think the conclusions can be directly carried over, but it's worth reading about the specific issues they ran into.

**Comment by tacaswell** [comment] 2017-08-01 13:05
You need to at least pre-render the text as that is the only way to know what size it will be (as it depends on the font, the input string, the font size, and the dpi).  It should be possible to walk the artist tree and render just the text to get their sizes, adjust the layout, blank the canvas, and then draw everything.

Where the layout manager makes contact with fixed-aspect Axes is going to be fun.

I _think_ the biggest changes to any `Artist` would be to stick a constraints attribute on `Artist` so that you can walk the Artist tree and collect them.

The beeware thread is interesting! I think our use case is more in the "must look good at exactly this size" and less "needs to look good across and order of magnitude of sizes", but it would be very easy to talk me out of that position.

**Comment by jklymak** [comment] 2017-08-01 16:22
First, I'm a little ignorant of the low-level details of how rendering gets done, so forgive any ignorant statements.

But it seems if we are going to render all the ticklabels, one might as well render all the axes elements w/o the data artists.  

Is it really impossible to get the M-width for a font of a given size if we know the renderer w/o actually rendering?  It seems that knowing the M-width would be fine for most cases, and then one could count digits in the tickvalues.

**Comment by WeatherGod** [comment] 2017-08-01 16:28
IIRC, the main problem is the LaTeX renderer. It is pretty much a complete
blackbox to us. The results depend upon what the TeX preamble (which can
change the fonts and styling) and whatever the string is (which can also
apply bolding, italics, etc as part of its markup).

We do have code to do a first-pass estimation of text size. It is used in
the tight_layout() code, since it can run prior to the actual rendering.

**Comment by has2k1** [comment] 2017-08-01 16:29
Happy coincidence. I've been thinking about it too! @Tillsten example still works. kiwi solver needs a release but master branch works with python 3.

I'm kind of the same view as @tacaswell, pre-render the text but I was thinking of a scratch canvas, hadn't thought of a blanking operation to reuse the same canvas. In the ideal situation, `tight_layout` should serve no purpose.

Here is my plan to clear the cobwebs on this. Slightly extend @Tillstens example to cover the main deficiencies of `gridspec`;

1. Make possible constrained stacking (vertical, horizontal) of text *around the axes* and *around the grid*.
2. Make possible to have stacked legends/`AnchoredOffsetBox` *around the grid* and/or *around the axes*.

The first should allow us to get an understanding about how to deal with titles, subtitles and captions to plots. It is also a precursor to tackling the axis texts. The second for it allows for it would be a requirement for multiple gridspecs with in a figure. These two cover (I think all) the cases of artists that draw outside the axes.

Hopefully, with those out of the way we would be able to come up a more complete plan.

---

>  "must look good at exactly this size" 

I have a feeling figure size will still be more of a ballpark number than an strict number.

**Comment by jklymak** [comment] 2017-08-01 17:41
What is missing, to me, in @Tillsten  example is that it does not line up the actual axes spines between the subplots.  Maybe there are some cases where that is OK, but 98% of the time, I think you want a constraint on the actual spine, not on the extent of the spine plus its ticks.  If it weren't for the issue of not knowing how big ticklabels will be, and how big x- and y- labels would be this would be easy.  

Here is a start of the rules I'd propose a layout manager follows.  I'm sure there are lots of cases that are not dealt with here, but I think we'd to nail the basics down before doing fancier layout.

(I appologize if some of the names I used below are different than @Tillsten used.  We can name these elements what we want).

## Basic axes layout:

Here are the elements I see constaining the *basic* layout of an axes inside a "container" of some sort (either the figure, or a fraction of a figure set by a sublotspec).  

From left to right: 
   - hpad-left:         fixed
   - labelbox-left:   adjusts to width of label
   - tickbox-left:     adjusts to width of ticklength+width of biggest ticklabel
   - axis-box:          adjusts width and left
   - tickbox-right    optionally zero width
   - labelbox-right  optionally zero width
   ? colorbar-right  adjusts to width of colorbar (which is its own axes)
   - hpad-right        fixed
From bottom to top:
   - hpad-bottom:        fixed
   ? colorbar-bottom:  adjusts to height of colorbar (which is its own axes)
   - labelbox-bottom:  adjusts to height of label
   - tickbox-bottom:    adjusts to height of ticklength+height of biggest ticklabel
   - axis-box:                adjusts height and bottom
   - tickbox-top            optionally zero height
   - labelbox-top          optionally zero height
   - hpad-top                fixed
   

## Interaction between axes: subplots

If an axis is created within the context of a subplot call, we assume the axes containers are all the same size, and that the user wants all the subplot axes to have the same offset from the edges of the containers.  So the width of the axes would be the constrained width of the smallest axes after it has made room for the fixed-width elements.  

There probably should be an API to align axes that are not made w/in the `subplot` paradigm.  

There should probably be an API to allow subplots to *not* align, i.e. to let each subplot do its layout independently.  One could argue which should be default, but I'd argue strongly that most papers I've seen published in journals usually align the axes spines.  

There is the possibility to align the label boxes as well i.e. all the vertically stacked label boxes could have the same "left" (or right?) property.  

## Colorbars:

To my mind, there are two kinds of colorbar placement. The first is per-axis, and that is accounted for in the colorbar-right and colorbar-bottom boxes above.  I like keeping this as an optionally zero-width axes layout property because then if you add a colorbar to one subplot, all the other associated subplots can be constrained to change width to match.  Maybe thats not always wanted, but 95% of the time when I put a colorbar on one subplot, I want the matching subplots to shrink too, even if they do not have colorbars because they have the same x limits.  If the API to let subplots be independent is called, then obviously this constraint would not occur.  

The second kind of placement is one colorbar for many axes.  I'd propose to handle this as a gridspec where the original container is retained, and two new containers are made, one for the subplots and one for the colorbar.  This seems to require an API where you can specify a gridspec as "tight" around its contents and another that "stretches" to fill its outer container.

**Comment by jklymak** [comment] 2017-08-02 23:21
Somewhat modifed version of @Tillsten  layout manager that tries to take into account the tick and ticklabel sizes.  It places the axes elements "somewhere"  and then looks at the difference between the `ax.get_tightbbox(self.renderer)` and `ax.get_position()` to descide how much space there needs to be for the ticks and their labels.  Subsequent resizes let it iterate on this.

Its fragile to backends.  It mostly seems to work for Qt5Agg.  It doesn't work for `macosx` or `nbagg` both of which seem to do funky things with the figure transforms, maybe due to Retina?

https://github.com/jklymak/mplconstrainedlayout

<img width="645" alt="example" src="https://user-images.githubusercontent.com/1562854/28899183-84be299e-779e-11e7-996d-3f8a57a53939.png">

**Comment by anntzer** [comment] 2017-08-02 23:58
You may want to give a try with https://github.com/matplotlib/matplotlib/pull/8771 -- not so much because of the cairo rendering, but because that PR tries to cleanly separate the rendering part (by Agg) from the windowing part (by Qt or whatever GUI toolkit you're using).

**Comment by jklymak** [comment] 2017-08-03 02:05
@anntzer That has quite a few dependencies that don't seem trivial to install on OS X, unless I'm missing something...

**Comment by jklymak** [comment] 2017-08-03 02:10
What I am still not following is how people think this would work w/o knowing

**Comment by anntzer** [comment] 2017-08-03 02:10
To use cairo, possibly.  But the refactor of Qt5Agg doesn't have any dependency.

**Comment by jklymak** [comment] 2017-08-03 02:24
@anntzer  As usual, I was missing something `condo install pyqt=5` worked fine ;-)  Sorry for the noise...

**Comment by jklymak** [comment] 2017-08-03 16:46
@anntzer 

> You may want to give a try with #8771 -- not so much because of the cairo rendering, but because that PR tries to cleanly separate the rendering part (by Agg) from the windowing part (by Qt or whatever GUI toolkit you're using).

OK, this still has trouble printing.  

  - If I run using your pyQT5 and use the pring button to create a png all the axes labels move around.  Similarly if I do `fig2.savefig('Example.png')`.
  - If I run using the pdf backend and `fig2.savefig('Example.pdf')` the results look great.
  - If I run using the pdf backend and `fig2.savefig('Example.png')` again the labels don't get positioned properly.  

If I use backend `cairo` then I get the following backtrace:

```
Traceback (most recent call last):
  File "layout.py", line 453, in <module>
    fl = FigureLayout(fig2)
  File "layout.py", line 433, in __init__
    self.renderer = find_renderer(mpl_figure)
  File "layout.py", line 423, in find_renderer
    fig.canvas.print_pdf(io.BytesIO())
  File "/Users/jklymak/anaconda3/envs/matplotlibqt5cairo/lib/python3.6/site-packages/matplotlib/backends/backend_cairo.py", line 454, in print_pdf
    return self._save(fobj, 'pdf', *args, **kwargs)
  File "/Users/jklymak/anaconda3/envs/matplotlibqt5cairo/lib/python3.6/site-packages/matplotlib/backends/backend_cairo.py", line 504, in _save
    renderer.set_ctx_from_surface(surface)
  File "/Users/jklymak/anaconda3/envs/matplotlibqt5cairo/lib/python3.6/site-packages/matplotlib/backends/backend_cairo.py", line 110, in set_ctx_from_surface
    self.set_width_height(surface.get_width(), surface.get_height())
AttributeError: 'cairo.PDFSurface' object has no attribute 'get_width'
```

So, printing is a bit of an issue.

**Comment by anntzer** [comment] 2017-08-03 19:31
1) was probably due to the figure-saving codepath falling back on Agg for png or matplotlib's own pdf/ps/svg backends.  Now fixed: everything should use cairo's implementations.
2) was due to the fact that the code paths were not tested.  Also fixed.

**Comment by jklymak** [comment] 2017-08-03 21:21
https://github.com/jklymak/mplconstrainedlayout now has a colorbar implemented as an `AxesContainer` stacked inside the main plot `AxesContainer`.  Could just as easily be a legend.   So this allows nesting of axes.  You of course need to decide what sort of contraints to set on such an axis - here I made it's width and height fixed fractions of the `raw_axes` that contains the `pcolormesh`, and made it vertically centered on that axis.  It has a default pad.  Note how the upper axis became smaller as well (obviously you wouldn't always want that).

<img width="806" alt="figure_0_and_readme_md_ ___dropbox_layout_and_matplotlib_colorbar_-_google_search" src="https://user-images.githubusercontent.com/1562854/28944168-6b2208da-7856-11e7-812e-160eae1dd4d3.png">

**Comment by jklymak** [comment] 2017-08-04 05:27
Printing issue was due to the fact that @Tillsten was placing the text using pixel rather than figure units.  Caused a bunch of label funkiness, but now it all works well.  Modified the code to do the constraint in figure units as well.

**Comment by jklymak** [comment] 2017-08-04 14:08
I think I understand what is going on well enough via @Tillsten  example to make progress.  Now Taking this back a step, some questions:

`ax.get_tightbbox(renderer)` gives the bounding box for the whole axis including the x and y labels and title.  The code for placing these items is quite mature, and to my mind does the "right" thing, and is deterministic (i.e. the `xlabel` goes to the left/right of the ticks.  )  

So what are the strong reasons for getting more granular than an `axes` object (spines+all labels) in the layout manager?  The only one I've personally come across is allowing right-justification of tick labels that are on the right hand side of an axis.  The issues referenced above don't seem to pertain to anything that can't be handled at a level above an `axes` object: i.e. lining up `axes` or their spines, making sure they fit on the canvas, and adding various parasitic axes (colorbar, legend, suptitle).  For a first pass, doing things at the axis level (and higher level objects like suptitles, colorbars, legends) would be far easier than going all the way down to the artist level.  What am I missing?  

I'm still after some guidance on how this gets executed.  When in matplotlb does the constraint solver get executed?  

I have lots of API questions, but I think guidance on if an axes-level constraint system would be good enough to start would help make that task a lot easier.

**Comment by WeatherGod** [comment] 2017-08-04 15:35
Possible use-cases (more of a devil's advocate, and might not be
appropriate for a constraints solver anyway):
  - automatic placement of legend within the plot box (we have code that
does this a bit right now)
  - automatic placement of contour labels (via clabel(), which isn't great
in its current form)

Another possibility is making the constraints solver available to the
end-user for situations like automatically adjusting text and annotations
so they don't overlap each other. This is a situation I am running into
right now with plotting wildfires on a map and labeling them with names. As
I zoom out, the labels become useless.

**Comment by WeatherGod** [comment] 2017-08-04 18:47
That makes sense. Probably the only complication I can think of is our
imshow() behavior, which does some weird feedback to the axes aspect ratio.

**Comment by WeatherGod** [comment] 2017-08-04 18:49
oooh, just thought of another thing -- spine placements

https://matplotlib.org/examples/pylab_examples/spine_placement_demo.html

**Comment by anntzer** [comment] 2017-08-05 14:31
(going to have on-and-off internet access in the coming days, so don't wait for me :-))

**Comment by jklymak** [comment] 2017-08-10 05:10
Progress report:  I have made a new package `LayoutBox` that implements a `LayoutBox` class and provides a bunch of helper functions.  Heavily based on @Tillsten .  Not properly documented yet etc.
https://github.com/jklymak/mplconstrainedlayout/blob/master/LayoutBox.py

I've also made a test notebook for this class: https://github.com/jklymak/mplconstrainedlayout/blob/master/TestLayoutBox.ipynb

The notebook starts to get towards an API for lining up axes using the layout manager.  See the section with `constrained_layout(fig, axs)`, where `axs` is a list of axes (in the figure, I hope) that you want to be constrained together.  They will stay within their gridspec, and constraining them together will give them all the same label, ticklabel, title - accommodating margins.  

I need to work on implementing nested gridspecs, but I think this is moving in the right direction.  Whether this happens automatically at some point in the future, or gets added as a bolt-on method to `figure` (i.e. `fig.contrain_layout()`) can be up for discussion once the rest of the ideas are fleshed out.

Any comments/criticisms most welcome.

**Comment by jklymak** [comment] 2017-08-14 04:59
A draft of a MEP (in notebook format)  https://github.com/jklymak/mplconstrainedlayout/blob/master/DraftMEP.ipynb

Comments very welcome.  As you can see, the scope here is pretty modest, and maybe not quite what folks were thinking, so any suggestions would be great.  Of course the same ideas could be used deeper inside an "axes", but I kept the scope "axes and larger" for now.  I've managed to implement most of this already, but not very cleanly yet.   If there is positive feedback I'll keep going.  If not, I'm happy to let someone else run with the ball.  

@tacaswell

**Comment by jklymak** [comment] 2017-08-23 05:33
Update: 

https://github.com/jklymak/matplotlib/tree/constrainedlayout is a fork of relatively recent master that is close to pull release.  

Right now all it does it "constrained_layout" on subplots, (nested) gridspecs, and colorbars.  Todo is to add suptitle support and maybe legends.  

Note that right now there are two API changes:

  1. gridspec has to be called with a figure argument.  Thats a pretty big non-backwards compatible change.  I'm considering how to get rid of it.  
  2. To get the constrained layout you specify `plt.figure(costrained_layout=True)`.  

I have tests, but I haven't put them in proper test format yet.

**Comment by jklymak** [comment] 2017-08-23 23:40
Update: See PR #9082  (WIP)

**Comment by dstansby** [comment] 2018-02-13 12:35
Closing since #9082 went into `2.2`

**Closed by dstansby** 2018-02-13 12:35 UTC
Labels: MEP needed, geometry manager
