### ISSUE TITLE
Home button is useless on Jupyter Notebook

### ISSUE THREAD

**Issue by songyuc** [matplotlib/matplotlib#15707] opened 2019-11-17 15:04 UTC
### Bug report

**Bug summary**

I plotted a 3D curve on Jupyter Notebook. I rotated the produced image using my mouse, and I wanted to use the Home button to reset it, because Home's comment says _Reset the original view_. However, after clicking Home button, there was nothing happened.

**Code for reproduction**

```python
# Paste your code here
#
#
%matplotlib notebook
# %matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import Ridge
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.gca(projection='3d')
# 如果不加这句话，图形就无法显示


model = Ridge(alpha=0.3)
model.fit([[0,0],[0,0],[1,1],[2,2]],[0,0.1,1,2])
print(model.coef_)
print(model.intercept_)

x = np.linspace(-10, 10, 1000)
y = np.linspace(-10, 10, 1000)
z = np.add(x, y)

ax.plot(x, y, z)
plt.show()
```
(Please ignore the comment in Chinese, because I am a Chinese student)

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

![图片](https://user-images.githubusercontent.com/27288110/69009062-d1506600-098c-11ea-9053-45dae3013551.png)
(I have rotated the image with my mouse)

**Expected outcome**

I want to use Home button to reset the image to the initial view, but Home button did not work.

**Matplotlib version**

  * Operating system: Win10
  * Matplotlib version: 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.7.3
  * Jupyter version (if applicable): 5.7.8
  * Other libraries: 

I installed matplotlib by Anaconda.

**Comment by ImportanceOfBeingErnest** [comment] 2019-11-17 16:39
I suppose this is a duplicate of https://github.com/matplotlib/matplotlib/issues/11178

**Comment by timhoffm** [comment] 2019-11-17 17:21
The buttons work for 2D plots. So this seems really to be a duplicate of #11178. Please report back if you encounter the problem with 2D plots.

**Closed by timhoffm** 2019-11-17 17:21 UTC
Labels: mplot3d

**Comment by 0xF4D3C0D3** [comment] 2019-11-17 17:57
I found even with 2d plot, after the `gca`, this can be reproduced.

mcve:
```python
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.gca()
ax.plot([1, 2, 3], [3, 6, 9])
```

**Comment by songyuc** [comment] 2019-11-18 07:16
Thank you, guys, for all your kind reponses.
