### ISSUE TITLE
Wrong labels plotting categorical

### ISSUE THREAD

**Issue by chedatomasz** [matplotlib/matplotlib#16918] opened 2020-03-26 15:07 UTC
### Bug report

Plotting pandas categorical variables with pyploy.plot and pyplot.scatter gives different result - labels are shifted

**Code for reproduction**
The actual code is a jupyter notebook, however I cannot attach that here.

```python
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import random

xs = [random.randint(1, 100) for i in range(100)]
ys = [random.choice(['a', 'b', 'c', 'd']) for i in range(100)]

good = pd.DataFrame({'x':xs, 'y':ys})
bad = good.astype({'y':'category'})

plt.plot(bad.x, bad.y, 'o')
plt.show()

plt.scatter(bad.x, bad.y)
plt.show()
```

**Actual outcome**

The plots are the different (labels are shifted)

scatter:
![scatter](https://user-images.githubusercontent.com/47541285/77661694-448d6880-6f7b-11ea-9f47-4dd9f488e9bf.png)

plot:

![plot](https://user-images.githubusercontent.com/47541285/77661696-4525ff00-6f7b-11ea-9376-d363c727b7ea.png)

**Expected outcome**

The plots are the same

**Matplotlib version**

  * Operating system: AWS Linux
  * Matplotlib version: 3.1.3
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.7.6
  * Jupyter version (if applicable): 6.0.3
  * Other libraries:  pandas 1.0.1

installed from conda

**Comment by timhoffm** [comment] 2020-03-27 01:15
As of master, I do get the same output for both. Please recheck with the latest released version 3.2.1.

**Comment by tacaswell** [comment] 2020-03-27 16:09
Does this behavior depend on the pandas version as well?

**Comment by timhoffm** [comment] 2020-03-27 16:27
I've been using pandas 0.24.1.

**Comment by tacaswell** [comment] 2020-03-27 16:38
I also don't see it with pandas ~master branch and our master branch.

**Comment by ImportanceOfBeingErnest** [comment] 2020-03-27 17:04
I can reproduce this with matplotlib 3.1.3 and pandas 1.0.1.  
I cannot reproduce this with matplotlib 3.2.0 and pandas 1.0.1.
So I'd say chances are pretty high that this is fixed already.

**Comment by timhoffm** [comment] 2020-03-29 16:54
In summary, it works for 3.2.0+, tested with different versions of pandas (but not every version combination of matplotlib and pandas).

I'm closing as already fixed. Please report back, in case you see this in matplotlib 3.2.0+.

**Closed by timhoffm** 2020-03-29 16:54 UTC
Labels: categorical, third-party integration
