### ISSUE TITLE
imshow() producing "inverted" colors since 3.0.3

### ISSUE THREAD

**Issue by cyclehome** [matplotlib/matplotlib#14293] opened 2019-05-21 14:32 UTC
### Bug report

**Bug summary**

Since 3.0.3 imshow() produces "inverted" colors, instead of just including the image as is.

**Code for reproduction**

```python
from PIL import Image
import matplotlib.pyplot as plt

img = Image.open("map.png")
plt.imshow(img)
plt.savefig("plot.png")
```

with this image as input:
![map](https://user-images.githubusercontent.com/48286302/58104034-f29de880-7bdb-11e9-9031-6660d0650a5d.png)

**Actual outcome**
![plot](https://user-images.githubusercontent.com/48286302/58102817-d13bfd00-7bd9-11e9-9e20-034f7d980ea1.png)

**Expected outcome**
![plot2](https://user-images.githubusercontent.com/48286302/58102968-13653e80-7bda-11e9-8cbb-4c2aafab27a5.png)
(until 3.0.2)

**Matplotlib version**

  * Operating system: win 7/10
  * Matplotlib version: 3.0.3, 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.2
  * Jupyter version (if applicable):
  * Other libraries: Pillow (6.0.0)

matplotlib installed from pip

**Comment by ImportanceOfBeingErnest** [comment] 2019-05-21 17:21
Not sure if this was intentional in https://github.com/matplotlib/matplotlib/pull/13405, so marking as Release Crititical.

**Comment by tacaswell** [comment] 2019-05-21 21:01
This looks like a regression to me.  I don't think the colors are inverted, I think one of the channels is getting color mapped....

**Comment by jklymak** [comment] 2019-05-21 21:09
Yeah basically we dropped support for PIL arrays, and we apparently never had tests for them...

**Comment by cyclehome** [comment] 2019-05-22 07:24
???
3.1.0 documentation for Axes.imshow() says for the first parameter:

> X : array-like or PIL image

However, if PIL support is dropped indeed, is this the intended way of doing it now:

`    plt.imshow(np.array(list(img.convert('RGBA').getdata())).reshape(img.height, img.width, 4))
`

Or is there a shorter way?

**Comment by jklymak** [comment] 2019-05-22 10:49
Sorry didn’t mean to say we meant to drop support, just that we did inadvertently.

**Comment by efiring** [comment] 2019-05-25 18:39
@anntzer I suspect this is something related to your #13405, and you will quickly see how to fix it.

**Closed** 2019-05-27 13:49 UTC
Labels: Release critical
