### ISSUE TITLE
[Bug]: Calling matplotlib.pyplot.show() outside of matplotlib.pyplot.rc_context no longer works

### ISSUE THREAD

**Issue by JohannesGaessler** [matplotlib/matplotlib#23172] opened 2022-06-01 08:53 UTC
### Bug summary

Creating a plot inside of matplotlib.pyplot.rc_context and then calling matplotlib.pyplot.show() outside said context causes the program to freeze.

### Code for reproduction

```python
import matplotlib.pyplot as plt

with plt.rc_context():
    plt.plot([1, 3, 2])

plt.show()
```

### Actual outcome

The program freezes.

### Expected outcome

The plot is shown.

### Additional information

* matplotlib.pyplot.savefig() works as expected.
* The bug did not occur in earlier versions.
* The bug does not occur when using Jupyter, only when using the regular Python interpreter.
* The bug does not occur if plt.show() is called inside of plt.rc_context.

### Operating system

Linux, 5.17.9-1-MANJARO, all packages up-to-date

### Matplotlib Version

3.5.2

### Matplotlib Backend

QtAgg

### Python version

3.10.4

### Jupyter version

3.4.2

### Installation

Linux package manager

**Comment by jklymak** [comment] 2022-06-01 09:26
I cannot reproduce on master, MacOS, Qt5Agg, from the interpreter.  Do you have something interesting in your matplotlibrc?

**Comment by oscargus** [comment] 2022-06-01 09:29
I have also tried on main with CentOS, both using python and ipython interpreters, and it does not happen here either.

**Comment by JohannesGaessler** [comment] 2022-06-01 09:52
> Do you have something interesting in your matplotlibrc?

I have made no changes to my global matplotlibrc file.

I also get the bug when using ipython.

Also perhaps I should attach the stack trace I get when interrupting the process:

```
KeyboardInterrupt                         Traceback (most recent call last)
File ~/Projects/snek/plot_no_show.py:6, in <module>
      3 with plt.rc_context():
      4     plt.plot([1, 3, 2])
----> 6 plt.show()

File /usr/lib/python3.10/site-packages/matplotlib/pyplot.py:389, in show(*args, **kwargs)
    345 """
    346 Display all open figures.
    347 
   (...)
    386 explicitly there.
    387 """
    388 _warn_if_gui_out_of_main_thread()
--> 389 return _get_backend_mod().show(*args, **kwargs)

File /usr/lib/python3.10/site-packages/matplotlib/backend_bases.py:3544, in _Backend.show(cls, block)
   3542         block = True
   3543 if block:
-> 3544     cls.mainloop()

File /usr/lib/python3.10/site-packages/matplotlib/backends/backend_qt.py:1054, in _BackendQT.mainloop()
   1052 @staticmethod
   1053 def mainloop():
-> 1054     with _maybe_allow_interrupt(qApp):
   1055         qt_compat._exec(qApp)

File /usr/lib/python3.10/contextlib.py:142, in _GeneratorContextManager.__exit__(self, typ, value, traceback)
    140 if typ is None:
    141     try:
--> 142         next(self.gen)
    143     except StopIteration:
    144         return False

File /usr/lib/python3.10/site-packages/matplotlib/backends/qt_compat.py:276, in _maybe_allow_interrupt(qapp)
    274 signal.signal(signal.SIGINT, old_sigint_handler)
    275 if handler_args is not None:
--> 276     old_sigint_handler(*handler_args)

KeyboardInterrupt: 
```

**Comment by JohannesGaessler** [comment] 2022-06-01 09:56
Switching the backend seems to fix the issue.
With the backend "GTK3Agg" the bug does not occur.

**Comment by JohannesGaessler** [comment] 2022-06-01 09:58
I think what actually happens is that the plot window is not shown.

**Comment by jklymak** [comment] 2022-06-30 08:37
I think your install is just bad - perhaps crossed Qt libraries.  I don't think we have an action here, but if you have further debugging details we can chase down, let us know!

**Comment by JohannesGaessler** [comment] 2022-06-30 09:40
Something strange is definitely going on here.
I was trying to figure out which of the backends specifically causes problems.
However, when manually setting a backend with the MPLBACKEND environmental variable, I was not able to reproduce the behavior I described in the OP with any of the available backends.
The backends I tested: ['GTK3Agg', 'GTK3Cairo', 'GTK4Agg', 'GTK4Cairo', 'MacOSX', 'nbAgg', 'QtAgg', 'QtCairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']

What's more, when adding the following print statement to my code the plot is shown correctly:

`
import matplotlib as mpl
import matplotlib.pyplot as plt

print(mpl.get_backend())

with plt.rc_context():
    plt.plot([1, 3, 2])

plt.show()
`
Console output: QtAgg

This suggests to me that the issue may be caused by matplotlib after all.

**Comment by jklymak** [comment] 2022-06-30 09:48
So I'm deeply confused.  What _does_ cause the error?

**Comment by jklymak** [comment] 2022-06-30 10:46
Some of the package managers do things with backends as well.  It would be good to know how we are to repo this.

**Comment by tacaswell** [comment] 2022-06-30 18:27
I strongly suspect that this will be fixed by https://github.com/matplotlib/matplotlib/pull/23299

**Comment by tacaswell** [comment] 2022-06-30 18:45
This is my story of what is going on:

1. the default backend is a "find a working GUI".  When you access the value we resolve it and then write that value back (remember this point)
2. we used to resolve this at pyplot import time, but not actually start the UI application etc (which caused the bug 89159614b349ff5f45bc4d49202362ddcd28345f fixed when we picked pyqt6 and the user tried to use pyqt5)
3. to solve that we stopped resolving the backend at pyplot import time (it seemed innocent enough!)
4. rcParams is a `dict` subsclass with some validation on `__getitem__` / `__setitem__`
5. with `rc_context` we stash everything in the rcparams via the `dict` methods which go around our logic (because we know they are valid, no reason to re-do the work)
6. in the context manager you create a figure which finally triggers the backend resolution (that as as side effect updates the backend in rcParams)
7. when exiting the context we use `dict` methods to reset the rcparam values including going back to our internal sentinel value.  Which half resets the backend.
8. This go wrong (I would have to trace the code to sort out exactly what is going wrong)

The reason adding the print fixes it is you resolve the backend before the context manager so it does not get changed.  Similarly if you explicitly set the backedn via `MPLBACKEND` the fallback logic is never involved so it all works.


https://github.com/matplotlib/matplotlib/issues/23298 is a different description of the same underlying problem.

**Comment by tacaswell** [comment] 2022-06-30 18:45
@JohannesGaessler Thank you for putting so much effort into chasing this down and I apologize for sending you on a wild goose chase.

**Comment by JohannesGaessler** [comment] 2022-06-30 19:39
I can confirm that when using the example code in the OP the plot is shown correctly on my machine when installing from the matplotlib master branch.
The more complex application that I actually care about also works correctly with the matplotlib master branch.
I would consider this issue to be resolved from my end.

**Comment by jklymak** [comment] 2022-06-30 20:02
OK, that makes sense as to why it worked for us and not you!  Sorry for not checking out 3.5.2 on my end!

**Closed** 2022-06-30 20:03 UTC
Labels: status: needs clarification
