### ISSUE TITLE
[Bug]: missing icons

### ISSUE THREAD

**Issue by Stoiber-dkar** [matplotlib/matplotlib#29293] opened 2024-12-12 10:44 UTC
### Bug summary

When using matplotlib==3.9.3 with PyGObject and Gtk4 I get errors for missing .svg files for the buttons. The Code works with 3.9.2

### Code for reproduction

```Python
import gi
import matplotlib.pyplot as plt

from matplotlib.backends.backend_gtk4 import NavigationToolbar2GTK4 as NavigationToolbar
from matplotlib.backends.backend_gtk4agg import FigureCanvasGTK4Agg as FigureCanvas
from matplotlib.figure import Figure

# Use PyGObject with GTK4
gi.require_version("Gtk", "4.0")
from gi.repository import Gtk


# Create a GTK4 application
class App(Gtk.Application):
    def __init__(self):
        super().__init__(application_id="com.example.matplotlibgtk4")

    def do_activate(self):
        # Create a main window
        win = Gtk.ApplicationWindow(application=self)
        win.set_title("Matplotlib + GTK4 Test")
        win.set_default_size(400, 200)

        fig = Figure(figsize=(8, 6))
        ax = fig.add_subplot(111)
        ax.plot([1, 2, 3], [4, 5, 6])
        canvas = FigureCanvas(fig)
        toolbar = NavigationToolbar(canvas)

        box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        box.append(toolbar)
        box.append(canvas)

        win.set_child(box)

        win.present()


if __name__ == "__main__":
    app = App()
    app.run([])
```

### Actual outcome

NavigationToolbar Buttons have Icon replacement and console errors:
Gtk-WARNING **: 11:40:42.561: Failed to load icon <path>/.venv/lib/python3.10/site-packages/matplotlib/mpl-data/images/home-symbolic.svg: Error opening file <path>/.venv/lib/python3.10/site-packages/matplotlib/mpl-data/images/home-symbolic.svg: No such file or directory

### Expected outcome

Gtk-WARNING and Buttons having Icons

### Operating system

Ubuntu 22.04 on WSL2

### Matplotlib Version

3.9.3

### Matplotlib Backend

backend_gtk4agg

### Python version

3.10

### Installation

pip

**Comment by greglucas** [comment] 2024-12-12 15:59
Closing as this is duplicate of: https://github.com/matplotlib/matplotlib/issues/29229

**Closed by greglucas** 2024-12-12 15:59 UTC
