### ISSUE TITLE
release 2.0.1 has qt4-incompatible code in backend_qt5.py

### ISSUE THREAD

**Issue by miketrumpis** [matplotlib/matplotlib#8570] opened 2017-05-04 14:45 UTC
### Bug report

In tag 2.0.1 the NavigationToolbar2QT includes an unchecked call to a Qt5 feature:

`pm.setDevicePixelRatio(self.canvas._dpi_ratio)`

https://github.com/matplotlib/matplotlib/blob/v2.0.1/lib/matplotlib/backends/backend_qt5.py#L587-L592

This is strange, b/c it's not there in tag 2.0.0 *and* it's not there in master!

I can reproduce this with a simple `plt.plot(np.random.randn(10))`.

`AttributeError: 'PySide.QtGui.QPixmap' object has no attribute 'setDevicePixelRatio'`

Issue goes away when I revert to 2.0.0

**Comment by jenshnielsen** [comment] 2017-05-04 14:57
This is a duplicate of #8565 #8563 and #8562 and will be fixed in 2.0.2 which should be released in the next few days

**Closed by jenshnielsen** 2017-05-04 14:57 UTC
