### ISSUE TITLE
errorbar pickling fails when specifying y error bars

### ISSUE THREAD

**Issue by hershen** [matplotlib/matplotlib#11716] opened 2018-07-20 20:03 UTC
### Bug report

**Bug summary**

Pickling errorbar plot with y axis error bars fails with error ```AttributeError: Can't pickle local object '_reverser.<locals>.freversed'```.

**Code for reproduction**

```python
import matplotlib.pylab as plt
import pickle as pl

fig = plt.figure()

x = [1,2,3]
y = [4,5,6]
err = [0.1,0.1,0.1]

plt.errorbar(x,y, yerr=err)
pl.dump(fig, open('errorbar.pl', 'wb'))
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: Can't pickle local object '_reverser.<locals>.freversed'
```

Same code without specifying the y axis errors (```plt.errorbar(x,y)```) pickles successfully.

**Matplotlib version**

  * Operating system: Ubuntu 17.10
  * Matplotlib version: 2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.2

**Comment by jklymak** [comment] 2018-07-20 21:17
Confirmed on 2.1.2, but this works for me on master and 2.2.2.  Closing as already fixed...

**Comment by hershen** [comment] 2018-07-20 22:32
Thanks for taking a look @jklymak. 
I'm get the same error even after upgrading to 2.2.2.

**Comment by ImportanceOfBeingErnest** [comment] 2018-07-20 22:41
The error does *not* occur for me on mpl 222, TkAgg on Windows. Possibly you did not run the code in the updated environment?

**Comment by hershen** [comment] 2018-07-20 22:52
```matplotlib.__version__``` reports 2.2.2:

```python
>>> import matplotlib
>>> matplotlib.__version__
'2.2.2'
>>> import matplotlib.pylab as plt
>>> import pickle as pl
>>> 
>>> fig = plt.figure()
>>> 
>>> x = [1,2,3]
>>> y = [4,5,6]
>>> err = [0.1,0.1,0.1]
>>> 
>>> plt.errorbar(x,y, yerr=err)
<ErrorbarContainer object of 3 artists>
>>> pl.dump(fig, open('errorbar.pl', 'wb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: Can't pickle local object '_reverser.<locals>.freversed'
```

I upgraded with ```pip install matplotlib --upgrade```. Is there something I'm missing?

Thanks for the help.

**Comment by anntzer** [comment] 2018-07-21 10:50
Actually the depends on the default cmap (likely set by the OP in the image.cmap entry in their matplotlibrc).  A simpler repro (on 2.2.2) is
```
import matplotlib.pylab as plt
import pickle as pl

fig, ax = plt.subplots()
ax.imshow([[0]], cmap="gnuplot_r")
pl.dumps(fig)
```
A similar issue (different message, but same picklability problem) occurs with "cubehelix_r" (my own default), or "gnuplot" (not reversed).

I agree that why this would show up with errorbar is curious.

**Comment by ImportanceOfBeingErnest** [comment] 2018-07-21 11:11
The list of colormaps that would produce this error. (They only come from two of the "categories", "Sequential (2)" and "Misc".)


Sequantial (2)
---------------
gist_yarg  
gist_yarg_r  
gist_gray  
gist_gray_r  
afmhot  
afmhot_r  
gist_heat  
gist_heat_r  


Miscellaneous
---------------
flag  
flag_r  
prism  
prism_r  
ocean  
ocean_r  
gnuplot  
gnuplot_r  
gnuplot2  
gnuplot2_r  
cubehelix  
cubehelix_r  
rainbow  
rainbow_r

**Comment by ImportanceOfBeingErnest** [comment] 2018-07-21 11:30
Those colormaps that are failing are exactly those that have their data defined as a lambda-function.

    _gist_heat_data = {
        'red': lambda x: 1.5 * x,
        'green': lambda x: 2 * x - 1,
        'blue': lambda x: 4 * x - 3,
    }

Would it be possible to use `dill` instead of `pickle`?

**Comment by WeatherGod** [comment] 2018-07-21 12:54
or we should not be defining the data as a lambda function, perhaps? I
would hate to pick up a new dependency just to address an edge case like
this

**Comment by jklymak** [comment] 2018-07-21 13:49
Wow great detective work!

**Comment by ImportanceOfBeingErnest** [comment] 2018-07-21 13:53
I don't know if `pickle` is really a dependency; but I think matplotlib advertises that figures are pickable (not dillable ;-)), so agreed, there should be a solution in the long run. Not sure though how that should look like, other then using function definitions and hence blowing up the `_cm.py` significantly.

**Comment by anntzer** [comment] 2018-07-21 13:56
It's not that bad, see #11723.

**Comment by hershen** [comment] 2018-07-21 16:15
I can confirm that my image.cmap is gist_heat_r which appears on @ImportanceOfBeingErnest 's list.

**Comment by anntzer** [comment] 2018-07-21 19:35
The cmap in the errorbar object comes from the vertical error bars, which are represented by a LineCollection, which is a ScalarMappable, which always has a cmap.

**Closed** 2018-08-18 16:55 UTC

**Comment by hershen** [comment] 2018-08-20 16:36
Thanks for the fix!
