### ISSUE TITLE
Cannot use threading with Mac OSX Backend

### ISSUE THREAD

**Issue by nils-werner** [matplotlib/matplotlib#5251] opened 2015-10-15 13:27 UTC
The following does not work on Mac OSX:

```
from __future__ import division

import threading
import time
import sys
import numpy as np
import matplotlib
matplotlib.use('MacOSX')

import matplotlib.pyplot as plt


class async_worker(threading.Thread):
    def __init__(self, fig, axis):
        threading.Thread.__init__(self)
        self.fig = fig
        self.axis = axis

    def run(self):
        i = 0
        while True:
            print "Run thread %d" % i
            sys.stdout.flush()
            i += 1
            time.sleep(0.1)


def main():
    fig = plt.figure()
    ax = fig.add_subplot(1, 1, 1)
    ax.plot(np.random.rand(251, 1))

    async_worker(fig, ax).start()
    plt.show()


if __name__ == "__main__":
    main()
```

I expect to see "Run thread" repeated every 0.1 seconds, no matter if I interact with the plot or not. Instead I only see it repeat when I click and drag around in the MPL figure.

When switching to `matplotlib.use('TkAgg')`, the second thread runs as expected.

**Comment by mdboom** [comment] 2015-10-15 15:22
Cc: @mdehoon

**Comment by mdehoon** [comment] 2015-10-16 04:17
I cannot replicate this with the current matplotlib in master; I get the same behavior with the MacOSX backend and the tkagg backend.
Which version of matplotlib are you using?
Can you try with the matplotlib release candidate:
https://github.com/matplotlib/matplotlib/releases/tag/v1.5.0rc2

**Comment by nils-werner** [comment] 2015-10-16 10:47
I have the same problem with 1.4.3 and after cloning and `pip install -e`ing e7e8bcb42e3e: The second thread only runs when I am moving my mouse.

**Comment by mdehoon** [comment] 2015-10-16 11:49
I can confirm the bug if I have interactive : False in matplotlibrc ;
the bug does not appear if I set interactive : True.
@nils-werner  Can you confirm this?

**Comment by nils-werner** [comment] 2015-10-16 11:52
When I add `plt.interactive(True)` to the top of the script

 - The thread runs
 - Matplotlib does not plot anything, the window seems to freeze (spinning ball of death)

**Comment by mdehoon** [comment] 2015-10-16 13:54
@nils-werner  Can you try with the latest master (or release candidate 1.5rc2)?
If I add plt.interactive(True) to the top of the script, the second thread runs and the window behaves normally.

**Comment by nils-werner** [comment] 2015-10-16 15:29
I tried it with both stable and master, the behaviour is always the same: The figure window stays blank.

**Comment by WeatherGod** [comment] 2015-10-16 15:31
how was python installed/built for you? Maybe it is a subtle difference
like the whole frameworks/nonframeworks issue?

**Comment by nils-werner** [comment] 2015-10-16 15:35
brew install python --with-brewed-openssl --framework

and fixed the virtualenv framework issue using https://github.com/gldnspud/virtualenv-pythonw-osx

**Comment by mdehoon** [comment] 2015-10-16 16:43
@nils-werner 
Can you try the following:
In the function ```static PyObject* show(PyObject* self)``` in src/_macosx.m, replace
```
    [NSApp run];
```
by
```
    Py_BEGIN_ALLOW_THREADS
    [NSApp run];
    Py_END_ALLOW_THREADS
```
That should get you the correct behavior in the non-interactive case.

**Comment by nils-werner** [comment] 2015-10-19 09:14
yes, that indeed fixes the issue!

**Comment by mdehoon** [comment] 2015-10-19 09:49
@nils-werner  We're not quite there yet; I have not yet been able to reproduce the spinning ball of death in the interactive case. Also there may be a more appropriate place to put the Py_BEGIN_ALLOW_THREADS / Py_END_ALLOW_THREADS block.

**Comment by mdehoon** [comment] 2015-10-23 08:12
@nils-werner  On second thought, since we are in the process of release candidates for the 1.5 release, perhaps it's better to wait with more extensive changes to _macosx.m. So if you could prepare a PR with the simply fix of putting Py_BEGIN_ALLOW_THREADS / Py_END_ALLOW_THREADS around [NSApp run], then I can accept it.

**Comment by tacaswell** [comment] 2015-10-24 16:36
@mdehoon Should this be closed or left open for a more through fix?

**Comment by mdehoon** [comment] 2015-10-25 01:37
@tacaswell  Let's leave it open. I will have another look after 1.5 final is out.

**Comment by nils-werner** [comment] 2015-11-02 09:03
I have discovered another issue while trying to `draw()` from another thread:

    from __future__ import division

    import threading
    import time
    import sys
    import numpy as np
    import matplotlib
    matplotlib.use('MacOSX')

    import matplotlib.pyplot as plt


    class async_worker(threading.Thread):
        def __init__(self, fig, axis):
            threading.Thread.__init__(self)
            self.fig = fig
            self.axis = axis

        def run(self):
            i = 0
            while True:
                self.fig.canvas.draw()
                print "Run thread %d" % i
                sys.stdout.flush()
                i += 1
                time.sleep(0.1)


    def main():
        fig = plt.figure()
        ax = fig.add_subplot(1, 1, 1)
        ax.plot(np.random.rand(251, 1))

        async_worker(fig, ax).start()
        plt.show()


    if __name__ == "__main__":
        main()

Whenever I click any of the navigation bar buttons, the entire process deadlocks. Again, when using `TkAgg`, this works just fine.

**Comment by mdehoon** [comment] 2015-11-07 01:52
You are trying to draw from the secondary thread, while typically you should draw from the main thread only. If you replace self.fig.canvas.draw by self.fig.canvas.invalidate, your script should work. Then the secondary thread merely informs the main thread that it should redraw itself, while the main thread does the actual drawing. I haven't done much testing with threads, so you may still run into some bugs; please let us know if you do.

**Comment by nils-werner** [comment] 2015-11-07 11:44
When I try to use `invalidate` I get

    AttributeError: 'FigureCanvasTkAgg' object has no attribute 'invalidate'

I tried in both mpl 1.4.3 and 1.5.0

**Comment by tacaswell** [comment] 2015-11-07 14:06
What does `matplotlib.get_backend()` return?  `invalidate` is an OSX backend specific thing, I would not expect it to work with `TkAgg`.

**Comment by mdehoon** [comment] 2015-11-08 13:25
You could use self.fig.canvas.draw_idle (which calls self.fig.canvas.invalidate on MacOSX backend). The draw_idle function is defined for all backends. In practice, this seems to work for the MacOSX backend only; tkagg gives "RuntimeError: main thread is not in main loop" and gtkagg gives a segmentation fault.

**Comment by nils-werner** [comment] 2015-11-12 09:50
Ah ok. Well obviously I want to write platform and backend independent code

**Comment by mdehoon** [comment] 2015-11-13 01:55
@nils-werner  Actually can you provide an example script that shows how you want to use threads in practice? From your current example, it's not clear to me what you are trying to achieve.

**Comment by mdehoon** [comment] 2015-11-25 12:42
Pull request #5562 provides a comprehensive fix for the first issue (October 15).
For the second issue (November 2), the following script should work:
```python
import threading
import time
import sys
import numpy as np
import matplotlib
matplotlib.use('MacOSX')
matplotlib.interactive(False)

import matplotlib.pyplot as plt


class async_worker(threading.Thread):
    def __init__(self, fig, axis):
        threading.Thread.__init__(self)
        self.fig = fig
        self.axis = axis

    def run(self):
        i = 0
        while True:
            self.axis.clear()
            self.axis.plot(np.random.rand(251, 1))
            self.fig.canvas.draw_idle()
            print "Run thread %d" % i
            sys.stdout.flush()
            i += 1
            time.sleep(0.1)


def main():
    fig = plt.figure()
    ax = fig.add_subplot(1, 1, 1)
    async_worker(fig, ax).start()
    plt.show()

if __name__ == "__main__":
    main()
```

**Comment by nils-werner** [comment] 2015-11-25 12:51
@mdboom this works on Mac OSX but not on Linux, right?

**Comment by jklymak** [comment] 2018-08-16 21:45
So far as I can tell the original issue now works in master on my mac, so I'm going to close this one.

**Closed by jklymak** 2018-08-16 21:45 UTC
