### ISSUE TITLE
Python 3.4 with Matplotlib 1.5 vs Python 3.6 with Matplotlib 2.1 

### ISSUE THREAD

**Issue by myak555** [matplotlib/matplotlib#10345] opened 2018-01-30 00:58 UTC
### Bug report

Inconsistent navigation toolbar behavior between major versions

**Bug summary**
Recently moved from (A) Matplotlib 1.5.0 to (B) Matplotlib 2.1.2

The same code produce:
Case A: a larger window with the toolbar displayed
Case B: a smaller window with the toolbar hidden
![image](https://user-images.githubusercontent.com/33710266/35541999-6df85330-05a9-11e8-9a45-d966ba6aac45.png)

**Code for reproduction**
Use any code from the example pages

**Expected outcome**
The toolbar behavior should be identical, or at least the change should be documented.
Personally I liked the behavior (A) better, as it saves the user a mouse click-and-drag movement (= welcome to CTS/RSI, folks) on every plot.
Alternatively, a way to control the bar appearance should be provided.

**Matplotlib version**
  * Operating system: Windows 10.0.16299 AMD64 
  * Matplotlib version: (A) 1.5.0 and (B) 2.1.2 (pip install)
  * Matplotlib backend: TkAgg
  * Python version: (A) 3.4.3 and (B) 3.6.4
  * Other libraries: numpy 1.13.3, scipy 1.0.0, PyQt4 4.11.4

**Comment by jklymak** [comment] 2018-01-30 01:03
The toolbar should still be there.  

Can you `plt.get_backend()` for the 2.1.2 version?  If its TkAgg, it may be useful to know the tk version you have.  Thanks!

**Comment by myak555** [comment] 2018-01-30 02:22
The backend reported is the same: TkAgg. I have Tcl/Tk version 8.6, installed together with Python 3.6

The navigation bar is still there (shortcut buttons work!), but most of the time the bar is invisible. By default, the graphics window opens with no bar.  To show the bar you must resize the window vertically or click on "Maximize" button (which is a pain, if you work with data).

I also mention that the same image 1500x1000 pixels  // plt.figure( figsize=(15,10)) // in version 1.5 occupied 1200x865 on screen (including the bar), and in version 2.1 takes 1500x1030 (no bar).  The image saved to disk is the same 1500x1000 pixels in both cases.  Seemingly, the version 1.5 applied some kind of scaling factor by default.  How is that documented?

**Comment by myak555** [comment] 2018-01-30 02:37
It seem the new version 2.1 does not honor the Windows 10 display setting "Change the size of text, apps and other items".  Version 1.5 behaved correctly.

**Comment by afvincent** [comment] 2018-01-30 02:52
@myak555 I suspect that the difference in the size of the displayed figure is due to the fact that Matplotlib 2+ now uses a 100 dpi on-screen value, while it was using only 80 dpi before (see the [what's new](https://matplotlib.org/2.0.2/users/dflt_style_changes.html#figure-size-font-size-and-screen-dpi) entry).

Not sure that it explains the other issues though :).

**Comment by myak555** [comment] 2018-01-30 03:12
@afvincent I confirm the screen resolution has nothing to do with the toolbar behavior.
setting mpl.rcParams['figure.dpi']  from 50 to 100 produces the plots of different screen resolution, none of them have the toolbar shown by default (all require the manual vertical resize to show).

**Comment by jklymak** [comment] 2018-01-30 05:35
Just to make sure you are starting clean, can you copy your old `~/.matplotlib/matplotlibrc`to `~/.matplotlib/matplotlibrcOld` just to make sure you don't have some old settings? 

Have you tried `matplotlib.use('Qt5Agg')`?  

Finally, you could send your debug info:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
import matplotlib.pyplot as plt
plt.plot(range(10))
```

I have no idea what the issue is, but these debugging steps may help.

**Comment by myak555** [comment] 2018-01-31 00:53
@jklymak:
1. Copied and verified I am using the original Lib\site-packages\matplotlib\mpl-data\matplotlibrc from the distribution. Same problem - the form starts with no bar visible.
2. With PyQt5 works correctly, but the toolbar is now above the plot. (I guess it's a new standard?)
3. The debug gives nothing
![image](https://user-images.githubusercontent.com/33710266/35598687-abaf4a68-0670-11e8-867f-5dd32435fec5.png)
4. The same code in Python 3.4 with matplotlib 1.5 work as expected: the bar is shown.

**Comment by jklymak** [comment] 2018-01-31 01:46
Oops, sorry about the debugging suggestion.  That'll be in place for 2.2!

**Comment by tacaswell** [comment] 2018-01-31 03:59
the qt toolbar has always been above the graph iirc.

Something is clearly going wrong with how we back the Tk window, how we compute how big the rasterized plot should be on the initial draw.  Do you have resize the window the full size of the tool bar or does it 'snap' to show the whole thing once it is resize at all?  If you do `fig.set_size_inches()` after you create the figure does it correctly show the toolbar?

I can not reproduce this issue in linux :/

> It seem the new version 2.1 does not honor the Windows 10 display setting "Change the size of text, apps and other items". Version 1.5 behaved correctly.

I suspect that this is due to the underlying tk or tk bindings (which we just use).  If you make a simple tk app does it respect the windows settings?  Might be worth checking if IDLE respects it as well.

**Comment by myak555** [comment] 2018-01-31 06:59
Please disregard the "Change the size of text, apps and other items," -- this is just a side note and has nothing to do with the bug.

The reproduction on my Windows 10 machine is as following

1. Run Python 3.4 with matplotlib 1.5 and a simple code:
![image](https://user-images.githubusercontent.com/33710266/35608108-5897a9c8-06a3-11e8-92ca-27fdf3388ec8.png)
Let's call it a "desired behavior"

2. Run the same code with Python 3.6 and matplotlib 2.1
![image](https://user-images.githubusercontent.com/33710266/35608367-8fe77114-06a4-11e8-8d39-9cabad4579ce.png)

3. To show the bar, grab the bottom of the window with mouse and pull down as shown:
![image](https://user-images.githubusercontent.com/33710266/35608497-1d0d820e-06a5-11e8-83a2-ccdea70b041c.png)
This is "undesired behavior", because I have to "grab-and-pull" about 500 windows every day.

4. The fig.set_size_inches() does not work if w and h are set identical to figsize:
![image](https://user-images.githubusercontent.com/33710266/35608793-63defbc6-06a6-11e8-8c89-39998bf7a2b4.png)

5. adding a little bit of height shows a tiny strip of the nav bar:
![image](https://user-images.githubusercontent.com/33710266/35608924-0f96c778-06a7-11e8-8ea4-17d938580941.png)

6. adding a lot of height shows the nav bar:
![image](https://user-images.githubusercontent.com/33710266/35609009-5b37fa3a-06a7-11e8-8a8d-d301f7206a18.png)
I guess, I can use it as a workaround, so no need to "grab-and-pull" all the time, but it looks like a bug to me. Users should not add magic lines to make the standard examples work correctly.

My PyQt4 is working perfectly, no issues with software other than matplotlib 2.1.x

**Comment by anntzer** [comment] 2018-01-31 07:31
fwiw I cannot reproduce with conda mpl2.1.2+py3.6+tkagg on Win7; don't have Win10 available for testing.

**Comment by tacaswell** [comment] 2018-01-31 14:09
Thanks for the very detailed report @myak555 !  Don't worry, we do think this is a bug :)

I can reproduce this after a fashion on linux if you drag the bottom of the window *up* you can hid the toolbar past some minimum height.  There is clearly something wrong with how we are packing the Tk window and it is deciding to truncate the toolbar in favor of the plot at some window sizes.

Is it possible to try mpl 1.5.1 with py 3.6 (just to reduce the number of things changing).

> My PyQt4 is working perfectly, no issues with software other than matplotlib 2.1.x

Did you mean tk here?

**Comment by myak555** [comment] 2018-02-01 01:38
Sorry, Tk, of course - too late in the night here.

**Comment by tacaswell** [comment] 2018-07-09 04:22
@myak555 can you try on current master?  I believe this is the same underlying bug as #6781 which was fixed by https://github.com/matplotlib/matplotlib/pull/11559

**Closed by tacaswell** 2018-07-09 04:22 UTC
Labels: GUI/tk, OS/Microsoft
