### ISSUE TITLE
Cannot pickle `figure` or `axes` (TypeError: instancemethod)

### ISSUE THREAD

**Issue by bgenchel** [matplotlib/matplotlib#8615] opened 2017-05-13 02:11 UTC
### Bug report

**Bug summary**

I can't pickle figure or axes objects. For both, I get the error: `TypeError: can't pickle instancemethod objects`

**Code for reproduction**

```python
import json
import numpy as np
import os.path as op
import pickle
from matplotlib import pyplot, cm
from mpl_toolkits.mplot3d import Axes3D

with open(op.join(op.dirname(op.abspath(__file__)), 'data.json')) as fp:
    data = json.load(fp)

Y = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
categories = [0, 1, 1]
category_labels = ['one', 'two', 'three']
colors = cm.rainbow(np.linspace(0, 1, len(category_labels)))

fig = pyplot.figure()
ax = Axes3D(fig)
for i in xrange(len(category_labels)):
    label = category_labels[i]
    subset = Y[np.where(categories == i)]
    ax.scatter(subset[:, 0], subset[:, 1], subset[:, 2], c=colors[i], label=label)

ax.legend(loc='lower right', prop={'size': 9})
fig.savefig('whatever.svg')
with open('whatever.pkl', 'w') as outfile:
    pickle.dump(fig, outfile)
pyplot.show()
```

**Actual outcome**

```
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 621, in _batch_appends
    save(x)
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/Users/bgenchel/anaconda/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/Users/bgenchel/anaconda/lib/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle instancemethod objects
```

**Expected outcome**
Saves my object to a pkl file as specified 

**Matplotlib version**
1.5.3
  * Operating System:
OS X El Capitan
  * Python Version:2.7.12 :: Anaconda 4.2.0 (x86_64)
  * Other Libraries: Pickle

**Comment by QuLogic** [comment] 2017-05-13 09:55
Please try with 2.0.2; I cannot reproduce the problem.

**Comment by tacaswell** [comment] 2017-05-13 20:56
Believe this was fixed by https://github.com/matplotlib/matplotlib/pull/7330

If you can reproduce this using 2.0.x please ping to have this re-opened.

**Closed by tacaswell** 2017-05-13 20:56 UTC
