### ISSUE TITLE
wx event loop broken (1.5.0rc1)

### ISSUE THREAD

**Issue by mdehoon** [matplotlib/matplotlib#5093] opened 2015-09-17 05:06 UTC
On Max OS X:
```python
>>> import matplotlib
>>> matplotlib.use("wx")
>>> from pylab import *
>>> figure()
```
causes the beachball to appear, with the figure unresponsive to mouse clicks.
Continuing with
```python
>>> plot([1,2,3])
```
does not draw the line (in interactive mode).

**Comment by tacaswell** [comment] 2015-09-17 13:48
My guess is that it's `draw_idle` does not work properly.  Does it behave better in IPython?

**Comment by newville** [comment] 2015-09-18 17:05
might need https://github.com/minrk/appnope?  I've seen terminal event loops hang (on OS X) with wx event loops, and disabling the "App Nap" behavior with this module fixes it.

**Comment by tacaswell** [comment] 2015-09-24 02:21
I can confirm this on linux as well.

Something is not going right with the registration of the `PyOS_inputhook`.  If you call `plt.pause(30)` (which runs the gui mainloop for 30s) then the figure is interactive.

It is interactive (with wxagg) in IPython if we let it set up the inputhook.

Somewhat worse, closing the figure results in a segfault.

**Comment by tacaswell** [comment] 2015-09-24 02:26
I can also reproduce these issues with  1.4.3 and 1.3.1 which makes me suspect that the issue is in wx, not in mpl.

**Comment by tacaswell** [comment] 2015-09-24 02:34
@RobinD42 sorry to bother you but something is clearly going very wrong here and it it outside of my knowledge to debug.

**Comment by tacaswell** [comment] 2015-10-29 17:47
The segfault is probably a separate issue that only happens when I use `ctrl-w` to close the window, using `plt.close('all')` works fine as does forcible closing the window from the window manager.

The input hook not being registered by mpl has been policy for a while, if you you want to use wx + interactive mode, you must use IPython or manage the input hook your self.

Closing as wontfix, will make a new issue for the segfault.

**Closed by tacaswell** 2015-10-29 17:47 UTC
Labels: GUI/wx, won't fix
