### ISSUE TITLE
OverflowError: Python int too large to convert to C long during ploting simple numbers on debian testing

### ISSUE THREAD

**Issue by karolszk** [matplotlib/matplotlib#7680] opened 2016-12-23 21:50 UTC
Hello,

The simple python program:

import matplotlib.pyplot as plt

numbers = [1,2,3,4,5]
plt.plot(numbers)
plt.show()

returns the following exception instead of drawing a picture. I'm using debian-testing and python 2.7.11-2 with:

dpkg -l python-matplotlib

ii  python-matplotlib                       1.5.3-1                  i386                     Python based plotting system in a style similar to Matlab

$ python test_overflowerror.py 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1545, in __call__
    return self.func(*args)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 283, in resize
    self.show()
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 355, in draw
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/tkagg.py", line 26, in blit
    _tkagg.tkinit(tk.interpaddr(), 1)
OverflowError: Python int too large to convert to C long

Regards, Karol

**Comment by efiring** [comment] 2016-12-23 21:59
This is a duplicate of #7633, which was closed by #7634.

**Closed by efiring** 2016-12-23 21:59 UTC

**Comment by karolszk** [comment] 2016-12-23 22:12
Hello @efiring thanks for fast response but as I see fix is for 2.x version instead of 1.5.3. What I can do know? Probably I will have to write to debian mailing list because this bug considers currently testing version of debian which is in freezing state now.

**Comment by efiring** [comment] 2016-12-23 22:19
I was afraid of something like that... We are not going to make any more releases in the 1.5.x series.  I don't know how the debian system works, but I imagine the options are:
- apply the patch to 1.5.3 for the debian package
- thaw debian testing just enough to squeeze in v2.0 when it is released, early next month
- or thaw it enough to go with the present, and probably the last, release candidate, v2.0rc2.

Any more thoughts on this, @tacaswell?

**Comment by karolszk** [comment] 2016-12-23 22:27
Please do tribute to debian :-) in X-mas time :-)

**Comment by tacaswell** [comment] 2016-12-23 23:18
@sandrotosi is our normal debian contact.  To my understanding the 2.0 release candidates were already in the debian pipeline.

There will be no more 1.5.x releases.

I suspect I am going to greatly annoy the debian folks this cycle as I also need to sneak an h5py release under the wire :smiling_imp: .

**Comment by sandrotosi** [comment] 2016-12-30 15:37
2.0.0rc2 reached testing yesterday, so this bug is fixed there as well (the debian freeze is a rather intricate process, i'm dealing with the various stages). the plan is to have an early Jan final release of mpl and at that point i'll promptly upload it to unstable which should give us plenty of time to migrate it to testing

there will likely be some bugs/regressions (as in projects not compatible and stuff), uploading early should catch those issues earlier (hopefully) but expect some issues submitted! ;)

**Comment by karolszk** [comment] 2016-12-30 15:42
Hi! I've checked and updated my debian testing packages hour ago and I confirm that python-matplotlib     is upgraded to 2.0.0~rc2-1 and my program correctly running without overflow exception. Thanks and happy New Year. :)
