### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ZhenyuanJin** [matplotlib/matplotlib#29216] opened 2024-12-02 03:44 UTC
### Bug summary

scatter with small s value leads to hollow point

### Code for reproduction

```Python
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
x = np.random.randn(10)
y = np.random.randn(10)
plt.scatter(x, y, s=0.1)
plt.savefig('scatter.pdf')
```

### Actual outcome

![8b04a39d583f67769c40d680ba54f0d2](https://github.com/user-attachments/assets/d39ee714-4146-484c-a5c3-a7ea4d835971)

### Expected outcome

the scatter should be not hollow, even for small s value

### Matplotlib Version

3.9.2

### Installation

None

**Comment by timhoffm** [comment] 2024-12-02 10:13
Please give a meaningful title. Which OS and PDF viewer are you using? I'm not able to reproduce this with Windows/Adobe Arcrobat.

**Comment by ZhenyuanJin** [comment] 2024-12-02 11:36
also, if save with png format, the problem still exist, even for large dpi (like 5000); I think png format is same for different platform and viewer. Again thanks for your kindly reply

**Comment by MiracleLin001** [comment] 2024-12-02 12:33
> Please give a meaningful title. Which OS and PDF viewer are you using? I'm not able to reproduce this with Windows/Adobe Arcrobat.

I have reproduced this issue and it may because of the magnitude difference in markersize `s` and `linewidth` parameter in scatter function. My workspace is Linux with python 3.10.10 and matplotlib 3.8.2.
Here is my code:
`import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots() 
ax.scatter([1], [1], s=1, marker='o', linewidth=15, edgecolors = 'red')  
fig.savefig('scatter2.pdf', dpi = 300)`
file 'scatter2' is attached here:
[scatter2.pdf](https://github.com/user-attachments/files/17977941/scatter2.pdf)

**Comment by MiracleLin001** [comment] 2024-12-02 12:34
> Please give a meaningful title. Which OS and PDF viewer are you using? I'm not able to reproduce this with Windows/Adobe Arcrobat.

I have reproduced this issue and it may because of the magnitude difference in markersize s and linewidth parameter in scatter function. My workspace is Linux with python 3.10.10 and matplotlib 3.8.2.
Here is my code:
`
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
ax.scatter([1], [1], s=1, marker='o', linewidth=15, edgecolors = 'red')
fig.savefig('scatter2.pdf', dpi = 300)
`
file 'scatter2' is attached here:
[scatter2.pdf](https://github.com/user-attachments/files/17977957/scatter2.pdf)

**Comment by MiracleLin001** [comment] 2024-12-02 12:37
I have reproduced this problem and it may be due to the difference in magnitude of the markersize `s` and `linewidth` parameters in the scatter function. I have tested several pairs of `s` and `linewidth` and the phenomenon is stable. My workspace is Linux with python 3.10.10 and matplotlib 3.8.2.
Here is my code:
```python
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
ax.scatter([1], [1], s=1, marker='o', linewidth=15, edgecolors = 'red')
fig.savefig('scatter2.pdf', dpi = 300)
```
file 'scatter2' is attached here:
[scatter2.pdf](https://github.com/user-attachments/files/17977986/scatter2.pdf)

**Comment by MiracleLin001** [comment] 2024-12-02 12:46
> Please give a meaningful title. Which OS and PDF viewer are you using? I'm not able to reproduce this with Windows/Adobe Arcrobat.

I have reproduced this problem and it may be due to the difference in magnitude of the markersize `s` and `linewidth` parameters in the scatter function. I have tested several pairs of `s` and `linewidth` and the phenomenon is stable.  My workspace is Linux with python 3.10.10 and matplotlib 3.8.2.
Here is my code:
```python
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
ax.scatter([1], [1], s=1, marker='o', linewidth=15, edgecolors = 'red')
fig.savefig('scatter2.png', dpi = 300)
```
file 'scatter2' is attached here:
![scatter2](https://github.com/user-attachments/assets/e0bd1185-6ced-4529-8a2d-69c71bf1a7e0)

I also tried to save as PDF file and use Adobe Arcrobat to open it on Windows, and then this issue didn't occur. It shows a red filled circle as we expected. However, the sumatraPDF shows differently from Arcrobat. The pdf file is attached here:
[scatter2.pdf](https://github.com/user-attachments/files/17978060/scatter2.pdf)

**Comment by QuLogic** [comment] 2024-12-03 00:29
This is because the edge is still drawn at the default width; this is noted on the [docs for the `s` parameter of `scatter`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.scatter.html).

This is a duplicate of #25410, among others.

**Closed by QuLogic** 2024-12-03 00:29 UTC
Labels: status: needs clarification
