### ISSUE TITLE
Trying to combine multiple closed paths to clip an image raise an exception.

### ISSUE THREAD

**Issue by KelSolaar** [matplotlib/matplotlib#12875] opened 2018-11-24 09:03 UTC
### Bug report

**Bug summary**

I was trying the method suggested in a [SO answer](https://stackoverflow.com/a/38291904/931625) to combine multiple closed paths to clip an image but it raises an exception.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Polygon

image = np.random.random([32, 32, 3])

figure, axes = plt.subplots()

p1 = [[0.25, 0.25], [0.75, 0.75], [0.25, 0.75]]
p2 = [[0.125, 0.125], [0.125, 0.65], [0.65, 0.65]]
p3 = np.concatenate([
    p1,
    [[np.nan, np.nan]],
    p2,
])

polygon = Polygon(p3, facecolor='none', edgecolor='none')
axes.add_patch(polygon)
im = axes.imshow(image, extent=(0, 1, 0, 1), clip_path=None)
im.set_clip_path(polygon)

plt.show()
```

**Actual outcome**

```
/usr/local/anaconda3/envs/colour-2.7/bin/python /Users/kelsolaar/Documents/Development/colour-science/colour-ramblings/ramblings_modules/ramblings_029.py
Traceback (most recent call last):
  File "/Users/kelsolaar/Documents/Development/colour-science/colour-ramblings/ramblings_modules/ramblings_029.py", line 22, in <module>
    plt.show()
  File "/usr/local/anaconda3/envs/colour-2.7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 253, in show
    return _show(*args, **kw)
  File "/Applications/PyCharm.app/Contents/helpers/pycharm_matplotlib_backend/backend_interagg.py", line 25, in __call__
    manager.show(**kwargs)
  File "/Applications/PyCharm.app/Contents/helpers/pycharm_matplotlib_backend/backend_interagg.py", line 107, in show
    self.canvas.show()
  File "/Applications/PyCharm.app/Contents/helpers/pycharm_matplotlib_backend/backend_interagg.py", line 63, in show
    FigureCanvasAgg.draw(self)
  File "/usr/local/anaconda3/envs/colour-2.7/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 437, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/anaconda3/envs/colour-2.7/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/anaconda3/envs/colour-2.7/lib/python2.7/site-packages/matplotlib/figure.py", line 1493, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/anaconda3/envs/colour-2.7/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/anaconda3/envs/colour-2.7/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/anaconda3/envs/colour-2.7/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2635, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/local/anaconda3/envs/colour-2.7/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/anaconda3/envs/colour-2.7/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/anaconda3/envs/colour-2.7/lib/python2.7/site-packages/matplotlib/image.py", line 596, in draw
    renderer.draw_image(gc, l, b, im)
OverflowError: In draw_image: Exceeded cell block limit
```

**Expected outcome**

Being able to combine multiple closed paths to have complex image clipping.

**Matplotlib version**
  * Operating system: macOs
  * Matplotlib version:  2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://backend_interagg
  * Python version: 2.7.14

**Comment by anntzer** [comment] 2018-11-24 11:33
FWIW, it works with https://github.com/anntzer/mplcairo, so the problem is (as can be expected from the error message) at the renderer level.

**Comment by QuLogic** [comment] 2018-11-25 07:18
> I don't think it's the result you want.

Actually, since the paths overlap, I'm not entirely sure which result is the one you expected.

**Comment by KelSolaar** [comment] 2018-11-25 07:45
Hi @QuLogic,

What I like to achieve is to clip the chromaticity diagram colours with the ellipses on that figure:

![image](https://user-images.githubusercontent.com/99779/48976811-df113980-f0f2-11e8-85b3-a7c7293ca0a4.png)

In order to have a result like that:

![image](https://user-images.githubusercontent.com/99779/48976823-f8b28100-f0f2-11e8-9da0-38bda4f4af87.png)

I will try `Path.make_compound_path` looks promising!

**Comment by KelSolaar** [comment] 2018-11-25 08:11
So this is what I get when I pass the resulting vertices of `Path.make_compound_path` to my Polygon patch:

![image](https://user-images.githubusercontent.com/99779/48977008-8ba0ea80-f0f6-11e8-8db8-f017f474ca03.png)

This is the reason I tried the `np.nan` as suggested in the SO answer.

**Comment by QuLogic** [comment] 2018-11-25 08:17
If you have a bunch of Ellipses (that should be the same path length, I think) then `Path.make_compound_path_from_polys` seems a better choice. For `Path.make_compound_path`, you need to make sure to add the correct `MOVETO` and `CLOSEPOLY` to the individual `Path`s.

**Comment by KelSolaar** [comment] 2018-11-25 08:55
`Path.make_compound_path_from_polys` worked great thanks!

![image](https://user-images.githubusercontent.com/99779/48977312-d45ba200-f0fc-11e8-8113-a90f802c0ad7.png)

**Comment by jklymak** [comment] 2018-11-25 17:44
I'm closing because there seems to be a solution and there isn't action we can take.  Feel free to discuss further, however...

**Closed by jklymak** 2018-11-25 17:44 UTC
Labels: backend/agg
