### ISSUE TITLE
ImageGrid bug when using inline backend

### ISSUE THREAD

**Issue by ezatterin** [matplotlib/matplotlib#12370] opened 2018-10-02 14:18 UTC
### Bug report

**Bug summary**

The `ImageGrid` class seems to not behave correctly since the upgrade to matplotlib `3.0.0` when the `inline` backend is used in a Jupyter notebook: the resulting subplots fail to arrange in a grid and are placed on top of eachother. The correct behaviour is reproduced if using the `notebook` or `ipympl` backends. Thanks!

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import ImageGrid
import numpy as np

im = np.arange(100)
im.shape = 10, 10

fig = plt.figure(1, (4., 4.))
grid = ImageGrid(fig, 111,  
                 nrows_ncols=(2, 2),  
                 axes_pad=0.1,  
                 )

for i in range(4):
    grid[i].imshow(im)  
    grid[i].set_title('test {0}{0}'.format(i)) 

plt.show()
```

**Actual outcome**
![image](https://user-images.githubusercontent.com/15064659/46354323-9d1dc700-c65e-11e8-9cf1-c8fdc40e9acf.png)

**Expected outcome**

![image](https://user-images.githubusercontent.com/15064659/46354286-88d9ca00-c65e-11e8-991f-7dfe32c4a529.png)

**Matplotlib version**
  * Operating system: Debian 9
  * Matplotlib version: 3.0.0
  * Matplotlib backend: `inline`
  * Python version: 3.5.3
  * Jupyter version (if applicable): 4.4.0
  * Other libraries:

**Comment by jklymak** [comment] 2018-10-02 14:47
Yeah this seems to be a duplicate of #12355; `inline` uses `bbox_inches='tight'`, and there was a bad interaction with `axes_grid1` subclasses and that saving option.  #12363 should fix this as well....

**Comment by jklymak** [comment] 2018-10-02 14:49
Just add `fig.savefig('Boo.png', bbox_inches='tight')` to the above to make it reproducible w/o a notebook.  #12363 indeed fixes this...

**Comment by jklymak** [comment] 2018-10-02 14:57
Thanks for the bug report - closing as a duplicate, but I used your example as a new test...

**Closed by jklymak** 2018-10-02 14:57 UTC

**Comment by ImportanceOfBeingErnest** [comment] 2018-10-02 20:12
@ezatterin While waiting for the new release which hopefully has this fixed you may always decide to not crop the images when using `%matplotlib inline` via

    %config InlineBackend.print_figure_kwargs = {'bbox_inches':None}

in IPython or Jupyter.
