### ISSUE TITLE
fig.show() doesn't work in Jupyterlab

### ISSUE THREAD

**Issue by sindzicat** [matplotlib/matplotlib#18047] opened 2020-07-24 09:56 UTC
Hello.

Jupyterlab 1.2.6.
matplotlib 3.2.2
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]

First I try:

```python
%matplotlib inline
import matplotlib.pyplot as plt
plt.plot([1,1.6,3])
plt.show()
```

All works fine, I see a chart.

Then I try:

```python
%matplotlib inline
fig = plt.figure()
fig.show()
```

I expect to see an empty figure, but I get an error unstead:
```
E:\MyDocs\rotmod\py3.7-win64-dev\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Matplotlib is currently using module://ipykernel.pylab.backend_inline, which is a non-GUI backend, so cannot show the figure.
  This is separate from the ipykernel package so we can avoid doing imports until
<Figure size 432x288 with 0 Axes>
```

Then I tested:

```python
%matplotlib inline
%matplotlib
```

I got:

```
Using matplotlib backend: Qt5Agg
```

Does this means, that `matplotlib inline` doesn't work in Jupyterlab?

Best regards,
Andrey.

**Comment by dopplershift** [comment] 2020-07-25 19:56
No, `matplotlib inline` works fine in Jupyterlab. That *warning* (not an error) is letting you know that since you're using a non-interactive backend (matplotlib inline), `fig.show()` does absolutely nothing.

Your code worked, and produced an empty figure, as noted by: `<Figure size 432x288 with 0 Axes>`. It has literally nothing to plot, so it doesn't. If you modify your code to add a subplot to the figure, you'll get an image:

```python
%matplotlib inline
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
fig.show()
```

I use matplotlib in Jupyterlab on a regular basis, and everything works fine.

**Comment by timhoffm** [comment] 2020-07-25 20:41
Can we make the warning more informative? Would it be correct changing from

> UserWarning: Matplotlib is currently using module://ipykernel.pylab.backend_inline, which is a non-GUI backend, so cannot show the figure.

to

> UserWarning: Matplotlib is currently using module://ipykernel.pylab.backend_inline, which is a non-interactive backend. Figure.show() cannot be used with this. You might want to use plt.show() instead.

**Comment by timhoffm** [comment] 2020-07-25 20:47
Can we make the message more informative. E.g. would it be correct changing from 

> UserWarning: Matplotlib is currently using module://ipykernel.pylab.backend_inline, which is a non-GUI backend, so cannot show the figure.
to 
> UserWarning: Matplotlib is currently using module://ipykernel.pylab.backend_inline, which is a non-interactive backend. Therefore, Figure.show() cannot be used. You might want to use plt.show() instead.

#### Note:
`%matplotlib inline` automatically shows open figures at the end of the cell. Therefore, you usually don't need to call any `show()` explicitly.

**Comment by dopplershift** [comment] 2020-07-25 20:52
I'm not sure that `plt.show()` is any more functional in jupyter notebook/lab.

**Comment by timhoffm** [comment] 2020-07-25 21:12
You can use `plt.show()` at any point in a notebook to dump the open figure(s). If there are figures open at the end of a cell execution, there's an implicit `plt.show()` to dump them as well.

![image](https://user-images.githubusercontent.com/2836374/88466382-0756ca00-cecc-11ea-8e46-533903c12081.png)

**Comment by dopplershift** [comment] 2020-07-25 21:19
Fair enough. I'm still not clear why `plt.show()` doesn't think it needs to warn while `fig.show()` does. That seems needlessly inconsistent.

**Comment by timhoffm** [comment] 2020-07-25 22:02
Well, `plt.show()` works, so it doesn't have to warn.

I'm actually not clear why `fig.show()` doesn't work (or cannot be made to work). I mean, `%matplotlib inline` doesn't need an event loop or other fancy stuff. It's probably just how it's implemented.

**Comment by dopplershift** [comment] 2020-07-25 22:11
`plt.show()`:
```python
return _backend_mod.show(*args, **kwargs)
```

`fig.show():`
```python
        try:
            self.canvas.manager.show()
        except NonGuiException as exc:
            cbook._warn_external(str(exc))
```

I haven't bothered to dig further, but they're both delegating to a show method in the backend. I'd be surprised if one of those doesn't call the other.

**Comment by timhoffm** [comment] 2020-07-25 22:51
`plt.show()` calls the backend `show()`, which loops over its managers and calls `manager.show()`. It will additionally handle the event loop for interactive cases.

**Comment by sindzicat** [comment] 2020-07-27 19:06
Thank you all very much for your answers! Now I understand, that it was only a warning message, not an error.

I found that I even don't need `%matplotlib inline`.

This works for me nice:

```python
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.plot([0,1], [0,1], color='blue', lw=2)
None # <- this will suppress output from the previous line
```

You can suppress `None` with `"";`, Semicolon suppresses output in Jupyter.

For an empty `fig` my code will be as following:

```python
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
```

**Comment by sindzicat** [comment] 2020-07-27 19:14
> Can we make the message more informative.

@timhoffm, maybe just fix `fig.show()`? 😊
But I noticed now, that all examples on matplotlib.org site seems to use `plt.show()`.

**Comment by timhoffm** [comment] 2020-07-27 20:41
> maybe just fix `fig.show()`? 😊

I'm not an expert on this, but I don't think this can be fixed in `fig.show()`. As far as I understand this, supporting the direct show of a figure would need to be supported by the respective backend; i.e. here the inline backend, which is not in the responsibility of the matplotlib project, but of ipython: https://github.com/ipython/ipykernel/blob/master/ipykernel/pylab/backend_inline.py.

**Comment by sindzicat** [comment] 2020-08-02 13:39
@timhoffm, sorry I was sure that you were one of the Matplotlib developers. ¯\_(ツ)_/¯

**Comment by jklymak** [comment] 2020-08-02 14:58
I think this has been discussed enough.  `fig.show()` does not work in jupyter, by design, and that design is not likely to change.

**Closed by jklymak** 2020-08-02 14:58 UTC

**Comment by tacaswell** [comment] 2020-08-02 16:02
I would also add that the `show` methods on the `Figure` and `Manager` classes are about "doing what ever is needed for this backend to put the window on the screen" where as `plt.show` is about "call `fig.manager.show()` on all active figures and then if needed run the event loop".  Smoothing out this sort of thing and standardizing across the many backends was/is one of the goals of the backend refactoring work.

@sindzicat  Tim is one of our core developers.

**Comment by sindzicat** [comment] 2020-08-02 16:09
@tacaswell OK

For now I have no problems to plot matplotlib figures in JupyterLab. I even don't use `%matplotlib inline` &mdash; all works fine without it. I remember about interactive widget for JupyterLab and installed it, but I don't need interactive charts for now.

Many thanks to all for solving my problem!

**Comment by timhoffm** [comment] 2020-08-02 16:13
> I was sure that you were one of the Matplotlib developers. ¯\_(ツ)_/¯

@sindzicat I am, but not every core developer is expert for every part of the library. It's just too big for that.
