### ISSUE TITLE
[Bug]: OverflowError: int too big to convert 

### ISSUE THREAD

**Issue by gkuklik** [matplotlib/matplotlib#28901] opened 2024-09-27 22:29 UTC
### Bug summary

pd.TimeStamps within a second result in conversion error when formatting datetime labels:

    347     dt = (np.datetime64(get_epoch()) +
--> 348           np.timedelta64(int(np.round(x * MUSECONDS_PER_DAY)), 'us'))
    349     if dt < np.datetime64('0001-01-01') or dt >= np.datetime64('10000-01-01'):
    350         raise ValueError(f'Date ordinal {x} converts to {dt} (using '

OverflowError: int too big to convert

### Code for reproduction

```Python
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
df = pd.DataFrame({'date': pd.to_datetime(['2023-10-26 12:12:10Z', '2023-10-26 12:12:11Z', '2023-10-26 12:12:12Z']), 'value': [10, 20, 15]})

df.plot(x='date', y='value')

# Format the x-axis
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d  %H:%M:%S.%f'))

plt.show()
```

### Actual outcome

matplotlib/dates.py in _from_ordinalf(x, tz)
    346 
    347     dt = (np.datetime64(get_epoch()) +
--> 348           np.timedelta64(int(np.round(x * MUSECONDS_PER_DAY)), 'us'))
    349     if dt < np.datetime64('0001-01-01') or dt >= np.datetime64('10000-01-01'):
    350         raise ValueError(f'Date ordinal {x} converts to {dt} (using '

OverflowError: int too big to convert

### Expected outcome

a plot

### Additional information

If the dates contain a fraction of a second, formatter works correctly. e.g.  add 1 ns to the first date 

df = pd.DataFrame({'date': [pd.Timestamp(x) for x in [1698322330000000001, 1698322331000000000, 1698322332000000000]], 'value': [10, 20, 15]})

df.plot(x='date', y='value')

# Format the x-axis
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d  %H:%M:%S.%f'))

plt.show()

### Operating system

Colab - Google linux

### Matplotlib Version

3.9.1

### Matplotlib Backend

module://IPython.kernel.zmq.pylab.backend_inline

### Python version

3.11.8

### Jupyter version

Colab

### Installation

None

**Comment by kyracho** [comment] 2024-09-28 09:59
Hello, it seems like the ` _from_ordinalf` function of the `matplotlib.dates` module causes an OverflowError when converting large float ordinal values into `datetime64` objects.

https://github.com/matplotlib/matplotlib/blob/bb68469d755bc04e0ddabff3f36908a9e2351423/lib/matplotlib/dates.py#L347-L348

I suggest replacing the use of Python's `int`with NumPy's `np.int64` to handle large values safely without causing overflow. 

Suggested fix:

```
microseconds_since_epoch = np.int64(np.round(x * MUSECONDS_PER_DAY))
dt = np.datetime64(get_epoch()) + np.timedelta64(microseconds_since_epoch, 'us')
```

This approach would maintain the full functionality and precision of the conversion while preventing the overflow error.

**Comment by tacaswell** [comment] 2024-09-28 12:13
The source of the problem is that the converter installed by Pandas arranges so that its converter gets installed which uses a different convention than the Matplotlib datetime converters use.  This means that when you switch to using the Matplotlib formatter we get feed very unexpected data and it fails.

I'm going to close this as a duplicate and re-direct discussion to https://github.com/matplotlib/matplotlib/issues/24951

**Closed by tacaswell** 2024-09-28 12:13 UTC
