### ISSUE TITLE
bar plot missing bars

### ISSUE THREAD

**Issue by mcspritz** [matplotlib/matplotlib#8808] opened 2017-06-27 12:33 UTC
I found a bug in the bar plot when the bar size gets really small and lots of bins are represented. I found it while doing a histogram and traced it into the bar plot. 

```python
from pylab import *
import random

random.seed()

b = int(2.2 / 0.0006)
x = [-1 + i * 0.0006 for i in range(b)]
y = [random.uniform(0, 100) for _ in range(b)]

fig, (ax1, ax2) = subplots(2, 1)

ax1.bar(x, y, width=0.0001)
ax2.plot(x, y, lw=0.2)

plt.tight_layout()
plt.savefig('hist.png', dpi=150, format='png')
plt.close()
```

**Actual outcome**

The bug consists in missing bars for some unknown reason. The code below shows the comparison between the bar plot and the same x, y plotted as a line. It can be noticed the difference in number of represented points.

![hist](https://user-images.githubusercontent.com/1878127/27587559-1f084a3c-5b45-11e7-8dca-ef7d5381eb42.png)

**Matplotlib version**
  * Operating System: Manjaro Linux
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.1

I installed through pre-compiled package provided by Manjaro maintainers

**Comment by tacaswell** [comment] 2017-06-27 12:56
It is because you bars are  narrower than a single pixel (which is ~ 0.00390625 in your data units).  If you zoom in the missing bars will render.  This is peculiarity of the Agg renderer, if you save to svg / pdf / eps all of the rectangles will be there (but then you are at the mercy of what ever rasterizes the vectors for you).  The feature that is getting you here is 'pixel snapping' which is aligns things to pixel boundaries to make the rendered lines look sharper, you can disable this by passing `snap=False` to the `bar` call 

```python
import matplotlib.pyplot as plt

import random

random.seed()

b = int(2.2 / 0.0006)
x = [-1 + i * 0.0006 for i in range(b)]
y = [random.uniform(0, 100) for _ in range(b)]

fig, (ax1, ax2) = plt.subplots(2, 1, sharex=True)

r_lst = ax1.bar(x, y, width=0.0001, snap=False)
ax2.plot(x, y, lw=0.2)

plt.tight_layout()

```
![so](https://user-images.githubusercontent.com/199813/27588493-5204877c-5b16-11e7-9525-0d4b00f0fb79.png)


In the case of hist, using `histtype='stepfilled'` is a much better option when there are many small bins (it renders the histogram as a single patch which at this number of bins is what you want and will have much better performance).

Closing as this is not a bug and there is a way to get better results in either this case or the motivating hist case.

**Closed by tacaswell** 2017-06-27 12:56 UTC

**Comment by shantisuresh01** [comment] 2018-06-18 22:15
@tacaswell  thanks for that helpful insight!
