### ISSUE TITLE
Cannot import pyplot

### ISSUE THREAD

**Issue by Cory-Kramer** [matplotlib/matplotlib#12173] opened 2018-09-19 14:49 UTC
### Bug report

**Bug summary**
I am unable to `import matplotlib.pyplot` starting in version 3.0.0. Might be related to Issue #9485?

**Code for reproduction**

```python
import matplotlib.pyplot as plt
```

**Actual outcome**

I get the following traceback when executing the above `import`

```
Traceback (most recent call last):
  File "C:\Python\Python35\lib\site-packages\matplotlib\font_manager.py", line 1353, in <module>
    fontManager = json_load(_fmcache)
  File "C:\Python\Python35\lib\site-packages\matplotlib\font_manager.py", line 888, in json_load
    with open(filename, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\.matplotlib\\fontlist-v300.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import matplotlib.pyplot as plt
  File "C:\Python\Python35\lib\site-packages\matplotlib\pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "C:\Python\Python35\lib\site-packages\matplotlib\colorbar.py", line 32, in <module>
    import matplotlib.contour as contour
  File "C:\Python\Python35\lib\site-packages\matplotlib\contour.py", line 18, in <module>
    import matplotlib.font_manager as font_manager
  File "C:\Python\Python35\lib\site-packages\matplotlib\font_manager.py", line 1363, in <module>
    _rebuild()
  File "C:\Python\Python35\lib\site-packages\matplotlib\font_manager.py", line 1344, in _rebuild
    fontManager = FontManager()
  File "C:\Python\Python35\lib\site-packages\matplotlib\font_manager.py", line 978, in __init__
    ttffiles = findSystemFonts(paths) + findSystemFonts()
  File "C:\Python\Python35\lib\site-packages\matplotlib\font_manager.py", line 264, in findSystemFonts
    fontfiles.update(win32InstalledFonts(fontext=fontext))
TypeError: 'NoneType' object is not iterable
```

**Matplotlib version**

  * Operating system: Windows 10 64-bit
  * Matplotlib version: 3.0.0
  * Matplotlib backend: TkAgg
  * Python version: 3.5.4
  * Jupyter version (if applicable): NA
  * Other libraries: NA

Installed via `pip`

**Comment by dsentinel** [comment] 2018-09-19 17:20
Same on a mac installed with conda if `~/.matplotlib/fontlist-v300.json` doesn't exist
```bash
(mat_bug_py37) moonbase:~ lloyd$ ls -al /Users/lloyd/.matplotlib/fontlist-v300.json
-rw-r--r--  1 lloyd  staff  130027 Sep 19 10:45 /Users/lloyd/.matplotlib/fontlist-v300.json
(mat_bug_py37) moonbase:~ lloyd$ python -c 'from matplotlib import pyplot'
(mat_bug_py37) moonbase:~ lloyd$ rm  /Users/lloyd/.matplotlib/fontlist-v300.json
(mat_bug_py37) moonbase:~ lloyd$ python -c 'from matplotlib import pyplot'
```
hangs.... ctl-c
```bash
^CTraceback (most recent call last):
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/site-packages/matplotlib/font_manager.py", line 1353, in <module>
    fontManager = json_load(_fmcache)
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/site-packages/matplotlib/font_manager.py", line 888, in json_load
    with open(filename, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lloyd/.matplotlib/fontlist-v300.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/site-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.contour as contour
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/site-packages/matplotlib/contour.py", line 18, in <module>
    import matplotlib.font_manager as font_manager
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/site-packages/matplotlib/font_manager.py", line 1363, in <module>
    _rebuild()
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/site-packages/matplotlib/font_manager.py", line 1344, in _rebuild
    fontManager = FontManager()
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/site-packages/matplotlib/font_manager.py", line 978, in __init__
    ttffiles = findSystemFonts(paths) + findSystemFonts()
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/site-packages/matplotlib/font_manager.py", line 270, in findSystemFonts
    fontfiles.update(OSXInstalledFonts(fontext=fontext))
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/site-packages/matplotlib/font_manager.py", line 218, in OSXInstalledFonts
    for directory in directories
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/site-packages/matplotlib/font_manager.py", line 220, in <listcomp>
    for path in list_fonts(directory, ext)]
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/site-packages/matplotlib/font_manager.py", line 157, in list_fonts
    for path in filter(Path.is_file, Path(directory).glob("**/*.*"))
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/site-packages/matplotlib/font_manager.py", line 156, in <listcomp>
    return [str(path)
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/pathlib.py", line 1344, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/Users/lloyd/anaconda2/envs/mat_bug_py37/lib/python3.7/pathlib.py", line 1140, in stat
    return self._accessor.stat(self)
KeyboardInterrupt
^C
```
`~/.matplotlib/fontlist-v300.json` didn't exist until I ran the import testing other versions (py27)

**Comment by MahdiEsf** [comment] 2018-09-20 01:51
I have the same issue, the same error. matplotlib 3.00. Doesn't find fontlist-v300.json

**Comment by tacaswell** [comment] 2018-09-20 02:14
Not finding that file in fine, it is a cache and automatically re-generated.

**Comment by Kojoley** [comment] 2018-09-22 13:28
There are more problem usages of `Path(...).suffix`.

  - Again the leading dot: 
 https://github.com/matplotlib/matplotlib/blob/2891f55ba42caab8143b65761891fab6623822d4/lib/matplotlib/font_manager.py#L158

  - Will fire an exception when file has no extension/suffix https://github.com/matplotlib/matplotlib/blob/07e2d54d8c5623efef7d3f18c61d855d5c6ef16e/lib/matplotlib/font_manager.py#L245

**Comment by anntzer** [comment] 2018-09-22 14:04
Thanks for investigating.
I don't think Path(fname).suffix[1:] will throw if there's no suffix though, as the suffix would be an empty string and [1:] on it will still be an empty string.  We do need to make sure that fontext is a list of strings and not a single string though.

**Comment by Kojoley** [comment] 2018-09-22 14:09
Oops, that's something I had misconception, I thought `''[1:]` will fire an index exception.

**Comment by anntzer** [comment] 2018-09-22 14:27
For lists too you can pass an "invalid" slice and it'll just give you an empty list.

**Comment by Kojoley** [comment] 2018-09-22 14:57
#12212 will not solve the issue.

The `win32InstalledFonts` returns `None` only if regkeys are missing. Any thoughts?

**Comment by anntzer** [comment] 2018-09-22 15:01
I think #12174 is just fine to handle this case.  Perhaps we were just lucky not to have run into that before?

**Comment by Kojoley** [comment] 2018-09-22 15:15
#12174 is fine, but [IIUC](https://docs.microsoft.com/en-us/windows/desktop/api/wingdi/nf-wingdi-addfontresourceexa) the reg key should always exist, may be the guys deleted it by hand or with some third party program?

**Comment by Kojoley** [comment] 2018-09-22 15:46
I am not sure what is the purpose of `win32InstalledFonts` if
https://github.com/matplotlib/matplotlib/blob/333dad1f98ad074533cea7db437ee1442ef37712/lib/matplotlib/font_manager.py#L275 will glob fonts in `win32FontDirectory()`

Is not `win32InstalledFonts` redundant in `findSystemFonts`, since it searches the fonts in `win32FontDirectory()` too? I also cannot find other usages of `win32InstalledFonts`.

**Comment by Kojoley** [comment] 2018-09-22 16:34
I suggest not to merge #12174 (or #12213), but remove `win32InstalledFonts` usage (the single usage is in `findSystemFonts`) for 3.0.1 and deprecate it since 3.1

**Comment by anntzer** [comment] 2018-09-22 21:46
Well, at least *technically* win32InstalledFonts *can* return fonts that are not in win32FontDirectory(), as the registry can specify absolute paths (https://superuser.com/a/1258913/41302).

**Comment by Kojoley** [comment] 2018-09-22 21:59
Well, than I am taking back my last post...

So, may be than solve the both problems (https://github.com/matplotlib/matplotlib/pull/12174#issuecomment-423756278 and #12213) by replacing
https://github.com/matplotlib/matplotlib/blob/333dad1f98ad074533cea7db437ee1442ef37712/lib/matplotlib/font_manager.py#L209 with `return list(items)`?

**Comment by anntzer** [comment] 2018-09-22 22:05
That'll be [] in any case, no?

**Comment by Kojoley** [comment] 2018-09-22 22:10
No, for example if `winreg.EnumValue` raise an exception in the middle of the loop (number of fonts lowered during the loop) the `items` will not be empty.

**Comment by anntzer** [comment] 2018-09-22 22:13
Then just change to call EnumValue until it raises OSError, as officially documented? (https://docs.python.org/3/library/winreg.html#winreg.EnumValue)
(It's also not clear how this can even happen, but sure...)

**Comment by Kojoley** [comment] 2018-09-22 22:16
I think changing `return None` to `return list(items)` and possibly removing https://github.com/matplotlib/matplotlib/blob/333dad1f98ad074533cea7db437ee1442ef37712/lib/matplotlib/font_manager.py#L206 is enough.

**Comment by timhoffm** [comment] 2018-09-22 22:29
> I think changing `return None` to `return list(items)` and possibly removing https://github.com/matplotlib/matplotlib/blob/333dad1f98ad074533cea7db437ee1442ef37712/lib/matplotlib/font_manager.py#L206 is enough.

That seems actually the best solution. Thanks for spotting the details.

**Comment by Kojoley** [comment] 2018-09-23 13:54
Closed in #12213

**Closed by Kojoley** 2018-09-23 13:54 UTC

**Comment by arameskandari** [comment] 2018-10-02 17:09
Hey, I tried removing `return list(items)` and changed `return None` to `return list(items)`, just as you said, but I still get the same error. Is there anything else I can try doing?

**Comment by Kojoley** [comment] 2018-10-02 17:16
You can try downloading snapshot wheels from the PR:
 - Python 3.5: https://ci.appveyor.com/project/matplotlib/matplotlib/build/1.0.11323/job/w5ntl0ccfi4ye8t4/artifacts
  - Python 3.6: https://ci.appveyor.com/project/matplotlib/matplotlib/build/1.0.11323/job/e9or7jbgyeawfjxk/artifacts

**Comment by arameskandari** [comment] 2018-10-03 07:38
> You can try downloading snapshot wheels from the PR:
> 
> * Python 3.5: https://ci.appveyor.com/project/matplotlib/matplotlib/build/1.0.11323/job/w5ntl0ccfi4ye8t4/artifacts
> * Python 3.6: https://ci.appveyor.com/project/matplotlib/matplotlib/build/1.0.11323/job/e9or7jbgyeawfjxk/artifacts

Big thanks, is there a link for Python 3.7 aswell? That's the version I'm using atm.

**Comment by Kojoley** [comment] 2018-10-03 10:58
Unfortunately, no.

**Comment by sebastianjungels** [comment] 2018-10-05 16:09
Hi, I just downloaded and am still getting the same error:

```
Failed to get real commands on module "kapua": python process died with code 1: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\matplotlib\font_manager.py", line 1353, in <module>
    fontManager = json_load(_fmcache)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\matplotlib\font_manager.py", line 888, in json_load
    with open(filename, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Owner\\.matplotlib\\fontlist-v300.json'
```
Any other ideas?

**Comment by Kojoley** [comment] 2018-10-05 16:18
@sebastianjungels can you check if #12408 solved the problem?
 - Python 3.5: https://ci.appveyor.com/api/buildjobs/jscy0x23a57kjnwp/artifacts/dist%2Fmatplotlib-3.0.0rc1%2B511.g030cb07f.dirty-cp35-cp35m-win_amd64.whl
  - Python 3.6: https://ci.appveyor.com/api/buildjobs/grna4e8ko079n6q5/artifacts/dist%2Fmatplotlib-3.0.0rc1%2B511.g030cb07f.dirty-cp36-cp36m-win_amd64.whl
  - Python 3.7: https://ci.appveyor.com/api/buildjobs/c25saceoi0peqw5f/artifacts/dist%2Fmatplotlib-3.0.0rc1%2B511.g030cb07f.dirty-cp37-cp37m-win_amd64.whl

**Comment by sebastianjungels** [comment] 2018-10-05 19:59
it did not, unfortunately. I simply added the missing file though.

________________________________

**Comment by sebastianjungels** [comment] 2018-10-05 21:57
Hi, I got the file from a colleague who didn't face the problem.


Let me know if you need it.


Thanks,
Sebastian

________________________________

**Comment by tacaswell** [comment] 2018-10-06 01:11
I would not have thought to try that....

Given that the cache encodes some local paths I am a bit surprised that this works....

**Comment by Kojoley** [comment] 2018-10-06 11:14
@sebastianjungels Can you please install a snapshot build from #12416 (wheels [3.5](https://ci.appveyor.com/api/buildjobs/hw43dg46c8hlr0x7/artifacts/dist%2Fmatplotlib-3.0.0rc1%2B568.g259de905.dirty-cp35-cp35m-win_amd64.whl) [3.6](https://ci.appveyor.com/api/buildjobs/kgg94aq0lvckqqnl/artifacts/dist%2Fmatplotlib-3.0.0rc1%2B568.g259de905.dirty-cp36-cp36m-win_amd64.whl) [3.7](https://ci.appveyor.com/api/buildjobs/nx78m7tutxow2g1g/artifacts/dist%2Fmatplotlib-3.0.0rc1%2B568.g259de905.dirty-cp37-cp37m-win_amd64.whl)) and provide us a traceback of the error?

**Comment by Kojoley** [comment] 2018-10-07 22:39
I have included links to wheels in my last post. You should be able to install one with `pip install path/to.whl`. I thought you have done it already in https://github.com/matplotlib/matplotlib/issues/12173#issuecomment-427482252.

**Comment by helldanno** [comment] 2018-10-10 08:16
@Kojoley the wheel you provided for #12408 fixed that problem for me. I am using python 3.5.6 with Miniconda on Windows 10 64 Bit . Thanks!

**Comment by tacaswell** [comment] 2018-10-18 17:31
@drdavella The OP here is a windows-specific bug (issues with getting keys out of the the windows registry) so I suspect you were seeing a different issue.

I am very confused by the report that changing what directory you are in making a difference, but if it does, that is almost certainly a bug we need to fix!  Can you open a new issue with more detials (if you can still reproduce the issue).

**Comment by drdavella** [comment] 2018-10-18 17:34
@tacaswell, oops I guess I skimmed this a little too quickly! Yes I can still reproduce it, so I'll open a new issue presently.

**Comment by deansg** [comment] 2018-10-19 08:19
Just wanted to add that as of today I can still reproduce it. Using Windows 10 with a 32-bit version of Python 3.5.2, installed mathplotlib via pip, and I get the exact same error when importing the module.

**Comment by tacaswell** [comment] 2018-10-19 15:10
@deansg That is expected, the fix is in the source but has not been released yet.  The current plan is to release 3.0.1 around Nov 3.

**Comment by deansg** [comment] 2018-10-19 16:11
@tacaswell Alright, I wasn't sure about it because after reading the entire exchange, at one point the focus shifted to a (possibly different?) bug in OSX and I couldn't figure out what the current status is. Maybe it will be beneficial to include an explicit workaround in the description (such as downgrading to 2.2.3)?

**Comment by erotavlas** [comment] 2018-11-20 18:43
What is the solution for this?  
I'm getting this error in conda environment using matplotlib v3.0.0

**Comment by drdavella** [comment] 2018-11-20 18:46
@erotavlas you should be able to install 3.0.1 using conda now.

**Comment by erotavlas** [comment] 2018-11-20 18:53
@drdavella  it wont let me, either from the prompt (conda update matplotlib) or from the anaconda navigator...it says "All requested packaged already installed "

**Comment by higgsch** [comment] 2019-01-13 06:37
Just installed v3.0.2 and am getting the exact same error. Python 3.6.0. Windows 8.1.

**Comment by wenzao** [comment] 2019-01-14 22:55
Are you all getting v3.0.1 now? My conda still only has v3.0.0 (python 3.6.8).

**Comment by band-a-prend** [comment] 2020-03-19 22:03
This issue is still reproduced for me on gentoo linux for python 3.6.10 + myplotlib 3.1.2 with error about no such file in "/home/user/.cache/matplotlib/fontlist-v310.json"
