### ISSUE TITLE
[Bug]: X-Axis date label not rotated

### ISSUE THREAD

**Issue by johan162** [matplotlib/matplotlib#22521] opened 2022-02-21 15:30 UTC
### Bug summary

Using a date x-axis that are being autoscaled outside the initial data range due to the added vline then the first (and only the first) data label gets no rotation.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import datetime

dates = [datetime.datetime(2022, 2, 21, 0, 0),
         datetime.datetime(2022, 2, 22, 0, 0),
         datetime.datetime(2022, 2, 27, 0, 0)]
data1 = [5,8,12]

fig, ax = plt.subplots(1, 1, figsize=(20/2.54, 12/2.54))
plt.subplots_adjust(left=0.08, bottom=0.15, right=0.95)
plt.title("Date x-axis label angle bug")

b1 = ax.bar(dates, data1, width=0.7)

# Setup the date x-axis in weeks marking start of each week start
ax.xaxis.set_major_locator(mdates.WeekdayLocator(byweekday=mdates.MO))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%a %b %d'))

# The same problem regardless the method to set the angle
#for label in ax.get_xticklabels(which='major'):
#    label.set(rotation=30, horizontalalignment='right')
plt.xticks(rotation=30, ha="right")

# Add a vline to force the auoscaling outside the data range
plt.axvline(x=datetime.datetime(2022, 3, 15, 0, 0))

plt.show()
```

### Actual outcome

As can be seen in the screenshot the Feb 28 label is not rotated.

![Screenshot 2022-02-21 at 16 19 12](https://user-images.githubusercontent.com/1390967/154983352-c9d03bbd-3d10-48b0-89fa-3d0f2fe07eb2.png)

### Expected outcome

That the dates are rotated as in the following screenshot.
![Screenshot 2022-02-21 at 16 22 14](https://user-images.githubusercontent.com/1390967/154983847-c47e312e-dc5e-4f6d-bced-36c53da76700.png)

Note: As long as the initial dates for the available data extends past Feb 28 then the labels are correctly rotated

### Additional information

This seems to occur if the autoscale range is forced outside the initial range (as required by the data) by the addition of annotations and/or vlines outside the original x-axis data span.

### Operating system

OSX

### Matplotlib Version

3.5.1

### Python version

3.9.10

### Installation

pip

**Comment by jklymak** [comment] 2022-02-21 15:47
Are dates actually needed to trigger this?

**Comment by johan162** [comment] 2022-02-21 16:20
I cannot be absolutely sure but I haven't been able to recreate it with plain text labels. For example

```
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import datetime

datax = [1,2,3]
labels = ['Zero', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven','Eight', 'Nine']
data1 = [5,8,12]

fig, ax = plt.subplots(1, 1, figsize=(20/2.54, 12/2.54))
plt.subplots_adjust(left=0.08, bottom=0.15, right=0.95)
plt.title("x-axis label angle bug")
b1 = ax.bar(datax, data1, width=0.7)

ax.set_xticklabels(labels, rotation=30, ha='right')

plt.axvline(x=7)
plt.show()
```

Works as expected. 

I actually realized there is a trivial workaround and that is to change the order of the adjustment of the labels and additional graph details. So instead of 

```
plt.xticks(rotation=30, ha="right")
plt.axvline(x=datetime.datetime(2022, 3, 15, 0, 0))
```
you swap to

```
plt.axvline(x=datetime.datetime(2022, 3, 15, 0, 0))
plt.xticks(rotation=30, ha="right")
```

it works since I assume that with the addition of the vline the xmax is adjusted and the full scale range is subjected to the rotation adjustment. So this seems highly likely (but not certain) to be some corner case involving date axis generation.

**Comment by mylasem** [comment] 2022-04-11 19:10
@jklymak I can work on this if this is still an issue. Just want to make sure i understand the problem correctly, if the **xticks** method is used before the **axvline** method, the date should still rotate as shown in the expected outcome. Is this correct?

**Comment by tacaswell** [comment] 2022-04-11 22:19
@mylasem Correct, independently of what plotting is done and in what order, all of the ticks should be rotated the same.

**Comment by timhoffm** [comment] 2022-04-12 00:00
https://github.com/matplotlib/matplotlib/blob/b36ef478bd07be1cf525789696d8d0334d913b67/lib/matplotlib/pyplot.py#L1817-L1819

is probably the cause. We may have more ticks allocated internally than are returned by `get_xticklabels`.

That said, we haven't specified the behavior of `plt.ticks(**kwargs)`. Does it only apply to current tick labels (which I think is the cause of the present issue), or does it define a global state similar to `plt.tick_params()`. If the latter, we probably have to tap into the mechanics used in `tick_params()`. Note however that parameter names may differ and we'd have to make sure to accept exactly the Text properties.
This might be a bit tedious. Therefore, I could also see an argument for not allowing  `plt.ticks(**kwargs)`, and instead refer the user to `tick_params()`.

**Comment by Sakyce** [comment] 2023-04-04 10:33
Any workarounds ?

**Comment by jklymak** [comment] 2023-04-04 14:39
Call fig.draw_without_rendering before rotating the ticks?

**Comment by scpsc** [comment] 2024-01-17 09:55
> Call fig.draw_without_rendering before rotating the ticks?

I have the same problem, with the second tick (also a date) being the only one which is not rotated. I am using :
`plt.setp(ax.get_xticklabels(), rotation=30, ha='right')`

And this workaround works for me, thanks!

**Comment by timhoffm** [comment] 2024-12-09 14:00
The recommended solution from 3.11 on will be the new tick rotations modes introduced in #28968, i.e. here

```
plt.xaxis.set_tick_params(rotation=30, rotation_mode="xtick")
```

I'm closing this as there is a current workaround (`fig.draw_without_rendering()`) and a better future tick styling using `tick_params`.

**Closed by timhoffm** 2024-12-09 14:00 UTC
Labels: topic: ticks axis labels
