### ISSUE TITLE
[Doc]: Visited link color in dark mode hard to see

### ISSUE THREAD

**Issue by pllim** [matplotlib/matplotlib#27832] opened 2024-02-28 19:41 UTC
### Documentation Link

https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.imshow.html

### Problem

Click on links in dark mode, then go back to the page and see the links become "visited links" and turn dark purple that is not easy to see anymore.

<img width="222" alt="Screenshot 2024-02-28 143823" src="https://github.com/matplotlib/matplotlib/assets/2090236/e2c997a3-dfee-450b-9ee6-4b4b6dab4ed1">

### Suggested improvement

Make it easier to see in dark mode.

Thanks!

**Comment by timhoffm** [comment] 2024-02-28 23:35
This is a duplicate of #27652.

**Closed by timhoffm** 2024-02-28 23:35 UTC
Labels: Documentation
