### ISSUE TITLE
(Re-)Generate automatic legend

### ISSUE THREAD

**Issue by nilswagner** [matplotlib/matplotlib#5496] opened 2015-11-17 08:18 UTC
Is it possible to use matplotlibrc to configure the behavior of the regeneration of the legend ?
IMHO, the default should be an activated checkbox.
![figure_options](https://cloud.githubusercontent.com/assets/5382885/11205949/179aed26-8d0c-11e5-9439-b1405aa6f82c.png)

**Comment by tacaswell** [comment] 2015-11-17 17:04
The reason it is not checked by default is that it can be destructive if the user has used `legend` manually (to change labels or to use proxy artists).

**Comment by nilswagner** [comment] 2015-11-17 17:38
Ok. Is there any workaround to modify the current behavior ?

**Comment by Higgs32584** [comment] 2023-03-25 21:33
Someone should check if this issue is still prevalent

**Comment by tacaswell** [comment] 2023-03-27 14:35
Per https://github.com/matplotlib/matplotlib/blob/676773859604eddb3bf7ac782a6af0cf978162b6/lib/matplotlib/rcsetup.py#L813-L1256 there is still not an rcparam for this.

**Comment by Higgs32584** [comment] 2023-03-27 14:46
Since this was raised 7 years ago, it's probably better to open up another issue request with an up to date screenshot, and make sure the issue is fully defined. Given the thousands of commits between when this issue was raised and now, I doubt the solution or the problem will be exactly the same. Also good so other people can see it at the top

**Comment by tacaswell** [comment] 2023-03-27 16:12
That is a good idea but I would add it to this issue rather than making a new one. There are some parts of the Matplotlib codebase that are very stable (one of our goals is to not break users!).  I think that the solution now is exactly the same: add an rcparam so that users can change a hard-coded default to one that they can control.

@Higgs32584 can you please take that screen shot?

**Comment by Higgs32584** [comment] 2023-03-27 16:24
I do not know how he generated this GUI

**Comment by tacaswell** [comment] 2023-03-27 16:30
The "edit axes" button on the Qt UI (it looks like an upward pointing graph).

**Comment by Higgs32584** [comment] 2023-03-27 19:58
![Screenshot 2023-03-27 155826](https://user-images.githubusercontent.com/55243596/228052773-c6a3141b-6d6b-4bc5-9ea7-73f5f93dbc95.png)

**Comment by Higgs32584** [comment] 2023-03-27 20:22
Hello, would setting

[#matplotlib/lib/matplotlib/backends/qt_editor/figureoptions.py

line 64 ](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/backends/qt_editor/figureoptions.py#L64)


to true technically fix this problem or no? I imagine it does not cause if it was he likely would have already submitted a pull request.

**Comment by tacaswell** [comment] 2023-03-27 21:14
It would fix this problem and create a different one in its place as it is just flipping the hard-coded default from one value to another.  We would then have a different set of users who are happy with the current behavior unhappy about having to un-tick the box every time in future versions.

As I said above, I think that `True` is a un-safe default because it will replace any manual calls to `fig.legend()` with the auto-generated one (and adding the logic to "only auto-generate if it was not manually generated" is too much complexity in my opinion) so the options are an rcParam (so people can opt-into dangerous behavior) or no action.

**Comment by Higgs32584** [comment] 2023-03-27 21:48
Ah, I see, so you can create an rcParam, but how would you link an rcParam to this desired functionality? What part reloads the legend

**Comment by tacaswell** [comment] 2023-03-28 16:48
We would change the line you link to above to something like

```python
('(Re-)Generate automatic legend', mpl.rcParams['figureoptions.dflt_autogenerate_legend']), 
```

(and make sure that actually gets run when the window is created not just at import time).

**Comment by Higgs32584** [comment] 2023-03-28 17:07
I imagine that would require importing mpl, would we be willing to do that if only one rcParam is present in figureoptions.py?

**Comment by Higgs32584** [comment] 2023-03-29 22:20
Ok I'll submit a PR for this and I'll think up some tests

**Comment by rcomer** [comment] 2023-06-03 15:05
Since my above comment got no objections and one :+1:, I'm going to go ahead and close this.

**Closed by rcomer** 2023-06-03 15:05 UTC
Labels: topic: rcparams, Difficulty: Easy
