### ISSUE TITLE
'Random' color in scatter3D when depthshade is False

### ISSUE THREAD

**Issue by MarkusSchwarz1980** [matplotlib/matplotlib#18336] opened 2020-08-24 08:04 UTC
When kwarg `depthshade` is `False`, the color of the points is seemingly random.

### Bug report

**Bug summary**

When kwarg `depthshade` is `False` in scatter3D, the color of the points is seemingly random. Using `depthshade=True` gives the correct colors.

**Code for reproduction**

```python
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
backend = matplotlib.get_backend()

# to reproduce values
np.random.seed(1234)

# 3D Gaussian distribution of points
data = np.random.normal(0, 1, size=(3,1000))

for depthshade in [False, True]:
    fig = plt.figure(f'backend {backend}, depthshade={depthshade}', clear=True)
    ax3d = fig.gca(projection='3d')
    ax3d.set(title=f'backend {backend}, depthshade={depthshade}', 
             xlabel='x', ylabel='y', zlabel='z')
    
    # color data according to z-coordinate
    scatter = ax3d.scatter(*data, c=data[2], depthshade=depthshade)
    
    fig.colorbar(scatter, label='z-coordinate')
    fig.tight_layout()
    
    plt.show()
```

**Actual outcome**

![Qt5Agg_False](https://user-images.githubusercontent.com/27952782/91016824-a9fa8980-e5ed-11ea-8a3e-6e0ce597e9cb.png)
With `depthshade=False` the color is assigned seemingly randomly.

**Expected outcome**
![Qt5Agg_True_linear](https://user-images.githubusercontent.com/27952782/91017952-3194c800-e5ef-11ea-9189-0caea4e2d032.png)
With `depthshade=True` the color is assigned correctly. 

The problem appeared after I updated these packages from conda-forge:
attrs                           19.3.0-py_0 --> 20.1.0-pyh9f0ad1d_0
matplotlib                        3.3.1-0 --> 3.3.1-1
matplotlib-base   3.3.1-py37h886f89f_0 --> 3.3.1-py37h886f89f_1
numpy              1.19.1-py37h1efc2f6_1 --> 1.19.1-py37h1efc2f6_2
The problem persisted after I reverted back to matplotlib 3.3.1-0 and matplotlib-base 3.3.1-py37h886f89f_0. (Maybe I did not revert back to the old version, since `matplotlib._version.get_versions()` prints   `'full-revisionid': '079e015ccad39526098098c05b5e7e510fef19df'` with either build?)

Sometimes (i.e. I have not managed to reproduce it reliably) the face- and edge-colors don't agree when `depthshade=True`.

**Matplotlib version**

  * Operating system: macOS 10.15.6 (19G2021)
  * Matplotlib version: 3.3.1-1 (from conda-forge)
  * Matplotlib backend (`print(matplotlib.get_backend())`): tested in Qt5Agg and MacOSX
  * Python version: 3.7.8
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by QuLogic** [comment] 2020-08-24 21:43
This is a duplicate of #18287.

**Closed by QuLogic** 2020-08-24 21:43 UTC
