### ISSUE TITLE
Weird looking surface plot in matplotlib

### ISSUE THREAD

**Issue by jiadong93** [matplotlib/matplotlib#14647] opened 2019-06-29 05:17 UTC
### Bug report

It seems matplotlib's 3d plot components is not rendering things right. The lines are disappearing at the top of surface plot.

**Bug summary**

**Code for reproduction**

```python
from mpl_toolkits.mplot3d import Axes3D

kk = 3
sigma = 0.8
t = np.linspace(-kk, kk, 128)
x, y = np.meshgrid(t, t)
f = (1-(x**2+y**2)/2/sigma**2)*np.exp(-(x**2+y**2)/2/sigma**2)/sigma**4

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(x,y, f, rcount=20, ccount=20)
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/15790176/60379952-4ddeb880-9a6f-11e9-994c-490b594f3855.png)

**Matplotlib version**

  * Operating system: Windows10
  * Matplotlib version:  3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7
  * Jupyter version (if applicable):
  * Other libraries: numpy

**Comment by WeatherGod** [comment] 2019-06-29 15:45
With rcount and ccount being set to 20 when you have 128 data points
available, the results will look "weird". Increase the counts for a higher
resolution result.

**Comment by GeekMe93** [comment] 2019-06-30 01:39
@WeatherGod , well, I increase the `rcount` and `ccount` values, it still looks wired...

![image](https://user-images.githubusercontent.com/15790176/60391151-9901d580-9b1a-11e9-86a3-e3bb43cba510.png)

See the top of of the surface, pls compare with the results from mathematica:

![image](https://user-images.githubusercontent.com/15790176/60391160-b46ce080-9b1a-11e9-8ff4-4e020e9988e8.png)

It seems matplotlib's 3D visulization is not comparable with it 2D plotting counterpart... 2D plotting in matploltib is fantastic...

**Comment by timhoffm** [comment] 2019-06-30 08:22
Indeed the grid lines are not drawn on the peak.

![peekQ00E4Z](https://user-images.githubusercontent.com/2836374/60394142-edf41a80-9b1f-11e9-851f-53c8c7911c6c.gif)

Obeservations:
- It depends on the viewing angle.
- It does not depend on the absolute height (the grid on the elevated borders stay visible)
- The limit is some curved line.

![image](https://user-images.githubusercontent.com/2836374/60394195-cd789000-9b20-11e9-9d8c-52c113430813.png)

Maybe something is going wrong with z-order calculation and Matplotlib thinks the grid is hidden there.

**Comment by WeatherGod** [comment] 2019-06-30 18:50
I'll say it again. mplot3d is not a true 3d renderer. It can never be one
due to the limitations of the 2d layering engine the underpins matplotlib.
Yes, mathmatica and other tools will render these things better. Please
view the FAQ for mplot3d:
https://matplotlib.org/mpl_toolkits/mplot3d/faq.html

**Comment by astromancer** [comment] 2020-03-02 21:15
Empirically, what I think is happening here: The polygons that make up the surface are drawn by default without any edgecolors. The ruled grid you see on the surface is due to the **gaps** between the polygons, not  actual grid lines.  You see the "lines" At the positions where the backdrop is white, but not visible where the backdrop is the face of another polygon.  So you can easily remedy this situation by adding an `edgecolor` to the polygons.

```python
fig, ax = plt.subplots(subplot_kw=dict(projection='3d'))
ax.plot_surface(x,y, f, rcount=20, ccount=20, edgecolor='0.7', linewidth=0.2)
```

![3dplot](https://user-images.githubusercontent.com/5623552/75718398-88be7d80-5cdb-11ea-96af-fa44530fb61f.png)

**Comment by QuLogic** [comment] 2020-09-03 01:09
As @astromancer says, these are not actually intentional, but artifacts of drawing multiple patches next to each other. So I'm closing this as a duplicate of #1188.

**Closed by QuLogic** 2020-09-03 01:09 UTC
Labels: Confirmed bug, mplot3d
