### ISSUE TITLE
[Bug]: unexpected axvspan behavior in polar plot

### ISSUE THREAD

**Issue by ycopin** [matplotlib/matplotlib#25571] opened 2023-03-29 18:07 UTC
### Bug summary

When coloring an angular wedge in a polar plot with `axvspan`, I expect the colored part to go from θ1 to θ2, both interpreted modulo 2π. E.g. I expect the [-3π/4, +3π/4] wedge to be the same as the [5π/4, 3π/4] one, because 5π/4 = -3π/4 [2π]. 

This is currently not the case, probably because of an (undocumented?) flip of the vspan limits (which somehow _could_ make sense in a rectilinear plot), so [5π/4, 3π/4] is first flipped to [3π/4, 5π/4], and the resulting wedge is not the same as the expected [-3π/4, +3π/4] one.

As a workaround, `axvspan` in polar plot works fine if θ1 < θ2, so in the above example, [-3π/4, +3π/4] and [5π/4, 11π/4] are looking the same.

I suggest either to disable the automatic flip of vspan angular limits in polar coordinates, or to issue a warning/error if  θ1 > θ2.

### Code for reproduction

```python
fig = plt.figure()

ax = fig.add_subplot(1, 2, 1, projection='polar')
ax.axvspan(-3*np.pi/4, 3*np.pi/4, fc='g', alpha=0.2)
ax.axvspan(5*np.pi/4, 3*np.pi/4, fc='r', alpha=0.2)
ax.set_title("Observed")

ax = fig.add_subplot(1, 2, 2, projection='polar')
ax.axvspan(-3*np.pi/4, 3*np.pi/4, fc='g', alpha=0.2)
ax.axvspan(5*np.pi/4, 11*np.pi/4, fc='r', alpha=0.2)
ax.set_title("Expected")
```

### Actual outcome

![polar](https://user-images.githubusercontent.com/812050/228625347-a653233c-7bd7-4b93-9664-641d31e0c9a8.png)

### Expected outcome

See above.

### Operating system

Ubuntu 20.04.6 LTS

### Matplotlib Version

3.6.2

### Matplotlib Backend

Qt5Agg

### Python version

Python 3.8.10

### Installation

pip

**Comment by ksunden** [comment] 2023-03-31 19:55
I think that this is intended behavior.

There are two steps that are happening when plotting onto polar axes:

- The cartesian coordinates are computed first
- Then those shapes are "wrapped" into the polar axes

There is no directionality to the cartesian rectangle that is formed by `axvspan`.

The difference between the ones that go around the circle vs the ones that don't are the size of the original rectangle before the "wrapping" transformation and whether or not they cross `0`/`2 pi`/`4 pi`/etc

Changing this behavior would be a departure from how most polar artists are computed, and would likely break for people who rely on the existing behavior.

**Comment by dstansby** [comment] 2024-01-14 18:41
I agree that this is expected behaviour for the reasons above, so I'll close this.

**Closed by dstansby** 2024-01-14 18:41 UTC
Labels: topic: polar
