### ISSUE TITLE
[Bug]: Animation is shifted in interactive mode

### ISSUE THREAD

**Issue by sigvaldm** [matplotlib/matplotlib#22124] opened 2022-01-06 10:19 UTC
### Bug summary

Plot in mp4 file generated by `FFMpegWriter` is shifted right when also using interactive mode (`plt.ion()`). The rightmost part of the plot appear on the left. If you look closely, the first frame is not only shifted, but also skewed. This does not affect the window opened by `plt.show()`, only the mp4 file.

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib.animation import FFMpegWriter
import numpy as np

plt.ion()
fig, ax = plt.subplots()
plt.show()

writer = FFMpegWriter(fps=5)
with writer.saving(fig, "output.mp4", dpi=100):

    x = np.linspace(0,2*np.pi,20)

    for t in np.linspace(0,2*np.pi,20):

        ax.clear()
        ax.plot(x, np.sin(x-t))

        fig.canvas.draw()
        fig.canvas.flush_events()

        writer.grab_frame()
```

### Actual outcome

https://user-images.githubusercontent.com/21025915/148367167-2b44a5c3-26ad-4c3f-9be9-af815539ec74.mp4

### Expected outcome

I expect the mp4 file to resemble the animation shown when running the example code.

### Operating system

Arch Linux

### Matplotlib Version

3.5.0

### Matplotlib Backend

QtAgg

### Python version

3.9.9

### Installation

Linux package manager

**Comment by jklymak** [comment] 2022-01-06 10:27
This doesn't seem a reasonable place to have interactive mode turned on and you are probably grabbing the frame in the middle of the "interactive" draw.

**Comment by sigvaldm** [comment] 2022-01-06 10:37
In the real scenario, I pause the first frame until I have indicated a point of interest with the mouse, which is why I use interactive mode. That is the only time I interact with the plot, and all the frames are grabbed after that. I do not grab any frames in the middle of the interaction. Do you have another way of doing what I want besides interactive mode? Regardless of whether this is a common thing to do or not, I would say the current behavior is a bug (although I understand your need to prioritize).

**Comment by QuLogic** [comment] 2022-01-07 04:44
I cannot reproduce this with the above code; the `output.mp4` looks fine. The sort of sliding display you get is usually caused by incorrectly specifying the width to ffmpeg, but it appears you cannot resize the window once the writer is initialized, so I don't know how you are getting that.

**Comment by sigvaldm** [comment] 2022-01-07 16:05
How odd! You are right, though, I do not resize the window or specify the width. I just run the above code as it is and get the attached file output.mp4. I suppose the GUI backend `QtAgg` is not involved in writing video files, so then that is not the difference between our systems. Could it be a Python 3.9 plus Matploblib thing?

**Comment by scottshambaugh** [comment] 2022-01-11 03:04
I cannot reproduce on python 3.9.7 and the latest `main` branch of matplotlib.

**Comment by QuLogic** [comment] 2022-01-11 07:58
It could also be the version of ffmpeg disagreeing about input sizes. You could try the `FFMpegFileWriter` instead to see if that works, since that writes to individual files with full metadata and ffmpeg cannot get confused about the size.

**Comment by sigvaldm** [comment] 2022-01-11 08:08
Good catch, @QuLogic! I just tried replacing `FFMpegWriter` with `FFMpegFileWriter` (which I didn't know existed), and that worked wonders. FYI, here's the ffmpeg version:

```
$ ffmpeg -version
ffmpeg version n4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 11.1.0 (GCC)
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
```

**Comment by jklymak** [comment] 2022-01-20 08:04
I'll close this, but feel free to ask for a reopen

**Closed by jklymak** 2022-01-20 08:04 UTC
Labels: status: needs clarification

**Comment by tacaswell** [comment] 2022-01-21 00:20
My guess is that the underlying issue here is the canvas resizing itself to match the number of pixels on the screen.  We can control (in Matplotlib) the size in inches and the dpi but in Qt we have an integer number of pixels to fit the plot into so we tweak the size of the figure to match the size of the window.   We have in the past had issues with this taking more than one "cycle" to settle down.  Putting a `plt.pause(.1)` outside of the loop may help?

**Comment by sigvaldm** [comment] 2022-01-21 07:45
Although changing to `FFMpegFileWriter` fixed the issue for me, I thought I'd test your hypothesis, @tacaswell, since my system appears to be one of a few affected, and in case someone else would like to have a go at fixing this later. I'm not sure I understood exactly where to put the pause, but I placed a bunch of them:

```
import matplotlib.pyplot as plt
from matplotlib.animation import FFMpegWriter, FFMpegFileWriter
import numpy as np

plt.ion()
fig, ax = plt.subplots()
plt.show()

writer = FFMpegWriter(fps=5)
# writer = FFMpegFileWriter(fps=5)

plt.pause(.1)

with writer.saving(fig, "output.mp4", dpi=100):

    x = np.linspace(0,2*np.pi,20)

    plt.pause(.1)

    for t in np.linspace(0,2*np.pi,20):

        ax.clear()
        ax.plot(x, np.sin(x-t))

        fig.canvas.draw()
        fig.canvas.flush_events()

        plt.pause(.1)
        writer.grab_frame()
        plt.pause(.1)

    plt.pause(.1)
```
This did not fix the issue.

**Comment by tacaswell** [comment] 2022-01-21 16:12
I appreciate the exhaustive approach to adding pauses!  I think that rules out my first guess.

My next guess is dpi miss-match between the figure and the writer, but I'm having a harder time coming up with an explanation there.

**Comment by tacaswell** [comment] 2022-01-21 16:16
I can reproduce this with QtAgg and can not with TkAgg which makes me think that this is related to high-dpi screen somehow.

**Comment by tacaswell** [comment] 2022-01-21 22:33
This patch seems to fix it locally for me:

```diff
diff --git a/lib/matplotlib/animation.py b/lib/matplotlib/animation.py
index 7909d11352..51c8df33db 100644
--- a/lib/matplotlib/animation.py
+++ b/lib/matplotlib/animation.py
@@ -346,7 +346,7 @@ class MovieWriter(AbstractMovieWriter):
         _log.debug('MovieWriter.grab_frame: Grabbing frame.')
         # Readjust the figure size in case it has been changed by the user.
         # All frames must have the same size to save the movie correctly.
-        self.fig.set_size_inches(self._w, self._h)
+        self.fig.set_size_inches(self._w, self._h, forward=False)
         # Save the figure data to the sink, using the frame format and dpi.
         self.fig.savefig(self._proc.stdin, format=self.frame_format,
                          dpi=self.dpi, **savefig_kwargs)

```

I think what is going on is that the logic in https://github.com/matplotlib/matplotlib/blob/1791022ad019f351ed7f66e05732904dda70af7b/lib/matplotlib/animation.py#L344-L352 is trying to prevent exactly this situation, but we are either caching the size at the wrong time or something is not quite right with the Qt (or other hi-dpi) cycle (the same thing I was worried about before, but through a different mechanism).

Unfortunately I testing movies is really hard so I do not think we can add a test for this, but if someone wants to pick this up the work we need is a non-hand-waving explanation of what is going wrong!

Putting some prints in the (current code) as

```diff
diff --git a/lib/matplotlib/animation.py b/lib/matplotlib/animation.py
index 7909d11352..8807edfd78 100644
--- a/lib/matplotlib/animation.py
+++ b/lib/matplotlib/animation.py
@@ -344,9 +344,12 @@ class MovieWriter(AbstractMovieWriter):
     def grab_frame(self, **savefig_kwargs):
         # docstring inherited
         _log.debug('MovieWriter.grab_frame: Grabbing frame.')
+        print('pre', self.fig.get_size_inches())
+        print('target', [self._w, self._h])
         # Readjust the figure size in case it has been changed by the user.
         # All frames must have the same size to save the movie correctly.
         self.fig.set_size_inches(self._w, self._h)
+        print('post', self.fig.get_size_inches())
         # Save the figure data to the sink, using the frame format and dpi.
         self.fig.savefig(self._proc.stdin, format=self.frame_format,
                          dpi=self.dpi, **savefig_kwargs)

```

I see

```
✔ 17:25:20 $ python test4.py
pre [6.4 4.8]
target [6.4, 4.8]
post [6.39 4.79]
pre [6.39 4.79]
target [6.4, 4.8]
post [6.4 4.8]
...
```

so we get one frame that is too small, but because we are streaming these into a pipe as raw RGBA, ffmpeg grabs it in the size chunks it expects.  The first frame is too small in both dimensions (so it looks slanted) and the rest of the frames are the right size, but because the missing pixels from the top left of the second frame got eaten by the bottom left of the first frame it looks horizontally wrapped
