### ISSUE TITLE
Tiles seem to overlap in zoomed out hexbin

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#7841] opened 2017-01-16 13:47 UTC
When looking at a zoomed out hexbin plot, the tiles seem to overlap, with the right-most tiles lying on top of the left-most tiles. This is present on master (see http://matplotlib.org/devdocs/_images/hexbin_demo.png), and here is an example (it helps to zoom into the .png image):

![screenshot from 2017-01-16 13-27-39](https://cloud.githubusercontent.com/assets/6197628/21985394/57c9b9dc-dbf2-11e6-860a-ed8f3c995728.png)

**Comment by tacaswell** [comment] 2017-01-16 16:58
This also happen in 2.0.0rc2

http://matplotlib.org/2.0.0rc2/_images/hexbin_demo.png

However this is not a regression, it has been like this for a long time: http://matplotlib.org/1.2.1/_images/hexbin_demo.png

**Comment by efiring** [comment] 2017-01-16 17:04
This is the ever-present problem of filling adjacent patches--the same as the problems with contourf.  If the edges are not stroked at all, there are light artifacts.  If the edges are stroked, as has always been the choice in hexbin, then the patches overlap, which is what is we see here.  Turning anti-aliasing on or off modifies the artifacts, and their behavior also changes depending on alpha, but the upshot is that we have never found a solution for this problem.  It seems to be a general problem with renderers.  For hexbin, using a thin edgewidth helps.

**Comment by anntzer** [comment] 2017-06-29 01:01
https://lists.cairographics.org/archives/cairo/2007-July/011098.html may be relevant (to explain the issue, not to solve it).

**Comment by anntzer** [comment] 2017-07-10 08:09
It may be possible to fix this issue by drawing the hexbin as a quadmesh rather than a polycollection.

**Comment by efiring** [comment] 2017-07-10 18:19
I don't think so.  First, hexagons are not quadrilaterals.  Second, the quadmesh is not immune to the adjacent patch rendering problems.

**Comment by anntzer** [comment] 2017-07-10 18:24
1. A hexagon can be represented as two quadrilaterals (in fact, splitting each hexagon in a top and a bottom half actually gives you a proper quadmesh).
2. I see no seams in https://files.gitter.im/matplotlib/matplotlib/9dTT/default-quadmesh.png, so I assume that Agg (and cairo) do have special handling for them.  (At least on cairo's side, the entire quadmesh is defined before rendering, so it *should* have all the info to compute the seams between the quads.)

**Comment by efiring** [comment] 2017-07-10 19:28
1) Yes, of course one can do this.
2) The Agg rendering seems to work well with and without antialiasing, provided alpha is 1.  It does not do so well with alpha = 0.3, for example.  Still, an improvement for the alpha=1 case is worthwhile, so I like your idea.
![alpha3](https://user-images.githubusercontent.com/85125/28035696-4293f756-6551-11e7-86b1-02c5ac33bafc.png)

**Comment by efiring** [comment] 2017-07-10 19:40
It seems there is an inaccuracy in agg quadmesh, though:
```python
x = np.arange(4)
y = np.arange(3)
z = np.arange(6).reshape(2, 3)
X, Y = np.meshgrid(x, y)
pcolormesh(X+Y, X-Y, z)
savefig('skewed.png')
```
All of the corners are slightly chopped off, with the top corner being the most obvious.
![skewed](https://user-images.githubusercontent.com/85125/28036050-7bef8686-6552-11e7-881f-c03b147c31a3.png)

**Comment by QuLogic** [comment] 2023-03-04 02:20
Closing as duplicate of #1188.

**Closed by QuLogic** 2023-03-04 02:20 UTC
