### ISSUE TITLE
[Bug]: 3.5.1 on mips64el: segfault when running on tests

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#21789] opened 2021-11-29 02:45 UTC
### Bug summary

Hello,
we got a couple of bug reports in Debian about matplotlib segfaulting on mipsel when running tests

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000774
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000435 (this is actually for astropy, but it fails the same as the one before)

### Code for reproduction

```python
running the test suite
```

### Actual outcome

```
build/lib.linux-mips64-3.10/matplotlib/tests/test_agg.py::test_repeated_save_with_alpha PASSED [  0%]
build/lib.linux-mips64-3.10/matplotlib/tests/test_agg.py::test_large_single_path_collection Fatal Python error: Segmentation fault

Current thread 0x000000fff1dc1710 (most recent call first):
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/lines.py", line 840 in draw
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/artist.py", line 50 in draw_wrapper
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/axis.py", line 299 in draw
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/artist.py", line 50 in draw_wrapper
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/axis.py", line 1163 in draw
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/artist.py", line 50 in draw_wrapper
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/image.py", line 132 in _draw_list_compositing_images
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/axes/_base.py", line 3082 in draw
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/artist.py", line 50 in draw_wrapper
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/image.py", line 132 in _draw_list_compositing_images
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/figure.py", line 2803 in draw
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/artist.py", line 50 in draw_wrapper
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/artist.py", line 73 in draw_wrapper
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/backends/backend_agg.py", line 436 in draw
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/backends/backend_agg.py", line 540 in print_png
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/_api/deprecation.py", line 412 in wrapper
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/backend_bases.py", line 1643 in wrapper
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/backend_bases.py", line 2314 in print_figure
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/figure.py", line 3012 in savefig
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/pyplot.py", line 958 in savefig
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/tests/test_agg.py", line 61 in test_large_single_path_collection
  File "/usr/lib/python3/dist-packages/_pytest/python.py", line 183 in pytest_pyfunc_call
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/python.py", line 1641 in runtest
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 162 in pytest_runtest_call
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 255 in <lambda>
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 311 in from_call
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 254 in call_runtest_hook
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 215 in call_and_report
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 126 in runtestprotocol
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 323 in _main
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 269 in wrap_session
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 162 in main
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/__init__.py", line 1262 in test
  File "/<<PKGBUILDDIR>>/build/lib.linux-mips64-3.10/matplotlib/_api/deprecation.py", line 205 in wrapper
  File "/<<PKGBUILDDIR>>/tests.py", line 33 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg.lapack_lite, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, matplotlib._c_internal_utils, PIL._imaging, matplotlib._path, kiwisolver, matplotlib._image, _cffi_backend, gi._gi, pvectorc, lxml._elementpath, lxml.etree, PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets (total: 27)
Segmentation fault
```

full build log [here](https://buildd.debian.org/status/fetch.php?pkg=matplotlib&arch=mips64el&ver=3.5.0-2&stamp=1638034545&raw=0)

### Expected outcome

no failure

### Operating system

Debian

### Matplotlib Version

3.5.0

### Python version

3.9.9 and 3.10.0

### Installation

Linux package manager

**Comment by jklymak** [comment] 2021-11-29 08:02
This is dying on `test_agg.py::test_large_single_path_collection` which says:

```
    # Generates a too-large single path in a path collection that
    # would cause a segfault if the draw_markers optimization is
    # applied.
```

Looks like we are causing a segfault, so therefore are applying the optimization?   This logic looks like it was tweaked in 53d2549 by @tacaswell, so maybe he has some ideas if something was missed?

**Comment by QuLogic** [comment] 2021-11-30 03:47
That commit didn't change any C code, just made the limits bigger. It's possibly overflowing now.

Can you get a complete backtrace with gdb?

**Comment by tacaswell** [comment] 2021-11-30 04:16
Due to our minor re-writing of history, github has lost the ability to point to the orign PR: https://github.com/matplotlib/matplotlib/pull/19343 .  The new version of the commit that is likely at fault is  d0b5550bfb06bbbccf3de18c763e45861699ada0 .  @sandrotosi Can you revert that patch on the broken system?

**Comment by sandrotosi** [comment] 2021-11-30 04:30
> @sandrotosi Can you revert that patch on the broken system?

only on mips64el and not on any other architecture? i'm not sure if that's supported by our build tools, i'll investigate

**Comment by QuLogic** [comment] 2021-11-30 09:17
Have you tried 3.4.3 again? It does not appear to pass the tests either, so I'm not sure this is a regression in Matplotlib.

**Comment by QuLogic** [comment] 2021-11-30 09:50
The crash is here:
https://github.com/matplotlib/matplotlib/blob/9765379ce6e7343070e815afc0988874041b98e2/src/_backend_agg.h#L658
and I did not look any further than that. Reverting d0b5550bfb06bbbccf3de18c763e45861699ada0 does not fix the crash.

**Comment by sandrotosi** [comment] 2021-12-01 04:41
(the git reorg makes it kinda tricky to navigate old prs and commit) i just had a look at the previous builds of mpl in Debian, and this was already happening in [3.3.4](https://buildd.debian.org/status/fetch.php?pkg=matplotlib&arch=mips64el&ver=3.3.4-2%2Bb1&stamp=1637459674&raw=0), then all the other builds from that version until the last one were fine.

Even 3.5.0 [built fine once](https://buildd.debian.org/status/fetch.php?pkg=matplotlib&arch=mips64el&ver=3.5.0-1&stamp=1637478122&raw=0) and then [failed](https://buildd.debian.org/status/fetch.php?pkg=matplotlib&arch=mips64el&ver=3.5.0-2&stamp=1638034545&raw=0) in a subsequent upload that was basically a no-code change release (enable of sphinx-panels).

It is very possible that the code causing the segfault has been there for a while, but now it looks like other packages have maybe started to stress the same faulty codepath that previously only mpl tests were using.

**Comment by olebole** [comment] 2021-12-09 11:14
FYI [Debian#1001168 (comment)](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001168#10) contains a backtrace for this issue, and also a minimal example code.

**Comment by sandrotosi** [comment] 2021-12-24 18:12
is there something we (debian) can do to help you figure out what's going on? since we build all matplotlib reverse-dependencies on mips64el too, and with mpl segfaulting there, many of them are also failing, causing quite a bit of a backlog on our end.

thanks!

**Comment by picca** [comment] 2021-12-24 20:47
for info, I rebuilt 3.5.0 on bullseye mips64el chroot and it works.

numpy switched from 1.19.5 to 1.21, so maybe this is something related to  this newer numpy.

here the info I found during my day's of debuging

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001168#57

**Comment by tacaswell** [comment] 2021-12-24 21:26
Try also reverting https://github.com/matplotlib/matplotlib/commit/26e00af0932ebbb1abd73a1e870f314af3515afb ?

Seems trivial, but previously copied paths lost of they should be simplified or not which could in turn be changing  details of which c-code gets run which may have brought this out.

Can someone who has access to a mips64 machine bisect based on @picca 's MWE?

-----

> (the git reorg makes it kinda tricky to navigate old prs and commit) 

Sorry about that,  we accidentally merged a whole virtualenv and its removal into our history.

**Comment by sandrotosi** [comment] 2021-12-27 02:47
just tried reverting 26e00af0932ebbb1abd73a1e870f314af3515afb (and only that commit) and the test suite failed in the same manner.

**Comment by sandrotosi** [comment] 2021-12-27 04:29
i tested:

3.5.0
3.4.3
3.3.4
3.2.2

all of them sigsegv on the same test.

this becomes evident the problem is somewhere else than mpl, likely numpy as picca mentioned. i'll start looking into that now

**Comment by sandrotosi** [comment] 2021-12-28 01:53
i've run again that single test in gdb and got

```
(gdb) r -m pytest build/lib.linux-mips64-3.10/matplotlib/tests/test_agg.py::test_large_single_path_collection --verbose --full-trace
Starting program: /usr/bin/python3.10 -m pytest build/lib.linux-mips64-3.10/matplotlib/tests/test_agg.py::test_large_single_path_collection --verbose --full-trace
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/mips64el-linux-gnuabi64/libthread_db.so.1".
============================================================================================================================= test session starts ==============================================================================================================================
platform linux -- Python 3.10.1, pytest-6.2.5, py-1.10.0, pluggy-0.13.0 -- /usr/bin/python3.10
cachedir: .pytest_cache
rootdir: /home/morph/matplotlib, configfile: pytest.ini
collecting ... [Detaching after vfork from child process 7446]
[Detaching after vfork from child process 7447]
collected 1 item                                                                                                                                                                                                                                                               

build/lib.linux-mips64-3.10/matplotlib/tests/test_agg.py::test_large_single_path_collection 
Program received signal SIGSEGV, Segmentation fault.
agg::pixfmt_alpha_blend_rgba<fixed_blender_rgba_plain<agg::rgba8T<agg::linear>, agg::order_rgba>, agg::row_accessor<unsigned char> >::blend_solid_hspan (covers=0x10000000000 <error: Cannot access memory at address 0x10000000000>, c=..., len=<optimized out>, y=534, 
    x=<optimized out>, this=<optimized out>) at extern/agg24-svn/include/agg_color_rgba.h:395
395             static AGG_INLINE value_type multiply(value_type a, value_type b)
(gdb) 
```

that seems to point to something in `extern/agg24-svn` and not numpy? there's no different between 3.4.3 and 3.5.0 in that directory, so maybe it's another library matplotlib includes that we should be looking at, but which one?

**Comment by sandrotosi** [comment] 2021-12-28 06:34
continuing with the investigation, i checked what packages were different between the last good build (`-`) and the first one that started SIGSEGVing (`+`) and here's an extract of the relevant ones (the full diff can be obtained with this command: ```diff -u <(curl -s 'https://buildd.debian.org/status/fetch.php?pkg=matplotlib&arch=mips64el&ver=3.3.4-2&stamp=1633211581&raw=1') <(curl -s 'https://buildd.debian.org/status/fetch.php?pkg=matplotlib&arch=mips64el&ver=3.3.4-2%2Bb1&stamp=1637459674&raw=1')``` , packages diff starts searching the string _Buildinfo_):

```
- g++ (= 4:10.2.1-1),
- g++-10 (= 10.3.0-11),
- gcc (= 4:10.2.1-1),
- gcc-10 (= 10.3.0-11),
- gcc-10-base (= 10.3.0-11),
- gcc-11-base (= 11.2.0-8),
+ g++ (= 4:11.2.0-2),
+ g++-11 (= 11.2.0-10),
+ gcc (= 4:11.2.0-2),
+ gcc-11 (= 11.2.0-10),
+ gcc-11-base (= 11.2.0-10),

- libfreetype-dev (= 2.10.4+dfsg-1),
- libfreetype6 (= 2.10.4+dfsg-1),
- libfreetype6-dev (= 2.10.4+dfsg-1),
+ libfreetype-dev (= 2.11.0+dfsg-1),
+ libfreetype6 (= 2.11.0+dfsg-1),
+ libfreetype6-dev (= 2.11.0+dfsg-1),

- libgcc-10-dev (= 10.3.0-11),
- libgcc-s1 (= 11.2.0-8),
+ libgcc-11-dev (= 11.2.0-10),
+ libgcc-s1 (= 11.2.0-10),

- libgl1-mesa-dri (= 21.2.2-1),
- libglapi-mesa (= 21.2.2-1),
- libglib2.0-0 (= 2.70.0-1+b1),
- libglibmm-2.4-1v5 (= 2.66.1-1),
+ libgl1-mesa-dri (= 21.2.5-1),
+ libglapi-mesa (= 21.2.5-1),
+ libglib2.0-0 (= 2.70.1-1),
+ libglibmm-2.4-1v5 (= 2.66.2-1),

(note: python 3.10 is added to the list of supported versions)
- libpython3-all-dev (= 3.9.2-3),
- libpython3-dev (= 3.9.2-3),
- libpython3-stdlib (= 3.9.2-3),
- libpython3.9 (= 3.9.7-4),
- libpython3.9-dev (= 3.9.7-4),
- libpython3.9-minimal (= 3.9.7-4),
- libpython3.9-stdlib (= 3.9.7-4),
- libqt5core5a (= 5.15.2+dfsg-12),
- libqt5dbus5 (= 5.15.2+dfsg-12),
+ libpython3-all-dev (= 3.9.8-1),
+ libpython3-dev (= 3.9.8-1),
+ libpython3-stdlib (= 3.9.8-1),
+ libpython3.10 (= 3.10.0-5),
+ libpython3.10-dev (= 3.10.0-5),
+ libpython3.10-minimal (= 3.10.0-5),
+ libpython3.10-stdlib (= 3.10.0-5),
+ libpython3.9 (= 3.9.9-1),
+ libpython3.9-dev (= 3.9.9-1),
+ libpython3.9-minimal (= 3.9.9-1),
+ libpython3.9-stdlib (= 3.9.9-1),
+ libqt5core5a (= 5.15.2+dfsg-13),
+ libqt5dbus5 (= 5.15.2+dfsg-13),
  libqt5designer5 (= 5.15.2-5),

- libstdc++-10-dev (= 10.3.0-11),
- libstdc++6 (= 11.2.0-8),
+ libstdc++-11-dev (= 11.2.0-10),
+ libstdc++6 (= 11.2.0-10),

- linux-libc-dev (= 5.14.6-3),
+ linux-libc-dev (= 5.14.16-1),

- python3 (= 3.9.2-3),
+ python3 (= 3.9.8-1),
  python3-alabaster (= 0.7.12-1),
- python3-all (= 3.9.2-3),
- python3-all-dev (= 3.9.2-3),
- python3-argon2 (= 18.3.0-2+b2),
+ python3-all (= 3.9.8-1),
+ python3-all-dev (= 3.9.8-1),
+ python3-argon2 (= 21.1.0-1),

- python3-cffi (= 1.14.6-2),
- python3-cffi-backend (= 1.14.6-2+b1),
+ python3-cffi (= 1.15.0-1),
+ python3-cffi-backend (= 1.15.0-1+b1),

- python3-numpy (= 1:1.19.5-1),
+ python3-numpy (= 1:1.21.4-2),
```

does any of them ring a bell to you guys?

**Comment by sandrotosi** [comment] 2022-01-03 01:43
I've upgraded matplotlib to 3.5.1 in Debian, and this is the confirmation the test suite still SIGSEGVs when running on mips64el; full build log [here](https://buildd.debian.org/status/fetch.php?pkg=matplotlib&arch=mips64el&ver=3.5.1-1&stamp=1641167485&raw=0)

**Comment by picca** [comment] 2022-01-03 21:33
Hello I investigated a bit more and compiled with gcc-10 and no-lto

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001168#72

no segfault with gcc-10 and no-lto.

**Comment by QuLogic** [comment] 2022-01-05 08:30
> ```
> - g++ (= 4:10.2.1-1),
> - g++-10 (= 10.3.0-11),
> - gcc (= 4:10.2.1-1),
> - gcc-10 (= 10.3.0-11),
> - gcc-10-base (= 10.3.0-11),
> - gcc-11-base (= 11.2.0-8),
> + g++ (= 4:11.2.0-2),
> + g++-11 (= 11.2.0-10),
> + gcc (= 4:11.2.0-2),
> + gcc-11 (= 11.2.0-10),
> + gcc-11-base (= 11.2.0-10),
> 
> - libgcc-10-dev (= 10.3.0-11),
> - libgcc-s1 (= 11.2.0-8),
> + libgcc-11-dev (= 11.2.0-10),
> + libgcc-s1 (= 11.2.0-10),
> ```

Maybe; probably, even?

> ``` 
> - libfreetype-dev (= 2.10.4+dfsg-1),
> - libfreetype6 (= 2.10.4+dfsg-1),
> - libfreetype6-dev (= 2.10.4+dfsg-1),
> + libfreetype-dev (= 2.11.0+dfsg-1),
> + libfreetype6 (= 2.11.0+dfsg-1),
> + libfreetype6-dev (= 2.11.0+dfsg-1),
> ```

There is some text in the test, but that seems unlikely if everything else is fine.

> ```
> - libgl1-mesa-dri (= 21.2.2-1),
> - libglapi-mesa (= 21.2.2-1),
> - libglib2.0-0 (= 2.70.0-1+b1),
> - libglibmm-2.4-1v5 (= 2.66.1-1),
> + libgl1-mesa-dri (= 21.2.5-1),
> + libglapi-mesa (= 21.2.5-1),
> + libglib2.0-0 (= 2.70.1-1),
> + libglibmm-2.4-1v5 (= 2.66.2-1),
> ```

Highly unlikely.

> ```
> (note: python 3.10 is added to the list of supported versions)
> - libpython3-all-dev (= 3.9.2-3),
> - libpython3-dev (= 3.9.2-3),
> - libpython3-stdlib (= 3.9.2-3),
> - libpython3.9 (= 3.9.7-4),
> - libpython3.9-dev (= 3.9.7-4),
> - libpython3.9-minimal (= 3.9.7-4),
> - libpython3.9-stdlib (= 3.9.7-4),
> - libqt5core5a (= 5.15.2+dfsg-12),
> - libqt5dbus5 (= 5.15.2+dfsg-12),
> + libpython3-all-dev (= 3.9.8-1),
> + libpython3-dev (= 3.9.8-1),
> + libpython3-stdlib (= 3.9.8-1),
> + libpython3.10 (= 3.10.0-5),
> + libpython3.10-dev (= 3.10.0-5),
> + libpython3.10-minimal (= 3.10.0-5),
> + libpython3.10-stdlib (= 3.10.0-5),
> + libpython3.9 (= 3.9.9-1),
> + libpython3.9-dev (= 3.9.9-1),
> + libpython3.9-minimal (= 3.9.9-1),
> + libpython3.9-stdlib (= 3.9.9-1),
> + libqt5core5a (= 5.15.2+dfsg-13),
> + libqt5dbus5 (= 5.15.2+dfsg-13),
>   libqt5designer5 (= 5.15.2-5),
> ```

Also doubtful.

> ```
> - libstdc++-10-dev (= 10.3.0-11),
> - libstdc++6 (= 11.2.0-8),
> + libstdc++-11-dev (= 11.2.0-10),
> + libstdc++6 (= 11.2.0-10),
> ```

Agg is in C++, so maybe, but I don't think it uses very much of the standard library.

> ```
> - linux-libc-dev (= 5.14.6-3),
> + linux-libc-dev (= 5.14.16-1),
> ```

Maybe, insomuch as libc affects everything.

> ```
> - python3 (= 3.9.2-3),
> + python3 (= 3.9.8-1),
>   python3-alabaster (= 0.7.12-1),
> - python3-all (= 3.9.2-3),
> - python3-all-dev (= 3.9.2-3),
> - python3-argon2 (= 18.3.0-2+b2),
> + python3-all (= 3.9.8-1),
> + python3-all-dev (= 3.9.8-1),
> + python3-argon2 (= 21.1.0-1),
> 
> - python3-cffi (= 1.14.6-2),
> - python3-cffi-backend (= 1.14.6-2+b1),
> + python3-cffi (= 1.15.0-1),
> + python3-cffi-backend (= 1.15.0-1+b1),
> ```

Nope.

> ```
> - python3-numpy (= 1:1.19.5-1),
> + python3-numpy (= 1:1.21.4-2),
> ```

Maybe.

**Comment by sandrotosi** [comment] 2022-01-29 08:22
this turned out to be a bug in gcc-11 on mips64* architectures (`-O1`/`-O2` may generated bad code, while `-O0`/`-O3` appear to be fine), which in debian we worked around by passing `-O3` to gcc

**Comment by QuLogic** [comment] 2022-01-31 23:36
I'll close this then as an upstream issue.

**Closed by QuLogic** 2022-01-31 23:36 UTC
Labels: status: upstream fix required
