### ISSUE TITLE
matplotlibrc causes import to fail 3.0.0 (didn't crash 2.y.z series)

### ISSUE THREAD

**Issue by dhermes** [matplotlib/matplotlib#12610] opened 2018-10-24 05:25 UTC
Using the following file in the current directory:

```
### MATPLOTLIBRC FORMAT

# See https://matplotlib.org/users/customizing.html

#### CONFIGURATION BEGINS HERE

# Custom math font settings (always use LaTeX "Computer Modern")
mathtext.fontset : cm
mathtext.rm      : serif
```

results in

```python
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.7/site-packages/matplotlib/__init__.py", line 1111, in <module>
    rcParamsOrig = RcParams(rcParams.copy())
  File ".../python3.7/site-packages/matplotlib/__init__.py", line 891, in __getitem__
    from matplotlib import pyplot as plt
  File ".../python3.7/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File ".../python3.7/site-packages/matplotlib/colorbar.py", line 40, in <module>
    import matplotlib._constrained_layout as constrained_layout
  File ".../python3.7/site-packages/matplotlib/_constrained_layout.py", line 52, in <module>
    from matplotlib.legend import Legend
  File ".../python3.7/site-packages/matplotlib/legend.py", line 43, in <module>
    from matplotlib.offsetbox import HPacker, VPacker, TextArea, DrawingArea
  File ".../python3.7/site-packages/matplotlib/offsetbox.py", line 33, in <module>
    from matplotlib.image import BboxImage
  File ".../python3.7/site-packages/matplotlib/image.py", line 19, in <module>
    from matplotlib.backend_bases import FigureCanvasBase
  File ".../python3.7/site-packages/matplotlib/backend_bases.py", line 46, in <module>
    from matplotlib import (
ImportError: cannot import name 'get_backend' from 'matplotlib' (.../python3.7/site-packages/matplotlib/__init__.py)
```

**Comment by cdeil** [comment] 2018-10-24 06:45
For us, this error also started to appear now: https://travis-ci.org/astropy/astropy-healpix/jobs/445499165#L1127

**Comment by QuLogic** [comment] 2018-10-24 06:48
Duplicate of #12601.

**Closed by QuLogic** 2018-10-24 06:48 UTC
