### ISSUE TITLE
Inconsistency in contourf colorbar

### ISSUE THREAD

**Issue by ycopin** [matplotlib/matplotlib#8935] opened 2017-07-25 16:47 UTC
### Bug report

**Bug summary**

I don't know if it's an undocumented/misunderstood feature or just an inconsistency, but `contourf(vmin, vmax)` does not produce expected results when used with a colorbar (i.e. results similar to `imshow(vmin, vmax)`).

**Code for reproduction**

```python
import numpy as N
import matplotlib.pyplot as P

y, x = N.mgrid[-2*N.pi:2*N.pi:11j,-2*N.pi:2*N.pi:11j]
z = N.sin(x) + N.sin(y)

fig, (axI, axC) = P.subplots(1, 2, figsize=(8, 3), tight_layout=True)

im = axI.imshow(z, vmin=0, vmax=1)
fig.colorbar(im, ax=axI, extend='both')
axI.set(aspect='equal', title='Imshow: OK')

ct = axC.contourf(z, vmin=0, vmax=1, extend='both')
fig.colorbar(ct, ax=axC)
axC.set(aspect='equal', title='Contourf: BUG')

P.show()
```

**Actual outcome**

![bug_contourf](https://user-images.githubusercontent.com/812050/28582692-9c15e28c-7166-11e7-8d84-8f9e72a4ffc2.png)

**Expected outcome**

I would expect the `contourf` colorbar to the right to look similar to the `imshow` colorbar to the left. I could set manually the levels, but shouldn't `contourf` levels honor vmin and vmax?

  * Operating System: Linux
  * Matplotlib Version: 2.0.2
  * Python Version: 2.7.12

**Comment by tacaswell** [comment] 2017-07-25 17:33
attn @efiring I have a vague memory of a fix for this going into master?

**Comment by dstansby** [comment] 2017-07-25 19:02
Unfortunately not, it looks the same as above on master (thanks for the easy to copy example!)

**Comment by efiring** [comment] 2017-07-25 19:03
No, vmin and vmax are being handled by contourf the same way they are handled in imshow and others like it: they are simply passed to the norm, so they set the range of the colors.  Setting contour levels is independent of this.

**Comment by efiring** [comment] 2017-07-25 20:59
I think this should be noted in the documentation; I do not think that the present behavior should be changed.

**Comment by ycopin** [comment] 2017-07-25 21:48
I understand this can be seen as an undocumented feature, and this is indeed coherent with `contour` behavior. Note however that by not using vmin & vmax in the computation of the contour levels, some/most/all the levels can fall outside of the [vmin, vmax] range (in the above example, there's only 3 contours visible). 

To follow on my initial intention (having a plot similar to the `imshow` one), there doesn't seem to be an easy way to get `contourf` to act similarly to `imshow`, e.g. a fiducial way to compute the levels from vmin to vmax. `N.linspace(vmin, vmax, 9)` is not enough, internal code uses the `MaxNLocator.tick_values` function. 

Or maybe one could define a new `range` keyword (similar to histograms) that would override the definition of min and max values? (in `QuadContourSet._contour_args)

**Comment by efiring** [comment] 2017-07-25 22:22
If you substitute the following for your present contourf call, doesn't it do what you are asking for?
```python
ct = axC.contourf(z, levels=N.linspace(0, 1, 9), extend='both')
```

**Comment by ycopin** [comment] 2017-07-25 23:07
Not exactly: as I mentioned, `contourf` uses a `MaxNLocator` internally to provide nice-valued coutour levels (and not some arbitrary values as provided by `linspace`).

**Comment by efiring** [comment] 2017-07-26 02:07
No, if you specify levels, it uses those levels.  Please try the line I suggested.

**Comment by QuLogic** [comment] 2017-07-26 02:19
But that's not the point, I think. The point is to pick limits and let Matplotlib choose reasonable levels in whatever way it sees fit.

**Comment by efiring** [comment] 2017-07-26 02:47
Here is the result with the example line above.
![imshow_contourf](https://user-images.githubusercontent.com/85125/28601926-d3e6f8fa-7156-11e7-99c2-372ec10df8ff.png)

Are you asking for vmin and vmax to be used by the internal automatic contour level selection mechanism in place of the actual data limits, in the case where there is no "levels" kwarg, or the levels kwarg is a scalar?

That would not be difficult, but would it really be useful?  What are the circumstances where you know the vmin and vmax values you want to use, regardless of the values in the data array, but don't know the contour levels you want to use--and will be happy with what contourf's automatic selection produces based on the vmin and vmax?

**Comment by ycopin** [comment] 2017-07-26 10:14
Sorry if it was not clear. My point is probably just a consistency issue with `imshow`: I wonder why vmin & vmax only affects the colorscale, but not the automatic levels, so that my test case would have automatically provided a result similar to yours. 

In the current situation, I don't really see the point of having a colorbar (which is built from levels) not adapted to the colormap (built from vmin & vmax), and extending so much with constant color outside [vmin, vmax] (e.g. everything below vmin=0 is dark blue, one cannot see the individual contours).

**Comment by tacaswell** [comment] 2017-07-28 15:01
I think it does make sense to special case vmin and vmax to limit the range of the auto-levels (absent other user input).

**Comment by martok** [comment] 2022-10-06 17:04
I keep running into this issue every couple of months and have not yet found a nice generic version that keeps over/under extends, "nice looking" levels corresponding to the colorbar ticks etc without micromanaging everything.

If nothing else, could the documentation be fixed? For current stable (3.6), the docstring for `levels` says:
> [...] If an int _n_, use `MaxNLocator`, which tries to automatically choose no more than _n+1_ "nice" contour levels between _vmin_ and _vmax_.

This is clearly not true, it creates levels between _Z.min()_ and _Z.max()_. vmin/max don't play a role in level determination (see `ContourSet._autolev`).
Further down, vmin/vmax are described as the "range the colormap covers" which is technically true iff one knows that the colormap values and contour levels have absolutely nothing to do with each other, but it's (IMHO) really not all that obvious.


> I think it does make sense to special case vmin and vmax to limit the range of the auto-levels (absent other user input).

Obviously this may have changed since this issue was originally opened, but currently `contourf` is the odd one out. Both `imshow` and `pcolor(mesh)` already handle vmin/max the way one would expect.

**Comment by jklymak** [comment] 2022-10-06 17:40
@martok, please open a new issue about the documentation issue.  If it is indeed the case that levels is chosen with respect to Z.min/Z.max, then agreed that the documentation is very confusing.  I assume the behaviour has been the same forever, and the documentation is simply incorrect (and maybe has also been incorrect forever).  If the behaviour change is new we should fix.  

That aside, I think the point _here_ is that in general *levels* need not have anything to do with vmin and vmax (e.g. the user can specify whatever they want), and hence the colorbar is doing the right thing showing all the levels, even if some of the colors are saturated.  I'm actually going to close this to prevent confusion, but again encourage a new report on the above.

**Closed by jklymak** 2022-10-06 17:40 UTC
Labels: Documentation, API: consistency, API: changes

**Comment by martok** [comment] 2022-10-07 09:11
Right, will do.
It definitely has been like this forever, and it has bothered me (and others, apparently) since forever.

Quick question before I do that, because that decides what to report:

> That aside, I think the point _here_ is that in general _levels_ need not have anything to do with vmin and vmax (e.g. the user can specify whatever they want)

Since we're talking only about auto-generated default levels here: does the combination of `vmin,vmax,levels=N` even have any use then, if all it can do is generate wildly inconsistent and borderline wrong visualisations? It should probably be discouraged altogether?

**Comment by jklymak** [comment] 2022-10-07 15:47
> Since we're talking only about auto-generated default levels here: does the combination of `vmin,vmax,levels=N` even have any use then, if all it can do is generate wildly inconsistent and borderline wrong visualisations? It should probably be discouraged altogether?

I understand where you are coming from, but it is pretty common to want to adjust the colours independently from the level choice.   The resulting visualizations are not necessarily "inconsistent" or "wrong".

**Comment by ycopin** [comment] 2022-10-07 17:15
@jklymak I tend to disagree: in my humble opinion, the simple code in the original bug report looks "inconsistent" or "wrong" to me from the colorbar perspective.

**Comment by jklymak** [comment] 2022-10-07 17:53
Colorbars show all the levels regardless of how you have coloured them.  You can now change the limits of the colorbars: untested, but `cb.ax.set_ylim(vmin, vmax)` should work...

**Comment by ycopin** [comment] 2022-10-07 18:00
> Colorbars show all the levels regardless of how you have coloured them. You can now change the limits of the colorbars: untested, but `cb.ax.set_ylim(vmin, vmax)` should work...

Indeed, thanks for the tip.

**Comment by martok** [comment] 2022-10-07 18:01
> @jklymak I tend to disagree: in my humble opinion, the simple code in the original bug report looks "inconsistent" or "wrong" to me from the colorbar perspective.

And it gets even more inconsistent when one wanted a continous colorbar and did that by using a separate `ScalarMappable(norm=ct.norm, cmap=ct.cmap)`. Then there's no indication at all that the data is not in fact out of range but the layers just got placed weirdly because the mappable follows the parameters even if the graphics do not.

In any case, writing the doc issue now, I'd prefer if this here could be kept open for the API itself, but if the current behavior is really as intended then that's ok too I guess.

**Comment by efiring** [comment] 2022-10-11 07:15
On 2022/10/07 8:01 AM, Sebastian Hütter wrote:
> And it gets even more inconsistent when one wanted a continous colorbar 
> and did that by using a separate |ScalarMappable(norm=ct.norm, 
> cmap=ct.cmap)|. Then there's no indication at all that the data is not 
> in fact out of range but the layers just got placed weirdly because the 
> mappable follows the parameters even if the graphics do not.

Are you saying you want a continuous colorbar for a contourf plot?  If 
so, why, and under what circumstances would this yield a good 
representation of the information in the plot?

**Comment by martok** [comment] 2022-10-11 11:28
> Are you saying you want a continuous colorbar for a contourf plot? If so, why, and under what circumstances would this yield a good representation of the information in the plot?

Writing that from memory was probably not a good idea, huh? Apologies for that.
The suggestion cam from this [SO question](https://stackoverflow.com/questions/54979958) (not mine) and the [accepted answer](https://stackoverflow.com/a/62659784/3280879). They use 400 levels though, so it's not really obvious why I could never get this to look good with something like 10 levels. Manually generating levels with linspace doesn't (generally) get nice values, setting up a _MaxNLocator_ and using that would probably have been the solution.

In the end, I used _pcolormesh_ and _contour_ for some reference overlays only. Not what I wanted and arguably hard to read, but good enough... ![Figure](https://ars.els-cdn.com/content/image/1-s2.0-S266691292100012X-gr4.jpg)
