### ISSUE TITLE
Unable to set more than one font in legends, impossible to label data with Glyph from multiple languages.

### ISSUE THREAD

**Issue by mvarnold** [matplotlib/matplotlib#15260] opened 2019-09-12 20:31 UTC
### Bug report

**Bug summary**

It is impossible to set more than one font in a legend making it impossible to label data in different languages, such as chinese, arabic and emojis, in the same legend. Allowing prop to accept lists of dictionaries would solve this issue. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt

f, axs = plt.subplots()
plt.plot([i for i in range(5)], label=u"#방탄소년단")
plt.plot([i for i in range(6)], label=u"#🔥")
plt.legend()
plt.show()
```

**Actual outcome**
![image](https://user-images.githubusercontent.com/19533106/64818450-14035580-d57a-11e9-8baf-78d1a406d089.png)

**Expected outcome**

While it would be nice if matplotlib searched for fonts with support for unicode characters, simply allowing lists of fonts to be specified for each handle label, rather than enforcing using one font.

**Comment by anntzer** [comment] 2019-09-13 08:29
> allowing lists of fonts to be specified for each handle label, rather than enforcing using one font.

The problem is well understood, but would require major rearchitecting of the text handling machinery, so is unlikely to happen soon.

**Comment by anntzer** [comment] 2020-11-03 19:27
I'll close this in favor of https://github.com/matplotlib/matplotlib/issues/18883 which is essentially the same but points more explicitly at font-family fallbacks.

**Closed by anntzer** 2020-11-03 19:27 UTC
Labels: Difficulty: Hard, text/fonts
