### ISSUE TITLE
some problem in eps file

### ISSUE THREAD

**Issue by wqshen** [matplotlib/matplotlib#8901] opened 2017-07-17 00:32 UTC
I think that is a matplotlib characteristic, when one draw a plot

```python
import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(0, 10, 500)
dashes = [10, 5, 100, 5]  # 10 points on, 5 off, 100 on, 5 off
fig, ax = plt.subplots()
line1, = ax.plot(x, np.sin(x), '--', linewidth=2,
                 label='Dashes set retroactively')
line1.set_dashes(dashes)
line2, = ax.plot(x, -1 * np.sin(x), dashes=[30, 5, 10, 5],
                 label='Dashes set proactively')
plt.xlim(1, 9)
ax.legend(loc='lower right')
plt.savefig('test1.eps', dpi=1000)
```

set the xlim will force the X-axis within 1-9, the line segment outside 1-9 hide, but it just hide not be clipped, **I don't know how can i actually clip elements with axes extent.**

I use Adobe Illustrator to open eps file. 
You see it is fine,
![image](https://user-images.githubusercontent.com/12339722/28252661-ec331396-6ac9-11e7-8944-317606ef6136.png)
But actually it is,
![image](https://user-images.githubusercontent.com/12339722/28252664-f635dd24-6ac9-11e7-9870-076d9f0ff320.png)

In sometimes, this characteristic is very useful, for example, if one use `plt.show()` to use the interactive mode, one can drag the canvas to left or to right to see the whole line in the range 0-10.

But in eps file, i do not think this characteristic reasonably, it typically increases the eps file size.
**Is it a method to change this behavior ?**

Matplotlib: `1.5.X` or `2.0.X`
OS: `Windows 10`  or `CentOS`

**Comment by tacaswell** [comment] 2017-07-17 15:43
That isn't quite how how the panning works; each time the plot updates it is fully re-drawn.

Looking at the code (in `matplotlib.backends.backend_eps.RendererPS.draw_path` at  https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_ps.py#L493 and https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_ps.py#L470 ) it looks like it _should_ be clipped before outputting to the eps file.

**Comment by WeatherGod** [comment] 2017-07-17 16:45
The second set of dashes is manually specified. Perhaps that is going down
a different codepath?

On Mon, Jul 17, 2017 at 12:19 PM, Thomas A Caswell <notifications@github.com

**Comment by tacaswell** [comment] 2017-07-20 00:34
The dash pattern is set on the graphic context and I am pretty sure I reproduced this with solid lines...

**Comment by QuLogic** [comment] 2023-04-19 02:32
If I run this and open in evince, the lines are correctly clipped, but if I open it in Scribus, then they are not. This might be just a viewer problem, but perhaps there is some less-defined behaviour we are using that could be improved.

**Comment by QuLogic** [comment] 2023-04-20 06:16
After a bit of review of what Scribus appears to do, and what is in the original report, we've come to the conclusion that this is expected behaviour. The line appears to be selected in the original post, so while it appears bigger, it _is_ clipped to the Axes box, but just its data continues outside of it. However, testing confirms that the line data _is_ cropped to the Figure bounds. While we could increase that cropping to the Axes itself, that won't necessarily save output size that much given the existing cropping. I think there's an existing issue already for better clipping (#9488 and similar), so we'll close this one.

**Closed by QuLogic** 2023-04-20 06:16 UTC
Labels: topic: path handling, backend: ps
