### ISSUE TITLE
Gridlines on top of plot by default in 2.0?

### ISSUE THREAD

**Issue by pbreach** [matplotlib/matplotlib#5980] opened 2016-02-09 01:56 UTC
I know the window for default style change proposals has long since closed, but as an avid user who is excited to see the new changes I thought I should ask about this (maybe not the best place either). 

After seeing the recently built devdocs I've noticed the grid lines are now placed on top of the plot. Was this intentional? If so feel free to close this. If not it would be great to see them placed behind the plotted data by default. The new lines look great, but I think the data should come first as done previously.

Just my two cents. Keep up the great work.

**Comment by efiring** [comment] 2016-02-09 02:45
I don't think that was intentional, so thanks for pointing it out.  I think we would want the grid to be behind lines and markers, but on top of major filled areas like images and filled contours.  It's not obvious to me how to handle histograms, bars, and pies, but maybe they should also be on top by default.

**Comment by Tillsten** [comment] 2016-02-09 05:04
This is actually not a default change, they were always drawn on top. One had to use `set_axisbelow` to get the grid in the background, which annoyinglyalso changed the zorder of the other artists of the axis. The behavior just got more visible due to the new gridlines style.

**Comment by pbreach** [comment] 2016-02-09 05:30
Hmmm... I've honestly never noticed that until now. Well maybe it's worth looking at if not now then never. Plots like this are super obvious:

![image](https://cloud.githubusercontent.com/assets/8889265/12908222/9fff95e8-cec2-11e5-8c49-0e5a8f72e5e8.png)

@efiring Good point on the different plot types. I guess there might be some subjectivity on whether to put the grid infront or behind certain plot types (and combinations) if a default set of rules were to be established. Maybe looking to other plotting packages could be useful.

On the other hand, incorporating a `zorder` kwarg in the grid method would probably be do-able and wouldn't have to be part of the default style changes?

**Comment by efiring** [comment] 2016-02-09 05:34
Looking at the code, I don't think this is correct.  `set_axisbelow` gives the grid a zorder of 0.5; otherwise it is 2.5.  I don't think anything else is changed.  It looks to me like a value of 1.5 might actually be a good default.  Furthermore, it is a shame to have set_axisbelow as a Boolean when it could offer finer control, such as a range of options.
@pbreach the `grid` method already accepts a zorder kwarg; it accepts the full set of Line2D kwargs, and zorder is inherited from the Artist base class.

**Comment by efiring** [comment] 2016-02-09 05:38
On second thought, I'm leaning toward the present 0.5 `set_axisbelow` value, and the idea that this should be the default now.  With the new grid lines, the plotted data look like they are in a federal penitentiary.

**Comment by Tillsten** [comment] 2016-02-09 06:28
@efiring IRC the zorder kwargs get overwritten later, i will check that. 
What i saw in some other PR was the proposal that it should be in front of contour, contourf, pcolormesh and image and below everything else, which is properly a good default for most cases. Also the decoupling of the grid/rest of axis of zordner would be a nice feature.

**Comment by u55** [comment] 2016-02-09 19:19
There is a related issue here: #4243.

**Comment by efiring** [comment] 2016-05-02 20:01
closed by #6287

**Closed by efiring** 2016-05-02 20:01 UTC
Labels: default changes

**Comment by fdeheeger** [comment] 2016-09-24 03:37
While testing the 2.0.0b4, I faced the same question regarding bar plot. Grid on top of bars did not feel right to me (personal perception).
I just wanted to raise the question as I did not find any issue talking about that point, but I might be wrong. Feel free to close if already discussed.

**Comment by efiring** [comment] 2016-09-24 04:54
It was discussed and is already closed; you have a good point, but the problem is that for some patch-like objects the grid works best on top, and for others below.  Rather than putting in a bunch of special-case logic, we ended up deciding on the present default.  Maybe we will regret it and have to add the special-case logic later, but for now (v2.0) this was the decision.
