### ISSUE TITLE
 invalid command name "..._on_timer" in FuncAnimation for (too) small interval

### ISSUE THREAD

**Issue by voxspox** [matplotlib/matplotlib#8107] opened 2017-02-20 14:49 UTC
To get a high frame rate for my animation I use a low value for 'interval' for 'FuncAnimation'. If interval is too low p.ex. 10, I get the following Exception, when (and only when) I close the window:

invalid command name "140613997300232_on_timer"
    while executing
"140613997300232_on_timer"
    ("after" script)
Traceback (most recent call last):
  File "./monitor.py", line 93, in <module>
    plt.show()
  File "env/lib/python3.5/site-packages/matplotlib/pyplot.py", line 253, in show
    return _show(*args, **kw)
  File "env/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 163, in __call__
    manager.show()
  File "env/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 610, in show
    self.canvas.manager.window.attributes('-topmost', 1)
AttributeError: 'NoneType' object has no attribute 'attributes'

matplotlib==2.0.0

**Comment by voxspox** [comment] 2017-02-20 14:49
https://bugs.launchpad.net/ubuntu/+source/matplotlib/+bug/1666230

**Comment by dstansby** [comment] 2017-02-20 15:04
Thanks for the bug report! Could you possibly post a minimal example of code (including all the module imports) that triggers this error?

**Comment by tacaswell** [comment] 2017-02-20 15:23
Looks like a race condition tearing down the window (because you closed it) and the timer being fired (only shows up at low interval because you have at catch a timer 'in flight' when you click the 'close' button).

**Comment by anntzer** [comment] 2017-02-20 16:03
I can reproduce with `examples/animation/simple_anim.py` with an interval set to 1 and the tkagg backend.

**Comment by QuLogic** [comment] 2017-02-21 09:20
@anntzer You need `cairocffi` for Gtk3Agg + Python 3 to work; you should have got a warning about it.

**Comment by anntzer** [comment] 2017-02-21 18:55
Ah, yes, I didn't see the warning because it got immediately drowned out by the repeating (due to animation) error message regarding `create_for_data`.

If it doesn't work without cairocffi, should it be an ImportError?

**Comment by Robomate** [comment] 2018-02-04 17:20
happens, when I close the matplotlib animation plot.
```
invalid command name "140609567202440_on_timer"
    while executing
"140609567202440_on_timer"
    ("after" script)
```

**Comment by richardsheridan** [comment] 2020-08-12 23:17
The ultimate cause of this bug was the destruction of the tk canvas occurring before the execution of `_on_timer` in the Tcl event queue while simultaneously failing to execute `after_cancel` (can't really explain that). The bug appears to be fixed on master, likely by #17802 or #17789. This issue should be closed if others can reproduce this, however, a new bug has appeared for the smallest values of interval, see #18236.

**Closed** 2020-08-18 20:14 UTC
Labels: Animation, GUI/tk

**Comment by ffernandoalves** [comment] 2020-10-31 21:48
I get the same error when the blit parameter is True, for a large volume of data

**Comment by aravindpoolla07** [comment] 2022-03-10 11:37
Hi, I got the same error. I am trying to plot real-time values in Tkinter which I obtained from Arduino sensor data. The plots work and everything is working but  I get this error shown below.  My sensor values contain floating-point values. 

Can someone tell me should I fix this issue or just leave it as everything is working fine?

Forex like this 
[2.05
1.74
1.65
1.6
1.59
1.59
1.6
1.59
1.58
1.58
1.6]

**My error is**

invalid command name "1873019790016_on_timer"
    while executing
"1873019790016_on_timer"
    ("after" script)
invalid command name "1873007000832_on_timer"
    while executing
"1873007000832_on_timer"
    ("after" script) 

**My code looks like this**

`style.use('ggplot')
fig = plt.figure(figsize=(15, 6), dpi=60)
ax1 = fig.add_subplot(221)
ax1.set_title("Analog Voltage ")
ax1.set_xlabel("Time")
ax1.set_ylabel(" Analog Voltage")
ax1.set_ylim(-0.5, 5)
line, = ax1.plot(analog_voltage, 'b')


ax2 = fig.add_subplot(222)
ax2.set_title("Voltage")
ax2.set_xlabel("Time")
ax2.set_ylabel(" Voltage")
ax2.set_ylim(-0.5, 5)
line1, = ax2.plot(Voltage, '-r')


ax3 = fig.add_subplot(223)
ax3.set_title("Current")
ax3.set_xlabel("Time")
ax3.set_ylabel(" Current mA")
ax3.set_ylim(-0.5, 3)
line2, = ax3.plot(Current, 'y')


ax4 = fig.add_subplot(224)
ax4.set_title("Temperature")
ax4.set_xlabel("Time")
ax4.set_ylabel(" Temperature °C")
ax4.set_ylim(-10, 80)
line3, = ax4.plot(Temperature, 'r') 

# Function to append values into the plot     
    def animate(i):
    
      line.set_xdata(range(0, len(analog_voltage)))
      line.set_ydata(analog_voltage)
      
      line1.set_xdata(range0, len(Voltage)))
      line1.set_ydata(Voltage)
      
      line2.set_xdata(range(0, len(Current)))
      line2.set_ydata(Current)
      
      line3.set_xdata(range(0, len(Temperature)))
      line3.set_ydata(Temperature)
  
      ax1.set_xlim(0,i+1)
      ax2.set_xlim(0,i+1)
      ax3.set_xlim(0,i+1)
      ax4.set_xlim(0,i+1)

    #plotting the live data
    plotcanvas = FigureCanvasTkAgg(fig, root)
    plotcanvas.get_tk_widget().pack()
    ani = animation.FuncAnimation(fig, animate,interval=1000 ,blit=False)`

**Comment by tacaswell** [comment] 2022-03-10 14:21
@aravindpoolla07 Can you please open a new issue?
