### ISSUE TITLE
pyplot.subplots() is slow

### ISSUE THREAD

**Issue by the-yeti** [matplotlib/matplotlib#7163] opened 2016-09-22 21:11 UTC
matplotlib 1.5.3, Python 2.7.3, Linux (Ubuntu 14.04 LTS), installed using pip

`pyplot.subplots()` is significantly slower than `pyplot.subplot()`. This becomes significant when plotting a large number of subplots. For example `subplots(40)` takes 2.3s whereas 40 calls to `subplot()` with differing parameters just take 25ms.

Minimal example (using ipython):

    import matplotlib.pyplot as plt
    %timeit plt.subplots(40)

- The effect does not depend on the grid: 40x1 is the same as 5x8.
- The time needed increases linearly with the number of subplots.
- The effect does not seem to depend on the parameters `sharex`, `sharey` and `squeeze` (though I have not tested all possible parameters)
- profiling the call reveals that there are a lot of calls to `reset_ticks`, which use up 75% of the time. See the runsnake screenshot below:

![matplotlib_subplots40](https://cloud.githubusercontent.com/assets/2836374/18766172/2920a28c-8119-11e6-95a8-99a4c0d15c76.png)

It seems there is a lot of unneccesary(?) clearing happening. Would it be possible to speed this up?

**Comment by Kojoley** [comment] 2016-09-22 21:13
I think is is a duplicate of #6664

**Comment by QuLogic** [comment] 2016-09-22 21:19
Probably related, but your issue doesn't seem to be specific to `plt.subplots`?

**Comment by the-yeti** [comment] 2016-09-22 21:20
Yes, it's most likely the same cause. I didn't find it because `subplots()` is not mentioned.

Without knowing anything on the matplotlib internals, I'm still wondering why `subplot()` can be fast. After all, it has to create an Axes instance as well. Maybe that could be a hint for an solution?

If this issue doesn't add additional information, it may be closed as duplicate.

**Comment by Kojoley** [comment] 2016-09-22 21:23
> Probably related, but your issue doesn't seem to be specific to `plt.subplots`?

Yes, but 

> 40 calls to `subplot()` with differing parameters just take 25ms.

creates exactly one Axes instance, while

> `subplots(40)` takes 2.3s

creates 40 Axes.

**Comment by QuLogic** [comment] 2016-09-22 21:29
> > 40 calls to subplot() with differing parameters just take 25ms.
> 
> creates exactly one Axes instance, while

No, with suitably different parameters, you get 40 `Axes` just the same. There is only one `Figure`.

**Comment by Kojoley** [comment] 2016-09-22 21:29
```python
import matplotlib.pylab as plt
ax1 = plt.subplot()
ax2 = plt.subplot()
print('same' if ax1 is ax2 else 'different')
```

**Comment by QuLogic** [comment] 2016-09-22 21:31
Of course that's the same; you're asking for the same subplot.
```python
import matplotlib.pylab as plt
ax1 = plt.subplot(40, 1, 1)
ax2 = plt.subplot(40, 1, 2)
print('same' if ax1 is ax2 else 'different')
```

**Comment by Kojoley** [comment] 2016-09-22 21:38
Yeah, that is strange:
```
>python -m timeit -s "import matplotlib.pylab as plt" "for i in range(9*9): plt.subplot(9, 9, i+1)"
10 loops, best of 3: 72.8 msec per loop

>python -m timeit -s "import matplotlib.pylab as plt" "plt.subplots(9*9)"
c:\working\repositories\matplotlib\lib\matplotlib\pyplot.py:522: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)
10 loops, best of 3: 2.12 sec per loop
```

**Comment by QuLogic** [comment] 2016-09-22 21:48
Wait, I think I know what it is. I think `timeit` and some subtle difference between `subplots` and `subplot` are conspiring against us a bit, and it's related to the return of the same subplot as noted above.

What is missing is that the figure is _never closed_. `plt.subplots` always returns a new figure, but `plt.subplot` accesses the current figure and looks up the subplot with the same parameters. Thus all runs except the first appear really fast to `timeit`. If you ensure the figure is closed everything comes out similar:

```python
In [3]: import matplotlib.pylab as plt

In [4]: def test():
    for i in range(40):
        plt.subplot(40, 1, i + 1)
   ...:         

In [5]: %timeit plt.subplots(40)
1 loops, best of 3: 1.04 s per loop

In [6]: %%timeit plt.close('all')
   ...: plt.subplots(40)
   ...: 
1 loops, best of 3: 1.03 s per loop

In [7]: plt.close('all')

In [8]: %timeit test()
The slowest run took 91.79 times longer than the fastest. This could mean that an intermediate result is being cached 
1 loops, best of 3: 11.2 ms per loop

In [9]: %%timeit plt.close('all')
   ...: test()
   ...: 
1 loops, best of 3: 1.01 s per loop
```
That warning there is the key 91.79 * 11.2ms ==1.028048s for the first run.

So I'm going to close as a duplicate then.

**Closed by QuLogic** 2016-09-22 21:48 UTC
