### ISSUE TITLE
matplotlib.pyplot picture is corrupted when the picture is too wide

### ISSUE THREAD

**Issue by optyang** [matplotlib/matplotlib#19745] opened 2021-03-19 18:03 UTC
### Bug report

matplotlib.pyplot picture is corrupted when the picture is too wide

**Code for reproduction**

A minimum working example is here:
```python
import matplotlib.pyplot as plt
import numpy as np

num_points = 1000
op_norms = range(1, num_points + 1)
op_names = ["name {}".format(p) for p in op_norms]
    
for figwidth in [300, 400]:
    f = plt.figure(num=None, figsize=(figwidth, 6), facecolor='w', edgecolor='k')
    for i, op_norm in enumerate(op_norms):
        plt.semilogy(i, op_norm, "o")

    plt.xticks(np.arange(num_points), op_names, rotation=90)
    plt.tight_layout()
    plt.grid(True)
    plt.savefig("wideplot_width_{}.png".format(figwidth), bbox_inches='tight')
    plt.close()```
```
**Expected outcome**: 
When `figwidth=300`, everything is fine; see [here](https://i.stack.imgur.com/DTeTE.png). However, when it is increased to `figwidth=400`, the plot is corrupted (boarder is not complete, x axis label not complete, dirty ink etc.); see [here](https://i.stack.imgur.com/1cMCl.png). 

  * Operating system: Debian GNU/Linux 10 (buster)
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version: 3.7.9

matplotlib is installed from conda.

Any hint would be very much appreciated! Thanks!

**Comment by jklymak** [comment] 2021-03-19 18:19
Yes, Agg has a 32,000-odd pixel limit.  You probably don't really want such a large figure.  This is basically a duplicate of #19209 (which is probably a duplicate of others)...

**Closed by jklymak** 2021-03-19 18:19 UTC
