### ISSUE TITLE
[Bug]: Color scale in colormapnorms.html has garbled text

### ISSUE THREAD

**Issue by ericdill** [matplotlib/matplotlib#23585] opened 2022-08-08 20:01 UTC
### Bug summary

visiting https://matplotlib.org/stable/tutorials/colors/colormapnorms.html#symmetric-logarithmic shows this colorbar with some garbled text

![image](https://user-images.githubusercontent.com/6223243/183503736-84f2b1f3-4bd9-410b-bf48-2526e29ffef1.png)

Let me know if you need more info

### Code for reproduction

```python
n/a
```

### Actual outcome

n/a

### Expected outcome

n/a

### Operating system

popos 22.04, chrome incognito Version 103.0.5060.134 (Official Build) (64-bit)

### Matplotlib Version

n/a

**Comment by timhoffm** [comment] 2022-08-08 20:25
Also present in dev version: https://matplotlib.org/devdocs/tutorials/colors/colormapnorms.html#symmetric-logarithmic

And at least since 2.1.0 https://matplotlib.org/2.1.0/tutorials/colors/colormapnorms.html#symmetric-logarithmic (before that the page did nit exist in that form).

**Comment by jklymak** [comment] 2022-08-08 22:24
Yes, the symlog ticker is basically broken.  Someone who uses SymLog should fix it!

**Comment by QuLogic** [comment] 2022-08-08 22:36
Duplicate of #18757

**Closed by QuLogic** 2022-08-08 22:36 UTC
Labels: topic: ticks axis labels, topic: transforms and scales
