### ISSUE TITLE
[MNT]: Add a default `markevery` for lines in rcParams

### ISSUE THREAD

**Issue by LorenzoPeri17** [matplotlib/matplotlib#29063] opened 2024-11-03 00:28 UTC
### Summary

`markevery` is the only property regarding lines for which it is not possible to set a default value in `rcParams`.
This property would be convenient if a user wants to set a default value, rather then needing to specify for each plot.

### Proposed fix

Add `lines.markevery : None` to the defaut `matplotlibrc`

**Comment by jklymak** [comment] 2024-11-03 02:20
This is a duplicate of #29025. Feel free to discuss there.

**Closed** 2024-11-03 02:20 UTC
Labels: Maintenance
