### ISSUE TITLE
[Bug]: Unexpected Behavior in Matplotlib's Colormap Chaining

### ISSUE THREAD

**Issue by SofoklisMouratidis** [matplotlib/matplotlib#27553] opened 2023-12-21 10:53 UTC
### Bug summary

I encountered unexpected behavior when attempting to chain in a single line the set_bad() color property with get_cmap(). The new bad color is set, but the colormap is not the requested (eg. 'rainbow'), but the default colormap ('viridis'). This issue happens with all cmaps I tested, and maybe is an issue involving the chaining mechanism or the behavior of get_cmap() when used in a chained context. 

### Code for reproduction

```python
import matplotlib.pyplot as plt

## cmap is 'viridis', instead of 'rainbow', with bad color '#1f1f1f'
cmap = plt.get_cmap('rainbow').set_bad(color='#1f1f1f')

## cmap is 'rainbow' with bad color '#1f1f1f'
cmap = plt.get_cmap('rainbow')
cmap.set_bad(color='#1f1f1f')
```

### Actual outcome

When chaining, 'rainbow' colomap is not retained and switches to 'viridis'

### Expected outcome

When chaining, 'rainbow' colomap should be retained

### Operating system

Linux (GoogleColab)

### Matplotlib Version

3.7.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

### Jupyter version

6.5.5

### Installation

None

**Comment by rcomer** [comment] 2023-12-21 11:23
Hi @SofoklisMouratidis, `get_cmap` works in place on the colour map, so if you do it in one line like

```python
cmap = plt.get_cmap('rainbow').set_bad(color='#1f1f1f')
```

then you are setting `cmap` to `None`.  Passing `cmap=None` to a plotting function means "use the default colour map", which is indeed Viridis.

So I think your second two line version is the right way to achieve what you want.

**Comment by timhoffm** [comment] 2023-12-21 11:38
Or you can do
```
cmap = plt.get_cmap('rainbow').with_extremes(bad='#1f1f1f')
```

**Comment by tacaswell** [comment] 2023-12-21 19:50
Unfortunately the chaining looks like it works (no errors!) but the return (`None`) means "do the default thing" when passed in place of a color map.  It is normal for methods that mutate an object in place to not return them selves (see `list.sort).  It is very unlikely that we are going to start systematically adding `return self` to object methods.

I am going to close this because this is the documented and expected behavior and because there is already a helper on colormaps to return a copy with the extremes (over/under/bad) set for exactly this use case.

**Closed by tacaswell** 2023-12-21 19:50 UTC
Labels: Community support
