### ISSUE TITLE
Make sure that Travis tests external links in docs, INSTALL, README etc.

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#4205] opened 2015-03-09 16:25 UTC
Avoid issues like the one fixed by #4204

**Comment by SidharthBansal** [comment] 2020-04-05 18:46
Can we close this @tacaswell ?

**Comment by SidharthBansal** [comment] 2020-04-05 18:52
Seems like duplicate issue of https://github.com/matplotlib/matplotlib/issues/5380

**Comment by timhoffm** [comment] 2020-04-12 23:35
Thanks @SidharthBansal. Closing as duplicate of #5380.

**Closed by timhoffm** 2020-04-12 23:35 UTC
Labels: Testing
