### ISSUE TITLE
Matplotlib 2.0.0rc2 banner still present in at least one docs page

### ISSUE THREAD

**Issue by jni** [matplotlib/matplotlib#11439] opened 2018-06-15 03:22 UTC
When I go to https://matplotlib.org/users/style_sheets.html I still see a banner announcing that Matplotlib 2.0.0rc2 is available. (See screenshot.)

![mpl-site](https://user-images.githubusercontent.com/492549/41448637-20c7e470-709f-11e8-85c4-265c5d1e5dc9.png)

**Comment by QuLogic** [comment] 2018-06-15 03:38
This is due to outdated pages not getting deleted; duplicate of #9556.

**Closed by QuLogic** 2018-06-15 03:38 UTC
