### ISSUE TITLE
[Bug]: colorbar not displaying properly with TwoSlopeNorm

### ISSUE THREAD

**Issue by chapochn** [matplotlib/matplotlib#23589] opened 2022-08-09 15:38 UTC
### Bug summary

The color bar is not properly displayed after version 3.5.0

### Code for reproduction

```python
Compare:
https://matplotlib.org/stable/tutorials/colors/colormapnorms.html#twoslopenorm-different-mapping-on-either-side-of-a-center
OR
https://matplotlib.org/devdocs/tutorials/colors/colormapnorms.html#twoslopenorm-different-mapping-on-either-side-of-a-center
with the older version:
https://matplotlib.org/3.4.3/tutorials/colors/colormapnorms.html#twoslopenorm-different-mapping-on-either-side-of-a-center
```

### Actual outcome

[new.pdf](https://github.com/matplotlib/matplotlib/files/9292469/new.pdf)

the color bar between -500 to 0 is as long as from 0 to 4000, although should be as long as 0 to 500

### Expected outcome

![old](https://user-images.githubusercontent.com/23103092/183694722-37a206f2-b783-4d27-a9ac-fc9d67a6f2ca.png)

### Matplotlib Version

stable/dev

**Comment by jklymak** [comment] 2022-08-09 15:50
The new behaviour is expected.  Duplicate of https://github.com/matplotlib/matplotlib/issues/23040

**Closed by jklymak** 2022-08-09 15:50 UTC

**Comment by chapochn** [comment] 2022-08-09 15:54
ok... then maybe would be good to update the tutorial, to show a code that is usable for that case?

**Comment by jklymak** [comment] 2022-08-09 15:56
@chapochn perhaps lets discuss at #23040 so the context of the original issue is preserved?

**Comment by chapochn** [comment] 2022-08-09 15:57
ok, thanks!

**Comment by jklymak** [comment] 2022-08-09 16:10
My apologies, the duplicate is with https://github.com/matplotlib/matplotlib/issues/22197
