### ISSUE TITLE
different behaviour of zoom while using ginput with MouseEvent vs KeyEvent

### ISSUE THREAD

**Issue by toniatop** [matplotlib/matplotlib#4353] opened 2015-04-19 05:10 UTC
When using ginput, such as in this example:

``` python
import matplotlib.pyplot as plt
plt.plot([1,2,3],[3,4,5])
plt.ginput(n=10)
```

If you click some points around the figure and later you try to zoom, it works (even if it keeps selecting the first point while zooming, but it doesn't really matter). If, at any moment, you press a key in the keyboard, you lose the capability of zooming while using ginput.

Some information about my configuration:
Windows 8.1
python 2.7.8
matplotlib 1.4.3
backend `Qt4Agg`

**Comment by tacaswell** [comment] 2015-04-19 12:37
I can not reproduce this on linux + py3k + master.  

Are you by any chance hitting 'enter' or 'esc' which are mapped 'stop'?

**Comment by toniatop** [comment] 2015-04-19 12:46
Yes, I am sure, i am not hitting the stopping keys. 

Later on I ll have access to a linux machine, and I'll test it over there.

**Comment by toniatop** [comment] 2015-04-20 04:47
I can confirm the issue on ubuntu 14.04, python 2.7.6, matplotlib 1.4.3

**Comment by tacaswell** [comment] 2015-04-28 01:56
I can not reproduce this with a clean conda installation (either python 2.7.6 or 2.7.9) on ubuntu or with the system python + 1.4.2-3 from ubuntu 15.04 repos.

**Comment by petehuang** [comment] 2017-01-10 01:53
I was unable to reproduce in Windows 8.1, python 2.7.12, MPL 1.5.3

**Comment by tacaswell** [comment] 2017-01-10 03:29
Closing as due to not being reproduced.

@toniatop If this is still an issue can you try to reproduce this with 1.5.3 or 2.0.0rc2 and ping to have this reopened?

**Closed by tacaswell** 2017-01-10 03:29 UTC
Labels: needs confirmation, widgets/UI
