### ISSUE TITLE
value error : unknown locale: UTF-8

### ISSUE THREAD

**Issue by rylanchiu** [matplotlib/matplotlib#5481] opened 2015-11-14 11:49 UTC
I want to import matplotlib to django project. I add "import matplotlib.pyplot as plt" in the front of the code and I get this error: 
Traceback:
File "/Users/yobichi/wi/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  119.                 resolver_match = resolver.resolve(request.path_info)
File "/Users/yobichi/wi/lib/python3.5/site-packages/django/core/urlresolvers.py" in resolve
  365.             for pattern in self.url_patterns:
File "/Users/yobichi/wi/lib/python3.5/site-packages/django/core/urlresolvers.py" in url_patterns
  401.         patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "/Users/yobichi/wi/lib/python3.5/site-packages/django/core/urlresolvers.py" in urlconf_module
  395.             self._urlconf_module = import_module(self.urlconf_name)
File "/Users/yobichi/wi/lib/python3.5/importlib/__init__.py" in import_module
  126.     return _bootstrap._gcd_import(name[level:], package, level)
File "/Users/yobichi/wi/raptle/raptle/urls.py" in <module>
  21.     url(r'^rap_song/', include('rap_song.urls', namespace = "rap_song")),
File "/Users/yobichi/wi/lib/python3.5/site-packages/django/conf/urls/__init__.py" in include
  33.         urlconf_module = import_module(urlconf_module)
File "/Users/yobichi/wi/lib/python3.5/importlib/__init__.py" in import_module
  126.     return _bootstrap._gcd_import(name[level:], package, level)
File "/Users/yobichi/wi/raptle/rap_song/urls.py" in <module>
  2. from . import views
File "/Users/yobichi/wi/raptle/rap_song/views.py" in <module>
  10. from .topicWords import update_topic
File "/Users/yobichi/wi/raptle/rap_song/topicWords.py" in <module>
  13. import matplotlib.pyplot as plt
File "/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py" in <module>
  1131. rcParams = rc_params()
File "/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py" in rc_params
  975.     return rc_params_from_file(fname, fail_on_error)
File "/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py" in rc_params_from_file
  1100.     config_from_file = _rc_params_in_file(fname, fail_on_error)
File "/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py" in _rc_params_in_file
  1018.     with _open_file_or_url(fname) as fd:
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py" in __enter__
  59.             return next(self.gen)
File "/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py" in _open_file_or_url
  1000.         encoding = locale.getdefaultlocale()[1]
File "/Users/yobichi/wi/lib/python3.5/locale.py" in getdefaultlocale
  559.     return _parse_localename(localename)
File "/Users/yobichi/wi/lib/python3.5/locale.py" in _parse_localename
  487.     raise ValueError('unknown locale: %s' % localename)

Exception Type: ValueError at /rap_song/lyric/user/fama/
Exception Value: unknown locale: UTF-8

I have changed the setting of terminal preferences but when I do this: 
import locale
locale.getdefaultlocale()

I get : (None, None).
Could you please help me for this issue? Thanks in advance!

**Comment by tacaswell** [comment] 2015-11-14 23:15
This is a duplicate of https://github.com/matplotlib/matplotlib/issues/5420 which is due to OSX have non-standard locales by default.

**Closed** 2015-11-15 08:12 UTC
Labels: OS/Apple, upstream fix required
