### ISSUE TITLE
mpl crashes with Segfault on Py3.10 upon importing pyplot and backend, while no crashes on Py3.9 and earlier

### ISSUE THREAD

**Issue by ullix** [matplotlib/matplotlib#22450] opened 2022-02-11 12:20 UTC
My program runs on Py3.9 all the way back to 3.5, but now on 3.10 fails with segfaults on importing pyplot and mpl.backend stuff. Problem is easy to show with Pys running in venv:

```
(vgl310) :~/$ python
Python 3.10.0a6 (default, Mar  2 2021, 02:01:08) [GCC 5.4.0 20160609] on linux
>>> import matplotlib.pyplot    as plt   
Speicherzugriffsfehler                                (literally: Memory Access Error)
```
Same when trying to import backend stuff:
```
(vgl310) :~/$ python
Python 3.10.0a6 (default, Mar  2 2021, 02:01:08) [GCC 5.4.0 20160609] on linux
>>> import matplotlib.backends.backend_qt5agg   
Speicherzugriffsfehler
```
Other imports work ok, no crashes:
```
(vgl310) :~/$ python
Python 3.10.0a6 (default, Mar  2 2021, 02:01:08) [GCC 5.4.0 20160609] on linux
import matplotlib.dates     as mpld
import matplotlib.animation as mplanim
import matplotlib.patches   as mpat
>>>
```

On Py3.9 and earlier all these commands work ok, no crashes:
```
(vgl39) :~/$ python
Python 3.9.4 (default, Apr  9 2021, 01:15:05)[GCC 5.4.0 20160609] on linux
>>> import matplotlib.pyplot    as plt
>>> import matplotlib.backends.backend_qt5agg
>>> import matplotlib.dates     as mpld
>>> import matplotlib.animation as mplanim
>>> import matplotlib.patches   as mpat
>>> 
```

I tested from the latest matplotlib 3.5.1 all the way back to 3.3.0 - the results always the same as above, i.e. ok on Py3.9, segfault crash on Py3.10.

**Comment by greglucas** [comment] 2022-02-11 13:48
It looks like you are on an alpha Python 3.10 release, can you try with a non-alpha/beta release? I can't reproduce this with 3.10.2.

**Comment by tacaswell** [comment] 2022-02-11 15:47
Can you please run with faulthandler https://docs.python.org/3/library/faulthandler.html

```
$ python3 -q -X faulthandler
>>> 
```

so we can see where this is crashing.

From the information here, I very strongly suspect that you have a broken pyqt5 / pyside2 installation and the segfault is coming from the bindings to Qt.

**Comment by ullix** [comment] 2022-02-11 16:26
Here is the faulthandler:
```
(vgl310) $ python3 -q -X faulthandler
>>> import matplotlib.pyplot    as plt
Fatal Python error: Segmentation fault

Current thread 0x00007f7d305b5700 (most recent call first):
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1127 in create_module
  File "<frozen importlib._bootstrap>", line 581 in module_from_spec
  File "<frozen importlib._bootstrap>", line 684 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1005 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1026 in _find_and_load
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1077 in _handle_fromlist
  File "/home/ullix/geigerlog/vgl310/lib/python3.10/site-packages/matplotlib/backends/qt_compat.py", line 73 in _setup_pyqt5
  File "/home/ullix/geigerlog/vgl310/lib/python3.10/site-packages/matplotlib/backends/qt_compat.py", line 168 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 834 in exec_module
  File "<frozen importlib._bootstrap>", line 698 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1005 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1026 in _find_and_load
  File "/home/ullix/geigerlog/vgl310/lib/python3.10/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 11 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 834 in exec_module
  File "<frozen importlib._bootstrap>", line 698 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1005 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1026 in _find_and_load
  File "/home/ullix/geigerlog/vgl310/lib/python3.10/site-packages/matplotlib/backends/backend_qt5.py", line 16 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 834 in exec_module
  File "<frozen importlib._bootstrap>", line 698 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1005 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1026 in _find_and_load
  File "/home/ullix/geigerlog/vgl310/lib/python3.10/site-packages/matplotlib/backends/backend_qt5agg.py", line 11 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 834 in exec_module
  File "<frozen importlib._bootstrap>", line 698 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1005 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1026 in _find_and_load
  File "<frozen importlib._bootstrap>", line 1049 in _gcd_import
  File "/usr/lib/python3.10/importlib/__init__.py", line 126 in import_module
  File "/home/ullix/geigerlog/vgl310/lib/python3.10/site-packages/matplotlib/pyplot.py", line 260 in backend_mod
  File "/home/ullix/geigerlog/vgl310/lib/python3.10/site-packages/matplotlib/pyplot.py", line 259 in switch_backend
  File "/home/ullix/geigerlog/vgl310/lib/python3.10/site-packages/matplotlib/pyplot.py", line 239 in switch_backend
  File "/home/ullix/geigerlog/vgl310/lib/python3.10/site-packages/matplotlib/__init__.py", line 703 in __getitem__
  File "/home/ullix/geigerlog/vgl310/lib/python3.10/site-packages/matplotlib/pyplot.py", line 2319 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 834 in exec_module
  File "<frozen importlib._bootstrap>", line 698 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1005 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1026 in _find_and_load
  File "<stdin>", line 1 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, kiwisolver, matplotlib._path, PIL._imaging, matplotlib._image (total: 17)
Speicherzugriffsfehler
```

**Comment by tacaswell** [comment] 2022-02-11 19:10
Can you please verify if you can run

```
> from PyQt5 import QtCore, QtGui, QtWidgets
> import sip
```

or 

```
> from PySide2 import QtCore, QtGui, QtWidgets, __version__
> import shiboken2
```

depending on which one you have installed.

**Comment by ullix** [comment] 2022-02-11 20:29
```
(vgl310) $ python
Python 3.10.0a6 (default, Mar  2 2021, 02:01:08) [GCC 5.4.0 20160609] on linux
>>> from PyQt5 import QtCore, QtGui, QtWidgets
Speicherzugriffsfehler
```

`import sip` fails for "ModuleNotFoundError: No module named 'sip'"

**Comment by tacaswell** [comment] 2022-02-11 20:36
For...reasons, you have to import PyQt5 before you can import sip.

I am going to close this because given that you can not import PyQt5 there is nothing we can do for you on the Matplotlib side.  I suggest re-installing and if that fails opening an issues with riverbank computing about the pyqt issue.

As someone else noted, you have an alpharelease of Python 3.10 installed.  There were some binary incompatible changes during the development, it is possible you got some libraries compiled against an either newer or older development version of Python.

**Closed by tacaswell** 2022-02-11 20:36 UTC

**Comment by ullix** [comment] 2022-02-12 11:11
Indeed, the problem is with PyQt5; sorry for barking up the wrong tree, but thanks for helping!

FWIW:
```
pyqt5-sip   12.9.0    segfaults always
            12.8.1    ok (the last release before 12.9.0)
```
But when pyqt5-sip 12.8.1 is used, then pyqt5 must be no higher than 5.15.4

With these restrictions, everything is running correctly again on my setup.
