### ISSUE TITLE
[Bug]: CenteredNorm gets stuck in infinite recusion when given all zeros

### ISSUE THREAD

**Issue by npbarnes** [matplotlib/matplotlib#24093] opened 2022-10-04 22:17 UTC
### Bug summary

If you try to make a pcolormesh plot with an array of all zeros, a CenteredNorm, and a colorbar it goes into infinite recursion and raises a RecursionError and then the exception handler also goes into infinite recursion and raises another RecursionError over and over again, forever (or at least as long as my patience). It appears to be infinitely recursive infinite recursion.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import CenteredNorm

a = np.reshape(np.zeros(9), (3,3))
plt.pcolormesh(a, norm=CenteredNorm())
plt.colorbar()
```

### Actual outcome

Traceback (most recent call last):
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 307, in process
    func(*args, **kwargs)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/colorbar.py", line 495, in update_normal
    self._draw_all()
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/colorbar.py", line 521, in _draw_all
    self._long_axis().set(label_position=self.ticklocation,
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 117, in <lambda>
    cls.set = lambda self, **kwargs: Artist.set(self, **kwargs)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 1194, in set
    return self._internal_update(cbook.normalize_kwargs(kwargs, self))
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 1186, in _internal_update
    return self._update_props(
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 1162, in _update_props
    ret.append(func(v))
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/axis.py", line 2494, in set_label_position
    self.stale = True
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 300, in stale
    self.stale_callback(self, val)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 84, in _stale_axes_callback
    self.axes.stale = val
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 300, in stale
    self.stale_callback(self, val)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/figure.py", line 53, in _stale_figure_callback
    self.figure.stale = val
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 300, in stale
    self.stale_callback(self, val)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/pyplot.py", line 806, in _auto_draw_if_interactive
    if (val and matplotlib.is_interactive()
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/__init__.py", line 1201, in is_interactive
    return rcParams['interactive']
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/__init__.py", line 673, in __getitem__
    elif key == "backend" and self is globals().get("rcParams"):
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 307, in process
    func(*args, **kwargs)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/cm.py", line 652, in changed
    self.callbacks.process('changed', self)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 312, in process
    self.exception_handler(exc)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 98, in _exception_printer
    traceback.print_exc()
  File "/import/home/npbarnes/py3/lib/python3.10/traceback.py", line 179, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/import/home/npbarnes/py3/lib/python3.10/traceback.py", line 119, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
  File "/import/home/npbarnes/py3/lib/python3.10/traceback.py", line 502, in __init__
    self.stack = StackSummary.extract(
  File "/import/home/npbarnes/py3/lib/python3.10/traceback.py", line 383, in extract
    f.line
  File "/import/home/npbarnes/py3/lib/python3.10/traceback.py", line 306, in line
    self._line = linecache.getline(self.filename, self.lineno)
  File "/import/home/npbarnes/py3/lib/python3.10/linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
  File "/import/home/npbarnes/py3/lib/python3.10/linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "/import/home/npbarnes/py3/lib/python3.10/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 307, in process
    func(*args, **kwargs)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/colorbar.py", line 495, in update_normal
    self._draw_all()
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/colorbar.py", line 535, in _draw_all
    X, Y = self._mesh()
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/colorbar.py", line 1110, in _mesh
    y, _ = self._proportional_y()
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/colorbar.py", line 1233, in _proportional_y
    y = self.norm(self._boundaries.copy())
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/colors.py", line 1571, in __call__
    self._set_vmin_vmax()
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/colors.py", line 1522, in _set_vmin_vmax
    self.vmin = self._vcenter - self._halfrange
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/colors.py", line 1245, in vmin
    self._changed()
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/colors.py", line 1273, in _changed
    self.callbacks.process('changed')
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 312, in process
    self.exception_handler(exc)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 98, in _exception_printer
    traceback.print_exc()
  File "/import/home/npbarnes/py3/lib/python3.10/traceback.py", line 179, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/import/home/npbarnes/py3/lib/python3.10/traceback.py", line 119, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
  File "/import/home/npbarnes/py3/lib/python3.10/traceback.py", line 552, in __init__
    context = TracebackException(
  File "/import/home/npbarnes/py3/lib/python3.10/traceback.py", line 502, in __init__
    self.stack = StackSummary.extract(
  File "/import/home/npbarnes/py3/lib/python3.10/traceback.py", line 383, in extract
    f.line
  File "/import/home/npbarnes/py3/lib/python3.10/traceback.py", line 306, in line
    self._line = linecache.getline(self.filename, self.lineno)
  File "/import/home/npbarnes/py3/lib/python3.10/linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
  File "/import/home/npbarnes/py3/lib/python3.10/linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "/import/home/npbarnes/py3/lib/python3.10/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 307, in process
    func(*args, **kwargs)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/colorbar.py", line 495, in update_normal
    self._draw_all()
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/colorbar.py", line 521, in _draw_all
    self._long_axis().set(label_position=self.ticklocation,
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 117, in <lambda>
    cls.set = lambda self, **kwargs: Artist.set(self, **kwargs)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 1194, in set
    return self._internal_update(cbook.normalize_kwargs(kwargs, self))
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 1186, in _internal_update
    return self._update_props(
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 1162, in _update_props
    ret.append(func(v))
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/axis.py", line 2494, in set_label_position
    self.stale = True
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 300, in stale
    self.stale_callback(self, val)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 84, in _stale_axes_callback
    self.axes.stale = val
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 300, in stale
    self.stale_callback(self, val)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/figure.py", line 53, in _stale_figure_callback
    self.figure.stale = val
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/artist.py", line 300, in stale
    self.stale_callback(self, val)
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/pyplot.py", line 806, in _auto_draw_if_interactive
    if (val and matplotlib.is_interactive()
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/__init__.py", line 1201, in is_interactive
    return rcParams['interactive']
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/__init__.py", line 673, in __getitem__
    elif key == "backend" and self is globals().get("rcParams"):
RecursionError: maximum recursion depth exceeded in comparison
Traceback (most recent call last):
  File "/import/home/npbarnes/py3/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 307, in process
    func(*args, **kwargs)
.
.
.
.
.

This is just a small snippet. I let it run for a little while and got several hundred thousand lines like this.

### Expected outcome

I would expect it to give me a much shorter and more descriptive error message. Or I suppose it might be acceptable if it produced a centered colorbar with some default range e.g. (-1,1). Personally, I'd prefer a descriptive error message.

### Operating system

CentOS release 6.10

### Matplotlib Version

3.6.0

### Matplotlib Backend

QtAgg

### Python version

Python 3.10.6

### Installation

conda

**Comment by tacaswell** [comment] 2022-10-06 18:57
This is not a 3.6 regression (get same issue on 3.5.3).

I think the fix is that we need to use our non-singular expander when we compute the min/max.

**Comment by jklymak** [comment] 2022-10-07 14:25
Ping @greglucas about the callbacks.

**Comment by greglucas** [comment] 2022-10-08 17:01
This is happening because in the colorbar we try to avoid non-singular norms and end up updating the vmin/vmax
https://github.com/matplotlib/matplotlib/blob/924e2107069c8fe9b8d7683a0b5ec0055c7c3647/lib/matplotlib/colorbar.py#L1099-L1100
But, CenteredNorm is a unique case where vmin/vmax are not defining qualities of the Norm, but rather derived quantities from the vcenter/halfrange. So, we are updating something in Colorbar, then the Norm says "I know best" and decides to change the vmin back again, and they recursively compete with each other.
https://github.com/matplotlib/matplotlib/blob/924e2107069c8fe9b8d7683a0b5ec0055c7c3647/lib/matplotlib/colors.py#L1569-L1571

I'm not sure where the "best" fix for this is. It seems a bit odd to be forcing symmetry in the CenteredNorm call to me, but that breaks a test expecting that behavior. The simple fix is to do the nonsingular expansion ourselves in colorbar for the CenteredNorm case.

```diff
diff --git a/lib/matplotlib/colorbar.py b/lib/matplotlib/colorbar.py
index 996949098f..3ca985704d 100644
--- a/lib/matplotlib/colorbar.py
+++ b/lib/matplotlib/colorbar.py
@@ -1096,6 +1096,8 @@ class Colorbar:
         if not self.norm.scaled():
             self.norm.vmin = 0
             self.norm.vmax = 1
+        if isinstance(self.norm, colors.CenteredNorm) and self.norm.halfrange == 0.:
+            self.norm.halfrange = 0.1
         self.norm.vmin, self.norm.vmax = mtransforms.nonsingular(
             self.norm.vmin, self.norm.vmax, expander=0.1)
         if (not isinstance(self.norm, colors.BoundaryNorm) and
```

**Comment by grgkaran03** [comment] 2022-10-12 18:55
Just implemented the solution given by @greglucas. Can you please review the changes

**Comment by krishnajalan** [comment] 2022-10-18 18:56
Hey! @grgkaran03,  can I work on this implementation ?

**Comment by timhoffm** [comment] 2022-10-18 20:00
"Good first issue" removed there are already PRs submitted.

**Comment by dstansby** [comment] 2023-01-02 17:27
Looks like https://github.com/matplotlib/matplotlib/pull/24132 fixed this

**Closed by dstansby** 2023-01-02 17:27 UTC
Labels: status: confirmed bug, Difficulty: Medium
