### ISSUE TITLE
Add `fmt_r` and `fmt_theta` methods to polar axes

### ISSUE THREAD

**Issue by atpage** [matplotlib/matplotlib#4568] opened 2015-06-29 17:58 UTC
The example here works in Cartesian coordinates:

http://matplotlib.org/examples/pylab_examples/coords_report.html

but if you change 

`subplots()`

to

`subplots(subplot_kw={'polar':True})`

Then the `millions()` function is never even called.

( no response on mailing list: http://matplotlib.1069221.n5.nabble.com/fmt-xdata-fmt-ydata-on-polar-plot-td45838.html )

**Comment by tacaswell** [comment] 2015-06-30 01:21
Because the polar plot does not use those functions.  The message shown in the the gui are generated by calls to `axes.format_coords`, which is the case the the basic Cartesian coordinates the function is: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_base.py#L3056 which looks at `self.fmt_xdata` and `self.fmt_ydata` (via `format_xdata` and `format_ydata`).  In contrast the same function on the `Axes` sub-class for polar axes (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/projections/polar.py#L589) does not.  

If you want to change the message for polar coordinates, directly assign to `ax.format_coords` as shown in http://matplotlib.org/examples/api/image_zcoord.html.

It would be sensible to have a `fmt_r` and `fmt_theta` functions attached to polar axes.

**Comment by atpage** [comment] 2015-06-30 13:22
Thanks for the solution!

As far as naming convention goes (if you do implement the new functions), I don't know if `fmt_r` and `fmt_theta` would make things more or less consistent... there are other cases in polar where we still use functions with 'x' and 'y' in the name... e.g. `set_yticklabels`.

**Comment by WeatherGod** [comment] 2015-06-30 13:36
The problem I have always had with PolarAxes is remembering whether x maps to r or theta. We need to use the x and y notations for subclassing purposes (that way the core matplotlib code can continue to work properly by treating PolarAxes like any other 2D axes object). Aliases to x and y for r and theta would be very useful to end-users in general, like we have now for some things in PolarAxes.

However, I don't know how valuable it would be for this particular case. The way we advertise these formatting functions, we expect users to either monkey patch the particular method they want to modify, or to subclass and override the relevant method. If we had aliases, they won't get updated to the new methods, nor would they get used anyway by the internal methods.

No, I think the correct solution here is to make PolarAxes have a `fmt_xdata` and `fmt_ydata` method like most other classes do. I think the code we see in `format_coords` is intended to be compatibility code to help transition Axes objects that had not yet been updated to provide such methods.

**Comment by antara-gandhi** [comment] 2023-03-29 02:36
hi there, @atpage @tacaswell is this issue still open?

**Comment by melissawm** [comment] 2023-03-29 16:00
Hi @antara-gandhi , unless the issue is closed (as seen on the GitHub interface) you are free to propose a PR or ask for guidance 😄 In this case, it would be nice to check if the issue is still present in recent versions and then propose a solution. Cheers!

**Comment by klorine28** [comment] 2023-07-04 20:08
Is the goal to change the example code to use fmt_r and fmt_theta and be displayed as a polar graph or a way to standardize using fmt_r and fmt_theta to change coordinate plots to polar plots?

My second question is more if there is code I can modify, or do I need to come up with a way to standardize this?

**Comment by klorine28** [comment] 2023-07-04 20:56
I changed and added to the example code is this correct?

`def fmt_r(r):
    
    return f"R={r:.2f}"

def fmt_theta(theta, pos=None):
    
    return f"Theta={np.degrees(theta):.2f}°"

def millions(x, pos=None):
    return '$%1.1fM' % (x*1e-6)

x = np.random.rand(20)
y = 1e7 * np.random.rand(20)

fig, ax = plt.subplots(subplot_kw={'polar': True})

ax.set_yticklabels([fmt_r(label) for label in ax.get_yticks()])

ax.set_xticklabels([fmt_theta(label) for label in ax.get_xticks()])

ax.yaxis.set_major_formatter(plt.FuncFormatter(millions))

ax.plot(x, y, 'o')

plt.show()`

**Closed** 2024-06-23 21:06 UTC
Labels: New feature, API: consistency, Difficulty: Easy, topic: polar
