### ISSUE TITLE
[Doc]: Note: vs Notes vs .. note::

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#22679] opened 2022-03-21 11:50 UTC
### Documentation Link

https://matplotlib.org/stable/api/figure_api.html?highlight=note#module-matplotlib.figure

### Problem

The usage of
```
Notes
------
```
vs
```
Note: 
```
vs 
```
.. note::
```
is a bit inconsistent. As an example, the linked page use all three versions.

Stats in current main (lib directory, not doc):

* `Note: `: 19
* `Notes`: 153
* `.. note::`: 59

There may for sure be a reason to use a particular approach in a gives instance, but it also may be a reason to try to make things more consistent.

### Suggested improvement

At least replace the Note: to one of the other.

Replace `Notes` with `.. note::`?

**Comment by timhoffm** [comment] 2022-03-21 21:21
Although all are called „notes“ the serve different purposes.

- `Notes` is a [numpydoc section](https://numpydoc.readthedocs.io/en/latest/format.html#notes).  It's the only way to get arbitrary text content after the *Parameters* section in the numpydoc format. It's intendend for general notes on the complete function. These should be used for additional information that is not quite important (because it’s rendered at the bottom of the docstring).
  See e.g. https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.imshow.html#matplotlib.axes.Axes.imshow
- `.. note::` is a sphinx admonition for a highlighted note in a local context. It should thus be used for:
  - notes in a local context, e.g. in a parameter description.
    See e.g. https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.boxplot.html#matplotlib.axes.Axes.boxplot
  - to highlight some important remark in the main docstring description, usually close to the top of the docstring.
    See e.g. https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.step.html#matplotlib.axes.Axes.step
- `Note:` These are only a minor remark within the text and not worth the prominent highlighting of an admontion. We could probably reword them or remove them without much semantic change.
  See e.g. https://matplotlib.org/stable/api/legend_api.html?highlight=note#matplotlib.legend.Legend in `title_fontsize`.

See also #21538.

**Comment by QuLogic** [comment] 2022-03-21 22:32
I'm going to close this as a duplicate of #21538.

**Closed by QuLogic** 2022-03-21 22:32 UTC
Labels: Documentation
