### ISSUE TITLE
create new linestyle

### ISSUE THREAD

**Issue by ganneng3682140** [matplotlib/matplotlib#8716] opened 2017-06-04 08:37 UTC
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating System:
  * Matplotlib Version: 
  * Python Version:
  * Jupyter Version (if applicable):
  * Other Libraries:

**Comment by anntzer** [comment] 2017-06-04 21:06
The description of the issue is missing, so I am closing it.  @ganneng3682140, I will reopen the issue if your provide a description.

**Closed by anntzer** 2017-06-04 21:06 UTC
