### ISSUE TITLE
[Bug]: Matplotlib hangs in while loop

### ISSUE THREAD

**Issue by Petrprogs** [matplotlib/matplotlib#28410] opened 2024-06-17 14:32 UTC
### Bug summary

matplotlib windows becomes unresponsive in while loop with `time.sleep()`

### Code for reproduction

```Python
import random
import matplotlib.pyplot as plt
import matplotlib
import time

x,y,y2 = [1],[2],[3]
plt.ion()
graph = plt.plot(x,y,color="r")[0]
graph2 = plt.plot(x,y2,color="b")[0] 
plt.pause(1)
while True:
  y.append(random.randint(2,10))
  y2.append(random.randint(2,10))
  x.append(random.randint(2,10))
  graph.remove()
  graph2.remove()
  graph = plt.plot(x,y,color="r")[0]
  graph2 = plt.plot(x,y2, color="b")[0] 
  plt.legend(loc='best')
  time.sleep(10)
  plt.pause(0.25)
```

### Actual outcome

matplotlib graph windows hangs

### Expected outcome

matplotlib graph window shouldn't hang

### Operating system

Debian 12

### Matplotlib Version

3.9.0

### Matplotlib Backend

QtAgg

### Python version

3.11.9

### Installation

pip

**Comment by ksunden** [comment] 2024-06-17 21:28
This is expected behavior.

For reasons outside of our control, `time.sleep` _will_ cause the entire thread to sleep, halting the ability of GUI event loops from responding to inputs.

A simple fix is to use `plt.pause` alone (with the full time amount you desire), rather than `time.sleep`, which has the same effect, except ensuring that the GUI loops are running.

You may also be interested in learning more about [Animations](https://matplotlib.org/stable/users/explain/animations/animations.html) for more full featured ability to do things like this example, without manually pausing at all.

Some other cross references to our docs for more in depth explanations/examples:

- [Interactive guide, in particular the blocking functions section](https://matplotlib.org/stable/users/explain/figure/interactive_guide.html#blocking-functions)
- [plt.pause API docs](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.pause.html)
- [Example of doing animations via plt.pause](https://matplotlib.org/stable/gallery/animation/animation_demo.html) which includes a notation that `time.sleep` will _not_ work


Since this is understood and documented behavior, I will close this, but thank you for your report.

**Closed by ksunden** 2024-06-17 21:28 UTC
Labels: Community support
