### ISSUE TITLE
Inconsistency between documentation and actual effect of the bar plot function

### ISSUE THREAD

**Issue by jdhao** [matplotlib/matplotlib#8327] opened 2017-03-18 06:24 UTC
#### Bug summary
There is an inconsistency between the [matplotlib's documentation](http://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.bar.html#matplotlib.axes.Axes.bar) and actual outcome of the bar plot function. The documentation says that `left`  argument in the bar plot function indicate
>the x coordinates of the left sides of the bars

In fact, the `left` parameter indicate the center of the bar.

#### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np
N = 3
width = 1.0
stat = [2.4, 3.2, 1.6]
ind = np.arange(1, 6, 2, dtype=np.float32)

fig, ax = plt.subplots()
ax.bar(ind, stat, width )
ax.set_xticks(ind+width/2.0)
plt.show()
```

#### Actual outcome and expected outcome
The x axis ticks should be in the center of bar if the documentation is right. In fact, the ticks are in the right side of each bar. See figure below
![image](https://cloud.githubusercontent.com/assets/16662357/24069524/f7d904e2-0be4-11e7-816e-c94c8a2ae8bd.png)

#### Matplotlib version

- Matplotlib version: 2.0.0
- Python version: 2.7.13 and 3.5.2
- Platform: Linux (CentOS 7)  and Windows 
- How did you install Matplotlib and Python: Anaconda

**Comment by QuLogic** [comment] 2017-03-18 07:32
This is a duplicate of #7954.

**Closed by QuLogic** 2017-03-18 07:32 UTC
