### ISSUE TITLE
zoom rectangle can't work in 3d 

### ISSUE THREAD

**Issue by yanbin-ha** [matplotlib/matplotlib#16829] opened 2020-03-19 06:48 UTC
zoom rectangle can't work in 3d

**Comment by timhoffm** [comment] 2020-03-19 08:39
Is this a duplicate of #110? If not, please describe what the problem is in more detail.

**Comment by yanbin-ha** [comment] 2020-03-19 08:49
> Is this a duplicate of #110? If not, please describe what the problem is in more detail.

I want to see the details at an intersection point. 
first I click the zoom rectangle button, now , in zoom rectangle state
but when I press left button, drag it , view never zoomed,  the view  was moving follow the mouse...
when I press right button, drag it, plot line zoomed, but aixs is stay the same...

My english is not very good, hope you can understand what i am saying  ^_^

**Comment by yanbin-ha** [comment] 2020-03-19 08:59
> Is this a duplicate of #110? If not, please describe what the problem is in more detail.
i think maybe can use  Mouse wheel for zoom,       ctrl + left mouse button  or alone right mouse button do the rotating,     alone left mouse button handle the moving of view port. ^_^

**Comment by timhoffm** [comment] 2020-03-19 09:15
Thanks, I understand your issue now. This is indeed #110. To sum up the current state:

- Panning is not implemented in 3D plots. The center is fixed.
- Zooming is possible with the mouse wheel.
- Neither of both the zoom and pan tools accessible via the toolbar work in 3D.

I'm going to close this. As a duplicate of #110.

**Closed by timhoffm** 2020-03-19 09:15 UTC
Labels: Duplicate, mplot3d
