### ISSUE TITLE
plot makes strip pattern

### ISSUE THREAD

**Issue by Auto-Ken** [matplotlib/matplotlib#16815] opened 2020-03-18 05:12 UTC
Plot function in matplotlib 3.1.3 generate following strips. 
```
ones = np.ones((200,100))
cumsum = np.cumsum(ones, axis=1)
plt.plot(cumsum, linestyle='', marker='o', markersize=0.6, color="k");
```
![200](https://user-images.githubusercontent.com/38831582/76927446-4d01f580-6922-11ea-9619-077d7ad6a97e.jpg)

**Comment by timhoffm** [comment] 2020-03-18 07:34
`plot()` aligns markers to pixel positions for faster and more clear rendering. Therefore markers may be shifted by fractions of a pixel. If the marker distance is not a multiple of the pixel size, you'll get these artifacts.

Duplicate of #13046 and #7233.

**Comment by timhoffm** [comment] 2020-03-18 07:46
A possible workaround is to use `scatter()` and introduce a tiny size variation (without size or color variation `scatter()` will use the same code path as `plot()`. This comes at the cost of inhomogeneously shaped markers and slower rendering performance.

~~~
X, Y = np.meshgrid(np.linspace(0, 1, 200), np.linspace(0, 1, 100))
S = 0.0001 * X + 1
plt.scatter(X, Y, s=S*0.6, marker='o',  color="k"); 
~~~
![grafik](https://user-images.githubusercontent.com/2836374/76937198-a7845d00-68f4-11ea-8df2-fe8424cd82b5.png)

**Closed** 2020-03-18 07:50 UTC
Labels: Duplicate
