### ISSUE TITLE
Pull in JSAnimation

### ISSUE THREAD

**Issue by dopplershift** [matplotlib/matplotlib#4703] opened 2015-07-15 17:14 UTC
Pulling in https://github.com/jakevdp/JSAnimation (which hasn't changed in over a year) would greatly enhance the experience of using animations in the notebook with stock matplotlib. Also, like trendvis, oceancm, and viscm, this would move an very useful matplotlib-based tool into our fold.

The core implementation of JSAnimation is just two parts:
- A new writer, HTMLWriter, which also includes some icons for the HTML controls
- IPython notebook display hook code

The `HTMLWriter` clearly makes sense in matplotlib (alongside `FFMpegWriter`, etc.). I'm not sure what to do with the IPython display code. Adding it as a `_repr_html` might not be too bad.

Thoughts?

**Comment by dopplershift** [comment] 2015-07-15 17:15
Longer term, it would be nice to refactor animation code so that the `HTMLWriter` could write directly to a string (via `StringIO`) rather than the verbose code required to  use a tempfile.

**Comment by jamespjh** [comment] 2015-07-20 16:02
As one user, this would make me happy...

**Comment by gforsyth** [comment] 2015-12-02 17:33
JSAnimation no longer works with matplotlib 1.5 -- jakevdp suggested that the new display hooks in 8cc21dbc3 may be the culprit.  It's a handy tool for notebooks, especially as the animations remain functional when rendered by nbviewer.

**Comment by dopplershift** [comment] 2015-12-02 17:35
I've got a PR that's waiting to pull JSAnimation into matplotlib #4821.

**Comment by gforsyth** [comment] 2015-12-02 17:36
Ahh.  apologies!  That's great news.

**Comment by jakevdp** [comment] 2015-12-02 19:04
@gforsyth – I couldn't reproduce the issues that were reported on twitter: seems to work on 1.5 for me. Does anyone have an example that breaks?

**Comment by gforsyth** [comment] 2015-12-02 19:07
@jakevdp - The animation in this notebook isn't working for me on two separate machines (one running jupyterhub, the other local).  https://github.com/numerical-mooc/numerical-mooc/blob/master/lessons/03_wave/03_02_convectionSchemes.ipynb

Everything loads (no errors thrown), but the buttons are unresponsive and no animation plays

**Comment by jakevdp** [comment] 2015-12-02 19:52
Found the source of the problem: with matplotlib 1.5, the HTMLWriter only outputs a single frame. I'm still not sure what caused this change however...

**Comment by jakevdp** [comment] 2015-12-02 20:09
It would be easier to debug with a minimal non-notebook example that fails.

I have to pivot to something else now — I would be much more likely to be able to debug this soon if someone were to tackle creating a minimal complete example that reproduces the bug.

**Comment by jenshnielsen** [comment] 2015-12-02 21:10
@jakevdp That bug sounds like a duplicate of  #5471

**Comment by gforsyth** [comment] 2015-12-02 21:20
@jenshnielsen @jakevdp Thanks!  That fixed it on my end -- JSAnimation working as expected.  Thanks for your help!

**Closed** 2017-09-01 03:10 UTC
Labels: needs_review
