### ISSUE TITLE
 imshow() in Cairo-based backends are flipped vertically

### ISSUE THREAD

**Issue by flueterflam** [matplotlib/matplotlib#11715] opened 2018-07-20 18:54 UTC
### Bug report

**Bug summary**

Using GTK3Cairo, TkCairo, and Qt5Cairo cause specgram() y-axis data to appear to rotate 180 degrees, while x-axis data is correct.  Compared with, for example, Qt5Agg, TkAgg, and GTK3Agg.

**Code for reproduction**

MWE (from comment https://github.com/matplotlib/matplotlib/issues/11715#issuecomment-406735726):
```python
ax1 = plt.subplot(212)
x = np.random.rand(20, 20)
x[3, :] = 19.
ax1.imshow(x)
plt.show()
```

ORIGINAL MWE:
(code pulled from https://matplotlib.org/gallery/images_contours_and_fields/specgram_demo.html#sphx-glr-gallery-images-contours-and-fields-specgram-demo-py and modified to include matplotlib.use(...) only)

```python
# Paste your code here
#
import matplotlib
#matplotlib.use("Qt5Cairo")# BAD - rotation
#matplotlib.use("TkCairo")# BAD - rotation
#matplotlib.use("GTK3Cairo")# BAD - rotation
matplotlib.use("Qt5Agg")# Good
#matplotlib.use("TkAgg")# Good
#matplotlib.use("GTK3Agg")# Good
#matplotlib.use("WebAgg")# Good
#%valid strings are ['GTK', 'GTKAgg', 'GTKCairo', 'GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'gdk', 'pdf', 'pgf', 'ps', 'svg', 'template']

import matplotlib.pyplot as plt
import numpy as np

# Fixing random state for reproducibility
np.random.seed(19680801)


dt = 0.0005
t = np.arange(0.0, 20.0, dt)
s1 = np.sin(2 * np.pi * 100 * t)
s2 = 2 * np.sin(2 * np.pi * 400 * t)

# create a transient "chirp"
mask = np.where(np.logical_and(t > 10, t < 12), 1.0, 0.0)
s2 = s2 * mask

# add some noise into the mix
nse = 0.01 * np.random.random(size=len(t))

x = s1 + s2 + nse  # the signal
NFFT = 1024       # the length of the windowing segments
Fs = int(1.0 / dt)  # the sampling frequency

# Pxx is the segments x freqs array of instantaneous power, freqs is
# the frequency vector, bins are the centers of the time bins in which
# the power is computed, and im is the matplotlib.image.AxesImage
# instance

ax1 = plt.subplot(211)
plt.plot(t, x)
plt.subplot(212, sharex=ax1)
Pxx, freqs, bins, im = plt.specgram(x, NFFT=NFFT, Fs=Fs, noverlap=900)
plt.show()
```

**Actual outcome**

![cairo_backend](https://user-images.githubusercontent.com/5010253/43019235-e6150a30-8c21-11e8-89c6-2f5732ccb268.png)

**Expected outcome**

![agg_backend](https://user-images.githubusercontent.com/5010253/43019207-cdf5315a-8c21-11e8-9eb4-9218990fbc26.png)

Unsure whether this issue occurred in previous versions...

**Matplotlib version**
  * Operating system: Windows 10 and Mingw64
  * Matplotlib version: 2.2.2
  *WORKING*
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg, TkAgg, GTK3Agg, WebAgg, etc.
  *NOT WORKING*
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Cairo, TkCairo, GTK3Cairo, cairo
  * Python version: 3.6.5 (Anaconda3), 3.7.0 (Mingw64)
  * Other libraries: numpy

For `conda` (Anaconda3), matplotlib installed from default channels
For `mingw` (MSYS2), matplotlib installed using `pacman -S mingw-w64-x86_64-python3-matplotlib` (2.2.2-2 mingw64)

For GTK-based backends, GTK and GObject, including all dependencies were installed following Windows directions from: https://pygobject.readthedocs.io/en/latest/getting_started.html  However, I used `x86_64` versions instead of `i686` versions.

**Note**
It is unclear to me whether this is a Matplotlib bug, or due to Cairo.  I do not have any other Cairo-based issues except for Matplotlib's `specgram()`.

**Comment by ImportanceOfBeingErnest** [comment] 2018-07-20 21:44
The image that appears under "Expected outcome" seems to be the one created with **Cairo, so this should be the **un**expected outcome, right?

**Comment by jklymak** [comment] 2018-07-20 21:44
I can confirm this, though in the opposite direction (Cairo has the spectral peak up at 900, and Agg has it down at 100)

**Comment by jklymak** [comment] 2018-07-20 21:44
ooops, cross post

**Comment by flueterflam** [comment] 2018-07-20 21:49
oops, yes.  Apologize for mixing the two images!  Edited to put actual/expected images in correct place.

**Comment by jklymak** [comment] 2018-07-20 21:50
Just to simplify this, Cairo is simply messing up imshow:

```python

ax1 = plt.subplot(212)
x = np.random.rand(20, 20)
x[3, :] = 19.
ax1.imshow(x)
plt.show()

```

### Qt5Cairo:


<img width="459" alt="boo" src="https://user-images.githubusercontent.com/1562854/43026791-131fbebc-8c2c-11e8-8464-08b2a71a1027.png">


I'll also point out the "Save" button on QtCairo doesn't respect high-res displays and only saves 1/4 of the plot.

**Comment by jklymak** [comment] 2018-07-20 21:51
(PS not that I *blame* QT cairo - I find `imshow`'s axis flipping behaviour very annoying)

**Comment by flueterflam** [comment] 2018-07-20 21:54
I updated the OP to reflect the more minimal example.

**Comment by QuLogic** [comment] 2018-07-20 23:31
Pretty sure this is a duplicate of one or more issues filed by @anntzer.

**Comment by jklymak** [comment] 2018-07-21 05:16
Yeah - #8798.  Closing as a duplicate....

**Closed by jklymak** 2018-07-21 05:16 UTC
Labels: GUI/Qt, backend/cairo
