### ISSUE TITLE
ImportError: DDL load faIled: The specified module could not be found.

### ISSUE THREAD

**Issue by scottwardc** [matplotlib/matplotlib#18338] opened 2020-08-24 12:00 UTC
Traceback (most recent call last):
  File "C:\Users\Scott Ward-Corderoy\Desktop\python_work\Projects\Data Visualisation\generating_data.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\Scott Ward-Corderoy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\matplotlib\__init__.py", line 174, in <module>
    _check_versions()
  File "C:\Users\Scott Ward-Corderoy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\matplotlib\__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: DLL load failed: The specified module could not be found.

I get the above error when trying to import matplotlib. I am new to programming and am unsure what I have done wrong. Any help would be massively appreciated. I assume more information is needed but I do not know what.

Thanks

**Comment by WeatherGod** [comment] 2020-08-24 13:37
How did you install matplotlib?

**Comment by scottwardc** [comment] 2020-08-24 13:43
> How did you install matplotlib?
> […](#)

By inputting this into the command terminal:

python -m pip install -U pip
python -m pip install -U matplotlib

The terminal displayed that it had been installed correctly which is why I do not understand what is causing the issue.

**Comment by Carlman92** [comment] 2020-08-24 14:53
I got the same problem this weekend, found similar threads and someone suggested downgrading to an older version and it works for me: 
matplotlib == 3.0.3
Not a fix for the problem but it could get you up and running until someone understand why it doesn't work.

**Comment by WeatherGod** [comment] 2020-08-24 16:43
This might be a duplicate of #18292

**Comment by QuLogic** [comment] 2020-08-24 22:30
I believe this is indeed a duplicate of #18292. There will be new wheels up in about 10 minutes that should fix this.

**Closed by QuLogic** 2020-08-24 22:30 UTC
Labels: Community support
