### ISSUE TITLE
pixels plotted by imshow aren't of constant size (some are larger than others)

### ISSUE THREAD

**Issue by mdeff** [matplotlib/matplotlib#13606] opened 2019-03-06 17:24 UTC
### Bug report

**The pixels plotted by ``imshow`` aren't of constant size. Some are larger than others.**

**Code for reproduction**

```python
import numpy as np
from matplotlib import pyplot as plt

matrix = np.diag(np.ones(100))

fig, ax = plt.subplots(figsize=(4, 4))
ax.imshow(matrix)
fig.savefig('imshow.png')

fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(matrix)
fig.savefig('imshow.pdf')
```

**Actual outcome**

It's quite visible on the following figure (`imshow.png` from the above code, but also shown like that in jupyter) that some pixels are larger than others.

![imshow](https://user-images.githubusercontent.com/6806065/53899959-b080f400-403b-11e9-8252-de3526cc1bdd.png)

While I assume it could be due to a low resolution image, the same happen for a larger `figsize`, even if the file is saved in a vector format such as PDF. Look (closely) at [`imshow.pdf`](https://github.com/matplotlib/matplotlib/files/2937465/imshow.pdf) from the above code.

**Expected outcome**

All pixels must be of the same size.

**Matplotlib version**

  * Operating system: Arch Linux
  * Matplotlib version: 3.0.3
  * Matplotlib backend: `module://ipykernel.pylab.backend_inline`
  * Python version: 3.7
  * Jupyter version (if applicable): jupyterlab 0.35.4

matplotlib was installed from pacman (the Arch Linux package manager)

**Comment by jklymak** [comment] 2019-03-06 17:36
It is indeed because your image does not have enough resolution;  imshow snaps to pixels, and if your data pixels don't divide into your image pixels you get a moire effect.  

I'm closing as a duplicate of https://github.com/matplotlib/matplotlib/issues/12934, but feel free to continue the conversation there if you have more to add!  Thanks...

**Closed by jklymak** 2019-03-06 17:36 UTC
