### ISSUE TITLE
MaxNLocator prune isn't working with decimals

### ISSUE THREAD

**Issue by kannkann** [matplotlib/matplotlib#8425] opened 2017-04-04 11:48 UTC
### Bug report

Using MaxNLocator with the prune='both' option should remove the upper and lower ticks. This does not work with decimal ticks. Probably because of rounding or something related with binary numbers.

Temporarily I fixed it for me by shifting the limits slightly instead of using prune.
axes.set(ylim=[axes.get_ylim()[0]*0.99999,axes.get_ylim()[1]*1.00001])

```python
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
fig,axes= plt.subplots(1,2)
axes[0].plot([0,4],[0.2,0.3])
axes[0].yaxis.set_major_locator(mtick.MaxNLocator(nbins=6, prune='both'))
print(axes[0].get_ylim())
axes[1].plot([0,4],[2,3])
axes[1].yaxis.set_major_locator(mtick.MaxNLocator(nbins=6, prune='both'))
print(axes[1].get_ylim())
plt.show()
```

**Actual outcome**
![image](https://cloud.githubusercontent.com/assets/26898407/24655223/4a306106-1935-11e7-95a8-7bdef51c73e8.png)

**Expected outcome**
(see right subplot)

**Matplotlib version**
Matplotlib 1.5.3
Python: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]

I hope I did everything right and this is helpful.

**Comment by afvincent** [comment] 2017-04-04 12:21
Thanks @kannkann for the report :)!

It looks like it may actually have been fixed on Matplotlib 2+. The following script (basically @kannkann's one with null y-margin due to the new defaults used in mpl 2+)
```python
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
fig, axs= plt.subplots(1,2)

for ax, ydata in zip(axs, ([0.2, 0.3], [2, 3])):
    ax.set_ymargin(0)  # to get ticks on the edges with Matplotlib 2+
    ax.plot([0, 4], ydata)
    ax.yaxis.set_major_locator(MaxNLocator(nbins=6, prune='both'))

plt.show()
```
produces
![figure_1-1](https://cloud.githubusercontent.com/assets/17270724/24656077/3f63bae6-1941-11e7-92c9-bcdbe3187750.png)
which seems like the expected behavior to me.

**Closed** 2017-04-04 16:33 UTC
