### ISSUE TITLE
Annotate arrows move improperly with figure resize

### ISSUE THREAD

**Issue by Jeitan** [matplotlib/matplotlib#8646] opened 2017-05-19 16:31 UTC
### Bug report

Annotate arrows change how they respect positioning / horizontal alignment depending on the size of the figure.

### Code

```python
import numpy as np
import matplotlib.pyplot as plt
    
xv = np.arange(100)
changes = np.ones(100) * 7.7
changes[35] = -40
changes[70] = -56
yv = changes.cumsum()
    
fig, ax = plt.subplots()
ax.plot(xv, yv)
ax.annotate('Big Drop', xy=(xv[35], yv[35]), xytext=(xv[35]-8, yv[35]-120),
            ha='center',
            arrowprops=dict(facecolor='k', width=0.5, headwidth=4,
                            headlength=6, shrink=0.1))
ax.annotate('Second Drop', xy=(xv[70], yv[70]), xytext=(xv[70]-8, yv[70]-120),
            ha='center',
            arrowprops=dict(facecolor='k', width=0.5, headwidth=4,
                            headlength=6, shrink=0.1))

plt.show()
```

**Actual outcome**

The text looks like it is placed correctly given the `xytext` offsets.  I'm expecting the arrows to point up and to the right, but this is the image created with the default figure size:
![figure_1](https://cloud.githubusercontent.com/assets/9399446/26257159/6d4b29de-3c74-11e7-80c0-92bf6b02c72e.png)

It looks like the arrow base is attached to the right side of the text box rather than the center.  If I manually shrink the width of the figure (by quite a bit), eventually both arrows pop over to what I'm expecting:
![figure_2](https://cloud.githubusercontent.com/assets/9399446/26257512/c539d414-3c75-11e7-8c97-87f6f43145b5.png)

The transition happens immediately at some particular width, but both arrows don't pop at the same time.

**Matplotlib version**

  * Operating System: Windows 10, 64-bit
  * Matplotlib Version: 2.0.0
  * Python Version: 3.5.2
  * Jupyter Version (if applicable):
  * Other Libraries: 

It doesn't appear to matter if I run this from Spyder or just simple IPython or just from the command line.

Installed from basic Anaconda 4.3.0 installer.

**Comment by tacaswell** [comment] 2017-05-20 03:03
Adding makers shows the text is where it should be

```python
import numpy as np
import matplotlib.pyplot as plt
    
xv = np.arange(100)
changes = np.ones(100) * 7.7
changes[35] = -40
changes[70] = -56
yv = changes.cumsum()
    
fig, ax = plt.subplots()
ax.plot(xv, yv)
ax.annotate('Big Drop', xy=(xv[35], yv[35]), xytext=(xv[35]-8, yv[35]-120),
            ha='center',
            arrowprops=dict(facecolor='k', width=0.5, headwidth=4,
                            headlength=6, shrink=0.1))
an = ax.annotate('Second Drop', xy=(xv[70], yv[70]), xytext=(xv[70]-8, yv[70]-120),
            ha='center',
            arrowprops=dict(facecolor='k', width=0.5, headwidth=4,
                            headlength=6, shrink=0.1))


an.draggable(True)
ax.plot(xv[[35, 70]]-8, yv[[35, 70]]-120, 'x', ms=25, mec='r')
plt.show()


```
![so](https://cloud.githubusercontent.com/assets/199813/26272319/f323441a-3ce2-11e7-804c-b8b6a6788330.png)

What is going on is that the annotation tries to make it's self as short as possible connecting from the data point to one of 8 points on the text bounding box (the corners and middle of each side).  The above example makes one of the annotations draggable, move it around to see the snapping.  As the aspect ratio of the figure changes the point chosen changes.  See 
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/text.py#L2267 for how this is implemented as an L1 norm, but :man_shrugging: 

To always go to the center, use a slightly different way of calling the annotation

```python
an2 = ax.annotate('Second Drop', xy=(xv[70], yv[70]), xytext=(xv[70]-8, yv[70]-120),
            ha='center',
            arrowprops=dict(facecolor='k', arrowstyle='->'))
```

which goes through a different code path.  See https://matplotlib.org/users/annotations.html#annotating-with-arrow for details.

Closing as not a bug but intentional behavior.

**Closed by tacaswell** 2017-05-20 03:03 UTC
