### ISSUE TITLE
[ENH]: Support Latex-like math rendering with Typst instead of pdflatex

### ISSUE THREAD

**Issue by SeerLite** [matplotlib/matplotlib#26098] opened 2023-06-09 14:28 UTC
### Problem

Latex compilers are very slow.

### Proposed solution

[Typst](https://github.com/typst/typst) is orders of magnitude faster than any latex compiler (runs in milliseconds) and has a much easier to use syntax than latex (subjective but I think most agree). I'd like to request support for it as a rendering engine for math in figures.

I'm not sure how rendering is currently done, but here's an example of a 0-margin document with math using typst:

```typst
#set page(width: auto, height: auto, margin: 0pt)
$ y = integral_(x_0)^x f(s) d s $
```
[Live preview on typst.app](https://typst.app/project/r4trB2mMP5Njm3x_X8teFo)

**Comment by oscargus** [comment] 2023-06-09 14:36
I doubt that "instead" will ever be the case (too many people rely on and know LaTeX already), but not impossible to add it as an alternative rendering engine. It may want to start as a third-party package though(?).

**Comment by ksunden** [comment] 2023-06-09 22:38
Typst is still _very_ new and changing rapidly.

I'm not opposed to including it in some way, but think it may not be quite ready for it yet.

Typst currently will only output in `pdf` or `png` format (and even the latter just made it into the released version _today_).

`png` is not a general solution as preferably text/equations are rendered as vector graphics where possible.

pdf is a complicated enough format that extracting vectors out of it is rather challenging, I believe, making that likely a poor candidate for the intermediate form. perhaps in the narrow case of a single page, single equation as it would be here, it is not _too_ bad, but I don't know.

Much of the internals for Matplotlib TeX rendering is done via `DVI` currently, so a DVI output from Typst would probably be the easiest to slot in, but perhaps svg or some other (simpler) vector format could work well too.

The other implementation detail that I think _may_ be hard to deal with is background color. We want transparent background, but I was unable (in quick testing) to get Typst to do that. PDF doesn't support a transparent background at all, but PNG _should_ be able to (it still had a white background if I set the `fill=rgb("#0000")` in the `page` command. This further precludes PNG from being a usable format, though I think a vector format would be able to extract only the actual content and ignore the background, so probably not actually any more of a blocker than having an extractable vector format.

The ability to have auto sized pages is cool, and may help any Typst implementation avoid some pitfalls of TeX such as #24166 if the bounding box given to us by Typst can be trusted more than the page size of TeX.

**Comment by anntzer** [comment] 2023-06-10 12:13
See also #22715 re: alternate TeX-like engines and https://github.com/matplotlib/matplotlib/issues/4880#issuecomment-141684932 (and the rest of that issue's thread) re: speed.
I am somewhat tempted to close this issue as a semi-duplicate of #22715 and also as "we'll consider a PR implementing this or moving towards it, but it'll have to come from interested users."

**Closed** 2023-06-10 15:13 UTC
Labels: New feature, topic: text

**Comment by jklymak** [comment] 2023-06-10 15:16
Agreed this is basically #22175 and given the state of typst getting something to work that has a parsable dvi-like output seems more likely.

**Comment by NeilGirdhar** [comment] 2025-08-15 05:46
It's been a couple years.  has the prognosis changed?

**Comment by ksunden** [comment] 2025-08-15 17:43
I don't think anybody from Matplotlib has kept up with Typst at all.

A quick look at their docs shows that they do now have export to SVG (unsure  whether math things are actually vector images or e.g. rasterized things embedded in a vector format (I'd guss the former, but have not looked))

This is still not the most ideal (given that our internals work primarily in DVI for intermediate format), but may make it _more_ likely to be able to work.

It would certainly require someone to champion it, and not sure anybody currently active in the project has the inclination to do so, so that is one big hurdle.

**Comment by SuperCowProducts** [comment] 2026-05-05 13:12
I will use [`t2l`](https://github.com/scipenai/tylax) CLI utlity for now, it's not always 100% accurate but still saves a lot of time.

Example:

```
yalihupokn@zoqu-endiman:~/Nextcloud/mp$ t2l <<< '$1/2$'
$\frac{1}{2}$
yalihupokn@zoqu-endiman:~/Nextcloud/mp$ 
```

**Comment by NeilGirdhar** [comment] 2026-05-05 13:45
@ksunden Which is more likely:
- Matplotlib consuming SVG,
- Typst producing DVI, or
- A third option (below)?

It seems like DVI is an almost dead format (only TeX uses it), and it's non-portable because fonts are not embedded, so the recipient must have the same fonts installed.  That's one of the things we want to avoid.

Also, a third option would be that Matplotlib calls a Python function to produce an SVG or similar that it renders.  Then, you could not only use that for the axis labels, but even things like tick mark numbers.  Everything would be rendered in the same font.

@SuperCowProducts A big part of the motivation for me for supporting Typst is using the exact same fonts so that my labels look the same as the surrounding text.

**Comment by tacaswell** [comment] 2026-05-07 16:21
When we shell out to LaTeX for rendering we then immediately consume the DVI and translate it to whatever output we are producing so none of those concerns about the portability or other use of DVI are relevant.

-----

If someone wants to prototype this in a stand alone code base I suggest sub-classing `matplotilb.text.Text`'s `draw` method.  If you can get an svg out of typst, then I suspect you will be able to convert that to a path and go through the render's `renderer.draw_path(...)` code path.  For example see https://github.com/matplotlib/matplotlib/blob/feb0e6e797bd54cd1535b3822dd730f07dade202/lib/matplotlib/backend_bases.py#L545-L576 which is the ultimate fallback path for rendering text.  Individual backends can provide version of `draw_text` (when we do everything ourself) and `draw_tex` (when we shell out to LaTeX to do something smarter).  Rather than messing around with svg (which you only need if you want to go to the vector backends), you could probably get away with generating a png from typst and dropping that in the output.

Once `TextTypst` exists and works (demo by just adding to the canvas), then we can think about a path to integrating it upstream.  This could be anything from "add `draw_typst` as a method on the renderer base classes and integrating it fully, to adopting the class and making it usable anyplace we use `Text`, or just making the class used for `Text` configurable and leaving the class in its own package.

One big concern as that we ship with an implementation of a sub-set of LaTeX is via mathtext which allows us to consume and render LaTeX strings without shelling out and we use this a number of places in generated text (e.g. tick labels).  Any proposal to push `TextTypst` upstream would have to include code that translates LaTeX to what typst understands both as a practical matter (we do not want to thread information about the users choice of text rendering through the whole code base) and to make it a tractable option for users with existing figures to switch back and forth between the two.

Given that typst is only three years old and looks like it is primarily backed by a company.  I am doubtful that we are going to drive this work from the Matplotlib side, I think this is going to have to be driven by someone who is really enthusiastic about typst.

---

To be clear the next step here is a `pip install` able package that lets you do:

```python
from mpl_typst import TextTypst
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.add_artist(TextTypst('$1/2$', ...))
# or at least a story of how to get here, maybe not automatic detection
ax.add_artist(TextTypst('$\frac{1}{2}$', ...))

fig.savefig('test.png')
fig.savefig('test.pdf')
fig.savefig('test.svg')
fig.savefig('test.eps')

```

Once that exists, then we can talk about how to best integrate it (if at all).

**Comment by NeilGirdhar** [comment] 2026-05-07 17:47
Thanks for the fast and clear reply!  I think the public API should make the persistent Typst context explicit:

```python
from typst import TypstSVGRenderer
import matplotlib.pyplot as plt
from matplotlib import SVGText

typst_renderer = TypstSVGRenderer(
    preamble="""
        #set text(font: "Libertinus Serif")
        #let skewfrac(a, b) = frac(a, b, style: "skewed")
    """
)

def typst(s: str) -> SVGText:
    return SVGText(s, svg_renderer=typst_renderer)

fig, ax = plt.subplots(text_factory=typst)

# text_factory makes it so that anywhere Matplotlib currently does something like:
#     Text(text=s, ...)
# it would instead do:
#     fig.text_factory(s, ...)

ax.set_xlabel("$x$")
ax.set_ylabel("$skewfrac(1, x)$")
ax.set_title("$sum_(i=1)^n x_i$")

fig.savefig("test.png")
fig.savefig("test.pdf")
fig.savefig("test.svg")
fig.savefig("test.eps")
```

Here `TypstSVGRenderer` is the persistent Typst renderer/cache/context that separates concerns (it knows nothing about Matplotlib):
```python
class TypstSVGRenderer(SVGRenderer):  # The SVGRenderer base just defines the interface.
    """Generic Typst renderer that produces SVG from strings."""
    def __init__(self, preamble: str = ""):
        self.preamble = preamble
        # Parse preamble once; own Typst cache/incremental state.

    def render(self, source: str) -> bytes:
        ...
```

Ideally, Matplotlib could provide the generic infrastructure for converting SVG output to `mathplotlib.path.Path` (together with fills, strokes, transforms, and metrics). For example, `SVGText` could work with any object satisfying an `SVGRenderer` interface, not just Typst:
```python
from matplotlib.backend_bases import RendererBase

class SVGText(matplotlib.text.Text):
    def __init__(self, source: str, *, svg_renderer: SVGRenderer):
        super().__init__(text=source)
        self.source = source
        self.svg_renderer = svg_renderer

    def draw(self, mpl_renderer: RendererBase) -> None:
        svg = self.svg_renderer.render(self.source)

        # Conceptually:
        #
        # paths = matplotlib.svg_to_paths(svg)
        #
        # for path in paths:
        #     mpl_renderer.draw_path(...)
```
> One big concern as that we ship with an implementation of a sub-set of LaTeX is via mathtext which allows us to consume and render LaTeX strings without shelling out and we use this a number of places in generated text (e.g. tick labels). Any proposal to push `TextTypst` upstream would have to include code that translates LaTeX to what typst understands both as a practical matter (we do not want to thread information about the users choice of text rendering through the whole code base) and to make it a tractable option for users with existing figures to switch back and forth between the two.

I may be misunderstanding the concern, but I don't think this proposal requires replacing mathtext, translating LaTeX to Typst, or threading a global “text rendering choice” through Matplotlib (which I agree would be horrible design). The text rendering strategy is already local to the figure using `text_factory`, while existing Text/mathtext behavior remains unchanged. In that sense this feels more like a generic SVG-backed text/vector-art infrastructure for Matplotlib, with Typst being just one possible SVG producer.

In an ideal world, you could also rip LaTeX out of Matplotlib and just make it another interchangeable producer behind one interface.  This is classic separation of concerns: Matplotlib handles the layout and backend rendering, and the text engine handles fonts.

Something like this feels like a natural fit for both Typst and Matplotlib’s rendering model.  What do you think?

**Comment by NeilGirdhar** [comment] 2026-05-22 02:54
@tacaswell Do you think the `SVGText` shown above might be something feasibly done by the matplotlib team?

**Comment by tacaswell** [comment] 2026-05-22 04:40
See https://matplotlib.org/stable/gallery/showcase/firefox.html for an example of going from svg -> `Path`.

As I said before, the blocking step here is someone who wants this feature to implement a working package that proves we typst can be integrated at all.  Any other discussion is getting ahead of our selves.  

-----

Because I can not help myself:

> In an ideal world, you could also rip LaTeX out of Matplotlib and just make it another interchangeable producer behind one interface.

Except they are not interchangeable, as it is my understanding typst is an entirely different markup language.  Thus even if you could trivially switch the `Text` class we would have to threaded through, anyplace we generate text for the users (mostly ticks via the formatters), information about which markup to use.  This is not intractable (we already do this for plain vas mathetx/LaTeX) but some design work, some naming work, and some tedious work.

>  The text rendering strategy is already local to the figure using text_factory,

The natural scope of Matplotlib is the figure so what you call "local" here, I would call "global" (as "local" is an isolated artist).  I do not think we have anything like this sort of factory that cascades all the way down from the `Figure`.  Artists do have references back up to their parents (which create loops which causes other problems so we do want to try and drop those) so in principle you could do this, but I think it would be messy.  We already have rcParams that control details of how we generate / render text, extending that is probably the most natural.  This does go one more "global" up, but we already have a context manager for working with them etc.

**Comment by NeilGirdhar** [comment] 2026-05-22 07:32
Thanks, that helps. I see now that the SVG-to-Path part can start much smaller than a general SVG renderer.

A reasonable first prototype seems to be:

1. make a standalone `mpl_typst` package;
2. implement a `TextTypst` Artist;
3. have it call the Typst CLI and produce SVG;
4. extract the SVG path data;
5. use the kind of SVG path parser you linked to convert that into `matplotlib.path.Path`;
6. draw those paths through the normal Matplotlib renderer path.

So the first target would not be `set_xlabel`, tick labels, rcParams, mathtext compatibility, or any upstream API. It would just be:

```python
from mpl_typst import TextTypst
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.add_artist(TextTypst("$frac(1, 2)$", x=0.5, y=0.5))
fig.savefig("test.png")
fig.savefig("test.pdf")
fig.savefig("test.svg")
fig.savefig("test.eps")
```

If that works, then the next problems are mostly engineering details: SVG transforms, fill/stroke handling, viewBox scaling, baseline/alignment, metrics, and caching. But I agree those are better discovered in a working external package than debated abstractly upstream.

What do you think?
