### ISSUE TITLE
[Bug]: "empty" PDF when I use a custom transformation

### ISSUE THREAD

**Issue by boffi** [matplotlib/matplotlib#28585] opened 2024-07-17 13:01 UTC
[A0_100.pdf](https://github.com/user-attachments/files/16265946/A0_100.pdf)
[A0_072a.pdf](https://github.com/user-attachments/files/16265949/A0_072a.pdf)
[A0_072b.pdf](https://github.com/user-attachments/files/16265953/A0_072b.pdf)

### Bug summary

I'm using a custom transformation and saving to PDF using the standard dpi value of 100 produces an "empty" file.
The only way that I've found[+] to have my Artists correctly rendered is to CREATE the Figure with `dpi=72`, 

[+] credit goes to SO member [Timeless](https://stackoverflow.com/users/16120011/timeless)'s [answer](https://stackoverflow.com/a/78754466/2749397) 
### Code for reproduction

```Python
import matplotlib.pyplot as plt
from matplotlib.transforms import Affine2D

mm = 1/25.4
w, h = 841, 1182

dpi = 100 # default dpi, but any dpi≠72 is "wrong"
fig = plt.figure(figsize=(w*mm, h*mm), layout='none', dpi=dpi)
trans = Affine2D().scale(mm*dpi).scale(1,-1).translate(0,h*mm*dpi)
fig.patches.append(
    plt.Rectangle((230, 190), 40, 18, transform=trans))
fig.savefig('A0_100.pdf',  dpi=dpi)
fig.savefig('A0_072a.pdf', dpi=72)

dpi = 72 # magic number
fig = plt.figure(figsize=(w*mm, h*mm), layout='none', dpi=dpi)
trans = Affine2D().scale(mm*dpi).scale(1,-1).translate(0,h*mm*dpi)
fig.patches.append(
    plt.Rectangle((230, 190), 40, 18, transform=trans))
fig.savefig('A0_072b.pdf')
```

### Actual outcome

A0_100.pdf is "blank"
A0_072a.pdf is blank
A0_72b.pdf is OK

### Expected outcome

Three PDF files containing a blue rectangle near the top-left corner

### Operating system

Suse Tumbleweed

### Matplotlib Version

3.9.0

### Matplotlib Backend

qtagg

### Python version

Python 3.11.9

### Installation

Linux package manager

**Comment by jklymak** [comment] 2024-07-17 13:53
It's not clear what you are trying to do, but doing things in raw pixels will always have this problem. An unfortunate historical artifact is that Matplotlib considers the unit transform to be pixels, but then that changes depending on output.  @QuLogic made an attempt to standardize to virtual pixels but I'm not sure where that got to. 

Anyway your transform will not survive dpi changes and that is indeed what happens when you save as pdf - the dpi changes from 100 to 72 which is the default pdf unit.  You will have the same problem saving to png with dpi=72 as well.  It's not clear what you are trying to do,  but doing things in physical units by using fig.dpi_scale_trans should make things dpi invariant

**Comment by boffi** [comment] 2024-07-17 15:23
@jklymak 

> It's not clear what you are trying to do

https://stackoverflow.com/questions/78746962/making-a-poster-how-to-place-artists-in-a-figure-using-mm-and-top-left-origin

I'm trying to force Matplotlib to work as a sort of page composition processor…

**Comment by jklymak** [comment] 2024-07-17 15:35
OK, so you want to put a 40x18 mm triangle at x = 230 mm, y = 190 mm?

The you want

```
import matplotlib.pyplot as plt
from matplotlib.transforms import Affine2D

mm = 1.0/25.4
w, h = 841.0, 1182.0
fig = plt.figure(figsize=(w*mm, h*mm), layout='none')

trans = Affine2D().scale(mm).scale(1,-1).translate(0,h*mm) + fig.dpi_scale_trans
fig.patches.append(
    plt.Rectangle((230, 190), 40, 18, transform=trans))
```

**Comment by boffi** [comment] 2024-07-17 15:42
@jklymak 
> You will have the same problem saving to png with dpi=72 as well
I have tested this code
```
import matplotlib.pyplot as plt
from matplotlib.transforms import Affine2D

mm = 1/25.4
w, h = 841, 1182

dpi = 100 # default dpi
fig = plt.figure(figsize=(w*mm, h*mm), layout='none', dpi=dpi)
trans = Affine2D().scale(mm*dpi).scale(1,-1).translate(0,h*mm*dpi)
fig.patches.append(
    plt.Rectangle((230, 190), 40, 18, transform=trans))
fig.savefig('A0_100.png',  dpi=dpi)
fig.savefig('A0_072a.png', dpi=72)

dpi = 72 # magic number
fig = plt.figure(figsize=(w*mm, h*mm), layout='none', dpi=dpi)
trans = Affine2D().scale(mm*dpi).scale(1,-1).translate(0,h*mm*dpi)
fig.patches.append(
    plt.Rectangle((230, 190), 40, 18, transform=trans))
fig.savefig('A0_072b.png')
```

Files `A0_100.png` and `A0_072b.png` are both correct (no change in dpi's during `savefig`) while `A0_072a.png1 is "empty" (`savefig`'s dpi is changed from `figure`'s dpi).

**Comment by boffi** [comment] 2024-07-17 15:46
@jklymak 
> `trans = Affine2D().scale(mm).scale(1,-1).translate(0,h*mm) + fig.dpi_scale_trans`

Thank you.

**Comment by jklymak** [comment] 2024-07-17 21:52
I'll close this as working as intended...

**Closed by jklymak** 2024-07-17 21:52 UTC
