### ISSUE TITLE
Saving with bbox='tight' does not respect figsize

### ISSUE THREAD

**Issue by ArchangeGabriel** [matplotlib/matplotlib#11681] opened 2018-07-17 17:10 UTC
### Bug report

When saving a picture with `bbox='tight'`, the produced file does not have the specified dimension (`figsize`).

This is mostly https://stackoverflow.com/questions/16118291/matplotlib-make-final-figure-dimensions-match-figsize-with-savefig-and-bbox-e

Especially this:
> Is there a way to specify the exact figure size after using bbox_inches='tight'? Basically, the extent of any whitespace around the figure ought to be decided in the document I'm inserting it into and not encoded into the figure pdf itself.

(Though excepted of “no whitespace” that would be replaced by “white space specified with `pad_inches`)

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.plot(range(0,10))
plt.savefig("tight.pdf",bbox_inches='tight',pad_inches=0)
```

**Actual outcome**

[tight.pdf](https://github.com/matplotlib/matplotlib/files/2202610/tight.pdf)

This file is `~5.1×3.9` inches instead of the expected mpl default of `6.4×4.8`.

**Expected outcome**

[tight_fixed.pdf](https://github.com/matplotlib/matplotlib/files/2202637/tight_fixed.pdf)

This file has the correct dimensions.

**Matplotlib version**
  * Operating system: Arch Linux
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.6

All packages from distro.

**Comment by ArchangeGabriel** [comment] 2018-07-17 17:11
Note: currently, as a workaround, I’m just trying the should-be-correct figure size `(a,b)`, then do a cross-product with the obtained size `(c,d)` to get a new figure size `(a*a/c,b*b/d)` to try, which in returns give me an output of size `(e,f)`. Finally, I’m doing the (seemingly quite correct) assumption of the obtained size to be an affine function of the input size, and thus get the slopes as `α=a*(a/c−1)/(e-c)` and `β=b*(b/d-1)/(f−d)`, which in turns makes me input `(a+α*(a−c),b+β*(b-d))`. At this point, I get (roughly?) the correct size. That’s how the second file was generated.

This is much more complex than I would like this to be, but I’m not sure whether a better solution will be implemented anytime soon.

I’m going to write a small helper to give me the correct size to give to matplotlib based on the obtained size and the desired one (especially because they are also conversions to be made since I have the desired value in TeX points, which are 1/72.27 of an inch, whereas I use pdfinfo to check the output size and this one uses PS points, which are 1/72 of an inch). I’ll share it when done.

**Comment by WeatherGod** [comment] 2018-07-17 17:13
By definition, bbox_inches defines what the final figure size should be.
The "tight" alias is a convenience function to have it compute what the
figure size should be in order to tightly bound all non-whitespace.

**Comment by ArchangeGabriel** [comment] 2018-07-17 17:20
@WeatherGod OK, but then the question remains as:
> Is there a way to specify the exact figure size after using bbox_inches='tight'? Basically, the extent of any whitespace around the figure ought to be decided in the document I'm inserting it into and not encoded into the figure pdf itself.

Or if you prefer: how can I make a figure of a given space with no “outside” whitespace?

**Comment by jklymak** [comment] 2018-07-17 17:20
You have three choices if you want the layout to be tight against the edges of a figure
1. Adjust the figure size around the tight bounding box of all the artists.  This is accomplished with `fig.savefig(fname, bbox='tight')`.
2. Adjust the figure elements so that they expand/contract to be at the edge of the figure.  This is accomplished with [`tight_layout`](https://matplotlib.org/tutorials/intermediate/tight_layout_guide.html#sphx-glr-tutorials-intermediate-tight-layout-guide-py)  or [`constrained_layout`](https://matplotlib.org/tutorials/intermediate/constrainedlayout_guide.html#sphx-glr-tutorials-intermediate-constrainedlayout-guide-py)
3. Use bbox='tight' and zoom the size of the figure in an external editor.  However, that won't preserve aspect ratio.

**Comment by ArchangeGabriel** [comment] 2018-07-17 17:32
1. Does not allow me to have a given figure size (at least not easily).
2. `plt.tight_layout(pad=0)` and `fig = plt.figure(constrained_layout=True); fig.set_constrained_layout_pads(w_pad=0, h_pad=0)` seem to work (at least they do on my above example). It’s strange, because I’ve spent half my day toying around this and always had too much whitespace remaining… Maybe I’ve missed something. I’ll retry, but not now.
3. Is not good, because it would also rescale fonts.

So 2. seems to be the solution, it’s strange that I didn’t succeed with it earlier. It also doesn’t match what is described on stackexchange, but it gives me an hint to what might be my issue: using both at the same time.

Anyway, thank you for your input, I’ll retry and let you know. ;)

**Comment by jklymak** [comment] 2018-07-17 17:35
Update the stackexchange answer if it works for you.  If 2. doesn't work, let us know why (w. a minimal example).  Maybe there is something wrong.  In particular `constrained_layout` is quite new, and the person who programmed has been known to make mistakes...

**Comment by tacaswell** [comment] 2018-07-17 17:43
Closing this as this as a feature not a bug,  As @WeatherGod says, `bbox_inches='tight'` is saying "resize the final figure to 'shrink wrap' the contents of my figure".  There is no way to do that, and to respect the figure size.

Can this discussion be moved to the mailing list (https://mail.python.org/mailman/listinfo/matplotlib-users) ?

**Comment by WeatherGod** [comment] 2018-07-17 17:44
(for those not in the know, that was self-deprecating humor). Jody is a
very fine programmer and we value his contributions to this project.

**Closed by tacaswell** 2018-07-17 17:43 UTC

**Comment by ArchangeGabriel** [comment] 2018-07-30 16:51
@jklymak Just to let you know, using both `tight_layout` and `bbox=tight` (because the last one was hardcoded in my matplotlibrc and apparently I cannot change that on the go) was the issue. Using either `tight_layout` or `constrained_layout` alone did the job, even if there is a bit more white space than I would want (setting all `pad` vars to 0).

I’ll answer the stackexchange and open a follow-up discussion on the ML.
