### ISSUE TITLE
alpha value of markeredgecolor is overwritten by markerfacecolor

### ISSUE THREAD

**Issue by hitzg** [matplotlib/matplotlib#4914] opened 2015-08-13 06:50 UTC
When setting both the `markeredgecolor` and the `markerfacecolor` as a rgba tuple, the transparency of both seems to be set to the one of `markerfacecolor`. Could this be a bug in matplotlib or am I making a mistake?

Minimal-ish example:

```python
import matplotlib.pyplot as plt
    
# plot markers with varying alpha values for edge and face colors
alpha_faces = [1.0, 0.3, 0.7, 0.3]
alpha_edges = [1.0, 0.3, 0.3, 1.0]
for n, (af, ae) in enumerate(zip(alpha_faces, alpha_edges)):
    plt.plot(n, 0, ms=20, mew=5, marker='s',  mfc=(1,0,0,af), mec=(0,0,1,ae))
    plt.text(n, 0.01, "$\\alpha$ edge: {}\n$\\alpha$ face {}".format(ae, af),
            va='bottom', ha='center')
    
# a black line to make the transparency clearer
plt.axhline(0, color='k', lw=3, zorder=0)
    
plt.xlim(-0.5, n+0.5)
plt.show()
```

Result:
![figure_1](http://i.stack.imgur.com/Bl5hp.png)

Versions: Ubuntu 12.04, python 2.7.3, matplotlib 1.4.3

I also posted this as a [question on SO](http://stackoverflow.com/questions/31981331/matplotlib-how-to-set-transparency-of-markeredgecolor).

**Comment by mdehoon** [comment] 2015-08-13 07:29
Duplicate of issue #4580 .

**Closed by mdehoon** 2015-08-13 07:29 UTC

**Comment by hitzg** [comment] 2015-08-13 07:36
Sorry, I couldn't find this one.
