### ISSUE TITLE
consider using qtpy for qt abstraction layer

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#6118] opened 2016-03-06 21:37 UTC
Instead of rolling our own, use https://github.com/spyder-ide/qtpy

The proposal would be to replace our `qt_compat.py` almost wholesale with `qtpy` imports.

**Comment by jenshnielsen** [comment] 2016-03-07 13:20
Sounds like a very good idea to me

**Comment by mdboom** [comment] 2016-03-07 14:46
Yes.  Spyder's needs of Qt are *much* more complex than ours, so I suspect it should do everything we need it to do.

**Comment by tacaswell** [comment] 2017-05-08 15:50
https://github.com/spyder-ide/qtpy/pull/84 <- they now support pyside2 so are back to wrapping parity.

**Comment by anntzer** [comment] 2017-12-13 18:44
See https://github.com/matplotlib/matplotlib/pull/9993#issuecomment-351482786 for arguments against it.

**Comment by anntzer** [comment] 2018-01-30 07:31
I think https://github.com/spyder-ide/qtpy/issues/138 needs to be fixed first by them.

**Comment by anntzer** [comment] 2018-06-19 16:14
Upon further thought, I am against switching to qtpy.  The main reason for this is that we *already* don't declare a dependency on any qt binding, and I guess we wouldn't declare a dependency on qtpy either.  Likewise, qtpy does not (by design) declare a dependency on any qt binding.  The end result is that you'd have to add yet another manual dependency management step for whoever wants to install matplotlib+qt from pypi.

**Comment by timhoffm** [comment] 2018-06-20 20:52
Not sure if this really works and is an accepted way of doing things, but could we create a placeholder package `matplotlib-qt`, that will basically only resolve the required dependencies when installing it with pip?

**Comment by anntzer** [comment] 2018-06-20 21:08
That doesn't really help, as the main sticking point is that multiple underlying qt bindings are supported (unless you want to create matplotlib-pyqt4, matplotlib-pyqt5, matplotlib-pyside, matplotlib-pyside2, but meh).

**Comment by timhoffm** [comment] 2018-06-20 21:30
All of them are an overkill, but maybe we declare one of them (pyside2 in the long run?) the preferred choice. Then there would be a simple way for the "standard" installation. If people want to use other bindings, they can but have to resolve the dependencies themselves.

**Comment by tacaswell** [comment] 2018-06-20 21:49
We have to keep supporting all the qt bindings and probably should not pick an (official) favorite.  We definitely can not pick up any dependencies on GUI bindings on pypi by default.  We probably should be using the 'extras' part of setup.py a bit more effectively though to support `pip install matplotlib[pyside2]` etc.

The advantage of moving to qtpy is that we can deprecate all of our binding selection logic and off-load it to qtpy.  We are then automatically in sync with any other project that uses qtpy (there is nothing more frustrating that trying to use more than one package that is opinionated about how to import qt bindings....).

**Comment by anntzer** [comment] 2018-06-21 22:09
> The advantage of moving to qtpy is that we can deprecate all of our binding selection logic and off-load it to qtpy. We are then automatically in sync with any other project that uses qtpy (there is nothing more frustrating that trying to use more than one package that is opinionated about how to import qt bindings....).

I think this would only be true if you decide to kill the qt4agg and qt5agg backends and replace them by a single qtagg backend, because otherwise we would still need to maintain code to override the backend selection logic to force either qt4 (pyqt4/pyside) or qt5 (pyqt5/pyside2).  (TBH I actually wouldn't mind doing such a deprecation, but I won't be the one making the call...)

**Comment by timhoffm** [comment] 2020-07-14 23:03
Is this still needed now that Qt4 is deprecated since Matplotlib 3.3?

**Comment by QuLogic** [comment] 2020-07-15 00:45
Depends on how Qt6 goes, I guess?

**Comment by timhoffm** [comment] 2020-07-15 00:51
Do we need to/would this cover also PySide2? I not I propose to close this as Qt6 is not yet there and we don't need  to hold the PR open just in case it may become relevant.

**Comment by efiring** [comment] 2020-07-15 01:17
Closing.  The last discussion was 2 years ago. If new reasons to switch to qtpy arise, a new issue can be opened.

**Closed by efiring** 2020-07-15 01:17 UTC
Labels: Difficulty: Medium, GUI/Qt
