### ISSUE TITLE
FAIL: matplotlib.tests.test_coding_standards.test_pep8_conformance_examples

### ISSUE THREAD

**Issue by jlec** [matplotlib/matplotlib#5857] opened 2016-01-15 08:34 UTC
Using pep8-1.7.0, python34 and matplotlib-1.5.1 I see the following error:

```python
======================================================================
FAIL: matplotlib.tests.test_coding_standards.test_pep8_conformance_examples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/matplotlib-1.5.1/work/matplotlib-1.5.1-python3_4/build/test/lib/matplotlib-1.5.1-py3.4-linux-x86_64.egg/matplotlib/tests/test_coding_standards.py", line 281, in test_pep8_conformance_examples
    expected_bad_files=expected_bad_files)
  File "/var/tmp/portage/dev-python/matplotlib-1.5.1/work/matplotlib-1.5.1-python3_4/build/test/lib/matplotlib-1.5.1-py3.4-linux-x86_64.egg/matplotlib/tests/test_coding_standards.py", line 143, in assert_pep8_conformance
    assert_equal(result.total_errors, 0, msg)
AssertionError: 1 != 0 : Found code syntax errors (and warnings):
/var/tmp/portage/dev-python/matplotlib-1.5.1/work/matplotlib-1.5.1-python3_4/examples/pylab_examples/legend_demo5.py:44:26: E711 comparison to None should be 'if cond is not None:'

----------------------------------------------------------------------
Ran 5166 tests in 738.112s
```

**Comment by jenshnielsen** [comment] 2016-01-15 09:07
This is caused by a new release of the pep8 tool and fixed by #5844

**Closed by jenshnielsen** 2016-01-15 09:07 UTC
