### ISSUE TITLE
[Bug]: 3d scatter plot marker problem

### ISSUE THREAD

**Issue by Donald-McLachlan** [matplotlib/matplotlib#27516] opened 2023-12-14 22:36 UTC
### Bug summary

Descriptions of markers say "." is a dot and "," is a pixel.  Using this example code, [matplotlib.org/stable/gallery/mplot3d/scatter3d.html](https://matplotlib.org/stable/gallery/mplot3d/scatter3d.html)
Changing "o" to "." works as expected, but changing "^" to "," produces a square.

### Code for reproduction

```python
matplotlib.org/stable/gallery/mplot3d/scatter3d.html
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/26903553/d46e8f1c-5d45-401c-99f0-c29cf07c0710)

### Expected outcome

I expect the squares to be pixels, but I cannot get matplotlib to produce it so I cannot show the expected result. ;-)

### Operating system

MacOS Sonoma 14.2

### Matplotlib Version

3.8.1

### Matplotlib Backend

MacOSX

### Python version

Python 3.10.12

### Installation

pip

**Comment by oscargus** [comment] 2023-12-15 06:56
This seems to be a problem for 2D-plots as well (here, `s` and `,` are used):

![image](https://github.com/matplotlib/matplotlib/assets/8114497/8a66698a-c4dd-4d18-9ae6-46868e6fce6f)

**Comment by ksunden** [comment] 2023-12-15 16:22
Closing as a duplicate of #11460

**Closed** 2023-12-15 16:22 UTC
Labels: topic: mplot3d, topic: markers
