### ISSUE TITLE
save file under existing name fails on windows

### ISSUE THREAD

**Issue by 1kastner** [matplotlib/matplotlib#9264] opened 2017-10-02 14:33 UTC
### Bug report

**Bug summary**

I create a figure, click save and use a name which is already in use. A pop-up asks me whether I really want to overwrite it. I click "yes". The saving process starts but the file does not change. Neither the image changes nor the last-modified date.

**Matplotlib version**

  * Operating System: WIndows 10
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6

**Comment by tacaswell** [comment] 2017-10-02 16:36
I can not reproduce this on linux

**Comment by kenogo** [comment] 2017-10-02 18:02
Just tried it out on Windows 10. I also have Python 3.6 and Matplotlib 2.0.2 installed. Couldn't reproduce this. I saved the file as PNG, what file type did you try?

**Comment by kenogo** [comment] 2017-10-02 20:08
Good idea @anntzer. My backend is Tkinter (matplotlib.get_backend() returns 'TkAgg'), so that one has no issues.

**Comment by 1kastner** [comment] 2017-10-03 08:22
My backend is 'Qt5Agg'. I tried to save it as a png. This error was not reproducable with a small example such as [0] but when i re-ran it with my large amount of data the same behavior persists.
With large I mean a data point for every one to ten minutes for a whole year from 200 to 630 different sources. While producing the plots it takes about 1 GB of memory. I am aware that this amount of data can not be seen in a small plot but downsampling is not the job I want to do and I am happy with the result. Everything else works fine.

How I circumvent the issue by now: save the file under a different name, delete the old file, rename the new file. That way the plot can perfectly be saved.

[0] http://matplotlib.org/examples/pylab_examples/pythonic_matplotlib.html

**Comment by tacaswell** [comment] 2017-10-03 08:34
Is it possible that you are just checking too quickly before it has finished saving / file system refreshing?

I can not think of any other mechanism that would couple the size of the plot to the reported problem.  In 2.1 we add a 'busy' cursor which might help debugging this sort of thing.

**Comment by 1kastner** [comment] 2017-10-03 17:12
I waited until the busy cursor stopped and turned back into the normal cursor. By that time nothing had changed. When I save it under a different name, the file shows up much earlier. Like, normally when I save it, it showed up some seconds later. Now I saved it under an existing name several hours ago and I kept everything open, went for a walk etc. and still the new file does not show up. Still everything is as before.

**Comment by 1kastner** [comment] 2017-10-03 17:27
Sadly I can not share the data as it is protected by license. I guess the best way is to create some random noise. For me it is 270 MB of CSV files to give an estimate of what is needed. Maybe I have a look at it from the wrong perspective and it is not the amount of data which matters here. Maybe I invoke something bad and matplotlib does not forgive me that. Now I am a bit busy to freely play around with it.

My code

    for station_dict in stations:  # maybe 200 stations
        station_df = retrieve_pandas_dataframe(station)  # should be some random data
        nan_df = pandas.DataFrame(
            index=pandas.date_range(station_df.index[0], station_df.index[-1], freq='H', 
                name="datetime"),  
            # datetime is the index used in the pandas station dataframe
        )

        station_df = station_df.join(nan_df, how="outer")
        pyplot.plot(station_df.index, station_df.temperature, linewidth=.4, color='gray', 
            alpha=.8)

    reference_station_df = load_reference_station_df()

    pyplot.plot(reference_station_df.index, reference_station_df.temperature, color="blue", 
        linewidth=.4, label="Referenznetzwerk")

    ax = pyplot.gca()
    ax.set_ylabel('Temperatur (°C)')
    ax.set_xlabel('2016')
    ax.margins(x=0)
    ax.yaxis.set_major_locator(mticker.MultipleLocator(5))  # draw line every 5 °C
    pyplot.grid(color='.9')  # a very light gray
    ax.xaxis.set_major_locator(mdates.MonthLocator())
    ax.xaxis.set_major_formatter(DateFormatter("%b"))

    # only one entry for many
    gray_line = mlines.Line2D([], [], color='gray', label="private Wetterstationen")  

    # proper line width to see color
    blue_line = mlines.Line2D([], [], color="blue", label="Referenznetzwerk") 
    ax.legend(
        [blue_line, gray_line],
        [blue_line.get_label(), gray_line.get_label()],
        loc='best'
    )
    pyplot.show()

**Comment by anntzer** [comment] 2017-10-03 17:30
Can you include a random data generation procedure (in a way that triggers the issue for you)?  This will make it easier for us to investigate the issue.

**Comment by 1kastner** [comment] 2017-10-03 18:15
This code does it for me:

    import numpy
    from matplotlib import pyplot
    import pandas
    from matplotlib import lines as mlines
    import matplotlib.dates as mdates

    for station_dict in range(20):  # maybe 200 stations
        station_df = pandas.DataFrame(numpy.random.randint(0, 100, size=(525600, 1)), columns=["temperature"])
        pyplot.plot(station_df.index, station_df.temperature, linewidth=.4, color='gray', 
            alpha=.8
        )

    ax = pyplot.gca()
    ax.set_ylabel('Temperatur (°C)')
    ax.set_xlabel('2016')
    ax.margins(x=0)
    pyplot.grid(color='.9')  # a very light gray
    ax.xaxis.set_major_locator(mdates.MonthLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b"))

    # only one entry for many
    gray_line = mlines.Line2D([], [], color='gray', label="private Wetterstationen")  

    # proper line width to see color
    blue_line = mlines.Line2D([], [], color="blue", label="Referenznetzwerk") 
    ax.legend(
        [blue_line, gray_line],
        [blue_line.get_label(), gray_line.get_label()],
        loc='best'
    )
    pyplot.show()

When I save that file by clicking on the save button, then it turns busy, the file appears, can be opened even though it is still busy. But when I want to overwrite an existing file, even after it comes back from being busy, no change can be detected.

**Comment by 1kastner** [comment] 2017-10-06 08:39
Did you have any chance to reproduce this behavior with my code?

**Comment by kenogo** [comment] 2017-10-06 10:02
@1kastner For me, initially saving the file took several minutes. So when I try to overwrite the file, I of course need to wait a couple minutes again until I can close the program. The file got overwritten for me using Qt5Agg and Windows 10 (judging by the "last-modified date"). So no, I couldn't reproduce your problem.

**Comment by 1kastner** [comment] 2017-10-06 11:36
I can understand your doubts in this issue and I can play it through several times again to be more than sure. Last time I gave it 5 hours even though normally after like two minutes it was saved. After 5 hours nothing had happened. I will try again

@kenogo did you write a script to do this automatically or did you use the UI to do the steps?

**Comment by kenogo** [comment] 2017-10-06 15:04
I used the UI for saving and your script, with the addition of `matplotlib.use("Qt5Agg")` in the beginning to ensure I use the same backend as you. Really strange that I can't observe that bug 😕 with the same system and everything, but if you let it run that long it surely can't be the problem that you just closed it too early. I don't have any clue what could be going on here.

**Comment by kenogo** [comment] 2017-10-06 15:16
Ok, two questions: Does this only happen when using the UI and have you tried running the script as administrator? Maybe/probably some weird Windows stuff is going on, and I'm honestly pretty clueless about Windows. I usually avoid using it.

**Comment by jklymak** [comment] 2018-07-15 15:59
Closing for lack of progress...

**Closed by jklymak** 2018-07-15 15:59 UTC
Labels: Needs confirmation, OS/Microsoft
