### ISSUE TITLE
streamplot on irregular grids

### ISSUE THREAD

**Issue by mghadam** [matplotlib/matplotlib#4133] opened 2015-02-19 22:48 UTC
I used my set of data to plot a streamplot using matplotlib 1.4.3

the data range is from 0 to 1, grid points are equally spaced (except near corners which is dx/2 & dy/2)
the generated streamlines are correct but it seems that the whole streamplot is somehow scaled,, the range is shown to be from 0 to 0.5 instead of 0 to 1.

Here is my python code:

```
import numpy as np
import matplotlib.pyplot as plt
import linecache
str = linecache.getline("./result.dat", 2)
[n_x, n_y] = [int(s) for s in str.split() if s.isdigit()]
[X, Y, P, U, V] = np.genfromtxt("./result.dat", skip_header=2, unpack=True)
X = X.reshape(n_x,n_y)
Y = Y.reshape(n_x,n_y)
U = U.reshape(n_x,n_y)
V = V.reshape(n_x,n_y)
plt.streamplot(X, Y, U, V,color=U, linewidth=.6)
plt.colorbar()
plt.show()
```

and here is my data file called "result.dat":

```
 VARIABLES = "Xp", "Yp", "P", "Up", "Vp"
 ZONE I=           6 , J=           6 , F=POINT
     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000
     0.12500000     0.00000000     0.00000000     0.00000000     0.00000000
     0.37500000     0.00000000     0.00000000     0.00000000     0.00000000
     0.62500000     0.00000000     0.00000000     0.00000000     0.00000000
     0.87500000     0.00000000     0.00000000     0.00000000     0.00000000
     1.00000000     0.00000000     0.00000000     0.00000000     0.00000000
     0.00000000     0.12500000     0.00000000     0.00000000     0.00000000
     0.12500000     0.12500000     0.00000000    -0.00163538     0.00163537
     0.37500000     0.12500000     0.00271924    -0.00390620     0.00063544
     0.62500000     0.12500000     0.00654694    -0.00391532    -0.00062633
     0.87500000     0.12500000     0.00931612    -0.00164449    -0.00164449
     1.00000000     0.12500000     0.00000000     0.00000000     0.00000000
     0.00000000     0.37500000     0.00000000     0.00000000     0.00000000
     0.12500000     0.37500000    -0.00274526    -0.00271282     0.00598356
     0.37500000     0.37500000     0.00165029    -0.00629836     0.00214359
     0.62500000     0.37500000     0.00754400    -0.00632485    -0.00209888
     0.87500000     0.37500000     0.01205898    -0.00273931    -0.00602829
     1.00000000     0.37500000     0.00000000     0.00000000     0.00000000
     0.00000000     0.62500000     0.00000000     0.00000000     0.00000000
     0.12500000     0.62500000    -0.01019055    -0.00543907     0.01413544
     0.37500000     0.62500000    -0.00096611    -0.01172831     0.00386647
     0.62500000     0.62500000     0.00987021    -0.01171517    -0.00380840
     0.87500000     0.62500000     0.01944773    -0.00542593    -0.01419353
     1.00000000     0.62500000     0.00000000     0.00000000     0.00000000
     0.00000000     0.87500000     0.00000000     0.00000000     0.00000000
     0.12500000     0.87500000    -0.02733655     0.00978724     0.00978725
     0.37500000     0.87500000    -0.00486621     0.02193280     0.00235832
     0.62500000     0.87500000     0.01378493     0.02195528    -0.00233585
     0.87500000     0.87500000     0.03680858     0.00980972    -0.00980973
     1.00000000     0.87500000     0.00000000     0.00000000     0.00000000
     0.00000000     1.00000000     0.00000000     1.00000000     0.00000000
     0.12500000     1.00000000     0.00000000     1.00000000     0.00000000
     0.37500000     1.00000000     0.00000000     1.00000000     0.00000000
     0.62500000     1.00000000     0.00000000     1.00000000     0.00000000
     0.87500000     1.00000000     0.00000000     1.00000000     0.00000000
     1.00000000     1.00000000     0.00000000     1.00000000     0.00000000
```

Result:
![figure_1](https://cloud.githubusercontent.com/assets/10244293/6277731/7f82d768-b8a6-11e4-9da4-167ac4833982.png)

Thanks

**Comment by tonysyu** [comment] 2015-02-20 01:42
This is a bug in the algorithm: There's an assumption that the grid is uniform (see https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/streamplot.py#L277):

```python
self.dx = x[1] - x[0]
self.dy = y[1] - y[0]
```

I don't know how difficult it would be to support irregular grids, but I know that @tomflannaghan has an implementation. Maybe this would be a good time to submit a PR :)

At a minimum, the lines linked above should be replaced with something like

```python
self.dy = y[1] - y[0]
assert_allclose(np.diff(y), self.dy)
```

**Comment by QuLogic** [comment] 2020-07-23 08:18
Closing as duplicate of #12025; though it's newer, it has some more information.

**Closed by QuLogic** 2020-07-23 08:18 UTC
Labels: New feature
