### ISSUE TITLE
Unexpected MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "dpi"

### ISSUE THREAD

**Issue by Aikhjarto** [matplotlib/matplotlib#19714] opened 2021-03-16 12:59 UTC
### Bug report

**Bug summary**
Without manually calling `savefig()`, a `MatplotlibDeprecationWarning`  regarding `savefig()` is generated when calling `tight_layout()`.

**Code for reproduction**
```python
from matplotlib.figure import Figure
fig = Figure()
fig.add_subplot(111)
fig.tight_layout()
```
**Actual outcome**
The warning
`MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "dpi" which is no longer supported as of 3.3 and will become an error two minor releases later
`
is displayed although savefig() was never called in the example.

**Expected outcome**
Figure instance generated without a warning.

**Matplotlib version**
***Testsetup 1:***
  * Operating system: openSUSE Leap 15.2
  * Matplotlib version 3.3.4
  * Matplotlib backend agg
  * Python version: 3.8.6
Matptlotlib was installed via `pip`.

***Testsetup 2:***
  * Operating system: Windows 10
  * Matplotlib version 3.3.2
  * Matplotlib backend Qt5agg
  * Python version: 3.6.12
Matptlotlib was installed via `conda` using the default channel.

**Comment by jklymak** [comment] 2021-03-16 14:30
I cannot reproduce.  make sure you don't have something set in your matplotlibrc.

However, I'm not sure you want to just instantiate a bare figure like that.  Suggest `fig=plt.figure()`.

**Comment by anntzer** [comment] 2021-03-16 14:59
I think this is fixed by https://github.com/matplotlib/matplotlib/pull/19503.

**Closed by anntzer** 2021-03-16 14:59 UTC
