### ISSUE TITLE
Inconsistent top and bottom xticks label padding

### ISSUE THREAD

**Issue by mrkwjc** [matplotlib/matplotlib#17208] opened 2020-04-22 05:31 UTC
Hi!
I get the inconsistent label padding for top and bottom xticks. The following code and picture shows this:
```python
import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.rcParams['xtick.top'] = True
mpl.rcParams['xtick.labeltop'] = True
mpl.rcParams['xtick.major.pad'] = 0
mpl.rcParams['xtick.minor.pad'] = 0

plt.plot([0, 5], [0, 5])
plt.xlabel('x label')
plt.ylabel('y label')

plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/4333031/79944038-dd27e300-846a-11ea-986b-ac12da8aaf84.png)

The problem is the non-zero label padding at the top whereas the padding is zero (as expected) at the bottom. Is this a bug or intended behavior? How can i change this?

**Comment by naveenv92** [comment] 2020-04-27 18:31
So from playing around a bit, it looks like there's a small gap between the text baseline and the bottom of the text object. So, if you run the following code instead (I generated a subplot in the figure since it makes it easier to get and set properties):

```python
import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.rcParams['xtick.top'] = True
mpl.rcParams['xtick.labeltop'] = True
mpl.rcParams['xtick.major.pad'] = 0
mpl.rcParams['xtick.minor.pad'] = 0

fig, ax = plt.subplots()
ax.plot([0, 5], [0, 5])
ax.set_xlabel('x label')
ax.set_ylabel('y label')

for label in ax.get_xticklabels():
    label.set_verticalalignment('baseline')

plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/6731730/80407148-076a0e00-887a-11ea-9675-c662e3ca014e.png)

We get the expected behavior on top now, but the ticks at the bottom are aligning their baseline to the end of the tick.

I think the most basic workaround would be to use a parasitic axis and set the vertical alignment of its x-ticks to "baseline".

```python
import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.rcParams['xtick.top'] = True
mpl.rcParams['xtick.labeltop'] = True
mpl.rcParams['xtick.major.pad'] = 0
mpl.rcParams['xtick.minor.pad'] = 0

fig, ax = plt.subplots()
ax2 = ax.twiny()
ax.plot([0, 5], [0, 5])
ax.set_xlabel('x label')
ax.set_ylabel('y label')
left, right = ax.get_xlim()
ax2.set_xlim(left, right)

for label in ax2.get_xticklabels():
    label.set_verticalalignment('baseline')

plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/6731730/80407365-5ca61f80-887a-11ea-9278-21054d09e3a3.png)

Hope this helps!

**Comment by timhoffm** [comment] 2020-04-29 11:43
The gap between the baseline and the the bottom of the text is the descender and is part of total text height.

See:
https://en.wikipedia.org/wiki/Baseline_(typography)
https://en.wikipedia.org/wiki/Descender

Most digits don't use the descender and therefore it looks like an additional gap for the the top labels. However quoting the second of the above links:

>  Some fonts, however, also use descenders for some numerals (typically 3, 4, 5, 7, and 9).

**I don't think that we want or even can do something about this.**
If you want to modify this for a specific plot, you should set an additional negative offset for upper tick labels.


You can check that there is no other additional gap by using letters:
~~~
import matplotlib.pyplot as plt 
import matplotlib as mpl 
 
mpl.rcParams['xtick.top'] = True 
mpl.rcParams['xtick.labeltop'] = True 
mpl.rcParams['xtick.major.pad'] = 0 
mpl.rcParams['xtick.minor.pad'] = 0 

plt.plot([0, 3], [0, 3]) 
plt.xticks(range(3), ['a', 'f', 'j']) 
plt.show() 
~~~

![grafik](https://user-images.githubusercontent.com/2836374/80591960-e55dc080-8a1e-11ea-9685-6cff0220ba14.png)

**Comment by mrkwjc** [comment] 2020-04-29 13:25
> If you want to modify this for a specific plot, you should set an additional negative offset for upper tick labels.

Unfortunately it seems there's only one setting for xticks padding, which means that bottom and top pad values cannot be differentiated. This is problem when you need both top and bottom labels. I think, this could be fixed by adding additional `xticks` options, like:
```
mpl.rcParams['xtick.major.toppad'] = -1 
mpl.rcParams['xtick.major.bottompad'] = 0
```
Otherwise you need the (dirty) workarounds with additional axes like @naveenv92 proposed (thanks by the way!).

**Comment by timhoffm** [comment] 2020-04-29 16:15
Yes, it's true that there are no separate pad options for top and bottom for the same axes.

However, I'm :-1: on adding those rcParams. That would just be a partial patch for this explicit use case. Other parameters can also not be tuned separately. There's a plan for a major overhaul of the tick system in the mid future. Adding more stuff to the current system would make that even harder. For now, I'd kindly ask you to use the workaround with a second axes if you need that level of control.

**Comment by jklymak** [comment] 2020-04-29 16:38
Ha ha, yeah, this isn't even possible the way ticks are implemented now.  The top and bottom axes "tick" is the same object, so they share the same pad.  As @timhoffm says, ticks and axes are due for a pretty major overhaul, so I would expect this to be considered during that overhaul.

**Comment by mrkwjc** [comment] 2020-04-29 17:38
Ok. Thank you very much for the clarifications. Second axes is an option for now, but i hope the re-engineered ticks will address the problem.

**Comment by timhoffm** [comment] 2020-07-20 08:53
Closing, because there's nothing that can Be done in the existing tick system. And independent pads per axis would be a natural thing for the tick overhaul. I don't think we need this open to track that.

**Closed by timhoffm** 2020-07-20 08:53 UTC
Labels: Won't or can't fix, ticks axis labels
