### ISSUE TITLE
UnboundLocalError in hist(x, bins, histtype='step', normed=1) on double entries in bins

### ISSUE THREAD

**Issue by Energya** [matplotlib/matplotlib#6649] opened 2016-06-27 09:15 UTC
A minimal working example (in v1.5.1):

```
import numpy as np
import matplotlib.pyplot as plt
x = np.arange(10)
bins = [0, 3, 3, 6, 10]                       # Note the double occurrence of '3'
plt.hist(x, bins, histtype='step', normed=1)  # Only fails on this combination
```

This results in:

> RuntimeWarning: invalid value encountered in true_divide
>   m = (m.astype(float) / db) / m.sum()

followed by:

> Traceback (most recent call last):
> [...]
>   File "C:\Python27\lib\site-packages\matplotlib\axes_axes.py", line 6209, in hist
>     ymin = max(ymin*0.9, minimum) if not input_empty else minimum
> UnboundLocalError: local variable 'ymin' referenced before assignment

I have already looked into the code: the problem is the double occurrence of a bin edge, which on a divide by zero results in a `nan` value somewhere.

An easy fix for this problem would probably be checking for 0-values in `np.diff(bins)`, but I'm not sure about a few things, which I hope someone can help me with so I can make a useful contribution to the code:
- Should this be fixed inline (i.e. something like `bins = sorted(set(bins))` or raise an exception?
- Should this be valid behavior for all other histogram cases?
- Is it better to check for this at the start, or only just before it actually becomes a problem? (i.e. around line 6000 of _axes.py)

I will be very grateful if someone can point me in the right direction, don't want to blindly create a pull-request which does not follow the coding style and then has to be redone several times.

Edit: linenumbers may be slightly off from v2.x, but I have checked the online code and it seems to be the same

**Comment by tacaswell** [comment] 2016-06-27 12:59
Maybe related to https://github.com/matplotlib/matplotlib/issues/6448 as it is related to handling corner cases is sorting out the y limits of the data.

Changing the bin edges the user passes in is not a good idea (as the size of the outputs from hist are documented in terms of the size of the inputs)

The correct place to fix this is in the code computes the x/y limits and maybe in the code that does the norm computation.

What does numpy do with zero-width bins in histograms?  I assume just put no counts in them?

Also see http://matplotlib.org/devel/index.html

**Comment by Energya** [comment] 2016-06-27 13:19
@tacaswell Thanks for the input and pointing me to the other issue report, I'll look into it.

> Changing the bin edges the user passes in is not a good idea (as the size of the outputs from hist are documented in terms of the size of the inputs)
Then I correctly suspected as much

> The correct place to fix this is in the code computes the x/y limits and maybe in the code that does the norm computation.
Most likely at the first division by zero warning then? As that is where the `nan` values enter the local variables used for plotting

> What does numpy do with zero-width bins in histograms? I assume just put no counts in them?
Yes, I looked into that. Numpy does force bins to be monotonically increasing, but that only checks that `bins[i] <= bins[i+1]`. Zero-width bins are simply given a count of 0.

**Comment by tacaswell** [comment] 2016-06-27 13:31
mpl will correctly plot `np.nan` (by skipping it), the issue is just in computing the limits.

**Comment by anntzer** [comment] 2017-04-16 06:19
As far as I can see this is no longer an issue in 2.0 (due to changes in how axes autolimits are computed), so closing. Feel free to request a reopen if necessary.

**Closed by anntzer** 2017-04-16 06:19 UTC
