### ISSUE TITLE
Incorrect font rendering with devanagari

### ISSUE THREAD

**Issue by pranphy** [matplotlib/matplotlib#15597] opened 2019-11-03 05:24 UTC
```
plt.plot([1,2,3,8,6,4,3,1],'o-',label='राष्ट्र')
plt.xlabel('निवृत्ति प्रतिशत')
plt.ylabel('चक्रीय ब्याज')
plt.legend()
```
![image](https://user-images.githubusercontent.com/10902216/68080742-c8ca2e00-fdd7-11e9-91d3-c1006da1df62.png)

Devanagari font rendering is incorrect. For example: निवृत्ती प्रतिशत should be displayed as 
![image](https://user-images.githubusercontent.com/10902216/68080730-9caead00-fdd7-11e9-95ca-31a280667128.png) but is instead displayed as: ![image](https://user-images.githubusercontent.com/10902216/68080736-ba7c1200-fdd7-11e9-86e9-dd13a234e155.png)

 In matplotlibrc I have specified
```
font.family         : sans-serif
font.sans-serif     : Lohit Devanagari
```
[`Lohit devanagari`](https://www.fontsc.com/font/lohit-devanagari) has the required glyphs, in fact the correct rendering example is using `Lohit Devanagari` font.

**Comment by QuLogic** [comment] 2019-11-03 09:05
This is unlikely to be fixed without switching to a more featured text rendering library (perhaps #14912).

At this time, if you require text with complex shaping requirements, I believe the [mplcairo backend](https://github.com/matplotlib/mplcairo) by @anntzer is capable enough to render your text:
![Figure_1](https://user-images.githubusercontent.com/302469/68082125-d0dd9a00-fde6-11e9-9c12-1802f7a92d77.png)

**Comment by anntzer** [comment] 2019-11-04 10:29
This is a duplicate of https://github.com/matplotlib/matplotlib/issues/8765.

**Closed by anntzer** 2019-11-04 10:29 UTC
Labels: Duplicate, text/fonts
