### ISSUE TITLE
Starting pylab or creating new figures steals focus

### ISSUE THREAD

**Issue by keflavich** [matplotlib/matplotlib#8246] opened 2017-03-09 01:54 UTC
I'm using matplotlib 2.0.0 installed via anaconda with ipython 4.2.0 on mac os x 10.9.5.  Since upgrading to matplotlib 2.0.0, whenever I start a matplotlib-enabled session (e.g., `ipython --matplotlib`) or a new window is created, it steals focus from the OS.  I'm using the `TkAgg` backend, though the same thing happens with Qt5.

This is particularly a problem for some test codes that create a large number of windows while running; I effectively cannot access the OS at all when the tests are running, even the terminal, so I can't kill the thread.

Any suggestions on what might have happened with this latest upgrade?  Since this was anaconda-installed, I can't rule out a change in the backends rather than with matplotlib, but I think the relevant expertise is likelier to be here.

**Comment by eas342** [comment] 2017-06-14 10:53
Using the `Agg` backend seems to stop stealing focus for my python 2.7, Mac OS X 10.10.5. This bug is annoying me too. Unfortunately, `Agg` is only a bandaid solution.

**Comment by tacaswell** [comment] 2017-06-14 18:34
https://github.com/matplotlib/matplotlib/pull/6384 https://github.com/matplotlib/matplotlib/issues/6378 and https://github.com/matplotlib/matplotlib/issues/596

This was likely intentional, but I am not sure exactly what change caused it.

For running tests and background tasks using a non-interactive backend is the right thing to do any way (or to not use `plt.show` + `plt.ion()`).

**Comment by tacaswell** [comment] 2017-08-13 01:51
Flagging this a critical to make sure we talk about it.

**Comment by patricknraanes** [comment] 2019-06-25 14:06
Is there any solution or hack to address this?

Although bring-to-front is nice, I really want to avoid loosing the focus from the terminal.

Tested with:
 - Python 3.7
 - matplotlib 3.1.0
 - MacOS 10.12 with backend Qt5Agg
 - Windows 10 with backend TkAgg
 - Windows 10 with backend Qt5Agg
Fin the last case, the focus is not stolen for window creation until I've created and closed some figures to begin with.

**Comment by m-a-r-o-u** [comment] 2021-11-28 10:19
This is still a problem for: 
    OSX Monterey 12.0.1
    Python 3.9.9
    Qt5Agg

**Comment by pag** [comment] 2021-12-02 15:16
This was annoying me enough that I tracked it down. It's an IPython thing and nothing to do with matplotlib per se. The cause is that as soon as you start processing events on a QApplication the MacOS dock entry is created and the application is activated. I couldn't find a way to stop the application being immediately activated (or to easily deactivate it once it's first activated), so my fix is to not process any Qt events in the IPython event hook until a window has been created, e.g. a matplotlib figure is shown. 

https://gist.github.com/pag/f7d1ebbd1b14fe9058bf68d73a52bc84 

It's working nicely. The only downside is that people using the IPython/Qt event loop integration for things other than plotting (via `%gui qt`) might notice the change in behaviour because Qt timers etc won't fire until they create a QWidget somewhere. Realistically I think that's a tiny edge case, but to solve it properly would require `%pylab`/`matplotlib.pyplot` to set a flag that `%gui qt` wouldn't and then make the patch behaviour be conditional on that flag. I don't have time to do that now or shepherd through the resulting PR so I'm including the patch here for what it's worth.

**Comment by tacaswell** [comment] 2021-12-02 19:15
> The only downside is that people using the IPython/Qt event loop integration for things other than plotting 

I think it is a little worse, if people were sloppy and relied on IPython to create the qapplication from them, the first attempt at creating a a QWidget would abort their process.

That said, @pag can you open a PR to IPython with that patch (and ping me, I can help review / shepherd it through there).  A slightly simpler change may be to only process events if someone _else_ has created a QAppliaction and never have IPython create one.  I have in the past had the opposite view on this, but am starting to change my mind.

----


This is also `rcParams['figure.raise_window']`

```
#figure.raise_window : True    # Raise the GUI window to front when show() is called.
```

which will prevent new windows from stealing focus.

**Comment by pag** [comment] 2021-12-03 17:21
@tacaswell with the patch a QApplication is still created at the moment of GUI loop integration (i.e. the moment that you run `%gui qt` or `%pylab qt`) but no events are processed until a top-level QWidget exists, so nothing will crash here that didn't crash before. The dock icon is created at the point of QApplication creation, but it only steals focus when the event loop begins.

**Comment by tgy** [comment] 2022-02-01 15:07
hey! was a PR opened for that in IPython? if so, what's the link?

**Comment by tacaswell** [comment] 2022-04-30 22:09
There is at least an issue on the IPython side to track this https://github.com/ipython/ipython/issues/13617

**Comment by tacaswell** [comment] 2022-04-30 22:14
I am going to close this because:

1. the root cause of the recently discussed issue is how IPython manages the Qt event loop integration
2. we now have an rcparam to control if showing a figure takes focus or not
3. https://github.com/matplotlib/matplotlib/pull/22005 further defers when we do any GUI framework importing which should also help

**Closed by tacaswell** 2022-04-30 22:14 UTC
