### ISSUE TITLE
'Figure' object has no attribute '_original_dpi'

### ISSUE THREAD

**Issue by fariza** [matplotlib/matplotlib#9040] opened 2017-08-15 22:23 UTC
With current master, running any example

`python3 histogram_cumulative.py`

I get
```
Traceback (most recent call last):
  File "/home/fariza/workspace/matplotlib/lib/matplotlib/backends/backend_qt5agg.py", line 80, in paintEvent
    self._update_figure_dpi()
  File "/home/fariza/workspace/matplotlib/lib/matplotlib/backends/backend_qt5.py", line 186, in _update_figure_dpi
    dpi = self._dpi_ratio * self.figure._original_dpi
AttributeError: 'Figure' object has no attribute '_original_dpi'
Traceback (most recent call last):
  File "/home/fariza/workspace/matplotlib/lib/matplotlib/backends/backend_qt5agg.py", line 80, in paintEvent
    self._update_figure_dpi()
  File "/home/fariza/workspace/matplotlib/lib/matplotlib/backends/backend_qt5.py", line 186, in _update_figure_dpi
    dpi = self._dpi_ratio * self.figure._original_dpi
AttributeError: 'Figure' object has no attribute '_original_dpi'
```
It opens the window but the image is black

If I force to use a GTK3 backend I dont get the error and the figure is fine

**Comment by fariza** [comment] 2017-08-15 22:24
maybe related to #8052

**Comment by tacaswell** [comment] 2017-08-15 22:27
What sha are you at?

https://github.com/matplotlib/matplotlib/pull/9002 went in yesterday and may have fixed this.

**Comment by fariza** [comment] 2017-08-15 22:39
I just pulled from master (20 min ago)

**Comment by fariza** [comment] 2017-08-15 22:45
From `git rev-parse HEAD`
3769792fd4b8c8b8191c4bd1d49793b073996250

**Comment by tacaswell** [comment] 2017-08-16 00:02
I can not reproduce this, I assume it has something to do some subtle ordering in when things are created and when things are attempted to be drawn.

Does applying

```diff
20:00 $ git diff
diff --git a/lib/matplotlib/backends/backend_qt5agg.py b/lib/matplotlib/backends/backend_qt5agg.py
index 78d9fdada..85954c003 100644
--- a/lib/matplotlib/backends/backend_qt5agg.py
+++ b/lib/matplotlib/backends/backend_qt5agg.py
@@ -176,7 +176,7 @@ class FigureCanvasQTAggBase(FigureCanvasAgg):
         self.draw()
 
 
-class FigureCanvasQTAgg(FigureCanvasQTAggBase, FigureCanvasQT):
+class FigureCanvasQTAgg(FigureCanvasQT, FigureCanvasQTAggBase):
     """
     The canvas the figure renders into.  Calls the draw and print fig
     methods, creates the renderers, etc.
```

help?

**Comment by fariza** [comment] 2017-08-16 13:34
@tacaswell no, I change the order and it doesn't help.

The `FigureCanvasQT.__init__` its not being called.

I think `FigureCanvasQTAggBase` it's being called directly

**Comment by fariza** [comment] 2017-08-16 16:18
@tacaswell  if I make the change in `backend_qt4agg.py.FigureCanvasQTAgg` the error changes to
```
Traceback (most recent call last):
  File "/home/fariza/workspace/matplotlib/lib/matplotlib/backends/backend_qt5.py", line 309, in resizeEvent
    self.draw_idle()
  File "/home/fariza/workspace/matplotlib/lib/matplotlib/backends/backend_qt5agg.py", line 143, in draw_idle
    if not self._agg_draw_pending:
AttributeError: 'FigureCanvasQTAgg' object has no attribute '_agg_draw_pending'
```

Why it shows me the error in qt5? if it is qt4 in reality?

**Comment by tacaswell** [comment] 2017-08-16 23:37
Ah!  Because the qt4 backend is a sub-class of the qt5 backend.  The main differences between them are that qt5 is co-opperative and qt4 is not which mostly shows up in the `__init__` method.

**Comment by tacaswell** [comment] 2017-08-17 00:55
```python
import networkx
import matplotlib.backends.backend_qt4agg

def build_inheritance_graph(cls):
    g = networkx.DiGraph()
    todo = set([cls])
    done = set()

    while todo:
        cls = todo.pop()
        for b in cls.__bases__:
            if b not in done:
                todo.add(b)
            g.add_edge(cls.__name__, b.__name__)
    return g

g = build_inheritance_graph(matplotlib.backends.backend_qt5agg.FigureCanvas)
networkx.draw_networkx(g)
```

will give you a visualization of the MI diagram from these classes (there are 3 diamonds, 1 from us, 1 from Qt and 1 from us + Qt back to `object`).  At least on `__init__` is not being properly called on the Qt4 side.

**Comment by tacaswell** [comment] 2017-08-17 02:40
```python
def decorate_init(cls):

    for b in cls.mro():
        decorate(b)

            
def decorate(cls):
    print(cls.__name__)
    if cls is object:
        return

    if 'matplotlib' not in cls.__module__:
        return
    if '__init__' not in cls.__dict__:
        return
    
    orig_init = cls.__dict__['__init__']
    
    def new_init(self, *args, **kwargs):
        print(cls.__module__, cls.__name__)
        return orig_init(self, *args, **kwargs)
    
    cls.__init__ = new_init
 


decorate_init(matplotlib.backends.backend_qt4agg.FigureCanvas)
```

Will trace through what get called.

**Comment by tacaswell** [comment] 2017-08-17 02:40
I have a patch that _works_ but calls base class inits too many times....

**Comment by fariza** [comment] 2017-08-17 11:45
@tacaswell with the decorator
```
FigureCanvasQTAgg
FigureCanvasQTAggBase
FigureCanvasAgg
FigureCanvasQT
FigureCanvasQT
QWidget
QObject
QPaintDevice
Object
FigureCanvasBase
object
matplotlib.backends.backend_qt5agg FigureCanvasQTAggBase
matplotlib.backends.backend_qt4 FigureCanvasQT
matplotlib.backend_bases FigureCanvasBase
Traceback (most recent call last):
  File "/home/fariza/workspace/matplotlib/lib/matplotlib/backends/backend_qt5agg.py", line 80, in paintEvent
    self._update_figure_dpi()
  File "/home/fariza/workspace/matplotlib/lib/matplotlib/backends/backend_qt5.py", line 186, in _update_figure_dpi
    dpi = self._dpi_ratio * self.figure._original_dpi
AttributeError: 'Figure' object has no attribute '_original_dpi'
Traceback (most recent call last):
  File "/home/fariza/workspace/matplotlib/lib/matplotlib/backends/backend_qt5agg.py", line 80, in paintEvent
    self._update_figure_dpi()
  File "/home/fariza/workspace/matplotlib/lib/matplotlib/backends/backend_qt5.py", line 186, in _update_figure_dpi
    dpi = self._dpi_ratio * self.figure._original_dpi
AttributeError: 'Figure' object has no attribute '_original_dpi'
```

**Comment by fariza** [comment] 2017-08-22 11:53
https://github.com/matplotlib/matplotlib/pull/9052 solves this problem

**Comment by fariza** [comment] 2017-08-22 19:03
closed by https://github.com/matplotlib/matplotlib/pull/9052

**Comment by zerothi** [comment] 2017-10-11 20:52
In 2.1.0 I still see this problem, 

    python3 ...

and with the decorator shown above I get
```
FigureCanvasQTAgg
FigureCanvasQTAggBase
FigureCanvasAgg
FigureCanvasQT
FigureCanvasQT
QWidget
QObject
wrapper
QPaintDevice
simplewrapper
FigureCanvasBase
object
matplotlib.backends.backend_qt5agg FigureCanvasQTAggBase
matplotlib.backends.backend_qt5 FigureCanvasQT
matplotlib.backend_bases FigureCanvasBase
Traceback (most recent call last):
  File "/opt/python/3.6.3/packages/matplotlib/2.1.0/gnu-7.2.0/lib/python3.6/site-packages/matplotlib-2.1.0-py3.6-linux-x86_64.egg/matplotlib/backends/backend_qt5agg.py", line 68, in paintEvent
    self._update_figure_dpi()
  File "/opt/python/3.6.3/packages/matplotlib/2.1.0/gnu-7.2.0/lib/python3.6/site-packages/matplotlib-2.1.0-py3.6-linux-x86_64.egg/matplotlib/backends/backend_qt5.py", line 230, in _update_figure_dpi
    dpi = self._dpi_ratio * self.figure._original_dpi
AttributeError: 'Figure' object has no attribute '_original_dpi'
```
From the path above, you may also see versions used, pyqt is 5.9 (the latest).

**Comment by tacaswell** [comment] 2017-10-12 05:50
How did you install matplotlib?  Are you using pyqt4 or pyqt5?

**Comment by zerothi** [comment] 2017-10-12 06:35
Sorry about the 5.9, specification.

This is the print-out at installation:
```
 $> python3 setup.py build
Edit setup.cfg to change the build options

BUILDING MATPLOTLIB
            matplotlib: yes [2.1.0]
                python: yes [3.6.3 (default, Oct  9 2017, 08:51:47)  [GCC
                        7.2.0]]
              platform: yes [linux]

REQUIRED DEPENDENCIES AND EXTENSIONS
                 numpy: yes [version 1.13.3]
                   six: yes [using six version 1.11.0]
              dateutil: yes [using dateutil version 2.6.1]
backports.functools_lru_cache: yes [Not required]
          subprocess32: yes [Not required]
                  pytz: yes [using pytz version 2017.2]
                cycler: yes [using cycler version 0.10.0]
               tornado: yes [using tornado version 4.5.2]
             pyparsing: yes [using pyparsing version 2.2.0]
                libagg: yes [pkg-config information for 'libagg' could not
                        be found. Using local copy.]
              freetype: yes [version 2.8.1]
                   png: yes [version 1.6.32]
                 qhull: yes [pkg-config information for 'libqhull' could not
                        be found. Using local copy.]

OPTIONAL SUBPACKAGES
           sample_data: yes [installing]
              toolkits: yes [installing]
                 tests: no  [skipping due to configuration]
        toolkits_tests: no  [skipping due to configuration]

OPTIONAL BACKEND EXTENSIONS
                macosx: no  [Mac OS-X only]
                qt5agg: yes [installing, Qt: 5.7.1, PyQt: 5.7.1; PySide2 not
                        found]
                qt4agg: no  [PySide not found; PyQt4 not found]
               gtk3agg: no  [Requires pygobject to be installed.]
             gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                gtkagg: no  [Requires pygtk]
                 tkagg: yes [installing; run-time loading from Python Tcl /
                        Tk]
                 wxagg: no  [requires wxPython]
                   gtk: no  [Requires pygtk]
                   agg: yes [installing]
                 cairo: no  [cairocffi or pycairo not found]
             windowing: no  [Microsoft Windows only]

OPTIONAL LATEX DEPENDENCIES
                dvipng: no
           ghostscript: yes [version 9.20]
                 latex: yes [version 3.14159265]
               pdftops: yes [version 0.48.0]

OPTIONAL PACKAGE DATA
                  dlls: no  [skipping due to configuration]
```

**Comment by zerothi** [comment] 2017-10-12 06:48
I just noticed that in fact it _is_ using PyQt 5.9. If I do:
```
>>> import PyQt5.QtCore as q
>>> print(q.PYQT_VERSION_STR)
5.9
>>> print(q.QT_VERSION_STR)
5.7.1
```
So I guess there is a bug in the QT_VERSION_STR, I will try and report this to their mailing list.

**Comment by zerothi** [comment] 2017-10-12 06:53
Ahh, no, of course. QT is the parent library, while PYQT is the python wrapper qt.

**Comment by zerothi** [comment] 2017-10-12 06:56
In fact, I believe this to be a bug in `setupext.py`, it reads (@line 2077 and 2127)

```        
qt_version = QtCore.QT_VERSION
pyqt_version_str = QtCore.QT_VERSION_STR
```
while I guess it should read:
```        
qt_version = QtCore.QT_VERSION
pyqt_version_str = QtCore.PYQT_VERSION_STR
```

**Comment by dopplershift** [comment] 2017-10-17 19:53
I think you're right, would you submit a PR for that fix? Not sure what's going wrong with your original problem, unfortunately.

**Comment by tacaswell** [comment] 2017-12-18 20:06
@zerothi Do you still have this problem with 2.1.1?

**Comment by tacaswell** [comment] 2018-01-08 20:25
Closing as we can not reproduce this with 2.1.1.  Please ping to be re-opened if you can still reproduce this issue with the current stable release.

**Closed by tacaswell** 2018-01-08 20:25 UTC
Labels: GUI/Qt, Release critical, needs confirmation
