### ISSUE TITLE
gui backends do not work inside of flask request handlers

### ISSUE THREAD

**Issue by KayHS** [matplotlib/matplotlib#12612] opened 2018-10-24 09:19 UTC
### Bug report

**Bug summary**

Hi i am trying to plot an image using the plt.imshow() function.

**Code for reproduction**

```python

        base64_data = req.get("base64")
        decoded = Image.open(BytesIO(base64.b64decode(base64_data)))
        arr = cv2.cvtColor(np.array(decoded), cv2.COLOR_BGR2RGB)
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

        ret, threshold = cv2.threshold(gray, 100, 255, cv2.THRESH_BINARY)

        plt.axis("off")
        plt.imshow(image)
        plt.show()
```

**Actual outcome**

> 2018-10-24 10:11:40.636 python[69065:3191133] It does not make sense to draw an image when [NSGraphicsContext currentContext] is nil.  This is a programming error. Break on void _NSWarnForDrawingImageWithNoCurrentContext(void) to debug.  This will be logged only once.  This may break in the future.

**Expected outcome**

A plot with the image.

**Matplotlib version**
  * Operating system: macOS High Sierra version 10.13.3
  * Matplotlib version: ==3.0.0
  * Matplotlib backend TkAgg
  * Python version: 3.7
  * Other libraries: cv2, Flask

`pipenv install matplotlib
`

**Comment by QuLogic** [comment] 2018-10-24 09:34
> Matplotlib version: *

You left out the important bit.

Also, can you reproduce this _without_ OpenCV?

**Comment by KayHS** [comment] 2018-10-24 09:36
@QuLogic Updated my issue to include matplotlib version

**Comment by KayHS** [comment] 2018-10-24 10:09
@QuLogic Yes without CV

```
        base64_input = req.get("base64")

        im = Image.open(BytesIO(base64.b64decode(base64_input)))

        plt.axis("off")
        plt.imshow(im)
        plt.show()

```

**Comment by tacaswell** [comment] 2018-10-24 10:35
Which micro of python?

If you are using the TkAgg backend we are not directly interfacing with the coco event loop (but are doing so implicitly via tk).  What version of tcl/tk are you using and where did you install it from?

Can you try with a different backend ('macosx' or 'qt5agg')?

**Comment by KayHS** [comment] 2018-10-24 11:04
I did not install anything, i just added it like this. If it helps i am using pipenv.

`matplotlib.use('TkAgg')
`

**macosx**

```
import matplotlib
matplotlib.use('macosx')
import matplotlib.pyplot as plt
```

Error:

> ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
> I

**qt5agg**

```
import matplotlib
matplotlib.use('Qt5agg')
import matplotlib.pyplot as plt
```


Error:

>     raise ImportError("Failed to import any qt binding")
> ImportError: Failed to import any qt binding

**Comment by KayHS** [comment] 2018-10-24 11:14
After installing `pipenv install PyQt5`

and using it like this

```
import matplotlib
matplotlib.use('Qt5agg')
import matplotlib.pyplot as plt
```

I get the following error.

> WARNING: QApplication was not created in the main() thread.
> objc[73464]: Class QCocoaPageLayoutDelegate is implemented in both /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x10dc01260) and /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/PyQt5/Qt/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x12df7cf40). One of the two will be used. Which one is undefined.
> objc[73464]: Class QCocoaPrintPanelDelegate is implemented in both /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x10dc012d8) and /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/PyQt5/Qt/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x12df7cf90). One of the two will be used. Which one is undefined.
> objc[73464]: Class QCocoaApplicationDelegate is implemented in both /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x10dc00fe0) and /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x12dea2850). One of the two will be used. Which one is undefined.
> objc[73464]: Class QNSApplication is implemented in both /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x10dc00f90) and /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x12dea28a0). One of the two will be used. Which one is undefined.
> objc[73464]: Class QCocoaMenuLoader is implemented in both /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x10dc00f40) and /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x12dea2990). One of the two will be used. Which one is undefined.
> objc[73464]: Class QNSImageView is implemented in both /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x10dc01300) and /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x12dea2a80). One of the two will be used. Which one is undefined.
> objc[73464]: Class QNSStatusItem is implemented in both /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x10dc01350) and /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x12dea2ad0). One of the two will be used. Which one is undefined.
> objc[73464]: Class QNSOpenSavePanelDelegate is implemented in both /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/cv2/.dylibs/QtGui (0x10dc01120) and /Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x12dea2b70). One of the two will be used. Which one is undefined.
> 127.0.0.1 - - [24/Oct/2018 12:11:20] "POST /api/documents HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask_restful/__init__.py", line 273, in error_router
>     return original_handler(e)
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask/_compat.py", line 34, in reraise
>     raise value.with_traceback(tb)
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask_restful/__init__.py", line 273, in error_router
>     return original_handler(e)
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask/_compat.py", line 34, in reraise
>     raise value.with_traceback(tb)
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
>     resp = resource(*args, **kwargs)
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask/views.py", line 88, in view
>     return self.dispatch_request(*args, **kwargs)
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
>     resp = meth(*args, **kwargs)
>   File "/Users/username1/HelloSoda/vision/src/app/documents/resource.py", line 46, in post
>     plt.show()
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/matplotlib/pyplot.py", line 253, in show
>     return _show(*args, **kw)
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3266, in show
>     cls.mainloop()
>   File "/Users/username1/.local/share/virtualenvs/vision-nnmWanvH/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 1128, in mainloop
>     signal.signal(signal.SIGINT, signal.SIG_DFL)
>   File "/Users/username1/opt/homebrew/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py", line 47, in signal
>     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
> ValueError: signal only works in main thread
> Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree), function NSViewSetCurrentlyBuildingLayerTreeForDisplay, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1561.20.106/AppKit.subproj/NSView.m, line 14480.

**Comment by tacaswell** [comment] 2018-10-24 11:19
Does that code work when not run inside of flask (aka on threads)?  

I suspect the problem is that GUIs (as a general rule) insist that they be run on t he main thread of the application (for their own reasons).  I suspect that that is the underlying problem (which is unfortunately not one we can fix).

**Comment by tacaswell** [comment] 2018-10-24 11:20
I took the liberty of updating the issue title, hope you do not mind.

**Comment by KayHS** [comment] 2018-10-24 11:34
@tacaswell 

Yep, i can confirm without flask it works fine.

```
from PIL import Image
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt

im = Image.open("original.png")

plt.axis("off")
plt.imshow(im)
plt.show()

```
 I don't know how to solve this problem with Flask, i guess i should create a ticket over there?

**Comment by tacaswell** [comment] 2018-10-24 12:07
@KayHS I am going to close this on the Matplotlib side.

I do not think this _can_ be solved due to the constraints imposed from the GUI frameworks.  I am also not sure you really want to solve this.  While it would be convenient for debugging, in production if you ran this with no one looking at it you would start to accumulate many open GUI windows and eventually exhaust your system resources!

**Closed by tacaswell** 2018-10-24 12:07 UTC
