### ISSUE TITLE
Feature Request: Allow the user to turn off the clipping mask when saving pdfs

### ISSUE THREAD

**Issue by breedlun** [matplotlib/matplotlib#2528] opened 2013-10-17 14:59 UTC
My usual workflow is to generate a plot using matplotlib, save the plot as a pdf using savefig(), and then open the plot in Adobe Illustrator to do final tweaking. Every pdf created by matplotlib has a clipping mask around the border of the content. I find it a bit tedious to always release the clipping mask and then delete the clipping bounding box before I begin adjusting my pdf. It would be nice if there were an option to eliminate the clipping box.

To make this more concrete, here is an example,

```
import matplotlib.pylab as plt
fig = plt.figure(figsize = (5,5))
ax = plt.subplot(111)
ax.plot([0,1], [0,1])
plt.savefig('Test.pdf')
```

which creates a pdf with a clipping mask around the outside edges, even though there is nothing to clip.

**Comment by atarashansky** [comment] 2019-12-20 07:12
Any updates on this? I like sizing my figures such that the axes are specific sizes as opposed to the figure itself. To do this, I use `figure.set_fig_size(...)` in conjunction with `figure.adjust_subplots(top=1,bottom=0,right=1,left=0)`. But having to go into the pdf and manually remove the clipping mask to show the axes labels and  tick-marks is really cumbersome and prevents me from being able to link my images in my illustrator files. 

I  tried setting all clipping off for all artists using `.set_clip_on(False)` but that seems to have no effect.

**Comment by anntzer** [comment] 2019-12-20 12:40
Is that something that can be checked without having access to illustrator?

**Comment by breedlun** [comment] 2019-12-21 01:40
I bet you could check whether a figure has a clipping box with Inkscape, the free, open-source, alternative to Illustrator.

**Comment by atarashansky** [comment] 2019-12-21 01:51
I should have updated my comment instead of deleting the message -- I messed up. I just realized you could save the figure with `bbox_inches='tight'` and it fixes the clipping situation. Sorry about that! This issue should be closed.

Best,
Alec

**Comment by anntzer** [comment] 2019-12-21 10:48
I'm not sure how to check this directly with inkscape, but opening the pdf with inkscape and right-clicking on it shows the "release clip" menu item grayed out and the "set clip" menu item active, so I'd guess there's no clipbox on it?

**Comment by breedlun** [comment] 2019-12-21 18:34
@atarashansky, I do not agree that the original issue is resolved when I use `bbox_inches='tight'`.   When I do the following
```
import matplotlib.pylab as plt
fig = plt.figure(figsize = (5,5))
ax = plt.subplot(111)
ax.plot([0,1], [0,1])
plt.savefig('Test-tight.pdf', bbox_inches = 'tight')
```
the clipping mask tightly wraps around the plot, which is good in some circumstances, but the clipping mask remains.  If I open the PDF in Adobe Illustrator, I have to remove the clipping mask around the plot before I can edit anything.  The clipping mask is not needed, in my opinion, since it is not actually clipping any artwork.

In case it matters, I am using matplotlib 2.2.3.

**Comment by breedlun** [comment] 2019-12-29 16:34
@anntzer, I just installed Inkscape.  I can confirm that the pdf opens in Inkscape without a clipping mask (as far as I can tell).  The same pdf, however, has a clipping mask in Adobe Illustrator.  I am not sure why these two applications treat the same pdf differently.

**Comment by anntzer** [comment] 2019-12-29 18:53
Thanks for checking.

**Comment by QuLogic** [comment] 2020-03-09 00:12
Using `pdfinfo` from Poppler, you can get some boxes:
```
$ pdfinfo -box Test.pdf 
Creator:        matplotlib 3.2.0rc2.post1692+gff927bb65, http://matplotlib.org
Producer:       matplotlib pdf backend 3.2.0rc2.post1692+gff927bb65
CreationDate:   Sun Mar  8 20:09:34 2020 EDT
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      360 x 360 pts
Page rot:       0
MediaBox:           0.00     0.00   360.00   360.00
CropBox:            0.00     0.00   360.00   360.00
BleedBox:           0.00     0.00   360.00   360.00
TrimBox:            0.00     0.00   360.00   360.00
ArtBox:             0.00     0.00   360.00   360.00
File size:      5596 bytes
Optimized:      no
PDF version:    1.4
```

I guess it's `CropBox` you'd want to remove? Can you run `pdfinfo` on the 'fixed' one in Illustrator to see what effect removing the clipping mask has?

**Comment by breedlun** [comment] 2020-03-10 03:42
At @QuLogic's suggestion, I ran 
```
import matplotlib.pylab as plt
fig = plt.figure(figsize = (5,5))
ax = plt.subplot(111)
ax.plot([0,1], [0,1])
plt.savefig('Test.pdf')
```
and then I used `pdfinfo` to get
```
$ pdfinfo -box Test.pdf
Creator:        matplotlib 2.2.3, http://matplotlib.org
Producer:       matplotlib pdf backend 2.2.3
CreationDate:   Mon Mar  9 21:25:34 2020 MDT
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      360 x 360 pts
Page rot:       0
MediaBox:           0.00     0.00   360.00   360.00
CropBox:            0.00     0.00   360.00   360.00
BleedBox:           0.00     0.00   360.00   360.00
TrimBox:            0.00     0.00   360.00   360.00
ArtBox:             0.00     0.00   360.00   360.00
File size:      5550 bytes
Optimized:      no
PDF version:    1.4
```
Then, I opened the pdf in Adobe Illustrator, deleted the clipping mask (even though it was not actually clipping any artwork), saved the file as `Test2.pdf`, and used `pdfinfo` to get:
```
$ pdfinfo -box Test2.pdf
Title:          Test2
Creator:        Adobe Illustrator CS4
Producer:       Adobe PDF library 9.00
CreationDate:   Mon Mar  9 21:27:10 2020 MDT
ModDate:        Mon Mar  9 21:27:10 2020 MDT
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      360 x 360 pts
Page rot:       0
MediaBox:           0.00     0.00   360.00   360.00
CropBox:            0.00     0.00   360.00   360.00
BleedBox:           0.00     0.00   360.00   360.00
TrimBox:            0.00     0.00   360.00   360.00
ArtBox:            22.75    24.88   324.40   317.20
File size:      58362 bytes
Optimized:      no
PDF version:    1.5
```
Clearly, the ArtBox changed size.  To take this a bit further, I also adjusted the canvas in Adobe Illustrator, saved the resulting file as `Test3.pdf`, and did `pdfinfo` again to get
```
$ pdfinfo -box Test3.pdf
Title:          Test3
Creator:        Adobe Illustrator CS4
Producer:       Adobe PDF library 9.00
CreationDate:   Mon Mar  9 21:27:31 2020 MDT
ModDate:        Mon Mar  9 21:27:31 2020 MDT
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      339.5 x 327 pts
Page rot:       0
MediaBox:           0.00     0.00   339.50   327.00
CropBox:            0.00     0.00   339.50   327.00
BleedBox:           0.00     0.00   339.50   327.00
TrimBox:            0.00     0.00   339.50   327.00
ArtBox:            22.75    15.38   324.40   307.70
File size:      64220 bytes
Optimized:      no
PDF version:    1.5
```
This time the Mediabox, CropBox, Bleedbox, TrimBox, and ArtBox all changed size.

**Comment by QuLogic** [comment] 2020-03-11 07:36
Unfortunately, I'm not sure there's much Matplotlib can do here. The only thing it sets for a page is `MediaBox`:
https://github.com/matplotlib/matplotlib/blob/50242cff1bf419464b22a642768ecdc552b84907/lib/matplotlib/backends/backend_pdf.py#L564-L573
Looking at the spec, `CropBox` defaults to `MediaBox`, and `BleedBox`, `TrimBox` and `ArtBox` default to `CropBox`. Maybe Illustrator is just deciding things based on whether they're defaults, or some non-standard option.

You can also verify this by setting `plt.rcParams['pdf.compression'] = False` and running your example. This allows you to read the file directly, and the only mention of `Box` is `MediaBox` and some `FontBBox`. There is only one clipping operation (`W`), which appears to be a smaller rectangle and probably is the `Axes`. In the above example, the size is 360 points and the only other mention of 360 is a path that winds around the figure. Actually, are you sure the clipping mask is not just the figure background?

**Comment by breedlun** [comment] 2020-03-14 16:40
@QuLogic, yes, I am certain the clipping mask is not the figure background.  I open the the `test.pdf` file in Illustrator and I cannot click on anything within the clipping mask until I have released the clipping mask.  The screen shot below shows how I must release the clipping mask.

![Illustrator_Clipping_Mask](https://user-images.githubusercontent.com/4099759/76686259-bf4f9e80-65df-11ea-807d-1a42ff58f8d3.jpeg)

**Comment by dtexwang** [comment] 2020-05-22 15:09
> @QuLogic, yes, I am certain the clipping mask is not the figure background. I open the the `test.pdf` file in Illustrator and I cannot click on anything within the clipping mask until I have released the clipping mask. The screen shot below shows how I must release the clipping mask.
> 
> ![Illustrator_Clipping_Mask](https://user-images.githubusercontent.com/4099759/76686259-bf4f9e80-65df-11ea-807d-1a42ff58f8d3.jpeg)

Can confirm @breedlun's findings w.r.t. Illustrator.  I have had the same inconvenience with matplotlib since I began using it in 2012.

**Comment by jklymak** [comment] 2020-05-22 15:38
We aren't actively creating the clipping mask, so someone will have to figure out how to stop Illustrator from thinking we did.

**Comment by PhillipMaire** [comment] 2022-12-22 00:51
has there been any progress on this? I am making figures for a scientific paper and I have to do a lot of extra work to get around this. I understand this may not be possible to fix but just curious since it's been 2 years since the last comment. Also a side note and maybe a less pretty fix could be to delete data outside of the current legend limits. pass in the figure handle and let a function remove all the data outside of the axes (or custom set limits passed in). the clipping masks would still be there but those can easily be deleted in illustrator, the issue really lies in the extra data (at least for me). not sure how hard this would be with things with shading like KDE plots. just a thought.

**Comment by oscargus** [comment] 2022-12-22 11:40
From my understanding, the problem is that we do not add a clip mask, but Illustrator somehow thinks we did. (It is also interesting to note that the example PDF is about 10 times larger after passing through Illustrator...)

Maybe it can be worth trying adding the other boxes as well to see if that makes Illustrator behave differently. Not sure if any dev have access to Illustrator though... It could be that Illustrator guesses that there is a clipping mask if not a specific box is defined? (Or something completely different...)

This would basically be to add lines of the type:
```
'MediaBox': [0, 0, 72 * width, 72 * height], 
```
but for different boxes, rerun the code and see if it changes Illustrators behavior.

**Comment by tacaswell** [comment] 2022-12-22 18:26
If you do `fig.set_clip_on(False)` does it make any difference?

Am I understanding correctly that this an Illustrator only issue?  Has anyone opened a support ticket with them?

Could someone who is having this problem do `plt.rcParams['pdf.compression'] = False` and then start removing lines until the problem is solved?  Know exactly which part of the pdf is triggering this behavior would be very helpful for us to sort out where in Matplotlib (if anywhere) we are emitting it.

**Comment by PhillipMaire** [comment] 2022-12-22 18:44
```
np.random.seed(42)
x = np.random.rand(100)
y = np.random.rand(100)
fig, ax = plt.subplots(2, 2)
fig.set_clip_on(False)
ax[1, 0].scatter(x, y)
ax[1, 0].set_ylim(0, .5)
ax[1, 0].set_xlim(0, .5)

bd = '/Users/phil/Desktop/untitled folder/'
plt.savefig(bd+'tmp2.pdf', transparent=True, format='pdf')
```
this produces a plot like this 
<img width="537" alt="0 1 0 2 0 3 0 4" src="https://user-images.githubusercontent.com/19584564/209204624-5ce32d3e-9f82-4333-804c-ddadac405ddd.png">

which is expected, when I open in illustrator it looks the same. 
but when I delete the clipping mask it looks like this and all the data pours over into the rest of the space. like this.
<img width="515" alt="0 2 0 4" src="https://user-images.githubusercontent.com/19584564/209204782-d3ac4a38-f486-45db-9a0b-090c65c65d74.png">

**Comment by PhillipMaire** [comment] 2022-12-22 18:49
some other useful things to note, 

- the only clipping mask that matters is the one that matches the plot axis in the plot. also lets say I plotted to times e.g. `plt.plot(x, 'r')` and `plt.plot(x, 'b')` then there would be 2 clipping masks for each ones that match the axis of the plot. 

- there is technically clipping masks on each dot as seen on this picture, although they don't seem to be doing anything. (I selected Select>Object>Clipping Masks) 
<img width="742" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/19584564/209205368-e8ce3471-609a-41f8-994a-be6a3611177d.png">

**Comment by PhillipMaire** [comment] 2022-12-22 18:59
> Could someone who is having this problem do `plt.rcParams['pdf.compression'] = False` and then start removing lines until the problem is solved? Know exactly which part of the pdf is triggering this behavior would be very helpful for us to sort out where in Matplotlib (if anywhere) we are emitting it.

I am not sure exactly what you mean by this? do you mean delete lines in matplotlib prior to saving PDF or in illustrator? here is what I have tested 
```
np.random.seed(42)
fig, ax = plt.subplots(2, 2)
ax[1, 0].set_ylim(0, .5)
ax[1, 0].set_xlim(0, .5)

bd = '/Users/phil/Desktop/untitled folder/'
plt.savefig(bd+'tmp4.pdf', transparent=True, format='pdf')
```
this does not create any clipping masks, which means that it is not associated with figure creation or setting x or y limits. Since the number of (axis based) clipping masks equals the number times we use plt.plot (or similar) then I would assume it would be associated with this. I am happy to read figures in illustrator if people want to test advanced things. 

one thought for those of you who know matplotlib well, is there any way to save a figure the line after the each major step in the plotting process? maybe even before it becomes visible and I can test those file and maybe this will narrow it down?

**Comment by breedlun** [comment] 2022-12-30 00:51
As far as I can tell, the issue in my original post (back in 2013) is now resolved.  If I execute the code in my original post using Matplotlib 3.5.1 and open Test.pdf in Adobe Illustrator 2022, then I do not find a clipping mask as I showed in my March 14th, 2020 post.  

As far as I can tell, @PhillipMaire is bringing up a different issue: he does not like the clipping mask around the axes.  I did not like the clipping mask for the whole figure, but that clipping mask is now gone.  I, therefore, think this ticket can be closed and @PhillipMaire should start up a new ticket.

**Comment by tacaswell** [comment] 2023-01-05 00:56
@PhillipMaire I mean edit the pdf.  If it is not compressed you can open it with a text editor and hack at it 😄 .  If you then re-load it in illustrator (or any pdf viewer) you can see the effects of your change. 

If you do not want to clip a particular Artist, the call `obj.set_clipon(False)` on it, eg:

```python
fig, ax = plt.subplots()
ln, = ax.plot(range(5))
ln.set_clipon(False)
fig.savefig('test.pdf')
```

but that will result in all of the data, even that being outside of the limits, being visible.  This is the expected behavior and for the vector backends we rely on adding clip boxes to let the renderer do the final clipping (e.g. for scatter we emit a bunch of circles and do not try to output a half circle if the marker is on the edge).  If you want to mask your data to the range you care about you have to do that before you pass it in to Matplotlib.

I agree with @breedlun I'm going to close this because the original issue is closed and the @PhillipMaire is describing what I think is the expected behavior.  Please open a new issue explaining what is not working for you.

**Closed by tacaswell** 2023-01-05 00:56 UTC
Labels: New feature, backend: pdf
