### ISSUE TITLE
plot_date() ignores timezone

### ISSUE THREAD

**Issue by timtroendle** [matplotlib/matplotlib#5575] opened 2015-11-27 18:15 UTC
Using matplotlib 1.5.0, I am doing the following:
```python
import pytz
import matplotlib.pyplot as plt
from datetime import datetime
time_index = [pytz.timezone('Europe/Berlin').localize(datetime(year=2015, month=11, day=27, hour=x)) for x in range(4)]
plt.plot_date(time_index, [4]*4, tz='Europe/Berlin')
plt.plot_date(time_index, [4]*4, tz='UTC')
```
The two ``plot_date`` calls yield the same plot, hence it seems ``plot_date()`` ignores the ``tz`` argument. This had been reported and fixed in #193, but for me it doesn't seem to work.

**Comment by mdboom** [comment] 2015-11-27 18:21
Might be a dupe of #5543.

**Comment by brendene** [comment] 2015-11-28 03:50
Fixing #5543 is a prerequisite to fixing this bug however there still exists another bug.

In matplotlib/axis.py update_units is called 3 times.  First from _base.py:_xy_from_xy where the single parameter passed in is the time_index above.  This sets Axis.units to 'Europe/Berlin'.

The second time is on the y-axis, ignore this one.

The third time is from the plot_date which calls xaxis_date.  Since Axis.units was already set to 'Europe/Berlin', it will not be set to the 'UTC' which was passed in.

Calling self.set_units(default) regardless of whether or not Axis.units is None fixes the issue above but probably isn't the most efficient.  I will continue reading through the code but I don't know it well enough yet to make a proper fix.

As for why there is also a dependency on #5543, making the above fix will fix it for the example above.  However, a subsequent call to plot_date using tz='US/Eastern' will still plot in UTC.

**Closed** 2016-03-13 20:53 UTC

**Comment by pjadzinsky** [comment] 2016-12-18 22:08
Hi,

I just upgraded to 1.5.3 and I still see the same behavior as originaly described by timtroendle

**Comment by tacaswell** [comment] 2016-12-19 05:01
@pjadzinsky can you make a new issue for this?
