### ISSUE TITLE
Saving a pdf, with a single image, grayscale colormap, and transparent background produces a black background

### ISSUE THREAD

**Issue by Stretch97** [matplotlib/matplotlib#4260] opened 2015-03-22 16:28 UTC
This issue appears to be similar to what eventually got resolved in https://github.com/matplotlib/matplotlib/pull/1894

If I save a pdf with a single image, grayscale colormap and a transparent background, the axes background does not remain transparent.  It becomes a black background.  If I deviate from any of those ingredients, then the background is transparent as specified.

Example:

    import matplotlib.pyplot as plt
    from numpy.random import rand
    
    fig, ax = plt.subplots(nrows=3, ncols=1, sharex=True)
    
    ax[0].imshow(rand(15,15), extent=[0, 2, 15, 0], \
                cmap=plt.cm.gray, aspect='auto', interpolation='Nearest')
            
    ax[1].imshow(rand(15,15), extent=[0, 2, 15, 0], \
                cmap=plt.cm.rainbow, aspect='auto', interpolation='Nearest')

    ax[2].imshow(rand(15,15), extent=[0, 2, 15, 0], \
                cmap=plt.cm.gray, aspect='auto', interpolation='Nearest')
    ax[2].imshow(rand(15,15), extent=[4, 6, 15, 0], \
                cmap=plt.cm.gray, aspect='auto', interpolation='Nearest')

    ax[-1].set_xlim([0, 8])
    fig.savefig('transparent.pdf', format='PDF', transparent = True)
    fig.savefig('opaque.pdf', format='PDF', transparent = False)
    fig.savefig('transparent.png', format='PNG', transparent = True)

Here is 'transparent.pdf', with the black background on the first set of axes:
![transparent-pdf](https://cloud.githubusercontent.com/assets/4099759/6770161/e5545712-d07d-11e4-9bb1-05bf047a87ba.png)

Here is 'opaque.pdf', which looks correct:
![opaque-pdf](https://cloud.githubusercontent.com/assets/4099759/6770166/022ea176-d07e-11e4-9f17-eeb629fbdfed.png)

Here is 'transparent.png', which also looks correct:
![transparent](https://cloud.githubusercontent.com/assets/4099759/6770171/17c3a932-d07e-11e4-9efc-fcbc581d1a95.png)

In case it matters, I am on Mac OS X 10.8.5, Enthought Canopy Python 2.7.6, and Matplotlib 1.4.0

**Comment by dkua** [comment] 2015-03-23 16:46
Can confirm that this also occurs on 

Mac OS X 10.9.5, Python 2.7.9, matplotlib 1.4.3
and
Ubuntu 12.04 LTS, Python 2.7.3, matplotlib 1.4.3

**Comment by jkseppan** [comment] 2015-07-17 11:35
I recently fixed one bug related to alpha channels in grayscale images, and I cannot reproduce this problem on current master, so I'll assume the fix helped with this case too. Thanks for a clearly written report, and please feel free to reopen if this reappears.

**Closed by jkseppan** 2015-07-17 11:35 UTC
Labels: Alpha color, backend/pdf

**Comment by breedlun** [comment] 2020-10-20 23:21
I can confirm the issue is gone now.  Thanks to @jkseppan.
