### ISSUE TITLE
[Bug]: Suptitle not working with `plt.subfigures()` whithout 'constrained' layout.

### ISSUE THREAD

**Issue by Miguel-LlamasLanza** [matplotlib/matplotlib#25514] opened 2023-03-20 16:42 UTC
### Bug summary

The suptitle of the figure does not show if using plt.subfigures, without defining layout to be 'constrained'.

### Code for reproduction

```python
fig = plt.figure(figsize=(20, 14))
subfigs = fig.subfigures(1, 4, wspace=0.5, width_ratios=[0.5, 1, 1, 1])

axs0= subfigs[0].subplots(nrows = 12, ncols = 1, sharex = True)
axs1 = subfigs[1].subplots(nrows = 12, ncols = 1, sharex = True)
subfigs[1].suptitle('\n A subfigure')

axs2 = subfigs[2].subplots(nrows = 12, ncols = 1, sharex = True)
subfigs[2].suptitle('\n A subfigure')

axs3 = subfigs[3].subplots(nrows = 12, ncols = 1, sharex = True)
subfigs[3].suptitle('\n A subfigure')
```

### Actual outcome

![image](https://user-images.githubusercontent.com/64196642/226391637-ccb126ff-c20e-4fbd-8fda-f6e599942c75.png)

### Expected outcome

A title should be given on top of the figure

### Operating system

Ubuntu

### Matplotlib Version

3.6.2

### Matplotlib Backend

Qt5Agg

### Python version

3.10.9

### Installation

conda

**Comment by rcomer** [comment] 2023-03-20 17:05
Thanks @Miguel-LlamasLanza.  I think this may be a duplicate of #24910.  That was addressed by changing subfigures to be transparent by default, and the change will appear in version 3.8.

**Closed** 2023-03-20 17:31 UTC

**Comment by Miguel-LlamasLanza** [comment] 2023-03-20 18:08
Thank you. Changing the subfigures to be transparent seems to work as a workaround until its solved
