### ISSUE TITLE
[Bug]: Showing lines as patches in legend using handler_map raises NotImplementedError

### ISSUE THREAD

**Issue by carlosgmartin** [matplotlib/matplotlib#25148] opened 2023-02-03 20:45 UTC
### Bug summary

I want lines to be shown as patches in my legends, as a global default. Based on the [legend guide](https://matplotlib.org/stable/tutorials/intermediate/legend_guide.html), I wrote the following code, but [patches.Patch.get_path](https://github.com/matplotlib/matplotlib/blob/v3.6.3/lib/matplotlib/patches.py#L597) raises `NotImplementedError: Derived must override`.

### Code for reproduction

```python
from matplotlib.legend import Legend
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

class ToPatch:
    def legend_artist(legend, orig_handle, fontsize, handlebox):
        patch = Patch(
            color=orig_handle.get_color(),
            label=orig_handle.get_label(),
        )
        handlebox.add_artist(patch)
        return patch

Legend.update_default_handler_map({Line2D: ToPatch})

import numpy as np
from matplotlib import pyplot as plt

fig, ax = plt.subplots()
x = np.linspace(-2, 2)
ax.plot(x, x, label='linear')
ax.plot(x, x ** 2, label='quadratic')
ax.legend()
# ax.legend(handles=ax.get_legend().legendHandles)
plt.show()
```

### Actual outcome

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 1193, in _on_timer
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/backends/backend_macosx.py", line 68, in callback_func
    callback()
  File "/usr/local/lib/python3.10/site-packages/matplotlib/backends/backend_macosx.py", line 88, in _draw_idle
    self.draw()
  File "/usr/local/lib/python3.10/site-packages/matplotlib/backends/backend_macosx.py", line 50, in draw
    super().draw()
  File "/usr/local/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 405, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/figure.py", line 3082, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.10/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3100, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.10/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/legend.py", line 649, in draw
    self._legend_box.draw(renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/offsetbox.py", line 366, in draw
    c.draw(renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/offsetbox.py", line 366, in draw
    c.draw(renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/offsetbox.py", line 366, in draw
    c.draw(renderer)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.10/site-packages/matplotlib/offsetbox.py", line 683, in draw
    c.draw(renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/patches.py", line 585, in draw
    path = self.get_path()
  File "/usr/local/lib/python3.10/site-packages/matplotlib/patches.py", line 599, in get_path
    raise NotImplementedError('Derived must override')
NotImplementedError: Derived must override
```

### Expected outcome

If I uncomment the commented line (which calls `ax.legend` a second time), I get the expected output:

![image](https://user-images.githubusercontent.com/8883917/216706741-9c4cf61a-e99a-4daa-8a19-909bd9e89481.png)

### Operating system

macOS 11.7.3

### Matplotlib Version

3.6.3

### Matplotlib Backend

MacOSX

### Python version

3.10.9

### Installation

pip

**Comment by ksunden** [comment] 2023-02-03 21:07
This is expected behavior.

Patch is as a base class that is not sufficient to actually draw directly on to the screen (hence the `NotImplementedError`)

Note that the `legend_handler.HandlerPatch` which will accept generic patches actually uses a [Rectangle](https://github.com/matplotlib/matplotlib/blob/c23ccdde6f0f8c071b09a88770e24452f2859e99/lib/matplotlib/legend_handler.py#L334) as the concrete patch that is drawn (at least as a fallback).

You may wish to start there, by using Rectangle instead of Patch.

**Comment by ksunden** [comment] 2023-02-03 21:25
One more note is that the handler_map should be an instance of your handler (rather than the class itself):

```python
Legend.update_default_handler_map({Line2D: ToPatch()})
```

Note the parentheses.

Upon further inspection you actually have two opposing oddities that cancel each other out, usually the `legend_artist` method includes `self` as the first argument (but when the class is there it is not the bound method and thus it was actually getting the right thing, but for consistency, `self` should be included and an instance passed instead of the class)

I tried just doing:

```python
Legend.update_default_handler_map({Line2D: HandlerPatch})
```

i.e. using the default patch handler for Line2D. This did not work because Line2D does not have an edge color, and that handler expects the edge color.


This should be just about what you want:

```python

from matplotlib.legend import Legend
from matplotlib.lines import Line2D
from matplotlib.patches import Rectangle
from matplotlib.legend_handler import HandlerBase

class ToPatch:
    def legend_artist(self, legend, orig_handle, fontsize, handlebox):
        x0, y0 = handlebox.xdescent, handlebox.ydescent
        patch = Rectangle(
            (x0, y0), handlebox.width, handlebox.height,
            color=orig_handle.get_color(),
            label=orig_handle.get_label(),
        )
        handlebox.add_artist(patch)
        return patch

Legend.update_default_handler_map({Line2D: ToPatch()})

import numpy as np
from matplotlib import pyplot as plt

fig, ax = plt.subplots()
x = np.linspace(-2, 2)
ax.plot(x, x, label='linear')
ax.plot(x, x ** 2, label='quadratic')
ax.legend()
# ax.legend(handles=ax.get_legend().legendHandles)
plt.show()
```

Closing as I don't think there is any action to be taken on our part, but hopefully you have enough to get where you want.

**Closed by ksunden** 2023-02-03 21:25 UTC
