### ISSUE TITLE
matplotlib imshow raise a warning

### ISSUE THREAD

**Issue by Interesting6** [matplotlib/matplotlib#16499] opened 2020-02-13 16:37 UTC
### Bug report: 

**Bug summary**
when use pot.imshow(img), it warn me the following:
2020-02-13 23:39:40.053 python3.7[35963:14500628] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (62.11 secs)

**Code for reproduction**

```python
# Paste your code here
a = np.ones(30, 50)
plt.imshow(a, cmap='gray')
plt.show()
```

**Actual outcome**
normal, but it freezes my mac 2-3 seconds

```
# If applicable, paste the console output here
In [14]: plt.imshow(a, cmap='gray')
Out[14]: <matplotlib.image.AxesImage at 0x11b7f4cf8>

In [15]: 2020-02-13 23:37:50.248 python3.7[35963:14500628] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (333.00 secs).
In [15]: plt.show()
```

**Expected outcome**

**Matplotlib version**

  * Operating system: High Sierra 10.13.6
  * Matplotlib version:  3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.0
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: 

brew install python   and pip install matplotlib   

pip resource: http://pypi.douban.com/simple

**Comment by tacaswell** [comment] 2020-02-13 17:02
Does this persist with v3.1.x?

**Comment by Interesting6** [comment] 2020-02-25 10:35
> Does this persist with v3.1.x?

yes, I just upgrade my matplotlib to version 3.1.3
the warns changed:

> 2020-02-25 18:33:21.995 Python[39126:11367781] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (8.27 secs).
2020-02-25 18:33:21.995 Python[39126:11367781] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (7.07 secs).
2020-02-25 18:33:21.995 Python[39126:11367781] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (6.40 secs).

**Comment by dstansby** [comment] 2021-04-05 08:52
Is this still happening in more recent versions of matplotlib (3.3.x or 3.4.x)?

**Comment by greglucas** [comment] 2022-03-13 21:09
Closing as I can't reproduce this with newer versions. Feel free to reopen if you are still having issues with more recent versions of Matplotlib.

**Closed by greglucas** 2022-03-13 21:09 UTC
Labels: OS/Apple, GUI/tk
