### ISSUE TITLE
ValueError: Key backend: '' is not a valid value for backend

### ISSUE THREAD

**Issue by pllim** [matplotlib/matplotlib#19848] opened 2021-04-01 22:41 UTC
### Bug report

I am actually not sure if this is a bug. It started happening today for `matplotlib` installed from your `master` branch for our CI. We run some [image tests using your dev version on CircleCI](https://github.com/astropy/astropy/blob/ef31833d826374721a727ad9c427124ffaf693d2/.circleci/config.yml#L38-L50), which uses [our tox.ini](https://github.com/astropy/astropy/blob/master/tox.ini) and some settings in [astropy/conftest.py](https://github.com/astropy/astropy/blob/master/astropy/conftest.py).

It starts to complain about no backend even though we set it at [astropy/conftest.py#L84](https://github.com/astropy/astropy/blob/ef31833d826374721a727ad9c427124ffaf693d2/astropy/conftest.py#L84) and that works for older versions of `matplotlib`.

```
INTERNALERROR>   File ".../matplotlib/__init__.py", line 843, in <module>
INTERNALERROR>     fail_on_error=True)
INTERNALERROR>   File ".../matplotlib/__init__.py", line 773, in _rc_params_in_file
INTERNALERROR>     config[key] = val  # try to convert to proper type or raise
INTERNALERROR>   File ".../matplotlib/__init__.py", line 607, in __setitem__
INTERNALERROR>     raise ValueError(f"Key {key}: {ve}") from None
INTERNALERROR> ValueError: Key backend: '' is not a valid value for backend; supported values are
['GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo',
'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
```

**Code for reproduction**

We can reproduce it on both GitHub Actions and CircleCI using tox + pytest but only with the dev version of matplotlib.

**Actual outcome**

See traceback above.

**Expected outcome**

It does not throw `ValueError`.

**Matplotlib version**

  * Operating system: Ubuntu on Actions, some Linux image on CircleCI
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): matplotlib @ git+https://github.com/matplotlib/matplotlib.git@cc8669fc69b0cc618336a17d324f5fdbf1922f22 (reported by CircleCI)
  * Matplotlib backend (`print(matplotlib.get_backend())`): Agg but somehow not registering (see above)
  * Python version: 3.7
  * Jupyter version (if applicable): N/A
  * Other libraries: There is a list on [CircleCI log under pip freeze](https://app.circleci.com/pipelines/github/astropy/astropy/4490/workflows/6451c29d-5f29-4ab4-a66f-12ca078f0ca5/jobs/86017)

Also, the [Actions log](https://github.com/astropy/astropy/runs/2246637843?check_suite_focus=true).

xref astropy/astropy#11458

**Comment by QuLogic** [comment] 2021-04-01 23:09
Probably related to #19603

**Comment by pllim** [comment] 2021-04-02 14:38
@QuLogic , what does that mean for downstream setup? Do we have to completely change the way we set backend for CI? Can you please advise? Thanks!

**Comment by ianhi** [comment] 2021-04-02 14:55
I ran into this yesterday as well and opened: https://github.com/matplotlib/pytest-mpl/issues/117

For me this was failing just from using pytest-mpl before getting to any tests:
```
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/pytest_mpl/plugin.py", line 124, in pytest_report_header
INTERNALERROR>     import matplotlib
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/matplotlib/__init__.py", line 840, in <module>
INTERNALERROR>     rcParamsDefault = _rc_params_in_file(
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/matplotlib/__init__.py", line 774, in _rc_params_in_file
INTERNALERROR>     config[key] = val  # try to convert to proper type or raise
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/matplotlib/__init__.py", line 608, in __setitem__
INTERNALERROR>     raise ValueError(f"Key {key}: {ve}") from None
INTERNALERROR> ValueError: Key backend: '' is not a valid value for backend; supported values are ['GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
```

**Comment by pllim** [comment] 2021-04-02 14:59
It is unclear to me where the fix should be. Does pytest-mpl need to be fixed to be compatible now, or is this unintentional side effect of matplotlib change?

**Comment by jklymak** [comment] 2021-04-02 15:05
I'm pretty sure it's unintentional and as @QuLogic  suggested probably caused by the merged change in the template handling.  @anntzer  is the expert on the fallback logic and maybe can tease it apart.

**Comment by tacaswell** [comment] 2021-04-02 17:29
This is definitely a fix on our side, I will look at this this afternoon.

**Comment by pllim** [comment] 2021-04-02 17:32
Thank you all for the quick responses!

**Comment by tacaswell** [comment] 2021-04-02 21:00
See #19854

**Closed** 2021-04-03 11:27 UTC
Labels: Release critical
