### ISSUE TITLE
Only upload failed images on failure

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#23400] opened 2022-07-07 22:51 UTC
Currently when a job fails on GHA we upload all 109 MB across ~7k files which takes a surprisingly long time.  What we really want is just the images that failed and the computed difference.

This is labeled as "good first issue" because there are no API designs here (it is all configuring CI).

Steps:

 - sort out how to identify the failed test images (there is a systematic naming convention)
 -  explain that to the uploader workflow (or just delete all of the non-failed fails!)

**Comment by QuLogic** [comment] 2022-07-08 05:26
@andrzejnovak actually did this in #19466, but we closed it when I accidentally did the upload carte-blanche in a different PR. I had some slight reservations about where the subsetting was in that PR. It seems our tests must have ballooned though, because it was only 50 MB at that point.

**Comment by Anika-Roy** [comment] 2022-07-13 18:31
I'm a beginner and I would like to work on this.

**Comment by N3XT14** [comment] 2023-04-11 02:33
Has anyone started to work on this ?

Would love to take it and also would like to know how can I follow the closed PR to make it work or get an Idea?

**Comment by tacaswell** [comment] 2023-04-11 23:25
@N3XT14 Please have a look at the linked PR and then ask any specific questions you have.

**Comment by N3XT14** [comment] 2023-04-13 15:57
Hi @tacaswell. I looked at the linked PR and understood it well but what I am trying to find out is the linked issue with that PR which I couldn't find.
I need it so that I can understand where the problem is, how do I reproduce it, and then work on fixing it.

**Comment by andrzejnovak** [comment] 2023-04-13 16:02
@N3XT14 The PR was linking a failed test job, think https://github.com/matplotlib/matplotlib/actions/runs/4679682790 for example, github just removes old actions understandably.

**Comment by tacaswell** [comment] 2023-04-14 21:59
@N3XT14 If that PR still looks good, then the task is to rebase in on current main, fix anything that is failing, verify it is doing what we want, and then shepherd it through review process.

**Comment by lukas-mar** [comment] 2023-10-07 12:14
Hi, I would love to start working on this issue, can I get assigned to it? thanks.

**Comment by rcomer** [comment] 2023-10-07 22:24
@lukas-mar you are welcome to submit a pull request for any issue, but we do not assign them.  Please see our contributors’ guide:
https://matplotlib.org/devdocs/devel/index.html

**Closed** 2024-04-10 20:46 UTC
Labels: Good first issue
