### ISSUE TITLE
Python Crashes Without Error When Closing Plot in tKinter

### ISSUE THREAD

**Issue by theGOTOguy** [matplotlib/matplotlib#17651] opened 2020-06-16 19:35 UTC
### Bug report

**Bug summary**

When creating a plot for display in tKinter, matplotlib crashes python with no error given when closing a plot, except when closing with `plt.close('all')`.  Thanks to @DanielGoldfarb for helping me research this bug.

**Code for reproduction**
requirements.txt:
```python
matplotlib==3.2.1
Pillow==7.1.2
```
repro.py
```python
import matplotlib.pyplot as plt
import io 
import tkinter as tk
from PIL import Image, ImageTk

class ReproWindow():
  def __init__(self):
    self.root = tk.Tk()
    self.root.geometry('800x600')

    self.image_label = tk.Label()
    self.image_reference = None

    self.image_label.pack()
    button = tk.Button(self.root, text="Next!", command=self.next)
    button.pack()

    self.get_image_and_display()

    self.root.mainloop()

  def get_image_and_display(self):
    x = [0,1,2,3,4,5,6]
    y = [2,3,1,4,2,5,3]

    fig, ax = plt.subplots()
    ax.plot(x,y)

    img_buffer = io.BytesIO()

    plt.savefig(fname=img_buffer, dpi=192)
    #plt.close('all')    # This works!
    plt.close(fig)      # This doesn't work
    #plt.close()          # This doesn't work.

    img_buffer.seek(0)

    pil_image = Image.open(img_buffer)
    pil_image = pil_image.resize((self.root.winfo_width(), self.root.winfo_height() - (self.root.winfo_reqheight() - self.image_label.winfo_height())))

    self.image_reference = ImageTk.PhotoImage(pil_image)
    self.image_label.configure(image=self.image_reference)
    self.image_label.image = self.image_reference

  def next(self):
    # Reset the window.
    self.get_image_and_display()

app = ReproWindow()
```

First, create a new directory and create a virtualenv for testing:
`virtualenv venv -p python3`
`source venv/bin/activate`

Install the requirements.
`pip install -r requirements.txt`

Run the repro.
`venv/bin/python repro.py`

Click the "Next!" button.

Python will crash with no error given when you hit "Next!"

**Actual outcome**

```python3
(venv) ben@anteater:~/code/repro$ venv/bin/python repro.py 
(venv) ben@anteater:~/code/repro$
```

**Expected outcome**

Clicking "Next!" should not crash python.  Note that uncommenting `plt.close('all')` and commenting `plt.close(fig)` actually works fine.  

**Matplotlib version**
  * Operating system:  Ubuntu 18.04
  * Matplotlib version:  3.2.1, installed through pip.
  * Matplotlib backend (`print(matplotlib.get_backend())`):  TkAgg
  * Python version:  3.6.9, installed through apt.

I can suggest how to fix the issue, but I don't understand why it works and I hope that one of your team will be able to clarify.  I was looking at how the plots are being torn down in _pylab_helpers.py, and it appears that the only difference between `destroy`'s approach and `destroy_all`'s approach is in the order of operations.  

matplotlib at HEAD has changed from my version, so I am including a code snippet from _pylab_helpers.py in matplotlib 3.2.1:
```python
    @classmethod
    def destroy(cls, num):
        """
        Try to remove all traces of figure *num*.

        In the interactive backends, this is bound to the
        window "destroy" and "delete" events.
        """
        if not cls.has_fignum(num):
            return
        manager = cls.figs[num]
        manager.canvas.mpl_disconnect(manager._cidgcf)
        cls._activeQue.remove(manager)
        del cls.figs[num]
        manager.destroy()
        gc.collect(1)

    @classmethod
    def destroy_fig(cls, fig):
        "*fig* is a Figure instance"
        num = next((manager.num for manager in cls.figs.values()
                    if manager.canvas.figure == fig), None)
        if num is not None:
            cls.destroy(num)

    @classmethod
    def destroy_all(cls):
        # this is need to ensure that gc is available in corner cases
        # where modules are being torn down after install with easy_install
        import gc  # noqa
        for manager in list(cls.figs.values()):
            manager.canvas.mpl_disconnect(manager._cidgcf)
            manager.destroy()

        cls._activeQue = []
        cls.figs.clear()
        gc.collect(1)
```

Note that in `destroy_all`, `manager.destroy()` is called before `cls.figs.clear()`, and in `destroy`, the figure is deleted from `cls.figs` before `manager.destroy()` is called.  It turns out that swapping these two operations in `destroy` fixes the issue!  

At first I thought that somehow `del cls.figs[num]` was deleting the manager and that this bug may have been accidentally fixed at HEAD in matplotlib by [this code cleanup](https://github.com/matplotlib/matplotlib/commit/7fcf123051c0b8402f779b68ac9988a2369ed329#diff-b8a1dd51d100507a3748685e6e9c7271), but substituting in `manager = cls.figs.pop(num)` and removing the `del cls.figs[num]` entirely does not fix the issue, so that's not what's going on.

**Comment by QuLogic** [comment] 2020-06-16 21:25
What do you mean by crashes?

I cannot run this:
```pytb
Traceback (most recent call last):
  File "../mpl-tests/issue17651.py", line 50, in <module>
    app = ReproWindow()
  File "../mpl-tests/issue17651.py", line 19, in __init__
    self.get_image_and_display()
  File "../mpl-tests/issue17651.py", line 40, in get_image_and_display
    pil_image = pil_image.resize((self.root.winfo_width(), self.root.winfo_height() - (self.root.winfo_reqheight() - self.image_label.winfo_height())))
  File "/var/container/conda/envs/mpl36/lib/python3.6/site-packages/PIL/Image.py", line 1883, in resize
    im = im.resize(size, resample, box)
  File "/var/container/conda/envs/mpl36/lib/python3.6/site-packages/PIL/Image.py", line 1888, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0
```

**Comment by DanielGoldfarb** [comment] 2020-06-16 23:07
"Crash" is probably not the best term.  The program appears to exit (the graph window closes and python no longer running on the terminal) when it should keep running.  And there is no message written to console.  Simply exits.

**Comment by theGOTOguy** [comment] 2020-06-16 23:17
I'm not sure why you're unable to reproduce in your container:  it looks like tKinter believes you have a window too small to display an image.  Are you sure you have GUI support configured correctly in that container?  What if you just change that line to something like this:

```python
    pil_image = pil_image.resize((200, 200))
```
To clarify, [I've created a video showing the issue.](https://www.youtube.com/watch?v=Bkfos74Qt6s&feature=youtu.be)

**Comment by DanielGoldfarb** [comment] 2020-06-16 23:42
@theGOTOguy 
Ben, I am able to reproduce this on my WSL Ubuntu 18.04.

On my MacOS 10.13.6 running iTerm then I get the same the same error that Elliot @QuLogic  got.

`pil_image = pil_image.resize((200, 200))` brings up the window ok (although `((400,400))` looks better on my display, ***but now*** the "Next!" button seems dead -- no response to a click at all.

**Comment by tacaswell** [comment] 2020-06-17 00:02
If you are going to be grabbing the buffer and displaying it in your own Tk window I would suggest either using the `Agg` backend (but leaving the rest of your code unchanged) or using the Tk widgets we supply (without pyplot) to do the embedding (see https://matplotlib.org/3.2.0/gallery/user_interfaces/embedding_in_tk_sgskip.html).  

I suspect the problem is that you are running a Tk application, creating a Tk window (implicitly via `plt.subplots`) rendering it and then closing it before it gets to be shown.  While I agree that there is something funny going on with the tear-down of never show figures, I think your actually application could be made to work with all currently released versions of Matplotlib with a bit of refactoring.

**Comment by DanielGoldfarb** [comment] 2020-06-17 01:53
@tacaswell 
Interesting.  Thanks Tom.  On Ubuntu, where I am able to reproduce, setting the backend to `Agg` cause the same `ValueError: height and width must be > 0` mentioned above.   Then, using `pil_image = pil_image.resize((400, 400))` in `repro.py` brings up the plot, and all works fine.

That said, should anything be done about this?

> I agree that there is something funny going on with the tear-down of never show figures

Although I am very naive about this part of matplotlib, _it does seem a little odd to me that_ `destroy_fig()` _and_ `destroy_all()` _seem to be going about things in very different ways._

**Comment by QuLogic** [comment] 2020-06-17 03:50
I cannot reproduce any crash after changing the resize line and uncommenting the other `close` options.

However, if you are using Tk directly, you should definitely _not_ use pyplot as it will attempt to manage windows as well. I don't know why it doesn't fail for me, but it's probably just a fluke. Following the embedding examples is a good idea.

**Comment by DanielGoldfarb** [comment] 2020-06-17 04:18
@QuLogic 
Elliot-  I was only able to reproduce this issue when running on Ubuntu where it appears my backend is defaulting to `"TkAgg"`.   When I specifically set my backend to `"Agg"` then the problem went away. 

On my Mac, by default my `matplotlib.get_backend()` returns `"MacOSX"`, and by default I cannot reproduce the problem.  But if I explicitly set my backend to `"TkAgg"` then I _can_ reproduce the problem on my Mac.

So this appears to be specifically related to using the `TkAgg` backend, likely for the reasons you mentioned.

--Daniel

**Comment by tacaswell** [comment] 2020-06-17 04:38
> That said, should anything be done about this?

It is probably worth getting to the bottom of this, but I think it is also worth simplifying the OP's code ;)

**Comment by jklymak** [comment] 2021-04-15 16:40
I'm going to close, but feel free to reopen if this can be narrowed down.

**Closed by jklymak** 2021-04-15 16:40 UTC
Labels: GUI/tk, status: needs clarification
