### ISSUE TITLE
[Bug]: backend from matplotlibrc not used

### ISSUE THREAD

**Issue by brobr** [matplotlib/matplotlib#21718] opened 2021-11-22 20:33 UTC
### Bug summary

Import of matplotlib leads to `KeyError: 'webagg.port'` on Slackware64-current.
Seems related to https://github.com/matplotlib/matplotlib/pull/21684, https://github.com/matplotlib/matplotlib/pull/21662

During building matplotlib from pypi.org source-tar.gz, patches corresponding to above commits had been applied, giving this
matplotlibrc:
>..
\## ***************************************************************************
\## * BACKENDS                                                                *
\## ***************************************************************************
\## The default backend.  If you omit this parameter, the first working
\## backend from the following list is used:
\##     MacOSX QtAgg Gtk4Agg Gtk3Agg TkAgg WxAgg Agg
\## Other choices include:
\##     QtCairo GTK4Cairo GTK3Cairo TkCairo WxCairo Cairo
\##     Qt5Agg Qt5Cairo Wx  # deprecated.
\##     PS PDF SVG Template
\## You can also deploy your own backend outside of Matplotlib by referring to
\## the module name (which must be in the PYTHONPATH) as 'module://my_backend'.
\#backend: QtAgg
\..

Still, also after commenting out `#backend: QtAgg` in either 
`~/.config/matplotlib/matplotlibrc `
or in 
`/usr/lib64/python3.9/site-packages/matplotlib/mpl-data/matplotlibrc`

results in this `KeyError: 'webagg.port'`

### Code for reproduction

```python
bash-5.1$ python
>>> import matplotlib
```

### Actual outcome

>
bash-5.1$ python
Python 3.9.9 (main, Nov 20 2021, 19:41:34) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.9/site-packages/matplotlib/__init__.py", line 895, in <module>
    defaultParams = rcsetup.defaultParams = {
  File "/usr/lib64/python3.9/site-packages/matplotlib/__init__.py", line 898, in <dictcomp>
    rcParamsDefault[key]),
  File "/usr/lib64/python3.9/site-packages/matplotlib/__init__.py", line 674, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'webagg.port'

### Expected outcome

>no import error, i.e:

bash-5.1$ python
Python 3.9.9 (main, Nov 20 2021, 19:41:34) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> import matplotlib
\>>> 

### Additional information

With matplotlib-3.4.3 nothing like this.

### Operating system

Slackware64-15.0-RC2

### Matplotlib Version

3.5.0

### Matplotlib Backend

not possible

### Python version

3.9.9

### Jupyter version

not used

### Installation

from source (.tar.gz)

**Comment by QuLogic** [comment] 2021-11-22 22:47
Duplicate of #21660

**Closed by QuLogic** 2021-11-22 22:47 UTC

**Comment by brobr** [comment] 2021-11-22 23:06
I checked that bug-report issue https://github.com/matplotlib/matplotlib/issues/21660 but despite the changes done in response to that, as mentioned at the top, the problem is still there... unless that problem has not been solved and then this would be a duplicate.

What I find baffling is that the matplotlibrc seems to have no impact (btw on 3.4.3 the QtAgg is not appreciated; best way to solve that is to remove the whole /.config/matplotlib/matploblibrc )

**Comment by QuLogic** [comment] 2021-11-22 23:09
There has been no release with the fix in that report; did you patch it yourself?

**Comment by brobr** [comment] 2021-11-22 23:39
yes:
[backend-init_patch.txt](https://github.com/matplotlib/matplotlib/files/7584991/backend-init_patch.txt)
[setupcfgtemplate_patch.txt](https://github.com/matplotlib/matplotlib/files/7584992/setupcfgtemplate_patch.txt)

**Comment by QuLogic** [comment] 2021-11-23 00:39
Did you apply the patch and then build from a completely clean tree, or apply the patch to the build you already made?

**Comment by brobr** [comment] 2021-11-23 17:41
No; patching should have been straight on an archive after it was unpacked to /tmp, just before building (maybe the script used for this shows that to you:
[matplotlib_SlackBuild.txt](https://github.com/matplotlib/matplotlib/files/7590032/matplotlib_SlackBuild.txt)
)

**Comment by brobr** [comment] 2021-12-05 02:01
Ok, sorry; I missed updating some dependencies (as I noticed when letting pip do it all; in a virtual environment). After putting these in place it all worked as usual (with the above patches included).
