### ISSUE TITLE
matplotlib can not handle pandas dataframe correctly when the label of the columns/index is strings but the actual data are float.

### ISSUE THREAD

**Issue by oulongwen** [matplotlib/matplotlib#10344] opened 2018-01-29 22:07 UTC
### Bug report

**Bug summary**

When using matplotlib.pyplot.scatter to plot a scatter plot for pandas.Dataframe, matplotlib will not generate ticks correctly if the data type of the columns/index of the dataframe is a string.
**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


a = pd.DataFrame(np.random.rand(5, 1), columns=['0'])
b = np.random.randn(5, 1)
plt.scatter(a, b)
plt.show()
```

**Actual outcome**

![figre1](https://user-images.githubusercontent.com/15234300/35522886-8adb8968-04eb-11e8-9933-93656240de95.png)

**Expected outcome**
![figure2](https://user-images.githubusercontent.com/15234300/35522969-be0f03be-04eb-11e8-9234-fc8525201f8f.png)

**Matplotlib version**

  * Operating system: Ubuntu 17.10
  * Matplotlib version:  2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6.3
 * Jupyter version: I tried this with and without jupyter notebook, this issue persists.

I tried this on two systems. The first one runs ubuntu 17.10 with matplotlib installed by anaconda; the second one runs Arch Linux with matplotlib installed with pip. They both have this issue.
I also tried this on Windows 10 and macOS High Sierra, neither of them has this issue.

**Comment by WeatherGod** [comment] 2018-01-29 22:20
Are you sure the version of matplotlib on the Windows 10 and macOS High
Sierra machines is v2.1.2? If I am guessing the problem correctly, this bug
was introduced relatively recently.

**Comment by afvincent** [comment] 2018-01-29 22:27
Is it really a bug? Looking at the documentation, it is not obvious to me, even though it might have been working until recently :/. See for example [types-of-inputs-to-plotting-functions](https://matplotlib.org/tutorials/introductory/usage.html?#types-of-inputs-to-plotting-functions). If I am correct, we are rather documenting the following to “natively” plot from `pandas.DataFrame` instances [plotting-with-keyword-strings](https://matplotlib.org/devdocs/tutorials/introductory/pyplot.html?#plotting-with-keyword-strings).

BTW thank you @oulongwen for the clean code snippet: I can indeed reproduce this behavior on the master branch with a Linux system (Fedora 27) and Python 3.6 (from Anaconda).

**Comment by oulongwen** [comment] 2018-01-29 22:27
@WeatherGod I think you are right. The matplotlib version on the Windows machine is v2.0.0. I can't check the version on the macOS machine right now, but I think it is also an older version. Both linux machines has matplotlib v2.1.2.

**Comment by jklymak** [comment] 2018-01-29 22:30
As of 2.1, strings get sent to Categorical support now, so are labeled with the string you supply and spaced an integer distance apart.  i.e try

```python
import matplotlib.pyplot as plt
import numpy

fig, ax = plt.subplots()
ax.plot(['a', 'd', 'b', 'Boooo', '1.23456'], np.random.rand(5))
```

If you want the x values to be floats, cast them as such...

**Comment by oulongwen** [comment] 2018-01-29 22:33
@jklymak If you look at the code, the inherent data of the dataframe are actually floats, only the label of the column is string and matplotlib does not seem to handle it correctly.

**Comment by jklymak** [comment] 2018-01-29 22:37
Can you reproduce w/o pandas?   Its definitely being sent to the categorical handler.

**Comment by oulongwen** [comment] 2018-01-29 22:39
@afvincent Thanks for your suggestions. Converting the dataframe to a `np.array` prior to  making the plot would work. I am hoping that matplotlib can handle pandas dataframe directly at least in most scenarios (especially it worked perfectly before). But I guess the best practice is to convert the dataframe to a `np.array` before making the plot.

**Comment by afvincent** [comment] 2018-01-29 22:39
From a quick `git bisect`, the behavior started to change after:
```
b1848420bf80cb40211f37fb32f3a2d07e9b5f7f is the first bad commit
commit b1848420bf80cb40211f37fb32f3a2d07e9b5f7f
Author: hannah <story645@gmail.com>
Date:   Thu Jun 16 18:19:18 2016 -0400

    Basic support for plotting lists of strings/categorical data. Support for updating ticks/animation in progress/buggy, 'especially for scatter.
```
But again, I am not sure that this behavior was not in the first place simply working “by accident”.

**Comment by tacaswell** [comment] 2018-01-29 22:40
This is the string-categorical logic triggering again, however I would not expect this to work in general (as a data frame is not a '1D array like' thing).  If you want to plot the column do 

```python
plt.scatter(a[0], b)
```

That this every worked is a bit of happenchance.   The categorical code is being triggered because DataFrames give slightly inconsistent results for iterating through them vs using `np.array`, ex

```python

In [9]: next(iter(a))
Out[9]: '0'

In [10]: np.array(a)
Out[10]: 
array([[ 0.82686393],
       [ 0.89649743],
       [ 0.00660374],
       [ 0.25387538],
       [ 0.15848726]])
```

I am inclined to close this as no-action as supporting full data frames is input to scatter is not something that I think we should support because it is not clear what heuristics should be used to deal with more than one column (particularly if they are of mixed types).

**Comment by afvincent** [comment] 2018-01-29 22:43
@tacaswell Rather `plt.scatter(a['0'], b)` I guess :).

**Comment by tacaswell** [comment] 2018-01-29 22:46
@oulongwen we support `pd.Series` as most inputs directly and `pd.DataFrame` in the `data=df` kwarg (ex `plt.scatter('0', b, data=a)` ).

**Comment by oulongwen** [comment] 2018-01-29 22:46
@tacaswell Yes I agree it is not common to send a dataframe to the `scatter` function. My use case is that I am trying to make a parity plot for a machine learning project where the actual target is stored in another file. So after reading it with pandas it is in a dataframe which is sent to `scatter` to make the parity plot. I can't think of any use case where a dataframe more than 2 columns would be used as a argument of the `scatter` function.

**Comment by oulongwen** [comment] 2018-01-29 22:48
Thank you @tacaswell. I think that would do the trick.

**Comment by tacaswell** [comment] 2018-01-29 23:41
Closing for the reasons discussed above.

**Closed by tacaswell** 2018-01-29 23:41 UTC
Labels: categorical, third-party integration

**Comment by tacaswell** [comment] 2018-01-29 23:42
Thanks for reporting this @oulongwen hopefully the work arounds are enough for you to keep working!
