### ISSUE TITLE
Using c and cmap in plt.loglog

### ISSUE THREAD

**Issue by ukumar8** [matplotlib/matplotlib#17653] opened 2020-06-16 22:32 UTC
```
cmap = plt.get_cmap('magma')

figure(num=None, figsize=(8, 6), dpi=150, facecolor='w')

plt.scatter(eta,V,s=1.5,lw=2,c=flux_max, cmap=cmap)

plt.colorbar(label = 'Max Flux')

plt.xlabel('$\eta$')

plt.ylabel('V')

plt.title('$\eta$ vs. V')

plt.xlim(min(eta), max(eta))

plt.ylim(min(V), max(V))

plt.show()
```

If I insert plt.loglog() after line 2, it changes the axes to log-log but the limits never work out so I have to manually set them although Python still refuses to add the points to the plot or scales it differently to how I specify. 

Works fine with plt.scatter() if I use a linear axes. Would be great if the c and cmap arguments could be added to plt.loglog() as we won't have to make the plots in plt.scatter and redo the axes and scaling after.

**Comment by QuLogic** [comment] 2020-06-17 01:42
Your example is incomplete. Please provide all inputs, or simplify the example some more.

**Comment by dstansby** [comment] 2020-07-12 18:08
Thanks for opening the issue! Since it's not clear exactly what the problem is here I'm going to close this - if you have more info, or can post a self contained example we can run then feel free to re-open this issue or open another one.

**Closed by dstansby** 2020-07-12 18:08 UTC
Labels: Needs clarification
