### ISSUE TITLE
[Bug]: axes vlines() / hlines() incorrectly use data coordinate as min when blended transform is applied

### ISSUE THREAD

**Issue by orionlee** [matplotlib/matplotlib#23171] opened 2022-05-31 22:33 UTC
### Bug summary

For `Axes.vlines()`, when I want to use axes coordinate for `ymin` / `ymax`, as suggested in [blended transformation](https://matplotlib.org/3.5.0/tutorials/advanced/transforms_tutorial.html#blended-transformations), `ymin` is incorrectly treated as data coordinate.

`Axes.hlines()` has a similar problem with `xmin`.

### Code for reproduction

```python
# Sample derived from
# https://matplotlib.org/3.5.0/gallery/lines_bars_and_markers/vline_hline_demo.html#sphx-glr-gallery-lines-bars-and-markers-vline-hline-demo-py
    
import matplotlib.pyplot as plt
import numpy as np

import matplotlib 
print('matplotlib', matplotlib.__version__)


t = np.arange(5.0, 10.0, 0.1)
s = np.exp(-t) + np.sin(2 * np.pi * t) + 10

vax = plt.figure(figsize=(12, 6)).gca()
vax.plot(t, s, '^')

# By using ``transform=vax.get_xaxis_transform()`` the y coordinates are scaled
# such that 0 maps to the bottom of the axes and 1 to the top.

vax.vlines([6, 7], ymin=0, ymax=0.15, transform=vax.get_xaxis_transform(), colors='r')
# if I use axvline() instead, it correctly treats ymin as axes coordinate.
# vax.axvline(6, ymin=0, ymax=0.15, c='r')
# vax.axvline(7, ymin=0, ymax=0.15, c='r')

vax.set_xlabel('time (s)')
vax.set_title('Vertical lines demo');
```

### Actual outcome

One can see that while `ymax` is applied correctly (about 15% of the y-axis), `ymin` is applied incorrectly. `ymin` is treated as data coordinate, incorrectly stretching the y-axis.

![image](https://user-images.githubusercontent.com/250644/171294142-451a27fe-2e01-498e-84cb-9acc99aa3232.png)

### Expected outcome

The expected outcome can be obtained using multiple `axvline()` instead of `vlines()`:
```python
vax.axvline(6, ymin=0, ymax=0.15, c='r')
vax.axvline(7, ymin=0, ymax=0.15, c='r')
```

![image](https://user-images.githubusercontent.com/250644/171294186-a4570463-54e6-4a26-ab59-36245567c096.png)

### Additional information

I've encountered the problem in earlier versions. I cannot recall it ever works correctly.

`Axes.hlines()`  has a similar problem with `xmin`.

One can add the following to the example codes above to test it:

```python
# axes.hlines() has similar problem.
vax.hlines([9, 9,5], xmin=0, xmax=0.2, transform=vax.get_yaxis_transform(), colors='green')
# uses multiple axhline() call would work correctly
# vax.axhline(9, xmin=0, xmax=0.2, c='green')
# vax.axhline(9.5, xmin=0, xmax=0.2, c='green')
```

### Operating system

Windows

### Matplotlib Version

3.5.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.9.10

### Jupyter version

6.4.11

### Installation

conda

**Comment by tacaswell** [comment] 2022-06-01 02:25
Labeling this as a good first issue because there is no API design and this appears to be a clearly identified bug that should be fixed.

Labeling as medium difficulty as this is probably not a project someone new to Python should take on.

**Comment by orionlee** [comment] 2022-06-01 03:34
I suspect the problem lies with the scaling done at the end of `vlines()` implementation

https://github.com/matplotlib/matplotlib/blob/9765379ce6e7343070e815afc0988874041b98e2/lib/matplotlib/axes/_axes.py#L1142-L1149

In the example scenario, the `miny` and `maxy` used in scaling are probably in axes coordinates, while the actual scaling in `update_datalim()` treat them as data coordinates.

In contrast, [`axvlines()`](https://github.com/matplotlib/matplotlib/blob/9765379ce6e7343070e815afc0988874041b98e2/lib/matplotlib/axes/_axes.py#L743) has such issue, because its scaling logic keeps y-axis scale unchanged.

**Comment by njj67229** [comment] 2022-07-14 04:22
Is anyone currently working on this issue? I have not done any open source contribution before and would be interested in giving it a stab as a first issue.

**Comment by QuLogic** [comment] 2022-07-20 23:44
I don't think anyone is working on this; feel free to take a stab at it.

**Comment by Ailieena** [comment] 2022-08-28 18:46
Hi, I'm new to open source and wanted to take a look at this issue. 
I looked at the code and I'm not fully convinced that the current behavior is incorrect. The description of ``vlines`` function suggests that it should plot "vertical lines at each *x* from *ymin* to *ymax*.".
It seems to me that ``vlines`` using ``ymin`` and ``ymax`` as coordinates is the expected outcome, am I wrong?

**Comment by story645** [comment] 2022-08-28 19:46
> It seems to me that vlines using ymin and ymax as coordinates is the expected outcome, am I wrong?
 
Forgive me if I'm misinterpreting you question, but the issue is that this function supports [multiple coordinate systems](https://matplotlib.org/stable/tutorials/advanced/transforms_tutorial.html)  and the original poster is trying to plot the vlines in the axes coordinate system. The axes coordinates are independent of the data coordinates and are fixed to the displayed axes: 

> The coordinate system of the Axes; (0, 0) is bottom left of the axes, and (1, 1) is top right of the axes.

In the expected image provided by the original poster, 0 in axes coordinates is the bottom of the displayed axes, which is supposed to be more or less at the same place as the data 9. 
![image](https://user-images.githubusercontent.com/1300499/187091489-3963646d-d755-4ea3-8524-5eeff01564d3.png)

The bug is that instead of plotting the bottom of the line in axes coordinates (so at around data 9), it is plotting the line at 0 in data coordinates.

**Comment by Ailieena** [comment] 2022-08-28 22:22
Thank you for the explanation, I understand now. I'll look into it more.

**Closed** 2023-04-19 21:51 UTC
Labels: Difficulty: Medium, Good first issue
