### ISSUE TITLE
numpy.polyfit() get messed up by ploting a graph 

### ISSUE THREAD

**Issue by robfiedler** [matplotlib/matplotlib#18559] opened 2020-09-24 10:03 UTC
### Bug report
I am trying to use np.polyfit function. I have been using this for quite some time, but yesterday realize that something is broken. First I use a polyfit to find a line arguments then I plot the graph, but when trying to call polyfit for the second time, it produce the error, even thou I am calling the same function with the same arguments.
raise LinAlgError("SVD did not converge in Linear Least Squares")
numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares

**Bug summary**

```python
import numpy as np
import matplotlib.pyplot as plt

import numpy.polynomial.polynomial as poly

x = np.linspace(0, 1e-5*10000, 10000, endpoint=False)
y = np.random.random(10000)
coef = poly.polyfit(x, y, 1)[::-1]
print(coef)

x_fit = np.zeros(2)
x_fit[:] = [x[0], x[-1]]
y_fit = x_fit*coef[0] + coef[1]

plt.plot(x, y, linewidth=0.1)
plt.plot(x_fit, y_fit, linewidth=2, linestyle='--', color='red')
plt.show()
plt.close("all")

coef = poly.polyfit(x[1:], y[1:], 1)[::-1]
print(coef)

#
```

**Actual outcome**

```
# If applicable, paste the console output here
[0.21593069 0.48646648]
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  5 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
Traceback (most recent call last):
  File "polyfit_example.py", line 31, in <module>
    coef = poly.polyfit(x[1:], y[1:], 1)[::-1]
  File "C:\python38\lib\site-packages\numpy\polynomial\polynomial.py", line 1350, in polyfit
    return pu._fit(polyvander, x, y, deg, rcond, full, w)
  File "C:\python38\lib\site-packages\numpy\polynomial\polyutils.py", line 706, in _fit
    c, resids, rank, s = np.linalg.lstsq(lhs.T/scl, rhs.T, rcond)
  File "<__array_function__ internals>", line 5, in lstsq
  File "C:\python38\lib\site-packages\numpy\linalg\linalg.py", line 2306, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
  File "C:\python38\lib\site-packages\numpy\linalg\linalg.py", line 100, in _raise_linalgerror_lstsq
    raise LinAlgError("SVD did not converge in Linear Least Squares")
numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
Win10 64bit
python-3.8.5-amd64
Matplotlib 3.3.2
numpy-1.19.2

pip install numpy
pip install matplotlib

**Comment by WeatherGod** [comment] 2020-09-24 16:04
This seems very similar to https://github.com/matplotlib/matplotlib/issues/17980

**Comment by jklymak** [comment] 2020-09-24 16:12
Yes, there appears to be some bad library mismatch in the Windows-verse.  I'll close and mark a duplicate of #18157, but please feel free to follow up there.

**Closed by jklymak** 2020-09-24 16:12 UTC
