### ISSUE TITLE
Problem of fonts with LaTeX rendering due to fonts-lyx package

### ISSUE THREAD

**Issue by grumpfou** [matplotlib/matplotlib#6617] opened 2016-06-20 21:52 UTC
Hello,

I both using Matplotlib and Lyx (https://wiki.lyx.org/) on Ubuntu. Recently I updated the package fonts-lyx from version 2.1.4-2 up to 2.2.0-1 . It provoked incoherent results in the latex rendering of Matplotlib: the simple :

```
import matplotlib.pyplot as plt
plt.text(0.5,0.5,r'$\mu_3$')
```

display random character (something like /Ω). I downgraded the version of fonts-lyx to 2.1.4-2 and it works again.
- Linux MyComputer 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- matplotlib.**version**: '1.5.1'
- Python 2.7.11+
- I installed Matplotlib via PIP

![capture du 2016-06-20 23-50-04](https://cloud.githubusercontent.com/assets/3619520/16211475/fc0d90fa-3741-11e6-9863-6a01f42928e5.png)
![capture du 2016-06-20 23-50-54](https://cloud.githubusercontent.com/assets/3619520/16211476/fc0f5124-3741-11e6-83e4-e75898bfb248.png)

**Comment by tacaswell** [comment] 2016-06-21 01:49
attn @mdboom @zblz

**Comment by jkseppan** [comment] 2016-06-21 13:32
@grumpfou What do you have in your matplotlibrc file? Are you using usetex? Which backend is this?

**Comment by jkseppan** [comment] 2016-06-21 13:40
@grumpfou Where does version 2.2.0-1 of fonts-lyx come from? The latest version I can find in the Ubuntu archives is fonts-lyx_2.1.4-2_all.deb.

**Comment by grumpfou** [comment] 2016-06-22 07:42
I did not touch to the matplotlibrc file, it is the one at /etc/matplotlibrc . For the backend, I have tested for TkAgg and for Qt4Agg for the same result.

Indeed, I have forgotten, but I have installed the ppa of lyx : ppa:lyx-devel/release . The package "fonts-lyx" is a sub-package in  "lyx - 2.2.0-1~xenial~ppa3" (see https://launchpad.net/~lyx-devel/+archive/ubuntu/release/+packages).

**Comment by jkseppan** [comment] 2016-06-22 08:41
I'm inclined to call this a bug in the lyx ppa then. Debian does some careful integration work on packages, and they have asked matplotlib to accommodate this, e.g. by not bundling our own copies of fonts and  Python dependencies. Apparently the ppa version of lyx installs some fonts with the same name as well-known TeX fonts but a different encoding, and that breaks the matplotlib rendering.
On 22 Jun 2016 10:42, Grumpfou <notifications@github.com> wrote:I did not touch to the matplotlibrc file, it is the one at /etc/matplotlibrc . For the backend, I have tested for TkAgg and for Qt4Agg for the same result.

Indeed, I have forgotten, but I have installed the ppa of lyx : ppa:lyx-devel/release . The package "fonts-lyx" is a sub-package in  "lyx - 2.2.0-1~xenial~ppa3" (see https://launchpad.net/~lyx-devel/+archive/ubuntu/release/+packages).

**Comment by jfmoulin** [comment] 2016-12-08 16:59
I have the exact same problem under Mint 18 which installs lyx-fonts 2.2.2-1~ubuntu16.04.1york1.
Regression to 2.1.4-2 solves the issue.

**Comment by jkseppan** [comment] 2016-12-26 14:39
@jfmoulin If you're installing matplotlib and lyx-fonts from distribution packages, please file a Mint bug because this would seem to be a problem with their integration testing. If you're installing matplotlib from source, it would be interesting to know if there is anything we can use to differentiate between the different versions of the fonts.

**Comment by jfmoulin** [comment] 2016-12-26 21:13
My lyx comes from distro packages (Mint), whereas matplotlib was instaled from pypi with pip.
Info about the font version is available in the ttf files in the name field number 5 (see http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=iws-chapter08)
I checked this using the command line pyftinspect from fonttools (https://pypi.python.org/pypi/FontTools). 
It seems fonttools provides also a module giving means to do the check from a script, but maybe you do not want this as a matplotlib dependency...

**Comment by jkseppan** [comment] 2017-01-02 07:38
I think this is the same bug as #6976, which has a link to the corresponding Debian bug and a workaround. I'll close this one as a duplicate.

**Closed by jkseppan** 2017-01-02 07:38 UTC
Labels: text, text/unicode
