### ISSUE TITLE
[Bug]: center of markers don't fall on plotted line

### ISSUE THREAD

**Issue by BoudewijnKlijn** [matplotlib/matplotlib#23635] opened 2022-08-16 08:02 UTC
### Bug summary

Markers displayed in a normal line plot may be in the wrong place: the center of the marker seems a little bit off the center of the line. I used seaborn pointplot as reference and those markers seem to be in the correct spot.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

x = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26])
y = np.array([0.00254902, 0.00509804, 0.00784314, 0.01882353, 0.03411765,
        0.05333333, 0.06862745, 0.08137255, 0.08745098, 0.09196078,
        0.09      , 0.08960784, 0.08235294, 0.06607843, 0.05901961,
        0.04392157, 0.03529412, 0.02411765, 0.02254902, 0.01313725,
        0.00862745, 0.00607843, 0.00254902, 0.00117647, 0.00294118,
        0.00098039, 0.00039216])

sns.pointplot(x=x, y=y)
plt.plot(x, y, marker='o', color='red')
plt.show()
```

### Actual outcome

Notice how the marker of x=3 seems to be a bit to the right, for example.

![image](https://user-images.githubusercontent.com/31416818/184827733-ba82aebb-daab-48e1-8f43-9412418e11c6.png)

### Expected outcome

Center of the marker should fall on the line of plot.

### Matplotlib Version

3.5.2

**Comment by timhoffm** [comment] 2022-08-16 08:50
Pretty sure this is related to rasterization. I assume seaborn pointplot uses `scatter` under the hood, which draws circles of basically arbitrary size. These are positioned at the exact location and then rastered. Depending on the relative position to the pixel grid, each marker looks slightly different. See, e.g. the top edges of the blue points at 10 and 11.

In contrast, `plot` is designed for constant sized markers, and it prioritizes that the markers look exactly the same. It therefore moves the markers by maximally half a pixel so that they all are positioned to the pixel grid in the same way. This effect is not as important/visible for circles, but very important for any marker with straight lines such as squares or ‘x’.

**Comment by BoudewijnKlijn** [comment] 2022-08-16 12:18
Does this mean that if the plot was create with more pixels, the markers of matplotlib would be positioned better (i.e. centers on the line)? If so, how can you create a plot with more pixels?

**Comment by oscargus** [comment] 2022-08-16 12:55
You can for example save with a higher dpi: `plt.savefig('filename.png', dpi=1000)`.

![image](https://user-images.githubusercontent.com/8114497/184884758-c80daf14-83bd-43fc-89ef-377fb2f8354f.png)

**Comment by jklymak** [comment] 2022-08-16 13:35
Please also see set_snap. https://matplotlib.org/stable/api/_as_gen/matplotlib.artist.Artist.set_snap.html

**Comment by timhoffm** [comment] 2022-09-07 20:32
I'm closing this as it is intended behavior. Use `set_snap` if you want the other behavior.

**Closed by timhoffm** 2022-09-07 20:32 UTC
