### ISSUE TITLE
[Bug]: patch circles or corresponding scatters are eccentric

### ISSUE THREAD

**Issue by alisheikholeslam** [matplotlib/matplotlib#26461] opened 2023-08-06 21:04 UTC
### Bug summary

I have coordinates and want to plot them as points and also unfilled circles like the example provided. I have plotted the circles using patches `plt.Circle` in a loop. The metric lengths of the axes must be proportional and be controlled by two of the axes i.e. length of the x axis (around 12) is one-third of the length of the y axis (which is 36).  

Q1 (**main question**). Some of the plotted points (not all of them) are tended to the circles' boundaries, so that points or their corresponding circles are eccentric. Why and how to solve this issue?

Q2: Can I plot the circles without looping if have a coordinate array (n*2)?  

Q3. I want to have two x axes, one topside and the other downside of the plot. I couldn't do this using just the `plt`. Does it need to use `ax` only or can be handled by `plt`?

Q4. Is there any easier way (some built-ins or ...) that adding new formulated coordinates, to handle the clipped part of the circles to be mirrored in the plot? E.g. for the upper left circle (it is just one quarter of the circle) another quarter be mirrored on x axis to be shown on coordinate `(12, 0)`.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt


plt.rcParams["figure.figsize"] = (19.2, 9.6)

perf_num = 20.0
circumL = 12.247274627871128
coord_circum = np.array([0.        ,  4.08242488, 8.16484975,  12.24727463, 0.62173624,
                         4.70416111,  8.78658599, 12.86901086, 1.24347247,  5.32589735,
                         9.40832222,  13.4907471, 1.86520871,  5.94763358,  10.03005846,
                         14.11248334, 2.48694494, 6.56936982,  10.6517947,  14.73421957])
coord_along = np.arange(0, 39, 2)

plt.gca().set_aspect("equal")

plt.scatter(coord_circum, coord_along, color="r", linewidths=1)

for i in range(int(perf_num)):
    circle_patch = plt.Circle((coord_circum[i], coord_along[i]), 0.4, fill=False, color='r', lw=1)
    plt.gca().add_patch(circle_patch)

# plt.xticks([])
plt.tick_params(axis='x', which='both', labeltop=True, labelbottom=False, top=True, bottom=False)
plt.xticks(np.arange(0, circumL, 4))
plt.xlim(0, circumL)
plt.ylim(0, 36)
# plt.gca().set_aspect(1 - circumL / 36)

# plt.twiny()
# plt.tick_params(axis='x', which='both', labeltop=False, labelbottom=True, top=False, bottom=True)
# plt.xticks(np.arange(0, 361, 60))  # --> changes x limits and plot  x to y lengths ratio
plt.gca().invert_yaxis()

plt.show()
```

### Actual outcome

![1](https://github.com/matplotlib/matplotlib/assets/63285654/0e209230-40b2-45cb-b9ef-6337a3c82908)

### Expected outcome

![2](https://github.com/matplotlib/matplotlib/assets/63285654/97ae960e-3892-4ed4-8a9d-ee3466d5b5de)

### Operating system

windows 10 x64

### Matplotlib Version

3.5.3

### Python version

3.8

### Installation

conda

**Comment by tacaswell** [comment] 2023-08-07 02:53
Q1 and Q2

> Why and how to solve this issue?

For performance reasons for uniformly drawn markers we render the marker once and then "stamp" it where ever it is needed, however this leads to sub-pixel shifts which are highlighted by this.  The `scatter` call goes through this optimization, the individual `Circle` patches do not, hence the weird results.

If you push the dpi way up it will look better.

If you need the circles to be sized in data coordinates you can use a `PatchCollection`, but if you can size both the markers and the circles in screen space use two calls to `ax.scatter` 

```python
fig, ax = plt.subplots()
# outer
ax.scatter(x, y, fc=(0, 0, 0, 0), lw=1, ec='red', s=100)
# inner
ax.scatter(x, y, fc='red', lw=0,  s=50)
```

You may need to tune the size a bit to get exactly what you want.


Q3

`pyplot` is an implicitly  stateful wrapper around the explict `Axes` API (see https://matplotlib.org/stable/users/explain/api_interfaces.html#native-matplotlib-interfaces).  Pyplot is useful for managing GUI windows and is good for interactively typing into a terminal, but for any scripts or imported functions, the explicit API is preferred. 

Q4

Not easily, may be possible to leverage the projections interface to get this, but I am not 100% sure.  This sort of thing is supported for map/globe projections, but I do not know if it is done at the marker level.

**Comment by alisheikholeslam** [comment] 2023-08-08 16:00
@tacaswell Thanks, I will use *patching* for both instead scatter. For Q3, I try to use *ax* for plotting as the desired one as:
```
fig, ax1 = plt.subplots()

ax1.set_aspect("equal")
ax1.set(xlim=(0, circumL), ylim=(0, 36))
ax1.set_xlabel('Perforation angle (°)', fontsize=12)
ax1.set_ylabel('Distance along hole axis (in)', fontsize=12)
ax1.set_xticks(np.linspace(0, circumL, 7))
ax1.set_xticklabels(np.arange(0, 361, 60))

ax2 = ax1.twiny()
ax2.set_aspect("equal")
ax2.set(xlim=(0, circumL), ylim=(0, 36))
ax2.set_xticks(np.arange(0, int(circumL) + 1, 3))
ax2.set_xlabel('Position around circumference (in)', fontsize=12)
ax2.invert_yaxis()
```
All is ok but the x axis length (metric) is not ok. How to fix it?? the red boxs intervals must be removed
![Figure_1](https://github.com/matplotlib/matplotlib/assets/63285654/713f0127-1f1d-4b53-92a1-adeb3e9eb3c4)

**Comment by tacaswell** [comment] 2023-08-08 22:13
The issue is that you are setting the aspect, the xlim, the ylim, and the axes size on the screen.  We have to ignore one of them and by default we adjust the data limits.

`ax.set_aspect('equal', adjustable='box')` should do what you want.

Another advantage of `scatter` is that it draws the shapes in screen space so will always be round no matter what the axis limits are (you can do the same with `Patch`, but would have to look up the right transforms to use).

I am going to close this because I do not think there is anything that needs to be done by Matplotlib.

If you have further usage questions could you post them to https://discourse.matplotlib.org instead?

**Closed by tacaswell** 2023-08-08 22:13 UTC
Labels: Community support
