### ISSUE TITLE
tight_layout puts axes title below twiny xlabel 

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5474] opened 2015-11-13 00:52 UTC
```
plt.title("title")
plt.gca().twiny().set_xlabel("xlabel")
plt.tight_layout()
```

![tight_twiny](https://cloud.githubusercontent.com/assets/1322974/11135816/ad60bf1e-895d-11e5-8090-2c93230aaf19.png)
matplotlib 1.5.0.

**Comment by tacaswell** [comment] 2015-11-13 02:25
Is this a regression from 1.4.3?

**Comment by tacaswell** [comment] 2015-11-13 02:27
I suspect the problem here is that the title is attached to the first axes, but the axis label is attached to the twin.

**Comment by anntzer** [comment] 2015-11-13 02:52
1.4.3 suffers from the same issue.

**Comment by tacaswell** [comment] 2015-11-13 03:06
I know it maybe annoying to users, but I am currently much more worried about regressions (ie things we _broke_ between 1.4.3 and 1.5.0) than long standing bugs.

**Comment by WeatherGod** [comment] 2015-11-13 14:32
This is going to be a tough one to solve. Technically speaking, there is no
bug here. tight_layout() is doing exactly what it is supposed to do. The
problem is that the xlabel text object has a position relative to the
x-axis, while the title has a position defined relative to the edge of the
subplot region. These two positions are only loosely related to each other,
and there is certainly no constraint system in place to enforce relative
positions from each other.

On Thu, Nov 12, 2015 at 10:06 PM, Thomas A Caswell <notifications@github.com

**Comment by tacaswell** [comment] 2015-11-13 14:38
This is wrapped up in the fact that we need a layout engine.  There was a
prototype using a linear constraint solver a while ago, but the hard part
is going to be (automatically?) generating the constraints.

**Comment by anntzer** [comment] 2015-11-13 16:37
Re: "I suspect the problem here is that the title is attached to the first axes, but the axis label is attached to the twin."
Actually not, if you move the first axes' xlabel and xticks to top (`gca().xaxis.set_{label,ticks}_position("top")`) you suffer from the same problem.

**Comment by Tillsten** [comment] 2015-11-17 13:01
@tacaswell The hard are not the constraits, that mostly busy-work. The hard part
is including it in a backwards compatible way. Also there is still the same chicken-egg problem which
is also faced by tight_layout that some variables are only known after drawn (labelsizes, ticklabelsizes).

**Comment by anntzer** [comment] 2017-10-20 08:12
@jklymak Sorry I ended up not having much time so far to look at your geometry manager PR, but perhaps this issue may be of interest for you...

**Comment by jklymak** [comment] 2017-10-21 00:29
I've not dared look at `twinx/twiny` yet, but if they are rationally constructed then this shouldn't be very hard.

**Comment by jklymak** [comment] 2017-10-21 02:45
OK, I got `twinx/twiny` to work, but it doesn't fix this problem because  #9082 doesn't handle things below the axes level, and title placement etc is handled at a level below that. 

I'll note that this problem is much more simple than this makes it seem, and has nothing to do with `twiny` other than `twiny` puts the xlabel at the top:

```python

import matplotlib.pyplot as plt
fig, ax = plt. subplots()
ax.xaxis.tick_top()
ax.xaxis.set_label_position('top')

ax.set_xlabel('Parent xlabel')
ax.set_title('Title')
```

<img width="834" alt="axes_legends_now_included_in_tight_bbox_ _matplotlib_2_1_0_post371_gfc04c62_documentation" src="https://user-images.githubusercontent.com/1562854/31847342-2e5ba0e4-b5cf-11e7-8820-7d57f83a603c.png">

**Comment by anntzer** [comment] 2017-10-21 03:23
Well, I actually did need labels both on top and on bottom (for separate axes).

**Comment by jklymak** [comment] 2017-10-21 03:36
Sure, its still an issue.

I'm just saying `tight_layout` and `twiny` are red-herrings; the real problem is that title doesn't care/know that there is an x-axis right there.

A geometry manager at the sub-axes level would be great too, and probably manageable for xlabel, ylabel, and title.  Once we get into tick labels and ticks themselves things get hairy.  And some seem to think layout managers would be good for placing legends, etc around data.  That hurts my head.  Not saying its not all possible, but just getting subplot placement sorted out was tough, and that should be the easy job...

**Comment by jklymak** [comment] 2017-10-21 03:55
Closing as a duplicate of #1415

**Closed by jklymak** 2017-10-21 03:55 UTC
Labels: geometry manager
