### ISSUE TITLE
I cannot install matplotlib woth Python 3.7.0

### ISSUE THREAD

**Issue by otsuka-kohei** [matplotlib/matplotlib#11606] opened 2018-07-09 12:45 UTC
### Bug report

**Bug summary**

I cannot install matplotlib with Python 3.7.0 on Windows 10.

**Code for reproduction**

```python
pip install matplotlib
```

**Actual outcome**

```
pip install matplotlib
Collecting matplotlib
  Using cached https://files.pythonhosted.org/packages/ec/ed/46b835da53b7ed05bd4c6cae293f13ec26e877d2e490a53a709915a9dcb7/matplotlib-2.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [2.2.2]
                    python: yes [3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018,
                            04:06:47) [MSC v.1914 32 bit (Intel)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.14.5]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype
                            (freetype2\ft2build.h) could not be found.  You may
                            need to install the development package.]
                       png: no  [The C/C++ header for png (png.h) could not be
                            found.  You may need to install the development
                            package.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PySide2 not found; PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: yes [installing]

    OPTIONAL LATEX DEPENDENCIES
                    dvipng: yes [version 1.15]
               ghostscript: no
                     latex: yes [version 3.14159265]
                   pdftops: yes [version 0.63.0]

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/freetype.htm for instructions to install
                            * freetype
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/libpng.htm for instructions to install png

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\otsuka\AppData\Local\Temp\pip-install-nwzb3cav\matplotlib\
```

**Expected outcome**

Successful installation of matplotlib

**Matplotlib version**

  * Operating system: Windows 10 Home 1803 64bit
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): NameError: name 'matplotlib' is not defined
  * Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]
  * Jupyter version (if applicable): None
  * Other libraries: None

**Comment by tacaswell** [comment] 2018-07-09 13:14
Sorry, we do not have windows wheels up yet.  

To compile from source on windows you will need to install the extra c-dependencies (it looks like you need freetype and libpng) and visual studio installed.

**Comment by tacaswell** [comment] 2018-07-09 13:15
I am going to close this as it is not a bug in Matplotlib but a gap in publishing wheels.

**Closed by tacaswell** 2018-07-09 13:15 UTC

**Comment by crawelsky** [comment] 2019-04-15 11:49
Hi, I faced the same issue, is someone found a way to pass this issue ? 
Regards.

**Comment by tacaswell** [comment] 2019-04-15 12:36
@crawelsky Can you please open a new issue.
