### ISSUE TITLE
the program written in spyder3.3.3 can't run in spyder3.3.6

### ISSUE THREAD

**Issue by fanzz1982** [matplotlib/matplotlib#15120] opened 2019-08-25 15:27 UTC
### Bug report
the program .py written in spyder3.3.3 can't run in spyder3.3.6. It seems that the command axes[].plot() from matplotlib has sth wrong in spyder3.3.6. The alarm messenge is : tuple index out of range 
I report the probelm to the admin of spyder. He reply me that it is the problem in matplotlib not in spyder, and I should update my code. 
What can I do about updating my code? my matplotlib in anaconda is 3.1.0 
**Bug summary**
 It seems that the command axes[].plot() from matplotlib has sth wrong in spyder3.3.6. The alarm messenge is : tuple index out of range 

**Code for reproduction**

```python
# Paste your code here
#
#
for i in range(n):
    irf_data = pd.DataFrame(
            [irf_1[:,i], irf_2[:,i], irf_3[:,i]]).T
    irf_data.columns = ['point', 'up', 'lower']
    
    axes[i//2, i % 2].plot(irf_data.index, irf_data.1,
                           color = 'blue', linestyle = '-')
```

**Actual outcome**
tuple index out of range 

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment] 2019-08-25 15:39
Can you make a self contained complete runnable example that shows the issue? Also report the full trace back?  And your matplotlib version (at the very least) and maybe the previous matplotlib version?

**Comment by fanzz1982** [comment] 2019-08-25 16:32
> Can you make a self contained complete runnable example that shows the issue? Also report the full trace back? And your matplotlib version (at the very least) and maybe the previous matplotlib version?

when the porblem occure, my matplotlib in anaconda is 3.1.0. Then I reinstall the anaconda, and the spyder is 3.3.3, matplotlib is 3.0.3, the .py runs well.  
n=9
irf_1 = np.random.uniform(0,1,(100,9))
irf_2 = np.random.uniform(0.5,1.5,(100,9))
irf_3 = np.random.uniform(-0.5,0.5,(100,9))
fig, axes = plt.subplots((n+1) // 2, 2)
for i in range(n):
    irf_data = pd.DataFrame(
            [irf_1[:,i], irf_2[:,i], irf_3[:,i]]).T
    irf_data.columns = ['point', 'up', 'lower']
    
    axes[i//2, i % 2].plot(irf_data.index, irf_data.point,
                           color = 'blue', linestyle = '-')
    axes[i//2, i % 2].plot(irf_data.index, irf_data.up,
                           color = 'red', linestyle = '--')
    axes[i//2, i % 2].plot(irf_data.index, irf_data.lower,
                           color = 'red', linestyle = '--')
plt.show()

**Comment by ImportanceOfBeingErnest** [comment] 2019-08-25 17:00
This is most probably a duplicate of https://github.com/matplotlib/matplotlib/issues/14992 and fixed by  https://github.com/matplotlib/matplotlib/pull/15007. 

What this means is that matplotlib 3.1.1 or lower is not compatible with pandas 0.25 when plotting the index of a dataframe.

Options are:
 
* Use numpy arrays (matplotlib tries to support pandas as good as possible, but there are still some hickups every now and then)
* Wait for matplotlib 3.1.2 to be released.
* Use pandas 0.24.x or 0.25.1 (once it's released)

**Closed by ImportanceOfBeingErnest** 2019-08-25 17:00 UTC
