### ISSUE TITLE
mpl_toolkits does not have __init__.py (Linux)

### ISSUE THREAD

**Issue by ngoonee** [matplotlib/matplotlib#4712] opened 2015-07-16 04:22 UTC
I refer to an old report - https://github.com/matplotlib/matplotlib/issues/2611/

The same happens with a standard 'python setup.py build' followed by 'python setup.py install --skip-build' which, I think, is quite standard for distro packages. That is, __init__.py is not placed in the mpl_toolkits folder.

This affects auto-completion behaviour for some python tools, would be great to have it resolved.

**Comment by efiring** [comment] 2015-07-16 07:33
I can't reproduce this.  I tried it in a virtualenv (python 3.4) with master, after 'git clean -dfx', removing the matplotlib...egg directory from site packages, and using exactly the two setup commands you list.  Inside the egg directory, there is a mpl_toolkits/\_\_init\_\_.py file.  This was in an xubuntu 14.04 VM, with setuptools 3.3.

**Comment by ngoonee** [comment] 2015-07-16 07:46
Hi efiring,

Perhaps I was oversimplifying things, here's the buildscript - https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/python-matplotlib

No need to bother to read that though, it's just for reference. When I do python setup.py build and then do python setup.py install -O1 --skip-build --root "/some/dir" --prefix=/usr the file doesn't show up. It exists in the build subdirectory, but not in the installed-to directory (/some/dir above).

Quick testing indicates that removing -O1 and --prefix=/usr doesn't solve that. Am doing a rebuild now just to confirm it.

**Comment by efiring** [comment] 2015-07-16 08:18
Yes, I see this if I use the --root option.  In this case there is no egg directory, but there is an ugly matplotlib-1.5.dev1-py3.4-nspkg.pth file and an egg-info directory.  All of this is impenetrable setuptools magic that we are stuck with, as far as I can see.  It works, in that we can install additional toolkits like basemap with no difficulty.  I'm going to close this, but you may reopen it if you come up with a solution.

**Closed by efiring** 2015-07-16 08:18 UTC
