### ISSUE TITLE
Matplotlib finding Win10 env when run via pytest on WSL

### ISSUE THREAD

**Issue by toonarmycaptain** [matplotlib/matplotlib#16419] opened 2020-02-05 17:34 UTC
### Bug report
https://github.com/numpy/numpy/issues/15520

I'm running pytest on a project in WSL Ubuntu, and I'm getting an error with numpy. Matplotlib is being found in the WSL python install, but that matplotlib finds numpy in the Windows env Pycharm has in my project folder:
```
PycharmProjects/
    project_folder/
        project_source/
        windows_project_env/
        README.md
        app_main.py
```
I'll note that the project works fine, but this is possibly because it is not using matplotlib/numpy in a way that that causes this issue.
Could this be an issue with matplotlib looking for numpy?

**Comment by jklymak** [comment] 2020-02-05 17:42
This is certainly an environment problem, not a matplotlib problem.  Yes matplotlib imports numpy, but we do it based on how your environment is set up.  Tools like anaconda make this easier, suggest you look into using that if you are not comfortable with how python environments work.

**Comment by toonarmycaptain** [comment] 2020-02-05 18:23
This is just a regular python3.8 install inside Ubuntu. I assumed it was an environment issue as well, but every other imported module when run via REPL, script, and tests in pytest has their `.__file__` returning a path in the regular site packages, including numpy and matplotlib, when called directly `import numpy; numpy.__file__`, but it errors when matplotlib calls numpy (or when pytest scans through matpotlib and follows it's links to numpy while it's doing test discovery) because it's finding it in a Windows Env (according to the stack trace) and the extensions are different etc. 

The caveat to my thinking is that that app works fine in practice, but this could be because my app doesn't use the extensions that are causing the issue. It also doesn't throw an error when pytest is run from within the project directory, but is passed the test directory directly rather than searching the entire project directory for tests. So this could also be Pytest.

**Comment by jklymak** [comment] 2020-02-05 19:03
Did you install pytest in the same environment?

**Comment by toonarmycaptain** [comment] 2020-02-05 19:47
Yes. From requirements files via: `python3.8 -m pip install -r requirements.txt -r requirements_dev.txt`

**Comment by jklymak** [comment] 2020-02-05 20:32
All matplotlib does is `import numpy as np` so you clearly have your installs crossed in some manner, or you've set some environmental variable.  Suggest this is better suited to discourse.matplotlib.org because this isn't really a bug per-se.

**Comment by toonarmycaptain** [comment] 2020-02-05 20:36
Fair enough. This was a clean install of Ubuntu on WSL in Windows 10 (repeated several times to make sure), then a clean install of python3.8/pip, and then the pip install I mentioned. It is strange. Might be how pytest is searching for tests, but would be bizarre. 

Cheers.

**Comment by tacaswell** [comment] 2020-02-06 22:30
pytest does some very serious magic as part of it's test discovery, as does pycharm.  

I am going to close this as there is nothing we can do about this at the Matplotlib level (as the issue is import finding the wrong enviroment).

This should be moved to https://discourse.matplotlib.org

**Closed by tacaswell** 2020-02-06 22:30 UTC
Labels: Community support
