### ISSUE TITLE
[Bug]: Using pandas dataframe results in 'NoneType' object is not callable error

### ISSUE THREAD

**Issue by frerksaxen** [matplotlib/matplotlib#22333] opened 2022-01-27 13:34 UTC
### Bug summary

There seems to be a conflict between pandas 1.4.0 (or 1.3.5) and matplotlib 3.5.1 with python 3.10.2 (or 3.10.1) on windows.
When I execute the code below I do get the following error: TypeError: 'NoneType' object is not callable
I'm using numpy 1.22.1
Edit: It does work with python 3.9.10

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.DataFrame({}) # comment this out and it'll work just fine
x = np.random.rand(5,2)
plt.plot(x[:,0],x[:,1])
plt.show()
```

### Actual outcome

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\getlimits.py", line 459, in __new__
    dtype = numeric.dtype(dtype)
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backends\_backend_tk.py", line 251, in idle_draw
    self.draw()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 9, in draw
    super().draw()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backends\backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\figure.py", line 2810, in draw
    mimage._draw_list_compositing_images(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\axes\_base.py", line 3020, in draw
    self._unstale_viewLim()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\axes\_base.py", line 776, in _unstale_viewLim
    self.autoscale_view(**{f"scale{name}": scale
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\axes\_base.py", line 2932, in autoscale_view
    handle_single_axis(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\axes\_base.py", line 2895, in handle_single_axis
    x0, x1 = locator.nonsingular(x0, x1)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\ticker.py", line 1654, in nonsingular
    return mtransforms.nonsingular(v0, v1, expander=.05)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\transforms.py", line 2880, in nonsingular
    if maxabsvalue < (1e6 / tiny) * np.finfo(float).tiny:
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\getlimits.py", line 462, in __new__
    dtype = numeric.dtype(type(dtype))
TypeError: 'NoneType' object is not callable
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\getlimits.py", line 459, in __new__
    dtype = numeric.dtype(dtype)
TypeError: 'NoneType' object is not callable

### Expected outcome

The code should just work fine without any errors. Without plt, it works and without pd, it works too. But combined not.

### Additional information

Unfortunately, I cannot install earlier versions of matplotlib.
I do get the same error with pandas 1.4 and 1.3.5 (can't instal earlier versions)

### Operating system

Windows

### Matplotlib Version

3.5.1

### Matplotlib Backend

TkAgg

### Python version

3.10.2

### Jupyter version

visual studio community

### Installation

pip

**Comment by jklymak** [comment] 2022-01-27 13:40
Please restart your kernel -I cannot reproduce with the code above, and there really is no way that code could cause that error.  I also strongly suspect that your underlying issue once you untangle your namespace is #22125

**Comment by frerksaxen** [comment] 2022-01-27 13:50
How do I restart my kernel? I did already restart my computer. Still the same issue.

**Comment by jklymak** [comment] 2022-01-27 13:53
Then start with a fresh jupyter notebook or lab.  The code above, by itself, doesn't produce the error you claim; you never access `df` after you create it, so how could it have anything to do with the error?

**Comment by frerksaxen** [comment] 2022-01-27 14:07
I was using visual studio community. When I start a jupyter notebook it does work. Doesn't make sense to me.

**Comment by jklymak** [comment] 2022-01-27 14:15
> When I start a jupyter notebook it does work.

What do you mean by this?  That you get no error in a fresh notebook?  If so, can we close this?  I suspect your numpy install was crossed between environments.  I'm going to close because we don't really track install errors here, but feel free to ask for more help at https://discourse.matplotlib.org

**Closed by jklymak** 2022-01-27 14:15 UTC
Labels: status: needs clarification, third-party integration: pandas

**Comment by kmodexc** [comment] 2022-04-28 15:17
i have the same error even after deleting and fresh install of my venv. For me its not an option to use jupyter. Is there anyway to fix this? 

```
File "[...]\env\lib\site-packages\numpy\core\getlimits.py", line 462, in __new__
    dtype = numeric.dtype(type(dtype))
TypeError: 'NoneType' object is not callable
```

I dont have anything globally installed.

**Comment by tacaswell** [comment] 2022-04-28 15:57
@kmodexc Can you please provide an minimal example, the full traceback, and the versions of Python, numpy, matplotlib, and pandas you have installed?

The two tracebacks are likely similar, but are hitting slightly different places in numpy but are both at
https://github.com/numpy/numpy/blob/0eaa40db3a2f6bef26c0d7cc28eacf4f6d461917/numpy/core/getlimits.py#L457-L462
```python
    def __new__(cls, dtype):
        try:
            dtype = numeric.dtype(dtype)
        except TypeError:
            # In case a float instance was given
            dtype = numeric.dtype(type(dtype))
```

which if I am reading the traceback right comes from

```python
 np.finfo(float).tiny
```

Does that work for you outside of the context of Matplotlib?

You should also be able to trigger this issue by doing `fig.savefig('/tmp/test.png')` and from there get into an interactive debugger.  It would be very helpful to know what `numeric`, `numeric.dtype`, `dtype`, and `type` are when it fails.


However, all of that said I agree with Jody, this is very likely a local installation issue.  The easiest path is likely to fully uninstall any Python you have on your system (keep going until vscode does not see any Python) and restart from scratch.

**Comment by kmodexc** [comment] 2022-04-28 16:46
@tacaswell 

`np.finfo(float).tiny` works

as i found out it only happens when i use [yappi ](https://github.com/sumerc/yappi) for profiling. Here the minimal example:

```
import pandas as pd
import matplotlib.pyplot as plt
import yappi

with yappi.run():
    dataset = pd.DataFrame(data={
        'x': list(range(10)),
        'y': list(range(10))})
    plt.plot(data=dataset)
    plt.savefig("fig.png")

yappi.get_func_stats().print_all()
```
- Python 3.10.4
- pandas 1.4.2
- matplotlib 3.5.1
- yappi 1.3.3

I could break on that point with pdb and it turns out `numeric.dtype` is None.

```
python -i .\bug_example.py
> c:\users\xxx\source\repos\erroranalytics\bug_example.py(7)<module>()
-> with yappi.run():
(Pdb) b env\lib\site-packages\numpy\core\getlimits.py:462
Breakpoint 1 at c:\users\mariu\source\repos\erroranalytics\env\lib\site-packages\numpy\core\getlimits.py:462
(Pdb) continue
> c:\users\mariu\source\repos\erroranalytics\env\lib\site-packages\numpy\core\getlimits.py(462)__new__()
-> dtype = numeric.dtype(type(dtype))
(Pdb) print(dtype)
<class 'float'>
(Pdb) print(type(dtype))
<class 'type'>
(Pdb) print(numeric)
<module 'numpy.core.numeric' from 'C:\\Users\\mariu\\source\\repos\\ErrorAnalytics\\env\\lib\\site-packages\\numpy\\core\\numeric.py'>
(Pdb) print(numeric.dtype)
None
(Pdb)
```

**Comment by tacaswell** [comment] 2022-04-28 17:13
So, I have a very wild guess that this is an interaction between yappi (with what ever it is doing for tracing), numpy's multi-level import of dtype (it looks like it comes from a c-extension, imported to multiarray then imported to numeric), and pandas (at least provious behavior) of forcibly re-importing numpy.

At the risk of playing hot-potato I think that this needs to be reported to `yappi`.
