### ISSUE TITLE
Histogram range appears to be calculated incorrectly when using "bins='auto'" with 2D data

### ISSUE THREAD

**Issue by seth-a** [matplotlib/matplotlib#8778] opened 2017-06-19 14:52 UTC
### Bug report

**Bug summary**

Using 'auto' to compute the number of bins with 2D data only uses the first column to compute the range.  This causes all other columns to be incorrectly displayed. 

 Calculating histograms using  bins='auto' with numpy gives the correct behavior.
**Code for reproduction**

```python
from pylab import *

# four values to examine
x = randn(1000, 4)*0.1 + arange(4)/7

figure()
ax1 = subplot(211)
plt.hist(x, histtype='step')
legend(['1', '2', '3', '4'])
ax2 = subplot(212)
plt.hist(x, bins='auto', histtype='step')
legend(['1', '2', '3', '4'])

# Match axes so it's clear where the problem is
ax2.set_xlim(ax1.get_xlim())
plt.show()

# Check that numpy doesn't have this bug
_, bins_default = np.histogram(x)
_, bins_auto = np.histogram(x, bins='auto')
assert(np.min(bins_default) == np.min(bins_auto))
assert(np.max(bins_default) == np.max(bins_auto))

```

**Actual outcome**
The range of the histogram corresponds to the range of the last column of data for all columns, see second subplot.

**Expected outcome**
The range of the histogram should correspond to the min/max of all data, as it is in the first subplot of the example code.

**Matplotlib version**

  * Operating System: Ubuntu 
  * Matplotlib Version:  2.0.0
  * Python Version:      3.5.2

**Comment by afvincent** [comment] 2017-06-19 15:15
It looks to me that the problem may come from [this section](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_axes.py#L6102) in `axes.hist`:
```python
for i in xrange(nx):
        # this will automatically overwrite bins,
        # so that each histogram uses the same bins
        m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
```
If the `bins` parameter that is initially passed to `hist` is “auto¹”, then bins becomes a sequence after the first iteration, and this iteration will be kept during the following runs. My first idea would be to just add some supplementary logic (in the loop?) to take care of the case of `bins` being a string.

¹ : maybe I am wrong, but one could pass any string that is valid for `numpy.histogram`, don't we? Is it deliberate to not mention it in `ax.docstring`? Otherwise, it looks like a pretty kind nice but unfortunately hidden feature ^^.

**Comment by WeatherGod** [comment] 2017-06-19 15:44
passing any string was intentional since we knew the plan was for numpy to
add more kinds of auto-ranges. If it isn't documented, it should be
something along the lines of "passes this value directly to numpy.hist()".

**Comment by tacaswell** [comment] 2017-06-19 21:19
Closing as a duplicate of https://github.com/matplotlib/matplotlib/issues/8636

**Closed by tacaswell** 2017-06-19 21:19 UTC

**Comment by afvincent** [comment] 2017-06-20 05:43
Indeed (and the on-going PR #8638 may fix this).
