### ISSUE TITLE
Pyplot: `pyplot.imshow()` exported as embedded png when exporting svg

### ISSUE THREAD

**Issue by tobast** [matplotlib/matplotlib#19984] opened 2021-04-16 12:55 UTC
### Bug report

**Bug summary**

When plotting a heatmap using `pyplot.imshow()`, then exporting the image to svg using `savefig`, the heatmap is exported as base64-encoded embedded png in the svg file. Although this behaviour is reasonable for an actual image being shown using `imshow`, it breaks up image scalability (which is often the point for vector graphics) when plotting a heatmap.

**Code for reproduction**

```python
from matplotlib import pyplot as plt
import numpy as np
import random

BOUND = 100

data = np.zeros((BOUND, BOUND))

for _ in range(BOUND * 1000):
    x = random.randint(0, BOUND - 1)
    y = random.randint(0, BOUND - 1)
    data[x, y] += 1

plt.imshow(data, extent=(0, 5, 0, 5), cmap="Blues", origin="lower")
plt.savefig("test.svg", format="svg", bbox_inches="tight")
```

**Actual outcome**

The SVG file contains embedded png; this can be checked with any text editor. Also note that opening this file, then zooming on the squares' boundaries on the heatmap results in a blur; while the axes are not blurred by zooming (being vector images).

**Expected outcome**

The heatmap part of the svg is actually an "array" or vector squares, without borders, of the desired colour; thus, it is possible to scale it to any extent without blurring.

**Alternatives**

Exporting the same heatmap to `pdf` instead of `svg` leads to a weird, seemingly vector graphic (zoomable without blur) result where each square of the heatmap has a grey border. Somehow, this is not the case with any PDF viewer; for instance, `zathura` seems to render the pdf image fine. However, such a pdf included in a LaTeX document compiled with `xelatex` with a regular `\includegraphics` yields those weird borders.

**Matplotlib version**

  * Operating system: ArchLinux `Linux 5.11.13-arch1-1 #1 SMP PREEMPT Sat, 10 Apr 2021 20:47:14 +0000 x86_64 GNU/Linux`
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): GTK3Agg
  * Python version: 3.9.3
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

Tested with matplotlib installed both from ArchLinux repositories and pip.

**Comment by QuLogic** [comment] 2021-04-16 22:58
`imshow` exists to display images; it is inherently not a vector. How it is interpolated at higher zoom is up to the image/PDF viewer. I think what you want is effectively #10112.

**Comment by WeatherGod** [comment] 2021-04-17 15:33
Perhaps one of the pcolor() functions would be better suited for SVG output
(modulo the half-step shift in the coordinate system)?

**Comment by jklymak** [comment] 2021-04-23 21:33
I'm going to close as essentially a duplicate of #10112, but please feel free to comment there if there are more subtleties.

**Closed by jklymak** 2021-04-23 21:33 UTC
Labels: backend/svg

**Comment by KOLANICH** [comment] 2021-05-19 06:02
Why is it closed? It is about imshow behavior for heatmaps, not about antialiasing. I mean that it is not good that 3x3 or 4x4 or 10x10 heatmap is rendered as a base64 image, small heatmaps when exported into SVG should remain vector. Whether to keep them vector should depend on their size and geometry, svging them should not make the size much worse than rasterizing them, and there should be a mode to enforce svg. The areas of same colors adjacent to each other should likely be merged into a single path for svg purposes.

**Comment by QuLogic** [comment] 2021-05-19 06:10
As I said before, `imshow` is _image_ show; it is not a vector and there are no paths to draw. If you want vectors, then do not use `imshow`.

**Comment by KOLANICH** [comment] 2021-05-19 06:47
`imshow` seems to be used by `matshow`, which is `matrix show`. While it can be possible to put the logic causing rendering as vector areas into `matshow` itself, I see no real reason not to put it into `imshow` instead.

**Comment by tobast** [comment] 2021-05-19 08:34
The main problem, in my opinion, is that `imshow` is the advertised solution for plotting heatmaps. It indeed makes sense to render *bitmap images* as embedded png, and this seems to be the original purpose of `imshow` indeed. However, it also makes sense to expect a way to plot a heatmap, that is, a "bitmap image with coarse pixels" (plus axes, etc.), as vector graphics : my usecase was to render a heatmap to include in an article, without prior knowledge of the size I planned the final image in the document to be. This further makes sense given what @KOLANICH points out.

One solution I can see would be to add an optional parameter, `False` by default, controlling whether the figure is rendered in vector graphics -- but this doesn't seem to integrate nicely with matplotlib's workflow. Another solution might be to add a `heatmap`, or even reworked `matshow` function, working just as `imshow` but in a vector- or bitmap-based fashion, depending on the rendering backend used.

**Comment by jklymak** [comment] 2021-05-19 13:18
I agree there is an example that uses imshow to make a heatmap, but I wouldn't say we advertise imshow as the "proper" way to make a heatmap.  If you want vector graphics, use pcolormesh. I would not be in favour of adding a flag to imshow to provide the functionality of another method.

**Comment by KOLANICH** [comment] 2021-05-19 13:21
If `imshow` is an "improper" way to make a heatmap, then why does `matshow` use it under the hood instead of the "proper" way?

**Comment by jklymak** [comment] 2021-05-19 13:27
As stated in the docs, matshow is just a convenience wrapper for imshow that sets different default kwargs.

**Comment by WeatherGod** [comment] 2021-05-19 13:44
Just to point out, we do have several plotting methods that take a kwarg of
"rasterized", which default to False. It isn't a huge stretch to consider
imshow() having a "rasterized" kwarg set to True by default. Now, how
feasible is it to have the returned object be treated in a vectorized
manner when drawn is a different question, as I imagine that might require
a fair amount of work to do (and I don't support changing the return type
based on the value of an input parameter).

I find the discussion about matshow() and heatmaps to be a distraction. To
me, heatmaps and matrix shows do not necessarily mean that they should be
vectorized, wheteras line plots do imply for me vectorization by default
where possible. So, I am not against adding a rasterized=True to
imshow()/matshow(), but I would not be surprised if the amount of work
required to make it happen is larger than what most devs here would be
willing to take on, especially when there is a decent alternative with
pcolormesh() (and I think hexbin() is vectorized by default, too?).

Ben
