### ISSUE TITLE
[ENH]: support `pgf.rcfonts: False` option for non-pgf backend

### ISSUE THREAD

**Issue by Fmajor** [matplotlib/matplotlib#28921] opened 2024-10-02 11:54 UTC
### Problem

I try to make a multi-color title like `ax.set_title("\textcolor{red}{red} \textcolor{blue}{blue} \textcolor{green}{green}")`
I setup rcparams as
```
  plt.rcParams.update({
    "text.usetex": True,
    "text.latex.preamble": r"\usepackage{xcolor}" + "\n" + r"\usepackage{amsmath}",
    "pgf.rcfonts": False,
    "pgf.preamble": r"\usepackage{xcolor}" + "\n" + r"\usepackage{amsmath}",
  })
```

when I set `matplotlib.use('pgf')`, I can get multi-color title in the saved `fig.pdf`
but when I use the default backend (any one but pgf), when i try to `plt.show()`, I always get `black` text in title.
I check the cache dvi file in `~/.cache/matplotlib/tex.cache/xx/xx/hash.dvi`, the text have color
It seems that matplotlib read the dvi file and reset the color based on the `text.color` parameter, and as we have `pgf.rcfont==False`, we can skip the color reset process and get colorful title when use the `pgf` backend.

can we add some options to also disable the color reset process in other backends? to directly use the div (compiled from .tex file) without reset its color based on `text.color` parameters, just like the `pgf.rcfont` setting?

### Proposed solution

add new rc params like `text.latex.rcfonts`, default is `True`, and if one want to reserve the color in cached `.div` file, they should set it to `False` 

also add `rcfonts` options in all related function, like `ax.text`

**Comment by anntzer** [comment] 2024-10-02 19:46
Duplicate of #6724, AFAICT (see in particular https://github.com/matplotlib/matplotlib/issues/6724#issuecomment-932273421).

**Closed by anntzer** 2024-10-02 19:46 UTC
Labels: New feature, status: duplicate, topic: text/usetex
