### ISSUE TITLE
background color of text is forground color on MacOSX

### ISSUE THREAD

**Issue by mbakker7** [matplotlib/matplotlib#4609] opened 2015-07-09 16:44 UTC
With MacOSX backend, the following fails:

from pylab import *
plot([1, 2, 3])
text(1, 2, 'Hello', backgroundcolor = 'red')

This plots a nice red box but no text. It looks like the backgroundcolor is set as the foreground. 
mpl version 1.4.3
backend: MacOSX
Works correctly with Qt4Agg and, as reported on mailinglist, works correctly with TkAgg

**Comment by jenshnielsen** [comment] 2015-07-09 16:45
Confirming that I see the same with the OSX backend

**Comment by jenshnielsen** [comment] 2015-07-09 16:49
This could be related to #4024, see #4202 too

**Comment by efiring** [comment] 2015-07-09 19:28
#4202 doesn't fix it.  This looks like a different problem. Strangely, the text is very faintly visible as a slight lightening of the red.  This is easier to see if you use `fontsize=30`. At least at the Python level, the default text color is not being overwritten by the background.  I don't know what is happening inside the extension code.
attn: @mdehoon 
```
In [16]: tt = text(1,2, 'hello', backgroundcolor='red', fontsize=30)

In [17]: tt.get_color()
'k'
```

**Comment by mdehoon** [comment] 2015-07-09 21:11
I can't reproduce this bug. It's working fine for me with the MacOSX backend, matplotlib version 1.4.3.

**Comment by efiring** [comment] 2015-07-09 21:24
@mbakker7 and @mdehoon which Python versions are you using?  I tested with python 3.  We have had several cases where the change between py2 and py3 in the order of iteration through a dictionary (such as kwargs in a function call) caused problems under py3.

**Comment by mdehoon** [comment] 2015-07-09 22:17
@efiring  Thanks! That is indeed the issue. With Python3, I am seeing this bug. Let me look into this.

**Comment by mdehoon** [comment] 2015-07-10 16:51
See pull request #4617 for a bug fix.

**Comment by jenshnielsen** [comment] 2015-07-11 15:17
Fixed by #4617

**Closed by jenshnielsen** 2015-07-11 15:17 UTC
Labels: GUI/osx

**Comment by mbakker7** [comment] 2015-07-11 20:24
Sorry for the late reply: I have the problem with Python 2.7.9-1. Got the
bug on two separate Macs, one with mpl 1.4.3, one with mpl 1.4.0, so it has
been around for a little while.

Thanks for looking into this,

Mark

**Comment by jenshnielsen** [comment] 2015-07-11 20:41
@mbakker7 Thanks for the confirmation

If you have a chance please test master and report it it fixes it for you
