### ISSUE TITLE
WXAgg embedded navigation zoom, home, back not working

### ISSUE THREAD

**Issue by digitalnumeric** [matplotlib/matplotlib#4109] opened 2015-02-16 23:17 UTC
I have a figure canvas and navigation bar embedded in a wx.Dialog.  In matplotlib version 1.2.1 and earlier the zoom, home, back (and pan) all worked fine.  If I upgrade to 1.3 (or 1.4.2) zoom, home, and back stop working.  Only pan works.   Any time I zoom, the zoom rectangle is drawn but nothing happens.  The zoom rectangle remains on the screen after I release the mouse button.   If I then switch to pan and left-click to pan the zoom takes effect.   Same thing with the home and back buttons.  If I click them nothing happens until I switch to pan and actually left click and pan then they take effect.

I also tried this with the user interface example: embedding_in_wx2.py
Running it alone it is fine.  If I put it in my app and do the following:

``` python
    def OnShowClicked(self, event):
        frame = CanvasFrame()
        frame.Show(True)
```

The window shows correctly, but the zoom, home, back don't work just as I described above.

I looked through the changes between 1.2.1 and >=1.3 but I didn't see anything that would point to this.  What changed between these versions that might causes this issue.

How do I work around this issue?  Is there an example somewhere that shows the right way to do things now to get zoom, home, back, etc. working again?

Thanks.

**Comment by tacaswell** [comment] 2015-02-16 23:23
what os?  Does the problem exist with 1.4.3?

**Comment by tacaswell** [comment] 2015-02-16 23:26
And am I understanding correctly that the demo works correctly (in that pan/zoom/the navigation buttons all work) but if you embed the demo on another application it does not work correctly?

**Comment by digitalnumeric** [comment] 2015-02-16 23:27
Windows 7 Pro 64-bit
The latest stable I see is 1.4.2
Yes the demo works correctly until it is embedded

**Comment by tacaswell** [comment] 2015-02-16 23:38
I just made the 1.4.3 windows binaries visible https://sourceforge.net/projects/matplotlib/files/matplotlib/matplotlib-1.4.3/  1.4.3rc1 is almost identical and would work too.

**Comment by tacaswell** [comment] 2015-02-16 23:39
It is not clear no me why this is a bug in mpl and not a bug in how you are doing the embedding.  Can you provide us with a _minimal_ example that fails to work?

**Comment by digitalnumeric** [comment] 2015-02-16 23:57
I am using wx version 2.8.12.1 (msw-unicode)
Right now all I know is that the code works fine with the old version 1.2.1 of mpl with wx 2.8.12.1.
If I leave all else the same and just upgrade to mpl > 1.2.1 I see the issue.
I will try to get you a minimal failing example

**Comment by tacaswell** [comment] 2015-02-17 00:18
My guess is that this commit is related: f237a74db820fd9d06d24075b21fc7c8debda1df

**Comment by tacaswell** [comment] 2015-02-17 00:19
Which is a cherry-pick of 0a160ad7982ba3a783b8912e052d2c82b94a5f41 which was merged to master in c001797cd2868f53c2014eb441af5a73df195139 as part of #2316

**Comment by digitalnumeric** [comment] 2015-02-17 00:56
I wonder if the functionality change could be related to this change: [#1849](https://github.com/matplotlib/matplotlib/pull/1849)

**Comment by efiring** [comment] 2015-02-17 00:58
#2316 is a pretty standard way of dealing with the deprecation of Wx.PySimpleApp.  I can't imagine how it could cause the symptoms listed.  Instead, I suspect it is related event handling and drawing.  Yes, #1849 seems a likelier candidate.  @digitalnumeric can you check that directly? Or bisect?

**Comment by tacaswell** [comment] 2015-02-17 01:07
That PR was close with out being merged as near as I can tell...

**Comment by efiring** [comment] 2015-02-17 07:14
Oops! You are right, of course.

**Comment by digitalnumeric** [comment] 2015-02-17 15:45
I verified the issue on a second Windows 7 machine this morning.   I did a fresh Python 2.7.9 install with mpl 1.4 and verfied the issue was present.  I then uninstalled mpl 1.4 and installed mpl 1.2.1 and the issue was gone.

I haven't been able to re-create the issue in a simple form other than switching from my actual data to a sin wave which gives the same results.   The image below shows how the zoom window just stays on the screen but zooming does not occur.
![zoom_window](https://cloud.githubusercontent.com/assets/11036731/6230924/f25751d0-b688-11e4-9ac1-1f70cb1c7e1d.png)

If I do a zoom the rectangle stays and the UI does not update.  If I click pan in the toolbar then left click and begin to drag the mouse the previous zoom takes effect immediately then the pan continues.

It seems like the canvas (and maybe toolbar) are not communicating or not updating on windows events.  

Was something changed in mpl in the way windows events were handled with the figure/canvas/navigation after 1.2.1 was released?

**Comment by digitalnumeric** [comment] 2015-02-17 15:52
FYI: I tried to access the 1.4.3 link tacaswell provided but I got "The sourceforge.net website is temporarily in static offline mode."  It looks like Christoph Gohlke site has it so I will get it from there to test with.

**Comment by digitalnumeric** [comment] 2015-02-17 16:04
Question: For mpl is there any benefit to using an exe installer over a wheel (whl)?  Does the exe do anything other than copy files to the correct location?

**Comment by mdboom** [comment] 2015-02-17 16:32
Cc: @cgohlke on the Windows question.

**Comment by digitalnumeric** [comment] 2015-02-17 16:43
I installed a 1.4.3 wheel from Christoph Gohlke's site and the issue is gone.   Below is am image showing the zoom windows.  After I released the mouse button it zoomed as expected.
![zoom_window2](https://cloud.githubusercontent.com/assets/11036731/6232167/dbcee4e4-b68f-11e4-9357-6535c1358072.png)

The home and back buttons work now as well.  I see the zoom window has changed from a black rectangle to a purple translucent window.  Nice.   What else could have changed between 1.4.2 and 1.4.3 that could have made the issue go away?

That main issue is gone but a smaller zoom related one has now appeared.   I have two subplots.
```python
self.axes_1 = self.figure.add_subplot(211)
self.axes_2 = self.figure.add_subplot(212) 
```
Zooming in the top window the purple zoom rectangle is always drawn.   Zooming in the bottom rectangle the purple zoom window is only sometimes drawn.   I verified this on two machines.  I will see If I can get a simple sample to do it as well.

**Comment by digitalnumeric** [comment] 2015-02-17 17:18
Update:  I have another graph with 3 subplots.
```python
self.axes_1 = self.figure.add_subplot(311)
self.axes_2 = self.figure.add_subplot(312)
self.axes_3 = self.figure.add_subplot(313)
```
Zooming on the first/top two always draws the purple zoomed rectangle.  The last one (bottom one) only draws it sometimes.  They all always zoom, but the rectangle is not always drawn for the bottom graph.  It is intermittent.

**Comment by tacaswell** [comment] 2015-02-19 04:00
@RobinD42  Any advice?

**Comment by RobinD42** [comment] 2015-02-20 00:23
Nothing comes to mind at the moment.  Is there a small runnable sample that can be used to demonstrate the problem?

**Comment by petehuang** [comment] 2017-01-09 16:36
Pinging again to repeat @RobinD42's request - is there a self-contained snippet we can run to re/confirm the issue?

**Comment by anntzer** [comment] 2017-12-15 19:11
Closing as the main issue appears to be solved and there is no repro for the second issue.
Feel free to request a reopen with additional information.

**Closed by anntzer** 2017-12-15 19:11 UTC
Labels: GUI/wx, needs confirmation
