### ISSUE TITLE
 Backend MacOSX keyboard not working

### ISSUE THREAD

**Issue by agallenne** [matplotlib/matplotlib#8982] opened 2017-08-02 20:39 UTC
Hi,

I am on MacOS and using the MacOSX backend. When a plot is displayed and I want to save it, I cannot change the name or go right/left in the text entry, the keyboard is not working. It was working properly before with matplotlib 1.5.1, now I upgraded to 2.0.2 (with anaconda). For now I am using the PyQt5 backend, which is OK, but if I move my plot to my second monitor (higher resolution), the window size stays the same but not the plots which is over-zoomed :-/ Any ideas to make the MacOSX backend works or solved the "dpi" issue for PyQt5?

  * Operating System: Mac OSX 10.12.6
  * Matplotlib Version: 2.0.2
  * Python Version: 2.7.13
  * Jupyter Version (if applicable):
  * Other Libraries:

**Comment by WeatherGod** [comment] 2017-08-02 20:42
We are working on a fix for the mixed resolution monitor problem (or it
might have just been merged recently).

Are any keyboard bindings working, or is the problem just for the text
entry widgets?

**Comment by agallenne** [comment] 2017-08-02 20:49
Keyboard bindings are not working either. Other things like zooming seem to work correctly.

**Comment by dstansby** [comment] 2017-08-02 21:04
#8931 fixed the mixed resolution issue on Qt5. I'm not seeing the same issues as you on the OSX backend, so maybe it's a python 2 only issue.

**Comment by agallenne** [comment] 2017-08-02 21:23
Ok thank you very much. Do I have to make the changes from #8931 in the .py files myself or I can download them somewhere?

**Comment by agallenne** [comment] 2017-08-02 21:45
Well, if I copy and past the corresponding corrected file (backend_qt5.py), I have the following error when starting ipython: "ImportError:  cannot import name _Backend".
Am I doing something wrong!

**Comment by anntzer** [comment] 2017-08-02 22:42
That file also depends on other files that have changed since 2.0.2 has been released, so just copying that file will not work.  I'll let the OSX devs comment on the best way to install off master.

**Comment by tacaswell** [comment] 2017-08-03 03:08
How exactly 

The problem with mac may be related related to IPython's switch from readline -> prompt toolkit (but if zoom is working, that may not be the issue).

Have you tried doing `%matplotlib` to make sure the event loop integration is set up correctly?

There are also issue with osx + 'framework' builds see http://matplotlib.org/faq/osx_framework.html#osxframework-faq

**Comment by agallenne** [comment] 2017-08-03 13:41
Zoom is indeed working for the macosx backend (note that I used a terminal to run python with: ipython --pylab). It worked before with previous version of matplotlib and ipython. What about PyQt5 and the changes from  #8931, how can I make them work on my computer?

**Comment by WeatherGod** [comment] 2017-08-03 13:44
Those changes are in master now, so you could checkout the master branch
and do a fresh install from source.

**Comment by agallenne** [comment] 2017-08-03 14:14
I did it yesterday and it did not change anything unfortunately.

**Comment by agallenne** [comment] 2017-08-04 20:11
Ok, so I removed all matplotlib versions I had in my .../site-packages/ directory, and installed the fresh one. The PyQt5 mixed resolution display (#8931) issue is fixed for me now. Thanks.

**Comment by tacaswell** [comment] 2017-08-05 18:07
@mdehoon Any guidance on what is wrong with the native backend?

**Comment by agallenne** [comment] 2017-08-07 16:36
Now that I removed some matplotlib versions, I have the error saying that python is not installed as a framework, so back to the link you sent.

**Comment by dstansby** [comment] 2017-08-07 17:24
With conda you can do `conda install python.app`, and then using `pythonw` in place of `python` at the command line should fix that problem.

**Comment by agallenne** [comment] 2017-08-07 17:29
I use ipython --pylab

**Comment by WeatherGod** [comment] 2017-08-07 17:35
side-note: the use of --pylab is discouraged and has been for some time. It
is fine for one-off interactive sessions that feel like matlab, but because
the --pylab is at the command-line, any code in the ipython history
implicitly depends on that action, which may not be clear to others if you
share your code snippets.

**Comment by dopplershift** [comment] 2017-10-23 21:53
I can't get IPython to run with the osx backend.

If I run a plot from the command line using `pythonw`, I can't reproduce any problems with the keyboard. The default keybindings work and saving a figure is fine.

**Comment by tacaswell** [comment] 2017-10-23 23:43
The issue in IPython is likely missing integration with prompt toolkit (attn @Carreau )

**Comment by jklymak** [comment] 2017-11-06 22:47
@dopplershift I can't get ipython to rin the macos backend either.  It gives me the "Framework required" error...

**Comment by tacaswell** [comment] 2017-11-07 06:28
I observed this issue on a number of systems today, but did not get details of IPython / OSX  versions, but mostly with mpl 2.1 (I think?).

**Comment by efiring** [comment] 2017-11-08 02:01
@jklymak, in a conda environment, this works for me with matplotlib 2.1.0.post222+gad730d131 (which is just what I happen to have in that environment at the moment):
```
(test) efiring@manini2:~/currents/temp/merger_qt2$ pythonw `which ipython`
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %matplotlib osx

In [2]: import matplotlib.pyplot as plt

In [3]: plt.plot([1,2,3,2,1])
[<matplotlib.lines.Line2D at 0x115e157b8>]
```

**Comment by jklymak** [comment] 2017-11-08 02:19
Ah OK, didn't think to try a magic!  Thanks!

**Comment by jklymak** [comment] 2017-11-08 02:23
Oh, and the `which python` trick.  OK that works.  But...

**Comment by efiring** [comment] 2017-11-08 04:42
...but the buttons don't work quite right.  Very strange.  Zoom and pan seem to work, but home, backwards, and forwards are erratic.

**Comment by dopplershift** [comment] 2017-11-13 20:01
Both the forward/back/home buttons and the keyboard events are working fine for me with the current v2.1.x branch in IPython (using `%matplotlib osx`). I'm going to close this out, but feel free to re-open if you find this is a problem with 2.1.1 when that is released.

**Closed by dopplershift** 2017-11-13 20:01 UTC
Labels: GUI/osx, third-party integration
