### ISSUE TITLE
 `zorder=None` not properly handled

### ISSUE THREAD

**Issue by jsh9** [matplotlib/matplotlib#9785] opened 2017-11-14 22:49 UTC
Matplotlib developers:

I have some feature requests and/or questions about the grid behaviors in matplotlib v2.0+:

(1) Is it possible to set the default grid line to even lighter gray, and even thinner line width? Just like the style in MATLAB? The current new Matplotlib defaults generate grid lines that look too pronounced.

In fact, when using Matplotlib 2.0+, I always use `plt.grid(ls=':')` instead of just `plt.grid()`. It looks much better.

(2) The `zorder` behavior, if set to None, is undefined, or at least not documented clearly.

For example, I tried the following codes respectively:

`plt.figure(); plt.plot([0,1],[0,1],lw=10); plt.grid()`
`plt.figure(); plt.plot([0,1],[0,1],lw=10,zorder=None); plt.grid()`
`plt.figure(); plt.plot([0,1],[0,1],lw=10); plt.grid(zorder=None)`
`plt.figure(); plt.plot([0,1],[0,1],lw=10,zorder=None); plt.grid(zorder=None)`

and I am getting confusing results.

There is indeed some needs to pass `None` to `zorder`, especially when designing wrapper functions where `zorder` sometimes needs to be specified by the user, and sometimes doesn't.

**Comment by anntzer** [comment] 2017-11-14 22:55
xref https://github.com/matplotlib/matplotlib/pull/9094 re: zorder.

**Comment by jsh9** [comment] 2017-11-14 23:04
I tried this:

`plt.figure(); ax=plt.axes(); plt.plot([0,1],[0,1],lw=10,zorder=None); plt.grid(); ax.set_axisbelow(True);`

But the line is still below the axes. Apparently `zorder=None` within `plt.plot()` sends the line to the most bottom layer...

Shouldn't `zorder=None` within `plt.plot()` just work as if we did not invoke this argument at all?

**Comment by anntzer** [comment] 2017-11-14 23:07
Non-numeric zorder errors out on Py3 because they can't, well, be compared with numbers.
On Py2 None is sorted before numbers hence the observed behavior.  I honestly don't care enough about Py2 anymore to fix that...

**Comment by ImportanceOfBeingErnest** [comment] 2017-11-15 17:48
@anntzer I really hope you do care about python 2 still. According to [this statics](https://www.jetbrains.com/pycharm/python-developers-survey-2016/)
![image](https://user-images.githubusercontent.com/23121882/32851337-00dae29a-ca35-11e7-8b2e-a44e1e0690f0.png)
it is still used more than python 3. Also see [here](https://hynek.me/articles/python3-2016/).

So there should be a defined behaviour of `zorder=None`, independent on the version of python in use. Why not simply throw an error as well?

**Comment by jklymak** [comment] 2017-11-15 18:03
@anntzer wasn't saying not to fix it.  He was saying he wasn't going to fix it.  I'm sure a sensible PR would be welcome.  But I think the point is that `zorder=None` is undefined, so don't do that.

**Comment by jsh9** [comment] 2017-11-15 18:13
I guess there is some need to update the documentation containing `zorder`, adding a note for Python 2 users in the documentation. Or Matplotlib can raise a warning message when Python 2 users try to set `zorder=None`

**Comment by WeatherGod** [comment] 2017-11-15 18:19
The general rule in matplotlib is that "*None* means do the default thing".
So, I agree that not specifying zorder and specifying zorder=None should be
equivalent.

**Comment by anntzer** [comment] 2017-11-15 18:58
To be clear: I will obviously not prevent anyone from fixing the issue on py2.

**Comment by tacaswell** [comment] 2017-11-15 19:07
We are committed to python2 support through mpl2.2 (early next year) and bug fixes on that branch until 2020.  The level of back-ported support to 2.2.x will depend on volunteer interest, but I am personally committed to does-not-import / segfault type bug fixes.

That said, this is not a python2/python3 bug, the issue is that `zorder=None` is not being properly handled in any version.  It should, as @WeatherGod says, mean 'do the default thing' as the OP expected.

@jsh9 You can use rcparams / style sheets to set the default gridline style and color https://matplotlib.org/users/customizing.html

**Comment by jsh9** [comment] 2017-11-15 19:34
@tacaswell Thanks for the comments.

Yes, I am aware of rcparams or style sheets, but it is somewhat cumbersome (for example, I have to revert the styles back for other users of my scripts, because I don't want to mess up their flavor of plotting styles).

The reason I'm bring this issue up is that I think the Matplotlib default style leaves some aesthetic room to be desired. And making the default style more pleasing can attract more potential users. (Of course, this is a somewhat subjective discussion, and I am open to hearing other people's opinion about this :-)

**Comment by jklymak** [comment] 2017-11-15 19:38
I think thats why there are style files - so you can set the grid however you want.  The default styles were just changed for 2.0, presumably to someone's aesthetic delight.  So my guess is that they won't be reconsidered again for a while.

**Comment by tacaswell** [comment] 2017-11-15 20:28
The style context managers can be helpful for ensure the style gets reverted.

Changed the issue title to better reflect the bug that needs to be fixed.

**Comment by jsh9** [comment] 2017-11-15 22:09
Not only `plt.grid` does not handle `zorder=None` properly, but also `plt.plot` and maybe other functions, am I correct?

**Comment by tacaswell** [comment] 2017-11-16 01:09
@jsh9 :sheep: did not read carefully enough or test

**Comment by afvincent** [comment] 2017-11-17 03:53
@tacaswell Should this issue be closed since #9793 was merged?

**Comment by tacaswell** [comment] 2017-11-17 15:51
It will auto-close when the merge up to master happens

**Comment by jklymak** [comment] 2017-11-17 18:42
But isn't #9793 merged already?  I'll close, and re-open if you meant something else...

**Comment by afvincent** [comment] 2017-11-17 20:00
@jklymak Well I think that @tacaswell is used to target “the right branch” for his PRs ^^. For example, #9793 was not merged on the *master* branch, so this might be the explanation.

**Comment by jklymak** [comment] 2017-11-17 20:02
Ohhhh.  I see.  He merged it into 2.1.x.  My mistake...

**Closed** 2017-11-18 22:12 UTC
