### ISSUE TITLE
`imshow` with datetime coordinate fails

### ISSUE THREAD

**Issue by shaharkadmiel** [matplotlib/matplotlib#23136] opened 2022-05-25 13:42 UTC
When trying to plot a 2d DataArray and setting the extent of one of the two axis with a numpy datetime64 value, the following error is returned:

```
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

I suggest adding the following code after this line https://github.com/matplotlib/matplotlib/blob/ca4958b8d755c303cfd0617556530da08094bab5/lib/matplotlib/image.py#L972 :

```python
from matplotlib.dates import date2num
extent_ = []
for value in extent:
    if np.issubdtype(value.dtype, np.datetime64):
        value = date2num(value)

    extent_.append(value)
```

This is linked to an issue I started on xarray:
https://github.com/pydata/xarray/issues/6629

**Comment by jklymak** [comment] 2022-05-25 14:00
Thanks, this is a duplicate of:
https://github.com/matplotlib/matplotlib/issues/22105

**Closed by jklymak** 2022-05-25 14:00 UTC
