### ISSUE TITLE
error import matplotlib.pyplot as plt

### ISSUE THREAD

**Issue by CBrauer** [matplotlib/matplotlib#10277] opened 2018-01-21 19:48 UTC
Hello,

I'm trying to run the CNTK tutorial notebook: CNTK_101_LogisticRegression.
I cannot import matplotlib.pyplot

```python
(base) C:\CNTK-Samples-2-3-1\Tutorials>python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Charles\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "C:\Users\Charles\Anaconda3\lib\site-packages\matplotlib\colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "C:\Users\Charles\Anaconda3\lib\site-packages\matplotlib\contour.py", line 21, in <module>
    import matplotlib.font_manager as font_manager
  File "C:\Users\Charles\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 58, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: DLL load failed: The specified procedure could not be found.
>>> quit()

(base) C:\CNTK-Samples-2-3-1\Tutorials>conda install matplotlib
Solving environment: done

# All requested packages already installed.

(base) C:\CNTK-Samples-2-3-1\Tutorials>python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Charles\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "C:\Users\Charles\Anaconda3\lib\site-packages\matplotlib\colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "C:\Users\Charles\Anaconda3\lib\site-packages\matplotlib\contour.py", line 21, in <module>
    import matplotlib.font_manager as font_manager
  File "C:\Users\Charles\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 58, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: DLL load failed: The specified procedure could not be found.

>>> import matplotlib
>>> matplotlib.__file__
'C:\\Users\\Charles\\Anaconda3\\lib\\site-packages\\matplotlib\\__init__.py'
>>> print(matplotlib.__version__)
2.1.1

```
Any help will be greatly appreciated.

Charles

**Comment by ImportanceOfBeingErnest** [comment] 2018-01-21 20:40
This error usually stems from having non-matching binaries installed. A solution can be to uninstall matplotlib and any dependencies completely and reinstall everything. 

Note that this is (almost certainly) not a matplotlib problem. It may be a problem with anaconda, or with something else you have installed incorrectly. The information at hand does not suffice to know what exact problem there is. Once more information on system, versions etc. are collected, such questions are often being answered on Stackoverflow where chances are higher to find someone with a similar system knowing a solution to the problem.

**Comment by tacaswell** [comment] 2018-01-21 21:00
See the discussion at https://github.com/ContinuumIO/anaconda-issues/issues/1672  and  https://github.com/ContinuumIO/anaconda-issues/issues/6689 .  A number of people there have implicated CNTK as being involved with this issue.

Closing this as it looks like this is a packaging / installation issue outside of our control.

duplicate of https://github.com/matplotlib/matplotlib/issues/10252

**Closed by tacaswell** 2018-01-21 21:00 UTC

**Comment by ceefour** [comment] 2018-02-16 03:40
I also got this, and my solution was: `pip uninstall cntk`

As a precaution, I also made sure I used conda's instead of pip's `matplotlib` : 

```
pip uninstall matplotlib
conda install -f matplotlib
```

**Comment by mithse** [comment] 2018-05-26 06:07
This is what I did on Windows to make pyplot work. 

`pip uninstall matplotlib`
`python -m pip install --upgrade pip`
`pip install matplotlib`

**Comment by linika** [comment] 2018-06-17 13:58
For me still not working please suggest

**Comment by muj1og** [comment] 2018-09-10 12:30
thank you Ceefuor I was having the same problem and
 your solution  just worked well 👍 
open terminal and just type : conda install -f matplotlib

**Comment by sahuvaibhav** [comment] 2018-11-30 12:13
> > This is what I did on Windows to make pyplot work.
> > `pip uninstall matplotlib`
> > `python -m pip install --upgrade pip`
> > `pip install matplotlib`
> 
> This Method work for matplotlib can not install device

finally this worked for me

**Comment by ShibaCoder** [comment] 2019-01-07 06:07
pip uninstall matplotlib
python -m pip install --upgrade pip
pip install matplotlib
WORKING
THNX

**Comment by xiangzz** [comment] 2019-02-16 17:09
> This is what I did on Windows to make pyplot work.
> 
> `pip uninstall matplotlib`
> `python -m pip install --upgrade pip`
> `pip install matplotlib`

Thanks, it works!
Windows 7
Anaconda 3 (python version=3.7)

**Comment by fuhaoda** [comment] 2019-03-07 03:09
> This is what I did on Windows to make pyplot work.
> 
> `pip uninstall matplotlib`
> `python -m pip install --upgrade pip`
> `pip install matplotlib`

also works in MacOS

**Comment by LiShi2269** [comment] 2019-06-15 03:46
> This is what I did on Windows to make pyplot work.
> 
> `pip uninstall matplotlib`
> `python -m pip install --upgrade pip`
> `pip install matplotlib`

It does not work for me

**Comment by anilpandey071999** [comment] 2019-06-25 16:17
> 
> 
> > This is what I did on Windows to make pyplot work.
> > `pip uninstall matplotlib`
> > `python -m pip install --upgrade pip`
> > `pip install matplotlib`
> 
> It does not work for me

**Comment by PandaSource** [comment] 2019-07-09 11:49
u should be using pip3 and not pip since ur using Python 3.6.3

**Comment by PandaSource** [comment] 2019-07-09 11:51
use pip3 for installing modules for Python3

for pip3 installation:
`sudo apt-get install python3-pip`

for matplotlib module installation:
`pip3 install matplotlib`

**Comment by herkadek** [comment] 2019-08-20 08:45
Today I had the same import error (after using matplotlib for quite a while). Employing the Dependencies application (https://github.com/lucasg/Dependencies) for the file ft2font.cp37-win_amd64.pyd in my matplotlib installation revealed that the required DLL freetype.dll was no longer available in the python installation. 
I copied this file from a similar Windows 10/Anaconda installation into the corresponding path ([Anaconda]\Library\bin
This solved the issue.

**Comment by xavnu** [comment] 2020-03-12 18:03
hello friends,

I've got the same problem , I'm using an iMac with the Python3 and the Editor : visual Studio code ...

maybe someone can thell me how i can install a packet via shell/ terminal 👍 

Thanks , you can answer in german and in english

**Comment by tacaswell** [comment] 2020-03-12 22:56
Please direct future replies to https://discourse.matplotlib.org/c/community/install

In you post please include:
 - your operating system
 - who provided your Python and how you installed it
 - the Python version
 - how you installed Matplotlib
 - what version of Matplotlib you were trying to install.
