### ISSUE TITLE
Time zone handling in plots not clear

### ISSUE THREAD

**Issue by lebigot** [matplotlib/matplotlib#2893] opened 2014-03-12 04:36 UTC
The way plots handle time zones should be clarified.

I understood from the documentation (http://matplotlib.org/api/dates_api.html#module-matplotlib.dates) that time zones were taken into account, but this does not appear to be always true (http://stackoverflow.com/questions/22255356/how-to-handle-times-with-a-time-zone-in-matplotlib?noredirect=1#comment33839427_22255356).

It would be good to make the above documentation more explicit. Linking to it in the relevant function documentation (plot, scatter,…) would be good too.

**Comment by LilCthulu** [comment] 2021-10-02 01:32
@tacaswell Could I give this a try?

**Comment by jklymak** [comment] 2021-10-04 07:32
@LilCthulu I would not tackle this without a clear understanding of what the issue is.  Matplotlib date handling has seen substantial changes since 2.2.  I'm actually going to close this as out of date.  If someone still has issues with timezone handling, please do open a new issue with a self-contained minimal example.  Also, please do not include pandas, they have their own date handling - we only guarantee things for `datetime` objects (and datetime64, but datetime64 doesn't have timezones).

**Closed by jklymak** 2021-10-04 07:32 UTC
Labels: Documentation, topic: date handling, Difficulty: Easy
