### ISSUE TITLE
matplotlib, date plotting create un-even spaced grid

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#15352] opened 2019-09-30 16:42 UTC
Hello,
this image:
![py2removal_progress](https://user-images.githubusercontent.com/346648/65898376-6cf72a00-e37f-11e9-90ab-fcefa8b8b2bf.png)

create from this code:

```
    # generate a progress graph
    d = defaultdict(int)
    for bug in bugs:
        # there are very old bugs (Jan 2018) tagged `py2removal`; they are just a handful, so let's ignore them
        if bug.done and bug.log_modified.date() >= datetime.date(2019, 7, 1):
            d[bug.log_modified.date()] += 1
    kdates, vbugs = [], []
    total = len(bugs)
    for kdate in sorted(d):
        kdates.append(kdate)
        total = total - d[kdate]  # we remove the amount of bugs closed that day from the total (whole bugs)
        vbugs.append(total)
    plt.plot(kdates, vbugs)
    plt.xticks(rotation=18, ha='right')
    plt.grid()
```

creates an un-even grid; it would be much more appealing if we can get an evenly spaced grid

BTW this is with mpl/3.0.2

**Comment by sandrotosi** [comment] 2019-09-30 17:04
hm now that i look as it better, is it because of the month beginning/end? it looks like 4 days spaced, until the end of the month, and then it starts from the 1st even if the interval is < 4 days?

**Comment by jklymak** [comment] 2019-09-30 20:55
https://matplotlib.org/3.1.1/api/dates_api.html#matplotlib.dates.AutoDateLocator  You can set interval_multiples to False.  I’m surprised you are getting 4 day intervals because it should be 3-days or 7, but maybe we changed the default recently.

**Comment by sandrotosi** [comment] 2019-10-01 22:33
(tbh i find it surprising this is on by default :) )

if i set interval_multiplies to False then as a side-effect all ticks are not only "2019" and no longer the full date, and they are really widely spaced, like i have only 5 vertical lines in the grid.

is there an option to keep the 4 days interval, but properly scale it to the change of month? thanks!

**Comment by jklymak** [comment] 2019-10-01 22:35
Can you give reproducible examples?  I’m not really clear what you are saying is happening...

**Comment by sandrotosi** [comment] 2019-10-01 22:44
of course, sorry about that :) attached is a sample script that produces 2 images: the first one is the current one, the second one is with the interval_multiples=False

[test_plt_date.py.txt](https://github.com/matplotlib/matplotlib/files/3678742/test_plt_date.py.txt)

**Comment by jklymak** [comment] 2019-10-01 23:19
OK, that just seems to be a bug with `interval_multiples=False`.  Not sure what is happening there at all...

What are you surprised about in the default behaviour?  That it marks the beginning of the month by default?  

BTW, you may be interested in `ConciseDateFormatter`:

```python
locator = mdates.AutoDateLocator(interval_multiples=True)
formatter = mdates.ConciseDateFormatter(locator)
fig, ax = plt.subplots()
ax.xaxis.set_major_locator(locator)
ax.xaxis.set_major_formatter(formatter)
ax.plot(kdates, vbugs)
plt.grid()
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/1562854/66007401-2846be00-e467-11e9-8ca2-4a994dfb99ef.png)

**Comment by sandrotosi** [comment] 2019-10-01 23:36
yeah, the default behaviour: i think it should start with the beginning of the data, and keep adding intervals, not marking the beginning of the month anything special

thanks for the suggestion about the concise format, but i like the ISO date at the bottom

**Comment by jklymak** [comment] 2019-10-02 00:27
The bug seems minor so I should have a fix by tonight.

**Comment by jklymak** [comment] 2019-10-02 01:45
Oops, not really a bug.  You need to re-set the formatter as well if you reset the locator (I won't argue if you want to say that is bad API ;-)

```python
locator = mdates.AutoDateLocator(interval_multiples=False)
formatter = mdates.AutoDateFormatter(locator)
fig, ax = plt.subplots()
ax.xaxis.set_major_locator(locator)
ax.xaxis.set_major_formatter(formatter)
ax.plot(kdates, vbugs)
plt.xticks(rotation=18, ha='right')
plt.grid()
plt.show()
```
![boo21](https://user-images.githubusercontent.com/1562854/66012300-79f94380-e47b-11e9-9c51-29efad0165ed.png)

**Comment by sandrotosi** [comment] 2019-10-02 01:57
oooh thanks for this! what if i want a more granular grid, like every 3/4 days?

**Comment by jklymak** [comment] 2019-10-02 02:26
https://matplotlib.org/3.1.1/api/dates_api.html#matplotlib.dates.DayLocator is basically what the AutoLocator calls when the axis has this xrange.

**Comment by sandrotosi** [comment] 2019-10-05 22:30
by using `mdates.DayLocator(interval=4)` (and `AutoDateFormatter`) i get a much nicer result, but i still think that `AutoDateLocator` default behaviour should be like `DayLocator(interval=N)` instead of resetting every 1st of the month.

this means i will not have to edit the interval value every so often as the time goes by

**Comment by psarka** [comment] 2020-07-03 10:41
Just bumped it this, very unexpected. A simpler and more extreme example:

```python
import matplotlib.pyplot as plt
import pandas as pd

plt.figure(figsize=(20, 5))
plt.plot(pd.date_range('2019-07-01', '2019-11-15'), [1]*138)
```

![image](https://user-images.githubusercontent.com/1212244/86461604-883a0000-bd2a-11ea-9e68-b71cf70e66ed.png)

**Comment by timhoffm** [comment] 2020-07-03 12:47
@psarka Your example will be fixed by #17727.

**Comment by psarka** [comment] 2020-07-03 14:34
Brilliant, thank you! 👏

**Comment by jklymak** [comment] 2020-07-03 15:01
In the meantime you can change the intervald of the locator by hand.

**Comment by timhoffm** [comment] 2020-07-04 22:49
@jklymak is there anything to do from our side about the original issue or can this be closed?

**Comment by jklymak** [comment] 2020-07-05 00:16
We could revert the change that interval_multiples=True.  But that change was originally made because people thought it strange we weren’t marking the first of the month.  It seems to me that if you don’t care about the first of the month you should just change to Julian day or some such.

**Comment by jklymak** [comment] 2020-07-21 19:32
I'll close this as there is no bug.  But certainly if there is a groundswell of opinion that `interval_multiples=True` is not a good choice we can reconsider.

**Closed** 2020-07-21 19:32 UTC
Labels: Date handling, Won't or can't fix
