### ISSUE TITLE
segfault ("recursive repaint") with Qt5Agg

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#9134] opened 2017-08-31 05:17 UTC
### Bug report

**Bug summary**

As of master,
```
$ python examples/images_contours_and_fields/plot_streamplot.py
QWidget::repaint: Recursive repaint detected
Fatal Python error: Segmentation fault
```
(Qt5Agg backend)

**Code for reproduction**

See above.

**Actual outcome**

NA

**Expected outcome**

Don't crash.

**Matplotlib version**

  * Operating System: Arch Linux
  * Matplotlib Version: master
  * Python Version: 3.6
  * Jupyter Version (if applicable):
  * Other Libraries: Qt5.9 from pypi in a venv.  *does not occur with Arch repo PyQt5* (recursive repaint message occurs sometimes, but does not crash even then)

bisects back to d0eeddb92 which is the merge commit for #9103; however, interestingly, the tip of that commit does *not* crash so something went wrong during the merge.

**Comment by tacaswell** [comment] 2017-08-31 11:32
Does master crash if you revert that merge?

**Comment by tacaswell** [comment] 2017-08-31 13:37
I can not reproduce this on v2.0.2-4836-gd0922df0d with or without hi-dpi scaling .

**Comment by tacaswell** [comment] 2017-08-31 13:44
I won't have access to an Arch machine until later tonight, currently testing against the qt5 distributed by continuum.

**Comment by anntzer** [comment] 2017-08-31 14:16
> Does master crash if you revert that merge?

Haven't tried yet.  Note that (unless I'm mistaken, which may well be the case) without the "fix" (...) introduced by that PR, I think it will take 2x longer for "big" images to pop up for the first time (as they are drawn twice); while I would definitely agree that a segfault is worse :-), I don't think a flat 2x speed regression is acceptable.

**Comment by tacaswell** [comment] 2017-08-31 14:31
A speed regression is something we can clean up post RC, a seg-fault is not.

**Comment by dopplershift** [comment] 2017-08-31 17:23
I can't reproduce on macOS with conda-forge python 3.6.2 and 2.0.2.post4838.dev0+g4f7337683.

**Comment by anntzer** [comment] 2017-08-31 17:41
Reverting the merge (`git revert -n d0eed -m1`) fixes the issue.
The issue actually only appears from within a venv (thus using pypi's pyqt5); when using the Arch repo pyqt5 the error message ("recursive repaint detected") appears sometimes (not always) but there is no crash in any case.  Updated the report accordingly.

**Comment by tacaswell** [comment] 2017-09-01 02:07
I can not reproduce this with:

```
(pyqt_pypi) ✔ ~/source/p/matplotlib [master {matplotlib/master}|⚑ 1] 
22:05 $ pip list --format=columns
Package          Version               Location                              
---------------- --------------------- --------------------------------------
cycler           0.10.0                
decorator        4.1.2                 
ipython          6.1.0                 
ipython-genutils 0.2.0                 
jedi             0.10.2                
matplotlib       2.0.2+4838.g4f7337683 /home/tcaswell/source/p/matplotlib/lib
numpy            1.13.1                
pexpect          4.2.1                 
pickleshare      0.7.4                 
pip              9.0.1                 
prompt-toolkit   1.0.15                
ptyprocess       0.5.2                 
Pygments         2.2.0                 
pyparsing        2.2.0                 
PyQt5            5.9                   
python-dateutil  2.6.1                 
pytz             2017.2                
setuptools       28.8.0                
simplegeneric    0.8.1                 
sip              4.19.3                
six              1.10.0                
traitlets        4.3.2                 
wcwidth          0.1.7                 
(pyqt_pypi) ✔ ~/source/p/matplotlib [master {matplotlib/master}|⚑ 1] 
22:05 $ MPLBACKEND=Qt5Agg python examples/images_contours_and_fields/plot_streamplot.py
(pyqt_pypi) ✔ ~/source/p/matplotlib [master {matplotlib/master}|⚑ 1] 
22:05 $ python --version
Python 3.6.2

```

**Comment by tacaswell** [comment] 2017-09-01 15:26
I just saw the warning doing something completely different so it is transient...

**Comment by tacaswell** [comment] 2017-09-28 05:56
Closed by #9199

**Closed by tacaswell** 2017-09-28 05:56 UTC
Labels: GUI/Qt, Release critical

**Comment by kawing-chiu** [comment] 2017-10-15 02:27
After upgrading to 2.1.0, my previously working app is completely broken, flooded with `QWidget::repaint: Recursive repaint detected`. I suspect that it is related to the 'fix' in this thread. What my app does is listening to draw_event and call 'blit_update' in the event handler.

**Comment by tacaswell** [comment] 2017-10-15 03:07
@kawing-chiu Sorry this broke for you.  Can you open a new issue provide a minimal example of what you are doing?  I am not sure what `blit_update` is (I can not find that string in the mpl codebase).

**Comment by kawing-chiu** [comment] 2017-10-15 03:10
@tacaswell I'm extracting a minimal example, please wait a minute.

**Comment by kawing-chiu** [comment] 2017-10-15 03:21
@tacaswell Please see issue #9406.
