### ISSUE TITLE
Default color after setting alptha to Patch in legened

### ISSUE THREAD

**Issue by KonradAdamczyk** [matplotlib/matplotlib#10574] opened 2018-02-23 20:24 UTC
### Bug report
After setting alpha to legend Patch, the color of edited patch resets to default(blue).

**Code for reproduction**

```python
"""
========
Barchart
========

A bar plot with errorbars and height labels on individual bars
"""
import matplotlib.pyplot as plt
import numpy as np

N = 5
men_means = (20, 35, 30, 35, 27)
men_std = (2, 3, 4, 1, 2)

ind = np.arange(N)  # the x locations for the groups
width = 0.35  # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(ind, men_means, width, color='r', yerr=men_std)

women_means = (25, 32, 34, 20, 25)
women_std = (3, 5, 2, 3, 3)
rects2 = ax.bar(ind + width, women_means, width, color='y', yerr=women_std)

# add some text for labels, title and axes ticks
ax.set_ylabel('Scores')
ax.set_title('Scores by group and gender')
ax.set_xticks(ind + width / 2)
ax.set_xticklabels(('G1', 'G2', 'G3', 'G4', 'G5'))

leg = ax.legend((rects1[0], rects2[0]), ('Men', 'Women'))

#this line causes bug - reset to default color(blue)
leg.get_patches()[0].set_alpha(0.854321)

plt.show()
```

**Actual outcome**
![obraz](https://user-images.githubusercontent.com/16255826/36615032-17f0e40e-18df-11e8-86ad-6570e5f3745e.png)
**Expected outcome**
![obraz](https://user-images.githubusercontent.com/16255826/36615150-930c4b1a-18df-11e8-8c90-567bd1e45b54.png)

**Matplotlib version**
  * Matplotlib version: 2.1.2
  * Python version: 2.7

**Comment by anntzer** [comment] 2018-11-03 16:40
Looks like duplicate of https://github.com/matplotlib/matplotlib/issues/11702 and fixed by #11703.

**Closed by anntzer** 2018-11-03 16:40 UTC
Labels: confirmed bug
