### ISSUE TITLE
Coordinates transform errors with ipympl or widget mode of Matplotlib

### ISSUE THREAD

**Issue by Mike-HubGit** [matplotlib/matplotlib#18166] opened 2020-08-04 12:24 UTC
### Bug report

I believe the "transform()" functions of Matplotlib do not behave well in ipympl or widget mode.

**Code for reproduction**

I simply use the matplotlib example published here:
https://matplotlib.org/3.1.1/tutorials/advanced/transforms_tutorial.html

I copy/paste the code for basic help :
```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

x = np.arange(0, 10, 0.005)
y = np.exp(-x/2.) * np.sin(2*np.pi*x)

fig, ax = plt.subplots()
ax.plot(x, y)
ax.set_xlim(0, 10)
ax.set_ylim(-1, 1)

xdata, ydata = 5, 0
xdisplay, ydisplay = ax.transData.transform_point((xdata, ydata))

bbox = dict(boxstyle="round", fc="0.8")
arrowprops = dict(
    arrowstyle="->",
    connectionstyle="angle,angleA=0,angleB=90,rad=10")

offset = 72
ax.annotate('data = (%.1f, %.1f)' % (xdata, ydata),
            (xdata, ydata), xytext=(-2*offset, offset), textcoords='offset points',
            bbox=bbox, arrowprops=arrowprops)

disp = ax.annotate('display = (%.1f, %.1f)' % (xdisplay, ydisplay),
                   (xdisplay, ydisplay), xytext=(0.5*offset, -offset),
                   xycoords='figure pixels',
                   textcoords='offset points',
                   bbox=bbox, arrowprops=arrowprops)

plt.show()
```

**Actual outcome**
 I get different results depending on the matplotlib mode : 
- on one side, %matplotlib inline gives the result expected and displayed in the example, as below :
![download](https://user-images.githubusercontent.com/65092924/89292441-ab730a80-d65c-11ea-8307-6861d50bd587.png)
- on the other side, %matplotlib ipympl or %matplotlib widget give erroneous results, as below :
<img width="649" alt="widget" src="https://user-images.githubusercontent.com/65092924/89292767-2b997000-d65d-11ea-9194-ea574d114a8b.png">
The result is the same if I download with the "floppy-disk" icon of the widget.

**Expected outcome**

The result with widget or ipympl mode should be the one of inline mode.

**Matplotlib version**

  * Operating system: MacOs X.12
  * Matplotlib version:                3.2.2
  * Matplotlib backend  : module://ipykernel.pylab.backend_inline or module://ipympl.backend_nbagg
  * Python version: Python 3.7.7 (default, Mar 26 2020, 10:32:53) 
  * Jupyter version (if applicable):  jupyterlab  1.2.6 from conda-forge
  * Other libraries: 

My set-up comes from miniconda.

**Comment by jklymak** [comment] 2020-08-04 14:33
When you apply the transform your dpi is the default (100).  When you output the figure, ipympl is using the hiddpi settings of your monitor and setting the dpi to 200.   When you use `inline` dpi is set to 100.  So, `annotate` is putting the annotation in the right spot each time.  

How you work around this is up to you.  Personally I don't ever use pixels because they don't really mean anything.  If you'd like that arrow to be in the same spot no matter what then use `transFigure` and 'figure fraction'.  Conversely if you really like pixels (and there are those who do), then set your dpi to 200 before the call to `ax.transData.transform_point`.  

I'm going to close this because I think matplotlib is working as designed, even if its unexpected, but feel free to carry on the conversation, or move discussion to discourse.matplotlib.org

**Closed by jklymak** 2020-08-04 14:33 UTC
