### ISSUE TITLE
Transparency in Animations

### ISSUE THREAD

**Issue by cbreeden** [matplotlib/matplotlib#5335] opened 2015-10-27 23:55 UTC
This report is somewhat of an extension to #5302.  It seems easy to miss handle transparent regions while working with nbagg.  The following is an example taken from the animation examples:

```
%matplotlib nbagg

import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np

def update_line(num, data, line):
    line.set_data(data[...,:num])
    return line,

fig = plt.figure()

plt.xlim(0, 1)
plt.ylim(0, 1)
plt.xlabel('x')
plt.title('test')

data = np.random.rand(2, 25)
l, = plt.plot([], [], 'r-')

ani = animation.FuncAnimation(fig, update_line, 25, fargs=(data, l),
    interval=50, blit=True)

ani.save('im.gif', writer='imagemagick', fps=8)
ani.save('im.mp4', extra_args=['-vcodec', 'libx264'])
```

The output produced is:

![im](https://cloud.githubusercontent.com/assets/12069845/10775906/9c861688-7cda-11e5-84db-773a1853bad1.gif)

As you can see, there is again some issues with the rendering of text in the figure (not axes) area where nbagg has set transparency to true.  The im.mp4 file looks nearly identical to the gif.  

I believe matplotlib saves each frame as a png and then sends those pngs to be saved as an animation through convert (imagemagick) or ffmpeg.  I believe the issue here is that while gifs properly support transparency, they only support either full alpha or no alpha, which forces imagemagick to decide between alpha or no alpha for each intermediate alpha which gives a pixelated appearance.

If we insert the code [for some reason `with plt.rc_context({'nbagg.transparent': False})` doesn't work here]:

```
import matplotlib
matplotlib.rcParams['nbagg.transparent'] = False
```

Then we will get this:

![im2](https://cloud.githubusercontent.com/assets/12069845/10776208/5b9de012-7cdd-11e5-8699-5b701b990f1d.gif)

Perhaps we can just disable transparency for gif files all together (I don't think matplotlib can properly handle boolean alpha levels), and then set the default frame format to gif files for animations; `animation.frame_format: 'gif'`

**Comment by cbreeden** [comment] 2015-10-29 14:23
This is just a post to document an attempt and the difficulties I ran into.  Good for me to reference when I try again, or perhaps useful if anyone else takes a peek.

I tried to give (while crossing my fingers) `_png.write_png` a  32-Bit RGBA bitmap from a numpy array as an experiment:

    %matplotlib nbagg

    import pylab
    from matplotlib.backends.backend_agg import FigureCanvasAgg
    from matplotlib import _png
    import numpy as np

    pylab.plot([1,2,3])

    canvas = pylab.get_current_fig_manager().canvas
    agg = canvas.switch_backends(FigureCanvasAgg)
    agg.draw()

    s = agg.buffer_rgba()
    # get the width and the height to resize the matrix
    l,b,w,h = agg.figure.bbox.bounds
    w, h = int(w), int(h)

    s = np.array(s.tolist()).reshape((w,h,4)) #Convert to RGBA to np.array
 
    filename_or_obj = 'testwrite.png'
    renderer = agg.renderer

    with open(filename_or_obj, 'wb') as fn:
        _png.write_png(memoryview(s), fn, agg.figure.dpi)

Get error: `IndexError: Unexpected SeqBase<T> length.`

I _think_ it has to do with `write_png` wants `s` to have a `array_view::converter_contiguous` method: https://github.com/matplotlib/matplotlib/blob/c32bde54dde984b9d51dd824b856d274f9022821/src/_png.cpp#L82

Haven't figured a way around that yet.  The goal is to then us numpy to flatten RGBA -> RGB to see if something like this would work for making the animations better by default.

**Comment by jenshnielsen** [comment] 2015-10-29 14:31
Could you try setting `blit=False` It looks to me like the issue is that the frames are not blitted correctly and all frames but the first ones are have the text plotted multiple times.

**Comment by cbreeden** [comment] 2015-10-30 02:36
I got the same results with `blit=False`.  I also tried using `writer=imagemagick_file` to see what frames we are giving imagemagick and here are a few samples:

![_tmp0000001](https://cloud.githubusercontent.com/assets/12069845/10837209/af1d347e-7e84-11e5-967e-fedeb8c49795.png)

![_tmp0000006](https://cloud.githubusercontent.com/assets/12069845/10837213/b3e7c3a2-7e84-11e5-8bbb-d808a3096534.png)

I used convert's +adjoin argument to deconstruct those frames from the gif and this is what they look like:

![frame_001](https://cloud.githubusercontent.com/assets/12069845/10837225/d4044552-7e84-11e5-8160-b7ab6a13e472.gif)

![frame_007](https://cloud.githubusercontent.com/assets/12069845/10837229/df609220-7e84-11e5-8c6a-419532e7d7f2.gif)

It looks like imagemagick really wants to keep the alpha channel (as shown in the first gif), but is then forced to decide between full alpha or no alpha which is what gives the pixelated appearance, and then for the later frames I guess it gives up on the who alpha channel idea for some reason unknown to me.

**Comment by cbreeden** [comment] 2015-10-30 15:35
Issue update:

I have written some quick code as a possible solution, but I ran into issues with animations in my git-installed version of matplotlib.  I will need to figure this out, but here is something I was considering:

        if kwargs.pop('flatten', False):
            bg = mcolors.colorConverter.to_rgb(
                     rcParams.get('savefig.facecolor', 'white'))
            bg = tuple([int(x * 255.0) for x in bg])
            w, h = int(renderer.width), int(renderer.height)

            src_a = renderer.buffer_rgba()
            src_a = np.array(memoryview(src_a))
            src_a = src_a.reshape((w,h,4))

            alpha = src_a[:,:,3]
            src = src_a[:,:,0:3]
      
            dest = np.empty((w,h,3))  
            dest[:,:,0] = (255 - alpha)*bg[0] + alpha*src[:,:,0]
            dest[:,:,1] = (255 - alpha)*bg[1] + alpha*src[:,:,1]
            dest[:,:,2] = (255 - alpha)*bg[2] + alpha*src[:,:,2]
            dest = (dest/255).astype(np.uint8)  

            _png.write_png(dest, filename_or_obj, self.figure.dpi)
        else:
             _png.write_png(renderer._renderer, filename_or_obj, self.figure.dpi)

This would add an `flatten` kwarg in savefig that can be called when animation.py when it wants it.

**Comment by jklymak** [comment] 2018-08-16 21:54
Closing, as I don't see the issue with current nbagg and master matplotlib.  OTOH, feel free to reopen if I'm in error.

**Closed by jklymak** 2018-08-16 21:54 UTC
Labels: Animation
