### ISSUE TITLE
Linestyle: dash tuple with offset

### ISSUE THREAD

**Issue by mkrphys** [matplotlib/matplotlib#5430] opened 2015-11-07 09:38 UTC
In the documentation of matplotlib.lines.set_linestyle() and elsewhere in the matplotlib docs it is written that the linestyle can be a dash tuple of the form (offset, onoffseq), where onoffseq is an even length tuple.

Providing the onoffseq works fine, but the offset seems to be ignored, e.g., the following code produces two identical plots:

x = linspace(0,10)
plot(x, ls=( 0, (10,10)))
plot(x, ls=(10, (10,10)))

**Comment by tacaswell** [comment] 2015-11-07 14:18
@mkrphys Did this ever work?  What version of mpl are you using?


```python
import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

x = np.linspace(0,10)
y = np.ones_like(x)
for j in range(10):
    ax.plot(x, j*y, ls=(j, (10,10)))


ax.set_ylim(-60, 60)
```

is a little easier to see that `offset` has no effect.

**Comment by mkrphys** [comment] 2015-11-07 20:00
I am using matplotlib 1.5 on MacOSX, installed with MacPorts. I have no clue if this ever worked, but being a documented feature implies to me as a user that this should work.

**Comment by tacaswell** [comment] 2015-11-07 22:56
Indeed it _should_ work as documented, but I am much more concerned about regressions (things that used to work and now do not) than documented features that have never existed.  The later is annoying and should be fixed, but the former breaks user code.

There is a comment in the code `        self._dashSeq = seq  # TODO: offset ignored for now` which was last touched in 2005 (!).

**Comment by tacaswell** [comment] 2015-11-07 23:14
See https://github.com/matplotlib/matplotlib/pull/5433 which will pass the value through, but the Agg backend does not do seem to do anything with it during rendering.

**Comment by afvincent** [comment] 2016-06-01 19:44
I was trying to update the following [example](http://matplotlib.org/examples/lines_bars_and_markers/line_demo_dash_control.html) to demonstrate the possibility of setting the dash style directly through the kwarg `linestyle`. I was also interested in showing that with the latter method, one can specify the offset of the dash sequence. However by doing this I find two surprising "behaviors". 

_As I found the current issue ticket about the very same feature, I post here. But if it would be better to open a dedicated new ticket, please let me know._

### What is the unit of the dash sequence?
Since the dash lengths are now scaled wrt the line width (PR #5926), is it still correct to say that the dash sequence is given in points? See for example 
![dash_sequence_unit_issue](https://cloud.githubusercontent.com/assets/17270724/15722244/0bd446a0-283d-11e6-8e2f-92f40cfaaef5.png)
where the same dash sequence (40, 2, 4, 4) (in "pt") with 2 different linewidths (1pt and 2 pt) gives two different lengths for the dashes. I understand it is the expected behavior but shouldn't the relevant doc be updated. (I haven't really found a nice formulation to propose for this...)

### Is a negative value allowed as the offset of a dash sequence?
To demonstrate how to set the offset value of a dash sequence (with (`offset, onoffseq)`), I adapted the existing example into
```python
import numpy as np
import matplotlib.pyplot as plt

dashes = [40, 2, 4, 4]  # 40 points on, 2 off, 4 on, 4 off
x = np.linspace(0, 10, 500)
y = np.sin(x)

# Set dash style via the Line method `set_dashes`
line, = plt.plot(x, y, '--', linewidth=2, color='0.25',
                 label="set_dashes({0})".format(dashes))
line.set_dashes(dashes)

# Set dash style directly via the `linestyle` keyword argument
# NB: The offset `dy` is "manually" adjusted to get a smooth evolution of the
# dashes offsets along the line stack.
for offset, dy in zip([-10, -5, 0, 5, 10], [-0.4, -0.2, 0.2, 0.4, 0.6]):
    ls = (offset, dashes)
    l, = plt.plot(x, y + dy, ls=ls, lw=2, label="ls={0}".format(ls))

plt.legend(loc='lower right', fontsize='small')
plt.axvline(0.95, color='0.8')  # to compare the offset values more easily
plt.show()
```
which results in
![dash_sequence_negative_offset_issue](https://cloud.githubusercontent.com/assets/17270724/15722608/dd82501a-283e-11e6-95b0-621210ca0c37.png)
It seems to me that the negative offset values (-5 and -10, the two first lines from the bottom) are not correctly handled, are they? (I added a vertical line to help checking.) As I didn't see indicated anywhere that negative values are *not* allowed for dashes offset, I wonder if it is the expected behavior.

**Comment by tacaswell** [comment] 2016-06-01 23:31
@afvincent I agree on all points.  The docs should be updated and the negative behavior looks funny.

retagged this issue as 2.0 to conserve issues.

Negative shifts not working is an Agg bug, svg shifts to the right and there is no-shift in the pdf.

**Comment by afvincent** [comment] 2016-06-02 09:11
About the documentation update, what about changing a bit the docstring of `lines.Line2D.set_linewidth`? For example by:
```
Alternatively a dash tuple of the following form can be provided::
    (offset, onoffseq),
where ``onoffseq`` is an even length tuple of on and off ink, in points if the
line width is thiner than 1 pt, and in units of line width if it is larger.
```
or
```
Alternatively a dash tuple of the following form can be provided::
    (offset, onoffseq),
where ``onoffseq`` is an even length tuple of on and off ink in points. If the
line width is larger than 1 pt, the dash tuple is scaled with respect to the
line width value (in pt).
```

IMHO, the second one is more precise as the offset value is also scaled by the line width value (see ll. 865-874 in commit 04ffd42)

If one of the formulations is OK, I can submit a PR with this change. As think that some other docstrings will need to be updated as well (at least the ones of `set_linestyle` in `collections.py` and `backend_bases.py`)

**Comment by afvincent** [comment] 2016-06-05 19:09
@tacaswell : Are you sure that the PDF backend is not working? Because if I simply do a `plt.savefig("NiceName.<ext among {png, pdf, svg}>", dpi=100)`, I have the feeling that only the PNG export is not working. Here are the pictures I got (conversions from PDF and SVG into PNG were done with ImageMagick):
![test_of_negative_dash_offset](https://cloud.githubusercontent.com/assets/17270724/15807537/44f4d54a-2b61-11e6-9997-af6653752ad3.png)
![test_of_negative_dash_offset_from_pdf](https://cloud.githubusercontent.com/assets/17270724/15807539/49fed3ba-2b61-11e6-811e-b96f511de959.png)
![test_of_negative_dash_offset_from_svg](https://cloud.githubusercontent.com/assets/17270724/15807540/4a30c9c4-2b61-11e6-84ca-a112acc14262.png)

PS: I generated the plots with Matplotlib `1.5.2rc2.post1938+g4ba20b8`

**Comment by tacaswell** [comment] 2016-06-05 19:38
Your right, I am was mistaken about pdf.  It could have the viewer I was using?

**Comment by afvincent** [comment] 2016-06-05 22:43
*Not sure I understood your last remark.* I just tested my PDF with Evince, xpdf, Inkscape (import), qpdfview and MuPDF (everything on Linux), and every viewer was fine. But isn't it the expected behavior and the PDF rationale?

PS : I don't know why but I can't upload on GitHub the PDF I produced in my previous answer. I get an error from GitHub (“Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.”)

**Comment by jkseppan** [comment] 2016-06-18 05:33
I think the pdf backend just writes the offset into the pdf file. The pdf specification doesn't seem to explicitly say that the offset must be nonnegative, but I think it is implied. Different viewers could handle it differently.

**Comment by afvincent** [comment] 2016-06-18 08:50
Here is what I found about dash patterns 
[PDFReference_3rd_ed_pp.175-176_bis.pdf](https://github.com/matplotlib/matplotlib/files/321662/PDFReference_3rd_ed_pp.175-176_bis.pdf), and indeed the way “dash phase” pattern is handled seems to assume it's a positive quantity : if I understood correctly, a line starts to be drawn when accumulated sum of the patterns is equal to the offset.

A possibility to handle negative values might be to convert them into a equivalent positive value (% length of a complete dash pattern). Something like 
```python
if offset < 0:
    offset = offset % np.sum(dash_pattern)
```

**Comment by afvincent** [comment] 2016-06-18 08:53
OK sorry, I've just seen that @jkseppan already commited a similar solution with 54450fd…

**Comment by tacaswell** [comment] 2016-07-12 04:39
With the changes in #6710 

![so](https://cloud.githubusercontent.com/assets/199813/16755291/ab587dd4-47c0-11e6-8212-307d84e4dddb.png)

**Closed** 2016-07-13 18:25 UTC
Labels: API consistency, Documentation
