### ISSUE TITLE
FuncAnimation.save throws TypeError

### ISSUE THREAD

**Issue by rmeno12** [matplotlib/matplotlib#16965] opened 2020-03-30 17:48 UTC
### Bug report

**Bug summary**

I was trying to use FuncAnimation's save method to save an animation that I'd created to a .mp4 file, but it threw a TypeError when I ran my code (the animation displays fine with plt.show()).

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import random

fig = plt.figure()
ax1 = fig.add_subplot(1, 1, 1)
x = [random.randint(0, 10) for _ in range(5)]
y = [random.randint(0, 10) for _ in range(5)]


def ani_func(i):
    x.append(random.randint(0, 10))
    y.append(random.randint(0, 10))
    ax1.clear()
    ax1.plot(x, y)

ani = animation.FuncAnimation(fig, ani_func, frames=10, repeat=False)
plt.show()
ani.save('test.mp4')

```

**Actual outcome**

The animation itself works fine in plt.show() producing this image as the last frame as expected:
![image](https://user-images.githubusercontent.com/28741889/77944244-380f5580-7284-11ea-8173-3484e533dc06.png)

However, the animation doesn't save to `test.mp4` and instead throws a TypeError. I have included the entire traceback below.
```
Traceback (most recent call last):
  File ".\disease_simulation\graphout.py", line 19, in <module>
    ani.save('test.mp4')
  File "C:\Users\menon\Desktop\disease-simulation\env\lib\site-packages\matplotlib\animation.py", line 1102, in save
    alt_writer = next(writers, None)
TypeError: 'MovieWriterRegistry' object is not an iterator
```

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.8

Matplotlib was installed via pip in a venv.

**Comment by tacaswell** [comment] 2020-03-30 18:36
Thanks for the report @rmeno12 .  We have a PR to fix the exception, but you will still have the problem that you do not have ffmpeg installed so will not be able to create an mp4 for you.

**Comment by timhoffm** [comment] 2020-03-31 13:28
Closed by #16965.

**Closed by timhoffm** 2020-03-31 13:28 UTC
Labels: Animation, Release critical

**Comment by gemerden** [comment] 2020-05-04 11:38
I seem to be having the same problem, any idea when the fix will come out? Is there a workaround like using FuncAnimation?

**Comment by gemerden** [comment] 2020-05-04 11:40
sorry, this is about FuncAnimation, came from another thread where they were using ArtistAnimation with the same problem, so ... any other workaround?

**Comment by QuLogic** [comment] 2020-05-04 22:15
3.2.2 will be out with the release candidate for 3.3.0, either end of this week or some time next week.

**Comment by bluesammer** [comment] 2020-05-26 13:09
Its still not around.

**Comment by tacaswell** [comment] 2020-05-31 20:59
We are a mostly volunteer organization and sometimes release dates slip.  Any help clearing the remaining issues for 3.2.2 and 3.3.0 would be appreciated and expedite the process.

https://github.com/matplotlib/matplotlib/milestone/52
https://github.com/matplotlib/matplotlib/milestone/48

**Comment by StevenLi-DS** [comment] 2020-07-11 12:47
I'm using `3.2.1` and already `pip install ffmpeg` but when I run the following code 
```
import matplotlib.animation as manimation
manimation.writers.list()
```
I still only got `['pillow', 'html']`. Is there an easy way to install ffmpeg on Windows rather than setting system var and am I missing something?

**Comment by tacaswell** [comment] 2020-07-11 16:42
@StevenLi-DS This fix is on 3.2.2 to get the better fallback behavior, but that won't solve your installation problem.

`ffmpeg` is usually a system dependency (the ffmpeg package on pypi is a python wrapper that calls out via sub-process).  I am not a regular windows user, but I suggest starting at https://ffmpeg.org/download.html

**Comment by ndavoudi** [comment] 2020-12-01 16:16
I am using matplotlib 3.3.2 on windows and still get the error "TypeError: 'str' object is not callable" when using animation save. Any help would be appreciated :)

**Comment by dopplershift** [comment] 2020-12-01 22:39
Can you open a new issue with a minimal example that causes the issue?

**Comment by pguthrey** [comment] 2020-12-19 08:25
I'm getting the same issue as @ndavoudi

**Comment by jklymak** [comment] 2020-12-19 16:02
We can't fix an error if we can't trigger it. Can someone provide a MWE so we can try and fix?

**Comment by pguthrey** [comment] 2020-12-20 07:41
I think this is just related to ' fallback behavior', perhaps?  When reinstalled ffmpeg the issue was resolved.  So there is something up with the pillow fallback perhaps?

**Comment by bcalvr** [comment] 2021-03-23 17:06
I am getting the same "TypeError: 'MovieWriterRegistry' object is not an iterator" message, does anyone know if this bug has now been fixed and therefore whether it's a problem at my end?

**Comment by jklymak** [comment] 2021-03-23 18:24
@bcalvr if it is exactly the same repro as the original issue we can re-open.  If its different, then please open a new issue with the reproducible example.  Also it looks like stating whether you have ffmpeg or not may be helpful.  Perhaps we have a broken untested fallback?

**Comment by bcalvr** [comment] 2021-03-24 03:24
I think I have managed to solve the problem - it was to do with the location of my ffmpeg installation. Thank you for the response though! I am now able to export animations to video files, but I am still struggling with getting them to play inline in Atom!

**Comment by liqinglin54951** [comment] 2021-11-15 01:38
Installation of FFmpeg in anaconda(from https://blog.csdn.net/Linli522362242/article/details/121313449):
`conda install -c conda-forge ffmpeg`
`import matplotlib.pyplot as plt
import matplotlib.animation as animation
import random
from IPython.display import HTML

fig = plt.figure()
ax1 = fig.add_subplot(1, 1, 1)
x = [random.randint(0, 10) for _ in range(5)]
y = [random.randint(0, 10) for _ in range(5)]


def ani_func(i):
    x.append(random.randint(0, 10))
    y.append(random.randint(0, 10))
    ax1.clear()
    ax1.plot(x, y)

ani = animation.FuncAnimation(fig, ani_func, frames=10, repeat=False)
plt.show()
ani.save('test2.mp4')
HTML( ani.to_html5_video() )`
![image](https://user-images.githubusercontent.com/36342491/141709062-57438924-f910-4318-92c8-935e24f04dd7.png)

![image](https://user-images.githubusercontent.com/36342491/141709087-ec0715af-6abc-43da-bcf3-586018b381a0.png)

**Comment by liqinglin54951** [comment] 2021-11-15 01:40
> I am using matplotlib 3.3.2 on windows and still get the error "TypeError: 'str' object is not callable" when using animation save. Any help would be appreciated :)

since you didn't install FFmpeg in anaconda, see detail solutions:https://blog.csdn.net/Linli522362242/article/details/121313449
