### ISSUE TITLE
How to fix the colorbar limits with contour during animation?

### ISSUE THREAD

**Issue by chengdi123000** [matplotlib/matplotlib#11774] opened 2018-07-25 14:38 UTC
### Bug report

**Bug summary**

I cannot change the colorbar using `set_clim`. I suppose it is used for changing contour limit.

**Code for reproduction**

```python
# Paste your code here
#
#
import matplotlib.pyplot as plt
import numpy as np

X=np.linspace(0,100)
Y=np.linspace(0,100)
X,Y = np.meshgrid(X,Y)
def Z(t):
    return np.cos(X/10)*np.cos(Y/10)*t

for t in range(5):
    fig,ax = plt.subplots()
    cz = ax.contourf(X,Y,Z(t),vmin=-4,vmax=4)
    cb = fig.colorbar(cz)
    cb.set_clim(-4,4) ##?? I want to fix the colorbar range for animation
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```
![image](https://user-images.githubusercontent.com/10754664/43206454-c7ef26e6-8ff3-11e8-8c03-8c6bf02bd367.png)
![image](https://user-images.githubusercontent.com/10754664/43206459-cb7ab76c-8ff3-11e8-89dd-726eea9e1210.png)
![image](https://user-images.githubusercontent.com/10754664/43206465-ce28c76a-8ff3-11e8-8746-f8aeb984aacd.png)
![image](https://user-images.githubusercontent.com/10754664/43206470-d1b9440e-8ff3-11e8-8cb4-04764c6efe76.png)
![image](https://user-images.githubusercontent.com/10754664/43206477-d55947ee-8ff3-11e8-969e-5a220f250af2.png)

**Expected outcome**

I want to have a fixed range of color mapping for my contour and a fixed colorbar. How can I do that?

cmap is only a function from [0,1] to colors
I expect `contourf()` option `vmax, vmin` would help me to scale `Z` from range `[vmin,vmax]` to range `[0,1]` and feed it to `cmap`.
I expect the colorbar's limit will follow the `vmin,vmax` rather than `max(Z),min(Z)`

**Matplotlib version**

  * Operating system: ubuntu 16.04
  * Matplotlib version:  2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): jupyter inline
  * Python version: 3.5.2
  * Jupyter version (if applicable): 5.5.0
  * Other libraries:

**Comment by jklymak** [comment] 2018-07-25 14:40
This is better for stackoverflow.   But set “levels” if you want the contour levels to not change.  Closing as not a bug.

**Closed by jklymak** 2018-07-25 14:40 UTC

**Comment by chengdi123000** [comment] 2018-07-25 14:51
why `set_clim()` do not work?

I searched stackoverflow. There is an example using `imshow()` with `set_clim()`. It works for `imshow()` but do not work for `contourf`.

**Comment by jklymak** [comment] 2018-07-25 14:58
`set_clim` is working; all your contours have the same colormap spanning the same color limits.    But the colorbar uses the contour levels.  Set your levels if you want the colorbar to stay the same.

**Comment by chengdi123000** [comment] 2018-07-25 15:03
I thought there are two steps:
1. Z from [vmin, vmax] to [0,1] using certain normalization function
2. cmap from [0,1] to colors
so where is `clim` ? It is different from vmin,vmax right?

**Comment by jklymak** [comment] 2018-07-25 15:15
This is the wrong forum for this discussion.  Github is for bug reports.  Please search stackexchange, and if you can't find your issue there, submit a new request.
