### ISSUE TITLE
NaN causes plt.vlines to not scale y limits

### ISSUE THREAD

**Issue by dadkins** [matplotlib/matplotlib#7406] opened 2016-11-04 18:38 UTC
I have reduced the error to the following code snippet which I run in a Jupyter notebook. A NaN as the first item in the series causes plt.vlines to not scale the y limits appropriately. The data values are in the thousands, but the ylimits are [-0.06, 0.06].

```python
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sys

print sys.version
print 'pandas', pd.__version__
print 'matplotlib', matplotlib.__version__
df = pd.DataFrame(index = pd.DatetimeIndex(['2016-10-07', '2016-10-14', '2016-10-21', '2016-10-28'], name='Date'),
                  data = [np.nan, -1000, -3000, 4500],
                  columns = ['Amount'])
print df

plt.figure(figsize=(12,3))
plt.vlines(df.index, 0, df['Amount'])
```

```
2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
pandas 0.19.0
matplotlib 1.5.3
            Amount
Date              
2016-10-07     NaN
2016-10-14 -1000.0
2016-10-21 -3000.0
2016-10-28  4500.0
```

- [ ] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
1.5.3, python 2.7.12, Linux

- [ ] How did you install Matplotlib and Python (pip, anaconda, from source ...)
conda

- [ ]
![matplotlib-bug](https://cloud.githubusercontent.com/assets/507004/20017909/ef12bd24-a282-11e6-84c2-1044adf3d2e8.png)

**Comment by phobson** [comment] 2016-11-04 19:18
Thanks for the clear and detailed report. I can confirm this. 

I can also confirm that moving to null value to a position other than the first in the sequence results in properly scaled axes.

An even more minimal example would be:

```python
import matplotlib.pyplot as plt
import numpy as np
fig, ax = plt.subplots()
ax.vlines([1, 2, 3, 4], 0, [np.nan, -1000, -3000, 4500], colors='b', linewidth=5)
```

Of the top of my head, one way to fix this would be to check that the first element isn't null and remove it if it is. However, that feels like treating the symptom and not the cause.

Will need to dig further.

**Comment by tacaswell** [comment] 2016-11-04 19:20
We are probably using `np.min` instead of `np.nanmin` and/or not masking the input properly.

**Closed** 2016-11-08 20:21 UTC
Labels: confirmed bug
