### ISSUE TITLE
wheels not picking correct default backend

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#7874] opened 2017-01-19 09:58 UTC
I installed matplotlib 2.0 the other day via
```
sudo -H pip install -U matplotlib
```
and found that, for the simplest of examples,
```python
import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
plt.ylabel('some numbers')
plt.show()
```
no plot would be produced. Upon setting the backend in `/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/m‌​atplotlibrc` to `TkAgg`, it all worked again, and in fact `TkAgg` turned out to be the _only_ backend to produce a plot at all.

Any hints on how to debug this?

**Comment by bjodah** [comment] 2017-01-19 14:49
I'm experiencing this too (Ubuntu 16.04):
`MPLBACKEND=Agg ipython3` does not give a plot window on `plt.show()`
whereas
`MPLBACKEND=TkAgg ipython3` does.

**Comment by tacaswell** [comment] 2017-01-19 15:21
It is expected that `Agg` does not produce a window (as it has no GUI bindings).  Saving figures etc should work correctly with `Agg`.  It _should_ auto-detect if there is tk available and use it.  To get any of the other backends to work you need to have the bindings for the GUI frame works installed (ex `pyqt4`/`pyqt5`/`pyside`/`pyside2` for Qt, `wx`, `gtk`/`gtk3` etc).  See http://matplotlib.org/faq/usage_faq.html#what-is-a-backend for details.

attn @matthew-brett worried this something with the way we build the manylinux wheels.

**Comment by tacaswell** [comment] 2017-01-19 15:22
@bjodah I assume you also installed via the wheel?

**Comment by bjodah** [comment] 2017-01-19 15:24
@tacaswell, yes I installed the whl using `python -m pip install --user --upgrade matplotlib`

**Comment by matthew-brett** [comment] 2017-01-19 16:28
Might well be a wheel / backend problem.   What backends have you tried?   How did you install them?

**Comment by matthew-brett** [comment] 2017-01-19 17:22
I see that the default backend for the Linux wheels is 'agg', when I was expecting 'tkagg'.   I'll check why this is, but we should probably make a new [build tag](https://github.com/MacPython/wiki/wiki/Build-Tags) where the default backend is tkagg at least.

**Comment by matthew-brett** [comment] 2017-01-19 18:21
The problem is that the manylinux containers on which we build the wheels, do not have tcl / tk installed, so the import of `tkinter` fails, and matplotlib falls back to the default run-time backend of `agg`.   Fixed with : https://github.com/MacPython/matplotlib-wheels/commit/540669914bbf929e5e1b31803f869ba00a7a90d8

**Comment by matthew-brett** [comment] 2017-01-19 18:34
Tom - OK to upload the new Linux wheels with a build tag, if they differ only in the default backend?

@nschloe @bjodah - what other backends did you have trouble with?

**Comment by matthew-brett** [comment] 2017-01-19 19:03
Wheels built, retagged and ready for upload if y'all agree.

**Comment by bjodah** [comment] 2017-01-19 23:55
Not sure which matplotlibrc is read but:
`~/.local/lib/python3.5/site-packages/matplotlib/mpl-data/matplotlibrc`
contains:
`backend      : agg`

**Comment by matthew-brett** [comment] 2017-01-20 17:38
@tacaswell - OK to upload the wheels with default tkagg backend?  I think this matches wheel behavior previous to https://github.com/matplotlib/matplotlib/pull/7530 .

**Comment by tacaswell** [comment] 2017-01-20 17:42
:+1: to re-uploading the wheels.

**Comment by matthew-brett** [comment] 2017-01-20 19:17
Done. @nschloe @bjodah - try reinstalling matplotlib - you should get a wheel with filename like `matplotlib-2.0.0-1-cp35-cp35m-manylinux1_x86_64.whl`.  Does this fix the problem?  It does for me.

**Comment by bjodah** [comment] 2017-01-23 10:14
it works, thanks! :+1:

**Closed** 2017-01-23 10:17 UTC
Labels: build

**Comment by tacaswell** [comment] 2017-01-23 15:00
Thanks for taking care of this @matthew-brett !

**Comment by PorcelainMouse** [comment] 2018-05-17 03:42
Hmm, so this is the same symptom I have, exactly as OP reported it, but this did not get fixed with MPL 2.x. I wonder what else could cause Tk to not be found or for agg to be chosen over all the others that are actually available and working.  No errors are thrown, so I'm pretty lost as to what is wrong.
