### ISSUE TITLE
axis limits don't coordinate with each other

### ISSUE THREAD

**Issue by jsh9** [matplotlib/matplotlib#13648] opened 2019-03-11 07:21 UTC
### Bug report (or feature request)

**Summary**

In `matplotlib`, when manually restricting `xlim`, `ylim` does not change accordingly.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.array([1,2,3,4,5,6,7])
y = x

fig = plt.figure()
ax = plt.axes()
ax.plot(x, y)
print('xlim: %s, ylim: %s' % (ax.get_xlim(), ax.get_ylim()))

fig = plt.figure()
ax = plt.axes()
ax.plot(x, y)
ax.set_xlim(1, 2)
print('xlim: %s, ylim: %s' % (ax.get_xlim(), ax.get_ylim()))
```

**Actual outcome**

```
xlim: (0.7, 7.3), ylim: (0.7, 7.3)
xlim: (1.0, 2.0), ylim: (0.7, 7.3)
```

**Expected outcome**

When I change xlim to (1, 2), I expect ylim to change accordingly (because y's value range becomes [1, 2], now that x's range shrinks), but ylim still remains (0.7, 7.3). In fact, in MATLAB xlim and ylim can coordinate with each other.

MATLAB codes to reproduce this behavior:

```matlab
x = [1,2,3,4,5,6,7];
y = x;
figure; plot(x, y); disp(ylim);
figure; plot(x, y); xlim([1, 2]); disp(ylim);
```

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): `module://ipykernel.pylab.backend_inline`
  * Python version: 3.6.6
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

**Comment by WeatherGod** [comment] 2019-03-11 16:42
I think you are asking that the y limits should auto-scale based on what is
visible in the new x limits?

**Comment by jklymak** [comment] 2019-03-11 16:46
... I think there are just as many people who would complain about that behaviour as might appreciate it.  I used Matlab for many years and don't recall it doing this, but perhaps I've forgoten.

**Comment by jsh9** [comment] 2019-03-11 19:16
@WeatherGod Yes, that is what I meant. I did try to set autoscale (https://matplotlib.org/api/_as_gen/matplotlib.pyplot.autoscale.html), but I could not get it to work due to lack of an official example.

@jklymak I think matplotlib can offer users the option to turn it on and off easily.

**Comment by anntzer** [comment] 2019-03-11 19:36
This was discussed and rejected in https://github.com/matplotlib/matplotlib/issues/9890.  It would also require a pretty deep rewrite of the way data limits are computed.

**Comment by jsh9** [comment] 2019-03-11 20:03
@anntzer So autoscale and set_autoscale_view currently just do nothing? (I tried autoscale and the poster in #9890 tried set_autoscale_view.)

If they are not for this purpose, then I would suggest an update on the official documentation, because it is quite vague to a user as currently written:

"matplotlib.pyplot.autoscale(enable=True, axis='both', tight=None)

Autoscale the axis view to the data (toggle).

Convenience method for simple axis view autoscaling. It turns autoscaling on or off, and then, if autoscaling for either axis is on, it performs the autoscaling on the specified axis or axes."

**Comment by WeatherGod** [comment] 2019-03-11 21:20
autoscale/autolim works on all collections. It asks each artist object and
collection for their bounding box and selects a limit that encompasses the
union of those bounding boxes. The feature that isn't implemented is to
figure out what the bounding box would be if one were to start with a
constraint. Not impossible to code, but it would be fairly extensive amount
of work.

**Comment by jsh9** [comment] 2019-03-11 21:50
Thanks for the explanation. I understand it would be a lot of work to implement this. So I guess a good compromise is to note this default in the documentation.

**Comment by WeatherGod** [comment] 2019-03-11 22:00
Let us know where you think the documentation is deficient. The autolimit
feature has been default for 10 or more years now.

**Comment by jsh9** [comment] 2019-03-11 22:54
With this short script below, I can confirm two different behaviors:

1. By setting `autoscale` to "on", I allow the y axis bounds to automatically stretch to make room for out-of-bound data points.
2. The y axis bounds do not automatically shrink with data, even if I set `autoscale` to on.

However, by reading the current documentation (https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.autoscale.html), I could only expect Behavior No. 1, but not Behavior No. 2.  So this is where I think the documentation can benefit from some improvements.

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.array([1,2,3,4,5,6,7])
y = x

fig = plt.figure()
ax = plt.axes()
ax.plot(x, y)
print('xlim: %s, ylim: %s' % (ax.get_xlim(), ax.get_ylim()))

ax.autoscale(enable=False)
y1 = 2 * x
ax.plot(x, y1)  # ylim is not allowed to stretch
print('xlim: %s, ylim: %s' % (ax.get_xlim(), ax.get_ylim()))

ax.autoscale(enable=True)
y2 = 2 * x + 1
ax.plot(x, y2)  # ylim stretches automatically
print('xlim: %s, ylim: %s' % (ax.get_xlim(), ax.get_ylim()))

ax.autoscale(enable=True)
y3 = 2 * x + 2
ax.set_xlim(1, 2)
ax.plot(x, y2)  # ylim does not shrink automatically
print('xlim: %s, ylim: %s' % (ax.get_xlim(), ax.get_ylim()))
```

**Comment by tacaswell** [comment] 2022-11-01 16:57
This issue is still valid.

The work is to add another paragraph to the `autoscale` docstring so that the observed behavior in https://github.com/matplotlib/matplotlib/issues/13648#issuecomment-471772427 is not surprising

**Comment by QuLogic** [comment] 2023-03-08 08:52
Closing as a duplicate of #2123.

**Closed by QuLogic** 2023-03-08 08:52 UTC
Labels: Documentation, Difficulty: Medium, Good first issue

**Comment by jklymak** [comment] 2023-03-09 23:15
@neilser See https://github.com/matplotlib/matplotlib/issues/2123#issuecomment-1459777188

**Comment by neilser** [comment] 2023-03-11 16:13
@jklymak oh dear! I have no idea how I missed that (I even remember reading the _first_ bit of the relevant sentence but somehow missed the key bit); my apologies to @QuLogic
