### ISSUE TITLE
Turning labels off using `tick_params()` doesn't remove the offset ones.

### ISSUE THREAD

**Issue by elkir** [matplotlib/matplotlib#18130] opened 2020-07-30 20:47 UTC
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here

import matplotlib.pyplot as plt
import numpy as np

a = np.linspace(1,5)+1e4
b = np.random.random(a.size)+1e5

fig,ax =plt.subplots(1,2,figsize=(6,3),dpi=200)
ax[0].plot(a,b)

ax[1].plot(a,b)
ax[1].tick_params(left=False,labelleft=False,
               bottom=False,labelbottom=False)
fig.show()
```

**Actual outcome**

![issue_removing_labels](https://user-images.githubusercontent.com/20708119/88972797-63e42b80-d2b6-11ea-89d0-2429e014f327.png)

**Expected outcome**

Both ticks and labels are removed, **including** the offset ones. 

`tick_params()` seems to be the most straightforward way of removing the ticks but keeping the box. Setting `labelxxx=False` should intuitively include all its parts. And there is no other parameter in `tick_params()` that could deal with it. 

**Matplotlib version**

  * Operating system: Ubuntu 18.04

  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://backend_interagg
  * Python version: 3.8.3

**Comment by QuLogic** [comment] 2020-07-30 21:01
Duplicate of #16895; fix in 3.3.0, please update.

**Closed by QuLogic** 2020-07-30 21:01 UTC
