### ISSUE TITLE
Running animation in Jupither

### ISSUE THREAD

**Issue by mg64ve** [matplotlib/matplotlib#12952] opened 2018-12-09 13:22 UTC
### Bug report

**Just trying to run an animation example in Jupyter fails**

I am not getting any error. I can only see an empty figure with both axis.
No error in the logs.

**Code for reproduction**

```python
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

fig, ax = plt.subplots()
xdata, ydata = [], []
ln, = plt.plot([], [], 'ro', animated=True)

def init():
    ax.set_xlim(0, 2*np.pi)
    ax.set_ylim(-1, 1)
    return ln,

def update(frame):
    xdata.append(frame)
    ydata.append(np.sin(frame))
    ln.set_data(xdata, ydata)
    return ln,

ani = FuncAnimation(fig, update, frames=np.linspace(0, 2*np.pi, 128),
                    init_func=init, blit=True)```

```

**Actual outcome**
Empty graph with axis but no value.

Console log

```
[W 12:10:24.759 NotebookApp] Clearing invalid/expired login cookie username-localhost-8888
[W 12:10:24.761 NotebookApp] Forbidden
[W 12:10:24.762 NotebookApp] 403 GET /api/sessions?_=1544334916656 (172.17.0.1) 4.60ms referer=http://localhost:8888/tree
[W 12:10:24.765 NotebookApp] Clearing invalid/expired login cookie username-localhost-8888
[W 12:10:24.766 NotebookApp] Forbidden
[W 12:10:24.767 NotebookApp] 403 GET /api/terminals?_=1544334916657 (172.17.0.1) 2.31ms referer=http://localhost:8888/tree
[I 12:10:33.460 NotebookApp] 302 GET /?token=c5048efec4dfe835a7296117127d4afe6945ba3016d894fd (172.17.0.1) 0.56ms
[I 12:10:39.531 NotebookApp] Writing notebook-signing key to /home/fastai/.local/share/jupyter/notebook_secret
[W 12:10:39.532 NotebookApp] Notebook Untitled1.ipynb is not trusted
[I 12:10:39.709 NotebookApp] Kernel started: 2f8cd46b-2aca-489f-ad74-7153126210b6
[I 12:10:40.161 NotebookApp] Adapting to protocol v5.1 for kernel 2f8cd46b-2aca-489f-ad74-7153126210b6
[I 12:11:14.693 NotebookApp] 302 GET /tree (172.17.0.1) 0.93ms
[I 12:12:41.516 NotebookApp] Saving file at /Untitled1.ipynb
[I 12:15:55.983 NotebookApp] Saving file at /Untitled1.ipynb
```

**Expected outcome**

I would expect and animated stream with sin function.

**Matplotlib version**

  * Operating system: Ubuntu docker image running on Centos 7.5.1804
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.6.7
  * Jupyter version (if applicable): 5.7.2

  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment] 2018-12-09 13:41
The problem is the `animated=True` inside of  `plot`. Removing that argument solves the issue.   
Does this example originate from the matplotlib gallery?

This raises of course the question of why `animated=True` would *prevent* an animation to show the plot. The animation should set this property itself if needed, which as far as I can see it does.

**Comment by mg64ve** [comment] 2018-12-09 14:12
This is an example from your documentation.
Why do you use animated=True ?

**Comment by ImportanceOfBeingErnest** [comment] 2018-12-09 14:35
Could you link to the example you're quoting? There seem to be [12 examples about animation](https://matplotlib.org/gallery/index.html#animation), but none of them seem to match the one from above.

**Comment by mg64ve** [comment] 2018-12-09 18:16
Ok. It is here:

https://matplotlib.org/api/animation_api.html

in the "FuncAnimation" section.
Can you find it?

**Comment by ImportanceOfBeingErnest** [comment] 2018-12-09 20:03
Thanks for pointing to the place in the docs where the problematic code comes from. It seems the best would really be to remove the `animated=True` from that example since it seems unnecessary and might hence confuse people. 

Concerning the "streamin tensor", note that there isn't any difference between supplying one new point per frame of 32 new points. This would be totally up to you, whatever you write in the updating function would happen.

**Comment by ImportanceOfBeingErnest** [comment] 2018-12-09 21:06
To clarify: This is the issue tracker of matplotlib. It's not a support desk where you get tickets. See the [Need help? section](https://matplotlib.org/index.html#need-help) on the homepage for user-support options.  
Issues are closed when the issue is handled. In this case this will happen once #12960 (or any other pull request that fixes the issue) is merged. 

At this point let me thank you again for bringing this inconsistency to our attention.

**Closed** 2018-12-10 01:59 UTC
