### ISSUE TITLE
Boxplot with zero IQR sets whiskers to max and min and leaves no outliers

### ISSUE THREAD

**Issue by lmcinnes** [matplotlib/matplotlib#5331] opened 2015-10-27 17:14 UTC
I believe the behaviour in matplotlib is deliberate (given lines 2018-2019 of cbook). However I don't believe this is the expected behaviour for a boxplot (for example R leaves the whiskers at the median and draws outlier points). I was hoping for clarification or a reference on the choice taken in matplotlib.

**Comment by tacaswell** [comment] 2015-10-28 22:52
@phobson

Do you have a reference that this is _not_ the correct behavior?

**Comment by phobson** [comment] 2015-10-28 23:02
For reference here's a link to the section of `cbook` in question:
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cbook.py#L2017

**Comment by phobson** [comment] 2015-10-28 23:45
Looks like the (my) decision to do so was fairly intensional
https://github.com/matplotlib/matplotlib/commit/7cf8b357c80c9e1acf78487bf49d2d2fc2683c61

**Comment by phobson** [comment] 2015-10-29 00:01
I'm looking through all my references (including R docs) and I can't find any guidance and this specific  scenario.

At the time, I can only imagine myself thinking that:
  1. It's pretty messed up data where Q1 = Q2 = Q3
  1. defining (potential) outliers when IQR is zero might be meaningless.

I stand by the first thought. But now I'm one the fence about the second. The omission of guidance that you *should* do something different in an edge case like makes me think that we *shouldn't*.

However, I do think that a horizontal line with whiskers looks better than a horizontal like with dots floating around. But matters of the heart matter little in matters such as these.

**Comment by jc-healy** [comment] 2015-10-29 01:07
Since boxplots have been tweaked and modified many times over the years I won't say your decision is wrong but it's definitely not one I've run into before.  Looking at this (http://www.stata-journal.com/sjpdf.html?articlenum=gr0039) paper by Cox.  The useful text from this paper is:

... Lines, often called whiskers, are drawn to span all data points within 1.5 IQR of
the nearer quartile. That is, one whisker extends to include all data points within
1.5 IQR of the upper quartile and stops at the largest such value, while the other
whisker extends to include all data within 1.5 IQR of the lower quartile and stops
at the smallest such value. Tukey called the outer limits of the whiskers adjacent
values. The whiskers also explain his alternative term, box-and-whiskers plots.
Note that either whisker could be of zero length. In practice, that will occur only
with very small datasets or heavily tied data.
2. Any data points beyond the whiskers are shown individually and often labeled
informatively.

He notes the zero length whisker possibility but doesn't worry about it.  My assumption from this, other general reading, and working with R over the years is that the expected behaviour for a box-whisker plot was that the whiskers would be drawn at 1.5 IQR.   As such the choice of 1.5 IQR unless IQR is zero then at the 0 and 100th percentile throws me off a bit.  I feel that it's a bit misleading especially in a plot with many other features who have a non zero IQR.   

That being said, there is no canonical box-whisker plot.  I've seen a number of alternate variations in the literature such as drawing whiskers at 2% and 98%.  But I feel that the interpretation which is truest the original description by Tukey (who himself played with variations) would be to have zero length whiskers with any remaining points differing from the median as points.  

In the end it's definitely your decision.  I'd at the very least recommend documenting this behaviour very explicitly in the boxplot documentation and perhaps even making it an option.

**Comment by phobson** [comment] 2015-10-29 01:11
> But I feel that the interpretation which is truest the original description by Tukey (who himself played with variations) would be to have zero length whiskers with any remaining points differing from the median as points.

@jc-healy I agree with this. Thanks very much with the well considered input. It's very valuable.

See the PR references above.

**Comment by jduc** [comment] 2016-01-26 13:06
Just to bump the conversation as I encountered this issue today and am curious to know what the plans are for next updates.  

In the case of plotting multiple boxplots on the same plot, it happens that one of the dataset has a IQR of 0 and I think it brings a lot of confusion to have a 90% of the boxplots using 1.5IQR whiskers and 10% of them using the "min/max" whiskers. Adding the possibility to chose what should happen to the whiskers in case of IQR=0 would add a bit more flexibility to the function and solve the issue. Thanks

**Comment by phobson** [comment] 2016-01-26 17:03
@jduc see #5343 

We standardize the behavior. When IQR is 0, the whiskers only go out to min/max when then `autorange` parameter is set to true.

I need refresh that PR. Hopefully I can get to that soon.

**Comment by jenshnielsen** [comment] 2016-03-14 08:54
Fixed in #5343

**Closed by jenshnielsen** 2016-03-14 08:54 UTC
Labels: API Changes
