### ISSUE TITLE
[Bug]: `matplotlib.pyplot.hist()` can't draw by tensor

### ISSUE THREAD

**Issue by WindwithNothing** [matplotlib/matplotlib#23608] opened 2022-08-12 12:04 UTC
### Bug summary

I put a `torch.Tensor` in `matplotlib.pyplot.hist()` ,  but it draw a wrong graphic and take a long time.
Although transform to numpy, the function work well. But all the others function I used are work well on tensor. So I think its a bug.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import torch

plt.hist(torch.randn(20))
plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/45221786/184349059-7aca87cb-6a5a-4b89-9d0b-207c8604e45e.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/45221786/184349216-c6ed46e2-bfb3-4bd6-b03e-4fb6120a1686.png)

### Operating system

Windows

### Matplotlib Version

3.5.1

### Matplotlib Backend

module://ipykernel.pylab.backend_inline

### Python version

3.7.13

### Jupyter version

6.4.8

### Installation

conda

**Comment by tacaswell** [comment] 2022-08-12 14:11
Thank you for reporting this.  It is a duplicate of https://github.com/matplotlib/matplotlib/issues/19574 so I am going to close this issue in favor of the existing one.   Can we please continue this discussion there?

**Closed by tacaswell** 2022-08-12 14:11 UTC
