### ISSUE TITLE
v1.5.3: marker=None no longer works in plot()

### ISSUE THREAD

**Issue by adrn** [matplotlib/matplotlib#7218] opened 2016-10-04 18:08 UTC
I just upgraded to v1.5.3 using Anaconda in Python 3.5.2 and noticed that using `marker=None` in `matplotlib.pyplot.plot()` no longer has an effect. Compare:

__v1.5.1__
![screen shot 2016-10-04 at 14 04 07](https://cloud.githubusercontent.com/assets/583379/19086361/cd925c04-8a3b-11e6-8d6a-816a54d59b01.png)

__v1.5.3__
![screen shot 2016-10-04 at 14 05 16](https://cloud.githubusercontent.com/assets/583379/19086375/dfaf14ae-8a3b-11e6-9e9d-24d59576aaf8.png)

**Comment by adrn** [comment] 2016-10-04 18:11
Interestingly, using `marker=''` or `marker='None'` instead does work.

**Comment by WeatherGod** [comment] 2016-10-04 18:17
passing None for most things in matplotlib means "do the default thing". It
was a bug that marker=None did what it did in v1.5.1. The current behavior
in v1.5.3 is the correct one.

**Comment by adrn** [comment] 2016-10-04 18:23
Uh, what? `marker=None` has been (and still is, as of v1.5.3) listed in the documentation as a valid input to get "nothing", not "do the default thing":
http://matplotlib.org/1.5.3/api/markers_api.html#module-matplotlib.markers

**Comment by adrn** [comment] 2016-10-04 18:30
@WeatherGod I have a ton of code that uses `marker=None`, and know many others who use this convention as well -- IMO you should have raised a deprecation warning rather than silently deleting this option, especially since it still appears in the documentation.

**Comment by adrn** [comment] 2016-10-04 18:40
Just to be clear and to summarize: using `marker=None` has worked (at least) between v1.0 and v1.5.1 and is still listed in the documentation as a valid input: http://matplotlib.org/1.5.3/api/markers_api.html#module-matplotlib.markers

**Comment by keflavich** [comment] 2016-10-04 19:06
It would be helpful if `linestyle` (http://matplotlib.org/api/lines_api.html#matplotlib.lines.Line2D.set_linestyle) behavior was consistent with `marker`.

**Comment by efiring** [comment] 2016-10-04 19:11
There is nothing we can do about it for the 1.5 series.  A quick check indicates that v2.x and master behave like the earlier versions, not like 1.5.3.  The remaining question is whether any deprecations, changes in documentation, or additional tests are needed for v2.x and master.

My opinion is that the None object should not be listed in that documentation table as being equivalent to the 'none' string, even though it has the same effect in practice.

**Comment by WeatherGod** [comment] 2016-10-04 19:20
Ok, my brain hurts... why is it that v1.5.3 has a different behavior from
master?

Sorry for prematurely closing this issue. It appears we got ourselves into
a little bind in our efforts to remove hard-coded defaults and defer to the
rcParams whenever an argument is None. We must have not appreciated that
None actually had sematic value for certain things.

My vote at this point is to start a (long) deprecation process for None as
a marker value, given how ingrained it seems to be.

**Comment by efiring** [comment] 2016-10-04 19:53
The handling of the None object by Marker is hard to discern--it seems to be implicit rather than explicit--and probably goes back a long way.  In practice, it would be perfectly consistent for the None object to refer to the default and for the default to be "nothing", so I don't see the behavior needing to change--just the documentation, initially.  Then the None object could be removed from the `markers` dictionary, and handled explicitly as a special case, selecting the rcParams default, which is the "None" string.

The `rcParams['lines.marker'] = 'None'` default is presently used in many places--but not in the `marker` module itself.

**Comment by WeatherGod** [comment] 2016-10-04 20:03
Except, how do you distinguish between someone not passing `marker` into
plot() versus someone passing `marker=None` into plot()? Before, it used to
be distinguished accidentally by the fact that missing keyword arguments
were simply not processed. But with the property normalization system that
is now in place, you can't distinguish that (and that was intended as a
feature in order to get rid of that ambiguity).

**Comment by tacaswell** [comment] 2016-10-04 21:42
@adrn I can not reproduce this.  What do you have in your rcParams? I suspect it is not the defaults as your font looks like your font in latex.

**Comment by adrn** [comment] 2016-10-05 00:14
@tacaswell Indeed, I have this in my .matplotlibrc:
```
lines.marker: .
```
But I'm not sure that's relevant? The point is that in previous versions and in the documentation, `marker=None` produced no marker, but now it means "do the default thing" (which, in my case hits the rcParam and shows a '.').

**Comment by efiring** [comment] 2016-10-05 00:24
Using None for default is a standard, and using the None object for no marker is an anomaly that we should have corrected long ago.  It seems that we accidentally fixed it, but only partially, and with no deprecation cycle.  I think the thing to do is fix it the rest of the way by correcting the documentation and removing None from the dictionary in markers.py.  That is preferable to re-breaking it for the sake of putting in a deprecation cycle.

**Comment by adrn** [comment] 2016-10-05 00:41
I don't have a strong opinion about the course of action but it would be good to put a clear note in the changelog somewhere.

I recognize and appreciate why `None` is the standard for "default value," since the default can come from many places and no other value really makes sense. But I've long felt that `marker=None` feels and reads much nicer than `marker='None'` since you're really saying "I want no marker" (and I'm strongly against passing around strings in contexts like these). Same for `linestyle='none'` and etc.

**Comment by efiring** [comment] 2016-10-05 01:04
On 2016/10/04 2:41 PM, Adrian Price-Whelan wrote:
> I'm strongly against passing around strings in contexts like these

Why? All of the normal values are strings; why shouldn't a "no marker" 
value also be a string?

**Comment by tacaswell** [comment] 2016-10-11 21:50
OK, so it looks like there was a high degree of the left hand not knowing what the right hand was doing here.  

The TL;DR is that we should not revert this, the docs need to be updated, and we want to break even more behavior.

-------

The change here is due to a2b90a8cb726ebe8ea9e8a8ae9c64855ec13d7b8 which bundles all of the kwargs for the line and passes them into the `__init__` of Line2D where `None` is interpreted as 'do the default thing' and hits the rcParams.  Previously, half of the kwargs would be passed `__init__` and the other half went in through `set_lineprops` which just falls back to `line.set(...)` which in turn falls

**Closed** 2016-10-18 21:10 UTC
Labels: Documentation, needs confirmation, needs_review, not a blocker

**Comment by adrn** [comment] 2016-10-24 15:47
@tacaswell thanks for the work on this! 

One other side effect of this that I just noticed is that if I set `lines.marker: '.'` in my rc file, markers show up when I use `axvline()` or `axhline()`, e.g.:

![image](https://cloud.githubusercontent.com/assets/583379/19652672/aab37b56-99df-11e6-8a7d-ce463f2856a9.png)

To me, this is a bug. What do you think?

**Comment by tacaswell** [comment] 2016-10-24 15:51
Yes, axvline and axhline should override that.
