### ISSUE TITLE
[Bug]: 25 Second timeout on first call

### ISSUE THREAD

**Issue by WalterSmuts** [matplotlib/matplotlib#25036] opened 2023-01-20 09:09 UTC
### Bug summary

First call using matplotlib waits 25 seconds for before continuing. 

### Code for reproduction

```python
import matplotlib.pyplot; matplotlib.pyplot.figure()
```

### Actual outcome

```
>>> import matplotlib.pyplot; matplotlib.pyplot.figure()
# /home/walter/.local/lib/python3.10/site-packages/matplotlib/__pycache__/__init__.cpython-310.pyc matches /home/walter/.local/lib/python3.10/site-packages/matplotlib/__init__.py

<SNIP>

import 'matplotlib.backends._backend_gtk' # <_frozen_importlib_external.SourceFileLoader object at 0x7fdd45ac23b0>
import 'matplotlib.backends.backend_gtk4' # <_frozen_importlib_external.SourceFileLoader object at 0x7fdd4653ec50>
import 'matplotlib.backends.backend_gtk4agg' # <_frozen_importlib_external.SourceFileLoader object at 0x7fdd46507e20>




### WAITS HERE FOR 25 SECONDS




<Figure size 640x480 with 0 Axes>
```

### Expected outcome

No 25 second pause.

### Additional information

Running `strace -timestamps` I get:
```
10:50:10 poll([{fd=12, events=POLLIN}], 1, 25000) = 1 ([{fd=12, revents=POLLIN}])
10:50:10 read(12, "\1\0\0\0\0\0\0\0", 16) = 8
10:50:10 write(12, "\1\0\0\0\0\0\0\0", 8) = 8
10:50:10 futex(0x55da64c43bc0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
10:50:10 close(12)                      = 0
10:50:10 write(11, "\1\0\0\0\0\0\0\0", 8) = 8
10:50:10 futex(0x55da64a84150, FUTEX_WAKE_PRIVATE, 1) = 1
10:50:10 futex(0x55da64b2a4e0, FUTEX_WAKE_PRIVATE, 1) = 1
10:50:10 futex(0x55da64b24078, FUTEX_WAKE_PRIVATE, 1) = 1
10:50:10 write(11, "\1\0\0\0\0\0\0\0", 8) = 8
10:50:10 futex(0x55da64a84150, FUTEX_WAKE_PRIVATE, 1) = 1
10:50:10 futex(0x55da64b2a4e0, FUTEX_WAKE_PRIVATE, 1) = 1
10:50:10 futex(0x55da64b24078, FUTEX_WAKE_PRIVATE, 1) = 1
10:50:10 futex(0x55da64b22480, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
10:50:10 futex(0x55da64b22480, FUTEX_WAKE_PRIVATE, 1) = 0
10:50:10 futex(0x55da64b24078, FUTEX_WAKE_PRIVATE, 1) = 1
10:50:10 futex(0x55da64b24078, FUTEX_WAKE_PRIVATE, 1) = 1
10:50:10 eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK) = 12
10:50:10 futex(0x7f487dff1ba0, FUTEX_WAKE_PRIVATE, 1) = 0
10:50:10 write(11, "\1\0\0\0\0\0\0\0", 8) = 8
10:50:10 futex(0x55da64b24078, FUTEX_WAKE_PRIVATE, 1) = 1
10:50:10 poll([{fd=12, events=POLLIN}], 1, 25000) = 0 (Timeout)
10:50:35 write(12, "\1\0\0\0\0\0\0\0", 8) = 8
```

So this is definitely a timeout of 25 seconds somewhere.

### Operating system

Arch

### Matplotlib Version

3.6.3

### Matplotlib Backend

GTK4Agg

### Python version

Python 3.10.9

### Jupyter version

N//A

### Installation

pip

**Comment by WalterSmuts** [comment] 2023-01-20 09:10
No timeout on subsequent calls. So this is some sort of initialisation bug.

**Comment by tacaswell** [comment] 2023-01-20 15:55
Does this only happen with the gtk backend?  And if so, can you try running https://github.com/matplotlib/matplotlib/blob/e6bf91dcfd8bb97490703d448804c631b33e2d5b/lib/matplotlib/backends/backend_gtk4.py#L11-L25 in isolation?  My guess (hope) is that this is actually a gtk / gi issue.

**Comment by WalterSmuts** [comment] 2023-01-20 16:51
> Does this only happen with the gtk backend? 

Just tried with `QtAgg` and it's fine.

> And if so, can you try running

Sure:
```
[walter@cuddles ~]$ cat temp.py
try:
    import gi
except ImportError as err:
    raise ImportError("The GTK4 backends require PyGObject") from err

try:
    # :raises ValueError: If module/version is already loaded, already
    # required, or unavailable.
    gi.require_version("Gtk", "4.0")
except ValueError as e:
    # in this case we want to re-raise as ImportError so the
    # auto-backend selection logic correctly skips.
    raise ImportError from e

from gi.repository import Gio, GLib, Gtk, Gdk, GdkPixbuf
[walter@cuddles ~]$ time python temp.py

real	0m0.089s
user	0m0.063s
sys	0m0.030s
```

**Comment by tacaswell** [comment] 2023-01-20 16:59
oh, I read the stack trace upside down 🤦🏻 .  Can you also add:

https://github.com/matplotlib/matplotlib/blob/e6bf91dcfd8bb97490703d448804c631b33e2d5b/lib/matplotlib/backends/_backend_gtk.py#L16-L26

**Comment by WalterSmuts** [comment] 2023-01-20 17:01
```
[walter@cuddles ~]$ cat temp.py
try:
    import gi
except ImportError as err:
    raise ImportError("The GTK4 backends require PyGObject") from err

try:
    # :raises ValueError: If module/version is already loaded, already
    # required, or unavailable.
    gi.require_version("Gtk", "4.0")
except ValueError as e:
    # in this case we want to re-raise as ImportError so the
    # auto-backend selection logic correctly skips.
    raise ImportError from e

from gi.repository import Gio, GLib, Gtk, Gdk, GdkPixbuf
import gi
 # The GTK3/GTK4 backends will have already called `gi.require_version` to set
 # the desired GTK.
from gi.repository import Gdk, Gio, GLib, Gtk


try:
    gi.require_foreign("cairo")
except ImportError as e:
    raise ImportError("Gtk-based backends require cairo") from e
[walter@cuddles ~]$ time python temp.py

real	0m0.089s
user	0m0.077s
sys	0m0.017s
```

**Comment by tacaswell** [comment] 2023-01-20 17:02
> No timeout on subsequent calls. So this is some sort of initialisation bug.

Another clarification, do you mean "subsequent calls to `plt.figure()` in the same process or subsequent processes?  If it is the second, then I suspect the font finding / caching logic...

**Comment by WalterSmuts** [comment] 2023-01-20 17:05
I mean a subsequent calls in a single process. Each new process does the 25 second wait. Subsequent calls to `matplotlib` does not.

**Comment by tacaswell** [comment] 2023-01-20 17:13
ok so that rules out the font discovery (failure to cache could cause it to be slow every time, but I would expect it hang on the import of `font_manager` and to affect both Qt and Gtk). 

I think you have ruled out any issue with gtk imports, which means the hang is probably in either creating the gtk application or the first window: https://github.com/matplotlib/matplotlib/blob/e6bf91dcfd8bb97490703d448804c631b33e2d5b/lib/matplotlib/backends/_backend_gtk.py#L140-L141 the `_create_application` helper is where we do the "create the application just once" dance.  Given that creating the second window is fast, my next guess as to where the problem is is: https://github.com/matplotlib/matplotlib/blob/e6bf91dcfd8bb97490703d448804c631b33e2d5b/lib/matplotlib/backends/_backend_gtk.py#L49-L62

Would you be willing to bisect your way through those calls to sort out where the hang is?

**Comment by jklymak** [comment] 2023-01-20 17:20
have we tested a hello-world?  https://www.tutorialspoint.com/pygtk/pygtk_hello_world.htm

**Comment by WalterSmuts** [comment] 2023-01-20 17:24
> Would you be willing to bisect your way through those calls to sort out where the hang is?

It's on the `_application.register()` call.

**Comment by WalterSmuts** [comment] 2023-01-20 17:41
> Perhaps more appropriate: https://pygobject.readthedocs.io/en/latest/getting_started.html

Doesn't have the issue.

**Comment by QuLogic** [comment] 2023-01-21 00:24
`Gtk.Application.register` will register a DBus name for uniqueness, and to pass flags from a secondary invocation to the primary one. Unfortunately, the bus connection still happens even if we pass `Gio.ApplicationFlags.NON_UNIQUE`.

I'm pretty sure DBus has a 20-30-ish second timeout, so I think your DBus is broken. Perhaps `DBUS_SESSION_BUS_ADDRESS` is incorrectly set in your environment.

You can check this with:
```python
from gi.repository import Gio
Gio.bus_get_sync(Gio.BusType.SESSION, None)
```

**Comment by WalterSmuts** [comment] 2023-01-21 09:25
> You can check this with:
>```
>from gi.repository import Gio
>Gio.bus_get_sync(Gio.BusType.SESSION, None)
>```

Not sure what you mean? How do I check? What do I check? If you mean I should expect the 25 second pause then I don't see it running that code snip.

**Comment by QuLogic** [comment] 2023-01-21 10:30
That is only the first step of `register`; there is much more that I didn't notice was happening. And also that we use a `GtkApplication` instead of the base `GApplication`.

The PyGObject `hello.py` is old and doesn't use the new `GApplication` framework; here is a test that should do so:
```python
import gi
gi.require_version('Gtk', '4.0')
from gi.repository import Gio, Gtk  # noqa


_application = None


def _shutdown_application(app):
    global _application
    _application = None
    print('shutdown')


_application = Gtk.Application.new('org.matplotlib.Matplotlib3',
                                   Gio.ApplicationFlags.NON_UNIQUE)
# The activate signal must be connected, but we don't care for
# handling it, since we don't do any remote processing.
_application.connect('activate', lambda *args, **kwargs: print('activate'))
_application.connect('shutdown', _shutdown_application)
_application.register()
_application.run()
```

As you said it gets stuck in `register`, this should be a minimal version that doesn't include the Matplotlib code.

**Comment by WalterSmuts** [comment] 2023-01-21 10:39
Yup, still gets stuck at the `register()` call

**Comment by tacaswell** [comment] 2023-01-23 17:34
Do we understand why the register is hanging?  This vaguely reminds me of when I was seeing 20s complete lock-ups of slack everytime I got a message that boiled down to me not running a notification services on dbus.  Are you running a minimal/cut down window manager @WalterSmuts ?

**Comment by WalterSmuts** [comment] 2023-01-23 17:57
I am :) i3. Not much else.

**Comment by QuLogic** [comment] 2023-01-24 00:24
This looks like what you're seeing: https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start i3 is not Wayland, so it's going to time out if it attempts it.

**Comment by tacaswell** [comment] 2023-01-27 18:35
I am inclined to close this as I think this is an issue of a minimal window manager being too minimal for GTK's taste

> Alternatively, set GTK_USE_PORTAL=0 in your environment.

seems like it should be the work-around?

**Closed by tacaswell** 2023-01-27 18:35 UTC
Labels: GUI: gtk
