### ISSUE TITLE
[Doc]: wrong year in copyright footer

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#21694] opened 2021-11-20 17:15 UTC
### Problem

The footer reads:

> © Copyright 2021 - 2012 John Hunter, Darren Dale, Eric Firing, Michael Droettboom and the Matplotlib development team; 2012 - 2021 The Matplotlib development team.

The first year range 2021-2012 is obviously wrong.

### Matplotlib Version

<s>3.5.0</s> devdocs

**Comment by jklymak** [comment] 2021-11-20 17:58
Where does it say that?  Thanks!

**Comment by jklymak** [comment] 2021-11-20 19:46
Ah, thats weird, I see it on the devdocs (but not stable).  Its particularly strange, as the `conf.py` is correct.

**Comment by timhoffm** [comment] 2021-11-20 20:01
Indeed it's only in the devdocs.

**Comment by QuLogic** [comment] 2021-11-20 22:49
That's automated replacement by Sphinx; I thought I pushed a fix for this, but maybe not? I'll do it on Monday then.

**Comment by QuLogic** [comment] 2021-11-20 22:50
I guess not; duplicate of #20854

**Closed by QuLogic** 2021-11-20 22:50 UTC
Labels: Documentation
