### ISSUE TITLE
Multi-page PDF file size jumps since 2.0.0

### ISSUE THREAD

**Issue by sean-lockwood** [matplotlib/matplotlib#9819] opened 2017-11-20 18:06 UTC
### Bug report

**Bug summary**

Multi-page PDFs written with PdfPages increase in size dramatically between MPL versions.

**Code for reproduction**

```python
#! /usr/bin/env python

import tempfile
import os
import sys
import numpy as np

import matplotlib
from matplotlib import pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
''' Determines a test file size for multi-page PDFs written with matplotlib PdfPages.'''

python_version = sys.version.split()[0]

def main():
    dir = tempfile.mkdtemp(prefix='tmp_matplotlib_pdf_')
    outname = os.path.join(dir, 'test_{}.pdf'.format(python_version))
    print ('Backend:  {}'.format(matplotlib.get_backend()))
    print ('Sending file to:  {}'.format(outname))
    
    with PdfPages(outname) as pdf:
        for i in range(10):      # Multi-page PDF
            for j in range(50):  # Multi-plot per page
                plt.plot(np.arange(1000), np.arange(1000) * i * j, '-x')
            
            pdf.savefig()
            plt.close()
    
    # Get the file's size:
    print ('Python {}, MPL {}:  {} KB'.format(
        python_version, matplotlib.__version__, os.path.getsize(outname) / 1e3 ))

if __name__ == '__main__':
    main()
```

**Actual outcome**

```
$ source activate astroconda
$ ./test_mpl_pdf_filesize.py 
Backend:  TkAgg
Sending file to:  /var/folders/3b/zd_kfm795gzg1jwm_ng55rc00004tj/T/tmp_matplotlib_pdf_xfbg4o6z/test_3.6.3.pdf
Python 3.6.3, MPL 2.1.0:  876.716 KB

$ source activate old_mpl
$ ./test_mpl_pdf_filesize.py 
Backend:  TkAgg
Sending file to:  /var/folders/3b/zd_kfm795gzg1jwm_ng55rc00004tj/T/tmp_matplotlib_pdf_nsxx71a0/test_3.5.4.pdf
Python 3.5.4, MPL 2.0.0:  250.257 KB
```

**Expected outcome**

File sizes should have remained relatively constant between versions.  I had a real-world ~250 page PDF scale from 750 KB to 52 MB on upgrade of MPL.

**Matplotlib version**
  * Operating system:  Mac OS X 10.12.6 (Sierra)
  * Matplotlib version:  2.1.0 (old_mpl environ had 2.0.0)
  * Matplotlib backend:  TkAgg
  * Python version:  3.6.3 (old_mpl environ had 3.5.4)
  * Other libraries:  numpy 1.13.3 (old_mpl environ had 1.12.1)

matplotlib installed via anaconda3 conda, channel=http://ssb.stsci.edu/astroconda

**Comment by jklymak** [comment] 2017-11-20 18:16
Dupe of #9716 fixed via #9724.  Thanks

**Closed by jklymak** 2017-11-20 18:16 UTC
Labels: Duplicate

**Comment by afvincent** [comment] 2017-11-20 18:17
Indeed :):
```
Python 3.6.2, MPL 2.1.0.post808+g3ccaf2d66:  250.301 KB
```

**Comment by tacaswell** [comment] 2017-11-20 18:44
Sorry about that!

2.1.1 should be tagged this week.
