### ISSUE TITLE
Error building documentation

### ISSUE THREAD

**Issue by pibion** [matplotlib/matplotlib#16668] opened 2020-03-05 01:05 UTC
### Bug report

**Bug summary**

Error when building documentation.

**Code for reproduction**

$ make html
Running Sphinx v2.2.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/aroberts/anaconda3/lib/python3.7/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/home/aroberts/anaconda3/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/mnt/c/Users/canto/Repositories/matplotlib/doc/conf.py", line 90, in <module>
    import sphinxext.gallery_order as gallery_order
  File "/mnt/c/Users/canto/Repositories/matplotlib/doc/sphinxext/gallery_order.py", line 6, in <module>
    from sphinx_gallery.sorting import ExplicitOrder
  File "/home/aroberts/anaconda3/lib/python3.7/site-packages/sphinx_gallery/sorting.py", line 16, in <module>
    from .gen_rst import extract_intro_and_title
  File "/home/aroberts/anaconda3/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 35, in <module>
    from .scrapers import (save_figures, ImagePathIterator, clean_modules,        File "/home/aroberts/anaconda3/lib/python3.7/site-packages/sphinx_gallery/scrapers.py", line 52, in <module>
    _import_matplotlib()
  File "/home/aroberts/anaconda3/lib/python3.7/site-packages/sphinx_gallery/scrapers.py", line 46, in _import_matplotlib
    import matplotlib.pyplot as plt
  File "/mnt/c/Users/canto/Repositories/matplotlib/lib/matplotlib/pyplot.py", line 44, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/mnt/c/Users/canto/Repositories/matplotlib/lib/matplotlib/figure.py", line 17, in <module>
    from matplotlib import docstring, projections
  File "/mnt/c/Users/canto/Repositories/matplotlib/lib/matplotlib/projections/__init__.py", line 4, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/home/aroberts/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/home/aroberts/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 42, in <module>
    class Axes3D(Axes):
  File "/home/aroberts/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 52, in Axes3D
    azim=-60, elev=30, zscale=None, sharez=None, proj_type='persp',
  File "/mnt/c/Users/canto/Repositories/matplotlib/lib/matplotlib/docstring.py", line 77, in dedent_interpd
    return interpd(func)
  File "/mnt/c/Users/canto/Repositories/matplotlib/lib/matplotlib/docstring.py", line 38, in __call__
    func.__doc__ %= self.params
KeyError: 'scale'

Makefile:30: recipe for target 'html' failed
make: *** [html] Error 2

**Matplotlib version**
  * Operating system: WLS2 
  * Matplotlib version: 3.2.0rc2+1631.g94e8edd55
  * Matplotlib backend: `print(matplotlib.get_backend())` returns the same error as `make html`
  * Python version: 3.7.4
  * sphinx: 2.2.0
  * colorspacious: 1.1.2
  * ipython: 7.8.0
  * ipywidgets: 7.5.1
  * numpydoc: 0.9.1
  * pillow: 6.2.0
  * sphinx-gallery: 0.5.0
  * sphinx-copybutton: 0.2.8

I installed this environment by following the "Writing documentation" guidelines:

```
pip install -e .
pip install -r requirements/doc/doc-requirements.txt
```

**Comment by tacaswell** [comment] 2020-03-05 01:29
It looks like you are getting crossed versions by pip installing a source install on top of an existing conda installation.  If you look at the paths in the traceback they alternate between `"/home/aroberts/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py"` and `"/mnt/c/Users/canto/Repositories/matplotlib/lib/matplotlib/"`.  Try doing

```
pip uninstall matplotlib
conda uninstall matplotlib
pip install -e .
```

**Comment by pibion** [comment] 2020-03-05 19:01
Crossed versions seems to have been the problem.  

I created a "clean" conda environment and then followed the environment setup instructions on https://matplotlib.org/3.1.3/devel/documenting_mpl.html#documenting-matplotlib and the docs are building fine now.

I think the instructions linked above could make the need for a clean development environment clearer; there are also some latex package dependencies that are not listed (dvipng, cm-super).  Also, the page I linked above is very useful but tough to find.

I'd be interested in trying to modify this part of the documentation; would you recommend opening a separate issue for that, or just create a pull request?

**Comment by timhoffm** [comment] 2020-03-06 00:03
You can directly create a PR.

**Comment by SidharthBansal** [comment] 2020-04-04 15:25
I think the issue is resolved and the changes mentioned above are published on web. So, we can close this issue

**Closed** 2020-04-04 17:27 UTC
