### ISSUE TITLE
`linestyle` parameter does not support default cycler through `None`, crashes instead.

### ISSUE THREAD

**Issue by madphysicist** [matplotlib/matplotlib#6173] opened 2016-03-17 17:11 UTC
Setup
-----
`matplotlib.__version__` = 1.5.1
`matplotlib.__version__numpy__` = 1.6
Python 3.5.1, IPython 4.1.2  running under anaconda
OS: Red Hat 6.5

Matplotlib installed with `conda install matplotlib`.

Issue
-----
Supplying `None` (the object, not the string) `linestyle` parameter to `plot` (and possible others) raises an error instead of going through the default cycler for that property. I would expect the following to work, but it does not:

    >>> import matplotlib.pyplot as plt
    >>> plt.plot(range(5), range(5), linestyle=None)
    ...
    TypeError: object of type 'NoneType' has no len()

The expected behavior would be that all lines are drawn 'solid'.

If this is something that is worth fixing, I can take a look in a couple of days and maybe add code similar to what is done for the `color` argument. The docs would need to be updated too.

**Comment by WeatherGod** [comment] 2016-03-17 17:22
The complete traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nas/home/broot/centos6/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 3154, in plot
    ret = ax.plot(*args, **kwargs)
  File "/nas/home/broot/centos6/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1812, in inner
    return func(ax, *args, **kwargs)
  File "/nas/home/broot/centos6/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/axes/_axes.py", line 1424, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/nas/home/broot/centos6/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/axes/_base.py", line 386, in _grab_next_args
    for seg in self._plot_args(remaining, kwargs):
  File "/nas/home/broot/centos6/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/axes/_base.py", line 374, in _plot_args
    seg = func(x[:, j % ncx], y[:, j % ncy], kw, kwargs)
  File "/nas/home/broot/centos6/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/axes/_base.py", line 281, in _makeline
    self.set_lineprops(seg, **kwargs)
  File "/nas/home/broot/centos6/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/axes/_base.py", line 189, in set_lineprops
    line.set(**kwargs)
  File "/nas/home/broot/centos6/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/artist.py", line 937, in set
    ret.extend([func(v)])
  File "/nas/home/broot/centos6/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/lines.py", line 1026, in set_linestyle
    if len(ls) != 2:
TypeError: object of type 'NoneType' has no len()
```

**Comment by WeatherGod** [comment] 2016-03-17 17:23
The bug is somewhere between _grab_next_args() and set_lineprops(). But I haven't a clue what.

**Comment by WeatherGod** [comment] 2016-03-17 17:25
If you feel like tracking this down, be my guest... but fair warning... there be dragons in that area of code.

**Comment by madphysicist** [comment] 2016-03-17 17:25
Thanks for the traceback. This is the one time when being lazy and doing a bulk copy-and-paste would have actually been better.

**Comment by tacaswell** [comment] 2016-03-17 17:26
The full traceback is

```pytb
In [4]: plt.plot(range(3), linestyle=None)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-979d24a29f1e> in <module>()
----> 1 plt.plot(range(3), linestyle=None)

/home/tcaswell/source/p/matplotlib/lib/matplotlib/pyplot.py in plot(*args, **kwargs)
   3151         ax.hold(hold)
   3152     try:
-> 3153         ret = ax.plot(*args, **kwargs)
   3154     finally:
   3155         ax.hold(washold)

/home/tcaswell/source/p/matplotlib/lib/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1817                     warnings.warn(msg % (label_namer, func.__name__),
   1818                                   RuntimeWarning, stacklevel=2)
-> 1819             return func(ax, *args, **kwargs)
   1820         pre_doc = inner.__doc__
   1821         if pre_doc is None:

/home/tcaswell/source/p/matplotlib/lib/matplotlib/axes/_axes.py in plot(self, *args, **kwargs)
   1422             kwargs['color'] = c
   1423 
-> 1424         for line in self._get_lines(*args, **kwargs):
   1425             self.add_line(line)
   1426             lines.append(line)

/home/tcaswell/source/p/matplotlib/lib/matplotlib/axes/_base.py in _grab_next_args(self, *args, **kwargs)
    384                 return
    385             if len(remaining) <= 3:
--> 386                 for seg in self._plot_args(remaining, kwargs):
    387                     yield seg
    388                 return

/home/tcaswell/source/p/matplotlib/lib/matplotlib/axes/_base.py in _plot_args(self, tup, kwargs)
    372         ncx, ncy = x.shape[1], y.shape[1]
    373         for j in xrange(max(ncx, ncy)):
--> 374             seg = func(x[:, j % ncx], y[:, j % ncy], kw, kwargs)
    375             ret.append(seg)
    376         return ret

/home/tcaswell/source/p/matplotlib/lib/matplotlib/axes/_base.py in _makeline(self, x, y, kw, kwargs)
    279         self._setdefaults(default_dict, kw, kwargs)
    280         seg = mlines.Line2D(x, y, **kw)
--> 281         self.set_lineprops(seg, **kwargs)
    282         return seg
    283 

/home/tcaswell/source/p/matplotlib/lib/matplotlib/axes/_base.py in set_lineprops(self, line, **kwargs)
    187     def set_lineprops(self, line, **kwargs):
    188         assert self.command == 'plot', 'set_lineprops only works with "plot"'
--> 189         line.set(**kwargs)
    190 
    191     def set_patchprops(self, fill_poly, **kwargs):

/home/tcaswell/source/p/matplotlib/lib/matplotlib/artist.py in set(self, **kwargs)
    938                raise TypeError('There is no %s property "%s"' %
    939                                (self.__class__.__name__, k))
--> 940             ret.extend([func(v)])
    941         return ret
    942 

/home/tcaswell/source/p/matplotlib/lib/matplotlib/lines.py in set_linestyle(self, ls)
   1025         """
   1026         if not is_string_like(ls):
-> 1027             if len(ls) != 2:
   1028                 raise ValueError()
   1029 

TypeError: object of type 'NoneType' has no len()
```

probably should be fixed in `_make_line` by removing any `None` valued kwargs from `**kwargs` in `_makeline`.

**Comment by madphysicist** [comment] 2016-03-17 17:27
I like the full one better than the complete one :) Thanks for the pointer, I will have a look in a couple of days.

**Comment by WeatherGod** [comment] 2016-03-17 17:28
I am not entirely sure that is the correct assessment. By that point, I think it should have gotten its value from the cycler.

**Comment by WeatherGod** [comment] 2016-03-17 17:29
Ah, maybe the problem is that the cycler doesn't have a value available for that kwarg, so it leaves it alone! I wonder if the cycler has a linestyle, then it would work?

**Comment by tacaswell** [comment] 2016-03-17 17:38
I actually think the `self.set_lineprops` line is redundant.  It looks like `self._set_defaults` updates the user supplied kwargs and then passes them directly to the `Line2D` constructor (which correctly handles the `None`).

**Comment by WeatherGod** [comment] 2016-03-17 17:44
Give it a shot and see what happens. I doubt it is really redundant, but I don't have any time to look into it right now. Lots of dragons there, so a lot of the stuff is the way it is because I didn't want to change what has been there for a long time...

**Comment by tacaswell** [comment] 2016-03-17 18:04
:dragon:  :disappointed:

**Comment by madphysicist** [comment] 2016-03-17 18:11
Let's turn that dragon upside down.

**Comment by tacaswell** [comment] 2016-03-17 18:15
Ok, sorted this dragon out, PR shortly.

**Closed** 2016-05-16 20:59 UTC
Labels: confirmed bug, Difficulty: Easy
