### ISSUE TITLE
[Bug]: Subgridspec fails to place aces appropriately

### ISSUE THREAD

**Issue by jwdebelius** [matplotlib/matplotlib#22302] opened 2022-01-24 13:05 UTC
### Bug summary

I'm attempting to generate a figure with 9 panels. The top and bottom row are specified as subgridspecs so I could keep their dimensions separate from the constrained layout in the rest of the figure, and not have the positions influenced by axis labels in the middle axes.

### Code for reproduction

```python
import matplotlib.pyplot as plt
%matplotlib inline # Working in a jupyter notebook

fig = plt.figure(
    constrained_layout=True,
    facecolor='None',
    figsize=(6,6.5),
    )

gs = fig.add_gridspec(3, 3)
gs_0 = gs[0, :].subgridspec(1, 3)
ax_3d_0 = fig.add_subplot(gs_0[0])
ax_3d_1 = fig.add_subplot(gs_0[1], sharex=ax_3d_0, sharey=ax_3d_0)
ax_3d_2 = fig.add_subplot(gs_0[2], sharex=ax_3d_0, sharey=ax_3d_0)


for i, ax in enumerate([ax_3d_0, ax_3d_1, ax_3d_2]):
    ax.text(0.5, 0.5, f'gs_0[{i}]',
            size=10, ha='center', va='center')


gs_lo = gs[2, :].subgridspec(1, 3)    
ax_leg_0 = fig.add_subplot(gs_lo[0])
ax_leg_1 = fig.add_subplot(gs_lo[1])
ax_leg_2 = fig.add_subplot(gs_lo[2])

for i, ax in enumerate([ax_leg_0, ax_leg_1, ax_leg_2]):
    ax.text(0.5, 0.5, f'gs_lo[{i}]',
            size=10, ha='center', va='center')
```

### Actual outcome

![image](https://user-images.githubusercontent.com/5534846/150771687-0ec47dbb-88e1-4a59-a097-19f5c17e9315.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/5534846/150787811-d7066875-7406-4e27-9057-08f8dc6fb3cd.png)

### Additional information

In a previous version (python 3.6.10, matplotlib 3.2.2), I had no issues.

In my current version (python 3.8. matplotlib 3.5.0) all the subgridspec axes end up on top of each other (see actual outcome)

### Operating system

osx

### Matplotlib Version

matplotlib 3.5.0

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.8.12

### Jupyter version

3.2.5

### Installation

conda

**Comment by jklymak** [comment] 2022-01-24 13:11
Thanks, this is a duplicate of https://github.com/matplotlib/matplotlib/issues/22143 and will be fixed in 3.5.2.  Sorry this broke, and note the hack workaround in that issue if you want to work around this in 3.5.1 for now.

**Closed by jklymak** 2022-01-24 13:11 UTC
Labels: topic: geometry manager

**Comment by jklymak** [comment] 2022-01-24 13:19
> and not have the positions influenced by axis labels in the middle axes.

BTW, have you tried rearranging using subfigures instead?   They are maybe a little easier to parse, and accomplish the same thing with constrained_layout.

**Comment by jwdebelius** [comment] 2022-01-24 13:28
Thank you @jklymak, sorry to have missed the duplicate! I did try to look, but I think my search was ineffective. I'll look at the hack and subfigures.
