### ISSUE TITLE
Undefined dictionary in __init__.py when used with Pyinstaller 

### ISSUE THREAD

**Issue by NHades** [matplotlib/matplotlib#18256] opened 2020-08-14 14:15 UTC
**Bug summary**
When using Pyinstaller in version 3.3.1, I get an error message that "defaultParams" is not defined. 
The dictionary is located in __ init __.py @ line # 563 (Version 3.3.1).

In Version 3.2.2, "defaultParams" was imported from rcsetup at beginning of file, but in version 3.3.1 it is not present 

Version 3.2.2 ==> **from matplotlib.rcsetup import defaultParams, validate_backend, cycler** 
Version 3.3.1 ==> **from matplotlib.rcsetup import validate_backend, cycler**

The only other location where  "defaultParams"  can be brought into __ init __.py is @ line # 916, but maybe it is too far down for program to see.

I tried adding the import back, but does not work :)

**Code for reproduction**
No code, just regular freezing in Pyinstaller 

**Actual outcome**
```
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "matplotlib\__init__.py", line 905, in <module>
  File "matplotlib\cbook\__init__.py", line 480, in _get_data_path
  File "matplotlib\__init__.py", line 239, in wrapper
  File "matplotlib\__init__.py", line 534, in get_data_path
  File "matplotlib\__init__.py", line 239, in wrapper
  File "matplotlib\__init__.py", line 563, in _get_data_path
NameError: name 'defaultParams' is not defined
```

  * Operating system: Win 10
  * Matplotlib version:  3.3.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): matplotlib.backends.backend_qt5agg
  * Python version: 3.7.7
  * Other libraries: PyQt5: 5.15.0

**Comment by timhoffm** [comment] 2020-08-14 15:54
Duplicate of #18180.

**Closed by timhoffm** 2020-08-14 15:54 UTC

**Comment by NHades** [comment] 2020-08-14 16:25
Thanks, did not see that one.
