### ISSUE TITLE
Colorbar: changing the norm does not update the Formatter

### ISSUE THREAD

**Issue by rayosborn** [matplotlib/matplotlib#7711] opened 2016-12-30 19:22 UTC
I have Matplotlib embedded in another application, and testing v2.0.0rc, I discovered that the colorbar, when using LogNorm without setting any options, except the minimum and maximum values, appears to have changed since v1.5.1, without any change in my code. I just do 

    self.image.set_norm(LogNorm(self.vaxis.lo, self.vaxis.hi))

I don't know if this is a bug, or if the default behavior is now different and requires me to select tick marks manually.  If someone is able to give some tips of what to look for, I will investigate the systematics more thoroughly.

I'm using Python 2.7.11 (Conda installation on Mac OS X 10.11.6).

![mpl_151](https://cloud.githubusercontent.com/assets/1193959/21571162/129218b8-ce92-11e6-96bf-3e8ebc19b425.png)
Matplotlib v1.5.1
![mpl_200rc2](https://cloud.githubusercontent.com/assets/1193959/21571161/1291f392-ce92-11e6-896b-9c03e442866c.png)
Matplotlib v2.0.0rc

**Comment by efiring** [comment] 2016-12-30 21:39
It's a bug.  It should not be putting in those minor ticks when you have a range this large.

**Comment by efiring** [comment] 2016-12-30 21:47
@rayosborn, would you post a minimal example illustrating this, please?  My first quick attempt to reproduce it has failed, so either the bug has been fixed after the rc you are using, or there is a subtle difference between your case and my attempted test case.

**Comment by rayosborn** [comment] 2016-12-31 16:04
The code is embedded in nexpy (http://nexpy.github.io/nexpy/), which is an application for viewing HDF5 data. I tried to extract the relevant code, but if you want to use my example data, which I have attached here, you will have to install the Python API that nexpy uses to read the HDF5 files, by doing `pip install nexusformat`. This is a fairly small module, but it requires h5py.

I think this code shows the excess tick marks. I'm having trouble extracting the code that produces all the overlapping colorbar labels - I think it may be related to using GridHelperCurveLinear in one of the Matplotlib toolkits with the MaxNLocator function, but my initial test adding the grid helper to the code below produced the same plot:

    import numpy as np
    import matplotlib.pyplot as plt
    from matplotlib.colors import LogNorm
    from nexusformat.nexus import *
    
    nxs_file = nxload('colorbar_test.nxs')
    
    signal = nxs_file['entry/data'].nxsignal
    axes = nxs_file['entry/data'].nxaxes
    
    data = signal.nxdata
    x = axes[-1].nxdata
    y = axes[-2].nxdata
    
    extent = (x[0], x[-1], y[0], y[-1])
    
    zmin = max(np.nanmin(data[data>-np.inf]), 0.01)
    zmax = np.nanmax(data[data<np.inf])
    norm = LogNorm(zmin, zmax)
    
    plt.ion()
    plt.autoscale(enable=True)
    plt.clf()
    ax = plt.gca()
    
    im = ax.imshow(data, extent=extent, norm=norm, origin='lower')
    im.get_cmap().set_bad('k', 1.0)
    ax.set_xlim(x[0], x[-1])
    ax.set_ylim(y[0], y[-1])
    ax.set_aspect('auto')
    plt.colorbar(im, ax=ax)
    plt.show()

[colorbar_test.nxs.zip](https://github.com/matplotlib/matplotlib/files/679685/colorbar_test.nxs.zip)

**Comment by efiring** [comment] 2016-12-31 16:31
The colorbar knows nothing about the data in the image it is connected to; and when it is called with no arguments other than what you show avove, the only things relevant to its axis ticking are the norm and the vmin and vmax in that norm.

What are your values for `self.vaxis.lo, self.vaxis.hi`?

Note also that the v1.5.1 result you show is incorrect; with a log norm, there should not be a tick labeled as "0".

Do I understand correctly that the code sample above does *not* give the incorrect plots you show above?

**Comment by rayosborn** [comment] 2016-12-31 16:45
I've made some progress. What I do in the program is plot the data with a linear scale, and then call set_norm to change it to a log scale. If I do that in the above code, I reproduce the problem with the overlapping colorbar text labels:

    import numpy as np
    import matplotlib.pyplot as plt
    from matplotlib.colors import LogNorm
    from nexusformat.nexus import *
    
    nxs_file = nxload('colorbar_test.nxs')
    
    signal = nxs_file['entry/data'].nxsignal
    axes = nxs_file['entry/data'].nxaxes
    
    data = signal.nxdata
    x = axes[-1].nxdata
    y = axes[-2].nxdata
    
    extent = (x[0], x[-1], y[0], y[-1])
    
    zmin = max(np.nanmin(data[data>-np.inf]), 0.01)
    zmax = np.nanmax(data[data<np.inf])
    norm = LogNorm(zmin, zmax)
    
    plt.ion()
    plt.autoscale(enable=True)
    plt.clf()
    ax = plt.gca()
    
    im = ax.imshow(data, extent=extent, origin='lower')
    im.get_cmap().set_bad('k', 1.0)
    ax.set_xlim(x[0], x[-1])
    ax.set_ylim(y[0], y[-1])
    ax.set_aspect('auto')
    cb = plt.colorbar(im, ax=ax)
    im.set_norm(norm)
    cb.set_norm(norm)
    cb.draw_all()
    plt.show()

Note that if I add `norm=norm` to the imshow command, this doesn't happen, even if I leave the subsequent calls to `set_norm` . It seems to be crucial to call `set_norm` on a previous linear plot.

**Comment by efiring** [comment] 2016-12-31 16:56
Yes, this is inherent in the present design.  The colorbar selects its Locator and Formatter based on the norm it has when it is created, and isn't smart enough to recognize that it needs to change them when the norm is changed.  This is not a regression, but it is a bug, so I am going to move the milestone for fixing it.  It probably makes sense to fix it in the context of other improvements in colorbar rather than trying to slap in a quick patch.

**Comment by rayosborn** [comment] 2016-12-31 17:27
So for the time being, I presume I should look into resetting the default Log Formatter automatically. Do you think this will be fixed before v2.0 is officially released?

**Comment by efiring** [comment] 2016-12-31 18:53
No, it will not be changed before v2.0.  Is there a reason you can't set the norm before making the colorbar?

**Comment by rayosborn** [comment] 2016-12-31 19:08
It's an interactive program, where people can switch log scaling on or off with a checkbox at any time. Obviously, I can make that trigger a new call to imshow each time, but I had assumed that calling the axis update functions was more efficient. I now realize that it wasn't changing the formatter before in MPL v1.5.1, but the problem only became obvious when v2.0.0rc added extra tick marks making the text labels overlap.

**Comment by efiring** [comment] 2016-12-31 19:27
It's possible there is a simple bug, and/or a simple workaround.  I'm investigating.

**Comment by efiring** [comment] 2016-12-31 20:00
Not so simple (to put it mildly).  As a workaround, though, you can try having your scaling-switch callback explicitly set the formatter appropriately.  Here is what is happening in the colorbar __init__, as a guide to the appropriate cbar formatter changes:
```python
            if isinstance(self.norm, colors.LogNorm):
                self.formatter = ticker.LogFormatterSciNotation()
            elif isinstance(self.norm, colors.SymLogNorm):
                self.formatter = ticker.LogFormatterSciNotation(
                                        linthresh=self.norm.linthresh)
            else:
                self.formatter = ticker.ScalarFormatter()
```
Then call `cbar.update_normal(im)` where `im` is your image object.  That might be sufficient.  I'm not sure because there is still something in all this that I haven't figured out.

**Comment by rayosborn** [comment] 2017-01-01 17:12
That is basically what I have done. The following now works when I switch to log scaling (in the context of the program):

      self.colorbar.set_norm(LogNorm(self.vaxis.lo, self.vaxis.hi))
      self.colorbar.locator = ticker.LogLocator()
      self.colorbar.formatter = ticker.LogFormatterSciNotation()
      self.image.set_norm(LogNorm(self.vaxis.lo, self.vaxis.hi))

I have an option for setting symmetric log plots as well, and discovered that I had to set the normalization of the colorbar before I set the image normalization. This was because, with a Qt4Agg backend, the call to `self.image.set_norm(SymLogNorm(...)` triggered a call to `backend_qt5agg.__draw_idle_agg` in the background, which tried to redraw the color bar with the old `LogNorm` normalization, producing a negative value exception. I guess there is probably a Qt signal I need to block when changing the normalization. If you think this counts as a potential bug, I can raise another issue.

**Comment by efiring** [comment] 2017-01-01 17:35
It's certainly a bug, but I think it is just part of the original bug: the colorbar is not getting updated properly when the image norm is changed.

**Comment by rayosborn** [comment] 2017-01-01 17:53
By the way, the question you asked about the v1.5.1 behavior, i.e., why there was a zero value in the color bar, is because the formatter was never changed from ScalarFormatter when the log normalization was chosen. The zero value was a rounded version of 0.1. So this bug was affecting my application all along, but it only became obvious when the density of tick marks increased in v2.0.0rc so I never looked into it.

**Comment by rayosborn** [comment] 2017-01-01 18:19
I found a place where the colorbar might need updating to prevent this. I would issue a pull request, but I can't currently test this because my installation of the latest development version of Matplotlib won't run since I don't have a compatible version of libpng, and I can't work out how to update it.

I think in colorbar.py, a call to set_norm should be added:

    def on_mappable_changed(self, mappable):
        """
        Updates this colorbar to match the mappable's properties.

        Typically this is automatically registered as an event handler
        by :func:`colorbar_factory` and should not be called manually.

        """
        self.set_norm(mappable.norm)
        self.set_cmap(mappable.get_cmap())
        self.set_clim(mappable.get_clim())
        self.update_normal(mappable)

A similar update is probably needed in mpl_toolkits/axes_grid1/axes_grid.py, but I'm not sure I know how to trigger this.

**Comment by efiring** [comment] 2017-01-01 18:24
Yes, I was looking at that spot also, but there is more: the formatter selection logic needs to be moved out of the __init__ and into the same location as the locator selection logic, saving the initial setting of the 'format' kwarg for reuse there.

**Comment by efiring** [comment] 2017-01-01 22:10
Are you using the colorbar from axes_grid1?

**Comment by rayosborn** [comment] 2017-01-02 15:10
No - not directly. I do have an option for skewing axes, which uses mpl_toolkit.axisartist.Subplot, through `figure.add_subplot`. The colorbar is then added with a call to `figure.colorbar`. I don't know if this invokes the axes_grid1 colorbar. However, the behavior I have been describing also happens for non-skewed axes. I only mentioned axes_grid1 because I noticed there was a colorbar update signal in the code.

**Comment by jklymak** [comment] 2021-09-16 11:33
I _think_ this is closed by the latest colorbar changes, but I couldn't test directly because there is no self-contained test here.    But

```python

from matplotlib.colors import LogNorm
import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
im = ax.imshow(np.abs(np.random.randn(30, 30))*100, norm=LogNorm(0.03, 20))
fig.colorbar(im)
plt.show()
```

yields 

![testCB](https://user-images.githubusercontent.com/1562854/133604959-5d82b8c1-1b1f-4576-8747-ae013cc31eb9.png)

**Closed by jklymak** 2021-09-16 11:33 UTC
