### ISSUE TITLE
[Bug]: `hexbin` incorrect bin sizes.

### ISSUE THREAD

**Issue by astromancer** [matplotlib/matplotlib#26202] opened 2023-06-27 16:45 UTC
### Bug summary

Cells are sized incorrectly. This becomes more apparent with larger grid size.

![hexbin_weird](https://github.com/matplotlib/matplotlib/assets/5623552/86c9829d-c019-4d56-8e21-d6acbc9ed2a8)

Zoom of rightmost plot:
![Screenshot from 2023-06-27 18-29-07](https://github.com/matplotlib/matplotlib/assets/5623552/a609cc3a-8fc8-4258-ae49-10ce3eec33d9)

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal


np.random.seed(112233)
mu = (0, 0)
sigma = ([0.8,  0.3],
         [0.3,  0.5])
res = 2 ** 3
rv = multivariate_normal(mu, np.array(sigma))

fig, axes = plt.subplots(1, 3, figsize=(10, 5))
for ax, gridsize in zip(axes, [10, 50, 100]):
    ax.hexbin(*rv.rvs(10000).T, gridsize=gridsize, mincnt=3)
    ax.set_title(f'{gridsize = :d}')
    
fig.savefig('hexbin_weird.png', dpi=600)
```

### Actual outcome

Hexagonal cells have incorrect size.

### Expected outcome

Hexagonal cells should not overlap with neighbours.

### Additional information

Unsure if this is a regression or just never noticed.

### Operating system

Ubuntu

### Matplotlib Version

3.8.0.dev1415+gc5f5eb35a0

### Matplotlib Backend

Qt5Agg

### Python version

Python 3.9.17

### Jupyter version

NA

### Installation

from source (.tar.gz)

**Comment by astromancer** [comment] 2023-06-27 21:10
Seems like this only happens for the default edgecolor.  Compare the two outcomes below:
```python
np.random.seed(112233)
mu = (0, 0)
sigma = ([1.8,  0.3],
         [0.3,  1.5])
rv = multivariate_normal(mu, np.array(sigma))
data = rv.rvs(10000).T

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 5), sharex=True, sharey=True)

ax1.hexbin(*data, gridsize=100, mincnt=3)
ax2.hexbin(*data, gridsize=100, mincnt=3, ec='none')
ax1.set(xlim=(-3, 3), ylim=(-3, 3))
```
![hexbin_weird3](https://github.com/matplotlib/matplotlib/assets/5623552/2ff355cf-08d7-4c86-96ec-a663cc45066b)

**Comment by ksunden** [comment] 2023-06-27 23:54
The default edgecolor is `"face"`, which is to say "match the  face color".

However, edges have a minimum width in screen space (defined by the `linewidth` parameter in points)

When the actual cells become small enough (in screen space) that the edges would fill the shapes, they start to compete with one another. (Try it with `edgecolor="k"`, that will make it much more clear what is happening)

I don't fully think setting the default facecolor to "none" is an apt path forward, that is considered an API change that would at least have to go through a deprecation period, which would be a pretty awkward one, but additionally leaves undesirable tiny slivers of gaps between the hexagons (which are more fine as the grid gets finer, but rather apparent for the larger hexagons). Covering such slivers is the main reason `edgecolor` defaults to `face` in the first place

The default linewidth was changed from hard coded 1.0 to refer to the `"patch.linewidth"` rc param in b0910984 (#25044), due out in mpl 3.8 next month or so. That RC param has the same default value, though, so unless it is set by code or style sheet, the behavior will be the same.

Given that the workarounds (either setting `lw=0` or `ec="none"`) are relatively easy, and the alternative to change it would have pretty widescale effect (changing defaults is rather hard, as many people rely on the default behavior), I would lean towards closing this with no action.

**Comment by astromancer** [comment] 2023-06-28 09:00
Thanks for the explanation of what happening here. Totally makes sense to keep the default edgecolor as 'face' for the reasons you mention, however..

If the default value of linewidth is being changed for the next major release in any case, why not change it to something that actually produces correct results? If the only argument for defaulting to `"patch.linewidth"` rc param is consistency, I would say this not strong enough to favour knowingly producing incorrect results.

**Comment by ksunden** [comment] 2023-06-28 14:45
It's being changed, but it also isn't. yes it's sourced from an rcparam, but that rcparam has the same value (by default), so the change for most users won't affect anything. Changing the value would be a larger api change.

I'm not _totally_ against changing the value, but also still think the path to do so is messier than I'd like still.

- Ideally we would not make a change without warning users (especially for default behavior)
- How do we warn the users using the default behavior who care, without annoying the (probably more numerous) users of the default behavior that don't care with warnings they can't get rid of?
- Some users clearly want to set it via rcparam, so would we need an rcparam specifically for hexbin linewidth? If so what else would need similar? because it feels unexpected that only one thing would have such a param.
- Could it share a param with eg pcolor? that currently defaults to 0.25, but a value of 0.25 for hexbin makes the gaps clearly visible in our hexbin test images, which I think is undesirable, so probably want something a bit higher by default
- Even if we lower the default, it's not actually changing the problem, just making it less noticeable for certain grid sizes. An improvement, perhaps, but not really a "fix".


So weighing it all out, I think I still fall on the side of "the complexity of the change outweighs the utility of the change, especially given how easy the workaround is for the users who care". That said, I would happily accept a documentation change making the workaround easier to learn.

Like I said, I'm not totally against. If consensus forms around either "it's worth the difficulty of the transition" or "there's an easier path", I'd not stand in the way, but this is my starting position for those conversations. Happy to hear other opinions (especially from other maintainers who would bear the brunt of the burden from making such a change).

**Comment by dstansby** [comment] 2024-02-24 12:31
Thanks for reporting - I think this is a duplicate of https://github.com/matplotlib/matplotlib/issues/7841, which was closed in favour of https://github.com/matplotlib/matplotlib/issues/1188, so I'll close this too.

**Closed by dstansby** 2024-02-24 12:31 UTC
