### ISSUE TITLE
AttributeError: Unknown property fontfamily

### ISSUE THREAD

**Issue by Bhard27** [matplotlib/matplotlib#18369] opened 2020-08-28 01:32 UTC
### Bug report

**Bug summary**

**Code for reproduction**

```python
fig, ax = plt.subplots(figsize=(18, 14))
sns.set_style('whitegrid')

world_map.plot(ax=ax, color='white', edgecolor='black', alpha=1)
ax.set_title('First infected humans', 
             loc='left', fontdict={'fontsize': 24, 
                                   'fontfamily': 'monospace', 
                                   'fontweight': 'bold',
                                   'color': 'black'})

ax.scatter(105.7633, 35.3790, color='orangered', s=200, alpha=0.8)
ax.text(115.7633, 30.3790, 'Wuhan, China \nin 2020', 
        fontfamily='monospace', fontsize=12, fontweight='bold',
        color='white', backgroundcolor='black')

ax.set_axis_off()
plt.savefig("img.png", bbox_inches='tight')
```

**Actual outcome**

```
AttributeError                            Traceback (most recent call last)
<ipython-input-39-89da488024c9> in <module>
      7                                    'fontfamily': 'monospace',
      8                                    'fontweight': 'bold',
----> 9                                    'color': 'black'})
     10 
     11 ax.scatter(105.7633, 35.3790, color='orangered', s=200, alpha=0.8)

/opt/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py in set_title(self, label, fontdict, loc, pad, **kwargs)
    198         title.update(default)
    199         if fontdict is not None:
--> 200             title.update(fontdict)
    201         title.update(kwargs)
    202         return title

/opt/anaconda3/lib/python3.7/site-packages/matplotlib/text.py in update(self, kwargs)
    183         sentinel = object()  # bbox can be None, so use another sentinel.
    184         bbox = kwargs.pop("bbox", sentinel)
--> 185         super(Text, self).update(kwargs)
    186         if bbox is not sentinel:
    187             self.set_bbox(bbox)

/opt/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py in update(self, props)
    886         try:
    887             ret = [_update_property(self, k, v)
--> 888                    for k, v in props.items()]
    889         finally:
    890             self.eventson = store

/opt/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py in <listcomp>(.0)
    886         try:
    887             ret = [_update_property(self, k, v)
--> 888                    for k, v in props.items()]
    889         finally:
    890             self.eventson = store

/opt/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py in _update_property(self, k, v)
    879                 func = getattr(self, 'set_' + k, None)
    880                 if not callable(func):
--> 881                     raise AttributeError('Unknown property %s' % k)
    882                 return func(v)
    883 

AttributeError: Unknown property fontfamily
```

**Expected outcome**

It still works but earlier there wasn't this warning. I get the same output either ways.

<img width="995" alt="Screenshot 2020-08-28 at 7 01 01 AM" src="https://user-images.githubusercontent.com/50989807/91510989-3e216500-e8fc-11ea-924d-8794913fab0f.png">

**Matplotlib version**

  * Operating system: 10.15.6 MAC OS Catalina
  * Matplotlib version: 2.2.5
  * Matplotlib backend (`print(matplotlib.get_backend())`): Shows error
  * Python version: Python 3.7.6
  * Jupyter version (if applicable):
  * Other libraries: 

 pip

**Comment by jklymak** [comment] 2020-08-28 01:41
Can you give us a reproducible example?  In particular `world_map` and `sns` are not matplotlib.

**Comment by Bhard27** [comment] 2020-08-28 01:56
So sorry, for a vague issue submission. I did some changes to the code available in the matplotlib documentation.
You can refer the following code:
```python
import matplotlib
import matplotlib.pyplot as plt

fig = plt.figure()
fig.suptitle('bold figure suptitle', fontsize=14, fontweight='bold')

ax = fig.add_subplot(111)
fig.subplots_adjust(top=0.85)
ax.set_title('axes title',loc='left', fontdict={'fontsize': 24, 
                                   'fontfamily': 'monospace', 
                                   'fontweight': 'bold',
                                   'color': 'black'})
 
             
ax.set_xlabel('xlabel')
ax.set_ylabel('ylabel')

ax.text(3, 8, 'boxed italics text in data coords', style='italic',
        bbox={'facecolor': 'red', 'alpha': 0.5, 'pad': 10})

ax.text(2, 6, r'an equation: $E=mc^2$', fontsize=15)

ax.text(3, 2, 'unicode: Institut für Festkörperphysik')

ax.text(0.95, 0.01, 'colored text in axes coords',
        verticalalignment='bottom', horizontalalignment='right',
        transform=ax.transAxes,
        color='black', fontsize=15)


ax.plot([2], [1], 'o')
ax.annotate('annotate', xy=(2, 1), xytext=(3, 4),
            arrowprops=dict(facecolor='black', shrink=0.05))

ax.axis([0, 10, 0, 10])

plt.show()
```

**Comment by diegopetrola** [comment] 2020-08-28 04:22
Is this the correct figure for the code above?
![image](https://user-images.githubusercontent.com/3846018/91520843-b07a5100-e8cc-11ea-8933-6daa5a2f8327.png)

If so the problem is already fixed on current `master` branch.

**Comment by QuLogic** [comment] 2020-08-28 05:28
The `fontfamily` setter was only added in Matplotlib 3. Previously, it was named [`family`](https://matplotlib.org/2.2.5/api/text_api.html#matplotlib.text.Text.set_family). I guess you found [this in current docs](https://matplotlib.org/3.3.1/api/text_api.html#matplotlib.text.Text.set_fontfamily)), which are not for Matplotlib 2.2.5. Those docs are available at https://matplotlib.org/2.2.5/

> Matplotlib version: 2.2.5
> Python version: Python 3.7.6

You're running a pretty old version, and are using Python 3 already, so there's no reason (based on Matplotlib requirements) to not update to Matplotlib 3.

**Closed by QuLogic** 2020-08-28 05:28 UTC
Labels: Community support

**Comment by Bhard27** [comment] 2020-08-28 09:09
Thanks for the clarification. I have updated to the Matplotlib 3. I work perfectly fine with family instead of fontfamily.
