### ISSUE TITLE
backend documentation is out of sync?

### ISSUE THREAD

**Issue by jni** [matplotlib/matplotlib#18195] opened 2020-08-07 03:08 UTC
If I look at the backend section of the FAQ:

https://matplotlib.org/faq/usage_faq.html#what-is-a-backend

it seems like the backend table is missing notebooks. If I instead go to the backends section of the introduction:

https://matplotlib.org/3.2.1/tutorials/introductory/usage.html#backends

I get a super similar table, but with (I think) a more up-to-date list, including the nbagg and ipympl backends. 

Tellingly, the `<title>` for the former page says "Matplotlib 2.0.2 documentation", despite having no version indicator on the URL.

Apologies if this is a duplicate — I did try a quick search but did not turn up a similar issue.

**Comment by QuLogic** [comment] 2020-08-07 04:46
That is not a current page; old ones need to be deleted.

Duplicate of #9556.

**Closed by QuLogic** 2020-08-07 04:46 UTC
