### ISSUE TITLE
User logged out on macOS

### ISSUE THREAD

**Issue by RMeli** [matplotlib/matplotlib#15241] opened 2019-09-10 11:17 UTC
### Bug report

**Bug summary**

When calling `matplotlib` on  macOS the user is logged out...

**Code for reproduction**

```python
from matplotlib import pyplot as plt

plt.plot()
plt.show()
```

**Actual outcome**

The user is logged out, the screen turns black for a few seconds and then the macOS login screen appears.

**Expected outcome**

I don't expect such a huge problem (user logged out) with the previous code snippet...

**Matplotlib version**

  * Operating system: macOS 10.14.6
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6

Python and `matplotlib` installation using `miniconda`:

```bash
conda create -n test python=3.6 ipython
conda activate test
conda install matplotlib
```

**Comment by tacaswell** [comment] 2019-09-10 11:50
This is a duplicate of https://github.com/matplotlib/matplotlib/issues/14999 and is due to an interaction betwee OSX and TK, there is nothing we can do about this on the Matplotlib.

The best work-around is to use a different backend (`matplotlib.use('qt5agg')`).

**Comment by tacaswell** [comment] 2019-09-10 11:56
Also see https://github.com/ContinuumIO/anaconda-issues/issues/11165

**Comment by anntzer** [comment] 2019-09-13 22:53
Closing for the same reason as https://github.com/matplotlib/matplotlib/issues/15130#issuecomment-525067035.

**Closed by anntzer** 2019-09-13 22:53 UTC
Labels: GUI/tk, OS/Apple, Upstream fix required
