### ISSUE TITLE
Figures not correctly displaying grid lines for minor ticks

### ISSUE THREAD

**Issue by paulangton** [matplotlib/matplotlib#16339] opened 2020-01-26 22:00 UTC
### Bug report

**Bug summary**

Figures not correctly showing grid for minor ticks on one axis. 
**Code for reproduction**

```python
x = np.arange(0,100,.5)
y = 2*x**3

plt.loglog(x,y)
plt.minorticks_on()
plt.grid(True,which="both", axis="both",ls="-")
plt.show()
```

**Actual outcome**

![mpl_grid_bug](https://user-images.githubusercontent.com/7799565/73142448-abb29d80-405c-11ea-9a13-ac0d1f583ede.jpg)

**Expected outcome**
The Y axis should have minor ticks and their corresponding grid lines.

**Matplotlib version**

  * Operating system: ArchLinux (5.4.6-arch3-1)
  * Matplotlib version:  3.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version: 3.8.1
  * Jupyter version (if applicable):
  * Other libraries: 

Installed via pip

**Comment by ImportanceOfBeingErnest** [comment] 2020-01-27 00:27
A workaround would be to use a custom locator

```
locmin = matplotlib.ticker.LogLocator(base=10.0,subs=(0.2,0.4,0.6,0.8),numticks=12)
ax.yaxis.set_minor_locator(locmin)
```

So the question is, if setting the ticks on via `ax.minorticks_on()` would be expected to superseed the log locator's choice not to show minor ticks in case the axis range is large (and the absolute axes size small).

**Comment by timhoffm** [comment] 2020-01-27 07:09
My first guess is that explicitly setting minor ticks should be respected. But I‘m not clear if there are fundamental reasons the log locator would want to override this. If we‘re deciding to not follow minorticks_on, we should at least issue a warning about that.

**Comment by jklymak** [comment] 2020-01-27 15:33
The minor locator is being called.  It’s just not finding any ticks  we could change the minor locator.

**Comment by ImportanceOfBeingErnest** [comment] 2020-01-27 17:48
There is a bit of history to this through #5161, #7000, #7419, #8111, #12865. 
The problem is that the locator determines if there are minor ticks to be shown or not and reading through the above issues/PRs it does that for good reasons. E.g. for small ranges you would need minor ticks, even if they haven't been turned on explicitely, but for large ranges minor ticks would overcrowd the axes; also, as seen in issue #8111 one needs to be a bit careful which minor ticks to show.

To me it looks like fixing this would require the locator to query the axes if minor ticks have been set on *explixitely* by the user and then come up with a logic for which minor ticks to show in such case where major ticks are more than a decade away from each other.

**Comment by oscargus** [comment] 2022-06-04 16:52
This seems to have been solved at some stage. With the current `main` branch this gives:
![image](https://user-images.githubusercontent.com/8114497/172017240-3faf82ca-2e1f-4c53-b3f9-15f576d00c23.png)

I'm closing this, but feel free to reopen if there are still issues.

**Closed by oscargus** 2022-06-04 16:52 UTC
