### ISSUE TITLE
[Bug] set_3d_properties type error in Matplotlib 3.5.1

### ISSUE THREAD

**Issue by jiashuhan** [matplotlib/matplotlib#22308] opened 2022-01-24 23:30 UTC
### Bug summary
I had a code that uses `animation.FuncAnimation` to generate an animation, where I update a `mpl_toolkits.mplot3d.art3d.Line3D` object using `set_data(a, b)` and `set_3d_properties(c)` where `a`, `b`, and `c` are of type `numpy.float64`. This code works perfectly in Matplotlib 3.4.3. However, after I upgraded to Matplotlib 3.5.1, it fails with the following error
```bash
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mpl_toolkits/mplot3d/art3d.py", line 175, in set_3d_properties
    zs = np.broadcast_to(zs, len(xs))
TypeError: object of type 'numpy.float64' has no len()
```

### Source
I checked the source code of `mpl_toolkits/mplot3d/art3d.py` and found that in Matplotlib 3.4.3, line 175 (the line where the error occurred) was `zs = np.broadcast_to(zs, xs.shape)` instead, and this avoids the error. I was able to make my code run again in Matplotlib 3.5.1 by changing my code to `set_data([a], [b])` and `set_3d_properties([c])`, but as expected, this would not run in 3.4.3. I am using Python 3.10.

Was this change in line 175 of `mpl_toolkits/mplot3d/art3d.py` intended?

**Comment by QuLogic** [comment] 2022-01-25 02:00
Can you please provide a simple self-contained example?

**Comment by tacaswell** [comment] 2022-01-25 03:18
Looks like that change was from https://github.com/matplotlib/matplotlib/pull/20555 which fixed one bug but introduced another.

**Comment by jiashuhan** [comment] 2022-01-25 06:17
> Can you please provide a simple self-contained example?

Here's an example. If you use the first two lines in `update`, it throws a TypeError in Matplotlib 3.5.1. This is the same issue pointed out by @christofhapp in #20555.
```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import mpl_toolkits.mplot3d.axes3d as p3

def update(step, xs, ys, zs, point):
    # use the following two lines for matplotlib 3.4.3
    point.set_data(xs[step], ys[step])
    point.set_3d_properties(position[2,step%num_steps])
    
    # use the following two lines for matplotlib 3.5.1
    #point.set_data([xs[step]], [ys[step]])
    #point.set_3d_properties([zs[step]])
    return point

fig = plt.figure()
ax = p3.Axes3D(fig, auto_add_to_figure=False)
fig.add_axes(ax)

point = ax.plot([], [], [], '.')[0]

xs = np.arange(100)
ys = np.arange(100)
zs = np.arange(100)

ax.set_xlim3d([0,100])
ax.set_ylim3d([0,100])
ax.set_zlim3d([0,100])

anim = animation.FuncAnimation(fig, update, 100,
                fargs=(xs, ys, zs, point), interval=1, blit=False)

plt.show()
```

**Comment by tacaswell** [comment] 2022-01-27 02:08
```python
    point.set_data(xs[step:step+1], ys[step:step+1])
    point.set_3d_properties(zs[step:step+1])

```

will work correctly on all version of Python.  Previously, numpy scalars would work, but if you use built in floats

```python
    point.set_data(float(xs[step]), float(ys[step]))
    point.set_3d_properties(float(zs[step]))

```

will fail on 3.4.3.

**Comment by QuLogic** [comment] 2022-01-27 08:06
The error is that `xs` is not a sequence, but they must be a sequence in 2D, so that should be required in 3D as well. This may have been a regression, but it is how it's supposed to work.

**Comment by christofhapp** [comment] 2022-01-27 08:51
No! It absolutely makes sense to plot a scalar (single point). A scalar should be interpreted as  an array with one element aswell. Because it's what it is mathematically. Don't throw a failure, make it plot a single point.

**Comment by tacaswell** [comment] 2022-01-27 18:38
> A scalar should be interpreted as an array with one element aswell. Because it's what it is mathematically.

I disagree that this is cut and dry, there is a significant amount of degeneracy at the scalar<->array boundary which is difficult to model correctly in software (see the difficulties / confusion that comes up around numpy scalars).   I do not think you are going to have much success changing anyone's mind with this argument. 

If your argument is "It is very convenient for me to pass scalars into these methods and have mpl do the scalar -> length 1 1D array", that is a reasonable position and one I find persuasive because we automatically up-cast on `ax.plot` for example.

**Comment by christofhapp** [comment] 2022-01-27 20:40
@tacaswell I don't know what you mean by up-cast. 
Yes, you're right, i didn't want to say a scalar should be of type array. What i wanted to say is more:
I want to be able to pass a scalar und the target function interprets that as an array if it is appropriate for the functionality. E.g. i want to plot points in ax.plot and my "sequence" can have any number of points including 1 and 0. I don't want to write a case distinction for that.

**Comment by QuLogic** [comment] 2022-01-27 20:42
Passing a scalar to `Axes.plot` is fine, and it adjusts single values into a sequence. But a `Line2D` is an object that represents a line, and it requires sequences. This is enforced on creation, and the lack of enforcement on `set_data` is a bug.

**Comment by jiashuhan** [comment] 2022-01-27 20:53
> Passing a scalar to `Axes.plot` is fine, and it adjusts single values into a sequence. But a `Line2D` is an object that represents a line, and it requires sequences. This is enforced on creation, and the lack of enforcement on `set_data` is a bug.

I agree with this assessment. I initially reported this because I want to know if the issue was due to a lack of enforcement for sequences or a lack of support for scalars. Clearly `Line2D` and `Line3D` objects are intended for sequences.

**Comment by christofhapp** [comment] 2022-01-27 21:18
But if i make a point plot with more than 1 point with ax.plot it becomes a Line2D automatically and if i want to update that plot with a point vector of length 1 later, it's not possible, because it's a Line2D. 
And it's not consistent with the official matplotlib description on matplotlib.org: "Plot y versus x as lines and/or markers."
the resulting object should be able to contain and update markers of length 1.

**Comment by jklymak** [comment] 2022-01-27 21:46
@christofhapp `set_data` is lower level than `ax.plot`.  All it takes is numpy arrays rather than the _many_ things ax.plot can take.  Your numpy array can have length 1.

**Comment by christofhapp** [comment] 2022-01-27 22:16
@jklymak ... that's exactly the point! :) python is an easy high-level programming language and that logic is not consistent. the same rules should apply for both functions as set_data is used for updating the data. 
and since ax.plot is able to plot markers, set_data should be able to plot data of length 1. 
plus, since ax.plot can plot markers, the resulting type should not be called Line2D, but that's a different story.

**Comment by tacaswell** [comment] 2022-06-16 04:20
> plus, since ax.plot can plot markers, the resulting type should not be called Line2D, but that's a different story.

This is a very philosophical point, is a line that you can not see still a line?

**Comment by christofhapp** [comment] 2022-06-16 14:06
> 

Discrete 2D points simply are not a line. They can be connected by lines in the given order, but theyre points still. So it's inappropriate to call them line(s). That has nothing to do with philosophy but programming consistancy.

**Comment by tacaswell** [comment] 2022-06-16 18:53
Consider:

```python
fig, ax = plt.subplots()
ln1, = ax.plot(range(5), marker='o', markerfacecolor='r', lw=5, color='w')  # not a line
ln2, = ax.plot(range(5)[::-1], marker='o', lw=5, color='r', markerfacecolor='w')  # a line
ax.set_facecolor('r')  # now ln1 is a line ln2 is not a line ?!
```

If you want to call an artists a "line" based on if you can see the connections or not is highly problematic because the visibility can depend on state outside of the line itself.  I think that `Line2D` is reasonable named because it has the potential to draw the connecting segments between the points, independent of the discern-ability of the connecting segments in the final render.

I could be misunderstanding your concern and you are saying it is problematic that `Line2D` can draw markers _at all_, but from a practical point of view markers can be critical to understanding a line plot so I guess `Line2DWithMarkers` is a better name, but we do not have (and I do not think should have `Line2DWithJustTheLine`) so taking the shorter `Line2D` for this purpose is reasonable.

I could still be misunderstanding and you are saying that `Line2D` should be reserved for things that are actually continuous functions, not discrete samplings of continuous functions, but this is both very impractical as (at least in experimental uses) we only ever have the discrete data (because we had to measure it) and it still suffers from the "change the axes color" issue to action-at-a-distance make it not a line.

**Comment by christofhapp** [comment] 2022-06-20 07:47
Mathematically we have a quantity of points (probably representing a curve consisting of a bunch of lines). They can be interpreted as a line or as markers or both at the  same time. Visible or not visible, whatever you wanna do with them. As you bring in the restriction of having to contain at least 2 points because we decide for being a Line2D shown as a Marker Plot, it throws a failure, because a Line2D needs at least 2 points. So it would be more appropriate to keep it as a point quantity (able to also contain one point) and show it as you wish (as markers, as a line plot, ....) . If it contains less than 2 points AND you interpret it as a line, you should simply don't see a Line (instead of throwing an error).

or in shorter words: Line2D updated with one element should work and be interpreted correctly without throwing an exception, because either a marker representation as well as a line representation with one element are fine.

**Comment by anntzer** [comment] 2022-06-20 08:17
Independently of whether we actually want to support that, I think the "correct" (i.e., not triggering this issue) way to spell `zs = np.broadcast_to(zs, len(xs))` (and the similar other uses of broadcast_to in the same module) would have been `_, zs = np.broadcast_arrays(xs, zs)`?

**Comment by tacaswell** [comment] 2022-06-20 22:05
> As you bring in the restriction of having to contain at least 2 points because we decide for being a Line2D shown as a Marker Plot, ...


This is incorrect, everyone agrees that `[1,]` should work (and it does), the question is should `1` work (and lets not bring numpy scalar into this ;) ).

**Closed** 2022-12-23 18:50 UTC
Labels: topic: mplot3d, status: needs clarification

**Comment by Telemaharry** [comment] 2023-06-22 04:29
Was this issue fixed? I am having the same issue.
