### ISSUE TITLE
Feature Request: Add ability to place annotations or at least "marker points" on plots in UI

### ISSUE THREAD

**Issue by cweickhmann** [matplotlib/matplotlib#8816] opened 2017-06-28 13:16 UTC
### Feature Request

This is a feature request, not a bug report. But the missing feature is brought up quite frequently by colleagues: You can format almost all features of plots in the Qt4/Qt5 plot interface, but there is no straight-forward way to highlight select points on plots.

Example:
```python
import numpy as np
import matplotlib.pyplot as plt # with Qt5 backend for instance

x = np.linspace(0, 1, 100)
y = x**2

plt.plot(x, y)
plt.show()
```

Produces a window with the desired plot. Adding a marker showing for instance that at x=0.5 the y-value is 0.25 is not possible.

In some other programs, there is either a keyboard shortcut like "M" or "A" which causes a marker (like a large black square) at the closest point of the closest plot.

I've visualised the basic idea.

![step1](https://user-images.githubusercontent.com/15192310/27638735-7db6a13a-5c14-11e7-8ee0-5f6d81b1079f.png)
![step2](https://user-images.githubusercontent.com/15192310/27638737-7dd9d6dc-5c14-11e7-8741-b2e5b77dc067.png)
![step3](https://user-images.githubusercontent.com/15192310/27638736-7dd73fc6-5c14-11e7-80c2-74e0e0ca0fe7.png)

Just to be clear: I know this is possible using the API. But it is lengthy and I am not as good a programmer to fiddle with this kind of thing. From practice I can tell this kind of feature is requested frequently and one of the main reasons people refrain from using matplotlib/Python in favour of e.g. Matlab. Thanks!

EDIT: A solution to the problem is shown [here](https://stackoverflow.com/questions/20637113/possible-to-make-labels-appear-when-hovering-over-a-point-in-matplotlib-in-stem). Does anyone feel apt to implement this in the graphical interface?

**Matplotlib version**

  * Operating System: all
  * Matplotlib Version: all (to my knowledge)
  * Python Version: all

**Comment by afvincent** [comment] 2017-06-28 13:47
Thank you for the detailed mock-up!

Just to know, did you have a look at [third-party packages](http://matplotlib.org/mpl_toolkits/index.html) like [mplcursors](https://mplcursors.readthedocs.io/en/stable/) or [mpldatacursor](https://github.com/joferkington/mpldatacursor)? They are not built-in in the GUI but should allow you to achieve something close to what you describe.

**Comment by cweickhmann** [comment] 2017-06-28 14:03
I did not know about these specific two 3rd party packages. I used an implementation similar to the link in the EDIT above [on Stackoverflow](https://stackoverflow.com/questions/20637113/possible-to-make-labels-appear-when-hovering-over-a-point-in-matplotlib-in-stem) but that's nothing you can ask of a standard engineer.
Thanks for the heads up, though! It looks promising and I'll see how this can fix my problem for now.

For the UI feature, still it would be neat if this were added in an upcoming release. ;)

**Comment by afvincent** [comment] 2017-06-28 14:15
I am using none of the two 3rd-party that I mentioned, but I am pretty sure that mplcursors should be quite easy and straightforward to use (@anntzer wrote it based on mpldatacursor with such a purpose in mind). If I understood correctly the basic example, one additional import and one supplementary line should be enough to already get something looking like what you want.

*About integrating such a feature in the GUI, I will let core devs see if they are 👍 or 👎 about this.*

**Comment by cweickhmann** [comment] 2017-06-28 14:31
Actually, at this time, both packages seem to be a bit buggy still. But it is a good 90%-solution to our problem. Thanks a lot!

**Comment by anntzer** [comment] 2017-06-28 16:35
Feel free to open issues on the mplcursors bug tracker if there are any specific bugs you want to get fixed.
As to integration with the GUI, I think this is basically stalled by the toolbar rewrite (MEP22/27).

Closing, as the issue is solved on mpl's side (except for the toolbar rewrite, which is already tracked by many other threads), but feel free to continue posting if you have any questions.

**Closed by anntzer** 2017-06-28 16:35 UTC
Labels: wishlist
