### ISSUE TITLE
deal with upcoming deprecations in CPython

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#25912] opened 2023-05-18 20:30 UTC
```
FAILED lib/matplotlib/tests/test_lines.py::test_set_line_coll_dash_image[svg] - matplotlib.testing.exceptions.ImageComparisonFailure: images not close (RMS 0.412):
FAILED lib/matplotlib/tests/test_backend_svg.py::test_url_tick - DeprecationWarning: datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.now(datetime.UTC).
FAILED lib/matplotlib/tests/test_backend_svg.py::test_svg_default_metadata - DeprecationWarning: datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.now(datetime.UTC).
FAILED lib/matplotlib/tests/test_backend_svg.py::test_svg_clear_default_metadata - DeprecationWarning: datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.now(datetime.UTC).
```

which was changed by https://github.com/python/cpython/pull/103858

We appear to use this a couple of places in Matplotlib https://github.com/search?q=repo%3Amatplotlib%2Fmatplotlib%20utcfromtimestamp&type=code all of which need to be changed to not-deprecated methods of achieving the same thing.

I am labeling this as "good first issue" because there is no API design and there should be no behavior changes (other than not getting warnings) but "medium" difficulty as datetime and timezones are involved.

**Comment by smeet07** [comment] 2023-05-18 22:20
I'll open a pr , do I need to assign this issue or can I directly start working on the pr?

**Comment by QuLogic** [comment] 2023-05-19 00:37
No, we do not assign issues. If there is no open PR linked here, you can just start working on it.

**Comment by ksunden** [comment] 2023-05-19 20:22
Do we have any sense of what is causing the image test failure? seems odd that that would be caused by the deprecation warning, but haven't looked into it at all.

**Comment by tacaswell** [comment] 2023-05-19 20:29
oh, I think I copied one too many lines, only meant to grab the deprecation warning lines here.  I am seeing ~50 failures on my very unstable (default branch of almost everything) environment.

**Closed** 2023-05-23 12:56 UTC
Labels: Difficulty: Medium, Good first issue
