### ISSUE TITLE
histogram density = True 

### ISSUE THREAD

**Issue by felliottkoch** [matplotlib/matplotlib#20810] opened 2021-08-08 22:26 UTC
a normalized distribution should have sum(bins) = 1 or at least be able to have this as an option

**Comment by jklymak** [comment] 2021-08-08 23:02
This is a duplicate of many issues: #14213, #15603, #16147 etc.  Please see the discussion in those.  Thanks!

**Closed by jklymak** 2021-08-08 23:02 UTC
