### ISSUE TITLE
Ticklabel alignment issue with Arial

### ISSUE THREAD

**Issue by asteppke** [matplotlib/matplotlib#4796] opened 2015-07-26 15:20 UTC
While changing the styling of my plots I also tried to change the font used for the tick labels. Upon closer inspection you can notice that the alignment is somehow off for the y tick label "1" in this example:

    import numpy as np
    import matplotlib
    import matplotlib.pyplot as plt

    rcParams = matplotlib.rcParams

    rcParams['font.serif'] = ['Times New Roman']
    rcParams['font.sans-serif'] = ['Arial']
    rcParams['font.family'] = 'sans-serif'

    fig = plt.figure(figsize=(6,3))
    ax = fig.add_subplot(1,1,1)

    t = np.arange(0.0, 1.0, 0.01)
    s = 5*t**2+1+np.sin(2*np.pi*t)

    line, = ax.plot(t, s, color='blue', lw=2)

    ax.tick_params(axis='y', pad=14)        

    plt.plot([0,1],[0,2])
    plt.savefig('test.png', dpi=300, bbox_inches='tight')
    plt.show()

Which results in the following plot:
![test](https://cloud.githubusercontent.com/assets/5851636/8894533/269fa146-33ba-11e5-97bd-6ababca70f47.png)

For some reason the alignment of the tick labels is not consistent, the "1" is clearly closer to the axis lines than the other labels. This does not happen with the default font, so I assume this is due to some interaction between both. Unfortunately Arial or Helvetica is the standard in many publications so I would like to stick to this font.

This happens with matplotlib 1.4.3 on Windows 7 using Python 3.4.1.

**Comment by tacaswell** [comment] 2015-07-26 23:10
It looks like the numbers are correctly right alligned.  Does

```python
[t.set_ha('center') for t in ax.yaxis.get_ticklabels()]
```

fix the alignment?  It will probably also move the tick labels which I don't remember off the top of my head how to move (but I am sure you can).

**Comment by asteppke** [comment] 2015-07-27 10:56
The issue is that the numbers are not correctly right aligned. It might be more obvious in the following picture where I zoomed in and added addtionally digits before the labels:
![image](https://cloud.githubusercontent.com/assets/5851636/8904255/1c505d76-345e-11e5-96fb-40fc97ef0116.png)

It seems that matplotlib is not using the correct bounding box for the character but something like a visual bounding box where the glyph "1" has a right margin of almost zero. 

This is how right alignment should look like in other plotting packages:
![image](https://cloud.githubusercontent.com/assets/5851636/8904338/d4245948-345e-11e5-8dcb-75d64377b497.png)

Centering the labels only helps as a workaround in few cases if not more than one digit ever appears in the labels.

**Comment by EdwinChan** [comment] 2015-07-30 01:12
I'm having a similar issue. The misalignment is extremely noticeable using the Ubuntu font:

![test](https://cloud.githubusercontent.com/assets/906137/8973703/093e4dae-3636-11e5-999a-4401f58e9d0e.png)

It appears the Agg backend suffers from this problem but not the pgf backend. I haven't tried the other backends though…

**Comment by tacaswell** [comment] 2015-07-30 12:13
Does the same happen on master?  @mdboom did some work on this recently.

**Comment by EdwinChan** [comment] 2015-07-30 19:13
I've performed two little tests. The first test

    import matplotlib

    # slightly noticeable
    matplotlib.rcParams['font.family'] = 'DejaVu Sans'
    # slightly noticeable
    matplotlib.rcParams['font.family'] = 'Liberation Serif'
    # extremely noticeable
    matplotlib.rcParams['font.family'] = 'Ubuntu'

    matplotlib.rcParams['font.weight'] = 200
    matplotlib.rcParams['font.size'] = 48
    from matplotlib import pyplot
    pyplot.plot([0, 5], [0, 5])
    for i in range(3):
      pyplot.annotate(i+1, (0, 0), (1, i+2), 'data', 'data', ha='right')
    pyplot.annotate(matplotlib.__version__, (0, 0), (2, 1),
      'data', 'data', ha='left')
    pyplot.savefig('test.png')

produces

![test](https://cloud.githubusercontent.com/assets/906137/8992593/6eb72b82-36cd-11e5-9787-2954c9f3aab9.png)

The second test

    import matplotlib

    # slightly noticeable
    matplotlib.rcParams['font.family'] = 'DejaVu Sans'
    # slightly noticeable
    matplotlib.rcParams['font.family'] = 'Liberation Serif'
    # extremely noticeable
    matplotlib.rcParams['font.family'] = 'Ubuntu'

    matplotlib.rcParams['font.weight'] = 200
    matplotlib.rcParams['font.size'] = 48
    from matplotlib import pyplot
    for i in range(10):
      pyplot.plot([0, 5], [0, 5])
      pyplot.annotate('{:.2f}'.format(i/100), (0, 0), (4, 1),
        'data', 'data', ha='right')
      pyplot.savefig('test{}.png'.format(i))
      pyplot.clf()

produces a chain of images. When the images are flipped through with your favorite image viewer, the 'timer' in the lower right doesn't jitter around like it did in matplotlib 1.4.3.

**Comment by mdboom** [comment] 2015-07-30 20:02
So, it appears this is fixed in git, then?

**Comment by EdwinChan** [comment] 2015-07-30 21:11
It does seem so.

**Comment by tacaswell** [comment] 2015-07-30 21:23
Great, closing as fixed on master.  

@asteppke Please ping to have this re-opened if you can reproduce this on the current master branch.

**Closed by tacaswell** 2015-07-30 21:23 UTC
