### ISSUE TITLE
[Bug]: Logarithmic scaling of inset_axes overrides ticklabels

### ISSUE THREAD

**Issue by adamcpovey** [matplotlib/matplotlib#24569] opened 2022-11-30 11:17 UTC
### Bug summary

If `set_xscale("log")` is set for an `inset_axes` instance, the default tick formatter is applied irrespective of any calls to `set_xticklabels()` (before or after the scaling). The same is true for the y-axis.

### Code for reproduction

```python
fig, axes = plt.subplots(1, 2)
for ax_main in axes:
    ax_in = ax_main.inset_axes([0.05, 0.5, 0.25, 0.5])
    ax_main.plot((1,2))
    ax_in.plot((1,2))
    ax_in.set_xticklabels(())
    ax_in.set_yticklabels(())

ax_in.set_xscale("log")

plt.show()
```

### Actual outcome

![Figure_1](https://user-images.githubusercontent.com/24915701/204782410-7088f3dd-1a2e-4181-b17f-e40073becd6d.png)

### Expected outcome

The left and right axes of the above should have identical tick labels (i.e. none).

### Operating system

Ubuntu

### Matplotlib Version

3.4.3

### Matplotlib Backend

Qt5Agg, module://matplotlib_inline.backend_inline

### Python version

Python 3.9.9

### Jupyter version

6.4.5

### Installation

conda

**Comment by anntzer** [comment] 2022-11-30 11:39
This also occurs with plain axes; I am almost certain this is a duplicate of #18572 so I'll close this as such.  Feel free to comment if you believe that this is significantly different.

**Closed by anntzer** 2022-11-30 11:39 UTC

**Comment by adamcpovey** [comment] 2022-11-30 11:53
My original problem happened when I set `xscale` on axis creation, then set `xticklabels`. In attempting to make a new minimal example, it seems the issue is actually with `seaborn`. Apologies for the waste of your time.

**Comment by adamcpovey** [comment] 2022-11-30 12:17
Wait, no, I eventually got an example of what I did,
```
fig, axes = plt.subplots(1, 2)
for ax_main in axes:
    ax_in = ax_main.inset_axes([0.02, 0.38, 0.2, 0.6],
                               xscale="log" if ax_main is axes[1] else None)
    ax_main.plot((1, 10, 100))
    ax_in.plot((1, 10, 100))
    ax_in.set_xticklabels(())
    ax_in.set_yticklabels(())

plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/24915701/204793919-ce3bb454-cc4f-46a2-a3b2-1d44e8883006.png)

If that's still the issue you reference, may I ask how one is supposed to remove tick labels from the inset_axes?

**Comment by adamcpovey** [comment] 2022-11-30 12:20
Further, the yscale works,
```
fig, axes = plt.subplots(1, 2)
for ax_main in axes:
    ax_in = ax_main.inset_axes([0.02, 0.38, 0.2, 0.6],
                               yscale="log" if ax_main is axes[1] else None)
    ax_main.plot((1, 10, 100))
    ax_in.plot((1, 10, 100))
    ax_in.set_xticklabels(())
    ax_in.set_yticklabels(())

plt.show()
```
![Figure_2](https://user-images.githubusercontent.com/24915701/204794792-013d22b3-59cd-47b6-a324-b3ced3cce5d9.png)

**Comment by adamcpovey** [comment] 2022-11-30 12:32
No, wait, I eventually made a new environment to clean everything up and managed this example of there being different behaviour for `xscale` and `yscale`,
```
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 3)
for ax_main in axes:
    ax_in = ax_main.inset_axes([0.02, 0.38, 0.2, 0.6],
                               xscale="log" if ax_main is axes[1] else None,
                               yscale="log" if ax_main is axes[2] else None)
    ax_main.plot((1, 10, 100))
    ax_in.plot((1, 10, 100))
    ax_in.set_xticklabels(())
    ax_in.set_yticklabels(())

plt.show()
```
![Figure_2](https://user-images.githubusercontent.com/24915701/204797000-2eb82be8-773d-4840-a8c4-414fae4f4d49.png)

**Comment by anntzer** [comment] 2022-11-30 12:52
What you see in the middle case are minor log-scale ticks (as your x-axis effectively spans [1, 2], so less than one decade).

**Comment by adamcpovey** [comment] 2022-11-30 13:04
Oh %*&$ I thought I'd turned those off globally but, yeah, those are minor ticks.

Thanks for your patience :)
