### ISSUE TITLE
Cannot make Latex plots when Pandas dataframe has underscore in variable name

### ISSUE THREAD

**Issue by khof312** [matplotlib/matplotlib#17774] opened 2020-06-27 00:04 UTC
### Bug report

**Bug summary**

When plotting a Pandas data frame with variables that have underscores in the name, I cannot use the `usetex` option without getting an error. Currently, [the only solution I can find](https://stackoverflow.com/questions/49136882/make-tex-compatible-names-for-pandas-plotting-function) recommends that I rename the columns in my dataframe to escape special characters, but it seems like there must be a better approach.

**Code for reproduction**
```python
import pandas as pd
import matplotlib
matplotlib.rcParams['text.usetex'] = True

df = pd.DataFrame([0,1,2], columns = ["test_column"])
df.plot()
```

**Actual outcome**

```
<matplotlib.axes._subplots.AxesSubplot at 0x22a107c4630>
---------------------------------------------------------------------------
...

RuntimeError: latex was not able to process the following string:
b'test_column'

...

! Missing $ inserted.
<inserted text> 
                $
l.14 ...size{10.000000}{12.500000}{\sffamily test_
                                                  column}
No pages of output.

...
```

**Expected outcome**
I think it would be good to create an option to easily prevent Latex from interpreting special characters when they appear in data frame column names.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.8
  * Jupyter version: Jupyterlab 2.1.4
  * Other libraries: Pandas 1.0.1
  * Installed with Anaconda

**Comment by jklymak** [comment] 2020-06-27 02:16
This seems more of a pandas issue to me because they are the ones assigning the column name to the label.  If you don't want this to happen, just do `ax.plot(df, label='test\_column'), ax.legend()`.  

Note we can't escape *all* instances of `_`, because we need them for math '$x_n$'.  I'll leave this open, because I guess its possible we might *always* want to escape `_` when its not enclosed in math delimiters.  But that seems like a lot of finicky parsing.  

I guess similarly this will be hard for pandas to fix because they won't be able to escape underscore without knowing if usetex is True or not.  Obviously you don't want the escape if usetex is False.

**Comment by khof312** [comment] 2020-06-28 19:41
Thanks for the comments. I see why this might not be a priority, but I thought it's worth flagging for the long term since it looks like others on SO are having problems as well. Just a few further notes:

Relabeling is possible but it can get a bit messy. For example, if plotting many columns then you are running list comprehensions over the variable names to generate the labels. In cases where the variable labels are applied to the axes of the plot (e.g. `scatter`), you need to rename the axes too.

I agree that you don't want to escape all `_`, but if as you say it is possible to escape any that are not enclosed in math characters, or simply to apply a switch that escapes all (if making latex plots that don't involve underscores), that would be helpful. Even something like `parse_colnames_literally = True`.

In any case, thanks for the effort to think this through!

**Comment by tacaswell** [comment] 2020-07-01 22:43
I think this as is related to `df.plot()` is better reported to pandas than to Matplotilb as we don't have any control of what `df.plot()` does internally. 

-----

You can however reproduce the same issue without using pandas via

```python
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['text.usetex'] = True
df = {'a_b': range(5)[::-1], 'c': range(5)}
fig, ax = plt.subplots()
ax.plot('c', 'a_b', data=df)
ax.legend()
plt.show()
```

The correct place to put the latex escaping code is in https://github.com/matplotlib/matplotlib/blob/c2e09e8a7be0db7226226412b86f71d28795c854/lib/matplotlib/__init__.py#L1295-L1301 which is used at https://github.com/matplotlib/matplotlib/blob/c2e09e8a7be0db7226226412b86f71d28795c854/lib/matplotlib/__init__.py#L1453-L1455 to infer a label when the incoming data gives it to us.

I have not given this a milestone, but it should go in the first minor release once it is implemented,

I labeled it as good first issue because all of the changes are relatively limited to one function so should not creep out into other parts of the code.

I labeled this as medium difficulty as part of the task is to write a reliable latex escaping function.  We may be able to re-use our existing mathtext parser to determine if a a given string is valid.  However it is not obvious to me how write the function that makes `'a_b $c_d$'` a valid tex string.  There is some API design here, but I think it will be adding an rcParam to determine if we apply the above normalizer or not

**Comment by timhoffm** [comment] 2020-07-02 11:05
> Relabeling is possible but it can get a bit messy.

In the simplest form this is just
~~~
df.rename(lambda s: s.replace('_', '\\_'), axis='columns')
~~~
You could also write a better mapping function an reuse that.

-----

General question: Are we sure we can do smart escaping in a consistent way for all cases? If not, I suggest not to try. Instead, we could provide a hook to supply a custom mapping function, possibly via `rcParams['label_mapper']` (default: None).

**Comment by anntzer** [comment] 2020-07-02 11:35
I would guess the *much* easier solution would be to use https://ctan.org/pkg/underscore (see also https://texfaq.org/FAQ-underscore).  Users can add it to text.latex.preamble, or we can add it to the default preamble if we want.

**Comment by tacaswell** [comment] 2020-07-02 22:45
Given that we already include a more-than-mimimal latex (to get cmsuper), do we already (practically) require this be available?

**Comment by anntzer** [comment] 2020-07-02 23:22
fwiw this appears to be in texlive-latex-recommended.

**Comment by billbrod** [comment] 2020-08-25 21:16
Wanted to add, as a user: adding `r"\usepackage{underscore}"` to my `text.latex.preamble` works very well as a drop-in solution; it also allows easy switching back and forth between using tex and not, which the other solutions I found on the internet (e.g., renaming all columns to replace `_` with `\_` do not).

**Comment by ikyman** [comment] 2021-01-27 21:48
So Seeing as this is still open, and that this is marked as a "Good First Issue", Could I work on this?

**Comment by timhoffm** [comment] 2021-01-31 14:30
There is a rough proposal at what to do at https://github.com/matplotlib/matplotlib/pull/18357#issuecomment-683410662.

**Comment by ikyman** [comment] 2021-02-01 20:29
Ok, and what parts of the repo do I fork?

**Comment by timhoffm** [comment] 2021-02-01 22:28
You fork https://github.com/matplotlib/matplotlib and make a pull request against the `master` branch.

**Closed** 2021-07-30 09:27 UTC
Labels: Difficulty: Medium, Good first issue, third-party integration, topic: text/usetex
