### ISSUE TITLE
[Bug]: Plots do not appear when debugging in `matplotlib >= 3.9`.

### ISSUE THREAD

**Issue by cbmorrell** [matplotlib/matplotlib#28979] opened 2024-10-15 18:38 UTC
### Bug summary

When running in debug mode using `matplotlib >= 3.9`, plots do not appear when called in the source code or in a debug console. Plots appear properly when executing source code outside of the debugger, so this may be an issue with interactive mode. I ran into these issues on both MacOS and Windows.

### Code for reproduction

```Python
import matplotlib.pyplot as plt

plt.figure()
plt.plot(range(10))
plt.show()
```

### Actual outcome

Plots are displayed properly when running the source code outside of the debugger, but plots are not shown when debugging.

### Expected outcome

Figures created in source code or the debug console are shown once a breakpoint is hit. These figures should be able to be modified using commands in the debug console.

### Additional information

From my testing, plots are displayed properly in version 3.8 but not version 3.9. I have tried this in `conda` and `venv` and found that the only solution was downgrading to version 3.8.

### Operating system

Windows, OS/X

### Matplotlib Version

3.9.0

### Matplotlib Backend

maxosx (OS/X), tkagg (Windows)

### Python version

3.10.15

### Installation

pip

**Comment by timhoffm** [comment] 2024-10-15 20:21
Since you say "debugger mode/debugger console", are you possibly using PyCharm?

This is likely https://github.com/matplotlib/matplotlib/issues/28581#issuecomment-2262579718.

**Comment by cbmorrell** [comment] 2024-10-16 13:29
> Since you say "debugger mode/debugger console", are you possibly using PyCharm?
> 
> This is likely [#28581 (comment)](https://github.com/matplotlib/matplotlib/issues/28581#issuecomment-2262579718).

@timhoffm In my case I'm using VS Code, but it seems like the same issue. Plotting in IPython from the command line works fine, but not when debugging, so I'm guessing it's a VS Code issue like the comment you linked said. Sorry for the duplicate and thanks for the help!

**Comment by ianthomas23** [comment] 2024-10-17 09:52
Closing as a duplicate of #28581.

**Closed by ianthomas23** 2024-10-17 09:52 UTC
Labels: status: duplicate

**Comment by tacaswell** [comment] 2025-02-07 14:09
The issue is that in the debugger nothing is spinning the GUI event loop. See https://matplotlib.org/stable/users/explain/figure/interactive_guide.html#command-prompt-integration for a longer explanation.

**Comment by landoskape** [comment] 2025-02-07 14:22
Thanks for pointing me there. It seems like this is a fundamental problem from that description more than just a versioning bug? So I'm confused because this works fine in previous versions, is it more like the "illusion" of simultaneity in that case? 

I guess I was just wondering what the maintainers meant when they said "nothing we can do here" -- does that mean there _is_ something someone can do elsewhere that I as a user can bug those someones about? If so I'd be happy to bug :)

**Comment by tacaswell** [comment] 2025-02-07 18:28
The input hook needs to be integrated into the loop that is running the repl so the integration needs to be done by who ever owns the repl.

**Comment by jklymak** [comment] 2025-02-07 18:52
@ianthomas23, @tacaswell do we understand what changed that caused this?   #28581 seems to indicate that it is the backend normalization...  Do we have guidance for vscode on exactly what they should fix?

**Comment by ianthomas23** [comment] 2025-02-07 19:37
I think (and I may well be wrong) that it is the change in the names of some of the backends that occurred as part of the backend normalisation that have caused this, most likely the changes in capitalisation rather than actual name changes. Hence hard-coded backend name checks in vscode/pycharm/whatever now take different code paths to not display correctly or not start the required event loops. The general guidance is that downstream libraries need to be aware of changes in this repo and adapt to them. Specific guidance would be to check what backend names are being passed to Matplotlib and what they receive back via `matplotlib.get_backend()` and deal with whatever has changed that affects them.
