### ISSUE TITLE
Polygons from contour patches don't capture vertices

### ISSUE THREAD

**Issue by ahmadia** [matplotlib/matplotlib#3020] opened 2014-04-28 17:23 UTC
Following the steps for generating polygons from [StackOverflow example](https://stackoverflow.com/questions/21150752/matplotlib-contour-plot-geojson-output), I am unable to get simplified contour paths from capturing polygon vertices.

Here's a simple code example and image:

```
import numpy as np
import matplotlib.pyplot as plt

x, y = np.mgrid[-77.5:-77:0.001,34.25:34.75:0.001]
z = 100*(x + y)

cs = plt.contourf(x,y,z,3, hold=False)
path = cs.collections[1].get_paths()[0]
poly_simple = path.to_polygons()[0]
path.should_simplify = False
poly_complex = path.to_polygons()[0]
plt.clf()
plt.plot(poly_complex[:,0], poly_complex[:,1], 'rx', hold=True, markersize=1, mew=1)
plt.plot(poly_simple[:,0], poly_simple[:,1], 'yx', hold=True, markersize=8, mew=8)
```

![image](https://cloud.githubusercontent.com/assets/512293/2820398/8ef65108-cef9-11e3-9fae-af75cd505ebe.png)

Note the missing vertex in the lower-mid corner of the polygon.  Is this intended behavior of the path simplification algorithm?  If so, does matplotlib possess a fast method of returning the simplified polygon being returned from a contour plot without losing the vertex information?

**Comment by anntzer** [comment] 2018-11-20 11:40
You can set path.simplification_threshold to something like 1e-3 (for the specific example above, one also needs to set `path.should_simplify` to True before the first call to `to_polygons()` as it now defaults to False).  (Alternatively one can transform to pixel coordinates, simplify, and transform back, as noted in the thread.)

Closing as the issue is old and I think things are behaving as expected (i.e. the simplification_threshold is in the same units as the path coordinates itself).

**Closed** 2018-11-20 11:40 UTC
Labels: Path handling
