### ISSUE TITLE
[Bug]: Saving as .eps and rc

### ISSUE THREAD

**Issue by pzivich** [matplotlib/matplotlib#24477] opened 2022-11-16 13:12 UTC
### Bug summary

When saving the output as an .eps file, the saved file removes the right y-axis and parts of the x-axes. This behavior occurs only when used with `rc` options.

### Code for reproduction

```python
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import rc

rc('text', usetex=True)  # removing this line results in expected output

# Generic plot
plt.plot([1, 2], [2, 1])
plt.tight_layout()   # removing line doesn't change things
plt.savefig("pub_figures/test.eps", 
            format='eps')
plt.show()
```

### Actual outcome

Outcome when outputting as .eps with `rc('text', usetex=True)` (this is a screenshot of the .eps file, since GitHub doesn't support .eps files being uploaded). Changing the backend to PS, did not solve the issue.

![image](https://user-images.githubusercontent.com/32672909/202188526-f2781749-59ab-494b-9922-de061d1d0c64.png)

### Expected outcome

Saving as .png works as expected

![expected](https://user-images.githubusercontent.com/32672909/202188956-fd378ed7-044c-441a-8055-2b8e7d7c98f9.png)

### Additional information

This seems to be related to rc. Once this line is removed in the minimal examples above, the .eps file displays as expected. 

### Operating system

Ubuntu 20.04.5

### Matplotlib Version

3.6.2

### Matplotlib Backend

TkAgg

### Python version

3.9.5

### Installation

pip

**Comment by oscargus** [comment] 2022-11-16 13:21
I think this is a duplicate of #23776 which contains a bit more debugging info, so closing this. Feel free to reopen if you disagree.

**Closed by oscargus** 2022-11-16 13:21 UTC
Labels: backend: ps, status: duplicate
