### ISSUE TITLE
colormap support for 3d quiver

### ISSUE THREAD

**Issue by twmr** [matplotlib/matplotlib#3382] opened 2014-08-18 10:06 UTC
It would be nice to have support for a colormap kwarg (like the `C` kwarg in the 2d implementation of `quiver` http://matplotlib.org/api/axes_api.html?highlight=quiver#matplotlib.axes.Axes.quiver) in the 3d version of quiver.

**Comment by delooper** [comment] 2016-03-17 21:02
I'm reading in the linecollection API for matplotlib 1.5.1 and it looks like you should be able to assign colors arrow-by-arrow but I haven't determined what format the library wants the call to be in.   The library makes it sound like it needs a nxmxkx3 or a nxmxkx4 array depending on if you are using RGB or RGBA colors.  But I'm not having any luck with it.

**Comment by WeatherGod** [comment] 2016-03-17 21:22
Most likely, the problem is that the colors might be getting re-assigned by
other parts of mplot3d. Color-handling has been extremely tricky in mplot3d.

**Comment by delooper** [comment] 2016-03-17 21:24
Do you know if one can change the length or width of a 3d quiver plot, element-by-element?   I haven't had luck with that, either.

**Comment by sytrus-in-github** [comment] 2017-04-14 14:31
@delooper I have just opend [another issue](https://github.com/matplotlib/matplotlib/issues/8484) on specifying colors for each arrow in 3D quiver plot (since this one is more about colormap) in which I have given a work around for my case: 

- reshape your array of shape (n,m,k,3) to (n*m*k, 3) (4 for RGBA I suppose)
- filter out color values corresponding to vectors of length 0 because they won't be drawn ...
- specify `colors = array + repeatEachElement(array, 2)` since first all "-" part of "->" will be drawn then the ">" part will be drawn 

Hope this helps.

**Comment by scottshambaugh** [comment] 2024-05-16 17:07
This is covered by the `colors` kwarg that is passed to `Line3DCollection`, and was fixed in https://github.com/matplotlib/matplotlib/pull/27754. Feel free to reopen if I'm wrong there.

**Closed by scottshambaugh** 2024-05-16 17:07 UTC
Labels: New feature, topic: mplot3d, keep
