### ISSUE TITLE
bar plot: in 2.0.0 bars not as given in the description, ie. first arg is not "left" but "center"

### ISSUE THREAD

**Issue by ritman** [matplotlib/matplotlib#7954] opened 2017-01-26 14:31 UTC
### Bug report

**Bug summary**

Using ``bar``, the first input argument is not used for the left edge of the bar, but rather the center, as if the kwarg ``align='center'`` was used. However, the desired behavior is obtained in both cases when using ``align = 'center'`` and ``align = 'edge'``. Just when ``align`` is not specified, it should be 'edge' aligned which it is not.

**Code for reproduction**
```python
import matplotlib.pyplot as plt
plt.bar([1], [1])
plt.show()
```

**Actual outcome**
![figure_1](https://cloud.githubusercontent.com/assets/4058407/22334729/17af86b4-e3dc-11e6-83d0-f5e3392625ac.png)
**Expected outcome**
![figure_2](https://cloud.githubusercontent.com/assets/4058407/22334747/2ce9afc8-e3dc-11e6-8f69-0c0150522359.png)

In matplotlib 1.5.3 I got the expected behavior.

**Matplotlib version**
matplotlib 2.0.0
python 3.6.0
both installed from the Arch Linux repository.

**Comment by phobson** [comment] 2017-01-26 15:47
My hunch is that this a documentation/naming convention oversight in the wake of the changes to the defaults.

IIRC, it was a bad user experience to align in the bars along the left edge (the previous default). So at some point, we ad the `align` kwarg so that the `left` parameter could actually specify the center of the bars. At that point, we should have renamed `left` to `x`, but probably could not for backwards compatibility reasons.

Then with v2 we changed the default value of `align` to "center", but still did not update the symbol `left` to `x`. 

I'm not sure what the best path forward is.

**Comment by tacaswell** [comment] 2017-01-26 16:21
This is definitely intended behavior.  The docstring on `left` should include a warning / comment on this.

Unfortunately we can not re-name the first positional argument without breaking API, I think that is a wart we are stuck with.

**Comment by ritman** [comment] 2017-01-27 08:17
I agree that left align was a poor user experience and I welcome the change to center being the default. I was just surprised to see the change in one of my scripts after updating to 2.0.0, in particular since the description did not reflect the obtained behavior.

I would suggest, though, to also make the same change to ``step``, which, in 1.5.3, could be used somewhat interchangeably to ``bar``, if none of the alignment options (``align`` for ``bar`` and ``where`` for ``step``) keywords were used. This is not the case anymore.

**Comment by jason-s** [comment] 2017-03-29 23:27
>IIRC, it was a bad user experience to align in the bars along the left edge

Except that aligning bars along the center when `log=True` is a bit of a pain to deal with; you need to take the geometric mean of the edges.

**Comment by pierre-haessig** [comment] 2017-04-08 06:05
I also got hit by the doctring inconsistency (not by the change of default value, because I rarely use `bar`).

@tacaswell is it really impossible to rename the first argument from `left` to `x` and advertise this as delayed change part of the 2.0 release. Of course a solution is to add a warning further down in the docstring. It would  be a good bandage, but it wouldn't fix for this terrible API inconsistency.

**Comment by pierre-haessig** [comment] 2017-04-08 07:56
also as a different, but related, issue on the documentation of `bar` function: there is a `data` keyword argument in the signature which, I believe, is not documented.

**Comment by WeatherGod** [comment] 2017-04-10 20:27
The v2.0 change was not an API change release. It was a style change
release. All code as written before still works now. What *might* be
possible is to change that argument name, and then add support for a "left"
kwarg by checking **kwargs for that key. If it is there, we can emit a
deprecation message, and then assign its value over to the new renamed
argument. Presumedly, this situation can only happen if supplying all the
arguments via **kwargs. The only hiccup with this idea is that the new
positional arguments wouldn't be filled by this approach, so the function
call would fail...

perhaps my idea could inspire someone else for a path for deprecating these
badly named arguments?

**Comment by skjaeve** [comment] 2017-07-17 20:55
@tacaswell 
> Unfortunately we can not re-name the first positional argument without breaking API, I think that is a wart we are stuck with.

Isn't the API already broken if the meaning of a positional argument was changed?

**Comment by WeatherGod** [comment] 2017-07-17 21:03
No, the meaning didn't change in v2.0, the default value for `align`
changed. The meaning changed when the `align` feature was added. The
documentation was always wrong since then, and it became more apparent when
the defaults changed in v2.0.

**Comment by tacaswell** [comment] 2017-07-18 20:36
it is 'broken' in the sense that it is confusing not 'broken' in the sense that code will raise exceptions.

**Comment by anntzer** [comment] 2017-07-18 22:01
Still advertising https://github.com/matplotlib/matplotlib/issues/7966 as a way to fix the signature...

**Comment by tacaswell** [comment] 2017-07-25 20:04
The consensus on the phone call today is:
 
 - change to `*args, **kwargs`
 - use `Signature.bind` to try the current signature and `(x, height, width=0.8, bottom=None, **kwargs)` and `(left, hegiht, width=0.8, bottom=None, **kwargs)`
 - document the first version in the docstring (and expose out if possible).

**Comment by anntzer** [comment] 2017-07-25 21:22
Actually, upon further thought, we don't need to create signature objects; we can just do something like https://github.com/matplotlib/matplotlib/pull/6404#issuecomment-316253405.  The advantage of using signature objects when using the #7966 decorator approach is that we can simulate positional-only args or even on Py2 keyword-only args, but if we're not using the decorator approach we may as well let the interpreter do the argument binding for us.  So something like

```
def bar(*args, **kwargs):
    matchers = [
        (lambda x, height, width, bottom, **kwargs:
         (x, height, width, bottom, kwargs)),
        (lambda left, height, width, bottom, **kwargs:
         (x, height, width, bottom, kwargs))]
    for matcher in matchers:
        try:
            x, height, width, bottom, kwargs = matcher(*args, **kwargs)
        except TypeError:
            # This can only come from a no-match as there is no other logic in
            # the matchers.
            continue
        else:
            break
    else:
        raise TypeError("...")  # We can even re-use the TypeError from the first match.
    ...
```

**Closed** 2017-08-31 02:14 UTC
Labels: default changes, Documentation, Release critical
