### ISSUE TITLE
Matplotlib save to pdf not showing hatch marks in bar plot — potential bug?

### ISSUE THREAD

**Issue by vkidamisc** [matplotlib/matplotlib#16052] opened 2019-12-30 22:50 UTC
### Bug report

I am using matplotlib version 3.1.1 on an ubuntu 18.04 machine and have tried this code in both python 3.6.8 and 3.7.4 on 2 different boxes.

The problem is that when there are more than 10 items the color repeats itself and I made a quick change to make hatch marks to differentiate. While this works well in display, the hatches do not show up when I savefig("\*.pdf"). savefig("\*.png") seems to work fine as seen in the figures below.

I have searched for this issue in multiple places but can't seem to find a solution that works. I have also tried PdfPages.

Simple code and output are attached below. I appreciate any suggestions.

**Code for reproduction**

```python
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd

matplotlib.__version__  #3.1.1
df=pd.DataFrame({'A':[0.1]*12, 'B':[0.1]*12}).T
tit='title'

ax=df.plot.bar(figsize=(11,8.5),stacked=True,title=tit)
nrows=len(df)
bars = ax.patches
hatches=['','-', '+', 'x','/','//','O','o','\\','\\\\']*nrows*10 #times rows*colors
#
hatches.sort()
hatches=hatches[0:len(bars)]
i=0 
for bar in bars:# goes down a column with same color,  then next with diff color and so on.  
    bar.set_hatch(hatches[i])
    #bar.text('1')
    #print(bar)
    i+=1    
ax.legend(#loc='lower center', loc='upper center',bbox_to_anchor=(0.5, -.05,0,0),fancybox=True, shadow=True, ncol=5,fontsize=5.5)

#plt.savefig('barhatch.png')   

plt.savefig('barhatch.pdf')   
```

This is the output I get.  Note that the hatch marks are missing.  This happens when writing pdf. 

![image](https://user-images.githubusercontent.com/59376516/71603630-c7915500-2b2b-11ea-8862-940b48f89a35.png)

This is the output when I save as png, which correctly shows the hatch marks. 

![image](https://user-images.githubusercontent.com/59376516/71603684-08896980-2b2c-11ea-9af3-64266cd59b0e.png)

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.8 & 3.7.3
  * Jupyter version (if applicable):
  * Other libraries: 

Installed using pip3

**Comment by anntzer** [comment] 2019-12-31 22:18
I can confirm; this only happens with pdf and not ps or svg, and not with mplcairo either.

**Comment by timhoffm** [comment] 2020-01-01 11:06
Possibly duplicate of #12367.

**Comment by anntzer** [comment] 2020-01-01 11:08
I could repro some of #12367 with mplcairo, but none of this, so I'm not 100% sure it's a dupe.

**Comment by georgedeath** [comment] 2022-01-23 11:06
As per https://stackoverflow.com/a/59389823/2161490, using alpha=0.99 is a viable workaround.

**Comment by Impaler343** [comment] 2024-04-16 11:21
I cannot reproduce this on the current master, has this already been solved?

**Comment by tacaswell** [comment] 2024-04-16 16:48
I agree this one looks solved.  Might be worth back-tracking to figure out when but going to milestone to 3.8

```python
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import itertools

matplotlib.__version__  #3.1.1
df=pd.DataFrame({'A':[0.1]*12, 'B':[0.1]*12}).T
tit='title'

ax=df.plot.bar(figsize=(11,8.5),stacked=True,title=tit)
nrows=len(df)
bars = ax.patches
hatches=['','-', '+', 'x','/','//','O','o','\\','\\\\']
#
hatches.sort()
hatches=hatches[0:len(bars)]
i=0
for hatch, bar in zip(itertools.cycle(hatches), bars):# goes down a column with same color,  then next with diff color and so on.
    bar.set_hatch(hatch)

ax.legend(loc='upper center',bbox_to_anchor=(0.5, -.05,0,0),fancybox=True, shadow=True, ncol=5,fontsize=5.5)

plt.savefig('/tmp/barhatch.pdf')
```

is a slightly modified test case.

**Closed by tacaswell** 2024-04-16 16:48 UTC
Labels: status: confirmed bug, backend: pdf, keep
