### ISSUE TITLE
English title does not go well with gcf().tight_layout(), which yields bad image direction

### ISSUE THREAD

**Issue by retsyo** [matplotlib/matplotlib#8202] opened 2017-03-06 04:42 UTC
I am using  Python 3.4.4 |Anaconda 2.3.0 (64-bit)  on win64 bits, with latest  matplotlib  and  pyqt  updated by  conda install xx 
for the following code, if I use unicode title in the for-loop, the images are shown with their corretced direction, i.e., the head is toward up like which is in original image. However, if I use English title, the images are upside-down: the people's head is toward earth

This can be observed for both  TkAgg  and  Qt5Agg 

```python
#coding=utf-8
import matplotlib
#~ matplotlib.rcParams['backend'] = 'TkAgg'
matplotlib.rcParams['backend'] = 'Qt5Agg'

from pylab import *
import PIL.Image as Image

im=Image.open('Mario cosplay.jpg').convert('L')

orgsize=im.size
newsize=[int(i/4) for i in orgsize]

subplot(2,3,1)
imshow(im, cmap='gray', vmin=0, vmax=255)
title('original pic', fontsize=20);

filters=[Image.NEAREST, Image.BILINEAR, Image.BICUBIC, Image.ANTIALIAS]
filtersName=['NEAREST', 'BILINEAR', 'BICUBIC', 'ANTIALIAS']
for k in range(len(filters)):
    subplot(2,3,k+2)
    im1=im.resize(newsize, filters[k])
    imshow(im1, cmap='gray', vmin=0, vmax=255)
    title('原图的1/%i，插值法：%s' %  (4, filtersName[k]), fontsize=20)       # head up
    title('size: 1/%i，interpolation: %s' %  (4, filtersName[k]), fontsize=20)    # head down

gcf().tight_layout()

show()
```
![chinese_headup](https://cloud.githubusercontent.com/assets/7960913/23596979/43168210-026a-11e7-8228-dd43c858b0d5.png)
![english_headdown](https://cloud.githubusercontent.com/assets/7960913/23596980/4440d8de-026a-11e7-9235-e4419e206e22.png)

**Comment by QuLogic** [comment] 2017-03-06 05:18
I think this is the same issue as #8062. @NelleV @anntzer

**Comment by anntzer** [comment] 2017-03-06 05:33
I would guess so, but @retsyo needs to provide a reproducible example (I don't have his sample image...).

**Comment by retsyo** [comment] 2017-03-06 05:57
@anntzer
any image can reproduce this

**Comment by anntzer** [comment] 2017-03-06 06:07
In general, it is preferable to provide a self contained example, so that we can easily reproduce the issue.  You may also check whether #8203 "solves" the issue (well, there's still not enough space and nothing we can do about it).

**Comment by QuLogic** [comment] 2017-08-10 20:23
I'm going to close this as a duplicate of #8062.

**Closed by QuLogic** 2017-08-10 20:23 UTC
