### ISSUE TITLE
v. 3.3.0:  horizontal colorbar broken

### ISSUE THREAD

**Issue by chris-hld** [matplotlib/matplotlib#18033] opened 2020-07-23 14:54 UTC
### Bug report

**Bug summary**

Horizontal colorbar location changed to something broken in latest 3.3.0

**Code for reproduction**

Here is a minimal example in the exact way I am using it. Is there any quick fix/workaround? I really appreciate the improved 3D axis handling in v. 3.3!

```python
import numpy as np
import matplotlib.pyplot as plt

import matplotlib as mpl
ver = mpl.__version__

num_plots = 4
fig = plt.figure(figsize=plt.figaspect(1 / num_plots),
                 constrained_layout=True)

ax_l = []

for idx in range(num_plots):
    ax = fig.add_subplot(1, num_plots, idx+1, projection='3d')
    p_tri = ax.plot_trisurf(np.random.randn(5), np.random.randn(5), np.random.randn(5),
                            cmap=plt.cm.coolwarm)
    ax_l.append(ax)

cbar = plt.colorbar(p_tri, ax=ax_l, orientation='horizontal')


plt.suptitle(ver)

plt.savefig(str(ver)+'.jpg')
plt.show()
```

**Actual outcome**

from v. 3.2.0
![3 2 0](https://user-images.githubusercontent.com/10830393/88301127-ee53ea80-cd0c-11ea-85ea-84e2cce8faba.jpg)

from v. 3.3.0
![3 3 0](https://user-images.githubusercontent.com/10830393/88301135-f0b64480-cd0c-11ea-82cf-834cc61bf37b.jpg)

**Comment by chris-hld** [comment] 2020-07-23 15:10
Possibly related to `constrained_layout`.

Output with `constrained_layout=False`
![3 3 0](https://user-images.githubusercontent.com/10830393/88303450-b9956280-cd0f-11ea-89e7-8a88264b61f7.jpg)

**Comment by jklymak** [comment] 2020-07-23 15:41
This is not a bug with regular axes, so its some sort of mplot3d issue.  

Its possible `constrained_layout` works w/ mplot3d sometimes, but its not tested with mplot3d.   But I can't bisect the error sensibly, partially because the toolkits don't install in conda/pip the same way as the core library.  So hopefully someone w/ a working mplot3d debug setup can at least bisect so we can see what change caused this.

**Comment by jklymak** [comment] 2020-07-23 16:02
Note this would be closed by #17494

**Comment by tacaswell** [comment] 2020-07-23 17:04
To check, the problematic change is the colorbar floating to the top?

Assuming we don't want to backport the CL re-write for 3.3.x is there another workaround other than turning CL off ?

**Comment by jklymak** [comment] 2020-07-23 17:08
I don't know.  I can't bisect mplot3d stuff to figure out what is going on.

**Comment by jklymak** [comment] 2020-07-23 17:37
This bisects to 4479a0ffe1b81ac8b1  https://github.com/matplotlib/matplotlib/pull/16472

**Comment by jklymak** [comment] 2020-07-23 18:08
ok fixed #18038 as far as I can tell.

**Closed** 2020-07-23 19:46 UTC
Labels: geometry manager, mplot3d

**Comment by jklymak** [comment] 2020-07-23 19:58
@chris-hld unfortunately I cannot think of a good workaround short of installing the 3.3.1 branch or downgrading to 3.2 until 3.3.1 is released.

**Comment by chris-hld** [comment] 2020-07-24 10:55
Thank you very much!
I just disable `constrained_layout` for this particular one now and will revisit with 3.3.1!
