### ISSUE TITLE
savefig does put the correct dpi in the metadata of jpeg

### ISSUE THREAD

**Issue by fonnesbeck** [matplotlib/matplotlib#9035] opened 2017-08-14 19:35 UTC
**Bug summary**

When I save a figure using `savefig` with a specified `dpi` argument, the resulting figure is not saved at that resolution.

**Code for reproduction**

I am saving the figure like this:

```python
bp.get_figure().savefig('../figures/domains_5.jpg', dpi=200) 
```

where `bp` is the axes of my figure.

**Actual outcome**

I get a figure saved to 72dpi

**Expected outcome**

I was expecting a figure at 200dpi

**Matplotlib version**
  * Operating System: macOS 10.12
  * Matplotlib Version: 2.0.0
  * Python Version: 3.6

**Comment by tacaswell** [comment] 2017-08-15 21:14
I can not reproduce this on master.

How are you determining the dpi of the jpeg?  

```
17:08 $ exiv2 so.jpg 
File name       : so.jpg
File size       : 52848 Bytes
MIME type       : image/jpeg
Image size      : 1280 x 960
```

Is the is the size I expect for 

```
n [15]: plt.gcf().get_size_inches()
Out[15]: array([ 6.4,  4.8])

```

**Comment by fonnesbeck** [comment] 2017-08-15 21:22
The journal I submitted a paper to returned them to me as being of insufficient resolution, and I confirmed using the properties pane in Preview for macOS.

![](http://d.pr/i/83gFnV+)

This shows 72 dpi.

**Comment by WeatherGod** [comment] 2017-08-15 21:29
What is interesting about 72 pixels/inch is that that is the old default.
v2.0 and higher has it at 100, IIRC.

**Comment by jklymak** [comment] 2017-08-16 00:59
@fonnesbeck did the journal think you were trying to submit a (1167/72=) 16.2"-wide figure?  I suspect your figure is the right # of pixels for whatever size you wanted, but the image DPI is just set incorrectly.  I agree it'd be nice if the DPI were set properly in the metadata, but the image is probably correct.

**Comment by fonnesbeck** [comment] 2017-08-16 02:15
The journal was expecting a particular dpi (200), and was not expecting any particular dimension.

**Comment by tacaswell** [comment] 2017-08-16 23:34
I suspect the issue is that we are just not putting a DPI into the meta-data.  Some tools will just not report it and others will default to 72.

See https://superuser.com/questions/1143219/changing-the-dpi-in-a-jpeg-without-re-encoding-with-imagemagick-or-something-el for a workaround to just reach in and set the dpi to what ever you want.

**Comment by QuLogic** [comment] 2018-02-09 23:19
@dstansby is there anything more to be done here, or do your PRs cover this?

**Comment by dstansby** [comment] 2018-02-10 12:14
I fixed it for Agg, but I'm not sure about other backends. Should be pretty easy to add tests like the one in #9066 to check though.

**Comment by QuLogic** [comment] 2018-02-10 21:30
It looks like the gdk, gtk, and wx files implement `print_jpg`. As you noted, the wx backend is deprecated. The gdk file is used for gtk, which is used for gtkagg and gtkcairo. However, both require PyGTK2 and GTK2, and don't run on Python 3, so I think they should also be deprecated.

**Comment by tacaswell** [comment] 2018-02-10 21:33
I am :+1: on just deleting backends that do not run on python3 as soon as master branch goes 3-only.

**Comment by QuLogic** [comment] 2018-02-10 21:50
Oh, checking a little further, both gdk and gtk are deprecated with the warning stating they'd be removed in 2.2. Not sure why gtkagg and gtkcairo didn't also get that treatment.

**Comment by QuLogic** [comment] 2018-02-10 21:57
In any case, I'm going to close this issue, because it works on the backends that will exist moving forward.

**Closed by QuLogic** 2018-02-10 21:57 UTC
