### ISSUE TITLE
nbagg backend "Stop Interaction" Feature not working if inside ipywidgets.Output()

### ISSUE THREAD

**Issue by yumasheta** [matplotlib/matplotlib#19447] opened 2021-02-03 18:15 UTC
### Bug report

**Bug summary**

Using the nbagg backend with matplotlib in a jupyter notebook and plotting the figure inside a `ipywidgets.Output()` widget breaks the functionality of the "Stop Interaction" button. If pressed, nothing happens.

**Code for reproduction**

Use inside a jupyter notebook.

```python
import ipywidgets as widgets
import matplotlib.pyplot as plt

%matplotlib notebook
# or %matplotlib nbagg

o = widgets.Output()
display(o)
with o:
    plt.plot(range(10), range(10))
    plt.show()
```

**Actual outcome**
Red circle added on the button for emphasis.
![Untitled](https://user-images.githubusercontent.com/59456929/106790033-4b810f00-6653-11eb-9f24-09be76ea250b.png)

**Expected outcome**

![image](https://user-images.githubusercontent.com/59456929/106790116-63589300-6653-11eb-97b1-e81bce1958d6.png)

**Matplotlib version**

  * Operating system:  Linux 5.10.11-arch1-1
  * Matplotlib version: 3.3.4 
  * Matplotlib backend: nbagg
  * Python version: 3.9.1
  * Jupyter version: 
    - jupyter core     : 4.6.3
    - jupyter-notebook : 6.2.0
    - qtconsole        : not installed
    - ipython          : 7.19.0
    - ipykernel        : 5.4.2
    - jupyter client   : 6.1.7
    - jupyter lab      : not installed
    - nbconvert        : 6.0.7
    - ipywidgets       : 7.6.2
    - nbformat         : 5.0.8
    - traitlets        : 5.0.5

All Python related packages installed via pip.

**Comment by QuLogic** [comment] 2021-02-04 00:03
Mostly a duplicate of #17576, I think.

**Closed by QuLogic** 2021-02-04 00:03 UTC
Labels: GUI/nbagg, third-party integration: jupyter

**Comment by yumasheta** [comment] 2021-02-04 01:31
I experienced the same problem of #17576, but I thought its unreleated.
Sorry for the trouble.
