### ISSUE TITLE
[Bug]: matplotlib/kiwisolver dependency fails to load on windows 10 (hacky solution included)

### ISSUE THREAD

**Issue by edoardo-kolver** [matplotlib/matplotlib#28391] opened 2024-06-13 20:23 UTC
### Bug summary

importing matplotlib 3.9.0 (with kiwisolver 1.4.5 and also tested with kiwisolver 1.3.1) on windows 10 gives this error:

```
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\py\Lib\site-packages\matplotlib\__init__.py", line 276, in <module>
    _check_versions()
  File "c:\py\Lib\site-packages\matplotlib\__init__.py", line 270, in _check_versions
    module = importlib.import_module(modname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\py\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\py\Lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: The specified module could not be found.
```
Installing the visual studio redistributable runtime does NOT solve this issue.

However, in my site-packages/matplotlib.libs directory, I have this file:
msvcp140-(here some sort of long garbage hash).dll
If I make a copy of this file in the same directory, renaming it msvcp140.dll (so that I have both files, one with the hash and one without), then importing matplotlib works...

### Code for reproduction

```Python
import matplotlib
```

### Actual outcome

ImportError: DLL load failed while importing _cext: The specified module could not be found.

### Expected outcome

no error

### Operating system

Windows 10 LTSC

### Matplotlib Version

3.9.0

### Matplotlib Backend

tkagg

### Python version

3.11.9

### Installation

pip

**Comment by ksunden** [comment] 2024-06-17 21:52
I believe this is a duplicate of #26745

In any case, this appears to be an installation issue with one of our dependencies ([kiwisolver](https://kiwisolver.readthedocs.io/en/latest/)) for which there is not much we can do. Reinstalling kiwisolver or both kiwisolver and matplotlib may help.

I see that you have reported this to kiwi as well (nucleic/kiwi#178) but will also point to nucleic/kiwi#173.

**Closed by ksunden** 2024-06-17 21:52 UTC
