### ISSUE TITLE
Using constrained layout and re-adding the axes of a colorbar throws a TypeError

### ISSUE THREAD

**Issue by mapfiable** [matplotlib/matplotlib#17628] opened 2020-06-13 17:22 UTC
### Bug report

**Bug summary**

Details copied from [here](https://stackoverflow.com/q/62363069/5472354), as I believe this is a bug:

I understand that `constrained_layout` is still experimental in `matplotlib`, nevertheless, I found this odd behaviour, which I guess is a bug and I wonder how to circumvent it.

If you run `re_add_colorbar_axes_as_subplot` with `constrained_layout=False`, there are no complaints, but if you set `constrained_layout=True`, it raises `TypeError: int() argument must be a string, a bytes-like object or a number, not 'Axes'`, which is traced back to the following line in [`matplotlib.axes.SubplotBase`][1]:

```python
s = str(int(args[0]))
```

Per the documentation, you can see that `SubplotBase` expected something completely different:
```python
    *args : tuple (*nrows*, *ncols*, *index*) or int
    The array of subplots in the figure has dimensions ``(nrows,
    ncols)``, and *index* is the index of the subplot being created.
    *index* starts at 1 in the upper left corner and increases to the
    right.
```

So I wonder what went wrong here by using constrained layout and the axes auto-generated by the `colorbar`-method, because if you re-add a subplot the same way, there is no issue.

The reason why I'm going through this trouble is because I would like the colorbar axes to be added to the figure as a separate `AxesSubplot` instance, and not just as a 'regular' `Axes` instance. I know you can pass the optional `cax` argument to the `colorbar`-method which allows you to determine which axes the colorbar is plotted in, as demonstrated in `add_another_subplot_fist`, but I don't know how I can get this to look properly.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np


def re_add_colorbar_axes_as_subplot(image, constrained_layout=False):
    fig, ax = plt.subplots(constrained_layout=constrained_layout)
    image_artist = ax.imshow(image)

    colorbar = fig.colorbar(image_artist)
    colorbar.ax.remove()
    colorbar.ax.figure = fig  # not sure why this is actually necessary either
    fig.add_subplot(colorbar.ax)

    fig.show()


def use_gridspec_keyword(image, constrained_layout=False):
    fig, ax = plt.subplots(constrained_layout=constrained_layout)
    image_artist = ax.imshow(image)

    colorbar = fig.colorbar(image_artist, ax=ax, use_gridspec=True)
    print(colorbar.ax)  # AxesSubplot instance if constained_layout=False,
    # Axes instance if constrained_layout=True
    fig.show()


def add_another_subplot_fist(image, constrained_layout=False):
    fig = plt.figure(constrained_layout=constrained_layout)
    ax = fig.add_subplot(121)
    image_artist = ax.imshow(image)

    ax2 = fig.add_subplot(122)
    fig.colorbar(image_artist, cax=ax2)
    # conversely, there is no problem when using constrained layout
    # and re-adding this subplot
    # ax2.remove()
    # ax2.figure = fig
    # fig.add_subplot(ax2)
    fig.show()


if __name__ == '__main__':
    image = np.random.uniform(0, 1, (100, 100))

    # re_add_colorbar_axes_as_subplot(image, True)
    # add_another_subplot_fist(image, True)
    use_gridspec_keyword(image, True)
```

**EDIT**

Ok, I just realized that you can pass the `use_gridspec` keyword to the `colorbar`-method. From the [docs][2]:

> If cax is None, a new cax is created as an instance of Axes. If ax is an instance of Subplot and use_gridspec is True, cax is created as an instance of Subplot using the gridspec module. 

But for some reason, this keyword seems to be ignored when using constrained layout.

**Matplotlib version**

  * Operating system: Windows 10 Home 64bit
  * Matplotlib version: 3.1.3 (via Anaconda)
  * Matplotlib backend: backend_interagg
  * Python version: 3.7.7

  [1]: https://matplotlib.org/3.2.1/_modules/matplotlib/axes/_subplots.html#SubplotBase
  [2]: https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.colorbar.html

**Comment by jklymak** [comment] 2020-06-13 18:53
Colorbars can be made either using use_gridspec True or false.  Except when constrained_layout is used because it needs to control the position of the colorbar itself and can’t do so in a nested gridspec layout.  So that kwarg is ignored And the colorbar is created as if use_gridspec is False.  I suppose we could warn. 

As for your fundamental problem it’s pretty hard to give you a workaround without some idea what you are trying to do and why.  Why are you removing and then adding the colorbar again?    I think it’s a mistake to consider a colorbar another axes for layout reasons and you will not find constrained_layout works properly if you do this even if it didn’t throw an error.

**Comment by mapfiable** [comment] 2020-06-13 19:53
Thanks for the quick reply! Sorry for my ignorance, but I am not sure I understand. `constrained_layout` works fine for a figure with several subplots (in fact, in think that is one of the [dedicated used cases](https://matplotlib.org/3.1.0/tutorials/intermediate/constrainedlayout_guide.html)), but it does not work when you want to have a colorbar in a separate subplot? You say 'nested layout'. So I take it the subplot that is created using `use_gridspec=True` is not in fact a subplot of the figure, but of the axes? Is that it?

>  Why are you removing and then adding the colorbar again?

To answer that I have to extend a little bit. I am designing a program using `PyQt5` for the UI and the `FigureCanvasQTAgg` backend from matplotlib to plot some interactive figures. At some point, I might want to save the figure, which, at that point, may or may not be relatively complex in terms of number and types of artists. Because I don't want to mess with the figure / canvas instance that is used to display the figure in the GUI, I want to copy the figure, which I can then safely modify and use to run `savefig()`. 
As I am sure you are aware, copying a figure instance is not super trivial and as far as I know also not recommended. [This post](https://stackoverflow.com/a/45812071/5472354) explains how that should work using `pickle`, but I have just found [that this doesn't always work.](https://github.com/matplotlib/matplotlib/issues/17627). I also tried to only move the axes as explained [here](https://stackoverflow.com/a/46906599/5472354), and after the figure is saved, move the axes back to original figure, but that didn't work either, as it messed up the interactivity somehow.  Unfortunately, I don't have code to show that right now, but I am sure you can imagine. It's not a nice solution anyways. 
Now I know the proper way would be to re-plot everything from scratch in a secondary figure that can be used for saving, but that is just so much work. 
- To get started, you can use `axes.get_children()` to get all the artists that reside in that axes, but unfortunately, the method doesn't distinguish between the default artists that come with the axes, like `spines` etc. and artists you added manually later on. I haven't found a way to make proper use of this.
- So instead, you could just keep track of all the artists you add along the way, which I guess is fair enough.
- But now, you need a way to easily replicate the artists. You can do something like `duplicate = type(artist)(**artist.properties())` to get you started, but the properties usually don't include the necessary `args`. So you need to retrieve them in a different way, which is hightly dependent on the type of the artist. 

Bottom line is, I haven't found a good approach to recreate a figure from scratch without having to take into consideration every kind of artist and how to initialize it that may be part of the figure. I am still hoping to find an easier way, as this is giving me a very hard time for the past week. Here is my current approach (which doesn't really work):

```python
import sys
import numpy as np
from copy import copy
import matplotlib.pyplot as plt
from contextlib import contextmanager

from PyQt5.QtWidgets import QDialog, QApplication, QGridLayout
from matplotlib.backends.backend_qt5agg import \
    FigureCanvasQTAgg as FigureCanvas


@contextmanager
def copy_figure(fig: plt.Figure):
    fig_copy = plt.figure()
    for ax in fig.axes:
        ax_copy = copy(ax)
        ax_copy.figure = fig_copy
        fig_copy.add_axes(ax_copy)

    yield fig_copy
    plt.close(fig_copy)


class MainWindow(QDialog):
    def __init__(self):
        super().__init__()
        self.fig, self.ax = plt.subplots(constrained_layout=True)
        self.canvas = FigureCanvas(self.fig)
        lay = QGridLayout(self)
        lay.addWidget(self.canvas)
        self.setLayout(lay)

        image = np.random.uniform(0, 1, (100, 100))
        image_artist = self.ax.imshow(image)
        cb = self.fig.colorbar(image_artist)
        with copy_figure(self.fig) as copy_fig:
            copy_fig.savefig('../test_files/test.png')


if __name__ == '__main__':
    app = QApplication(sys.argv)
    GUI = MainWindow()
    GUI.show()
    sys.exit(app.exec_())
```

**Comment by mapfiable** [comment] 2020-06-13 20:22
Right, I actually forgot to really answer your question. 

> Why are you removing and then adding the colorbar again?

If instead of:

```python
    with copy_figure(self.fig) as copy_fig:
        copy_fig.savefig('../test_files/test.png')
```
You run:

```python
    with copy_figure(self.fig) as copy_fig:
        copy_fig.show()
```
You get the following `Warning`:
```
C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pycharm_matplotlib_backend\backend_interagg.py:68: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  self.figure.tight_layout()
```
I couldn't find *any* documentation on this message though, so I had to find out myself what it actually means, that an axes instance is 'not compatible with tight_layout'. 
First of all, I quickly noticed that this is caused by the axes instance of the colorbar. I then followed the traceback to the `figure.py` and found that this warning is raised `if None in subplotspec_list`. So what does that mean? So I looked at `get_subplotspec_list` in `tight_layout.py` and found that items in `subplotspec_list` can be `None` for a couple of reasons, but in the case of a colorbar axes specifically, it is because the axes doesn't have a `get_subplotspec` method. And why is that? Because the axes of the colorbar is a regular `Axes`, and not an `AxesSubplot`. So I thought I could resolve this by adding the colorbar axes as a subplot.

**Comment by jklymak** [comment] 2020-06-13 20:34
I’ll try and help more tomorrow but...

The colorbar created with use_gridspec=False is incompatible with tight_layout, but use_gridspec=True is compatible.  But I’m not clear what this has to do with constrained_layout.  The two do the same thing and don’t mix.  And constrained_layout will not survive a pickle because we strip all the state.

**Comment by mapfiable** [comment] 2020-06-13 20:41
Thank you, much appreciated! I know there is a lot of context and questions here.. I'm sorry! I think I have summarized everything now though.

**Comment by tacaswell** [comment] 2020-06-23 03:24
> I don't understand why, when calling fig.show()

It is because pycharm's custom backend is calling it unconditionally: https://github.com/JetBrains/intellij-community/blob/959c2300a2853d6a5622c37fccd9f864ab696c1e/python/helpers/pycharm_matplotlib_backend/backend_interagg.py#L68  This should probably be reported to jetbrains as a bug?

**Comment by mapfiable** [comment] 2020-06-26 13:07
Good to know, I think it should.

**Comment by anntzer** [comment] 2020-06-26 14:05
Generic figure copying/serialization and swappable style sheets are both *hard* problems which I guess is nice to keep track of as a wishlist but which I doubt will ever be solved except by hiring someone to work on them for quite a while, and even then there's no guarantee.  (For concrete examples as to why:  To copy a figure you need in theory to also copy the tick formatters (so that interactivity still works with the new figure), but formatters can basically be arbitrary callables and serialization of arbitrary callables is, well, not something Python does well.  For swapping style sheets, we currently haven't even managed to have a consistent policy as to whether style sheets are consulted at artist creation time or at draw time, which clearly seems to be a prerequisite for swapping the style sheet.)  In any case both problems are already tracked elsewhere...

For the specific problem at hand, have you considered just always adding all artists but then making some of them invisible (via `set_visible`)?  Possibly also making them not participate in constrained_layout, if that's possible... (perhaps *that's* something more actionable).

**Comment by jklymak** [comment] 2020-06-26 14:30
All artists have set_in_layout.

**Comment by jklymak** [comment] 2020-07-21 17:37
I'm going to close this because I don't think there is anything actionable here.  @mapfiable if you have some narrower concerns, please feel to open a new issue with a minimal reproducible example.

**Closed by jklymak** 2020-07-21 17:37 UTC

**Comment by mapfiable** [comment] 2020-07-25 07:11
No worries, thanks a lot for everyone's input! For now, I did find a workaround although I am not super happy with it. But judging by what @anntzer said, this seems to be part of a very complicated issue that is being tracked anyways, so I guess there is nothing I can do about it. I definitely learned something, and maybe this 'essay' can be of help at some point.
