### ISSUE TITLE
Marker disappears with markerfacecolor='None' when saving as eps file

### ISSUE THREAD

**Issue by arbolis** [matplotlib/matplotlib#11832] opened 2018-08-09 12:53 UTC
### Bug report

Markers disappear if I use markerfacecolor='None', when saving as eps file. if I save as png file, they are correctly displayed. 
Note that markeredgewidth is correctly set to a non zero value and markeredgecolor is correctly set to a color. As I said, the figure is correctly produced when saved as png, so it should really work similarly for eps figure, but it doesn't.

**Code for reproduction**

I'm too lazy for a complete reproducible example. But here are the relevant lines.

```python
axe.plot(x, y, linestyle = '-', linewidth=0.5, marker = 's', markeredgewidth = 0.5, label='something', c
    lip_on= False, markersize = '3',markerfacecolor='None', markeredgecolor='green', color='green')

plt.savefig('another_name_come_on_not_this_again.png', format='png', dpi=400)
plt.savefig('another_name_come_on_not_this_again.eps', format='eps', dpi=400)
```

Only the line is displayed. No marker.

**Expected outcome**

As said above, the edges of the makers should be displayed, as in the case when the picture is saved as png. But they aren't.

**Matplotlib version**

  * Operating system: GNU/Arch Linux.
  * Matplotlib version: 2.2.2.
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.0.

**Comment by tacaswell** [comment] 2018-08-09 13:26
Thanks for reporting this.  You were only two calls to `np.random.rand` away from a reproducible example!

This is a duplicate of https://github.com/matplotlib/matplotlib/issues/11372 and https://github.com/matplotlib/matplotlib/issues/10921 which was fixed on master via https://github.com/matplotlib/matplotlib/pull/10935 and backported to 2.2.x via https://github.com/matplotlib/matplotlib/pull/10937.

2.2.3 and 3.0rc1 (which should be tagged any day now) will have this fix.

**Closed by tacaswell** 2018-08-09 13:26 UTC
