### ISSUE TITLE
backend_pdf has a FutureWarning

### ISSUE THREAD

**Issue by WeatherGod** [matplotlib/matplotlib#4078] opened 2015-02-07 22:54 UTC
While running mplot3d tests, I get that numpy FutureWarning about comparing against None, but this time in backend_pdf!

```
/home/ben/.local/lib/python2.7/site-packages/matplotlib-1.4.x-py2.7-linux-x86_64.egg/matplotlib/backends/backend_pdf.py:2277: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  different = bool(ours != theirs)
```

**Comment by jenshnielsen** [comment] 2015-02-08 08:28
Can you reproduce this on master? I would think that this was fixed by #3718

**Comment by WeatherGod** [comment] 2015-02-08 14:43
yes, this is on master

**Comment by tacaswell** [comment] 2015-02-08 19:20
@WeatherGod I can't reproduce this and agree it should have been fixed by #3718 

See https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_pdf.py#L2296

**Comment by WeatherGod** [comment] 2015-02-08 19:52
Grrrrrr, I just noticed that I had an install of matplotlib in my .local
directory that was overriding the install that I was testing in the conda
environment. Probably also explains the error I am seeing for the rc.

**Comment by jenshnielsen** [comment] 2015-02-09 07:53
Ok to close this then?

**Closed** 2015-02-09 15:33 UTC
Labels: backend/pdf
