### ISSUE TITLE
ApplePersistenceIgnoreState error

### ISSUE THREAD

**Issue by noahaskell** [matplotlib/matplotlib#6242] opened 2016-03-29 23:22 UTC
I'm using Python 3.5.1 (Anaconda 2.5.0 distribution) on OS X 10.11.3. With Matplotlib 1.5.1, when I tried to import pyplot (e.g., `import matplotlib.pyplot as pl`), I would get the following error:

```
2016-03-29 19:00:39.396 python[30241:4673155] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/vm/851b53f57ql7tsx_jjpltblh0000gn/T/com.continuum.python.savedState
```

I would get the same error if I tried to use the `--pylab` flag when I started IPython or if I used the `%pylab` magic. After `import matplotlib.pyplot as pl`, I could go ahead and use, e.g., `pl.plot` to make a figure, but once the figure showed up, it wouldn't return control to IPython.

So, I removed Matplotlib 1.5.1 and installed 1.4, and the problem seemed to go away. But then I got the same error message the first time I tried to plot something. In this case, it showed the figure just fine, and it returns control to IPython just fine. However, when a figure doesn't show up and I use, e.g., `pl.show()`, it (still) doesn't return control.

**Comment by tacaswell** [comment] 2016-04-08 05:19
What backend are you using?  

Do you get the same errors in 'plain' python shell?

**Comment by Auerilas** [comment] 2016-04-19 16:56
I also get this error message now. I am running Python v2.7 on OSX 10.11.14 with matplotlib v1.5.1. I recently installed pyglet, and now every time that I run

    import matplotlib.pyplot as plt

I receive:

    Python[1237:50603] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/zl/yxc7hlld61b6y2n5ghnn_q4h0000gn/T/org.python.python.savedState

I uninstalled pyglet, but the error persists. This happens on every backend that I've tried (macosx, qt4agg, cocoa, etc.), and occurs in both IPython and plain Python. It doesn't break Python, and I can still execute my code, but I'm curious as to what the error is, how to debug it, and how to resolve it.

Thanks!

**Comment by smearedink** [comment] 2016-05-02 18:50
I'm also seeing this.  Python 3.5.1 installed with homebrew, OS X 10.11.3, matplotlib 1.5.1, installed with pip.  I see it as soon as I import pyplot.  It's still functional, just annoying.  (I'm also using IPython 4.0.0)

**Comment by dstansby** [comment] 2017-11-01 17:05
Could someone try upgrading to matplotlib version 2.1 and seeing if the issue is still present?

**Comment by noahmotion** [comment] 2017-11-01 17:35
I have matplotlib 2.0.0, and I haven't seen this problem in a while (I don't remember exactly when I upgraded to 2). I just upgraded to 2.1.0, and everything seems to be working fine.

**Comment by dstansby** [comment] 2017-11-01 17:37
Great, I'll close this then. Feel free to re-open if the issue starts again!

**Comment by kghelwegen** [comment] 2017-11-20 11:34
I still have this issue with matplotlib 2.1.0, Python 3.6.3, but (as far as I can discover) only if I first load matplotlib.pyplot in a jupyter notebook and leave that notebook open for some time (a "Starting buffering for ..." message appears in the log of jupyter).

The ApplePersistenceIgnoreState message appears both in the IPython and regular python shell.

**Comment by cbrnr** [comment] 2018-02-22 08:47
Same here, macOS 10.13.3, Python 3.6.4 (Homebrew), matplotlib 2.1.2. This warning pops up right after importing `matplotlib.pyplot` or running `%matplotlib` in IPython. It is annoying because I have to press Enter to re-enable the prompt.

**Comment by cbrnr** [comment] 2018-02-22 08:50
NB that this does *not*  happen with Anaconda.

**Comment by cbrnr** [comment] 2018-02-22 08:54
With Homebrew Python, a Python icon is added to the dock after `%matplotlib`, whereas nothing is added to the dock with Anaconda. The problem is independent of the backend (happens with `osx` as well as with `qt5`).

**Comment by cbrnr** [comment] 2018-02-22 09:40
I found [this answer](https://stackoverflow.com/a/21567601/1112283) on SO. Turns out that you can turn off a new macOS feature that's not really necessary/working for Python:

    defaults write org.python.python ApplePersistenceIgnoreState NO

Not sure if this can cause any side effects though. Also not sure if this can be solved by matplotlib - looks like it probably should be fixed by Homebrew.

**Comment by cbrnr** [comment] 2018-02-27 08:30
Quick update, this is not a Homebrew issue. I've created an upstream issue in the Python bug tracker (https://bugs.python.org/issue32909). The Python devs note that the `defaults` solution is a hack and not a proper solution, and that the problem should be fixed in the GUI libs or matplotlib. Any idea how to solve this in matplotlib?

**Comment by jenshnielsen** [comment] 2018-02-27 09:06
@cbrnr I have never seen it on several macs. It seems most likely that you have persistent state left over from an old version of python that has crashed or non cleanly shutdown at some point. Anaconda uses a different application id (http://com.continuum.python/ instead of org.python.python) 

To solve it we would need to figure out how to cleanup that state

**Comment by cbrnr** [comment] 2018-02-27 12:09
@jenshnielsen I think you are right. I might have figured out how to clean up this state. It seems like creating the key with `defaults write org.python.python ApplePersistenceIgnoreState NO` fixes the problem, because next I deleted the key with `defaults delete org.python.python ApplePersistenceIgnoreState` and voilà - the warning message is gone!

**Closed** 2020-09-07 22:24 UTC
Labels: Needs clarification, OS/Apple
