### ISSUE TITLE
Markers are not centered properly

### ISSUE THREAD

**Issue by jason-s** [matplotlib/matplotlib#11836] opened 2018-08-09 21:21 UTC
I am using IPython Notebook to view matplotlib graphs. I have noticed many times that the markers are drawn slightly off-center. Here is an example:

![image](https://user-images.githubusercontent.com/738893/43926583-a25148f4-9bdf-11e8-96ce-0b57e0deb61f.png)

Closeup:

![image](https://user-images.githubusercontent.com/738893/43926636-cd55433e-9bdf-11e8-857d-fbb0b8300839.png)

Code to reproduce:

```python
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

t = np.linspace(-1,1,40)
plt.plot(t,t**3 - 0.75*t,'.-',linewidth=0.3)
plt.grid(True)
```

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 2.2.2'
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 2.7.15 from Anaconda Python
  * Jupyter version (if applicable): 5.5.0
  * Other libraries: n/a

**Comment by afvincent** [comment] 2018-08-09 21:26
Possibly related to  #7233?

**Comment by jason-s** [comment] 2018-08-09 21:27
oops, yeah I just found that and #8533

**Comment by jason-s** [comment] 2018-08-09 21:27
mark as duplicate?

**Comment by afvincent** [comment] 2018-08-09 21:35
No problem. Thank you for opening the ticket ;). I did not follow the latest evolution of those issues, so I do not know if there were some improvements on that topic :/ (and pinging @anntzer who tried to tackle those questions IIRC ^^).

Marking as duplicate and closing as the issue seems similar to the ones reported in #7233, #7262, #7624, and #8533. Anyone please remove the flag and reopen the thread (or ask for it) if you disagree.

**Closed by afvincent** 2018-08-09 21:35 UTC
Labels: Duplicate

**Comment by ImportanceOfBeingErnest** [comment] 2018-08-09 21:58
I just want to note, while there certainly *is* the annoying  issue of marker stamping present here, most of the mismatch from the example comes from the wrong `linspace` in use. If you want points spaced by `0.05`, you need to use **41** points between -1 and 1, not 40.
So with `t = np.linspace(-1,1,41)` we get
![image](https://user-images.githubusercontent.com/23121882/43928117-0db5ca52-9c30-11e8-8389-7c7f2b195b29.png)

which is indeed not optimal, but not as bad as it seems at first sight.

**Comment by jason-s** [comment] 2018-08-10 01:14
thanks but that doesn't concern me, it's only the fact that the markers are off-center.

**Comment by anntzer** [comment] 2018-08-10 20:14
There is no one working on fixing this for the default Agg-based backends (AFAIK), although the issue is well understood.  You may want to try the cairo based backends, which don't have this specific issue (not sure you can activate them with jupyter notebook? Perhaps @jklymak knows something here as I know he uses the notebook); alternatively, I wrote https://github.com/anntzer/mplcairo (another cairo based backend) in particular to fix the issue.

**Comment by ImportanceOfBeingErnest** [comment] 2018-08-10 21:47
You may use the Cairo backends in jupyter just as other backends, `matplotlib.use("TkCairo")`. The output will of course be a figure window invoked by `plt.show()`. There is no "inline"-cairo backend, but one may of course quickly tinker one together:

```
import matplotlib
matplotlib.use("TkCairo")

import numpy as np
import matplotlib.pyplot as plt

t = np.linspace(-1,1,41)
fig = plt.figure()
plt.plot(t,t**3 - 0.75*t,'.-',linewidth=0.3, markersize=3)
plt.grid(True)

def inline_show(fig=None):
    import io
    from IPython.display import Image, display
    fig = fig or plt.gcf()
    buff = io.BytesIO()
    fig.savefig(buff)
    buff.seek(0)
    display(Image(data=buff.getvalue()))
    plt.close(fig)
    
    
inline_show(fig)  
```

![image](https://user-images.githubusercontent.com/23121882/43982588-ce57a110-9cf6-11e8-8659-1edbdc610bc9.png)


The same approach can also be used with the usual AGG backends. Because the stamping issue is more pronounced the smaller the dpi, one may save a high-dpi version of the figure and display it with lower width in the notebook.

```
%matplotlib inline  # "inline is Agg based
import numpy as np
import matplotlib.pyplot as plt

t = np.linspace(-1,1,41)
fig = plt.figure()
plt.plot(t,t**3 - 0.75*t,'.-',linewidth=0.3, markersize=3)
plt.grid(True)

def inline_show(fig=None):
    import io
    from IPython.display import Image, display
    fig = fig or plt.gcf()
    buff = io.BytesIO()
    fig.savefig(buff, dpi=400)
    buff.seek(0)
    display(Image(data=buff.getvalue(), width=480))
    plt.close(fig)
    
inline_show(fig)
```

![image](https://user-images.githubusercontent.com/23121882/43982764-c2672488-9cf7-11e8-9618-54f08d402dea.png)

**Comment by endolith** [comment] 2024-04-09 02:02
Was this fixed?  I'm not sure if I'm still seeing it or something else:

![image](https://github.com/matplotlib/matplotlib/assets/58611/5c5601fe-6aa2-4de4-8efd-17d4a6ba2452)

The dots seem to be below the line more often than not:

![image](https://github.com/matplotlib/matplotlib/assets/58611/5a485e39-7649-444f-84e0-67673120e25c)

**Comment by tacaswell** [comment] 2024-04-09 02:51
Unfortunately we have not increased the number of marker stamps yet.  The linked issues are still open.

**Comment by tacaswell** [comment] 2024-04-09 02:52
The issue can be ameliorated by increasing the DPI.
