### ISSUE TITLE
[Bug]: Calling invert_yaxis() on a 3D plot inverts the xaxis

### ISSUE THREAD

**Issue by baloe** [matplotlib/matplotlib#21843] opened 2021-12-02 12:55 UTC
### Bug summary

Instead of inverting the yaxis, `invert_yaxis` actually has the same effect as `invert_xaxis`:

The demo code is derived from the demo [here](https://github.com/matplotlib/matplotlib/issues/14577/#issuecomment-503560047).

### Code for reproduction

```python
import matplotlib
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(9,3.5), dpi=80)
ax1 = fig.add_subplot(141, projection='3d')
ax2 = fig.add_subplot(142, projection='3d')
ax3 = fig.add_subplot(143, projection='3d')
ax4 = fig.add_subplot(144, projection='3d')

fig.suptitle(f"matplotlib v{matplotlib.__version__}")

ax1.plot([1,1,10,10], [1,10,10,10], [1,1,1,10], marker="o")
ax2.plot([1,1,10,10], [1,10,10,10], [1,1,1,10], marker="o")
ax3.plot([1,1,10,10], [1,10,10,10], [1,1,1,10], marker="o")
ax4.plot([1,1,10,10], [1,10,10,10], [1,1,1,10], marker="o")

ax2.invert_xaxis()
ax3.invert_yaxis()
ax4.invert_zaxis()

plt.show()
```

### Actual outcome

![Figure_1](https://user-images.githubusercontent.com/12622691/144425541-ddb3f3ca-a5d0-47fa-a634-d87279c07db9.png)

### Expected outcome

![Figure_edit](https://user-images.githubusercontent.com/12622691/144481685-d50ea336-ff9b-43d7-b842-b6d290e45da6.png)  
(well ... somewhat like this)

### Additional information

This was worked on here, but apparently did not fix my issue, or am I missing something?
https://github.com/matplotlib/matplotlib/pull/14579/commits/0e413176143711bb417439634acd8d6031264612
https://github.com/matplotlib/matplotlib/pull/14579

### Matplotlib Version

3.5.0

### Installation

conda

**Comment by dstansby** [comment] 2021-12-02 20:27
Thanks for reporting with a clear example! I'm going to close this as a duplicate of https://github.com/matplotlib/matplotlib/issues/21369

**Closed by dstansby** 2021-12-02 20:27 UTC
