### ISSUE TITLE
text.get_window_extent() is incorrect until a draw actually occurs

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7614] opened 2016-12-12 00:17 UTC
The docstring of `Text.get_window_extent` contains the snippet
```
    *renderer* defaults to the _renderer attribute of the text
    object.  This is not assigned until the first execution of
    :meth:`draw`, so you must use this kwarg if you want
    to call :meth:`get_window_extent` prior to the first
    :meth:`draw`.  For getting web page regions, it is
    simpler to call the method after saving the figure.
```
which suggests (not explicitly, for sure) that passing in the renderer *will* yield the correct window extent even before the first draw.  But this is not the case (as of 1.5.3 and 2.0rc1):
```
from matplotlib import pyplot as plt

fig, ax = plt.subplots()
fig.canvas.draw()
ann = plt.annotate("foo", (.5, .5))
print(ann.get_window_extent(ax.get_renderer_cache()))
# print(ann.get_window_extent()) # would not work here
fig.canvas.draw()
print(ann.get_window_extent(ax.get_renderer_cache()))
# print(ann.get_window_extent()) # would give the same result here
```
yields
```
Bbox(x0=0.5, y0=-2.5, x1=22.375, y1=11.5) # first result is incorrect
Bbox(x0=328.0, y0=234.59999999999997, x1=349.875, y1=248.59999999999997)
```

Note: A quickfix may be to declare that computing the window extent is not supported as long as the rendering did not take place...

**Comment by tacaswell** [comment] 2016-12-12 06:16
It looks like `Annotation.draw` is doing a bit more work at the top to update it's self:

```python
from matplotlib import pyplot as plt

fig, ax = plt.subplots()
fig.canvas.draw()
ann = plt.annotate("foo", (.5, .5))
renderer = ax.get_renderer_cache()

xy_pixel = ann._get_position_xy(renderer)
ann._update_position_xytext(renderer, xy_pixel)
ann.update_bbox_position_size(renderer)

print(ann.get_window_extent(renderer))

# print(ann.get_window_extent()) # would not work here
fig.canvas.draw()
print(ann.get_window_extent(ax.get_renderer_cache()))
print(ann.get_window_extent()) # would give the same result here
```

This gives the right results in all cases, but the need to hit a private method(s) is less than ideal.  I suspect that some of that book keeping needs to be moved to `get_window_extent`, but have not chased through the code enough to be sure a) this is the minimal set of things that need to be done b) doing these things in `get_window_extent` is actually a good idea c) there is not a cleaner way to factor this.

**Comment by anntzer** [comment] 2016-12-12 06:50
Actually one can just add a call to the public `update_positions(renderer)` which does exactly `ann._update_position_xytext(renderer, ann._get_position_xy(renderer))`; the second call (`update_bbox_position_size`) only affects the FancyBboxPatch (if any) and does not change the window extent.

**Comment by tacaswell** [comment] 2016-12-12 06:54
adding note to look at how the auto-wrapping feeds into this and when that computation is done.

**Comment by jklymak** [comment] 2018-09-12 15:49
marking these `get_window_extent` issues as "geometry manager" for want of a better tag.  But I think this can/should be fixed, but not right now...

**Comment by bilylee** [comment] 2019-01-04 12:31
@mightyCelu A simple hack to fix the problem would be to save the figure twice.

**Comment by brunobeltran** [comment] 2020-10-19 03:08
I can no longer reproduce this error.

**Closed by brunobeltran** 2020-10-19 03:08 UTC
Labels: Documentation, geometry manager
