### ISSUE TITLE
It would be great if mathtext.py supported LaTeX environments

### ISSUE THREAD

**Issue by moorepants** [matplotlib/matplotlib#5169] opened 2015-10-02 19:44 UTC
Matrices and array environments would be useful to display with matplotlib.

Here is a stackoverflow question that is related: http://stackoverflow.com/questions/26329177/how-to-display-a-matrix-in-the-matplotlib-annotations

We'd also like support for our SymPy printing backends. See #5162 for some related info.

**Comment by tacaswell** [comment] 2015-10-02 21:32
attn @mdboom 

I assume this will require a pretty major effort to implement more of latex in our mathtex engine?

**Comment by moorepants** [comment] 2015-10-02 22:56
It may not be worth doing this, as opposed the user installing LaTeX. I'm not sure how much demand there may be for this functionality. We are working on solutions for SymPy that work around this. And it could be a perpetual request from us to implement new renderings for various SymPy objects. FYI.

**Comment by mdboom** [comment] 2015-10-06 14:04
Historically, it's always been hard to know where to draw the line on this kind of functionality.  I'd love to have it do "everything", but we have finite time and all that.

@moorepants: Do you have a good sense of what would be the most useful features that mathtext currently doesn't do?  `\begin{matrix}\end{matrix}` is probably high on the list, I would guess.  Any others?

**Comment by moorepants** [comment] 2015-10-12 03:19
Yes, the various matrix commands from amsmath would be most helpful, or simply array.

**Comment by cesss** [comment] 2017-02-11 11:56
I need to display matrices without having LaTeX installed, so consider me as another one hit by this mathtext limitation. I agree that fully supporting environments could be a huge effort, but some array-like workaround would be great. Note that my matrices are not numeric, each matrix element is another mathtext expression, which can have fractions, integrals, etc...

**Comment by anntzer** [comment] 2019-03-22 10:58
I'm going to close this as essentially a duplicate of #321 (the main issue is with general environment support, not what the specific environments we need to support are).

**Closed by anntzer** 2019-03-22 10:58 UTC
Labels: Wishlist, text
