### ISSUE TITLE
install backend gtk in Cygwin

### ISSUE THREAD

**Issue by nowox** [matplotlib/matplotlib#5418] opened 2015-11-06 13:51 UTC
When installing matplotlib from sources I get this error for `setupext.BackendGtk()`

```
OPTIONAL BACKEND EXTENSIONS
      0 [main] python2.7 27276 child_info_fork::abort: address space needed by 'cygEGL-1.dll' (0x7F0000) is already occupied
Traceback (most recent call last):
  File "setup.py", line 271, in <module>
    result = package.check()
  File "/usr/src/matplotlib-1.5.0/setupext.py", line 520, in check
    additional_info = self.check_requirements()
  File "/usr/src/matplotlib-1.5.0/setupext.py", line 1608, in check_requirements
    ext = self.get_extension()
  File "/usr/src/matplotlib-1.5.0/setupext.py", line 1629, in get_extension
    self.add_flags(ext)
  File "/usr/src/matplotlib-1.5.0/setupext.py", line 1690, in add_flags
    pkg_config.setup_extension(ext, 'pygtk-2.0')
  File "/usr/src/matplotlib-1.5.0/setupext.py", line 306, in setup_extension
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable
```

**Comment by jenshnielsen** [comment] 2015-11-06 14:06
This is trying to fork a subprocess which is apparently not always reliable in cygwin. Have you tried following the guide in https://cygwin.com/faq-nochunks.html#faq.using.fixing-fork-failures especially ensuring that you are not running any of the software in https://cygwin.com/faq-nochunks.html#faq.using.bloda

**Comment by jenshnielsen** [comment] 2015-11-06 14:09
If you don't need GTK you can also disable the backend in `setup.cfg` Modify `setup.cfg.template` and rename to `setup.cfg`

**Comment by nowox** [comment] 2015-11-06 14:10
I disabled any of [these](https://cygwin.com/faq.html#faq.using.bloda) and did a `rebase`. I still have the same issue.

**Comment by nowox** [comment] 2015-11-06 14:11
I need to display figures and plots somewhere. Gtk seems to be the best solution in my case.

**Comment by jenshnielsen** [comment] 2015-11-06 14:22
> I disabled any of these and did a rebase. I still have the same issue. 
There is not much we can do to fix this from the matplotlib side as this is really a known limitation in Cygwin not a bug in Matplotlib.

I would suggest using QT or WX rather than GTK since they have no compile time dependencies. Then disable all backends in setup.cfg so you don't need to fork and try again.

**Comment by nowox** [comment] 2015-11-06 16:02
Then comes the problem to install WX or QT on Cygwin :(

**Comment by nowox** [comment] 2015-11-08 08:15
Would it be possible to use Cygwin/Python and a plotting engine running on native Windows and provided by Anaconda or Python (x,y)?

**Comment by nowox** [comment] 2015-11-09 08:28
Some news...

By installing these packages on Cygwin: 

```
python-wx-tools
python-wx2.8
python-wx3.0
python-wxversion
```

And leaving only the `Windowing()`

```
    # These backends are listed in order of preference, the first
    # being the most preferred.  The first one that looks like it will
    # work will be selected as the default backend.
    #setupext.BackendMacOSX(),
    #setupext.BackendQt5(),
    #setupext.BackendQt4(),
    #setupext.BackendGtk3Agg(),
    #setupext.BackendGtk3Cairo(),
    #setupext.BackendGtkAgg(),
    #setupext.BackendTkAgg(),
    #setupext.BackendWxAgg(),
    #setupext.BackendGtk(),
    #setupext.BackendAgg(),
    #setupext.BackendCairo(),
    setupext.Windowing(),        
```

I was able to plot something using the X-server. 

I still need to specify manually my backend: 

```
import matplotlib
matplotlib.use('Wx')  # The next step is to configure this as default...
import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
plt.show()
```

**Comment by jenshnielsen** [comment] 2015-11-09 08:54
Great. You can set your preferred backend manually by setting in in the matplotlibrc file See http://matplotlib.org/users/customizing.html#the-matplotlibrc-file

**Comment by tacaswell** [comment] 2015-11-11 05:02
@nowox Would you be willing to write up the details of what you had to do for the docs?  Closing this as it sounds like you resolved your own problem?

**Closed by tacaswell** 2015-11-11 05:02 UTC

**Comment by joshwarren** [comment] 2016-09-13 12:54
Did this ever get written up? I am having a very similar problem, but it refuses to install Windowing and I can't find any documentation on it (for dependencies etc).

**Comment by nowox** [comment] 2016-09-26 06:56
Sorry for the long delay. 

So I could install matplotlib under Cygwin with the following patch on `setup.py`:

```
--- matplotlib-1.5.0/setup.py	2015-11-09 10:42:05.101335000 +0100
+++ matplotlib-1.5.0/setup_new.py	2015-11-09 10:42:02.730059000 +0100
@@ -94,17 +94,17 @@
     # These backends are listed in order of preference, the first
     # being the most preferred.  The first one that looks like it will
     # work will be selected as the default backend.
-    setupext.BackendMacOSX(),
-    setupext.BackendQt5(),
-    setupext.BackendQt4(),
-    setupext.BackendGtk3Agg(),
-    setupext.BackendGtk3Cairo(),
-    setupext.BackendGtkAgg(),
-    setupext.BackendTkAgg(),
-    setupext.BackendWxAgg(),
-    setupext.BackendGtk(),
-    setupext.BackendAgg(),
-    setupext.BackendCairo(),
+    #setupext.BackendMacOSX(),
+    setupext.BackendQt5(),
+    setupext.BackendQt4(),
+    #setupext.BackendGtk3Agg(),
+    #setupext.BackendGtk3Cairo(),
+    setupext.BackendGtkAgg(),
+    setupext.BackendTkAgg(),
+    setupext.BackendWxAgg(),
+    setupext.BackendGtk(),
+    setupext.BackendAgg(),
+    setupext.BackendCairo(),
     setupext.Windowing(),
     'Optional LaTeX dependencies',
     setupext.DviPng(),
```

It seems `Gtk3Agg` and `Gtk3Cairo` cause a `fork` issue in Cygwin even in Cygwin64.
