### ISSUE TITLE
Matplotlib requires sudo on Ubuntu 14.04 for me

### ISSUE THREAD

**Issue by skarthikkrishna92** [matplotlib/matplotlib#3960] opened 2015-01-01 16:17 UTC
I recently shifted to a new laptop. After installing Ubuntu 14.04 LTS and all of the packages that my previous system contained, I copied all my files from my old system to the new one. 

Whenever I try executing any python code that has a matplotlib call, I get the following error

    File "Q1.py", line 2, in <module>
    import matplotlib.pyplot as plt

    File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 24, in <module>
    import matplotlib.colorbar
  
    File "/usr/lib/pymodules/python2.7/matplotlib/colorbar.py", line 29, in <module>
    import matplotlib.collections as collections
  
    File "/usr/lib/pymodules/python2.7/matplotlib/collections.py", line 23, in <module>
    import matplotlib.backend_bases as backend_bases
  
    File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 50, in <module>
    import matplotlib.textpath as textpath
    
    File "/usr/lib/pymodules/python2.7/matplotlib/textpath.py", line 11, in <module>
    import matplotlib.font_manager as font_manager
    
    File "/usr/lib/pymodules/python2.7/matplotlib/font_manager.py", line 1356, in <module>
    _rebuild()
  
    File "/usr/lib/pymodules/python2.7/matplotlib/font_manager.py", line 1343, in _rebuild
    pickle_dump(fontManager, _fmcache)
    
    File "/usr/lib/pymodules/python2.7/matplotlib/font_manager.py", line 939, in pickle_dump
    with open(filename, 'wb') as fh:
  
    IOError: [Errno 2] No such file or directory: '/tmp/matplotlib-skarthikkrishna/fontList.cache'
    
From what I've been able to try, this problem seems to crop up because the code cannot access /tmp/ for writing onto it. The code runs just fine when I add a sudo tag before the execution command.

I'm curious as to why this is happening now. All the packages on my old and new laptop, especially the pyplot package are the same. I haven't missed out on installing any package, nor has there been any update that is not reflected in one of the systems. The code runs just fine in my old laptop. It refuses to work without sudo in the new one. I'd appreciate it if someone could help me out on that

**A few details, if they are relevant:**

Both systems run Ubuntu 14.04 LTS, last upgraded on 26th Dec, 2014.

I'm running Python 2.7.6 on both systems. [It's a mandated requirement for most of my coursework] 

Matplotlib version installed on both systems is 1.3.1

**EDIT :**

The output of `ls -ld /tmp/`  is

    drwxrwxrwt 4 root root 4096 Dec 27 18:45 /tmp/

The output of `ls -ld /tmp/matplotlib-skarthikkrishna` is

    ls: cannot access /tmp/matplotlib-skarthikkrishna: No such file or directory

The output remains the same with and without sudo, if at all that is relevant.

I used `sudo apt-get install python-matplotlib` to install matplotlib on both systems

The output of `python -c "import matplotlib; print(matplotlib.get_configdir())"` is

`/home/skarthikkrishna/.config/matplotlib`

The output of `python -c "import matplotlib;print(matplotlib.get_cachedir())"` is

`/tmp/matplotlib-skarthikkrishna`

All the permission have been set appropriately to the best of my knowledge, but I'm not very sure about that. The stackoverflow thread for this is located at 

https://stackoverflow.com/questions/27667641/matplotlib-requires-sudo-on-ubuntu-14-04

**Comment by WeatherGod** [comment] 2015-01-01 17:45
Are the user names the same on both systems? I also find it curious that it
is trying to put the font list cache in the /tmp directory. Are you getting
the same output for get_configdir() and get_cachedir() on both systems?

On Thu, Jan 1, 2015 at 11:17 AM, skarthikkrishna92 <notifications@github.com

**Comment by skarthikkrishna92** [comment] 2015-01-01 17:50
@WeatherGod  - I remember making sure that the user names on both systems were the same. I don't have access to the other system right now, so I can't be one hundred percent sure. I'll find the answers to both the questions and update the thread as soon as I get my hands on my old system

**Comment by efiring** [comment] 2015-01-01 18:25
In transferring your identity and files from one machine to another, it is not just a matter of user name and group name, but also of their respective numbers, UID and GID, set in the /etc/passwd and /etc/group files.
The fact that mpl is using /tmp means that it could not write to the expected location in your home directory, which is puzzling; but the second puzzle is why it apparently can't write to /tmp.
In any case, all this has nothing to do with matplotlib and Ubuntu 14.04 in general; it is a problem specific to your installation.

Try this: use the standard gui tool (whatever is provided with the desktop environment you are using) to create a new user account with some other name.  Then log out of your present account and into the new one, and try running something in matplotlib.  You should find that it is no longer using /tmp, but a newly-created subdirectory in your home directory.

I think the cache dir should be ~/.cache, but this can be changed depending on your environment variables.  You can see what it is in your test user account, and then check to see if this can be created and is writable in your real user account.

**Comment by cel4** [comment] 2015-01-01 19:28
@efiring, if that is the issue, `ls -ld /home/skarthikkrishna/.config/matplotlib`  should show user and group ids instead of names. If copied from a root account, maybe `root` still owns this directory? Anyway, `chown -R <username>: /home/skarthikkrishna/.config/matplotlib`  should fix this issue in this case.

What really confused me is, that writing to the folder in `tmp` is apparently not possible. the tmp directory has full permissions: `drwxrwxrwt`. No matter what user you are, you really should be able to create a folder there. Does matplotlib try to create the temp folder if it does not exist?

Anyway it might be a good idea to catch this case and report permission issues. In my opinion, if matplotlib cannot write to its config directory, this is probably always a bad sign. The fallback to the tmp directory is fine, but an explicit warning about permission issues might be a good idea.

**Comment by pelson** [comment] 2015-01-04 10:47
> Anyway it might be a good idea to catch this case and report permission issues. In my opinion, if matplotlib cannot write to its config directory, this is probably always a bad sign. The fallback to the tmp directory is fine, but an explicit warning about permission issues might be a good idea.

I'd be :+1: on that idea. I'll close this original issue, but if you wanted to get involved and submit a PR for the warning, I think it would be a welcome addition.

Thanks!

**Closed by pelson** 2015-01-04 10:47 UTC
Labels: can't fix

**Comment by skarthikkrishna92** [comment] 2015-01-10 02:04
@cel4 - Sorry I couldn't get back earlier. I've tried taking control of the config folder using `chown`. While it doesn't throw up any errors, I still find that I require sudo to run any code that requires matplotlib

**Comment by aberaud** [comment] 2015-07-13 23:18
I had the issue, fixed it by deleting `$HOME/.cache/matplotlib` that happened to be owned by root.

**Comment by hhfei** [comment] 2015-09-30 06:21
@aberaud +1 works for me

**Comment by anntzer** [comment] 2018-03-12 18:59
Can't reproduce:
```
$ sudo su -s /bin/bash nobody
[nobody@antony1 antony]$ python -c 'import matplotlib; print(matplotlib.get_home(), matplotlib.get_configdir(), matplotlib.get_cachedir())'
/ /tmp/matplotlib-_yu6e_ak /tmp/matplotlib-_yu6e_ak
```

**Comment by jessecooper** [comment] 2018-03-12 20:36
I got it to work with the service account. Seemed to be a group supplemental  I needed to add to that service account.
