### ISSUE TITLE
GTK Warning

### ISSUE THREAD

**Issue by JLCCI** [matplotlib/matplotlib#6846] opened 2016-07-27 08:24 UTC
Thanks for providing the great package.

I have the newest version of python 3 and matplotlib installed through pip. Not sure why by everytime I use even the simplest script I get this error.

(test.pl:4086): Gtk-WARNING **: Theme parsing error: gtk-dark.css:67:29: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version

Even as simple as the below triggers the error:

from matplotlib import pyplot as plt
plot_kd = plt.figure()

Any advice on how to fix this? I am using Arch Linux with Gnome Desktop Enviroment.

Many thanks!

**Comment by jenshnielsen** [comment] 2016-07-27 08:33
As far as I know there is nothing in matplotlib which has a reference to `gtk-dark.css` are you sure this is not caused by by a GTK theme that you have selected somewhere else?

What happens if you import GTK3 in a regular python shell without calling matplotlib

```python
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk, Gdk, GObject, GLib
```

On OSX that results in 
```
>>> import gi
>>> gi.require_version("Gtk", "3.0")
>>> from gi.repository import Gtk, Gdk, GObject, GLib
2016-07-27 09:32:09.569 Python[12709:3189111] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
```
which it then clearly a bug in GTK3 and not in Maplotlib (The same warning is triggered when you plot in the GTK3Agg backend)

**Comment by JLCCI** [comment] 2016-07-27 08:55
Hi Jens,

Thanks for your fast response. I tried the code you provided and it imported without a problem.

I guess it is possible that the error is caused by something in my theme settings, I will investigate.

**Comment by jenshnielsen** [comment] 2016-07-27 09:02
I guess it's also possible that the warning is first triggered when the main gtk loop is executed. Matplotlib runs `Gtk.main()` but testing that without matplotlib is more complicated.

I would suggest searching for where `gtk-dark.css` is on your filesystem and figure out if if belongs to a specific package

**Comment by tacaswell** [comment] 2016-07-28 12:33
Closing as likely not a bug in mpl.

attn @OceanWolf @fariza as the local gtk experts.

Given that you are on Arch you probably also have a bleeding edge version of gtk.

**Closed by tacaswell** 2016-07-28 12:33 UTC

**Comment by OceanWolf** [comment] 2016-07-28 13:22
Interesting error message... do you use the new toolbar?  I.e. do you have the rcParam ``toolbar`` set as ``toolmanager``?

As far as I know, ``GtkStatusbar`` only gets used by the new ``toolmanager`` (we have almost finished it, but not quite, hopefully in a few months).

**Comment by OceanWolf** [comment] 2016-07-28 13:35
But yes, I agree with conclusion, it sounds like a theme problem to me.   I don't know if the example that @jenshnielsen gave was complete enough as it only loaded the packages and didn't open a window or anything, where such a themeing problem would arise.

**Comment by jenshnielsen** [comment] 2016-07-28 13:40
@OceanWolf I fully agree I was hoping that it might happen early and I don't know enough GTK to be able to write a full app on the fly

**Comment by OceanWolf** [comment] 2016-07-28 13:43
I like to put in print() commands (I would say "statements", but python3 has changed that), that way one should see where abouts the warning occurs, i.e. which command triggers it.  Or does a way exist to instruct python to treat warnings as errors?

**Comment by OceanWolf** [comment] 2016-07-28 14:09
But yes, I suggest taking the issue up with Arch if you use the default theme (or even a theme that has come from one of your repositories), otherwise with the people you got the theme from.  Of course don't forget to try searching for similar problems.

@fariza Do you have anything to add to that?

**Comment by QuLogic** [comment] 2016-07-28 14:26
> I like to put in print() commands (I would say "statements", but python3 has changed that)

Well, they are still statements; they just happen to contain function calls instead.

> Or does a way exist to instruct python to treat warnings as errors?

[python -W](https://docs.python.org/3/using/cmdline.html#cmdoption-W)

**Comment by JLCCI** [comment] 2016-07-29 01:47
Thanks a lot for exploring the issue. I will try to investigate though I'm new to GTK and matplotlib.

Please feel free to send me any code for testing if you ever want to dig deeper into this.

Many thanks for your work on the library!
