### ISSUE TITLE
Increase of Computation time from 2.1.0 to 2.1.1

### ISSUE THREAD

**Issue by MichaelLutter** [matplotlib/matplotlib#10162] opened 2018-01-04 16:42 UTC
### Bug report

Matplotlib 2.1.1 creates severe performance for interactive plotting compared to 2.1.0.  If I update the plots using the format below 2.1.0 generates a smooth interactive plot, while the computation time for 2.1.1 increases by a factor of 20. This behaviour has been observed on MacOS & Ubuntu.

**Code for reproduction**
```python
import matplotlib as mp
mp.use("Qt5Agg")

import matplotlib.pyplot as plt
import numpy as np
import time

if __name__ == "__main__":

    print "Matplotlib Version:          \t{0}".format(mp.__version__)
    print "Matplotlib Backend:          \t{0}".format(mp.get_backend())

    n = 100
    x = np.linspace(0., 2. * np.pi)
    p = np.linspace(0., 4. * np.pi, n)
    y = np.sin(x)

    plt.ion()
    fig = plt.figure()
    ax = fig.add_subplot(111)
    line = ax.plot(x, y)

    t0 = time.time()
    for i in xrange(n):

        line[0].set_ydata(np.sin(x + p[i]))
        fig.canvas.update()
        fig.canvas.flush_events()

    t_for = time.time() - t0
    t_update = t_for / float(n)

    print "Computation Time n-Updates:  \t{0:.3f}s".format(t_for)
    print "Computation Time per Update: \t{0:.3f}s".format(t_update)
    plt.ioff()
```

**Outcome Matplotlib 2.1.0** 
```
Matplotlib Version:          	2.1.0
Matplotlib Backend:          	Qt5Agg
Computation Time n-Updates:  	3.284s
Computation Time per Update: 	0.033s
```

**Outcome Matplotlib 2.1.1** 
```
Matplotlib Version:          	2.1.1
Matplotlib Backend:          	Qt5Agg
Computation Time n-Updates:  	69.129s
Computation Time per Update: 	0.691s
```

**Matplotlib version**
  * Operating system: MacOs 10.13.2  & Ubuntu 16.04 
  * Matplotlib version: 2.1.0 & 2.1.1
  * Matplotlib backend: Qt5Agg
  * Python version: 2.7.13
  * Other libraries: None

The matplotlib packages of both versions were installed using pip.

**Comment by jklymak** [comment] 2018-01-04 20:09
I can confirm this on my machine.  Not sure what changed, or if the code above is the "best" way to animate a plot, but it definitely is a lot slower in 2.1.1

If I use "MacOSX" the code doesn't display the figure at all.  

If I use QtAgg, I get around 0.098s/update, which is slower, but not anywhere near as bad as Qt5Agg.

**Comment by jklymak** [comment] 2018-01-04 20:13
Manually bisecting, the slowdown appears to be caused by https://github.com/matplotlib/matplotlib/commit/9b8a944db954c8240e14413e517e1b781881b80b#diff-24fdb85343951b7d9bd270c47d6abe8f  ping @tacaswell...

**Comment by jklymak** [comment] 2018-01-04 20:26
Note that #10142 (just merged) does *not* fix this performance issue.

**Comment by jklymak** [comment] 2018-01-04 20:38
@MichaelLutter if you had the ability to test #10164 that *should* fix the issue for you.  Whether it breaks other things or not, I'm not sure...

**Comment by tacaswell** [comment] 2018-01-05 00:43
@MichaelLutter You don't need `plti.ion()` in this case (it really only is useful if you are trying to integrate figures with a command prompt, see https://github.com/matplotlib/matplotlib/pull/4779 (can you provide any feedback if that text is helpful?)).

Does using `draw_idle` instead of `update` help at all (with the current v2.1.x branch)?

**Comment by MichaelLutter** [comment] 2018-01-05 09:20
@jklymak  #10164 fixes the issue for me. I don't know if this is the "best" solution to animate a plot but it is the only solution I got to work on MacOS & Ubuntu. IMO pushing real-time updates from computation to the plots is missing in Matplotlib. 

@tacaswell  Well, theoretically I may not need ```plt.ion()``` but practically I do, because this is the only working solution, that I am aware of, to displaying the figure. An alternative would be to use ```plt.show(block=False)```, however this does not show the figure in MacOS & Ubuntu. 

#4779  is a good start as the event-loop as well as best practice to update data is quite undocumented. However, it is still missing quite a bit. Currently, I just used trial and error to get things working. For example I tried out ```plt.pause()```, ```fig.canvas.draw(), fig.canvas.flush_events()``` and  ```fig.canvas.update(), fig.canvas.flush_events()``` and came to the conclusion that the last works empirically the most efficient.

**Comment by tacaswell** [comment] 2018-01-15 22:42
@MichaelLutter Can you check on current 2.1.x?  This is what I get:

```
16:59 $ python /tmp/loop.py 
Matplotlib Version:     2.1.1.post48+gd9d52899b
Matplotlib Backend:     Qt5Agg
Computation Time n-Updates:     1.008s
Computation Time per Update:    0.010s
```

-----

```python
import matplotlib as mp
mp.use("Qt5Agg")

import matplotlib.pyplot as plt
import numpy as np
import time

if __name__ == "__main__":

    print(f"Matplotlib Version:\t{mp.__version__}")
    print(f"Matplotlib Backend:\t{mp.get_backend()}")

    n = 100
    x = np.linspace(0., 2. * np.pi)
    p = np.linspace(0., 4. * np.pi, n)
    y = np.sin(x)

    plt.ion()
    fig = plt.figure()
    ax = fig.add_subplot(111)
    line = ax.plot(x, y)

    t0 = time.time()
    for i in range(n):

        line[0].set_ydata(np.sin(x + p[i]))
        fig.canvas.update()
        fig.canvas.flush_events()

    t_for = time.time() - t0
    t_update = t_for / float(n)

    print(f"Computation Time n-Updates:  \t{t_for:.3f}s")
    print(f"Computation Time per Update: \t{t_update:.3f}s")
    plt.ioff()

```

**Comment by jklymak** [comment] 2018-01-15 22:47
Oh huh, its way faster now.  What changed?  master from a couple of days ago was still slow...

```
Matplotlib Version:	2.1.1.post1068+gb511bb250
Matplotlib Backend:	Qt5Agg
Computation Time n-Updates:  	2.461s
Computation Time per Update: 	0.025s
```

**Comment by tacaswell** [comment] 2018-01-15 23:28
For reference:

```
18:23 $ python /tmp/loop.py 
Matplotlib Version:     2.1.1.post1068+gb511bb250
Matplotlib Backend:     Qt5Agg
Computation Time n-Updates:     1.002s
Computation Time per Update:    0.010s
```

```
18:25 $ python /tmp/loop.py 
Matplotlib Version:     2.1.1
Matplotlib Backend:     Qt5Agg
Computation Time n-Updates:     43.489s
Computation Time per Update:    0.435s
```

I think we can close this with no further action.

**Comment by jklymak** [comment] 2018-01-17 18:15
I'm going to close this, as confirmed fixed.  Please re-open if 2.1.2 doesn't fix things for you...

**Closed by jklymak** 2018-01-17 18:15 UTC
Labels: GUI/Qt, confirmed bug
