### ISSUE TITLE
[Bug]: savefig creates blank EPS files

### ISSUE THREAD

**Issue by dbishel** [matplotlib/matplotlib#25069] opened 2023-01-24 12:53 UTC
### Bug summary

When using plt.savefig() or plt.gcf().savefig() to save an active figure in EPS format, the resulting file is blank. The same commands produce the correct image when saving to PNG format. Error occurs in both Spyder and Jupyter Notebooks.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

plt.figure()
plt.plot(1,1,'x')
plt.savefig('test.png', fmt='png')
plt.savefig('test.eps', fmt='eps')
```

### Actual outcome

PNG file:
![test](https://user-images.githubusercontent.com/56979209/214295963-ec8e2862-51a0-4fca-9632-605a39e1fec9.png)

The EPS file cannot be uploaded, but is just a white rectangle of the same dimensions as the PNG.

### Expected outcome

EPS file should look identical to the PNG.

### Operating system

OSX Ventura 13.1

### Matplotlib Version

3.5.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.10.4

### Jupyter version

3.3.4

### Installation

conda

**Comment by dstansby** [comment] 2023-01-24 16:56
I've just run this (thanks for the easy-to-run code!), and get a good .eps file that shows a plot as expected. Could you upgrade to a more recent version of Matplotlib (3.6), and see if it's still an issue for you?

**Comment by jklymak** [comment] 2023-01-24 17:07
I'm guessing you have auto layout turned on, and this is a duplicate of https://github.com/matplotlib/matplotlib/issues/21930?  I'm going to close, but if this is not a duplicate, please comment and we can re-open.

**Closed by jklymak** 2023-01-24 17:07 UTC
Labels: status: needs clarification

**Comment by dbishel** [comment] 2023-01-24 18:22
@jklymak Setting auto layout to False fixed the issue. Thank you!

**Comment by jklymak** [comment] 2023-01-24 18:23
Note that the bug was fixed but you will need a more recent Matplotlib.
