### ISSUE TITLE
interpreter freezes while using matplotlib and a projector

### ISSUE THREAD

**Issue by mmckerns** [matplotlib/matplotlib#12977] opened 2018-12-11 17:03 UTC
### Bug report

**Bug summary**

Python interpreter randomly freezes when using `matplotlib` in presentation mode (i.e. with a projector).  It typically happens after minutes to hours of presenting, and is seemingly random when it occurs.  It's a rare corner case, only experienced when projecting.

**Code for reproduction**

Can be reproduced by importing `matplotlib`, then create a plot, then keep working until the interpreter will lock up (i.e. freeze).  I realize this is a hard-to-reproduce corner case, as you have to be presenting... but it is almost guaranteed to occur if presenting using `matplotlib` in a python interpreter for longer than an hour or two.

**Actual outcome**

Python interpreter is frozen (i.e. cannot type anything).  Interpreter needs to be killed, however, if left alone for hours, sometimes the interpreter "unfreezes" itself.

I'm only reporting this now, as I've discovered a workaround.  No idea why it works, it's magic... but if the interpreter freezes, it can be unfrozen instantly by clicking on the "python" icon (i.e. the rocket) that shows up in dock when matplotlib is imported.

**Matplotlib version**

I have experienced this behavior for at least five years, across several versions of `matplotlib`, installed with all sorts of methods (`pip`,`edm`, `conda`, `brew`, `macports`, using the version on `git`, etc.).  I've only experienced it on a mac (several different versions of OS), and several different versions of python (2.7, 3.5, 3.6), and  only while presenting.

**Comment by WeatherGod** [comment] 2018-12-11 17:41
are you using the python interpreter or ipython/jupyter?

I have given 5 scipy tutorials on matplotlib (~4 hours long), and have
co-chaired the tutorial committee for SciPy for the past 3 years, and this
issue has never come up as far as I am aware.

My immediate suspicion is that if you are using ipython/jupyter, then you
may be having an accumulation of objects taking up memory and you are swap
thrashing. ipython does not automatically let objects get garbage-collected
because it stores the results of cells in a special object that just grows.

**Comment by mmckerns** [comment] 2018-12-11 18:08
@WeatherGod: I realize that it's been used in tutorials for several hours at SciPy and etc.  I typically see it when I'm teaching an all day workshop... i.e. 8-9 hours.  It's pretty much a guarantee then.
I've never experienced it using ipython/jupyter, as I typically present out of a basic python interpreter that has been augmented with a `.python` file that uses `rcompleter`.

It's not necessarily due to plotting large objects, but yes, it could be do to memory and swap thrashing, as I'm using a session for several hours.  That's actually what I figured it might be... but since the workaround is to **click on the python rocket icon in the dock**, that's where I thought, hmm.... maybe not.  I'm typically giving an "all-day tutorial"... so the data I'm using is typically just some small examples, so again, another point against it being a memory issue.  Next time I experience it, I'll quickly check my memory before "unfreezing" it.

**Comment by WeatherGod** [comment] 2018-12-11 18:22
hmm, good point. Well, the other interesting data point is that you are on
a mac. Which backend are you using? If it is the macosx backend, then
perhaps there is some sort of issue with the event loop? The macosx backend
has a completely different eventloop paradigm than all the other gui
backends due to design decisions for macs.

**Comment by mmckerns** [comment] 2018-12-11 18:48
yep, I'm using the MacOSX backend.

I've pasted a copy of a session from over a year ago where it froze up over the course of two hours... I'm not doing anything that related to memory, or otherwise interesting or weird.  The only other thing that's relevant to know is that I have MS powerpoint open, which is a memory hog.  Come to think of it, it could be an issue with the interaction with MS powerpoint (as opposed to the projector), as creating a plot with `matplotlib` can cause the powerpoint window to resize.  I know... I know... it sounds totally crazy. 

```
>$ python
Python 3.5.4 (default, Aug 12 2017, 14:31:52) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> t2 = pd.date_range('2017-09-21', periods=4, freq='MS')
>>> s0 = pd.Series([1,2,3,4], index=t2)
>>> s0
2017-10-01    1
2017-11-01    2
2017-12-01    3
2018-01-01    4
Freq: MS, dtype: int64
>>> s0.loc[pd.to_datetime('2017-10-01')]
1
>>> s0.loc[pd.to_datetime('2017-10')]
1
>>> s0.loc[pd.to_datetime('2017')]
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/indexing.py", line 1434, in _has_valid_type
    error()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/indexing.py", line 1429, in error
    (key, self.obj._get_axis_name(axis)))
KeyError: 'the label [2017-01-01 00:00:00] is not in the [index]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/indexing.py", line 1328, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/indexing.py", line 1551, in _getitem_axis
    self._has_valid_type(key, axis)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/indexing.py", line 1442, in _has_valid_type
    error()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/indexing.py", line 1429, in error
    (key, self.obj._get_axis_name(axis)))
KeyError: 'the label [2017-01-01 00:00:00] is not in the [index]'
>>> s0.loc[pd.to_datetime('2017-10-01')]
1
>>> s0.loc['2017-10-01']
1
>>> s0.loc['2017']
2017-10-01    1
2017-11-01    2
2017-12-01    3
Freq: MS, dtype: int64
>>> s0.loc['2017-10']
2017-10-01    1
Freq: MS, dtype: int64
>>> 
>>> t2 = pd.date_range('2017-09-21', periods=8, freq='15D')
>>> t2
DatetimeIndex(['2017-09-21', '2017-10-06', '2017-10-21', '2017-11-05',
               '2017-11-20', '2017-12-05', '2017-12-20', '2018-01-04'],
              dtype='datetime64[ns]', freq='15D')
>>> s0 = pd.Series([1,2,3,4,5,6,7,8], index=t2)
>>> s0
2017-09-21    1
2017-10-06    2
2017-10-21    3
2017-11-05    4
2017-11-20    5
2017-12-05    6
2017-12-20    7
2018-01-04    8
Freq: 15D, dtype: int64
>>> s0['2017-10']
2017-10-06    2
2017-10-21    3
Freq: 15D, dtype: int64
>>> import pytz 
>>> 
>>> s0
2017-09-21    1
2017-10-06    2
2017-10-21    3
2017-11-05    4
2017-11-20    5
2017-12-05    6
2017-12-20    7
2018-01-04    8
Freq: 15D, dtype: int64
>>> s0.index
DatetimeIndex(['2017-09-21', '2017-10-06', '2017-10-21', '2017-11-05',
               '2017-11-20', '2017-12-05', '2017-12-20', '2018-01-04'],
              dtype='datetime64[ns]', freq='15D')
>>> s0.index.year
Int64Index([2017, 2017, 2017, 2017, 2017, 2017, 2017, 2018], dtype='int64')
>>> s0.index.month
Int64Index([9, 10, 10, 11, 11, 12, 12, 1], dtype='int64')
>>> s0.index.month > 10
array([False, False, False,  True,  True,  True,  True, False], dtype=bool)
>>> s0[s0.index.month > 10]
2017-11-05    4
2017-11-20    5
2017-12-05    6
2017-12-20    7
Freq: 15D, dtype: int64
>>> map(lambda x:x*x, [1,2,3,4,5])
<map object at 0x103c7b4e0>
>>> list(map(lambda x:x*x, [1,2,3,4,5]))
[1, 4, 9, 16, 25]
>>> s0
2017-09-21    1
2017-10-06    2
2017-10-21    3
2017-11-05    4
2017-11-20    5
2017-12-05    6
2017-12-20    7
2018-01-04    8
Freq: 15D, dtype: int64
>>> s0.apply(lambda x:x*x)
2017-09-21     1
2017-10-06     4
2017-10-21     9
2017-11-05    16
2017-11-20    25
2017-12-05    36
2017-12-20    49
2018-01-04    64
Freq: 15D, dtype: int64
>>> s0
2017-09-21    1
2017-10-06    2
2017-10-21    3
2017-11-05    4
2017-11-20    5
2017-12-05    6
2017-12-20    7
2018-01-04    8
Freq: 15D, dtype: int64
>>> s0gb = s0.groupby(lambda x:x.month)
>>> s0gb.groups
{1: DatetimeIndex(['2018-01-04'], dtype='datetime64[ns]', freq='15D'), 10: DatetimeIndex(['2017-10-06', '2017-10-21'], dtype='datetime64[ns]', freq='15D'), 11: DatetimeIndex(['2017-11-05', '2017-11-20'], dtype='datetime64[ns]', freq='15D'), 12: DatetimeIndex(['2017-12-05', '2017-12-20'], dtype='datetime64[ns]', freq='15D'), 9: DatetimeIndex(['2017-09-21'], dtype='datetime64[ns]', freq='15D')}
>>> s0gb.mean()
1     8.0
9     1.0
10    2.5
11    4.5
12    6.5
dtype: float64
>>> s0gb[:2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/base.py", line 354, in __getitem__
    raise KeyError("Column not found: %s" % key)
KeyError: 'Column not found: slice(None, 2, None)'
>>> s0gb.iloc[:2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/groupby.py", line 548, in __getattr__
    return self._make_wrapper(attr)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/groupby.py", line 562, in _make_wrapper
    raise AttributeError(msg)
AttributeError: Cannot access callable attribute 'iloc' of 'SeriesGroupBy' objects, try using the 'apply' method
>>> s0gb.apply(lambda x:x[:2])
2017-09-21    1
2017-10-06    2
2017-10-21    3
2017-11-05    4
2017-11-20    5
2017-12-05    6
2017-12-20    7
2018-01-04    8
Freq: 15D, dtype: int64
>>> d1 = pd.DataFrame({'s1':dict(a=1,b=2,c=4), 's2':dict(a=2,b=2,c=4,d=3)})
>>> d1
    s1  s2
a  1.0   2
b  2.0   2
c  4.0   4
d  NaN   3
>>> d1['s3'] = [True, False, False, True]
>>> d1
    s1  s2     s3
a  1.0   2   True
b  2.0   2  False
c  4.0   4  False
d  NaN   3   True
>>> gb = d1.groupby('s3')
>>> gb
<pandas.core.groupby.DataFrameGroupBy object at 0x103c7ba20>
>>> gb.mean()
        s1   s2
s3             
False  3.0  3.0
True   1.0  2.5
>>> gb.std()
             s1        s2
s3                       
False  1.414214  1.414214
True        NaN  0.707107
>>> import numpy as np
>>> gb.agg([np.mean, np.std])
        s1             s2          
      mean       std mean       std
s3                                 
False  3.0  1.414214  3.0  1.414214
True   1.0       NaN  2.5  0.707107
>>> m = _.columns
>>> m
MultiIndex(levels=[['s1', 's2'], ['mean', 'std']],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])
>>> m[0]
('s1', 'mean')
>>> m[1]
('s1', 'std')
>>> m[2]
('s2', 'mean')
>>> m[3]
('s2', 'std')
>>> q = gb.agg([np.mean, np.std])
>>> q
        s1             s2          
      mean       std mean       std
s3                                 
False  3.0  1.414214  3.0  1.414214
True   1.0       NaN  2.5  0.707107
>>> q[('s1','mean')]
s3
False    3.0
True     1.0
Name: (s1, mean), dtype: float64
>>> 
>>> # parse_dates:   
... # [0,1]
... # [[0,1,2],5]
... 
>>> # date_parser:
... # date_parser takes input from parse_dates, if columns are specified
... 
>>> 
>>> d1
    s1  s2     s3
a  1.0   2   True
b  2.0   2  False
c  4.0   4  False
d  NaN   3   True
>>> d1.head()
    s1  s2     s3
a  1.0   2   True
b  2.0   2  False
c  4.0   4  False
d  NaN   3   True
>>> d1.head(2)
    s1  s2     s3
a  1.0   2   True
b  2.0   2  False
>>> d1.h
```

**Comment by timhoffm** [comment] 2020-07-16 20:03
Closing as non-actionable. You are welcome to reopen if the problem still exists. In that case, please try find a reproducible way to induce the freeze.

**Closed by timhoffm** 2020-07-16 20:03 UTC
Labels: GUI/osx

**Comment by mmckerns** [comment] 2020-07-26 11:02
I've noted that the behavior still persists - however, I've found that a mouse-click on the python icon in the dock after matplotlib freezes will trigger an "unfreezing".  So, there's a workaround.

**Comment by tacaswell** [comment] 2020-07-27 05:38
See https://github.com/ipython/ipython/issues/4431/ and the links there in.

I suspect the issue is that OSX has decided, that because we show a GUI window that Python is a GUI application.  If you don't touch the GUI for long enough the operating system decides to put the program to sleep (take a "nap") which manifest as a freeze.  By clicking on the icon in the doc you are probably forcing it back awake.  My guess is that the cases where you don't touch the GUI figure for long enough and hit the other conditions that make App Nap likely only when presenting....
