### ISSUE TITLE
Memory hole when using Cursor widget with Qt (PySide) and useblit=True on Windows

### ISSUE THREAD

**Issue by dryo** [matplotlib/matplotlib#4283] opened 2015-03-26 19:45 UTC
I'm using matplotlib with PySide and I managed to crash the program by moving the mouse. ;)

I made a minimal example (see below) that triggers the problem. Just run it and move your mouse over the canvas keeping the memory consumption under observation. You will see significant increase when moving the mouse.

This only happens when setting `useblit=True` in the # MARKed line.

```python
import sys
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.widgets import Cursor
from PySide import QtGui


class MyApp(QtGui.QMainWindow):

    def __init__(self):
        # Init the object as a QMainWindow
        super().__init__()

        # create figure and plot something
        fig = Figure()
        ax = fig.add_subplot(111)
        ax.plot([1, 5, 2, 3])
        canvas = FigureCanvas(fig)
        cursor = Cursor(ax, useblit=True)  # MARK

        # set central widget of main window to the canvas of the figure
        self.setCentralWidget(canvas)

    def run(self):
        self.show()
        # enter main loop
        myApp.exec_()


if __name__ == '__main__':
    myApp = QtGui.QApplication(sys.argv)
    MyApp().run()
```

Some version info:
* Windows 7 64bit
* Python 3.4.2 64bit
* Matplotlib 1.4.3 64bit
* PySide 1.2.2 (installed via pip)

**Comment by tacaswell** [comment] 2015-04-12 02:30
I can reproduce this with pyside + python 3.4 + master but can not reproduce with PyQt4v2 which makes me think that this is reall a PySide bug, not a mpl bug...

**Comment by tacaswell** [comment] 2015-04-12 02:34
@mfitzp any insight on this?

**Comment by tacaswell** [comment] 2015-04-12 02:43
And the cursor does not seem to work at all with PySide on py2k.  Modified the test as such:

```python
import sys
import matplotlib
matplotlib.rcParams['backend.qt4'] = 'PySide'
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.widgets import Cursor
from PySide import QtGui


class MyApp(QtGui.QMainWindow):

    def __init__(self):
        # Init the object as a QMainWindow
        super(MyApp, self).__init__()

        # create figure and plot something
        fig = Figure()
        ax = fig.add_subplot(111)
        ax.plot([1, 5, 2, 3])
        canvas = FigureCanvas(fig)
        cursor = Cursor(ax, useblit=False)  # MARK

        # set central widget of main window to the canvas of the figure
        self.setCentralWidget(canvas)

    def run(self):
        self.show()
        # enter main loop
        myApp.exec_()


if __name__ == '__main__':
    myApp = QtGui.QApplication(sys.argv)
    MyApp().run()

```

**Comment by mfitzp** [comment] 2015-04-14 11:13
Can confirm (also on Windows + PySide). I've tracked the error all the way up from `self.canvas.blit(self.ax.bbox)` in the `Cursor` to `self.repaint(l, self.renderer.height-t, w, h)` then onto `FigureCanvasQTAggBase.paintEvent` (in `backend_qt5agg.py`) where the specific line that appears to cause the leak is:

            qImage = QtGui.QImage(stringBuffer, w, h,
                                  QtGui.QImage.Format_ARGB32)

My first guess would be that the qImage is not being discarded by PySide once it falls out of scope (perhaps because it's passed into the QPixmap below.

**Comment by mfitzp** [comment] 2015-04-20 20:12
Here is a very relevant bug on the PySide tracker [PYSIDE-140](https://bugreports.qt.io/browse/PYSIDE-140) which reports the same memory leak on the same platform (Windows) and Python 3. The reporter offers a temporary workaround that involves manually adjusting the reference counter.

I'll test this workaround with `backend_qt5agg.py` tomorrow and report back (not sure this is something we will want to apply to the code, but worth offering a temporary patch for completeness sake).

@tacaswell Since this is an upstream bug should it be closed?

**Comment by tacaswell** [comment] 2015-04-20 20:46
This is stirring memories that we used to have this work around in the
code, it may have gotten lost in the reactor for qt5.  This is enough of a
problem that we should patch over it locally.

**Comment by mfitzp** [comment] 2015-04-24 14:36
The fix appears (with some small modifications)  - 

            rcount = ctypes.c_long.from_address(id(stringBuffer)).value # Get the reference count of self.data.
            qImage = QtGui.QImage(stringBuffer, w, h, QtGui.QImage.Format_ARGB32)
            ctypes.c_long.from_address(id(stringBuffer)).value=rcount

Since the stringBuffer is only used in this function as a temporary variable (so `rcount` is always `1`) we can also simplify this to - 

            qImage = QtGui.QImage(stringBuffer, w, h, QtGui.QImage.Format_ARGB32)
            ctypes.c_long.from_address(id(stringBuffer)).value=1

I'll work this into a PR.

@tacaswell Is the issue with the cursor not working with `useblit=False` a different bug (i.e. no memory leak)?

**Comment by tacaswell** [comment] 2015-04-24 14:39
Yes, cursor not working with out blit is a separate issue.

**Comment by mfitzp** [comment] 2015-06-10 15:59
Closed by https://github.com/matplotlib/matplotlib/pull/4377

@tacaswell I opened a separate issue (#4513) for the cursor not working at all with `blit=False` on PySide

**Closed by mfitzp** 2015-06-10 15:59 UTC
Labels: confirmed bug, GUI/Qt, widgets/UI
