### ISSUE TITLE
Colorbars contain no colors when created on ppc64 (big-endian)

### ISSUE THREAD

**Issue by AdamWill** [matplotlib/matplotlib#7788] opened 2017-01-10 19:44 UTC
Recently I've been looking at errors in the matplotlib test suite when building on Fedora's ppc64 arch, which is big-endian. I've sent a couple of PRs:

https://github.com/matplotlib/matplotlib/issues/7768
https://github.com/matplotlib/matplotlib/pull/7781

to fix some integer type problems in the freetype wrapper, which cuts the error count down from hundreds to 38, but I don't think I can fix the remaining issues, so I'm filing tickets for them.

Several of the remaining failed tests fall into the general category 'colorbar generation does not work right at all' - the following tests all fail:

matplotlib.tests.test_axes.test_contour_colorbar.test
matplotlib.tests.test_colorbar.test_colorbar_closed_patch.test
matplotlib.tests.test_colorbar.test_colorbar_extension_length.test
matplotlib.tests.test_colorbar.test_colorbar_extension_shape.test
matplotlib.tests.test_colorbar.test_colorbar_positioning.test
matplotlib.tests.test_colorbar.test_colorbar_single_scatter.test
matplotlib.tests.test_colorbar.test_gridspec_make_colorbar.test

All the failures are image comparison failures. I'll attach some of the failures here; the failure mode seems to be basically the same in all cases. The colorbar box is drawn the right size and shape and in the right position and with the right marks, but no actual colors are drawn inside the box - it's just white inside.

This occurs building from the 2.0.0rc2 source using the Fedora spec file, numpy will be 1.11.2 I believe. No warning messages are logged during the test run that relate to this issue (I confirmed by cutting the test run down to just `test_colorbar_tests` and when I do that, there are no error/warning messages logged).

cbar_locationing GOT: ![cbar_locationing](https://cloud.githubusercontent.com/assets/916551/21821831/d2510656-d729-11e6-96b3-a7433e83d95e.png)
cbar_locationing EXPECTED: ![cbar_locationing-expected](https://cloud.githubusercontent.com/assets/916551/21821828/d24b3096-d729-11e6-8f7e-042acffa6f7c.png)
cbar_sharing GOT: ![cbar_sharing](https://cloud.githubusercontent.com/assets/916551/21821829/d24d0150-d729-11e6-9834-3726fdb4b70b.png)
cbar_sharing EXPECTED: ![cbar_sharing-expected](https://cloud.githubusercontent.com/assets/916551/21821833/d2541990-d729-11e6-8cc3-80f8ad6c2422.png)
cbar_with_orientation GOT: ![cbar_with_orientation](https://cloud.githubusercontent.com/assets/916551/21821832/d25224c8-d729-11e6-8675-007e5ffe4c40.png)
cbar_with_orientation EXPECTED: ![cbar_with_orientation-expected](https://cloud.githubusercontent.com/assets/916551/21821830/d2506ae8-d729-11e6-9b16-886f8c629947.png)
cbar_with_subplots_adjust GOT: ![cbar_with_subplots_adjust](https://cloud.githubusercontent.com/assets/916551/21821834/d25d7cf6-d729-11e6-94ef-82375b34af31.png)
cbar_with_subplots_adjust EXPECTED: ![cbar_with_subplots_adjust-expected](https://cloud.githubusercontent.com/assets/916551/21821835/d260075a-d729-11e6-8f22-0110eef4e674.png)

That's not all of them, but I guess enough to get the idea.

@QuLogic (who seems interested in this area)

**Comment by AdamWill** [comment] 2017-01-10 20:31
There are also failures in two colormesh tests which look a lot like the same thing:

matplotlib.tests.test_axes.test_pcolormesh_datetime_axis.test
matplotlib.tests.test_axes.test_pcolormesh.test

Images:

pcolormesh GOT: ![pcolormesh](https://cloud.githubusercontent.com/assets/916551/21823602/9813909c-d730-11e6-9f1f-f91ae918e66e.png)
pcolormesh EXPECTED: ![pcolormesh-expected](https://cloud.githubusercontent.com/assets/916551/21823603/9813e59c-d730-11e6-83d8-a80642c18bec.png)
pcolormesh_datetime_axis GOT: ![pcolormesh_datetime_axis](https://cloud.githubusercontent.com/assets/916551/21823606/98148d94-d730-11e6-90f7-d696712d8c32.png)
pcolormesh_datetime_axis EXPECTED: ![pcolormesh_datetime_axis-expected](https://cloud.githubusercontent.com/assets/916551/21823604/9813fbc2-d730-11e6-92f5-31d71e35a036.png)

It's interesting that just *one* of the figures in pcolormesh shows up OK, but the other two don't...

**Comment by WeatherGod** [comment] 2017-01-10 21:32
colorbars are implemented using pcolormesh, iirc. So that would help track
down the source of the bug.

**Comment by WeatherGod** [comment] 2017-01-10 21:35
The one pcolormesh that showed up in your tests had gouraud shading turned
on. Interesting.

**Comment by QuLogic** [comment] 2017-01-10 21:35
The last one is different because it uses gouraud shading which uses a differeng code path. I think the problem is in the Agg draw_quad_mesh which parses a `size_t` with `I` but that type is not guaranteed to be the size of an int.

**Comment by AdamWill** [comment] 2017-01-10 21:35
Well, I *may* be making a bit of progress with this; I think we're winding up in `_draw_path_collection_generic` in _backend_agg.h with Npaths being 0, for some reason. But I may be way off track. Continuing to look into it.

**Comment by AdamWill** [comment] 2017-01-10 21:52
Ah, so we were converging on the same issue :) Indeed, @QuLogic , that looks to be the problem. If I change all those `size_t`s to `unsigned long`s and use the appropriate format specifier ('k'), the tests pass, and `Npaths` for `_draw_path_collection_generic` is no longer 0 for any of the tests.

**Comment by tacaswell** [comment] 2017-01-11 17:23
This is fixed by #7791

**Closed by tacaswell** 2017-01-11 17:23 UTC
