### ISSUE TITLE
Spacing in math text is broken (AIX specific)

### ISSUE THREAD

**Issue by sungeunbae** [matplotlib/matplotlib#6704] opened 2016-07-08 02:29 UTC
Matplotlib 1.5.1 POWER6 AIX cluster (built from source)

The following code generates a figure with broken axis tick values as values involve numbers with exponents. X-axis should be 10^0 ~ 10^5 and Y-axis should be 10^0~10^10. Basically horizontal spacing appears to be ignored. Has anyone seen this before? 

```
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
x=np.arange(100000)+1.
y=x**2
plt.figure()
plt.loglog(x,y)
plt.savefig('testlog.png')
```

![testlog](https://cloud.githubusercontent.com/assets/466989/16675844/ef306c6a-4518-11e6-9bf1-8718364c83dc.png)

**Comment by tacaswell** [comment] 2016-07-08 02:45
What version of freetype and what font are you using?

Does it work with non-log tick labels or other text?

**Comment by sungeunbae** [comment] 2016-07-08 02:54
Thanks Thomas. I'm using freetype 2.5.0.1 and I used default font.  Last two lines replaced with 

```
plt.plot(x,y)
plt.savefig('test_nonlog.png')
```
![test_nonlog](https://cloud.githubusercontent.com/assets/466989/16676128/78ba0598-451b-11e6-929f-aec93072a8ed.png)

How do I check the font I am using?  Thanks

**Comment by sungeunbae** [comment] 2016-07-08 03:26
I tried something else.
```
plt.title(r'$10^0 and 10^5$')
```
Before saving the figure. The result looks pretty bad. The title appears at the top of the box, all squashed.
![testlog](https://cloud.githubusercontent.com/assets/466989/16676589/ddc8fde6-451f-11e6-834e-74aee1818633.png)

**Comment by sungeunbae** [comment] 2016-07-11 04:29
I tried something else.
```
plt.title(r'$10^0 and 10^5$')
```
Before saving the figure. The result looks pretty bad. The title appears at the top of the box, all squashed.
![testlog](https://cloud.githubusercontent.com/assets/466989/16676589/ddc8fde6-451f-11e6-834e-74aee1818633.png)

**Comment by tacaswell** [comment] 2016-07-11 04:31
It looks like for some reason mathtext mode is confused about how wide glyphs are.

attn @mdboom @zblz

**Comment by zblz** [comment] 2016-07-11 16:24
@sungeunbae: I cannot reproduce it locally. Does it also happen with mathtext string that do not contain superscripts? e.g., something like `plt.title(r'$10 and 20$')`

**Comment by sungeunbae** [comment] 2016-07-11 21:58
@zblz This issue appears to be happening to all mathtext strings regardless of superscripts.
Unfortunately, this is only happening on AIX machine. If you suggest where to look at, to generate more debug info, I'll be happy to oblige.
![testlog](https://cloud.githubusercontent.com/assets/466989/16748163/aa0aba86-4816-11e6-99de-
984348004fef.png)

**Comment by QuLogic** [comment] 2017-02-06 06:02
Is AIX machine big-endian? This looks very much like the spacing is 0 because the wrong bytes are being read. It should be fixed by #7781 in 2.0.0.

@sungeunbae Can you try again with 2.0.0?

**Comment by sungeunbae** [comment] 2017-02-06 20:54
@QuLogic Yes, it's IBM POWER6-powered and is big-endian! Thank you for the good news!

**Comment by QuLogic** [comment] 2017-02-26 01:34
@sungeunbae Did you try with 2.0.0? Can this be closed?

**Comment by QuLogic** [comment] 2017-04-15 07:17
I'm going to close this; please ping if it needs re-opening.

**Closed by QuLogic** 2017-04-15 07:17 UTC
Labels: needs clarification, text
