### ISSUE TITLE
[Bug]: Matplotlib complains about empty values when `plt.savefig()` is called in thread/during concurrent processing

### ISSUE THREAD

**Issue by ericdrosas87** [matplotlib/matplotlib#28012] opened 2024-04-02 22:55 UTC
### Bug summary

(In JupyterLabs) While attempting to process a large amount of figures (1k -> 10k) in four separate concurrently running threads, the `plt.savefig()` fails with an array about an out of range index on `minor = self.minorTicks[0]` in `matplotlib/axis.py:2216`. The same error does _not_ occur when not running in a multithreaded, concurrent way.

### Code for reproduction

```Python
import matplotlib.pyplot as plt

def concurrent_processing():
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
            results_generator = executor.map(make_manifest_with_images, sub_cutouts_arr, butler, [batch_dir, batch_dir, batch_dir, batch_dir], [True,True,True,True])
            for manifest_row in results_generator:
                manifest += manifest_row

def make_manifest_with_images(results_table, butler, batch_dir, concurrent=False):
    for index, row in results_table.iterrows():
        # Get image data, then
        figout = make_figure(deepCoadd, batch_dir + filename)

def make_figure(exp, out_name):
    fig = plt.figure(figsize=(10, 8))
    afw_display = afwdisplay.Display(1)
    afw_display.scale("asinh", "zscale")
    afw_display.mtv(exp)
    plt.gca().axis("on")
    plt.savefig(out_name) # This line fails

    return fig
```

### Actual outcome

Stack trace:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[7], line 5
      3 print(f"Make the manifest file and save both the manifest and the cutout images in this folder: {batch_dir}")
      4 # manifest = utils.make_manifest_with_images(results_table, butler, batch_dir)
----> 5 manifest = utils.create_images_and_manifest(results_table, butler, batch_dir)

File ~/WORK/utils.py:205, in create_images_and_manifest(results_table, butler, batch_dir)
    203 with concurrent.futures.ThreadPoolExecutor() as executor:
    204     results_generator = executor.map(make_manifest_with_images, sub_cutouts_arr, butler, [batch_dir, batch_dir, batch_dir, batch_dir], [True,True,True,True])
--> 205     for manifest_row in results_generator:
    206         manifest += manifest_row
    208 # erosas beginning of debug   

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/concurrent/futures/_base.py:619, in Executor.map.<locals>.result_iterator()
    616 while fs:
    617     # Careful not to keep a reference to the popped future
    618     if timeout is None:
--> 619         yield _result_or_cancel(fs.pop())
    620     else:
    621         yield _result_or_cancel(fs.pop(), end_time - time.monotonic())

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/concurrent/futures/_base.py:317, in _result_or_cancel(***failed resolving arguments***)
    315 try:
    316     try:
--> 317         return fut.result(timeout)
    318     finally:
    319         fut.cancel()

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/concurrent/futures/_base.py:456, in Future.result(self, timeout)
    454     raise CancelledError()
    455 elif self._state == FINISHED:
--> 456     return self.__get_result()
    457 else:
    458     raise TimeoutError()

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/concurrent/futures/_base.py:401, in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/concurrent/futures/thread.py:58, in _WorkItem.run(self)
     55     return
     57 try:
---> 58     result = self.fn(*self.args, **self.kwargs)
     59 except BaseException as exc:
     60     self.future.set_exception(exc)

File ~/WORK/utils.py:245, in make_manifest_with_images(results_table, butler, batch_dir, concurrent)
    241 # after_butler_query = time.time() # debug
    242 # running_time += (after_butler_query - before_butler_query) # debug
    244 filename = "cutout" + str(row["objectId"]) + ".png"
--> 245 figout = make_figure(deepCoadd, batch_dir + filename)
    247 # Create the CSV-file-row-as-dict
    248 csv_row = {
    249     "filename": filename,  # required column, do not change the column name
    250     "objectId": row.objectId,  # required column, do not change the column name
   (...)
    258     "r_inputCount": row.r_inputCount,
    259 }

File ~/WORK/utils.py:60, in make_figure(exp, out_name)
     58 afw_display.mtv(exp)
     59 plt.gca().axis("on")
---> 60 plt.savefig(out_name)
     62 return fig

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/pyplot.py:1119, in savefig(*args, **kwargs)
   1116 fig = gcf()
   1117 # savefig default implementation has no return, so mypy is unhappy
   1118 # presumably this is here because subclasses can return?
-> 1119 res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
   1120 fig.canvas.draw_idle()  # Need this if 'transparent=True', to reset colors.
   1121 return res

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/figure.py:3390, in Figure.savefig(self, fname, transparent, **kwargs)
   3388     for ax in self.axes:
   3389         _recursively_make_axes_transparent(stack, ax)
-> 3390 self.canvas.print_figure(fname, **kwargs)

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/backend_bases.py:2193, in FigureCanvasBase.print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2189 try:
   2190     # _get_renderer may change the figure dpi (as vector formats
   2191     # force the figure dpi to 72), so we need to set it again here.
   2192     with cbook._setattr_cm(self.figure, dpi=dpi):
-> 2193         result = print_method(
   2194             filename,
   2195             facecolor=facecolor,
   2196             edgecolor=edgecolor,
   2197             orientation=orientation,
   2198             bbox_inches_restore=_bbox_inches_restore,
   2199             **kwargs)
   2200 finally:
   2201     if bbox_inches and restore_bbox:

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/backend_bases.py:2043, in FigureCanvasBase._switch_canvas_and_return_print_method.<locals>.<lambda>(*args, **kwargs)
   2039     optional_kws = {  # Passed by print_figure for other renderers.
   2040         "dpi", "facecolor", "edgecolor", "orientation",
   2041         "bbox_inches_restore"}
   2042     skip = optional_kws - {*inspect.signature(meth).parameters}
-> 2043     print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
   2044         *args, **{k: v for k, v in kwargs.items() if k not in skip}))
   2045 else:  # Let third-parties do as they see fit.
   2046     print_method = meth

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py:497, in FigureCanvasAgg.print_png(self, filename_or_obj, metadata, pil_kwargs)
    450 def print_png(self, filename_or_obj, *, metadata=None, pil_kwargs=None):
    451     """
    452     Write the figure to a PNG file.
    453 
   (...)
    495         *metadata*, including the default 'Software' key.
    496     """
--> 497     self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py:445, in FigureCanvasAgg._print_pil(self, filename_or_obj, fmt, pil_kwargs, metadata)
    440 def _print_pil(self, filename_or_obj, fmt, pil_kwargs, metadata=None):
    441     """
    442     Draw the canvas, then save it using `.image.imsave` (to which
    443     *pil_kwargs* and *metadata* are forwarded).
    444     """
--> 445     FigureCanvasAgg.draw(self)
    446     mpl.image.imsave(
    447         filename_or_obj, self.buffer_rgba(), format=fmt, origin="upper",
    448         dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py:388, in FigureCanvasAgg.draw(self)
    385 # Acquire a lock on the shared font cache.
    386 with (self.toolbar._wait_cursor_for_draw_cm() if self.toolbar
    387       else nullcontext()):
--> 388     self.figure.draw(self.renderer)
    389     # A GUI class may be need to update a window using this draw, so
    390     # don't forget to call the superclass.
    391     super().draw()

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/artist.py:95, in _finalize_rasterization.<locals>.draw_wrapper(artist, renderer, *args, **kwargs)
     93 @wraps(draw)
     94 def draw_wrapper(artist, renderer, *args, **kwargs):
---> 95     result = draw(artist, renderer, *args, **kwargs)
     96     if renderer._rasterizing:
     97         renderer.stop_rasterizing()

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/artist.py:72, in allow_rasterization.<locals>.draw_wrapper(artist, renderer)
     69     if artist.get_agg_filter() is not None:
     70         renderer.start_filter()
---> 72     return draw(artist, renderer)
     73 finally:
     74     if artist.get_agg_filter() is not None:

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/figure.py:3154, in Figure.draw(self, renderer)
   3151         # ValueError can occur when resizing a window.
   3153 self.patch.draw(renderer)
-> 3154 mimage._draw_list_compositing_images(
   3155     renderer, self, artists, self.suppressComposite)
   3157 for sfig in self.subfigs:
   3158     sfig.draw(renderer)

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/image.py:132, in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130 if not_composite or not has_images:
    131     for a in artists:
--> 132         a.draw(renderer)
    133 else:
    134     # Composite any adjacent images together
    135     image_group = []

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/artist.py:72, in allow_rasterization.<locals>.draw_wrapper(artist, renderer)
     69     if artist.get_agg_filter() is not None:
     70         renderer.start_filter()
---> 72     return draw(artist, renderer)
     73 finally:
     74     if artist.get_agg_filter() is not None:

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/axes/_base.py:3034, in _AxesBase.draw(self, renderer)
   3031     for spine in self.spines.values():
   3032         artists.remove(spine)
-> 3034 self._update_title_position(renderer)
   3036 if not self.axison:
   3037     for _axis in self._axis_map.values():

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/axes/_base.py:2967, in _AxesBase._update_title_position(self, renderer)
   2965 for ax in axs:
   2966     bb = None
-> 2967     if (ax.xaxis.get_ticks_position() in ['top', 'unknown']
   2968             or ax.xaxis.get_label_position() == 'top'):
   2969         bb = ax.xaxis.get_tightbbox(renderer)
   2970     if bb is None:

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/axis.py:2491, in XAxis.get_ticks_position(self)
   2485 def get_ticks_position(self):
   2486     """
   2487     Return the ticks position ("top", "bottom", "default", or "unknown").
   2488     """
   2489     return {1: "bottom", 2: "top",
   2490             "default": "default", "unknown": "unknown"}[
-> 2491                 self._get_ticks_position()]

File /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/axis.py:2216, in Axis._get_ticks_position(self)
   2202 def _get_ticks_position(self):
   2203     """
   2204     Helper for `XAxis.get_ticks_position` and `YAxis.get_ticks_position`.
   2205 
   (...)
   2214     - "unknown" otherwise.
   2215     """
-> 2216     major = self.majorTicks[0]
   2217     minor = self.minorTicks[0]
   2218     if all(tick.tick1line.get_visible()
   2219            and not tick.tick2line.get_visible()
   2220            and tick.label1.get_visible()
   2221            and not tick.label2.get_visible()
   2222            for tick in [major, minor]):

IndexError: list index out of range
```

### Expected outcome

The figures are written to the notebook filesystem with no issues.

### Additional information

This only happens during concurrent process, it does not occur when there is no multithreading.

### Operating system

JupyterLabs Linux

### Matplotlib Version

3.8.2

### Matplotlib Backend

agg

### Python version

3.11.7

### Jupyter version

7.0.7

### Installation

conda

**Comment by jklymak** [comment] 2024-04-02 23:12
Please make a self contained minimal working example.  Also note that Matplotlib is not thread safe.

**Comment by ericdrosas87** [comment] 2024-04-03 00:38
> Please make a self contained minimal working example.
I don't think I'll be able to get you a _minimal_ functioning code block unfortunately. I can point you to a repo that has the notebook and helper script though if that's helpful?

Although your comment about Matplotlib not being thread safe may be a sufficient enough answer. I was able to initialize some of the `plt` fields at the beginning of the for-loop that creates the image file, but this only bought me slightly more time and eventually it errored out for another reason.

Is making Matplotlib thread-safe on the development roadmap at all?

**Comment by tacaswell** [comment] 2024-04-03 19:50
The problem is that `plt.savefig` works on the "current figure" which is process global state and when you create a new `Figure` it is automatically set as the "current figure" .  The issue you are seeing is because your threads are stepping on each other like:

- thread A: I'm about to save
- thread B: I'm making a new display let me start to clear the figure!
- thread A: give me the current Figure
- thread A: I can't save this, its broken!
- thread B: I'm done clearing and ready to save!

There is nothing we can do at the Matplotlib level to protect you from this.  However, use of the global state in pyplot is completely optional!

```python
from matplotlib.figure import Figure

def concurrent_processing():
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
            results_generator = executor.map(make_manifest_with_images, sub_cutouts_arr, butler, [batch_dir, batch_dir, batch_dir, batch_dir], [True,True,True,True])
            for manifest_row in results_generator:
                manifest += manifest_row

def make_manifest_with_images(results_table, butler, batch_dir, concurrent=False):
    for index, row in results_table.iterrows():
        # Get image data, then
        figout = make_figure(deepCoadd, batch_dir + filename)

def make_figure(exp, out_name):
    fig = Figure(figsize=(10, 8))
    afw_display = afwdisplay.Display(fig)
    afw_display.scale("asinh", "zscale")
    afw_display.mtv(exp)
    fig.gca().axis("on")
    fig.savefig(out_name) # This line fails

    return fig

```

I suspect that even baring this problem, your plots are going to be messed up.

`pyplot` and the implicit state of "current Axes/Figure" is very much not thread safe (and there is no way to make it so as it is inherently process-global mutable state!), any given object can not be accessed from multiple threads (e.g. updating the data on a `Line2D` from one thread while saving it in another is not safe), but if you have multiple `Figure` objects they can safely be used on independent threads.

It looks like this is coming from https://github.com/lsst/afw ?  It does look like 
args / kwargs are threaded through https://github.com/lsst/afw/blob/8cdfe0ae6a59c0ff800b63c9eb6ec3d6b7833702/python/lsst/afw/display/interface.py#L172 and I assume you are also using https://github.com/lsst/display_matplotlib/blob/main/python/lsst/display/matplotlib/matplotlib.py  so there is a good chance the code I wrote above will work?

Looking at 

https://github.com/lsst/display_matplotlib/blob/0265f82a028ed87659288d5918a086523e0c8947/python/lsst/display/matplotlib/matplotlib.py#L131-L145

```python
    def __init__(self, display, verbose=False,
                 interpretMaskBits=True, mtvOrigin=afwImage.PARENT, fastMaskDisplay=False,
                 reopenPlot=False, useSexagesimal=False, dpi=None, *args, **kwargs):
        """
        Initialise a matplotlib display


        @param fastMaskDisplay      If True only show the first bitplane that's
                                    set in each pixel
                                    (e.g. if (SATURATED & DETECTED)
                                    ignore DETECTED)
                                    Not really what we want, but a bit faster
        @param interpretMaskBits    Interpret the mask value under the cursor
        @param mtvOrigin            Display pixel coordinates with LOCAL origin
                                    (bottom left == 0,0 not XY0)
        @param reopenPlot           If true, close the plot before opening it.
                                    (useful with e.g. %ipympl)
        @param useSexagesimal       If True, display coordinates in sexagesimal
                                    E.g. hh:mm:ss.ss (default:False)
                                    May be changed by calling
                                          display.useSexagesimal()
        @param dpi                  Number of dpi (passed to pyplot.figure)


        The `frame` argument to `Display` may be a matplotlib figure; this
        permits code such as
           fig, axes = plt.subplots(1, 2)


           disp = afwDisplay.Display(fig)
           disp.scale('asinh', 'zscale', Q=0.5)


           for axis, exp in zip(axes, exps):
              plt.sca(axis)    # make axis active
              disp.mtv(exp)
        """
        if hasattr(display.frame, "number"):   # the "display" quacks like a matplotlib figure
            figure = display.frame
        else:
            figure = None


        virtualDevice.DisplayImpl.__init__(self, display, verbose)


        if reopenPlot:
            pyplot.close(display.frame)


        if figure is not None:
            self._figure = figure
        else:
            self._figure = pyplot.figure(display.frame, dpi=dpi)
            self._figure.clf()
```

What is going on here is that first it sniffs if the `display.frame` input looks like a `Figure`, (here `display.frame` is what ever you passed into `Display(...)`...I don't fully understand this code yet).  In that case it sets a local variable `figure` which a bit farther down it sets to `self._figure` which is used subsequently.  On the other hand, if you are passing in the number 1 then that eventually falls through to `pyplot.figure` which means "get me the figure numbered 1 or make me a new one if it exists" and then, just to be safe, the figure is cleared.  Thus, all of your threads are trying to draw to the same figure and stepping all over each other.


I'm going to close this because there is nothing we can do on the Matplotlib side (because we are doing exactly what the user asked...it is just not what the user wants) and it appears that there exists an easy user side change to make their code thread safe.


-----

xref https://matplotlib.org/stable/users/explain/quick_start.html#coding-styles
xref https://matplotlib.org/stable/gallery/user_interfaces/web_application_server_sgskip.html

**Closed by tacaswell** 2024-04-03 19:50 UTC
Labels: status: needs clarification

**Comment by ericdrosas87** [comment] 2024-04-04 19:35
Thank you for the detailed explanation, just for clarification should I always be setting `fig.number = 1` or should it be dynamically set, like `fig.number = idx`?

**Comment by tacaswell** [comment] 2024-04-04 20:51
I think you can set it to anything as it only needs to be there to trip the type-sniffing in lsst/display_matplotlib (and you don't pass the flag to close and re-open the figure).

**Comment by ericdrosas87** [comment] 2024-04-05 16:31
Also thank you for patching `display_matplotlib`! I'm also on the LSST/Rubin project, but on a different team than the maintainers of that repo.
