### ISSUE TITLE
AttributeError: module 'matplotlib' has no attribute 'verbose'

### ISSUE THREAD

**Issue by YunnuoFan** [matplotlib/matplotlib#10755] opened 2018-03-12 03:25 UTC
### Bug report

**Bug summary**

AttributeError: module 'matplotlib' has no attribute 'verbose'

**Code for reproduction**

```python
# from matplotlib import cbook, pyplot as plt, style
#
#
```

**Actual outcome**

```
Traceback (most recent call last):
  File "C:/Users/95235/Desktop/history-1.py", line 4, in <module>
    from matplotlib import cbook, pyplot as plt, style
  File "D:\JetBrains\pyEnv\python363\lib\site-packages\matplotlib\pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "D:\JetBrains\pyEnv\python363\lib\site-packages\matplotlib\backends\__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "D:\JetBrains\PyCharm 2017.3\helpers\pycharm_matplotlib_backend\backend_interagg.py", line 17, in <module>
    verbose = matplotlib.verbose
AttributeError: module 'matplotlib' has no attribute 'verbose'
```

**Expected outcome**

"verbose = matplotlib.verbose"(line in in backend_interagg.py) should be "verbose = matplotlib.Verbose"

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: matplotlib-2.2.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://backend_interagg
  * Python version: python 3.6.3
  * Jupyter version (if applicable):
  * Other libraries: 

pip install matplotlib

**Comment by jklymak** [comment] 2018-03-12 04:43
This is a duplicate w/ #10716, and a fix is in.  In PyCharm, you can disable the built-in backend: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000097690-AttributeError-module-matplotlib-has-no-attribute-verbose-?page=1#community_comment_360000089824

Note that JetBrains appear to have a fix (see the next comment linked above)

**Closed** 2018-03-12 04:43 UTC

**Comment by QuLogic** [comment] 2018-03-12 04:44
Duplicate of #10716.
