### ISSUE TITLE
Segmentation fault with PySide2 5.12.1 (works with 5.11.0)

### ISSUE THREAD

**Issue by tfeldmann** [matplotlib/matplotlib#13466] opened 2019-02-19 10:30 UTC
### Bug report

A segmentation fault happening with PySide2 5.12.1 but not with 5.11.0.
This might be an upstream issue. 

**Code for reproduction**

```python
import sys
import faulthandler
faulthandler.enable(file=sys.stdout)

from matplotlib import rcParams
from matplotlib.backends.backend_qt5agg import FigureCanvas as Canvas
from matplotlib.figure import Figure
from PySide2.QtWidgets import QApplication, QVBoxLayout, QWidget

class MatplotlibWidget(QWidget):
    def __init__(self):
        QWidget.__init__(self)
        self.canvas = Canvas(Figure())
        vertLayout = QVBoxLayout()
        vertLayout.addWidget(self.canvas)
        self.setLayout(vertLayout)
        self.axes = self.canvas.figure.add_subplot(111)

if __name__ == "__main__":
    qapp = QApplication(sys.argv)
    app = MatplotlibWidget()
    app.axes.plot(range(12), range(12))
    app.show()
    qapp.exec_()
```

**Actual outcome**

This code works fine for PySide2 5.11.0 but crashes for 5.12.1:

```
Fatal Python error: Segmentation fault

Current thread 0x00000001142cb5c0 (most recent call first):
  File "<frozen importlib._bootstrap_external>", line 525 in _compile_bytecode
  File "<frozen importlib._bootstrap_external>", line 857 in get_code
  File "<frozen importlib._bootstrap_external>", line 724 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/usr/local/lib/python3.7/site-packages/matplotlib/projections/__init__.py", line 3 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/usr/local/lib/python3.7/site-packages/matplotlib/figure.py", line 42 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/usr/local/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 17 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/usr/local/lib/python3.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 11 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "script.py", line 6 in <module>
[1]    98230 segmentation fault  python3 script.py
```

**Matplotlib version**
  * Operating system: macOS X 10.14.3
  * Matplotlib version: 3.0.2
  * Python version:  3.7.2

**Comment by Tbarowski** [comment] 2019-02-25 11:28
Same problem here on Ubuntu 16.04, matplotlib 3.0.2, python 3.5.2

**Comment by tacaswell** [comment] 2019-02-25 14:01
It is the same Matplotlib version with either PySide2 5.11.0 or 5.12.1? 

Does moving the pyside2 import above the matplotlib imports help?

If I am reading this right it is failing on import?   That also suggests to me that there are some c-level conflicts.

**Comment by tfeldmann** [comment] 2019-02-27 08:16
> Does moving the pyside2 import above the matplotlib imports help?

No, same error. Just tried it.

> It is the same Matplotlib version with either PySide2 5.11.0 or 5.12.1?

Yes, same matplotlib v3.0.2

**Comment by astrofrog** [comment] 2019-03-22 22:32
It looks like PySide2 5.12.2 [has been released](https://pypi.org/project/PySide2/5.12.2), so it'd be worth checking if it works with that version?

**Comment by tacaswell** [comment] 2019-03-23 00:51
I'm going to close this as a duplicate of https://github.com/matplotlib/matplotlib/issues/13429

**Closed by tacaswell** 2019-03-23 00:51 UTC
Labels: third-party integration

**Comment by tfeldmann** [comment] 2019-03-25 08:36
Just wanted to let you know that everything works fine with the new PySide version 👍

**Comment by tacaswell** [comment] 2019-03-25 13:44
Is it worth noting in the docs that pyside2 5.12.1 is known-bad?  I suspect that we are not the only project that will get tripped up by this and long-term the problem will solve it's self as that version gets removed from package managers.
