### ISSUE TITLE
[Bug]: Text box doesn't render when plotting.

### ISSUE THREAD

**Issue by ShaiAvr** [matplotlib/matplotlib#26728] opened 2023-09-09 09:32 UTC
### Bug summary

I use an `AnnotationBbox` together with a `TextArea` to render some text to the right of my plot. It worked fine in the past, but when I recently tried it with another project, it didn't work. Matplotlib created the space needed for the text box, but the text and the box don't show up. When I commented out the plotting, it suddenly worked as expected.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.offsetbox import AnnotationBbox, TextArea

fig, ax = plt.subplots(layout="constrained")

f = np.array([2.15, 2.22, 2.3, 2.43, 2.54, 2.7, 2.79, 2.91, 3.04, 3.2, 3.29])
f_err = 0.01
d = np.array(
    [
        0.3393,
        0.3458,
        0.3622666666666667,
        0.38306666666666667,
        0.4004,
        0.429,
        0.43939999999999996,
        0.45239999999999997,
        0.481,
        0.5044,
        0.5174,
    ]
)
d_err = 0.0052

ax.errorbar(f, d, xerr=f_err, yerr=d_err, fmt=".", label="Measurements")

text_area = TextArea("Hello there!!!!!!")
text_box = AnnotationBbox(
    text_area, (1, 1), box_alignment=(0, 1), boxcoords="axes fraction"
)
ax.add_artist(text_box)

ax.legend()
plt.show()
```

### Actual outcome

When I run the code with the plotting enabled, the text doesn't show up, but there is a space for it:

![Figure_1](https://github.com/matplotlib/matplotlib/assets/35605235/af7e246d-5392-4c52-bdea-885f6248b8c4)
Changing the text causes the space next to the plot to adjust, but the text box doesn't render. If I comment out the plotting of the `errorbar`, the text does show up:

![Figure_1](https://github.com/matplotlib/matplotlib/assets/35605235/40645d7e-25c0-4262-8a79-f2622e622382)

### Expected outcome

The text should render regardless of the plotting I do. As I said above, a similar code to this worked for me in the past on the same computer with the same versions of Python and matplotlib.

![Figure_1](https://github.com/matplotlib/matplotlib/assets/35605235/feba29d5-8407-4ce1-9d92-8af5cf6d165a)

### Operating system

Windows

### Matplotlib Version

3.7.2

### Matplotlib Backend

QtAgg

### Python version

3.11.4

### Jupyter version

4.0.3

### Installation

pip

**Comment by rcomer** [comment] 2023-09-09 09:37
I confirm I have reproduced the problem with the `main` development branch.  Replacing the `errorbar` call with `ax.plot([0, 1])` also allows the annotation to show as expected.

**Comment by ksunden** [comment] 2023-09-11 17:48
The problem is that it is attaching to the point `(1,1)` in data space (the default coordinate system for `AnnotationBbox`, so even though the expected text box does not really associate with that point, if that point is outside of the view limits (as it is with those data values) then the text box does not appear.

switching to `plot` only worked because it included that point, not anything special from `plot` vs `errorbar`.  removing the `errorbar` worked because the default limits are 0-1, so the point was included.

If you zoom out interactively on the plot and scroll around, you can observe this behavior.

Either setting `xycoords` to something other than `data` (e.g. `axes`) or setting `annotation_clip=False` (the default is `None`, which is to clip if the point is outside of the bounds and xycoords is "data") will fix this

```python
text_box = AnnotationBbox(
    text_area, (1, 1), box_alignment=(0, 1), boxcoords="axes fraction", xycoords="axes"
)

or

text_box = AnnotationBbox(
    text_area, (1, 1), box_alignment=(0, 1), boxcoords="axes fraction", annotate_clip=False
)
```

This is expected/documented behavior so I will close this.

**Closed by ksunden** 2023-09-11 17:48 UTC
Labels: status: confirmed bug, topic: annotation

**Comment by ksunden** [comment] 2023-09-11 17:58
I would also perhaps suggest using `AnchoredText` or `AnchoredOffsetbox` for this purpose rather than `AnnotatedBbox`, as those explicitly handle the anchoring without the association with another data point. (`AnchoredOffsetbox` is closer to what you have in this example in terms of usage, `AnchoredText` might allow you to skip the `TextArea` all together if a simpler `Text` will do.

- https://matplotlib.org/devdocs/gallery/misc/anchored_artists.html
- https://matplotlib.org/devdocs/users/explain/text/annotations.html#placing-artist-at-anchored-axes-locations
