### ISSUE TITLE
Unexpected behaviour of imshow default interpolation

### ISSUE THREAD

**Issue by Trel725** [matplotlib/matplotlib#19838] opened 2021-03-31 16:02 UTC
### Bug report

**Bug summary**

Artifacts appear when plotting periodic data with discontinuities, i.e. something like x mod 1.0   
The bug appears at when render resolution is relatively small comparing to the real resolution of the data (downsampling problem?).

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

xx, yy = np.meshgrid(np.linspace(-5, 5, 201), np.linspace(-5, 5, 201))
psi = xx % 1.0

plt.figure()
plt.imshow(psi, cmap="twilight")
plt.savefig("small.png", dpi=100)
plt.savefig("large.png", dpi=200)
```

**Outcome**

 

<img src="https://user-images.githubusercontent.com/11896426/113173843-173c6000-924a-11eb-907f-3bb546a0941b.png"  alt="alt text" width="40%"> <img src="https://user-images.githubusercontent.com/11896426/113173851-199eba00-924a-11eb-95b4-97b2b6262ed7.png"  alt="alt text" width="40%"> 

(large.png, small.png)

**Matplotlib version**

The issue is repeatable locally and in CoLab:

  * Operating system: Linux
  * Matplotlib version: 3.3.3, 3.2.2
  * Matplotlib backend (): TkAgg, ipykernel.pylab.backend_inline 
  * Python version: 3.8.5, 3.7

**Comment by jklymak** [comment] 2021-03-31 16:25
Yes, this is a consequence of the interpolation being done in data space rather than colourspace, so your jumps at 0,1 get interpolated as ~0.5, and show up as a purple line.  

There is a bit of a religious war about this among the devs, where some devs think that any interpolation that creates pixels that are not in the colormap is anathema.  While of course that is true for interpolation, or smoothing of an image, others of us do not think that is true for downsampling.    See #18782 and issues linked therein for more discussion.

**Comment by QuLogic** [comment] 2021-03-31 21:39
Closing as a duplicate of one of the issues linked to the above PR. I'm not sure which one, but there's no need to have a bunch of these open.

**Closed by QuLogic** 2021-03-31 21:39 UTC
Labels: status: duplicate, topic: images
