### ISSUE TITLE
matplotlib.pyplot.figure confused by multplie instances of "Figure"

### ISSUE THREAD

**Issue by tjohnson310** [matplotlib/matplotlib#23361] opened 2022-06-28 17:20 UTC
### Bug summary

line 751 in matplotlib.pyplot, in the figure() function, this first block of code checks whether "num" is of type "class". Arg 2 of isinstance() is "Figure". 

Changing "Figure" to "matplotlib.figure.Figure" will resolve any confusion when pyplot.figure() data args contain matplotlib.figure.Figure class instances. 

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(10,8))
```

### Actual outcome

TypeError: isinstance() arg 2 must be a type or tuple of types

### Expected outcome

change "Figure" in the first block of pyplot.figure as follows:

def figure(num=None,  # autoincrement if None, else integer from 1-N
           figsize=None,  # defaults to rc figure.figsize
           dpi=None,  # defaults to rc figure.dpi
           facecolor=None,  # defaults to rc figure.facecolor
           edgecolor=None,  # defaults to rc figure.edgecolor
           frameon=True,
           FigureClass=Figure,
           clear=False,
           **kwargs
           ):  
    if isinstance(num, matplotlib.figure.Figure):      <--------------------------------------------------------------------
        if num.canvas.manager is None:
            raise ValueError("The passed figure is not managed by pyplot")
        _pylab_helpers.Gcf.set_active(num.canvas.manager)
        return num

### Matplotlib Version

3.5.1

### Installation

pip

**Comment by jklymak** [comment] 2022-06-28 17:29
Can you show code that triggers an error for you?  I cannot follow what you think the bug is here I'm afraid.

**Comment by tacaswell** [comment] 2022-06-28 19:16
From the partial traceback, I think that the name `FigureBase` in the `pyplot` namespace has ended up as something other that the base class which makes me think some code is monkey-patching `pyplot` and if you are monkey-patching `pyplot` all bets are off.  We can really only address bugs that you can reproduce with a un-modified installation of Matplotlib.

**Comment by tjohnson310** [comment] 2022-10-11 08:03
It’s literally getting tripped at the plt.figure() command. When I run the command by itself, it works fine. It’s only when I run it with my software, that uses multiple matplotlib.figure.Figure instances that the exception gets tripped. It seems that the isinstance check in pyplot.figure needs to specify which Figure to use as arg2, hence my suggestion into replace it with an explicit matplotlib.figure.Figure.

I wish I could provide an example for you, but unfortunately I’d have to share my entire code base :/

We have seen this occur from multiple different directions, but it looks like no one else is seeing it.

Tim

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tacaswell** [comment] 2022-10-11 15:41
> When I run the command by itself, it works fine. It’s only when I run it with my software

This strongly suggests to me that the bug is in your software and not in Matplotlib.  If I set `plt.Figure` to something other than `Figure` class:

```python
 11:32:56 $ ipython
Python 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib.pyplot as plt

In [2]: fig = plt.figure()

In [3]: plt.Figure = 'please do not do this'

In [4]: plt.figure()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [4], line 1
----> 1 plt.figure()

File /usr/lib/python3.10/site-packages/matplotlib/pyplot.py:772, in figure(num, figsize, dpi, facecolor, edgecolor, frameon, FigureClass, clear, **kwargs)
    686 def figure(num=None,  # autoincrement if None, else integer from 1-N
    687            figsize=None,  # defaults to rc figure.figsize
    688            dpi=None,  # defaults to rc figure.dpi
   (...)
    694            **kwargs
    695            ):
    696     """
    697     Create a new figure, or activate an existing figure.
    698
   (...)
    770     in the matplotlibrc file.
    771     """
--> 772     if isinstance(num, Figure):
    773         if num.canvas.manager is None:
    774             raise ValueError("The passed figure is not managed by pyplot")

TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

In [5]:

```

I can reproduce this error (or at least one that looks like it).

In your code please do not set any attribute on `plt` (or really any module you import!) unless you are sure you need to do it (aka "monkey patching") as it can have surprising side effects like this (and is effectively process global state).


-----

I am going to close this because while I can see an argument for pulling `Figure` from the `mpl.figure` module in in `pyplot.figure`, it is also the case that we should be able to assume we control that namespace and can expect `plt.Figure` to always be the `Figure` class as we imported at the top.  The correct fix here is for client code to not monkey patch `pyplot`.

**Closed by tacaswell** 2022-10-11 15:41 UTC
Labels: status: needs clarification
