### ISSUE TITLE
Math accents are not correctly aligned

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#5999] opened 2016-02-14 06:32 UTC
This is a bit of a nitpick, but if you look at the [latest mathtext example](http://matplotlib.org/devdocs/examples/pylab_examples/mathtext_examples.html), many accents are too far to the left. It's actually a bit off in the 1.5.x docs, but perhaps not as noticeable with the other font.

For example, the acute accent on the 'a' is pretty clearly too far to the left, with the bottom starting at the start of the curve, when it really should start above the middle like the grave accent. The breve, dot, umlaut, tilde and arrow arrow also just slightly to the left (though pretty reasonable.) At this size, the macron seems okay, but at a larger font size, it seems slightly to the left as well.

At a guess, perhaps the location for the accents is tuned for regular text, and so is slightly to the left for math text, which is usually italic?

**Comment by NelleV** [comment] 2016-10-10 22:14
Duplicate of #4561

**Comment by NelleV** [comment] 2016-10-10 22:15
Please reopen if you don't think that is a duplicate. I am just trying to sort out which tickets need to be fixed for 2.0

**Closed by NelleV** 2016-10-10 22:14 UTC
Labels: text
