### ISSUE TITLE
Failure to find matplotlibrc when testing installed distribution

### ISSUE THREAD

**Issue by matthew-brett** [matplotlib/matplotlib#10717] opened 2018-03-08 13:39 UTC
During wheel testing:

```
_______________________ test_if_rctemplate_is_up_to_date _______________________
[gw0] linux -- Python 3.5.3 /venv/bin/python3.5

    def test_if_rctemplate_is_up_to_date():
        # This tests if the matplotlibrc.template file
        # contains all valid rcParams.
        dep1 = mpl._all_deprecated
        dep2 = mpl._deprecated_set
        deprecated = list(dep1.union(dep2))
        #print(deprecated)
        path_to_rc = mpl.matplotlib_fname()
>       with open(path_to_rc, "r") as f:
E       FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.5/site-packages/matplotlib/mpl-data/matplotlibrc'

```

See full log available via https://travis-ci.org/MacPython/matplotlib-wheels/jobs/350816982

Is the matplotlibrc being correctly bundled / registered for install?

**Comment by matthew-brett** [comment] 2018-03-26 14:47
Just a plea - the builds have been failing continuously since I put up this issue.  Leaving the builds to fail means it's harder to detect new failures in wheel builds, making it harder to do the eventual release.  I am happy to turn off the daily builds if it does not seem worth the effort to support them.

**Comment by matthew-brett** [comment] 2018-04-02 12:14
OK - disabling the daily builds for now.

**Comment by QuLogic** [comment] 2018-04-02 21:34
Does #10929 help with this?

**Comment by ImportanceOfBeingErnest** [comment] 2018-04-03 12:01
Yep sorry, I wasn't aware that `mpl.matplotlib_fname()` could actually point to anything other than the shipped matplotlibrc. The file that should be tested is the `matplotlibrc.template` which resides in the root folder of the source, but after building should be `matplotlib\mpl-data\matplotlibrc` (without extension). However it seems that this is not always the case?

**Comment by matthew-brett** [comment] 2018-04-08 13:05
@QuLogic - thanks for the suggestion - but no - current master (which has #10929 merged I believe) still fails with the same error:

https://api.travis-ci.org/v3/job/363745427/log.txt

**Comment by QuLogic** [comment] 2018-04-08 18:51
>        path_to_rc = mpl.matplotlib_fname()

That's not how that line should look with #10929.

**Comment by QuLogic** [comment] 2018-04-10 21:03
Please try again now that `v2.2.x` is merged into `master`.

**Comment by matthew-brett** [comment] 2018-04-11 08:06
Same failure building mpl commit 0a571534c : https://api.travis-ci.org/v3/job/364856291/log.txt

**Comment by QuLogic** [comment] 2018-04-13 04:25
I built a wheel `python3 setup.py bdist_wheel` and unzipped it and `matplotlib/mpl-data/matplotlibrc` was there. So I made a venv and installed it and the file was still there. I'm sorry, but you (or maybe someone on macOS?) will have to investigate this more as I cannot reproduce the problem.

**Comment by matthew-brett** [comment] 2018-04-13 07:52
The OSX installation is standard (and passes all the other tests) (and lots of other projects use it and pass their tests).

Did you try running the tests?

**Comment by jflatow** [comment] 2018-05-11 18:44
Is this the same issue? Copying `matplotlibrc` from the install dir got deleted here: https://github.com/matplotlib/matplotlib/commit/9093eddb812ba1d8a38f1ff0d63f14980f5d87b3#diff-c28358ce9623af21f7b6e068f69085b7L725

**Closed** 2018-05-20 00:30 UTC
