### ISSUE TITLE
Matplotlib figures stop to respond in %matplotlib mode in notebook

### ISSUE THREAD

**Issue by mmagnuski** [matplotlib/matplotlib#6675] opened 2016-07-02 10:03 UTC
The simplest example:

``` python
# In[1]
import numpy as np
from matplotlib import pyplot as plt
x = np.linspace(-10, 10)
y = np.sin(x)

# In[2] (this works)
%matplotlib
plt.plot(x, y)

# In[3] (this does not work if used after the previous command)
plt.plot(x, y)
```

The GUI window that shows up after the `In[3]` is not responding and does not contain any plot (it is full white, not event toolbar is visible).
The only way to close that window without killing the kernel is calling `%matplotlib` again.
So in the end to work interactively with matplotlib from the notebook I have to add `%matplotlib` to every cell that does plotting.
But then plots sometime open and immediatelly close and the console from which I have started notebook prints:

```
QSocketNotifier: Multiple socket notifiers for same socket 348 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 860 and type Read
```
## System info

```
$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.7
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

Some of the packages as shown by `conda list`:

```
anaconda                  4.0.0               np110py35_0
...
conda                     4.0.7                    py35_0
...
ipykernel                 4.3.1                    py35_0
ipython                   4.1.2                    py35_1
...
jupyter                   1.0.0                    py35_2
jupyter-client            4.2.2                     <pip>
jupyter-console           4.1.1                     <pip>
jupyter-core              4.1.0                     <pip>
jupyter_client            4.2.2                    py35_0
jupyter_console           4.1.1                    py35_0
jupyter_core              4.1.0                    py35_0
...
matplotlib                1.5.1               np110py35_0
...
notebook                  4.2.0                    py35_0
...
numpy                     1.10.4                   py35_0
```

**Comment by tacaswell** [comment] 2016-07-03 00:20
Which backend are you using?  If you are using one of the native GUI backends I would expect the second call to `plt.plot` to show up on the same axes as the first.

**Comment by tacaswell** [comment] 2016-07-03 00:20
attn @takluyver

**Comment by mmagnuski** [comment] 2016-07-03 01:54
Sorry, the freeze happens only when I close the first figure.

When I turn on interactive mode I get:
```
Using matplotlib backend:Qt4Agg
```
I've seen this problem on at least 3 different windows machines.

**Comment by takluyver** [comment] 2016-07-03 10:36
If you do `%matplotlib` in one cell and then plot in the next, does it work? Or is it only working if `%matplotlib` is in the same cell as the plot is created?

What about if you explicity specify the backend like `%matplotlib qt4`?

**Comment by takluyver** [comment] 2016-07-03 10:39
Looking at the code in ipykernel, it appears to use the edge-triggered zmq fds, which @minrk has told me it's basically impossible to use reliably. But if that were the cause, I'd expect the failure to be in the other direction: that mpl plot window would be responding, but IPython wouldn't process any further execution messages.

**Comment by mmagnuski** [comment] 2016-07-03 10:50
Actually it seems that running `%matplotlib` in a separate cell (no plotting in the same cell) fixes the problem. 
`%matplotlib qt4` doesn't help by itself, only when it is called in a separate cell.
Also, calling `%matplotlib` in a separate cell does not work once the problem has already appeared. Then - only restarting the kernel and calling `%matplotlib` in a separate cell fixes it.

**Comment by takluyver** [comment] 2016-07-03 11:36
I'd guess that it's something like: if IPython's event loop integration isn't fully set up before you plot, mpl creates a separate Qt event loop and uses that, so the integration isn't properly active.

**Comment by mmagnuski** [comment] 2016-07-04 01:20
Ok, thanks!

**Comment by minrk** [comment] 2016-07-05 06:19
The use of the zmq FD could result in lost events, but if anything becomes unresponsive as a result, it would be executing new cells in the kernel, not the figure itself. Fortunately, the way we send messages makes this failure in this particular case fairly unlikely.

**Comment by mmagnuski** [comment] 2016-07-05 08:39
@minrk Maybe I'm just unlucky but I've seen it on all windows computers I have been working on (about 4 - 5 machines) - and it happens every time I run `%matplotlib` in the same cell as plotting... 
I can test it on more machines, if you like. And if you need any more info to debug this issue - I'd be happy to help.

**Comment by minrk** [comment] 2016-07-05 09:28
@mmagnuski sorry, what I meant to communicate was that your issue is unlikely to be related to the zmq.FD point, which could cause the kernel to hang, but not the figure, as @takluyver described. Whatever's causing your figure windows to hang ought to be something else.

If running the matplotlib magic in a separate cell works, then I think @takluyver is on the right track: eventloop integration isn't set up when the first window is created (IPython's eventloop integration activates between cells), so maybe there are two eventloops that end up being created, and only one is running.

**Comment by mmagnuski** [comment] 2016-07-05 09:42
I wasn't sure which one you meant to be unlikelly, thanks for clarification. :)
If IPython's eventloop integration always activates between cells - maybe a warning would be enough if IPython detects %matplotlib is not the last call in the cell (or something like this)? Or do you think it's fixable?

**Comment by minrk** [comment] 2016-07-05 09:48
I think it's fixable, we just need to dig carefully through the sequence of events of who's getting and creating handles on the Qt eventloop.

**Comment by mmagnuski** [comment] 2016-11-13 04:16
hi @minrk @takluyver, is there any news on this? Unfortunatelly any help I can offer is in testing potential solutions on multiple windows machines.

**Comment by QuLogic** [comment] 2016-11-13 06:33
This may be getting a bit better in later versions, but shouldn't the `%matplotlib` magic be before the matplotlib import to ensure the backend is set correctly?

**Comment by takluyver** [comment] 2016-11-13 19:49
No news as far as I know.

@QuLogic I don't think it has to be first unless you want to specify a backend, e.g. `%matplotlib qt`. I'm not sure of that, though, so feel free to experiment.

**Comment by mmagnuski** [comment] 2017-02-10 17:22
Just wanted to reference a similar issue here: ipython/ipython#5798 and add that:
In my recent experience if I run two consecutive cells, first with `%matplotlib` and second with **any code**: if the second cell is run before first one finishes it hangs. It just stays in the candle state (`[*]`) forever. So it shouldn't matter if the second cell does plotting or not.

**Comment by mmagnuski** [comment] 2018-01-28 16:52
Just wanted to add a note on a related issue: often running `%matplotlib` in a notebook (especially after being in inline mode before) does not correctly switch you to the interactive mode (at least on Windows). It is frequently needed to invoke `%matplotlib` again, and sometimes run it for the third time (I've never had to run it more than three times).

**Comment by mmagnuski** [comment] 2019-01-07 12:44
Hi, I don't experience the freeze nowadays. But I have the issue with figures closing immediately after creating them (seems to happen on all windows machines I've used) - see the post above. After initializing interactive mode when I plot something in the next cell it opens and immediately closes. Calling `%matplotlib` again sometimes resolves the issues, sometimes not. Calling `%matplotlib` yet another time fixes the problem.

**Comment by luckjiff** [comment] 2019-05-29 02:24
The original issue from years ago is still v much present:
QSocketNotifier: Multiple socket notifiers for same socket 348 and type Read
I have the latest install of everything and no matter what permutation I try I get endless QSocketNotifier messages.  I've just learned to live with it.  Only on Windows and only within emacs running jupyter console..

**Comment by neopku** [comment] 2020-09-30 06:27
> The original issue from years ago is still v much present:
> QSocketNotifier: Multiple socket notifiers for same socket 348 and type Read
> I have the latest install of everything and no matter what permutation I try I get endless QSocketNotifier messages. I've just learned to live with it. Only on Windows and only within emacs running jupyter console..

It is also happened in windows console window. I believe the problem is "jupyter console".

``` ipython
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %matplotlib qt5

In [2]: import pandas as pd
QSocketNotifier: Multiple socket notifiers for same socket 680 and type Read

In [3]: t = pd.Series([1,2,3])

In [4]: QSocketNotifier: Multiple socket notifiers for same socket 680 and type Read
In [4]: t.plot()
QSocketNotifier: Multiple socket notifiers for same socket 680 and type Read
Out[4]: <matplotlib.axes._subplots.AxesSubplot at 0x22245470>

In [5]:
```

**Comment by neopku** [comment] 2020-09-30 11:55
I update ipykernel to 5.3.4 and the message disappeared.

**Comment by jklymak** [comment] 2020-09-30 15:11
Closing as likely obsolete...

**Closed by jklymak** 2020-09-30 15:11 UTC
Labels: GUI/Qt, Upstream fix required

**Comment by mmagnuski** [comment] 2020-10-01 08:59
@neopku @jklymak Yes, I can confirm I no longer have this problem.
