### ISSUE TITLE
Matplotlib handle infinite containing formula failure

### ISSUE THREAD

**Issue by david2588e** [matplotlib/matplotlib#16103] opened 2020-01-05 02:24 UTC
### Bug report

**Bug summary**
When plot the formula containing infinite , there seems a bug :

**Code for reproduction**
  import numpy as np
import matplotlib.pyplot as plt
plt.figure(1)
#
x = np.linspace(-20.0, 6, 200)  # 在0到2pi之间，均匀产生200点的数组
# r = 2cosθ
y = (x/(x+1.))-(2./(x**2.-1.))-1 # 半径
plt.grid()
plt.plot(x, y,label='First Curve')#

and another plot with only part of another infinite, 
 import numpy as np
import matplotlib.pyplot as plt
plt.figure(1)
#
x = np.linspace(-20.0, 6, 200)  # 在0到2pi之间，均匀产生200点的数组
# r = 2cosθ
y = (x/(x+1.)) # 半径
plt.grid()

So it looks that matplotlib only handle the second part of infinite and the first infinite part not included, but it should be wrong from math rule.

```python
# Paste your code here
#
#
```
![image](https://user-images.githubusercontent.com/19882172/71774180-28de7b80-2fa5-11ea-9cf2-77628918e54c.png)

![image](https://user-images.githubusercontent.com/19882172/71774193-54616600-2fa5-11ea-9e97-ea4c8ea5339e.png)

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment] 2020-01-05 03:01
This is just the fact you only have 200 values in x.  Try with 200000 or 2e6.   Closing as not a bug and not having anything to do w matplotlib.

**Closed by jklymak** 2020-01-05 03:01 UTC

**Comment by david2588e** [comment] 2020-01-05 03:16
Hallo :

Looks the left infinite still not show up.
X = -1 is infitie

import numpy as np
import matplotlib.pyplot as plt
plt.figure(1)
#
x = np.linspace(-20.0, 6, 2000000)  # 在0到2pi之间，均匀产生200点的数组
# r = 2cosθ
y = (x/(x+1.))-(2./(x**2.-1.))-1 # 半径
plt.grid()
plt.plot(x, y,label='First Curve')#
[cid:image002.png@01D5C3B9.79B55270]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Jody Klymak<mailto:notifications@github.com>
发送时间: 2020年1月5日 11:01
收件人: matplotlib/matplotlib<mailto:matplotlib@noreply.github.com>
抄送: david2588e<mailto:liujinyi@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [matplotlib/matplotlib] Matplotlib handle infinite containing formula failure (#16103)


This is just the fact you only have 200 values in x. Try with 200000 or 2e6. Closing as not a bug and not having anything to do w matplotlib.

―

**Comment by david2588e** [comment] 2020-01-05 03:34
Maybe the second part is squared one, so more significant in chart than the first part,

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Jody Klymak<mailto:notifications@github.com>
发送时间: 2020年1月5日 11:01
收件人: matplotlib/matplotlib<mailto:matplotlib@noreply.github.com>
抄送: david2588e<mailto:liujinyi@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [matplotlib/matplotlib] Matplotlib handle infinite containing formula failure (#16103)


This is just the fact you only have 200 values in x. Try with 200000 or 2e6. Closing as not a bug and not having anything to do w matplotlib.

―

**Comment by jklymak** [comment] 2020-01-05 03:55
Can you reformat these?   Your figures are not showing up.  

I’m still not sure what you think the error here is.  Please look at the underlying data in numpy.  

If your point is that you prefer the negative side not join with the positive then just plot them separately.  Or put an inf at the value closest to -1.

**Comment by david2588e** [comment] 2020-01-05 04:33
[cid:image003.png@01D5C3C4.48AE81A0]
Dear Sir:

I will try to show the chart of this function to show the solution when this function =0, and the root of +/-1 is not accessible through this matplotlib.pyplot

But only x = 1 is infinite we can see, but x= -1 seems not obvious, maybe plot is more sensitive to X**2 part, but x / (x+1) when x = -1 is not easily to show ,
It is the root of this formula but it is not valid solution to this …

So I thought something wrong when combination of different order in the formula, the matplotlib has some issue onto that, the higher order,more significant. Or it can be solved when meet such infinite, different order part can cut into close Y and all infinite can show off regardless of orders…

Thanks



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Jody Klymak<mailto:notifications@github.com>
发送时间: 2020年1月5日 11:55
收件人: matplotlib/matplotlib<mailto:matplotlib@noreply.github.com>
抄送: david2588e<mailto:liujinyi@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [matplotlib/matplotlib] Matplotlib handle infinite containing formula failure (#16103)


Can you reformat these? Your figures are not showing up.

I’m still not sure what you think the error here is. Please look at the underlying data in numpy.

If your point is that you prefer the negative side not join with the positive then just plot them separately. Or put an inf at the value closest to -1.

―

**Comment by david2588e** [comment] 2020-01-06 00:35
Hallo Sir:

As expected, if the squared order changed to normal order, the plot looks fine as the following code:

import numpy as np
import matplotlib.pyplot as plt
plt.figure(1)
#
x = np.linspace(-20.0, 6, 2000000)  #
y = (x/(x+1.))-(2./(x**2.-1.))-1
plt.grid()
plt.plot(x, y,label='First Curve')#

X= +/- 1 infinite,

Thanks

[cid:image003.png@01D5C46C.434D2920]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: liu lei<mailto:liujinyi@hotmail.com>
发送时间: 2020年1月5日 12:33
收件人: matplotlib/matplotlib<mailto:reply@reply.github.com>
主题: 回复: [matplotlib/matplotlib] Matplotlib handle infinite containing formula failure (#16103)

[cid:image003.png@01D5C3C4.48AE81A0]
Dear Sir:

I will try to show the chart of this function to show the solution when this function =0, and the root of +/-1 is not accessible through this matplotlib.pyplot

But only x = 1 is infinite we can see, but x= -1 seems not obvious, maybe plot is more sensitive to X**2 part, but x / (x+1) when x = -1 is not easily to show ,
It is the root of this formula but it is not valid solution to this …

So I thought something wrong when combination of different order in the formula, the matplotlib has some issue onto that, the higher order,more significant. Or it can be solved when meet such infinite, different order part can cut into close Y and all infinite can show off regardless of orders…

Thanks



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Jody Klymak<mailto:notifications@github.com>
发送时间: 2020年1月5日 11:55
收件人: matplotlib/matplotlib<mailto:matplotlib@noreply.github.com>
抄送: david2588e<mailto:liujinyi@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [matplotlib/matplotlib] Matplotlib handle infinite containing formula failure (#16103)


Can you reformat these? Your figures are not showing up.

I’m still not sure what you think the error here is. Please look at the underlying data in numpy.

If your point is that you prefer the negative side not join with the positive then just plot them separately. Or put an inf at the value closest to -1.

―

**Comment by david2588e** [comment] 2020-01-06 00:36
Sorry :

The right code is :
import numpy as np
import matplotlib.pyplot as plt
plt.figure(1)
#
x = np.linspace(-20.0, 6, 2000000)  # 在0到2pi之间，均匀产生200点的数组
# r = 2cosθ
y = (x/(x+1.))-(2./(x-1.))-1 # 半径
plt.grid()
plt.plot(x, y,label='First Curve')#

[cid:image005.png@01D5C46C.69EBC9B0]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: liu lei<mailto:liujinyi@hotmail.com>
发送时间: 2020年1月6日 8:35
收件人: matplotlib/matplotlib<mailto:reply@reply.github.com>
主题: 回复: 回复: [matplotlib/matplotlib] Matplotlib handle infinite containing formula failure (#16103)

Hallo Sir:

As expected, if the squared order changed to normal order, the plot looks fine as the following code:

import numpy as np
import matplotlib.pyplot as plt
plt.figure(1)
#
x = np.linspace(-20.0, 6, 2000000)  #
y = (x/(x+1.))-(2./(x**2.-1.))-1
plt.grid()
plt.plot(x, y,label='First Curve')#

X= +/- 1 infinite,

Thanks

[cid:image003.png@01D5C46C.434D2920]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: liu lei<mailto:liujinyi@hotmail.com>
发送时间: 2020年1月5日 12:33
收件人: matplotlib/matplotlib<mailto:reply@reply.github.com>
主题: 回复: [matplotlib/matplotlib] Matplotlib handle infinite containing formula failure (#16103)

[cid:image003.png@01D5C3C4.48AE81A0]
Dear Sir:

I will try to show the chart of this function to show the solution when this function =0, and the root of +/-1 is not accessible through this matplotlib.pyplot

But only x = 1 is infinite we can see, but x= -1 seems not obvious, maybe plot is more sensitive to X**2 part, but x / (x+1) when x = -1 is not easily to show ,
It is the root of this formula but it is not valid solution to this …

So I thought something wrong when combination of different order in the formula, the matplotlib has some issue onto that, the higher order,more significant. Or it can be solved when meet such infinite, different order part can cut into close Y and all infinite can show off regardless of orders…

Thanks



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Jody Klymak<mailto:notifications@github.com>
发送时间: 2020年1月5日 11:55
收件人: matplotlib/matplotlib<mailto:matplotlib@noreply.github.com>
抄送: david2588e<mailto:liujinyi@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [matplotlib/matplotlib] Matplotlib handle infinite containing formula failure (#16103)


Can you reformat these? Your figures are not showing up.

I’m still not sure what you think the error here is. Please look at the underlying data in numpy.

If your point is that you prefer the negative side not join with the positive then just plot them separately. Or put an inf at the value closest to -1.

―

**Comment by tacaswell** [comment] 2020-01-06 02:09
Matplotlib only gets to see your function sampled at the points in `x`.   Matplotlib does not know that you are plotting an analytical function with a divergence, we only get to see the points that you pass to us, so unless you happen to include the location of the discontinuity in the data set it will be "hidden" from Matplotlib.
