### ISSUE TITLE
Can't Import Matplotlib.pyplot - Anaconda 4.4, Python 3.6 & Windows 10

### ISSUE THREAD

**Issue by drcrook1** [matplotlib/matplotlib#10252] opened 2018-01-15 16:36 UTC
### Bug report

**Bug summary**

Can't import matplotlib.pyplot

**Code for reproduction**

```python
import matplotlib.pyplot as plt
```

**Actual outcome**

```
# If applicable, paste the console output here
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f09a4c6b4388> in <module>()
      1 import numpy as np
----> 2 import matplotlib.pyplot as plt
      3 import scipy.ndimage.imread as imread
      4 
      5 path = 'C:/data/cifar_10/train/15.png'

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py in <module>()
     30 from cycler import cycler
     31 import matplotlib
---> 32 import matplotlib.colorbar
     33 from matplotlib import style
     34 from matplotlib import _pylab_helpers, interactive

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\colorbar.py in <module>()
     34 import matplotlib.collections as collections
     35 import matplotlib.colors as colors
---> 36 import matplotlib.contour as contour
     37 import matplotlib.cm as cm
     38 import matplotlib.gridspec as gridspec

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\contour.py in <module>()
     19 import matplotlib.colors as colors
     20 import matplotlib.collections as mcoll
---> 21 import matplotlib.font_manager as font_manager
     22 import matplotlib.text as text
     23 import matplotlib.cbook as cbook

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\font_manager.py in <module>()
     56 
     57 import matplotlib
---> 58 from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
     59 from matplotlib.compat import subprocess
     60 from matplotlib.fontconfig_pattern import (

ImportError: DLL load failed: The specified procedure could not be found.
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries: 

Everything was installed via anaconda.

**Comment by drcrook1** [comment] 2018-01-15 16:45
I'm 99% sure this is the same problem: https://github.com/ContinuumIO/anaconda-issues/issues/1672

**Comment by jklymak** [comment] 2018-01-15 17:29
Can you supply the relevant version information requested above?  That'd help see where the problem is.  Also, did this ever work for you or is this your first install?  

Following your link above doesn't make this sound like something Matpltolib can help with, but rather an install problem on your machine with clashing DLLs or an issue on conda's end.

**Comment by efiring** [comment] 2018-01-16 00:08
Closing.  This is definitely a local installation problem, as noted in the anaconda issue you reference, and it is not something we can solve.

**Closed by efiring** 2018-01-16 00:08 UTC
Labels: upstream fix required

**Comment by hitesh17** [comment] 2018-06-13 14:37
Windows to make pyplot work.

pip uninstall matplotlib
python -m pip install --upgrade pip
pip install matplotlib

**Comment by jasonsross** [comment] 2018-07-11 16:47
In my case I traced the error down to a duplicate zlib.dll file existing in another program's installation directory. On windows, use the below command to find out if your system is finding multiple dlls (note: these results can depend on where you perform the command from and your PATH, which can be temporarily changed by 3rd party programs. This was my issue. I was launching python from another program that had a zlib.dll file of its own and was inserting itself into my windows PATH before everything so the zlib.dll that existed in my Anaconda installation was not being chosen for importing pyplot (or more specifically, the import of ft2font)).

`where zlib.dll`

My solution was to force my 3rd party program to remove itself from PATH before launching my python script. You solution could be similar or could involve uninstalling other programs that have the duplicate dll or just deleting the dll if you think that's safe. Goodluck

**Comment by Joannalq** [comment] 2018-08-09 02:12
I have the same issue with you. I solved it. I install it under tensorflow
>>activate tensorflow
>>conda install matplotlib

**Comment by PradeepaRajendran** [comment] 2019-01-11 09:30
For Spyder,

open the anaconda prompt and move to the respective dlib python examples directory, and follow the below comments.
For Example:-C:\Users\Admin\Desktop\dlib-19.16\python_examples> 
pip install numpy scipy matplotlib scikit-learn spyder
pip install opencv-contrib-python
pip install dlib


Windows to make pyplot work.

pip uninstall matplotlib
python -m pip install --upgrade pip
pip install matplotlib

**Comment by biswajitdikun** [comment] 2019-06-11 16:03
I was facing the same problem but got a solution.Try this...
got to cmd or anaconda prompt and type the following code.
conda uninstall matplotlib
conda install -c sunpy matplotlib

**Comment by timhoffm** [comment] 2019-06-11 20:02
@biswajitdikun this is using the sunpy channel, which itself states it's just copying from conda-forge https://anaconda.org/sunpy/matplotlib. If that's true it would be more clear to just use the conda-forge channel.
*Disclaimer:* I don't know what the conda-forge packagers on matplotlib do different from the official anaconda ones.

**Comment by manikandan540** [comment] 2020-03-10 15:59
How to resolve the following problem 
                 matplotlib backend error on windows 10.
