### ISSUE TITLE
[Bug]: _raw_ticker() istep

### ISSUE THREAD

**Issue by BertJorissen** [matplotlib/matplotlib#27603] opened 2024-01-05 17:48 UTC
### Bug summary

Before 3.8.0, in matplotlib.ticker.MaxNLocator._raw_ticker(), there was a for-loop going over different possibilities that breaks out of the loop if a suitable condition was found, now it returns an empty list and fails.

### Code for reproduction

```python
# set up
import matplotlib as mpl
import numpy as np
mpl.rcParams['axes.autolimit_mode'] = 'round_numbers'
mnl = mpl.ticker.MaxNLocator()
mnl._nbins = 1
mnl._extended_steps = np.array([0.1,0.2,0.5,1.,2.,5.,10. ,20.])

# function that causes the bug to appear
mnl._raw_ticks(-9.4, 18.9)
```

### Actual outcome

IndexError: index 0 is out of bounds for axis 0 with size 0

### Expected outcome

not failing, it should just break at line 2135

### Additional information

https://github.com/matplotlib/matplotlib/blob/eb02b108ea181930ab37717c75e07ba792e01f1d/lib/matplotlib/ticker.py#L2109C7-L2109C8

Before 3.8.0, in matplotlib.ticker.MaxNLocator._raw_ticker(), there was a for-loop going over different possibilities that breaks out of the loop if a suitable condition was found, now it returns an empty list. Then, it searches for values in this list. As this list is empty, it gives an error.

This worked before 3.8.0. I'm currently preparing a new release of my own package 'pybinding', and I noticed that this error appeared in the newer versions (available on test.pypi.org).
The error originates from calling the function ax.autoscale_view() or calling other functions from Matplotlib that in turn call ax.autoscale_view().
I just discovered this, and I can probably work around this issue, but I though to inform you to know if this is wanted behavior.

### Matplotlib Version

3.8.0

### Installation

None

**Comment by dstansby** [comment] 2024-01-05 18:57
Since `_raw_ticks()` starts with an underscore we consider it private API that we can change in each release without notifying users, and we don't expect users to use it. Is there an example that uses only public documented code that produces the error you're talking about? otherwise I think we can close this.

**Comment by BertJorissen** [comment] 2024-01-06 21:47
Thank for the fast reply.
Upon further inspection, it appears that there was some uasage of other private functions and inheritance from Matplotlib in the background.
However, this bug can still be reached with specific combinations of public functions;
``` 
import matplotlib as mpl
mpl.use("tkagg")
mpl.rcParams['axes.autolimit_mode'] = 'round_numbers'
import matplotlib.pyplot as plt
from matplotlib.collections import CircleCollection
_, ax = plt.subplots()
col = CircleCollection(sizes=[10, 10], offsets=[[0, 0], [1, 0]], offset_transform=ax.transData)
ax.add_collection(col)
ax.set_aspect('equal')
ax.autoscale_view()
```
I'll probably find a workaround for this function, as the error only appears in very specific situations.

**Comment by tacaswell** [comment] 2024-01-08 17:45
With the loop we had an implicit fallback case of none of the steps were "good", but with the vectorized approach we can end up with no "good" steps.  

Hopefully we only need a `if not `np.any(large_steps): ...` that reproduces what ever the old fallback was, but I could also see there being some funny behavior with the "round" steps.

**Comment by ddeibert-nso** [comment] 2024-05-23 20:55
These changes seem to be working in our local implementation that overrides `MaxNLocator._raw_ticks`:

```
    if any(large_steps):
        istep = np.nonzero(large_steps)[0][0]
    else:
        istep = len(steps) - 1
```

With this test:

```
def test_temp_raw_ticks():
    import matplotlib as mpl
    import numpy as np

    # valid values:  data | round_numbers
    mpl.rcParams["axes.autolimit_mode"] = "round_numbers"
    mnl = mpl.ticker.MaxNLocator()
    mnl._nbins = 1
    mnl._extended_steps = np.array([0.1, 0.2, 0.5, 1.0, 2.0, 5.0, 10.0, 20.0])
    actual_raw_ticks = mnl._raw_ticks(-9.4, 18.9)
    expected_raw_ticks = np.array([-10.0, 0.0, 10.0, 20.0])
    assert np.array_equal(actual_raw_ticks, expected_raw_ticks)
```

**Comment by jklymak** [comment] 2024-05-24 00:38
@ddeibert-nso any interest in submitting a PR (if you haven't already?)

**Comment by ddeibert-nso** [comment] 2024-05-24 14:09
I'll submit a PR.  I didn't want to take it on if someone else was already working on it.

**Closed** 2024-06-02 14:47 UTC
Labels: status: confirmed bug
