### ISSUE TITLE
figure created using figure.Figure doesn't save figure

### ISSUE THREAD

**Issue by abbazs** [matplotlib/matplotlib#12447] opened 2018-10-08 18:02 UTC
Figure object created using "from matplotlib import figure" is not able to save figure.

**Code for reproduction**

```
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib import figure

def figure_bug(file):
    fig = figure.Figure(figsize=(2,5), constrained_layout=True)
    gs = gridspec.GridSpec(5, 1, figure=fig)
    axs = [fig.add_subplot(gs[x]) for x in range(1, 5)] 
    fig.text(0.5, 0.5, file, fontsize=25)
    fig.savefig(file)
    plt.close(fig)

if __name__ == '__main__':
    for i in range(0, 110):
        file_name = f'{i}.png'
        figure_bug(file_name)
        print(f'Done {i}')
```

**Actual outcome**
```
AttributeError Traceback (most recent call last)
D:\...\img_test\layou_test.py in <module>()
     14     for i in range(0, 110):
     15         file_name = f'{i}.png'
---> 16         figure_bug(file_name)
     17         print(f'Done {i}')

D:\....\img_test\layou_test.py in gridspec_bug(file)
      8     axs = [fig.add_subplot(gs[x]) for x in range(1, 5)]
      9     fig.text(0.5, 0.5, file, fontsize=25)
---> 10     fig.savefig(file)
     11     plt.close(fig)
     12

C:\....\matplotlib\figure.py in savefig(self, fname, frameon, transparent, **kwargs)
   2095             self.set_frameon(frameon)
   2096
-> 2097         self.canvas.print_figure(fname, **kwargs)
   2098
   2099         if frameon:

AttributeError: 'NoneType' object has no attribute 'print_figure'
```

**Expected outcome**
Saved image

**Matplotlib version**
  * Operating system: Windows
  * Matplotlib version: 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.5
  * Jupyter version (if applicable): NA
  * Other libraries: NA

**Comment by anntzer** [comment] 2018-10-08 18:11
(I think we should perhaps attach a FigureCanvasBase by default to Figures...).

**Comment by WeatherGod** [comment] 2018-10-08 18:15
Eh, that won't be easy. And still won't be very useful in the end.

Can I ask why you are instantiating the Figure object directly? Usually,
the only time one does that is when embedding in a GUI widget and in those
situations, you don't instantiate the baseclass, you instantiate the
GUI-specific Figure class.

**Comment by anntzer** [comment] 2018-10-08 18:19
> Eh, that won't be easy.

Why?  It's literally `self.canvas = FigureCanvasBase()` instead of `self.canvas = None`...

>  And still won't be very useful in the end.

Well, now you get to save these figures...

**Comment by abbazs** [comment] 2018-10-08 18:57
I'm creating several images in loop and the memory keeps increasing and one solution given in [so](https://stackoverflow.com/a/12300012/1437877) was to create figure from `figure.Figure` instead of `plt.figure`

**Comment by jklymak** [comment] 2018-10-09 17:57
What sticks around after `figure.close`?  We should plug that shouldn't we?

**Comment by WeatherGod** [comment] 2018-10-09 18:08
The problem is that the figure stays behind in the pyplot module. This is
actually by design and it is how the pyplot interface works. Now, we should
double-check the behavior when fig.close() is called, as I suspect that
could be tightened up, but the slightly confusing part is that leaving the
scope of a for-loop, for example, would not garbage-collect the figure. So,
you are left with either recycling the figure, or explicitly closing it.

**Comment by anntzer** [comment] 2018-10-09 18:50
There isn't actually a fig.close() method... (that makes sense as "closing" is a pyplot concept, not a figure concept)
There's plt.close(fig) and that does the right thing.

**Comment by jklymak** [comment] 2018-10-09 19:12
Indeed.  But OTOH:

```python
import os
import psutil
import matplotlib.pyplot as plt

while True:
  fig, ax = plt.subplots()
  ax.plot(range(10))
  process = psutil.Process(os.getpid())
  print(process.memory_info().rss)
  plt.close(fig)
  del(fig)
```

shouldn't keep growing memory use ad-infinitum, should it?

**Comment by anntzer** [comment] 2018-10-09 19:40
That's almost certainly https://github.com/matplotlib/matplotlib/issues/9141 (this only appears to leak when using qt, not with other interactive or noninteractive backends).

**Comment by jklymak** [comment] 2018-10-09 19:46
OK, agreed - with Agg memory use grows a tiny bit, but very very slowly.

**Comment by rudrathegreat** [comment] 2018-11-08 09:04
Another way I found which works (requirements below)  - 

```Python

fig, ax = plt.subplots(figsize=(12, 6))  # create matplotlib figure and axes

```

And then, if you can, be able to save this to your folder - 

```Python

plt.savefig('Images/image.png')

```

And possibly even save it using `scipy.io.wavfile.write` - 

```Python

write('Audio/audio.wav', RATE, data)

```

## Requirements

> Python 3.7
>
> Matplotlib 2.2.3
>
> Scipy 1.15.0 (optional)
>
>NumPy 1.10.0 (recommendation)

I hope that helped!

**Comment by anntzer** [comment] 2020-01-14 14:59
Closed by https://github.com/matplotlib/matplotlib/pull/12450 (AFAICT).

**Closed by anntzer** 2020-01-14 14:59 UTC
