### ISSUE TITLE
Jupyter notebook showing partial plots

### ISSUE THREAD

**Issue by SandboChang** [matplotlib/matplotlib#18238] opened 2020-08-13 02:31 UTC
**Bug summary**

When using Jupyter notebook and matplotlib.pyplot with setting %matplotlib notebook,
the plots generated only show the top left corner. One can pan and see the remaining section of the plot.

Using %matplotlib inline does not have the same problem.

**Code for reproduction**

##any plotting code will do, a simple example is attached
import matplotlib.pyplot as plt
%matplotlib notebook

x = np.arange(10)
y = x
plt.plot(x,y)

**Outcome**
I am posting another user's stackoverflow result, as he already attached the outcome:
https://stackoverflow.com/questions/63106366/matplotlib-notebook-magic-in-jupyter-notebook-partial-plot

**Matplotlib version**

  * Operating system: ubuntu 20.04.1
  * Matplotlib version: '3.3.0'
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.8.2
  * Jupyter version (if applicable): 6.1.1
  * Other libraries: 

 pip3, by having --user flag

**Comment by QuLogic** [comment] 2020-08-13 02:47
This is a duplicate of #18132, and will be fixed in 3.3.1.

**Closed by QuLogic** 2020-08-13 02:47 UTC
