### ISSUE TITLE
[Bug]: savefig with bbox_inches does not save image in the figure

### ISSUE THREAD

**Issue by chappet** [matplotlib/matplotlib#25116] opened 2023-01-31 18:01 UTC
### Bug summary

The image added in the text bbox is not saved with savefig if setting a bbox.
savefig without option do save the image

### Code for reproduction

```python
def GrabTextWithImage():
    
    fig = plt.figure()
    plt.subplot(111)

    #Display Text
    txt = plt.gcf().text(0.10, 0.5, "      ................\n      ................\n      ................"
                      ,bbox={'edgecolor':'black','alpha' : 0.2,'facecolor':'white', 'pad':10, 'linewidth' : 2},
                      verticalalignment='center', horizontalalignment='left', color='black', fontsize=12,zorder = 3)
    

    #Add an image
    an_array = numpy.random.random((20,20)) * 255    
    fig.figimage(an_array,70,240, zorder = 1)

    #Grab around text and return image
    ax = plt.gca()
    r = fig.canvas.get_renderer()
    bb = txt.get_window_extent(r)
    
    transf = ax.transData.inverted()    
    bb_datacoords = bb.transformed(transf)  
    bbox = bb_datacoords.transformed(ax.transData).transformed(fig.dpi_scale_trans.inverted())
    
    plt.axis('off')

    fp = tempfile.TemporaryFile()  
    plt.savefig(fp, bbox_inches = bbox) #BUG : image is not displayed
#     plt.savefig(fp) #Image is displayed
    
    im = Image.open(fp)
    return im

if __name__ == "__main__":
    import numpy
    print (mpl.__version__)

    im = GrabTextWithImage()
    plt.show()
    im.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/1446742/215844148-8deaf81c-dea5-489f-96a0-26e16734407f.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/1446742/215844238-3718c2f4-c82b-4525-83fc-e1daf343f75d.png)

### Operating system

Win, Python 3.8, Matplotlib 3.6.2

### Matplotlib Version

3.6.2

### Matplotlib Backend

QtAgg

### Python version

3.8.2

### Installation

pip

**Comment by jklymak** [comment] 2023-01-31 18:05
I would expect this is much the same as https://github.com/matplotlib/matplotlib/issues/23399. So far as I can tell `figimage` doesn't handle dpi changes properly.  I would personally recommend not using figimage, but we probably should fix.

**Comment by jklymak** [comment] 2023-01-31 18:17
@chappet if you want help doing what you want, suggest a discussion over at https://discourse.matplotlib.org.  Your bug report has many other issues with it that make the results confounding.

**Comment by jalajk24** [comment] 2023-01-31 18:52
Can I work on this issue? I am new to this but interested to work on it

**Comment by jklymak** [comment] 2023-01-31 18:53
Anyone can work on any issue, but I don't think we have isolated a problem yet.

**Comment by tacaswell** [comment] 2023-01-31 21:13
The bug is very likely a miss-matched assumption between https://github.com/matplotlib/matplotlib/blob/5ec2bd279729ff534719b8bf238dbbca907b93c5/lib/matplotlib/image.py#L1394-L1409 and what the `bbox_inches` code is doing that is causing the image to be drawn "off screen".

Given the example images, `BBoxImage` (https://matplotlib.org/stable/gallery/images_contours_and_fields/demo_bboximage.html#bboximage-demo) may be a better option for the @chappet anyway....

**Comment by chappet** [comment] 2023-02-02 14:37
> 

Thanks for your advice.
Therefore, I use Image.crop from the PIL library to do the job.

**Comment by jklymak** [comment] 2023-02-09 19:53
I'm closing as a duplicate of https://github.com/matplotlib/matplotlib/issues/23399, but we probably should fix figimage for modern hiDPI...

**Closed by jklymak** 2023-02-09 19:54 UTC
