### ISSUE TITLE
Regression: "TypeError: Period('2000-12-31', 'D') is not a string" when a Series with date index was plotted

### ISSUE THREAD

**Issue by toobaz** [matplotlib/matplotlib#11623] opened 2018-07-10 21:38 UTC
### Bug report

**Bug summary**

If I plot a pandas ``Series`` with dates index and then try to plot a simple line, I get a ``TypeError``.

**Code for reproduction**

```
In [3]: from matplotlib import pyplot as plt

In [4]: import pandas as pd

In [5]: s = pd.Series(range(10), index=pd.date_range(start='2000-12-31', periods=10, freq='D'))

In [6]: s.plot()
Out[6]: <matplotlib.axes._subplots.AxesSubplot at 0x7f1bfdcb1c88>

In [7]: plt.plot(["2001-01-01"], [-5])
Traceback (most recent call last):
  File "/home/nobackup/repo/matplotlib/lib/matplotlib/cbook/__init__.py", line 290, in process
    proxy(*args, **kwargs)
  File "/home/nobackup/repo/matplotlib/lib/matplotlib/cbook/__init__.py", line 137, in __call__
    return mtd(*args, **kwargs)
  File "/home/nobackup/repo/matplotlib/lib/matplotlib/lines.py", line 635, in recache_always
    self.recache(always=True)
  File "/home/nobackup/repo/matplotlib/lib/matplotlib/lines.py", line 639, in recache
    xconv = self.convert_xunits(self._xorig)
  File "/home/nobackup/repo/matplotlib/lib/matplotlib/artist.py", line 186, in convert_xunits
    return ax.xaxis.convert_units(x)
  File "/home/nobackup/repo/matplotlib/lib/matplotlib/axis.py", line 1521, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "/home/nobackup/repo/matplotlib/lib/matplotlib/category.py", line 53, in convert
    unit.update(values)
  File "/home/nobackup/repo/matplotlib/lib/matplotlib/category.py", line 188, in update
    raise TypeError("{val!r} is not a string".format(val=val))
TypeError: Period('2000-12-31', 'D') is not a string
Out[7]: [<matplotlib.lines.Line2D at 0x7f1be11ff898>]
```

**Expected outcome**

No error

**Matplotlib version**
The above is ran on last git, and works instead with matplotlib 2.0.0.

  * Operating system: Debian Linux (but the Debian packaged version, 2.0.0, works)
  * Matplotlib version: last git
  * Matplotlib backend : reproduced both with ``pdf`` and with ``module://ipykernel.pylab.backend_inline``
  * Python version:3.5
  * Jupyter version (if applicable):5.4.0
  * Other libraries: up-to-date git pandas

**Comment by WeatherGod** [comment] 2018-07-10 22:24
looks like a weird collision. The issue is that the
`plt.plot(["2001-01-01"], [-5])` call is treating "2001-01-01" as a
categorical. Meanwhile, the axes object already has data plotted for the
x-axis with some sort of "units" information under the hood. Those units
are now trying to be converted over to the new "units" of the categorical,
which is non-sensical. Now, to be honest, I wouldn't expect this to work,
either, unless PeriodIndex has registers some sort of string converter
(which I don't think it does).

**Comment by tacaswell** [comment] 2018-07-10 22:44
I agree with @WeatherGod and am deeply surprised that this ever worked.

I suspect that if we fixed the unit-locking issue this would be fixed as the second time around we would not try to sort out what units to use, we would just use what ever was already there and I suspect that the pandas code for handling the datetime idicies will take in almost anything date like to hence, passing a list of dates formatted as strings surreptitiously works.

I think the immediately work around is to make a pandas datetime series before calling matplotlib.

**Comment by toobaz** [comment] 2018-07-11 05:56
I forgot to mention: from the user point of view, the workaround is actually very simple: just replace ``plt.plot(["2001-01-01"], [-5])`` with ``plt.plot([pd.Period("2001-01-01")], [-5])``.

I opened this issue only because the thing used to work, but I'm not personally arguing it should.

**Comment by jklymak** [comment] 2019-03-03 04:52
This now works on master, so closing.  Thanks!

**Closed by jklymak** 2019-03-03 04:52 UTC
Labels: pandas integration, units
