### ISSUE TITLE
Matplotlib NavigationToolbar2Tk disappears when reducing window size

### ISSUE THREAD

**Issue by dallas74** [matplotlib/matplotlib#13485] opened 2019-02-22 02:00 UTC
Using the example in the link below, the toolbar will disappear when reducing the height of the window. I have read about this bug in here and it was stated as resolved but I still have that problem.

https://matplotlib.org/gallery/user_interfaces/embedding_in_tk_sgskip.html#sphx-glr-gallery-user-interfaces-embedding-in-tk-sgskip-py

One solution is to use grid and one frame for FigureCanvasTkAgg and one frame for NavigationToolbar2Tk but then the cursor dont change appearance depending on if zoom, pan etc is selected.

Im using Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32 and matplotlib v 3.0.2

Kind regards, Daniel

**Comment by tacaswell** [comment] 2019-02-24 17:50
@dallas74 Can you link to the other related issue?  Have you tried this with either the 3.0.x branch or the master branch?  We close issues as resolved when the fix is merged to a development branch (not when it is released) so it is possible that it is fixed in the source.

**Comment by ImportanceOfBeingErnest** [comment] 2019-02-24 18:21
Here is a video of the issue, running the example code with the current master branch:

![embeddingtknav](https://user-images.githubusercontent.com/23121882/53303252-9fc8c500-3868-11e9-8d68-f3610ef372b7.gif)

However, using TkAgg and pyplot the issue is not present any more. What this means is that whatever fix was applied internally should probably make it into the docs as well.

**Comment by tacaswell** [comment] 2019-02-24 18:25
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/_backend_tk.py is probably the right place to compare against.  

@dallas74 Want to take a crack at this?

**Comment by dallas74** [comment] 2019-02-24 18:48
Hi, feel a bit lost, probably above my competence level, Id love to take a
crack but dont know what to do/compare, can I get some guidance?

Best regards, Daniel

Den sön 24 feb. 2019 kl 19:25 skrev Thomas A Caswell <
notifications@github.com>:

**Comment by tacaswell** [comment] 2019-02-25 02:10
Great!

There is some difference to how the tk widgets are set up in https://matplotlib.org/gallery/user_interfaces/embedding_in_tk_sgskip.html#sphx-glr-gallery-user-interfaces-embedding-in-tk-sgskip-py vs https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/_backend_tk.py .  We need to make the first one look more like the second one as it relates to how we are calling tk.

**Comment by dallas74** [comment] 2019-02-26 10:15
Hi, ok Ill try to have a go :-)

Best regards, Daniel

Den mån 25 feb. 2019 kl 03:11 skrev Thomas A Caswell <
notifications@github.com>:

**Comment by timhoffm** [comment] 2019-09-07 10:25
Good issue for somebody with a bit of Tk background or who can dig a bit into the code:

- Compare the example and how we use Tk internally (see https://github.com/matplotlib/matplotlib/issues/13485#issuecomment-466847547)
- Adapt the example to work similar to what we do internally.

**Comment by jmehne** [comment] 2019-09-14 19:44
See PR, but in summary for future reference:

The widget that got packed last is resized first. Thus, make sure you pack the canvas after the toolbar was initialized (which implicitly calls `pack`).

**Closed** 2019-09-15 12:58 UTC
Labels: Documentation, GUI/tk, Good first issue
