### ISSUE TITLE
RectangleSelector affecting axis('tight')

### ISSUE THREAD

**Issue by Mastiff37** [matplotlib/matplotlib#19067] opened 2020-12-04 22:54 UTC
I've run into an issue where creating a RectangleSelector prevents ax.axis('tight') from working properly.  I've discovered that when the selector is created, it creates new line objects near coordinate (0,0) on the plot.  Though not visible, the axis('tight') respects their presence and will not collapse around the real data.  This matters if the real data is far from the origin.  This seems like a bug? 

I could work around it if I could figure out how to set the initial location of the RS line objects.

**Comment by Mastiff37** [comment] 2020-12-04 23:26
I found out that the _extents_ property of the rectangle selector is settable.  This sets the location of the (invisible) line objects.  By setting this on creation. I can put it near the data.

**Comment by QuLogic** [comment] 2021-05-18 21:04
Closing as duplicate of #18477.

**Closed by QuLogic** 2021-05-18 21:04 UTC
Labels: Community support
