### ISSUE TITLE
1.5.0rc1: Crash with multiline text.

### ISSUE THREAD

**Issue by Tillsten** [matplotlib/matplotlib#5107] opened 2015-09-20 20:45 UTC
Really serious bug:

    import matplotlib.pyplot as plt
    txt = u""" Two Lines
    """
    ax = plt.gca()
    plt.text(0.5, 0.5, txt)
    plt.show()

Crashs Python, again windows 10, 64 bit, 2.7

**Comment by efiring** [comment] 2015-09-20 21:39
I can't reproduce this with python 3.4 on OS X 10.9, qt4agg, or on Linux with python 2.7 or 3.4, tkagg.

**Comment by cgohlke** [comment] 2015-09-20 21:43
Could be related to https://github.com/matplotlib/matplotlib/pull/5084, which was fixed. I can not reproduce this with matplotlib:master on Windows.

**Comment by Tillsten** [comment] 2015-09-21 00:46
@cgohlke Seems very likely. We can close it now, or i will retest it when rc2 is out.

**Comment by tacaswell** [comment] 2015-10-02 21:02
Closing as this it is reported fixed on master.

@Tillsten can you please ping if this in not fixed in rc2

**Closed by tacaswell** 2015-10-02 21:02 UTC
