### ISSUE TITLE
[Bug]: ax.ticklabel_format(useOffset=True) isn't working as expected

### ISSUE THREAD

**Issue by ap-Codkelden** [matplotlib/matplotlib#25439] opened 2023-03-12 12:44 UTC
### Bug summary

As mentioned in the [documentation](https://matplotlib.org/stable/api/ticker_api.html#matplotlib.ticker.ScalarFormatter), 

> The offset notation separates an additive constant, e.g. `+1e6`. The offset notation label is always prefixed with a `+` or `-` sign and is thus distinguishable from the order of magnitude label.

With huge integers, it works as described (see the `offset_notation 1` axis on the attached figure). But for small decimals `ScalarFormatter` produces a scientific notation for tick labels, at least that's how it looks (see `offset_notation 2` axis). In addition, the offset notation for the range `0.00001, 0.00005` looks exactly like scientific notation (see `scientific notation` axis) for the same range, with no `+` or `-` sign prefix.

### Code for reproduction

```python
lim1 = (100000, 100001)
lim2 = (0.00001, 0.00005)

fig, (ax1, ax2, ax3) = plt.subplots(3, 1, gridspec_kw={'hspace': 2})

ax1.set(title='offset_notation 1', xlim=lim1)
ax1.ticklabel_format(useOffset=True)

ax2.set(title='offset_notation 2', xlim=lim2)
ax2.ticklabel_format(useOffset=True)

ax3.set(title='scientific notation', xlim=lim2)
ax3.ticklabel_format(useOffset=False)
```

### Actual outcome

![image](https://user-images.githubusercontent.com/1292133/224542123-8ca7918a-7d91-43c3-87dc-a8c2b0ddf141.png)

### Expected outcome

The desired outcome of the `ax.ticklabel_format(useOffset=True)` behavior is some negative additive constant, not a multiplicative scaling factor.

### Operating system

macOS 12.6.4

### Matplotlib Version

3.6.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.10.10

### Jupyter version

6.4.12

### Installation

pip

**Comment by rcomer** [comment] 2023-03-22 15:17
I'm not sure that this is a bug.  The [documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.ticklabel_format.html#matplotlib.axes.Axes.ticklabel_format) for `useOffset` says

> If True, the offset is calculated **as needed**

(my bold)

The offset is arguably not needed in this case.  Scientific notation is also the default, but you can change the style to "plain" and choose a specific offset:

```python
import matplotlib.pyplot as plt

lim1 = (100000, 100001)
lim2 = (0.00001, 0.00005)

fig, (ax1, ax2, ax3) = plt.subplots(3, 1, gridspec_kw={'hspace': 2})

ax1.set(title='offset_notation 1', xlim=lim1)
ax1.ticklabel_format(useOffset=True)

ax2.set(title='offset_notation 2', xlim=lim2)
ax2.ticklabel_format(useOffset=0.00001, style='plain')
ax2.tick_params(axis='x', labelrotation=20)

ax3.set(title='scientific notation', xlim=lim2)
ax3.ticklabel_format(useOffset=False)

plt.savefig("test.png")


```
![test](https://user-images.githubusercontent.com/10599679/226950154-38d4ea5f-86b8-4913-b35b-d57091a2d969.png)

Having said that, I'm not clear why the offset appears at the top left on my second axes but not on my first.  Using 3.7.1.

**Comment by rcomer** [comment] 2023-03-22 15:32
I'm going to close this as I think this is not a bug. But you are welcome to open a question over at https://discourse.matplotlib.org/ if you need more help.

**Closed by rcomer** 2023-03-22 15:32 UTC
Labels: topic: ticks axis labels
