### ISSUE TITLE
Inconsistent conversion from normalized to 8-bit RGBA tuples

### ISSUE THREAD

**Issue by 1313e** [matplotlib/matplotlib#17410] opened 2020-05-14 09:39 UTC
# Colors
While I was in the process of writing some colormap manipulation scripts, I went into the MPL code on 'colors' to find out how exactly it handles the conversion between the normalized RGBA tuples that MPL uses, and the actual 8-bit RGBA tuples that are used for colors in general.

Looking at the [colors](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colors.py) module, I noticed that the conversion from normalized to 8-bit tuples is inconsistent in several places.

For example, when one requests some colors from a `Colormap` object in their 8-bit forms by using `bytes=True`, the normalized values are multiplied by `255` and then rounded down, as shown in https://github.com/matplotlib/matplotlib/blob/8bddf0a885384b60864be278917ade792d92674e/lib/matplotlib/colors.py#L575-L583 

However, if I were to convert a normalized RGBA-tuple into an RGBA-hex (which should be the same as an 8-bit RGBA-tuple) using the `to_hex` function, then the normalized values are multiplied by `255` and rounded to nearest, as shown in
https://github.com/matplotlib/matplotlib/blob/8bddf0a885384b60864be278917ade792d92674e/lib/matplotlib/colors.py#L333-L343

If I go over the several other modules that deal with this conversion, I see that rounding down is much more common than rounding to nearest, even though I would have expected the latter (picking the closest corresponding color makes much more sense than picking the closest darker color).
The latter would also ensure that doing `8-bit -> normalized -> 8-bit` always gives the same values back, regardless of potential floating point errors.
Is there a reason why there are two different conversions for the same thing, and why the (in my opinion) worse conversion is much more common?

# Colormaps
I also found a similar peculiarity for picking colors from a `Colormap` object, shown in https://github.com/matplotlib/matplotlib/blob/8bddf0a885384b60864be278917ade792d92674e/lib/matplotlib/colors.py#L558-L568
I would have expected here that the nearest color in the colormap is selected when a fraction is given, i.e., `xa` is calculated as
```python
xa = np.rint(xa*(self.N-1))
```
instead of
```python
xa *= self.N
```

**Comment by anntzer** [comment] 2020-05-14 13:05
I think this is basically a duplicate of https://github.com/matplotlib/matplotlib/issues/12071.  Basically probably no one ever paid enohgh attention to this to come up with a consistent approach, but it's probably worth fixing this once and for all.
Perhaps close this and continue the discussion at #12071?

**Comment by QuLogic** [comment] 2020-05-14 21:37
Closing as duplicate of #12071.

**Closed by QuLogic** 2020-05-14 21:37 UTC
Labels: color and colormaps

**Comment by 1313e** [comment] 2020-05-14 23:58
This issue is not a duplicate of #12071 at all.
It just so happened that that thread became a discussion very similar to the issue I am raising here.
Also, that issue hasn't seen activity in over 1½ years now.

**Comment by 1313e** [comment] 2020-05-15 05:58
However, I guess that issue has seen some discussion as well, so it might be easier to continue there (although I do believe that I provided a pretty decent summary of the situation here).
