### ISSUE TITLE
Feature Requestion: filled step plot

### ISSUE THREAD

**Issue by jseabold** [matplotlib/matplotlib#1709] opened 2013-01-26 23:26 UTC
This was asked a long time ago, and I just ran into a similar need. It would be nice to be able to easily make a filled step plot. The solutions I've come up with are suboptimal.

http://www.mail-archive.com/matplotlib-users@lists.sourceforge.net/msg13072.html

**Comment by tacaswell** [comment] 2015-05-15 19:50
Closing as duplicate of https://github.com/matplotlib/matplotlib/issues/643

**Closed by tacaswell** 2015-05-15 19:50 UTC
Labels: wishlist
