### ISSUE TITLE
Change `legend` to accept `alpha` instead of (only) `framealpha`.

### ISSUE THREAD

**Issue by lzkelley** [matplotlib/matplotlib#6363] opened 2016-05-03 21:18 UTC
[It seems this parameter name comes from the internal parameter being set, `e.g. leg.get_frame().set_alpha(0.5)`](https://github.com/matplotlib/matplotlib/pull/1626), but it seems like it would make much more sense from an API perspective if one could simply use the argument `alpha`, i.e.

`plt.legend(alpha=0.5)` instead of `plt.legend(framealpha=0.5)`.

**Comment by efiring** [comment] 2016-05-03 21:34
The problem is that there is much more in a legend than the frame; a plain "alpha" kwarg would imply changing the alpha of all components of the legend.

**Comment by tacaswell** [comment] 2016-05-03 23:03
I am with @efiring on this on.

**Comment by WeatherGod** [comment] 2016-05-04 13:45
Now, that being said, is having a "alpha" keyword to adjust the alpha of
everything in the legend all that bad of an idea?

**Comment by lzkelley** [comment] 2016-05-04 14:07
Yeah, I totally see your points.  At the same time, I feel like the effect of `framealpha` is the most basic type of transparency someone would want (presumably why its the one implemented).  The most basic application of legend transparency wouldn't necessarily want to change the appearance of the symbols, or decrease the readability of the labels... instead just the background opacity.

**Comment by tacaswell** [comment] 2016-05-04 15:51
This is a common sort of trade off in API design, the 'do what I mean' vs 'do what I told you'.  The upside of mapping `alpha` -> `framealpha` is that in some (but not all) cases that is the 'do what I mean'.  However, the down side is that with the rest of the API, passing in `alpha` to a function applies to all of the artists created by that call.

That said, looking at the `set_alpha` method on `Legend` (and the various `Packer` classes we use for layout of the legends) they do not actually work and need to broadcast to their children (a-la https://github.com/matplotlib/matplotlib/pull/3944)

**Comment by efiring** [comment] 2016-05-15 04:16
I'm going to close this.  For the time being, I think we need to stick with the moderately ugly but descriptive `framealpha`.  How the ubiquitous `set_alpha` method should be handled for all sorts of constructs like the legend is another topic--probably big enough to warrant a MEP.  Do we really want every `set_alpha` to cascade down through all levels?  I suspect the answer to this will not be as straightforward as one might expect.

**Closed by efiring** 2016-05-15 04:16 UTC
Labels: API Changes
