### ISSUE TITLE
Issue with plotting zeros in log space

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#4049] opened 2015-01-29 15:15 UTC
The following simple example shows an issues with zero values when calling ``loglog``:

```
import matplotlib.pyplot as plt

nu = [1e2, 1e3, 1e4, 1e5, 1e6, 1e7]
fnu = [1, 1e-30, 1e-45, 0., 0., 0.]

fig = plt.figure()
ax = fig.add_subplot(1,1,1)
ax.loglog(nu, fnu, color='blue')
fig.savefig('mpl.png')
```

The output is:

![mpl](https://cloud.githubusercontent.com/assets/314716/5959827/8d0677cc-a7d1-11e4-8cd3-7227dee4a37a.png)

Of course, zero is undefined in log space, but I don't understand why it defaults to plotting a value of 0.1 instead. Doing:

```
fnu = [1, 1e-30, 1e-45, np.nan, np.nan, np.nan]
```

Does the right thing on the other hand. So maybe the best solution is to replace 0 values by np.nan inside ``loglog``?

I am using matplotlib 1.5.x with Python 3.4.

**Comment by mdboom** [comment] 2015-01-29 15:37
Puzzling -- the values are masked out in the log scalar and have been for years.  Something else is going wrong here.  Investigating.

**Comment by mdboom** [comment] 2015-01-29 15:54
First bad commit is 91725d8665975de9a26d631445ab1448b0391e1a (only affects master).  Looking into a solution now.

**Comment by tacaswell** [comment] 2015-01-29 16:17
I thought I fixed this recently....

**Comment by tacaswell** [comment] 2015-01-29 16:18
https://github.com/matplotlib/matplotlib/pull/4008

**Comment by astrofrog** [comment] 2015-01-29 16:19
Great, thanks! That does indeed seem to be the same issue.

**Comment by tacaswell** [comment] 2015-01-29 16:20
This is a duplicate of https://github.com/matplotlib/matplotlib/issues/3998

**Comment by mdboom** [comment] 2015-01-29 16:54
Sorry I missed that duplicate.  I have a few comments about the solution over at #4008...

**Closed** 2015-01-30 23:18 UTC
Labels: confirmed bug, Duplicate
