### ISSUE TITLE
Error on updating to matplotlib 2.1.0

### ISSUE THREAD

**Issue by bidhya** [matplotlib/matplotlib#9467] opened 2017-10-18 03:05 UTC
### Bug report

**Bug summary**
Matplotlib was working properly. Upon updating to newer version 2.1.0 I cannot use matplotlib anymore. Just not possible to import matplotlib. I noticed the same problem on Ubuntu system.

**Code for reproduction**

```python
import matplotlib
```

**Actual outcome**

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-82be63b7783c> in <module>()
----> 1 import matplotlib

C:\Users\bny\Anaconda2\envs\gis\lib\site-packages\matplotlib\__init__.py in <module>()
    122 # cbook must import matplotlib only within function
    123 # definitions, so it is safe to import from it here.
--> 124 from . import cbook
    125 from matplotlib.cbook import (
    126     _backports, mplDeprecation, dedent, get_label, sanitize_sequence)

ImportError: cannot import name cbook
```

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 32 bit Python 2.7
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: 

Python including matplotlib was installed using Conda.
Updated matplotlib with "conda update --all"

Conda installed from default channel
Conda-forge also exist on the system

**Comment by WeatherGod** [comment] 2017-10-18 15:12
That is strange... It is possible that there are mixed up installs
happening here. Can you try creating a new conda environment and installing
matplotlib that way?

**Comment by Kojoley** [comment] 2017-10-21 00:18
Please, provide a `conda list --show-channel-urls` output.
Does the `python -c "import matplotlib"` produce same error?
Also you could you try to uninstall the matplotlib package?

---
It looks like the epidemy incoming [1](https://stackoverflow.com/questions/44623376/importerror-cannot-import-name-cbook) [2](https://stackoverflow.com/questions/46651581/importerror-cannot-import-name-cbook-when-using-pycharms-profiler) [3](https://trac.macports.org/ticket/55063) [4](http://marohn-public.site44.com/Marohn-20171011-102214--Pelican-and-ipynb.html)

**Comment by Kojoley** [comment] 2017-10-21 00:29
I think I know what happened, we previously had the `cbook.py` so after updating the `cbook.pyc` left and it confuses python.

**Comment by tacaswell** [comment] 2017-10-21 17:05
I can not reproduce this by copying an old cbook.pyc back into the site-packages (on 2.7 on 64bit linux).  

At least some version of conda are good about cleaning up the pyc files.

If there is a clear reproduction path on the package management side this can be reported to pip/conda maintainers as a bug, but the best solution is probably to just create a new env as @WeatherGod suggested.

**Comment by bidhya** [comment] 2017-10-24 20:56
In the new environment created using conda, I was able to update to Matplotlib 2.1.0 seems to work properly. But when I try to update the root environment with Matplotlib 2.1.0, the problem still persist. I also suspect, it could be mixed installs. So in my free time I will try to uninstall and reinstall the Anaconda to see if the problem still persist.

**Comment by bhargavvader** [comment] 2017-10-25 15:14
Have the same problem on OSX and python 2.7.

**Comment by WeatherGod** [comment] 2017-10-25 15:21
and did you install via conda, homebrew, macports? Also, what
troubleshooting have you tried that was discussed here?

**Comment by tacaswell** [comment] 2017-10-25 17:12
@bidhya @bhargavvader Do either if you have the exact history of what you did to get to the bad state (channels, previous version, current version, etc)? 

I spent some time creating new environments, updating them, etc trying to reproduce this and could not :(

I suspect that `conda list --revisions` will be informative here http://blog.rtwilson.com/conda-revisions-letting-you-rollback-to-a-previous-version-of-your-environment/

**Comment by bidhya** [comment] 2017-10-25 18:09
I ended up uninstalling, then then clean install Anaconda. Now upon updating to Matplotlib 2.1.0, it works fine. Clean install on Ubuntu too, and it works fine

@tacaswell I use also a lot of geospatial packages that depend on GDAL. For some reason, there has always been issues with libraries that depend on GDAL (due to dll etc). In the process I will install additional packages using wheel, pip, and conda-forge channels. I am not 100% sure, but it could have one of these packages/channels mix-up create the problem.

Somewhat surprising to me was that the same problem was observed on both Windows and Ubuntu. And now upon clean install of Anaconda, the issue seems resolved.

**Comment by dstansby** [comment] 2017-10-25 18:23
Glad to hear the problem is solved!

**Closed by dstansby** 2017-10-25 18:23 UTC
