### ISSUE TITLE
[Bug]: Empty bars are styled incorrectly in legend

### ISSUE THREAD

**Issue by rongcuid** [matplotlib/matplotlib#27638] opened 2024-01-11 19:42 UTC
### Bug summary

When plotting multiple plots with specified colors, if plot data is empty, color parameter is ignored.

### Code for reproduction

```python
plt.figure()
plt.barh([], [], label="X", color="C0")
plt.barh([], [], label="Y", color="C1")
plt.legend()
plt.show()
```

### Actual outcome

![legend](https://github.com/matplotlib/matplotlib/assets/1312525/eec42660-630a-4412-b1bb-a0a7c40adeed)

### Expected outcome

![legend_expected](https://github.com/matplotlib/matplotlib/assets/1312525/01dfac55-e183-4388-a006-5cac5ccd7b79)

### Matplotlib Version

3.8.2

### Installation

None

**Comment by QuLogic** [comment] 2024-01-12 00:05
In fact, you don't need both `X` and `Y`, any single thing with non-`C0` is not the right colour.

**Comment by QuLogic** [comment] 2024-01-12 00:16
The problem here is that `bar[h]` return a `BarContainer` which doesn't know anything about the inputs. The legend looks at the first patch for styling, and since there are none, it just returns the default style. All the input settings have been thrown away so there's no other way for it to figure it out.

As a workaround, it looks like you can pass a `np.nan` so that at least a `Patch` is created, but it won't be drawn:
```
plt.barh([np.nan], [np.nan], label="X", color="C1")
```
![issue27638](https://github.com/matplotlib/matplotlib/assets/302469/1de668e3-082b-493f-8558-45bec894c73a)

**Comment by rongcuid** [comment] 2024-01-12 03:32
Can bar container record the style then? I suppose it's not hard to add.

**Comment by lcapalleja** [comment] 2024-01-30 18:43
> As a workaround, it looks like you can pass a `np.nan` so that at least a `Patch` is created, but it won't be drawn:

Would it make sense to do something like this (below) to always create a dummy patch if provided with an empty list or array? Or is this too hacky? It seems to solve this bug but I am not sure if it would change expected behavior too much.

_axes.py
![image](https://github.com/matplotlib/matplotlib/assets/15110959/ff4ae3d4-694d-4c68-826c-3bd4b7a48c19)
Would obviously add an analog to the horizontal case too.

**Comment by tacaswell** [comment] 2024-02-01 19:10
Adding it to the container seems like a better option.  If the user adds the `np.nan` they know, but if we start adding invisible artists that may break some users who are not expecting it...

**Comment by oscargus** [comment] 2024-02-01 22:04
Related to https://github.com/matplotlib/matplotlib/issues/21506

**Comment by QuLogic** [comment] 2024-05-17 21:15
I'm going to close as a duplicate of #21506; @oscargus also has a PR at #22182, but it uses the `np.nan` approach, which seems disliked.

**Closed by QuLogic** 2024-05-17 21:15 UTC
Labels: status: confirmed bug, topic: legend
