### ISSUE TITLE
[Bug]:  Hist2d is less sensitive to narrow bins in new version, resulting in different plots

### ISSUE THREAD

**Issue by mmajewsk** [matplotlib/matplotlib#23505] opened 2022-07-28 17:04 UTC
### Bug summary

I was redoing old analysis, which earlier has been showing narrow bands in histogram:

(matplotlib 3.3.4)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/5279578/181595968-e3039a27-5c1c-4fe4-bb1d-b3df23686f78.png)

and when i tried it again, with exactly the same code, the same data the bands are gone:
(matplotlib 3.5.1)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/5279578/181595950-86653bb4-49cf-4042-a51f-ea67a44483d7.png)

### Code for reproduction

```python
axe.hist2d(px, py,range=[[0,2047],[0,30]], bins=[2048,30],cmin=1)
```

### Actual outcome

(matplotlib 3.5.1)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/5279578/181595950-86653bb4-49cf-4042-a51f-ea67a44483d7.png)

### Expected outcome

(matplotlib 3.3.4)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/5279578/181595968-e3039a27-5c1c-4fe4-bb1d-b3df23686f78.png)

### Matplotlib Version

3.5.1

**Comment by jklymak** [comment] 2022-07-28 17:11
Please make a reproducible minimal example.  We can't test this as-is.

**Comment by tacaswell** [comment] 2022-07-28 18:04
If you zoom in do the bands come back?  Can you also check than `np.histogram2d` behaves the same with both numpy versions?

My knee-jerk diagnosis is that either something changed with how we are doing anti-aliasing on pcolormesh or have shifted something in the rendering by a few pixels so that it is hitting the AA code differently.  If I am reading that right, there is something like 2-3x as many bins in the x-direction as there pixels available.

**Comment by mmajewsk** [comment] 2022-07-28 18:46
@jklymak 

minimal code sample:

```python
import matplotlib.pyplot as plt
import numpy as np
size = 2048

px = []
py = []
std=3

cases = 100
for i in range(size):
    for j in range(cases):
        px.append(i)
        m = 10*i/size
        if i%32 == 0:
            py.append(np.random.normal(1.5*m,std*2))
        else:
            py.append(np.random.normal(m,std))

fig, axe = plt.subplots(1,1,figsize=(15,7))
axe.hist2d(px, py,range=[[0,2047],[0,30]], bins=[2048,30],cmin=1)
```
matplotlib 3.3.4

![bugmplold](https://user-images.githubusercontent.com/5279578/181614253-b3523dea-a1e5-468f-b881-1752b5fd64b0.png)

matplotlib 3.5.1

![bugmplnew](https://user-images.githubusercontent.com/5279578/181614329-70fe5e64-76b2-43a9-8b68-1167f97896d8.png)

**Comment by mmajewsk** [comment] 2022-07-28 19:01
> If you zoom in do the bands come back? Can you also check than `np.histogram2d` behaves the same with both numpy versions?

That would actually be hard for me to do right now, but i think this can be excluded because:

> My knee-jerk diagnosis is that either something changed with how we are doing anti-aliasing on pcolormesh or have shifted something in the rendering by a few pixels so that it is hitting the AA code differently. If I am reading that right, there is something like 2-3x as many bins in the x-direction as there pixels available.

It seems it must be the rendereing since when written to pdf both plots are roughly the same.

**Comment by jklymak** [comment] 2022-07-28 19:14
I think we just need a FAQ https://matplotlib.org/stable/users/faq/index.html for these sorts of issues.  Basically if you have too many pixels we (or any rendering engine) have to decide which ones to show.  We don't anti-alias pcolormesh _cells_ like we do imshow.

**Comment by mmajewsk** [comment] 2022-07-28 19:24
@jklymak 
I literally wouldn't have published a few papers If I would see the version from new matplotlib.
I don't know how this can be solved within the code, but i would strongly suggest going back to the previous rendering, since:

1. The new way hurts reproducibility of plots with matplotlib
2. Very crutial things on the plot can be missed in the way that the new plots are made.
3. AFAIK the anti-aliasing is for the plots to look nice, and if i would care for them looking nice i would opt for it, but good representation of the underlying data should take precedence.

It doesn't help matplotlib to be serious plotting library missing information from a plot because of a rendering issue (which wasn't there before).

**Comment by jklymak** [comment] 2022-07-28 19:33
The contention is you had a rendering issue in both versions, just that it was different.

**Comment by jklymak** [comment] 2022-07-28 21:02
For instance in the above, at least on my screen, the 3.5.1 version has _more_ detail than the 3.3.4 version.  Maybe you got them backwards, but regardless, you ideally will have two pixels for each bin, which for your plot means at least 275 dpi (4096 dots /15 inches).  And practically you need more because your axes don't reach both sides of the figure, so round up to 300 dpi.  Anything less and you will get aliasing.    

If you use a pdf viewer it will anti-alias for you and do a better job of dealing with the singletons by averaging visual pixels.  We do a version of that for imshow (https://matplotlib.org/stable/gallery/images_contours_and_fields/image_antialiasing.html) but we do not do that for pcolormesh rasters.

**Comment by tacaswell** [comment] 2022-07-28 22:35
Did we change something about drawing edges by default on pcolormesh?

**Comment by jklymak** [comment] 2022-07-28 23:18
Maybe?  All I remember us working of for pcolormesh was the shading, which shouldn't affect this...

**Comment by greglucas** [comment] 2022-07-28 23:52
Snapping was changed, so maybe something related to that? https://github.com/matplotlib/matplotlib/pull/16090

**Comment by jklymak** [comment] 2022-07-29 00:19
@mmajewsk try setting snap=False to get the old (still aliased) behaviour.

**Comment by jklymak** [comment] 2022-07-29 20:15
I can confirm that `snap=False` gives the 3.3.4 behaviour.  

The fundamental issue still remains that pcolormesh (or `hist2d`) with more bins than pixels is going to be aliased.  I strongly recommend that folks who want to do raster outputs save in a quite high dpi and then reduce visually using an external package.  Theoretically Matplotlib could do that, but currently we do not.  For it to work properly you need the whole image to be composed in high definition and no matter what high definition you use, it will be too low for someone's plot.

**Comment by jklymak** [comment] 2022-10-26 22:30
I'm going to close this, because I don't think there is much we can do about this issue...

**Closed by jklymak** 2022-10-26 22:30 UTC
